[1]
catalognumber = "ANZX-9884"
date = "2012-03-21"
album = "A-CHANNEL THE ANIMATION +smile BONUS DISC Disc 1 [ANZX-9884]"
tracks = [
    [1, "バルーンシアター -Full size-", "", ""],
    [2, "バルーンシアター -TV size-", "", ""],
    [3, "バルーンシアター (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/49001"]

[2]
catalognumber = "ANZX-9885"
date = "2012-03-21"
album = "A-CHANNEL THE ANIMATION +smile BONUS DISC Disc 2 [ANZX-9885]"
tracks = [
    [1, "大切な場所", "", ""],
    [2, "HAPPY NEW DAYS", "", ""],
    [3, "スマイル方程式 -Full size-", "", ""],
    [4, "スマイル方程式 -TV size-", "", ""],
    [5, "大切な場所 (Instrumental)", "", ""],
    [6, "HAPPY NEW DAYS (Instrumental)", "", ""],
    [7, "スマイル方程式 (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/49001"]

[3]
catalognumber = "SVWC-7970"
date = "2013-12-11"
album = "First Touch / 河野マリナ Disc 1 (CD) [SVWC-7970]"
tracks = [
    [1, "その声を覚えてる", "", ""],
    [2, "消えるdaydream", "", ""],
    [3, "Morning Arch", "", ""],
    [4, "たからもの", "", ""],
    [5, "MAGIC OF MUSIC", "", ""],
    [6, "バルーンシアター", "", ""],
    [7, "Do!! Do!! Let me Fun♪", "", ""],
    [8, "Cheer for me!!", "", ""],
    [9, "snowdrop -河野マリナ ver.-", "", ""],
    [10, "Imperfect blue", "", ""],
    [11, "アラタなるセカイ", "", ""],
    [12, "この優しい世界のなか", "", ""],
]
links = ["https://vgmdb.net/album/42081"]

[4]
catalognumber = "SVWC-7971"
date = "2013-12-11"
album = "First Touch / 河野マリナ Disc 2 (DVD) [SVWC-7971]"
tracks = [
    [1, "河野マリナ スペシャルドキュメンタリー「First Touch」", "", ""],
    [2, "Morning Arch (MUSIC CLIP)", "", ""],
    [3, "たからもの (MUSIC CLIP)", "", ""],
    [4, "その声を覚えてる (MUSIC CLIP)", "", ""],
]
links = ["https://vgmdb.net/album/42081"]

[5]
catalognumber = "ANZX-9872"
date = "2011-05-25"
album = "A-CHANNEL THE ANIMATION 1 BONUS DISC Ending theme & Inserted Songs"
tracks = [
    [1, "ハミングガール", "", ""],
    [2, "はるかぜの化学", "", ""],
    [3, "Start", "", ""],
    [4, "ハミングガール (Instrumental)", "", ""],
    [5, "はるかぜの化学 (Instrumental)", "", ""],
    [6, "Start (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/25783"]

[6]
catalognumber = "SVWC-7767"
date = "2011-05-25"
album = "Morning Arch / 河野マリナ"
tracks = [
    [1, "Morning Arch", "", ""],
    [2, "I meet You◎", "", ""],
    [3, "FOCUS! FOCUS!", "", ""],
    [4, "Morning Arch (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/25781"]

[7]
catalognumber = "ANZX-9880"
date = "2011-09-21"
album = "A-CHANNEL THE ANIMATION 5 BONUS DISC Inserted Songs"
tracks = [
    [1, "オカシナ時間", "", ""],
    [2, "Happy Snow", "", ""],
    [3, "オカシナ時間 (Instrumental)", "", ""],
    [4, "Happy Snow (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/48999"]

[8]
catalognumber = "QWCE-00194"
date = "2011-08-03"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 13"
tracks = [
    [1, "コネクト", "", ""],
    [2, "CORE PRIDE", "", ""],
    [3, "魔・カ・セ・テ Tonight", "", ""],
    [4, "ぱんでみっく！！", "", ""],
    [5, "Destin Histoire", "", ""],
    [6, "インモラリスト", "", ""],
    [7, "RPG", "", ""],
    [8, "わが名は小学生", "", ""],
    [9, "Choose My Love!", "", ""],
    [10, "Morning Arch", "", ""],
    [11, "A Whole New World God Only Knows", "", ""],
    [12, "Scarlet Ballet", "", ""],
    [13, "STRAIGHT JET", "", ""],
    [14, "Taste Of Paradise", "", ""],
    [15, "Os-宇宙人", "", ""],
    [16, "SHINY SHINY", "", ""],
    [17, "SCARLET KNIGHT", "", ""],
    [18, "青い栞", "", ""],
    [19, "Magia", "", ""],
]
links = ["https://vgmdb.net/album/29349"]

[9]
catalognumber = "SVWC-70501, SVWC-70502, SVWC-70503, SVWC-70504, SVWC-70505, SVWC-70506"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" [完全生産限定盤] Vocal Disc 1"
tracks = [
    [1, "ふたりのもじぴったん(fine c'est la mix)", "", ""],
    [2, "God knows...", "", ""],
    [3, "Lost my music", "", ""],
    [4, "GO MY WAY!!(M@STER VERSION)", "", ""],
    [5, "もってけ！セーラーふく", "", ""],
    [6, "幸せ願う彼方から", "", ""],
    [7, "セキレイ", "", ""],
    [8, "motto☆派手にね!", "", ""],
    [9, "Super Driver", "", ""],
    [10, "staple stable", "", ""],
    [11, "帰り道", "", ""],
    [12, "ambivalent world", "", ""],
    [13, "恋愛サーキュレーション", "", ""],
    [14, "sugar sweet nightmare", "", ""],
    [15, "りある＿りあるが＿あんりある", "", ""],
    [16, "雨上がりのミライ", "", ""],
]
links = ["https://vgmdb.net/album/93335"]

[10]
catalognumber = "SVWC-70501, SVWC-70502, SVWC-70503, SVWC-70504, SVWC-70505, SVWC-70506"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" [完全生産限定盤] Vocal Disc 2"
tracks = [
    [1, "SOMEONE ELSE", "", ""],
    [2, "ハートのエッジに挑もう Go to Heart Edge", "", ""],
    [3, "モノクローム ～ version de l'apprivoiser", "", ""],
    [4, "ただいま。", "", ""],
    [5, "めてお☆いんぱくと", "", ""],
    [6, "Morning Arch", "", ""],
    [7, "ハミングガール", "", ""],
    [8, "READY!!（M@STER VERSION）", "", ""],
    [9, "二言目", "", ""],
    [10, "marshmallow justice", "", ""],
    [11, "白金ディスコ", "", ""],
    [12, "たからもの", "", ""],
    [13, "お後がよろしくって…よ!", "", ""],
    [14, "アラタなるセカイ", "", ""],
    [15, "happy endings", "", ""],
    [16, "perfect slumbers", "", ""],
    [17, "chocolate insomnia", "", ""],
]
links = ["https://vgmdb.net/album/93335"]

[11]
catalognumber = "SVWC-70501, SVWC-70502, SVWC-70503, SVWC-70504, SVWC-70505, SVWC-70506"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" [完全生産限定盤] Vocal Disc 3"
tracks = [
    [1, "happy bite", "", ""],
    [2, "光のオクターブ", "", ""],
    [3, "七つの海よりキミの海", "", ""],
    [4, "もうそう♡えくすぷれす", "", ""],
    [5, "木枯らしセンティメント", "", ""],
    [6, "タチアガレ!", "", ""],
    [7, "M@STERPIECE", "", ""],
    [8, "夢幻の華", "", ""],
    [9, "最後のラブレター", "", ""],
    [10, "étoile et toi [édition le blanc]", "", ""],
    [11, "terminal terminal", "", ""],
    [12, "dreamy date drive", "", ""],
    [13, "Stand by...MUSIC!!!", "", ""],
    [14, "Bright Burning Shout", "", ""],
    [15, "awakening", "", ""],
    [16, "さようならのパレード", "", ""],
]
links = ["https://vgmdb.net/album/93335"]

[12]
catalognumber = "SVWC-70501, SVWC-70502, SVWC-70503, SVWC-70504, SVWC-70505, SVWC-70506"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" [完全生産限定盤] Original Soundtrack Disc 4"
tracks = [
    [1, "ある雨の日", "", ""],
    [2, "いつもの風景", "", ""],
    [3, "おいおい", "", ""],
    [4, "好調好調", "", ""],
    [5, "悲劇のヒロイン", "", ""],
    [6, "フンフンフン♪だよ、らき☆すた", "", ""],
    [7, "らっきー☆ちゃんねるのテーマ", "", ""],
    [8, "ランランラン♪だよ、らき☆すた", "", ""],
    [9, "次回予告だよ、らき☆すた", "", ""],
    [10, "かなたのテーマ", "", ""],
    [11, "はじまり", "", ""],
    [12, "おほほほ", "", ""],
    [13, "こうりん", "", ""],
    [14, "かみのき", "", ""],
    [15, "こもれび", "", ""],
    [16, "序章", "", ""],
    [17, "街談巷説", "", ""],
    [18, "神域", "", ""],
    [19, "以下、回想", "", ""],
    [20, "戯言", "", ""],
    [21, "白線マーチ", "", ""],
    [22, "活動開始", "", ""],
    [23, "おふざけマーチ", "", ""],
    [24, "着ぐるみカエル隊", "", ""],
    [25, "いつもの風景から始まる物語", "", ""],
    [26, "SOS団再び", "", ""],
    [27, "あの日の記憶を追いかけて", "", ""],
    [28, "はじまり", "", ""],
    [29, "俺の妹が(ry", "", ""],
    [30, "兄貴の日常", "", ""],
    [31, "＼(^o^)／", "", ""],
    [32, "アキハバラマーチ", "", ""],
    [33, "くぁwせdrftgyふじこlp", "", ""],
]
links = ["https://vgmdb.net/album/93335"]

[13]
catalognumber = "SVWC-70501, SVWC-70502, SVWC-70503, SVWC-70504, SVWC-70505, SVWC-70506"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" [完全生産限定盤] Original Soundtrack Disc 5"
tracks = [
    [1, "絢爛", "", ""],
    [2, "楽園", "", ""],
    [3, "運命", "", ""],
    [4, "銀河美少年", "", ""],
    [5, "偽物", "", ""],
    [6, "怪異の王", "", ""],
    [7, "絆", "", ""],
    [8, "恋", "", ""],
    [9, "私の物語", "", ""],
    [10, "真実からは程遠い存在", "", ""],
    [11, "まがいものそのものの女", "", ""],
    [12, "気まぐれ", "", ""],
    [13, "昔語り", "", ""],
    [14, "クチナワ", "", ""],
    [15, "竜頭蛇尾", "", ""],
    [16, "地獄の沙汰も金次第", "", ""],
    [17, "血", "", ""],
    [18, "鉄血篇 エンドロール", "", ""],
    [19, "おっぱい", "", ""],
    [20, "もしも", "", ""],
    [21, "中学生の通学路", "", ""],
    [22, "逃げ出せない", "", ""],
    [23, "背伸び", "", ""],
    [24, "天輪聖王", "", ""],
    [25, "おわらない僕らのMusic", "", ""],
]
links = ["https://vgmdb.net/album/93335"]

[14]
catalognumber = "SVWC-70507"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" Disc 1 [SVWC-70507]"
tracks = [
    [1, "ふたりのもじぴったん(fine c'est la mix)", "", ""],
    [2, "God knows...", "", ""],
    [3, "Lost my music", "", ""],
    [4, "GO MY WAY!!(M@STER VERSION)", "", ""],
    [5, "もってけ！セーラーふく", "", ""],
    [6, "幸せ願う彼方から", "", ""],
    [7, "セキレイ", "", ""],
    [8, "motto☆派手にね!", "", ""],
    [9, "Super Driver", "", ""],
    [10, "staple stable", "", ""],
    [11, "帰り道", "", ""],
    [12, "ambivalent world", "", ""],
    [13, "恋愛サーキュレーション", "", ""],
    [14, "sugar sweet nightmare", "", ""],
    [15, "りある＿りあるが＿あんりある", "", ""],
    [16, "雨上がりのミライ", "", ""],
]
links = ["https://vgmdb.net/album/93336"]

[15]
catalognumber = "SVWC-70508"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" Disc 2 [SVWC-70508]"
tracks = [
    [1, "SOMEONE ELSE", "", ""],
    [2, "ハートのエッジに挑もう Go to Heart Edge", "", ""],
    [3, "モノクローム ～ version de l'apprivoiser", "", ""],
    [4, "ただいま。", "", ""],
    [5, "めてお☆いんぱくと", "", ""],
    [6, "Morning Arch", "", ""],
    [7, "ハミングガール", "", ""],
    [8, "READY!!（M@STER VERSION）", "", ""],
    [9, "二言目", "", ""],
    [10, "marshmallow justice", "", ""],
    [11, "白金ディスコ", "", ""],
    [12, "たからもの", "", ""],
    [13, "お後がよろしくって…よ!", "", ""],
    [14, "アラタなるセカイ", "", ""],
    [15, "happy endings", "", ""],
    [16, "perfect slumbers", "", ""],
    [17, "chocolate insomnia", "", ""],
]
links = ["https://vgmdb.net/album/93336"]

[16]
catalognumber = "SVWC-70509"
date = "2020-03-18"
album = "神前暁 20th Anniversary Selected Works \"DAWN\" Disc 3 [SVWC-70509]"
tracks = [
    [1, "happy bite", "", ""],
    [2, "光のオクターブ", "", ""],
    [3, "七つの海よりキミの海", "", ""],
    [4, "もうそう♡えくすぷれす", "", ""],
    [5, "木枯らしセンティメント", "", ""],
    [6, "タチアガレ!", "", ""],
    [7, "M@STERPIECE", "", ""],
    [8, "夢幻の華", "", ""],
    [9, "最後のラブレター", "", ""],
    [10, "étoile et toi [édition le blanc]", "", ""],
    [11, "terminal terminal", "", ""],
    [12, "dreamy date drive", "", ""],
    [13, "Stand by...MUSIC!!!", "", ""],
    [14, "Bright Burning Shout", "", ""],
    [15, "awakening", "", ""],
    [16, "さようならのパレード", "", ""],
]
links = ["https://vgmdb.net/album/93336"]

[17]
catalognumber = "ANZX-9878"
date = "2011-08-24"
album = "A-CHANNEL THE ANIMATION 4 BONUS DISC Inserted Songs"
tracks = [
    [1, "Summer breeze", "", ""],
    [2, "オチャメロディカルビューティバンバン", "", ""],
    [3, "恋一夜夢一夜", "", ""],
    [4, "ともだち", "", ""],
    [5, "君の手", "", ""],
    [6, "翼はないけど", "", ""],
    [7, "Summer breeze (Instrumental)", "", ""],
    [8, "オチャメロディカルビューティバンバン (Instrumental)", "", ""],
    [9, "恋一夜夢一夜 (Instrumental)", "", ""],
    [10, "ともだち (Instrumental)", "", ""],
    [11, "君の手 (Instrumental)", "", ""],
    [12, "翼はないけど (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/60810"]

[18]
catalognumber = "ANZX-9876"
date = "2011-07-27"
album = "A-CHANNEL THE ANIMATION 3 BONUS DISC Inserted Songs"
tracks = [
    [1, "Mermaid Sisters", "", ""],
    [2, "探検のススメ", "", ""],
    [3, "Mermaid Sisters (Instrumental)", "", ""],
    [4, "探検のススメ (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/26073"]

[19]
catalognumber = "ANZX-9882"
date = "2011-10-26"
album = "A-CHANNEL THE ANIMATION 6 BONUS DISC Inserted Songs"
tracks = [
    [1, "きっと ずっと もっと", "", ""],
    [2, "未確認飛行ガール", "", ""],
    [3, "きっと ずっと もっと (Instrumental)", "", ""],
    [4, "未確認飛行ガール (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/49000"]

[20]
catalognumber = "SVWC-7765"
date = "2011-05-25"
album = "Morning Arch / 河野マリナ Vocal"
tracks = [
    [1, "Morning Arch", "", ""],
    [2, "I meet You◎", "", ""],
    [3, "FOCUS! FOCUS!", "", ""],
    [4, "Morning Arch (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/25782"]

[21]
catalognumber = "SVWC-7766"
date = "2011-05-25"
album = "Morning Arch / 河野マリナ Video"
tracks = [
    [1, "Morning Arch (Video Clip)", "", ""],
]
links = ["https://vgmdb.net/album/25782"]

[22]
catalognumber = "ANZX-9874"
date = "2011-06-20"
album = "A-CHANNEL THE ANIMATION 2 BONUS DISC Inserted Songs"
tracks = [
    [1, "Gyutto Shite Hoshiinda", "", ""],
    [2, "summer dream syndrome", "", ""],
    [3, "Gyutto Shite Hoshiinda (instrumental)", "", ""],
    [4, "summer dream syndrome (instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/26072"]

[23]
catalognumber = "SVWC-7770"
date = "2011-06-22"
album = "Aチャンネル おりじなるさうんどとらっく"
tracks = [
    [1, "Morning Arch TV ver.", "", ""],
    [2, "awake", "", ""],
    [3, "alongside", "", ""],
    [4, "academic", "", ""],
    [5, "apple", "", ""],
    [6, "artistic", "", ""],
    [7, "awful", "", ""],
    [8, "anxious", "", ""],
    [9, "april fool", "", ""],
    [10, "aggressive", "", ""],
    [11, "amazing", "", ""],
    [12, "air", "", ""],
    [13, "approach", "", ""],
    [14, "attack", "", ""],
    [15, "ace", "", ""],
    [16, "alone", "", ""],
    [17, "accept", "", ""],
    [18, "avenue", "", ""],
    [19, "agony", "", ""],
    [20, "about", "", ""],
    [21, "accident", "", ""],
    [22, "advise", "", ""],
    [23, "à la mode", "", ""],
    [24, "around", "", ""],
    [25, "absurd", "", ""],
    [26, "anywhere", "", ""],
    [27, "angel", "", ""],
    [28, "audience", "", ""],
    [29, "addict", "", ""],
    [30, "above", "", ""],
    [31, "actress", "", ""],
    [32, "again", "", ""],
    [33, "almost", "", ""],
    [34, "ashamed", "", ""],
    [35, "active", "", ""],
    [36, "absent", "", ""],
    [37, "alarm", "", ""],
    [38, "abnormal", "", ""],
    [39, "august", "", ""],
    [40, "autumn", "", ""],
    [41, "afternoon", "", ""],
    [42, "ハミングガール TV ver.", "", ""],
]
links = ["https://vgmdb.net/album/25780"]

[24]
catalognumber = "ANZX-12084"
date = "2017-09-27"
album = "A-CHANNEL THE ANIMATION Blu-ray Disc BOX -MUSIC CHANNEL- Disc 1 [ANZX-12084]"
tracks = [
    [1, "Morning Arch", "", ""],
    [2, "ハミングガール", "", ""],
    [3, "バルーンシアター", "", ""],
    [4, "スマイル方程式", "", ""],
    [5, "大切な場所", "", ""],
    [6, "HAPPY NEW DAYS", "", ""],
    [7, "Viba鍋!よっつ星", "", ""],
]
links = ["https://vgmdb.net/album/71758"]

[25]
catalognumber = "ANZX-12085"
date = "2017-09-27"
album = "A-CHANNEL THE ANIMATION Blu-ray Disc BOX -MUSIC CHANNEL- Disc 2 [ANZX-12085]"
tracks = [
    [1, "はるかぜの化学", "", ""],
    [2, "Start", "", ""],
    [3, "ぎゅっとして欲しいんだ", "", ""],
    [4, "summer dream syndrome", "", ""],
    [5, "Mermaid Sisters", "", ""],
    [6, "探検のススメ", "", ""],
    [7, "Summer breeze", "", ""],
    [8, "オチャメロディカルビューティバンバン", "", ""],
    [9, "恋一夜夢一夜", "", ""],
    [10, "ともだち", "", ""],
    [11, "君の手", "", ""],
    [12, "翼はないけど", "", ""],
    [13, "オカシナ時間", "", ""],
    [14, "Happy Snow", "", ""],
    [15, "きっと ずっと もっと", "", ""],
    [16, "未確認飛行ガール", "", ""],
]
links = ["https://vgmdb.net/album/71758"]

[26]
catalognumber = "ANZX-12086"
date = "2017-09-27"
album = "A-CHANNEL THE ANIMATION Blu-ray Disc BOX -MUSIC CHANNEL- Disc 3 [ANZX-12086]"
tracks = [
    [1, "awake", "", ""],
    [2, "alongside", "", ""],
    [3, "academic", "", ""],
    [4, "apple", "", ""],
    [5, "artistic", "", ""],
    [6, "awful", "", ""],
    [7, "anxious", "", ""],
    [8, "april fool", "", ""],
    [9, "aggressive", "", ""],
    [10, "amazing", "", ""],
    [11, "air", "", ""],
    [12, "approach", "", ""],
    [13, "attack", "", ""],
    [14, "ace", "", ""],
    [15, "alone", "", ""],
    [16, "accept", "", ""],
    [17, "avenue", "", ""],
    [18, "agony", "", ""],
    [19, "about", "", ""],
    [20, "accident", "", ""],
    [21, "advise", "", ""],
    [22, "a la mode", "", ""],
    [23, "around", "", ""],
    [24, "absurd", "", ""],
    [25, "anywhere", "", ""],
    [26, "angel", "", ""],
    [27, "audience", "", ""],
    [28, "addict", "", ""],
    [29, "above", "", ""],
    [30, "actress", "", ""],
    [31, "again", "", ""],
    [32, "almost", "", ""],
    [33, "ashamed", "", ""],
    [34, "active", "", ""],
    [35, "absent", "", ""],
    [36, "alarm", "", ""],
    [37, "abnormal", "", ""],
    [38, "august", "", ""],
    [39, "autumn", "", ""],
    [40, "afternoon", "", ""],
]
links = ["https://vgmdb.net/album/71758"]

[27]
catalognumber = "SVWC-7972"
date = "2013-12-11"
album = "First Touch / 河野マリナ"
tracks = [
    [1, "その声を覚えてる", "", ""],
    [2, "消えるdaydream", "", ""],
    [3, "Morning Arch", "", ""],
    [4, "たからもの", "", ""],
    [5, "MAGIC OF MUSIC", "", ""],
    [6, "バルーンシアター", "", ""],
    [7, "Do!! Do!! Let me Fun♪", "", ""],
    [8, "Cheer for me!!", "", ""],
    [9, "snowdrop -河野マリナ ver.-", "", ""],
    [10, "Imperfect blue", "", ""],
    [11, "アラタなるセカイ", "", ""],
    [12, "この優しい世界のなか", "", ""],
]
links = ["https://vgmdb.net/album/42082"]
