[1]
catalognumber = "SVWC-7291"
date = "2005-10-26"
album = "かみちゅ!◎オリジナル・サウンドトラック"
tracks = [
    [1, "恋の自習時間", "", ""],
    [2, "君につづく坂道", "", ""],
    [3, "ちゅう学生がゆく!", "", ""],
    [4, "バチあたるぞ!", "", ""],
    [5, "恋は、ふしぎ", "", ""],
    [6, "自転車で帰ろう", "", ""],
    [7, "時はゆっくり流れてる", "", ""],
    [8, "なんでもありません", "", ""],
    [9, "もののけだよ全員集合!", "", ""],
    [10, "すこし、ふしぎ", "", ""],
    [11, "アイラブユーは川を越えて", "", ""],
    [12, "神々Cガール", "", ""],
    [13, "センチメンタル・カントリー・ロマンス", "", ""],
    [14, "いつだってお昼寝ちゅう", "", ""],
    [15, "あたふた あたふた", "", ""],
    [16, "天国時間", "", ""],
    [17, "恋の片道フェリー", "", ""],
    [18, "夢色坂道", "", ""],
    [19, "あの夏の坂道", "", ""],
    [20, "ウキウキ寄り道オーマイガッ!", "", ""],
    [21, "ちゅう学生がもっとゆく!", "", ""],
    [22, "海はグー! 瀬戸内サーフィン天国", "", ""],
    [23, "晴れのちハレ! (TVバージョン)", "", ""],
    [24, "アイスキャンディー (TVバージョン)", "", ""],
]
links = ["https://vgmdb.net/album/17770"]

[2]
catalognumber = "5352-2"
date = "2006-10-10"
album = "KamiChu! Original Soundtrack"
tracks = [
    [1, "Study Period in Love", "", ""],
    [2, "The Hill That Leads to You", "", ""],
    [3, "Junior High school Students March On!", "", ""],
    [4, "It's Bad Karma!", "", ""],
    [5, "Love is Mysterious", "", ""],
    [6, "Let's Go Home by Bike", "", ""],
    [7, "Time Flows Slowly", "", ""],
    [8, "It's Nothing", "", ""],
    [9, "Come Together, Ghosts and Goblins!", "", ""],
    [10, "A Little Mysterious", "", ""],
    [11, "Saying 'I Love You' Across the River", "", ""],
    [12, "Divine Girls", "", ""],
    [13, "Sentimental Country Romance", "", ""],
    [14, "Nap Time Anytime", "", ""],
    [15, "Rush, Rush, Rush", "", ""],
    [16, "Paradise Time", "", ""],
    [17, "The One-way Ferry of Love", "", ""],
    [18, "Dream Colored Hill", "", ""],
    [19, "The Hill from That Summer", "", ""],
    [20, "An Exciting Detour Oh My God!", "", ""],
    [21, "Junior High school Students March Further On!", "", ""],
    [22, "The Beach is Good! Setouchi Surfin' Paradise", "", ""],
    [23, "Clear, Later Clear! (TV version)", "", ""],
    [24, "Ice Candy (TV Version)", "", ""],
]
links = ["https://vgmdb.net/album/25854"]
