[1]
catalognumber = "LACM-14667"
date = "2017-10-25"
album = "ココロニツボミ / eufonius"
tracks = [
    [1, "ココロニツボミ", "", ""],
    [2, "はじめて", "", ""],
    [3, "ココロニツボミ (Instrumental)", "", ""],
    [4, "はじめて (Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/70620"]

[2]
catalognumber = "LACA-9565"
date = "2018-01-10"
album = "TVアニメ『このはな綺譚』おりじなるさうんどとらっく Disc 1 [LACA-9565]"
tracks = [
    [1, "「このはな綺譚」～メインテーマ～", "", ""],
    [2, "此花亭", "", ""],
    [3, "～櫻～", "", ""],
    [4, "～蓮～", "", ""],
    [5, "迷子", "", ""],
    [6, "花めく", "", ""],
    [7, "焦燥", "", ""],
    [8, "蓮呆", "", ""],
    [9, "葛藤", "", ""],
    [10, "新異", "", ""],
    [11, "不可思議", "", ""],
    [12, "街場", "", ""],
    [13, "らうたし", "", ""],
    [14, "珍妙", "", ""],
    [15, "喪失", "", ""],
    [16, "湯治", "", ""],
    [17, "水面", "", ""],
    [18, "暮夜", "", ""],
    [19, "花時姉妹", "", ""],
    [20, "春の旅路", "", ""],
    [21, "心ニ蕾", "", ""],
    [22, "「このはな綺譚」サブタイトル", "", ""],
    [23, "「このはな綺譚」アイキャッチ", "", ""],
    [24, "「このはな綺譚」次回予告", "", ""],
]
links = ["https://vgmdb.net/album/72191"]

[3]
catalognumber = "LACA-9566"
date = "2018-01-10"
album = "TVアニメ『このはな綺譚』おりじなるさうんどとらっく Disc 2 [LACA-9566]"
tracks = [
    [1, "～皐～", "", ""],
    [2, "韶光", "", ""],
    [3, "瀟洒", "", ""],
    [4, "奉公", "", ""],
    [5, "柚困", "", ""],
    [6, "～柚～", "", ""],
    [7, "～棗～", "", ""],
    [8, "逍遥", "", ""],
    [9, "沈心", "", ""],
    [10, "廃憶", "", ""],
    [11, "離離", "", ""],
    [12, "寂寥", "", ""],
    [13, "自省", "", ""],
    [14, "此花亭怪談", "", ""],
    [15, "安閑", "", ""],
    [16, "滑稽", "", ""],
    [17, "木瓜", "", ""],
    [18, "影向", "", ""],
    [19, "宿願", "", ""],
    [20, "昇華", "", ""],
    [21, "姿の花", "", ""],
    [22, "玉響", "", ""],
    [23, "夏祭", "", ""],
    [24, "夏花想々", "", ""],
    [25, "A:椴木", "", ""],
    [26, "B:聖夜", "", ""],
    [27, "四時・草の縁", "", ""],
]
links = ["https://vgmdb.net/album/72191"]

[4]
catalognumber = "TBZR-0981"
date = "2018-02-28"
album = "ラジオCD「らじお 此花亭へようこそ」 Disc 1"
tracks = []
links = ["https://vgmdb.net/album/84141"]

[5]
catalognumber = "TBZR-0982"
date = "2018-02-28"
album = "ラジオCD「らじお 此花亭へようこそ」 Disc 2"
tracks = []
links = ["https://vgmdb.net/album/84141"]

[6]
catalognumber = "LACM-14697"
date = "2017-12-13"
album = "此花亭の四季 / 此花亭仲居の会"
tracks = [
    [1, "春ウララ、君ト咲キ誇ル", "", ""],
    [2, "夏咲き恋花火", "", ""],
    [3, "茜空、君舞フ紅葉ノ散歩道", "", ""],
    [4, "雪華煌めく家路にて", "", ""],
]
links = ["https://vgmdb.net/album/71406"]
