[4]
catalognumber = "VTCL-60016"
date = "2007-12-27"
album = "テレビ東京系アニメーション「スケッチブック～full color's～」ドラマCD スケッチブックストーリーズ～前夜祭～"
tracks = [
    [1, "文化祭への道", "", ""],
    [2, "究極のヤキソバ", "", ""],
    [3, "一杯の天ぷらそば", "", ""],
    [4, "やるきな美術部", "", ""],
    [5, "流れ星きらきら", "", ""],
    [6, "たんぽぽ水車", "", ""],
]
links = ["https://vgmdb.net/album/67093"]

[5]
catalognumber = "VTCL-60005"
date = "2007-11-21"
album = "テレビ東京系アニメーション「スケッチブック～full color's～」オリジナルサウンドトラック"
tracks = [
    [1, "遠まわりして帰ろ", "", ""],
    [2, "風さがし-TVサイズ-", "", ""],
    [3, "人見知りなままで～出逢いがしら", "", ""],
    [4, "人見知りなままで", "", ""],
    [5, "迷子の子猫", "", ""],
    [6, "小さな幸せ", "", ""],
    [7, "バルーンムード～夢から覚めても", "", ""],
    [8, "微笑みのもと", "", ""],
    [9, "夕焼けを歩いたね", "", ""],
    [10, "春風の贈りもの", "", ""],
    [11, "スピード2", "", ""],
    [12, "私の時間", "", ""],
    [13, "私の時間～また明日", "", ""],
    [14, "草摘みのうた", "", ""],
    [15, "お調子者のうた", "", ""],
    [16, "空き地のそら～ネコたちの自由", "", ""],
    [17, "僕らの冒険", "", ""],
    [18, "僕らの冒険～かえりみち", "", ""],
    [19, "希望のへさき", "", ""],
    [20, "ハッピーアワー", "", ""],
    [21, "雲の澪を行く", "", ""],
    [22, "夕まぐれの国", "", ""],
    [23, "バルーンムード～ピアノソロ", "", ""],
    [24, "スケッチブックを持ったまま-TVサイズ-", "", ""],
    [25, "希望のへさき～未来編", "", ""],
]
links = ["https://vgmdb.net/album/19860"]

[6]
catalognumber = "VTCL-35003"
date = "2007-10-24"
album = "スケッチブックを持ったまま / 牧野由依"
tracks = [
    [1, "スケッチブックを持ったまま", "", ""],
    [2, "遠くまで行こう", "", ""],
    [3, "6つの小品 Op.118 間奏曲 イ長調", "", ""],
    [4, "スケッチブックを持ったまま -Instrumental-", "", ""],
    [5, "遠くまで行こう -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/35385"]
