[1]
catalognumber = "LACA-15656"
date = "2017-08-09"
album = "TVアニメ『ひなろじ〜from Luck&Logic〜』ENDING THEME & CHARACTER SONG MINI ALBUM Baby Birds"
tracks = [
    [1, "ベィビィバード! 〜ガクエンロジック〜", "", ""],
    [2, "やわらかな明日", "", ""],
    [3, "EX-Positive Expositor!", "", ""],
    [4, "Grow Together!!!", "", ""],
    [5, "愛は華、愛は雛", "", ""],
    [6, "Foreigner Song 〜フォーリナーの唄〜", "", ""],
]
links = ["https://vgmdb.net/album/68040"]

[2]
catalognumber = "EMTN-10010"
date = "2016-02-17"
album = "盟約の彼方 / 新田恵海"
tracks = [
    [1, "盟約の彼方", "", ""],
    [2, "つなぐメロディー", "", ""],
    [3, "盟約の彼方 -Instrumental-", "", ""],
    [4, "つなぐメロディー -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/55703"]

[3]
catalognumber = "EMTN-10016"
date = "2017-07-19"
album = "Trace of EMUSIC / 新田恵海 Disc 1 (CD)"
tracks = [
    [1, "Smile again with you", "", ""],
    [2, "EMUSIC", "", ""],
    [3, "笑顔と笑顔で始まるよ!", "", ""],
    [4, "探求Dreaming", "", ""],
    [5, "NEXT PHASE", "", ""],
    [6, "盟約の彼方", "", ""],
    [7, "言葉より強く", "", ""],
    [8, "OURS POWERS", "", ""],
    [9, "ROCKET HEART", "", ""],
]
links = ["https://vgmdb.net/album/88881"]

[4]
catalognumber = "EMTN-10016"
date = "2017-07-19"
album = "Trace of EMUSIC / 新田恵海 Disc 2 (CD)"
tracks = [
    [1, "想像を超えた世界", "", ""],
    [2, "想いよ届け", "", ""],
    [3, "優しい世界そして未来へ", "", ""],
    [4, "Dear everyday", "", ""],
    [5, "Rainy*flower", "", ""],
    [6, "WONDER! SHUTTER LOVE", "", ""],
    [7, "スピカ", "", ""],
    [8, "つなぐメロディー", "", ""],
    [9, "きらめきを夢みて", "", ""],
    [10, "Believe in (E)MUSIC", "", ""],
]
links = ["https://vgmdb.net/album/88881"]

[5]
catalognumber = "EMTN-10016"
date = "2017-07-19"
album = "Trace of EMUSIC / 新田恵海 Disc 3 (Blu-ray)"
tracks = [
    [1, "笑顔と笑顔で始まるよ! (Music Clip)", "", ""],
    [2, "探求Dreaming (Music Clip)", "", ""],
    [3, "NEXT PHASE (Music Clip)", "", ""],
    [4, "EMUSIC (Music Clip)", "", ""],
    [5, "盟約の彼方 (Music Clip)", "", ""],
    [6, "ROCKET HEART (Music Clip)", "", ""],
    [7, "Smile again with you (Music Clip)", "", ""],
]
links = ["https://vgmdb.net/album/88881"]

[6]
catalognumber = "LACA-35723"
date = "2018-04-25"
album = "Lonely Queen's Liberation Party / TRUE [Limited Edition] Disc 1 (CD) [LACA-35723]"
tracks = [
    [1, "Lonely Queen's Liberation Party", "", ""],
    [2, "Sincerely", "", ""],
    [3, "次の僕へ", "", ""],
    [4, "分身", "", ""],
    [5, "終わりたい世界", "", ""],
    [6, "BUTTERFLY EFFECTOR", "", ""],
    [7, "JUMPIN'", "", ""],
    [8, "Roadmap", "", ""],
    [9, "フロム", "", ""],
    [10, "酸素", "", ""],
    [11, "耳恋ミュージック", "", ""],
    [12, "サンドリヨン", "", ""],
    [13, "パズル", "", ""],
    [14, "Anchors Step", "", ""],
]
links = ["https://vgmdb.net/album/74815"]

[7]
catalognumber = "LACA-35723"
date = "2018-04-25"
album = "Lonely Queen's Liberation Party / TRUE [Limited Edition] Disc 2 (Blu-ray) [LAPD-1495]"
tracks = [
    [1, "Rainbow The Daydream", "", ""],
    [2, "サウンドスケープ", "", ""],
    [3, "アイワナビ", "", ""],
    [4, "RIPTIDE", "", ""],
    [5, "鍵のない鳥籠", "", ""],
    [6, "ヒカリ", "", ""],
    [7, "キネマ", "", ""],
    [8, "海底のお城", "", ""],
    [9, "Dear answer", "", ""],
    [10, "STEEL -鉄血の絆-", "", ""],
    [11, "飛竜の騎士", "", ""],
    [12, "グレースケール", "", ""],
    [13, "ボイスグライダー", "", ""],
    [14, "UNISONIA", "", ""],
    [15, "Divine Spell", "", ""],
    [16, "BUTTERFLY EFFECTOR", "", ""],
    [17, "カレイドスコープ", "", ""],
    [18, "フロム", "", ""],
    [19, "TRUE COLORS -ENCORE-", "", ""],
    [20, "DREAM SOLISTER -ENCORE-", "", ""],
    [21, "サウンドスケープ -ENCORE-", "", ""],
]
links = ["https://vgmdb.net/album/74815"]

[8]
catalognumber = "EMTN-10011"
date = "2016-02-17"
album = "盟約の彼方 / 新田恵海 Disc 1 (CD)"
tracks = [
    [1, "盟約の彼方", "", ""],
    [2, "つなぐメロディー", "", ""],
    [3, "盟約の彼方 -Instrumental-", "", ""],
    [4, "つなぐメロディー -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/55704"]

[9]
catalognumber = "EMTN-10011"
date = "2016-02-17"
album = "盟約の彼方 / 新田恵海 Disc 2 (DVD)"
tracks = [
    [1, "DVD", "", ""],
]
links = ["https://vgmdb.net/album/55704"]

[10]
catalognumber = "LACM-34422"
date = "2016-01-27"
album = "STORY / 小野賢章 Disc 1 (CD) [LACM-34422]"
tracks = [
    [1, "STORY", "", ""],
    [2, "Rainbow Road", "", ""],
    [3, "STORY (Off Vocal)", "", ""],
    [4, "Rainbow Road (Off Vocal)", "", ""],
]
links = ["https://vgmdb.net/album/55710"]

[11]
catalognumber = "LACM-34422"
date = "2016-01-27"
album = "STORY / 小野賢章 Disc 2 (DVD) [LAPD-1371]"
tracks = [
    [1, "STORY -Music Video-", "", ""],
]
links = ["https://vgmdb.net/album/55710"]

[12]
catalognumber = "LACA-15723"
date = "2018-04-25"
album = "Lonely Queen's Liberation Party / TRUE"
tracks = [
    [1, "Lonely Queen's Liberation Party", "", ""],
    [2, "Sincerely", "", ""],
    [3, "次の僕へ", "", ""],
    [4, "分身", "", ""],
    [5, "終わりたい世界", "", ""],
    [6, "BUTTERFLY EFFECTOR", "", ""],
    [7, "JUMPIN'", "", ""],
    [8, "Roadmap", "", ""],
    [9, "フロム", "", ""],
    [10, "酸素", "", ""],
    [11, "耳恋ミュージック", "", ""],
    [12, "サンドリヨン", "", ""],
    [13, "パズル", "", ""],
    [14, "Anchors Step", "", ""],
]
links = ["https://vgmdb.net/album/74816"]

[13]
catalognumber = "LACA-35886"
date = "2021-08-25"
album = "コトバアソビ / TRUE [初回限定盤] Vocal"
tracks = [
    [1, "MUSIC", "", ""],
    [2, "Blast!", "", ""],
    [3, "Another colony", "", ""],
    [4, "空に読む物語", "", ""],
    [5, "inorganic", "", ""],
    [6, "Acceleration", "", ""],
    [7, "リブート!", "", ""],
    [8, "叙情詩とロマンス", "", ""],
    [9, "ステラ", "", ""],
    [10, "僕の中の君へ", "", ""],
    [11, "Storyteller", "", ""],
    [12, "WILL", "", ""],
    [13, "Sincerely (English version)", "", ""],
]
links = ["https://vgmdb.net/album/112172"]

[14]
catalognumber = "LACA-35886"
date = "2021-08-25"
album = "コトバアソビ / TRUE [初回限定盤] Vocal, Live Event, Video"
tracks = [
    [1, "黎明", "", ""],
    [2, "Lonely Queen's Liberation Party", "", ""],
    [3, "Another colony", "", ""],
    [4, "終わりたい世界", "", ""],
    [5, "名前のない空腹", "", ""],
    [6, "Dear answer", "", ""],
    [7, "ステラ", "", ""],
    [8, "memento", "", ""],
    [9, "Sincerely", "", ""],
    [10, "Blast!", "", ""],
    [11, "分身", "", ""],
    [12, "次の僕へ", "", ""],
    [13, "サウンドスケープ", "", ""],
    [14, "WILL～未来のひとへ", "", ""],
    [15, "BUTTERFLY EFFECTOR", "", ""],
    [16, "Storyteller", "", ""],
    [17, "DREAM SOLISTER", "", ""],
]
links = ["https://vgmdb.net/album/112172"]

[15]
catalognumber = "LACM-14422"
date = "2016-01-27"
album = "STORY / 小野賢章"
tracks = [
    [1, "STORY", "", ""],
    [2, "Rainbow Road", "", ""],
    [3, "STORY (Off Vocal)", "", ""],
    [4, "Rainbow Road (Off Vocal)", "", ""],
]
links = ["https://vgmdb.net/album/55709"]

[16]
catalognumber = "LACA-9551"
date = "2017-10-18"
album = "TVアニメ『ひなろじ～from Luck & Logic～』オリジナルサウンドトラック Disc 1 [LACA-9551]"
tracks = [
    [1, "ひなろじ", "", ""],
    [2, "BUTTERFLY EFFECTOR (TVサイズ)", "", ""],
    [3, "ピラリ学園へようこそ", "", ""],
    [4, "上を下への大騒ぎ", "", ""],
    [5, "学園長の竪琴", "", ""],
    [6, "フォーリナー", "", ""],
    [7, "危険な暴走", "", ""],
    [8, "あなたの力になりたい", "", ""],
    [9, "ベルのテーマ", "", ""],
    [10, "ロジカリストをめざして", "", ""],
    [11, "トランス! 〜やよいver.〜", "", ""],
    [12, "トランス! 〜まひろver.〜", "", ""],
    [13, "手加減はなしよ!", "", ""],
    [14, "汗と涙と友情と", "", ""],
    [15, "白樺寮の休日", "", ""],
    [16, "ごめんあそばせ", "", ""],
    [17, "隣は何をする人ぞ", "", ""],
    [18, "生徒会長のお出まし", "", ""],
    [19, "トランス! 〜夕子ver.〜", "", ""],
    [20, "愛の語らい", "", ""],
    [21, "森と泉に囲まれて", "", ""],
    [22, "心が触れ合うとき", "", ""],
    [23, "流星に願いを", "", ""],
    [24, "乙女たちの時間", "", ""],
    [25, "ピラリ音頭", "", ""],
    [26, "ひなろじエレジー", "", ""],
]
links = ["https://vgmdb.net/album/69584"]

[17]
catalognumber = "LACA-9552"
date = "2017-10-18"
album = "TVアニメ『ひなろじ～from Luck & Logic～』オリジナルサウンドトラック Disc 2 [LACA-9552]"
tracks = [
    [1, "大草原の大きな学園", "", ""],
    [2, "やるときはやるのよ", "", ""],
    [3, "夢への扉を開けて", "", ""],
    [4, "終わりよければすべてよし", "", ""],
    [5, "まどろみの教室", "", ""],
    [6, "とかくこの世はままならぬ", "", ""],
    [7, "浮き浮き気分で行こう", "", ""],
    [8, "気まずい空気", "", ""],
    [9, "素直になれなくて", "", ""],
    [10, "迷い道", "", ""],
    [11, "緊迫の対峙", "", ""],
    [12, "焦燥", "", ""],
    [13, "トランス! 〜ニーナver.〜", "", ""],
    [14, "白熱戦", "", ""],
    [15, "胸を裂く悲しみ", "", ""],
    [16, "迫りくる危機", "", ""],
    [17, "盟約", "", ""],
    [18, "トランス! 〜リオンver.〜", "", ""],
    [19, "神秘の力", "", ""],
    [20, "大切な人を守るため", "", ""],
    [21, "ありがとうを伝えたい", "", ""],
    [22, "学び舎をわたる風", "", ""],
    [23, "いつか巣立つ日まで", "", ""],
    [24, "ベィビィバード! 〜ガクエンロジック〜 (TVサイズ)", "", ""],
]
links = ["https://vgmdb.net/album/69584"]

[18]
catalognumber = "LACA-9446"
date = "2016-04-20"
album = "TVアニメ『ラクエンロジック』オリジナルサウンドトラック「Music & Sound」 Original Soundtrack"
tracks = [
    [1, "Luck & Logic", "", ""],
    [2, "Will of Logicalist", "", ""],
    [3, "Will of Foreigner", "", ""],
    [4, "Septopia", "", ""],
    [5, "Yoshichika & Athena", "", ""],
    [6, "Relationship of Trust", "", ""],
    [7, "Olga Breakchild", "", ""],
    [8, "Olga & Lucifer", "", ""],
    [9, "Tamaki Yurine", "", ""],
    [10, "Chloe Maxwell", "", ""],
    [11, "Mana Asuha", "", ""],
    [12, "Yukari Nanahoshi", "", ""],
    [13, "Quetzalcoatl", "", ""],
    [14, "Veronica Ananko", "", ""],
    [15, "Paradox Zone", "", ""],
    [16, "Lucifer", "", ""],
    [17, "Trance", "", ""],
    [18, "Trance Image", "", ""],
    [19, "Chance Meeting", "", ""],
    [20, "Trial lesson", "", ""],
    [21, "Trial attack", "", ""],
    [22, "Yoshichika's family", "", ""],
    [23, "Daily ALCA", "", ""],
    [24, "Tiny \"Quets\"", "", ""],
    [25, "Holiday!", "", ""],
    [26, "Party!", "", ""],
    [27, "Horror Picture", "", ""],
]
links = ["https://vgmdb.net/album/56689"]

[19]
catalognumber = "LACA-9447"
date = "2016-04-20"
album = "TVアニメ『ラクエンロジック』オリジナルサウンドトラック「Music & Sound」 Original Soundtrack, Vocal"
tracks = [
    [1, "Tension", "", ""],
    [2, "Mission", "", ""],
    [3, "Enemy Attack (Paradox Level3.7)", "", ""],
    [4, "Enemy Attack (Paradox Level6.5)", "", ""],
    [5, "Enemy Attack (Paradox Level8.9)", "", ""],
    [6, "With Warmth", "", ""],
    [7, "For Mana", "", ""],
    [8, "Doubts", "", ""],
    [9, "Open the Door", "", ""],
    [10, "Emotional Conflict", "", ""],
    [11, "Trouble of the World", "", ""],
    [12, "Olga's Secret Agreement", "", ""],
    [13, "Tetra-Heaven", "", ""],
    [14, "Logic Drive", "", ""],
    [15, "Go! Logicalist", "", ""],
    [16, "Battle of Logicalist", "", ""],
    [17, "The Power of the Team,ALCA", "", ""],
    [18, "Trance Jack", "", ""],
    [19, "For Trance", "", ""],
    [20, "Logicalist Battle", "", ""],
    [21, "Trance Olga", "", ""],
    [22, "Over Trance", "", ""],
    [23, "Memory of Lucifer", "", ""],
    [24, "Athena", "", ""],
    [25, "STORY(TV Size)", "", ""],
    [26, "盟約の彼方(TV Size)", "", ""],
    [27, "ろんり", "", ""],
    [28, "うんね", "", ""],
    [29, "あど", "", ""],
]
links = ["https://vgmdb.net/album/56689"]

[20]
catalognumber = "LACA-15567"
date = "2016-06-08"
album = "TVアニメ『ラクエンロジック』キャラクターソングアルバム SONGS & MELODY"
tracks = [
    [1, "White Destination", "", ""],
    [2, "愛が世界を救う♡Love is forever♡", "", ""],
    [3, "SWORD FOR DEFEND!", "", ""],
    [4, "月に囁くその声で", "", ""],
    [5, "行け! 空飛ぶDreamer", "", ""],
    [6, "真実のウォーリアー", "", ""],
    [7, "My dearest Hero", "", ""],
]
links = ["https://vgmdb.net/album/57642"]

[21]
catalognumber = "LACM-14621"
date = "2017-07-26"
album = "BUTTERFLY EFFECTOR / TRUE"
tracks = [
    [1, "BUTTERFLY EFFECTOR", "", ""],
    [2, "HANABI", "", ""],
    [3, "BUTTERFLY EFFECTOR (off vocal)", "", ""],
]
links = ["https://vgmdb.net/album/68039"]
