[1]
catalognumber = "TYCT-60192"
date = "2022-03-02"
album = "事象の地平線 / 神はサイコロを振らない Disc 1 [TYCT-60192]"
tracks = [
    [1, "イリーガル・ゲーム", "", ""],
    [2, "タイムファクター", "", ""],
    [3, "巡る巡る", "", ""],
    [4, "初恋", "", ""],
    [5, "泡沫花火", "", ""],
    [6, "LOVE", "", ""],
    [7, "1on1", "", ""],
    [8, "愛のけだもの", "", ""],
    [9, "遺言状", "", ""],
    [10, "徒夢の中で", "", ""],
]
links = ["https://vgmdb.net/album/116829"]

[2]
catalognumber = "TYCT-60193"
date = "2022-03-02"
album = "事象の地平線 / 神はサイコロを振らない Disc 2 [TYCT-60193]"
tracks = [
    [1, "あなただけ", "", ""],
    [2, "クロノグラフ彗星", "", ""],
    [3, "少年よ永遠に", "", ""],
    [4, "目蓋", "", ""],
    [5, "導火線", "", ""],
    [6, "パーフェクト・ルーキーズ", "", ""],
    [7, "夜永唄 - Unplugged 2022", "", ""],
    [8, "プラトニック・ラブ", "", ""],
    [9, "未来永劫", "", ""],
    [10, "僕だけが失敗作みたいで", "", ""],
]
links = ["https://vgmdb.net/album/116829"]

[3]
catalognumber = "AVCD-83283"
date = "2015-05-27"
album = "アシタノヒカリ / AAA [アニメ盤]"
tracks = [
    [1, "アシタノヒカリ", "", ""],
    [2, "アシタノヒカリ(Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/51802"]

[4]
catalognumber = "VICL-65031"
date = "2018-08-16"
album = "The Best of Pile / Pile"
tracks = [
    [1, "伝説のFLARE", "", ""],
    [2, "⇒ NEXT WORLD ⇒", "", ""],
    [3, "Furuwasete", "", ""],
    [4, "キミがくれたKISEKI", "", ""],
    [5, "ドリームトリガー", "", ""],
    [6, "チェックメイト", "", ""],
    [7, "P.S.ありがとう...", "", ""],
    [8, "Melody", "", ""],
    [9, "素晴らしきSekai", "", ""],
    [10, "VENGEANCE", "", ""],
    [11, "ROAD", "", ""],
    [12, "絆Hero", "", ""],
    [13, "Lost Paradise", "", ""],
    [14, "Cliche", "", ""],
    [15, "Go My Way", "", ""],
    [16, "BJ", "", ""],
    [17, "Your is All... (Bonus Track)", "", ""],
]
links = ["https://vgmdb.net/album/81723"]

[5]
catalognumber = "TKCA-74156"
date = "2014-11-05"
album = "笑顔の理由。/GIRIGIRI / ソナーポケット [初回生産限定盤A] Disc 1 (CD)"
tracks = [
    [1, "笑顔の理由。", "", ""],
    [2, "GIRIGIRI", "", ""],
    [3, "笑顔の理由。(instrumental)", "", ""],
    [4, "GIRIGIRI(instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/48021"]

[6]
catalognumber = "TKCA-74156"
date = "2014-11-05"
album = "笑顔の理由。/GIRIGIRI / ソナーポケット [初回生産限定盤A] Disc 2 (DVD)"
tracks = [
    [1, "笑顔の理由。 (MV)", "", ""],
    [2, "笑顔の理由。 (MV メイキング&オフショット)", "", ""],
]
links = ["https://vgmdb.net/album/48021"]

[7]
catalognumber = "UPCH-5984"
date = "2021-12-15"
album = "雲外憧憬 / FantasticYouth"
tracks = [
    [1, "雲外憧憬", "", ""],
    [2, "雲外憧憬 - English ver.", "", ""],
    [3, "東京青走", "", ""],
]
links = ["https://vgmdb.net/album/115394"]

[8]
catalognumber = "UICZ-4353"
date = "2016-05-11"
album = "TVアニメ『ワールドトリガー』オリジナル・サウンドトラック"
tracks = [
    [1, "ワールドトリガー メインテーマ", "", ""],
    [2, "平和な日々", "", ""],
    [3, "ランク戦-思考-", "", ""],
    [4, "実力派エリート", "", ""],
    [5, "自分への問い", "", ""],
    [6, "ランク戦-理由-", "", ""],
    [7, "ランク戦-反撃-", "", ""],
    [8, "玉狛のおやつ", "", ""],
    [9, "100倍楽しむ!", "", ""],
    [10, "ボーダー上層部", "", ""],
    [11, "近界民(ネイバー)の驚異", "", ""],
    [12, "ゲート発生-近界民(ネイバー)襲撃-", "", ""],
    [13, "城戸司令の思惑", "", ""],
    [14, "ボーダー出撃", "", ""],
    [15, "孤独", "", ""],
    [16, "楽しい日々", "", ""],
    [17, "近界民(ネイバー)との対峙", "", ""],
    [18, "ブラックトリガー", "", ""],
    [19, "トリガーオン!!", "", ""],
    [20, "ランク戦-開始-", "", ""],
    [21, "近界民(ネイバー)の力", "", ""],
    [22, "雷神丸", "", ""],
    [23, "未来への光", "", ""],
    [24, "ランク戦-乱戦-", "", ""],
    [25, "惑星国家の軌道", "", ""],
    [26, "神の国アフトクラトル", "", ""],
    [27, "ギリギリの戦い", "", ""],
    [28, "エルガテスからの刺客", "", ""],
    [29, "乱星国家エルガテス", "", ""],
    [30, "未来への約束", "", ""],
    [31, "玉狛の休日", "", ""],
    [32, "激戦開始", "", ""],
    [33, "制御不能", "", ""],
    [34, "麗しき破壊の女神", "", ""],
    [35, "トリオン兵召喚", "", ""],
    [36, "絆", "", ""],
    [37, "玉狛で迎える朝", "", ""],
    [38, "GIRIGIRI (TV SIZE) -Bonus Tracks-", "", ""],
    [39, "アシタノヒカリ (TV SIZE) -Bonus Tracks-", "", ""],
    [40, "ドリームトリガー (TVサイズ ver.) -Bonus Tracks-", "", ""],
]
links = ["https://vgmdb.net/album/57968"]

[9]
catalognumber = "VICL-37165"
date = "2016-05-18"
album = "Melody / Pile [アニメ盤]"
tracks = [
    [1, "Melody", "", ""],
    [2, "ドリームトリガー -another ver.-", "", ""],
    [3, "Melody <off vocal>", "", ""],
    [4, "ドリームトリガー -another ver.- <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/57858"]

[10]
catalognumber = "DSSD-11215"
date = "2015-07-08"
album = "ワールドトリガー オリジナルドラマCD『玉狛支部の眠れない夜』"
tracks = [
    [1, "玉狛支部の眠れない夜", "", ""],
]
links = ["https://vgmdb.net/album/117257"]

[11]
catalognumber = "UV1AS-00682"
date = "2021-10-17"
album = "タイムファクター / 神はサイコロを振らない"
tracks = [
    [1, "タイムファクター", "", ""],
]
links = ["https://vgmdb.net/album/115773"]

[12]
catalognumber = "TKCA-74170"
date = "2014-11-05"
album = "GIRIGIRI/笑顔の理由。 / ソナーポケット [通常盤B]"
tracks = [
    [1, "GIRIGIRI", "", ""],
    [2, "笑顔の理由。", "", ""],
    [3, "タノシマセ隊!!!", "", ""],
    [4, "GIRIGIRI(TV size)", "", ""],
    [5, "GIRIGIRI(instrumental)", "", ""],
    [6, "笑顔の理由。(instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/48018"]

[13]
catalognumber = "VIZL-895"
date = "2015-11-04"
album = "ドリームトリガー / Pile [初回限定盤 A] Disc 1 (CD)"
tracks = [
    [1, "ドリームトリガー", "", ""],
    [2, "ヴァンパイア革命", "", ""],
    [3, "伝説のFLARE -strings ver.- <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/55199"]

[14]
catalognumber = "VIZL-895"
date = "2015-11-04"
album = "ドリームトリガー / Pile [初回限定盤 A] Disc 2 (DVD)"
tracks = [
    [1, "「ドリームトリガー」Music Video", "", ""],
    [2, "Live映像「JEWEL VOX」ワンマンツアー＠渋谷duo", "", ""],
]
links = ["https://vgmdb.net/album/55199"]

[15]
catalognumber = "TYCT-69234"
date = "2022-03-02"
album = "事象の地平線 / 神はサイコロを振らない [初回限定盤] Vocal Disc 1"
tracks = [
    [1, "イリーガル・ゲーム", "", ""],
    [2, "タイムファクター", "", ""],
    [3, "巡る巡る", "", ""],
    [4, "初恋", "", ""],
    [5, "泡沫花火", "", ""],
    [6, "LOVE", "", ""],
    [7, "1on1", "", ""],
    [8, "愛のけだもの", "", ""],
    [9, "遺言状", "", ""],
    [10, "徒夢の中で", "", ""],
]
links = ["https://vgmdb.net/album/116830"]

[16]
catalognumber = "TYCT-69234"
date = "2022-03-02"
album = "事象の地平線 / 神はサイコロを振らない [初回限定盤] Vocal Disc 2"
tracks = [
    [1, "あなただけ", "", ""],
    [2, "クロノグラフ彗星", "", ""],
    [3, "少年よ永遠に", "", ""],
    [4, "目蓋", "", ""],
    [5, "導火線", "", ""],
    [6, "パーフェクト・ルーキーズ", "", ""],
    [7, "夜永唄 - Unplugged 2022", "", ""],
    [8, "プラトニック・ラブ", "", ""],
    [9, "未来永劫", "", ""],
    [10, "僕だけが失敗作みたいで", "", ""],
]
links = ["https://vgmdb.net/album/116830"]

[17]
catalognumber = "TYCT-69234"
date = "2022-03-02"
album = "事象の地平線 / 神はサイコロを振らない [初回限定盤] Vocal, Live Event, Video"
tracks = [
    [1, "クロノグラフ彗星", "", ""],
    [2, "揺らめいて候", "", ""],
    [3, "遺言状", "", ""],
    [4, "泡沫花火", "", ""],
    [5, "胡蝶蘭", "", ""],
    [6, "解放宣言", "", ""],
    [7, "パーフェクト・ルーキーズ", "", ""],
    [8, "ジュブナイルに捧ぐ", "", ""],
    [9, "夜永唄", "", ""],
    [10, "プラトニック・ラブ", "", ""],
    [11, "1on1", "", ""],
    [12, "未来永劫", "", ""],
    [13, "巡る巡る", "", ""],
    [14, "illumination", "", ""],
    [15, "遠征ライブ密着 - ライブ稼働の裏側全部見せちゃいます -", "", ""],
    [16, "野音Live 2022「最下層からの観測」ドッキリ開催発表映像", "", ""],
]
links = ["https://vgmdb.net/album/116830"]

[18]
catalognumber = "TYCT-69189"
date = "2021-01-20"
album = "STILL DREAMING / TOMORROW X TOGETHER [初回限定盤A]"
tracks = [
    [1, "Intro : DREAMING", "", ""],
    [2, "Force", "", ""],
    [3, "5時53分の空で見つけた君と僕 [Japanese Ver.]", "", ""],
    [4, "9と4分の3番線で君を待つ (Run Away) [Japanese Ver.]", "", ""],
    [5, "ある日、頭からツノが生えた (CROWN) [Japanese Ver.]", "", ""],
    [6, "Angel Or Devil [Japanese Ver.]", "", ""],
    [7, "Drama [Japanese Ver.]", "", ""],
    [8, "永遠に光れ (Everlasting Shine)", "", ""],
    [9, "Can't You See Me? (世界が燃えてしまった夜、僕たちは...) [Japanese Ver.]", "", ""],
    [10, "Outro : STILL", "", ""],
]
links = ["https://vgmdb.net/album/108279"]

[19]
catalognumber = "VIZL-1406"
date = "2018-08-16"
album = "The Best of Pile / Pile [初回限定盤A] Disc 1 (CD)"
tracks = [
    [1, "伝説のFLARE", "", ""],
    [2, "⇒ NEXT WORLD ⇒", "", ""],
    [3, "Furuwasete", "", ""],
    [4, "キミがくれたKISEKI", "", ""],
    [5, "ドリームトリガー", "", ""],
    [6, "チェックメイト", "", ""],
    [7, "P.S.ありがとう…", "", ""],
    [8, "Melody", "", ""],
    [9, "素晴らしきSekai", "", ""],
    [10, "VENGEANCE", "", ""],
    [11, "ROAD", "", ""],
    [12, "絆Hero", "", ""],
    [13, "Lost Paradise", "", ""],
    [14, "Cliche", "", ""],
    [15, "Go My Way", "", ""],
    [16, "BJ", "", ""],
    [17, "Your is All... (Bonus Track)", "", ""],
]
links = ["https://vgmdb.net/album/81724"]

[20]
catalognumber = "VIZL-1406"
date = "2018-08-16"
album = "The Best of Pile / Pile [初回限定盤A] Disc 2 (Blu-ray)"
tracks = [
    [1, "BJ", "", ""],
    [2, "Lost Paradise", "", ""],
    [3, "素晴らしきSekai", "", ""],
    [4, "Melody", "", ""],
    [5, "ドリームトリガー", "", ""],
    [6, "キミがくれたKISEKI", "", ""],
    [7, "伝説のFLARE", "", ""],
    [8, "Black Butterfly", "", ""],
    [9, "～Jewelry Door～", "", ""],
]
links = ["https://vgmdb.net/album/81724"]

[21]
catalognumber = "VICL-37114"
date = "2015-11-04"
album = "ドリームトリガー / Pile [初回限定盤 B]"
tracks = [
    [1, "ドリームトリガー", "", ""],
    [2, "ヴァンパイア革命", "", ""],
    [3, "キミがくれたKISEKI -strings ver.- <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/55200"]

[22]
catalognumber = "COCX-41714"
date = "2022-04-27"
album = "TVアニメ「ワールドトリガー」オリジナル・サウンドトラック2"
tracks = [
    [1, "ランク戦-攻勢- (M102)", "", ""],
    [2, "オフタイム (M123)", "", ""],
    [3, "ガロプラ-計略- (M120)", "", ""],
    [4, "ランク戦-撹乱- (M111)", "", ""],
    [5, "突破口 (M115)", "", ""],
    [6, "戸惑い (M117)", "", ""],
    [7, "平和な時間 (M124)", "", ""],
    [8, "走れ!雷神丸 (M109)", "", ""],
    [9, "分析 (M61)", "", ""],
    [10, "ランク戦-頭脳戦- (M112)", "", ""],
    [11, "ガロプラ-脅威- (M110)", "", ""],
    [12, "1対1 (M114)", "", ""],
    [13, "逆転 (M21)", "", ""],
    [14, "夢への一歩 (M49)", "", ""],
    [15, "対峙と激突 (M113)", "", ""],
    [16, "超常 (M24)", "", ""],
    [17, "前へ (M107)", "", ""],
    [18, "探り合い (M84)", "", ""],
    [19, "交渉 (M105)", "", ""],
    [20, "予兆 (M25)", "", ""],
    [21, "勝利の食卓 (M79)", "", ""],
    [22, "すいません、ウソです! (M36)", "", ""],
    [23, "陽太郎! (M64)", "", ""],
    [24, "駆け引き (M27)", "", ""],
    [25, "ランク戦-最終局面- (M57)", "", ""],
    [26, "ランク戦-勝利- (M2)", "", ""],
    [27, "想い (M31)", "", ""],
    [28, "辛い記憶 (M30)", "", ""],
    [29, "ランク戦-激突- (M18)", "", ""],
    [30, "活路 (M55)", "", ""],
    [31, "クライマックス (M122)", "", ""],
    [32, "解析 (M119)", "", ""],
    [33, "新しい日常 (M108)", "", ""],
    [34, "意志 (M45)", "", ""],
    [35, "別れ (M65)", "", ""],
    [36, "生死 (M48)", "", ""],
    [37, "意地 (M122B)", "", ""],
    [38, "約束 (M121)", "", ""],
    [39, "新生 (M101)", "", ""],
]
links = ["https://vgmdb.net/album/116237"]

[23]
catalognumber = "TYCT-39153"
date = "2021-03-17"
album = "エーテルの正体 / 神はサイコロを振らない [アニメ盤]"
tracks = [
    [1, "未来永劫", "", ""],
    [2, "クロノグラフ彗星", "", ""],
    [3, "プラトニック・ラブ", "", ""],
    [4, "1on1", "", ""],
]
links = ["https://vgmdb.net/album/107975"]

[24]
catalognumber = "VICL-37115"
date = "2015-11-04"
album = "ドリームトリガー / Pile [アニメ盤]"
tracks = [
    [1, "ドリームトリガー", "", ""],
    [2, "ヴァンパイア革命", "", ""],
]
links = ["https://vgmdb.net/album/55201"]

[25]
catalognumber = "DSSD-11213"
date = "2015-05-13"
album = "ワールドトリガー オリジナルドラマCD『祝! 玉狛支部・たつこの部屋出演!』"
tracks = [
    [1, "祝! 玉狛支部・たつこの部屋出演!", "", ""],
]
links = ["https://vgmdb.net/album/117256"]

[26]
catalognumber = "TKCA-74160"
date = "2014-11-05"
album = "笑顔の理由。/GIRIGIRI / ソナーポケット [通常盤A]"
tracks = [
    [1, "笑顔の理由。", "", ""],
    [2, "GIRIGIRI", "", ""],
    [3, "タノシマセ隊!!!", "", ""],
    [4, "笑顔の理由。(instrumental)", "", ""],
    [5, "GIRIGIRI(instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/48017"]

[27]
catalognumber = "VICL-37164"
date = "2016-05-18"
album = "Melody / Pile [初回限定盤B]"
tracks = [
    [1, "Melody", "", ""],
    [2, "angel song -another ver.-", "", ""],
    [3, "ドリームトリガー -another ver.-", "", ""],
    [4, "Melody <off vocal>", "", ""],
    [5, "angel song -another ver.- <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/57857"]

[28]
catalognumber = "TYCT-39152"
date = "2021-03-17"
album = "エーテルの正体 / 神はサイコロを振らない [LIVE盤] Vocal"
tracks = [
    [1, "未来永劫", "", ""],
    [2, "クロノグラフ彗星", "", ""],
    [3, "プラトニック・ラブ", "", ""],
    [4, "1on1", "", ""],
]
links = ["https://vgmdb.net/album/107976"]

[29]
catalognumber = "TYCT-39152"
date = "2021-03-17"
album = "エーテルの正体 / 神はサイコロを振らない [LIVE盤] Vocal, Live Event, Video"
tracks = [
    [1, "ジュブナイルに捧ぐ (Streaming Live「理-kotowari-」)", "", ""],
    [2, "揺らめいて候 (Streaming Live「理-kotowari-」)", "", ""],
    [3, "胡蝶蘭 (Streaming Live「理-kotowari-」)", "", ""],
    [4, "illumination (Streaming Live「理-kotowari-」)", "", ""],
    [5, "解放宣言 (Streaming Live「理-kotowari-」)", "", ""],
    [6, "アノニマス (Streaming Live「理-kotowari-」)", "", ""],
    [7, "パーフェクト・ルーキーズ (Streaming Live「理-kotowari-」)", "", ""],
    [8, "No Matter What (Streaming Live「理-kotowari-」)", "", ""],
    [9, "CLUB 27 (Streaming Live「理-kotowari-」)", "", ""],
    [10, "夜永唄 (Streaming Live「理-kotowari-」)", "", ""],
    [11, "泡沫花火 (Streaming Live「理-kotowari-」)", "", ""],
    [12, "目蓋 (九州産業大学「香椎祭」)", "", ""],
    [13, "クロノグラフ彗星 (Studio Shot in One Take Live-Keeping COUNTDOWN JAPAN&RADIO CRAZY spirit alive)", "", ""],
]
links = ["https://vgmdb.net/album/107976"]

[30]
catalognumber = "TYCT-69190"
date = "2021-01-20"
album = "STILL DREAMING / TOMORROW X TOGETHER [初回限定盤B] Vocal"
tracks = [
    [1, "Intro : DREAMING", "", ""],
    [2, "Force", "", ""],
    [3, "5時53分の空で見つけた君と僕 [Japanese Ver.]", "", ""],
    [4, "9と4分の3番線で君を待つ (Run Away) [Japanese Ver.]", "", ""],
    [5, "ある日、頭からツノが生えた (CROWN) [Japanese Ver.]", "", ""],
    [6, "Angel Or Devil [Japanese Ver.]", "", ""],
    [7, "Drama [Japanese Ver.]", "", ""],
    [8, "永遠に光れ (Everlasting Shine)", "", ""],
    [9, "Can't You See Me? (世界が燃えてしまった夜、僕たちは...) [Japanese Ver.]", "", ""],
    [10, "Outro : STILL", "", ""],
]
links = ["https://vgmdb.net/album/108281"]

[31]
catalognumber = "TYCT-69190"
date = "2021-01-20"
album = "STILL DREAMING / TOMORROW X TOGETHER [初回限定盤B] Vocal, Video"
tracks = [
    [1, "5時53分の空で見つけた君と僕 [Japanese Ver.] (Music Video)", "", ""],
    [2, "5時53分の空で見つけた君と僕 [Japanese Ver.] (Making of Music Video)", "", ""],
    [3, "Making of Jacket Photos", "", ""],
]
links = ["https://vgmdb.net/album/108281"]

[32]
catalognumber = "VIZL-963"
date = "2016-05-18"
album = "Melody / Pile [初回限定盤A] Arrangement, Vocal"
tracks = [
    [1, "Melody", "", ""],
    [2, "angel song", "", ""],
    [3, "ドリームトリガー -another ver.-", "", ""],
    [4, "Melody <off vocal>", "", ""],
    [5, "angel song <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/57856"]

[33]
catalognumber = "VIZL-963"
date = "2016-05-18"
album = "Melody / Pile [初回限定盤A] Vocal"
tracks = [
    [1, "「Melody」ミュージックビデオ", "", ""],
]
links = ["https://vgmdb.net/album/57856"]

[34]
catalognumber = "TYCT-30121"
date = "2021-03-17"
album = "エーテルの正体 / 神はサイコロを振らない"
tracks = [
    [1, "未来永劫", "", ""],
    [2, "クロノグラフ彗星", "", ""],
    [3, "プラトニック・ラブ", "", ""],
    [4, "1on1", "", ""],
]
links = ["https://vgmdb.net/album/107974"]

[35]
catalognumber = "VICL-37116"
date = "2015-11-04"
album = "ドリームトリガー / Pile"
tracks = [
    [1, "ドリームトリガー", "", ""],
    [2, "ヴァンパイア革命", "", ""],
    [3, "ドリームトリガー -strings ver.- <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/55198"]

[36]
catalognumber = "DSSD-11211"
date = "2015-03-13"
album = "ワールドトリガー オリジナルドラマCD『もしも修と迅が嵐山隊に入ったら』"
tracks = [
    [1, "もしも修と迅が嵐山隊に入ったら", "", ""],
]
links = ["https://vgmdb.net/album/117255"]

[37]
catalognumber = "VICL-37163"
date = "2016-05-18"
album = "Melody / Pile"
tracks = [
    [1, "Melody", "", ""],
    [2, "angel song", "", ""],
    [3, "ドリームトリガー -another ver.-", "", ""],
    [4, "Melody <off vocal>", "", ""],
    [5, "angel song <off vocal>", "", ""],
]
links = ["https://vgmdb.net/album/57855"]

[38]
catalognumber = "TYCT-69191"
date = "2021-01-20"
album = "STILL DREAMING / TOMORROW X TOGETHER"
tracks = [
    [1, "Intro : DREAMING", "", ""],
    [2, "Force", "", ""],
    [3, "5時53分の空で見つけた君と僕 [Japanese Ver.]", "", ""],
    [4, "9と4分の3番線で君を待つ (Run Away) [Japanese Ver.]", "", ""],
    [5, "ある日、頭からツノが生えた (CROWN) [Japanese Ver.]", "", ""],
    [6, "Angel Or Devil [Japanese Ver.]", "", ""],
    [7, "Drama [Japanese Ver.]", "", ""],
    [8, "永遠に光れ (Everlasting Shine)", "", ""],
    [9, "Can't You See Me? (世界が燃えてしまった夜、僕たちは...) [Japanese Ver.]", "", ""],
    [10, "Outro : STILL", "", ""],
]
links = ["https://vgmdb.net/album/108278"]

[39]
catalognumber = "VIZL-1407"
date = "2018-08-16"
album = "The Best of Pile / Pile [初回限定盤B]"
tracks = [
    [1, "伝説のFLARE", "", ""],
    [2, "⇒ NEXT WORLD ⇒", "", ""],
    [3, "Furuwasete", "", ""],
    [4, "キミがくれたKISEKI", "", ""],
    [5, "ドリームトリガー", "", ""],
    [6, "チェックメイト", "", ""],
    [7, "P.S.ありがとう...", "", ""],
    [8, "Melody", "", ""],
    [9, "素晴らしきSekai", "", ""],
    [10, "VENGEANCE", "", ""],
    [11, "ROAD", "", ""],
    [12, "絆Hero", "", ""],
    [13, "Lost Paradise", "", ""],
    [14, "Cliche", "", ""],
    [15, "Go My Way", "", ""],
    [16, "BJ", "", ""],
    [17, "Your is All... (Bonus Track)", "", ""],
]
links = ["https://vgmdb.net/album/81725"]

[40]
catalognumber = "TKCA-74166"
date = "2014-11-05"
album = "GIRIGIRI/笑顔の理由。 / ソナーポケット [初回生産限定盤B] Disc 1 (CD)"
tracks = [
    [1, "GIRIGIRI", "", ""],
    [2, "笑顔の理由。", "", ""],
    [3, "GIRIGIRI(TV size)", "", ""],
    [4, "GIRIGIRI(instrumental)", "", ""],
    [5, "笑顔の理由。(instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/48020"]

[41]
catalognumber = "TKCA-74166"
date = "2014-11-05"
album = "GIRIGIRI/笑顔の理由。 / ソナーポケット [初回生産限定盤B] Disc 2 (DVD)"
tracks = [
    [1, "GIRIGIRI (MV)", "", ""],
    [2, "GIRIGIRI (MV メイキング&オフショット)", "", ""],
]
links = ["https://vgmdb.net/album/48020"]

[42]
catalognumber = "AVCD-83215"
date = "2015-05-27"
album = "アシタノヒカリ / AAA"
tracks = [
    [1, "アシタノヒカリ", "", ""],
    [2, "アシタノヒカリ(Instrumental)", "", ""],
]
links = ["https://vgmdb.net/album/51801"]
