[1]
catalognumber = ""
date = "2022-01-19"
album = "『無職転生 ～異世界行ったら本気だす～』 オリジナル・サウンドトラック2"
tracks = [
    [1, "冒険", "", ""],
    [2, "思考", "", ""],
    [3, "駆け引き", "", ""],
    [4, "いたずら", "", ""],
    [5, "まずい状況", "", ""],
    [6, "魔力が集まる場所", "", ""],
    [7, "ルイジェルドの怒り", "", ""],
    [8, "掌の上", "", ""],
    [9, "トーナとエリスの別れ", "", ""],
    [10, "ミリス神聖国", "", ""],
    [11, "初めての海", "", ""],
    [12, "魔界大帝キシリカ・キシリス!?", "", ""],
    [13, "ギレーヌのこと", "", ""],
    [14, "信頼を得る為に", "", ""],
    [15, "ウェンポート", "", ""],
    [16, "密輸組織", "", ""],
    [17, "作戦会議", "", ""],
    [18, "笑顔の力", "", ""],
    [19, "快適な牢屋", "", ""],
    [20, "先輩と新入", "", ""],
    [21, "ドルディア族", "", ""],
    [22, "共闘", "", ""],
    [23, "再会", "", ""],
    [24, "冒険者", "", ""],
    [25, "慰め", "", ""],
    [26, "待ってる", "", ""],
    [27, "神聖な世界", "", ""],
    [28, "シーローン王宮", "", ""],
    [29, "秘密の作戦", "", ""],
    [30, "まさか!?", "", ""],
    [31, "旅人の唄 -EP17 Inst Ver.-", "", ""],
    [32, "ロキシーへの想い", "", ""],
    [33, "ザノバの力", "", ""],
    [34, "圧倒的力との遭遇", "", ""],
]
links = ["https://vgmdb.net/album/117523"]

[2]
catalognumber = "TBR33225D-2"
date = "2023-10-18"
album = "無職転生II ～異世界行ったら本気だす～ Original Soundtrack 1 Special Edition"
tracks = [
    [1, "復活", "", ""],
    [2, "Neck And Neck", "", ""],
    [3, "アリエルの言葉", "", ""],
    [4, "凛として", "", ""],
    [5, "永遠なれ、アスラ王国", "", ""],
    [6, "夢の中でも", "", ""],
    [7, "バシェラント公国", "", ""],
    [8, "Critical The Situation", "", ""],
    [9, "冒険者稼業", "", ""],
    [10, "敵襲", "", ""],
    [11, "自分への問いかけ", "", ""],
    [12, "脈アリ？", "", ""],
    [13, "ブルームローズの館", "", ""],
    [14, "ゾルダードの優しさ", "", ""],
    [15, "エリナリーゼ", "", ""],
    [16, "朗報", "", ""],
    [17, "ラノア魔法大学のある街", "", ""],
    [18, "ザノバ再会", "", ""],
    [19, "高飛車", "", ""],
    [20, "学校生活", "", ""],
    [21, "荒くれ者", "", ""],
    [22, "優しいフィッツ", "", ""],
    [23, "フィッツの気持ち", "", ""],
    [24, "厳しいフィッツ", "", ""],
    [25, "シルフィとして", "", ""],
    [26, "人形制作", "", ""],
    [27, "命令", "", ""],
    [28, "内緒", "", ""],
    [29, "Clover -instrumental ver.-", "", ""],
    [30, "落胆", "", ""],
    [31, "リニアとプルセナ", "", ""],
    [32, "遭遇の予感", "", ""],
    [33, "バーディガーディ", "", ""],
    [34, "ナナホシの本音", "", ""],
]
links = ["https://vgmdb.net/album/132782"]

[3]
catalognumber = "TBR33253D-2"
date = "2024-07-17"
album = "無職転生II ～異世界行ったら本気だす～ Original Soundtrack 2 Special Edition"
tracks = [
    [1, "幸せな日々", "", ""],
    [2, "新居探索", "", ""],
    [3, "襲いかかる人形", "", ""],
    [4, "新婚", "", ""],
    [5, "ルディとシルフィ", "", ""],
    [6, "友人からの祝福", "", ""],
    [7, "ゼニスへの思い", "", ""],
    [8, "家族のぬくもり", "", ""],
    [9, "昔の自分", "", ""],
    [10, "魔法陣", "", ""],
    [11, "ツバサ", "", ""],
    [12, "ロキシーの優しさ", "", ""],
    [13, "世渡り上手", "", ""],
    [14, "ダンジョン", "", ""],
    [15, "転移遺跡", "", ""],
    [16, "ターニングポイント", "", ""],
    [17, "旅路", "", ""],
    [18, "決死の覚悟", "", ""],
    [19, "転移迷宮", "", ""],
    [20, "迷宮都市ラパン", "", ""],
    [21, "パウロ", "", ""],
    [22, "酒場", "", ""],
    [23, "為す術無し", "", ""],
    [24, "悲愴", "", ""],
    [25, "オン・ザ・フロントライン - Piano ver.", "", ""],
]
links = ["https://vgmdb.net/album/132783"]

[4]
catalognumber = ""
date = "2021-04-21"
album = "『無職転生 〜異世界行ったら本気だす〜』 オリジナル・サウンドトラック1"
tracks = [
    [1, "魔術の授業", "", ""],
    [2, "魔法が存在する世界で", "", ""],
    [3, "詠唱", "", ""],
    [4, "ルディの失態", "", ""],
    [5, "小さい家庭教師\"ロキシー\"", "", ""],
    [6, "無職転生", "", ""],
    [7, "まだ見ぬ世界", "", ""],
    [8, "ロキシーからの贈り物", "", ""],
    [9, "外には絶望", "", ""],
    [10, "ロキシー最後の授業", "", ""],
    [11, "師匠のお守り", "", ""],
    [12, "グレイラット家の日々", "", ""],
    [13, "友達", "", ""],
    [14, "思わぬ現実", "", ""],
    [15, "エリスの笑顔", "", ""],
    [16, "シルフィの涙", "", ""],
    [17, "ロキシーからの手紙", "", ""],
    [18, "オンリー(アコースティックVer.)", "", ""],
    [19, "パウロ VS ルディ", "", ""],
    [20, "ギレーヌと二人きり", "", ""],
    [21, "エリス怒る", "", ""],
    [22, "金でデレは買えない", "", ""],
    [23, "サウロス登場", "", ""],
    [24, "お願いにゃん", "", ""],
    [25, "ギレーヌの誘導", "", ""],
    [26, "剣術指導", "", ""],
    [27, "魔法を使わないダンス", "", ""],
    [28, "5年後の約束!", "", ""],
    [29, "ヒトガミの助言", "", ""],
    [30, "大切な仲間", "", ""],
]
links = ["https://vgmdb.net/album/117110"]

[5]
catalognumber = ""
date = "2023-09-25"
album = "『無職転生 ～異世界行ったら本気だす～』 第2期 オリジナル・サウンドトラック"
tracks = [
    [1, "無詠唱魔術", "", ""],
    [2, "アリエルの言葉", "", ""],
    [3, "凛として", "", ""],
    [4, "永遠なれ、アスラ王国", "", ""],
    [5, "姑息な鼠", "", ""],
    [6, "夢の中でも", "", ""],
    [7, "Critical The Situation", "", ""],
    [8, "冒険者稼業", "", ""],
    [9, "敵襲", "", ""],
    [10, "取り分", "", ""],
    [11, "カウンターアローとの時間", "", ""],
    [12, "依頼の準備", "", ""],
    [13, "自分への問いかけ", "", ""],
    [14, "脈アリ？", "", ""],
    [15, "ブルームローズの館", "", ""],
    [16, "ゾルダードの優しさ", "", ""],
    [17, "エリナリーゼ", "", ""],
    [18, "吟遊詩人", "", ""],
    [19, "朗報", "", ""],
    [20, "知りたい情報", "", ""],
    [21, "トラブル回避", "", ""],
    [22, "ラノア魔法大学のある街", "", ""],
    [23, "ラノア魔法大学について", "", ""],
    [24, "ザノバ再会", "", ""],
    [25, "優しいフィッツ", "", ""],
    [26, "フィッツの気持ち", "", ""],
    [27, "厳しいフィッツ", "", ""],
    [28, "シルフィとして", "", ""],
    [29, "アスラ王国第二王女", "", ""],
    [30, "内緒", "", ""],
    [31, "Clover -instrumental ver.-", "", ""],
    [32, "歓喜", "", ""],
    [33, "転移事件の真相", "", ""],
    [34, "リニアとプルセナ", "", ""],
    [35, "バーディガーディ", "", ""],
    [36, "陽気な男", "", ""],
    [37, "人形生活のはじまり", "", ""],
    [38, "白い仮面", "", ""],
]
links = ["https://vgmdb.net/album/132779"]

[6]
catalognumber = "TBR31096D-2"
date = "2022-01-19"
album = "無職転生 ～異世界行ったら本気だす～ Original Soundtrack 2 Special Edition"
tracks = [
    [1, "心の奥底", "", ""],
    [2, "もう大丈夫", "", ""],
    [3, "格式ある家系", "", ""],
    [4, "計略", "", ""],
    [5, "目的", "", ""],
    [6, "したごころ", "", ""],
    [7, "陽気な日", "", ""],
    [8, "額の目", "", ""],
    [9, "知っていること", "", ""],
    [10, "たくらみ", "", ""],
    [11, "アジト", "", ""],
    [12, "虚無の世界", "", ""],
    [13, "アイシャ", "", ""],
    [14, "初めての海", "", ""],
    [15, "魔界大帝キシリカ・キシリス!?", "", ""],
    [16, "ギレーヌのこと", "", ""],
    [17, "信頼を得る為に", "", ""],
    [18, "ウェンポート", "", ""],
    [19, "密輸組織", "", ""],
    [20, "作戦会議", "", ""],
    [21, "笑顔の力", "", ""],
    [22, "快適な牢屋", "", ""],
    [23, "先輩と新入", "", ""],
    [24, "ドルディア族", "", ""],
    [25, "共闘", "", ""],
    [26, "再会", "", ""],
    [27, "冒険者", "", ""],
    [28, "慰め", "", ""],
    [29, "待ってる", "", ""],
    [30, "神聖な世界", "", ""],
    [31, "シーローン王宮", "", ""],
    [32, "秘密の作戦", "", ""],
    [33, "まさか!?", "", ""],
    [34, "旅人の唄 -EP17 Inst Ver.-", "", ""],
    [35, "ロキシーへの想い", "", ""],
    [36, "ザノバの力", "", ""],
    [37, "圧倒的力との遭遇", "", ""],
]
links = ["https://vgmdb.net/album/108264"]

[7]
catalognumber = "TBR31094D-2"
date = "2021-04-21"
album = "無職転生 ～異世界行ったら本気だす～ Original Soundtrack 1 Special Edition"
tracks = [
    [1, "魔術の授業", "", ""],
    [2, "魔法が存在する世界で", "", ""],
    [3, "詠唱", "", ""],
    [4, "ルディの失態", "", ""],
    [5, "小さい家庭教師\"ロキシー\"", "", ""],
    [6, "ロキシーの訓練", "", ""],
    [7, "無職転生", "", ""],
    [8, "5歳のお祝い", "", ""],
    [9, "ルディのナイスガイスキル", "", ""],
    [10, "まだ見ぬ世界", "", ""],
    [11, "ロキシーからの贈り物", "", ""],
    [12, "外には絶望", "", ""],
    [13, "ロキシー最後の授業", "", ""],
    [14, "師匠のお守り", "", ""],
    [15, "グレイラット家の日々", "", ""],
    [16, "友達", "", ""],
    [17, "思わぬ現実", "", ""],
    [18, "シルフに教える魔術", "", ""],
    [19, "シルフィの涙", "", ""],
    [20, "ロキシーからの手紙", "", ""],
    [21, "オンリー (アコースティックVer.)", "", ""],
    [22, "ギレーヌ登場", "", ""],
    [23, "パウロ VS ルディ", "", ""],
    [24, "ボレアス家", "", ""],
    [25, "エリス怒る", "", ""],
    [26, "金でデレは買えない", "", ""],
    [27, "サウロス登場", "", ""],
    [28, "ギレーヌの誘導", "", ""],
    [29, "剣術指導", "", ""],
    [30, "ボレアス邸の一日", "", ""],
    [31, "10歳の宴", "", ""],
    [32, "魔法を使わないダンス", "", ""],
    [33, "5年後の約束!", "", ""],
    [34, "ヒトガミの助言", "", ""],
    [35, "ルイジェルド", "", ""],
    [36, "ノコパラの陰謀", "", ""],
    [37, "旅人の唄 (アコースティックVer.)", "", ""],
]
links = ["https://vgmdb.net/album/108263"]

[8]
catalognumber = "THCA-60269"
date = "2021-12-22"
album = "TVアニメ『無職転生～異世界行ったら本気出す～』Theme Song Collection"
tracks = [
    [1, "旅人の唄", "", ""],
    [2, "目覚めの唄", "", ""],
    [3, "継承の唄", "", ""],
    [4, "祈りの唄", "", ""],
    [5, "遠くの子守の唄", "", ""],
    [6, "旅人の唄～帰郷～", "", ""],
    [7, "オンリー", "", ""],
    [8, "風と行く道", "", ""],
]
links = ["https://vgmdb.net/album/114953"]

[9]
catalognumber = ""
date = "2024-07-02"
album = "『無職転生 ～異世界行ったら本気だす～』 第2期 オリジナル・サウンドトラック2"
tracks = [
    [1, "幸せな日々", "", ""],
    [2, "新居探索", "", ""],
    [3, "襲いかかる人形", "", ""],
    [4, "新婚", "", ""],
    [5, "ルディとシルフィ", "", ""],
    [6, "友人からの祝福", "", ""],
    [7, "ゼニスへの思い", "", ""],
    [8, "家族のぬくもり", "", ""],
    [9, "昔の自分", "", ""],
    [10, "魔法陣", "", ""],
    [11, "ツバサ", "", ""],
    [12, "ロキシーの優しさ", "", ""],
    [13, "世渡り上手", "", ""],
    [14, "ダンジョン", "", ""],
    [15, "転移遺跡", "", ""],
    [16, "ターニングポイント", "", ""],
    [17, "旅路", "", ""],
    [18, "決死の覚悟", "", ""],
    [19, "転移迷宮", "", ""],
    [20, "迷宮都市ラパン", "", ""],
    [21, "パウロ", "", ""],
    [22, "酒場", "", ""],
    [23, "為す術無し", "", ""],
    [24, "悲愴", "", ""],
]
links = ["https://vgmdb.net/album/141120"]

[10]
catalognumber = "THCA-60295"
date = "2024-09-18"
album = "TVアニメ『無職転生Ⅱ ～異世界行ったら本気だす～』エンディングテーマコレクション"
tracks = [
    [1, "Clover", "", ""],
    [2, "ムスビメ", "", ""],
    [3, "花咲み", "", ""],
    [4, "守りたいもの", "", ""],
    [5, "ツバサ", "", ""],
    [6, "かげくらべの唄", "", ""],
]
links = ["https://vgmdb.net/album/142154"]
