[1]
catalognumber = "VTCL-35296"
date = "2019-01-30"
album = "気ままな天使たち×ハッピー・ハッピー・フレンズ / わたてん☆5"
tracks = [
    [1, "気ままな天使たち", "", ""],
    [2, "ハッピー・ハッピー・フレンズ", "", ""],
    [3, "気ままな天使たち -Instrumental-", "", ""],
    [4, "ハッピー・ハッピー・フレンズ -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/82216"]

[2]
catalognumber = "TGCS-11164"
date = "2019-04-24"
album = "私に天使が舞い降りた! キャラクターソングCD 02"
tracks = [
    [1, "GO! GO! GO!", "", ""],
    [2, "GO! GO! GO! -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/83286"]

[3]
catalognumber = ""
date = "2020-01-31"
album = "私に天使が舞い降りた! 7 特装版 付録ドラマCD"
tracks = [
    [1, "オープニング", "", ""],
    [2, "いつか本当に捕まりそうでシンパイ", "", ""],
    [3, "みゃーこってその犬?", "", ""],
    [4, "わたしの顔使ってもいいぞ", "", ""],
    [5, "もういつ死んでもいいわ", "", ""],
    [6, "味見してただけです", "", ""],
    [7, "エンディング", "", ""],
]
links = ["https://vgmdb.net/album/93041"]

[4]
catalognumber = "VTCL-60539"
date = "2020-11-25"
album = "デリシャス・スマイル! / わたてん☆5"
tracks = [
    [1, "デリシャス・スマイル!", "", ""],
    [2, "無限大ハピネス", "", ""],
    [3, "スイーツスイーツパーティー!", "", ""],
    [4, "スペシャルコーディネート", "", ""],
    [5, "スイーツランド・パラドックス", "", ""],
    [6, "みゃー姉!!", "", ""],
    [7, "参上!小悪魔エンジェル", "", ""],
    [8, "My canon", "", ""],
    [9, "いっしょにおててをつなごうね", "", ""],
    [10, "ディアマイフレンド", "", ""],
]
links = ["https://vgmdb.net/album/103945"]

[5]
catalognumber = "VTCL-60483"
date = "2019-02-27"
album = "「私に天使が舞い降りた!」キャラクターソングアルバム 天使のうたごえ"
tracks = [
    [1, "シュガーコート・ドリーム", "", ""],
    [2, "やっぱりみゃー姉なんばーわん", "", ""],
    [3, "アタシ♡カワイイ♡宣言!!!", "", ""],
    [4, "あかいろリトルリーダー", "", ""],
    [5, "とっておきのことば", "", ""],
    [6, "私に\"好き\"が舞い降りた", "", ""],
    [7, "シュガーコート・ドリーム -Instrumental-", "", ""],
    [8, "やっぱりみゃー姉なんばーわん -Instrumental-", "", ""],
    [9, "アタシ♡カワイイ♡宣言!!! -Instrumental-", "", ""],
    [10, "あかいろリトルリーダー -Instrumental-", "", ""],
    [11, "とっておきのことば -Instrumental-", "", ""],
    [12, "私に\"好き\"が舞い降りた -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/82935"]

[6]
catalognumber = ""
date = "2020-09-18"
album = "無限大ハピネス COMIC ver. / わたてん☆5"
tracks = [
    [1, "無限大ハピネス COMIC ver.", "", ""],
    [2, "無限大ハピネス COMIC ver. -Instrumental-", "", ""],
    [3, "おまけドラマ「インタビュー」", "", ""],
]
links = ["https://vgmdb.net/album/103452"]

[7]
catalognumber = "TGCS-11162"
date = "2019-03-27"
album = "私に天使が舞い降りた! キャラクターソングCD 01"
tracks = [
    [1, "晴れルヤ!", "", ""],
    [2, "晴れルヤ! -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/83285"]

[8]
catalognumber = ""
date = "2022-08-24"
album = "私に天使が舞い降りた! CHARACTER SONG & RADIO CD"
tracks = [
    [1, "晴れルヤ!", "", ""],
    [2, "GO! GO! GO!", "", ""],
    [3, "(data track)", "", ""],
]
links = ["https://vgmdb.net/album/120020"]

[9]
catalognumber = "VTZL-152"
date = "2019-01-30"
album = "気ままな天使たち×ハッピー・ハッピー・フレンズ / わたてん☆5 Disc 1 (CD) [VTCL-35296]"
tracks = [
    [1, "気ままな天使たち", "", ""],
    [2, "ハッピー・ハッピー・フレンズ", "", ""],
    [3, "気ままな天使たち -Instrumental-", "", ""],
    [4, "ハッピー・ハッピー・フレンズ -Instrumental-", "", ""],
]
links = ["https://vgmdb.net/album/82215"]

[10]
catalognumber = "VTZL-152"
date = "2019-01-30"
album = "気ままな天使たち×ハッピー・ハッピー・フレンズ / わたてん☆5 Disc 2 (DVD) [VTBY-158]"
tracks = [
    [1, "気ままな天使たち (Music Clip)", "", ""],
    [2, "気ままな天使たち (Making Movie)", "", ""],
]
links = ["https://vgmdb.net/album/82215"]

[11]
catalognumber = "VTCL-60494"
date = "2019-04-03"
album = "TVアニメ「私に天使が舞い降りた!」サウンドコレクション"
tracks = [
    [1, "爽やかなる決意", "", ""],
    [2, "私に天使が舞い降りた! I", "", ""],
    [3, "私に天使が舞い降りた! II", "", ""],
    [4, "みやこエキサイト", "", ""],
    [5, "幸せな一日", "", ""],
    [6, "もにょっとした気持ち", "", ""],
    [7, "いっくぞー!", "", ""],
    [8, "応援があれば頑張れる!", "", ""],
    [9, "苦労して手に入れたお菓子", "", ""],
    [10, "幸せな時間", "", ""],
    [11, "小悪魔", "", ""],
    [12, "サイキョーにカワイイ", "", ""],
    [13, "トラブルメーカー", "", ""],
    [14, "想う気持ち", "", ""],
    [15, "焦り", "", ""],
    [16, "友達詐欺", "", ""],
    [17, "どんより", "", ""],
    [18, "ドタバタパニック", "", ""],
    [19, "勝負 II", "", ""],
    [20, "夢うつつ", "", ""],
    [21, "勝負 I", "", ""],
    [22, "無駄骨徒労で報われず", "", ""],
    [23, "信頼 I", "", ""],
    [24, "何でも遊び心", "", ""],
    [25, "夢は叶えるもの", "", ""],
    [26, "信頼 II", "", ""],
    [27, "憧れの人", "", ""],
    [28, "悲しみ", "", ""],
    [29, "優しさを感じて", "", ""],
    [30, "右往左往", "", ""],
    [31, "ホッコリタイム", "", ""],
    [32, "一段落", "", ""],
    [33, "ナイスアイデア", "", ""],
    [34, "疲れた...", "", ""],
    [35, "回想", "", ""],
    [36, "なんてこった", "", ""],
    [37, "ご満悦", "", ""],
    [38, "Eye Catch", "", ""],
    [39, "神殿にて", "", ""],
    [40, "天使の眼差し Prologue", "", ""],
    [41, "私を呼ぶ声", "", ""],
    [42, "ようこそ天使の国へ", "", ""],
    [43, "恋するお菓子屋さん", "", ""],
    [44, "あの子に会いたい", "", ""],
    [45, "決意", "", ""],
    [46, "受け継ぐ心", "", ""],
    [47, "天使の眼差し Epilogue", "", ""],
]
links = ["https://vgmdb.net/album/83724"]

[12]
catalognumber = "VTZL-213"
date = "2022-10-12"
album = "私に天使が舞い降りた! プレシャス・フレンズ サウンド・コレクション [初回限定盤] Original Soundtrack, Vocal"
tracks = [
    [1, "プレシャス・フレンズ!", "", ""],
    [2, "星野家の日常", "", ""],
    [3, "髪飾り I", "", ""],
    [4, "お母さんズ", "", ""],
    [5, "旅行に行こう!", "", ""],
    [6, "おばあちゃんの家", "", ""],
    [7, "長瀞旅行", "", ""],
    [8, "ご飯です!", "", ""],
    [9, "お菓子作り", "", ""],
    [10, "桜の気持ち", "", ""],
    [11, "長瀞温泉交流", "", ""],
    [12, "髪飾り II", "", ""],
    [13, "観光!", "", ""],
    [14, "花とみやこ I", "", ""],
    [15, "夕暮れの長瀞", "", ""],
    [16, "こよりとかのん", "", ""],
    [17, "ノアとひなた", "", ""],
    [18, "明かりに照らされて", "", ""],
    [19, "無くなった髪飾り", "", ""],
    [20, "大切な気持ち", "", ""],
    [21, "一件落着", "", ""],
    [22, "花とみやこ II", "", ""],
    [23, "おばあちゃんになっても一緒", "", ""],
    [24, "ずっと…ずっと…", "", ""],
    [25, "みんなでいただきます!", "", ""],
    [26, "かえりみち", "", ""],
    [27, "Q.E.D.", "", ""],
]
links = ["https://vgmdb.net/album/122040"]

[13]
catalognumber = "VTZL-213"
date = "2022-10-12"
album = "私に天使が舞い降りた! プレシャス・フレンズ サウンド・コレクション [初回限定盤] Vocal, Video"
tracks = [
    [1, "プレシャス・フレンズ! (ミュージックビデオ)", "", ""],
    [2, "わたてん☆5スケッチ映像", "", ""],
]
links = ["https://vgmdb.net/album/122040"]

[14]
catalognumber = "VTCL-60566"
date = "2022-10-12"
album = "私に天使が舞い降りた! プレシャス・フレンズ サウンド・コレクション"
tracks = [
    [1, "プレシャス・フレンズ!", "", ""],
    [2, "星野家の日常", "", ""],
    [3, "髪飾り I", "", ""],
    [4, "お母さんズ", "", ""],
    [5, "旅行に行こう!", "", ""],
    [6, "おばあちゃんの家", "", ""],
    [7, "長瀞旅行", "", ""],
    [8, "ご飯です!", "", ""],
    [9, "お菓子作り", "", ""],
    [10, "桜の気持ち", "", ""],
    [11, "長瀞温泉交流", "", ""],
    [12, "髪飾り II", "", ""],
    [13, "観光!", "", ""],
    [14, "花とみやこ I", "", ""],
    [15, "夕暮れの長瀞", "", ""],
    [16, "こよりとかのん", "", ""],
    [17, "ノアとひなた", "", ""],
    [18, "明かりに照らされて", "", ""],
    [19, "無くなった髪飾り", "", ""],
    [20, "大切な気持ち", "", ""],
    [21, "一件落着", "", ""],
    [22, "花とみやこ II", "", ""],
    [23, "おばあちゃんになっても一緒", "", ""],
    [24, "ずっと…ずっと…", "", ""],
    [25, "みんなでいただきます!", "", ""],
    [26, "かえりみち", "", ""],
    [27, "Q.E.D.", "", ""],
]
links = ["https://vgmdb.net/album/122039"]

[15]
catalognumber = "VTZL-179"
date = "2020-11-25"
album = "デリシャス・スマイル! / わたてん☆5 [初回限定盤] Vocal"
tracks = [
    [1, "デリシャス・スマイル!", "", ""],
    [2, "無限大ハピネス", "", ""],
    [3, "スイーツスイーツパーティー!", "", ""],
    [4, "スペシャルコーディネート", "", ""],
    [5, "スイーツランド・パラドックス", "", ""],
    [6, "みゃー姉!!", "", ""],
    [7, "参上!小悪魔エンジェル", "", ""],
    [8, "My canon", "", ""],
    [9, "いっしょにおててをつなごうね", "", ""],
    [10, "ディアマイフレンド", "", ""],
]
links = ["https://vgmdb.net/album/103946"]

[16]
catalognumber = "VTZL-179"
date = "2020-11-25"
album = "デリシャス・スマイル! / わたてん☆5 [初回限定盤] Vocal, Video"
tracks = [
    [1, "デリシャス・スマイル! (Music Clip)", "", ""],
    [2, "デリシャス・スマイル! (Making Movie)", "", ""],
]
links = ["https://vgmdb.net/album/103946"]

[17]
catalognumber = "TGCS-11166"
date = "2019-05-24"
album = "私に天使が舞い降りた! スペシャルラジオCD"
tracks = [
    [1, "(no title available)", "", ""],
]
links = ["https://vgmdb.net/album/83287"]
