[eb06aab012047d05f03997fae5b3a5c3]
catalognumber = ""
date = "2014-01-01"
album = "离乡"
tracks = [
    [1, "离乡", "ilem/洛天依Official", 1],
]
links = ["https://music.163.com/#/album?id=154778629"]

[7f2ea89c180427acf0bd013e914522f4]
catalognumber = ""
date = "2014-01-01"
album = "怪物大暴走"
tracks = [
    [1, "怪物大暴走", "洛天依Official/言和/ilem", 1],
]
links = ["https://music.163.com/#/album?id=154778639"]

[35573bc6a437676d91df39a8e59ddcf0]
catalognumber = ""
date = "2014-01-01"
album = "深夜诗人"
tracks = [
    [13, "深夜诗人", "洛天依Official/言和/ilem", 1],
]
links = ["https://music.163.com/#/album?id=154800348"]

[7e2bec6e56ab41da4e0e8c98d7236b46]
catalognumber = ""
date = "2014-01-01"
album = "葬歌"
tracks = [
    [1, "葬歌", "洛天依Official/言和/ilem", 0],
]
links = ["https://music.163.com/#/album?id=154788648"]

[9685766359de19535a7ea762ba546c4f]
catalognumber = ""
date = "2014-12-30"
album = "ilem2014年作品合集"
tracks = [
    [1, "一样", "ilem/洛天依Official", 1],
    [2, "最忆江南", "ilem/洛天依Official/言和", 1],
    [3, "离乡", "ilem/洛天依Official", 1],
    [4, "言氏战鼓", "ilem/言和", 1],
    [5, "孤高光棍歌", "ilem/洛天依Official/言和", 1],
    [6, "弗拉门戈之星", "ilem/洛天依Official", 1],
    [7, "神经病之歌", "ilem/洛天依Official/言和", 1],
]
links = ["https://music.163.com/#/album?id=381136937"]

[ef332c2f625e0012d6f5e8c3091bde2e]
catalognumber = ""
date = "2015-01-01"
album = "僵尸舞"
tracks = [
    [1, "僵尸舞", "洛天依Official/言和/ilem", 1],
]
links = ["https://music.163.com/#/album?id=154778564"]

[02a5b6496980e08ea4eed7bf3aa49ec7]
catalognumber = ""
date = "2015-07-22"
album = "暗黑五部曲"
tracks = [
    [1, "今天没吃药", "ilem/洛天依Official/言和", 0],
    [2, "僵尸舞", "ilem/洛天依Official/言和", 1],
    [3, "怪物大暴走", "ilem/洛天依Official/言和", 1],
    [4, "阴阳先生", "ilem/洛天依Official/言和", 0],
    [5, "葬歌", "ilem/洛天依Official/言和", 0],
]
links = ["https://music.163.com/#/album?id=381136023"]

[ce7c22d7dab90ad75446cd209e7b5b78]
catalognumber = ""
date = "2015-12-24"
album = "ilem2015年作品合集"
tracks = [
    [1, "葛平之歌", "ilem", 1],
    [2, "Song For You", "ilem/言和", 1],
    [3, "星雨之夜", "ilem/心华", 1],
    [4, "花儿纳吉", "ilem/言和/洛天依Official", 1],
    [5, "今天的诗", "ilem", 1],
    [6, "大时代", "ilem/心华/乐正绫", 1],
    [7, "写给我第一个喜欢的女孩的歌", "ilem/洛天依Official", 2],
]
links = ["https://music.163.com/#/album?id=381136945"]

[627e38681ac53c2c9bef7983c20079ba]
catalognumber = ""
date = "2016-01-07"
album = "普通DISCO"
tracks = [
    [1, "普通DISCO", "ilem/洛天依Official/言和", 0],
]
links = ["https://music.163.com/#/album?id=3111187"]

[97633fd49386d01e09156ed39fcb7233]
catalognumber = ""
date = "2016-02-04"
album = "星雨之夜"
tracks = [
    [1, "星雨之夜", "心华/ilem", 1],
]
links = ["https://music.163.com/#/album?id=154789578"]

[673e990512ba70a8493f996f70311f2d]
catalognumber = ""
date = "2016-12-05"
album = "ilem2016年作品合集"
tracks = [
    [1, "一人行者", "ilem/心华", 1],
    [3, "牧星者", "ilem/星尘", 1],
    [4, "尖叫鸭子", "ilem", 1],
    [5, "最美的夏天", "ilem/洛天依Official", 1],
    [6, "埃及方块", "ilem/洛天依Official/言舞", 1],
    [7, "深夜诗人", "ilem/洛天依Official/言和", 1],
]
links = ["https://music.163.com/#/album?id=381136982"]

[0ab0ffdcddda61f3854ab3bd66296ea9]
catalognumber = ""
date = "2017-06-15"
album = "达拉崩吧"
tracks = [
    [1, "达拉崩吧", "ilem/洛天依Official/言和", 1],
]
links = ["https://music.163.com/#/album?id=36875139"]

[8fccae3869db18007d6f0310b564e256]
catalognumber = ""
date = "2018-12-29"
album = "ilem2017-2018年作品合集"
tracks = [
    [1, "达拉崩吧", "ilem/洛天依Official/言和", 1],
    [2, "上下上下", "ilem/洛天依Official", 1],
    [3, "车", "ilem/洛天依Official", 1],
    [4, "欧菲香", "ilem/洛天依Official/言和", 1],
    [5, "9Bang15便士", "ilem/洛天依Official", 1],
    [6, "O", "ilem/洛天依Official", 1],
    [7, "傲娇系男孩的告白日", "ilem/乐正绫", 1],
    [8, "鸽子", "ilem/洛天依Official/言和", 1],
]
links = ["https://music.163.com/#/album?id=381139948"]

[df03d36cc47febbeb3872c9cbf8f3d8f]
catalognumber = ""
date = "2019-02-24"
album = "2:3"
tracks = [
    [1, "勾指起誓", "洛天依Official/ilem", 2],
    [1, "勾指起誓 (甜蜜版)", "欣小萌/ilem", 1],
    [2, "夜间出租车", "洛天依Official/ilem", 1],
    [2, "夜间出租车 (复古Disco版)", "陈乐一/ilem", 1],
    [3, "大氿歌", "ilem/洛天依Official", 1],
    [3, "大氿歌 (国风版)", "戴荃/ilem", 1],
    [4, "得过且过的勇者", "ilem/洛天依Official/言和", 1],
    [4, "得过且过的勇者 (Funk版)", "三无Marblue", 1],
    [5, "写给我家狗的歌 (Vocaloid版)", "ilem/洛天依Official", 1],
    [5, "写给我家狗的歌 (抒情摇滚版)", "小可儿", 1],
    [6, "威海", "乐正龙牙/ilem", 1],
    [6, "威海 (流行R&B版)", "萧忆情Alex", 1],
    [7, "售楼小姐", "ilem/洛天依Official", 1],
    [7, "售楼小姐 (现场版)", "上海彩虹室内合唱团", 1],
    [8, "勾指起誓 (Vocaloid版伴奏)", "洛天依Official/ilem", 1],
    [8, "勾指起誓 (甜美版伴奏)", "欣小萌/ilem", 1],
    [9, "夜间出租车 (Vocaloid版伴奏)", "ilem/洛天依Official", 1],
    [9, "夜间出租车 (复古Disco版伴奏)", "陈乐一/ilem", 1],
    [10, "大氿歌 (Vocaloid版伴奏)", "ilem/洛天依Official", 1],
    [10, "大氿歌 (国风版伴奏)", "戴荃/ilem", 1],
    [11, "得过且过的勇者 (Vocaloid版伴奏)", "ilem/洛天依Official/言和", 1],
    [11, "得过且过的勇者 (Funk版伴奏)", "三无Marblue", 1],
    [12, "写给我家狗的歌 (Vocaloid版伴奏)", "ilem/洛天依Official", 1],
    [12, "写给我家狗的歌 (抒情摇滚版伴奏)", "小可儿", 1],
    [13, "威海 (Vocaloid版伴奏)", "乐正龙牙", 1],
    [13, "威海 (流行R&B版伴奏)", "萧忆情Alex", 1],
    [14, "售楼小姐 (Vocaloid版伴奏)", "ilem/洛天依Official", 1],
]
links = ["https://music.163.com/#/album?id=75017206"]

[22b538993310a97aeea70bcd34174390]
catalognumber = ""
date = "2022-01-15"
album = "烟火赴新年"
tracks = [
    [1, "烟火赴新年", "咻咻满/Bo Peep/ilem", 1],
    [2, "烟火赴新年（伴奏）", "咻咻满/Bo Peep/ilem", 1],
]
links = ["https://music.163.com/#/album?id=138745465"]

[4f1985bbcaeac14d8cf32b2cc688b649]
catalognumber = ""
date = "2023-08-28"
album = "ilem2019-2023年作品合集"
tracks = [
    [1, "保卫罗德岛", "ilem/洛天依Official", 1],
    [2, "上山岗", "ilem/洛天依Official", 1],
    [3, "看星星", "ilem/星尘/徵羽摩柯", 1],
    [4, "苍蝇", "ilem/赤羽", 1],
    [5, "泥汤", "ilem/洛天依Official", 1],
    [6, "梦良衣", "ilem/赤羽", 1],
    [7, "我没有歌能给你听", "ilem/洛天依Official", 1],
    [8, "白鸟过河滩", "ilem/洛天依Official", 1],
    [9, "大吉", "ilem/洛天依Official", 1],
    [10, "开心高兴歌", "ilem/洛天依Official", 1],
    [11, "四风判词", "ilem/洛天依Official", 1],
]
links = ["https://music.163.com/#/album?id=381140016"]

[522cdb0096983c6b3342df74c16ded82]
catalognumber = ""
date = "2023-08-31"
album = "四风判词"
tracks = [
    [1, "四风判词", "ilem", 1],
    [2, "四风判词 (伴奏)", "ilem", 1],
]
links = ["https://music.163.com/#/album?id=173768531"]

[5f91662ec8dfc3044c89f14d49bee431]
catalognumber = ""
date = "2024-01-11"
album = "白鸟过河滩"
tracks = [
    [1, "白鸟过河滩", "ilem", 1],
    [2, "白鸟过河滩 (伴奏)", "ilem", 1],
]
links = ["https://music.163.com/#/album?id=182737853"]

[ffbe7184ff3ab4e9b8984e7274f7b19f]
catalognumber = ""
date = "2024-01-26"
album = "小孩小孩"
tracks = [
    [1, "小孩小孩", "ilem", 0],
    [2, "小孩小孩 (伴奏)", "ilem", 0],
]
links = ["https://music.163.com/#/album?id=183597328"]

[0eee953a63cf36189c97d64d0571d9f8]
catalognumber = ""
date = "2024-02-04"
album = "来春打马"
tracks = [
    [1, "来春打马", "ilem", 0],
    [2, "来春打马 (伴奏)", "ilem", 0],
]
links = ["https://music.163.com/#/album?id=184828092"]

[9e9cd159cbf89bd9143dc7a10e65a088]
catalognumber = ""
date = "2025-06-19"
album = "脑壳疼"
tracks = [
    [0, "脑壳疼", "洛天依/ilem", 1],
]
links = ["https://music.163.com/#/album?id=275613949"]

[c2d7afa0d057d209e92eb28b8d6450f3]
catalognumber = ""
date = "2026-04-24"
album = "告死鸟"
tracks = [
    [1, "告死鸟", "ilem", 0],
    [2, "告死鸟 (伴奏)", "ilem", 0],
]
links = ["https://music.163.com/#/album?id=372235821"]

[03cb0122ab8e0830381e22619f8589d4]
catalognumber = ""
date = "2026-06-28"
album = "Old Sad Song"
tracks = [
    [1, "Old Sad Song", "ilem", 1],
    [2, "老丧歌 伴奏", "ilem", 1],
]
links = ["https://music.163.com/#/album?id=383622005"]
