[72ca2f5034ae4a440e75f3e3a05e420c]
catalognumber = ""
date = "2006-12-31"
album = "しあわせちびっこせいかつ。"
tracks = [
    [1, "しあわせちびっこせいかつ。", "とも", 0],
    [2, "しあわせちびっこせいかつ。（off vocal）", "task", 0],
]
links = ["https://www.dojin-music.info/cd/1229"]

[5c9c27b9aa15c0873d49eb2065529563]
catalognumber = "2DIM-0002"
date = "2007-08-17"
album = "ﾄﾞｷﾄﾞｷ☆いもうとﾊｧﾄ"
tracks = [
    [1, "ﾄﾞｷﾄﾞｷ☆いもうとﾊｧﾄ", "とも", 0],
    [2, "ﾄﾞｷﾄﾞｷ☆いもうとﾊｧﾄ（off vocal）", "ガイドライナー108", 0],
]
links = ["https://www.dojin-music.info/cd/1228", "https://beta.musicbrainz.org/release/628876e6-64e9-4d4e-a9aa-98c53742fabd"]

[44753dc368344334812574bf73202714]
catalognumber = ""
date = "2007-12-31"
album = "うさみみショートケーキ"
tracks = [
    [1, "うさみみショートケーキ", "斎藤桃子", 0],
    [2, "うさみみショートケーキ（pico-mimi rmx）", "斎藤桃子", 0],
    [3, "うさみみショートケーキ（off vocal）", "task", 0],
]
links = ["https://www.dojin-music.info/cd/1225"]

[ea8f0a07cb159db1e436cb93756fcca5]
catalognumber = ""
date = "2008-06-29"
album = "うさみみショートケーキ -みくみくばーじょん-"
tracks = []
links = ["https://www.dojin-music.info/cd/1227"]

[73a24598b2520de5988caa91b73f6180]
catalognumber = ""
date = "2008-08-16"
album = "USB!!! -うさみみ すぅい〜と ばに〜がぁる-"
tracks = [
    [1, "USB!!! -うさみみ すぅい〜と ばに〜がぁる-", "斎藤桃子", 0],
    [2, "きらきらびより", "斎藤桃子", 0],
    [3, "USB!!! -うさみみ すぅい〜と ばに〜がぁる- (your turn)", "task", 0],
    [4, "USB!!! -うさみみ すぅい〜と ばに〜がぁる- (Instrumental)", "task", 0],
    [5, "きらきらびより (your turn)", "task", 0],
    [6, "きらきらびより (Instrumental)", "task", 0],
]
links = ["https://www.dojin-music.info/cd/1226"]

[627bd023732d5de4686ced2778561fed]
catalognumber = ""
date = "2008-12-29"
album = "どきどき！たまタン×はろぅわーるど☆"
tracks = [
    [1, "どきどき！たまタン", "斎藤桃子", 0],
    [2, "はろぅわーるど☆", "斎藤桃子", 0],
    [3, "うさみみショートケーキ Chiffon Cake style", "task Remix:Bong-G", 0],
    [4, "USB!!! -うさみみ すぅい〜と ばに〜がぁる- Hi-Speeeed 2.0 style", "task Remix:Bong-G", 0],
    [5, "うさみみショートケーキ", "斎藤桃子", 0],
    [6, "どきどき！たまタン Off Vocal", "", 0],
    [7, "どきどき！たまタン Instrumental", "", 0],
    [8, "はろぅわーるど☆ Off Vocal", "task", 0],
    [9, "はろぅわーるど☆ Instrumental", "task", 0],
]
links = ["https://www.dojin-music.info/cd/1815"]

[3a95a540f8af3aaef3aed2f8df48abeb]
catalognumber = ""
date = "2009-05-05"
album = "しあわせちびっこせいかつ。 -りにゅ〜ある-"
tracks = []
links = ["https://www.dojin-music.info/cd/1816"]

[bf7ac86f27cc4d638725ed501335b74e]
catalognumber = ""
date = "2009-08-15"
album = "ハッピー！スマイル☆たまタン"
tracks = [
    [1, "ハッピー！スマイル☆たまタン", "斎藤桃子", 0],
    [2, "きらきらびより -すたーらいと☆りみっくす-", "斎藤桃子", 0],
    [3, "ハートのリズム(Short Version)", "斎藤桃子", 0],
    [4, "ハッピー！スマイル☆たまタン(off vocal)", "task", 0],
]
links = ["https://www.dojin-music.info/cd/2032"]

[d655520b3e03b935a71dd84c99edd0c1]
catalognumber = ""
date = "2009-12-30"
album = "parade"
tracks = [
    [1, "Introduction", "声：下田麻美", 0],
    [2, "レモンのきもち。", "miko（藤咲かりん）", 0],
    [3, "ありがと、あんパン♪", "茶太", 0],
    [4, "Plastic＊girl", "野宮あゆみ", 0],
    [5, "受信BOXはLOVE?メールMAX!!!", "めらみぽっぷ", 0],
    [6, "Sweet tale", "まめこ", 0],
    [7, "parade", "茶太 miko（藤咲かりん） めらみぽっぷ 野宮あゆみ まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/2345"]

[18591962c08f6449458b5c0787994d0f]
catalognumber = "2DIM-0011"
date = "2010-08-14"
album = "sweet*time"
tracks = [
    [1, "しあわせちびっこせいかつ。", "茶太", 0],
    [2, "オトメチック☆恋愛モード", "miko（藤咲かりん）", 0],
    [3, "1st Kiss", "まめこ", 0],
    [4, "片想いスコープ", "めらみぽっぷ", 0],
]
links = ["https://www.dojin-music.info/cd/3054", "https://beta.musicbrainz.org/release/8d76edfc-e9ca-447f-bbbb-e2798eb01e5a"]

[603d3ddd03ad68ee62d58fc91c7f87a5]
catalognumber = ""
date = "2010-12-31"
album = "sweet*baske"
tracks = [
    [1, "ふわっふわ☆白うさぎ", "miko（藤咲かりん）", 0],
    [2, "Honey Pot -New Recording Version-", "まめこ", 0],
    [3, "受信BOXはLOVE♥メールMAX!!! -New Arrange Version-", "めらみぽっぷ", 0],
    [4, "Minty", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/5744"]

[4c8541d8284f763997b3188a4abf0fd5]
catalognumber = ""
date = "2011-08-13"
album = "Dear You"
tracks = [
    [1, "Dear You", "まめこ", 0],
    [2, "空色の恋", "ひなうさ", 0],
    [3, "Dear You (Instrumental)", "", 0],
    [4, "空色の恋 (Instrumental)", "", 0],
]
links = ["https://www.dojin-music.info/cd/5743"]

[fd3ad808c22098f232b122c43469f5fb]
catalognumber = ""
date = "2011-12-31"
album = "Colorpop"
tracks = [
    [1, "ふぁーすと♡ラブ", "茶太", 0],
    [2, "ハッピーオレンジサンシャイン★", "miko（藤咲かりん）", 0],
    [3, "ATTACK!!", "ななひら まめこ", 0],
    [4, "STARTER☆", "めらみぽっぷ", 0],
]
links = ["https://www.dojin-music.info/cd/5741", "https://beta.musicbrainz.org/release/fde4cba1-0a6a-4c03-ac9a-5c67881d832c"]

[3e1d8d6e8385c5b0d5b32d5f19f2beaa]
catalognumber = ""
date = "2012-08-11"
album = "Colorpop 2"
tracks = [
    [1, "課金厨のうた", "ななひら", 0],
    [2, "もっとChu！っと！", "りこ。", 0],
    [3, "君への想い", "ひなうさ", 0],
]
links = ["https://www.dojin-music.info/cd/5740", "https://beta.musicbrainz.org/release/b5d43df3-7895-4823-bd86-83a70652aba5"]

[0497a978b4d5ac8f4062c922c7443707]
catalognumber = ""
date = "2012-12-31"
album = "Drivin' Life!"
tracks = [
    [1, "Drivin' Life!", "仲村芽衣子", 0],
    [2, "Drivin' Life! (Instrumental)", "", 0],
]
links = ["https://www.dojin-music.info/cd/5745"]

[0df99a3acc17b145d37b2ae550d3a7a0]
catalognumber = ""
date = "2013-12-31"
album = "Colorpop 3"
tracks = [
    [1, "弱虫プリンセス", "miko（藤咲かりん）", 0],
    [2, "どんな逆境でも女の子は決して諦めないことを今ここに改めて宣言してみた。", "なゆ", 0],
    [3, "ももいろハート", "ななひら", 0],
    [4, "スノウ・ドール", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/5742", "https://beta.musicbrainz.org/release/a1cd1ffe-9813-40b6-89d5-98cf2f25b0c0"]

[02da7d26fdc1b50ddec1d86185daadf0]
catalognumber = ""
date = "2015-12-31"
album = "PRISM"
tracks = [
    [1, "とっておきの魔法", "ななひら", 0],
    [2, "弱虫プリンセス", "miko（藤咲かりん）", 0],
    [3, "シキンキョリ♥Lover", "ななひら", 0],
    [4, "ふぁーすと♥ラブ", "茶太", 0],
    [5, "素敵なはにぃ・たいむ！", "ココ", 0],
    [6, "ねぇ誓って！お姫様だけって♥", "大瀬良あい", 0],
    [7, "フライングキャッチャー", "仲村芽衣子", 0],
    [8, "世界でイチバン！", "ななひら ひなうさ", 0],
    [9, "MiRai SKetch", "仲村芽衣子", 0],
    [10, "君への想い", "ひなうさ", 0],
    [11, "1st Kiss", "まめこ", 0],
    [12, "merry-melody", "ななひら りこ。", 0],
    [13, "Cherry Stars", "まめこ", 0],
    [14, "課金厨のうた -More Charin Ver.-", "ななひら", 0],
    [15, "ストロベリィ★イグニッション(Special Version)", "SHAKING PINK", 0],
    [16, "どんな逆境でも女の子は決して諦めないことを 今ここに改めて宣言してみた。", "なゆ", 0],
    [17, "冬のキセキ", "miko（藤咲かりん）", 0],
    [18, "parade", "茶太 miko（藤咲かりん） めらみぽっぷ 野宮あゆみ まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/5739", "https://beta.musicbrainz.org/release/af549e72-6bc6-4544-93a4-de55734b93d0"]

[d0e3f7c2ae588829fbb6ffa96d38f2b6]
catalognumber = ""
date = "2017-08-11"
album = "秋M3か冬コミで大型アルバムをリリースするまでの間を繋ぐ前フリCD"
tracks = [
    [1, "乙女チック☆恋愛モード(前フリCDSpVer)", "miko（藤咲かりん）", 0],
    [2, "受信BoxはLoveメールMAX!!!(前フリCDSpVer)", "めらみぽっぷ", 0],
]
links = ["https://www.dojin-music.info/cd/22921"]
