[20e00cfba8323c2058c64209c677696e]
catalognumber = ""
date = ""
album = "おっさんに火をつけろ"
tracks = [
    [1, "おっさんに火をつけろ", "ぷらいむまりぃ", 1],
    [2, "恋の消防車", "ぷらいむまりぃ", 1],
]
links = ["https://www.last.fm/music/%E3%81%B7%E3%82%89%E3%81%84%E3%82%80%E3%81%BE%E3%82%8A%E3%81%83/%E3%81%8A%E3%81%A3%E3%81%95%E3%82%93%E3%81%AB%E7%81%AB%E3%82%92%E3%81%A4%E3%81%91%E3%82%8D"]

[296db0f65d41eb6909e1618433c3fc29]
catalognumber = ""
date = "2009-05-05"
album = "戦え！！！アイドロイド"
tracks = [
    [1, "戦え！！！アイドロイド", "33.turbo", 1],
    [2, "nano.", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/346e9047-eb2f-408b-962b-96dbde61ba5d"]

[79f105e8c4f3881bb85ece65c84839dd]
catalognumber = ""
date = "2009-10-11"
album = "ニャン☆パラ"
tracks = [
    [1, "ねこさんといっしょ！～hyper 園児′n version～", "33.turbo", 1],
    [2, "ニャン☆パラ", "33.turbo", 1],
    [3, "まいまいダーリン", "33.turbo", 1],
    [4, "ネコゼット", "33.turbo", 1],
    [5, "ねこさんといっしょ！～sasami version～", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/0f863524-337c-43a4-8f88-d70090980e35", "https://www.dojin-music.info/cd/2721"]

[d1d580644a7384d13c32c01ca55f2945]
catalognumber = ""
date = "2010-05-05"
album = "放課後ミックスジュース"
tracks = [
    [1, "ギー太に首ったけ", "33.turbo", 1],
    [2, "ふわふわ時間", "33.turbo", 1],
    [3, "Don't Say“lazy”", "33.turbo", 1],
    [4, "UNTN～hyper 園児′n Version～", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/363d1526-b71b-49fb-9778-c162793cbdcd", "https://www.dojin-music.info/cd/2963"]

[75744e0d58e545f6cc297dc40da83483]
catalognumber = ""
date = "2010-10-31"
album = "イモート☆アラモード"
tracks = [
    [1, "†邪気×sis†", "33.turbo", 1],
    [2, "うちのお兄ちゃんが鈍感でこまる", "33.turbo", 1],
    [3, "ずっと、妹", "33.turbo", 1],
    [4, "妹道", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/9723abd9-ff35-4e61-aaa6-ce148f7ab9c7", "https://www.dojin-music.info/cd/7537"]

[3f386983162b353e667334dbc7d2e9d9]
catalognumber = ""
date = "2011-01-05"
album = "ホイップライフ"
tracks = [
    [1, "おげんき☆電気", "33.turbo", 1],
    [2, "恋の送電線", "33.turbo", 1],
    [3, "愛の買占め", "33.turbo", 1],
    [4, "ぼーなすとらっく　おげんき☆電気　TranceCoreMix", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/374fb12f-6da8-4ff1-b8c0-e0f71c484df1", "https://www.dojin-music.info/cd/3385"]

[716a07f4c3965c1ea9fb7a989e522a21]
catalognumber = ""
date = "2011-10-30"
album = "おとチャ"
tracks = [
    [1, "Uta-Oh", "33.turbo", 2],
    [2, "聖☆幼女", "33.turbo", 1],
    [3, "Sleeping Cutie", "33.turbo", 1],
    [4, "Micro☆Miracle", "33.turbo", 1],
    [5, "???", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/3aac558f-e2b8-4729-bf4b-ba8bf4cb1ff3"]

[92cd301c03b0753e11ed1ffa2a97f784]
catalognumber = ""
date = "2011-10-30"
album = "おとチャ"
tracks = []
links = ["https://www.dojin-music.info/cd/7539"]

[7893d4d6c6e6457352ac79ade0d42b64]
catalognumber = ""
date = "2012-04-30"
album = "まにこれ!?"
tracks = [
    [1, "しびる★びる★びる", "33.turbo", 1],
    [2, "ストタイニーソ", "33.turbo", 1],
    [3, "南国育ちの娘さん", "33.turbo", 1],
    [4, "Atack", "33.turbo", 1],
    [5, "Shooting Star", "33.turbo", 1],
    [6, "なにこれ！？", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/020cf9b1-c23f-4e30-9ba3-88518910395e"]

[54f1f640baec3dc75975407bf5782b89]
catalognumber = ""
date = "2012-04-30"
album = "まにこれ！？"
tracks = []
links = ["https://www.dojin-music.info/cd/7538"]

[62bb7f3acd13385600ba03b263e27533]
catalognumber = ""
date = "2012-10-28"
album = "Dempa de Dance"
tracks = [
    [1, "ジュリアナ幼女", "33.turbo", 1],
    [2, "幼女☆音頭", "33.turbo", 1],
    [3, "man=MAN", "33.turbo", 1],
    [4, "neko・manma", "33.turbo", 1],
    [5, "ダンシン幼女", "33.turbo", 1],
    [6, "ジュリ穴♂┌(┌^o^)┐ホモォ...", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/50124265-6ebe-4052-a5a7-c3a85d8673bc", "https://www.dojin-music.info/cd/6639"]

[4706f3a0bfcfaf859b3de821b8dee39a]
catalognumber = ""
date = "2013-04-29"
album = "電波de保健体育"
tracks = [
    [1, "頭文字Dempa", "33.turbo", 1],
    [2, "萌え萌え体操第2", "33.turbo", 1],
    [3, "ブルマでないと!", "33.turbo", 1],
    [4, "ナ・イ・シ・ョのレッスン", "33.turbo", 1],
    [5, "幼女マッサージ", "33.turbo", 1],
    [6, "ガチムチパンツレスリング体操第1", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/d580ce0b-c474-4e8a-96d3-5135b206f446"]

[c4085f69d2fa8d61e10e8c88be76401c]
catalognumber = ""
date = "2013-04-29"
album = "電波de保健体育"
tracks = [
    [1, "頭文字Dempa", "幼女A", 1],
    [2, "萌え萌え体操第２", "幼女A", 1],
    [3, "ブルマでナイト", "幼女A", 0],
    [4, "ナ・イ・シ・ョのレッスン", "幼女A", 1],
    [5, "幼女マッサージ", "", 1],
]
links = ["https://www.dojin-music.info/cd/6638"]

[08960b9eab3161a214742214a845bac9]
catalognumber = ""
date = "2013-10-27"
album = "電波deグルメ"
tracks = [
    [1, "どさんこグルメ", "33.turbo", 1],
    [2, "マジカる☆カクテる☆トロピカる", "33.turbo", 1],
    [3, "焼き肉の館", "33.turbo", 1],
    [4, "どさんこグルメ(魂の叫びver.)", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/12fe3505-9a4a-4e23-a500-e33355a0b60f", "https://www.dojin-music.info/cd/6637"]

[a0bfceced153f21646307aceb26d757f]
catalognumber = ""
date = "2014-04-27"
album = "ガチムチかるた"
tracks = [
    [1, "[unnamed]", "33.turbo", 0],
    [2, "[unnamed]", "33.turbo", 0],
    [3, "[unnamed]", "33.turbo", 0],
    [4, "[unnamed]", "33.turbo", 0],
    [5, "[unnamed]", "33.turbo", 0],
    [6, "[unnamed]", "33.turbo", 0],
    [7, "[unnamed]", "33.turbo", 0],
    [8, "[unnamed]", "33.turbo", 0],
    [9, "[unnamed]", "33.turbo", 0],
    [10, "[unnamed]", "33.turbo", 0],
    [11, "[unnamed]", "33.turbo", 0],
    [12, "[unnamed]", "33.turbo", 0],
    [13, "[unnamed]", "33.turbo", 0],
    [14, "[unnamed]", "33.turbo", 0],
    [15, "[unnamed]", "33.turbo", 0],
    [16, "[unnamed]", "33.turbo", 0],
    [17, "[unnamed]", "33.turbo", 0],
    [18, "[unnamed]", "33.turbo", 0],
    [19, "[unnamed]", "33.turbo", 0],
    [20, "[unnamed]", "33.turbo", 0],
    [21, "[unnamed]", "33.turbo", 0],
    [22, "[unnamed]", "33.turbo", 0],
    [23, "[unnamed]", "33.turbo", 0],
    [24, "[unnamed]", "33.turbo", 0],
    [25, "[unnamed]", "33.turbo", 0],
    [26, "[unnamed]", "33.turbo", 0],
    [27, "[unnamed]", "33.turbo", 0],
    [28, "[unnamed]", "33.turbo", 0],
    [29, "[unnamed]", "33.turbo", 0],
    [30, "[unnamed]", "33.turbo", 0],
    [31, "[unnamed]", "33.turbo", 0],
    [32, "[unnamed]", "33.turbo", 0],
    [33, "[unnamed]", "33.turbo", 0],
    [34, "[unnamed]", "33.turbo", 0],
    [35, "[unnamed]", "33.turbo", 0],
    [36, "[unnamed]", "33.turbo", 0],
    [37, "[unnamed]", "33.turbo", 0],
    [38, "[unnamed]", "33.turbo", 0],
    [39, "[unnamed]", "33.turbo", 0],
    [40, "[unnamed]", "33.turbo", 0],
    [41, "[unnamed]", "33.turbo", 0],
    [42, "[unnamed]", "33.turbo", 0],
    [43, "[unnamed]", "33.turbo", 0],
    [44, "[unnamed]", "33.turbo", 0],
    [45, "[unnamed]", "33.turbo", 0],
    [46, "[unnamed]", "33.turbo", 0],
    [47, "[unnamed]", "33.turbo", 0],
    [48, "[unnamed]", "33.turbo", 0],
    [49, "[unnamed]", "33.turbo", 0],
    [50, "[unnamed]", "33.turbo", 0],
    [51, "[unnamed]", "33.turbo", 0],
    [52, "[unnamed]", "33.turbo", 0],
    [53, "[unnamed]", "33.turbo", 0],
    [54, "[unnamed]", "33.turbo", 0],
    [55, "[unnamed]", "33.turbo", 0],
    [56, "[unnamed]", "33.turbo", 0],
    [57, "[unnamed]", "33.turbo", 0],
    [58, "[unnamed]", "33.turbo", 0],
    [59, "[unnamed]", "33.turbo", 0],
    [60, "[unnamed]", "33.turbo", 0],
    [61, "[unnamed]", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/b6461c30-6b47-4f4a-a6ef-52bfbe72efac"]

[09842970118743d9d85400827a0c3353]
catalognumber = ""
date = "2014-04-27"
album = "電波 de わっしょい♪"
tracks = [
    [1, "カーニバルフェスティバル祭", "33.turbo", 1],
    [2, "はじめてのちゅうかな", "33.turbo", 1],
    [3, "ごはんは猫の最大のイベントです。", "33.turbo", 1],
    [4, "お兄ちゃんの性癖～ストライクゾーンは満10歳まで～", "33.turbo", 1],
    [5, "キャベツまつり", "33.turbo", 1],
    [6, "カーニバルフェスティバルレスリング", "33.turbo", 1],
    [7, "パンツ♂まつり", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/42765829-0972-44cc-8590-055996ed494d", "https://www.dojin-music.info/cd/6636"]

[2fa08afe1717b9565dd9c7ad886cdce4]
catalognumber = ""
date = "2014-08-17"
album = "電波deBEST"
tracks = []
links = ["https://www.dojin-music.info/cd/6635"]

[5f1e465460edd3dc04fe09f0d4bbb9ac]
catalognumber = ""
date = "2014-08-17"
album = "電波de休日"
tracks = [
    [1, "明るい夏休み計画。", "33.turbo", 1],
    [2, "はっぴーまんでー", "33.turbo", 1],
    [3, "おにいちゃんのおやすみ", "33.turbo feat. 例のあいつ", 1],
    [4, "コミケのうた", "33.turbo", 1],
    [5, "兄貴達のおやすみ", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/4bffc4bb-e848-43aa-8053-0535f55d9644", "https://www.dojin-music.info/cd/6634"]

[3b89a77959183a08fec120938b614bce]
catalognumber = ""
date = "2014-08-27"
album = "電波 de BEST"
tracks = [
    [1, "ニャン☆パラ", "33.turbo", 1],
    [2, "おげんき☆電気", "33.turbo", 1],
    [3, "南国育ちの娘さん", "33.turbo", 1],
    [4, "†邪気×sis†", "33.turbo", 1],
    [5, "uta-oh", "33.turbo", 1],
    [6, "いまいち萌えないうた", "33.turbo", 1],
    [7, "Attack", "33.turbo", 1],
    [8, "うちのお兄ちゃんが鈍感でこまる", "33.turbo", 1],
    [9, "恋の送電線", "33.turbo", 1],
    [10, "nano.", "33.turbo", 1],
    [11, "Micro☆Miracle", "33.turbo", 1],
    [12, "ネコゼット", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/ae3a7c15-f894-49bf-b409-37763bd0c568"]

[3a27d8d49932e8eea8ced24b5c22f675]
catalognumber = ""
date = "2014-10-26"
album = "電波de若大将"
tracks = [
    [1, "幼稚園の若大将", "33.turbo", 1],
    [2, "いつかの若大将～海辺の星～", "33.turbo", 1],
    [3, "純白の若大将～きみといつまでも～", "33.turbo", 1],
    [4, "お・ま・け", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/96e42563-bb9f-4d2c-b234-dfa0450f7412"]

[9daad5d3e400fd869d22f5a4c1c8d7b4]
catalognumber = ""
date = "2014-10-26"
album = "電波de若大将"
tracks = [
    [1, "幼稚園の若大将", "幼女A", 1],
    [2, "いつかの若大将～海辺の星～", "幼女A", 1],
    [3, "純白の若大将～きみといつまでも～", "幼女A", 1],
]
links = ["https://www.dojin-music.info/cd/6633"]

[9d7b416d59f4ae72d3d720e9d4078d69]
catalognumber = ""
date = "2014-12-30"
album = "電波de病院（ほすぴたる）"
tracks = [
    [1, "電波de病院（ほすぴたる）", "33.turbo", 1],
    [2, "ようこそようじょのホスピタル", "33.turbo", 1],
    [3, "愛のお医者さんごっこ", "33.turbo", 1],
    [4, "わたしの闘病生活", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/8ca2804d-1e07-4a83-a744-1dfb564a4316", "https://www.dojin-music.info/cd/6632"]

[3bfb7ad1569ea9be3ad2b9e73de47a81]
catalognumber = ""
date = "2015-04-26"
album = "電波de青春"
tracks = [
    [1, "セイシュン白書", "幼女A", 1],
    [2, "ちょっと足りないので妄想してみた結果", "幼女A", 1],
    [3, "モテたくてギターを始めてみた結果wwww", "幼女A", 1],
    [4, "青春応援団☆", "幼女A", 1],
]
links = ["https://www.dojin-music.info/cd/6631"]

[80821fdb3167d1f1c546d8934695d3ff]
catalognumber = ""
date = "2015-04-26"
album = "電波de青春"
tracks = [
    [1, "セイシュン白書", "33.turbo", 1],
    [2, "ちょっと足りないので妄想してみた結果", "33.turbo", 1],
    [3, "モテたくてギターを始めてみた結果wwww", "33.turbo", 1],
    [4, "青春応援団☆", "33.turbo", 1],
    [5, "パンツ♂白書", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/f83f6078-c8a3-4f33-80c4-ec2a76c828e6"]

[d1afca6c5cb6a0c1a1c2cfbccc55e38c]
catalognumber = ""
date = "2015-08-14"
album = "電波de日本"
tracks = [
    [1, "開国幼女ぺりーちゃん", "33.turbo", 1],
    [2, "日本酒で日本一周", "33.turbo", 1],
    [3, "くーる・じゃぱん", "33.turbo", 1],
    [4, "ちょんマげ！！", "33.turbo", 1],
    [5, "キレにク！", "33.turbo", 1],
    [6, "平家♂BOY", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/c1b91f4a-09c6-493d-a158-896cfd9e53b7"]

[cfa5ee5d624d57790bf3dc5a4b68d1d9]
catalognumber = ""
date = "2015-08-14"
album = "電波de超まとめ"
tracks = [
    [1, "ジュリアナ幼女", "33.turbo", 1],
    [2, "ナ・イ・シ・ョのレッスン", "33.turbo", 1],
    [3, "どさんこグルメのうた", "33.turbo", 1],
    [4, "焼肉の館", "33.turbo", 1],
    [5, "萌え萌え体操第２", "33.turbo", 1],
    [6, "幼女マッサージ", "33.turbo", 1],
    [7, "man=MAN", "33.turbo", 1],
    [8, "幼女☆音頭", "33.turbo", 1],
    [9, "頭文字Dempa", "33.turbo", 1],
    [10, "neko・manma", "33.turbo", 1],
    [11, "マジカる☆カクテる☆トロピカる", "33.turbo", 1],
    [12, "ブルマでないと！", "33.turbo", 1],
    [13, "ダンシン幼女", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/ff5f3fba-bdc7-4171-9e2d-8e10c5ffbc87"]

[ff335730b862d0426afc64da9f499585]
catalognumber = ""
date = "2015-08-16"
album = "電波de日本"
tracks = [
    [1, "開国幼女ぺりーちゃん", "幼女A", 1],
    [2, "くーる・じゃぱん", "幼女A", 1],
    [3, "日本酒で日本一周", "幼女A", 1],
    [4, "ちょんマげ！！", "幼女A", 1],
]
links = ["https://www.dojin-music.info/cd/6630"]

[96ffd2db8aeb3e40512c8489143403b0]
catalognumber = ""
date = "2015-08-16"
album = "電波de超まとめ"
tracks = []
links = ["https://www.dojin-music.info/cd/7536"]

[00831e75627c20a9c144e540a9d8af8f]
catalognumber = ""
date = "2015-10-25"
album = "電波deカレー"
tracks = [
    [1, "悟れ！カレー！", "33.turbo", 1],
    [2, "フォン・ド・幼女", "33.turbo", 1],
    [3, "今日も１日乙カレー", "33.turbo", 1],
    [4, "例のカレー", "33.turbo", 1],
]
links = ["https://beta.musicbrainz.org/release/14667ce0-6643-42bf-b583-053685cb27f5"]

[4d3e458fac631a4b52340ec82167a2d7]
catalognumber = ""
date = "2015-12-31"
album = "電波deディスコ"
tracks = [
    [1, "でぃすこ☆筋肉", "幼女A", 1],
    [2, "おらジュリアナさ行くだ", "幼女A", 1],
    [3, "ナウいディスコ", "幼女A", 1],
    [4, "でぃすこ☆しましま", "ほたる", 1],
    [5, "ナウい♂ムスコ", "幼女A", 1],
]
links = ["https://www.dojin-music.info/cd/6261"]
