[88d3771d5c819295b0450dbf891625cf]
catalognumber = ""
date = ""
album = "おっさんに火をつけろ"
tracks = [
    [1, "おっさんに火をつけろ", "ぷらいむまりぃ", 0],
    [2, "恋の消防車", "ぷらいむまりぃ", 0],
]
links = ["https://www.last.fm/music/%E3%81%B7%E3%82%89%E3%81%84%E3%82%80%E3%81%BE%E3%82%8A%E3%81%83/%E3%81%8A%E3%81%A3%E3%81%95%E3%82%93%E3%81%AB%E7%81%AB%E3%82%92%E3%81%A4%E3%81%91%E3%82%8D"]

[71e258d92c841a02f0a1430710efd3de]
catalognumber = ""
date = "2009-05-05"
album = "戦え！！！アイドロイド"
tracks = [
    [1, "戦え！！！アイドロイド", "33.turbo", 0],
    [2, "nano.", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/346e9047-eb2f-408b-962b-96dbde61ba5d"]

[3d970932f73d786729411fb2b9c72b0c]
catalognumber = ""
date = "2009-10-11"
album = "ニャン☆パラ"
tracks = [
    [1, "ねこさんといっしょ！～hyper 園児′n version～", "33.turbo", 0],
    [2, "ニャン☆パラ", "33.turbo", 0],
    [3, "まいまいダーリン", "33.turbo", 0],
    [4, "ネコゼット", "33.turbo", 0],
    [5, "ねこさんといっしょ！～sasami version～", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/0f863524-337c-43a4-8f88-d70090980e35", "https://www.dojin-music.info/cd/2721"]

[e7db9dcbdc7a66b00e90b88b84e911c0]
catalognumber = ""
date = "2010-05-05"
album = "放課後ミックスジュース"
tracks = [
    [1, "ギー太に首ったけ", "33.turbo", 0],
    [2, "ふわふわ時間", "33.turbo", 0],
    [3, "Don't Say“lazy”", "33.turbo", 0],
    [4, "UNTN～hyper 園児′n Version～", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/363d1526-b71b-49fb-9778-c162793cbdcd", "https://www.dojin-music.info/cd/2963"]

[86e3841eef5fcbe003da61226bf6a6d4]
catalognumber = ""
date = "2010-10-31"
album = "イモート☆アラモード"
tracks = [
    [1, "†邪気×sis†", "33.turbo", 0],
    [2, "うちのお兄ちゃんが鈍感でこまる", "33.turbo", 0],
    [3, "ずっと、妹", "33.turbo", 0],
    [4, "妹道", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/9723abd9-ff35-4e61-aaa6-ce148f7ab9c7", "https://www.dojin-music.info/cd/7537"]

[73483660fb6304c36dc366acee17831d]
catalognumber = ""
date = "2011-01-05"
album = "ホイップライフ"
tracks = [
    [1, "おげんき☆電気", "33.turbo", 0],
    [2, "恋の送電線", "33.turbo", 0],
    [3, "愛の買占め", "33.turbo", 0],
    [4, "ぼーなすとらっく　おげんき☆電気　TranceCoreMix", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/374fb12f-6da8-4ff1-b8c0-e0f71c484df1", "https://www.dojin-music.info/cd/3385"]

[5973ab09484ce8f9641dc2db09ba675f]
catalognumber = ""
date = "2011-10-30"
album = "おとチャ"
tracks = [
    [1, "Uta-Oh", "33.turbo", 0],
    [2, "聖☆幼女", "33.turbo", 0],
    [3, "Sleeping Cutie", "33.turbo", 0],
    [4, "Micro☆Miracle", "33.turbo", 0],
    [5, "???", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/3aac558f-e2b8-4729-bf4b-ba8bf4cb1ff3"]

[573daaf187fe8f975385e47c7dd019ec]
catalognumber = ""
date = "2011-10-30"
album = "おとチャ"
tracks = []
links = ["https://www.dojin-music.info/cd/7539"]

[e07f960bdfa6fdbeb1a01f402fab63f1]
catalognumber = ""
date = "2012-04-30"
album = "まにこれ!?"
tracks = [
    [1, "しびる★びる★びる", "33.turbo", 0],
    [2, "ストタイニーソ", "33.turbo", 0],
    [3, "南国育ちの娘さん", "33.turbo", 0],
    [4, "Atack", "33.turbo", 0],
    [5, "Shooting Star", "33.turbo", 0],
    [6, "なにこれ！？", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/020cf9b1-c23f-4e30-9ba3-88518910395e"]

[e25cd4b935264b9dc7fac0188e157fe7]
catalognumber = ""
date = "2012-04-30"
album = "まにこれ！？"
tracks = []
links = ["https://www.dojin-music.info/cd/7538"]

[567fb3e32d7b56d925281c1e7040f958]
catalognumber = ""
date = "2012-10-28"
album = "Dempa de Dance"
tracks = [
    [1, "ジュリアナ幼女", "33.turbo", 0],
    [2, "幼女☆音頭", "33.turbo", 0],
    [3, "man=MAN", "33.turbo", 0],
    [4, "neko・manma", "33.turbo", 0],
    [5, "ダンシン幼女", "33.turbo", 0],
    [6, "ジュリ穴♂┌(┌^o^)┐ホモォ...", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/50124265-6ebe-4052-a5a7-c3a85d8673bc", "https://www.dojin-music.info/cd/6639"]

[aefe0c287b820b156555ae008c5acebb]
catalognumber = ""
date = "2013-04-29"
album = "電波de保健体育"
tracks = [
    [1, "頭文字Dempa", "33.turbo", 0],
    [2, "萌え萌え体操第2", "33.turbo", 0],
    [3, "ブルマでないと!", "33.turbo", 0],
    [4, "ナ・イ・シ・ョのレッスン", "33.turbo", 0],
    [5, "幼女マッサージ", "33.turbo", 0],
    [6, "ガチムチパンツレスリング体操第1", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/d580ce0b-c474-4e8a-96d3-5135b206f446"]

[cc2d1a8e4ce99f85d03492cdb8381149]
catalognumber = ""
date = "2013-04-29"
album = "電波de保健体育"
tracks = [
    [1, "頭文字Dempa", "幼女A", 0],
    [2, "萌え萌え体操第２", "幼女A", 0],
    [3, "ブルマでナイト", "幼女A", 0],
    [4, "ナ・イ・シ・ョのレッスン", "幼女A", 0],
    [5, "幼女マッサージ", "", 0],
]
links = ["https://www.dojin-music.info/cd/6638"]

[80c7348a6cd786ea4dbdca255661763d]
catalognumber = ""
date = "2013-10-27"
album = "電波deグルメ"
tracks = [
    [1, "どさんこグルメ", "33.turbo", 0],
    [2, "マジカる☆カクテる☆トロピカる", "33.turbo", 0],
    [3, "焼き肉の館", "33.turbo", 0],
    [4, "どさんこグルメ(魂の叫びver.)", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/12fe3505-9a4a-4e23-a500-e33355a0b60f", "https://www.dojin-music.info/cd/6637"]

[a23e3d25db152f1567d9de96004bcd67]
catalognumber = ""
date = "2014-04-27"
album = "ガチムチかるた"
tracks = [
    [1, "[unnamed]", "33.turbo", 0],
    [2, "[unnamed]", "33.turbo", 0],
    [3, "[unnamed]", "33.turbo", 0],
    [4, "[unnamed]", "33.turbo", 0],
    [5, "[unnamed]", "33.turbo", 0],
    [6, "[unnamed]", "33.turbo", 0],
    [7, "[unnamed]", "33.turbo", 0],
    [8, "[unnamed]", "33.turbo", 0],
    [9, "[unnamed]", "33.turbo", 0],
    [10, "[unnamed]", "33.turbo", 0],
    [11, "[unnamed]", "33.turbo", 0],
    [12, "[unnamed]", "33.turbo", 0],
    [13, "[unnamed]", "33.turbo", 0],
    [14, "[unnamed]", "33.turbo", 0],
    [15, "[unnamed]", "33.turbo", 0],
    [16, "[unnamed]", "33.turbo", 0],
    [17, "[unnamed]", "33.turbo", 0],
    [18, "[unnamed]", "33.turbo", 0],
    [19, "[unnamed]", "33.turbo", 0],
    [20, "[unnamed]", "33.turbo", 0],
    [21, "[unnamed]", "33.turbo", 0],
    [22, "[unnamed]", "33.turbo", 0],
    [23, "[unnamed]", "33.turbo", 0],
    [24, "[unnamed]", "33.turbo", 0],
    [25, "[unnamed]", "33.turbo", 0],
    [26, "[unnamed]", "33.turbo", 0],
    [27, "[unnamed]", "33.turbo", 0],
    [28, "[unnamed]", "33.turbo", 0],
    [29, "[unnamed]", "33.turbo", 0],
    [30, "[unnamed]", "33.turbo", 0],
    [31, "[unnamed]", "33.turbo", 0],
    [32, "[unnamed]", "33.turbo", 0],
    [33, "[unnamed]", "33.turbo", 0],
    [34, "[unnamed]", "33.turbo", 0],
    [35, "[unnamed]", "33.turbo", 0],
    [36, "[unnamed]", "33.turbo", 0],
    [37, "[unnamed]", "33.turbo", 0],
    [38, "[unnamed]", "33.turbo", 0],
    [39, "[unnamed]", "33.turbo", 0],
    [40, "[unnamed]", "33.turbo", 0],
    [41, "[unnamed]", "33.turbo", 0],
    [42, "[unnamed]", "33.turbo", 0],
    [43, "[unnamed]", "33.turbo", 0],
    [44, "[unnamed]", "33.turbo", 0],
    [45, "[unnamed]", "33.turbo", 0],
    [46, "[unnamed]", "33.turbo", 0],
    [47, "[unnamed]", "33.turbo", 0],
    [48, "[unnamed]", "33.turbo", 0],
    [49, "[unnamed]", "33.turbo", 0],
    [50, "[unnamed]", "33.turbo", 0],
    [51, "[unnamed]", "33.turbo", 0],
    [52, "[unnamed]", "33.turbo", 0],
    [53, "[unnamed]", "33.turbo", 0],
    [54, "[unnamed]", "33.turbo", 0],
    [55, "[unnamed]", "33.turbo", 0],
    [56, "[unnamed]", "33.turbo", 0],
    [57, "[unnamed]", "33.turbo", 0],
    [58, "[unnamed]", "33.turbo", 0],
    [59, "[unnamed]", "33.turbo", 0],
    [60, "[unnamed]", "33.turbo", 0],
    [61, "[unnamed]", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/b6461c30-6b47-4f4a-a6ef-52bfbe72efac"]

[0b75b8df81b704a11842ebf774988e6c]
catalognumber = ""
date = "2014-04-27"
album = "電波 de わっしょい♪"
tracks = [
    [1, "カーニバルフェスティバル祭", "33.turbo", 0],
    [2, "はじめてのちゅうかな", "33.turbo", 0],
    [3, "ごはんは猫の最大のイベントです。", "33.turbo", 0],
    [4, "お兄ちゃんの性癖～ストライクゾーンは満10歳まで～", "33.turbo", 0],
    [5, "キャベツまつり", "33.turbo", 0],
    [6, "カーニバルフェスティバルレスリング", "33.turbo", 0],
    [7, "パンツ♂まつり", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/42765829-0972-44cc-8590-055996ed494d", "https://www.dojin-music.info/cd/6636"]

[068c39e6162dda6d257a90a080ff163c]
catalognumber = ""
date = "2014-08-17"
album = "電波deBEST"
tracks = []
links = ["https://www.dojin-music.info/cd/6635"]

[4849255f3e61a3117f5b62bf46598b4b]
catalognumber = ""
date = "2014-08-17"
album = "電波de休日"
tracks = [
    [1, "明るい夏休み計画。", "33.turbo", 0],
    [2, "はっぴーまんでー", "33.turbo", 0],
    [3, "おにいちゃんのおやすみ", "33.turbo feat. 例のあいつ", 0],
    [4, "コミケのうた", "33.turbo", 0],
    [5, "兄貴達のおやすみ", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/4bffc4bb-e848-43aa-8053-0535f55d9644", "https://www.dojin-music.info/cd/6634"]

[6c7165cfa7813f0abb7dcdf1c111eaa7]
catalognumber = ""
date = "2014-08-27"
album = "電波 de BEST"
tracks = [
    [1, "ニャン☆パラ", "33.turbo", 0],
    [2, "おげんき☆電気", "33.turbo", 0],
    [3, "南国育ちの娘さん", "33.turbo", 0],
    [4, "†邪気×sis†", "33.turbo", 0],
    [5, "uta-oh", "33.turbo", 0],
    [6, "いまいち萌えないうた", "33.turbo", 0],
    [7, "Attack", "33.turbo", 0],
    [8, "うちのお兄ちゃんが鈍感でこまる", "33.turbo", 0],
    [9, "恋の送電線", "33.turbo", 0],
    [10, "nano.", "33.turbo", 0],
    [11, "Micro☆Miracle", "33.turbo", 0],
    [12, "ネコゼット", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/ae3a7c15-f894-49bf-b409-37763bd0c568"]

[135195517eef879de277d091553e1ed1]
catalognumber = ""
date = "2014-10-26"
album = "電波de若大将"
tracks = [
    [1, "幼稚園の若大将", "33.turbo", 0],
    [2, "いつかの若大将～海辺の星～", "33.turbo", 0],
    [3, "純白の若大将～きみといつまでも～", "33.turbo", 0],
    [4, "お・ま・け", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/96e42563-bb9f-4d2c-b234-dfa0450f7412"]

[fee32972d014cbcffb3fb438d45a8405]
catalognumber = ""
date = "2014-10-26"
album = "電波de若大将"
tracks = [
    [1, "幼稚園の若大将", "幼女A", 0],
    [2, "いつかの若大将～海辺の星～", "幼女A", 0],
    [3, "純白の若大将～きみといつまでも～", "幼女A", 0],
]
links = ["https://www.dojin-music.info/cd/6633"]

[df6964cb6a6d4c3daf37de09696a8604]
catalognumber = ""
date = "2014-12-30"
album = "電波de病院（ほすぴたる）"
tracks = [
    [1, "電波de病院（ほすぴたる）", "33.turbo", 0],
    [2, "ようこそようじょのホスピタル", "33.turbo", 0],
    [3, "愛のお医者さんごっこ", "33.turbo", 0],
    [4, "わたしの闘病生活", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/8ca2804d-1e07-4a83-a744-1dfb564a4316", "https://www.dojin-music.info/cd/6632"]

[1fc934f70f52573265cc90e24c04a72c]
catalognumber = ""
date = "2015-04-26"
album = "電波de青春"
tracks = [
    [1, "セイシュン白書", "幼女A", 0],
    [2, "ちょっと足りないので妄想してみた結果", "幼女A", 0],
    [3, "モテたくてギターを始めてみた結果wwww", "幼女A", 0],
    [4, "青春応援団☆", "幼女A", 0],
]
links = ["https://www.dojin-music.info/cd/6631"]

[9b8d82070ad31b35fcfc944913607a1e]
catalognumber = ""
date = "2015-04-26"
album = "電波de青春"
tracks = [
    [1, "セイシュン白書", "33.turbo", 0],
    [2, "ちょっと足りないので妄想してみた結果", "33.turbo", 0],
    [3, "モテたくてギターを始めてみた結果wwww", "33.turbo", 0],
    [4, "青春応援団☆", "33.turbo", 0],
    [5, "パンツ♂白書", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/f83f6078-c8a3-4f33-80c4-ec2a76c828e6"]

[dc1b5fa2b842c06149caad6baa9ee6fe]
catalognumber = ""
date = "2015-08-14"
album = "電波de日本"
tracks = [
    [1, "開国幼女ぺりーちゃん", "33.turbo", 0],
    [2, "日本酒で日本一周", "33.turbo", 0],
    [3, "くーる・じゃぱん", "33.turbo", 0],
    [4, "ちょんマげ！！", "33.turbo", 0],
    [5, "キレにク！", "33.turbo", 0],
    [6, "平家♂BOY", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/c1b91f4a-09c6-493d-a158-896cfd9e53b7"]

[088d55985fdf3a04b5789aa78014d14d]
catalognumber = ""
date = "2015-08-14"
album = "電波de超まとめ"
tracks = [
    [1, "ジュリアナ幼女", "33.turbo", 0],
    [2, "ナ・イ・シ・ョのレッスン", "33.turbo", 0],
    [3, "どさんこグルメのうた", "33.turbo", 0],
    [4, "焼肉の館", "33.turbo", 0],
    [5, "萌え萌え体操第２", "33.turbo", 0],
    [6, "幼女マッサージ", "33.turbo", 0],
    [7, "man=MAN", "33.turbo", 0],
    [8, "幼女☆音頭", "33.turbo", 0],
    [9, "頭文字Dempa", "33.turbo", 0],
    [10, "neko・manma", "33.turbo", 0],
    [11, "マジカる☆カクテる☆トロピカる", "33.turbo", 0],
    [12, "ブルマでないと！", "33.turbo", 0],
    [13, "ダンシン幼女", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/ff5f3fba-bdc7-4171-9e2d-8e10c5ffbc87"]

[5414d254d7f794aca148d8fba644c3d6]
catalognumber = ""
date = "2015-08-16"
album = "電波de日本"
tracks = [
    [1, "開国幼女ぺりーちゃん", "幼女A", 0],
    [2, "くーる・じゃぱん", "幼女A", 0],
    [3, "日本酒で日本一周", "幼女A", 0],
    [4, "ちょんマげ！！", "幼女A", 0],
]
links = ["https://www.dojin-music.info/cd/6630"]

[822e1a6e3751798897d1ef9d303f87eb]
catalognumber = ""
date = "2015-08-16"
album = "電波de超まとめ"
tracks = []
links = ["https://www.dojin-music.info/cd/7536"]

[016f78985935e6ad1919682cba148931]
catalognumber = ""
date = "2015-10-25"
album = "電波deカレー"
tracks = [
    [1, "悟れ！カレー！", "33.turbo", 0],
    [2, "フォン・ド・幼女", "33.turbo", 0],
    [3, "今日も１日乙カレー", "33.turbo", 0],
    [4, "例のカレー", "33.turbo", 0],
]
links = ["https://beta.musicbrainz.org/release/14667ce0-6643-42bf-b583-053685cb27f5"]

[a02cc9c2ffdb92487af64bc24928cac3]
catalognumber = ""
date = "2015-12-31"
album = "電波deディスコ"
tracks = [
    [1, "でぃすこ☆筋肉", "幼女A", 0],
    [2, "おらジュリアナさ行くだ", "幼女A", 0],
    [3, "ナウいディスコ", "幼女A", 0],
    [4, "でぃすこ☆しましま", "ほたる", 0],
    [5, "ナウい♂ムスコ", "幼女A", 0],
]
links = ["https://www.dojin-music.info/cd/6261"]
