[b460d983f24d940aec29bac67257926e]
catalognumber = ""
date = "2020-12-02"
album = "Quiet"
tracks = [
    [1, "Quiet", "A-SOUL", 1],
    [2, "Quiet (伴奏)", "A-SOUL", 1],
]
links = ["https://music.163.com/#/album?id=98971470"]

[1500f849fae9dd000668ab5e4f765a0f]
catalognumber = ""
date = "2021-05-06"
album = "超级敏感"
tracks = [
    [1, "超级敏感", "A-SOUL", 2],
    [2, "超级敏感 (伴奏)", "A-SOUL", 1],
]
links = ["https://music.163.com/#/album?id=126788670"]

[656a704e97c094e7084880b1969327c7]
catalognumber = ""
date = "2021-12-17"
album = "传说的世界"
tracks = [
    [1, "传说的世界", "A-SOUL", 1],
    [2, "传说的世界  (伴奏)", "A-SOUL", 1],
]
links = ["https://music.163.com/#/album?id=137519227"]

[4f7ae350df915e646f64838c58e091ff]
catalognumber = ""
date = "2022-02-03"
album = "除夕"
tracks = [
    [1, "除夕", "音阙诗听/A-SOUL", 1],
    [2, "除夕(伴奏)", "音阙诗听/A-SOUL", 1],
]
links = ["https://music.163.com/#/album?id=140137855"]

[3a7532b3d7c60ef08072597412c3c0e9]
catalognumber = ""
date = "2022-12-12"
album = "共鸣 Re-sonance (上)"
tracks = [
    [1, "Re-sonance", "A-SOUL", 0],
    [2, "DA DA", "向晚Ava/嘉然Diana", 0],
    [3, "练习心事", "贝拉Bella/乃琳Eileen", 0],
]
links = ["https://music.163.com/#/album?id=156143561"]

[8eff255c35d4a1d14e8db6bf0c74a09d]
catalognumber = ""
date = "2022-12-12"
album = "Leap Top"
tracks = [
    [1, "Leap Top", "A-SOUL", 1],
    [2, "Leap Top (伴奏)", "A-SOUL", 1],
]
links = ["https://music.163.com/#/album?id=156141458"]

[14443ff81ce932879ca911a2199ee0a7]
catalognumber = ""
date = "2023-12-11"
album = "绽放Bloom（下）"
tracks = [
    [1, "绽放Bloom", "A-SOUL", 0],
    [2, "风与花Wind & Flowers", "向晚Ava/乃琳Eileen", 0],
    [3, "蓓蕾Bud", "贝拉Bella/嘉然Diana", 0],
]
links = ["https://music.163.com/#/album?id=179428905"]

[7c640bfb5b35e7020e1c7cd2a3975091]
catalognumber = ""
date = "2024-12-22"
album = "冬日奇迹"
tracks = [
    [1, "Snow Dancing", "A-SOUL", 1],
    [2, "周末出逃计划", "嘉然Diana/乃琳Eileen", 1],
    [3, "Snow Dancing (伴奏)", "A-SOUL", 1],
    [4, "周末出逃计划 (伴奏)", "嘉然Diana/乃琳Eileen", 1],
]
links = ["https://music.163.com/#/album?id=258537934"]
