[cd98473cc32459e8478def8f0a74d8f0]
catalognumber = "ANTX-1022"
date = "2010-11-24"
album = "デートに行けない日曜日"
tracks = [
    [1, "初恋", "HAPPY BIRTHDAY", 0],
    [2, "デリケイトゾーン", "HAPPY BIRTHDAY", 0],
    [3, "君は灰色あたしはオセロ", "HAPPY BIRTHDAY", 0],
    [4, "PMS", "HAPPY BIRTHDAY", 0],
    [5, "秘密のじかん", "HAPPY BIRTHDAY", 0],
    [6, "ポーラはなにもわからない", "HAPPY BIRTHDAY", 0],
    [7, "K", "HAPPY BIRTHDAY", 0],
    [8, "つまらない先輩は白いズボンを履いている", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/24865cab-a37b-4672-8d2d-1c9410fbd8ad"]

[bceea91a20ec71c1b2afb183a92ca86e]
catalognumber = "AICL-2309"
date = "2011-10-26"
album = "ファーストキス"
tracks = [
    [1, "しゃかいのごみのうた", "HAPPY BIRTHDAY", 0],
    [2, "だきしめて怪獣くん!", "HAPPY BIRTHDAY", 0],
    [3, "SHIT!", "HAPPY BIRTHDAY", 0],
    [4, "特別な日々", "HAPPY BIRTHDAY", 0],
    [5, "エピローグ", "HAPPY BIRTHDAY", 0],
    [6, "光る記憶", "HAPPY BIRTHDAY", 0],
    [7, "閃光", "HAPPY BIRTHDAY", 0],
    [8, "こころの王様", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/ef16715d-26cd-41b7-ad36-4b37bafffca7"]

[c66fc6791f95ba112c536d7ba86ca8bc]
catalognumber = "AICL-2378"
date = "2012-05-23"
album = "嘘でもかわいいと言って"
tracks = [
    [1, "あの子の彼氏", "HAPPY BIRTHDAY", 0],
    [2, "愛のパレード", "HAPPY BIRTHDAY", 0],
    [3, "あなたの居ない明日", "HAPPY BIRTHDAY", 0],
    [4, "アイプチコンプレックス", "HAPPY BIRTHDAY", 0],
    [5, "こうやってまた君に嫌われる", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/04758d2a-6c5a-4de3-ae80-3fb49279d792"]

[e6067e892d3db0d551cbfd1bfdff0fc8]
catalognumber = "AICL-2412"
date = "2012-08-15"
album = "恋暴動 / DAIKIRAI-DAISUKI"
tracks = [
    [1, "恋暴動", "HAPPY BIRTHDAY", 0],
    [2, "DAIKIRAI-DAISUKI", "HAPPY BIRTHDAY", 0],
    [3, "アイプチコンプレックス - Kanimiso MIX -", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/df2337e4-c0a6-4929-819e-595de5c5e5b4"]

[a7391e4207b655c9a65d60406046f5ee]
catalognumber = "AICL-2413"
date = "2012-08-15"
album = "恋暴動 / DAIKIRAI-DAISUKI"
tracks = [
    [1, "恋暴動", "HAPPY BIRTHDAY", 0],
    [2, "DAIKIRAI-DAISUKI", "HAPPY BIRTHDAY", 0],
    [3, "アイプチコンプレックス - Kanimiso MIX -", "HAPPY BIRTHDAY", 0],
    [4, "恋暴動 (アニメsize)", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/65fa0b64-529d-4304-81f3-52e101b6f047"]

[951737d652ec80cf08caa9aa5fbe89e1]
catalognumber = "AICL-2500"
date = "2013-02-06"
album = "イチャイチャチュッチュキャピキャピラブラブスリスリドキドキ"
tracks = [
    [1, "イチャイチャチュッチュキャピキャピラブラブスリスリドキドキ", "HAPPY BIRTHDAY", 0],
    [2, "ムーンライト伝説", "HAPPY BIRTHDAY", 0],
    [3, "恋暴動 (PandaBoY Remix)", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/4c6ed33f-da73-4bd8-8d8d-ad42950e4438"]

[81c4d0e0f5728c60bf74ab3657e47742]
catalognumber = "AICL-2501"
date = "2013-02-06"
album = "イチャイチャチュッチュキャピキャピラブラブスリスリドキドキ"
tracks = [
    [1, "イチャイチャチュッチュキャピキャピラブラブスリスリドキドキ", "HAPPY BIRTHDAY", 0],
    [2, "ムーンライト伝説", "HAPPY BIRTHDAY", 0],
    [3, "恋暴動 (PandaBoY Remix)", "HAPPY BIRTHDAY", 0],
    [4, "イチャイチャチュッチュキャピキャピラブラブスリスリドキドキアニメSIZE", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/fc00f974-ed15-42d8-985a-207b7b836ea3"]

[ccc844ff988b64c44f714eb5a9815439]
catalognumber = "AICL-2525"
date = "2013-03-13"
album = "今夜きみが怖い夢を見ませんように"
tracks = [
    [1, "恋暴動", "HAPPY BIRTHDAY", 0],
    [2, "イチャイチャチュッチュキャピキャピラブラブスリスリドキドキ", "HAPPY BIRTHDAY", 0],
    [3, "わたしは君のママじゃない", "HAPPY BIRTHDAY", 0],
    [4, "君だったら", "HAPPY BIRTHDAY", 0],
    [5, "期待外れのメリーゴーランド", "HAPPY BIRTHDAY", 0],
    [6, "魔法のタイムマシン", "HAPPY BIRTHDAY", 0],
    [7, "1989", "HAPPY BIRTHDAY", 0],
    [8, "ありがとうまたね", "HAPPY BIRTHDAY", 0],
    [9, "ぼくがそばにいる", "HAPPY BIRTHDAY", 0],
    [10, "DAIKIRAI-DAISUKI", "HAPPY BIRTHDAY", 0],
    [11, "目を開けて", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/a8f65b2a-7022-4242-a1de-7d3e960caf98"]

[a135e9ca9e233030bb416da808b7e381]
catalognumber = "AICL02412B00Z"
date = "2014-04-01"
album = "恋暴動 / DAIKIRAI-DAISUKI"
tracks = [
    [1, "恋暴動", "HAPPY BIRTHDAY", 0],
    [2, "DAIKIRAI-DAISUKI", "HAPPY BIRTHDAY", 0],
    [3, "アイプチコンプレックス -Kanimiso MIX- by mathru (かにみそP)", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/8decf65d-d183-4db8-954a-cc605d0fba54"]

[3edec744849728bf7b36c675bd33ab67]
catalognumber = "AICL-2697~8"
date = "2014-06-04"
album = "NEW ME NEW ME NEW"
tracks = [
    [1, "NEW ME NEW ME NEW", "HAPPY BIRTHDAY", 0],
    [2, "ダイヤモンドブス", "HAPPY BIRTHDAY", 0],
    [3, "週休五日の仕事がしたい", "HAPPY BIRTHDAY", 0],
    [4, "何番目かの女の子", "HAPPY BIRTHDAY", 0],
    [5, "スターライトシティ", "HAPPY BIRTHDAY", 0],
    [6, "電気を消したら始めよう", "HAPPY BIRTHDAY", 0],
    [7, "MUSIC", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/8fa5b312-3b1d-4e4e-82ad-19f135c70790"]

[7d09cb16ac9ae78d13514f509ff62194]
catalognumber = "AICL-2699"
date = "2014-06-04"
album = "NEW ME NEW ME NEW"
tracks = [
    [1, "NEW ME NEW ME NEW", "HAPPY BIRTHDAY", 0],
    [2, "ダイヤモンドブス", "HAPPY BIRTHDAY", 0],
    [3, "週休五日の仕事がしたい", "HAPPY BIRTHDAY", 0],
    [4, "何番目かの女の子", "HAPPY BIRTHDAY", 0],
    [5, "スターライトシティ", "HAPPY BIRTHDAY", 0],
    [6, "電気を消したら始めよう", "HAPPY BIRTHDAY", 0],
    [7, "MUSIC", "HAPPY BIRTHDAY", 0],
]
links = ["https://beta.musicbrainz.org/release/25056817-0f1e-4996-a614-ff9ee1838d0f"]
