[e5f9e17dd8fcbb3ec5ec22d0186cd4e8]
catalognumber = ""
date = "2009-10-11"
album = "Honey Pop"
tracks = [
    [1, "Dazzlin'", "まめこ", 0],
    [2, "Sweet Afternoon", "まめこ", 0],
    [3, "Honey Pot", "まめこ", 0],
    [4, "Astral", "まめこ", 0],
    [5, "Gateaux Sucre", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/2119"]

[e2fc7db65bd1980198d0cf22f23a0820]
catalognumber = ""
date = "2011-05-01"
album = "Jewel"
tracks = [
    [1, "Oscilloscope", "まめこ", 0],
    [2, "prisoner", "まめこ", 0],
    [3, "Sunshine Girls", "まめこ", 0],
    [4, "blindness", "まめこ", 0],
    [5, "Rainy tears", "まめこ", 0],
    [6, "Imitation Sky", "まめこ", 0],
    [7, "white fairy tale", "まめこ", 0],
    [8, "Dear", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3235"]

[392fccb37fb41d50cfce852c32e56918]
catalognumber = ""
date = "2011-10-30"
album = "Affetto"
tracks = [
    [1, "FAKE IT", "まめこ 後藤ハルキ", 0],
    [2, "Moon Cradle", "まめこ 後藤ハルキ", 0],
    [3, "願い星", "まめこ 後藤ハルキ", 0],
    [4, "Sugar Bit", "まめこ 後藤ハルキ", 0],
]
links = ["https://www.dojin-music.info/cd/17091"]

[9110be9961413dc703fa63f91d3f7faa]
catalognumber = ""
date = "2011-12-31"
album = "Floralies"
tracks = [
    [1, "moon at noon", "まめこ", 0],
    [2, "Ribbon bow", "まめこ", 0],
    [3, "Cherry Stars", "まめこ", 0],
    [4, "はるかぜを通り抜けて", "まめこ", 0],
    [5, "水玉ミントドロップ", "まめこ", 0],
    [6, "星のかけら", "まめこ", 0],
    [7, "Stray Bird", "まめこ", 0],
    [8, "Urban blast", "まめこ", 0],
    [9, "Memory", "まめこ", 0],
    [10, "Chewy Cotton Candy", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3979"]

[4d196de1a3726b88b1688ac21dd24a9f]
catalognumber = ""
date = "2013-12-31"
album = "Chococolation"
tracks = [
    [1, "Chocolate Strawberry", "まめこ", 0],
    [2, "チョコレート一粒の勇気", "まめこ", 0],
    [3, "マシュマロココア", "まめこ", 0],
    [4, "Petite Chocolatiere", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3972"]

[f8e767f7edccb10fcfa38f353789277f]
catalognumber = ""
date = "2014-08-17"
album = "Candy×Ice"
tracks = [
    [1, "Hang in there!", "まめこ", 0],
    [2, "Ice★Sweets", "まめこ", 0],
    [3, "Summer Sunset", "まめこ", 0],
    [4, "FAKE IT -mameko solo ver.-", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3978"]

[469f0242b57d1285ab6be6900bd1cc9e]
catalognumber = ""
date = "2015-04-26"
album = "Alice in Wonderforest"
tracks = [
    [1, "Hello my day", "まめこ", 0],
    [2, "闇薔薇ノ森ニ堕散ル", "まめこ", 0],
    [3, "キノコ談義 ～Myco-monologue～", "まめこ", 0],
    [4, "スター☆トラベラー", "まめこ", 0],
    [5, "夢幻の透明洞窟にて", "まめこ", 0],
    [6, "LitTle QueEN's?KiNgdOm", "まめこ", 0],
    [7, "I am Alice", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3973"]

[227536b5099ec4df86e9e78303045eba]
catalognumber = ""
date = "2015-10-25"
album = "Melody！"
tracks = [
    [1, "エスポワール", "まめこ", 0],
    [2, "Merry Berry Melody", "まめこ", 0],
    [3, "Glace Genesis", "まめこ", 0],
    [4, "グルメ・モンストル", "まめこ", 0],
    [5, "Crystal Prelude", "まめこ", 0],
    [6, "Macaron Magic", "まめこ", 0],
    [7, "おはようの呪文", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3974"]

[6fb989a1835f6b3d09ef1a23c4248201]
catalognumber = ""
date = "2016-04-24"
album = "Heroinee-ヒロイニー-"
tracks = [
    [1, "moon fairy tale", "まめこ", 0],
    [2, "Don't be late, Alice", "まめこ", 0],
    [3, "林檎姫症候群-リンゴヒメシンドローム-", "まめこ", 0],
    [4, "フェアリーネバープラネット", "まめこ", 0],
    [5, "桃色戦士ドリームガーディアン", "まめこ", 0],
    [6, "籠の中の空想姫", "まめこ", 0],
    [7, "Once apon a time", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3975"]

[a6fe0302bf17839465923718728b906b]
catalognumber = ""
date = "2016-10-30"
album = "Spookids！-スプーキッズ-"
tracks = [
    [1, "Haunted Street", "まめこ", 0],
    [2, "umpopoff", "まめこ", 0],
    [3, "月虹LOUP-GAROU", "まめこ", 0],
    [4, "Cavity!Cavity!", "まめこ", 0],
    [5, "Ms.Application", "まめこ", 0],
    [6, "きゅーけchu♥プリンセス", "まめこ", 0],
    [7, "Spookids' parade", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3976"]

[eee4609f2538df771f5aec0515903455]
catalognumber = ""
date = "2017-04-30"
album = "ふわらぶあにまる"
tracks = [
    [1, "ハートフル❤ふる！", "まめこ", 0],
    [2, "Cafe de mon plume", "まめこ", 0],
    [3, "You❤Me きゃっちぼーる", "まめこ", 0],
    [4, "sugar bunny", "まめこ", 0],
    [5, "春のまぼろし", "まめこ", 0],
    [6, "ぱいへーちゃんどぅ", "まめこ", 0],
    [7, "Sweet pastel", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3977"]

[407e29d562eaea6161d7b665b7d12cb7]
catalognumber = ""
date = "2017-10-29"
album = "Furry Party!"
tracks = [
    [1, "Furry Party", "まめこ", 0],
    [2, "はむはむでいず", "まめこ", 0],
    [3, "不器用ハンティング", "まめこ", 0],
    [4, "ALPCPCS", "まめこ", 0],
    [5, "闇色チョコレヰトメルト", "まめこ", 0],
    [6, "うぱるぱ！", "まめこ", 0],
    [7, "狐魅姫ノ花餐宴", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3980"]

[7693fbd1587ec01137badcb2b24eb28c]
catalognumber = ""
date = "2017-12-29"
album = "お嬢さま症候群"
tracks = [
    [1, "お嬢さまと呼びなさいっ", "まめこ", 0],
    [2, "スノードーム・シンドローム", "まめこ", 0],
    [3, "お嬢さまと呼びなさいっ-instrumental-", "ひろて〜", 0],
    [4, "スノードーム・シンドローム-instrumental-", "ねぎとろ", 0],
    [5, "まちぼうけ", "", 0],
]
links = ["https://www.dojin-music.info/cd/3982"]

[660335750f11a334ccc094847f71818b]
catalognumber = ""
date = "2018-04-29"
album = "ゆづ まめ"
tracks = [
    [1, "ゆづ❤まめ", "小岩井ゆづき まめこ", 0],
    [2, "『YES』か『はい』かでお答えください！", "小岩井ゆづき まめこ", 0],
    [3, "めりーめりーうぃずゆー！", "小岩井ゆづき まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/3981"]

[4ffd99149969adf352799169207aafcd]
catalognumber = ""
date = "2018-08-19"
album = "ぴかっ☆toとろぴかる"
tracks = [
    [1, "ぴか★とろ", "まめこ", 0],
    [2, "あの、ちょっといいですか", "まめこ", 0],
    [3, "ぴか★とろ～inst～", "まめこ", 0],
    [4, "あの、ちょっといいですか～inst～", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/4038"]

[ce3f636a005335b073e97adf0140e1d0]
catalognumber = ""
date = "2018-10-28"
album = "ぽっぴんどりーみん"
tracks = [
    [1, "ろりぽっぷ☆ちゅーん", "まめこ", 0],
    [2, "カップラーメンのうた", "まめこ", 0],
    [3, "ゆめきゃゎ×poppinぱーてぃ♡", "まめこ", 0],
    [4, "ぐるぐるChu*moothie", "まめこ", 0],
    [5, "ねぇ、先生", "まめこ", 0],
    [6, "めるちーゆー", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/4545", "https://beta.musicbrainz.org/release/22e851d9-a284-4707-b06b-1023a7711c36"]

[bfce4842113489b1fe2522cca635cfd9]
catalognumber = ""
date = "2019-04-28"
album = "ぷちプリマヴェーラ"
tracks = [
    [1, "Soaring☆Spring", "まめこ", 0],
    [2, "Cherry Stars -2019 ver.-", "まめこ", 0],
    [3, "Sweet Afternoon -2019 ver.-", "まめこ", 0],
    [4, "moon at noon -2019 ver.-", "まめこ", 0],
    [5, "Chewy Cotton Candy -2019 ver.-", "まめこ", 0],
    [6, "水玉ミントドロップ -2019 ver.-", "まめこ", 0],
    [7, "チョコレート1粒の勇気 -2019 ver.-", "まめこ", 0],
    [8, "Gateaux Sucre -2019 ver.-", "まめこ", 0],
    [9, "Honey pot -2019 ver.-", "まめこ", 0],
    [10, "Chocolate Strawberry -2019 ver.-", "まめこ", 0],
    [11, "Dear -2019 ver.-", "まめこ", 0],
    [12, "Dazzlin' -2019 ver.-", "まめこ", 0],
    [13, "サクライロ幸福論", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/4030"]

[1f62c9ee4c6b518618715c60973d5c6e]
catalognumber = ""
date = "2019-10-27"
album = "夢童話ロンリネス"
tracks = [
    [1, "せかいなんていらない", "まめこ", 0],
    [2, "Fortuna vitrea est", "まめこ", 0],
    [3, "ChuKiss!して☆おとこの娘", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/10363"]

[4dab7523b35b5e4505791d5f91214d78]
catalognumber = ""
date = "2019-10-27"
album = "Affectus"
tracks = [
    [1, "ラルラルラ", "小菅こんにゃく", 0],
    [2, "Almunafis Allayliu", "鈴葉ユミ", 0],
    [3, "純情TONIGHT", "たっち", 0],
    [4, "Sugar Bit", "しの", 0],
    [5, "Moon Cradle", "ニゴロウ", 0],
    [6, "願い星", "Stremanic", 0],
    [7, "FAKE IT", "ひろさわけんぢ", 0],
]
links = ["https://www.dojin-music.info/cd/10428"]

[1da34b2ae2028692564f9c1299f08f4d]
catalognumber = ""
date = "2020-03-01"
album = "180℃Girl"
tracks = [
    [1, "ヘルシー＆テイスティー", "まめこ", 0],
    [2, "Sugar Sugar Candy", "まめこ", 0],
    [3, "ひとり想い", "まめこ", 0],
    [4, "Frozen Mermaid", "まめこ", 0],
    [5, "フォレ・ノワール", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/17180"]

[bf6c899bdb72582fedca57482b3bfac3]
catalognumber = ""
date = "2020-10-25"
album = "Chum!"
tracks = [
    [1, "Chain of Happiness", "まめこ", 0],
    [2, "Yum! Yum! Yummy!", "まめこ", 0],
    [3, "くろねこさんぽ", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/22452"]

[995f3fe8882a952bcf99e4085e3257d3]
catalognumber = ""
date = "2021-04-25"
album = "Dreaming Girl"
tracks = [
    [1, "飛び出せ！虹色ワンダーランド", "まめこ", 0],
    [2, "My Favorite", "まめこ", 0],
    [3, "硝子越しの恋", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/23978"]

[bc3faa42d1848032583cafd58451a671]
catalognumber = ""
date = "2021-10-31"
album = "最低な明日におはよう / Starry Parade"
tracks = [
    [1, "最低な明日におはよう", "まめこ", 0],
    [2, "Starry Parade", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/25400"]

[2b3675025386ceb4a42d16d55f4323af]
catalognumber = ""
date = "2022-04-24"
album = "Rainbow Rain"
tracks = [
    [1, "Rainy Step", "まめこ", 0],
    [2, "monochrome rainbow", "まめこ", 0],
    [3, "Puddle Sparkle", "まめこ", 0],
    [4, "Rainbow Drops", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/26666"]

[2b9b7cf08837a0cf097449fef229892b]
catalognumber = ""
date = "2022-10-30"
album = "ゴーストランド -Ghostland-"
tracks = [
    [1, "秘密のゴーストランドへようこそ", "まめこ", 0],
    [2, "幽霊列車ハ今日モ往ク", "まめこ", 0],
    [3, "狂恋観覧車", "まめこ", 0],
    [4, "迷廻り木馬と誘のワルツ", "まめこ", 0],
    [5, "ゴーストパレード", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/28391"]

[6060e2e9ae33b808fd7ea02b852b6683]
catalognumber = ""
date = "2023-04-30"
album = "Cristir"
tracks = [
    [1, "バラバライム", "まめこ", 0],
    [2, "スイート×スイートナイトメア", "まめこ", 0],
    [3, "手遅れになっちゃう前に", "まめこ", 0],
    [4, "紅玉は渦中で嗤う", "まめこ", 0],
    [5, "砂のカケラ", "まめこ", 0],
]
links = ["https://www.dojin-music.info/cd/28998"]
