[a54296fce9f159fc030bcbf8a620d47a]
catalognumber = ""
date = "2013-08-12"
album = "twinkle はじめてのしんぐる…"
tracks = [
    [1, "ぷににふともも ニーソックスを添えて", "ちょこ みるく", 1],
    [2, "妹のしゅーくりぃむ ほんとに食べちゃうの！？", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5793"]

[9ae285d060b1c33c2b847da5d3200367]
catalognumber = ""
date = "2013-10-27"
album = "twinkle"
tracks = [
    [1, "くるるん☆ついんくる", "ちょこ", 1],
    [2, "はじめてのクリスマス", "ちょこ みるく", 1],
    [3, "ツインテでぶたれたいかい！？", "みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5792"]

[1b20b2a00cddef1dc3a8dbe3ed2d5283]
catalognumber = ""
date = "2013-12-31"
album = "せーふく♀これくしょん"
tracks = [
    [1, "制服で～と☆", "ちょこ みるく", 1],
    [2, "きみといると feat.twinkle", "ちょこ みるく", 2],
    [3, "おにーちゃんのこれくしょん", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5791"]

[9111de5da7e1b1ff587a757a9b0b800a]
catalognumber = ""
date = "2014-04-27"
album = "ぱじゃま de あ・そ・ぼ"
tracks = [
    [1, "ぐどもにもーにんっ☆", "ちょこ みるく", 1],
    [2, "眠れない どーしよう！？", "ちょこ みるく", 1],
    [3, "ぱじゃま☆あいどる", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5790"]

[54b846c7c9eb9a09698c3822ce2dbe80]
catalognumber = ""
date = "2014-08-17"
album = "ラブラブ☆ツインキュア"
tracks = [
    [1, "ラブラブ☆ツインキュア", "ちょこ みるく", 2],
    [2, "ふたりできゅあきゅあ", "ちょこ みるく", 1],
    [3, "chokolate◆症候群", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5789"]

[3916e3a032a754a2627a3182d227041e]
catalognumber = ""
date = "2014-10-26"
album = "ついんくるカフェ"
tracks = [
    [1, "Welcome to sylvan cafe", "ちょこ みるく", 2],
    [2, "すいーつすいーつらぶ feat.twinkle", "ちょこ みるく", 2],
    [3, "がおがおぴょん", "ちょこ みるく", 2],
]
links = ["https://www.dojin-music.info/cd/5788"]

[fe13a514b72df1ab68eac3a453d9a5cb]
catalognumber = ""
date = "2014-12-30"
album = "僕の妹に巫女服を着せた結果！？"
tracks = [
    [1, "DANCExSING 舞妹♡神楽 ～神COME☆やおよろずのおにーちゃん～", "ちょこ みるく", 2],
    [2, "恋の進捗どうですか？", "ちょこ みるく", 1],
    [3, "Do you need sugar and milk?", "みるく", 2],
]
links = ["https://www.dojin-music.info/cd/5787"]

[a9b868bd7231a5b66adc7a30303b2d76]
catalognumber = ""
date = "2015-04-26"
album = "ろりんくる"
tracks = [
    [1, "ろりりん☆ろりんくる", "ちょこ みるく", 1],
    [2, "第二次あにまるぱんちゅ大戦ρ", "ちょこ みるく", 1],
    [3, "ちゅ～してくれなきゃヤダヤダ！", "ちょこ みるく", 2],
    [4, "えんじょぃｘえんじょぃ feat.twinkle", "ちょこ みるく", 1],
    [5, "ろり～た☆えんじん", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5786"]

[76c17e36c0e58d52e7bec8f54220eb7a]
catalognumber = ""
date = "2015-08-16"
album = "夏Koiゆかた☆ふぇぇ…スティバル！"
tracks = [
    [1, "夏Koiゆかた☆ふぇぇ…スティバル！", "ちょこ みるく", 1],
    [2, "夕立ロマンチカ", "ちょこ みるく", 1],
    [3, "妹慕情", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5785"]

[3570c95518252a0a8a24b0ac288cff6d]
catalognumber = ""
date = "2015-10-25"
album = "はじめてのべすとあるばむ"
tracks = [
    [1, "くるるん☆ついんくる", "ちょこ みるく", 1],
    [2, "ぐどもにもーにんっ☆", "ちょこ みるく", 1],
    [3, "夏Ｋｏｉゆかた☆ふぇぇ…スティバル！", "ちょこ みるく", 1],
    [4, "Welcome to sylvan cafe", "ちょこ みるく", 1],
    [5, "眠れないどうしよう！？", "ちょこ みるく", 1],
    [6, "第二次あにまるぱんちゅ大戦ρ", "ちょこ みるく", 1],
    [7, "ろりーた☆えんじん", "ちょこ みるく", 1],
    [8, "chokolate◆症候群", "ちょこ", 1],
    [9, "Do you need sugar and milk?", "みるく", 1],
    [10, "ラブラブ☆ツインキュア", "ちょこ みるく", 1],
    [11, "DANCExSING 舞妹♡神楽 ～神COME☆やおよろずのおにーちゃん～", "ちょこ みるく", 1],
    [12, "がおがおぴょん～くまとうさぎのための協奏曲～", "ちょこ みるく", 1],
    [13, "制服で～と☆", "ちょこ みるく", 1],
    [14, "ぷににふともも ニーソックスを添えて", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/31863"]

[5efccde88833dfb146c0af08e1dfa2fc]
catalognumber = ""
date = "2015-10-25"
album = "悪戯M♡NSTER"
tracks = [
    [1, "Halloween Party", "ちょこ みるく", 1],
    [2, "恋愛ZOMBIE♡", "ちょこ みるく", 1],
    [3, "がおがおぴょん ～beast mode～", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5784"]

[13c8204682c13949616153608ee8d902]
catalognumber = ""
date = "2015-12-31"
album = "レンズフレンズ"
tracks = [
    [1, "SuperMeganeLady", "ちょこ みるく", 1],
    [2, "∞レンズフレンズ∞", "ちょこ みるく", 1],
    [3, "わたしはめがね", "ちょこ", 1],
]
links = ["https://www.dojin-music.info/cd/5783"]

[57422d1b90cad98789a554edd691bbef]
catalognumber = ""
date = "2016-04-24"
album = "もぎたてチアファイター！"
tracks = [
    [1, "もぎたてチアファイター！", "ちょこ みるく", 1],
    [2, "ちあちああちち", "ちょこ みるく", 1],
    [3, "ゆめのあとさき", "ちょこ みるく", 1],
    [4, "みるく帝國へようこそ", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5782"]

[0058fdc00008ebe18f81307923c05929]
catalognumber = ""
date = "2016-08-14"
album = "cream☆soda"
tracks = [
    [1, "cream☆soda", "ちょこ ほたる", 0],
]
links = ["https://www.dojin-music.info/cd/24534"]

[5f9117e7bf505c8d2a8f99d7381bf89d]
catalognumber = ""
date = "2016-10-30"
album = "ぷり～ずちゅ～ずみぃ☆"
tracks = [
    [1, "please choose me", "ちょこ みるく", 1],
    [2, "ZOOっとZOOっと", "ちょこ みるく", 1],
    [3, "Ferris Wheel Lovin'", "ちょこ みるく", 2],
    [4, "ぷり～ずちゅ～ずみぃ☆", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5781"]

[fc72348674dd2c8011e3ceafc151d823]
catalognumber = ""
date = "2016-12-31"
album = "怪盗ツインクル"
tracks = [
    [1, "怪盗ツインクル ～キングサーモンの涙 いただき計画♡～", "ちょこ みるく", 1],
    [2, "maiden love", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5777"]

[a9dc5dce4e6b0277ef832e5a43470129]
catalognumber = ""
date = "2017-04-30"
album = "ろりんくるにーっ！"
tracks = [
    [1, "Angel Fall", "", 1],
    [2, "幼天使再臨～地上のおにーちゃんに告ぐ～", "ちょこ みるく", 1],
    [3, "第三次あにまるぱんちゅ大戦α", "ちょこ みるく", 1],
    [4, "ろりんくる式☆少子化対策", "ちょこ みるく", 1],
    [5, "ろりーた☆えんじんturbo ～lolita's high～", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5780"]

[60e8b12e655222dcdd3322438a525d48]
catalognumber = ""
date = "2017-10-29"
album = "てんこい"
tracks = [
    [1, "twinkle stories", "ちょこ みるく", 1],
    [2, "School Girl's REVOLUTION", "ちょこ みるく", 1],
    [3, "春うらら", "ちょこ みるく", 1],
    [4, "あいのことば", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5779"]

[5afaaa0858b56c4444f362b3591d4e27]
catalognumber = ""
date = "2017-11-04"
album = "twinkle はじめてのベストアルバム＋"
tracks = [
    [1, "くるるん☆ついんくる", "twinkle", 1],
    [2, "ぐどもにもーにんっ☆", "twinkle", 1],
    [3, "夏koiゆかた☆ふぇぇ…スティバル！", "twinkle", 1],
    [4, "Welcome to sylvan cafe", "twinkle", 1],
    [5, "眠れないどうしよう！？", "twinkle", 1],
    [6, "第二次あにまるぱんちゅ大戦ρ", "twinkle", 1],
    [7, "ろりーた☆えんじん", "twinkle", 1],
    [8, "chokolate◆症候群", "twinkle", 1],
    [9, "Do you need sugar and milk?", "twinkle", 1],
    [10, "ラブラブ☆ツインキュア", "twinkle", 1],
    [11, "DANCExSING 舞妹♡神楽 〜神COMEやおよろずのおにーちゃん〜", "twinkle", 1],
    [12, "がおがおぴょん 〜くまとうさぎのための協奏曲〜", "twinkle", 1],
    [13, "制服で〜と☆", "twinkle", 1],
    [14, "ぷににふともも 〜ニーソックスを添えて〜", "twinkle", 1],
    [15, "はじめてのクリスマス", "twinkle", 1],
    [16, "ツインテでぶたれたいかい！？", "twinkle", 1],
    [17, "妹のしゅーくりぃむほんとに食べちゃうの！？", "twinkle", 1],
]
links = ["https://beta.musicbrainz.org/release/e2840711-ac8c-4e1f-8cab-2ddd1a3c4ee5"]

[8a60f9af5052bf39fe2921d610f7b210]
catalognumber = ""
date = "2017-12-29"
album = "twinkleの湯けむり旅日記。～みちのく編～"
tracks = [
    [1, "おんせん♨ぱらだいす", "ちょこ みるく", 1],
    [2, "銀河系より関西系！？しゃべくりアイドルついんくる☆なんでやねん", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5778"]

[03f87250feca56455bf4e5bedf339cac]
catalognumber = ""
date = "2018-04-29"
album = "初恋ぱてぃしえ～る"
tracks = [
    [1, "初恋ぱてぃしえ～る", "ちょこ みるく", 1],
    [2, "バグ♡ドキ", "ちょこ みるく", 1],
    [3, "すきぴ", "ちょこ みるく", 1],
    [4, "きゅんきゅん♡ぱんでみっく", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5776"]

[62829bf54638e569887cc5eeef987b64]
catalognumber = ""
date = "2018-08-10"
album = "名探偵ツインクル"
tracks = [
    [1, "starry mystery", "ちょこ みるく", 1],
    [2, "消えたラブレターの謎", "ちょこ みるく", 1],
    [3, "ボイスドラマ 探偵ツインクル～はじめての大事件～", "", 1],
]
links = ["https://www.dojin-music.info/cd/5775"]

[c9c77678f154a58dceca71d5d4af7cfd]
catalognumber = ""
date = "2018-10-28"
album = "ふぇありぃめろでぃ"
tracks = [
    [1, "prologue", "", 1],
    [2, "ツインテイルファンタジー§見習い勇者とせっかち妖精の不思議な冒険", "ちょこ みるく", 1],
    [3, "Fairies may be hiding in your room", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5774"]

[67d7ae22d7da0271e50d52a563906dff]
catalognumber = ""
date = "2018-12-30"
album = "ついんくるのべすと"
tracks = [
    [1, "twinkle stories", "twinkle", 2],
    [2, "maiden love", "twinkle", 2],
    [3, "ちあちああちち", "twinkle", 1],
    [4, "幼天使再臨 〜地上のおにーちゃんに告ぐ〜", "twinkle", 2],
    [5, "ろりーた☆えんじん turbo 〜lolita’s high〜", "twinkle", 1],
    [6, "ぷりーずちゅーずみぃ☆", "twinkle", 1],
    [7, "Halloween Party", "twinkle", 1],
    [8, "Super Megane Lady", "twinkle", 1],
    [9, "銀河系より関西系！？ しゃべくりアイドルついんくる☆なんでやねん", "twinkle", 1],
    [10, "第三次あにまるぱんちゅ大戦α", "twinkle", 1],
    [11, "starry mystery", "twinkle", 1],
    [12, "初恋ぱてぃしえ〜る", "twinkle", 1],
    [13, "Fairies may be hiding in your room", "twinkle", 1],
    [14, "もぎたてチアファイター！", "twinkle", 1],
    [15, "あいのことば", "twinkle", 1],
    [16, "きゅんきゅん☆ぱんでみっく", "twinkle", 1],
]
links = ["https://beta.musicbrainz.org/release/33af4ad7-4bda-41a0-a888-44091e6f0b51"]

[ba89e10d9f951e38d27ad57b55753185]
catalognumber = ""
date = "2019-04-28"
album = "ろりんくるFINAL"
tracks = [
    [1, "Angel Refall", "", 1],
    [2, "幼天使は三度舞い降りる", "ちょこ みるく", 1],
    [3, "超幼女合体☆ロリンクルガーＺ", "ちょこ みるく", 1],
    [4, "第四次あにまるぱんちゅ大戦Ν", "ちょこ みるく", 1],
    [5, "ろりーた☆えんじん twinturbo～final ignition", "ちょこ みるく", 1],
    [6, "らんどせるんば feat.twinkle", "ちょこ みるく", 1],
]
links = ["https://www.dojin-music.info/cd/5763"]

[76a969ba19b74bcd4cb056a00194dee3]
catalognumber = ""
date = "2019-08-12"
album = "夏色ラプソディ"
tracks = [
    [1, "夏色ラプソディ", "ちょこ みるく", 1],
    [2, "恋愛ZOMBIE ちょこVer", "ちょこ", 1],
    [3, "すいーつすいーつらぶ みるくVer", "みるく", 1],
    [4, "制服で～と♡ ちょこVer", "ちょこ", 1],
    [5, "制服で～と♡ みるくVer", "みるく", 1],
]
links = ["https://www.dojin-music.info/cd/7130"]

[2a633055a237dcc8854e9187729d8733]
catalognumber = ""
date = "2019-10-27"
album = "うきうき☆GAKUENふぇすてぃぼー！"
tracks = [
    [1, "うきうき☆GAKUENふぇすてぃぼー！", "ちょこ みるく", 2],
    [2, "ミスコン♡ラブバトラーズ", "ちょこ みるく", 1],
    [3, "Do you need sugar and milk?(2019)", "みるく", 1],
    [4, "chokolate◆症候群(2019)", "ちょこ", 1],
]
links = ["https://www.dojin-music.info/cd/14093"]

[0234ad2d33162216bf1caf911d19a049]
catalognumber = ""
date = "2020-03-01"
album = "こいこい♡ひなまつり"
tracks = [
    [1, "こいこい♡ひなまつり", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/24531"]

[ddabaf81ab78fd8491aeecaa0ea08e94]
catalognumber = ""
date = "2022-04-24"
album = "こいこい♡ひなまつり"
tracks = [
    [1, "こいこい♡ひなまつり", "ちょこ みるく", 0],
    [2, "おはなばたけLOVE♡", "ちょこ みるく", 0],
    [3, "さくらメランコリー", "ちょこ みるく", 0],
    [4, "はっぴーばーすでぃ", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/26970"]

[a1c4e2bff78038fd01128e265e1df0c9]
catalognumber = ""
date = "2022-08-13"
album = "ついんくるのべすとあるばむ さんはいっ♡"
tracks = []
links = ["https://www.dojin-music.info/cd/28013"]

[acdbd1684419c94b99c23a5844481a0b]
catalognumber = ""
date = "2023-03-07"
album = "ついんくるのべすとあるばむ さんはいっ"
tracks = [
    [1, "どきどき♡どっきん法違反", "twinkle", 0],
    [2, "夏色ラプソディ", "twinkle", 1],
    [3, "ツインテイルファンタジー", "twinkle", 0],
    [4, "おにーちゃんのこれくしょん", "twinkle", 1],
    [5, "ぱじゃま☆あいどる", "twinkle", 1],
    [6, "ZOOっとZOOっと", "twinkle", 1],
    [7, "ツインテでぶたれたいかい！？", "twinkle", 1],
    [8, "がおがおぴょん 〜beast mode〜", "twinkle", 1],
    [9, "怪盗ツインクル〜『キングサーモンの涙』いただき計画♪〜", "twinkle", 1],
    [10, "消えたラブレターの謎", "twinkle", 1],
    [11, "すきぴ", "twinkle", 1],
    [12, "みるく帝國へようこそ", "twinkle", 1],
    [13, "夕立ロマンチカ", "twinkle", 1],
    [14, "ゆめのあとさき", "twinkle", 1],
    [15, "きみといると", "twinkle", 1],
    [16, "恋の進捗どうですか？", "twinkle", 1],
]
links = ["https://beta.musicbrainz.org/release/d6971b98-40b7-457b-b52c-29785e1948af"]
