[10287c5708d580331599a75171632a28]
catalognumber = ""
date = "2013-08-12"
album = "twinkle はじめてのしんぐる…"
tracks = [
    [1, "ぷににふともも ニーソックスを添えて", "ちょこ みるく", 0],
    [2, "妹のしゅーくりぃむ ほんとに食べちゃうの！？", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5793"]

[48dbf00020919572a16630cd8523e2a1]
catalognumber = ""
date = "2013-10-27"
album = "twinkle"
tracks = [
    [1, "くるるん☆ついんくる", "ちょこ", 0],
    [2, "はじめてのクリスマス", "ちょこ みるく", 0],
    [3, "ツインテでぶたれたいかい！？", "みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5792"]

[86ffa4ff90e724100dd699610f87bd87]
catalognumber = ""
date = "2013-12-31"
album = "せーふく♀これくしょん"
tracks = [
    [1, "制服で～と☆", "ちょこ みるく", 0],
    [2, "きみといると feat.twinkle", "ちょこ みるく", 0],
    [3, "おにーちゃんのこれくしょん", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5791"]

[ae0bcb74b7a26b78641b38955eff9548]
catalognumber = ""
date = "2014-04-27"
album = "ぱじゃま de あ・そ・ぼ"
tracks = [
    [1, "ぐどもにもーにんっ☆", "ちょこ みるく", 0],
    [2, "眠れない どーしよう！？", "ちょこ みるく", 0],
    [3, "ぱじゃま☆あいどる", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5790"]

[66cacf59ab6a3324194f9f94e0083e55]
catalognumber = ""
date = "2014-08-17"
album = "ラブラブ☆ツインキュア"
tracks = [
    [1, "ラブラブ☆ツインキュア", "ちょこ みるく", 0],
    [2, "ふたりできゅあきゅあ", "ちょこ みるく", 0],
    [3, "chokolate◆症候群", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5789"]

[7bf66c4d779c9e2954277c86fc98feba]
catalognumber = ""
date = "2014-10-26"
album = "ついんくるカフェ"
tracks = [
    [1, "Welcome to sylvan cafe", "ちょこ みるく", 0],
    [2, "すいーつすいーつらぶ feat.twinkle", "ちょこ みるく", 0],
    [3, "がおがおぴょん", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5788"]

[ad5c563da659cef03e3230ef257e5521]
catalognumber = ""
date = "2014-12-30"
album = "僕の妹に巫女服を着せた結果！？"
tracks = [
    [1, "DANCExSING 舞妹♡神楽 ～神COME☆やおよろずのおにーちゃん～", "ちょこ みるく", 0],
    [2, "恋の進捗どうですか？", "ちょこ みるく", 0],
    [3, "Do you need sugar and milk?", "みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5787"]

[87c9f10392cf5cb0fa673482cc34c827]
catalognumber = ""
date = "2015-04-26"
album = "ろりんくる"
tracks = [
    [1, "ろりりん☆ろりんくる", "ちょこ みるく", 0],
    [2, "第二次あにまるぱんちゅ大戦ρ", "ちょこ みるく", 0],
    [3, "ちゅ～してくれなきゃヤダヤダ！", "ちょこ みるく", 0],
    [4, "えんじょぃｘえんじょぃ feat.twinkle", "ちょこ みるく", 0],
    [5, "ろり～た☆えんじん", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5786"]

[e66d9369baea8149a536ea0e47556ab9]
catalognumber = ""
date = "2015-08-16"
album = "夏Koiゆかた☆ふぇぇ…スティバル！"
tracks = [
    [1, "夏Koiゆかた☆ふぇぇ…スティバル！", "ちょこ みるく", 0],
    [2, "夕立ロマンチカ", "ちょこ みるく", 0],
    [3, "妹慕情", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5785"]

[7b574c596d46b2da5d99e2f41ec9158d]
catalognumber = ""
date = "2015-10-25"
album = "はじめてのべすとあるばむ"
tracks = [
    [1, "くるるん☆ついんくる", "ちょこ みるく", 0],
    [2, "ぐどもにもーにんっ☆", "ちょこ みるく", 0],
    [3, "夏Ｋｏｉゆかた☆ふぇぇ…スティバル！", "ちょこ みるく", 0],
    [4, "Welcome to sylvan cafe", "ちょこ みるく", 0],
    [5, "眠れないどうしよう！？", "ちょこ みるく", 0],
    [6, "第二次あにまるぱんちゅ大戦ρ", "ちょこ みるく", 0],
    [7, "ろりーた☆えんじん", "ちょこ みるく", 0],
    [8, "chokolate◆症候群", "ちょこ", 0],
    [9, "Do you need sugar and milk?", "みるく", 0],
    [10, "ラブラブ☆ツインキュア", "ちょこ みるく", 0],
    [11, "DANCExSING 舞妹♡神楽 ～神COME☆やおよろずのおにーちゃん～", "ちょこ みるく", 0],
    [12, "がおがおぴょん～くまとうさぎのための協奏曲～", "ちょこ みるく", 0],
    [13, "制服で～と☆", "ちょこ みるく", 0],
    [14, "ぷににふともも ニーソックスを添えて", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/31863"]

[99ba9b521cc8f6960b8d31a4965b8612]
catalognumber = ""
date = "2015-10-25"
album = "悪戯M♡NSTER"
tracks = [
    [1, "Halloween Party", "ちょこ みるく", 0],
    [2, "恋愛ZOMBIE♡", "ちょこ みるく", 0],
    [3, "がおがおぴょん ～beast mode～", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5784"]

[2588b66a43ec3f20f06cf6a6ebc6e828]
catalognumber = ""
date = "2015-12-31"
album = "レンズフレンズ"
tracks = [
    [1, "SuperMeganeLady", "ちょこ みるく", 0],
    [2, "∞レンズフレンズ∞", "ちょこ みるく", 0],
    [3, "わたしはめがね", "ちょこ", 0],
]
links = ["https://www.dojin-music.info/cd/5783"]

[258dd36ba96628ad66c66ff763e4c4bd]
catalognumber = ""
date = "2016-04-24"
album = "もぎたてチアファイター！"
tracks = [
    [1, "もぎたてチアファイター！", "ちょこ みるく", 0],
    [2, "ちあちああちち", "ちょこ みるく", 0],
    [3, "ゆめのあとさき", "ちょこ みるく", 0],
    [4, "みるく帝國へようこそ", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5782"]

[0058fdc00008ebe18f81307923c05929]
catalognumber = ""
date = "2016-08-14"
album = "cream☆soda"
tracks = [
    [1, "cream☆soda", "ちょこ ほたる", 0],
]
links = ["https://www.dojin-music.info/cd/24534"]

[4d41a8942bd864f6b05d92c890e27fa9]
catalognumber = ""
date = "2016-10-30"
album = "ぷり～ずちゅ～ずみぃ☆"
tracks = [
    [1, "please choose me", "ちょこ みるく", 0],
    [2, "ZOOっとZOOっと", "ちょこ みるく", 0],
    [3, "Ferris Wheel Lovin'", "ちょこ みるく", 0],
    [4, "ぷり～ずちゅ～ずみぃ☆", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5781"]

[830d0af7d211210a6eeec5f0f6bc3e52]
catalognumber = ""
date = "2016-12-31"
album = "怪盗ツインクル"
tracks = [
    [1, "怪盗ツインクル ～キングサーモンの涙 いただき計画♡～", "ちょこ みるく", 0],
    [2, "maiden love", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5777"]

[179be4a429a86c5341cf564b9bbee1cb]
catalognumber = ""
date = "2017-04-30"
album = "ろりんくるにーっ！"
tracks = [
    [1, "Angel Fall", "", 0],
    [2, "幼天使再臨～地上のおにーちゃんに告ぐ～", "ちょこ みるく", 0],
    [3, "第三次あにまるぱんちゅ大戦α", "ちょこ みるく", 0],
    [4, "ろりんくる式☆少子化対策", "ちょこ みるく", 0],
    [5, "ろりーた☆えんじんturbo ～lolita's high～", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5780"]

[cd3d5c79b6e771aede070e712b3125df]
catalognumber = ""
date = "2017-10-29"
album = "てんこい"
tracks = [
    [1, "twinkle stories", "ちょこ みるく", 0],
    [2, "School Girl's REVOLUTION", "ちょこ みるく", 0],
    [3, "春うらら", "ちょこ みるく", 0],
    [4, "あいのことば", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5779"]

[45b98371df13e085ecf483c33465d6e8]
catalognumber = ""
date = "2017-11-04"
album = "twinkle はじめてのベストアルバム＋"
tracks = [
    [1, "くるるん☆ついんくる", "twinkle", 0],
    [2, "ぐどもにもーにんっ☆", "twinkle", 0],
    [3, "夏koiゆかた☆ふぇぇ…スティバル！", "twinkle", 0],
    [4, "Welcome to sylvan cafe", "twinkle", 0],
    [5, "眠れないどうしよう！？", "twinkle", 0],
    [6, "第二次あにまるぱんちゅ大戦ρ", "twinkle", 0],
    [7, "ろりーた☆えんじん", "twinkle", 0],
    [8, "chokolate◆症候群", "twinkle", 0],
    [9, "Do you need sugar and milk?", "twinkle", 0],
    [10, "ラブラブ☆ツインキュア", "twinkle", 0],
    [11, "DANCExSING 舞妹♡神楽 〜神COMEやおよろずのおにーちゃん〜", "twinkle", 0],
    [12, "がおがおぴょん 〜くまとうさぎのための協奏曲〜", "twinkle", 0],
    [13, "制服で〜と☆", "twinkle", 0],
    [14, "ぷににふともも 〜ニーソックスを添えて〜", "twinkle", 0],
    [15, "はじめてのクリスマス", "twinkle", 0],
    [16, "ツインテでぶたれたいかい！？", "twinkle", 0],
    [17, "妹のしゅーくりぃむほんとに食べちゃうの！？", "twinkle", 0],
]
links = ["https://beta.musicbrainz.org/release/e2840711-ac8c-4e1f-8cab-2ddd1a3c4ee5"]

[95fcb50656fbafe5db1ce49cf9de98b9]
catalognumber = ""
date = "2017-12-29"
album = "twinkleの湯けむり旅日記。～みちのく編～"
tracks = [
    [1, "おんせん♨ぱらだいす", "ちょこ みるく", 0],
    [2, "銀河系より関西系！？しゃべくりアイドルついんくる☆なんでやねん", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5778"]

[019f29ad5d68a5bba0bd805665f8bec3]
catalognumber = ""
date = "2018-04-29"
album = "初恋ぱてぃしえ～る"
tracks = [
    [1, "初恋ぱてぃしえ～る", "ちょこ みるく", 0],
    [2, "バグ♡ドキ", "ちょこ みるく", 0],
    [3, "すきぴ", "ちょこ みるく", 0],
    [4, "きゅんきゅん♡ぱんでみっく", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5776"]

[2f809e671f8036679b7137377e2f3281]
catalognumber = ""
date = "2018-08-10"
album = "名探偵ツインクル"
tracks = [
    [1, "starry mystery", "ちょこ みるく", 0],
    [2, "消えたラブレターの謎", "ちょこ みるく", 0],
    [3, "ボイスドラマ 探偵ツインクル～はじめての大事件～", "", 0],
]
links = ["https://www.dojin-music.info/cd/5775"]

[38f7e3075bcea73196b2d685db2f2604]
catalognumber = ""
date = "2018-10-28"
album = "ふぇありぃめろでぃ"
tracks = [
    [1, "prologue", "", 0],
    [2, "ツインテイルファンタジー§見習い勇者とせっかち妖精の不思議な冒険", "ちょこ みるく", 0],
    [3, "Fairies may be hiding in your room", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5774"]

[61c86af8d2c90ecaa441cadb62e54420]
catalognumber = ""
date = "2018-12-30"
album = "ついんくるのべすと"
tracks = [
    [1, "twinkle stories", "twinkle", 0],
    [2, "maiden love", "twinkle", 0],
    [3, "ちあちああちち", "twinkle", 0],
    [4, "幼天使再臨 〜地上のおにーちゃんに告ぐ〜", "twinkle", 0],
    [5, "ろりーた☆えんじん turbo 〜lolita’s high〜", "twinkle", 0],
    [6, "ぷりーずちゅーずみぃ☆", "twinkle", 0],
    [7, "Halloween Party", "twinkle", 0],
    [8, "Super Megane Lady", "twinkle", 0],
    [9, "銀河系より関西系！？ しゃべくりアイドルついんくる☆なんでやねん", "twinkle", 0],
    [10, "第三次あにまるぱんちゅ大戦α", "twinkle", 0],
    [11, "starry mystery", "twinkle", 0],
    [12, "初恋ぱてぃしえ〜る", "twinkle", 0],
    [13, "Fairies may be hiding in your room", "twinkle", 0],
    [14, "もぎたてチアファイター！", "twinkle", 0],
    [15, "あいのことば", "twinkle", 0],
    [16, "きゅんきゅん☆ぱんでみっく", "twinkle", 0],
]
links = ["https://beta.musicbrainz.org/release/33af4ad7-4bda-41a0-a888-44091e6f0b51"]

[738bc388254329a8d77fee4ea260a7e0]
catalognumber = ""
date = "2019-04-28"
album = "ろりんくるFINAL"
tracks = [
    [1, "Angel Refall", "", 0],
    [2, "幼天使は三度舞い降りる", "ちょこ みるく", 0],
    [3, "超幼女合体☆ロリンクルガーＺ", "ちょこ みるく", 0],
    [4, "第四次あにまるぱんちゅ大戦Ν", "ちょこ みるく", 0],
    [5, "ろりーた☆えんじん twinturbo～final ignition", "ちょこ みるく", 0],
    [6, "らんどせるんば feat.twinkle", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/5763"]

[2f151e2b623de7969e36d0d267171fd3]
catalognumber = ""
date = "2019-08-12"
album = "夏色ラプソディ"
tracks = [
    [1, "夏色ラプソディ", "ちょこ みるく", 0],
    [2, "恋愛ZOMBIE ちょこVer", "ちょこ", 0],
    [3, "すいーつすいーつらぶ みるくVer", "みるく", 0],
    [4, "制服で～と♡ ちょこVer", "ちょこ", 0],
    [5, "制服で～と♡ みるくVer", "みるく", 0],
]
links = ["https://www.dojin-music.info/cd/7130"]

[b88a9be41dc08e99e9c40eff6aa20792]
catalognumber = ""
date = "2019-10-27"
album = "うきうき☆GAKUENふぇすてぃぼー！"
tracks = [
    [1, "うきうき☆GAKUENふぇすてぃぼー！", "ちょこ みるく", 0],
    [2, "ミスコン♡ラブバトラーズ", "ちょこ みるく", 0],
    [3, "Do you need sugar and milk?(2019)", "みるく", 0],
    [4, "chokolate◆症候群(2019)", "ちょこ", 0],
]
links = ["https://www.dojin-music.info/cd/14093"]

[0234ad2d33162216bf1caf911d19a049]
catalognumber = ""
date = "2020-03-01"
album = "こいこい♡ひなまつり"
tracks = [
    [1, "こいこい♡ひなまつり", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/24531"]

[ddabaf81ab78fd8491aeecaa0ea08e94]
catalognumber = ""
date = "2022-04-24"
album = "こいこい♡ひなまつり"
tracks = [
    [1, "こいこい♡ひなまつり", "ちょこ みるく", 0],
    [2, "おはなばたけLOVE♡", "ちょこ みるく", 0],
    [3, "さくらメランコリー", "ちょこ みるく", 0],
    [4, "はっぴーばーすでぃ", "ちょこ みるく", 0],
]
links = ["https://www.dojin-music.info/cd/26970"]

[a1c4e2bff78038fd01128e265e1df0c9]
catalognumber = ""
date = "2022-08-13"
album = "ついんくるのべすとあるばむ さんはいっ♡"
tracks = []
links = ["https://www.dojin-music.info/cd/28013"]

[c5097343f33812fde4305afb7388563d]
catalognumber = ""
date = "2023-03-07"
album = "ついんくるのべすとあるばむ さんはいっ"
tracks = [
    [1, "どきどき♡どっきん法違反", "twinkle", 0],
    [2, "夏色ラプソディ", "twinkle", 0],
    [3, "ツインテイルファンタジー", "twinkle", 0],
    [4, "おにーちゃんのこれくしょん", "twinkle", 0],
    [5, "ぱじゃま☆あいどる", "twinkle", 0],
    [6, "ZOOっとZOOっと", "twinkle", 0],
    [7, "ツインテでぶたれたいかい！？", "twinkle", 0],
    [8, "がおがおぴょん 〜beast mode〜", "twinkle", 0],
    [9, "怪盗ツインクル〜『キングサーモンの涙』いただき計画♪〜", "twinkle", 0],
    [10, "消えたラブレターの謎", "twinkle", 0],
    [11, "すきぴ", "twinkle", 0],
    [12, "みるく帝國へようこそ", "twinkle", 0],
    [13, "夕立ロマンチカ", "twinkle", 0],
    [14, "ゆめのあとさき", "twinkle", 0],
    [15, "きみといると", "twinkle", 0],
    [16, "恋の進捗どうですか？", "twinkle", 0],
]
links = ["https://beta.musicbrainz.org/release/d6971b98-40b7-457b-b52c-29785e1948af"]
