[fb9f185f9af046a4686682013c63263e]
catalognumber = ""
date = "2002-06-26"
album = "426 ORIGINAL SOUND TRACK"
tracks = [
    [1, "はじまり", "V.A.", 0],
    [1, "暴走", "V.A.", 0],
    [2, "不動洋菓子学校", "V.A.", 0],
    [2, "胎動", "V.A.", 0],
    [3, "目覚めのあさ", "V.A.", 0],
    [3, "日常", "V.A.", 0],
    [4, "日常", "V.A.", 0],
    [4, "逍遥", "V.A.", 0],
    [5, "あっ!", "V.A.", 0],
    [5, "静寂", "V.A.", 0],
    [6, "ハツラツ", "V.A.", 0],
    [6, "感傷", "V.A.", 0],
    [7, "ほんわか", "V.A.", 0],
    [7, "哀愁", "V.A.", 0],
    [8, "優雅", "V.A.", 0],
    [8, "侵蝕", "V.A.", 0],
    [9, "威厳", "V.A.", 0],
    [9, "衝動", "V.A.", 0],
    [10, "おもい", "V.A.", 0],
    [10, "迷宮", "V.A.", 0],
    [11, "たのしいひととき", "V.A.", 0],
    [11, "突破", "V.A.", 0],
    [12, "みんなでいっしょに", "V.A.", 0],
    [12, "策略", "V.A.", 0],
    [13, "レディ!", "V.A.", 0],
    [13, "接触", "V.A.", 0],
    [14, "ファイト", "V.A.", 0],
    [14, "疾走", "V.A.", 0],
    [15, "ティスティング", "V.A.", 0],
    [15, "抱擁", "V.A.", 0],
    [16, "これから…", "V.A.", 0],
    [16, "疑念", "V.A.", 0],
    [17, "傷心", "V.A.", 0],
    [17, "終焉", "V.A.", 0],
    [18, "やさしさ", "V.A.", 0],
    [18, "朝日の向こう", "佐藤ひろ美", 0],
    [19, "プカプカ", "U", 1],
    [19, "プカプカ (カラオケ)", "上松範康(Elements Garden)/藤間仁(Elements Garden)", 1],
    [20, "心の息吹", "V.A.", 0],
    [20, "farewells (カラオケ)", "藤間仁(Elements Garden)", 0],
    [21, "変わらぬ喧噪", "V.A.", 0],
    [21, "朝日の向こう (カラオケ)", "上松範康(Elements Garden)", 0],
    [22, "手放せぬ日常", "V.A.", 0],
    [23, "追憶", "V.A.", 0],
    [24, "現実との葛藤", "V.A.", 0],
    [25, "真実の重圧", "V.A.", 0],
    [26, "滾る思い", "V.A.", 0],
    [27, "交わりし魂", "V.A.", 0],
    [28, "死を司る者", "V.A.", 0],
    [29, "妖艶なる吐息", "V.A.", 0],
    [30, "我が道を行く", "V.A.", 0],
    [31, "飾らぬ心", "V.A.", 0],
    [32, "巡り愛", "V.A.", 0],
    [33, "全てを包む抱擁", "V.A.", 0],
    [34, "慈しむ思い", "V.A.", 0],
    [35, "世界との隔離", "V.A.", 0],
    [36, "最初で最後の人", "V.A.", 0],
    [37, "この世の果て", "V.A.", 0],
    [38, "farewells", "Faylan", 0],
]
links = ["https://music.163.com/#/album?id=240125345"]

[996301f34a89e32d2a6c7247f2dbe3cc]
catalognumber = ""
date = "2005-04-22"
album = "魔界天使ジブリール -episode 2- オープニングテーマ『LITTLE MY STAR』"
tracks = [
    [1, "LITTLE MY STAR", "U", 1],
    [2, "LITTLE MY STAR (Instrumental)", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/e428d67a-455f-45ad-bae0-d06fb7ef1bae", "https://music.163.com/#/album?id=97404718"]

[65b2376199005458434330203f5fe39f]
catalognumber = ""
date = "2005-09-16"
album = "V-HEARTS VOL.3 ～美少女PCゲーム歌曲集～"
tracks = [
    [1, "ハートにご用心", "スマイルビーム", 0],
    [2, "おやつのじかん", "安倍ようこ", 0],
    [3, "いつも一緒に", "U", 1],
    [4, "夢みてナイト！", "門脇舞以", 0],
    [5, "めびねこマーチ", "長谷川めぐみ", 0],
    [6, "冬だより", "原田ひとみ", 0],
    [7, "約束～resume～", "原田ひとみ", 0],
    [8, "☆☆☆☆☆☆", "榊原ゆい/茶谷やすら/榎津まお/春日りか/倉沢はるか", 0],
    [9, "星座の日々", "原田ひとみ", 0],
    [10, "明日の青空", "千葉由美", 0],
    [11, "君のカケラ", "美羽", 0],
    [12, "AOIRO", "美羽", 0],
    [13, "もう一度だけ", "原田ひとみ", 0],
]
links = ["https://music.163.com/#/album?id=242812882"]

[75ef94cbab75ae6c163a8efd30864554]
catalognumber = "IMAE-00006"
date = "2005-11-25"
album = "GWAVE SuperFeature's vol.2 Ultra:U"
tracks = [
    [1, "あなたのロケットで", "U", 1],
    [2, "夢見て☆エンジェル", "U", 1],
    [3, "ツナガッテルカナ？", "U", 1],
    [4, "天使の3分間クッキング ～ラーメン大好きラブリエルちゃん～", "U", 1],
    [5, "だめ？？？", "U", 1],
    [6, "Candy Pop", "U", 1],
    [7, "HAPPY ENDING", "U", 2],
    [8, "Ciao", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/41960275-bd4d-4e90-9b93-3c9fbf96a3f0", "https://music.163.com/#/album?id=2090710"]

[f686989ebd49296e667403c1c88cb086]
catalognumber = "IMAE-00010"
date = "2006-08-11"
album = "GWAVE SuperFeature's vol.4 PR Mighty Love"
tracks = [
    [1, "Mighty Love", "U", 1],
    [2, "LOVE OS", "U", 0],
    [3, "天使の5分間クッキング on the Digital", "U & ラブリエル", 1],
]
links = ["https://beta.musicbrainz.org/release/02e8390d-b522-4f3b-85f3-98d31afd24c4"]

[9ee5962c09775c6c5faddbcb9182ba57]
catalognumber = ""
date = "2006-09-29"
album = "ゲーム「めがちゅ！」オープニング＆エンディングテーマ"
tracks = [
    [1, "Help! heaven!", "U", 2],
    [2, "ツナガッテルカナ?", "U", 1],
    [3, "Help! heaven! (Instrumental)", "U", 1],
]
links = ["https://music.163.com/#/album?id=97126595"]

[3502eae8622723e336237f81e8f127f1]
catalognumber = "IMAE-00011"
date = "2006-10-27"
album = "U☆TOPIA - GWAVE SuperFeature's Vol.4"
tracks = [
    [1, "to U☆Topia -Introduction", "U", 1],
    [2, "Special Day", "U", 2],
    [3, "LITTLE MY STAR", "U", 1],
    [4, "ether trip", "U", 2],
    [5, "アナタトアタシノスナドケイハ", "U", 1],
    [6, "なの☆なの", "U", 1],
    [7, "レッゴー ラヴリィ 変身タイム!", "U", 1],
    [8, "天空merry-go-round", "U", 1],
    [9, "我愛イ尓", "U", 1],
    [10, "Mighty Love", "U", 1],
    [11, "ride on fate", "U", 1],
    [12, "Help!heaven!", "U", 1],
    [13, "あなたがSなら", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/e095db2f-6e69-44fc-9a5f-ec04425253cd", "https://music.163.com/#/album?id=2090709"]

[2eb379f9efcfd0600f537dcaf00bb53e]
catalognumber = "FRC-16E"
date = "2007-12-29"
album = "魔界天使ジブリール -episode 3- 主题歌『クルクルlovely day!!!』"
tracks = [
    [1, "クルクルlovely day!!!", "U", 2],
    [2, "クルクルlovely day!!! (カラオケ)", "U", 1],
    [3, "クルクルlovely day!!! (カラオケ・コーラス入り)", "U", 1],
    [4, "クルクルlovely day!!! Half Ver.", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/0b8f6acf-0a93-4d6e-a816-87800563a771"]

[1123e43bd35bf1c43a446097966fa24c]
catalognumber = ""
date = "2008-05-30"
album = "GWAVE SuperFeature's vol.9 \"U MY STAR -Frontwing Complete Best!!!-\""
tracks = [
    [1, "クルクルLovely day!!!", "U", 1],
    [2, "DOOR", "U", 2],
    [3, "ONLY YOUR WITCH", "U", 1],
    [4, "CHANGE OF LIFE", "U", 1],
    [5, "レッゴーラブリィ変身タイム!", "U", 1],
    [6, "プカプカ", "U", 1],
    [7, "いつも一绪に", "U", 1],
    [8, "Help! Heaven!", "U", 1],
    [9, "ツナガッテルカナ?", "U", 1],
    [10, "Little My Star", "U", 1],
    [11, "银河系の宇宙の果てまで", "U", 1],
    [12, "S・O・S ラヴ", "U", 1],
]
links = ["https://music.163.com/#/album?id=2090708"]

[b2807eece068239ab7d61ca6c1326ca0]
catalognumber = "IMAE-00023, IMAE-00023"
date = "2008-05-30"
album = "GWAVE SuperFeature's vol.9 U☆MYSTAR -Frontwing Complete Best!!!-"
tracks = [
    [1, "クルクルLovely day!!!", "U", 1],
    [2, "DOOR", "U", 1],
    [3, "ONLY YOUR WITCH", "U", 1],
    [4, "CHANGE OF LIFE", "U", 1],
    [5, "レッゴーラブリィ変身タイム!", "U", 1],
    [6, "プカプカ", "U", 1],
    [7, "いつも一緒に", "U", 1],
    [8, "Help!heaven!", "U", 1],
    [9, "ツナガッテルカナ？", "U", 1],
    [10, "LITTLE MY STAR", "U", 1],
    [11, "銀河系の宇宙の果てまで", "U", 1],
    [12, "S・O・S ラヴ", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/d40e8db9-9ba6-458c-b6be-7c221930bf5b", "https://music.163.com/#/album?id=72477"]

[c0468880d91fe3ad9ea65eccaae0708f]
catalognumber = ""
date = "2008-06-27"
album = "ゲーム「魔界天使ジブリール3」オープニング&エンディングテーマ"
tracks = [
    [1, "クルクルlovely day!!!", "U", 1],
    [2, "銀河系の宇宙の果てまで", "U", 1],
    [3, "クルクルlovely day!!! (Instrumental)", "U", 1],
    [4, "銀河系の宇宙の果てまで (Instrumental)", "U", 1],
]
links = ["https://music.163.com/#/album?id=97404257"]

[9f90f3a64bd5c8c09ff629f8d206cb52]
catalognumber = "IMAE-00028"
date = "2008-12-28"
album = "GWAVE 5th Anniversary Festa!"
tracks = [
    [1, "はーてにゃ？", "U", 2],
    [2, "love-go-round", "U", 2],
    [3, "はーてにゃ？(inst)", "U", 1],
    [4, "love-go-round(inst)", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/1409d434-2c56-463e-b484-6f170c3f0f53"]

[63ec9b045dc03ba10f524e793e6eba70]
catalognumber = "IMAE-00029"
date = "2009-03-27"
album = "GWAVE SuperFeature's vol.12 ULTRA☆U2"
tracks = [
    [1, "GO GO☆ら～びゅ", "U", 1],
    [2, "i save your place!", "U", 1],
    [3, "恋のサイエンス", "U", 1],
    [4, "Hi-Fi day", "U", 1],
    [5, "love-go-round すぺしゃるばーじょん", "U", 1],
    [6, "情熱よFly away", "U", 1],
    [7, "コトノハ ～my leaf of words～", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/8da768ba-ee97-4bbe-98cb-0a1653fd2972", "https://music.163.com/#/album?id=2090707"]

[8ec48e7e98c1fddec45b82ea5166c42a]
catalognumber = "IMAE-00037"
date = "2009-12-29"
album = "NICONICO☆BabyBaby"
tracks = [
    [1, "Nico Nico", "U", 0],
    [2, "Baby Baby", "U", 0],
    [3, "Nico Nico (karaoke)", "U", 0],
    [4, "Baby Baby (karaoke)", "U", 0],
]
links = ["https://beta.musicbrainz.org/release/f967d253-1921-44b7-b965-49e9e13eced1"]

[2b37f2742bbec6a009ab350ea6509ec4]
catalognumber = "IMAE-00039"
date = "2010-04-23"
album = "じぶりーる ふぉー♥ the first the last"
tracks = [
    [1, "the first the last", "U", 1],
    [2, "新生時～この恋ときみとあたし～", "U", 1],
    [3, "the first the last (Karaoke)", "U", 1],
    [4, "新生時～この恋ときみとあたし～ (Karaoke)", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/ab82ae84-1783-46c6-8cad-454ba23ff0f6", "https://music.163.com/#/album?id=35347380"]

[c866d4edcf2bedb3e290330d650ae130]
catalognumber = ""
date = "2011-07-29"
album = "ゲーム「戦国天使ジブリール」オープニング&エンディングテーマ"
tracks = [
    [1, "サクラ 咲ク", "U", 1],
    [2, "懐いは古今東西", "U", 1],
    [3, "サクラ 咲ク (Instrumental)", "U", 1],
    [4, "懐いは古今東西 (Instrumental)", "U", 1],
]
links = ["https://music.163.com/#/album?id=97404894"]

[2add472653ac2ff2ee33028fb2378fa7]
catalognumber = "IMAE-00049"
date = "2011-08-12"
album = "サクラ☆咲ク-戦国天使ジブリール music disc-"
tracks = [
    [1, "サクラ咲ク", "U", 1],
    [2, "懐いは古今東西", "U", 1],
    [3, "変身もも", "ピクセルビー", 1],
    [4, "ふわり、ももいろ日和", "ピクセルビー", 1],
    [5, "変身葵", "ピクセルビー", 1],
    [6, "流れる雲、青い空", "ピクセルビー", 1],
    [7, "変身ユズハ", "ピクセルビー", 1],
    [8, "ゆる～く、あせらず", "ピクセルビー", 1],
    [9, "お茶の心はホニャララ流", "ピクセルビー", 1],
    [10, "城を歩けば侍気分", "ピクセルビー", 1],
    [11, "城下町で羽を伸ばそう", "ピクセルビー", 1],
    [12, "天守から見えるもの", "ピクセルビー", 1],
    [13, "優しい匂いに包まれて", "ピクセルビー", 1],
    [14, "柔らかな月光", "ピクセルビー", 1],
    [15, "蹂躙される聖天使", "ピクセルビー", 1],
    [16, "闇に舞う異形ども", "ピクセルビー", 1],
    [17, "第六天魔王降臨", "ピクセルビー", 1],
    [18, "抜刀！合戦！ジブリール！", "ピクセルビー", 1],
    [19, "別れ 旅立ち", "ピクセルビー", 1],
    [20, "可愛い悪魔の大行進", "ピクセルビー", 1],
    [21, "サクラ咲ク (カラオケ)", "U", 1],
    [22, "懐いは古今東西 (カラオケ)", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/0d8f555c-5de5-4fdc-812c-12c720ce022a", "https://music.163.com/#/album?id=72403"]

[728e2e5d0e528506d8d408ac1a37908b]
catalognumber = "IMAE-00052"
date = "2011-09-30"
album = "GWAVE SuperFeature's vol.19 ULTRA★U -GALAXY-"
tracks = [
    [1, "ゆるしてあげないもん", "U", 1],
    [2, "はーてにゃ？", "U", 1],
    [3, "テンシノスイッチ", "U", 1],
    [4, "the first the last", "U", 1],
    [5, "きらきらきらめく", "U", 1],
    [6, "肯定☆ペンギンダンス!", "U", 1],
    [7, "NICONICO", "U", 1],
    [8, "あいのプログラム", "U", 1],
    [9, "とろとろ", "U", 1],
    [10, "like constellation", "U", 1],
    [11, "サクラ咲ク Album Remix", "U", 1],
    [12, "ぬすまれないよ", "U", 1],
    [13, "merry-go-round", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/e425837c-f173-444e-9ed6-f5ae4c435747"]

[317b056f5d3dfc5336c7040648e07a9b]
catalognumber = ""
date = "2011-09-30"
album = "GWAVE SuperFeature's vol.19 \"ULTRA U -GALAXY-\""
tracks = [
    [1, "ゆるしてあげないもん", "U", 1],
    [1, "ちょ~LOVE", "U", 1],
    [2, "はーてにゃ?", "U", 1],
    [3, "テンシノスイッチ", "U", 1],
    [4, "the first the last", "U", 1],
    [5, "きらきらきらめく", "U", 1],
    [6, "肯定☆ペンギンダンス", "U", 1],
    [7, "NICONICO", "U", 1],
    [8, "あいのプログラム", "U", 1],
    [9, "とろとろ", "U", 1],
    [10, "like constellation", "U", 1],
    [11, "サクラ咲ク Album Remix", "U", 1],
    [12, "ぬすまれないよ", "U", 1],
    [13, "merry-go-round", "U", 1],
]
links = ["https://music.163.com/#/album?id=2090706"]

[3bbb45e8cb8e0cd590d4b13e03fe2637]
catalognumber = ""
date = "2011-09-30"
album = "ULTRA☆U -GALAXY-"
tracks = [
    [1, "ゆるしてあげないもん", "U", 1],
    [2, "はーてにゃ?", "U", 1],
    [3, "テンシノスイッチ", "U", 1],
    [4, "the first the last", "U", 1],
    [5, "きらきらきらめく", "U", 1],
    [6, "肯定☆ペンギンダンス", "U", 2],
    [7, "NICONICO", "U", 1],
    [8, "あいのプログラム", "U", 1],
    [9, "とろとろ", "U", 1],
    [10, "like constellation", "U", 1],
    [11, "サクラ咲ク Album Remix", "U", 1],
    [12, "ぬすまれないよ", "U", 1],
    [13, "merry-go-round", "U", 1],
    [14, "ちょ~LOVE", "U", 1],
]
links = ["https://music.163.com/#/album?id=72400"]

[f8cc153a365e3942aa6f16e0455abf47]
catalognumber = "IMAE-00053"
date = "2011-09-30"
album = "GWAVE SuperFeature's vol.19 【ULTRA☆U -GALAXY-/Uの秘密ディスク】"
tracks = [
    [1, "ちょ～ LOVE", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/dfb3a20e-2071-405f-b4be-16c416dc19c3"]

[99544527388ccac4f25b5dab07dc1785]
catalognumber = "IMAE-00058"
date = "2011-11-29"
album = "ULTRA★U -GALAXY- 感謝祭!"
tracks = [
    [1, "かんしゃ☆かんげき", "U", 1],
    [2, "ずっと♥いっしょよ", "U", 1],
    [3, "ゆるしてあげないもん べつばーじょん", "U", 1],
    [4, "かんしゃ☆かんげき (からおけ)", "U", 1],
    [5, "ずっと♥いっしょよ (からおけ)", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/1e911ff7-f95c-4dd4-b97c-269455e458d7", "https://music.163.com/#/album?id=2389164"]

[38abb69d5c522257be0e462ad6ffccd4]
catalognumber = ""
date = "2019-07-12"
album = "アイドル魔法少女ちるちる☆みちる オリジナル・サウンドトラック"
tracks = [
    [1, "I love everyday", "U", 1],
    [2, "In my dream", "U", 1],
    [3, "strawberry on the cake", "U", 0],
    [4, "JAZZ BAR 9029", "U", 0],
    [5, "Scherzo Waltz", "U", 0],
    [6, "Useless struggle", "U", 1],
    [7, "Bonehead", "U", 0],
    [8, "ADEYAKA STREET", "ピクセルビー", 0],
    [9, "Going travelling", "ピクセルビー", 0],
    [10, "Necessary", "U", 0],
    [11, "Raison D'etre", "U", 1],
    [12, "Change Magical", "U", 1],
    [13, "Change Magical(Short ver)", "U", 1],
    [14, "Deadly sins", "U", 1],
    [15, "Great soul", "U", 1],
    [16, "MAJICK", "はな", 1],
    [17, "MAJICK -instrumental-", "藤間仁", 1],
    [18, "Love me DO!!", "茶太", 1],
    [19, "Love me DO!! -instrumental-", "U", 1],
    [20, "KISS YOU", "はな", 1],
    [21, "KISS YOU -instrumental-", "U", 1],
    [22, "KISS YOU(Duet)(game size ver)", "はな & 茶太", 1],
    [23, "KISS YOU(Duet)", "はな & 茶太", 1],
]
links = ["https://beta.musicbrainz.org/release/5765a466-3c79-42eb-a51e-004ef57bdd3e", "https://music.163.com/#/album?id=36412343"]

[ae524127e00249fe6c9da40d4f5ce1fa]
catalognumber = ""
date = "2020-07-31"
album = "ゲーム「魔界天使ジブリール4」オープニング&エンディングテーマ"
tracks = [
    [1, "the first the last", "U", 1],
    [2, "新生時 ～この恋ときみとあたし～ (Shinseiji Kono Koi To Kimi To Atashi)", "U", 1],
    [3, "the first the last (Instrumental)", "U", 1],
    [4, "新生時 ～この恋ときみとあたし～ (Shinseiji Kono Koi To Kimi To Atashi) (Instrumental)", "U", 1],
]
links = ["https://music.163.com/#/album?id=97404288"]

[66e679527972e5167a58f762b178010d]
catalognumber = ""
date = "2020-07-31"
album = "魔界天使ジブリール オープニングテーマ『レッゴーラブリー変身タイム!』"
tracks = [
    [1, "レッゴーラブリー変身タイム!", "U", 1],
    [2, "レッゴーラブリー変身タイム! (Instrumental)", "U", 1],
]
links = ["https://beta.musicbrainz.org/release/ad9cf58f-9b8b-478d-8ef2-fa987e5c00ff", "https://music.163.com/#/album?id=97403878"]

[6f0bd54dca5f191ab54ad5650444a03c]
catalognumber = ""
date = "2024-11-06"
album = "虚心の陰り"
tracks = [
    [1, "虚心の陰り", "U/Megpoid", 1],
]
links = ["https://music.163.com/#/album?id=253698749"]

[d785500f7e75faf1d80fc5f719ce5310]
catalognumber = ""
date = "2025-02-02"
album = "花咲く道"
tracks = [
    [1, "花咲く道", "U", 1],
]
links = ["https://music.163.com/#/album?id=261459251"]

[73ca5ff7831dbd50b5e36e839169ef00]
catalognumber = ""
date = "2025-02-03"
album = "過ぎ去りし季節"
tracks = [
    [1, "過ぎ去りし季節", "U", 1],
]
links = ["https://music.163.com/#/album?id=261457354"]

[7d5c5791684f423a4a105e4d69a28d52]
catalognumber = ""
date = "2025-02-04"
album = "メモリーズ"
tracks = [
    [1, "メモリーズ", "U", 1],
]
links = ["https://music.163.com/#/album?id=261455060"]

[0c2ac35681581854b91defbfa61fc07e]
catalognumber = ""
date = "2025-02-05"
album = "雲の向こうへ"
tracks = [
    [1, "雲の向こうへ", "U", 1],
]
links = ["https://music.163.com/#/album?id=261458650"]

[3cb10e418495479e5c157681f028322f]
catalognumber = ""
date = "2025-02-06"
album = "Now or Never"
tracks = [
    [1, "Now or Never", "U", 1],
]
links = ["https://music.163.com/#/album?id=261721686"]

[ef231e0e41559a20abe7fba2c3ed6cc7]
catalognumber = ""
date = "2025-02-07"
album = "風に伝わる継承"
tracks = [
    [1, "風に伝わる継承", "U", 1],
]
links = ["https://music.163.com/#/album?id=261407501"]

[a2aec2da99bc99ce56598ca9e748f6d8]
catalognumber = ""
date = "2025-02-13"
album = "そのままで…"
tracks = [
    [1, "そのままで…", "U", 1],
]
links = ["https://music.163.com/#/album?id=262074112"]

[cf071f5ce0e276e74532525d3a7a9ee6]
catalognumber = ""
date = "2025-02-17"
album = "Prophecy of the Wind"
tracks = [
    [1, "Prophecy of the Wind", "U", 1],
]
links = ["https://music.163.com/#/album?id=262728201"]

[d951e7d74470744ea7177e3d74060f6e]
catalognumber = ""
date = "2025-02-24"
album = "Cry It Out"
tracks = [
    [1, "Cry It Out", "U", 1],
]
links = ["https://music.163.com/#/album?id=263224132"]

[54b545932ddacb72c5e39e6fb4095f9f]
catalognumber = ""
date = "2025-08-16"
album = "アルナイル"
tracks = [
    [1, "アルナイル", "U/Megpoid", 0],
]
links = ["https://music.163.com/#/album?id=283198241"]

[f15f970da7142fe224329b4d28ee1698]
catalognumber = ""
date = "2025-12-08"
album = "impatience"
tracks = [
    [1, "焦燥の輪廻", "U", 1],
    [2, "憤惑の天秤", "U/GUMI", 1],
    [3, "虚心の陰り", "U/GUMI", 1],
    [4, "猜疑の舞台", "U/GUMI", 1],
    [5, "橙の鐘", "U/GUMI", 1],
    [6, "薄明の星", "U/GUMI", 1],
    [7, "空ノ心", "U", 1],
]
links = ["https://music.163.com/#/album?id=353552683"]
