[564134447641c8b2272518ee9f013701]
catalognumber = "DMPCD-001"
date = "2010-12-31"
album = "電波っぽいのっ!"
tracks = [
    [1, "sis×con", "桃箱 愛原圭織", 0],
    [2, "恋心 発生注意報～ねぇ、どっち?!～", "桃箱 愛原圭織", 0],
    [3, "専属メイド☆宣言", "桃箱 愛原圭織", 0],
    [4, "おさかな♪らぶそんぐ", "桃箱 愛原圭織", 0],
    [5, "女子力UPで恋シCHAおっ!", "桃箱 愛原圭織", 0],
    [6, "Flower", "桃箱 愛原圭織", 0],
    [7, "ジュウナンザイのうた。", "桃箱 愛原圭織", 0],
    [8, "まじかる★あだるてぃ～変身だもーん～", "桃箱 愛原圭織", 0],
    [9, "新装開店!さくらんぼ旅館", "桃箱 愛原圭織", 0],
    [10, "ちょこ せんせい ね～え?", "桃箱 愛原圭織", 0],
    [11, "はぴはぴ!くりすます", "桃箱 愛原圭織", 0],
    [12, "え?あぁ、そう。～dmp☆mix～", "桃箱 愛原圭織", 0],
]
links = ["https://www.dojin-music.info/cd/3585", "https://beta.musicbrainz.org/release/dbe8681d-e984-4118-8dca-a62f8be8203e"]

[528e4d5adeaf249f55b599e2463266fa]
catalognumber = "DMPCD-002"
date = "2011-08-13"
album = "電波LOVE"
tracks = [
    [1, "電波LOVE～でんぱあいす～", "桃箱 愛原圭織", 0],
    [2, "らじおONAIR♪", "桃箱 愛原圭織", 0],
    [3, "魔女っ子dmp☆", "桃箱 愛原圭織", 0],
    [4, "女の子どうしでちゅっちゅしましょ!", "桃箱 愛原圭織", 0],
    [5, "戦国!乙女節", "桃箱 愛原圭織", 0],
    [6, "Magical Summer", "桃箱 愛原圭織", 0],
    [7, "がーるずLoveげっちゅ!～神様には内緒だよ～", "桃箱 愛原圭織", 0],
    [8, "僕の好きな女の子。", "桃箱 愛原圭織", 0],
    [9, "突撃!となりのツンデレようじょ", "桃箱 愛原圭織", 0],
    [10, "ジュウナンザイのうた。～ぎたーかっこいいver～", "桃箱 愛原圭織", 0],
    [11, "KAGAYAKE★乙女", "桃箱 愛原圭織", 0],
]
links = ["https://www.dojin-music.info/cd/3586", "https://beta.musicbrainz.org/release/f5d604cc-c711-4a19-85e8-7a0784003d92"]

[c07a746778b4614305eaa1cfde59750f]
catalognumber = "DMPCD-003"
date = "2012-04-30"
album = "ちょこっと電波♪"
tracks = [
    [1, "ラブ☆ファンタジー", "桃箱 愛原圭織", 0],
    [2, "どち×カノっ!～選んでお願い☆～", "桃箱 愛原圭織", 0],
    [3, "恋☆愛☆禁☆止☆条☆例", "桃箱 愛原圭織", 0],
    [4, "とっとこPARADE", "桃箱", 0],
    [5, "あいろにーっ!", "愛原圭織", 0],
    [6, "planisphere", "桃箱 愛原圭織", 0],
]
links = ["https://www.dojin-music.info/cd/3587", "https://beta.musicbrainz.org/release/c14063f2-fa10-4ff0-934d-cb1b9488ef5a"]

[83af4126daceba5c2f57c5c6b2001398]
catalognumber = "DMPCD-004"
date = "2012-08-11"
album = "電波娘々"
tracks = [
    [1, "中華娘はアイヤイアイヤイヤパパパパー", "桃箱", 0],
    [2, "にゃんだふるｘふり！", "U-ske", 0],
    [3, "恋して男の娘☆", "桃箱", 0],
    [4, "おさかな♪らぶそんぐ～もぉーっと！にゃんにゃんver～", "桃箱", 0],
    [5, "Honey days～おさなづまの場合～", "桃箱", 0],
    [6, "愛しの野良猫ちゃん", "桃箱", 0],
    [7, "恋のミサイル", "桃箱", 0],
    [8, "恋☆愛☆禁☆止☆条☆例☆", "桃箱", 0],
    [9, "箱庭DAYDREAM", "桃箱", 0],
    [10, "セクシーキャットレディ", "桃箱", 0],
    [11, "ミントアイス", "桃箱", 0],
    [12, "千本桜", "", 0],
]
links = ["https://www.dojin-music.info/cd/5663", "https://beta.musicbrainz.org/release/2d076708-6bfe-470f-920b-580ea76db9bf"]

[e4d0c8656d9e7c6bde2f9ca1a2ae633f]
catalognumber = "DMPCD-005"
date = "2013-04-29"
album = "だめぽじゃないですでんぱですっ！！"
tracks = [
    [1, "セツナトリップ", "桃箱 愛原圭織", 0],
    [2, "恋愛フィロソフィア", "桃箱 愛原圭織", 0],
    [3, "聖ボーダーニーハイ学園へようこそ☆", "", 0],
    [4, "いーあるふぁんくらぶ", "桃箱 愛原圭織", 0],
    [5, "腐れ外道とチョコレイト", "桃箱 愛原圭織", 0],
    [6, "え？あぁ、そう。", "桃箱 愛原圭織", 0],
    [7, "ろりこんでよかった〜", "桃箱 愛原圭織", 0],
    [8, "秘密警察", "桃箱 愛原圭織", 0],
    [9, "千本桜", "桃箱 愛原圭織", 0],
    [10, "ハッピーシンセサイザー", "桃箱 愛原圭織", 0],
]
links = ["https://www.dojin-music.info/cd/5662", "https://beta.musicbrainz.org/release/e912b5df-5277-483d-a9ab-25086226acd8"]

[bc9353d16743ec668cd4504b4909e772]
catalognumber = "DMPCD-006"
date = "2013-08-12"
album = "電波CHU×違法"
tracks = [
    [1, "CHU＊LIP", "桃箱 愛原圭織", 0],
    [2, "トキメキエンザ流行中♪", "桃箱 愛原圭織", 0],
    [3, "クノイチでも恋がしたい", "桃箱 愛原圭織", 0],
    [4, "げつようじょ", "桃箱 愛原圭織", 0],
    [5, "Perfect Dreamer", "桃箱 愛原圭織", 0],
    [6, "さくらんぼ旅館は移転しました", "桃箱 愛原圭織", 0],
    [7, "ハニカミウサギ", "桃箱 愛原圭織", 0],
    [8, "幸せになれる隠しコマンドがあるらしい", "桃箱 愛原圭織", 0],
    [9, "ゴー！ホー！ロリ", "桃箱 愛原圭織", 0],
    [10, "専属メイド☆宣言", "桃箱 愛原圭織", 0],
    [11, "One Summer's Day", "桃箱 愛原圭織", 0],
    [12, "ジュウナンザイのうた。～オルゴールVER～ (Instrumental Ending)", "華飯", 0],
]
links = ["https://www.dojin-music.info/cd/5661", "https://beta.musicbrainz.org/release/b229b6a3-f941-4565-bbe3-748aafbb59ca"]

[70cf2b3052a8219dd43c60b8e53d6878]
catalognumber = "MMBK-003"
date = "2014-04-27"
album = "ふあふあガールフレンド(仮)"
tracks = [
    [1, "Let's go to school！", "ちぃむdmp☆", 0],
    [2, "フレンチ★KiSS desuyo.", "ちぃむdmp☆", 0],
    [3, "パッカパカーン☆マーチ～頭パッカーンしちゃいます？～", "ちぃむdmp☆", 0],
    [4, "フルーツパニック", "ちぃむdmp☆", 0],
    [5, "Honey Time", "ちぃむdmp☆", 0],
    [6, "きのこFREEDOM！！", "ちぃむdmp☆", 0],
    [7, "先生はいつも大変", "ちぃむdmp☆", 0],
    [8, "Let's go to school！（instrumental ending）", "ちぃむdmp☆", 0],
]
links = ["https://beta.musicbrainz.org/release/02bb4d69-19eb-4d86-8e04-8e88874ef6e8"]

[758c99a39fc65d193ac7da4bd21700c4]
catalognumber = "DMPCD-007"
date = "2014-08-17"
album = "でんぱSchool☆"
tracks = [
    [1, "We love school～私立dmp学園 校歌もついてます～", "桃箱 愛原圭織", 0],
    [2, "激闘！勇者vs宿題", "桃箱 愛原圭織", 0],
    [3, "Wacky Races -World B-", "桃箱 愛原圭織", 0],
    [4, "スク☆ライ～私と君とのあるある話～", "桃箱 愛原圭織", 0],
    [5, "School lunch time!", "桃箱 愛原圭織", 0],
    [6, "GO MY WAY!", "愛原圭織", 0],
    [7, "それでも単位はあきらめない", "桃箱 愛原圭織", 0],
    [8, "だって夏でしょ?しょ!～summer vacation MIX～", "桃箱", 0],
    [9, "トナリノトモダチ", "桃箱 愛原圭織", 0],
    [10, "でんぱschool☆", "桃箱 愛原圭織", 0],
]
links = ["https://www.dojin-music.info/cd/5660", "https://beta.musicbrainz.org/release/ab7aaec2-cd59-4309-8693-043740e7ba59"]

[b47377514e6ea3b2ab0ee32b0c945900]
catalognumber = "DMPCD-CDR01"
date = "2014-10-26"
album = "さくらんぼ旅館FOREVER"
tracks = [
    [1, "プロローグ", "", 0],
    [2, "さくらんぼ旅館FOREVER", "桃箱 愛原圭織", 0],
    [3, "新装開店!さくらんぼ旅館～リニューアル～", "桃箱 愛原圭織", 0],
    [4, "さくらんぼ旅館は移転しました", "", 0],
]
links = ["https://www.dojin-music.info/cd/5659", "https://beta.musicbrainz.org/release/9ade809a-492d-43d6-a775-2accf8720f5b"]
