[efe8c8bcd78471aba4ca6a27ef6c5635]
catalognumber = "QAFC-10002"
date = "2016-04-26"
album = "きみわずらい / 妄想桜"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "妄想桜", "まねきケチャ", 0],
    [3, "きみわずらい (中川美優 Vocal Ver.)", "中川美優", 0],
]
links = ["https://beta.musicbrainz.org/release/489207c7-e737-4097-9f92-38b91de8f3c6"]

[b6cbe372c8532a662d893fc927ce6168]
catalognumber = "QAFC-10005"
date = "2016-04-26"
album = "きみわずらい / 妄想桜"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "妄想桜", "まねきケチャ", 0],
    [3, "きみわずらい (宮内凛 Vocal Ver.)", "宮内凛", 0],
]
links = ["https://beta.musicbrainz.org/release/0cfe3ad2-6d53-4e98-9a1d-11d340a0eb45"]

[2f9f65c9d0cbfbe6cbf468d4c3355cb6]
catalognumber = "QAFC-10004"
date = "2016-04-26"
album = "きみわずらい / 妄想桜"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "妄想桜", "まねきケチャ", 0],
    [3, "きみわずらい (藤咲真有香 Vocal Ver.)", "藤咲真有香", 0],
]
links = ["https://beta.musicbrainz.org/release/dbb63c4d-f866-48f1-aecb-29ff5b62968d"]

[1c8bf044ff01a809ea49c7d85bd241cd]
catalognumber = "QAFC-10006"
date = "2016-04-26"
album = "きみわずらい / 妄想桜"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "妄想桜", "まねきケチャ", 0],
    [3, "きみわずらい (松下玲緒菜 Vocal Ver.)", "松下玲緒菜", 0],
]
links = ["https://beta.musicbrainz.org/release/2d9d3126-9442-433c-9032-4cd9c2add9f1"]

[b28a3f0efeed20b8d78804f2168c1767]
catalognumber = "QAFC-10003"
date = "2016-04-26"
album = "きみわずらい / 妄想桜"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "妄想桜", "まねきケチャ", 0],
    [3, "きみわずらい (藤川千愛 Vocal Ver.)", "藤川千愛", 0],
]
links = ["https://beta.musicbrainz.org/release/4219c48e-9f1c-4585-8983-93aa6c61278d"]

[b0487c9fe418a7fedb737191cbfa3469]
catalognumber = "QAFC-10001"
date = "2016-04-26"
album = "きみわずらい / 妄想桜"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "妄想桜", "まねきケチャ", 0],
    [3, "きみわずらい (Vocal Off Ver.)", "まねきケチャ", 0],
    [4, "妄想桜 (Vocal Off Ver.)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/e1c9ef27-aacb-4116-8f06-0435078ff6bc"]

[df9bf448ad9510e783c591f17726437a]
catalognumber = "QAFC-10007"
date = "2016-10-18"
album = "タイムマシン / SPLASH"
tracks = [
    [1, "タイムマシン", "まねきケチャ", 0],
    [2, "SPLASH", "まねきケチャ", 0],
    [3, "タイムマシン (Off Vocal Ver.)", "まねきケチャ", 0],
    [4, "SPLASH (Off Vocal Ver.)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/29d2e9f5-c3f1-4640-b835-dc6e7934822a"]

[293fc79238592bdc130f1778973b6545]
catalognumber = "TYCT-30065"
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "どうでもいいや (Instrumental)", "まねきケチャ", 0],
    [4, "ありきたりな言葉で (Instrumental)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/ab238bff-b861-45f5-95ac-64f047574790"]

[a8d1d599aab4114e783ece00b9a48148]
catalognumber = "TYCT-39058"
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "どうでもいいや (松下玲緒菜ソロ)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/8add0841-dd90-49eb-b7fb-42771528e8ca"]

[ef0407af2db9326fb7181292328e0573]
catalognumber = "TYCT-39054"
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "どうでもいいや (中川美優ソロ)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/1c069b0f-1f3b-4eff-ae72-1ee940bae7ca"]

[28ec11925f7ba3e15eabdbca29063986]
catalognumber = "TYCT-39056"
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "ありきたりな言葉で (藤咲真有香ソロ)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/feea5295-47af-47c1-bc33-1be852fa8cbf"]

[3551c7f8d65c591cc272284cd7974e2e]
catalognumber = "TYCT-39055"
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "どうでもいいや (藤川千愛ソロ)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/e4185273-ccbd-43cc-afaa-6abcb147ac00"]

[c68e0a228eb5fd6ad1b6a600657bcb91]
catalognumber = "TYCT-39057"
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "ありきたりな言葉で (宮内凛ソロ)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/ee6764fd-f99d-4810-a816-47db8785add0"]

[af9e5736e4eb7b2aa879ebd4e1c98e0d]
catalognumber = ""
date = "2017-06-28"
album = "どうでもいいや / ありきたりな言葉で"
tracks = [
    [1, "どうでもいいや", "まねきケチャ", 0],
    [2, "ありきたりな言葉で", "まねきケチャ", 0],
    [3, "どうでもいいや (中川美優ソロ)", "まねきケチャ", 0],
    [4, "どうでもいいや (藤川千愛ソロ)", "まねきケチャ", 0],
    [5, "ありきたりな言葉で (藤咲真有香ソロ)", "まねきケチャ", 0],
    [6, "ありきたりな言葉で (宮内凛ソロ)", "まねきケチャ", 0],
    [7, "どうでもいいや (松下玲緒菜ソロ)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/be16ec2c-93d2-4de7-a66a-42de880d90a1"]

[998fed5b37465c0c118bd3f482c44a61]
catalognumber = "COCP-40307"
date = "2018-04-18"
album = "きみわずらい"
tracks = [
    [1, "きみわずらい", "まねきケチャ", 0],
    [2, "タイムマシン", "まねきケチャ", 0],
    [3, "青息吐息", "まねきケチャ", 0],
    [4, "ありきたりな言葉で", "まねきケチャ", 0],
    [5, "奇跡", "まねきケチャ", 0],
    [6, "キミに届け", "まねきケチャ", 0],
    [7, "僕が僕を", "まねきケチャ", 0],
    [8, "カクカクシカジカ", "まねきケチャ", 0],
    [9, "一刀両断", "まねきケチャ", 0],
    [10, "妄想日記", "まねきケチャ", 0],
    [11, "キミが笑えば", "まねきケチャ", 0],
    [12, "SEVENTH HEAVEN", "まねきケチャ", 0],
    [13, "冗談じゃないね", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/01e63493-14cc-45b8-b26b-0cbf78b689ce"]

[5abf573954dd7274b67bc223e740d929]
catalognumber = "COZA-1428"
date = "2018-04-18"
album = "鏡の中から / あたしの残りぜんぶあげる Disc 1"
tracks = [
    [1, "鏡の中から", "まねきケチャ", 0],
    [2, "あたしの残りぜんぶあげる", "まねきケチャ", 0],
    [3, "ハリネズミの唄", "まねきケチャ", 0],
    [4, "鏡の中から (Instrumental)", "まねきケチャ", 0],
    [5, "あたしの残りぜんぶあげる (Instrumental)", "まねきケチャ", 0],
    [6, "ハリネズミの唄 (Instrumental)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/9d10e730-8fa5-466b-81ee-73e107d7d0ee"]

[7a86164dcbb8b6f066a24a42afc8ce77]
catalognumber = "COZA-1428"
date = "2018-04-18"
album = "鏡の中から / あたしの残りぜんぶあげる Disc 2"
tracks = [
    [1, "あたしの残りぜんぶあげる (ミュージックビデオ) (Complete Edition)", "まねきケチャ", 0],
    [2, "鏡の中から (振付映像)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/9d10e730-8fa5-466b-81ee-73e107d7d0ee"]

[7770a8385725e7c55ace4e94666de4ce]
catalognumber = "COKM-42120"
date = "2018-08-28"
album = "昨日のあたしに負けたくないの"
tracks = [
    [1, "昨日のあたしに負けたくないの", "まねきケチャ", 0],
    [2, "ありよりのあり", "まねきケチャ", 0],
    [3, "相思い", "まねきケチャ", 0],
    [4, "昨日のあたしに負けたくないの (Instrumental)", "まねきケチャ", 0],
    [5, "ありよりのあり (Instrumental)", "まねきケチャ", 0],
    [6, "相思い (Instrumental)", "まねきケチャ", 0],
    [7, "Special Track", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/3a7c80e3-05a9-4564-8486-9bef015bc04f"]

[f1d69a3cef7a111c3f1a3956e15e5333]
catalognumber = "COCA-17582"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "ジャンプ", "深瀬美桜", 0],
]
links = ["https://beta.musicbrainz.org/release/7169a244-6df8-4328-9ee5-19fd749e9baa"]

[95c73900c43838ad14d92a0d38927110]
catalognumber = "COCA-17581"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "漫画みたいに恋したい", "松下玲緒菜", 0],
]
links = ["https://beta.musicbrainz.org/release/d6fc31ee-093b-4312-a38a-f9bcb1b2fc38"]

[10ebbedf990f9e41f33598f3d68b7a97]
catalognumber = "COZA-1529"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス Disc 1"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "いつかどこかで (instrumental)", "まねきケチャ", 0],
    [5, "ワンチャンス (instrumental)", "まねきケチャ", 0],
    [6, "さよならなんて (instrumental)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/3b0b2c3f-5efc-4201-86e8-2fc66afb6a2d"]

[e1262417c1ee56dd75ba212ad33237cd]
catalognumber = "COZA-1530"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス Disc 2"
tracks = [
    [1, "いつかどこかで (MV メイキング映像)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/3b0b2c3f-5efc-4201-86e8-2fc66afb6a2d"]

[4747cf0371c4d8768578c4cfb43e2fe1]
catalognumber = "COCA-17580"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "Guess!!", "宮内凛", 0],
]
links = ["https://beta.musicbrainz.org/release/0dc33205-bac8-4f30-b9f0-666d1c302693"]

[c5128ec868120a5c1ee2e48d17d9e307]
catalognumber = "COCA-17583"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "ワンチャンス", "篠原葵", 0],
]
links = ["https://beta.musicbrainz.org/release/63c0fbca-979c-43ed-a2ab-813d0fedb855"]

[e0a184f36fe4fbfc63c2b4d766a20a7e]
catalognumber = "COCA-17579"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "虹を探しに", "中川美優", 0],
]
links = ["https://beta.musicbrainz.org/release/669e014a-1850-4f8b-86d5-613da289e25e"]

[5ee52c4129c026fb9c1abecd41b02c4e]
catalognumber = "COCA-17584"
date = "2019-03-20"
album = "いつかどこかで / ワンチャンス"
tracks = [
    [1, "いつかどこかで", "まねきケチャ", 0],
    [2, "ワンチャンス", "まねきケチャ", 0],
    [3, "さよならなんて", "まねきケチャ", 0],
    [4, "いつかどこかで (instrumental)", "まねきケチャ", 0],
    [5, "ワンチャンス (instrumental)", "まねきケチャ", 0],
    [6, "さよならなんて (instrumental)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/87ef18b7-fc53-4a6c-9a4b-bfd44f5f2e44"]

[636c54a6c70e4ff6e776e9247bec7d71]
catalognumber = "COCP-17696"
date = "2019-12-18"
album = "あるわけないの"
tracks = [
    [1, "共通項", "まねきケチャ", 0],
    [2, "君のいない世界に", "まねきケチャ", 0],
    [3, "相思い", "まねきケチャ", 0],
    [4, "あるわけないのその奥に", "まねきケチャ", 0],
    [5, "鏡の中から", "まねきケチャ", 0],
    [6, "愛と狂気とカタルシス", "まねきケチャ", 0],
    [7, "ありよりのあり", "まねきケチャ", 0],
    [8, "ジャンプ", "まねきケチャ", 0],
    [9, "妄想桜", "まねきケチャ", 0],
    [10, "漫画みたいに恋したい", "まねきケチャ", 0],
    [11, "Guess!!", "まねきケチャ", 0],
    [12, "SPLASH", "まねきケチャ", 0],
    [13, "虹を探しに", "まねきケチャ", 0],
    [14, "昨日のあたしに負けたくないの", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/eab59af9-41a2-4de8-a7fc-6d70d89a5ef4"]

[0344cb8f8757c5ad673edddb73b47df5]
catalognumber = "COZP-1601"
date = "2019-12-18"
album = "あるわけないの Disc 1"
tracks = [
    [1, "共通項", "まねきケチャ", 0],
    [2, "君のいない世界に", "まねきケチャ", 0],
    [3, "相思い", "まねきケチャ", 0],
    [4, "あるわけないのその奥に", "まねきケチャ", 0],
    [5, "鏡の中から", "まねきケチャ", 0],
    [6, "愛と狂気とカタルシス", "まねきケチャ", 0],
    [7, "ありよりのあり", "まねきケチャ", 0],
    [8, "ジャンプ", "まねきケチャ", 0],
    [9, "妄想桜", "まねきケチャ", 0],
    [10, "漫画みたいに恋したい", "まねきケチャ", 0],
    [11, "Guess!!", "まねきケチャ", 0],
    [12, "SPLASH", "まねきケチャ", 0],
    [13, "虹を探しに", "まねきケチャ", 0],
    [14, "昨日のあたしに負けたくないの", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/0bc93720-2cb3-4564-83fb-fc59e0d72c82"]

[5c343e206a07ab876791be3b3616cd49]
catalognumber = "COZP-1601"
date = "2019-12-18"
album = "あるわけないの Disc 2"
tracks = [
    [1, "あるわけないのその奥に Music Video", "まねきケチャ", 0],
    [2, "あるわけないのその奥に Music Video メイキング映像", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/0bc93720-2cb3-4564-83fb-fc59e0d72c82"]

[c3ed2b6bbaf1c5aae7fdfce81338e4b4]
catalognumber = "COCP-17697"
date = "2019-12-18"
album = "あるわけないの"
tracks = [
    [1, "共通項", "まねきケチャ", 0],
    [2, "君のいない世界に", "まねきケチャ", 0],
    [3, "相思い", "まねきケチャ", 0],
    [4, "あるわけないのその奥に", "まねきケチャ", 0],
    [5, "鏡の中から", "まねきケチャ", 0],
    [6, "愛と狂気とカタルシス", "まねきケチャ", 0],
    [7, "ありよりのあり", "まねきケチャ", 0],
    [8, "ジャンプ", "まねきケチャ", 0],
    [9, "妄想桜", "まねきケチャ", 0],
    [10, "漫画みたいに恋したい", "まねきケチャ", 0],
    [11, "Guess!!", "まねきケチャ", 0],
    [12, "SPLASH", "まねきケチャ", 0],
    [13, "虹を探しに", "まねきケチャ", 0],
    [14, "昨日のあたしに負けたくないの", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/56426953-a479-4cdc-9ae5-c56d8f69ed46"]

[66423e4b89630224e70635978bc2cb78]
catalognumber = "COCA-17876"
date = "2021-04-21"
album = "まわる世界に"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
    [3, "引き算", "まねきケチャ", 0],
    [4, "まわる世界に (中川美優 Vocal Ver.)", "中川美優", 0],
]
links = ["https://beta.musicbrainz.org/release/b972098a-65be-4a1c-ac82-25d81e7f1ddf"]

[285ef8fcb7fa71766053ddf6aaa257f0]
catalognumber = "COCA-17879"
date = "2021-04-21"
album = "まわる世界に"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
    [3, "引き算", "まねきケチャ", 0],
    [4, "まわる世界に (深瀬美桜 Vocal Ver.)", "深瀬美桜", 0],
]
links = ["https://beta.musicbrainz.org/release/a9ccd494-6888-49d5-ad48-096d304b378c"]

[0ebcdedd6eeb465bc4f277d3d66bd745]
catalognumber = "COCA-17878"
date = "2021-04-21"
album = "まわる世界に"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
    [3, "引き算", "まねきケチャ", 0],
    [4, "まわる世界に (松下玲緒菜 Vocal Ver.)", "松下玲緒菜", 0],
]
links = ["https://beta.musicbrainz.org/release/c7bb3d7c-7887-460a-bb59-b6076bb68047"]

[ac66e02071a382693e79c53900d5445a]
catalognumber = "COCA-17880"
date = "2021-04-21"
album = "まわる世界に"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
    [3, "引き算", "まねきケチャ", 0],
    [4, "まわる世界に (篠原葵 Vocal Ver.)", "篠原葵", 0],
]
links = ["https://beta.musicbrainz.org/release/489f589f-c0b6-4c90-9a06-a0bf7f8c44b3"]

[a254f3397bd6073fd30f7d874fc43abe]
catalognumber = "COZA-1745"
date = "2021-04-21"
album = "まわる世界に"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
    [3, "引き算", "まねきケチャ", 0],
    [4, "まわる世界に (Instrumental)", "まねきケチャ", 0],
    [5, "難攻不落 (Instrumental)", "まねきケチャ", 0],
    [6, "引き算 (Instrumental)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/a28b574e-2907-49be-a09a-94eed6f5c24a"]

[9237fa54dd74a7d6680f96b3025e5ac0]
catalognumber = "COZA-1746"
date = "2021-04-21"
album = "まわる世界に LINE CUBE SHIBUYAde まねきケチャ"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/a28b574e-2907-49be-a09a-94eed6f5c24a"]

[a19dccf77804683060122302f73ea91b]
catalognumber = "COCA-17877"
date = "2021-04-21"
album = "まわる世界に"
tracks = [
    [1, "まわる世界に", "まねきケチャ", 0],
    [2, "難攻不落", "まねきケチャ", 0],
    [3, "引き算", "まねきケチャ", 0],
    [4, "まわる世界に (宮内凛 Vocal Ver.)", "宮内凛", 0],
]
links = ["https://beta.musicbrainz.org/release/f2d126e5-df8a-432c-812c-459caf7f1763"]

[13afdba467e40a9dccfb9ff40c20d192]
catalognumber = "COZA-1896"
date = "2022-04-14"
album = "Awesome!"
tracks = [
    [1, "Awesome!", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/23c39e17-f722-49cc-a54b-322d8c25bfea"]

[22a37b7bc71134ed93e2a217d6f70b07]
catalognumber = "COCA-17999"
date = "2022-04-20"
album = "Awesome!"
tracks = [
    [1, "Awesome!", "まねきケチャ", 0],
    [2, "めんどくせー", "まねきケチャ", 0],
    [3, "狂気 (中川美優、松下玲緒菜、深瀬美桜 Vocal Ver.)", "まねきケチャ", 0],
    [4, "Awesome! (宮内凛、篠原葵 Vocal Ver.)", "まねきケチャ", 0],
    [5, "Awesome! (Instrumental)", "まねきケチャ", 0],
    [6, "めんどくせー (Instrumental)", "まねきケチャ", 0],
    [7, "狂気 (Instrumental)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/ca07e00a-9eab-4275-9643-f993346e17bb"]

[1ea97e8b670a69a2ff9b0e7dec3a0484]
catalognumber = "COZA-1896"
date = "2022-04-20"
album = "Awesome!"
tracks = [
    [1, "Awesome!", "まねきケチャ", 0],
    [2, "めんどくせー", "まねきケチャ", 0],
    [3, "狂気 (中川美優、松下玲緒菜、深瀬美桜 Vocal Ver.)", "まねきケチャ", 0],
    [4, "Awesome! (宮内凛、篠原葵 Vocal Ver.)", "まねきケチャ", 0],
    [5, "狂気 (中川美優 Vocal Ver.)", "まねきケチャ", 0],
    [6, "Awesome! (宮内凛 Vocal Ver.)", "まねきケチャ", 0],
    [7, "狂気 (松下玲緒菜 Vocal Ver.)", "まねきケチャ", 0],
    [8, "狂気 (深瀬美桜 Vocal Ver.)", "まねきケチャ", 0],
    [9, "Awesome! (篠原葵 Vocal Ver.)", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/8f76bc18-1eea-4b0a-adc5-a71efdfe5b4e"]

[e904ddc0a87b402f52cf400bc4cdd667]
catalognumber = ""
date = "2025-01-19"
album = "ヲタク体操アイドル謳歌"
tracks = [
    [1, "ヲタク体操アイドル謳歌", "まねきケチャ", 0],
]
links = ["https://beta.musicbrainz.org/release/d5e8b674-e1ba-4b6e-b8bb-db785fef2a69"]
