[ed470ac86bcf249cb536678125338f36]
catalognumber = ""
date = "2015-08-16"
album = "愛らぶでんぱるりるへるつ"
tracks = [
    [1, "電波ジャック★ろりろりコンプレックス", "AKICat", 0],
    [2, "ありがとうの１００円", "しふぉん", 0],
    [3, "わたしのおと", "AKICat", 0],
    [4, "ようぢょはにぃとらっぷ☆", "AKICat", 0],
    [5, "もしも魔法がつかえたら", "しふぉん", 0],
    [6, "内緒のポシェット", "しふぉん", 0],
    [7, "いたずらテレフォンぴぽぱぽぴぽぱ♪", "AKICat しふぉん", 0],
]
links = ["https://www.dojin-music.info/cd/5872"]

[4d2605e4fff5a22a273ec8c50751ae39]
catalognumber = ""
date = "2015-10-25"
album = "おでんぱおでんはおでんわで"
tracks = [
    [1, "おでんぱおでんはおでんわで", "舞園あき", 0],
    [2, "にじいろ晴れ模様", "きゃらめる", 0],
    [3, "うさぎ系女子チアソング", "しふぉん", 0],
]
links = ["https://www.dojin-music.info/cd/5871"]

[e8c63668c3a6558a193c9e730af10eb7]
catalognumber = ""
date = "2015-12-31"
album = "萌え袖注意報"
tracks = [
    [1, "届け！あぽろけっと！", "未々子", 0],
    [2, "万年床の守護者と黒き悪魔の幼女", "AKICat しふぉん", 0],
    [3, "萌え袖注意報", "ほたる", 0],
]
links = ["https://www.dojin-music.info/cd/5870"]

[fcbf455bcefcdc1f013ecd80a82ce02e]
catalognumber = ""
date = "2016-04-24"
album = "はるいちばん"
tracks = [
    [1, "割引JKせぇらちゃん", "AKICat", 0],
    [2, "また桜の咲く頃に", "AKICat", 0],
    [3, "がんちゃん", "しふぉん", 0],
]
links = ["https://www.dojin-music.info/cd/5843"]

[9fed34b76b9d79885040c51ba34921dd]
catalognumber = "RRDP-005"
date = "2016-08-14"
album = "ゆめみて"
tracks = [
    [1, "よるはこわいの", "桃箱", 0],
    [2, "おいでよ獣耳のロリ", "ちょこ", 0],
    [3, "ナイル川人間のテーマ", "秘密結社はみはみ", 0],
    [4, "絵本の君と観覧車の僕が出会って時計の針は逆方向に廻りました", "まいん", 0],
    [5, "call,in木星彼氏", "桃箱", 1],
    [6, "組曲：わたしのゆめにっき", "きゃらめる", 0],
    [7, "ぐるしゃん！", "未々子", 0],
    [8, "ちょっぴり早歩き", "AKICat", 0],
    [9, "TOOOOOOOOOFU!!!", "野々宮めぷ", 0],
    [10, "モテかわ♡アイドル計画", "ほたる & ほたるちん親衛隊（ライブは常に最前列！）", 0],
]
links = ["https://beta.musicbrainz.org/release/abf0e31c-b885-48ef-bc29-fd2b47986b6f", "https://www.dojin-music.info/cd/5809"]

[919991a4a6f4abeb4c449b5e4992a5ab]
catalognumber = ""
date = "2016-10-30"
album = "Hallo, Win Magic"
tracks = [
    [1, "Hallo, Win Magic", "野々宮めぷ", 0],
    [2, "@ra^^el|7 (Calamel banana)", "きゃらめる", 1],
    [3, "ω#！s|X＼:官○冂々 (Whisky:bonbon)", "しなもんしゅがー☆", 0],
]
links = ["https://beta.musicbrainz.org/release/1cf50de0-ac7e-4472-9c3c-7e988ec31f95", "https://www.dojin-music.info/cd/5847"]

[45c7c8741bd95b20e772340036d3bc4c]
catalognumber = ""
date = "2016-12-31"
album = "ついんふぃ～る（零）"
tracks = [
    [1, "桃色お空にまじないを 甘い想いにうらないを", "桃箱 きゃらめる", 0],
    [2, "割引愛玩女子高生 超がんちゃん.", "AKICat しふぉん", 0],
    [3, "桃色お空にまじないを 甘い想いにうらないを（Instrumental）", "", 0],
    [4, "おまけボイストラック", "", 0],
]
links = ["https://www.dojin-music.info/cd/5846"]

[b481e62e0837c30380d11b26d746d006]
catalognumber = ""
date = "2017-04-30"
album = "るりる伝記オンライン"
tracks = [
    [1, "タイトル", "こはる。", 0],
    [2, "†癒聖猫堕天使未々子にゃん†", "ラブピコヘルツ VS 未々子 & 未々子フレンズ", 0],
    [3, "デバッグ戦士「ああああ」の受難", "川名唯", 0],
    [4, "夢を見る塔", "imu", 0],
    [5, "魔王", "桃箱", 0],
    [6, "キセキノハナ", "きゃらめる", 0],
    [7, "エンディング", "こはる。", 0],
]
links = ["https://www.dojin-music.info/cd/5845"]

[7a822aeeb307750e8755386454fa5be7]
catalognumber = ""
date = "2017-08-11"
album = "寝落ち幼稚園～入園編～"
tracks = [
    [1, "ようこそ寝落ち幼稚園へ", "大山チロル 未々子 まいん まめ乃", 0],
    [2, "白昼夢", "まめ乃", 0],
    [3, "ぽきた！魔剤からの寝落ちで入園！", "大山チロル", 0],
]
links = ["https://beta.musicbrainz.org/release/63a3dd3e-b973-44cd-b925-1e7f54d58991", "https://www.dojin-music.info/cd/5842"]

[7b0a4101f5784d77d24d7c3c6afcb50b]
catalognumber = "RRDP-005"
date = "2017-11-30"
album = "ゆめみて"
tracks = [
    [1, "よるはこわいの", "るりる電波部 feat. 桃箱", 0],
    [2, "おいでよ獣耳のロリ", "るりる電波部 feat. ちょこ", 0],
    [3, "ナイル川人間のテーマ", "るりる電波部 feat. 秘密結社はみはみ & ジョセフ鶴屋", 0],
    [4, "絵本の君と観覧車の僕が出会って時計の針は逆方向に廻りました", "るりる電波部 feat. まいん", 0],
    [5, "call, in木星彼氏", "るりる電波部 feat. 桃箱", 1],
    [6, "組曲:わたしのゆめにっき", "るりる電波部 feat. きゃらめる & 夢の案内ウサギ", 0],
    [7, "ぐるしゃん!", "るりる電波部 feat. 未々子", 0],
    [8, "ちょっぴり早歩き", "るりる電波部 feat. AKICat", 0],
    [9, "TOOOOOOOOOFU!!!", "るりる電波部 feat. 野々宮めぷ", 0],
    [10, "モテかわ?アイドル計画", "るりる電波部 feat. ほたる", 0],
]
links = ["https://beta.musicbrainz.org/release/32940b2a-8b42-4cb1-9998-f6463fb77221"]

[49e9f2a5c7bd40bbc55f0c70ec958ce8]
catalognumber = ""
date = "2017-12-29"
album = "Cosmoe'pic Sensation"
tracks = [
    [1, "Cosmoe'pic Sensation", "すずしろ", 0],
    [2, "未計測@↑￣", "大山チロル", 0],
    [3, "無重力@↓＿", "ちよこ", 0],
    [4, "Cosmic hope …pheyeen（Inst）", "こはる。", 0],
]
links = ["https://www.dojin-music.info/cd/5844"]

[2e2d63c28dfa0157ab83ed177adb0539]
catalognumber = ""
date = "2018-06-01"
album = "しゃんぷー☆はっと！"
tracks = [
    [1, "極っ！しゃんぷーぱれぇど♡", "未々子", 0],
    [2, "nel.", "未々子", 0],
    [3, "未々子の婚活オタク最前線", "未々子", 0],
    [4, "おまけトラック", "", 0],
]
links = ["https://www.dojin-music.info/cd/5810"]

[6be2a89911758d621ee9ec09186a323d]
catalognumber = ""
date = "2019-04-28"
album = "えれめんぽっぷ"
tracks = [
    [1, "\"Hello World\"", "かなキ", 1],
    [2, "Pump up Cinderella Story", "みどり 未々子 しなもんしゅがー☆", 0],
    [3, "Rock☆Your Hert あきばえんじぇる♪", "こはる。", 0],
    [4, "超最先端AIカノジョいつきたん", "棗いつき", 0],
    [5, "超最優先ヤミカワAIカノジョゆのぴたん", "ゆの", 0],
    [6, "Boundary of ordinary", "溝口ゆうま", 1],
    [7, "Pathos", "Evin a'k", 0],
    [8, "Action!", "uno", 1],
    [9, "星の中の銀貨", "きゃらめる", 0],
    [10, "独奏のミスティア", "ricono", 0],
    [11, "わたのびんせん", "すずしろ", 0],
    [12, "TRIP'S→strippe", "K.AyuTAka", 0],
    [13, "しろたま", "のの", 0],
    [14, "pico2 cubic", "立秋", 0],
    [15, "今ボクの中の犬派と猫派がバトルの真っ最中 (2019 Re-Battle)", "ねこみりん", 0],
    [16, "Telling Fortune Fllower ｜い占花｜", "れにゃた", 0],
    [17, "MoonLight Stage", "月乃", 0],
    [18, "ASMR！催眠双子と共に行く天国と地獄の旅 〜忠犬お兄ちゃん編〜", "真宮ゆず 大山チロル", 1],
    [19, "合わせ鏡の恋", "閣下", 0],
    [20, "Cold Breath 〜VOCAL REMIX ver.Wishful〜", "ゆずり", 0],
    [21, "das Leben nach dem Tode", "Rabbit House", 0],
    [22, "still hesitating", "Yutaka Kouzaki", 0],
    [23, "おべんとんぐ♪〜日本国産桃色heatを添えて〜", "桃箱", 0],
    [24, "一握", "大瀬良あい", 0],
    [25, "散歩道", "閣下", 0],
    [26, "いんすた！スイーツ写真☆ヘタクソ大戦争っ！(・ω<)ノ", "一之瀬りと", 0],
    [27, "Dark Spirits", "アナザー", 0],
    [28, "シグナルほっぴんぐ！", "クワガタ", 0],
    [29, "Ringing", "溝口ゆうま", 0],
    [30, "精霊歌", "薛南", 0],
]
links = ["https://www.dojin-music.info/cd/5808"]

[31e39fc6efb8236eceb8687798c34352]
catalognumber = ""
date = "2019-10-27"
album = "るりる電波部ベスト"
tracks = [
    [1, "Hallo,Win Magic", "野々宮めぷ", 0],
    [2, "call,in木星彼氏", "桃箱", 1],
    [3, "キセキノハナ", "きゃらめる", 0],
    [4, "おでんぱおでんはおでんわで", "舞園あき", 0],
    [5, "ようこそ寝落ち幼稚園へ", "大山チロル 未々子 まいん まめ乃", 0],
    [6, "桃色お空にまじないを 甘い想いにうらないを", "桃箱 きゃらめる", 0],
    [7, "Cosmoe'pic Sensation", "すずしろ", 0],
    [8, "ぐるしゃん！", "未々子", 0],
    [9, "夢を見る塔", "imu", 0],
    [10, "細砂糖", "しなもんしゅがー☆ きゃらめる 星音チョコ", 0],
    [11, "nel.", "未々子", 0],
    [12, "Dream Experience", "月乃", 0],
    [13, "月影の輪廻曲", "大瀬良あい きゃらめる", 0],
    [14, "ゆあまいえんじぇる", "yuayua", 0],
]
links = ["https://www.dojin-music.info/cd/10420"]

[ec956a277d79f4cb1aeac3d98ec3803a]
catalognumber = ""
date = "2020-10-25"
album = "タイムカプセル"
tracks = [
    [1, "タイムカプセル", "まるもこ", 0],
]
links = ["https://www.dojin-music.info/cd/22597"]

[6fa573c0474bae885a118d247341664b]
catalognumber = ""
date = "2021-04-25"
album = "寝落ちするとこみてあげないっ！→Answer"
tracks = [
    [1, "寝落ちするとこみてあげないっ！⇨Answer", "まるもこ", 0],
    [2, "寝落ちするとこみてあげないっ！", "こはる。", 0],
]
links = ["https://www.dojin-music.info/cd/24075"]

[b88f9f2ae211fbe48a0b6800d84193c9]
catalognumber = ""
date = "2021-04-30"
album = "しゃんぷー☆はっと!"
tracks = [
    [1, "極っ!しゃんぷーぱれぇど", "るりる電波部 (feat. 未々子)", 0],
    [2, "nel.", "るりる電波部 (feat. 未々子)", 0],
    [3, "未々子の婚活オタク最前線", "るりる電波部 (feat. 未々子)", 0],
]
links = ["https://beta.musicbrainz.org/release/25711dfb-77b0-4dd0-a010-ee3922e57556"]

[45689299d9329f43afc975a1cf57e3fa]
catalognumber = ""
date = "2021-08-28"
album = "LoveFlag"
tracks = [
    [1, "LoveFlag", "まるもこ", 0],
]
links = ["https://www.dojin-music.info/cd/24586"]

[0dd92c51782b0ea256db37891cd24326]
catalognumber = ""
date = "2021-10-31"
album = "Doll"
tracks = [
    [1, "Doll", "まるもこ", 0],
]
links = ["https://www.dojin-music.info/cd/26288"]

[74bb9fde945e7c0d1ab72d6085b39a18]
catalognumber = ""
date = "2023-04-30"
album = "パラレルカプセル"
tracks = [
    [1, "パラレルカプセル", "まるもこ", 0],
    [2, "LiveMode", "まるもこ", 0],
    [3, "呪いの人形メアリーちゃん", "まるもこ", 0],
    [4, "タイムカプセル", "まるもこ", 0],
]
links = ["https://www.dojin-music.info/cd/29073"]

[59f7f95c26511f3d2b25889ae256e82d]
catalognumber = ""
date = "2024-04-28"
album = "死期祭（完全版）"
tracks = [
    [1, "黒で塗りつぶされた新規レイヤー", "りむる", 0],
    [2, "夜襲連理", "りむる", 0],
    [3, "合わせ鏡の恋_YukimiRemix_featりむる", "りむる", 0],
    [4, "散歩道_YukimiRemix_りむる", "りむる", 0],
    [5, "黒で塗りつぶされた新規レイヤー_OffVocal", "こはる。", 0],
    [6, "夜襲連理_OffVocal", "こはる。", 0],
    [7, "合わせ鏡の恋_YukimiRemix_inst", "こはる。", 0],
    [8, "散歩道_YukimiRemix_inst_", "こはる。", 0],
]
links = ["https://www.dojin-music.info/cd/31528"]
