[98845108ea607f251c7899270e2fe49a]
catalognumber = ""
date = "2011-05-01"
album = "空の下の五線譜"
tracks = [
    [1, "空の下の五線譜", "ちな", 1],
    [2, "初恋ハーモニー", "ちな", 1],
    [3, "Lavushuca", "ちな", 1],
    [4, "Girls' Communication", "ちな", 1],
    [5, "愛がくれるうた", "ちな", 1],
]
links = ["https://www.dojin-music.info/cd/3355"]

[8d3f2b5d03dce81dfdaff5677f09e750]
catalognumber = ""
date = "2011-10-30"
album = "秋風ノート"
tracks = [
    [1, "つよがりや", "ななひら", 2],
    [2, "Remeet to U", "ひななた", 1],
]
links = ["https://www.dojin-music.info/cd/9016", "https://y.qq.com/n/ryqq_v2/albumDetail/000tAjGB4dxEQF"]

[ed0b510a44d296becb813489bca44c49]
catalognumber = ""
date = "2012-04-30"
album = "宵闇のカプリス"
tracks = [
    [1, "Twinkle☆Star", "なゆ ゆきまめ", 2],
    [2, "囚われの城", "犬飼あお", 1],
    [3, "空転シティ", "仲村芽衣子", 1],
    [4, "月宵", "愛原圭織", 1],
    [5, "Starlight", "星名優子", 1],
    [6, "きみに、おやすみ", "なゆ ゆきまめ", 2],
]
links = ["https://www.dojin-music.info/cd/9017", "https://y.qq.com/n/ryqq_v2/albumDetail/0046WngS0dYSLY"]

[b1f3a75fc5640adff8dab66cd9028247]
catalognumber = ""
date = "2012-10-28"
album = "笑顔になる魔法"
tracks = [
    [1, "笑顔になる魔法", "ちな ななひら", 2],
    [2, "この一杯を、キミに。", "こっこ ひななた", 2],
    [3, "笑顔になる魔法(Instrumental)", "", 1],
    [4, "この一杯を、キミに。(Instrumental)", "", 1],
]
links = ["https://www.dojin-music.info/cd/9015", "https://y.qq.com/n/ryqq_v2/albumDetail/003HBmD91uoOf7"]

[ca4ab814902df7ce7a32f3d9bb567480]
catalognumber = ""
date = "2014-10-26"
album = "HITO＊HIRA"
tracks = [
    [1, "HITOHIRA", "深冬", 1],
    [2, "木漏れ日のカケラ", "深冬", 1],
]
links = ["https://www.dojin-music.info/cd/9018", "https://y.qq.com/n/ryqq_v2/albumDetail/003rdu0T4BXjoQ"]

[eee54d847961ec1f24a837b58c7ccbf8]
catalognumber = ""
date = "2018-04-30"
album = "キラメクオトメ"
tracks = [
    [1, "キラメクオトメ", "まめこ", 1],
    [2, "キラメクオトメ(Off Vocal)", "", 1],
]
links = ["https://www.dojin-music.info/cd/17079"]

[591bb776ebdd84f62777ade15e5dcd73]
catalognumber = ""
date = "2019-03-29"
album = "初恋レモンタルト"
tracks = [
    [1, "初恋レモンタルト", "yuayua", 1],
]
links = ["https://www.dojin-music.info/cd/17078"]

[9ef074289b41b72d4ee95ef73ee95c88]
catalognumber = ""
date = "2019-04-28"
album = "桜リフレイン"
tracks = [
    [1, "桜リフレイン", "月乃", 0],
    [2, "Spring*Step", "ちな", 0],
    [3, "Breaking Dawn", "レジ", 0],
    [4, "CALLS", "如月梢", 0],
    [5, "虹色バタフライ", "愛原圭織", 0],
    [6, "brand new day", "つゆり花鈴", 0],
    [7, "夏小路", "棗いつき", 0],
]
links = ["https://www.dojin-music.info/cd/4439"]

[585e8e1f7598d6404d2c15ad0211194a]
catalognumber = ""
date = "2020-10-25"
album = "にじいろシンフォニー"
tracks = [
    [1, "Prelude", "しの", 1],
    [2, "Shiny Morning Smiling!", "松下", 2],
    [3, "ミッドナイト・アンバー", "ricono", 1],
    [4, "miracle☆countdown", "愛原圭織", 1],
    [5, "Sail Of Star", "ちな", 1],
    [6, "螺子巻き仕掛けの御伽噺", "たねまき", 1],
    [7, "Dazzling Sky", "しの", 1],
    [8, "CLOSE TO YOU", "月乃", 1],
    [9, "ライラック", "棗いつき", 2],
    [10, "My Dear, My Dream.", "利香", 1],
    [11, "にじいろシンフォニー", "愛原圭織 たねまき ちな 月乃 棗いつき 松下 利香 ricono", 1],
]
links = ["https://www.dojin-music.info/cd/22346", "https://y.qq.com/n/ryqq_v2/albumDetail/001hLMso0fjoYg"]

[8db75ae75a2c7b5d83a70c31ec834e3c]
catalognumber = ""
date = "2024-11-13"
album = "ジャカランダ"
tracks = [
    [1, "ジャカランダ", "しの/音街鳗 (音街ウナ)", 1],
]
links = ["https://y.qq.com/n/ryqq_v2/albumDetail/003IPLPY1EuVtr"]
