[4ebeecd9227b131712e46813c4921644]
catalognumber = ""
date = "2011-05-01"
album = "空の下の五線譜"
tracks = [
    [1, "空の下の五線譜", "ちな", 0],
    [2, "初恋ハーモニー", "ちな", 0],
    [3, "Lavushuca", "ちな", 0],
    [4, "Girls' Communication", "ちな", 0],
    [5, "愛がくれるうた", "ちな", 0],
]
links = ["https://www.dojin-music.info/cd/3355"]

[4b0ed8a3726e1c47e6eb8b4886a08ddc]
catalognumber = ""
date = "2011-10-30"
album = "秋風ノート"
tracks = [
    [1, "つよがりや", "ななひら", 0],
    [2, "Remeet to U", "ひななた", 0],
]
links = ["https://www.dojin-music.info/cd/9016", "https://y.qq.com/n/ryqq_v2/albumDetail/000tAjGB4dxEQF"]

[b4cc2c95301f063498edeb99da7aab15]
catalognumber = ""
date = "2012-04-30"
album = "宵闇のカプリス"
tracks = [
    [1, "Twinkle☆Star", "なゆ ゆきまめ", 0],
    [2, "囚われの城", "犬飼あお", 0],
    [3, "空転シティ", "仲村芽衣子", 0],
    [4, "月宵", "愛原圭織", 0],
    [5, "Starlight", "星名優子", 0],
    [6, "きみに、おやすみ", "なゆ ゆきまめ", 2],
]
links = ["https://www.dojin-music.info/cd/9017", "https://y.qq.com/n/ryqq_v2/albumDetail/0046WngS0dYSLY"]

[05b600792c6b3c5dea02a93b0eaaa0c2]
catalognumber = ""
date = "2012-10-28"
album = "笑顔になる魔法"
tracks = [
    [1, "笑顔になる魔法", "ちな ななひら", 0],
    [2, "この一杯を、キミに。", "こっこ ひななた", 0],
    [3, "笑顔になる魔法(Instrumental)", "", 0],
    [4, "この一杯を、キミに。(Instrumental)", "", 0],
]
links = ["https://www.dojin-music.info/cd/9015", "https://y.qq.com/n/ryqq_v2/albumDetail/003HBmD91uoOf7"]

[0398699a34abc80782477e74e0c94742]
catalognumber = ""
date = "2014-08-14"
album = "彼女が俺にくれたもの。俺が彼女にあげるもの。オープニングテーマソング＆サウンドトラック"
tracks = [
    [1, "Sugar time＊", "日の当たる場所 (篠原瑞希)", 0],
    [2, "One's taste", "日の当たる場所 (篠原瑞希)", 0],
    [3, "~Kiss My Darling!~", "新堂真弓/眞田朱音", 0],
    [4, "HAPPY FLAVOR", "日の当たる場所 (篠原瑞希)", 0],
    [5, "The matter!!", "日の当たる場所 (篠原瑞希)", 0],
    [6, "Like!Love!Trouble!", "日の当たる場所 (篠原瑞希)", 0],
    [7, "Ah…", "日の当たる場所 (篠原瑞希)", 0],
    [8, "Pink fizzy", "日の当たる場所 (篠原瑞希)", 0],
    [9, "Dream one", "日の当たる場所 (篠原瑞希)", 0],
    [10, "Drip drop", "日の当たる場所 (篠原瑞希)", 0],
    [11, "monologuea", "日の当たる場所 (篠原瑞希)", 0],
    [12, "The bond of the two…", "日の当たる場所 (篠原瑞希)", 0],
    [13, "Let's show time!!", "日の当たる場所 (篠原瑞希)", 0],
    [14, "Tut!Tut!Tut!", "日の当たる場所 (篠原瑞希)", 0],
    [15, "Break time", "日の当たる場所 (篠原瑞希)", 0],
    [16, "YES! Princess parade", "日の当たる場所 (篠原瑞希)", 0],
    [17, "ROOT", "日の当たる場所 (篠原瑞希)", 0],
    [18, "Blend you & me", "日の当たる場所 (篠原瑞希)", 0],
    [19, "Heart sketch", "日の当たる場所 (篠原瑞希)", 0],
]
links = ["https://y.qq.com/n/ryqq_v2/albumDetail/002mgKyw1JdrKx"]

[25e8e54b85f7bb4c6b054a33756de595]
catalognumber = ""
date = "2014-10-26"
album = "HITO＊HIRA"
tracks = [
    [1, "HITOHIRA", "深冬", 0],
    [2, "木漏れ日のカケラ", "深冬", 0],
]
links = ["https://www.dojin-music.info/cd/9018", "https://y.qq.com/n/ryqq_v2/albumDetail/003rdu0T4BXjoQ"]

[9124f128c5bf6d1a91207b28309b2b48]
catalognumber = ""
date = "2018-04-30"
album = "キラメクオトメ"
tracks = [
    [1, "キラメクオトメ", "まめこ", 0],
    [2, "キラメクオトメ(Off Vocal)", "", 0],
]
links = ["https://www.dojin-music.info/cd/17079"]

[cef88cef7d555d35f4e78cd66c6e1f31]
catalognumber = ""
date = "2019-03-29"
album = "初恋レモンタルト"
tracks = [
    [1, "初恋レモンタルト", "yuayua", 0],
]
links = ["https://www.dojin-music.info/cd/17078"]

[9ef074289b41b72d4ee95ef73ee95c88]
catalognumber = ""
date = "2019-04-28"
album = "桜リフレイン"
tracks = [
    [1, "桜リフレイン", "月乃", 0],
    [2, "Spring*Step", "ちな", 0],
    [3, "Breaking Dawn", "レジ", 0],
    [4, "CALLS", "如月梢", 0],
    [5, "虹色バタフライ", "愛原圭織", 0],
    [6, "brand new day", "つゆり花鈴", 0],
    [7, "夏小路", "棗いつき", 0],
]
links = ["https://www.dojin-music.info/cd/4439"]

[60b4bceb9da8c41a5716a0a9ce650e8e]
catalognumber = ""
date = "2020-10-25"
album = "にじいろシンフォニー"
tracks = [
    [1, "Prelude", "しの", 0],
    [2, "Shiny Morning Smiling!", "松下", 0],
    [3, "ミッドナイト・アンバー", "ricono", 0],
    [4, "miracle☆countdown", "愛原圭織", 0],
    [5, "Sail Of Star", "ちな", 0],
    [6, "螺子巻き仕掛けの御伽噺", "たねまき", 0],
    [7, "Dazzling Sky", "しの", 0],
    [8, "CLOSE TO YOU", "月乃", 0],
    [9, "ライラック", "棗いつき", 0],
    [10, "My Dear, My Dream.", "利香", 0],
    [11, "にじいろシンフォニー", "愛原圭織 たねまき ちな 月乃 棗いつき 松下 利香 ricono", 0],
]
links = ["https://www.dojin-music.info/cd/22346", "https://y.qq.com/n/ryqq_v2/albumDetail/001hLMso0fjoYg"]

[1bbb9cfe2dd725836455872a0071edae]
catalognumber = ""
date = "2024-11-13"
album = "ジャカランダ"
tracks = [
    [1, "ジャカランダ", "しの/音街鳗 (音街ウナ)", 0],
]
links = ["https://y.qq.com/n/ryqq_v2/albumDetail/003IPLPY1EuVtr"]
