[83a8f5dc2f2c89d4b4d7dc79b75df59f]
catalognumber = ""
date = "2014-10-26"
album = "秘密結社はみはみ"
tracks = []
links = ["https://www.dojin-music.info/cd/6856"]

[2a18ff11b9f3b762d0f78da085300f46]
catalognumber = ""
date = "2015-10-25"
album = "凸撃！となりのはみごはん"
tracks = [
    [1, "凸撃！となりのはみごはん", "秘密結社はみはみ", 0],
    [2, "Miracle★★★★★food", "秘密結社はみはみ", 0],
    [3, "はみだせダイエット大作戦！！〜出荷寸前！？食肉系女子最後の晩餐♡〜", "秘密結社はみはみ", 0],
    [4, "凸撃！となりのはみごはん (Inst)", "秘密結社はみはみ", 0],
    [5, "はみだせダイエット大作戦！！〜出荷寸前！？食肉系女子最後の晩餐♡〜(Inst)", "秘密結社はみはみ", 0],
    [6, "凸撃となりのはみごはん！ボーナストラック", "秘密結社はみはみ", 0],
]
links = ["https://beta.musicbrainz.org/release/c099ec98-0469-41c5-b357-89efdb0d6786", "https://www.dojin-music.info/cd/6855"]

[42fcb18244b9338ccabdbaa7e8e5c356]
catalognumber = ""
date = "2015-12-31"
album = "修羅場えぶりでぃないと"
tracks = [
    [1, "修羅場えぶりでぃないと", "秘密結社はみはみ", 0],
    [2, "修羅場えぶりでぃないと (Inst)", "秘密結社はみはみ", 0],
    [3, "修羅場えぶりでぃないとボーナストラック", "秘密結社はみはみ", 0],
]
links = ["https://beta.musicbrainz.org/release/240600a6-6285-4c05-861f-c30215a5cdff", "https://www.dojin-music.info/cd/6854"]

[22a43a9453ce42a554517cfa8c8c1de1]
catalognumber = ""
date = "2016-04-24"
album = "おふはみ!"
tracks = [
    [1, "もぐはみ", "秘密結社はみはみ", 0],
    [2, "†エターナルダークポーク〜目覚めの刻〜†", "秘密結社はみはみ", 0],
    [3, "モーレツ社員！企業戦士シャチクイーン", "秘密結社はみはみ", 0],
    [4, "おやはみ", "秘密結社はみはみ", 0],
    [5, "もぐはみ(Inst)", "秘密結社はみはみ", 0],
    [6, "†エターナルダークポーク〜目覚めの刻〜†(Inst)", "秘密結社はみはみ", 0],
    [7, "モーレツ社員！企業戦士シャチクイーン(Inst)", "秘密結社はみはみ", 0],
    [8, "おやはみ(Inst)", "秘密結社はみはみ", 0],
    [9, "ボーナストラック", "秘密結社はみはみ", 0],
]
links = ["https://beta.musicbrainz.org/release/2031e34a-8154-4d30-8d30-569015a2a461", "https://www.dojin-music.info/cd/6853"]

[648e4859e32f3fb3eaf3b18bc4d53b10]
catalognumber = ""
date = "2016-10-30"
album = "秘密の謝肉祭〜シークレットカーニバル〜"
tracks = [
    [1, "飯テロ警察24時〜はみはミックス〜", "初乃葉ゆづの 豚田ひかり", 0],
    [2, "プロ結社員に御成り！〜ビーフ様とおよびなさい！〜", "初乃葉ゆづの", 0],
    [3, "じょぶちぇんっ！うわっ…私の残高、なさすぎ…？", "豚田ひかり", 0],
    [4, "はみはみハーベスト☆きのこ狩り", "初乃葉ゆづの", 0],
    [5, "飯テロ警察24時〜はみはミックス〜(inst)", "", 0],
    [6, "プロ結社員に御成り！〜ビーフ様とおよびなさい！〜(inst)", "", 0],
    [7, "じょぶちぇんっ！うわっ…私の残高、なさすぎ…？(inst)", "", 0],
    [8, "はみはみハーベスト☆きのこ狩り(inst)", "", 0],
    [9, "ボーナストラック", "", 0],
]
links = ["https://www.dojin-music.info/cd/6852"]

[271982ff495cd3334400cbae827d4685]
catalognumber = ""
date = "2017-04-30"
album = "お前らこ→ゆ→の好きなんだろっ！？"
tracks = [
    [1, "ぺこはみ", "秘密結社はみはみ", 0],
    [2, "アオハルセンセーション", "秘密結社はみはみ", 0],
    [3, "恋色sunset", "秘密結社はみはみ", 0],
    [4, "ぺこはみ（instrumental)", "秘密結社はみはみ", 0],
    [5, "アオハルセンセーション（instrumental)", "秘密結社はみはみ", 0],
    [6, "恋色sunset（instrumental)", "秘密結社はみはみ", 0],
    [7, "6thボーナストラック", "秘密結社はみはみ", 0],
]
links = ["https://beta.musicbrainz.org/release/ec93bc4a-ba5e-4e54-b369-61bfdd304b63", "https://www.dojin-music.info/cd/6851"]

[f83c2a22e8eebff9f56caf76a011008d]
catalognumber = ""
date = "2017-10-29"
album = "はぴかむっ！SweetsHunter"
tracks = [
    [1, "はぴかむっ！SweetsHunter", "初乃葉ゆづの 豚田ひかり", 0],
    [2, "はぴかむっ！SweetsHunter(Instrumental)", "", 0],
    [3, "ボーナストラック", "", 0],
]
links = ["https://www.dojin-music.info/cd/6850"]

[52c8fda7ccfabc1dcaaeca86dec35cdb]
catalognumber = ""
date = "2017-11-18"
album = "アッパレ！笑顔百景はみ日和"
tracks = [
    [1, "脂肪遊戯みぃとぼぉるるん♪～全てははみはみの手中に～", "", 0],
    [2, "アッパレ！笑顔百景はみ日和", "", 0],
    [3, "脂肪遊戯みぃとぼぉるるん♪～全てははみはみの手中に～（Instrumental）", "", 0],
    [4, "アッパレ！笑顔百景はみ日和（Instrumental）", "", 0],
    [5, "8thボーナストラック", "", 0],
]
links = ["https://www.dojin-music.info/cd/6849"]

[eab933c2430bcbbc9ced5636cecfc46e]
catalognumber = ""
date = "2018-04-29"
album = "今日もブタはユメを見る"
tracks = [
    [1, "アブLOVE♡セキユの王子様！", "豚田ひかり", 0],
    [2, "おねえちゃんといっしょに××しましょ", "豚田ひかり ちょこ", 0],
    [3, "今日もブタはユメを見る", "豚田ひかり", 0],
]
links = ["https://www.dojin-music.info/cd/5609"]
