[20370c38f4dbe5da76d581842b114a45]
catalognumber = ""
date = "2010-01-18"
album = "from Y to Y (cover)"
tracks = [
    [1, "from Y to Y (cover)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=277163004"]

[5315f13827af6f3af243a79bdac33bd5]
catalognumber = ""
date = "2014-08-22"
album = "好きなひと"
tracks = [
    [1, "未来図 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [2, "告白予行練習 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [3, "テレカクシ思春期 (feat. 鎖那)", "HoneyWorks/鎖那", 2],
    [4, "初恋の絵本 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [5, "告白ライバル宣言 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [6, "ヤキモチの答え (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [7, "イノコリ先生 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [8, "ロリババアに恋をした (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [9, "ラズベリー＊モンスター (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [10, "病名恋ワズライ", "鎖那", 0],
    [11, "おまけ音源", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=2979081"]

[94459380800e5219938d118503bfc0a6]
catalognumber = ""
date = "2014-11-15"
album = "sigh."
tracks = [
    [1, "BEYOND", "鎖那", 1],
    [2, "モカ", "鎖那", 0],
    [3, "コーヒーカップ", "鎖那", 0],
    [4, "Ryrie", "鎖那", 1],
    [5, "トラベリングムード", "鎖那", 0],
    [6, "two of us", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3111375"]

[dea8914bb72e583485d6c26b75225167]
catalognumber = ""
date = "2015-04-16"
album = "言葉のいらない約束（TV size）"
tracks = [
    [1, "言葉のいらない約束（TV size）", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=3139285"]

[6d98075717a80d6e9db6e32960ba8402]
catalognumber = ""
date = "2015-05-27"
album = "言葉のいらない約束 / 暁月夜-アカツキヅクヨ-"
tracks = [
    [1, "言葉のいらない約束", "鎖那", 0],
    [2, "暁月夜-アカツキヅクヨ-", "鎖那", 1],
    [3, "言葉のいらない約束 (Instrumetal)", "鎖那", 0],
    [4, "暁月夜 -アカツキヅクヨ- (Instrumetal)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3154377"]

[b6640772ecb8ce6d30e9310f45a46d90]
catalognumber = ""
date = "2015-12-31"
album = "(un) sentimental spica"
tracks = [
    [1, "花とクマ", "鎖那", 0],
    [2, "すきなうた", "鎖那", 0],
    [3, "さようなら、花泥棒さん (cover)", "鎖那", 2],
    [4, "転校前夜 (cover)", "鎖那", 0],
    [5, "言の葉クリニック (cover)", "鎖那", 0],
    [6, "パケットヒーロー (cover)", "鎖那", 0],
    [7, "パズルガール (cover)", "鎖那", 0],
    [8, "siawase", "鎖那", 1],
    [9, "だってキミは大切な人", "鎖那", 0],
    [10, "cantabile (cover)", "鎖那", 1],
    [11, "歩いても歩いても、夜空は僕を追いかけてくる (cover)", "鎖那", 0],
    [12, "リトルファイター", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=3439884"]

[eed1a0f1eac8a928bcbaefe20f2899c1]
catalognumber = ""
date = "2016-12-31"
album = "夏休みの転校生"
tracks = [
    [1, "夏休みの転校生", "鎖那", 2],
    [2, "さよならグッバイ (Voice Memo)", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=35314462"]

[46ab326965c9d695ecdb909922615116]
catalognumber = ""
date = "2017-09-15"
album = "花降る日々、"
tracks = [
    [1, "ニゲラの花束", "鎖那", 1],
    [2, "紫陽花、まばたき、梅雨の日。", "000", 0],
    [3, "マーガレットは眠る", "めありー", 1],
    [4, "花降るラジオ", "めありー/鎖那/000", 0],
    [5, "ニゲラの花束 (instrumental)", "鎖那", 1],
    [6, "紫陽花、まばたき、梅雨の日。 (instrumental)", "000", 0],
    [7, "マーガレットは眠る (instrumental)", "めありー", 1],
]
links = ["https://music.163.com/#/album?id=74268888"]

[bc0081d4ed05a23b8c25f7122a92628f]
catalognumber = ""
date = "2017-09-27"
album = "Hush a by little girl"
tracks = [
    [1, "さよなら、テディベア", "鎖那", 0],
    [2, "鍵っ子", "鎖那", 0],
    [3, "ひねくれ", "鎖那", 0],
    [4, "彼女は旅に出る", "鎖那", 2],
    [5, "嘘つきエミリー", "鎖那", 0],
    [6, "ginger snaps", "鎖那", 1],
    [7, "ニゲラの花束", "鎖那", 1],
    [8, "オオカミと少女", "鎖那", 0],
    [9, "宝石", "鎖那", 0],
    [10, "シュテルン", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=36303697"]

[4c7e8586322b3f43901bf02f7911487d]
catalognumber = ""
date = "2020-02-22"
album = "ハッピーでバッドな眠りは浅い"
tracks = [
    [1, "ハッピーでバッドな眠りは浅い", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=86432816"]

[ada19b95864574169a03f4bd0abf8d81]
catalognumber = ""
date = "2020-12-12"
album = "備忘録"
tracks = [
    [1, "備忘録", "鎖那", 2],
]
links = ["https://music.163.com/#/album?id=120835351"]

[ad1f773ce9f09092432aa961a854056b]
catalognumber = ""
date = "2021-02-08"
album = "LOVE LETTER with 鎖那"
tracks = [
    [1, "LOVE LETTER with 鎖那", "OCEANS/鎖那", 1],
]
links = ["https://music.163.com/#/album?id=122419490"]

[fe2e1e960ddf0590e2ade20698116b0c]
catalognumber = ""
date = "2021-07-10"
album = "tutu"
tracks = [
    [1, "tutu", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=129269500"]

[f4a20a70939b314fe90112d8ce065fc8]
catalognumber = ""
date = "2021-11-26"
album = "ベイビーヘイロー"
tracks = [
    [1, "ベイビーヘイロー", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=135678329"]

[7d9d13bf8eaf2c6cef736f7cdf4daec6]
catalognumber = ""
date = "2022-11-26"
album = "カプセル"
tracks = [
    [1, "カプセル", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=153931660"]

[c1dc09994eb69479f8de7fe7c2de6588]
catalognumber = ""
date = "2024-02-26"
album = "ラブポーション (cover)"
tracks = [
    [1, "ラブポーション (cover)", "鎖那/なゆごろう", 0],
]
links = ["https://music.163.com/#/album?id=186625731"]

[0ddb1260ad1037dbc2331a8247370232]
catalognumber = ""
date = "2025-03-10"
album = "それは内緒にしておいて (cover)"
tracks = [
    [1, "それは内緒にしておいて (cover)", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=265072970"]

[a80934fa0e96bd03e2cd4c1622e18b32]
catalognumber = ""
date = "2025-05-28"
album = "sparkle"
tracks = [
    [1, "sparkle", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=272386837"]

[b0342ffd367a393dfd843d8ebf922cc9]
catalognumber = ""
date = "2025-06-18"
album = "ラブポーション (cover) [Rearrange ver.]"
tracks = [
    [1, "ラブポーション (cover) [Rearrange ver.]", "鎖那/なゆごろう", 0],
]
links = ["https://music.163.com/#/album?id=275164204"]

[2a1314b2e9477ce9efe4829329fd0745]
catalognumber = ""
date = "2025-11-21"
album = "CLOUD HAIRPIN"
tracks = [
    [1, "1step 2step", "鎖那", 1],
    [2, "KISSIN' CLAW", "鎖那", 1],
    [3, "くらくらった", "鎖那", 1],
    [4, "ベイビーヘイロー", "鎖那", 0],
    [5, "mimicry", "鎖那", 1],
    [6, "カプセル", "鎖那", 0],
    [7, "sparkle", "鎖那", 1],
    [8, "テルテルユー", "鎖那", 0],
    [9, "tutu", "鎖那", 1],
    [10, "備忘録", "鎖那", 1],
    [11, "oh my girl", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=289131412"]
