[6fd2a57acf57527fdc71155197ae22f9]
catalognumber = ""
date = "2010-01-18"
album = "from Y to Y (cover)"
tracks = [
    [1, "from Y to Y (cover)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=277163004"]

[5c97d6d7118ab30d2b2637876ae07eb6]
catalognumber = ""
date = "2014-08-22"
album = "好きなひと"
tracks = [
    [1, "未来図 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [2, "告白予行練習 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [3, "テレカクシ思春期 (feat. 鎖那)", "HoneyWorks/鎖那", 2],
    [4, "初恋の絵本 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [5, "告白ライバル宣言 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [6, "ヤキモチの答え (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [7, "イノコリ先生 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [8, "ロリババアに恋をした (feat. 鎖那)", "HoneyWorks/鎖那", 2],
    [9, "ラズベリー＊モンスター (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [10, "病名恋ワズライ", "鎖那", 1],
    [11, "おまけ音源", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=2979081"]

[6e7fb13f7e28c71992c84948ba1c32c5]
catalognumber = ""
date = "2014-11-15"
album = "sigh."
tracks = [
    [1, "BEYOND", "鎖那", 1],
    [2, "モカ", "鎖那", 1],
    [3, "コーヒーカップ", "鎖那", 1],
    [4, "Ryrie", "鎖那", 1],
    [5, "トラベリングムード", "鎖那", 1],
    [6, "two of us", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3111375"]

[93055e018994f063db0f5ccfadac6900]
catalognumber = ""
date = "2015-04-16"
album = "言葉のいらない約束（TV size）"
tracks = [
    [1, "言葉のいらない約束（TV size）", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3139285"]

[24c948dbff2759d49e8fa0e7323d220a]
catalognumber = ""
date = "2015-05-27"
album = "言葉のいらない約束 / 暁月夜-アカツキヅクヨ-"
tracks = [
    [1, "言葉のいらない約束", "鎖那", 1],
    [2, "暁月夜-アカツキヅクヨ-", "鎖那", 1],
    [3, "言葉のいらない約束 (Instrumetal)", "鎖那", 1],
    [4, "暁月夜 -アカツキヅクヨ- (Instrumetal)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3154377"]

[2fda98434f3f427d5ab601dce52b0a51]
catalognumber = ""
date = "2015-12-31"
album = "(un) sentimental spica"
tracks = [
    [1, "花とクマ", "鎖那", 1],
    [2, "すきなうた", "鎖那", 1],
    [3, "さようなら、花泥棒さん (cover)", "鎖那", 2],
    [4, "転校前夜 (cover)", "鎖那", 1],
    [5, "言の葉クリニック (cover)", "鎖那", 1],
    [6, "パケットヒーロー (cover)", "鎖那", 1],
    [7, "パズルガール (cover)", "鎖那", 1],
    [8, "siawase", "鎖那", 1],
    [9, "だってキミは大切な人", "鎖那", 1],
    [10, "cantabile (cover)", "鎖那", 1],
    [11, "歩いても歩いても、夜空は僕を追いかけてくる (cover)", "鎖那", 1],
    [12, "リトルファイター", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3439884"]

[09c8f563c8b6f9b68f2999e41f0dec78]
catalognumber = ""
date = "2016-12-31"
album = "夏休みの転校生"
tracks = [
    [1, "夏休みの転校生", "鎖那", 2],
    [2, "さよならグッバイ (Voice Memo)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=35314462"]

[9f337efadd6883ffc154e2c3f8f6ba93]
catalognumber = ""
date = "2017-09-15"
album = "花降る日々、"
tracks = [
    [1, "ニゲラの花束", "鎖那", 1],
    [2, "紫陽花、まばたき、梅雨の日。", "000", 1],
    [3, "マーガレットは眠る", "めありー", 1],
    [4, "花降るラジオ", "めありー/鎖那/000", 1],
    [5, "ニゲラの花束 (instrumental)", "鎖那", 1],
    [6, "紫陽花、まばたき、梅雨の日。 (instrumental)", "000", 1],
    [7, "マーガレットは眠る (instrumental)", "めありー", 1],
]
links = ["https://music.163.com/#/album?id=74268888"]

[dbcfaaeb18312e91882a595831698c11]
catalognumber = ""
date = "2017-09-27"
album = "Hush a by little girl"
tracks = [
    [1, "さよなら、テディベア", "鎖那", 1],
    [2, "鍵っ子", "鎖那", 1],
    [3, "ひねくれ", "鎖那", 1],
    [4, "彼女は旅に出る", "鎖那", 2],
    [5, "嘘つきエミリー", "鎖那", 1],
    [6, "ginger snaps", "鎖那", 1],
    [7, "ニゲラの花束", "鎖那", 1],
    [8, "オオカミと少女", "鎖那", 2],
    [9, "宝石", "鎖那", 1],
    [10, "シュテルン", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=36303697"]

[3af901d004fec754fadb18974261132a]
catalognumber = ""
date = "2020-02-22"
album = "ハッピーでバッドな眠りは浅い"
tracks = [
    [1, "ハッピーでバッドな眠りは浅い", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=86432816"]

[e2e794e581b7a45cbf504937529344a2]
catalognumber = ""
date = "2020-12-12"
album = "備忘録"
tracks = [
    [1, "備忘録", "鎖那", 2],
]
links = ["https://music.163.com/#/album?id=120835351"]

[353f570792054545d6b71697a3be1a1c]
catalognumber = ""
date = "2021-02-08"
album = "LOVE LETTER with 鎖那"
tracks = [
    [1, "LOVE LETTER with 鎖那", "OCEANS/鎖那", 1],
]
links = ["https://music.163.com/#/album?id=122419490"]

[a82d6ba52e0ed54f959f06ab19951c81]
catalognumber = ""
date = "2021-07-10"
album = "tutu"
tracks = [
    [1, "tutu", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=129269500"]

[bdf0921951103946e7707ef1d9fc5717]
catalognumber = ""
date = "2021-11-26"
album = "ベイビーヘイロー"
tracks = [
    [1, "ベイビーヘイロー", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=135678329"]

[9847eeecf3b3b29f0a985fe94b66ab80]
catalognumber = ""
date = "2022-11-26"
album = "カプセル"
tracks = [
    [1, "カプセル", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=153931660"]

[91db3e8d7cb1a6cda850a0a9d86f14c8]
catalognumber = ""
date = "2024-02-26"
album = "ラブポーション (cover)"
tracks = [
    [1, "ラブポーション (cover)", "鎖那/なゆごろう", 1],
]
links = ["https://music.163.com/#/album?id=186625731"]

[4fbcb4f7834ad203156329099a3ea94f]
catalognumber = ""
date = "2025-03-10"
album = "それは内緒にしておいて (cover)"
tracks = [
    [1, "それは内緒にしておいて (cover)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=265072970"]

[3825949fbe13693ca9bcc4b79ab96fb4]
catalognumber = ""
date = "2025-05-28"
album = "sparkle"
tracks = [
    [1, "sparkle", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=272386837"]

[eb4a4e0729740031b5219e615e7bd8df]
catalognumber = ""
date = "2025-06-18"
album = "ラブポーション (cover) [Rearrange ver.]"
tracks = [
    [1, "ラブポーション (cover) [Rearrange ver.]", "鎖那/なゆごろう", 1],
]
links = ["https://music.163.com/#/album?id=275164204"]

[1ff83beb7f240cdc6679d7d5fa784635]
catalognumber = ""
date = "2025-11-21"
album = "CLOUD HAIRPIN"
tracks = [
    [1, "1step 2step", "鎖那", 1],
    [2, "KISSIN' CLAW", "鎖那", 1],
    [3, "くらくらった", "鎖那", 1],
    [4, "ベイビーヘイロー", "鎖那", 1],
    [5, "mimicry", "鎖那", 1],
    [6, "カプセル", "鎖那", 1],
    [7, "sparkle", "鎖那", 1],
    [8, "テルテルユー", "鎖那", 1],
    [9, "tutu", "鎖那", 1],
    [10, "備忘録", "鎖那", 1],
    [11, "oh my girl", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=289131412"]
