[9ca088ea39472db5cf54ead81d524391]
catalognumber = ""
date = "2010-01-18"
album = "from Y to Y (cover)"
tracks = [
    [1, "from Y to Y (cover)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=277163004"]

[210d118249ef0139636cacadd201d4df]
catalognumber = ""
date = "2014-08-22"
album = "好きなひと"
tracks = [
    [1, "未来図 (feat. 鎖那)", "HoneyWorks/鎖那", 1],
    [2, "告白予行練習 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [3, "テレカクシ思春期 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [4, "初恋の絵本 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [5, "告白ライバル宣言 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [6, "ヤキモチの答え (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [7, "イノコリ先生 (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [8, "ロリババアに恋をした (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [9, "ラズベリー＊モンスター (feat. 鎖那)", "HoneyWorks/鎖那", 0],
    [10, "病名恋ワズライ", "鎖那", 0],
    [11, "おまけ音源", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=2979081"]

[a3037196aa687fe32d7dc45554afde34]
catalognumber = ""
date = "2014-11-15"
album = "sigh."
tracks = [
    [1, "BEYOND", "鎖那", 1],
    [2, "モカ", "鎖那", 0],
    [3, "コーヒーカップ", "鎖那", 0],
    [4, "Ryrie", "鎖那", 1],
    [5, "トラベリングムード", "鎖那", 0],
    [6, "two of us", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=3111375"]

[dea8914bb72e583485d6c26b75225167]
catalognumber = ""
date = "2015-04-16"
album = "言葉のいらない約束（TV size）"
tracks = [
    [1, "言葉のいらない約束（TV size）", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=3139285"]

[3f3974a66c4d40ca2afbe6551599af8d]
catalognumber = ""
date = "2015-05-27"
album = "言葉のいらない約束 / 暁月夜-アカツキヅクヨ-"
tracks = [
    [1, "言葉のいらない約束", "鎖那", 0],
    [2, "暁月夜-アカツキヅクヨ-", "鎖那", 1],
    [3, "言葉のいらない約束 (Instrumetal)", "鎖那", 0],
    [4, "暁月夜 -アカツキヅクヨ- (Instrumetal)", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=3154377"]

[6e3a3666fb0d53c5b266f17dff8d8edf]
catalognumber = ""
date = "2015-12-31"
album = "(un) sentimental spica"
tracks = [
    [1, "花とクマ", "鎖那", 0],
    [2, "すきなうた", "鎖那", 0],
    [3, "さようなら、花泥棒さん (cover)", "鎖那", 0],
    [4, "転校前夜 (cover)", "鎖那", 0],
    [5, "言の葉クリニック (cover)", "鎖那", 0],
    [6, "パケットヒーロー (cover)", "鎖那", 0],
    [7, "パズルガール (cover)", "鎖那", 0],
    [8, "siawase", "鎖那", 1],
    [9, "だってキミは大切な人", "鎖那", 0],
    [10, "cantabile (cover)", "鎖那", 1],
    [11, "歩いても歩いても、夜空は僕を追いかけてくる (cover)", "鎖那", 0],
    [12, "リトルファイター", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=3439884"]

[6897248386bc3c8c7fcf813ffa3d48ab]
catalognumber = ""
date = "2016-12-31"
album = "夏休みの転校生"
tracks = [
    [1, "夏休みの転校生", "鎖那", 0],
    [2, "さよならグッバイ (Voice Memo)", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=35314462"]

[bafb654451853d44b51edf5c80df079e]
catalognumber = ""
date = "2017-09-15"
album = "花降る日々、"
tracks = [
    [1, "ニゲラの花束", "鎖那", 0],
    [2, "紫陽花、まばたき、梅雨の日。", "000", 0],
    [3, "マーガレットは眠る", "めありー", 0],
    [4, "花降るラジオ", "めありー/鎖那/000", 0],
    [5, "ニゲラの花束 (instrumental)", "鎖那", 0],
    [6, "紫陽花、まばたき、梅雨の日。 (instrumental)", "000", 0],
    [7, "マーガレットは眠る (instrumental)", "めありー", 0],
]
links = ["https://music.163.com/#/album?id=74268888"]

[37fc07acf4169f374fe846b5988f2eb0]
catalognumber = ""
date = "2017-09-27"
album = "Hush a by little girl"
tracks = [
    [1, "さよなら、テディベア", "鎖那", 0],
    [2, "鍵っ子", "鎖那", 0],
    [3, "ひねくれ", "鎖那", 0],
    [4, "彼女は旅に出る", "鎖那", 2],
    [5, "嘘つきエミリー", "鎖那", 0],
    [6, "ginger snaps", "鎖那", 1],
    [7, "ニゲラの花束", "鎖那", 0],
    [8, "オオカミと少女", "鎖那", 0],
    [9, "宝石", "鎖那", 0],
    [10, "シュテルン", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=36303697"]

[4c7e8586322b3f43901bf02f7911487d]
catalognumber = ""
date = "2020-02-22"
album = "ハッピーでバッドな眠りは浅い"
tracks = [
    [1, "ハッピーでバッドな眠りは浅い", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=86432816"]

[ece9e862d2b664d82f3ce8a70d41852f]
catalognumber = ""
date = "2020-12-12"
album = "備忘録"
tracks = [
    [1, "備忘録", "鎖那", 2],
]
links = ["https://music.163.com/#/album?id=120835351"]

[3d4a39ab08ba7b5297e6a4e3c778be4a]
catalognumber = ""
date = "2021-02-08"
album = "LOVE LETTER with 鎖那"
tracks = [
    [1, "LOVE LETTER with 鎖那", "OCEANS/鎖那", 1],
]
links = ["https://music.163.com/#/album?id=122419490"]

[a2b9de83dcaab6924ff8d2be0714ea73]
catalognumber = ""
date = "2021-07-10"
album = "tutu"
tracks = [
    [1, "tutu", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=129269500"]

[f4a20a70939b314fe90112d8ce065fc8]
catalognumber = ""
date = "2021-11-26"
album = "ベイビーヘイロー"
tracks = [
    [1, "ベイビーヘイロー", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=135678329"]

[7d9d13bf8eaf2c6cef736f7cdf4daec6]
catalognumber = ""
date = "2022-11-26"
album = "カプセル"
tracks = [
    [1, "カプセル", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=153931660"]

[c1dc09994eb69479f8de7fe7c2de6588]
catalognumber = ""
date = "2024-02-26"
album = "ラブポーション (cover)"
tracks = [
    [1, "ラブポーション (cover)", "鎖那/なゆごろう", 0],
]
links = ["https://music.163.com/#/album?id=186625731"]

[0ddb1260ad1037dbc2331a8247370232]
catalognumber = ""
date = "2025-03-10"
album = "それは内緒にしておいて (cover)"
tracks = [
    [1, "それは内緒にしておいて (cover)", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=265072970"]

[882a19d88726ce145df75aa6741fb7ce]
catalognumber = ""
date = "2025-05-28"
album = "sparkle"
tracks = [
    [1, "sparkle", "鎖那", 0],
]
links = ["https://music.163.com/#/album?id=272386837"]

[b0342ffd367a393dfd843d8ebf922cc9]
catalognumber = ""
date = "2025-06-18"
album = "ラブポーション (cover) [Rearrange ver.]"
tracks = [
    [1, "ラブポーション (cover) [Rearrange ver.]", "鎖那/なゆごろう", 0],
]
links = ["https://music.163.com/#/album?id=275164204"]

[0c1ab367a86e38b1c7b3972e845a83b2]
catalognumber = ""
date = "2025-11-21"
album = "CLOUD HAIRPIN"
tracks = [
    [1, "1step 2step", "鎖那", 1],
    [2, "KISSIN' CLAW", "鎖那", 1],
    [3, "くらくらった", "鎖那", 0],
    [4, "ベイビーヘイロー", "鎖那", 0],
    [5, "mimicry", "鎖那", 1],
    [6, "カプセル", "鎖那", 0],
    [7, "sparkle", "鎖那", 0],
    [8, "テルテルユー", "鎖那", 0],
    [9, "tutu", "鎖那", 0],
    [10, "備忘録", "鎖那", 1],
    [11, "oh my girl", "鎖那", 1],
]
links = ["https://music.163.com/#/album?id=289131412"]
