[8190ee0c9b0bbf051eba290247744099]
catalognumber = "PCSP-05889"
date = "2024-07-06"
album = "シャッターチャンス / めいちゃん"
tracks = [
    [1, "シャッターチャンス", "めいちゃん", 1],
]
links = ["https://beta.musicbrainz.org/release/82dcc25b-4890-4a2e-9bb8-40ad80b9eef8", "https://vgmdb.net/album/145034"]

[84992d4adff6cd132f753cc1e4225d38]
catalognumber = "PCCG-70539"
date = "2024-08-28"
album = "Watch Me/逢い合い傘 / 天乃リリサ (CV: 前田佳織里), 橘美花莉 (CV: 鬼頭明里)"
tracks = [
    [1, "Watch Me", "天乃リリサ(CV: 前田佳織里)・橘美花莉(CV: 鬼頭明里)", 1],
    [2, "逢い合い傘", "天乃リリサ(CV: 前田佳織里)・橘美花莉(CV: 鬼頭明里)", 1],
    [3, "Watch Me (instrumental)", "天乃リリサ(CV: 前田佳織里)・橘美花莉(CV: 鬼頭明里)", 1],
    [4, "逢い合い傘 (instrumental)", "天乃リリサ(CV: 前田佳織里)・橘美花莉(CV: 鬼頭明里)", 1],
]
links = ["https://beta.musicbrainz.org/release/86230be3-1730-4a4c-93aa-af71ace53a35", "https://vgmdb.net/album/143023"]

[85daed2839a83674a0d10a5697fbdd4f]
catalognumber = "PCSP-06030"
date = "2024-09-27"
album = "ツギハギの翼"
tracks = [
    [1, "ツギハギの翼", "そらる", 1],
]
links = ["https://beta.musicbrainz.org/release/bd1a6ecd-b585-4efe-ad81-2730f691a657"]

[9c3bb0aede88201f2a80f120925eedec]
catalognumber = "PCCG-02421"
date = "2024-12-18"
album = "Release Sigh / 天乃リリサ(cv.前田佳織里)、橘美花莉(cv.鬼頭明里)、ノノア(cv.鈴代紗弓)、喜咲アリア(cv.渡部紗弓)"
tracks = [
    [1, "Release Sigh", "天乃リリサ(CV: 前田佳織里)、橘美花莉(CV: 鬼頭明里)、ノノア(CV: 鈴代紗弓)、喜咲アリア(CV: 渡部紗弓)", 1],
    [2, "Release Sigh ballade ver.", "天乃リリサ(CV: 前田佳織里)", 1],
    [3, "Release Sigh (inst)", "天乃リリサ(CV: 前田佳織里)、橘美花莉(CV: 鬼頭明里)、ノノア(CV: 鈴代紗弓)、喜咲アリア(CV: 渡部紗弓)", 1],
    [4, "Release Sigh ballade ver. (inst)", "天乃リリサ(CV: 前田佳織里)", 1],
    [5, "Watch Me リリサver.", "天乃リリサ(CV: 前田佳織里)", 1],
    [6, "Watch Me 美花莉ver.", "橘美花莉(CV: 鬼頭明里)", 1],
]
links = ["https://beta.musicbrainz.org/release/a8ddb674-c25c-4b5d-8983-0f9a17cbc5e8", "https://vgmdb.net/album/145037"]

[0073cb4e23752c94e522f1ea441d40c4]
catalognumber = "PCCG-02424"
date = "2025-01-22"
album = "TVアニメ「2.5次元の誘惑」 ORIGINAL SOUNDTRACK Disc 1"
tracks = [
    [1, "シャッターチャンス (TVサイズ)", "めいちゃん", 1],
    [2, "2.5次元の誘惑 (Main Theme)", "堤博明", 1],
    [3, "放課後のひととき", "堤博明", 1],
    [4, "3次元女子", "堤博明", 1],
    [5, "リリエル愛", "堤博明", 1],
    [6, "二次元の住人", "堤博明", 1],
    [7, "最高のコンビ", "堤博明", 1],
    [8, "新人カメラマン", "堤博明", 1],
    [9, "共同作業", "堤博明", 1],
    [10, "楽しい部活動", "堤博明", 1],
    [11, "むずがゆい", "堤博明", 1],
    [12, "あるある話", "堤博明", 1],
    [13, "余裕の微笑み", "堤博明", 1],
    [14, "夢見る乙女", "堤博明", 1],
    [15, "愛を語る", "堤博明", 1],
    [16, "想いが止まらない!", "堤博明", 1],
    [17, "コスプレじゃないの忘れてたー!", "堤博明", 1],
    [18, "不可抗力", "堤博明", 1],
    [19, "虚無⁉", "堤博明", 1],
    [20, "ヤキモキ", "堤博明", 1],
    [21, "深夜にオタクがふたり", "堤博明", 1],
    [22, "私これやるの・・・?", "堤博明", 1],
    [23, "白ロム", "堤博明", 1],
    [24, "鼻血のプロ", "堤博明", 1],
    [25, "呼吸を合わせて", "堤博明", 1],
    [26, "天使が現れた", "堤博明", 1],
    [27, "新星", "堤博明", 1],
    [28, "変わらない優しさ", "堤博明", 1],
    [29, "どっちがコスプレを愛してる?", "堤博明", 1],
    [30, "大好きを伝えたい", "堤博明", 1],
    [31, "勇気をくれたから", "堤博明", 1],
    [32, "君の物語", "堤博明", 1],
    [33, "『アシュフォード戦記』", "堤博明", 1],
    [34, "シャッターチャンス (OST ver.)", "堤博明", 1],
    [35, "Watch Me (TVサイズ)", "天乃リリサ(CV: 前田佳織里)・橘美花莉(CV: 鬼頭明里)", 1],
]
links = ["https://beta.musicbrainz.org/release/94520cdd-eb06-4ffb-8b72-0f508cf9d205", "https://vgmdb.net/album/145032"]

[1e626461ac68e6cbc10938a5a91c6712]
catalognumber = "PCCG-02424"
date = "2025-01-22"
album = "TVアニメ「2.5次元の誘惑」 ORIGINAL SOUNDTRACK Disc 2"
tracks = [
    [1, "ツギハギの翼 (TVサイズ)", "そらる", 1],
    [2, "コスプレ四天王", "堤博明", 1],
    [3, "トップに連れて行く", "堤博明", 1],
    [4, "いざ、夏コミ!", "堤博明", 1],
    [5, "この世界の頂上", "堤博明", 1],
    [6, "百戦錬磨のオーラ", "堤博明", 1],
    [7, "ヒロイン談義", "堤博明", 1],
    [8, "硬派オタク", "堤博明", 1],
    [9, "好きなものを好きでいたい", "堤博明", 1],
    [10, "コスプレのプロ", "堤博明", 1],
    [11, "素早さMAX", "堤博明", 1],
    [12, "デバフマスター", "堤博明", 1],
    [13, "氷のプリンセス?", "堤博明", 1],
    [14, "インドア派", "堤博明", 1],
    [15, "オタクマインド", "堤博明", 1],
    [16, "物騒なオーラ", "堤博明", 1],
    [17, "現状分析", "堤博明", 1],
    [18, "複雑なリスク", "堤博明", 1],
    [19, "作戦会議", "堤博明", 1],
    [20, "混乱状態", "堤博明", 1],
    [21, "忘れていた想い", "堤博明", 1],
    [22, "自己嫌悪", "堤博明", 1],
    [23, "過去に蓋をして", "堤博明", 1],
    [24, "友達になりたい", "堤博明", 1],
    [25, "あなたに憧れて", "堤博明", 1],
    [26, "隣にいてくれるなら", "堤博明", 1],
    [27, "愛の形は一つじゃない", "堤博明", 1],
    [28, "心ほぐす時間", "堤博明", 1],
    [29, "G線上のアリア", "堤博明", 1],
    [30, "友達の意味", "堤博明", 1],
    [31, "大事なのは愛", "堤博明", 1],
    [32, "Watch Me (OST ver.)", "堤博明", 1],
    [33, "Release Sigh (TVサイズ)", "天乃リリサ(CV: 前田佳織里)、橘美花莉(CV: 鬼頭明里)、ノノア(CV: 鈴代紗弓)、喜咲アリア(CV: 渡部紗弓)", 1],
]
links = ["https://beta.musicbrainz.org/release/94520cdd-eb06-4ffb-8b72-0f508cf9d205", "https://vgmdb.net/album/145032"]
