[bcd93192a76d437ab35568e393da44b8]
catalognumber = "KICM-1410"
date = "2012-08-01"
album = "希望について / NO NAME"
tracks = [
    [1, "希望について", "NO NAME", 0],
    [2, "夢は何度も生まれ変わる", "NO NAME", 0],
    [3, "虹の列車", "NO NAME", 0],
    [4, "希望について (off vocal ver．)", "NO NAME", 0],
    [5, "夢は何度も生まれ変わる(off vocal ver．)", "NO NAME", 0],
    [6, "虹の列車(off vocal ver．)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/3f85a9cb-c2b7-43f3-a9ed-c0a5e89134a0", "https://vgmdb.net/album/33439"]

[ffc064aebe02679702703e255bbbbb9b]
catalognumber = "KICM-91410"
date = "2012-08-01"
album = "希望について / NO NAME Vocal"
tracks = [
    [1, "希望について", "NO NAME", 0],
    [2, "夢は何度も生まれ変わる", "NO NAME", 0],
    [3, "虹の列車", "NO NAME", 0],
    [4, "希望について (off vocal ver．)", "NO NAME", 0],
    [5, "夢は何度も生まれ変わる(off vocal ver．)", "NO NAME", 0],
    [6, "虹の列車(off vocal ver．)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/3f85a9cb-c2b7-43f3-a9ed-c0a5e89134a0", "https://vgmdb.net/album/33440"]

[b561aa5debee531e02381f2bca7f3812]
catalognumber = "KICM-91410"
date = "2012-08-01"
album = "希望について / NO NAME Video"
tracks = [
    [1, "「希望について」 Music Video 〜NO NAMEメンバー Version〜", "NO NAME", 0],
    [2, "「NO NAME NO NABE 〜普段はこんな感じ？〜」", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/3f85a9cb-c2b7-43f3-a9ed-c0a5e89134a0", "https://vgmdb.net/album/33440"]

[1251757fd9d8f7d22e58d89d083ab093]
catalognumber = "KICM-1411"
date = "2012-08-01"
album = "希望について / NO NAME"
tracks = [
    [1, "希望について", "NO NAME", 0],
    [2, "夢は何度も生まれ変わる", "NO NAME", 0],
    [3, "虹の列車", "NO NAME", 0],
    [4, "希望について (off vocal ver.)", "NO NAME", 0],
    [5, "夢は何度も生まれ変わる (off vocal ver.)", "NO NAME", 0],
    [6, "虹の列車 (off vocal ver.)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/204b52c9-a6a1-4690-92e7-0cf464d9da1b", "https://vgmdb.net/album/33441"]

[c7ef9aedb0e84d170246d8837d7c6fc7]
catalognumber = "KICM-91411"
date = "2012-08-01"
album = "希望について / NO NAME Vocal"
tracks = [
    [1, "希望について", "NO NAME", 0],
    [2, "夢は何度も生まれ変わる", "NO NAME", 0],
    [3, "虹の列車", "NO NAME", 0],
    [4, "希望について (off vocal ver.)", "NO NAME", 0],
    [5, "夢は何度も生まれ変わる (off vocal ver.)", "NO NAME", 0],
    [6, "虹の列車 (off vocal ver.)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/b55b1ad4-5595-4e87-89f2-dc6f225674b9", "https://vgmdb.net/album/33442"]

[d8e11be8690fb394900c1e776598651e]
catalognumber = "KICM-91411"
date = "2012-08-01"
album = "希望について / NO NAME Video"
tracks = [
    [1, "「希望について」 Music Video ～オリジナルアニメーション Version～", "NO NAME", 0],
    [2, "「Making of Music Video」", "NO NAME", 0],
    [3, "「THE潜入～制作現場に突撃しよう～」", "佐藤亜美菜、石田晴香、佐藤すみれ", 0],
]
links = ["https://beta.musicbrainz.org/release/b55b1ad4-5595-4e87-89f2-dc6f225674b9", "https://vgmdb.net/album/33442"]

[30d39f298de695a6bbc8c923491ff3c5]
catalognumber = "SSX-10245"
date = "2012-10-31"
album = "AKB0048 オリジナルサウンドトラックCD"
tracks = [
    [1, "「ヘビーローテーション」AKB0048ver.", "山崎燿", 0],
    [2, "「会いたかった」AKB0048ver. ～Orchestra～", "BOUNCEBACK", 0],
    [3, "AKB0048スペシャルメドレー ～「希望について」・「Pioneer」・「ポニーテールとシュシュ」・「最終ベルが鳴る」・「転がる石になれ」・「希望について」～", "川浦正大, 野中“まさ”雄一, 多田慎也, 八重樫ゆう一, 山崎燿", 0],
    [4, "秋葉星の日常", "高木洋", 0],
    [5, "「支え」AKB0048ver.", "太田美知彦", 0],
    [6, "私たちの夢", "高木洋", 0],
    [7, "DES軍襲来", "高木洋", 0],
    [8, "戦闘態勢", "高木洋", 0],
    [9, "「大声ダイヤモンド」AKB0048ver.", "高木洋", 0],
    [10, "アイドルの休日", "高木洋", 0],
    [11, "今日もドタバタ研究生!", "高木洋", 0],
    [12, "レッスンが終われば…", "高木洋", 0],
    [13, "「これからWonderland」AKB0048ver.", "井上ヨシマサ", 0],
    [14, "滲みゆく星屑", "高木洋", 0],
    [15, "少女の涙", "高木洋", 0],
    [16, "一日の始まり", "高木洋", 0],
    [17, "のどかな昼下がり", "高木洋", 0],
    [18, "スパルタ!牛山先生", "高木洋", 0],
    [19, "会いたかった」AKB0048ver. ～Comical～", "BOUNCEBACK", 0],
    [20, "悲しみのあとに", "高木洋", 0],
    [21, "キララの輝き", "高木洋", 0],
    [22, "宇宙狂想曲", "高木洋", 0],
    [23, "フライングゲット飛翔", "高木洋", 0],
    [24, "銀河のオアシス", "高木洋", 0],
    [25, "あの日見たステージ", "高木洋", 0],
    [26, "運命の輪", "高木洋", 0],
    [27, "「初日」AKB0048ver.", "岡田実音", 0],
    [28, "「夢は何度も生まれ変わる」AKB0048ver.", "伊藤心太郎", 0],
]
links = ["https://beta.musicbrainz.org/release/fbe55109-13e7-48d1-ac1d-86cc55ad4b58", "https://vgmdb.net/album/32929"]

[4f4978aef406a861e8ca2fffac01fdb1]
catalognumber = "KICM-1444"
date = "2013-04-10"
album = "この涙を君に捧ぐ / NO NAME [Type D]"
tracks = [
    [1, "この涙を君に捧ぐ", "NO NAME", 0],
    [2, "主なきその声", "NO NAME", 0],
    [3, "てもでもの涙 (NO NAME ver.)", "NO NAME", 0],
    [4, "オーディオドラマ後編「ブラックスノーの陰謀」", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/d5db4705-397a-4685-9424-0da1dbba1182", "https://vgmdb.net/album/37748"]

[5cad31e901689ceb67b69e2ed670b519]
catalognumber = "KIZM-203~4"
date = "2013-04-10"
album = "この涙を君に捧ぐ / NO NAME [Type B] Vocal"
tracks = [
    [1, "この涙を君に捧ぐ", "NO NAME", 0],
    [2, "主なきその声", "NO NAME", 0],
    [3, "大声ダイヤモンド NO NAME ver.", "NO NAME", 0],
    [4, "この涙を君に捧ぐ (off vocal ver.)", "NO NAME", 0],
    [5, "主なきその声 (off vocal ver.)", "NO NAME", 0],
    [6, "大声ダイヤモンド (off vocal ver.)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/3a661768-199c-4bc5-9d1b-200d1820081a", "https://vgmdb.net/album/37750"]

[297fe8a4204e8c035ef2bda98cc946d0]
catalognumber = "KIZM-203~4"
date = "2013-04-10"
album = "この涙を君に捧ぐ / NO NAME [Type B] Video"
tracks = [
    [1, "この涙を君に捧ぐ Music Video", "NO NAME", 0],
    [2, "Making of Music Video", "NO NAME", 0],
    [3, "『AKB0048 NO NAME FIRST KILALIVE』後編", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/3a661768-199c-4bc5-9d1b-200d1820081a", "https://vgmdb.net/album/37750"]

[57a91a81e7ebc3281664322ee72a2728]
catalognumber = "KIZM-201~2"
date = "2013-04-10"
album = "この涙を君に捧ぐ / NO NAME [Type A] Vocal"
tracks = [
    [1, "この涙を君に捧ぐ", "NO NAME", 0],
    [2, "主なきその声", "NO NAME", 0],
    [3, "少女たちよ NO NAME ver.", "NO NAME", 0],
    [4, "この涙を君に捧ぐ (off vocal ver.)", "NO NAME", 0],
    [5, "主なきその声 (off vocal ver.)", "NO NAME", 0],
    [6, "少女たちよ (off vocal ver.)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/a90d98c1-5abd-42a2-bd74-e1d7e9c4fe71", "https://vgmdb.net/album/37749"]

[eaae38d0155676e9bf8c0d61cabc4dbc]
catalognumber = "KIZM-201~2"
date = "2013-04-10"
album = "この涙を君に捧ぐ / NO NAME [Type A] Video"
tracks = [
    [1, "この涙を君に捧ぐ Music Video", "NO NAME", 0],
    [2, "Making of Music Video", "NO NAME", 0],
    [3, "『AKB0048 NO NAME FIRST KILALIVE』前編", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/a90d98c1-5abd-42a2-bd74-e1d7e9c4fe71", "https://vgmdb.net/album/37749"]

[bbfd3020848fadee34d486d1d95d9b2e]
catalognumber = "KICM-1443"
date = "2013-04-10"
album = "この涙を君に捧ぐ / NO NAME [Type C]"
tracks = [
    [1, "この涙を君に捧ぐ", "NO NAME", 0],
    [2, "主なきその声", "NO NAME", 0],
    [3, "初日 (NO NAME ver.)", "NO NAME", 0],
    [4, "3型目の謎 (オーディオドラマ前編)", "NO NAME", 0],
]
links = ["https://beta.musicbrainz.org/release/3ee22ab9-e179-455e-b38b-47e79947c4ce", "https://vgmdb.net/album/37747"]

[b5066e4f7c1b9136f2ea790795633c5d]
catalognumber = "SSX-10268"
date = "2013-07-24"
album = "AKB0048 next stage 特典ドラマCD「優子のマル秘特訓大作戦」"
tracks = []
links = ["https://vgmdb.net/album/37461"]
