[184d06ad9ab565ab9202725b95b02e0e]
catalognumber = "EYCA-10953/B"
date = "2016-05-25"
album = "明日でいいから / Happy Clover Disc 1 (CD)"
tracks = [
    [1, "明日でいいから", "Happy Clover", 0],
    [2, "願いは負けない星だから", "Happy Clover", 0],
    [3, "明日でいいから (Instrumental)", "Happy Clover", 0],
    [4, "願いは負けない星だから (Instrumental)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/8943b7e4-339e-4b07-bd87-caec24bd62c8", "https://vgmdb.net/album/57523"]

[7407de2b3864a700fd97e4613e98cbf2]
catalognumber = "EYCA-10953/B"
date = "2016-05-25"
album = "明日でいいから / Happy Clover Disc 2 (DVD)"
tracks = [
    [1, "明日でいいから (Music Video)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/8943b7e4-339e-4b07-bd87-caec24bd62c8", "https://vgmdb.net/album/57523"]

[287f4ead300f100dae26b730cc518e7a]
catalognumber = "EYCA-10954"
date = "2016-05-25"
album = "明日でいいから / Happy Clover"
tracks = [
    [1, "明日でいいから", "Happy Clover", 0],
    [2, "願いは負けない星だから", "Happy Clover", 0],
    [3, "明日でいいから (Instrumental)", "Happy Clover", 0],
    [4, "願いは負けない星だから (Instrumental)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/65e14a8a-a3f6-41f4-baad-2ca17f24070f", "https://vgmdb.net/album/57522"]

[66798d992e3224a14c0f2cd2ea38cf59]
catalognumber = "EYCA-10956"
date = "2016-05-25"
album = "PUNCH☆MIND☆HAPPINESS / Happy Clover"
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS", "Happy Clover", 0],
    [2, "わいわいお天気ロード", "Happy Clover", 0],
    [3, "PUNCH☆MIND☆HAPPINESS (Instrumental)", "Happy Clover", 0],
    [4, "わいわいお天気ロード (Instrumental)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/ab85de62-0459-4463-9e78-09e1e9c327e0", "https://vgmdb.net/album/57520"]

[8a4d155f9e8161506de0d43a9989b6e0]
catalognumber = "EYCA-10955/B"
date = "2016-05-25"
album = "PUNCH☆MIND☆HAPPINESS / Happy Clover [CD+DVD] Disc 1 (CD)"
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS", "Happy Clover", 0],
    [2, "わいわいお天気ロード", "Happy Clover", 0],
    [3, "PUNCH☆MIND☆HAPPINESS (Instrumental)", "Happy Clover", 0],
    [4, "わいわいお天気ロード (Instrumental)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/3a78d849-609f-4cb5-8807-ff50b2d248e8", "https://vgmdb.net/album/57521"]

[6771f24e794aafda52f058bdca48582f]
catalognumber = "EYCA-10955/B"
date = "2016-05-25"
album = "PUNCH☆MIND☆HAPPINESS / Happy Clover [CD+DVD] Disc 2 (DVD)"
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS (Music Video)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/3a78d849-609f-4cb5-8807-ff50b2d248e8", "https://vgmdb.net/album/57521"]

[d67c8d50e773eccb8c75b070311e980b]
catalognumber = "OVXN-0023"
date = "2016-06-22"
album = "あんハピ♪ 第1巻 EXTRA CD HANAKO ver."
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS HANAKO solo ver.", "花守ゆみり", 0],
    [2, "SOUND DRAMA『花小泉さんち』", "花守ゆみり", 0],
]
links = ["https://beta.musicbrainz.org/release/a012485a-cfd7-4d7d-a1a7-85cc01ace2b8", "https://vgmdb.net/album/60584"]

[5a048707cf8b681defdbe64d1193994a]
catalognumber = "EYCA-11001"
date = "2016-06-22"
album = "あんハピ♪キャラクターソングシリーズ1 はなこ&ヒバリ"
tracks = [
    [1, "なるまるまーる", "はなこ(CV.花守ゆみり)", 0],
    [2, "紙ひこうき風になった", "ヒバリ(CV.白石晴香)", 0],
    [3, "なるまるまーる (Instrumental)", "はなこ(CV.花守ゆみり)", 0],
    [4, "紙ひこうき風になった (Instrumental)", "ヒバリ(CV.白石晴香)", 0],
]
links = ["https://beta.musicbrainz.org/release/72d9aa42-1c3b-42fd-8425-49eef47336b1", "https://vgmdb.net/album/58379"]

[619fe12790e67234ea08a0f9a7150a0e]
catalognumber = "EYCA-11002"
date = "2016-06-29"
album = "あんハピ♪キャラクターソングシリーズ2 ぼたん&チモシ"
tracks = [
    [1, "サプリナル", "ぼたん(CV.安野希世乃)", 0],
    [2, "ミチノチモシーキミノキモチ", "チモシー(CV.森永千才)", 0],
    [3, "サプリナル (Instrumental)", "ぼたん(CV.安野希世乃)", 0],
    [4, "ミチノチモシーキミノキモチ (Instrumental)", "チモシー(CV.森永千才)", 0],
]
links = ["https://beta.musicbrainz.org/release/82ad17cc-0e35-4c0e-b852-820f82e54e54", "https://vgmdb.net/album/58380"]

[fffab3f90763ff32ffdbb2da0458e835]
catalognumber = "EYCA-11003"
date = "2016-07-06"
album = "あんハピ♪キャラクターソングシリーズ3 ヒビキ&レン"
tracks = [
    [1, "Knock Knock Map Map", "ヒビキ(CV.山村響)", 0],
    [2, "Baby Blanket, 24", "レン(CV.吉岡茉祐)", 0],
    [3, "Knock Knock Map Map (Instrumental)", "ヒビキ(CV.山村響)", 0],
    [4, "Baby Blanket, 24 (Instrumental)", "レン(CV.吉岡茉祐)", 0],
]
links = ["https://beta.musicbrainz.org/release/929b7093-7953-4669-9309-fe855ff49eb6", "https://vgmdb.net/album/58381"]

[b126f984e418aa2701e4f96c419c3105]
catalognumber = "EYCA-11004"
date = "2016-07-20"
album = "あんハピ♪キャラクターソングシリーズ4 はなこ＆ヒバリ＆ぼたん"
tracks = [
    [1, "とりぷるトラブル", "はなこ&ヒバリ&ぼたん(CV.花守ゆみり&白石晴香&安野希世乃)", 0],
    [2, "春夏秋冬ハッピーデイズ♪ (はなこヒバリぼたんver.)", "はなこ&ヒバリ&ぼたん(CV.花守ゆみり&白石晴香&安野希世乃)", 0],
    [3, "とりぷるトラブル (Instrumental)", "はなこ&ヒバリ&ぼたん(CV.花守ゆみり&白石晴香&安野希世乃)", 0],
    [4, "春夏秋冬ハッピーデイズ♪ (はなこヒバリぼたんver.) (Instrumental)", "はなこ&ヒバリ&ぼたん(CV.花守ゆみり&白石晴香&安野希世乃)", 0],
]
links = ["https://beta.musicbrainz.org/release/f5fb295f-091a-44ec-a376-6936b0055557", "https://vgmdb.net/album/58382"]

[6df3a56c72bdf84d18f2d32e3b274f44]
catalognumber = "OVXN-0024"
date = "2016-07-27"
album = "あんハピ♪ 第2巻 EXTRA CD HIBARI ver."
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS HIBARI solo ver.", "白石晴香", 0],
    [2, "SOUND DRAMA『ヒバリ編』", "白石晴香", 0],
]
links = ["https://beta.musicbrainz.org/release/d38c15a3-4b6c-4a3f-bcc0-1d165c1c26d6", "https://vgmdb.net/album/60585"]

[f223ee432cf2d02fdbc5fbb044bde8b4]
catalognumber = "EYCA-11005"
date = "2016-07-27"
album = "あんハピ♪キャラクターソングシリーズ5 ヒビキ&レン"
tracks = [
    [1, "Sinfonietta", "ヒビキ&レン(CV.山村響&吉岡茉祐)", 0],
    [2, "春夏秋冬ハッピーデイズ♪ (ヒビキレンver.)", "ヒビキ&レン(CV.山村響&吉岡茉祐)", 0],
    [3, "Sinfonietta (Instrumental)", "ヒビキ&レン(CV.山村響&吉岡茉祐)", 0],
    [4, "春夏秋冬ハッピーデイズ♪ (ヒビキレンver.) (Instrumental)", "ヒビキ&レン(CV.山村響&吉岡茉祐)", 0],
]
links = ["https://beta.musicbrainz.org/release/414701c9-c01f-45a3-8d5f-b1cf83e086d5", "https://vgmdb.net/album/58383"]

[e8d5a9bef015575a91c189be3456737e]
catalognumber = "EYCA-11006"
date = "2016-08-10"
album = "あんハピ♪ キャラクターユニットソングシリーズ1"
tracks = [
    [1, "Go!業!スクールライフ☆", "はなこ&ぼたん&レン(CV.花守ゆみり&安野希世乃&吉岡茉佑)", 0],
    [2, "ぼんやり漂流譚", "はなこ&ぼたん&レン(CV.花守ゆみり&安野希世乃&吉岡茉佑)", 0],
    [3, "Go!業!スクールライフ☆ (Instrumental)", "はなこ&ぼたん&レン(CV.花守ゆみり&安野希世乃&吉岡茉佑)", 0],
    [4, "ぼんやり漂流譚 (Instrumental)", "はなこ&ぼたん&レン(CV.花守ゆみり&安野希世乃&吉岡茉佑)", 0],
]
links = ["https://beta.musicbrainz.org/release/352208d6-cc9d-4013-8e7d-a91737a96d66", "https://vgmdb.net/album/58384"]

[2b49845ac67fcafc653fb8eed1c54683]
catalognumber = "EYCA-11007"
date = "2016-08-24"
album = "あんハピ♪ キャラクターユニットソングシリーズ2"
tracks = [
    [1, "Hi・Ba・Na", "ヒバリ&ヒビキ(CV.白石晴香&山村響)", 0],
    [2, "しあわせの地図", "ヒバリ&ヒビキ(CV.白石晴香&山村響)", 0],
    [3, "Hi・Ba・Na (Instrumental)", "ヒバリ&ヒビキ(CV.白石晴香&山村響)", 0],
    [4, "しあわせの地図 (Instrumental)", "ヒバリ&ヒビキ(CV.白石晴香&山村響)", 0],
]
links = ["https://beta.musicbrainz.org/release/fd9ef483-7626-4547-9046-c93fc971c854", "https://vgmdb.net/album/58385"]

[23f990dd56b879044ddd65afaf3ea2ff]
catalognumber = "OVXN-0025"
date = "2016-08-24"
album = "あんハピ♪ 第3巻 EXTRA CD BOTAN ver."
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS BOTAN solo ver.", "安野希世乃", 0],
    [2, "SOUND DRAMA『ぼたん編』", "安野希世乃", 0],
]
links = ["https://beta.musicbrainz.org/release/d21104a7-b43c-4eed-8660-2e0fb523d005", "https://vgmdb.net/album/60586"]

[a60d07cc44e24d1fdafc788d82300a84]
catalognumber = "EYCA-11008"
date = "2016-09-07"
album = "Happening Lucky Rhapsody / Happy Clover"
tracks = [
    [1, "Happening Lucky Rhapsody", "Happy Clover", 0],
    [2, "帰りみち", "Happy Clover", 0],
    [3, "Happening Lucky Rhapsody (Instrumental)", "Happy Clover", 0],
    [4, "帰りみち (Instrumental)", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/264600b9-0118-4a23-9df2-eeb055c4802b", "https://vgmdb.net/album/58378"]

[de5d29a11f29db4b67bec63b37c40bc3]
catalognumber = "OVXN-0026"
date = "2016-09-28"
album = "あんハピ♪ 第4巻 EXTRA CD HIBIKI ver."
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS HIBIKI solo ver.", "山村響", 0],
    [2, "SOUND DRAMA『ヒビキ編』", "山村響", 0],
]
links = ["https://beta.musicbrainz.org/release/519110aa-7c49-4443-973a-7845e7382354", "https://vgmdb.net/album/60587"]

[c862d17244410d9e4f192308084f6980]
catalognumber = "OVXN-0027"
date = "2016-10-26"
album = "あんハピ♪ 第5巻 EXTRA CD REN ver."
tracks = [
    [1, "PUNCH☆MIND☆HAPPINESS REN solo ver.", "吉岡茉祐", 0],
    [2, "SOUND DRAMA『レン編』", "吉岡茉祐", 0],
]
links = ["https://beta.musicbrainz.org/release/42c0912a-445d-45c1-b4a7-234a26ef910f", "https://vgmdb.net/album/60588"]

[d4cab4a0b6349c96f1e7d5b1cde01aec]
catalognumber = "OVXN-0028"
date = "2016-11-23"
album = "あんハピ♪ 第6巻 EXTRA CD"
tracks = [
    [1, "エクストラサウンドドラマ「みんなで宿題合宿」", "", 0],
    [2, "サウンドドラマ「幸せの黄色い鳥」", "", 0],
]
links = ["https://vgmdb.net/album/60589"]

[48d6409c1618f00ee55efc2065d0c06f]
catalognumber = "EYCA-11333~5"
date = "2017-02-24"
album = "あんハピ♪ All Music Collection「ハピコレ」 Disc 1 [EYCA-11333]"
tracks = [
    [1, "瑠璃色の風景", "高橋邦幸", 0],
    [2, "髪を揺らす粒子", "高橋邦幸", 0],
    [3, "必然の災難", "瀬尾祥太郎", 0],
    [4, "アプリコット・ジャム", "田中秀和", 0],
    [5, "春の呼び声", "神前暁", 0],
    [6, "PUNCH☆MIND☆HAPPINESS", "Happy Clover", 0],
    [7, "期待に膨らむ胸", "神前暁", 0],
    [8, "幸せな杏の樹", "田中秀和", 0],
    [9, "微笑みが踊るよ", "神前暁", 0],
    [10, "天香国色", "高橋邦幸", 0],
    [11, "手折れやすいお花", "高橋邦幸", 0],
    [12, "気怠い日晴鳥", "高橋邦幸", 0],
    [13, "スカートをひるがえして", "瀬尾祥太郎", 0],
    [14, "幸せはどこにあるのでしょう?", "広川恵一", 0],
    [15, "レッツゴー幸福クラス!", "広川恵一", 0],
    [16, "負の業", "高橋邦幸", 0],
    [17, "赤面ブルース", "石濱翔", 0],
    [18, "なんじゃそりゃ", "高橋邦幸", 0],
    [19, "街角乙女ゴコロ", "田中秀和", 0],
    [20, "あっちへこっちへ", "田中秀和", 0],
    [21, "からももの実", "石濱翔", 0],
    [22, "不憫の予兆", "石濱翔", 0],
    [23, "Unhappy Go Lucky!!", "高橋邦幸", 0],
    [24, "姫雛鳥", "石濱翔", 0],
    [25, "希望の名は", "高橋邦幸", 0],
    [26, "明日でいいから", "Happy Clover", 0],
    [27, "閑話休題♪", "神前暁", 0],
    [28, "Timothy-Awakening-", "帆足圭吾", 0],
    [29, "Hope for Tomorrow", "広川恵一、瀬尾祥太郎", 0],
    [30, "Timothy-White Rabbit-", "瀬尾祥太郎", 0],
    [31, "はじめての幸福実技", "帆足圭吾", 0],
    [32, "紫睡蓮", "石濱翔", 0],
    [33, "喜びをポッケに詰めて", "神前暁", 0],
    [34, "一件落着?", "神前暁", 0],
    [35, "Down the Rabbit Hole", "瀬尾祥太郎", 0],
    [36, "紅の響迷", "帆足圭吾", 0],
    [37, "一息つきますね", "高橋邦幸", 0],
    [38, "意気揚々と帆を高く", "瀬尾祥太郎", 0],
    [39, "Let's Party!", "瀬尾祥太郎", 0],
]
links = ["https://beta.musicbrainz.org/release/7d0eb316-5192-41b7-a092-c4194c2663a8", "https://vgmdb.net/album/63566"]

[c3820bc062277b9c42ba973711f419df]
catalognumber = "EYCA-11333~5"
date = "2017-02-24"
album = "あんハピ♪ All Music Collection「ハピコレ」 Disc 2 [EYCA-11334]"
tracks = [
    [1, "わいわいお天気ロード", "Happy Clover", 0],
    [2, "にゃん道探検隊", "高橋邦幸", 0],
    [3, "雲雀の羽休め", "高橋邦幸", 0],
    [4, "幸福が咲く場所", "瀬尾祥太郎", 0],
    [5, "それはさておき", "高橋邦幸", 0],
    [6, "煌めきの憧憬", "帆足圭吾", 0],
    [7, "やがて宙を舞う兎", "帆足圭吾", 0],
    [8, "陽気な放課後", "神前暁", 0],
    [9, "パンチマインドな昼下がり", "田中秀和", 0],
    [10, "紫陽花とてるてる坊主", "広川恵一", 0],
    [11, "職業選択の不自由", "広川恵一", 0],
    [12, "今はただ剣を掲げて", "高橋邦幸", 0],
    [13, "紅の響奏", "帆足圭吾", 0],
    [14, "疾風怒濤!", "高橋邦幸", 0],
    [15, "刻むよ四つ葉のリズム", "岡部啓一", 0],
    [16, "はばたきの彼方へ", "帆足圭吾", 0],
    [17, "魔神降誕", "高橋邦幸", 0],
    [18, "願いは負けない星だから", "Happy Clover", 0],
    [19, "おきらくごくらく", "高橋邦幸", 0],
    [20, "すっごくついてたね", "神前暁", 0],
    [21, "ロコモコ・どこどこ", "高橋邦幸", 0],
    [22, "Samba for Tomorrow", "広川恵一", 0],
    [23, "ミチノチモシーキミノキモチ", "瀬尾祥太郎", 0],
    [24, "Knock Knock Map Map", "ヒビキ(CV.山村響)", 0],
    [25, "Baby Blanket, 24", "レン(CV.吉岡茉祐)", 0],
    [26, "サプリナル", "ぼたん(CV.安野希世乃)", 0],
    [27, "なるまるまーる", "はなこ(CV.花守ゆみり)", 0],
    [28, "紙ひこうき風になった", "ヒバリ(CV.白石晴香)", 0],
    [29, "パンチマインドな星空", "田中秀和、瀬尾祥太郎", 0],
    [30, "終わりよければすべてハッピー", "田中秀和", 0],
]
links = ["https://beta.musicbrainz.org/release/7d0eb316-5192-41b7-a092-c4194c2663a8", "https://vgmdb.net/album/63566"]

[38c5bfd336b31e3b1316a6e8b3419999]
catalognumber = "EYCA-11333~5"
date = "2017-02-24"
album = "あんハピ♪ All Music Collection「ハピコレ」 Disc 3 [EYCA-11335]"
tracks = [
    [1, "とりぷるトラブル", "はなこ&ヒバリ&ぼたん(CV.花守ゆみり&白石晴香&安野希世乃)", 0],
    [2, "春夏秋冬ハッピーデイズ♪ (はなこ&ヒバリ&ぼたんver.)", "はなこ&ヒバリ&ぼたん(CV.花守ゆみり&白石晴香&安野希世乃)", 0],
    [3, "Sinfonietta", "ヒビキ&レン(CV.山村響&吉岡茉祐)", 0],
    [4, "春夏秋冬ハッピーデイズ♪ (ヒビキ&レンver.)", "ヒビキ&レン(CV.山村響&吉岡茉祐)", 0],
    [5, "春夏秋冬ハッピーデイズ♪ (Happy Clover ver.)", "Happy Clover", 0],
    [6, "Go!業!スクールライフ☆", "はなこ&ぼたん&レン(CV.花守ゆみり&安野希世乃&吉岡茉佑)", 0],
    [7, "ぼんやり漂流譚", "はなこ&ぼたん&レン(CV.花守ゆみり&安野希世乃&吉岡茉佑)", 0],
    [8, "Hi・Ba・Na", "ヒバリ&ヒビキ(CV.白石晴香&山村響)", 0],
    [9, "しあわせの地図", "ヒバリ&ヒビキ(CV.白石晴香&山村響)", 0],
    [10, "Happening Lucky Rhapsody", "Happy Clover", 0],
    [11, "帰りみち", "Happy Clover", 0],
]
links = ["https://beta.musicbrainz.org/release/7d0eb316-5192-41b7-a092-c4194c2663a8", "https://vgmdb.net/album/63566"]
