[006973db1d243c0a3ee76362266ca5ca]
catalognumber = "PCSP-06607"
date = "2025-07-02"
album = "LUCKY / TOMOO"
tracks = [
    [1, "LUCKY", "TOMOO", 0],
]
links = ["https://beta.musicbrainz.org/release/eb944f28-cb4b-4d77-990d-d35733948cfd", "https://vgmdb.net/album/151966"]

[4fcfa83a41575675c8e1340a0f026865]
catalognumber = "PCCG-02440"
date = "2025-07-23"
album = "TVアニメ CITY THE ANIMATION オリジナル・サウンドトラック"
tracks = [
    [1, "かき氷", "ピラニアンズ", 0],
    [2, "ROAD TO THE CITY", "ピラニアンズ", 0],
    [3, "熱帯夜", "ピラニアンズ", 0],
    [4, "Small Dance (⼩踊り)", "ピラニアンズ", 0],
    [5, "さえずり", "ピラニアンズ", 0],
    [6, "街レゲエ", "ピラニアンズ", 0],
    [7, "街レゲエ (ギターバージョン)", "ピラニアンズ", 0],
    [8, "静かに思うこと", "ピラニアンズ", 0],
    [9, "Cat Fight (ネコ 対 ねこじゃらし)", "ピラニアンズ", 0],
    [10, "Snake Charmer (へび使い)", "ピラニアンズ", 0],
    [11, "Snake Charmer (毒へびバージョン)", "ピラニアンズ", 0],
    [12, "まめ大福", "ピラニアンズ", 0],
    [13, "まめ⼤福 (こし餡バージョン)", "ピラニアンズ", 0],
    [14, "メガマウス", "ピラニアンズ", 0],
    [15, "福引き", "ピラニアンズ", 0],
    [16, "溢れる想い (マリンバメロディ)", "ピラニアンズ", 0],
    [17, "溢れる想い (ピラニアンズメロディ)", "ピラニアンズ", 0],
    [18, "荒唐無稽な幸せ", "ピラニアンズ", 0],
    [19, "荒唐無稽な幸せ (スカバージョン)", "ピラニアンズ", 0],
    [20, "⽯畳の遊歩道", "ピラニアンズ", 0],
    [21, "走れ", "ピラニアンズ", 0],
    [22, "Funks On The Street", "ピラニアンズ", 0],
    [23, "浮遊", "ピラニアンズ", 0],
    [24, "気どり屋の1⽇", "ピラニアンズ", 0],
    [25, "街レゲエ (ダブバージョン)", "ピラニアンズ", 0],
    [26, "かき氷 (かき氷のワルツ)", "ピラニアンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/fd98cc74-fc99-442e-bd25-ee203d0fc5ad", "https://vgmdb.net/album/149990"]

[6fee04df1c1ac2fc57465737ba321635]
catalognumber = "PCCA-06402"
date = "2025-07-30"
album = "Hello / Furui Riho"
tracks = [
    [1, "Hello", "Furui Riho", 0],
    [2, "ちゃんと", "Furui Riho", 0],
    [3, "Hello (TV ver.)", "Furui Riho", 0],
    [4, "Hello (Instrumental)", "Furui Riho", 0],
]
links = ["https://beta.musicbrainz.org/release/889e9644-9ccd-4440-a159-4ab2a63151d2", "https://vgmdb.net/album/151968"]

[03e259116bb61572061a702b63fe3f89]
catalognumber = "PCCA-06401"
date = "2025-07-30"
album = "Hello / Furui Riho Vocal"
tracks = [
    [1, "Hello", "Furui Riho", 0],
    [2, "ちゃんと", "Furui Riho", 0],
    [3, "Hello (TV ver.)", "Furui Riho", 0],
    [4, "Hello (Instrumental)", "Furui Riho", 0],
]
links = ["https://beta.musicbrainz.org/release/889e9644-9ccd-4440-a159-4ab2a63151d2", "https://vgmdb.net/album/151967"]

[f2607a6cb3a1b33ac186e16f79db03a0]
catalognumber = "PCCA-06401"
date = "2025-07-30"
album = "Hello / Furui Riho Video"
tracks = [
    [1, "PSYCHO", "Furui Riho", 0],
    [2, "ピンクの髪", "Furui Riho", 0],
    [3, "言えないわ", "Furui Riho", 0],
    [4, "青信号", "Furui Riho", 0],
    [5, "Do What Makes You Happy", "Furui Riho", 0],
    [6, "Candle Light", "Furui Riho", 0],
    [7, "でこぼこ", "Furui Riho", 0],
    [8, "SAPPORO TOKYO", "Furui Riho", 0],
    [9, "Rebirth", "Furui Riho", 0],
    [10, "We are", "Furui Riho", 0],
    [11, "Super Star", "Furui Riho", 0],
    [12, "Tomorrow", "Furui Riho", 0],
    [13, "LOA", "Furui Riho", 0],
    [14, "Purpose", "Furui Riho", 0],
    [15, "MONSTER (EN)", "Furui Riho", 0],
    [16, "Your Love (EN)", "Furui Riho", 0],
]
links = ["https://beta.musicbrainz.org/release/889e9644-9ccd-4440-a159-4ab2a63151d2", "https://vgmdb.net/album/151967"]

[e3ef98464f8c8a247cc763ecd9874b27]
catalognumber = "PCXE-51073-2"
date = "2025-12-03"
album = "CITY THE ANIMATION 劇中曲集 \"In The CITY\""
tracks = [
    [1, "りこの走馬灯", "ピラニアンズ", 0],
    [2, "未来の自分", "ピラニアンズ", 0],
    [3, "真壁鶴菱の黄昏", "ピラニアンズ", 0],
    [4, "決闘のテーマ", "ピラニアンズ", 0],
    [5, "麗しい思い出", "ピラニアンズ", 0],
    [6, "The Story of Twin Tower", "ピラニアンズ", 0],
    [7, "臨終マーチ", "ピラニアンズ", 0],
    [8, "本官の妄想", "ピラニアンズ", 0],
    [9, "劇団テカリダケ第7回公演『のど』", "ピラニアンズ", 0],
    [10, "CITYレース発走", "ピラニアンズ", 0],
    [11, "Free on Game", "ピラニアンズ", 0],
    [12, "劇団テカリダケ特別公演『自尊心』", "ピラニアンズ", 0],
    [13, "モーニングルーティン", "ピラニアンズ", 0],
    [14, "競馬ロマン", "ピラニアンズ", 0],
    [15, "フォーエヴァーヤング", "ピラニアンズ", 0],
    [16, "オーバーチュア", "ピラニアンズ", 0],
    [17, "大繁盛", "ピラニアンズ", 0],
    [18, "なぜりこちゃんが", "ピラニアンズ", 0],
    [19, "とにかく踊ろう", "ピラニアンズ", 0],
    [20, "料理たくさん", "ピラニアンズ", 0],
    [21, "料理ない", "ピラニアンズ", 0],
    [22, "罠", "ピラニアンズ", 0],
    [23, "この件", "ピラニアンズ", 0],
    [24, "電話〜神秘", "ピラニアンズ", 0],
    [25, "政治のはなし", "ピラニアンズ", 0],
    [26, "星って", "ピラニアンズ", 0],
    [27, "洋食マカベです！", "ピラニアンズ", 0],
    [28, "出前", "ピラニアンズ", 0],
    [29, "タイムマシーン", "ピラニアンズ", 0],
    [30, "フィナーレ", "ピラニアンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/48d48728-6275-4eb0-a3c3-23d07087a7e6", "https://vgmdb.net/album/154727"]
