[9ee055a83938c2d495ef6c14920466a4]
catalognumber = "GPHCD-1003"
date = "2010-08-27"
album = "Custom Maid 3D ~entrance to you~"
tracks = [
    [1, "entrance to you", "nao", 1],
    [2, "scarlet leap", "nao", 1],
    [3, "scarlet leap (IOSYS Remix)", "ARM (IOSYS)", 1],
    [4, "entrance to you (カラオケバージョン)", "ARM (IOSYS)", 1],
    [5, "scarlet leap (カラオケバージョン)", "ARM (IOSYS)", 1],
]
links = ["https://beta.musicbrainz.org/release/99d024eb-8bb7-426a-b8d7-653fbc3e0f29", "https://vgmdb.net/album/23618"]

[e0a8cbf7e87c3f4fef4a4c43893c1c76]
catalognumber = "N/A"
date = "2014-03-28"
album = "カスタムメイドオンライン主題歌candy♥girl"
tracks = [
    [1, "candy♥girl Maid'ish(Duca&Rita&茶太)", "Duca&Rita&茶太", 2],
    [2, "candy♥girl (short Version)", "", 1],
    [3, "candy♥girl (short Version :Duca ver.)", "", 1],
    [4, "candy♥girl (short Version :Rita ver.)", "", 1],
    [5, "candy♥girl (short Version :茶太 ver.)", "", 1],
    [6, "candy♥girl (Instrumental)", "", 1],
    [7, "candy♥girl (short Instrumental)", "", 1],
]
links = ["https://vgmdb.net/album/45151"]

[a950a2272b98c7b8e17163820c1fa712]
catalognumber = ""
date = "2016-08-26"
album = "Custom Maid 3d Original Sound Track"
tracks = [
    [1, "Welcome to the empire club (CM3D ver)", "Cosmic Cube", 1],
    [2, "Schedule (CM3D ver)", "Cosmic Cube", 1],
    [3, "Edit me (CM3D ver)", "Cosmic Cube", 1],
    [4, "Theme of Tsudere (CM3D ver)", "Cosmic Cube", 1],
    [5, "Theme of Junshin (CM3D ver)", "Cosmic Cube", 1],
    [6, "Them of Kudere (CM3D ver)", "Cosmic Cube", 1],
    [7, "Theme of Amaenbo (CM3D ver)", "Cosmic Cube", 1],
    [8, "プレイルーム", "Cosmic Cube", 1],
    [9, "バスルーム", "Cosmic Cube", 1],
    [10, "SMルーム", "Cosmic Cube", 1],
    [11, "ステージ", "Cosmic Cube", 1],
    [12, "プール", "Cosmic Cube", 1],
    [13, "中庭", "Cosmic Cube", 1],
    [14, "街", "Cosmic Cube", 1],
    [15, "happiness", "Cosmic Cube", 1],
    [16, "Entrance to you(CM3D ver)", "Cosmic Cube", 1],
    [17, "エッチな歌", "Cosmic Cube", 1],
    [18, "セクシな夜", "Cosmic Cube", 1],
    [19, "コスプレ広場", "Cosmic Cube", 1],
    [20, "Scarlet leap (CM3D ver)", "Cosmic Cube", 1],
    [21, "リビング", "Cosmic Cube", 1],
    [22, "トイレ", "Cosmic Cube", 1],
    [23, "屋敷", "Cosmic Cube", 1],
]
links = ["https://music.163.com/#/album?id=73326657"]

[3c3aefc073eb5b782145bd08c2a85737]
catalognumber = "SCM-001"
date = "2017-03-24"
album = "CUSTOM MAID VOCAL COLLECTION Disc 1"
tracks = [
    [1, "ドキドキ☆Fallin' Love [Full Love☆xury version]", "Love☆xury", 1],
    [2, "ドキドキ☆Fallin' Love [Full nao version]", "nao", 1],
    [3, "ドキドキ☆Fallin' Love [Full 佐咲紗花 version]", "佐咲紗花", 1],
    [4, "ドキドキ☆Fallin' Love [Full 美郷あき version]", "美郷あき", 1],
    [5, "stellar my tears [Full nao version]", "nao", 1],
    [6, "stellar my tears [Full 佐咲紗花 version]", "佐咲紗花", 1],
    [7, "stellar my tears [Full 美郷あき version]", "美郷あき", 1],
    [8, "happy! happy! スキャンダル!! [Full nao version]", "nao", 1],
    [9, "happy! happy! スキャンダル!! [Full 佐咲紗花 version]", "佐咲紗花", 1],
    [10, "happy! happy! スキャンダル!! [Full 美郷あき version]", "美郷あき", 1],
]
links = ["https://beta.musicbrainz.org/release/579a9916-02a9-4768-a1d8-f0f1eca8a679", "https://vgmdb.net/album/70702"]

[7a7e7f70b05e710146778e85355d817c]
catalognumber = "SCM-001"
date = "2017-03-24"
album = "CUSTOM MAID VOCAL COLLECTION Disc 2"
tracks = [
    [1, "candy girl [Full Maid'ish version]", "Maid'ish", 1],
    [2, "candy girl [Duca version]", "Duca", 1],
    [3, "candy girl [Rita version]", "Rita", 1],
    [4, "candy girl [茶太 version]", "茶太", 1],
    [5, "Selfish Destiny [Full Rita & yozuca* version]", "Rita & yozuca*", 1],
    [6, "Selfish Destiny [Full Rita version]", "Rita", 1],
    [7, "Selfish Destiny [Full yozuca* version]", "yozuca*", 1],
    [8, "Can Know Two Close? [Full 姫野珠世 version]", "姫野珠世", 1],
    [9, "rhythmix to you [Full nao version]", "nao", 1],
    [10, "scarlet leap [Full nao version]", "nao", 1],
    [11, "entrance to you [Full nao version]", "nao", 1],
]
links = ["https://beta.musicbrainz.org/release/579a9916-02a9-4768-a1d8-f0f1eca8a679", "https://vgmdb.net/album/70702"]

[a50895f4fab49adfa1dca29751a06d0d]
catalognumber = ""
date = "2017-12-22"
album = "Custom Maid 3d2 Original Sound Track"
tracks = [
    [1, "Welcome to the empire club", "Cosmic Cube", 1],
    [2, "Edit me", "Cosmic Cube", 1],
    [3, "優しい光に包まれて", "Cosmic Cube", 1],
    [4, "Whatever you like", "Cosmic Cube", 1],
    [5, "floatin'", "Cosmic Cube", 1],
    [6, "Healing Space", "Cosmic Cube", 1],
    [7, "ティータイム", "Cosmic Cube", 1],
    [8, "Dancin'", "Cosmic Cube", 1],
    [9, "Busy busy", "Cosmic Cube", 1],
    [10, "禁断の扉", "Cosmic Cube", 1],
    [11, "Sweetie Garden", "Cosmic Cube", 1],
    [12, "雅", "Cosmic Cube", 1],
    [13, "Night after night", "Cosmic Cube", 1],
    [14, "キッチンミュージック", "Cosmic Cube", 1],
    [15, "スケジュールは正確に", "Cosmic Cube", 1],
    [16, "夜の通り", "Cosmic Cube", 1],
    [17, "書斎にて", "Cosmic Cube", 1],
    [18, "Hospitality", "Cosmic Cube", 1],
    [19, "平穏の時", "Cosmic Cube", 1],
    [20, "お花にご挨拶", "Cosmic Cube", 1],
    [21, "忍び寄る不条理", "Cosmic Cube", 1],
    [22, "Immoral Conduct", "Cosmic Cube", 1],
    [23, "Precious step", "Cosmic Cube", 1],
    [24, "秘密のハネムーン", "Cosmic Cube", 1],
    [25, "僕と遊ぼっ", "Cosmic Cube", 1],
    [26, "Sweets on the table", "Cosmic Cube", 1],
]
links = ["https://music.163.com/#/album?id=72796201"]

[ca5679dfa37dbf3b75f23afe23c57d45]
catalognumber = "SCM003"
date = "2018-03"
album = "CUSTOM ORDER MAID3D2 VOCAL COLLECTION Disc 2"
tracks = [
    [1, "Luminous moment [Full Chorus]", "", 1],
    [2, "Luminous moment [Full Chorus ver.nao]", "", 1],
    [3, "Luminous moment [Full Chorus ver.中恵光城]", "", 1],
    [4, "Luminous moment [Full Chorus ver.彩音]", "", 1],
    [5, "melody of empire [Full Chorus]", "", 1],
    [6, "melody of empire [Full Chorus ver.nao]", "", 1],
    [7, "melody of empire [Full Chorus ver.中恵光城]", "", 1],
    [8, "melody of empire [Full Chorus ver.彩音]", "", 1],
]
links = ["https://vgmdb.net/album/94423"]

[57cb4f27710816f1df438017f886da91]
catalognumber = "SCM003"
date = "2018-03"
album = "CUSTOM ORDER MAID3D2 VOCAL COLLECTION Disc 1"
tracks = [
    [1, "Night Magic Fire [Full Chorus]", "", 1],
    [2, "Night Magic Fire [Full Chorus ver.nao]", "", 1],
    [3, "Night Magic Fire [Full Chorus ver.中恵光城]", "", 1],
    [4, "Night Magic Fire [Full Chorus ver.彩音]", "", 1],
    [5, "Blooming∞Dreaming! [Full Chorus]", "nao、御苑生メイ、中恵光城、彩音", 1],
    [6, "Blooming∞Dreaming! [Full Chorus ver.nao]", "nao", 1],
    [7, "Blooming∞Dreaming! [Full Chorus ver.中恵光城]", "中恵光城", 1],
    [8, "Blooming∞Dreaming! [Full Chorus ver.彩音]", "彩音", 1],
    [9, "キミに愛情でりぃしゃす [Full Chorus]", "", 1],
    [10, "キミに愛情でりぃしゃす [Full Chorus ver.nao]", "", 1],
    [11, "キミに愛情でりぃしゃす [Full Chorus ver.中恵光城]", "", 1],
    [12, "キミに愛情でりぃしゃす [Full Chorus ver.彩音]", "", 1],
]
links = ["https://vgmdb.net/album/94423"]

[5351e292219ce6d8c6ae1aef452414f1]
catalognumber = "KISS-COM3D2-1808"
date = "2018-08-09"
album = "CUSTOM ORDER MAID3D2 if story 俺の愛しのメイドが容赦無くNTRれてしまうボイスドラマ"
tracks = [
    [1, "無垢で天使な仔犬系", "", 0],
    [2, "真面目でエッチな事が苦手な委員長系", "", 0],
    [3, "凜としてるけれどたまにデレるお姉さん", "", 0],
    [4, "連動シナリオ『IF-他の男とイチャラブ』", "", 0],
    [5, "連動シナリオ『IF-他の男に仕込まれて』", "", 0],
    [6, "連動シナリオ『IF-全てを奪われた恋人』", "", 0],
]
links = ["https://vgmdb.net/album/94425"]

[9df18405d23e442cc4c6a4b801f9e6c9]
catalognumber = "SCRC-001"
date = "2018-08-09"
album = "CUSTOM ORDER MAID3D2 VOCAL COLLECTION"
tracks = [
    [1, "Night Magic Fire", "", 1],
    [2, "in pulse", "", 1],
    [3, "Blooming∞Dreaming！", "", 1],
    [4, "キミに愛情でりぃしゃす", "", 1],
    [5, "Luminous moment", "", 1],
    [6, "melody of empire", "", 1],
]
links = ["https://vgmdb.net/album/94424"]

[c4ef91d6decdd71457c968b5d70c8603]
catalognumber = "SCM005"
date = "2019-08-08"
album = "CUSTOM MAID & CUSTOM ORDER MAID VOCAL COLLECTION Disc 1"
tracks = [
    [1, "sweet sweet everyday [Full chorus ver.nao]", "nao", 1],
    [2, "sweet sweet everyday [Full chorus ver.佐咲紗花]", "佐咲紗花", 1],
    [3, "sweet sweet everyday [Full chorus ver.美郷あき]", "美郷あき", 1],
    [4, "改革的ハートグラフィー [Full chorus ver.nao]", "nao", 1],
    [5, "改革的ハートグラフィー [Full chorus ver.小春めう]", "小春めう", 1],
    [6, "Sun☆シャイン☆夏 [Full chorus ver.nao]", "nao", 1],
    [7, "Sun☆シャイン☆夏 [Full chorus ver.佐咲紗花]", "佐咲紗花", 1],
    [8, "Sun☆シャイン☆夏 [Full chorus ver.美郷あき]", "美郷あき", 1],
]
links = ["https://beta.musicbrainz.org/release/3f021b3f-48a1-48f1-ad30-f572cd8b67cb", "https://vgmdb.net/album/94427"]

[36aa39dec745482e7cf8620495bf6a47]
catalognumber = "SCM005"
date = "2019-08-08"
album = "CUSTOM MAID & CUSTOM ORDER MAID VOCAL COLLECTION Disc 2"
tracks = [
    [1, "さくらうららか、はらひらり [Full chorus]", "nao", 1],
    [2, "mainly priority [Full chorus]", "中恵光城", 1],
    [3, "in-pulse", "山田重利", 1],
    [4, "secret deep blue [Full chorus]", "nao, 中恵光城 & 彩音", 1],
    [5, "secret deep blue [Full chorus ver.nao]", "nao", 1],
    [6, "secret deep blue [Full chorus ver.中恵光城]", "中恵光城", 1],
    [7, "secret deep blue [Full chorus ver.彩音]", "彩音", 1],
    [8, "fusionic addiction [Full chorus]", "nao", 1],
    [9, "1st only you [Full chorus ver.nao]", "nao", 1],
    [10, "1st only you [Full chorus ver.御苑生メイ]", "御苑生メイ", 1],
    [11, "Night Magic Fire [English ver. Full chorus]", "nao, 中恵光城 & 彩音", 1],
    [12, "Night Magic Fire [English ver. Full chorus ver.nao]", "nao", 1],
    [13, "Night Magic Fire [English ver. Full chorus ver.中恵光城]", "中恵光城", 1],
    [14, "Night Magic Fire [English ver. Full chorus ver.彩音]", "彩音", 1],
]
links = ["https://beta.musicbrainz.org/release/3f021b3f-48a1-48f1-ad30-f572cd8b67cb", "https://vgmdb.net/album/94427"]

[92f77b11eec7d569bde5766585e9bc8a]
catalognumber = ""
date = "2020-11-06"
album = "CUSTOM ORDER MAID 3D2 Original Sound Track"
tracks = [
    [1, "無垢のテーマ", "山田重利", 1],
    [2, "真面目のテーマ", "山田重利", 1],
    [3, "凛デレのテーマ", "山田重利", 1],
    [4, "Welcome To The Empire Club(Com3d2 ver)", "山田重利", 1],
    [5, "Edit me(COM3D2 ver)", "山田重利", 1],
    [6, "みんなの幸せ", "山田重利", 1],
    [7, "屋敷", "山田重利", 1],
    [8, "ライブ", "山田重利", 1],
    [9, "執務室（夜）", "山田重利", 1],
    [10, "カジノ", "山田重利", 1],
    [11, "ソープ", "山田重利", 1],
    [12, "黒の欲望", "山田重利", 1],
    [13, "バーラウンジ", "山田重利", 1],
    [14, "レストラン", "山田重利", 1],
    [15, "劇場", "山田重利", 1],
    [16, "夢の始まり", "山田重利", 1],
    [17, "感傷", "山田重利", 1],
    [18, "乙女の心", "山田重利", 1],
    [19, "少女の悩み", "山田重利", 1],
    [20, "執務室（朝）", "山田重利", 1],
    [21, "絶望の中の希望", "山田重利", 1],
    [22, "夜伽", "山田重利", 1],
    [23, "ダークネス", "山田重利", 1],
    [24, "文学少女のテーマ", "山田重利", 1],
    [25, "小悪魔のテーマ", "山田重利", 1],
    [26, "ポロステージ", "山田重利", 1],
    [27, "おしとやかのテーマ", "山田重利", 1],
    [28, "メイド秘書のテーマ", "山田重利", 1],
    [29, "ふわふわ妹のテーマ", "山田重利", 1],
    [30, "無愛想のテーマ", "山田重利", 1],
    [31, "夢の終わり", "山田重利", 1],
    [32, "朝の光", "山田重利", 1],
    [33, "お嬢様のテーマ", "山田重利", 1],
    [34, "幼馴染のテーマ", "山田重利", 1],
    [35, "ドＭド変態のテーマ", "山田重利", 1],
    [36, "腹黒のテーマ", "山田重利", 1],
]
links = ["https://music.163.com/#/album?id=128185666"]

[d436bb0ffd13b0ba1a7eab041dd62cd4]
catalognumber = "N/A"
date = "2025-07"
album = "CUSTOM ORDER MAID3D2 VOCAL COLLECTION Vol.2 Disc 2"
tracks = [
    [1, "Charm in Love", "", 1],
    [2, "Charm in Love Ver.nao", "", 1],
    [3, "Charm in Love Ver.紫咲ほたる", "", 1],
    [4, "rainy unbalance", "", 1],
    [5, "rainy unbalance Ver.nao", "", 1],
    [6, "rainy unbalance Ver.紫咲ほたる", "", 1],
    [7, "wondering beads", "", 1],
    [8, "memories sympathy", "", 1],
    [9, "memories sympathy Ver.nao", "", 1],
    [10, "memories sympathy Ver.中恵光城", "", 1],
    [11, "memories sympathy Ver.彩音", "", 1],
    [12, "stellar my tears", "", 1],
]
links = ["https://vgmdb.net/album/149522"]

[2d4b3ef2c54e5b74d81438d447a08246]
catalognumber = "N/A"
date = "2025-07"
album = "CUSTOM ORDER MAID3D2 VOCAL COLLECTION Vol.2 Disc 1"
tracks = [
    [1, "DAN!GAN!パーティー!!", "", 1],
    [2, "DAN!GAN!パーティー!! Ver.nao", "", 1],
    [3, "DAN!GAN!パーティー!! Ver.中恵光城", "", 1],
    [4, "DAN!GAN!パーティー!! Ver.彩音", "", 1],
    [5, "remember to dearest", "", 1],
    [6, "remember to dearest Ver.nao", "", 1],
    [7, "remember to dearest Ver.中恵光城", "", 1],
    [8, "remember to dearest Ver.彩音", "", 1],
    [9, "lovemore crymore", "", 1],
    [10, "レグルスの涙", "", 1],
    [11, "speed up mind", "", 1],
    [12, "speed up mind Ver.nao", "", 1],
    [13, "speed up mind Ver.彩音", "", 1],
]
links = ["https://vgmdb.net/album/149522"]
