[c244ca825a1ba7e7493621a6c7190fd2]
catalognumber = "FCCN-0017"
date = "2006-04-21"
album = "ドラマCD GOSICK -ゴシック-"
tracks = [
    [1, "Track.1", "", 0],
    [2, "Track.2", "", 0],
    [3, "Track.3", "", 0],
    [4, "Track.4", "", 0],
    [5, "Track.5", "", 0],
    [6, "Track.6", "", 0],
    [7, "Track.7", "", 0],
    [8, "Bonus Track", "", 0],
]
links = ["https://vgmdb.net/album/89118"]

[c03335484d2667fde154e0aa913f9b92]
catalognumber = "COZC-493~4"
date = "2011-03-02"
album = "Destin Histoire / yoshiki*lisa [完全初回限定生産盤] Vocal, Video"
tracks = [
    [1, "Destin Histoire", "yoshiki*lisa", 0],
    [2, "限りある世界で", "yoshiki*lisa", 0],
    [3, "Destin Histoire (オリジナル・カラオケ)", "yoshiki*lisa", 0],
    [4, "限りある世界で (オリジナル・カラオケ)", "yoshiki*lisa", 0],
]
links = ["https://beta.musicbrainz.org/release/39ddb231-ae6b-48b3-924f-10b77a0a2246", "https://vgmdb.net/album/23833"]

[a90b0a426f357c992ac465968c008169]
catalognumber = "COZC-493~4"
date = "2011-03-02"
album = "Destin Histoire / yoshiki*lisa [完全初回限定生産盤] Video"
tracks = [
    [1, "Destin Histoire (プロモーション映像他収録予定)", "", 0],
]
links = ["https://vgmdb.net/album/23833"]

[d61b66b089b0b5016408bfd65df05543]
catalognumber = "COCC-16449"
date = "2011-03-02"
album = "Destin Histoire / yoshiki*lisa"
tracks = [
    [1, "Destin Histoire", "yoshiki*lisa", 0],
    [2, "限りある世界で", "yoshiki*lisa", 0],
    [3, "Destin Histoire (オリジナル・カラオケ)", "yoshiki*lisa", 0],
    [4, "限りある世界で (オリジナル・カラオケ)", "yoshiki*lisa", 0],
]
links = ["https://beta.musicbrainz.org/release/f7090090-31bc-4b41-bc28-5cbf01fbfff7", "https://vgmdb.net/album/23834"]

[6aabaa3eef789451147c469e4a11e153]
catalognumber = "COCX-36662"
date = "2011-04-13"
album = "GOSICK -ゴシック- ◆ORIGINAL SOUNDTRACK◆"
tracks = [
    [1, "偽りと真の枢密", "中川幸太郎", 0],
    [2, "連結への共鳴", "中川幸太郎", 0],
    [3, "序列されし混沌", "中川幸太郎", 0],
    [4, "暗躍と廻る運命", "中川幸太郎", 0],
    [5, "黒き死神の学問", "中川幸太郎", 0],
    [6, "トランクの仕分け人", "中川幸太郎", 0],
    [7, "鼓動止まりし瞬間", "中川幸太郎", 0],
    [8, "出口無き血路", "中川幸太郎", 0],
    [9, "闇が蔽う真相", "中川幸太郎", 0],
    [10, "迫り来る畏怖の影", "中川幸太郎", 0],
    [11, "灰色狼への招待状", "中川幸太郎", 0],
    [12, "策略の奇禍", "中川幸太郎", 0],
    [13, "我こそが華麗なる名警部", "中川幸太郎", 0],
    [14, "隣り合わせの事変", "中川幸太郎", 0],
    [15, "終極の見えぬ危殆", "中川幸太郎", 0],
    [16, "天命に抗する運命", "中川幸太郎", 0],
    [17, "悪魔の微笑み", "中川幸太郎", 0],
    [18, "金貨の鎖が繋ぐもの", "中川幸太郎", 0],
    [19, "甘美な退屈凌ぎ", "中川幸太郎", 0],
    [20, "求めるは終焉の讃美歌", "中川幸太郎", 0],
    [21, "糸口への導き", "中川幸太郎", 0],
    [22, "選ばれし者を導く金色の糸", "中川幸太郎", 0],
    [23, "可愛らしき冒険家", "中川幸太郎", 0],
    [24, "愚鈍の叫び", "中川幸太郎", 0],
    [25, "翻弄のなかの生命", "中川幸太郎", 0],
    [26, "離すことなきは護るべき手", "中川幸太郎", 0],
    [27, "火炎の夏至祭", "中川幸太郎", 0],
    [28, "哀しみの果てにあるこたえ", "中川幸太郎", 0],
    [29, "心地よい処での眠り", "中川幸太郎", 0],
    [30, "勇敢なる日の本の少年", "中川幸太郎", 0],
    [31, "Destin Histoire -TV size-", "yoshiki*lisa", 0],
    [32, "Resuscitated Hope -TV size-", "コミネリサ", 0],
]
links = ["https://beta.musicbrainz.org/release/0fdd5af5-4ef0-44d2-a9d2-a71bbd4ae59d", "https://vgmdb.net/album/23436"]

[d1cbd299e31ee55f6bf2e661d3a07f33]
catalognumber = "COCC-16467"
date = "2011-04-27"
album = "Resuscitated Hope/unity / コミネリサ"
tracks = [
    [1, "Resuscitated Hope", "コミネリサ", 0],
    [2, "unity", "コミネリサ", 0],
    [3, "Resuscitated Hope (Instrumental)", "坂部剛", 0],
    [4, "unity (Instrumental)", "Asu", 0],
]
links = ["https://beta.musicbrainz.org/release/7c9d05d6-8645-4f5c-b85d-7b9584d77892", "https://vgmdb.net/album/23952"]

[eb436cb94bc8389b481c991a0cba9a53]
catalognumber = "COCX-36765"
date = "2011-06-01"
album = "GOSICK-ゴシック- 知恵の泉と小夜曲(セレナード)"
tracks = [
    [1, "花降る亡霊は夏の夜を彩る 第1章", "[dialogue]", 0],
    [2, "巡り行く時間を君と", "久城一弥(CV:江口拓也)", 0],
    [3, "花降る亡霊は夏の夜を彩る 第2章", "[dialogue]", 0],
    [4, "My Adventure", "アブリル・ブラッドリー(CV:下屋則子)", 0],
    [5, "花降る亡霊は夏の夜を彩る 第3章", "[dialogue]", 0],
    [6, "Incertitude", "ヴィクトリカ・ド・ブロワ(CV:悠木碧)", 0],
    [7, "花降る亡霊は夏の夜を彩る 第4章", "[dialogue]", 0],
    [8, "Incertitude (Original Ver.)", "ヴィクトリカ・ド・ブロワ(CV:悠木碧)", 0],
]
links = ["https://beta.musicbrainz.org/release/4bfb4aba-b241-41f4-944c-cf53616a9d8b", "https://vgmdb.net/album/26070"]

[aeb9db1d640d07122752b2c20db783bd]
catalognumber = "KAXA-3003-CD"
date = "2011-06-24"
album = "GOSICK -ゴシック- 3 オリジナルドラマCD 『金髪の少女は金色の妖精を追う』"
tracks = [
    [1, "金髪の少女は金色の妖精を追う #01", "", 0],
    [2, "金髪の少女は金色の妖精を追う #02", "", 0],
    [3, "金髪の少女は金色の妖精を追う #03", "", 0],
    [4, "金髪の少女は金色の妖精を追う #04", "", 0],
    [5, "金髪の少女は金色の妖精を追う #05", "", 0],
    [6, "金髪の少女は金色の妖精を追う #06", "", 0],
]
links = ["https://vgmdb.net/album/89119"]

[37a8fb887a8e9f6ed458d408d8dacfd7]
catalognumber = "COCX-36823"
date = "2011-06-29"
album = "GOSICK -ゴシック- ORIGINAL SOUNDTRACK SECOND SEASON"
tracks = [
    [1, "聖霊の涙へ捧ぐ鎮魂", "中川幸太郎", 0],
    [2, "言語化されし混沌", "中川幸太郎", 0],
    [3, "悪因の枢軸", "中川幸太郎", 0],
    [4, "憂慮に纏われし身躯", "中川幸太郎", 0],
    [5, "英雄は死神", "中川幸太郎", 0],
    [6, "奇術師は赤毛の狼", "中川幸太郎", 0],
    [7, "街路に列する土産物", "中川幸太郎", 0],
    [8, "虹が示す処へのあかり", "中川幸太郎", 0],
    [9, "石榴色の錬金術", "中川幸太郎", 0],
    [10, "艱苦に忍ぶ“アフリカ人の歌”", "中川幸太郎", 0],
    [11, "回想録からの挑戦状", "中川幸太郎", 0],
    [12, "口承されし“アフリカ人の歌”", "中川幸太郎", 0],
    [13, "祭典に隠されし宴", "中川幸太郎", 0],
    [14, "終結の先に待つもの", "中川幸太郎", 0],
    [15, "涙目の書簡が伝書する事", "中川幸太郎", 0],
    [16, "思案の先にある暗示", "中川幸太郎", 0],
    [17, "魔神の悪計", "中川幸太郎", 0],
    [18, "薔薇色の人生", "中川幸太郎", 0],
    [19, "不徳に塗れし数奇", "中川幸太郎", 0],
    [20, "ファントムに咲く薔薇", "中川幸太郎", 0],
    [21, "“美しき怪物”を呑む混沌", "中川幸太郎", 0],
    [22, "逸興なる異国の聖夜", "中川幸太郎", 0],
    [23, "切なき思慕の優しい思い出", "中川幸太郎", 0],
    [24, "束の間の生誕祭", "中川幸太郎", 0],
    [25, "隔たりの連結", "中川幸太郎", 0],
    [26, "先見されし嵐", "中川幸太郎", 0],
    [27, "見えぬ聖母の慈愛", "中川幸太郎", 0],
    [28, "小さな母の大いなる生", "中川幸太郎", 0],
    [29, "永遠に繋がれし絆", "中川幸太郎", 0],
    [30, "unity -TVsize-", "コミネリサ", 0],
]
links = ["https://beta.musicbrainz.org/release/dae617eb-7cef-4521-951e-11d287b16d02", "https://vgmdb.net/album/26045"]

[54a2c02401c4cc5d36ce70f8e0381c9f]
catalognumber = "QWCE-00194"
date = "2011-08-03"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 13"
tracks = [
    [1, "コネクト", "plazma feat.Nahoko", 0],
    [2, "CORE PRIDE", "Hommarju feat.TAKANORI", 0],
    [3, "魔・カ・セ・テ Tonight", "Booing Day feat.MAKI", 0],
    [4, "ぱんでみっく!", "Hommarju feat.mi-mi", 0],
    [5, "Destin Histoire", "Icon feat.JJ", 0],
    [6, "インモラリスト", "Hommarju feat.R.Cena+hideki", 0],
    [7, "RPG", "Booing Day feat.puchi", 0],
    [8, "わが名は小学生", "Dizzi Mystica feat.405+mi-mi", 0],
    [9, "Choose my love!", "Booing Day feat.KANA", 0],
    [10, "Morning Arch", "Dizzi Mystica feat.YURiE", 0],
    [11, "A Whole New World God Only Knows", "Hommarju feat.R.Cena", 0],
    [12, "Scarlet Ballet", "Dizzi Mystica feat.mi-mi", 0],
    [13, "STRAIGHT JET", "MK feat.Latte", 0],
    [14, "Taste of Paradise", "Dizzi Mystica feat.yumemi", 0],
    [15, "Os-宇宙人", "Dizzi Mystica feat.mi-mi", 0],
    [16, "SHINY SHINY", "MK feat.405", 0],
    [17, "SCARLET KNIGHT", "Dizzi Mystica feat.Latte", 0],
    [18, "青い栞", "Icon feat.Yusuke+yuno", 0],
    [19, "Magia", "Dizzi Mystica feat.Natsuhi+R.Cena", 0],
]
links = ["https://beta.musicbrainz.org/release/212e98cc-5094-428f-8042-5fade11a7075", "https://vgmdb.net/album/29349"]

[7154337c19863f877369b4c0aab798b7]
catalognumber = "COCX-36886"
date = "2011-08-31"
album = "GOSICK-ゴシック- 知恵の泉と独唱曲(アリエッタ)"
tracks = [
    [1, "花びらと梟 第1章", "[dialogue]", 0],
    [2, "KentAi to Konton (Original Ver.)", "ヴィクトリカ・ド・ブロワ(CV:悠木碧)", 0],
    [3, "花びらと梟 第2章", "[dialogue]", 0],
    [4, "Fatal Ironies", "ブライアン・ロスコー(CV:大川透)", 0],
    [5, "花びらと梟 第3章", "[dialogue]", 0],
    [6, "Pour fille ～約束の子守唄～", "コルデリア・ギャロ(CV:沢城みゆき)", 0],
    [7, "花びらと梟 第4章", "[dialogue]", 0],
    [8, "KentAi to Konton", "ヴィクトリカ・ド・ブロワ(CV:悠木碧)", 0],
]
links = ["https://beta.musicbrainz.org/release/c525a7b2-1e29-49f5-8b42-0f6af6c77bd7", "https://vgmdb.net/album/27008"]
