[db01c95fe62ec487123d797fb5c1afeb]
catalognumber = "SMRR-006"
date = "2017-02-08"
album = "春待ちクローバー / 花坂結衣 (CV: M·A·O)"
tracks = [
    [1, "春待ちクローバー", "花坂結衣(CV:M・A・O)", 2],
    [2, "春待ちクローバー -blooming mix-", "花坂結衣(CV:M・A・O)", 1],
    [3, "春待ちクローバー (Instrumental)", "花坂結衣(CV:M・A・O)", 1],
]
links = ["https://beta.musicbrainz.org/release/d0da3564-6078-4291-9f6e-757b494d7300", "https://vgmdb.net/album/63666"]

[5090d4dd7be4cc5e9af0801c9e221279]
catalognumber = "SMRR-007"
date = "2017-02-22"
album = "夏空エール / 桃原奈月 (CV: 村川梨衣)"
tracks = [
    [1, "夏空エール", "桃原奈月(CV:村川梨衣)", 2],
    [2, "夏空エール -pretty perky mix-", "桃原奈月(CV:村川梨衣)", 1],
    [3, "夏空エール (Instrumental)", "桃原奈月(CV:村川梨衣)", 1],
]
links = ["https://beta.musicbrainz.org/release/692d72ae-943e-4061-a7d0-f0166b52a353", "https://vgmdb.net/album/63667"]

[ad6dde98c4fb370aac7a8bafa953c43e]
catalognumber = "SMRR-008"
date = "2017-03-08"
album = "希望リフレイン / 青島萌香 (CV: 三森すずこ)"
tracks = [
    [1, "希望リフレイン", "青島萌香(CV:三森すずこ)", 2],
    [2, "希望リフレイン -late summer mix-", "青島萌香(CV:三森すずこ)", 1],
    [3, "希望リフレイン (Instrumental)", "青島萌香(CV:三森すずこ)", 1],
]
links = ["https://beta.musicbrainz.org/release/122a87d1-9908-43dc-81a3-6c9ac7198e81", "https://vgmdb.net/album/63668"]

[d0b59bc6c3abcb59c7c4d51b9dbf90ff]
catalognumber = "SMRR-009"
date = "2017-06-14"
album = "君色スマイル / 葦原巧 (CV:前野智昭), 仁科葵 (CV:花江夏樹), 宮坂真也 (CV:鳥海浩輔)"
tracks = [
    [1, "君色スマイル", "葦原巧 (CV:前野智昭), 仁科葵 (CV:花江夏樹), 宮坂真也 (CV:鳥海浩輔)", 0],
    [2, "君色スマイル (葦原巧.ver)", "葦原巧 (CV:前野智昭)", 0],
    [3, "君色スマイル (仁科葵.ver)", "仁科葵 (CV:花江夏樹)", 0],
    [4, "君色スマイル (宮坂真也.ver)", "宮坂真也 (CV:鳥海浩輔)", 0],
    [5, "君色スマイル (Instrumental)", "葦原巧 (CV:前野智昭), 仁科葵 (CV:花江夏樹), 宮坂真也 (CV:鳥海浩輔)", 0],
]
links = ["https://vgmdb.net/album/70628"]

[5f7599d81b315974891d35a338905627]
catalognumber = "SMRR-013"
date = "2018-07-27"
album = "青空モーニンググローリー / 花坂結衣(CV: M·A·O)"
tracks = [
    [1, "青空モーニンググローリー", "花坂結衣(CV: M・A・O)", 2],
    [2, "青空モーニンググローリー (Happy house remix)", "花坂結衣(CV: M・A・O)", 1],
    [3, "青空モーニンググローリー (Instrumental)", "花坂結衣(CV: M・A・O)", 1],
]
links = ["https://beta.musicbrainz.org/release/95179f21-646e-4d7d-bb02-b0a0513ea795", "https://vgmdb.net/album/78134"]

[f22605440557edc754b626df42e10360]
catalognumber = "SMRR-014"
date = "2018-08-24"
album = "ポプラと僕らのヒストリー / 七橋御乃梨(CV:高橋李依)"
tracks = [
    [1, "ポプラと僕らのヒストリー", "七橋御乃梨(CV: 高橋李依)", 2],
    [2, "ポプラと僕らのヒストリー (happy house mix)", "七橋御乃梨(CV: 高橋李依)", 1],
    [3, "ポプラと僕らのヒストリー (Instrumental)", "七橋御乃梨(CV: 高橋李依)", 1],
]
links = ["https://beta.musicbrainz.org/release/b7aa4d7e-a315-4848-a8a3-04da929644c2", "https://vgmdb.net/album/78135"]

[7337151b3a437f2ad9fcae24520aa222]
catalognumber = "SMRR-015"
date = "2018-09-14"
album = "サーチライトと月灯り / 天月真白(CV:水瀬いのり)"
tracks = [
    [1, "サーチライトと月灯り", "天月真白(CV: 水瀬いのり)", 1],
    [2, "サーチライトと月灯り(fakejazzmix)", "天月真白(CV: 水瀬いのり)", 1],
    [3, "サーチライトと月灯り(instrumental)", "天月真白(CV: 水瀬いのり)", 1],
]
links = ["https://beta.musicbrainz.org/release/54369200-0562-450c-8dd8-717ba9a77733", "https://vgmdb.net/album/78136"]

[0470ffb69975a0042b606d69bd67515c]
catalognumber = "SMRR-019"
date = "2020-10-30"
album = "太陽とレインボー / 琴川晶(CV:富田美憂)"
tracks = [
    [1, "太陽とレインボー", "琴川晶(CV.富田美憂)", 1],
    [2, "太陽とレインボー (Remix Ver.)", "琴川晶(CV.富田美憂)", 1],
    [3, "太陽とレインボー (Instrumental)", "琴川晶(CV.富田美憂)", 1],
]
links = ["https://beta.musicbrainz.org/release/31103e2b-a8de-42dc-b068-1b17681c57f3", "https://vgmdb.net/album/104666"]

[7ddc232767da6040aed01834896a2e91]
catalognumber = "SMRR-020"
date = "2020-12-11"
album = "3階からヤマトナデシコ / 織崎紗耶(CV:花守ゆみり)"
tracks = [
    [1, "3階からヤマトナデシコ", "織崎紗耶(CV. 花守ゆみり)", 1],
    [2, "3階からヤマトナデシコ (Remix Ver.)", "織崎紗耶(CV. 花守ゆみり)", 1],
    [3, "3階からヤマトナデシコ (Instrumental)", "織崎紗耶(CV. 花守ゆみり)", 1],
]
links = ["https://beta.musicbrainz.org/release/0eb5fee6-0726-43fa-bf21-06694a174754", "https://vgmdb.net/album/106354"]

[06332066bf8c1cd935adb338671911af]
catalognumber = "SMIB-044-2"
date = "2021-02-26"
album = "TVアニメ One Room サードシーズン 主題歌"
tracks = [
    [1, "青空に紙ヒコーキ", "桃原奈月(CV:村川梨衣)", 1],
    [2, "雪の街と空想タイムマシン", "七橋御乃梨(CV:高橋李依)", 1],
    [3, "春夏秋冬＊笑顔日和", "花坂結衣(CV:M・A・O)", 2],
]
links = ["https://beta.musicbrainz.org/release/1995d84a-950b-449b-8b4e-5f02f3196229", "https://vgmdb.net/album/106736"]
