[760019ec4eb5711c35d7e45e46875b12]
catalognumber = "COCA-17998"
date = "2022-04-20"
album = "Awesome! / まねきケチャ [Type-B]"
tracks = [
    [1, "Awesome!", "まねきケチャ", 1],
    [2, "めんどくせー", "まねきケチャ", 1],
    [3, "狂気 (中川美優、松下玲緒菜、深瀬美桜 Vocal Ver.)", "まねきケチャ", 1],
    [4, "Awesome! (宮内凛、篠原葵 Vocal Ver.)", "まねきケチャ", 1],
    [5, "Awesome! (Instrumental)", "まねきケチャ", 1],
    [6, "めんどくせー (Instrumental)", "まねきケチャ", 1],
    [7, "狂気 (Instrumental)", "まねきケチャ", 1],
]
links = ["https://beta.musicbrainz.org/release/ca07e00a-9eab-4275-9643-f993346e17bb", "https://vgmdb.net/album/117953"]

[fbdc29229c686da5712615900bc229b7]
catalognumber = "COCA-17999"
date = "2022-04-20"
album = "Awesome! / まねきケチャ [Type-C]"
tracks = [
    [1, "Awesome!", "まねきケチャ", 1],
    [2, "めんどくせー", "まねきケチャ", 1],
    [3, "狂気 (中川美優、松下玲緒菜、深瀬美桜 Vocal Ver.)", "まねきケチャ", 1],
    [4, "Awesome! (宮内凛、篠原葵 Vocal Ver.)", "まねきケチャ", 1],
    [5, "Awesome! (Instrumental)", "まねきケチャ", 1],
    [6, "めんどくせー (Instrumental)", "まねきケチャ", 1],
    [7, "狂気 (Instrumental)", "まねきケチャ", 1],
]
links = ["https://beta.musicbrainz.org/release/ca07e00a-9eab-4275-9643-f993346e17bb", "https://vgmdb.net/album/117954"]

[773a3959f38382d6bbcb59c7ea6a77d6]
catalognumber = "COZA-1896~7"
date = "2022-04-20"
album = "Awesome! / まねきケチャ [Type-A] Vocal"
tracks = [
    [1, "Awesome!", "まねきケチャ", 2],
    [2, "めんどくせー", "まねきケチャ", 1],
    [3, "狂気 (中川美優、松下玲緒菜、深瀬美桜 Vocal Ver.)", "まねきケチャ", 2],
    [4, "Awesome! (宮内凛、篠原葵 Vocal Ver.)", "まねきケチャ", 1],
    [5, "狂気 (中川美優 Vocal Ver.)", "まねきケチャ", 1],
    [6, "Awesome! (宮内凛 Vocal Ver.)", "まねきケチャ", 1],
    [7, "狂気 (松下玲緒菜 Vocal Ver.)", "まねきケチャ", 1],
    [8, "狂気 (深瀬美桜 Vocal Ver.)", "まねきケチャ", 1],
    [9, "Awesome! (篠原葵 Vocal Ver.)", "まねきケチャ", 1],
]
links = ["https://beta.musicbrainz.org/release/8f76bc18-1eea-4b0a-adc5-a71efdfe5b4e", "https://vgmdb.net/album/117952"]

[93b483ccd61aa3069650da5020cc879b]
catalognumber = "COZA-1896~7"
date = "2022-04-20"
album = "Awesome! / まねきケチャ [Type-A] Vocal, Live Event, Video"
tracks = [
    [1, "Awesome! (Music Video)", "", 1],
    [2, "招かれチューン (まねきケチャ結成6周年記念公演 『6周年だよ!まねきケチャ』) (Live Video)", "", 0],
    [3, "メドレー (まねきケチャ結成6周年記念公演 『6周年だよ!まねきケチャ』) (Live Video)", "", 0],
    [4, "ありきたりな言葉で (まねきケチャ結成6周年記念公演 『6周年だよ!まねきケチャ』) (Live Video)", "", 0],
    [5, "きみわずらい (まねきケチャ結成6周年記念公演 『6周年だよ!まねきケチャ』) (Live Video)", "", 0],
]
links = ["https://vgmdb.net/album/117952"]

[d3355449d831822a8b8d321f8caea712]
catalognumber = "COZC-1892~3"
date = "2022-04-27"
album = "Make Up Life! / 風色琴音(CV:井上ほの花)、ファー(CV:木野日菜)、ルフリア(CV:川井田夏海)、ラキラ(CV:石見舞菜香) [限定盤] Vocal"
tracks = [
    [1, "Make Up Life!", "風色琴音、ファー、ラキラ、ルフリア(CV:井上ほの花、木野日菜、川井田夏海、石見舞菜香)", 1],
    [2, "Make Up Life!(琴音ソロ)", "風色琴音(CV:井上ほの花)", 1],
    [3, "Make Up Life!(ファーソロ)", "ファー(CV:木野日菜)", 1],
    [4, "Make Up Life!(ルフリアソロ)", "ルフリア(CV:川井田夏海)", 1],
    [5, "Make Up Life!(ラキラソロ)", "ラキラ(CV:石見舞菜香)", 1],
    [6, "Make Up Life! オリジナル・カラオケ", "風色琴音、ファー、ラキラ、ルフリア(CV:井上ほの花、木野日菜、川井田夏海、石見舞菜香)", 1],
]
links = ["https://beta.musicbrainz.org/release/6a73e453-aaba-4a3a-9124-b3cad02765fc", "https://vgmdb.net/album/118325"]

[e5eb59bcd8911a1ec8738b68818f31d4]
catalognumber = "COZC-1892~3"
date = "2022-04-27"
album = "Make Up Life! / 風色琴音(CV:井上ほの花)、ファー(CV:木野日菜)、ルフリア(CV:川井田夏海)、ラキラ(CV:石見舞菜香) [限定盤] Video"
tracks = [
    [1, "RPG不動産キャスト対談≪井上ほの花×川井田夏海≫≪木野日菜×石見舞菜香≫", "井上ほの花×川井田夏海 / 木野日菜×石見舞菜香", 0],
    [2, "連想ゲーム", "井上ほの花, 木野日菜, 川井田夏海 & 石見舞菜香", 0],
    [3, "4人一致を目指そう！", "井上ほの花, 木野日菜, 川井田夏海 & 石見舞菜香", 0],
    [4, "自分のRPG不動産", "井上ほの花, 木野日菜, 川井田夏海 & 石見舞菜香", 0],
    [5, "4人からのメッセージ", "井上ほの花, 木野日菜, 川井田夏海 & 石見舞菜香", 0],
    [6, "エンディング ～Make Up Life!～", "風色琴音、ファー、ラキラ、ルフリア(CV:井上ほの花、木野日菜、川井田夏海、石見舞菜香)", 0],
]
links = ["https://beta.musicbrainz.org/release/6a73e453-aaba-4a3a-9124-b3cad02765fc", "https://vgmdb.net/album/118325"]

[2df3411f4072bc8fa78b9d76b61d6e95]
catalognumber = "COCC-17996"
date = "2022-04-27"
album = "Make Up Life! / 風色琴音(CV:井上ほの花)、ファー(CV:木野日菜)、ルフリア(CV:川井田夏海)、ラキラ(CV:石見舞菜香)"
tracks = [
    [1, "Make Up Life!", "風色琴音、ファー、ラキラ、ルフリア(CV:井上ほの花、木野日菜、川井田夏海、石見舞菜香)", 2],
    [2, "Make Up Life!(琴音ソロ)", "風色琴音(CV:井上ほの花)", 1],
    [3, "Make Up Life!(ファーソロ)", "ファー(CV:木野日菜)", 1],
    [4, "Make Up Life!(ルフリアソロ)", "ルフリア(CV:川井田夏海)", 1],
    [5, "Make Up Life!(ラキラソロ)", "ラキラ(CV:石見舞菜香)", 1],
    [6, "Make Up Life! オリジナル・カラオケ", "風色琴音、ファー、ラキラ、ルフリア(CV:井上ほの花、木野日菜、川井田夏海、石見舞菜香)", 1],
]
links = ["https://beta.musicbrainz.org/release/bf9cc374-681f-4cff-ae02-18fb47e0638d", "https://vgmdb.net/album/118324"]
