[46e66136271719cc2a4de327d767f01b]
catalognumber = "LASM-4060"
date = "2010-07-28"
album = "Now loading...SKY!! / スフィア"
tracks = [
    [1, "Now loading...SKY!!", "スフィア", 0],
    [2, "かってな成長期", "スフィア", 0],
    [3, "Now loading...SKY!! (Off Vocal)", "スフィア", 0],
    [4, "かってな成長期 (Off Vocal)", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/ed07ac94-fdcd-3e1e-ba6e-f0ba67b4b458", "https://vgmdb.net/album/25371"]

[2fccb35257e272bd061a76435f63d74a]
catalognumber = "LASM-34060~1"
date = "2010-07-28"
album = "Now loading...SKY!! / スフィア [限定生産盤] Vocal"
tracks = [
    [1, "Now loading...SKY!!", "スフィア", 0],
    [2, "かってな成長期", "スフィア", 0],
    [3, "Now loading...SKY!! (Off Vocal)", "スフィア", 0],
    [4, "かってな成長期 (Off Vocal)", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/d1d128ed-09d9-4544-9493-c4a6d26c4aed", "https://vgmdb.net/album/25379"]

[9f88df3c9523bfbc53f9f45227f28168]
catalognumber = "LASM-34060~1"
date = "2010-07-28"
album = "Now loading...SKY!! / スフィア [限定生産盤] Disc 2 (DVD) [LASM-34061]"
tracks = [
    [1, "Now loading...SKY!! Music Clip", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/d1d128ed-09d9-4544-9493-c4a6d26c4aed", "https://vgmdb.net/album/25379"]

[534bba7483af4b0e8089e50444970a92]
catalognumber = "LASM-4062"
date = "2010-08-11"
album = "Happy Sunshine / エリス (CV.伊藤かな恵)"
tracks = [
    [1, "Happy Sunshine", "エリス(CV.伊藤かな恵)", 0],
    [2, "Wonderfulな世界", "エリス(CV.伊藤かな恵)", 0],
    [3, "Happy Sunshine (off vocal)", "エリス(CV.伊藤かな恵)", 0],
    [4, "Wonderfulな世界 (off vocal)", "エリス(CV.伊藤かな恵)", 0],
]
links = ["https://beta.musicbrainz.org/release/6322880b-36ea-41bf-8223-42acee0eabd1", "https://vgmdb.net/album/25374"]

[fbf46401989476cd0ad1d03d205b1e58]
catalognumber = "LASM-4063"
date = "2010-08-11"
album = "心の窓辺にて / 双葉アオイ(CV.花澤香菜)"
tracks = [
    [1, "心の窓辺にて", "双葉アオイ(CV.花澤香菜)", 0],
    [2, "君色＊コンプリート", "双葉アオイ(CV.花澤香菜)", 0],
    [3, "心の窓辺にて (off vocal)", "双葉アオイ(CV.花澤香菜)", 0],
    [4, "君色＊コンプリート (off vocal)", "双葉アオイ(CV.花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/8fbc7d2d-8cdd-4547-94cb-c53dc5377e17", "https://vgmdb.net/album/25372"]

[848a74ded5161ec05132f73a64034dcd]
catalognumber = "LASM-4064"
date = "2010-08-11"
album = "想い出がジャマをする / 金武城真奈美(CV.戸松遥)"
tracks = [
    [1, "想い出がジャマをする", "金武城真奈美(CV.戸松 遥)", 0],
    [2, "君にOver Drive", "金武城真奈美(CV.戸松 遥)", 0],
    [3, "想い出がジャマをする (off vocal)", "金武城真奈美(CV.戸松 遥)", 0],
    [4, "君にOver Drive (off vocal)", "金武城真奈美(CV.戸松 遥)", 0],
]
links = ["https://beta.musicbrainz.org/release/a47f9eeb-264c-48dc-ad64-22d5e8645970", "https://vgmdb.net/album/25373"]

[bb96fb946af7d4e489a218c1e618b88a]
catalognumber = "LASA-5057"
date = "2010-09-08"
album = "TVアニメ「あそびにいくヨ!」ドラマ+キャラソンCD ～きもめだししました～"
tracks = [
    [1, "こわいおはなし。", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [2, "おふろでぷるるん♡", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [3, "いちらく☆ぱーと・わん", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [4, "からおけしましょ♪", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [5, "わかさとおべんとう。", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [6, "いちらく☆ぱーと・つー", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [7, "きもだめしでどっきり！", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [8, "あったかいせなか。", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [9, "ついにはっけん！？", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [10, "あのこはだあれ？", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 0],
    [11, "スマイル☆ピース", "エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/451b837e-5fca-4274-a8ef-85488751dbf4", "https://vgmdb.net/album/25381"]

[b2e077c8a04e5ab2c9084420b2bb5d1e]
catalognumber = "LASA-5062"
date = "2010-09-22"
album = "TVアニメ「あそびにいくヨ!」 ORIGINAL SOUND TRACK"
tracks = [
    [1, "ちゅら海の奏", "菊谷知樹", 0],
    [2, "あそびきにました！", "菊谷知樹", 0],
    [3, "エリスのテーマ", "菊谷知樹", 0],
    [4, "ゴロゴロしましょ♡", "菊谷知樹", 0],
    [5, "海と太陽とサングラス", "菊谷知樹", 0],
    [6, "真奈美のテーマ", "菊谷知樹", 0],
    [7, "ご、誤解ですぅ", "菊谷知樹", 0],
    [8, "実像と虚像と", "菊谷知樹", 0],
    [9, "悪運紅葉", "菊谷知樹", 0],
    [10, "迷い", "菊谷知樹", 0],
    [11, "アオイのテーマ", "菊谷知樹", 0],
    [12, "宝物のような想い出", "菊谷知樹", 0],
    [13, "コバルトブルーの海", "菊谷知樹", 0],
    [14, "アシストロイドのテーマ", "菊谷知樹", 0],
    [15, "ルーロスのテーマ", "菊谷知樹", 0],
    [16, "キャーティア奇跡のテクノロジー", "菊谷知樹", 0],
    [17, "猫耳教団のテーマ", "菊谷知樹", 0],
    [18, "猫耳の福音", "菊谷知樹", 0],
    [19, "ご神体を取り戻せ", "菊谷知樹", 0],
    [20, "情報戦", "菊谷知樹", 0],
    [21, "忍び寄る影", "菊谷知樹", 0],
    [22, "DIAファイル", "菊谷知樹", 0],
    [23, "戦闘準備", "菊谷知樹", 0],
    [24, "秘密結社·ビューティフルコンタクトのテーマ", "菊谷知樹", 0],
    [25, "荘厳なる行進", "菊谷知樹", 0],
    [26, "結界", "菊谷知樹", 0],
    [27, "奪還せよ！", "菊谷知樹", 0],
    [28, "追撃を振り切って", "菊谷知樹", 0],
    [29, "chase！chase！chase！", "菊谷知樹", 0],
    [30, "攻防", "菊谷知樹", 0],
    [31, "決死の作戦", "菊谷知樹", 0],
    [32, "激突！", "菊谷知樹", 0],
    [33, "マタタビくらくらHappy♪", "菊谷知樹", 0],
    [34, "肉球のワルツ", "菊谷知樹", 0],
    [35, "繁殖しましょ♡", "菊谷知樹", 0],
    [36, "サヨナラ発情期", "菊谷知樹", 0],
    [37, "優しい彼", "菊谷知樹", 0],
    [38, "騎央のテーマ", "菊谷知樹", 0],
    [39, "伝えたい気持ちは一つなのに", "菊谷知樹", 0],
    [40, "君の背中は遠く", "菊谷知樹", 0],
    [41, "沖縄の風に吹かれて", "菊谷知樹", 0],
    [42, "次回予告！！", "菊谷知樹", 0],
    [43, "おいらは淋しいスペースマン", "ラウリィ(茅原実里)", 0],
]
links = ["https://beta.musicbrainz.org/release/61a64040-7dea-4e31-a913-2f56f5a3ca9d", "https://vgmdb.net/album/20460"]

[5e78a5eafe541d47a723c5677b573218]
catalognumber = "LASA-35085~6"
date = "2011-03-16"
album = "Spring is here / Sphere [Limited Edition] Vocal"
tracks = [
    [1, "Spring is here", "スフィア", 0],
    [2, "Now loading...SKY!!", "スフィア", 0],
    [3, "キミが太陽", "スフィア", 0],
    [4, "REALOVE:REALIFE", "スフィア", 0],
    [5, "Congratulations!!", "スフィア", 0],
    [6, "手のひらに夢", "スフィア", 0],
    [7, "風をあつめて", "スフィア", 0],
    [8, "かってな成長期", "スフィア", 0],
    [9, "MOON SIGNAL", "スフィア", 0],
    [10, "By MY PACE!!", "スフィア", 0],
    [11, "Brave my heart", "スフィア", 0],
    [12, "クライマックスホイッスル", "スフィア", 0],
    [13, "夢奏レコード", "スフィア", 0],
    [14, "虹を駆ける旋律", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/a87f5632-6f13-4177-9530-73145ecadc7d", "https://vgmdb.net/album/44274"]

[dd9b35e9e8bde00301c63fc699cade2e]
catalognumber = "LASA-35085~6"
date = "2011-03-16"
album = "Spring is here / Sphere [Limited Edition] Video"
tracks = [
    [1, "『Spring is here』 Music Clip", "スフィア", 0],
    [2, "Making", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/a87f5632-6f13-4177-9530-73145ecadc7d", "https://vgmdb.net/album/44274"]

[e6f51181f84a8852fc6f91cd8e0a77c2]
catalognumber = "LASA-35089~91"
date = "2011-03-16"
album = "Spring is here / Sphere [Crystal Spring Box/Limited Edition] Vocal"
tracks = [
    [1, "Spring is here", "スフィア", 0],
    [2, "Now loading...SKY!!", "スフィア", 0],
    [3, "キミが太陽", "スフィア", 0],
    [4, "REALOVE:REALIFE", "スフィア", 0],
    [5, "Congratulations!!", "スフィア", 0],
    [6, "手のひらに夢", "スフィア", 0],
    [7, "風をあつめて", "スフィア", 0],
    [8, "かってな成長期", "スフィア", 0],
    [9, "MOON SIGNAL", "スフィア", 0],
    [10, "By MY PACE!!", "スフィア", 0],
    [11, "Brave my heart", "スフィア", 0],
    [12, "クライマックスホイッスル", "スフィア", 0],
    [13, "夢奏レコード", "スフィア", 0],
    [14, "虹を駆ける旋律", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/7512a97b-f6e8-40d2-a0d2-f1ed134fb3cf", "https://vgmdb.net/album/71788"]

[03803ee9f61592ff5e46f7ce8ba7370a]
catalognumber = "LASA-35089~91"
date = "2011-03-16"
album = "Spring is here / Sphere [Crystal Spring Box/Limited Edition] Video Disc 2"
tracks = [
    [1, "『Spring is here』 Music Clip", "スフィア", 0],
    [2, "Making", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/a87f5632-6f13-4177-9530-73145ecadc7d", "https://vgmdb.net/album/71788"]

[a1047aea6fba9706785049622f697bd1]
catalognumber = "LASA-35089~91"
date = "2011-03-16"
album = "Spring is here / Sphere [Crystal Spring Box/Limited Edition] Video Disc 3"
tracks = [
    [1, "『うたたね』スフィア特集", "スフィア", 0],
    [2, "MOON SIGNAL in 武道館", "スフィア", 0],
    [3, "クライマックスホイッスル in 武道館", "スフィア", 0],
    [4, "『スフィアと過ごす、“一日遅れの”プレミアムクリスマスパーティー』ダイジェスト", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/7512a97b-f6e8-40d2-a0d2-f1ed134fb3cf", "https://vgmdb.net/album/71788"]

[9fb11e0015ed010572401a52f776519b]
catalognumber = "LASA-5085"
date = "2011-03-16"
album = "Spring is here / Sphere"
tracks = [
    [1, "Spring is here", "スフィア", 0],
    [2, "Now loading...SKY!!", "スフィア", 0],
    [3, "キミが太陽", "スフィア", 0],
    [4, "REALOVE:REALIFE", "スフィア", 0],
    [5, "Congratulations!!", "スフィア", 0],
    [6, "手のひらに夢", "スフィア", 0],
    [7, "風をあつめて", "スフィア", 0],
    [8, "かってな成長期", "スフィア", 0],
    [9, "MOON SIGNAL", "スフィア", 0],
    [10, "By MY PACE!!", "スフィア", 0],
    [11, "Brave my heart", "スフィア", 0],
    [12, "クライマックスホイッスル", "スフィア", 0],
    [13, "夢奏レコード", "スフィア", 0],
    [14, "虹を駆ける旋律", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/82312e7a-011f-4c17-b936-bc786067a82e", "https://vgmdb.net/album/71787"]

[3b820efb8e57565dc1d92b9deff93d7c]
catalognumber = "SVWC-70189~90"
date = "2016-08-30"
album = "KANAight ～花澤香菜キャラソン ハイパークロニクルミックス～ Disc 1 [SVWC-70189]"
tracks = [
    [1, "恋愛サーキュレーション -Yunomi \"Kawaii EDM\" Remix-", "", 0],
    [2, "リカバーデコレーション -Hymn to the Queen Remix-", "", 0],
    [3, "Delicateにラブ・ミー・プリーズ -More Delicate Remix-", "", 0],
    [4, "モノクロ☆HAPPY DAY -Small Chic Dance Remix-", "", 0],
    [5, "おしえてナウカ、夢みるペチカ -cozy analog Remix-", "", 0],
    [6, "もうそう♡えくすぷれす -folclore Remix-", "", 0],
    [7, "sweets parade -lyrical Remix-", "", 0],
]
links = ["https://vgmdb.net/album/65499"]

[e2b7eec1fc655b50130c2ab6cc9f1589]
catalognumber = "SVWC-70189~90"
date = "2016-08-30"
album = "KANAight ～花澤香菜キャラソン ハイパークロニクルミックス～ Disc 2 [SVWC-70190]"
tracks = [
    [1, "恋するマドモアゼル", "シャルロット・デュノア(花澤香菜)", 0],
    [2, "I wonder why…", "向井戸まなか(花澤香菜)", 0],
    [3, "シナプスの鏡", "邪神かがみ(花澤香菜)", 0],
    [4, "みどりのメロディ", "草野(花澤香菜)", 0],
    [5, "Raison d'etre", "汐宮栞(花澤香菜)", 0],
    [6, "Delicateにラブ・ミー・プリーズ", "ざんげちゃん(花澤香菜)", 0],
    [7, "ソレイユ・ブーケ", "シャルロット・デュノア(花澤香菜)", 0],
    [8, "モノクロ☆HAPPY DAY", "黒猫(花澤香菜)", 0],
    [9, "キミをマモリタイ", "市ヶ谷りか(花澤香菜)", 0],
    [10, "ヘンな神様知ってるよ", "乱崎優歌(花澤香菜)", 0],
    [11, "Qunka!", "板東まりも(花澤香菜)", 0],
    [12, "HEAVEN's TALE", "ベンヤ(花澤香菜)", 0],
    [13, "バンブー・ランデヴー♡", "メイメイ(花澤香菜)", 0],
    [14, "迷惑スペクタクル", "横井るみ(花澤香菜)", 0],
    [15, "まじかる☆まーじゃん☆わーるど (ver.玄)", "松実玄(花澤香菜)", 0],
    [16, "Punctuation!", "松隆奈々子(花澤香菜)", 0],
    [17, "自主恋Shoooooter!", "湊智花(花澤香菜)", 0],
    [18, "君色*コンプリート", "双葉アオイ(花澤香菜)", 0],
    [19, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(花澤香菜)", 0],
    [20, "Dazzling Smile", "マリー(花澤香菜)", 0],
    [21, "ハッピーガール☆ラッキーガール!", "桜市子(花澤香菜)", 0],
    [22, "ダンジョン ショコラティエース", "シロ(花澤香菜)", 0],
    [23, "おにくじゃぽねすく!", "ゼウシくん(花澤香菜)", 0],
    [24, "プリコグ (M@STER VERSION)", "水谷絵理(花澤香菜)", 0],
    [25, "みのりのぞっこん未来予報♡", "中沢農(花澤香菜)", 0],
    [26, "君らしくなきゃヤダよ!", "結城美柑(花澤香菜)", 0],
    [27, "私がモテないのは可愛くないからだよね?", "ゆうちゃん(花澤香菜)", 0],
    [28, "心の窓辺にて", "双葉アオイ(花澤香菜)", 0],
    [29, "もうそう♡えくすぷれす", "千石撫子(花澤香菜)", 0],
    [30, "sweets parade", "髏々宮カルタ(花澤香菜)", 0],
    [31, "リカバーデコレーション", "小野寺小咲(花澤香菜)", 0],
    [32, "スプーンひとさじの愛", "宮野まゆ(花澤香菜)", 0],
    [33, "恋愛サーキュレーション", "千石撫子(花澤香菜)", 0],
    [34, "あした来る日〜桜咲くころ", "花戸小鳩(花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/af9b0033-666b-42e6-be05-cb4280729814", "https://vgmdb.net/album/65499"]
