[dbfcb92083c7d3e9fafe349b26ba64e7]
catalognumber = "LASM-4060"
date = "2010-07-28"
album = "Now loading...SKY!! / スフィア"
tracks = [
    [1, "Now loading...SKY!!", "スフィア", 1],
    [2, "かってな成長期", "スフィア", 2],
    [3, "Now loading...SKY!! (Off Vocal)", "スフィア", 1],
    [4, "かってな成長期 (Off Vocal)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/ed07ac94-fdcd-3e1e-ba6e-f0ba67b4b458", "https://vgmdb.net/album/25371"]

[52fe6f9ade8e19c43262e3fe9479b074]
catalognumber = "LASM-34060~1"
date = "2010-07-28"
album = "Now loading...SKY!! / スフィア [限定生産盤] Vocal"
tracks = [
    [1, "Now loading...SKY!!", "スフィア", 1],
    [2, "かってな成長期", "スフィア", 1],
    [3, "Now loading...SKY!! (Off Vocal)", "スフィア", 1],
    [4, "かってな成長期 (Off Vocal)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/d1d128ed-09d9-4544-9493-c4a6d26c4aed", "https://vgmdb.net/album/25379"]

[3f799f7a751c5c66e466b2e9aa684e71]
catalognumber = "LASM-34060~1"
date = "2010-07-28"
album = "Now loading...SKY!! / スフィア [限定生産盤] Disc 2 (DVD) [LASM-34061]"
tracks = [
    [1, "Now loading...SKY!! Music Clip", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/d1d128ed-09d9-4544-9493-c4a6d26c4aed", "https://vgmdb.net/album/25379"]

[b83eef6dfbf905176713e5e0c814ea6c]
catalognumber = "LASM-4062"
date = "2010-08-11"
album = "Happy Sunshine / エリス (CV.伊藤かな恵)"
tracks = [
    [1, "Happy Sunshine", "エリス(CV.伊藤かな恵)", 2],
    [2, "Wonderfulな世界", "エリス(CV.伊藤かな恵)", 1],
    [3, "Happy Sunshine (off vocal)", "エリス(CV.伊藤かな恵)", 1],
    [4, "Wonderfulな世界 (off vocal)", "エリス(CV.伊藤かな恵)", 1],
]
links = ["https://beta.musicbrainz.org/release/6322880b-36ea-41bf-8223-42acee0eabd1", "https://vgmdb.net/album/25374"]

[9cc444b049686cd01469a6413d7e7bba]
catalognumber = "LASM-4063"
date = "2010-08-11"
album = "心の窓辺にて / 双葉アオイ(CV.花澤香菜)"
tracks = [
    [1, "心の窓辺にて", "双葉アオイ(CV.花澤香菜)", 2],
    [2, "君色＊コンプリート", "双葉アオイ(CV.花澤香菜)", 1],
    [3, "心の窓辺にて (off vocal)", "双葉アオイ(CV.花澤香菜)", 1],
    [4, "君色＊コンプリート (off vocal)", "双葉アオイ(CV.花澤香菜)", 1],
]
links = ["https://beta.musicbrainz.org/release/8fbc7d2d-8cdd-4547-94cb-c53dc5377e17", "https://vgmdb.net/album/25372"]

[99379bb3fb411d0802f07685fd0cc8c3]
catalognumber = "LASM-4064"
date = "2010-08-11"
album = "想い出がジャマをする / 金武城真奈美(CV.戸松遥)"
tracks = [
    [1, "想い出がジャマをする", "金武城真奈美(CV.戸松 遥)", 1],
    [2, "君にOver Drive", "金武城真奈美(CV.戸松 遥)", 2],
    [3, "想い出がジャマをする (off vocal)", "金武城真奈美(CV.戸松 遥)", 1],
    [4, "君にOver Drive (off vocal)", "金武城真奈美(CV.戸松 遥)", 1],
]
links = ["https://beta.musicbrainz.org/release/a47f9eeb-264c-48dc-ad64-22d5e8645970", "https://vgmdb.net/album/25373"]

[1911a74feffadfc69faa84040b1cf738]
catalognumber = "LASA-5057"
date = "2010-09-08"
album = "TVアニメ「あそびにいくヨ!」ドラマ+キャラソンCD ～きもめだししました～"
tracks = [
    [1, "こわいおはなし。", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [2, "おふろでぷるるん♡", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [3, "いちらく☆ぱーと・わん", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [4, "からおけしましょ♪", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [5, "わかさとおべんとう。", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [6, "いちらく☆ぱーと・つー", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [7, "きもだめしでどっきり！", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [8, "あったかいせなか。", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [9, "ついにはっけん！？", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [10, "あのこはだあれ？", "嘉和騎央(CV.田村睦心),エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜),糸嘉州マキ (CV.平田宏美)", 1],
    [11, "スマイル☆ピース", "エリス (CV.伊藤かな恵),金武城真奈美 (CV.戸松遥),双葉アオイ (CV.花澤香菜)", 2],
]
links = ["https://beta.musicbrainz.org/release/451b837e-5fca-4274-a8ef-85488751dbf4", "https://vgmdb.net/album/25381"]

[70ed9f7582f48167cd33268f181dce30]
catalognumber = "LASA-5062"
date = "2010-09-22"
album = "TVアニメ「あそびにいくヨ!」 ORIGINAL SOUND TRACK"
tracks = [
    [1, "ちゅら海の奏", "菊谷知樹", 1],
    [2, "あそびきにました！", "菊谷知樹", 1],
    [3, "エリスのテーマ", "菊谷知樹", 1],
    [4, "ゴロゴロしましょ♡", "菊谷知樹", 1],
    [5, "海と太陽とサングラス", "菊谷知樹", 1],
    [6, "真奈美のテーマ", "菊谷知樹", 1],
    [7, "ご、誤解ですぅ", "菊谷知樹", 1],
    [8, "実像と虚像と", "菊谷知樹", 1],
    [9, "悪運紅葉", "菊谷知樹", 1],
    [10, "迷い", "菊谷知樹", 1],
    [11, "アオイのテーマ", "菊谷知樹", 1],
    [12, "宝物のような想い出", "菊谷知樹", 1],
    [13, "コバルトブルーの海", "菊谷知樹", 1],
    [14, "アシストロイドのテーマ", "菊谷知樹", 1],
    [15, "ルーロスのテーマ", "菊谷知樹", 1],
    [16, "キャーティア奇跡のテクノロジー", "菊谷知樹", 1],
    [17, "猫耳教団のテーマ", "菊谷知樹", 1],
    [18, "猫耳の福音", "菊谷知樹", 1],
    [19, "ご神体を取り戻せ", "菊谷知樹", 1],
    [20, "情報戦", "菊谷知樹", 1],
    [21, "忍び寄る影", "菊谷知樹", 1],
    [22, "DIAファイル", "菊谷知樹", 1],
    [23, "戦闘準備", "菊谷知樹", 1],
    [24, "秘密結社·ビューティフルコンタクトのテーマ", "菊谷知樹", 1],
    [25, "荘厳なる行進", "菊谷知樹", 1],
    [26, "結界", "菊谷知樹", 1],
    [27, "奪還せよ！", "菊谷知樹", 1],
    [28, "追撃を振り切って", "菊谷知樹", 1],
    [29, "chase！chase！chase！", "菊谷知樹", 1],
    [30, "攻防", "菊谷知樹", 1],
    [31, "決死の作戦", "菊谷知樹", 1],
    [32, "激突！", "菊谷知樹", 1],
    [33, "マタタビくらくらHappy♪", "菊谷知樹", 1],
    [34, "肉球のワルツ", "菊谷知樹", 1],
    [35, "繁殖しましょ♡", "菊谷知樹", 1],
    [36, "サヨナラ発情期", "菊谷知樹", 1],
    [37, "優しい彼", "菊谷知樹", 1],
    [38, "騎央のテーマ", "菊谷知樹", 1],
    [39, "伝えたい気持ちは一つなのに", "菊谷知樹", 1],
    [40, "君の背中は遠く", "菊谷知樹", 1],
    [41, "沖縄の風に吹かれて", "菊谷知樹", 1],
    [42, "次回予告！！", "菊谷知樹", 1],
    [43, "おいらは淋しいスペースマン", "ラウリィ(茅原実里)", 1],
]
links = ["https://beta.musicbrainz.org/release/61a64040-7dea-4e31-a913-2f56f5a3ca9d", "https://vgmdb.net/album/20460"]

[72bf659c967a678d65c643d54eecd2c5]
catalognumber = "LASA-35085~6"
date = "2011-03-16"
album = "Spring is here / Sphere [Limited Edition] Vocal"
tracks = [
    [1, "Spring is here", "スフィア", 0],
    [2, "Now loading...SKY!!", "スフィア", 1],
    [3, "キミが太陽", "スフィア", 0],
    [4, "REALOVE:REALIFE", "スフィア", 0],
    [5, "Congratulations!!", "スフィア", 0],
    [6, "手のひらに夢", "スフィア", 0],
    [7, "風をあつめて", "スフィア", 0],
    [8, "かってな成長期", "スフィア", 1],
    [9, "MOON SIGNAL", "スフィア", 0],
    [10, "By MY PACE!!", "スフィア", 0],
    [11, "Brave my heart", "スフィア", 0],
    [12, "クライマックスホイッスル", "スフィア", 0],
    [13, "夢奏レコード", "スフィア", 0],
    [14, "虹を駆ける旋律", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/a87f5632-6f13-4177-9530-73145ecadc7d", "https://vgmdb.net/album/44274"]

[dd9b35e9e8bde00301c63fc699cade2e]
catalognumber = "LASA-35085~6"
date = "2011-03-16"
album = "Spring is here / Sphere [Limited Edition] Video"
tracks = [
    [1, "『Spring is here』 Music Clip", "スフィア", 0],
    [2, "Making", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/a87f5632-6f13-4177-9530-73145ecadc7d", "https://vgmdb.net/album/44274"]

[4ac87916f7d19408d48353b4e5715911]
catalognumber = "LASA-35089~91"
date = "2011-03-16"
album = "Spring is here / Sphere [Crystal Spring Box/Limited Edition] Vocal"
tracks = [
    [1, "Spring is here", "スフィア", 0],
    [2, "Now loading...SKY!!", "スフィア", 1],
    [3, "キミが太陽", "スフィア", 0],
    [4, "REALOVE:REALIFE", "スフィア", 0],
    [5, "Congratulations!!", "スフィア", 0],
    [6, "手のひらに夢", "スフィア", 0],
    [7, "風をあつめて", "スフィア", 0],
    [8, "かってな成長期", "スフィア", 1],
    [9, "MOON SIGNAL", "スフィア", 0],
    [10, "By MY PACE!!", "スフィア", 0],
    [11, "Brave my heart", "スフィア", 0],
    [12, "クライマックスホイッスル", "スフィア", 0],
    [13, "夢奏レコード", "スフィア", 0],
    [14, "虹を駆ける旋律", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/7512a97b-f6e8-40d2-a0d2-f1ed134fb3cf", "https://vgmdb.net/album/71788"]

[03803ee9f61592ff5e46f7ce8ba7370a]
catalognumber = "LASA-35089~91"
date = "2011-03-16"
album = "Spring is here / Sphere [Crystal Spring Box/Limited Edition] Video Disc 2"
tracks = [
    [1, "『Spring is here』 Music Clip", "スフィア", 0],
    [2, "Making", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/a87f5632-6f13-4177-9530-73145ecadc7d", "https://vgmdb.net/album/71788"]

[a1047aea6fba9706785049622f697bd1]
catalognumber = "LASA-35089~91"
date = "2011-03-16"
album = "Spring is here / Sphere [Crystal Spring Box/Limited Edition] Video Disc 3"
tracks = [
    [1, "『うたたね』スフィア特集", "スフィア", 0],
    [2, "MOON SIGNAL in 武道館", "スフィア", 0],
    [3, "クライマックスホイッスル in 武道館", "スフィア", 0],
    [4, "『スフィアと過ごす、“一日遅れの”プレミアムクリスマスパーティー』ダイジェスト", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/7512a97b-f6e8-40d2-a0d2-f1ed134fb3cf", "https://vgmdb.net/album/71788"]

[f0c2b4b078fab01267aaf2e70a40eb06]
catalognumber = "LASA-5085"
date = "2011-03-16"
album = "Spring is here / Sphere"
tracks = [
    [1, "Spring is here", "スフィア", 0],
    [2, "Now loading...SKY!!", "スフィア", 1],
    [3, "キミが太陽", "スフィア", 0],
    [4, "REALOVE:REALIFE", "スフィア", 0],
    [5, "Congratulations!!", "スフィア", 0],
    [6, "手のひらに夢", "スフィア", 0],
    [7, "風をあつめて", "スフィア", 0],
    [8, "かってな成長期", "スフィア", 1],
    [9, "MOON SIGNAL", "スフィア", 0],
    [10, "By MY PACE!!", "スフィア", 0],
    [11, "Brave my heart", "スフィア", 0],
    [12, "クライマックスホイッスル", "スフィア", 0],
    [13, "夢奏レコード", "スフィア", 0],
    [14, "虹を駆ける旋律", "スフィア", 0],
]
links = ["https://beta.musicbrainz.org/release/82312e7a-011f-4c17-b936-bc786067a82e", "https://vgmdb.net/album/71787"]
