[89f6dedca6dd8e6f72e9f5e59ea06891]
catalognumber = "TYDY-2036"
date = "1992-05-01"
album = "勇気のファイター / YASU"
tracks = [
    [1, "勇気のファイター", "", 0],
    [2, "Dear My Best Friend", "", 0],
]
links = ["https://vgmdb.net/album/71542"]

[658966c7886025ec0acf61273ca56b86]
catalognumber = "TYCY-5232"
date = "1992-06-24"
album = "うしおととら オリジナル・アルバム"
tracks = [
    [1, "Overture～紫紺の調", "", 0],
    [2, "英雄不要論序説", "", 0],
    [3, "Kaleidoscopical sky", "", 0],
    [4, "獣を見たよ", "", 0],
    [5, "ブギ、ウギ、モンスター", "", 0],
    [6, "雷(いかずち)の舞", "", 0],
    [7, "オーディオ・ドラマ 麻子が語る うしおととら出会うの縁", "", 0],
    [8, "パンドラの箱", "", 0],
    [9, "サイレンスの下で…", "", 0],
]
links = ["https://vgmdb.net/album/56677"]

[4347f85dcfb30621a43afd8897170f94]
catalognumber = "TYCY-5247"
date = "1992-08-26"
album = "うしおととらII オリジナル・サウンド・トラック"
tracks = [
    [1, "勇気のファイター", "", 0],
    [2, "500年前の死闘", "", 0],
    [3, "おれとボケおやじ", "", 0],
    [4, "謎の地下室", "", 0],
    [5, "悲しみの逆襲", "", 0],
    [6, "アイキャッチ", "", 0],
    [7, "うしお変身!", "", 0],
    [8, "別れ", "", 0],
    [9, "奇妙な関係", "", 0],
    [10, "妖怪退治心得マーチ", "", 0],
    [11, "妖怪の楽しみ", "", 0],
    [12, "無気味な影", "", 0],
    [13, "石喰い", "", 0],
    [14, "幻になるまで", "", 0],
    [15, "票の仇", "", 0],
    [16, "狙われるとら", "", 0],
    [17, "Dear My Best Friend", "", 0],
]
links = ["https://vgmdb.net/album/56699"]

[545ee73723fdf996fa07e3ba2997dde7]
catalognumber = "TYCY-5252"
date = "1992-09-23"
album = "ミニ・ヒストリー・オブ・ユーメックスVol.Ⅱ VIDEO・ヴォーカル・ライブラリー"
tracks = [
    [1, "戦え!!イクサー1", "", 0],
    [2, "S.F.", "", 0],
    [3, "アイ・シティ", "", 0],
    [4, "今夜はハリケーン", "", 0],
    [5, "Finally～ストリート・ダンサーに愛をこめて", "", 0],
    [6, "未来ROMANCER", "", 0],
    [7, "DANCIN' WITH A HEARTACHE", "", 0],
    [8, "チェリームーンで踊らせて", "", 0],
    [9, "ROAD BUSTER", "", 0],
    [10, "紅のロンリネス", "", 0],
    [11, "剣豪烈伝", "", 0],
    [12, "戦え!おたキング", "", 0],
    [13, "幻想地帯", "", 0],
    [14, "勇気のファイター", "", 0],
]
links = ["https://vgmdb.net/album/137471"]

[b40a4bbf35144422217bdfd0b4a0cf6c]
catalognumber = "TYDY-2045"
date = "1993-04-07"
album = "獣の槍/誰かがおまえを狙ってる"
tracks = [
    [1, "獣の槍", "", 0],
    [2, "誰かがおまえを狙ってる", "", 0],
]
links = ["https://vgmdb.net/album/71543"]

[968360d4034b8175838d3d538b3e39b2]
catalognumber = "TYCY-5306"
date = "1993-05-26"
album = "うしおととらIII Resurrection"
tracks = [
    [1, "獣の槍", "", 0],
    [2, "果敢な勇者", "", 0],
    [3, "憎しみの果て", "", 0],
    [4, "気配", "", 0],
    [5, "剛くやさしい心", "", 0],
    [6, "悲しみを憎しみに変えて", "", 0],
    [7, "儚い生涯", "", 0],
    [8, "Resurrection 〜天使たちの復活〜", "", 0],
    [9, "妖気", "", 0],
    [10, "アイ・キャッチ", "", 0],
    [11, "夏の終わりの戯れ", "", 0],
    [12, "トランシーバーの少年", "", 0],
    [13, "海の蛇(くちなわ)", "", 0],
    [14, "たばね役 \"海座頭\"", "", 0],
    [15, "風と雪の化身", "", 0],
    [16, "悪戦苦闘", "", 0],
    [17, "幼少の時代(とき)", "", 0],
    [18, "暗雲低迷", "", 0],
    [19, "長飛丸参上!", "", 0],
    [20, "魂たちの解放", "", 0],
    [21, "ささやかな休息", "", 0],
    [22, "誰かがおまえを狙ってる", "", 0],
]
links = ["https://vgmdb.net/album/56707"]

[0ef602369de276e0819857edaf6838e5]
catalognumber = "TYCY-5308"
date = "1993-06-23"
album = "うしおととら ヴォーカル・コレクション"
tracks = [
    [1, "獣の槍", "井口慎也", 0],
    [2, "Dear My Best Friend", "佐々木望", 0],
    [3, "英雄不要論序説", "yasu", 0],
    [4, "獣を見たよ", "佐々木望", 0],
    [5, "ブギ・ウギ・モンスター", "天野由梨 & 冬馬由美", 0],
    [6, "パンドラの箱", "Hidemi Miura", 0],
    [7, "サイレンスの下で…", "yasu & Hidemi Miura", 0],
    [8, "悲しみの逆襲", "yasu", 0],
    [9, "妖怪退治心得マーチ", "佐々木望", 0],
    [10, "幻になるまで", "Hidemi Miura", 0],
    [11, "誰かがおまえを狙ってる", "佐々木望", 0],
    [12, "Resurrection 〜天使たちの復活〜", "井口慎也", 0],
    [13, "風と雪の化身", "SATOKO", 0],
    [14, "勇気のファイター", "yasu", 0],
]
links = ["https://beta.musicbrainz.org/release/3cc2a6f6-ef78-44a4-a89b-b7d2d6c647ee", "https://vgmdb.net/album/56718"]

[527385f797c24da046f8cffd4bb3182b]
catalognumber = "TKCA-74249"
date = "2015-08-05"
album = "混ぜるな危険 / 筋肉少女帯"
tracks = [
    [1, "混ぜるな危険", "筋肉少女帯", 0],
    [2, "イワンのばか ('14 Live Version)", "筋肉少女帯", 0],
    [3, "ムツオさん ('14 Live Version)", "筋肉少女帯", 0],
    [4, "釈迦 ('14 Live Version)", "筋肉少女帯", 0],
    [5, "混ぜるな危険 ～TV Mix Version～", "筋肉少女帯", 0],
    [6, "混ぜるな危険 (Instrumental)", "筋肉少女帯", 0],
]
links = ["https://beta.musicbrainz.org/release/efae53ef-544d-4d9e-a4de-a67f7f5c8764", "https://vgmdb.net/album/53081"]

[cd339b2bad256f4cf7f82adb650cf58c]
catalognumber = "TKCA-74245"
date = "2015-08-05"
album = "混ぜるな危険 / 筋肉少女帯 Disc 1 (CD)"
tracks = [
    [1, "混ぜるな危険", "筋肉少女帯", 0],
    [2, "イワンのばか ('14 Live Version)", "筋肉少女帯", 0],
    [3, "ムツオさん ('14 Live Version)", "筋肉少女帯", 0],
    [4, "釈迦 ('14 Live Version)", "筋肉少女帯", 0],
    [5, "混ぜるな危険 ～TV Mix Version～", "筋肉少女帯", 0],
    [6, "混ぜるな危険 (Instrumental)", "筋肉少女帯", 0],
]
links = ["https://beta.musicbrainz.org/release/efae53ef-544d-4d9e-a4de-a67f7f5c8764", "https://vgmdb.net/album/53082"]

[fcda9bb1220ddae7d18760110bafdcb7]
catalognumber = "TKCA-74245"
date = "2015-08-05"
album = "混ぜるな危険 / 筋肉少女帯 Disc 2 (DVD)"
tracks = [
    [1, "心の折れたエンジェル", "", 0],
    [2, "ニルヴァナ", "", 0],
    [3, "ゾロ目", "", 0],
    [4, "ロシアンルーレット・マイライフ", "", 0],
    [5, "愛のリビドー（性的衝動）", "", 0],
    [6, "北極星の二人 ～内田のラブソング～", "", 0],
    [7, "ワインライダー・フォーエバー（筋少 Ver.）", "", 0],
    [8, "労働讃歌", "", 0],
    [9, "戦え!何を!?人生を!", "", 0],
    [10, "トゥルー・ロマンス", "", 0],
    [11, "デコイとクレーター", "", 0],
    [12, "恋の蜜蜂飛行", "", 0],
]
links = ["https://vgmdb.net/album/53082"]

[ed3c8945202b74c64d0dc5c86131e7ee]
catalognumber = "TKCA-74275"
date = "2015-08-19"
album = "HERO/Good bye 大切な人。 / ソナーポケット [通常盤A]"
tracks = [
    [1, "HERO", "ソナーポケット", 0],
    [2, "Good bye 大切な人。", "ソナーポケット", 0],
    [3, "tomorrow", "ソナーポケット", 0],
    [4, "HERO (TV size)", "ソナーポケット", 0],
    [5, "HERO (instrumental)", "ソナーポケット", 0],
    [6, "Good bye 大切な人。 (instrumental)", "ソナーポケット", 0],
]
links = ["https://beta.musicbrainz.org/release/3942cbca-16b8-4d63-b4c0-675e6ae1f5d4", "https://vgmdb.net/album/53936"]

[ea6b9f156b0bbbac9aeee27bfc3c7a9e]
catalognumber = "TKCA-74276"
date = "2015-08-19"
album = "Good bye 大切な人。/HERO / ソナーポケット [通常盤B]"
tracks = [
    [1, "Good bye 大切な人。", "", 0],
    [2, "HERO", "", 0],
    [3, "tomorrow", "", 0],
    [4, "Good bye 大切な人。 (instrumental)", "", 0],
    [5, "HERO (instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/53937"]

[7ae0c77dd2c6d8c0e3c63e33a142104d]
catalognumber = "TKCA-74271"
date = "2015-08-19"
album = "HERO/Good bye 大切な人。 / ソナーポケット [初回生産限定盤A] Disc 1 (CD)"
tracks = [
    [1, "HERO", "", 0],
    [2, "Good bye 大切な人。", "", 0],
    [3, "HERO (instrumental)", "", 0],
    [4, "Good bye 大切な人。 (instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/53938"]

[8afde6f4ded4410f70e422f56e6d319c]
catalognumber = "TKCA-74271"
date = "2015-08-19"
album = "HERO/Good bye 大切な人。 / ソナーポケット [初回生産限定盤A] Disc 2 (DVD)"
tracks = [
    [1, "『HERO』MV", "", 0],
    [2, "『HERO』MVメイキング&オフショット", "", 0],
]
links = ["https://vgmdb.net/album/53938"]

[c39228a0f55ad787be7ef22051f4f4ee]
catalognumber = "TKCA-74272"
date = "2015-08-19"
album = "Good bye 大切な人。/HERO / ソナーポケット [初回生産限定盤B] Disc 2 (DVD)"
tracks = [
    [1, "『Good bye 大切な人。』MV", "", 0],
    [2, "『Good bye 大切な人。』MVメイキング&オフショット", "", 0],
]
links = ["https://vgmdb.net/album/53939"]

[ee67743a529838d5415d7252b56a3004]
catalognumber = "TKCA-74272"
date = "2015-08-19"
album = "Good bye 大切な人。/HERO / ソナーポケット [初回生産限定盤B] Disc 1 (CD)"
tracks = [
    [1, "Good bye 大切な人。", "", 0],
    [2, "HERO", "", 0],
    [3, "Good bye 大切な人。 (instrumental)", "", 0],
    [4, "HERO (instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/53939"]

[54e9e57192656e390985f27ca524d68c]
catalognumber = "TKCA-74278"
date = "2015-10-14"
album = "TVアニメ うしおととら オリジナルサウンドトラック I"
tracks = [
    [1, "オープニングテーマ 混ぜるな危険 〜TV Mix Version〜", "筋肉少女帯", 0],
    [2, "槍の男1", "瀬川英史", 0],
    [3, "妖気", "瀬川英史", 0],
    [4, "うしおのテーマ1", "瀬川英史", 0],
    [5, "うしおのテーマ5", "瀬川英史", 0],
    [6, "浮遊", "瀬川英史", 0],
    [7, "妖艶", "瀬川英史", 0],
    [8, "うしおのテーマ7", "瀬川英史", 0],
    [9, "とらのテーマ", "瀬川英史", 0],
    [10, "うしおのテーマ2", "瀬川英史", 0],
    [11, "敵2", "瀬川英史", 0],
    [12, "恐怖", "瀬川英史", 0],
    [13, "槍の男3", "瀬川英史", 0],
    [14, "うしおのテーマ6", "瀬川英史", 0],
    [15, "不安", "瀬川英史", 0],
    [16, "事件発生", "瀬川英史", 0],
    [17, "とらのテーマ2", "瀬川英史", 0],
    [18, "敵3", "瀬川英史", 0],
    [19, "怨み", "瀬川英史", 0],
    [20, "敵7", "瀬川英史", 0],
    [21, "槍の男5", "瀬川英史", 0],
    [22, "不穏", "瀬川英史", 0],
    [23, "心配", "瀬川英史", 0],
    [24, "希望", "瀬川英史", 0],
    [25, "うしおのテーマ4", "瀬川英史", 0],
    [26, "邪教", "瀬川英史", 0],
    [27, "敵8", "瀬川英史", 0],
    [28, "槍の男4", "瀬川英史", 0],
    [29, "対峙", "瀬川英史", 0],
    [30, "精査分析", "瀬川英史", 0],
    [31, "うしおのテーマ3", "瀬川英史", 0],
    [32, "敵4", "瀬川英史", 0],
    [33, "うしおのテーマ9", "瀬川英史", 0],
    [34, "敵1", "瀬川英史", 0],
    [35, "槍の男2", "瀬川英史", 0],
    [36, "エンディングテーマ HERO (TV size)", "KINNIKUSHOJOTAI & SONAR POCKET", 0],
]
links = ["https://beta.musicbrainz.org/release/1db12edc-4194-467b-8677-df17615b5954", "https://vgmdb.net/album/54056"]

[7d772e4835d53b8133e66ac878ce5b88]
catalognumber = "TKCA-74301"
date = "2015-11-04"
album = "負けるな小さきものよ / 若旦那"
tracks = [
    [1, "負けるな小さきものよ", "若旦那", 0],
    [2, "ブランニューデイズ (Hi-Fi City Mix)", "若旦那", 0],
    [3, "サンタクロース", "若旦那", 0],
    [4, "負けるな小さきものよ (TV ver.)", "若旦那", 0],
    [5, "ブランニューデイズ (Neo 80's Mix)", "若旦那", 0],
    [6, "負けるな小さきものよ (Instrumental)", "若旦那", 0],
]
links = ["https://beta.musicbrainz.org/release/e8d38535-2d0a-4b57-b854-4a6deb04994d", "https://vgmdb.net/album/55658"]

[3389b2d8b7f729c87dbd035d72908c8a]
catalognumber = "TKCA-74353"
date = "2016-04-20"
album = "週替わりの奇跡の神話"
tracks = [
    [1, "週替わりの奇跡の神話", "筋肉少女帯", 0],
    [2, "混ぜるな危険 ('15 Live Version)", "筋肉少女帯", 0],
    [3, "日本印度化計画 ('15 Live Version)", "筋肉少女帯", 0],
    [4, "週替わりの奇跡の神話 ～TV Mix Version～", "筋肉少女帯", 0],
    [5, "週替わりの奇跡の神話 ～TV Mix Version～ (Original Karaoke)", "筋肉少女帯", 0],
    [6, "週替わりの奇跡の神話 (Instrumental)", "筋肉少女帯", 0],
]
links = ["https://beta.musicbrainz.org/release/e1fa9900-73c9-4b01-a9a6-a6bf50c1b169"]

[657daee45e825255854088169c0515e8]
catalognumber = "TKCA-74356"
date = "2016-05-11"
album = "決戦前夜"
tracks = [
    [1, "決戦前夜", "LUNKHEAD", 0],
    [2, "ユキシズク", "LUNKHEAD", 0],
    [3, "決戦前夜 [TV OA ver.]", "LUNKHEAD", 0],
    [4, "決戦前夜 [Instrumental]", "LUNKHEAD", 0],
    [5, "ユキシズク [Instrumental]", "LUNKHEAD", 0],
]
links = ["https://beta.musicbrainz.org/release/08ff71e6-9a35-49c3-8bec-d0d0b766184f"]

[b4e22911cda76e07794e6fe8b63582d3]
catalognumber = ""
date = "2016-05-18"
album = "うしおととらうしおととらキャラクターソングス"
tracks = [
    [1, "いつの日か旅の終わりに", "畠中祐", 0],
    [2, "渇いた魂", "浪川大輔/細谷佳正", 0],
    [3, "おかえり", "小松未可子", 0],
    [4, "私のナイト", "安野希世乃/小山力也", 0],
    [5, "終わりない道", "清水理沙", 0],
    [6, "生きる証", "潘めぐみ", 0],
]
links = ["https://music.163.com/#/album?id=34700515"]

[245f360ee09f3a75a7b6e5a0576717fc]
catalognumber = "TKXA-1070"
date = "2017-12-20"
album = "うしおととら オリジナルサウンドトラック & キャラクターソング集 Original Soundtrack"
tracks = [
    [1, "槍の男1", "", 0],
    [2, "妖気", "", 0],
    [3, "うしおのテーマ1", "", 0],
    [4, "うしおのテーマ5", "", 0],
    [5, "浮遊", "", 0],
    [6, "妖艶", "", 0],
    [7, "うしおのテーマ7", "", 0],
    [8, "とらのテーマ", "", 0],
    [9, "うしおのテーマ2", "", 0],
    [10, "敵2", "", 0],
    [11, "恐怖", "", 0],
    [12, "槍の男3", "", 0],
    [13, "うしおのテーマ6", "", 0],
    [14, "不安", "", 0],
    [15, "事件発生", "", 0],
    [16, "とらのテーマ2", "", 0],
    [17, "敵3", "", 0],
    [18, "怨み", "", 0],
    [19, "敵7", "", 0],
    [20, "槍の男5", "", 0],
    [21, "不穏", "", 0],
    [22, "心配", "", 0],
    [23, "希望", "", 0],
    [24, "うしおのテーマ4", "", 0],
    [25, "邪教", "", 0],
    [26, "敵8", "", 0],
    [27, "槍の男4", "", 0],
    [28, "対峙", "", 0],
    [29, "精査分析", "", 0],
    [30, "うしおのテーマ3", "", 0],
    [31, "敵4", "", 0],
    [32, "うしおのテーマ9", "", 0],
    [33, "敵1", "", 0],
    [34, "槍の男2", "", 0],
]
links = ["https://vgmdb.net/album/71837"]

[d1482df9fff312bba338b5a0384a7ac2]
catalognumber = "TKXA-1070"
date = "2017-12-20"
album = "うしおととら オリジナルサウンドトラック & キャラクターソング集 Original Soundtrack, Vocal"
tracks = [
    [1, "うしおのテーマ8", "", 0],
    [2, "敵5", "", 0],
    [3, "秋葉", "", 0],
    [4, "兄妹愛", "", 0],
    [5, "日輪のテーマ", "", 0],
    [6, "白面のテーマ1", "", 0],
    [7, "ハマー機関1", "", 0],
    [8, "白面のテーマ2", "", 0],
    [9, "エルザールの鎌", "", 0],
    [10, "暴走", "", 0],
    [11, "斗和子の葬送曲", "", 0],
    [12, "獣の槍の誕生", "", 0],
    [13, "白面のテーマ3", "", 0],
    [14, "鎧のうしお", "", 0],
    [15, "鎧のとら", "", 0],
    [16, "死闘", "", 0],
    [17, "集結", "", 0],
    [18, "いつの日か旅の終わりに", "", 0],
    [19, "渇いた魂", "", 0],
    [20, "おかえり", "", 0],
    [21, "私のナイト", "", 0],
    [22, "終わりない道", "", 0],
    [23, "生きる証", "", 0],
]
links = ["https://vgmdb.net/album/71837"]
