[c9252e4692c807f40ba27d082bfcd985]
catalognumber = "KICM-3354"
date = "2019-01-23"
album = "えんどろ～る! / 勇者パーティー"
tracks = [
    [1, "えんどろ～る!", "勇者パーティー<ユーシャ(CV：赤尾ひかる)、セイラ(CV：夏川椎菜)、ファイ(CV：小澤亜李)、メイ(CV：水瀬いのり)>", 2],
    [2, "はっぴぃとぅご～!", "勇者パーティー<ユーシャ(CV：赤尾ひかる)、セイラ(CV：夏川椎菜)、ファイ(CV：小澤亜李)、メイ(CV：水瀬いのり)>", 2],
    [3, "えんどろ～る! (off vocal)", "勇者パーティー<ユーシャ(CV：赤尾ひかる)、セイラ(CV：夏川椎菜)、ファイ(CV：小澤亜李)、メイ(CV：水瀬いのり)>", 1],
    [4, "はっぴぃとぅご～! (off vocal)", "勇者パーティー<ユーシャ(CV：赤尾ひかる)、セイラ(CV：夏川椎菜)、ファイ(CV：小澤亜李)、メイ(CV：水瀬いのり)>", 1],
]
links = ["https://beta.musicbrainz.org/release/64cabe94-dffe-45d5-98f3-69cf66a6a1cb", "https://vgmdb.net/album/82240"]

[a3df8b2ccaaf7dd9c8ba2307b9d4f392]
catalognumber = "KICM-1914"
date = "2019-01-23"
album = "Wonder Caravan! / 水瀬いのり"
tracks = [
    [1, "Wonder Caravan!", "水瀬いのり", 2],
    [2, "君色プロローグ", "水瀬いのり", 1],
    [3, "Snow White", "水瀬いのり", 1],
]
links = ["https://beta.musicbrainz.org/release/d86168f3-f9e1-4441-b801-010964f4b366", "https://vgmdb.net/album/82239"]

[83362c5a4016f60fcd8665b098bc472e]
catalognumber = "KIZX-378"
date = "2019-03-27"
album = "えんどろ～! ドラマCD「最初の最初の物語～!」"
tracks = [
    [1, "最初の最初の物語～！", "Various Artists", 0],
]
links = ["https://beta.musicbrainz.org/release/c3f2ec1d-39dd-4b1f-ae57-7be04e5bc6fc", "https://vgmdb.net/album/83378"]

[a4b9530d2ba6c46f456f38a751fdef20]
catalognumber = "KICS-3785"
date = "2019-04-10"
album = "Catch the Rainbow! / 水瀬いのり"
tracks = [
    [1, "Step Up!", "水瀬いのり", 0],
    [2, "ココロはMerry-Go-Round", "水瀬いのり", 0],
    [3, "Kitty Cat Adventure", "水瀬いのり", 0],
    [4, "Wonder Caravan!", "水瀬いのり", 1],
    [5, "今を僕らしく生きてくために", "水瀬いのり", 0],
    [6, "約束のアステリズム", "水瀬いのり", 0],
    [7, "Future Seeker", "水瀬いのり", 0],
    [8, "brave climber", "水瀬いのり", 0],
    [9, "TRUST IN ETERNITY", "水瀬いのり", 0],
    [10, "水彩メモリー", "水瀬いのり", 0],
    [11, "My Graffiti", "水瀬いのり", 0],
    [12, "Catch the Rainbow!", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/a1bc3f29-e4fc-4429-9912-1fc1cf0f1ca3", "https://vgmdb.net/album/83835"]

[f4f9160041cf31130e5e4d4fa7cb483e]
catalognumber = "KICS-93785"
date = "2019-04-10"
album = "Catch the Rainbow! / 水瀬いのり [初回限定盤] Disc 1 (CD)"
tracks = [
    [1, "Step Up!", "水瀬いのり", 0],
    [2, "ココロはMerry-Go-Round", "水瀬いのり", 0],
    [3, "Kitty Cat Adventure", "水瀬いのり", 0],
    [4, "Wonder Caravan!", "水瀬いのり", 1],
    [5, "今を僕らしく生きてくために", "水瀬いのり", 0],
    [6, "約束のアステリズム", "水瀬いのり", 0],
    [7, "Future Seeker", "水瀬いのり", 0],
    [8, "brave climber", "水瀬いのり", 0],
    [9, "TRUST IN ETERNITY", "水瀬いのり", 0],
    [10, "水彩メモリー", "水瀬いのり", 0],
    [11, "My Graffiti", "水瀬いのり", 0],
    [12, "Catch the Rainbow!", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/6fa565ca-a814-4545-9bd9-5908c3f2c14b", "https://vgmdb.net/album/83836"]

[53e83bc210f1684330aca546d6939401]
catalognumber = "KICS-93785"
date = "2019-04-10"
album = "Catch the Rainbow! / 水瀬いのり [初回限定盤] Disc 2 (Blu-ray)"
tracks = [
    [1, "TRUST IN ETERNITY", "水瀬いのり", 0],
    [2, "Wonder Caravan!", "水瀬いのり", 1],
    [3, "Catch the Rainbow!", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/6fa565ca-a814-4545-9bd9-5908c3f2c14b", "https://vgmdb.net/album/83836"]

[2656d30c3d025d0bf637259abc71ab13]
catalognumber = "KIZX-380"
date = "2019-04-24"
album = "えんどろ～! オリジナルサウンドトラック①"
tracks = [
    [1, "魔王城の死闘", "藤澤慶昌", 1],
    [2, "エンドロールじゃあ終わらないんだよ", "藤澤慶昌", 1],
    [3, "ある日、ある朝", "藤澤慶昌", 1],
    [4, "冒険者学校", "藤澤慶昌", 1],
    [5, "マオちゃん先生の授業(1時間目)", "藤澤慶昌", 1],
    [6, "冒険実習", "藤澤慶昌", 1],
    [7, "マオのたくらみ", "藤澤慶昌", 1],
    [8, "古代の遺跡は奥が深い", "藤澤慶昌", 1],
    [9, "試練さんエントリーっす", "藤澤慶昌", 1],
    [10, "勇者パーティーの帰還", "藤澤慶昌", 1],
    [11, "パジャマパーティー", "藤澤慶昌", 1],
    [12, "ワケワカメ", "藤澤慶昌", 1],
    [13, "ええからはよ起きんかい", "藤澤慶昌", 1],
    [14, "セイラのなげき", "藤澤慶昌", 1],
    [15, "猫探しを終えて", "藤澤慶昌", 1],
    [16, "鯖魚人との別れ", "藤澤慶昌", 1],
    [17, "自主制作絵本", "藤澤慶昌", 1],
    [18, "ローナ・プリシパ・オ・ラパネスタ", "藤澤慶昌", 1],
    [19, "紫黒のフェイトゥルース", "藤澤慶昌", 1],
    [20, "勇者祭", "藤澤慶昌", 1],
    [21, "勇者様への憧れ", "藤澤慶昌", 1],
    [22, "転校生はお姫様", "藤澤慶昌", 1],
    [23, "魔王熱の脅威", "藤澤慶昌", 1],
    [24, "マオちゃん先生もちゅぱってする?", "藤澤慶昌", 1],
    [25, "おかあさんの優しさ", "藤澤慶昌", 1],
    [26, "ポカポカじゃ", "藤澤慶昌", 1],
]
links = ["https://beta.musicbrainz.org/release/fc469847-c513-4906-87e0-5c14a2c97d21", "https://vgmdb.net/album/83379"]

[8d809c26c2d3f0a4a0433339a50152d9]
catalognumber = "KIZX-382"
date = "2019-05-29"
album = "えんどろ～! ドラマCD「温泉湯煙ぶらり旅～!」"
tracks = [
    [1, "温泉湯煙ぶらり旅～！", "Various Artists", 1],
]
links = ["https://beta.musicbrainz.org/release/8fc42a41-3b73-448d-bf0e-703e57379fe4", "https://vgmdb.net/album/83380"]

[a888d6cef35eeeeeaad638e6dc4a8a2c]
catalognumber = "KIXM-379"
date = "2019-06-26"
album = "水瀬いのり MUSIC CLIP BOX"
tracks = [
    [1, "夢のつぼみ", "", 0],
    [2, "harmony ribbon", "", 0],
    [3, "Starry Wish", "", 0],
    [4, "春空", "", 0],
    [5, "アイマイモコ", "", 0],
    [6, "Ready Steady Go!", "", 0],
    [7, "Million Futures", "", 0],
    [8, "TRUST IN ETERNITY", "", 0],
    [9, "Wonder Caravan!", "", 1],
    [10, "Catch the Rainbow!", "", 0],
    [11, "まっすぐに、トウメイに。(original ver)", "", 0],
    [12, "まっすぐに、トウメイに。(anime ver)", "", 0],
    [13, "夢のつぼみ (Making Movie)", "", 0],
    [14, "harmony ribbon (Making Movie)", "", 0],
    [15, "Starry Wish (Making Movie)", "", 0],
    [16, "春空 (Making Movie)", "", 0],
    [17, "アイマイモコ (Making Movie)", "", 0],
    [18, "Ready Steady Go! (Making Movie)", "", 0],
    [19, "Million Futures (Making Movie)", "", 0],
    [20, "TRUST IN ETERNITY (Making Movie)", "", 0],
    [21, "Wonder Caravan! (Making Movie)", "", 1],
    [22, "Catch the Rainbow! (Making Movie)", "", 0],
    [23, "夢のつぼみ typeA (CM)", "", 0],
    [24, "夢のつぼみ typeB (CM)", "", 0],
    [25, "harmony ribbon (CM)", "", 0],
    [26, "Starry Wish typeA (CM)", "", 0],
    [27, "Starry Wish typeB (CM)", "", 0],
    [28, "Innocent flower (CM)", "", 0],
    [29, "アイマイモコ typeA (CM)", "", 0],
    [30, "アイマイモコ typeB (CM)", "", 0],
    [31, "Ready Steady Go (CM)", "", 0],
    [32, "Inori Minase 1st LIVE Ready Steady Go! typeA (CM)", "", 0],
    [33, "Inori Minase 1st LIVE Ready Steady Go! typeB (CM)", "", 0],
    [34, "BLUE COMPASS typeA (CM)", "", 0],
    [35, "BLUE COMPASS typeB (CM)", "", 0],
    [36, "BLUE COMPASS typeC (CM)", "", 0],
    [37, "TRUST IN ETERNITY (CM)", "", 0],
    [38, "Inori Minase LIVE TOUR BLUE COMPASS typeA (CM)", "", 0],
    [39, "Inori Minase LIVE TOUR BLUE COMPASS typeB (CM)", "", 0],
    [40, "Wonder Caravan! typeA (CM)", "", 1],
    [41, "Wonder Caravan! typeB (CM)", "", 1],
    [42, "Catch the Rainbow! typeA (CM)", "", 0],
    [43, "Catch the Rainbow! typeB (CM)", "", 0],
    [44, "Inori Minase MUSIC CLIP BOX (CM)", "", 0],
]
links = ["https://vgmdb.net/album/88664"]

[d6f5acf8aff9eb76dad3bd32c84d193e]
catalognumber = "KIZX-384"
date = "2019-06-26"
album = "えんどろ～! オリジナルサウンドトラック②"
tracks = [
    [1, "えんどろ～る! (TV size)", "齋藤真也", 1],
    [2, "サブタイトル1", "藤澤慶昌", 1],
    [3, "ローナ姫の学校生活", "藤澤慶昌", 1],
    [4, "ローナ姫ファイと～!", "藤澤慶昌", 1],
    [5, "寝袋草", "藤澤慶昌", 1],
    [6, "アンダス・メロン大食い大会", "藤澤慶昌", 1],
    [7, "クエスト実習", "藤澤慶昌", 1],
    [8, "マオちゃん先生の授業(2時間目)", "藤澤慶昌", 1],
    [9, "酒と泪と魔王と女戦士", "藤澤慶昌", 1],
    [10, "アイキャッチ1", "藤澤慶昌", 1],
    [11, "アイキャッチ2", "藤澤慶昌", 1],
    [12, "アイキャッチ3", "藤澤慶昌", 1],
    [13, "カルタードの木", "藤澤慶昌", 1],
    [14, "秘境!タルカ村", "藤澤慶昌", 1],
    [15, "カルタード・アンセム", "藤澤慶昌", 1],
    [16, "セイラの妄想", "藤澤慶昌", 1],
    [17, "カルタイーターが見せる夢", "藤澤慶昌", 1],
    [18, "サブタイトル2", "藤澤慶昌", 1],
    [19, "メイゴ登場", "藤澤慶昌", 1],
    [20, "なぜこやつがここに...!?", "藤澤慶昌", 1],
    [21, "エルフ怖い...", "藤澤慶昌", 1],
    [22, "メイゴの決意と魔王の矜持", "藤澤慶昌", 1],
    [23, "勇者と魔王の運命", "藤澤慶昌", 1],
    [24, "えんどろ～る! (Piano arrangement)", "齋藤真也", 1],
    [25, "Wonder Caravan! (Piano arrangement)", "新田目翔", 1],
    [26, "すべての終わりで、そして始まり", "藤澤慶昌", 1],
    [27, "武器のカルタード", "藤澤慶昌", 1],
    [28, "Wonder Caravan! (TV size)", "新田目翔", 1],
    [29, "ありそでなかったその向こう", "藤澤慶昌", 1],
]
links = ["https://beta.musicbrainz.org/release/7e88c63a-a69c-47e8-87a4-e2f4dca380d5", "https://vgmdb.net/album/83381"]

[5e736f4cc4aa72ab6c9c2050ae15510f]
catalognumber = "KICS-94217~8"
date = "2025-09-03"
album = "Travel Record [初回限定盤] / 水瀬いのり Vocal Disc 1"
tracks = [
    [1, "夢のつぼみ", "水瀬いのり", 0],
    [2, "harmony ribbon", "水瀬いのり", 0],
    [3, "Starry Wish", "水瀬いのり", 0],
    [4, "春空", "水瀬いのり", 0],
    [5, "Innocent flower", "水瀬いのり", 0],
    [6, "アイマイモコ", "水瀬いのり", 0],
    [7, "Ready Steady Go!", "水瀬いのり", 0],
    [8, "Million Futures", "水瀬いのり", 0],
    [9, "BLUE COMPASS", "水瀬いのり", 0],
    [10, "TRUST IN ETERNITY", "水瀬いのり", 0],
    [11, "Wonder Caravan!", "水瀬いのり", 1],
    [12, "Catch the Rainbow!", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/d2beb59c-8710-42ef-92bb-1f69e3cd3cc9", "https://vgmdb.net/album/159853"]

[258133ef8a705e85aa476acf70d2e8fc]
catalognumber = "KICS-94217~8"
date = "2025-09-03"
album = "Travel Record [初回限定盤] / 水瀬いのり Vocal Disc 2"
tracks = [
    [1, "まっすぐに、トウメイに。", "水瀬いのり", 0],
    [2, "ココロソマリ", "水瀬いのり", 0],
    [3, "僕らは今", "水瀬いのり", 0],
    [4, "Starlight Museum", "水瀬いのり", 0],
    [5, "HELLO HORIZON", "水瀬いのり", 0],
    [6, "REAL-EYES", "水瀬いのり", 0],
    [7, "glow", "水瀬いのり", 0],
    [8, "アイオライト", "水瀬いのり", 0],
    [9, "スクラップアート", "水瀬いのり", 0],
    [10, "フラーグム", "水瀬いのり", 0],
    [11, "heart bookmark", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/d2beb59c-8710-42ef-92bb-1f69e3cd3cc9", "https://vgmdb.net/album/159853"]

[d643de7925134d79678279890873719e]
catalognumber = "KICS-94217~8"
date = "2025-09-03"
album = "Travel Record [初回限定盤] / 水瀬いのり Video"
tracks = [
    [1, "10周年記念ドキュメントムービー", "水瀬いのり", 0],
    [2, "ビジュアル撮影メイキングムービー", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/d2beb59c-8710-42ef-92bb-1f69e3cd3cc9", "https://vgmdb.net/album/159853"]

[73628931d002986e7a4d29442c5c3f05]
catalognumber = "KICS-4217~8"
date = "2025-09-03"
album = "Travel Record / 水瀬いのり Disc 1 [KICS-4217]"
tracks = [
    [1, "夢のつぼみ", "水瀬いのり", 0],
    [2, "harmony ribbon", "水瀬いのり", 0],
    [3, "Starry Wish", "水瀬いのり", 0],
    [4, "春空", "水瀬いのり", 0],
    [5, "Innocent flower", "水瀬いのり", 0],
    [6, "アイマイモコ", "水瀬いのり", 0],
    [7, "Ready Steady Go!", "水瀬いのり", 0],
    [8, "Million Futures", "水瀬いのり", 0],
    [9, "BLUE COMPASS", "水瀬いのり", 0],
    [10, "TRUST IN ETERNITY", "水瀬いのり", 0],
    [11, "Wonder Caravan!", "水瀬いのり", 1],
    [12, "Catch the Rainbow!", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/d2beb59c-8710-42ef-92bb-1f69e3cd3cc9", "https://vgmdb.net/album/155112"]

[b464253b8a646c8c62f200e6cc180df3]
catalognumber = "KICS-4217~8"
date = "2025-09-03"
album = "Travel Record / 水瀬いのり Disc 2 [KICS-4218]"
tracks = [
    [1, "まっすぐに、トウメイに。", "水瀬いのり", 0],
    [2, "ココロソマリ", "水瀬いのり", 0],
    [3, "僕らは今", "水瀬いのり", 0],
    [4, "Starlight Museum", "水瀬いのり", 0],
    [5, "HELLO HORIZON", "水瀬いのり", 0],
    [6, "REAL-EYES", "水瀬いのり", 0],
    [7, "glow", "水瀬いのり", 0],
    [8, "アイオライト", "水瀬いのり", 0],
    [9, "スクラップアート", "水瀬いのり", 0],
    [10, "フラーグム", "水瀬いのり", 0],
    [11, "heart bookmark", "水瀬いのり", 0],
]
links = ["https://beta.musicbrainz.org/release/d2beb59c-8710-42ef-92bb-1f69e3cd3cc9", "https://vgmdb.net/album/155112"]
