[e0246d319e475a22b1d281952a00f734]
catalognumber = "ZMCZ-14191"
date = "2020-10-28"
album = "TVアニメ「おちこぼれフルーツタルト」テーマソングCD"
tracks = [
    [1, "キボウだらけのEVERYDAY", "フルーツタルト", 2],
    [2, "ワンダー!", "フルーツタルト", 2],
    [3, "タルトなキモチ", "フルーツタルト", 2],
    [4, "キボウだらけのEVERYDAY (instrumental)", "フルーツタルト", 1],
    [5, "ワンダー! (instrumental)", "フルーツタルト", 1],
    [6, "タルトなキモチ (instrumental)", "フルーツタルト", 1],
]
links = ["https://beta.musicbrainz.org/release/dfb2f18d-0fbf-4305-9fed-1d6317c38639", "https://vgmdb.net/album/102566"]

[9d4a3ba7baa2ad6719471b4123650ac3]
catalognumber = "ZMCZ-14552"
date = "2020-12-23"
album = "TVアニメ「おちこぼれフルーツタルト」オリジナルサウンドトラックCD"
tracks = [
    [1, "おおきく息を吸い込んで", "高田龍一", 1],
    [2, "ちょうしょくはカレーです", "Oliver Good", 1],
    [3, "これは……!", "高田龍一", 1],
    [4, "ぼんっ!", "高田龍一", 1],
    [5, "れっつごー!フルーツタルト!", "高田龍一", 1],
    [6, "フイウチ", "Oliver Good", 1],
    [7, "ルーツとする感情", "Oliver Good", 1],
    [8, "It's wonderful", "高田龍一", 1],
    [9, "ツイニヤリマス!", "高田龍一", 1],
    [10, "夕日に向かってマリンバ", "高田龍一", 1],
    [11, "ループする焦り", "高田龍一", 1],
    [12, "トキドキドギマキ", "井上馨太", 1],
    [13, "聴き耳立てて", "井上馨太", 1],
    [14, "いっしょに考えよう", "Oliver Good", 1],
    [15, "てくてくおちフル!", "Oliver Good", 1],
    [16, "くりかえすおちフル!", "井上馨太", 1],
    [17, "れきだい最強!", "井上馨太", 1],
    [18, "てんさいの感覚", "井上馨太", 1],
    [19, "あー……", "Oliver Good", 1],
    [20, "りくつじゃない", "井上馨太", 1],
    [21, "がやがやの時間", "Oliver Good", 1],
    [22, "とくべつな夜", "井上馨太", 1],
    [23, "うれしさ爆発", "高田龍一", 1],
    [24, "!", "Oliver Good", 1],
    [25, "末のみえない恋", "Oliver Good", 1],
    [26, "永遠にだらだら", "井上馨太", 1],
    [27, "くりーむあんみつ!", "Oliver Good", 1],
    [28, "よくできました", "井上馨太", 1],
    [29, "ろーどおぶあいどる", "Oliver Good", 1],
    [30, "しずかなるワルツ", "高田龍一", 1],
    [31, "くるくる回るよ", "高田龍一", 1],
    [32, "おちこぼれる", "井上馨太", 1],
    [33, "願ってもドタバタ", "井上馨太", 1],
    [34, "いつもより背伸び", "井上馨太", 1],
    [35, "しつこいぞ", "Oliver Good", 1],
    [36, "まきこんであんみつ", "井上馨太", 1],
    [37, "すごくこわい", "井上馨太", 1],
    [38, "!イマジネーション!", "Oliver Good", 1],
    [39, "たのしき学び舎", "高田龍一", 1],
    [40, "かっこいい寝起き", "Oliver Good", 1],
    [41, "だまってられない", "高田龍一", 1],
    [42, "いちだいじ", "井上馨太", 1],
    [43, "のーぷらん?", "Oliver Good", 1],
    [44, "うみだした絆", "Oliver Good", 1],
    [45, "えいこうへの道", "高田龍一", 1],
    [46, "おちこぼれだって", "井上馨太", 1],
    [47, "りそうに向かって", "高田龍一", 1],
    [48, "ばりばり頑張ります", "高田龍一", 1],
    [49, "Intro!", "Oliver Good", 1],
]
links = ["https://beta.musicbrainz.org/release/c206f524-1685-483c-a267-a27fdfe62d95", "https://vgmdb.net/album/104842"]

[500e905f505ad502de0fe98c480e2975]
catalognumber = "ZMXZ-14321CD"
date = "2021-01-27"
album = "おちこぼれフルーツタルト Bonus Disc 1"
tracks = [
    [1, "ネズミ戦隊ネズレンジャー", "関野ロコ(CV:久保田梨沙)、貫井はゆ(CV:白石晴香)、前原仁菜(CV:近藤玲奈)", 1],
    [2, "ネズミ戦隊ネズレンジャー", "フルーツタルト（4人ver.）", 1],
    [3, "ブロ子の歌", "関野ロコ(CV:久保田梨沙)", 1],
    [4, "ネズミ戦隊ネズレンジャー (instrumental)", "Various Artists", 1],
    [5, "ブロ子の歌 (instrumental)", "Various Artists", 1],
]
links = ["https://beta.musicbrainz.org/release/157fcfd5-3e78-4e08-9b1e-a174368baa6d", "https://vgmdb.net/album/104924"]

[974ad952b60de09d5fc44815d24dd4bf]
catalognumber = "ZMXZ-14322CD"
date = "2021-02-24"
album = "おちこぼれフルーツタルト Bonus Disc 2"
tracks = [
    [1, "タルトなキモチ", "フルーツタルト（4人ver.）", 1],
    [2, "タルトなキモチ", "フルーツタルト", 1],
    [3, "ブルーの爽快がめちゃShiny!", "クリームあんみつ", 1],
    [4, "タルトなキモチ（instrumental）", "Various Artists", 1],
    [5, "ブルーの爽快がめちゃShiny!（instrumental）", "Various Artists", 1],
]
links = ["https://beta.musicbrainz.org/release/a87f3f61-fbc2-4a33-be4a-c54922bdb97d", "https://vgmdb.net/album/104925"]

[8730fe5042862ecfd634a916e167eafb]
catalognumber = "ZMXZ-14323CD"
date = "2021-03-24"
album = "おちこぼれフルーツタルト Bonus Disc 3"
tracks = [
    [1, "目指せ！カレーNo.1！", "フルーツタルト", 1],
    [2, "青春の終焉と少女の翼", "クリームあんみつ", 1],
    [3, "青春の終焉と少女の翼", "タルト&あんみつ", 1],
    [4, "目指せ！カレーNo.1！(Instrumental)", "Various Artists", 1],
    [5, "青春の終焉と少女の翼(Instrumental)", "Various Artists", 1],
]
links = ["https://beta.musicbrainz.org/release/12d02147-c218-48f8-a188-553bfddf7b70", "https://vgmdb.net/album/104926"]
