[48a02f52dd53bfbf1524bba9fd354f1b]
catalognumber = "THCS-60205"
date = "2018-02-14"
album = "言わないけどね。 / 大原ゆい子 [アーティスト盤]"
tracks = [
    [1, "言わないけどね。", "大原ゆい子", 1],
    [2, "木星バット", "大原ゆい子", 1],
    [3, "言わないけどね。 (Instrumental)", "大原ゆい子", 1],
    [4, "木星バット (Instrumental)", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/fdfef2d8-4fcc-4fe3-bcbf-ed239f907966", "https://vgmdb.net/album/73548"]

[dafcd565e744c529e860bfdf3cfd8ce5]
catalognumber = "THCS-60204"
date = "2018-02-14"
album = "言わないけどね。 / 大原ゆい子 [アニメ盤]"
tracks = [
    [1, "言わないけどね。", "大原ゆい子", 1],
    [2, "旅立ちの風", "大原ゆい子", 1],
    [3, "言わないけどね。 (Instrumental)", "大原ゆい子", 1],
    [4, "旅立ちの風 (Instrumental)", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/76298364-7a7c-4a55-b63f-38c46bae4c23", "https://vgmdb.net/album/73549"]

[e640a2cc93b5d171945cd1d288d996b8]
catalognumber = "TBCR-0979"
date = "2018-02-28"
album = "DJCD「TVアニメ『からかい上手の高木さん』Presents からかい上手の高\"橋\"さんラジオ」"
tracks = []
links = ["https://vgmdb.net/album/93227"]

[b36be1df4fb3e7a34deff0c5dfbd096e]
catalognumber = "THCA-60210"
date = "2018-03-28"
album = "「からかい上手の高木さん」 Cover Song Collection"
tracks = [
    [1, "気まぐれロマンティック", "高木さん(CV:高橋李依)", 1],
    [2, "AM11:00", "高木さん(CV:高橋李依)", 2],
    [3, "自転車", "高木さん(CV:高橋李依)", 1],
    [4, "風吹けば恋", "高木さん(CV:高橋李依)", 1],
    [5, "小さな恋のうた", "高木さん(CV:高橋李依)", 1],
    [6, "愛唄", "高木さん(CV:高橋李依)", 1],
    [7, "出逢った頃のように", "高木さん(CV:高橋李依)", 1],
]
links = ["https://beta.musicbrainz.org/release/66c8dbed-774d-4f7e-9c7c-71278c0aae8d", "https://vgmdb.net/album/74458"]

[2a7d42778ac80aa6230ec6ec3da48141]
catalognumber = "TBR28092D-2"
date = "2018-04-18"
album = "からかい上手の高木さん ドラマCD1"
tracks = [
    [1, "花の名前", "", 1],
    [2, "卵焼き", "", 1],
]
links = ["https://vgmdb.net/album/74066"]

[3bf6c8de18549048ec4c921fb97ddf2d]
catalognumber = "THCA-60211"
date = "2018-04-18"
album = "「からかい上手の高木さん」Music Collection"
tracks = [
    [1, "高木さんと西片", "堤博明", 1],
    [2, "「言わないけどね。」 (リコーダーバージョン)", "堤博明", 1],
    [3, "消しゴム", "堤博明", 1],
    [4, "変顔", "堤博明", 1],
    [5, "やっとこっち向いた", "堤博明", 1],
    [6, "見てろよ高木さん! その1", "堤博明", 1],
    [7, "見てろよ高木さん! その2", "堤博明", 1],
    [8, "チャンス!", "堤博明", 1],
    [9, "ダンディさん", "堤博明", 1],
    [10, "西部のダンディ", "堤博明", 1],
    [11, "思春期の妄想", "堤博明", 1],
    [12, "よく見ると高木さんって、、、", "堤博明", 1],
    [13, "赤くなる一言", "堤博明", 1],
    [14, "西片の葛藤", "堤博明", 1],
    [15, "からかわれた回数の3倍の腕立て", "堤博明", 1],
    [16, "作戦考え中", "堤博明", 1],
    [17, "よくあるオチ その1", "堤博明", 1],
    [18, "よくあるオチ その2", "堤博明", 1],
    [19, "ボンボンボン", "堤博明", 1],
    [20, "中学生の毎日", "堤博明", 1],
    [21, "青春したい", "堤博明", 1],
    [22, "相合い傘", "堤博明", 1],
    [23, "雨宿り", "堤博明", 1],
    [24, "晴れた帰り道", "堤博明", 1],
    [25, "どや顔", "堤博明", 1],
    [26, "怒られる西片", "堤博明", 1],
    [27, "高木さんにやにや", "堤博明", 1],
    [28, "落ち込む西片", "堤博明", 1],
    [29, "ざわざわドクンドクンもやもやー", "堤博明", 1],
    [30, "高木さんにドキドキ", "堤博明", 1],
    [31, "ミナとユカリとサナエ", "堤博明", 1],
    [32, "尾行", "堤博明", 1],
    [33, "100%片想い (インストゥルメンタル)", "堤博明", 1],
    [34, "100%片想い (TVサイズ)", "大嵜さん", 1],
    [35, "高木さんと西片の学校", "堤博明", 1],
    [36, "西片イライラ", "堤博明", 1],
    [37, "気まずい", "堤博明", 1],
    [38, "どんより", "堤博明", 1],
    [39, "勝利確信の西片", "堤博明", 1],
    [40, "からかい上手", "堤博明", 1],
    [41, "夏休み!", "堤博明", 1],
    [42, "肝試し", "堤博明", 1],
    [43, "台風", "堤博明", 1],
    [44, "からかわれた帰り道", "堤博明", 1],
    [45, "高木さんのいたずら", "堤博明", 1],
    [46, "高木さんのほおづえ", "堤博明", 1],
    [47, "高木さんと西片の日常", "堤博明", 1],
    [48, "やってしまった、、、", "堤博明", 1],
    [49, "恐怖動画", "堤博明", 1],
    [50, "100%片想い (カラオケ)", "堤博明", 1],
    [51, "休み時間", "堤博明", 1],
    [52, "ちょっと恥ずかしい", "堤博明", 1],
    [53, "高木さんの寂しげな顔", "堤博明", 1],
    [54, "席替え", "堤博明", 1],
    [55, "100%片想い", "大嵜さんと堤くん", 1],
]
links = ["https://beta.musicbrainz.org/release/09fda17a-3e4f-485e-a95b-2703198b6a0d", "https://vgmdb.net/album/75579"]

[06957b69801aeb13a83381e72c9e7316]
catalognumber = "TBR28094D-2"
date = "2018-06-13"
album = "からかい上手の高木さん ドラマCD2"
tracks = [
    [1, "アイス", "高木さん（高橋李依）・西片（梶裕貴）", 1],
    [2, "ノート", "", 1],
]
links = ["https://vgmdb.net/album/74067"]

[e5bb8f1f7c9eeaeb73d08e7d82a0b212]
catalognumber = "TBR28096D-2"
date = "2018-08-15"
album = "からかい上手の高木さん ドラマCD3"
tracks = [
    [1, "秋の日", "", 1],
    [2, "体操着", "", 1],
]
links = ["https://vgmdb.net/album/74068"]

[441392730fb27d807406af2b5fd6ddfe]
catalognumber = "THCS-60245"
date = "2019-07-17"
album = "ゼロセンチメートル / 大原ゆい子 [アーティスト盤]"
tracks = [
    [1, "ゼロセンチメートル", "大原ゆい子", 1],
    [2, "ラブビーム中", "大原ゆい子", 1],
    [3, "チャンス", "大原ゆい子", 1],
    [4, "ゼロセンチメートル -INSTRUMENTAL-", "大原ゆい子", 1],
    [5, "ラブビーム中 -INSTRUMENTAL-", "大原ゆい子", 1],
    [6, "チャンス -INSTRUMENTAL-", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/9b3eda00-6647-48a7-b58d-472bad2cdc36", "https://vgmdb.net/album/86120"]

[16b753c3e6bd238ed504fd4acb8d2040]
catalognumber = "THCS-60246"
date = "2019-07-17"
album = "ゼロセンチメートル / 大原ゆい子 [アニメ盤]"
tracks = [
    [1, "ゼロセンチメートル", "大原ゆい子", 1],
    [2, "知らなければ", "大原ゆい子", 1],
    [3, "君と光", "大原ゆい子", 1],
    [4, "ゼロセンチメートル -INSTRUMENTAL-", "大原ゆい子", 1],
    [5, "知らなければ -INSTRUMENTAL-", "大原ゆい子", 1],
    [6, "君と光 -INSTRUMENTAL-", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/4d934fac-b55a-4033-acdf-10efe5da220e", "https://vgmdb.net/album/86121"]

[e9ab117c77905e37881fa1a6ecb94cea]
catalognumber = "THCA-60251"
date = "2019-09-25"
album = "「からかい上手の高木さん2」Music Collection"
tracks = [
    [1, "手をつないでくれたら西片の勝ち", "堤博明", 1],
    [2, "教科書忘れた?", "堤博明", 1],
    [3, "西片と高木さんって、、", "堤博明", 1],
    [4, "西片と高木さんって、、ゆっくりと", "堤博明", 1],
    [5, "サブタイトル 高木さん 1", "堤博明", 1],
    [6, "サブタイトル 高木さん 2", "堤博明", 1],
    [7, "サブタイトル 高木さん 3", "堤博明", 1],
    [8, "サブタイトル 高木さん 4", "堤博明", 1],
    [9, "サブタイトル 高木さん 5", "堤博明", 1],
    [10, "不器用な中井と真野さん", "堤博明", 1],
    [11, "こっちは?", "堤博明", 1],
    [12, "お花見", "堤博明", 1],
    [13, "100%片想い セカンドシ一ズン", "大嵜慶子", 1],
    [14, "100%先輩", "堤博明", 1],
    [15, "後輩ごっこ", "堤博明", 1],
    [16, "もう一個の答え", "堤博明", 1],
    [17, "ご機嫌", "堤博明", 1],
    [18, "くしゃみ", "堤博明", 1],
    [19, "へ?", "堤博明", 1],
    [20, "「ゼロセンチメートル」 高木さんBGMVer", "大原ゆい子", 2],
    [21, "高木さんのおはよう", "堤博明", 1],
    [22, "二人の距離", "堤博明", 1],
    [23, "西片の催眠術", "堤博明", 1],
    [24, "手をあっためる", "堤博明", 1],
    [25, "下校中の西片と高木さん", "堤博明", 1],
    [26, "サブタイトル 西片 1", "堤博明", 1],
    [27, "サブタイトル 西片 2", "堤博明", 1],
    [28, "サブタイトル 西片 3", "堤博明", 1],
    [29, "ブラジルのダンディ", "堤博明", 1],
    [30, "高木さんはメロンソーダ", "堤博明", 1],
    [31, "ダンディ2", "堤博明", 1],
    [32, "ダンディな高木さん", "堤博明", 1],
    [33, "ダンディの日常", "堤博明", 1],
    [34, "ミナとユカリとサナエのまったり", "堤博明", 1],
    [35, "スポーッテスト", "堤博明", 1],
    [36, "駄菓子屋", "堤博明", 1],
    [37, "これだ!", "堤博明", 1],
    [38, "林間学校", "堤博明", 1],
    [39, "ハイキング", "堤博明", 1],
    [40, "どしゃ降りからの晴れ", "堤博明", 1],
    [41, "ミナとユカリとサナエのカレー作り", "堤博明", 1],
    [42, "テントからの合図", "堤博明", 1],
    [43, "林間学校のドキドキ", "堤博明", 1],
    [44, "天の川の出会い", "堤博明", 1],
    [45, "西片と高木さんの天の川", "堤博明", 1],
    [46, "星に願い事", "堤博明", 1],
    [47, "頼む木村!高尾! ~西片の願い~", "堤博明", 1],
    [48, "サブタイトル 西片と高木さん 1", "堤博明", 1],
    [49, "サブタイトル 西片と高木さん 2", "堤博明", 1],
    [50, "体育倉庫で", "堤博明", 1],
    [51, "体育倉庫で 2", "堤博明", 1],
    [52, "たじろぐ西片", "堤博明", 1],
    [53, "宝くじが当たったら", "堤博明", 1],
    [54, "西片と高木さんの宝くじ", "堤博明", 1],
    [55, "一回もからかわれない日", "堤博明", 1],
    [56, "お母さんとケンカ", "堤博明", 1],
    [57, "北条さんは大人っぽい人が好き", "堤博明", 1],
    [58, "ユカリと花火", "堤博明", 1],
    [59, "タ燒け空", "堤博明", 1],
    [60, "西片の勇気", "堤博明", 1],
    [61, "サブタイトル 夏祭り", "堤博明", 1],
    [62, "浴衣姿の高木さん", "堤博明", 1],
    [63, "カップルと呼ばれたら", "堤博明", 1],
    [64, "ミナとユカリとサナエの夏祭り", "堤博明", 1],
    [65, "プレゼント", "堤博明", 1],
    [66, "二人で", "堤博明", 1],
    [67, "線香花火", "堤博明", 1],
]
links = ["https://beta.musicbrainz.org/release/89ce17c3-b23c-403f-8114-e89239875e1b", "https://vgmdb.net/album/88289"]

[548f9e798d970ddb30470675c93adea2]
catalognumber = "THCA-60249"
date = "2019-09-25"
album = "星に名前をつけるとき / 大原ゆい子"
tracks = [
    [1, "Magic Parade", "大原ゆい子", 0],
    [2, "ゼロセンチメートル", "大原ゆい子", 1],
    [3, "夢の途中で", "大原ゆい子", 0],
    [4, "透明な翼", "大原ゆい子", 0],
    [5, "星が眠るまで踊ろうよ", "大原ゆい子", 0],
    [6, "えがおのまほう", "大原ゆい子", 0],
    [7, "からっぽになりたい", "大原ゆい子", 0],
    [8, "煌めく浜辺", "大原ゆい子", 0],
    [9, "雨宿り", "大原ゆい子", 0],
    [10, "205号室", "大原ゆい子", 0],
    [11, "ハイステッパー", "大原ゆい子", 0],
    [12, "言わないけどね。", "大原ゆい子", 1],
    [13, "変わらない宝物", "大原ゆい子", 0],
    [14, "月より綺麗だった", "大原ゆい子", 0],
    [15, "星を辿れば", "大原ゆい子", 0],
    [16, "夜になれば", "大原ゆい子", 0],
]
links = ["https://beta.musicbrainz.org/release/5a1f8b50-c297-4906-900d-1e77498a0810", "https://vgmdb.net/album/88287"]

[7d2b8d756fe9fa9f8dcb44206b72b5e3]
catalognumber = "THCA-60250"
date = "2019-09-25"
album = "「からかい上手の高木さん2」Cover Song Collection"
tracks = [
    [1, "奏(かなで)", "高木さん(CV:高橋李依)", 2],
    [2, "粉雪", "高木さん(CV:高橋李依)", 2],
    [3, "キセキ", "高木さん(CV:高橋李依)", 2],
    [4, "ありがとう", "高木さん(CV:高橋李依)", 1],
    [5, "STARS", "高木さん(CV:高橋李依)", 1],
    [6, "あなたに", "高木さん(CV:高橋李依)", 1],
    [7, "言わないけどね。", "高木さん(CV:高橋李依)", 1],
    [8, "やさしい気持ち", "高木さん(CV:高橋李依)", 1],
    [9, "100万回の「I love you」", "高木さん(CV:高橋李依)", 2],
]
links = ["https://beta.musicbrainz.org/release/7d4d2989-fa18-40ff-92c4-bce89b7aaf72", "https://vgmdb.net/album/88288"]

[88e212ca5ebbabd9622fa68010d11c59]
catalognumber = ""
date = "2019-12-23"
album = "100万回の「I love you」"
tracks = [
    [1, "100万回の「I love you」", "高橋李依", 1],
]
links = ["https://music.163.com/#/album?id=187934627"]

[a6b0d97a401db8d6586f3a2f2d17c8db]
catalognumber = "TBZR-1141~2"
date = "2020-01-29"
album = "ラジオCD「TVアニメ『からかい上手の高木さん2』Presents からかい上手の高\"橋\"さんラジオ2」"
tracks = []
links = ["https://vgmdb.net/album/93228"]

[c9ab814bc31e472c3945593b677f1b19]
catalognumber = "QECR-91003"
date = "2020-12-23"
album = "IMAGINATION vol.3"
tracks = [
    [1, "スターラブレイション", "愛宮みるく", 0],
    [2, "気分上々↑↑", "鈴鹿詩子", 0],
    [3, "ね～え？", "周防パトラ", 0],
    [4, "そばかす", "鈴原るる", 0],
    [5, "GLAMOROUS SKY", "宗谷いちか", 0],
    [6, "恋のつぼみ", "角巻わため", 0],
    [7, "風吹けば恋", "夏色まつり", 1],
    [8, "I WISH", "犬山たまき", 0],
    [9, "じょいふる", "愛宮みるく ＆ 鈴鹿詩子", 1],
    [10, "もってけ！セーラーふく", "周防パトラ ＆ 鈴原るる", 0],
    [11, "365日の紙飛行機", "犬山たまき ＆ 夏色まつり", 0],
    [12, "走れ!", "宗谷いちか ＆ 角巻わため", 0],
    [13, "大声ダイヤモンド", "愛宮みるく、鈴鹿詩子、周防パトラ、鈴原るる、宗谷いちか、角巻わため、夏色まつり ＆ 犬山たまき", 0],
]
links = ["https://beta.musicbrainz.org/release/5d2d162b-610b-40c6-b51f-93aadbb972cc", "https://vgmdb.net/album/113955"]

[7f291ad872498bd2bdeb054febeb96b5]
catalognumber = "N/A"
date = "2021-12-27"
album = "まっすぐ / 大原ゆい子"
tracks = [
    [1, "まっすぐ", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/d1f96f83-e9c9-4410-aa37-dfcd3be8d5b8", "https://vgmdb.net/album/116870"]

[0dff4f91d442b512e3e895fff0b76b32]
catalognumber = "N/A"
date = "2022-01-08"
album = "夢で逢えたら / 高木さん(CV:高橋李依)"
tracks = [
    [1, "夢で逢えたら", "", 1],
]
links = ["https://vgmdb.net/album/117081"]

[0d166497eb7c2d3aa68799531e8b7109]
catalognumber = "N/A"
date = "2022-01-15"
album = "Over Drive / 高木さん(CV:高橋李依)"
tracks = [
    [1, "Over Drive", "", 1],
]
links = ["https://vgmdb.net/album/117082"]

[80638a06def53b4cb1d79b2c50c421f8]
catalognumber = "N/A"
date = "2022-01-29"
album = "ひまわりの約束 / 高木さん(CV:高橋李依)"
tracks = [
    [1, "ひまわりの約束", "", 1],
]
links = ["https://vgmdb.net/album/117846"]

[3eea0f14471d0ba42712a14a6619759e]
catalognumber = "N/A"
date = "2022-02-12"
album = "まっすぐ～ラララver.～ / 大原ゆい子"
tracks = [
    [1, "まっすぐ～ラララver.～", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/293cdf2c-b275-4b50-b623-5966d10b2413", "https://vgmdb.net/album/118093"]

[e240c1f0ad8c5fcc2056a766f64b6003]
catalognumber = "N/A"
date = "2022-02-12"
album = "学園天国 / 高木さん(CV:高橋李依)"
tracks = [
    [1, "学園天国", "", 1],
]
links = ["https://vgmdb.net/album/117847"]

[6c1e8b1b858e787f6b3d2e2e6c697558]
catalognumber = "N/A"
date = "2022-02-19"
album = "じょいふる / 高木さん(CV:高橋李依)"
tracks = [
    [1, "じょいふる", "", 1],
]
links = ["https://vgmdb.net/album/117848"]

[f34e15c4298f4f3934bf51b4db4e2320]
catalognumber = "N/A"
date = "2022-03-05"
album = "サンタが町にやってくる / 高木さん(CV:高橋李依)"
tracks = [
    [1, "サンタが町にやってくる", "", 1],
]
links = ["https://vgmdb.net/album/117849"]

[56af34a8b5fa4277302ee58c93d05c1e]
catalognumber = "N/A"
date = "2022-03-05"
album = "サンタになりたい / 大原ゆい子"
tracks = [
    [1, "サンタになりたい", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/655bdfb0-acba-4aaf-9a23-2b7031330b1a", "https://vgmdb.net/album/118094"]

[cf7f5f5f18bcee6064f0e86dba81f478]
catalognumber = "N/A"
date = "2022-03-12"
album = "スノーマジックファンタジー / 高木さん(CV:高橋李依)"
tracks = [
    [1, "スノーマジックファンタジー", "", 1],
]
links = ["https://vgmdb.net/album/117850"]

[ed7d1bc9798ca8b2dfc2fa07a23bc690]
catalognumber = "N/A"
date = "2022-03-26"
album = "花 / 高木さん(CV:高橋李依)"
tracks = [
    [1, "花", "", 1],
]
links = ["https://vgmdb.net/album/117851"]

[39cc73c6bcb00eb790342085965f794c]
catalognumber = "N/A"
date = "2022-03-26"
album = "風見鶏を見つけて / 大原ゆい子"
tracks = [
    [1, "風見鶏を見つけて", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/466a22f6-24e9-43c1-948d-0ae892e7a99e", "https://vgmdb.net/album/118095"]

[f11a2cf81c702e3326c524fbf7cd39eb]
catalognumber = "N/A"
date = "2022-06-10"
album = "からかい上手の高木さん3 Music Collection"
tracks = [
    [1, "握力のやつ", "堤博明", 1],
    [2, "西片の夢の中", "堤博明", 1],
    [3, "いつか・・・", "堤博明", 1],
    [4, "気配", "堤博明", 1],
    [5, "続気配", "堤博明", 1],
    [6, "RUNNER -Instrumental Ver.-", "堤博明", 1],
    [7, "二人で見る夕日", "堤博明", 1],
    [8, "早秋の朝", "堤博明", 1],
    [9, "魔球タイムスリップ", "堤博明", 1],
    [10, "ミナとユカリとサナエのネコ救出", "堤博明", 1],
    [11, "ミナとユカリとサナエの日常", "堤博明", 1],
    [12, "コノナツ VS 爆サカ", "堤博明", 1],
    [13, "雨の日", "堤博明", 1],
    [14, "UFOの曲", "堤博明", 1],
    [15, "UFOの曲2", "堤博明", 1],
    [16, "トラ柄衣装の高木さん", "堤博明", 1],
    [17, "ピーマン", "堤博明", 1],
    [18, "ロミ代とジュリ夫", "堤博明", 1],
    [19, "牛の部位", "堤博明", 1],
    [20, "ロミ代とジュリ夫(本番)", "堤博明", 1],
    [21, "春の日の出逢い", "堤博明", 1],
    [22, "まっすぐ -EP07 Instrumental Ver.-", "堤博明", 1],
    [23, "ざわつく気持ち", "堤博明", 1],
    [24, "牽制しあう浜口と北条", "堤博明", 1],
    [25, "高木サンタの悪夢", "堤博明", 1],
    [26, "本島行きのフェリー", "堤博明", 1],
    [27, "迷子の二人", "堤博明", 1],
    [28, "サンタクロースはオレだ", "堤博明", 1],
    [29, "高木さんの演技", "堤博明", 1],
    [30, "クリスマスプレゼント", "堤博明", 1],
    [31, "帰りのフェリー", "堤博明", 1],
    [32, "ミナとユカリとサナエの正月1", "堤博明", 1],
    [33, "ミナとユカリとサナエの正月2", "堤博明", 1],
    [34, "バレンタインの不安", "堤博明", 1],
    [35, "西片クエスト", "堤博明", 1],
    [36, "夢かどうか", "堤博明", 1],
]
links = ["https://beta.musicbrainz.org/release/16171e39-f234-447c-ad3a-1cd5d0402fef", "https://vgmdb.net/album/120940"]

[a258984f92318a35c67326f5a4190426]
catalognumber = "N/A"
date = "2022-06-10"
album = "劇場版 からかい上手の高木さん Music Collection"
tracks = [
    [1, "雨のち晴れ", "堤博明", 1],
    [2, "チョキ作戦", "堤博明", 0],
    [3, "からかい貯金", "堤博明", 0],
    [4, "いつもと違う高木さん", "堤博明", 0],
    [5, "ミナとユカリとサナエの同じような日々", "堤博明", 0],
    [6, "誘う勇気と誘われる喜び", "堤博明", 1],
    [7, "虫送り", "堤博明", 1],
    [8, "小さなバス停", "堤博明", 0],
    [9, "会う理由", "堤博明", 0],
    [10, "ハナとの出会い", "堤博明", 0],
    [11, "思い入れのはじまり", "堤博明", 0],
    [12, "ミナとユカリとサナエのやりたいこと100", "堤博明", 0],
    [13, "名前決め対決", "堤博明", 0],
    [14, "ハナと高木さんと西片", "堤博明", 0],
    [15, "ハナと勝負", "堤博明", 0],
    [16, "終わりたくない", "堤博明", 1],
    [17, "ハナとの別れ", "堤博明", 0],
    [18, "西片から高木さんへ", "堤博明", 1],
    [19, "高木さんから西片へ", "堤博明", 1],
    [20, "からかい上手の高木さん", "堤博明", 0],
    [21, "家族揃って", "堤博明", 0],
]
links = ["https://beta.musicbrainz.org/release/b02b46a9-3ff4-465a-84c8-c7b5b6959723", "https://vgmdb.net/album/120941"]

[1401adadd7fed3ed528aa21357cda58b]
catalognumber = "THCA-60274"
date = "2022-07-13"
album = "からかい上手の高木さん3&劇場版 Memorial Box Arrangement, Vocal"
tracks = [
    [1, "夢で逢えたら", "高木さん(CV:高橋李依)", 1],
    [2, "Over Drive", "高木さん(CV:高橋李依)", 1],
    [3, "ひまわりの約束", "高木さん(CV:高橋李依)", 1],
    [4, "学園天国", "高木さん(CV:高橋李依)", 1],
    [5, "じょいふる", "高木さん(CV:高橋李依)", 1],
    [6, "サンタが町にやってくる", "高木さん(CV:高橋李依)", 1],
    [7, "スノーマジックファンタジー", "高木さん(CV:高橋李依)", 1],
    [8, "花", "高木さん(CV:高橋李依)", 1],
    [9, "明日への扉", "高木さん(CV:高橋李依)", 1],
    [10, "天体観測", "高木さん(CV:高橋李依)", 1],
    [11, "fragile", "高木さん(CV:高橋李依)", 1],
    [12, "君に届け", "高木さん(CV:高橋李依)", 1],
]
links = ["https://beta.musicbrainz.org/release/ea92cf20-e377-4cea-901a-5ce6de364929", "https://vgmdb.net/album/119228"]

[1f29f5effbccd6378f68fb33554b7aa3]
catalognumber = "THCA-60274"
date = "2022-07-13"
album = "からかい上手の高木さん3&劇場版 Memorial Box Vocal"
tracks = [
    [1, "まっすぐ", "大原ゆい子", 1],
    [2, "まっすぐ～ラララver.～", "大原ゆい子", 1],
    [3, "サンタになりたい", "大原ゆい子", 1],
    [4, "風見鶏を見つけて", "大原ゆい子", 1],
    [5, "はじまりの夏", "大原ゆい子", 1],
    [6, "ハマボウの花", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/ea92cf20-e377-4cea-901a-5ce6de364929", "https://vgmdb.net/album/119228"]

[3a6c6867c24099ccaed2bea7862ebbc1]
catalognumber = "THCA-60274"
date = "2022-07-13"
album = "からかい上手の高木さん3&劇場版 Memorial Box Vocal, Live Event, Video"
tracks = [
    [1, "「からかい上手の高木さん」クリスマスイヴイヴイヴライブ～あたため上手の高木サンタ～", "", 0],
]
links = ["https://vgmdb.net/album/119228"]

[194a37e1301f175cf8754b991650ba30]
catalognumber = "THCA-60273"
date = "2022-07-13"
album = "Island Memories / 大原ゆい子"
tracks = [
    [1, "まっすぐ", "大原ゆい子", 1],
    [2, "まっすぐ～ラララver.～", "大原ゆい子", 1],
    [3, "サンタになりたい", "大原ゆい子", 1],
    [4, "風見鶏を見つけて", "大原ゆい子", 1],
    [5, "はじまりの夏", "大原ゆい子", 2],
    [6, "ハマボウの花", "大原ゆい子", 1],
]
links = ["https://beta.musicbrainz.org/release/ba8bff20-5250-48d0-93b6-d9893d8bc0c2", "https://vgmdb.net/album/119226"]

[e86503d33daec21647242f436a9468ad]
catalognumber = "THCA-60272"
date = "2022-07-13"
album = "「からかい上手の高木さん3&劇場版」 Cover Song Collection"
tracks = [
    [1, "夢で逢えたら", "高木さん(CV:高橋李依)", 1],
    [2, "Over Drive", "高木さん(CV:高橋李依)", 1],
    [3, "ひまわりの約束", "高木さん(CV:高橋李依)", 2],
    [4, "学園天国", "高木さん(CV:高橋李依)", 1],
    [5, "じょいふる", "高木さん(CV:高橋李依)", 1],
    [6, "サンタが町にやってくる", "高木さん(CV:高橋李依)", 1],
    [7, "スノーマジックファンタジー", "高木さん(CV:高橋李依)", 1],
    [8, "花", "高木さん(CV:高橋李依)", 1],
    [9, "明日への扉", "高木さん(CV:高橋李依)", 1],
    [10, "天体観測", "高木さん(CV:高橋李依)", 1],
    [11, "fragile", "高木さん(CV:高橋李依)", 2],
    [12, "君に届け", "高木さん(CV:高橋李依)", 1],
]
links = ["https://beta.musicbrainz.org/release/0c8fd578-69e6-42ac-9571-a534262f93a0", "https://vgmdb.net/album/119227"]
