[1a1216b3634bb0f9d8aa31654166a848]
catalognumber = "KICM-1286"
date = "2009-08-05"
album = "君へとつなぐココロ / 中町かな (CV:豊崎愛生)・天野咲妃 (CV:水原薫)・久地院美華 (CV:釘宮理恵)"
tracks = [
    [1, "君へとつなぐココロ", "中町かな(CV:豊崎愛生)・天野咲妃(CV:水原薫)・久地院美華(CV:釘宮理恵)", 0],
    [2, "WAKE ME UP(^_-)b!", "中町かな(CV:豊崎愛生)・天野咲妃(CV:水原薫)・久地院美華(CV:釘宮理恵)", 0],
    [3, "君へとつなぐココロ (off vocal ver.)", "中町かな(CV:豊崎愛生)・天野咲妃(CV:水原薫)・久地院美華(CV:釘宮理恵)", 0],
    [4, "WAKE ME UP(^_-)b! (off vocal ver.)", "中町かな(CV:豊崎愛生)・天野咲妃(CV:水原薫)・久地院美華(CV:釘宮理恵)", 0],
]
links = ["https://beta.musicbrainz.org/release/93d97d52-8a9d-47b7-b941-fb73e15539b1", "https://vgmdb.net/album/61240"]

[658ec39fd039eae0ef3ffec58e04d5cd]
catalognumber = "KICM-1282"
date = "2009-08-26"
album = "YAHHO!! / 堀江由衣"
tracks = [
    [1, "YAHHO!!", "堀江由衣", 0],
    [2, "daisy", "堀江由衣", 0],
    [3, "YAHHO!! (off vocal ver.)", "堀江由衣", 0],
    [4, "daisy (off vocal ver.)", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/f685e7b5-b1ac-4b8c-993e-b97bbf76b865", "https://vgmdb.net/album/64587"]

[81318fc1a7fb62feaae8c94219094567]
catalognumber = "KIZM-35~6"
date = "2009-08-26"
album = "YAHHO!! / 堀江由衣 [初回限定盤] Vocal"
tracks = [
    [1, "YAHHO!!", "堀江由衣", 0],
    [2, "daisy", "堀江由衣", 0],
    [3, "YAHHO!! (off vocal ver.)", "堀江由衣", 0],
    [4, "daisy (off vocal ver.)", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/8ce3803a-b3e3-435d-aace-ecfe1cbe3eb5", "https://vgmdb.net/album/64586"]

[a0bd0d3831f3584bf30aef08d931a318]
catalognumber = "KIZM-35~6"
date = "2009-08-26"
album = "YAHHO!! / 堀江由衣 [初回限定盤] Video"
tracks = [
    [1, "YAHHO!! (MUSIC CLIP)", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/8ce3803a-b3e3-435d-aace-ecfe1cbe3eb5", "https://vgmdb.net/album/64586"]

[79ec68eabcbb3d70f43f211507475fe7]
catalognumber = "KICA-990~1"
date = "2009-09-09"
album = "「かなめも」キャラクターソング＆オリジナルサウンドトラック アルバム: かなめろ Vocal"
tracks = [
    [1, "虹色ニュース", "中町かな", 0],
    [2, "ペカっと 朝顔スマイル", "天野咲妃", 0],
    [3, "甘味のち快晴", "北岡ゆめ&南ゆうき", 0],
    [4, "Where is gold?", "東ひなた", 0],
    [5, "LOVE萌え呑み", "西田はるか", 0],
    [6, "友情宣言←ジュースで乾杯☆", "久地院美華", 0],
    [7, "最新ニュースを待っててね。～風新新聞専売所のテーマ～", "風新新聞専売所員with久地院美華", 0],
    [8, "ビキニはすぐにペロンペロン ♪", "西田はるか", 0],
    [9, "夏はやっぱりプールでしょ ♪", "北岡ゆめ・南ゆうき・東ひなた", 0],
    [10, "それが水着 ♪", "西田はるかwith北岡ゆめ・南ゆうき・東ひなた", 0],
    [11, "代理は鬼 ♪", "北岡ゆめ・南ゆうき・東ひなた・西田はるか", 0],
    [12, "働く少女 ♪", "働く少女達", 0],
    [13, "だいじょうブイ", "中町かな", 0],
]
links = ["https://beta.musicbrainz.org/release/1426f26b-5c20-4b25-9fec-97f373302fa5", "https://vgmdb.net/album/50231"]

[55cce47568dd30d6b93a796286e19693]
catalognumber = "KICA-990~1"
date = "2009-09-09"
album = "「かなめも」キャラクターソング＆オリジナルサウンドトラック アルバム: かなめろ Original Soundtrack, Vocal"
tracks = [
    [1, "君へとつなぐココロ　TV-Size Ver.", "中町かな(CV:豊崎愛生)・天野咲妃(CV:水原薫)・久地院美華(CV:釘宮理恵)", 0],
    [2, "みんながいるから (M3)", "橋本由香利", 0],
    [3, "風新新聞 (M20)", "橋本由香利", 0],
    [4, "今日も元気元気!! (M9)", "橋本由香利", 0],
    [5, "いつもの坂道 (M10)", "橋本由香利", 0],
    [6, "萌えなの～ね (M38)", "橋本由香利", 0],
    [7, "次、行ってみよ～ (M6)", "橋本由香利", 0],
    [8, "う～ん困った。。。。 (M11)", "橋本由香利", 0],
    [9, "おぼろ月夜 (M7)", "橋本由香利", 0],
    [10, "ゆったり、のんびり (M8)", "橋本由香利", 0],
    [11, "こんなんじゃダメ、、、よねぇ (M21)", "橋本由香利", 0],
    [12, "残念な感じ (M26)", "橋本由香利", 0],
    [13, "とほほ、、、、 (M34)", "橋本由香利", 0],
    [14, "一寸先は闇 (M37)", "橋本由香利", 0],
    [15, "凍り付く笑顔 (M35)", "橋本由香利", 0],
    [16, "冷たい視線 (M36)", "橋本由香利", 0],
    [17, "アイキャッチA (M12A)", "橋本由香利", 0],
    [18, "うす雲と雨粒 (M2)", "橋本由香利", 0],
    [19, "ほんとうはひとりぼっち (M14)", "橋本由香利", 0],
    [20, "おばあちゃんへの手紙 (M5)", "橋本由香利", 0],
    [21, "かなの日々 (M13)", "橋本由香利", 0],
    [22, "この曲のタイトルを教えてあげてもよろしくてよ (M31)", "橋本由香利", 0],
    [23, "フワフワでホワホワ～ (M25)", "橋本由香利", 0],
    [24, "にゃんこの恋 (M19)", "橋本由香利", 0],
    [25, "はるか妄想 (M30)", "橋本由香利", 0],
    [26, "アイキャッチB (M12B)", "橋本由香利", 0],
    [27, "気分を変えて (M27)", "橋本由香利", 0],
    [28, "急展開 (M28)", "橋本由香利", 0],
    [29, "おだやかな季節 (M15)", "橋本由香利", 0],
    [30, "夜明け前の空 (M17)", "橋本由香利", 0],
    [31, "それぞれの事情 (M18B)", "橋本由香利", 0],
    [32, "幸せってこんな感じよね (M16)", "橋本由香利", 0],
    [33, "友情の調べ (M4)", "橋本由香利", 0],
    [34, "優しい気持ち (M22)", "橋本由香利", 0],
    [35, "YAHHO!! かなめもVer.", "堀江由衣", 0],
    [36, "来週もハッピィ? (M12C)", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/1426f26b-5c20-4b25-9fec-97f373302fa5", "https://vgmdb.net/album/50231"]

[666d3b96d4095a70657a9bad632c14e8]
catalognumber = "QWCE-00131"
date = "2009-11-04"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 8"
tracks = [
    [1, "ふわふわ時間", "MK feat.Latte+CAMRY", 0],
    [2, "止マレ！", "Hommarju feat.himi*mai+Ma15+MAKI", 0],
    [3, "君へとつなぐココロ", "Acid=Stone Valley feat.MAKI+Ma15", 0],
    [4, "林檎もぎれビーム！", "N.O.-SYO feat.TAKANORI+MAKI", 0],
    [5, "Super Driver", "Hommarju feat.yumemi", 0],
    [6, "Mind as Judgment", "B.U.S feat.Latte", 0],
    [7, "片翼の鳥", "Hommarju feat.mamiko", 0],
    [8, "staple stable", "Dizzi Mystica feat.Latte", 0],
    [9, "私の恋はホッチキス", "Starving Trancer feat.Latte+CAMRY", 0],
    [10, "KARMA", "MK feat.R.Cena", 0],
    [11, "Super scription of data", "Icon feat.YURiE", 0],
    [12, "Glossy:MMM", "MK feat.Ma15", 0],
    [13, "本日、満開ワタシ色！", "Hommarju feat.MAKI", 0],
    [14, "明日へのキズナ", "Acid=Stone Valley feat.Latte", 0],
    [15, "YAHHO!!", "MK feat.MAKI", 0],
    [16, "Parallel Hearts", "Acid=Stone Valley feat.YURiE", 0],
    [17, "inner universe", "Icon feat.R.Cena", 0],
    [18, "futuristic imagination", "DJ Sa9 feat.MAKI", 0],
    [19, "キミノウタ", "Acid=Stone Valley feat.YUKI", 0],
    [20, "21st century dreamin' girl", "MAKI", 0],
]
links = ["https://beta.musicbrainz.org/release/acabdb0d-b377-489e-a98e-314b362f276d", "https://vgmdb.net/album/46162"]

[0f6fc94c98a9b465720532c7f92a828e]
catalognumber = "KICS-1737"
date = "2012-02-22"
album = "秘密 / 堀江由衣"
tracks = [
    [1, "秘密 〜プロローグ〜", "堀江由衣", 0],
    [2, "kiss to you", "堀江由衣", 0],
    [3, "Coloring", "堀江由衣", 0],
    [4, "True truly love", "堀江由衣", 0],
    [5, "秘密 〜君を見てた〜", "堀江由衣", 0],
    [6, "イマカラキミノモトヘ", "堀江由衣", 0],
    [7, "PRESENTER", "堀江由衣", 0],
    [8, "インモラリスト", "堀江由衣", 0],
    [9, "MISSION", "堀江由衣", 0],
    [10, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
    [11, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [12, "YAHHO!!", "堀江由衣", 0],
    [13, "sky fish", "堀江由衣", 0],
    [14, "秘密 〜待ち合わせ〜", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/ca8a27f8-9cbc-4686-929a-4a1d0730563c", "https://vgmdb.net/album/65824"]

[2795626b2118c9162082b7a0a1a46d93]
catalognumber = "KICS-91738"
date = "2012-02-22"
album = "秘密 / 堀江由衣 [初回限定盤 秋冬]"
tracks = [
    [1, "秘密 ～プロローグ～", "堀江由衣", 0],
    [2, "kiss to you", "堀江由衣", 0],
    [3, "Coloring", "堀江由衣", 0],
    [4, "True truly love", "堀江由衣", 0],
    [5, "秘密 ～君を見てた～", "堀江由衣", 0],
    [6, "イマカラキミノモトヘ", "堀江由衣", 0],
    [7, "PRESENTER", "堀江由衣", 0],
    [8, "インモラリスト", "堀江由衣", 0],
    [9, "MISSION", "堀江由衣", 0],
    [10, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
    [11, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [12, "YAHHO!!", "堀江由衣", 0],
    [13, "sky fish", "堀江由衣", 0],
    [14, "秘密 ～待ち合わせ～", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/5cdc70f8-03b9-4bbd-9b18-61f1418fd7c8", "https://vgmdb.net/album/65826"]

[a125c80265c102ba3668b9f0c01f0368]
catalognumber = "KICS-91737"
date = "2012-02-22"
album = "秘密 / 堀江由衣 [初回限定盤 春夏]"
tracks = [
    [1, "秘密 ～プロローグ～", "堀江由衣", 0],
    [2, "kiss to you", "堀江由衣", 0],
    [3, "Coloring", "堀江由衣", 0],
    [4, "True truly love", "堀江由衣", 0],
    [5, "秘密 ～君を見てた～", "堀江由衣", 0],
    [6, "イマカラキミノモトヘ", "堀江由衣", 0],
    [7, "PRESENTER", "堀江由衣", 0],
    [8, "インモラリスト", "堀江由衣", 0],
    [9, "MISSION", "堀江由衣", 0],
    [10, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
    [11, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [12, "YAHHO!!", "堀江由衣", 0],
    [13, "sky fish", "堀江由衣", 0],
    [14, "秘密 ～待ち合わせ～", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/5e2afb06-206e-498d-82c4-da73c61c15b8", "https://vgmdb.net/album/65825"]

[b18dec398db2ef5264809f2b0112b355]
catalognumber = "KICS-91819~20"
date = "2012-09-20"
album = "堀江由衣 BEST ALBUM / 堀江由衣 [初回限定盤] Disc 1 [KICS-91819]"
tracks = [
    [1, "Love Destiny", "堀江由衣", 0],
    [2, "キラリ☆宝物", "堀江由衣", 0],
    [3, "ALL MY LOVE", "堀江由衣", 0],
    [4, "心晴れて 夜も明けて", "堀江由衣", 0],
    [5, "スクランブル", "堀江由衣", 0],
    [6, "ヒカリ", "堀江由衣", 0],
    [7, "Days", "堀江由衣", 0],
    [8, "恋する天気図", "堀江由衣", 0],
    [9, "バニラソルト", "堀江由衣", 0],
    [10, "silky heart", "堀江由衣", 0],
    [11, "YAHHO!!", "堀江由衣", 0],
    [12, "インモラリスト", "堀江由衣", 0],
    [13, "PRESENTER", "堀江由衣", 0],
    [14, "Coloring", "堀江由衣", 0],
    [15, "夏の約束", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/002f2c69-60a1-41fe-acc3-293b02e313f7", "https://vgmdb.net/album/65918"]

[3e0bb9a8783f2fdaf81424b476b69ecf]
catalognumber = "KICS-91819~20"
date = "2012-09-20"
album = "堀江由衣 BEST ALBUM / 堀江由衣 [初回限定盤] Disc 2 [KICS-91820]"
tracks = [
    [1, "桜", "堀江由衣", 0],
    [2, "この指とまれ", "堀江由衣", 0],
    [3, "翼", "堀江由衣", 0],
    [4, "お気に入りの自転車", "堀江由衣", 0],
    [5, "Angel 恋をした", "堀江由衣", 0],
    [6, "Romantic Flight", "堀江由衣", 0],
    [7, "It’s my style", "堀江由衣", 0],
    [8, "A Girl in Love", "堀江由衣", 0],
    [9, "笑顔の連鎖", "堀江由衣", 0],
    [10, "マッシュルームマーチ", "堀江由衣", 0],
    [11, "Say cheese!", "堀江由衣", 0],
    [12, "ずっと", "堀江由衣", 0],
    [13, "JET!!", "堀江由衣", 0],
    [14, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [15, "HAPPY SNOW", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/002f2c69-60a1-41fe-acc3-293b02e313f7", "https://vgmdb.net/album/65918"]

[6ca8034081a92efc65f4354db32e1d38]
catalognumber = "KICS-1819"
date = "2012-09-20"
album = "堀江由衣 BEST ALBUM / 堀江由衣"
tracks = [
    [1, "Love Destiny", "堀江由衣", 0],
    [2, "キラリ☆宝物", "堀江由衣", 0],
    [3, "ALL MY LOVE", "堀江由衣", 0],
    [4, "心晴れて 夜も明けて", "堀江由衣", 0],
    [5, "スクランブル", "堀江由衣", 0],
    [6, "ヒカリ", "堀江由衣", 0],
    [7, "Days", "堀江由衣", 0],
    [8, "恋する天気図", "堀江由衣", 0],
    [9, "バニラソルト", "堀江由衣", 0],
    [10, "silky heart", "堀江由衣", 0],
    [11, "YAHHO!!", "堀江由衣", 0],
    [12, "インモラリスト", "堀江由衣", 0],
    [13, "PRESENTER", "堀江由衣", 0],
    [14, "Coloring", "堀江由衣", 0],
    [15, "夏の約束", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/002f2c69-60a1-41fe-acc3-293b02e313f7", "https://vgmdb.net/album/65919"]
