[497017563caacc94fc7a70e37da60618]
catalognumber = "COZC-1679~80"
date = "2020-10-07"
album = "イツカノキオク/透明のペダル / 和氣あず未 Vocal"
tracks = [
    [1, "イツカノキオク", "和氣あず未", 0],
    [2, "透明のペダル", "和氣あず未", 0],
    [3, "Girl's Riot!!", "和氣あず未", 0],
    [4, "Break Theory", "和氣あず未", 0],
    [5, "イツカノキオク (Instrumental)", "和氣あず未", 0],
    [6, "透明のペダル (Instrumental)", "和氣あず未", 0],
    [7, "Girl's Riot!! (Instrumental)", "和氣あず未", 0],
    [8, "Break Theory (Instrumental)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/7012823c-d054-4c64-9cda-6dab8b9016d5", "https://vgmdb.net/album/101804"]

[1d20e91386987b4ded8ace2b26c591f4]
catalognumber = "COZC-1679~80"
date = "2020-10-07"
album = "イツカノキオク/透明のペダル / 和氣あず未 Vocal, Video"
tracks = [
    [1, "イツカノキオク（ミュージックビデオ）", "和氣あず未", 0],
    [2, "イツカノキオク（メイキング）", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/7012823c-d054-4c64-9cda-6dab8b9016d5", "https://vgmdb.net/album/101804"]

[36c918aedf907b2b5799106f30590d8c]
catalognumber = "COCC-17810"
date = "2020-10-07"
album = "イツカノキオク/透明のペダル / 和氣あず未"
tracks = [
    [1, "イツカノキオク", "和氣あず未", 0],
    [2, "透明のペダル", "和氣あず未", 0],
    [3, "Girl's Riot!!", "和氣あず未", 0],
    [4, "Break Theory", "和氣あず未", 0],
    [5, "イツカノキオク (Instrumental)", "和氣あず未", 0],
    [6, "透明のペダル (Instrumental)", "和氣あず未", 0],
    [7, "Girl's Riot!! (Instrumental)", "和氣あず未", 0],
    [8, "Break Theory (Instrumental)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/002b4145-c588-40e4-b305-c9ffbf8e50ba", "https://vgmdb.net/album/101803"]

[70b83b1c767f0169115a393237ff1cbf]
catalognumber = "COCC-17809"
date = "2020-10-21"
album = "あのね。 / ユナ(CV.河瀬茉希)"
tracks = [
    [1, "あのね。", "ユナ(CV:河瀬茉希)", 0],
    [2, "Let’s get started!", "ユナ(CV:河瀬茉希)", 0],
    [3, "あのね。 (Instrumental)", "ユナ(CV:河瀬茉希)", 0],
    [4, "Let’s get started! (Instrumental)", "ユナ(CV:河瀬茉希)", 0],
]
links = ["https://beta.musicbrainz.org/release/14cc74ae-0f79-4c15-9178-b91a8e46fc04", "https://vgmdb.net/album/102692"]

[15d9c1b1d5ea2d84923e7e138835cfdb]
catalognumber = "COCX-41331"
date = "2020-11-25"
album = "TVアニメ「くまクマ熊ベアー」オリジナルサウンドトラック"
tracks = [
    [1, "異世界の風景 #1", "小森茂生", 0],
    [2, "ユナのテーマ #1", "小森茂生", 0],
    [3, "フィナのテーマ", "小森茂生", 0],
    [4, "ギルドの日常", "小森茂生", 0],
    [5, "くまゆる&くまきゅう", "小森茂生", 0],
    [6, "魔物との戦い #3", "小森茂生", 0],
    [7, "現実世界のユナ", "小森茂生", 0],
    [8, "どうしたらいいんだ!？", "小森茂生", 0],
    [9, "怒りのブラックバイパー", "小森茂生", 0],
    [10, "魔物との戦い #1", "小森茂生", 0],
    [11, "優しい気持ち", "小森茂生", 0],
    [12, "ノアのテーマ", "小森茂生", 0],
    [13, "異世界の風景 #2", "小森茂生", 0],
    [14, "ユナのテーマ #3", "小森茂生", 0],
    [15, "これは引くね〜", "小森茂生", 0],
    [16, "まあ、まあ、かな", "小森茂生", 0],
    [17, "不安な気持ち", "小森茂生", 0],
    [18, "嫌な感じがするよ", "小森茂生", 0],
    [19, "悲しい出来事", "小森茂生", 0],
    [20, "孤独", "小森茂生", 0],
    [21, "魔法 #1", "小森茂生", 0],
    [22, "空気が重いよ", "小森茂生", 0],
    [23, "不気味な感じ", "小森茂生", 0],
    [24, "のんびり行こう!", "小森茂生", 0],
    [25, "異世界の風景 #3", "小森茂生", 0],
    [26, "ユナのテーマ #2", "小森茂生", 0],
    [27, "なんだか嬉しいね", "小森茂生", 0],
    [28, "幸せなヒトトキ", "小森茂生", 0],
    [29, "魔法 #2", "小森茂生", 0],
    [30, "魔法の奇跡", "小森茂生", 0],
    [31, "張り詰めた空気", "小森茂生", 0],
    [32, "ちょっとだけピンチ!", "小森茂生", 0],
    [33, "魔物との戦い #2", "小森茂生", 0],
    [34, "ラスボス登場", "小森茂生", 0],
    [35, "最後の闘い", "小森茂生", 0],
    [36, "モヤモヤするユナ", "小森茂生", 0],
    [37, "寂しげなフィナ", "小森茂生", 0],
    [38, "楽しくやろうよ", "小森茂生", 0],
    [39, "今日も元気な子供達", "小森茂生", 0],
    [40, "ユナとフィナ", "小森茂生", 0],
    [41, "イツカノキオク -TVサイズ-", "和氣あず未", 0],
    [42, "あのね。 -TVサイズ-", "ユナ(CV:河瀬茉希)", 0],
]
links = ["https://beta.musicbrainz.org/release/355207fd-7c79-4618-96a3-6a9f6f103bbd", "https://vgmdb.net/album/103906"]

[38d7a24bb9fb13b0d1fa100906006ca9]
catalognumber = "COKM-43033"
date = "2020-12-24"
album = "あのね。 -loved ones ver.- / ユナ (CV: 河瀬茉希) & フィナ (CV: 和氣あず未)"
tracks = [
    [1, "あのね。-loved ones ver.-", "ユナ(CV:河瀬茉希) & フィナ(CV:和氣あず未)", 0],
]
links = ["https://beta.musicbrainz.org/release/a2574a2b-e424-419a-aad4-ed2deb56e801", "https://vgmdb.net/album/107585"]

[90e7bdc9446e02134490409d1ab5f668]
catalognumber = "COZC-1980~1"
date = "2023-04-12"
album = "キミトノミライ/Invisible stars / 和氣あず未 [初回限定盤] Disc 1 (CD) [COZC-1980]"
tracks = [
    [1, "キミトノミライ", "和氣あず未", 0],
    [2, "Invisible stars", "和氣あず未", 0],
    [3, "キミトノミライ (Instrumental)", "和氣あず未", 0],
    [4, "Invisible stars (Instrumental)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/febbcdd4-8198-4e2e-bee2-e8a385d81dd0", "https://vgmdb.net/album/127310"]

[8afcb2315049b9723ba203b869d960cf]
catalognumber = "COZC-1980~1"
date = "2023-04-12"
album = "キミトノミライ/Invisible stars / 和氣あず未 [初回限定盤] Disc 2 (DVD) [COZC-1981]"
tracks = [
    [1, "キミトノミライ (ミュージックビデオ)", "和氣あず未", 0],
    [2, "キミトノミライ (メイキング映像)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/febbcdd4-8198-4e2e-bee2-e8a385d81dd0", "https://vgmdb.net/album/127310"]

[07de4f60f2037199e5d45b316f104eed]
catalognumber = "COCC-18068"
date = "2023-04-12"
album = "キミトノミライ/Invisible stars / 和氣あず未"
tracks = [
    [1, "キミトノミライ", "和氣あず未", 0],
    [2, "Invisible stars", "和氣あず未", 0],
    [3, "キミトノミライ (Instrumental)", "和氣あず未", 0],
    [4, "Invisible stars (Instrumental)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/25ab564f-8a06-44a1-9b3a-cd7f3259820e", "https://vgmdb.net/album/127309"]

[e55f70796f31fed7dcbdaac4c5f3041a]
catalognumber = "COCC-18117"
date = "2023-04-19"
album = "ずっと / ユナ(CV.河瀬茉希)"
tracks = [
    [1, "ずっと", "ユナ(CV:河瀬茉希)", 0],
    [2, "ほんとのきもち。〜あのね。そのつづき〜", "ユナ(CV:河瀬茉希)", 0],
    [3, "あのね。-loved ones ver.-", "ユナ(CV:河瀬茉希) & フィナ(CV:和氣あず未)", 0],
    [4, "あのね。-loved ones ユナside-", "ユナ(CV:河瀬茉希)", 0],
    [5, "あのね。-loved ones フィナside-", "フィナ(CV:和氣あず未)", 0],
    [6, "ずっと (Instrumental)", "ユナ(CV:河瀬茉希)", 0],
    [7, "ほんとのきもち。〜あのね。そのつづき〜 (Instrumental)", "ユナ(CV:河瀬茉希)", 0],
]
links = ["https://beta.musicbrainz.org/release/3820ca2b-91ed-42e5-96a5-82ca3101907b", "https://vgmdb.net/album/127432"]
