[877dcee3e8f6d58556f04a724bcecea1]
catalognumber = "EMCD-1000"
date = "2010-01-01"
album = "こわれかけのオルゴール Original Sound Tracks"
tracks = [
    [1, "はじまり", "Kiyoma", 0],
    [2, "目覚めの时", "Kiyoma", 0],
    [3, "ボツンと一人", "Kiyoma", 0],
    [4, "日记", "Kiyoma", 0],
    [5, "散步", "Kiyoma", 0],
    [6, "ドジっ子", "Kiyoma", 0],
    [7, "オンチ", "Kiyoma", 0],
    [8, "体操", "Kiyoma", 0],
    [9, "努力", "Kiyoma", 0],
    [10, "祭", "Kiyoma", 0],
    [11, "テレビBGM1", "Kiyoma", 0],
    [12, "テレビBGM2", "Kiyoma", 0],
    [13, "喫茶店", "Kiyoma", 0],
    [14, "テレビBGM3", "Kiyoma", 0],
    [15, "夏の浜辺", "Kiyoma", 0],
    [16, "思いやり", "Kiyoma", 0],
    [17, "旧友", "Kiyoma", 0],
    [18, "危机", "Kiyoma", 0],
    [19, "搜り", "Kiyoma", 0],
    [20, "ふらわー", "Kiyoma", 0],
    [21, "梦", "Kiyoma", 0],
    [22, "告白", "Kiyoma", 0],
    [23, "好奇心", "Kiyoma", 0],
    [24, "祈", "Kiyoma", 0],
    [25, "思い出", "Kiyoma", 0],
    [26, "敬一郎の思い", "初音ミク", 0],
    [27, "こわれかけのオルゴールOff Vocal Ver", "佐藤ひろ美", 0],
    [28, "オルゴール", "Kiyoma", 0],
]
links = ["https://beta.musicbrainz.org/release/f399dcb9-01d7-418b-b3ff-2ff1579d7740", "https://vgmdb.net/album/31620"]

[3dadfafbf01e8cbf69049d0fb72a5ba8]
catalognumber = "PDSP-1002"
date = "2010-07-17"
album = "こわれかけのオルゴール"
tracks = [
    [1, "こわれかけのオルゴール", "佐藤ひろ美", 0],
    [2, "こわれかけのオルゴール―Short ver.―", "佐藤ひろ美", 0],
    [3, "こわれかけのオルゴール(Inst)", "佐藤ひろ美", 0],
    [4, "こわれかけのオルゴール―Short ver.―(Inst)", "佐藤ひろ美", 0],
]
links = ["https://beta.musicbrainz.org/release/49b8e557-031f-46b3-8598-44ed02c0716c", "https://vgmdb.net/album/31621"]
