[8b02036f50c3928f670f736a286346fe]
catalognumber = "VTCL-60438"
date = "2016-11-09"
album = "この世界の片隅に オリジナルサウンドトラック"
tracks = [
    [1, "神の御子は今宵しも", "コトリンゴ", 0],
    [2, "悲しくてやりきれない", "コトリンゴ", 0],
    [3, "引き潮の海を歩く子供たち", "コトリンゴ", 0],
    [4, "すいかの思い出", "コトリンゴ", 0],
    [5, "周作さん", "コトリンゴ", 0],
    [6, "うちらどこかで", "コトリンゴ", 0],
    [7, "朝のお仕事", "コトリンゴ", 0],
    [8, "隣組", "コトリンゴ", 0],
    [9, "すずさんと晴美さん", "コトリンゴ", 0],
    [10, "広島の街", "コトリンゴ", 0],
    [11, "戦艦大和", "コトリンゴ", 0],
    [12, "ごはんの支度", "コトリンゴ", 0],
    [13, "径子", "コトリンゴ", 0],
    [14, "疑い", "コトリンゴ", 0],
    [15, "ありこさん", "コトリンゴ", 0],
    [16, "ヤミ市", "コトリンゴ", 0],
    [17, "りんさん", "コトリンゴ", 0],
    [18, "デート", "コトリンゴ", 0],
    [19, "大丈夫かのう", "コトリンゴ", 0],
    [20, "お見送り", "コトリンゴ", 0],
    [21, "あの道", "コトリンゴ", 0],
    [22, "良かった", "コトリンゴ", 0],
    [23, "左手で描く世界", "コトリンゴ", 0],
    [24, "白いサギを追って", "コトリンゴ", 0],
    [25, "広島から来たんかね", "コトリンゴ", 0],
    [26, "飛び去る正義", "コトリンゴ", 0],
    [27, "明日も明後日も", "コトリンゴ", 0],
    [28, "すずさんの右手", "コトリンゴ", 0],
    [29, "最後の務め", "コトリンゴ", 0],
    [30, "みぎてのうた", "コトリンゴ", 0],
    [31, "たんぽぽ", "コトリンゴ", 0],
    [32, "すずさん", "コトリンゴ", 0],
    [33, "New day", "コトリンゴ", 0],
]
links = ["https://beta.musicbrainz.org/release/ff73cb4b-63ee-4cec-8af3-a590f9110608", "https://vgmdb.net/album/61082"]

[19a180003f6ec7ee102fc9bfc6930366]
catalognumber = "VTCL-60514"
date = "2019-12-18"
album = "映画「この世界の片隅に」さらにいくつものサウンドトラック"
tracks = [
    [1, "神の御子は今宵しも", "コトリンゴ", 0],
    [2, "悲しくてやりきれない", "コトリンゴ", 0],
    [3, "引き潮の海を歩く子供たち", "コトリンゴ", 0],
    [4, "すいかの思い出", "コトリンゴ", 0],
    [5, "周作さん", "コトリンゴ", 0],
    [6, "うちらどこかで", "コトリンゴ", 0],
    [7, "朝のお仕事", "コトリンゴ", 0],
    [8, "隣組", "コトリンゴ", 0],
    [9, "すずさんと晴美さん", "コトリンゴ", 0],
    [10, "広島の街", "コトリンゴ", 0],
    [11, "戦艦大和", "コトリンゴ", 0],
    [12, "試験栽培", "コトリンゴ", 0],
    [13, "ごはんの支度", "コトリンゴ", 0],
    [14, "径子", "コトリンゴ", 0],
    [15, "疑い", "コトリンゴ", 0],
    [16, "ありこさん", "コトリンゴ", 0],
    [17, "ヤミ市", "コトリンゴ", 0],
    [18, "りんさん", "コトリンゴ", 0],
    [19, "デート", "コトリンゴ", 0],
    [20, "知らんでええこと", "コトリンゴ", 0],
    [21, "大丈夫かのう", "コトリンゴ", 0],
    [22, "お見送り", "コトリンゴ", 0],
    [23, "あの道", "コトリンゴ", 0],
    [24, "良かった", "コトリンゴ", 0],
    [25, "左手で描く世界", "コトリンゴ", 0],
    [26, "白いサギを追って", "コトリンゴ", 0],
    [27, "広島から来たんかね", "コトリンゴ", 0],
    [28, "飛び去る正義", "コトリンゴ", 0],
    [29, "明日も明後日も", "コトリンゴ", 0],
    [30, "すずさんの右手", "コトリンゴ", 0],
    [31, "最後の務め", "コトリンゴ", 0],
    [32, "りんどうの秘密", "コトリンゴ", 0],
    [33, "みぎてのうた", "コトリンゴ", 0],
    [34, "たんぽぽ (さらにいくつものversion)", "コトリンゴ", 0],
    [35, "わたしの居場所", "コトリンゴ", 0],
    [36, "New day", "コトリンゴ", 0],
    [37, "すずさん", "コトリンゴ", 0],
    [38, "かんとくさん", "コトリンゴ", 0],
]
links = ["https://beta.musicbrainz.org/release/32de03e7-2c5e-4cd3-b371-f6afc11f2fba", "https://vgmdb.net/album/92014"]
