[aa1e13d6b99ec14efee4a4e186f3b56d]
catalognumber = "MMCC-4215"
date = "2009-12-30"
album = "ドラマCD これはゾンビですか"
tracks = [
    [1, "1話 はい、イチゴが好きです", "寺島拓篤, 水原薫, 田村ゆかり, 伊藤静, 能登麻美子, 高橋伸也, 立木文彦, 稲田徹", 1],
    [2, "2話 はい、水着が眩しいです", "寺島拓篤, 水原薫, 田村ゆかり, 伊藤静, 能登麻美子, 高橋伸也, 立木文彦, 稲田徹", 1],
    [3, "3話 マグロ、撮影快調です", "寺島拓篤, 水原薫, 田村ゆかり, 伊藤静, 能登麻美子, 高橋伸也, 立木文彦, 稲田徹", 1],
    [4, "4話 キャストトーク「これはゾンビですか？いえ、伝説の生き物です」", "寺島拓篤, 水原薫, 田村ゆかり, 伊藤静, 能登麻美子, 高橋伸也, 立木文彦, 稲田徹", 1],
]
links = ["https://www.amazon.co.jp/%E3%83%89%E3%83%A9%E3%83%9ECD-%E3%81%93%E3%82%8C%E3%81%AF%E3%82%BE%E3%83%B3%E3%83%93%E3%81%A7%E3%81%99%E3%81%8B-%E3%82%A4%E3%83%A1%E3%83%BC%E3%82%B8%E3%83%BB%E3%82%A2%E3%83%AB%E3%83%90%E3%83%A0/dp/B002SDO1U2"]

[ba4a3063a759fbeccbf7b22457e50e9f]
catalognumber = "VTCL-35103"
date = "2011-02-09"
album = "気づいてゾンビさま、私はクラスメイトです / 山口理恵 with manzo"
tracks = [
    [1, "気づいてゾンビさま、私はクラスメイトです", "山口理恵 with manzo", 1],
    [2, "君がくれた飴", "山口理恵", 1],
    [3, "卒業", "山口理恵", 1],
    [4, "気づいてゾンビさま、私はクラスメイトです ～without vocal", "山口理恵 with manzo", 1],
    [5, "君がくれた飴 ～without vocal", "山口理恵", 1],
    [6, "卒業 ～without vocal", "山口理恵", 1],
]
links = ["https://beta.musicbrainz.org/release/1faec766-ad4e-4829-8b01-b604333617bb", "https://vgmdb.net/album/23957"]

[b7cba79114befb8108cfb86a0b3aabfb]
catalognumber = "VTCL-60237"
date = "2011-02-09"
album = "テレビアニメーション「これはゾンビですか?」ドラマCD『これはゾンビですか? はい、波乱盤上です。』"
tracks = [
    [1, "相川家からご挨拶", "間島淳司, 野水いおり, 吉野裕行 & 日笠陽子", 1],
    [2, "これはゾンビですか?意識調査", "間島淳司, 野水いおり, 吉野裕行 & 日笠陽子", 1],
    [3, "DJハルナの質問コーナー1", "野水いおり", 1],
    [4, "激突!ハルナVSトモノリ", "間島淳司, 野水いおり & 吉野裕行", 1],
    [5, "DJハルナの質問コーナー2", "野水いおり", 1],
    [6, "驚異!月刊コモドドラゴンマガジン計画", "間島淳司, 野水いおり, 吉野裕行, 日笠陽子 & 月宮みどり", 1],
    [7, "妄想ユー会議", "野水いおり & 日笠陽子", 1],
    [8, "おわりに", "間島淳司, 野水いおり & 日笠陽子", 1],
    [9, "DJハルナの質問コーナー3", "野水いおり", 1],
    [10, "おまけ ハルナ", "野水いおり", 1],
    [11, "おまけ セラ", "日笠陽子", 1],
    [12, "おまけ 歩", "間島淳司", 1],
]
links = ["https://beta.musicbrainz.org/release/744bbcc0-9b67-4abd-ba2a-3db1f7099b2d", "https://vgmdb.net/album/147355"]

[f7ed697fff20dd9b1c379ad2e3f5779e]
catalognumber = "VTCL-35102"
date = "2011-02-09"
album = "魔・カ・セ・テ Tonight / 野水いおり"
tracks = [
    [1, "魔・カ・セ・テ Tonight", "野水いおり", 1],
    [2, "テルモメルモ", "野水いおり", 1],
    [3, "魔・カ・セ・テ Tonight (without Iori)", "野水いおり", 1],
    [4, "テルモメルモ (without Iori)", "野水いおり", 1],
]
links = ["https://beta.musicbrainz.org/release/f44695d1-3a0f-44cf-ba16-f62f6b606d0f", "https://vgmdb.net/album/23956"]

[656096448ee427af1c0ef6aac9918a4b]
catalognumber = "VTCL-60238"
date = "2011-03-09"
album = "テレビアニメーション「これはゾンビですか？」ラジオCD１『これは女子力の訓練ですか？はい、ラジオです』～ハルナのお茶会“めっちゃ女子力”～"
tracks = [
    [1, "オープニング", "野水いおり, 山口理恵 & 月宮みどり", 1],
    [2, "前半戦 ～女子力向上計画ケーキ作り～", "野水いおり, 山口理恵 & 月宮みどり", 1],
    [3, "中盤戦 ～女子力向上計画ケーキ作り～", "野水いおり, 山口理恵 & 月宮みどり", 1],
    [4, "後半戦 ～女子力向上計画ケーキ作り～", "野水いおり, 山口理恵 & 月宮みどり", 1],
    [5, "試食！～エンディング ～女子力向上計画ケーキ作り～", "野水いおり, 山口理恵 & 月宮みどり", 1],
]
links = ["https://beta.musicbrainz.org/release/424ef0e4-e0c6-4770-85ff-88bc57b7151f", "https://vgmdb.net/album/139826"]

[dc83b0dc08164a804b3da4814ad9cb1d]
catalognumber = "VTCL-60243"
date = "2011-03-09"
album = "テレビアニメーション「これはゾンビですか?」オリジナルサウンドトラック『めっちゃサントラ』"
tracks = [
    [1, "曇りのち晴れ", "柿島伸次", 1],
    [2, "天気予報なんて当てにならない", "柿島伸次", 1],
    [3, "俺、ゾンビっす!", "柿島伸次", 1],
    [4, "ただいま", "柿島伸次", 1],
    [5, "真夜中の墓地", "柿島伸次", 1],
    [6, "それ!キックじゃね~!", "柿島伸次", 1],
    [7, "ご飯まだ~?", "柿島伸次", 1],
    [8, "お茶の間と扇風機", "柿島伸次", 1],
    [9, "出席番号六億三千四百五十二万六千三百七十九", "柿島伸次", 1],
    [10, "お前が欲しい!", "柿島伸次", 1],
    [11, "100%", "柿島伸次", 1],
    [12, "めっちゃ魔装変身", "柿島伸次", 1],
    [13, "バーッとやってギーだ!", "柿島伸次", 1],
    [14, "120%", "柿島伸次", 1],
    [15, "ノモブヨ、ヲシ、ハシタワ、ドゲダ、グンミーチャ、デー、リブラ!", "柿島伸次", 1],
    [16, "ZOMBIE アイキャッチA", "柿島伸次", 1],
    [17, "惨劇の記憶", "柿島伸次", 1],
    [18, "なんだこの美味さは~", "柿島伸次", 1],
    [19, "またまた、ただいま~", "柿島伸次", 1],
    [20, "傷", "柿島伸次", 1],
    [21, "チェロがいい音だぜ!", "柿島伸次", 1],
    [22, "秘剣!燕返し", "柿島伸次", 1],
    [23, "抜き足、差し足", "柿島伸次", 1],
    [24, "ZOMBIE アイキャッチB", "柿島伸次", 1],
    [25, "この糞虫が!", "柿島伸次", 1],
    [26, "UFOを信じますか?", "柿島伸次", 1],
    [27, "ネクロマンサー", "柿島伸次", 1],
    [28, "惨劇の記録", "柿島伸次", 1],
    [29, "妄想", "柿島伸次", 1],
    [30, "忘却", "柿島伸次", 1],
    [31, "お兄ちゃん、お風呂にする?", "柿島伸次", 1],
    [32, "おはよう!お兄ちゃん!!", "柿島伸次", 1],
    [33, "良いことあるかな?やっぱダメか?", "柿島伸次", 1],
    [34, "ゾンビワルツ", "柿島伸次", 1],
    [35, "勝負だ!", "柿島伸次", 1],
    [36, "勝負止めた(>_<)", "柿島伸次", 1],
    [37, "夕暮れの風", "柿島伸次", 1],
    [38, "明日も遊ぼう!!", "柿島伸次", 1],
    [39, "また来週!", "柿島伸次", 1],
    [40, "魔・カ・セ・テ Tonight ~TV SIZE EDIT", "野水いおり", 1],
    [41, "気づいてゾンビさま、私はクラスメイトです ~TV SIZE EDIT", "山口理恵", 1],
]
links = ["https://beta.musicbrainz.org/release/492105ef-1593-4b99-93c8-2bb0ebbbae31", "https://vgmdb.net/album/22780"]

[988ee3d8e942dcf1294b911c04317f64]
catalognumber = "VTCL-60239"
date = "2011-04-13"
album = "テレビアニメーション「これはゾンビですか？」ラジオCD２『これはセーフですか？はい、ラジオです』～ハルナとお泊まり“めっちゃ夜更かし”～"
tracks = [
    [1, "オープニング", "月宮みどり & 山口理恵", 1],
    [2, "お泊まり会～パジャマ de トーク～", "月宮みどり & 山口理恵", 1],
    [3, "マダムが教えてあ・げ・る!", "月宮みどり & 山口理恵", 1],
    [4, "この場で決めちゃう?ミス・これはゾンビですか?", "月宮みどり & 山口理恵", 1],
    [5, "エンディング", "月宮みどり & 山口理恵", 1],
]
links = ["https://beta.musicbrainz.org/release/4ac06b27-8875-489d-aace-0e2bab750d0e", "https://vgmdb.net/album/139898"]

[34e05fe989a8c6284e8a916d0a4a884b]
catalognumber = "VTCL-60246"
date = "2011-04-20"
album = "テレビアニメーション「これはゾンビですか?」 めっちゃ挿入歌&めっちゃサントラ番外編 『なんだサントラ2枚に別けただけじゃないの? はい、そのとおりです!』"
tracks = [
    [1, "そりゃ魔装でしょ! Rock'n Roll", "野水いおり", 1],
    [2, "吸血ヴィーナス", "合田彩 & 日笠陽子", 1],
    [3, "キラキラダイアモンド", "合田彩", 1],
    [4, "素顔", "月宮みどり & 野水いおり", 1],
    [5, "4話スペシャルBGM", "柿島伸次", 1],
    [6, "9話スペシャルBGM", "柿島伸次", 1],
    [7, "11話スペシャルBGM 前編", "柿島伸次", 1],
    [8, "11話スペシャルBGM 後編", "柿島伸次", 1],
    [9, "ゾンビ的な劇伴じゃないか!", "柿島伸次", 1],
    [10, "涙がでちゃう。", "柿島伸次", 1],
    [11, "相川歩です", "柿島伸次", 1],
    [12, "遊びにいこ~ぜ! バユム", "柿島伸次", 1],
    [13, "ふざけんな......", "柿島伸次", 1],
    [14, "大暴走しちゃいましたね~", "柿島伸次", 1],
    [15, "何だか脱力なBGMだなぁ~", "柿島伸次", 1],
    [16, "月夜の晩に何か起こる!", "柿島伸次", 1],
    [17, "願いが叶いますように。", "柿島伸次", 1],
    [18, "大先生", "柿島伸次", 1],
    [19, "闇の力", "柿島伸次", 1],
    [20, "何で?", "柿島伸次", 1],
    [21, "どうして?", "柿島伸次", 1],
    [22, "ネバーギブアップ!", "柿島伸次", 1],
    [23, "もうタイトル思いつかない", "柿島伸次", 1],
    [24, "まだまだ続きますように!", "柿島伸次", 1],
    [25, "そりゃ魔装でしょ! Rock'n Roll -KARAOKE MIX-", "manzo", 1],
    [26, "吸血ヴィーナス -KARAOKE MIX-", "水野大輔", 1],
    [27, "キラキラダイアモンド -KARAOKE MIX-", "水野大輔", 1],
    [28, "素顔 -KARAOKE MIX-", "柿島伸次", 1],
]
links = ["https://beta.musicbrainz.org/release/17931b06-8c28-4105-8ff1-69340b251885", "https://vgmdb.net/album/24298"]

[ed64bce93d3644cf7bd547d1e73b9d58]
catalognumber = "QWCE-00194"
date = "2011-08-03"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 13"
tracks = [
    [1, "コネクト", "plazma feat.Nahoko", 0],
    [2, "CORE PRIDE", "Hommarju feat.TAKANORI", 0],
    [3, "魔・カ・セ・テ Tonight", "Booing Day feat.MAKI", 1],
    [4, "ぱんでみっく!", "Hommarju feat.mi-mi", 0],
    [5, "Destin Histoire", "Icon feat.JJ", 0],
    [6, "インモラリスト", "Hommarju feat.R.Cena+hideki", 0],
    [7, "RPG", "Booing Day feat.puchi", 0],
    [8, "わが名は小学生", "Dizzi Mystica feat.405+mi-mi", 0],
    [9, "Choose my love!", "Booing Day feat.KANA", 0],
    [10, "Morning Arch", "Dizzi Mystica feat.YURiE", 0],
    [11, "A Whole New World God Only Knows", "Hommarju feat.R.Cena", 0],
    [12, "Scarlet Ballet", "Dizzi Mystica feat.mi-mi", 0],
    [13, "STRAIGHT JET", "MK feat.Latte", 0],
    [14, "Taste of Paradise", "Dizzi Mystica feat.yumemi", 0],
    [15, "Os-宇宙人", "Dizzi Mystica feat.mi-mi", 0],
    [16, "SHINY SHINY", "MK feat.405", 0],
    [17, "SCARLET KNIGHT", "Dizzi Mystica feat.Latte", 0],
    [18, "青い栞", "Icon feat.Yusuke+yuno", 0],
    [19, "Magia", "Dizzi Mystica feat.Natsuhi+R.Cena", 0],
]
links = ["https://beta.musicbrainz.org/release/212e98cc-5094-428f-8042-5fade11a7075", "https://vgmdb.net/album/29349"]

[14bc1e80afee6f966778ec6570dcf294]
catalognumber = "VTZL-28"
date = "2011-10-19"
album = "月虹カタン / 野水いおり Disc 1 (CD) [VTCL-60280]"
tracks = [
    [1, "Flame", "野水いおり", 0],
    [2, "魔・カ・セ・テ Tonight", "野水いおり", 1],
    [3, "Predawn Song", "野水いおり", 0],
    [4, "テルモメルモ", "野水いおり", 1],
    [5, "Broken Wings", "野水いおり", 0],
    [6, "Glory Days", "野水いおり", 0],
    [7, "月虹", "野水いおり", 0],
    [8, "もっと愛しあいましょ", "野水いおり", 0],
]
links = ["https://beta.musicbrainz.org/release/e599f867-1adc-4e89-be15-d5d658c2d3a7", "https://vgmdb.net/album/88160"]

[1379fc956658062f1a4613073e15c5b5]
catalognumber = "VTZL-28"
date = "2011-10-19"
album = "月虹カタン / 野水いおり Disc 2 (DVD) [VTBY-42]"
tracks = [
    [1, "Flame (Music Video)", "野水いおり", 0],
    [2, "Special Feature", "野水いおり", 0],
    [3, "TV-SPOT", "野水いおり", 0],
]
links = ["https://beta.musicbrainz.org/release/e599f867-1adc-4e89-be15-d5d658c2d3a7", "https://vgmdb.net/album/88160"]

[ef30cebe3625acaf9db3bd6082d90a6a]
catalognumber = "VTCL-60280"
date = "2011-10-19"
album = "月虹カタン / 野水いおり"
tracks = [
    [1, "Flame", "野水いおり", 0],
    [2, "魔・カ・セ・テ Tonight", "野水いおり", 1],
    [3, "Predawn Song", "野水いおり", 0],
    [4, "テルモメルモ", "野水いおり", 1],
    [5, "Broken Wings", "野水いおり", 0],
    [6, "Glory Days", "野水いおり", 0],
    [7, "月虹", "野水いおり", 0],
    [8, "もっと愛しあいましょ", "野水いおり", 0],
]
links = ["https://beta.musicbrainz.org/release/52408f48-0a32-44f9-a154-8ef883265b58", "https://vgmdb.net/album/109877"]

[3277bb31d88905e3038fcae54743c873]
catalognumber = "VTCL-35129"
date = "2012-04-25"
album = "恋のビギナーなんです(T_T) / 山口理恵"
tracks = [
    [1, "恋のビギナーなんです(T_T)", "山口理恵", 1],
    [2, "ずっと", "山口理恵", 1],
    [3, "またあしたねII", "山口理恵", 1],
    [4, "恋のビギナーなんです(T_T) 〜without vocal", "山口理恵", 1],
    [5, "ずっと 〜without vocal", "山口理恵", 1],
    [6, "またあしたねII 〜without vocal", "山口理恵", 1],
]
links = ["https://beta.musicbrainz.org/release/6ae98d25-4504-41f6-9233-8ae69a0444ab", "https://vgmdb.net/album/31763"]

[ad1fd98f3df0ad018dd32b7c01d0696f]
catalognumber = "VTZL-42"
date = "2012-04-25"
album = "*** パショナート / 野水いおり Vocal"
tracks = [
    [1, "*** パショナート", "野水いおり", 1],
    [2, "Signalize", "野水いおり", 1],
    [3, "*** パショナート (without Iori)", "野水いおり", 1],
    [4, "Signalize (without Iori)", "野水いおり", 1],
]
links = ["https://beta.musicbrainz.org/release/5aae6c8a-b6c5-43fc-a930-86c79bd53533", "https://vgmdb.net/album/31764"]

[d4f53578136bc2d64b3705aaa7b9bc25]
catalognumber = "VTZL-42"
date = "2012-04-25"
album = "*** パショナート / 野水いおり Video"
tracks = [
    [1, "野水いおり オリジナルカホーンアニメーション「Cajon's Saga」", "", 0],
]
links = ["https://vgmdb.net/album/31764"]

[41f0b2996f425ac406fc7a57fe5d7aa8]
catalognumber = "VTCL-35128"
date = "2012-04-25"
album = "*** パショナート / 野水いおり"
tracks = [
    [1, "*** パショナート", "野水いおり", 1],
    [2, "Signalize", "野水いおり", 1],
    [3, "*** パショナート (without Iori)", "野水いおり", 1],
    [4, "Signalize (without Iori)", "野水いおり", 1],
]
links = ["https://beta.musicbrainz.org/release/5aae6c8a-b6c5-43fc-a930-86c79bd53533", "https://vgmdb.net/album/31762"]

[3ebeba8407ba924ef86d7fe4f4fbf23a]
catalognumber = "VTCL-60312"
date = "2012-07-04"
album = "TVアニメーション「これはゾンビですか? オブ・ザ・デッド」ドラマCD『これは波乱盤上ですか?もう!そうなんでしょ!』"
tracks = [
    [1, "ガイアよ!", "間島淳司", 1],
    [2, "いつもの朝?", "日笠陽子, 間島淳司 & 月宮みどり", 1],
    [3, "妄想対決", "間島淳司, 若本規夫, 月宮みどり & 日笠陽子", 1],
    [4, "エピローグ", "間島淳司, 月宮みどり & 野水いおり", 1],
    [5, "妄想劇場", "月宮みどり & 野水いおり", 1],
]
links = ["https://beta.musicbrainz.org/release/86d80f18-24c1-4df4-8e72-74c891715aa3", "https://vgmdb.net/album/89255"]

[8bc411132356332e699396413de0e3e9]
catalognumber = "VTCL-60310~1"
date = "2012-07-04"
album = "TVアニメーション「これはゾンビですか? オブ・ザ・デッド」 めっちゃフェスティボー! 公式ガイドCD〜つまり歌モノ全部と2期のBGM入り2枚組BEST Vocal"
tracks = [
    [1, "*** パショナート ～TV-SIZE", "野水いおり", 1],
    [2, "めっちゃ!LOVE!イマジネーション", "野水いおり, 月宮みどり, 清水愛, 金元寿子, 合田彩 & 山口理恵", 1],
    [3, "悲・ト・リ・デ 都内Tonight", "manzo", 1],
    [4, "魔・カ・セ・テ Tonight", "野水いおり", 1],
    [5, "すくいたいSOY2", "清水愛", 1],
    [6, "みんなもいいな", "金元寿子", 1],
    [7, "キラキラダイアモンド", "合田彩", 1],
    [8, "気づいてゾンビさま、私はクラスメイトです", "山口理恵 & manzo", 1],
    [9, "素顔 ～ユー&ハルナ Duet version", "月宮みどり & 野水いおり", 1],
    [10, "またあしたね。", "山口理恵", 1],
    [11, "吸血ヴィーナス ～セラversion", "日笠陽子", 1],
    [12, "そりゃ魔装でしょ!Rock'nRoll", "野水いおり", 1],
    [13, "まちびとLOVE SONG.", "合田彩", 2],
    [14, "恋のビギナーなんです(T_T) ～TV-SIZE", "山口理恵", 1],
]
links = ["https://beta.musicbrainz.org/release/0311ff4d-e16a-4ec2-99f6-9a749c16901d", "https://vgmdb.net/album/33104"]

[6dc8a701568414e43aaa5ebe6b07cfe9]
catalognumber = "VTCL-60310~1"
date = "2012-07-04"
album = "TVアニメーション「これはゾンビですか? オブ・ザ・デッド」 めっちゃフェスティボー! 公式ガイドCD〜つまり歌モノ全部と2期のBGM入り2枚組BEST Original Soundtrack, Talk"
tracks = [
    [1, "めっちゃサントラ講座1", "柿島伸次", 1],
    [2, "M56B", "柿島伸次", 1],
    [3, "M56A", "柿島伸次", 1],
    [4, "めっちゃサントラ講座2", "柿島伸次", 1],
    [5, "M57", "柿島伸次", 1],
    [6, "M61", "柿島伸次", 1],
    [7, "M62", "柿島伸次", 1],
    [8, "めっちゃサントラ講座3", "柿島伸次", 1],
    [9, "M65A", "柿島伸次", 1],
    [10, "M65B", "柿島伸次", 1],
    [11, "めっちゃサントラ講座4", "柿島伸次", 1],
    [12, "M59", "柿島伸次", 1],
    [13, "M63", "柿島伸次", 1],
    [14, "M66", "柿島伸次", 1],
    [15, "めっちゃサントラ講座5", "柿島伸次", 1],
    [16, "M58", "柿島伸次", 1],
    [17, "M59B", "柿島伸次", 1],
    [18, "めっちゃサントラ講座6", "柿島伸次", 1],
    [19, "M64", "柿島伸次", 1],
    [20, "M67", "柿島伸次", 1],
    [21, "めっちゃサントラ講座7", "柿島伸次", 1],
    [22, "越冬サントラ海峡 (M60)", "柿島伸次", 1],
    [23, "M68", "柿島伸次", 1],
]
links = ["https://beta.musicbrainz.org/release/0311ff4d-e16a-4ec2-99f6-9a749c16901d", "https://vgmdb.net/album/33104"]

[e10fe29e0caa66a47b70d5ec42b7bc60]
catalognumber = "TUHA-003"
date = "2012-08-11"
album = "fromage / 葉月ゆら+月子(La Bella Luna)"
tracks = [
    [1, "流星センセーション", "葉月ゆら & 月子", 0],
    [2, "ライオン", "葉月ゆら & 月子", 0],
    [3, "緋色の空", "葉月ゆら & 月子", 0],
    [4, "BREEZE", "葉月ゆら & 月子", 0],
    [5, "恋のビギナーなんです（Ｔ＿Ｔ）", "葉月ゆら & 月子", 1],
    [6, "アンインストール", "葉月ゆら & 月子", 0],
    [7, "Rainbow", "葉月ゆら & 月子", 0],
    [8, "AGAPE", "葉月ゆら & 月子", 0],
    [9, "月影ジェネレーション", "葉月ゆら & 月子", 0],
    [10, "ゆらと月子のおしゃべり", "葉月ゆら & 月子", 0],
    [11, "推定可憐♪魔法少女", "葉月ゆら & 月子", 0],
]
links = ["https://beta.musicbrainz.org/release/e5b35a81-219c-4f52-ae6b-5c3f3ff5f1ff", "https://vgmdb.net/album/74642"]

[c23a77f7673eaaa0b9555cad3c14eb4d]
catalognumber = "VTZL-67"
date = "2013-08-21"
album = "Hat Trick / 野水いおり Disc 1 (CD) [VTCL-60355]"
tracks = [
    [1, "h@trick.", "野水いおり", 0],
    [2, "小さな恋のメロディ", "野水いおり", 0],
    [3, "*** パショナート", "野水いおり", 1],
    [4, "WISH", "野水いおり", 0],
    [5, "SAVE MY HEART", "野水いおり", 0],
    [6, "MICRO DISTANCE", "野水いおり", 0],
    [7, "君と永遠に同じ夢を見る", "野水いおり", 0],
    [8, "サイレン", "野水いおり", 0],
    [9, "BREATHLESS", "野水いおり", 0],
    [10, "ストロベリーレイン", "野水いおり", 0],
    [11, "Signalize", "野水いおり", 1],
    [12, "SAVE THE WORLD", "野水いおり", 0],
    [13, "Black † White", "野水いおり", 0],
]
links = ["https://beta.musicbrainz.org/release/799fff02-dfa6-4363-9b50-473076f36768", "https://vgmdb.net/album/41253"]

[7ca93a98e110a388d00c3a2e93a009e9]
catalognumber = "VTZL-67"
date = "2013-08-21"
album = "Hat Trick / 野水いおり Disc 2 (DVD) [VTBY-79]"
tracks = [
    [1, "h@trick. (Music Video)", "", 0],
    [2, "*** パショナート (Music Video)", "", 1],
    [3, "魔・カ・セ・テ Tonight (Music Video)", "", 1],
    [4, "Black † White ～1st ワンマンライブ「Signalize」(2013.1.6 @ 新宿FACE)より", "", 0],
    [5, "魔・カ・セ・テ Tonight (アンコールVer.) ～1st ワンマンライブ「Signalize」(2013.1.6 @ 新宿FACE)より", "", 1],
]
links = ["https://vgmdb.net/album/41253"]

[1d75d257a92c943bf0a166173e8b2d10]
catalognumber = "VTCL-60355"
date = "2013-08-21"
album = "Hat Trick / 野水いおり"
tracks = [
    [1, "h@trick.", "野水いおり", 0],
    [2, "小さな恋のメロディ", "野水いおり", 0],
    [3, "*** パショナート", "野水いおり", 1],
    [4, "WISH", "野水いおり", 0],
    [5, "SAVE MY HEART", "野水いおり", 0],
    [6, "MICRO DISTANCE", "野水いおり", 0],
    [7, "君と永遠に同じ夢を見る", "野水いおり", 0],
    [8, "サイレン", "野水いおり", 0],
    [9, "BREATHLESS", "野水いおり", 0],
    [10, "ストロベリーレイン", "野水いおり", 0],
    [11, "Signalize", "野水いおり", 1],
    [12, "SAVE THE WORLD", "野水いおり", 0],
    [13, "Black † White", "野水いおり", 0],
]
links = ["https://beta.musicbrainz.org/release/799fff02-dfa6-4363-9b50-473076f36768", "https://vgmdb.net/album/41252"]

[305caa3532ee951070d2b10ca35b6660]
catalognumber = "BRMM-10868"
date = "2025-01-15"
album = "-未来- / 燐舞曲 [完全受注生産特装盤] Vocal"
tracks = [
    [1, "ラストソング", "燐舞曲", 0],
    [2, "「花の手錠と魔物の箱庭」", "燐舞曲", 0],
    [3, "カレンデュラ", "燐舞曲", 0],
    [4, "クライノイド", "燐舞曲", 0],
    [5, "群青のフローセカ", "燐舞曲", 0],
    [6, "BLACK LOTUS", "燐舞曲", 0],
    [7, "-World Etude-", "燐舞曲", 0],
    [8, "ニルヴァナ", "燐舞曲", 0],
    [9, "ARCANA", "燐舞曲", 0],
    [10, "夜想曲", "燐舞曲", 0],
    [11, "夢想曲 -Träumerei-", "燐舞曲", 0],
    [12, "雨音", "燐舞曲", 0],
]
links = ["https://beta.musicbrainz.org/release/a5b5f480-487f-4c84-85f6-af99032c4c5e", "https://vgmdb.net/album/143411"]

[55a28c019c652a610d8f2f3d4a4f4abc]
catalognumber = "BRMM-10868"
date = "2025-01-15"
album = "-未来- / 燐舞曲 [完全受注生産特装盤] Arrangement, Vocal"
tracks = [
    [1, "神蕾-シン・ライ-", "燐舞曲", 0],
    [2, "昊天 -koten-", "燐舞曲", 0],
    [3, "Horizontal Oath", "燐舞曲", 0],
    [4, "[Re] termination", "燐舞曲", 0],
    [5, "prayer[s]", "燐舞曲", 0],
    [6, "瞬動-movement- / [silence] / prayer(葵依Ver)", "燐舞曲 / 三宅葵依(CV:つんこ)", 0],
    [7, "暗黒の翼", "青柳椿(CV:加藤里保菜)", 0],
    [8, "ツキミソウ", "月見山渚(CV:大塚紗英)", 0],
    [9, "魔・カ・セ・テ Tonight", "矢野緋彩(CV:もものはるな)", 1],
    [10, "カタオモイ", "三宅葵依(CV:つんこ)", 0],
]
links = ["https://beta.musicbrainz.org/release/a5b5f480-487f-4c84-85f6-af99032c4c5e", "https://vgmdb.net/album/143411"]

[3b79441e9c4e0f8471a9ac12c2c8f8e1]
catalognumber = "BRMM-10868"
date = "2025-01-15"
album = "-未来- / 燐舞曲 [完全受注生産特装盤] Vocal, Live Event"
tracks = [
    [1, "群青のフローセカ／2nd LIVE「-邂逅-/-観想-」昼公演", "", 0],
    [2, "カレンデュラ（short edit）／D4DJ D4 FES. LIVE -ALL IN- DAY1", "", 0],
    [3, "Horizontal Oath／Merm4id×燐舞曲 合同LIVE「FAKE OFF」夜公演", "", 0],
    [4, "瞬動-movement-／3rd LIVE「-Maria-」昼公演", "", 0],
    [5, "BLACK LOTUS／3rd LIVE「-Maria-」昼公演", "", 0],
    [6, "ARCANA／4th LIVE「雨音の鮮花」夜公演", "", 0],
    [7, "雨音／4th LIVE「雨音の鮮花」夜公演", "", 0],
    [8, "夢想曲 -Träumerei-／Merm4id×燐舞曲 2nd LIVE「VERSUS」夜公演", "", 0],
]
links = ["https://vgmdb.net/album/143411"]

[f4964a249cb91921b5a5912b6842f3bf]
catalognumber = "BRMM-10868"
date = "2025-01-15"
album = "-未来- / 燐舞曲 [完全受注生産特装盤] Live Event, Video"
tracks = [
    [1, "燐舞曲 4th LIVE 雨音の鮮花 夜公演", "", 0],
    [2, "Merm4id×燐舞曲 2nd LIVE「VERSUS」夜公演", "", 0],
]
links = ["https://vgmdb.net/album/143411"]

[f35b3fc68f126a12c23e03f5ee7df93a]
catalognumber = "BRMM-10869"
date = "2025-01-15"
album = "-未来- / 燐舞曲 Disc 1"
tracks = [
    [1, "ラストソング", "燐舞曲", 0],
    [2, "「花の手錠と魔物の箱庭」", "燐舞曲", 0],
    [3, "カレンデュラ", "燐舞曲", 0],
    [4, "クライノイド", "燐舞曲", 0],
    [5, "群青のフローセカ", "燐舞曲", 0],
    [6, "BLACK LOTUS", "燐舞曲", 0],
    [7, "-World Etude-", "燐舞曲", 0],
    [8, "ニルヴァナ", "燐舞曲", 0],
    [9, "ARCANA", "燐舞曲", 0],
    [10, "夜想曲", "燐舞曲", 0],
    [11, "夢想曲 -Träumerei-", "燐舞曲", 0],
    [12, "雨音", "燐舞曲", 0],
]
links = ["https://beta.musicbrainz.org/release/a5b5f480-487f-4c84-85f6-af99032c4c5e", "https://vgmdb.net/album/143410"]

[57f764198497a4cd8fd8bdb6a900b256]
catalognumber = "BRMM-10869"
date = "2025-01-15"
album = "-未来- / 燐舞曲 Disc 2"
tracks = [
    [1, "神蕾-シン・ライ-", "燐舞曲", 0],
    [2, "昊天 -koten-", "燐舞曲", 0],
    [3, "Horizontal Oath", "燐舞曲", 0],
    [4, "[Re] termination", "燐舞曲", 0],
    [5, "prayer[s]", "燐舞曲", 0],
    [6, "瞬動-movement- / [silence] / prayer(葵依Ver)", "燐舞曲 / 三宅葵依(CV:つんこ)", 0],
    [7, "暗黒の翼", "青柳椿(CV:加藤里保菜)", 0],
    [8, "ツキミソウ", "月見山渚(CV:大塚紗英)", 0],
    [9, "魔・カ・セ・テ Tonight", "矢野緋彩(CV:もものはるな)", 1],
    [10, "カタオモイ", "三宅葵依(CV:つんこ)", 0],
]
links = ["https://beta.musicbrainz.org/release/a5b5f480-487f-4c84-85f6-af99032c4c5e", "https://vgmdb.net/album/143410"]
