[224c1dc8e38267478f8fdd4d5623d55d]
catalognumber = "ZMCZ-8038"
date = "2012-08-29"
album = "TVアニメ「さくら荘のペットな彼女」スターターCD BOX"
tracks = [
    [1, "なchuラル", "椎名ましろ (茅野愛衣)", 1],
    [2, "あなたがつないで", "椎名ましろ (茅野愛衣)", 1],
    [3, "なchuラル (Instrumental)", "椎名ましろ (茅野愛衣)", 1],
    [4, "あなたがつないで (Instrumental)", "椎名ましろ (茅野愛衣)", 1],
]
links = ["https://beta.musicbrainz.org/release/c55ab94c-48d9-4e58-a7ff-331af5b5f38a", "https://vgmdb.net/album/33553"]

[b2b93d848a965dd72707eb93f9767477]
catalognumber = "ZMCZ-8232"
date = "2012-11-21"
album = "DAYS of DASH / 鈴木このみ"
tracks = [
    [1, "DAYS of DASH", "鈴木このみ", 1],
    [2, "Fly to the stars", "鈴木このみ", 1],
    [3, "DAYS of DASH (Instrumental)", "鈴木このみ", 1],
    [4, "Fly to the stars (Instrumental)", "鈴木このみ", 1],
]
links = ["https://beta.musicbrainz.org/release/c6be36b7-b936-418f-a8d5-79d631957c31", "https://vgmdb.net/album/35016"]

[38295999e005d1a965dc580f7e5adae2]
catalognumber = "ZMCZ-8231"
date = "2012-11-21"
album = "君が夢を連れてきた / ペットな彼女たち"
tracks = [
    [1, "君が夢を連れてきた", "ペットな彼女たち", 2],
    [2, "君が夢を連れてきた WHITE Ver.", "ペットな彼女たち", 1],
    [3, "君が夢を連れてきた (Instrumental)", "ペットな彼女たち", 1],
    [4, "君が夢を連れてきた WHITE Ver. (Instrumental)", "ペットな彼女たち", 1],
]
links = ["https://beta.musicbrainz.org/release/5f273c38-8d2d-4c68-983d-d67a04ec4e26", "https://vgmdb.net/album/35015"]

[a1037e9037d6997face2e41ea2cf149c]
catalognumber = "TGCS-7325"
date = "2013-01-30"
album = "さくら荘のペットな彼女 スペシャルDisc Vol.1"
tracks = [
    [1, "なんで? なんで? なんで?", "椎名ましろ(茅野愛衣)", 1],
    [2, "なんで? なんで? なんで? (Instrumental)", "椎名ましろ(茅野愛衣)", 1],
]
links = ["https://beta.musicbrainz.org/release/a72b32fc-c41d-4d2c-b7c2-6857267202f3", "https://vgmdb.net/album/35760"]

[4a25ad9221753a412d4605fc0d06d935]
catalognumber = "MFCZ-1025"
date = "2013-01-30"
album = "さくら荘のペットな彼女 ドラマCD 第1巻"
tracks = [
    [1, "祭り囃子と金魚 その1", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
    [2, "祭り囃子と金魚 その2", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
    [3, "祭り囃子と金魚 その3", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
    [4, "スイコーの不思議な夜 その1", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
    [5, "スイコーの不思議な夜 その2", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
    [6, "スイコーの不思議な夜 その3", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
    [7, "キャストトーク", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、千石 千尋(CV:豊口めぐみ)、メイド(CV:堀江由衣)、白山 小春(CV:高橋美佳子)", 1],
]
links = ["https://beta.musicbrainz.org/release/d103191c-25aa-473a-8190-eeded7ff94c0", "https://vgmdb.net/album/45226"]

[ea8ccccb69712749a77d9452f2b89c5c]
catalognumber = "TGCS-7327"
date = "2013-02-27"
album = "さくら荘のペットな彼女 スペシャルDisc Vol.2 Soundtrack①"
tracks = [
    [1, "おはよー", "林有三", 1],
    [2, "起きろ、椎名", "林有三", 1],
    [3, "着替えは?", "林有三", 1],
    [4, "服をきろ、椎名", "林有三", 1],
    [5, "なあに、空太", "林有三", 1],
    [6, "ぱんつは?", "林有三", 1],
    [7, "ごはんできたよー", "林有三", 1],
    [8, "いってきまーす", "林有三", 1],
    [9, "水明芸術大学付属高校、通称スイコー", "林有三", 1],
    [10, "ねーねーこーはいくん!", "林有三", 1],
    [11, "一大事だよこーはいくん!", "林有三", 1],
    [12, "年中無休ましろ当番", "林有三", 1],
    [13, "やるったらやるんだもーん!", "林有三", 1],
    [14, "椎名さん?", "林有三", 1],
    [15, "どーせ神田くんは", "林有三", 1],
    [16, "龍之介さまはお忙しいのです", "林有三", 1],
    [17, "ウイルスとか送っちゃうぞ(笑)", "林有三", 1],
    [18, "千石千尋(29歳と27ヶ月)", "林有三", 1],
    [19, "芸術はバクハツ", "林有三", 1],
    [20, "下心満載だよ!", "林有三", 1],
    [21, "じーーーーーーーーーーん!", "林有三", 1],
    [22, "ちょっとまて、椎名", "林有三", 1],
    [23, "朝はもう来ないわ", "林有三", 1],
    [24, "一致団結", "林有三", 1],
    [25, "衝突", "林有三", 1],
    [26, "けんかのまま", "林有三", 1],
    [27, "またあした", "林有三", 1],
    [28, "ただいま", "林有三", 1],
]
links = ["https://beta.musicbrainz.org/release/0a0e8925-d613-480d-a06d-84df1fd26bd0", "https://vgmdb.net/album/35761"]

[4504f11c21826ff65e59c790d5898aef]
catalognumber = "MFCZ-1026"
date = "2013-02-27"
album = "さくら荘のペットな彼女 ドラマCD 第2巻"
tracks = [
    [1, "パンツが…欲しいです その1", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、", 1],
    [2, "パンツが…欲しいです その2", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、", 1],
    [3, "空太はヘタなのね その1", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、", 1],
    [4, "空太はヘタなのね その2", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、", 1],
    [5, "空太はヘタなのね その3", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、", 1],
    [6, "キャストトーク", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、", 1],
]
links = ["https://beta.musicbrainz.org/release/f1fcf102-f456-40b9-8caf-f94eaae1145e", "https://vgmdb.net/album/45248"]

[514086b69e8ce33cd62943af3aa8c95e]
catalognumber = "ZMCZ-8234"
date = "2013-02-27"
album = "Prime number～君と出会える日～ / 大倉明日香"
tracks = [
    [1, "Prime number 〜君と出会える日〜", "大倉明日香", 1],
    [2, "Prime number 〜君と出会える日〜 Blue Sky VER.", "大倉明日香", 1],
    [3, "Prime number 〜君と出会える日〜 (Instrumental)", "大倉明日香", 1],
    [4, "Prime number 〜君と出会える日〜 Blue Sky VER. (Instrumental)", "大倉明日香", 1],
]
links = ["https://beta.musicbrainz.org/release/567d132b-bc2f-49f9-abbb-91746a17f58b", "https://vgmdb.net/album/37067"]

[f1045363a248cc3094aa692b3eea7834]
catalognumber = "ZMCZ-8233"
date = "2013-02-27"
album = "夢の続き / 鈴木このみ"
tracks = [
    [1, "夢の続き", "鈴木このみ", 1],
    [2, "囚人 -Paradox 2013-", "鈴木このみ", 1],
    [3, "夢の続き (Instrumental)", "鈴木このみ", 1],
    [4, "囚人 -Paradox 2013- (Instrumental)", "鈴木このみ", 1],
]
links = ["https://beta.musicbrainz.org/release/55e52e4d-3eb8-485d-a201-9bf42605cc45", "https://vgmdb.net/album/37066"]

[4c23f5d9296007f4c66489dabe048f5d]
catalognumber = "TGCS-7329"
date = "2013-03-27"
album = "さくら荘のペットな彼女 スペシャルDisc Vol.3"
tracks = [
    [1, "I call your name again", "青山七海 (CV:中津真莉子)", 1],
    [2, "I call your name again Instrumental ver.", "青山七海 (CV:中津真莉子)", 1],
]
links = ["https://beta.musicbrainz.org/release/73f9575b-ced6-47a6-9005-6ecea5d5ad42", "https://vgmdb.net/album/35762"]

[a4ec73895d1c70a2f237d2800616523f]
catalognumber = "MFCZ-1027"
date = "2013-04-24"
album = "さくら荘のペットな彼女 ドラマCD 第3巻"
tracks = [
    [1, "二度あることは三度ある!? その1", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、神田 優子(CV:小倉唯)", 1],
    [2, "二度あることは三度ある!? その2", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、神田 優子(CV:小倉唯)", 1],
    [3, "二度あることは三度ある!? その3", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、神田 優子(CV:小倉唯)", 1],
    [4, "二度あることは三度ある!? その4", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、神田 優子(CV:小倉唯)", 1],
    [5, "キャストトーク", "神田 空太(CV:松岡禎丞)、椎名ましろ(CV:茅野愛衣)、青山七海(CV:中津真莉子)、上井草 美咲(CV:高森奈津美)、三鷹 仁(CV:櫻井孝宏)、赤坂 龍之介(CV:堀江由衣)、メイド(CV:堀江由衣)、神田 優子(CV:小倉唯)", 1],
]
links = ["https://beta.musicbrainz.org/release/57bdb802-c16d-442a-878d-cf61f5b352fd", "https://vgmdb.net/album/45249"]

[0d72de2bb50500b71c443aa9b60761b0]
catalognumber = "TGCS-7333"
date = "2013-05-29"
album = "さくら荘のペットな彼女 スペシャルDisc Vol.5"
tracks = [
    [1, "ワイルドにZooっきゅ〜ん!", "上井草 美咲(CV:高森奈津美)", 1],
    [2, "ワイルドにZooっきゅ〜ん! Instrumental ver.", "上井草 美咲(CV:高森奈津美)", 1],
]
links = ["https://beta.musicbrainz.org/release/7990c495-76da-4c3d-a35a-f28b009d73e7", "https://vgmdb.net/album/35763"]

[fc7b939df24fe04f94bb89e6b67517a8]
catalognumber = "TGCS-7335"
date = "2013-06-26"
album = "さくら荘のペットな彼女 スペシャルDisc Vol.6"
tracks = [
    [1, "「メイドちゃんより。」", "メイドちゃん (堀江由衣)", 1],
    [2, "「メイドちゃんより。」 Instrumental ver.", "メイドちゃん (堀江由衣)", 1],
]
links = ["https://beta.musicbrainz.org/release/b4350f76-1ecf-45f6-8d36-24c8b63d21bb", "https://vgmdb.net/album/35764"]

[cf1adaae49fd21cc6d2bb9a797bf4c84]
catalognumber = "TGCS-7337"
date = "2013-07-24"
album = "さくら荘のペットな彼女 スペシャルDisc Vol.7 Soundtrack②"
tracks = [
    [1, "銀河猫にゃぼろんのテーマ", "佐宗綾子", 1],
    [2, "VSニャンゴロー星人", "細江慎治", 1],
    [3, "猫背のアイン", "細江慎治", 1],
    [4, "ミートボールビーム!", "細江慎治", 1],
    [5, "美しき愛の星よ、永遠に", "細江慎治", 1],
    [6, "水明芸術大学付属高等学校 校歌", "水明高校 生徒一同", 1],
    [7, "誰もいない朝", "林有三", 1],
    [8, "まっしろなキャンバス", "林有三", 1],
    [9, "ねえ、空太", "林有三", 1],
    [10, "絵を描いてきたの", "林有三", 1],
    [11, "私は空太も傷つけた?", "林有三", 1],
    [12, "DAYS of DASH piano arr.", "林有三", 1],
    [13, "頑張れてるかな", "林有三", 1],
    [14, "天才と凡人", "林有三", 1],
    [15, "天才", "林有三", 1],
    [16, "自分の居場所くらい、自分で決めろ", "林有三", 1],
    [17, "私の中から出ていって", "林有三", 1],
    [18, "汚れたキャンバス", "林有三", 1],
    [19, "君が夢を連れてきた guitar arr.", "林有三", 1],
    [20, "友達", "林有三", 1],
    [21, "頑張ってみるよ", "林有三", 1],
    [22, "いっぱい、ありがとう", "林有三", 1],
    [23, "いつも見てるよ", "林有三", 1],
    [24, "なまえを呼んで", "林有三", 1],
    [25, "今日の日はさようなら", "水明高校 生徒一同", 1],
]
links = ["https://beta.musicbrainz.org/release/3a369078-19fb-4f85-a75e-d2213e128e5a", "https://vgmdb.net/album/35765"]
