[43831b441fc31e707f0881764cc5cd81]
catalognumber = "NMAX-1191"
date = "2015-06-18"
album = "耳の中へ / イヤホンズ"
tracks = [
    [1, "耳の中へ", "イヤホンズ", 2],
    [2, "耳の中へ (off vocal ver.)", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/15185f6e-aeb6-4aab-8aeb-0fdce73fcc5b", "https://vgmdb.net/album/53991"]

[91f212de73931cc9d5dfc38582cba4ec]
catalognumber = "KIZM-347~8"
date = "2015-07-22"
album = "それが声優!/あなたのお耳にプラグイン! / イヤホンズ [イヤホンズ盤] Disc 1 (CD) [KIZM-347]"
tracks = [
    [1, "それが声優!", "イヤホンズ", 1],
    [2, "あなたのお耳にプラグイン!", "イヤホンズ", 1],
    [3, "それが声優! (off vocal ver.)", "イヤホンズ", 1],
    [4, "あなたのお耳にプラグイン! (off vocal ver.)", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/af4b39f1-d4ae-47a9-b000-8410cbc105be", "https://vgmdb.net/album/53041"]

[fe65ea0db2b011bb3755c4fb9c857760]
catalognumber = "KIZM-347~8"
date = "2015-07-22"
album = "それが声優!/あなたのお耳にプラグイン! / イヤホンズ [イヤホンズ盤] Disc 2 (DVD) [KIZM-348]"
tracks = [
    [1, "それが声優! (MUSIC VIDEO)", "イヤホンズ", 1],
    [2, "MVメイキング", "イヤホンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/af4b39f1-d4ae-47a9-b000-8410cbc105be", "https://vgmdb.net/album/53041"]

[8fbdce159d170ff7d82a81bd0a22f5c7]
catalognumber = "KICM-1616"
date = "2015-07-22"
album = "それが声優!/あなたのお耳にプラグイン! / イヤホンズ [それが声優! 盤]"
tracks = [
    [1, "それが声優!", "イヤホンズ", 1],
    [2, "あなたのお耳にプラグイン!", "イヤホンズ", 1],
    [3, "背中のWING", "イヤホンズ", 1],
    [4, "それが声優! (off vocal ver.)", "イヤホンズ", 1],
    [5, "あなたのお耳にプラグイン! (off vocal ver.)", "イヤホンズ", 1],
    [6, "背中のWING (off vocal ver.)", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/e6c47995-c50f-474d-882a-6d1d60276c34", "https://vgmdb.net/album/53040"]

[237d940e8a1c15551da559fd748b750a]
catalognumber = "NKCD-6709"
date = "2015-08-14"
album = "それが声優! E.P.スピンオフムービー主題歌集"
tracks = [
    [1, "愛と絶望のイデア", "AKINO from bless4", 1],
    [2, "ヒーローじゃなくていい", "イヤホンズ", 1],
    [3, "この世はスパイラル！", "釘宮理恵", 1],
    [4, "愛と絶望のイデア(off vocal ver.)", "AKINO", 1],
    [5, "ヒーローじゃなくていい(off vocal ver.)", "堀江由衣", 1],
    [6, "この世はスパイラル！(off vocal ver.)", "釘宮理恵", 1],
]
links = ["https://beta.musicbrainz.org/release/5efc7f3e-d371-4db4-a0e9-7cb4c9c19d80", "https://vgmdb.net/album/56047"]

[5112082fe21b82bb87433a20bbdad238]
catalognumber = "SSX-10378"
date = "2015-09-30"
album = "それが声優! サウンドトラック Vol.1"
tracks = [
    [1, "1日のはじまり", "橋本由香利", 1],
    [2, "ホームはこの家の外に作ってみせる", "橋本由香利", 1],
    [3, "アフレコ現場", "橋本由香利", 1],
    [4, "フタフタのテーマ", "橋本由香利", 1],
    [5, "双葉といちご", "橋本由香利", 1],
    [6, "現役中学生声優", "橋本由香利", 1],
    [7, "アフレコスタジオ調整室", "橋本由香利", 1],
    [8, "アフレコスタジオブース", "橋本由香利", 1],
    [9, "「こぼし」って何?", "橋本由香利", 1],
    [10, "気合いを入れて", "橋本由香利", 1],
    [11, "役作りの成果", "橋本由香利", 1],
    [12, "普通って何!?", "橋本由香利", 1],
    [13, "モノローグとセリフ", "橋本由香利", 1],
    [14, "声優失格", "橋本由香利", 1],
    [15, "声のお仕事", "橋本由香利", 1],
    [16, "いちご星のプリンセス", "橋本由香利", 1],
    [17, "お仕事があるじゃないですか", "橋本由香利", 1],
    [18, "紺野さんのテーマ", "橋本由香利", 1],
    [19, "オーディション", "橋本由香利", 1],
    [20, "WEBラジオって怖い", "橋本由香利", 1],
    [21, "ボサツオンオープニング", "橋本由香利", 1],
    [22, "ボサツオンのテーマ", "橋本由香利", 1],
    [23, "最後のアフレコ", "橋本由香利", 1],
    [24, "優しい先輩", "橋本由香利", 1],
    [25, "Track 25", "橋本由香利", 1],
]
links = ["https://beta.musicbrainz.org/release/03765cfc-c1e6-4711-984a-3352c8da9d1a", "https://vgmdb.net/album/53788"]

[ee22e7346d17fefc744c023a6de23a8b]
catalognumber = "KICM-1628"
date = "2015-09-30"
album = "光の先へ / イヤホンズ"
tracks = [
    [1, "光の先へ", "イヤホンズ", 1],
    [2, "ヒーローじゃなくていい", "イヤホンズ", 1],
    [3, "Love Power", "イヤホンズ", 1],
    [4, "光の先へ (off vocal ver.)", "イヤホンズ", 1],
    [5, "ヒーローじゃなくていい (off vocal ver.)", "イヤホンズ", 1],
    [6, "Love Power (off vocal ver.)", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/61f0a961-ac8b-4cfd-9caa-daffbad13a33", "https://vgmdb.net/album/54109"]

[c7f7a464eea177f2b24424a934a08d94]
catalognumber = "SSX-10379"
date = "2015-10-28"
album = "それが声優! ラジオCD Vol.1 -イヤホンズのあなたのお耳にプラグイン!-"
tracks = [
    [1, "第1回", "", 1],
    [2, "第2回", "", 1],
    [3, "第3回", "", 1],
    [4, "第4回", "", 1],
    [5, "第5回", "", 1],
    [6, "第6回", "", 1],
]
links = ["https://vgmdb.net/album/120188"]

[5c2163e78bd2e405d6c58d42a9d68bef]
catalognumber = "KICS-3325"
date = "2015-11-21"
album = "MIRACLE MYSTERY TOUR / イヤホンズ"
tracks = [
    [1, "overture", "イヤホンズ", 0],
    [2, "それが声優!", "イヤホンズ", 1],
    [3, "成長!全力シンデレラ", "イヤホンズ", 0],
    [4, "耳の中へ", "イヤホンズ", 1],
    [5, "Magic of love", "イヤホンズ", 0],
    [6, "ススメ!音羽少女隊", "イヤホンズ", 0],
    [7, "私でキマリ☆", "イヤホンズ", 0],
    [8, "280秒間世界一周 〜幸せのイヤホンを探して〜", "イヤホンズ", 0],
    [9, "勇者へのミサ・ブレイヴィス", "イヤホンズ", 0],
    [10, "プロ根! 〜地獄の一丁目特訓!の巻〜", "イヤホンズ", 0],
    [11, "お買物めっちゃええねんチャンネルのうた", "イヤホンズ", 0],
    [12, "光の先へ", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/50909b7e-d901-4b12-9175-888f226fcec1", "https://vgmdb.net/album/56042"]

[8177a4a8350d2c13d26a2698abff9f42]
catalognumber = "KICS-93325"
date = "2015-11-21"
album = "MIRACLE MYSTERY TOUR / イヤホンズ [初回限定盤] Vocal"
tracks = [
    [1, "overture", "イヤホンズ", 0],
    [2, "それが声優！", "イヤホンズ", 1],
    [3, "成長！全力シンデレラ", "イヤホンズ", 0],
    [4, "耳の中へ", "イヤホンズ", 1],
    [5, "Magic of love", "イヤホンズ", 0],
    [6, "ススメ！音羽少女隊", "イヤホンズ", 0],
    [7, "私でキマリ☆", "イヤホンズ", 0],
    [8, "280秒間世界一周 〜幸せのイヤホンを探して〜", "イヤホンズ", 0],
    [9, "勇者へのミサ・ブレイヴィス", "イヤホンズ", 0],
    [10, "プロ根！ 〜地獄の一丁目特訓！の巻〜", "イヤホンズ", 0],
    [11, "お買物めっちゃええねんチャンネルのうた", "イヤホンズ", 0],
    [12, "光の先へ", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/4f3a00d9-55ae-4370-b3e5-a4c28813266f", "https://vgmdb.net/album/56043"]

[91146c7de6e67ea925b072d909851a20]
catalognumber = "KICS-93325"
date = "2015-11-21"
album = "MIRACLE MYSTERY TOUR / イヤホンズ [初回限定盤] Vocal, Video"
tracks = [
    [1, "成長！全力シンデレラ (MUSIC VIDEO)", "イヤホンズ", 0],
    [2, "3rd Sg「光の先へ」ダイジェストトレーラー", "イヤホンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/4f3a00d9-55ae-4370-b3e5-a4c28813266f", "https://vgmdb.net/album/56043"]

[931010e397ee810c1a987221371f906c]
catalognumber = "SSX-10380"
date = "2015-11-25"
album = "それが声優! サウンドトラック Vol.2"
tracks = [
    [1, "双葉のライブ", "橋本由香利", 1],
    [2, "ステージから見ているもの", "橋本由香利", 1],
    [3, "クロネコ・オブ・エターニャ2のテーマ", "橋本由香利", 1],
    [4, "突然の雨", "橋本由香利", 1],
    [5, "ユマの役は…", "橋本由香利", 1],
    [6, "それが声優! (ピアノVer.)", "橋本由香利", 1],
    [7, "仕事を終えて", "橋本由香利", 1],
    [8, "マネージャーの仕事", "橋本由香利", 1],
    [9, "鈴とサヨ", "橋本由香利", 1],
    [10, "迷ったことないですか?", "橋本由香利", 1],
    [11, "ずっと一緒だよ", "橋本由香利", 1],
    [12, "皆でビラ配り", "橋本由香利", 1],
    [13, "わたしたちのペース", "橋本由香利", 1],
    [14, "イヤホンズのテーマ", "橋本由香利", 1],
    [15, "ゾンビのおたけび", "橋本由香利", 1],
    [16, "ラジオジングル1", "橋本由香利", 1],
    [17, "ラジオジングル2", "橋本由香利", 1],
    [18, "ラジオジングル3", "橋本由香利", 1],
    [19, "それが声優!放送開始", "橋本由香利", 1],
    [20, "それが声優!放送開始 (オルゴールVer.)", "橋本由香利", 1],
    [21, "あなたのお耳にプラグイン! (トランペットVer.)", "橋本由香利", 1],
]
links = ["https://beta.musicbrainz.org/release/3c7dbab5-d7e1-4c35-b95d-ca202988ae5a", "https://vgmdb.net/album/55667"]

[483aaeaa1b6cb4a978c964743cdc3f1a]
catalognumber = "SSX-10381"
date = "2015-12-23"
album = "それが声優! ラジオCD Vol.2 -イヤホンズのあなたのお耳にプラグイン!-"
tracks = [
    [1, "第7回", "", 1],
    [2, "第8回", "", 1],
    [3, "第9回", "", 1],
    [4, "第10回", "", 1],
    [5, "第11回", "", 1],
    [6, "第12回", "", 1],
    [7, "第13回", "", 1],
]
links = ["https://vgmdb.net/album/120189"]

[2994c772f60468deaf729d3c1480f485]
catalognumber = "SSX-10382"
date = "2016-01-27"
album = "それが声優! ラジオCD Vol.3 -それが声優! Presents WEBラジオ! 総集編Vol.1-"
tracks = [
    [1, "(no title available)", "", 1],
]
links = ["https://vgmdb.net/album/120192"]

[974522d573cacdadcd0ba7e5b4b534de]
catalognumber = "SSX-10383"
date = "2016-02-24"
album = "それが声優! ラジオCD Vol.4 -それが声優! Presents WEBラジオ! 総集編Vol.2-"
tracks = [
    [1, "(no title available)", "", 1],
]
links = ["https://vgmdb.net/album/120193"]

[2eeca6707b536c55513437648dbc4535]
catalognumber = "N/A"
date = "2016-03-23"
album = "それが声優! Blu-ray全巻購入ゲーマーズ限定特典 イヤホンズオリジナルCD"
tracks = []
links = ["https://vgmdb.net/album/120196"]

[a3f7caacb0bb9853d83f79a9a3de59f9]
catalognumber = "SSX-10384"
date = "2016-03-23"
album = "あなたのお耳にプラグイン! 全13話コンプリートディスク"
tracks = [
    [1, "第1話ver.：リクエスト曲「残酷な天使のテーゼ」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [2, "第2話ver.：リクエスト曲「人として軸がぶれている」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [3, "第3話ver.：リクエスト曲「Endless Story」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [4, "第4話ver.：リクエスト曲「MOON PRIDE」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [5, "第5話ver.：リクエスト曲「Love Destiny」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [6, "第6話ver.：リクエスト曲「プレパレード」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [7, "第7話ver.：リクエスト曲「ETERNAL BLAZE」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [8, "第8話ver.：リクエスト曲「YOU GET TO BURNING」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [9, "第9話ver.：リクエスト曲「Get along」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [10, "第10話ver.：リクエスト曲「輪舞-revolution」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [11, "第11話ver.：リクエスト曲「ハッピー☆マテリアル」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [12, "第12話ver.：リクエスト曲「For フルーツバスケット」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
    [13, "第13話ver.：リクエスト曲「それが声優！」", "一ノ瀬 双葉、萌咲 いちご、小花 鈴", 1],
]
links = ["https://vgmdb.net/album/120194"]

[a8d09c69fcea670dfa29903e10a7f6d8]
catalognumber = "GCA-0060"
date = "2016-03-23"
album = "それが声優! Blu-ray全巻購入とらのあな限定特典 ラジオCDとらのあなver."
tracks = []
links = ["https://vgmdb.net/album/120197"]

[780053f175f98e634931f2e1ebf2306b]
catalognumber = "ANIM-3134"
date = "2016-03-23"
album = "それが声優! Blu-ray全巻購入アニメイト限定特典 ラジオCDアニメイトver."
tracks = []
links = ["https://vgmdb.net/album/120195"]

[6aeb6f00aa0714a4d29e84bd21fd5e62]
catalognumber = "KICS-93684"
date = "2018-03-14"
album = "Some Dreams / イヤホンズ Disc 1 [KICS-93684]"
tracks = [
    [1, "新次元航路", "イヤホンズ", 0],
    [2, "理想郷物語", "イヤホンズ", 0],
    [3, "一件落着ゴ用心", "イヤホンズ", 0],
    [4, "ミーチャイキュットンティーガプリウテグバンコ", "イヤホンズ", 0],
    [5, "あたしのなかのものがたり", "イヤホンズ", 0],
    [6, "Fuwa くちゃ Dreamer", "イヤホンズ", 0],
    [7, "予め失われた僕らのバラッド", "イヤホンズ", 0],
    [8, "ウィッチクラフト 《テオフィルの奇蹟》", "イヤホンズ", 0],
    [9, "Yummy Yummy Party", "イヤホンズ", 0],
    [10, "サンキトウセン!", "イヤホンズ", 0],
    [11, "ヨロコビノウタ", "イヤホンズ", 0],
    [12, "未来泥棒", "イヤホンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/ffa33608-bcbf-4f3e-841f-924afc648316", "https://vgmdb.net/album/76424"]

[52304ccf29cd73fb6abfc30e7d97a468]
catalognumber = "KICS-93684"
date = "2018-03-14"
album = "Some Dreams / イヤホンズ Disc 2 [SSX-10450]"
tracks = [
    [1, "イヤホンズのMusic Trip 01", "イヤホンズ", 0],
    [2, "残酷な天使のテーゼ", "イヤホンズ", 0],
    [3, "イヤホンズのMusic Trip 02", "イヤホンズ", 0],
    [4, "現象のブレイド", "大槻ケンヂとイヤホンズ", 0],
    [5, "イヤホンズのMusic Trip 03", "イヤホンズ", 0],
    [6, "乙女のポリシー", "石田燿子とイヤホンズ", 0],
    [7, "イヤホンズのMusic Trip 04", "イヤホンズ", 0],
    [8, "パラレルギャロップ", "イヤホンズ", 0],
    [9, "イヤホンズのMusic Trip 05", "イヤホンズ", 0],
    [10, "UNRULY COASTER", "イヤホンズ", 0],
    [11, "イヤホンズのMusic Trip 06", "イヤホンズ", 0],
    [12, "いーあるさんせっと", "イヤホンズ", 0],
    [13, "イヤホンズのMusic Trip 07", "イヤホンズ", 0],
    [14, "応援歌!", "イヤホンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/ffa33608-bcbf-4f3e-841f-924afc648316", "https://vgmdb.net/album/76424"]

[a7dd4fed60d39d627e4029570d812c6d]
catalognumber = "VTCL-60540~2"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 Disc 1 [VTCL-60540]"
tracks = [
    [1, "創聖のアクエリオン", "AKINO", 0],
    [2, "ニケ15歳", "AKINO", 0],
    [3, "荒野のヒース", "AKINO", 0],
    [4, "Go Tight!", "AKINO", 0],
    [5, "プライド〜嘆きの旅", "AKINO", 0],
    [6, "Genesis of Aquarion", "AKINO", 0],
    [7, "Genesis of LOVE〜愛の起源", "AKINO with bless4", 0],
    [8, "素足", "AKINO", 0],
    [9, "パラドキシカルZOO", "AKINO with bless4", 0],
    [10, "イヴの断片", "AKINO from bless4", 0],
    [11, "君の神話〜アクエリオン第二章", "AKINO with bless4", 0],
    [12, "月光シンフォニア", "AKINO & AIKI from bless4", 0],
    [13, "ZERO ゼロ", "AKINO from bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/438e0534-6c7c-4555-ab4c-44933103867c", "https://vgmdb.net/album/108533"]

[e19cc21ea8fdf02c8ec2cc42056d06f8]
catalognumber = "VTCL-60540~2"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 Disc 2 [VTCL-60541]"
tracks = [
    [1, "エクストラ・マジック・アワー", "AKINO with bless4", 0],
    [2, "Jet Coaster Ride", "AKINO with bless4", 0],
    [3, "海色", "AKINO from bless4", 0],
    [4, "The Ghost of You", "AKINO with bless4", 0],
    [5, "雪のように", "AKINO with bless4", 0],
    [6, "Let’s Fly", "AKINO with bless4", 0],
    [7, "EXTRA MAGIC HOUR [International Edition]", "AKINO with bless4", 0],
    [8, "Golden Life", "AKINO with bless4", 0],
    [9, "ドキドキするから", "AKINO with bless4", 0],
    [10, "cross the line", "AKINO with bless4", 0],
    [11, "I Got This", "AKINO with bless4", 0],
    [12, "OVERNIGHT REVOLUTION", "AKINO with bless4", 0],
    [13, "月のもう半分", "AIKI & AKINO from bless4", 0],
    [14, "月明かりのMonologue", "AKINO arai × AKINO from bless4", 0],
    [15, "Étoile de prière", "AKINO arai × AKINO from bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/438e0534-6c7c-4555-ab4c-44933103867c", "https://vgmdb.net/album/108533"]

[96557500aa374d85485ef2fed1b92128]
catalognumber = "VTCL-60540~2"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 Disc 3 [VTCL-60542]"
tracks = [
    [1, "Chance To Shine", "AKINO", 0],
    [2, "運命の前奏曲", "AKINO", 0],
    [3, "愛と絶望のイデア", "AKINO from bless4", 1],
    [4, "Chase the WAVE", "Tatsh feat. AKINO with bless4", 0],
    [5, "What Am I Fighting For", "AKINO with bless4", 0],
    [6, "シラカバの光", "AKINO with bless4", 0],
    [7, "運命のプロローグ", "王族BAND, AKINO from bless4", 0],
    [8, "The End begins", "AKINO with bless4", 0],
    [9, "Soccer Spirits", "AKINO with bless4", 0],
    [10, "your ears, our years", "AKINO with bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/438e0534-6c7c-4555-ab4c-44933103867c", "https://vgmdb.net/album/108533"]

[3d33f8f43b243767e3501a31e1c2cbc2]
catalognumber = "VTZL-181"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 [初回限定盤] Vocal Disc 1"
tracks = [
    [1, "創聖のアクエリオン", "AKINO", 0],
    [2, "ニケ15歳", "AKINO", 0],
    [3, "荒野のヒース", "AKINO", 0],
    [4, "Go Tight!", "AKINO", 0],
    [5, "プライド〜嘆きの旅", "AKINO", 0],
    [6, "Genesis of Aquarion", "AKINO", 0],
    [7, "Genesis of LOVE〜愛の起源", "AKINO with bless4", 0],
    [8, "素足", "AKINO", 0],
    [9, "パラドキシカルZOO", "AKINO with bless4", 0],
    [10, "イヴの断片", "AKINO from bless4", 0],
    [11, "君の神話〜アクエリオン第二章", "AKINO with bless4", 0],
    [12, "月光シンフォニア", "AKINO & AIKI from bless4", 0],
    [13, "ZERO ゼロ", "AKINO from bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/19783f22-e44c-4eca-ba1d-f954717936e8", "https://vgmdb.net/album/108534"]

[6218deb2f984e75d8530a98a81c65c53]
catalognumber = "VTZL-181"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 [初回限定盤] Vocal Disc 2"
tracks = [
    [1, "エクストラ・マジック・アワー", "AKINO with bless4", 0],
    [2, "Jet Coaster Ride", "AKINO with bless4", 0],
    [3, "海色", "AKINO from bless4", 0],
    [4, "The Ghost of You", "AKINO with bless4", 0],
    [5, "雪のように", "AKINO with bless4", 0],
    [6, "Let’s Fly", "AKINO with bless4", 0],
    [7, "EXTRA MAGIC HOUR [International Edition]", "AKINO with bless4", 0],
    [8, "Golden Life", "AKINO with bless4", 0],
    [9, "ドキドキするから", "AKINO with bless4", 0],
    [10, "cross the line", "AKINO with bless4", 0],
    [11, "I Got This", "AKINO with bless4", 0],
    [12, "OVERNIGHT REVOLUTION", "AKINO with bless4", 0],
    [13, "月のもう半分", "AIKI & AKINO from bless4", 0],
    [14, "月明かりのMonologue", "AKINO arai × AKINO from bless4", 0],
    [15, "Étoile de prière", "AKINO arai × AKINO from bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/19783f22-e44c-4eca-ba1d-f954717936e8", "https://vgmdb.net/album/108534"]

[32440c89ff6ce6faca69ca356cb92f54]
catalognumber = "VTZL-181"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 [初回限定盤] Vocal Disc 3"
tracks = [
    [1, "Chance To Shine", "AKINO", 0],
    [2, "運命の前奏曲", "AKINO", 0],
    [3, "愛と絶望のイデア", "AKINO from bless4", 1],
    [4, "Chase the WAVE", "Tatsh feat. AKINO with bless4", 0],
    [5, "What Am I Fighting For", "AKINO with bless4", 0],
    [6, "シラカバの光", "AKINO with bless4", 0],
    [7, "運命のプロローグ", "王族BAND, AKINO from bless4", 0],
    [8, "The End begins", "AKINO with bless4", 0],
    [9, "Soccer Spirits", "AKINO with bless4", 0],
    [10, "your ears, our years", "AKINO with bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/19783f22-e44c-4eca-ba1d-f954717936e8", "https://vgmdb.net/album/108534"]

[8832ab5925c4e0cc75928d421f4cd3d7]
catalognumber = "VTZL-181"
date = "2021-03-24"
album = "your ears, our years / AKINO from bless4 [初回限定盤] Vocal, Video"
tracks = [
    [1, "「創聖のアクエリオン」music video", "AKINO from bless4", 0],
    [2, "「cross the line」music video", "AKINO from bless4", 0],
]
links = ["https://beta.musicbrainz.org/release/19783f22-e44c-4eca-ba1d-f954717936e8", "https://vgmdb.net/album/108534"]

[bf3b9ebcca44064c176f50b99fb1e842]
catalognumber = "KIZX-499~500"
date = "2021-09-22"
album = "identity / イヤホンズ Disc 1 (Blu-ray) [KIZX-499]"
tracks = [
    [1, "はじめまして (Music Video)", "イヤホンズ", 0],
    [2, "Table Talk (長久友紀×あさのますみ)", "イヤホンズ", 0],
    [3, "Table Talk (高橋李依×あさのますみ)", "イヤホンズ", 0],
    [4, "Table Talk (高野麻里佳×あさのますみ)", "イヤホンズ", 0],
    [5, "それが声優!2021 (Music Trailer)", "イヤホンズ", 1],
]
links = ["https://beta.musicbrainz.org/release/d235991c-fdcd-499f-85c5-53ffce946eec", "https://vgmdb.net/album/115316"]

[55a1f07df1cc143e1fabc5bac8d72cde]
catalognumber = "KIZX-499~500"
date = "2021-09-22"
album = "identity / イヤホンズ Disc 2 (CD) [KIZX-500]"
tracks = [
    [1, "それが声優!2021", "イヤホンズ", 1],
    [2, "はじめまして", "イヤホンズ", 0],
    [3, "かなしみ", "イヤホンズ", 0],
    [4, "それが声優!2021 (off vocal ver.)", "イヤホンズ", 1],
    [5, "はじめまして (off vocal ver.)", "イヤホンズ", 0],
    [6, "かなしみ (off vocal ver.)", "イヤホンズ", 0],
]
links = ["https://beta.musicbrainz.org/release/d235991c-fdcd-499f-85c5-53ffce946eec", "https://vgmdb.net/album/115316"]
