[ef16a9ce41e961bf7ed83d62d5396855]
catalognumber = "DSP-01995"
date = "2013"
album = "デラ・モチマッヅィのうた"
tracks = [
    [1, "デラ・モチマッヅィのうた", "", 0],
]
links = ["https://vgmdb.net/album/108076"]

[647b60a48a486120da75e7d9b590917a]
catalognumber = "PCCG-70172"
date = "2013-01-25"
album = "ドラマチックマーケットライド / 北白川たまこ(CV: 洲崎 綾)"
tracks = [
    [1, "ドラマチックマーケットライド", "北白川たまこ(CV:洲崎綾)", 0],
    [2, "ともろう", "北白川たまこ(CV:洲崎綾)", 0],
    [3, "ドラマチックマーケットライド (Instrumental)", "北白川たまこ(CV:洲崎綾)", 0],
    [4, "ともろう (Instrumental)", "北白川たまこ(CV:洲崎綾)", 0],
]
links = ["https://beta.musicbrainz.org/release/2f1dcef3-45d3-4ed6-ac85-44c5a621a56d", "https://vgmdb.net/album/36610"]

[cbfc1c8567773bc0a0b41040406f846e]
catalognumber = "PCCG-70173"
date = "2013-01-25"
album = "ねぐせ / 北白川たまこ (CV: 洲崎 綾)"
tracks = [
    [1, "ねぐせ", "北白川たまこ(CV:洲崎綾)", 0],
    [2, "キミの魔法", "北白川たまこ(CV:洲崎綾)", 0],
    [3, "ねぐせ (Instrumental)", "北白川たまこ(CV:洲崎綾)", 0],
    [4, "キミの魔法 (Instrumental)", "北白川たまこ(CV:洲崎綾)", 0],
]
links = ["https://beta.musicbrainz.org/release/76ed65aa-661b-48ea-abce-ba4adea3c934", "https://vgmdb.net/album/36611"]

[7db4423521687d85f214ff3ace6b50cc]
catalognumber = "PCCG-01328"
date = "2013-02-20"
album = "TVアニメ『たまこまーけっと』キャラクターソングアルバム twinkle ride CD"
tracks = [
    [1, "おもちアフェっクション!", "北白川たまこ(CV:洲崎綾)", 0],
    [2, "Girlfriend", "常盤みどり(CV:金子有希)", 0],
    [3, "カンカン・マキマキ", "牧野かんな(CV:長妻樹里)", 0],
    [4, "Call me Anne", "北白川あんこ(CV:日高里菜)", 0],
    [5, "今日も言えない", "朝霧史織(CV:山下百合恵)", 0],
    [6, "太陽とドラム", "チョイ・モチマッヅィ(CV:山岡ゆり)", 0],
    [7, "きっとね、ずっとね、よろしくね。", "たまこ、みどり、かんな、あんこ、史織、チョイ・モチマッヅィ", 0],
]
links = ["https://beta.musicbrainz.org/release/5e33d5d1-72d2-48ab-ad84-98c0d9e558b9", "https://vgmdb.net/album/37595"]

[8d8a7a25ba5cfc985ce2c5f3f8709673]
catalognumber = "PCXE-50251"
date = "2013-03-20"
album = "My Love's Like / Cage North"
tracks = [
    [1, "My Love's Like", "Max Tundra", 0],
]
links = ["https://beta.musicbrainz.org/release/6ba3fda7-fb7c-4c9d-8ced-24ec54cee23d", "https://vgmdb.net/album/37307"]

[22627573dee4d3f5d1cce12e9968adde]
catalognumber = "PCXE-50252"
date = "2013-04-17"
album = "Un Lieu de Rencontre / Marilou"
tracks = [
    [1, "Un Lieu de Rencontre", "Marilou", 0],
]
links = ["https://beta.musicbrainz.org/release/03579c0e-5ad5-4727-8c1f-1178bbfeee76", "https://vgmdb.net/album/38077"]

[c26103571b1b8df9dbbf41735d509549]
catalognumber = "PCCG-01329"
date = "2013-04-26"
album = "たまこまーけっと オリジナル・サウンドトラック『Snappy Music Around of Tamako』 Disc 1 [PCCG-01329-1]"
tracks = [
    [1, "ドラマチックマーケットライド (TVサイズ)", "北白川たまこ(CV:洲崎綾)", 0],
    [2, "たのしいたまこ", "片岡知子", 0],
    [3, "もっと楽しいたまこ", "片岡知子", 0],
    [4, "もの思いのたまこ", "片岡知子", 0],
    [5, "もの思いのたまこ～その2", "片岡知子", 0],
    [6, "おセンチたまこ", "片岡知子", 0],
    [7, "怒りのたまこ", "片岡知子", 0],
    [8, "お昼寝たまこ", "薄井由行", 0],
    [9, "たのしいたまこ・ピアノソロ", "片岡知子", 0],
    [10, "もっと楽しいたまこ・ピアノソロ", "片岡知子", 0],
    [11, "恋するデラ", "片岡知子", 0],
    [12, "コミカルデラ", "片岡知子", 0],
    [13, "かっこつけデラ", "片岡知子", 0],
    [14, "デラとたまこ", "片岡知子", 0],
    [15, "サブタイトル", "片岡知子", 0],
    [16, "朝のたまや", "片岡知子", 0],
    [17, "北白川家のテーマ", "片岡知子", 0],
    [18, "おじいちゃんのおもち", "片岡知子", 0],
    [19, "とーちゃんのおもち", "片岡知子", 0],
    [20, "朝のたまや・ピアノソロ", "片岡知子", 0],
    [21, "アイキャッチ", "山田尚子＋片岡知子", 0],
    [22, "みどりのテーマ", "片岡知子", 0],
    [23, "かんなのテーマ", "片岡知子", 0],
    [24, "かんなのテーマ・BPM124", "片岡知子", 0],
    [25, "史織のテーマ", "片岡知子", 0],
    [26, "もち蔵のテーマ", "永田太郎", 0],
    [27, "チョイのテーマ", "片岡知子", 0],
    [28, "バトン部三人娘のテーマ", "片岡知子", 0],
    [29, "たのしいたまこの可憐なイントロ", "片岡知子", 0],
]
links = ["https://beta.musicbrainz.org/release/7c14e3d1-deb9-49fa-ac15-e7aaec8c1a82", "https://vgmdb.net/album/37897"]

[61dc5cb47aa801ae73c06b348b6dd412]
catalognumber = "PCCG-01329"
date = "2013-04-26"
album = "たまこまーけっと オリジナル・サウンドトラック『Snappy Music Around of Tamako』 Disc 2 [PCCG-01329-2]"
tracks = [
    [1, "たのしいたまこのとんまなイントロ", "片岡知子", 0],
    [2, "学校とスクールガール", "冷水ひとみ", 0],
    [3, "放課後", "片岡知子", 0],
    [4, "いつものたまこと豆大", "山口優", 0],
    [5, "バトン部三人娘のテーマ・ピアノソロ", "片岡知子", 0],
    [6, "放課後・ピアノソロ", "片岡知子", 0],
    [7, "デラ登場", "薄井由行", 0],
    [8, "お化け屋敷", "薄井由行", 0],
    [9, "たのしいあんこ", "片岡知子", 0],
    [10, "ドキドキあんこ", "片岡知子", 0],
    [11, "ナーバスあんこ", "山口優", 0],
    [12, "胸キュンあんこ", "山口優", 0],
    [13, "さよならのあんこ", "片岡知子", 0],
    [14, "アイキャッチ(Instrumental)", "山田尚子＋片岡知子", 0],
    [15, "しあわせの商店街", "片岡知子", 0],
    [16, "商店街の日常", "片岡知子", 0],
    [17, "朝の商店街", "片岡知子＋冷水ひとみ", 0],
    [18, "商店街のピンチ", "片岡知子", 0],
    [19, "お祭りの商店街", "片岡知子＋永田太郎", 0],
    [20, "バレンタインの商店街", "片岡知子＋永田太郎", 0],
    [21, "夕暮れの商店街", "片岡知子＋冷水ひとみ", 0],
    [22, "しあわせすぎる商店街", "片岡知子", 0],
    [23, "しあわせの商店街・ピアノソロ", "片岡知子", 0],
    [24, "ドラマチックマーケットライド (たまこハミングバージョン)", "北白川たまこ(CV:洲崎綾)", 0],
    [25, "ねぐせ (TVサイズ)", "北白川たまこ(CV:洲崎綾)", 0],
]
links = ["https://beta.musicbrainz.org/release/7c14e3d1-deb9-49fa-ac15-e7aaec8c1a82", "https://vgmdb.net/album/37897"]

[51e0d6178fc91067628106db52e922b5]
catalognumber = "PCXE-50253"
date = "2013-05-15"
album = "Excerpts from \"The Return Of The Drowning Witch\" (Part1~Part9) / Hogweed"
tracks = [
    [1, "The Return Of The Drowning Witch Part1", "松前公高", 0],
    [2, "The Return Of The Drowning Witch Part2", "松前公高", 0],
    [3, "The Return Of The Drowning Witch Part3", "松前公高", 0],
    [4, "The Return Of The Drowning Witch Part4", "松前公高", 0],
    [5, "The Return Of The Drowning Witch Part5", "松前公高", 0],
    [6, "The Return Of The Drowning Witch Part6", "松前公高", 0],
    [7, "The Return Of The Drowning Witch Part7", "松前公高", 0],
    [8, "The Return Of The Drowning Witch Part8", "松前公高", 0],
    [9, "The Return Of The Drowning Witch Part9", "松前公高", 0],
]
links = ["https://beta.musicbrainz.org/release/062ff658-b1a6-40d3-bf48-f0203d43ab05", "https://vgmdb.net/album/38385"]

[850de4e6bc10d72696962b17884c5cc7]
catalognumber = "PCXE-50254"
date = "2013-06-19"
album = "Girl Next Door ORIGINAL SOUNDTRACK RECORDING"
tracks = [
    [1, "Girl Next Door (Zizzania)", "", 0],
]
links = ["https://vgmdb.net/album/39074"]

[6dafd2d65a7fdc268906c17aa971099b]
catalognumber = "PCXE-50255"
date = "2013-07-17"
album = "恋の歌 / ダイナマイトビーンズ"
tracks = [
    [1, "恋の歌", "", 0],
]
links = ["https://vgmdb.net/album/40002"]

[26d07d156960a37b8d05362fe5386e7a]
catalognumber = "PCXE-50256"
date = "2013-08-21"
album = "Girl on the 94 / The Cupid's Toy"
tracks = [
    [1, "Girl on the 94", "", 0],
]
links = ["https://vgmdb.net/album/40489"]

[ef6b5771e82fbf8a47784f1baef14033]
catalognumber = "SCCG-00002"
date = "2014-03-22"
album = "TVアニメ『たまこまーけっと』キャラクターソング・リミックス omochi-tronica EP plus"
tracks = [
    [1, "Jimanica Plays おもちアフェっクション!", "", 0],
    [2, "Call Me Anne Louder", "", 0],
    [3, "おもちアフェックション! (instrumental)", "", 0],
    [4, "Girlfriend (instrumental)", "", 0],
    [5, "カンカン・マキマキ (instrumental)", "", 0],
    [6, "Call Me Anne (instrumental)", "", 0],
    [7, "今日も言えない (instrumental)", "", 0],
    [8, "太陽とドラム (instrumental)", "", 0],
    [9, "きっとね、ずっとね、よろしくね。 (instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/44913"]

[d992f0e55f95ecb2321dfb8b488aa743]
catalognumber = "PCCG-70210"
date = "2014-04-30"
album = "プリンシプル / 洲崎綾"
tracks = [
    [1, "プリンシプル", "洲崎綾", 0],
    [2, "こいのうた", "北白川たまこ(CV:洲崎綾)", 0],
    [3, "プリンシプル (instrumental)", "洲崎綾", 0],
    [4, "こいのうた (instrumental)", "北白川たまこ(CV:洲崎綾)", 0],
]
links = ["https://beta.musicbrainz.org/release/4ded0387-422c-4a86-ba4e-9d85989062d1", "https://vgmdb.net/album/44619"]

[125225ecd9d4844bfb5d2e6a6e15961f]
catalognumber = "PCCG-01415"
date = "2014-07-16"
album = "映画「たまこラブストーリー」オリジナル・サウンドトラック"
tracks = [
    [1, "商店街の日常 (Cinema ver.)", "片岡知子", 0],
    [2, "KOI NO UTA", "北白川豆大(CV:藤原啓治)", 0],
    [3, "かんなのテーマ", "片岡知子", 0],
    [4, "バトン部三人娘のテーマ ピアノソロ", "片岡知子", 0],
    [5, "放課後 ピアノソロ", "片岡知子", 0],
    [6, "幸せの商店街 (Cinema ver.)", "片岡知子＋冷水ひとみ", 0],
    [7, "恋するもち蔵", "片岡知子", 0],
    [8, "もち蔵の計画", "薄井由行", 0],
    [9, "うさ湯にて", "薄井由行", 0],
    [10, "朝の学校", "片岡知子", 0],
    [11, "みどりともち蔵", "片岡知子", 0],
    [12, "河原のたまこともち蔵", "片岡知子", 0],
    [13, "たまこ錯乱中", "片岡知子", 0],
    [14, "やさしい雨降り", "片岡知子", 0],
    [15, "ちいさな秘密", "片岡知子", 0],
    [16, "学校とスクールガール (Cinema ver.)", "冷水ひとみ", 0],
    [17, "ひなこの想い出", "片岡知子", 0],
    [18, "宇宙の入り口", "片岡知子", 0],
    [19, "とーちゃんのおもち", "片岡知子", 0],
    [20, "秘密", "片岡知子", 0],
    [21, "秘密 ピアノソロ", "片岡知子", 0],
    [22, "おじいちゃんのおもち", "片岡知子", 0],
    [23, "おセンチたまこ (Cinema ver.)", "片岡知子", 0],
    [24, "中庭", "片岡知子", 0],
    [25, "恋のあれこれ", "片岡知子", 0],
    [26, "豆大さんへ～「きらきら星」より", "ひなこ(CV:日笠陽子)", 0],
    [27, "たまこへ", "片岡知子", 0],
    [28, "上を向いて歩こう", "片岡知子", 0],
    [29, "教室", "山口優", 0],
    [30, "みどりのテーマ", "片岡知子", 0],
    [31, "風の吹く先", "片岡知子", 0],
    [32, "こいのうた (ショートサイズ)", "北白川たまこ(CV:洲崎綾)", 0],
    [33, "プリンシプル (ショートサイズ)", "洲崎綾", 0],
    [34, "みどりの気持ち", "片岡知子", 0],
]
links = ["https://beta.musicbrainz.org/release/458c1ac6-97bf-40aa-8f3a-a69be5f7f00c", "https://vgmdb.net/album/45695"]

[74177494318117b9f0b957899a872016]
catalognumber = "PCCG-01416"
date = "2014-07-16"
album = "TVアニメ「たまこまーけっと」& 映画「たまこラブストーリー」劇中曲コンピレーションCD 星とピエロ compilated by Kunio Yaobi"
tracks = [
    [1, "My Love's Like", "Max Tundra", 0],
    [2, "Un Lieu de Rencontre", "Marilou", 0],
    [3, "O.S.T \"Girl Next Door\"", "Franco Casa / Paul Bennett", 0],
    [4, "Hajimete No Hoshi", "Toshiya Nagoshi", 0],
    [5, "Taste a moment of Satan's madness", "Pink Marigold Ice Cream & Giuliano Sopliani", 0],
    [6, "Atlantis Flower", "Paul Dante and His Lobularia Orchestra", 0],
    [7, "恋の歌", "ダイナマイトビーンズ", 0],
    [8, "Devata Vlna Tanec", "Vladislav Fibich Symfonietta", 0],
    [9, "Girl on the 94", "The Cupid's Toy", 0],
    [10, "qum Daiwtiigyam", "Daniels", 0],
    [11, "The Return Of The Drowning Witch Part1", "松前公高", 0],
    [12, "The Return Of The Drowning Witch Part2", "松前公高", 0],
    [13, "The Return Of The Drowning Witch Part3", "松前公高", 0],
    [14, "The Return Of The Drowning Witch Part4", "松前公高", 0],
    [15, "The Return Of The Drowning Witch Part5", "松前公高", 0],
    [16, "The Return Of The Drowning Witch Part6", "松前公高", 0],
    [17, "The Return Of The Drowning Witch Part7", "松前公高", 0],
    [18, "The Return Of The Drowning Witch Part8", "松前公高", 0],
    [19, "The Return Of The Drowning Witch Part9", "松前公高", 0],
]
links = ["https://beta.musicbrainz.org/release/17d22c10-3d45-43ca-aac9-da49c69cf1c2", "https://vgmdb.net/album/45696"]

[fd594e6c676bf6abf64ed2a347788cba]
catalognumber = "QPCPVL0010086"
date = "2015-03-18"
album = "Tamako Out-Takes"
tracks = [
    [1, "ドラマチックマーケットライド (first demo)", "", 0],
    [2, "ねぐせ (first demo)", "", 0],
    [3, "Pre \"もっと楽しいたまこ\" with DONCA MATIC (PV用音楽)", "", 0],
    [4, "恋の歌 (first demo)", "", 0],
    [5, "Girlfriend (フレンチVer.)", "", 0],
    [6, "ともろう (first demo)", "", 0],
    [7, "もち蔵とあんこ (Full Ver.)", "", 0],
]
links = ["https://vgmdb.net/album/100786"]

[2e71fdd6bf3c929a19c23b33a712584d]
catalognumber = "PCCG-01447"
date = "2015-03-18"
album = "TVアニメ「たまこまーけっと」&映画「たまこラブストーリー」ベスト・アルバム「Everybody Loves Somebody ～ うさぎ山から愛をこめて」"
tracks = [
    [1, "ドラマチックマーケットライド", "北白川たまこ(CV:洲崎綾)", 0],
    [2, "ともろう", "北白川たまこ(CV:洲崎綾)", 0],
    [3, "KOI NO UTA", "北白川豆大(CV:藤原啓治)", 0],
    [4, "プリンシプル", "洲崎綾", 0],
    [5, "ねぐせ", "北白川たまこ(CV:洲崎綾)", 0],
    [6, "キミの魔法", "北白川たまこ(CV:洲崎綾)", 0],
    [7, "こいのうた", "北白川たまこ(CV:洲崎綾)", 0],
    [8, "恋の歌", "ダイナマイトビーンズ", 0],
    [9, "デラ・モチマッヅィのうた", "デラ・モチマッヅィ(cv:山崎たくみ)", 0],
    [10, "デラ・モチマッヅィのうた(Instrumental)", "デラ・モチマッヅィ(cv:山崎たくみ)", 0],
    [11, "Call Me Anne Louder", "北白川あんこ(cv:日高里菜)", 0],
    [12, "今日も明日も", "北白川たまこ&大路もち蔵(cv:洲崎綾・田丸篤志)", 0],
    [13, "二重奏クレッシェンド", "常盤みどり&牧野かんな牧野かんな(cv:金子有希・長妻樹里)", 0],
    [14, "太陽とドラムと喋る鳥", "チョイ・モチマッヅィ&デラ・モチマッヅィ(cv:山岡ゆり・山崎たくみ)", 0],
    [15, "うさ湯音頭", "湯本長治(cv:津久井教生)", 0],
    [16, "ひなこより", "ひなこ(cv:日笠陽子)", 0],
    [17, "きっとね、ずっとね、よろしくね。", "たまこ、みどり、かんな、あんこ、史織、チョイ・モチマッヅィ", 0],
]
links = ["https://beta.musicbrainz.org/release/8a6050a7-2e2c-4cd9-a214-e90aac04fe7d", "https://vgmdb.net/album/49578"]

[9738985bdc49836e56f9d693538a9a82]
catalognumber = "PJO-0001"
date = "2016-08-14"
album = "Precious Jazz Orchestra Plays Anime Standards vol.1"
tracks = [
    [1, "Star!!", "Precious Jazz Orchestra", 0],
    [2, "Butter-Fly", "Precious Jazz Orchestra", 0],
    [3, "？でわっしょい", "Precious Jazz Orchestra", 0],
    [4, "Sis puella magica!", "Precious Jazz Orchestra", 0],
    [5, "ルミナス", "Precious Jazz Orchestra", 0],
    [6, "ドラマチックマーケットライド", "Precious Jazz Orchestra", 0],
    [7, "夏色えがおで1,2,Jump!", "Precious Jazz Orchestra", 0],
    [8, "風といっしょに", "Precious Jazz Orchestra", 0],
]
links = ["https://beta.musicbrainz.org/release/5f47c96c-9fcd-45ea-8ba6-0a92522b3fce", "https://vgmdb.net/album/60516"]

[963f73ac90c6df9108c2b13ab57a6f35]
catalognumber = "N/A"
date = "2019-01-22"
album = "アルニメクト / callasoiled"
tracks = [
    [1, "ﾄﾞｩﾙﾙﾙﾙﾙﾙ三└(┐卍^o^)卍ｲﾔｯﾎｵｵｵｫｫｫｵｵｵｵｵｵｵ!!!!!!!!!!!!d=(^o^)=b", "", 0],
    [2, "エルフェンリートの「Lilium」を切り刻み原型を無くしたもののRemix", "", 0],
    [3, "たまこまーけっとの「ねぐせ」を原型が無くなるまで切り刻んだもののRemix", "", 0],
    [4, "ニコニコ動画で流行った「星間飛行」のリミックスに便乗したもののRemix", "", 0],
    [5, "デッドマンズワンダーランドの「Shiny Shiny」をRemixしたものをRemix", "", 0],
    [6, "Maltine RecordsからリリースされたBanvoxの「Laser」をRemixした事のある人間だけが持ってる音声を用いて再度Remixしたもの", "", 0],
    [7, "田中ヒメがまだヒメヒナでは無かった頃に作った、ライブに使おうとしてやめたもの（Bonus Track）", "", 0],
]
links = ["https://vgmdb.net/album/137853"]

[f35386c109c29243fa04b67bd0ca8af6]
catalognumber = "KYOG-202151"
date = "2022-11-24"
album = "第5回京都アニメーションファン感謝イベントKYOANI MUSIC FESTIVAL ―感動を未来へ― Blu-ray Disc 1 (Blu-ray)"
tracks = [
    [1, "ユメミタソラ", "", 0],
    [2, "ドラマチックマーケットライド", "", 0],
    [3, "ねぐせ", "", 0],
    [4, "プリンシプル", "", 0],
    [5, "Naked Dive", "", 0],
    [6, "純真Always", "", 0],
    [7, "Naru", "", 0],
    [8, "オレンジ色", "", 0],
    [9, "Songbirds", "", 0],
    [10, "Don't say \"lazy\"", "", 0],
    [11, "ふわふわ時間", "", 0],
    [12, "優しさの理由", "", 0],
    [13, "From EVER BLUE", "", 0],
    [14, "Rhythm of new sensation", "", 0],
    [15, "Departure for the future", "", 0],
    [16, "Pure blue starting～Starting days", "", 0],
    [17, "Starting to the future", "", 0],
    [18, "Relate to you", "", 0],
    [19, "Into the new world", "", 0],
    [20, "Never seen landscapes", "", 0],
    [21, "Don't matter anymore", "", 0],
    [22, "We could be free", "", 0],
    [23, "トゥッティ！", "", 0],
    [24, "ヴィヴァーチェ！", "", 0],
    [25, "Blast!", "", 0],
    [26, "サウンドスケープ", "", 0],
    [27, "DREAM SOLISTER", "", 0],
    [28, "てとてとて", "", 0],
]
links = ["https://vgmdb.net/album/121243"]

[59aeb6e8dbd82c4a61317978ea2b44ce]
catalognumber = "KYOG-202151"
date = "2022-11-24"
album = "第5回京都アニメーションファン感謝イベントKYOANI MUSIC FESTIVAL ―感動を未来へ― Blu-ray Disc 2 (Blu-ray)"
tracks = [
    [1, "ユメミタソラ", "", 0],
    [2, "Sparkling Daydream", "", 0],
    [3, "VOICE", "", 0],
    [4, "JOURNEY", "", 0],
    [5, "INSIDE IDENTITY", "", 0],
    [6, "Van!shment Th!s World", "", 0],
    [7, "境界の彼方", "", 0],
    [8, "会いたかった空", "", 0],
    [9, "約束の絆", "", 0],
    [10, "めいど・うぃず・どらごんず♥", "", 0],
    [11, "イシュカン・コミュニケーション", "", 0],
    [12, "愛のシュプリーム", "", 0],
    [13, "青空のラプソディ", "", 0],
    [14, "優しい忘却", "", 0],
    [15, "ハレ晴レユカイ", "", 0],
    [16, "もってけ！セーラーふく", "", 0],
    [17, "ヴァイオレット・エヴァーガーデン劇伴メドレー", "", 0],
    [18, "Sincerely", "", 0],
    [19, "エイミー", "", 0],
    [20, "みちしるべ ～Movie Version～", "", 0],
    [21, "WILL", "", 0],
    [22, "未来のひとへ ～Movie Version～", "", 0],
    [23, "Violet Snow", "", 0],
    [24, "てとてとて", "", 0],
]
links = ["https://vgmdb.net/album/121243"]

[7a76dade78dc8e3fdaabed12d129c194]
catalognumber = "KYOG-202151"
date = "2022-11-24"
album = "第5回京都アニメーションファン感謝イベントKYOANI MUSIC FESTIVAL ―感動を未来へ― Blu-ray Disc 3 (CD)"
tracks = [
    [1, "イベントエンディングリミックスCD", "", 0],
]
links = ["https://vgmdb.net/album/121243"]

[e33f9e683675ed60d4e0f943656cdcb2]
catalognumber = "PCKG-00003"
date = "2023-10-18"
album = "プリンシプル/こいのうた [完全生産限定盤]"
tracks = [
    [1, "プリンシプル", "洲崎綾", 0],
]
links = ["https://beta.musicbrainz.org/release/f7b04c55-6e63-4595-9705-027732809fd3", "https://vgmdb.net/album/130370"]

[6793d8f3da49bf9b46b66b72f354c5a5]
catalognumber = "PCJG-00009"
date = "2023-10-18"
album = "映画「たまこラブストーリー」オリジナル・サウンドトラック [完全生産限定盤]"
tracks = []
links = ["https://vgmdb.net/album/130368"]

[a75fbb6fe064602ee7a573c7eccb71ea]
catalognumber = "PCJG-00008"
date = "2023-10-18"
album = "たまこまーけっと オリジナル・サウンドトラック『Snappy Music Around of Tamako』 [完全生産限定盤]"
tracks = [
    [1, "たのしいたまこ", "", 0],
    [2, "もっと楽しいたまこ", "", 0],
    [3, "もの思いのたまこ", "", 0],
    [4, "おセンチたまこ", "", 0],
    [5, "怒りのたまこ", "", 0],
    [6, "恋するデラ", "", 0],
    [7, "コミカルデラ", "", 0],
    [8, "かっこつけデラ", "", 0],
    [9, "デラとたまこ", "", 0],
    [10, "サブタイトル", "", 0],
    [11, "朝のたまや", "", 0],
    [12, "北白川家のテーマ", "", 0],
    [13, "商店街の日常", "", 0],
    [14, "かんなのテーマ・BPM124", "", 0],
    [15, "史織のテーマ", "", 0],
    [16, "チョイのテーマ", "", 0],
    [17, "バトン部三人娘のテーマ", "", 0],
    [18, "たのしいたまこの可憐なイントロ", "", 0],
    [19, "たのしいたまこのとんまなイントロ", "", 0],
    [20, "放課後", "", 0],
    [21, "たのしいあんこ", "", 0],
    [22, "さよならのあんこ", "", 0],
    [23, "しあわせの商店街", "", 0],
    [24, "商店街のピンチ", "", 0],
    [25, "しあわせすぎる商店街", "", 0],
]
links = ["https://vgmdb.net/album/130367"]

[635753958ebc04ae7d9709bd806cabed]
catalognumber = "PCKG-00002"
date = "2023-10-18"
album = "ドラマチックマーケットライド/ねぐせ / 北白川たまこ(CV: 洲崎 綾) [完全生産限定盤]"
tracks = [
    [1, "ドラマチックマーケットライド", "", 0],
    [2, "ねぐせ", "", 0],
]
links = ["https://vgmdb.net/album/130369"]
