[1a82cb0fc887b2136cb67a7100fa0e58]
catalognumber = "VPCC-82301"
date = "2011-11-30"
album = "YOUTHFUL / 99RadioService"
tracks = [
    [1, "YOUTHFUL", "99RadioService", 0],
    [2, "YOUTHFUL ～from Studio Yamato～", "99RadioService", 0],
    [3, "Same love, Different heart", "99RadioService", 0],
]
links = ["https://beta.musicbrainz.org/release/a3795c60-64d5-47b3-920b-702b89c481f8", "https://vgmdb.net/album/29879"]

[85cfe79d50d5c0e5dc9ba3f4be36ef1e]
catalognumber = "VPCG-84916"
date = "2012-01-18"
album = "ちはやふる オリジナル・サウンドトラック&キャラクターソング集 第1首"
tracks = [
    [1, "YOUTHFUL (TVサイズ)", "99RadioService", 0],
    [2, "かるた日和", "山下康介", 0],
    [3, "高ぶるキモチ", "山下康介", 0],
    [4, "まなざし", "山下康介", 0],
    [5, "心構え", "山下康介", 0],
    [6, "秘めた想い", "山下康介", 0],
    [7, "「ちはやふる」メインテーマ", "山下康介", 0],
    [8, "かるたの目", "山下康介", 0],
    [9, "過去の記憶", "山下康介", 0],
    [10, "かるたなんて", "山下康介", 0],
    [11, "勝利への道", "山下康介", 0],
    [12, "焦り", "山下康介", 0],
    [13, "思わぬ展開", "山下康介", 0],
    [14, "本当の実力", "山下康介", 0],
    [15, "和美人", "山下康介", 0],
    [16, "曇りココロ", "山下康介", 0],
    [17, "大きな存在", "山下康介", 0],
    [18, "活動開始!", "山下康介", 0],
    [19, "おさななじみ", "山下康介", 0],
    [20, "チームちはやふる", "山下康介", 0],
    [21, "「ちはやふる」メインテーマ ～p.f.ver.～", "山下康介", 0],
    [22, "full throttle", "綾瀬千早 (cv. 瀬戸麻沙美)", 0],
    [23, "夢への地図", "綿谷新 (cv. 細谷佳正)", 0],
    [24, "NICK MAN!", "西田優征 (cv. 奈良徹)", 0],
    [25, "そしていま", "瀬戸麻沙美", 0],
]
links = ["https://beta.musicbrainz.org/release/ec8a6048-fe88-4013-9644-4a3d2cdedc9b", "https://vgmdb.net/album/30054"]

[b690ed8384c7047c4eb0e2071b00a5ed]
catalognumber = "VPCG-84917"
date = "2012-03-28"
album = "ちはやふる オリジナル・サウンドトラック&キャラクターソング集 第2首"
tracks = [
    [1, "YOUTHFUL (TVサイズ)", "99RadioService", 0],
    [2, "反撃開始!", "山下康介", 0],
    [3, "流れをつかめ!", "山下康介", 0],
    [4, "小さなミス", "山下康介", 0],
    [5, "息抜きに", "山下康介", 0],
    [6, "怪しい雲行き", "山下康介", 0],
    [7, "好勝負", "山下康介", 0],
    [8, "ココロの距離", "山下康介", 0],
    [9, "試合は進んで", "山下康介", 0],
    [10, "揺れ動く想い", "山下康介", 0],
    [11, "おかしな関係", "山下康介", 0],
    [12, "強敵出現!", "山下康介", 0],
    [13, "張りつめた糸", "山下康介", 0],
    [14, "命運", "山下康介", 0],
    [15, "絶好調!", "山下康介", 0],
    [16, "深層の声", "山下康介", 0],
    [17, "葛藤", "山下康介", 0],
    [18, "悲しみの敗北", "山下康介", 0],
    [19, "Fight!", "山下康介", 0],
    [20, "交叉する想い", "山下康介", 0],
    [21, "見えない敵", "山下康介", 0],
    [22, "小さな大事なコト", "山下康介", 0],
    [23, "かるたとともに", "山下康介", 0],
    [24, "何度も生まれては消えていく雪のようなもの", "真島太一（cv. 宮野真守）", 0],
    [25, "乙女の恋は蝶結び", "大江奏 (cv. 茅野愛衣)", 0],
    [26, "人生スクワット", "駒野勉 (cv. 代永翼)", 0],
    [27, "そしていま (TVサイズ)", "瀬戸麻沙美", 0],
]
links = ["https://beta.musicbrainz.org/release/ba20ec0e-38ec-42d8-a34d-5fe8cd229e40", "https://vgmdb.net/album/31210"]

[764ff816458d1da415c0109ff1f875ba]
catalognumber = "QWCE-00226"
date = "2012-04-04"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 15"
tracks = [
    [1, "残念系隣人部★★☆（星ふたつ半）", "Ryu* feat.mi-mi+R.Cena", 0],
    [2, "空想メソロギヰ", "kinoto feat.R.Cena", 0],
    [3, "BLOOD TELLER", "Hommarju feat.mamiko", 0],
    [4, "ROCK OVER JAPAN", "Hommarju feat.si-na+R.Cena", 0],
    [5, "HIGH POWERED", "Dizzi Mystica feat.mi-mi+JJ", 0],
    [6, "私のキ・モ・チ", "Booing Day feat.Latte", 0],
    [7, "少年よ我に帰れ", "MK feat.405", 0],
    [8, "君の神話〜アクエリオン第二章", "Dizzi Mystica feat.R.Cena", 0],
    [9, "TERMINATED", "Dizzi Mystica feat.YURiE", 0],
    [10, "FLY AWAY", "Icon feat.puchi", 0],
    [11, "YOUTHFUL", "Icon feat.TAKANORI", 0],
    [12, "I'LL BELIEVE", "Dizzi Mystica feat.KANA+TAKANORI", 0],
    [13, "SKY'S THE LIMIT", "Dizzi Mystica feat.YURiE+MFMW", 0],
    [14, "COOLISH WALK", "Dizzi Mystica feat.mi-mi+R.Cena", 0],
    [15, "U-N-D-E-R--STANDING!", "Icon feat.puchi+TAKANORI", 0],
    [16, "紋", "Booing Day feat.yumemi", 0],
    [17, "君の中の英雄", "MK feat.KANA", 0],
    [18, "おかえりなさい", "MK feat.Nahoko", 0],
    [19, "ENDLESS STORY", "Dizzi Mystica feat.Latte", 0],
    [20, "ノルニル", "Hommarju feat.405", 0],
]
links = ["https://beta.musicbrainz.org/release/2b80d131-81ee-4e02-b169-87d60b75f2ab", "https://vgmdb.net/album/32343"]

[860dd61d2ad1a259b6f99dc3067f32b4]
catalognumber = "PRVA-823"
date = "2012-07-18"
album = "ちはやふる 第8巻 ドラマCD"
tracks = [
    [1, "ちはやふる・今昔物語(前編)", "綾瀬千早(CV.瀬戸麻沙美), 真島太一(CV.宮野真守), 大江奏(CV.茅野愛衣), 駒野勉(CV.代永翼), 西田優征(CV.奈良徹), 綿谷新(CV.細谷佳正)", 0],
]
links = ["https://beta.musicbrainz.org/release/57b027b3-56a3-4667-9f7d-7fcb544b7e1c", "https://vgmdb.net/album/52358"]

[7bc882d38e3341cfadade187b1ed57cd]
catalognumber = "PRVA-824"
date = "2012-08-22"
album = "ちはやふる 第9巻 ドラマCD"
tracks = [
    [1, "ちはやふる・今昔物語(後編)", "綾瀬千早(CV.瀬戸麻沙美), 真島太一(CV.宮野真守), 大江奏(CV.茅野愛衣), 駒野勉(CV.代永翼), 西田優征(CV.奈良徹), 綿谷新(CV.細谷佳正)", 0],
]
links = ["https://beta.musicbrainz.org/release/d2f4be51-3d74-4072-978e-ec02d67a8375", "https://vgmdb.net/album/52359"]

[23b3e84a0fe940347389301e21fdf500]
catalognumber = "VPCC-82309"
date = "2013-03-06"
album = "STAR / 99RADIOSERVICE"
tracks = [
    [1, "STAR", "99RadioService", 0],
    [2, "カモミール", "99RadioService", 0],
    [3, "STAR －instrumental－", "99RadioService", 0],
    [4, "カモミール －instrumental－", "99RadioService", 0],
]
links = ["https://beta.musicbrainz.org/release/9e370297-85f3-49e9-8f9a-adad431487c3", "https://vgmdb.net/album/36800"]

[710853f2dba412d5cec8563dc3ed6734]
catalognumber = "VPCC-82644"
date = "2013-03-06"
album = "STAR / 99RADIOSERVICE [初回限定盤] Disc 1 (CD)"
tracks = [
    [1, "STAR", "99RadioService", 0],
    [2, "カモミール", "99RadioService", 0],
    [3, "STAR －instrumental－", "99RadioService", 0],
    [4, "カモミール －instrumental－", "99RadioService", 0],
]
links = ["https://beta.musicbrainz.org/release/72caffb8-5d2d-4464-832c-713dab8ae3e3", "https://vgmdb.net/album/36801"]

[9c937efd719d1a9c1f3365011eeaa982]
catalognumber = "VPCC-82644"
date = "2013-03-06"
album = "STAR / 99RADIOSERVICE [初回限定盤] Disc 2 (DVD)"
tracks = [
    [1, "YOUTHFUL Music Video", "99RadioService", 0],
    [2, "STAR Music Video", "99RadioService", 0],
    [3, "「ちはやふる」 オープニング映像", "99RadioService", 0],
    [4, "「ちはやふる２」 オープニング映像", "99RadioService", 0],
]
links = ["https://beta.musicbrainz.org/release/72caffb8-5d2d-4464-832c-713dab8ae3e3", "https://vgmdb.net/album/36801"]

[60bc76e51c615c06637c18a5809808f3]
catalognumber = "VPCG-84939"
date = "2013-03-20"
album = "ちはやふる2 オリジナル・サウンドトラック Original Soundtrack, Vocal"
tracks = [
    [1, "STAR (TV Size)", "99RadioService", 0],
    [2, "小さな出会い", "山下康介", 0],
    [3, "新学期スタート!", "山下康介", 0],
    [4, "恋の駆け引き", "山下康介", 0],
    [5, "異種格闘技!?", "山下康介", 0],
    [6, "都立瑞沢高校校歌", "山下康介", 0],
    [7, "揺れる心", "山下康介", 0],
    [8, "開きかけた蕾", "山下康介", 0],
    [9, "一歩一歩", "山下康介", 0],
    [10, "プレッシャーとの戦い", "山下康介", 0],
    [11, "札の導き", "山下康介", 0],
    [12, "勝負のゆくえ", "山下康介", 0],
    [13, "涙の数だけ", "山下康介", 0],
    [14, "夢に向かって", "山下康介", 0],
    [15, "勝利をつかめ", "山下康介", 0],
    [16, "かけがえのない友とともに", "山下康介", 0],
    [17, "茜空", "瀬戸麻沙美", 0],
    [18, "都立瑞沢高校校歌 (Karaoke)", "山下康介", 0],
    [19, "茜空 (TV Size)", "瀬戸麻沙美", 0],
]
links = ["https://beta.musicbrainz.org/release/f22e5cfb-195d-4352-95d0-63df3b6b5c04", "https://vgmdb.net/album/37425"]

[d67d083b21ffc3682125a653585149af]
catalognumber = "VPCG-84939"
date = "2013-03-20"
album = "ちはやふる2 オリジナル・サウンドトラック Talk"
tracks = [
    [1, "『ちはやふる～浜松町かるた部～』オープニングトーク", "瀬戸麻沙美・茅野愛衣", 0],
    [2, "『ちはやふる～浜松町かるた部～』#1", "瀬戸麻沙美・茅野愛衣", 0],
    [3, "『ちはやふる～浜松町かるた部～』#2", "瀬戸麻沙美・茅野愛衣", 0],
    [4, "『ちはやふる～浜松町かるた部～』#3", "瀬戸麻沙美・茅野愛衣", 0],
    [5, "『ちはやふる～浜松町かるた部～』#4", "瀬戸麻沙美・茅野愛衣", 0],
    [6, "『ちはやふる～浜松町かるた部～』#5", "瀬戸麻沙美・茅野愛衣", 0],
    [7, "『ちはやふる～浜松町かるた部～』エンディングトーク", "瀬戸麻沙美・茅野愛衣", 0],
]
links = ["https://beta.musicbrainz.org/release/f22e5cfb-195d-4352-95d0-63df3b6b5c04", "https://vgmdb.net/album/37425"]

[dc612172be1fb38e6768acf43f0bc9a2]
catalognumber = "UPCH-2076"
date = "2016-04-06"
album = "映画『ちはやふる』 オリジナル・サウンドトラック"
tracks = [
    [1, "つながれ つながれ！ つながれ！！", "横山克", 0],
    [2, "だるまさんが・・", "横山克", 0],
    [3, "屋上で聞こえた声", "横山克", 0],
    [4, "かるた部をやろうよ", "横山克", 0],
    [5, "三人での記憶", "横山克", 0],
    [6, "ありがとう。かるたを一緒にしてくれて", "横山克", 0],
    [7, "千早のかるた", "横山克", 0],
    [8, "帰り道でのおんぶ", "横山克", 0],
    [9, "かるた部、、ふぁいと・・", "横山克", 0],
    [10, "四人目の部員", "横山克", 0],
    [11, "五人目の部員", "横山克", 0],
    [12, "はじめてかるたを教えてくれたひと", "横山克", 0],
    [13, "もしもし、元気?", "横山克", 0],
    [14, "かるたを学ぼう", "横山克", 0],
    [15, "強化合宿", "横山克", 0],
    [16, "言わないって言ったのに・・・", "横山克", 0],
    [17, "新って、どんな人・・?", "横山克", 0],
    [18, "S", "横山克", 0],
    [19, "優勝への道", "横山克", 0],
    [20, "あと◯◯日", "横山克", 0],
    [21, "百人一首と人の思い", "横山克", 0],
    [22, "ありがとう。かるたを好きでいてくれて", "横山克", 0],
    [23, "原田先生と太一", "横山克", 0],
    [24, "こんな気持ちにならなかったのに・・", "横山克", 0],
    [25, "瑞沢一勝！", "横山克", 0],
    [26, "運命を", "横山克", 0],
    [27, "変えたい", "横山克", 0],
    [28, "情熱がくれたもの", "横山克", 0],
    [29, "その瞬間", "横山克", 0],
    [30, "理由", "横山克", 0],
    [31, "詩暢のセンス", "横山克", 0],
    [32, "圧倒的なかるた", "横山克", 0],
    [33, "気持ちの整理", "横山克", 0],
    [34, "馬鹿は・・一人で十分！", "横山克", 0],
    [35, "おかえり", "横山克", 0],
    [36, "目の前が・・・。", "横山克", 0],
    [37, "個人戦だけど、団体戦", "横山克", 0],
    [38, "かるたが楽しかった時", "横山克", 0],
    [39, "その先に見える世界", "横山克", 0],
]
links = ["https://beta.musicbrainz.org/release/fd0f27ef-b10e-46c8-8a5a-9241c75c73dd", "https://vgmdb.net/album/60212"]

[dee24f1e5d6b18c7fca691e8afad40c2]
catalognumber = "HISN-05541"
date = "2019-10-22"
album = "COLORFUL / 99RadioService"
tracks = [
    [1, "COLORFUL", "99RadioService", 0],
]
links = ["https://beta.musicbrainz.org/release/0b9c5a31-b433-4f5d-a5d8-01e64081685a", "https://vgmdb.net/album/92072"]

[77e89b1dcf83118dcf1a75b7ccb61bc6]
catalognumber = "KDS-0435"
date = "2019-12-13"
album = "ちはやふる 第43巻 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/91369"]

[9b019ca68994412064c2bd2a637f9c57]
catalognumber = "SANPA-0006"
date = "2020-01-08"
album = "一目惚れ / バンドハラスメント"
tracks = [
    [1, "一目惚れ", "バンドハラスメント", 0],
    [2, "Fifty", "バンドハラスメント", 0],
    [3, "大人になるために (2020 ver.)", "バンドハラスメント", 0],
]
links = ["https://beta.musicbrainz.org/release/f74486be-7ec1-4ce1-99be-1639c6642605", "https://vgmdb.net/album/93999"]

[3a6ff4ce2a15ad5b35b7de7466f26cf6]
catalognumber = "COCC-17530"
date = "2020-07-15"
album = "THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER 40 バベル"
tracks = [
    [1, "バベル (M@STER VERSION)", "一ノ瀬志希(CV:藍原ことみ)、二宮飛鳥(CV:青木志貴)", 0],
    [2, "STAR", "道明寺歌鈴、浜口あやめ、脇山珠美", 0],
    [3, "君の青春は輝いているか", "南条光(CV:神谷早矢佳)", 0],
    [4, "風になりたい", "依田芳乃(CV:高田憂希)、藤原肇(CV:鈴木みのり)", 0],
    [5, "バベル (M@STER VERSION) (オリジナル・カラオケ)", "一ノ瀬志希、二宮飛鳥", 0],
    [6, "バベル (GAME VERSION)", "一ノ瀬志希、二宮飛鳥", 0],
]
links = ["https://beta.musicbrainz.org/release/c184b306-1449-434e-a2de-e8678cbcf2a4", "https://vgmdb.net/album/100490"]
