[4eb434f24e487c943425dd2db13423fc]
catalognumber = "HBDC-103"
date = "2012-04-27"
album = "ドラマCD のうりん"
tracks = []
links = ["https://vgmdb.net/album/51520"]

[f2e0008ae709d16e4aec834f66706231]
catalognumber = "N/A"
date = "2014-01-12"
album = "ドラマCD のうりん ～現実ゲーム～"
tracks = []
links = ["https://vgmdb.net/album/80805"]

[af0fcadfa0a702b646cd2582e0649441]
catalognumber = "MFCZ-1043"
date = "2014-01-22"
album = "コードレス☆照れ☆PHONE/も・ぎ・た・て♡フルーツガールズ"
tracks = [
    [1, "コードレス☆照れ☆PHONE", "草壁ゆか(CV:田村ゆかり)", 0],
    [2, "も・ぎ・た・て♡フルーツガールズ", "木下林檎(CV:田村ゆかり)＆中沢 農(CV:花澤香菜)", 0],
    [3, "コードレス☆照れ☆PHONE ～ゆかたんコンサートバージョン～", "草壁ゆか(CV:田村ゆかり) with 訓練された者たち", 0],
    [4, "も・ぎ・た・て♡フルーツガールズ (林檎only ver.)", "木下林檎(CV:田村ゆかり)", 0],
    [5, "も・ぎ・た・て♡フルーツガールズ (農only ver.)", "中沢 農(CV:花澤香菜)", 0],
    [6, "コードレス☆照れ☆PHONE (instrumental)", "草壁ゆか(CV:田村ゆかり)", 0],
    [7, "も・ぎ・た・て♡フルーツガールズ (instrumental)", "木下林檎(CV:田村ゆかり)＆中沢 農(CV:花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/73972656-9a7c-4912-97a3-f0bf6ce1da89", "https://vgmdb.net/album/42487"]

[42c926398a686b6ebc6e98e9c1d7e701]
catalognumber = "KICM-1494"
date = "2014-02-05"
album = "秘密の扉から会いにきて / 田村ゆかり"
tracks = [
    [1, "秘密の扉から会いにきて", "田村ゆかり", 0],
    [2, "レリーフのひとかけら", "田村ゆかり", 0],
    [3, "I DO 愛", "田村ゆかり", 0],
]
links = ["https://beta.musicbrainz.org/release/bce5481a-5f76-4a5e-9661-89b4ebfcc71e", "https://vgmdb.net/album/42609"]

[35ec7898b9296a17cde3edd80bc244a9]
catalognumber = "QWCE-00344"
date = "2014-04-02"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 21"
tracks = [
    [1, "回レ!雪月花", "plazma feat. si-na + YURiE", 0],
    [2, "MUSIC S.T.A.R.T!!", "MK feat. SAYURI + 405", 0],
    [3, "TRUE BLUE TRAVELER", "Flash back Dominant feat. Latte", 0],
    [4, "STAND UP!!!!", "kinoto feat. さつき + maburu-choko", 0],
    [5, "届かない恋", "plazma feat. KANA", 0],
    [6, "シンクロマニカ", "Dizzi Mystica feat. MFMW", 0],
    [7, "なないろびより", "MK feat. 405", 0],
    [8, "THE OTHER SELF", "Dizzi Mystica feat. hideki", 0],
    [9, "WALK", "Icon feat. LTT", 0],
    [10, "IMAGINATION>REALITY", "MK feat. Puchi", 0],
    [11, "ANICCA", "Dizzi Mystica feat. HARUKA", 0],
    [12, "も・ぎ・た・て フルーツガールズ", "Icon feat. SAYURI + さつき", 0],
    [13, "シリウス", "Hommarju feat. mai", 0],
    [14, "BEAUTIFUL SKY", "MK feat. SAYURI + Natsuhi", 0],
    [15, "革命デュアリズム", "Hommarju feat. mi-mi + hideki", 0],
]
links = ["https://beta.musicbrainz.org/release/6a16bbac-7a74-4df8-9204-e45e4dd3d55a", "https://vgmdb.net/album/46191"]

[4260842971729efdc34061c6f7c72a82]
catalognumber = "MFXN-0013EX"
date = "2014-04-09"
album = "のうりん vol.1 スペシャルCD"
tracks = []
links = ["https://vgmdb.net/album/44543"]

[d867ab0f63e53655850b2847006f79fd]
catalognumber = "MFXN-0014EX"
date = "2014-05-02"
album = "のうりん vol.2 スペシャルCD"
tracks = [
    [1, "みのりのぞっこん未来予報♡", "中沢農(CV:花澤香菜)", 0],
    [2, "みのりのぞっこん未来予報♡ 〜TVサイズ〜", "中沢農(CV:花澤香菜)", 0],
    [3, "みのりのぞっこん未来予報♡ 〜Instrumental〜", "中沢農(CV:花澤香菜)", 0],
    [4, "みのりのぞっこん未来予報♡ 〜TVサイズInstrumental〜", "中沢農(CV:花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/8bc990f9-ee9d-4388-a2f9-3529f130925c", "https://vgmdb.net/album/44544"]

[50c0690d02d9bc28f39b9cb63dddeda8]
catalognumber = "MFXN-0015EX"
date = "2014-06-04"
album = "のうりん vol.3 スペシャルCD"
tracks = [
    [1, "「発酵少女聖域」", "", 0],
    [2, "「発酵少女聖域」 instr.", "", 0],
]
links = ["https://vgmdb.net/album/44545"]

[d96b86690035f6c5a32421942d3e58bb]
catalognumber = "MFXN-0016EX"
date = "2014-07-02"
album = "のうりん vol.4 スペシャルCD"
tracks = [
    [1, "ポニーテールの四十", "戸次菜摘(CV: 斎藤千和)", 0],
    [2, "ポニーテールの四十 ～TVサイズ～", "戸次菜摘(CV: 斎藤千和)", 0],
    [3, "ポニーテールの四十 ～Instrumental～", "戸次菜摘(CV: 斎藤千和)", 0],
    [4, "ポニーテールの四十 ～TVサイズInstrumental～", "戸次菜摘(CV: 斎藤千和)", 0],
]
links = ["https://beta.musicbrainz.org/release/5905075b-71e5-4384-9773-ad04f91bbc37", "https://vgmdb.net/album/44546"]

[098a293252d59b93ee7744f470ced679]
catalognumber = "MFXN-0017EX"
date = "2014-08-06"
album = "のうりん vol.5 スペシャルCD"
tracks = [
    [1, "君と＊にゅう＊DAY♡", "良田胡蝶(CV: 井上麻里奈)", 0],
    [2, "君と＊にゅう＊DAY♡ ~TV Size~", "良田胡蝶(CV: 井上麻里奈)", 0],
    [3, "君と＊にゅう＊DAY♡ ~Instrumental~", "良田胡蝶(CV: 井上麻里奈)", 0],
    [4, "君と＊にゅう＊DAY♡ ~TV Size Instrumental~", "良田胡蝶(CV: 井上麻里奈)", 0],
]
links = ["https://beta.musicbrainz.org/release/f51db57f-4cba-4586-b065-54d81f362117", "https://vgmdb.net/album/44547"]

[c8eb09fa84660b0e0014b39869690260]
catalognumber = "BECKY-0040"
date = "2014-09-03"
album = "Everyday加齢臭 / AKB40(CV:斎藤千和)"
tracks = []
links = ["https://vgmdb.net/album/56076"]

[8b10654ee8a2d363568a129661b921ee]
catalognumber = "MFXN-0018EX"
date = "2014-09-03"
album = "のうりん vol.6 スペシャルCD"
tracks = [
    [1, "コードレス☆照れ☆PHONE～木下林檎バージョン～", "", 0],
    [2, "耕作のテーマ～ハイテンション～", "", 0],
    [3, "耕作のテーマ～真心～", "", 0],
    [4, "耕作のテーマ～夢を語る～", "", 0],
    [5, "耕作のテーマ～絶望～", "", 0],
    [6, "林檎のテーマ～純真～", "", 0],
    [7, "林檎のテーマ～傷心～", "", 0],
    [8, "農のテーマ～厳しい～", "", 0],
    [9, "農のテーマ～わくわく～", "", 0],
    [10, "良田さんのテーマ", "", 0],
    [11, "継のテーマ", "", 0],
    [12, "ベッキーのテーマ～くどい～", "", 0],
    [13, "ベッキーのテーマ～エロい～", "", 0],
    [14, "バイオ鈴木のテーマ", "", 0],
    [15, "マネー金上のテーマ", "", 0],
    [16, "ウッドマン林太郎のテーマ", "", 0],
    [17, "ローズ花園のテーマ", "", 0],
    [18, "不気味な四天農", "", 0],
    [19, "熱血四天農", "", 0],
    [20, "田茂農林のまったりした日常", "", 0],
    [21, "田茂農林の楽しい日常", "", 0],
    [22, "田茂農林のワイルドな日常", "", 0],
    [23, "青田寮のゆるい生活", "", 0],
    [24, "青田寮の素敵な生活", "", 0],
    [25, "王様ゲーム", "", 0],
    [26, "ビキニアーマーVSハイレグアーマー", "", 0],
    [27, "スーパーロボットバトル風", "", 0],
    [28, "「旧スク」とは", "", 0],
    [29, "猿対策会議", "", 0],
    [30, "ガイアからのメッセージ", "", 0],
    [31, "悲しい過去", "", 0],
    [32, "ポッキン勝負", "", 0],
    [33, "林檎、大豆を撒く！", "", 0],
    [34, "狂乱のマネーゲーム", "", 0],
    [35, "「もえたま!」CM", "", 0],
    [36, "ざわ…", "", 0],
    [37, "独神(ヒトリガミ)参上", "", 0],
    [38, "ベッキーの人生", "", 0],
    [39, "「何か夏っぽい音楽」", "", 0],
    [40, "結婚行進曲(雅楽)", "", 0],
    [41, "プロジェクトガイア", "", 0],
    [42, "収穫の喜び", "", 0],
    [43, "コードレス☆照れ☆PHONE～木下林檎バージョン～instrumental", "", 0],
]
links = ["https://vgmdb.net/album/44548"]

[d5de22e6f29b3455d170df96ed38fa2c]
catalognumber = "N/A"
date = "2015-03-14"
album = "のうりん ドラマCD 最後の寮生"
tracks = []
links = ["https://vgmdb.net/album/80803"]

[8c9093aeb215238471ddb1595a79f23c]
catalognumber = "N/A"
date = "2016-03-25"
album = "Everyday加齢臭 / AKB40(CV:斎藤千和)"
tracks = []
links = ["https://vgmdb.net/album/56077"]

[3b820efb8e57565dc1d92b9deff93d7c]
catalognumber = "SVWC-70189~90"
date = "2016-08-30"
album = "KANAight ～花澤香菜キャラソン ハイパークロニクルミックス～ Disc 1 [SVWC-70189]"
tracks = [
    [1, "恋愛サーキュレーション -Yunomi \"Kawaii EDM\" Remix-", "", 0],
    [2, "リカバーデコレーション -Hymn to the Queen Remix-", "", 0],
    [3, "Delicateにラブ・ミー・プリーズ -More Delicate Remix-", "", 0],
    [4, "モノクロ☆HAPPY DAY -Small Chic Dance Remix-", "", 0],
    [5, "おしえてナウカ、夢みるペチカ -cozy analog Remix-", "", 0],
    [6, "もうそう♡えくすぷれす -folclore Remix-", "", 0],
    [7, "sweets parade -lyrical Remix-", "", 0],
]
links = ["https://vgmdb.net/album/65499"]

[e2b7eec1fc655b50130c2ab6cc9f1589]
catalognumber = "SVWC-70189~90"
date = "2016-08-30"
album = "KANAight ～花澤香菜キャラソン ハイパークロニクルミックス～ Disc 2 [SVWC-70190]"
tracks = [
    [1, "恋するマドモアゼル", "シャルロット・デュノア(花澤香菜)", 0],
    [2, "I wonder why…", "向井戸まなか(花澤香菜)", 0],
    [3, "シナプスの鏡", "邪神かがみ(花澤香菜)", 0],
    [4, "みどりのメロディ", "草野(花澤香菜)", 0],
    [5, "Raison d'etre", "汐宮栞(花澤香菜)", 0],
    [6, "Delicateにラブ・ミー・プリーズ", "ざんげちゃん(花澤香菜)", 0],
    [7, "ソレイユ・ブーケ", "シャルロット・デュノア(花澤香菜)", 0],
    [8, "モノクロ☆HAPPY DAY", "黒猫(花澤香菜)", 0],
    [9, "キミをマモリタイ", "市ヶ谷りか(花澤香菜)", 0],
    [10, "ヘンな神様知ってるよ", "乱崎優歌(花澤香菜)", 0],
    [11, "Qunka!", "板東まりも(花澤香菜)", 0],
    [12, "HEAVEN's TALE", "ベンヤ(花澤香菜)", 0],
    [13, "バンブー・ランデヴー♡", "メイメイ(花澤香菜)", 0],
    [14, "迷惑スペクタクル", "横井るみ(花澤香菜)", 0],
    [15, "まじかる☆まーじゃん☆わーるど (ver.玄)", "松実玄(花澤香菜)", 0],
    [16, "Punctuation!", "松隆奈々子(花澤香菜)", 0],
    [17, "自主恋Shoooooter!", "湊智花(花澤香菜)", 0],
    [18, "君色*コンプリート", "双葉アオイ(花澤香菜)", 0],
    [19, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(花澤香菜)", 0],
    [20, "Dazzling Smile", "マリー(花澤香菜)", 0],
    [21, "ハッピーガール☆ラッキーガール!", "桜市子(花澤香菜)", 0],
    [22, "ダンジョン ショコラティエース", "シロ(花澤香菜)", 0],
    [23, "おにくじゃぽねすく!", "ゼウシくん(花澤香菜)", 0],
    [24, "プリコグ (M@STER VERSION)", "水谷絵理(花澤香菜)", 0],
    [25, "みのりのぞっこん未来予報♡", "中沢農(花澤香菜)", 0],
    [26, "君らしくなきゃヤダよ!", "結城美柑(花澤香菜)", 0],
    [27, "私がモテないのは可愛くないからだよね?", "ゆうちゃん(花澤香菜)", 0],
    [28, "心の窓辺にて", "双葉アオイ(花澤香菜)", 0],
    [29, "もうそう♡えくすぷれす", "千石撫子(花澤香菜)", 0],
    [30, "sweets parade", "髏々宮カルタ(花澤香菜)", 0],
    [31, "リカバーデコレーション", "小野寺小咲(花澤香菜)", 0],
    [32, "スプーンひとさじの愛", "宮野まゆ(花澤香菜)", 0],
    [33, "恋愛サーキュレーション", "千石撫子(花澤香菜)", 0],
    [34, "あした来る日〜桜咲くころ", "花戸小鳩(花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/af9b0033-666b-42e6-be05-cb4280729814", "https://vgmdb.net/album/65499"]

[a879b3c1ad1ba7beb1f3e6eed9377509]
catalognumber = "BRMM-10632"
date = "2023-05-31"
album = "Pastel à la mode / Pastel*Palettes Disc 1"
tracks = [
    [1, "はなまる◎アンダンテ", "Pastel＊Palettes", 0],
    [2, "パスパレボリューションず☆", "Pastel＊Palettes", 0],
    [3, "SURVIVOR ねばーぎぶあっぷ！", "Pastel＊Palettes", 0],
    [4, "Wonderland Girl", "Pastel＊Palettes", 0],
    [5, "ゼッタイ宣言～Recital～", "Pastel＊Palettes", 0],
    [6, "ぎゅっDAYS♪", "Pastel＊Palettes", 0],
    [7, "Wonderful Sweet！", "Pastel＊Palettes", 0],
    [8, "るんっ♪てぃてぃー！", "Pastel＊Palettes", 0],
    [9, "パッパレ☆人生！バーン万歳！", "Pastel＊Palettes", 0],
    [10, "Brand new Pastel Road！", "Pastel＊Palettes", 0],
    [11, "あこがれacross", "Pastel＊Palettes", 0],
    [12, "ハレハレ☆フォーチュン", "Pastel＊Palettes", 0],
    [13, "ハナヒバナ", "Pastel＊Palettes", 0],
]
links = ["https://beta.musicbrainz.org/release/3bf92190-2a37-4c6c-a72f-2c47a05fac7a", "https://vgmdb.net/album/130157"]

[edc164eab497b1bf7e2b9be3245f1657]
catalognumber = "BRMM-10632"
date = "2023-05-31"
album = "Pastel à la mode / Pastel*Palettes Disc 2"
tracks = [
    [1, "そばかす", "Pastel＊Palettes", 0],
    [2, "気まぐれロマンティック", "Pastel＊Palettes", 0],
    [3, "ドリームパレード", "Pastel＊Palettes", 0],
    [4, "ラムのラブソング", "Pastel＊Palettes", 0],
    [5, "DANCE! おジャ魔女", "Pastel＊Palettes", 0],
    [6, "DISCOTHEQUE", "Pastel＊Palettes", 0],
    [7, "ゆりゆららららゆるゆり大事件", "Pastel＊Palettes", 0],
    [8, "SAKURAスキップ", "Pastel＊Palettes", 0],
    [9, "Stay Alive", "Pastel＊Palettes", 0],
    [10, "秘密の扉から会いにきて", "Pastel＊Palettes", 0],
]
links = ["https://beta.musicbrainz.org/release/3bf92190-2a37-4c6c-a72f-2c47a05fac7a", "https://vgmdb.net/album/130157"]
