[64a98acede3621d8a8ec5462fcc2ede8]
catalognumber = "LACM-4052"
date = "2002-04-24"
album = "Wake up Angel ～ねがいましては∞(無限)なり～ / Funta"
tracks = [
    [1, "Wake up Angel〜ねがいましては∞(無限)なり〜", "Funta", 1],
    [2, "We are all Dreamer", "Funta", 0],
    [3, "Wake up Angel〜ねがいましては∞(無限)なり〜 (off vocal)", "Funta", 1],
    [4, "We are all Dreamer (off vocal)", "Funta", 0],
]
links = ["https://beta.musicbrainz.org/release/cb2a70d3-e022-4d2c-baf5-c7799cf84307", "https://vgmdb.net/album/59146"]

[b788fc42ab3f850a78383ec5f9ecb0b4]
catalognumber = "LACM-4054"
date = "2002-05-22"
album = "*ちいさなまほう* / 湖太郎 (CV: 沢城みゆき)"
tracks = [
    [1, "ちいさなまほう(エンディングテーマ)", "沢城みゆき", 1],
    [2, "TROUBLE ANGEL", "沢城みゆき", 1],
    [3, "ちいさなまほう(off vocal)", "沢城みゆき", 1],
    [4, "TROUBLE Angel(off vocal)", "沢城みゆき", 1],
]
links = ["https://beta.musicbrainz.org/release/ea5f909b-bd17-4a13-bd31-52a9f3d14de2", "https://vgmdb.net/album/69840"]

[ac056095d4de95c3d6ef2f353fc3f741]
catalognumber = "LACM-4062"
date = "2002-06-26"
album = "TVアニメーション『ぴたテン』キャラクターCDシリーズVol.2 Sigh, Sigh. 小星 / 釘宮理恵"
tracks = [
    [1, "Sigh, Sigh.", "小星 (CV.釘宮理恵)", 1],
    [2, "小さな願い", "小星 (CV.釘宮理恵)", 2],
    [3, "「マイネーム イズ 小星・植松!」", "[dialogue]", 1],
    [4, "Sigh, Sigh. (off vocal)", "小星 (CV.釘宮理恵)", 1],
    [5, "小さな願い (off vocal)", "小星 (CV.釘宮理恵)", 1],
]
links = ["https://beta.musicbrainz.org/release/cdbcd777-6a33-43c9-807b-4121fda7f05d", "https://vgmdb.net/album/88449"]

[0b2555722a4c8e5d2d8ef84c4f2a2f6e]
catalognumber = "LACA-5114"
date = "2002-07-24"
album = "ぴたテン SOUNDTRACK「幸せ音楽会」Vol.1"
tracks = [
    [1, "天使の朝", "七瀬光", 1],
    [2, "湖太郎、いつもの毎日", "七瀬光", 1],
    [3, "天使の飛翔", "七瀬光", 1],
    [4, "わいわいで行こう", "七瀬光", 1],
    [5, "湖太郎と美紗", "七瀬光", 1],
    [6, "天使のラグタイム", "七瀬光", 1],
    [7, "回想", "七瀬光", 1],
    [8, "いつも大あわて", "七瀬光", 1],
    [9, "どっきりな事", "七瀬光", 1],
    [10, "ちぐはぐな関係", "七瀬光", 1],
    [11, "大ちゃん登場", "七瀬光", 1],
    [12, "ちいさなドキドキ", "七瀬光", 1],
    [13, "うれしい思いやり", "七瀬光", 1],
    [14, "薫がゆく!", "七瀬光", 1],
    [15, "天使のスキップ", "七瀬光", 1],
    [16, "楽しくて毎日", "七瀬光", 1],
    [17, "めでたし", "七瀬光", 1],
    [18, "次回は…", "七瀬光", 1],
    [19, "Wake Up Angel 〜ねがいましては∞(無限)なり〜 (TV ver.)", "Funta", 1],
    [20, "ちいさなまほう (TV ver.)", "沢城みゆき", 1],
]
links = ["https://beta.musicbrainz.org/release/cc5638cf-e4c6-43a0-9014-aea3fc3d30e3", "https://vgmdb.net/album/45441"]

[2fbbeb018c710270878a9750c72acaa2]
catalognumber = "LACA-5120"
date = "2002-10-02"
album = "TVアニメーション『ぴたテン』イメージアルバム わいわいで行こう"
tracks = [
    [1, "ドラマ「がんばった人へのがんばり方」", "[dialogue]", 0],
    [2, "うきうき☆タラッタ", "美紗(CV.田村ゆかり)", 0],
    [3, "ドラマ「教育指導の仕方」", "[dialogue]", 0],
    [4, "予感 (ショートサイズver.)", "紫亜(CV.ゆかな) & ニャー(CV.冬馬由美)", 0],
    [5, "ドラマ「おとなり天使の探り方」", "[dialogue]", 0],
    [6, "Sigh,Sigh. (ショートサイズver.)", "小星(CV.釘宮理恵)", 1],
    [7, "ドラマ「兄妹対決の仕方」", "[dialogue]", 0],
    [8, "薫のミラクル・スパイラル・ラブ!", "薫(CV.野川さくら)", 1],
    [9, "ドラマ「おなじところの見つけ方」", "[dialogue]", 0],
    [10, "TROUBLE ANGEL (ショートサイズver.)", "太郎(CV.沢城みゆき)", 1],
]
links = ["https://beta.musicbrainz.org/release/52f6cc81-3997-4b1d-a66c-7ac8e9bc8844", "https://vgmdb.net/album/65804"]

[5bccaa802d9eb182b9f4e77cc72224d1]
catalognumber = "LACA-5129"
date = "2002-10-23"
album = "ぴたテン SOUNDTRACK「幸せ音楽会」Vol.2"
tracks = [
    [1, "天使の奮闘", "七瀬光", 1],
    [2, "走る走る", "七瀬光", 1],
    [3, "夢の世界", "七瀬光", 1],
    [4, "穏やかな関係", "七瀬光", 1],
    [5, "紫亜がほんのり", "七瀬光", 1],
    [6, "紫亜的めでたし", "七瀬光", 1],
    [7, "紫亜のお手伝い", "七瀬光", 1],
    [8, "みんな元気", "七瀬光", 1],
    [9, "がんばる女の子", "七瀬光", 1],
    [10, "幼い思い出", "七瀬光", 1],
    [11, "不安と思案", "七瀬光", 1],
    [12, "小星の妄想", "七瀬光", 1],
    [13, "逃げるぞぉ…", "七瀬光", 1],
    [14, "心で思っていること", "七瀬光", 1],
    [15, "きもだめし", "七瀬光", 1],
    [16, "なかよし", "七瀬光", 1],
    [17, "妄想へと…", "七瀬光", 1],
    [18, "静かな思いやり", "七瀬光", 1],
    [19, "リゾートだ", "七瀬光", 1],
    [20, "小さな夢", "七瀬光", 1],
    [21, "日本の夏", "七瀬光", 1],
    [22, "静的描写", "七瀬光", 1],
    [23, "想いがはやる", "七瀬光", 1],
    [24, "熱い特訓", "七瀬光", 1],
    [25, "元気な朝", "七瀬光", 1],
    [26, "気まずい空気", "七瀬光", 1],
    [27, "さらに深刻に…", "七瀬光", 1],
    [28, "紫亜、美紗別れの予感", "七瀬光", 1],
    [29, "紫亜との別れ", "七瀬光", 1],
    [30, "消えるということ…", "七瀬光", 1],
    [31, "天使のハッピーエンド", "七瀬光", 1],
    [32, "今日のお話は…", "七瀬光", 1],
    [33, "アイキャッチ-1", "七瀬光", 1],
    [34, "アイキャッチ-2", "七瀬光", 1],
]
links = ["https://beta.musicbrainz.org/release/5a3ea3ad-2977-4b5c-82b2-66e264a46502", "https://vgmdb.net/album/65813"]

[b397bb6a8882dc852bab695b2f00afc7]
catalognumber = "LACA-5134"
date = "2003-01-22"
album = "TVアニメーション『ぴたテン』ヴォーカルアルバム 天使たちの合唱会"
tracks = [
    [1, "Wake up Angel ～ねがいましては∞(無限)なり～", "Funta", 1],
    [2, "うきうき☆タラッタ", "美紗(CV.田村ゆかり)", 0],
    [3, "Sigh,Sigh.", "小星 (CV.釘宮理恵)", 1],
    [4, "TROUBLE ANGEL", "沢城みゆき", 1],
    [5, "幸せになるといいな!", "美紗(CV.田村ゆかり)", 1],
    [6, "予感", "紫亜&ニャー(CV.ゆかな&冬馬由美)", 0],
    [7, "コズミック・ダイビング", "美紗(CV.田村ゆかり) & 湖太郎(CV.沢城みゆき)", 0],
    [8, "薫のミラクル・スパイラル・ラブ!", "薫(CV.野川さくら)", 1],
    [9, "なつかしい宝物", "紫亜&ニャー(CV.ゆかな&冬馬由美)", 1],
    [10, "うれしい空の飛び方", "美紗(CV.田村ゆかり)", 1],
    [11, "小さな願い", "小星 (CV.釘宮理恵)", 1],
    [12, "ちいさなまほう", "沢城みゆき", 2],
]
links = ["https://beta.musicbrainz.org/release/8eb5812f-9aea-4657-a565-747a12085c97", "https://vgmdb.net/album/65812"]

[89ec7b8b771753fa684e86b5f39ad91c]
catalognumber = "GNCA-1020"
date = "2004-08-25"
album = "Hyper Yocomix / 石田燿子"
tracks = [
    [1, "あんなに一緒だったのに", "石田燿子", 0],
    [2, "Be My Angel", "石田燿子", 0],
    [3, "Wake up Angel 〜ねがいましては∞なり〜", "石田燿子", 1],
    [4, "ギャラクシー☆ばばんがBang!", "石田燿子", 0],
    [5, "1st Priority", "石田燿子", 0],
    [6, "Shooting Star", "石田燿子", 0],
    [7, "Let Me Be With You", "石田燿子", 0],
    [8, "ヘミソフィア", "石田燿子", 0],
    [9, "コッペリアの柩", "石田燿子", 0],
    [10, "明日へのbrilliant road", "石田燿子", 0],
    [11, "ALL MY LOVE", "石田燿子", 0],
    [12, "かえりみち", "石田燿子", 0],
    [13, "永遠の花", "石田燿子", 0],
    [14, "こむぎ気分でろっくんロール", "石田燿子", 0],
    [15, "天罰!エンジェルラヴィ", "石田燿子", 0],
    [16, "カサブタ", "石田燿子", 0],
    [17, "嘆きのロザリオ", "石田燿子", 0],
    [18, "キングゲイナー・オーバー!", "石田燿子", 0],
]
links = ["https://beta.musicbrainz.org/release/f12185c0-bd2f-4c90-95b9-8dc46c849568", "https://vgmdb.net/album/21756"]

[308cfcc9cbcbbcbb2e7905913525bc14]
catalognumber = "YWRCD-117"
date = "2005-07-28"
album = "투니버스 만화영화 주제가 BEST WE3"
tracks = [
    [1, "Taxiing", "", 0],
    [2, "When I Canoe to the Paradise", "", 0],
    [3, "Promise of Victory", "", 0],
    [4, "Don't Go Alone", "", 0],
    [5, "With My Heart", "", 0],
    [6, "Nanana", "", 0],
    [7, "SOS of Love", "", 0],
    [8, "Remember Me", "", 0],
    [9, "Lifepath toward Myself", "", 0],
    [10, "Via Dolorosa", "", 0],
    [11, "To Me, You Are...", "", 0],
    [12, "Gather Around", "", 0],
    [13, "Guardian", "", 0],
    [14, "Angel's High Flying", "", 0],
    [15, "Star of Promise", "", 0],
    [16, "Look at That Sky", "", 0],
]
links = ["https://vgmdb.net/album/73228"]

[66657fe5d399d3c8c738040f5a9423e6]
catalognumber = "LACA-5415"
date = "2005-08-03"
album = "野川さくら キャラクター&テーマソングベスト Cherries"
tracks = [
    [1, "SAKURA... 舞い散る空へ", "野川さくら", 0],
    [2, "thunder of PP", "野川さくら", 0],
    [3, "心配かけてゴメンね?", "野川さくら", 0],
    [4, "今日、笑顔があれば", "野川さくら", 0],
    [5, "One Drop", "野川さくら", 0],
    [6, "ラブロケ☆パイロット", "野川さくら", 0],
    [7, "アクビ娘", "野川さくら", 0],
    [8, "Lip to Love", "野川さくら", 0],
    [9, "100%SmileJuice", "野川さくら", 0],
    [10, "竹箒にまたがって", "野川さくら", 0],
    [11, "風のMon-Ami", "野川さくら", 0],
    [12, "薫のミラクル・スパイラル・ラブ!", "野川さくら", 1],
    [13, "ぽっぴん☆らっぴん", "野川さくら", 0],
    [14, "恋のときめきチャンス!", "野川さくら", 0],
    [15, "\"bonus track\" 君色パレット ～acoustic version～", "野川さくら", 0],
]
links = ["https://beta.musicbrainz.org/release/9419a84c-c156-42f4-b1d4-9362b29e4146", "https://vgmdb.net/album/67792"]
