[f0a4f0701fc80829799ce7fede708551]
catalognumber = "ANZX-14462"
date = "2019-01-26"
album = "ぼくたちは勉強ができない オリジナル・サウンドトラックCD"
tracks = [
    [1, "ぼくたちは勉強ができない", "中山真斗", 0],
    [2, "教育係を命じる", "中山真斗", 0],
    [3, "赤点先生", "中山真斗", 0],
    [4, "ぼくたちは勉強する", "中山真斗", 0],
    [5, "まどろみの午後", "中山真斗", 0],
    [6, "やっぱり見捨てるんじゃないですか", "中山真斗", 0],
    [7, "できない気持ちがわかるのは", "中山真斗", 0],
    [8, "やっかいな気持ち", "中山真斗", 0],
    [9, "Didn't you kiss someone?", "中山真斗", 0],
    [10, "微分積分スクランブル", "中山真斗", 0],
    [11, "好きなんだ、星", "中山真斗", 0],
    [12, "機械仕掛けの親指姫", "中山真斗", 0],
    [13, "解答欄ずれてない?", "中山真斗", 0],
    [14, "誰にでも一生懸命", "中山真斗", 0],
    [15, "KOJUTO", "中山真斗", 0],
    [16, "Go!Go! Athletic", "中山真斗", 0],
    [17, "エスケープ・フロム・ザ・スクール", "中山真斗", 0],
    [18, "覚えててくれたんだ", "中山真斗", 0],
    [19, "放課後のノクターン", "中山真斗", 0],
    [20, "ファットなミジンコ", "中山真斗", 0],
    [21, "その人物の心情を答えなさい", "中山真斗", 0],
    [22, "99パーセントの努力", "中山真斗", 0],
    [23, "唯我家の食卓", "中山真斗", 0],
    [24, "頭が良くなるラグタイム", "中山真斗", 0],
]
links = ["https://beta.musicbrainz.org/release/6ebca288-81f7-4459-a533-7229e44a516d"]

[0b4265d5bfd6a351d1ffbdba3eef8a5b]
catalognumber = "SVWC-70411"
date = "2019-05-29"
album = "セイシュンゼミナール / Never Give It Up!! Disc 1"
tracks = [
    [1, "セイシュンゼミナール", "Study", 0],
    [2, "Never Give It Up!!", "Study", 0],
    [3, "セイシュンゼミナール (Instrumental)", "Study", 0],
    [4, "Never Give It Up!! (Instrumental)", "Study", 0],
]
links = ["https://beta.musicbrainz.org/release/70a02850-f1ff-417f-8282-6fb6a3130182"]

[a700444378fb9bb389436fa318c1fe70]
catalognumber = "SVWC-70412"
date = "2019-05-29"
album = "セイシュンゼミナール / Never Give It Up!! Disc 2"
tracks = [
    [1, "セイシュンゼミナール (Music Video)", "Study", 0],
    [2, "Study First Interview", "Study", 0],
]
links = ["https://beta.musicbrainz.org/release/70a02850-f1ff-417f-8282-6fb6a3130182"]

[d74c297cd6963c4a15983a9dc0d90bee]
catalognumber = "ANZX-14464"
date = "2019-07-24"
album = "ぼくたちは勉強ができない キャラクターソング1"
tracks = [
    [1, "トモダチ座", "古橋文乃(CV.白石晴香)", 0],
    [2, "トモダチ座 (off vocal)", "古橋文乃(CV.白石晴香)", 0],
]
links = ["https://beta.musicbrainz.org/release/c737e938-bf39-4944-92fb-fb0768bd356b"]

[ecc6ea71830c8ac8aa3299baa8e45629]
catalognumber = "SVWC-70436"
date = "2019-07-24"
album = "PROGRESSIVE Disc 1"
tracks = [
    [1, "ready STUDY go!", "Study", 0],
    [2, "Happy weather girl", "Study", 0],
    [3, "トゥインクルにおける［x］の現象", "Study", 0],
    [4, "打算だ!!!", "Study", 0],
    [5, "すべてが [ｘ] の世界線", "Study", 0],
    [6, "引き出せ!ポテンシャル", "Study", 0],
]
links = ["https://beta.musicbrainz.org/release/e3fc5b3e-4faa-440c-8e6d-6f53aa8b3fbf"]

[fa22824d8206bda3f3c3019101cc5241]
catalognumber = "SVWC-70436"
date = "2019-07-24"
album = "PROGRESSIVE Disc 2"
tracks = [
    [1, "ready STUDY go! (MusicVideo)", "Study", 0],
    [2, "オフショットコメンタリー映像", "Study", 0],
]
links = ["https://beta.musicbrainz.org/release/e3fc5b3e-4faa-440c-8e6d-6f53aa8b3fbf"]

[ced6b61d940719b2b0a7e339caddac32]
catalognumber = "ANZX-14466"
date = "2019-08-28"
album = "ぼくたちは勉強ができない キャラクターソング2「ことだまコンフュージョン」"
tracks = [
    [1, "ことだまコンフュージョン", "緒方理珠(CV.富田美憂)", 0],
    [2, "ことだまコンフュージョン (Instrumental)", "緒方理珠(CV.富田美憂)", 0],
]
links = ["https://beta.musicbrainz.org/release/2fc32357-b234-4cd0-a180-639c900f41a1"]

[da1e13ff05569519adb525ecdfe2f7a9]
catalognumber = "ANZX-14468"
date = "2019-09-25"
album = "ぼくたちは勉強ができない キャラクターソング3「太陽とドルフィンキック」"
tracks = [
    [1, "太陽とドルフィンキック", "武元うるか(CV.鈴代紗弓)", 0],
    [2, "太陽とドルフィンキック (Instrumental)", "武元うるか(CV.鈴代紗弓)", 0],
]
links = ["https://beta.musicbrainz.org/release/c8e655c7-9203-4fc0-bc8b-85174e3619c4"]

[d8c00f598d07fa83d284d870d5818693]
catalognumber = "SVWC-70448"
date = "2019-10-30"
album = "Can now, Can now / Study"
tracks = [
    [1, "Can now, Can now", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [2, "関係≧方程式", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [3, "ていく・あ・ぶれいく♪", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓)", 0],
    [4, "Can now, Can now(Instrumental)", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [5, "関係≧方程式(Instrumental)", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [6, "ていく・あ・ぶれいく♪(Instrumental)", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓)", 0],
]
links = ["https://beta.musicbrainz.org/release/68b51dcc-d681-493a-85e6-0bf8d3aced80", "https://vgmdb.net/album/88884"]

[4ca095710cd440ebefda30dbe1b164f0]
catalognumber = "SVWC-70446~7"
date = "2019-10-30"
album = "Can now, Can now / Study [Limited Edition] Disc 1 (CD) [SVWC-70446]"
tracks = [
    [1, "Can now, Can now", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [2, "関係≧方程式", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [3, "ていく・あ・ぶれいく♪", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓)", 0],
    [4, "Can now, Can now(Instrumental)", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [5, "関係≧方程式(Instrumental)", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓), 桐須真冬(CV.Lynn), 小美浪あすみ(CV.朝日奈丸佳)", 0],
    [6, "ていく・あ・ぶれいく♪(Instrumental)", "古橋文乃(CV.白石晴香), 緒方理珠(CV.富田美憂), 武元うるか(CV.鈴代紗弓)", 0],
]
links = ["https://beta.musicbrainz.org/release/68b51dcc-d681-493a-85e6-0bf8d3aced80", "https://vgmdb.net/album/88885"]

[98d9993d4ba0a4c9eb807243f3ea0900]
catalognumber = "SVWC-70446~7"
date = "2019-10-30"
album = "Can now, Can now / Study [Limited Edition] Disc 2 (Blu-ray) [SVWC-70447]"
tracks = [
    [1, "Can now, Can now (Music Video)", "", 0],
    [2, "Can now, Can now (MVメイキング映像)", "", 0],
]
links = ["https://vgmdb.net/album/88885"]

[e31159aeff35ab9cabc4f6a6028008ae]
catalognumber = "ANZX-14470"
date = "2019-10-30"
album = "ぼくたちは勉強ができない キャラクターソング4「次の問いに答えよ」"
tracks = [
    [1, "次の問いに答えよ", "桐須真冬(CV.Lynn)", 0],
    [2, "次の問いに答えよ (Instrumental)", "桐須真冬(CV.Lynn)", 0],
]
links = ["https://beta.musicbrainz.org/release/95beb9fc-7206-4082-b068-329cd8eafacf"]

[8aa1b752cfa9ee906f3f0eded64661f1]
catalognumber = "VVCL-1542"
date = "2019-11-13"
album = "放課後のリバティ / halca"
tracks = [
    [1, "放課後のリバティ", "halca", 0],
    [2, "Complexの事情", "halca", 0],
    [3, "A・WA・WA・WA", "halca", 0],
    [4, "放課後のリバティ -Instrumental-", "halca", 0],
    [5, "Complexの事情 -Instrumental-", "halca", 0],
    [6, "A・WA・WA・WA -Instrumental-", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/02affd2f-6e83-462a-bdca-c3da97eba223", "https://vgmdb.net/album/90148"]

[a12a7282845174a5f72c82add0171e4a]
catalognumber = "VVCL-1543~4"
date = "2019-11-13"
album = "放課後のリバティ / halca Disc 1 (CD) [VVCL-1543]"
tracks = [
    [1, "放課後のリバティ", "halca", 0],
    [2, "Complexの事情", "halca", 0],
    [3, "A・WA・WA・WA", "halca", 0],
    [4, "放課後のリバティ -TV ver.-", "halca", 0],
    [5, "放課後のリバティ -Instrumental-", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/62b2c5cb-6831-484d-9708-76ec3327c303", "https://vgmdb.net/album/90150"]

[a7059d7eb073905e2e2b3ff2ab10d8ea]
catalognumber = "VVCL-1543~4"
date = "2019-11-13"
album = "放課後のリバティ / halca Disc 2 (DVD) [VVCL-1544]"
tracks = [
    [1, "TVアニメ「ぼくたちは勉強ができない!」ノンクレジットエンディング", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/62b2c5cb-6831-484d-9708-76ec3327c303", "https://vgmdb.net/album/90150"]

[a5aaf8163007baa2a646ef5dd99f6711]
catalognumber = "VVCL-1540~1"
date = "2019-11-13"
album = "放課後のリバティ / halca Disc 2 (DVD) [VVCL-1541]"
tracks = [
    [1, "放課後のリバティ (music clip)", "", 0],
]
links = ["https://vgmdb.net/album/90149"]

[cd2f45bbe88b58be486fdf9fed6b99bf]
catalognumber = "VVCL-1540~1"
date = "2019-11-13"
album = "放課後のリバティ / halca Disc 1 (CD) [VVCL-1540]"
tracks = [
    [1, "放課後のリバティ", "halca", 0],
    [2, "Complexの事情", "halca", 0],
    [3, "A・WA・WA・WA", "halca", 0],
    [4, "放課後のリバティ -Instrumental-", "halca", 0],
    [5, "Complexの事情 -Instrumental-", "halca", 0],
    [6, "A・WA・WA・WA -Instrumental-", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/886b30b8-525d-4313-bfa5-b68f5598d009", "https://vgmdb.net/album/90149"]

[1a5462ca7c0c82899520efbe3e5d47c8]
catalognumber = "ANZX-14472"
date = "2019-11-27"
album = "ぼくたちは勉強ができない キャラクターソング5「小妖精ファイターあしゅみぃ伝説"
tracks = [
    [1, "小妖精ファイターあしゅみぃ伝説", "小美浪あすみ(CV.朝日奈丸佳)", 0],
    [2, "小妖精ファイターあしゅみぃ伝説 (Instrumental)", "小美浪あすみ(CV.朝日奈丸佳)", 0],
]
links = ["https://beta.musicbrainz.org/release/79eda8b6-abda-4913-ac07-8fcccb35a075"]

[a0c2deb7ce298fa5334007533bb7b7da]
catalognumber = "ANZX-14922"
date = "2019-12-25"
album = "ぼくたちは勉強ができない! キャラクターソング & オリジナル・サウンドトラック Vol.2"
tracks = [
    [1, "流星のち晴れ", "古橋文乃(CV.白石晴香)", 0],
    [2, "流星のち晴れ (Instrumental)", "古橋文乃(CV.白石晴香)", 0],
    [3, "近すぎて、遠い", "中山真斗", 0],
    [4, "あしたからまた頑張る", "中山真斗", 0],
    [5, "図書室は雨", "中山真斗", 0],
    [6, "初恋", "中山真斗", 0],
    [7, "ファンキードッグ&モンキーフレンズ", "中山真斗", 0],
    [8, "学習者のためのワルツ", "中山真斗", 0],
    [9, "文系エレクトロニカ", "中山真斗", 0],
    [10, "問題A", "中山真斗", 0],
    [11, "イリーガルレッスン", "中山真斗", 0],
    [12, "おしえて文乃先生", "中山真斗", 0],
    [13, "ブランクアウト・ブラックアウト", "中山真斗", 0],
    [14, "氷の女王は思考する", "中山真斗", 0],
    [15, "背伸びして見えた空", "中山真斗", 0],
    [16, "曰く、ラブコメの住人", "中山真斗", 0],
    [17, "ここからA判定", "中山真斗", 0],
    [18, "Shred", "中山真斗", 0],
    [19, "解答B", "中山真斗", 0],
    [20, "あたしよりずっと泣きたい人", "中山真斗", 0],
    [21, "ガッコウノカイダン", "中山真斗", 0],
    [22, "少女は恋を悪巧む", "中山真斗", 0],
    [23, "計画[x]", "中山真斗", 0],
    [24, "一ノ瀬学園文化祭", "中山真斗", 0],
    [25, "小妖精メイド あしゅみぃ", "中山真斗", 0],
    [26, "進路について本気出して考えてみた", "中山真斗", 0],
    [27, "あくまで友達の話", "中山真斗", 0],
    [28, "少年少女よ、大志を抱け", "中山真斗", 0],
]
links = ["https://beta.musicbrainz.org/release/8f87e24a-9568-4bbe-a69d-863a5ce2889d", "https://vgmdb.net/album/91174"]

[b4269556eb6d258c87f06bff09f483c2]
catalognumber = "ANZX-14924"
date = "2020-01-29"
album = "ぼくたちは勉強ができない! キャラクターソング「100点が取れるまで」 / 緒方理珠(CV.富田美憂)"
tracks = [
    [1, "100点が取れるまで", "緒方理珠(CV.富田美憂)", 0],
    [2, "100点が取れるまで (Instrumental)", "緒方理珠(CV.富田美憂)", 0],
]
links = ["https://beta.musicbrainz.org/release/766489e1-2b89-4980-b172-c9a9974ed4c6", "https://vgmdb.net/album/91175"]

[e70e4f8a53716dfdcd5fe004f7fe7f08]
catalognumber = "VVCL-1599"
date = "2020-02-12"
album = "Assortrip / halca"
tracks = [
    [1, "キミの隣", "halca", 0],
    [2, "one another", "halca", 0],
    [3, "うそじゃないよ", "halca", 0],
    [4, "放課後のリバティ", "halca", 0],
    [5, "be your XXX", "halca", 0],
    [6, "あの頃の僕たちを", "halca", 0],
    [7, "HORiZON", "halca", 0],
    [8, "サカナイトデイズ", "halca", 0],
    [9, "Ride on Music!", "halca", 0],
    [10, "スターティングブルー", "halca", 0],
    [11, "ハローセカイ", "halca", 0],
    [12, "センチメンタルクライシス", "halca", 0],
    [13, "サワリタイミライ", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/e7694e74-2663-4134-8060-91a4b46d6a91", "https://vgmdb.net/album/93545"]

[d7c5a3893dfd2bc42e9c9303aa94d472]
catalognumber = "VVCL-1597~8"
date = "2020-02-12"
album = "Assortrip / halca [初回限定盤B] Vocal"
tracks = [
    [1, "キミの隣", "halca", 0],
    [2, "one another", "halca", 0],
    [3, "うそじゃないよ", "halca", 0],
    [4, "放課後のリバティ", "halca", 0],
    [5, "be your XXX", "halca", 0],
    [6, "あの頃の僕たちを", "halca", 0],
    [7, "HORiZON", "halca", 0],
    [8, "サカナイトデイズ", "halca", 0],
    [9, "Ride on Music!", "halca", 0],
    [10, "スターティングブルー", "halca", 0],
    [11, "ハローセカイ", "halca", 0],
    [12, "センチメンタルクライシス", "halca", 0],
    [13, "サワリタイミライ", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/aedd9187-1445-427c-a619-3152e2fda672", "https://vgmdb.net/album/93547"]

[4534a9664d799563019f93d0b8dadfdf]
catalognumber = "VVCL-1597~8"
date = "2020-02-12"
album = "Assortrip / halca [初回限定盤B] Vocal, Live Event, Video"
tracks = [
    [1, "A・WA・WA・WA", "halca", 0],
    [2, "放課後のリバティ", "halca", 0],
    [3, "センチメンタルクライシス", "halca", 0],
    [4, "Live Document", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/aedd9187-1445-427c-a619-3152e2fda672", "https://vgmdb.net/album/93547"]

[4f4977a9af3ebca5d66265c8a00d1143]
catalognumber = "VVCL-1595~6"
date = "2020-02-12"
album = "Assortrip / halca [初回限定盤A] Disc 1 (CD) [VVCL-1595]"
tracks = [
    [1, "キミの隣", "halca", 0],
    [2, "one another", "halca", 0],
    [3, "うそじゃないよ", "halca", 0],
    [4, "放課後のリバティ", "halca", 0],
    [5, "be your XXX", "halca", 0],
    [6, "あの頃の僕たちを", "halca", 0],
    [7, "HORiZON", "halca", 0],
    [8, "サカナイトデイズ", "halca", 0],
    [9, "Ride on Music!", "halca", 0],
    [10, "スターティングブルー", "halca", 0],
    [11, "ハローセカイ", "halca", 0],
    [12, "センチメンタルクライシス", "halca", 0],
    [13, "サワリタイミライ", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/e7694e74-2663-4134-8060-91a4b46d6a91", "https://vgmdb.net/album/93546"]

[313eab1715b78f7f729fda053f1a11b6]
catalognumber = "VVCL-1595~6"
date = "2020-02-12"
album = "Assortrip / halca [初回限定盤A] Disc 2 (Blu-ray) [VVCL-1596]"
tracks = [
    [1, "キミの隣", "", 0],
    [2, "スターティングブルー", "", 0],
    [3, "センチメンタルクライシス", "", 0],
    [4, "君だけ", "", 0],
    [5, "放課後のリバティ", "", 0],
    [6, "one another", "", 0],
]
links = ["https://vgmdb.net/album/93546"]

[f79946896735926620bec223e44bd4d8]
catalognumber = "ANZX-14926"
date = "2020-02-26"
album = "ぼくたちは勉強ができない! キャラクターソング「水平線でクイックターン」 / 武元うるか(CV.鈴代紗弓)"
tracks = [
    [1, "水平線でクイックターン", "武元うるか(CV.鈴代紗弓)", 0],
    [2, "水平線でクイックターン (Instrumental)", "武元うるか(CV.鈴代紗弓)", 0],
]
links = ["https://beta.musicbrainz.org/release/a5960e47-1a24-4504-a225-16ea5629a756", "https://vgmdb.net/album/91176"]

[d9fa003ad3ce262c0d522c72a478ceb4]
catalognumber = "ANZX-14928"
date = "2020-03-25"
album = "ぼくたちは勉強ができない! キャラクターソング「My first story」 / 桐須真冬(CV.Lynn)"
tracks = [
    [1, "My first story", "桐須真冬(CV.Lynn)", 0],
    [2, "My first story (Instrumental)", "桐須真冬(CV.Lynn)", 0],
]
links = ["https://beta.musicbrainz.org/release/9a8ecd2c-4478-4d73-a312-48e683df769b", "https://vgmdb.net/album/91177"]

[26cef73c551488b6841aec6713eb384d]
catalognumber = "ANZX-14930"
date = "2020-05-27"
album = "ぼくたちは勉強ができない! キャラクターソング「明日見あげる場所」 / 小美浪あすみ(CV.朝日奈丸佳)"
tracks = [
    [1, "明日見あげる場所", "小美浪あすみ(CV.朝日奈丸佳)", 0],
    [2, "明日見あげる場所 (Instrumental)", "小美浪あすみ(CV.朝日奈丸佳)", 0],
]
links = ["https://beta.musicbrainz.org/release/11235746-3c71-4f88-a09a-78e31e9a9a61", "https://vgmdb.net/album/91178"]

[bd74d3d34646ec4eabb33a0dec09cce4]
catalognumber = "ANZX-14932"
date = "2020-06-24"
album = "ぼくたちは勉強ができない! オリジナル・サウンドトラックVol.3"
tracks = [
    [1, "ワンダー・ピュアマジック！", "Lynn, 大地葉 & 阿澄佳奈", 0],
    [2, "星空のプレリュード", "武元うるか", 0],
    [3, "才能ある者のトッケン", "中山真斗", 0],
    [4, "親子の抱える数式", "中山真斗", 0],
    [5, "一夏のディベルディメント", "中山真斗", 0],
    [6, "こんなに愛しいことはないと思わない？", "中山真斗", 0],
    [7, "最愛の星に[x]の名を", "中山真斗", 0],
    [8, "臨時休校？臨時授業！", "中山真斗", 0],
    [9, "Reckless", "中山真斗", 0],
    [10, "眠れる姫は即興にて幕を下ろす", "中山真斗", 0],
    [11, "祭りの後、夢の跡", "中山真斗", 0],
    [12, "一ノ瀬学園の伝説", "中山真斗", 0],
    [13, "仰げば尊し", "中山真斗", 0],
]
links = ["https://beta.musicbrainz.org/release/f61520aa-291e-45d6-9c27-55655b0d21a8", "https://vgmdb.net/album/91179"]

[7f854444ea2f45058c970ff13c0ab682]
catalognumber = "VVCL-2185~6"
date = "2023-01-25"
album = "nolca solca / halca [初回生産限定盤B] Vocal"
tracks = [
    [1, "時としてバイオレンス", "halca", 0],
    [2, "FIRST DROP", "halca", 0],
    [3, "weather through", "halca", 0],
    [4, "もういいや。", "halca", 0],
    [5, "あれこれドラスティック", "halca feat. 鈴木愛奈", 0],
    [6, "なんで?なんで?なんで?", "halca", 0],
    [7, "告白バンジージャンプ", "halca", 0],
    [8, "LOVEして", "halca", 0],
    [9, "誰彼スクランブル", "halca", 0],
    [10, "BUZZER BEATER", "halca", 0],
    [11, "キミがいたしるし", "halca", 0],
    [12, "ロマンティックマニフェスト", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/2152ed8a-707b-4c37-8094-99a5528fac28", "https://vgmdb.net/album/124804"]

[7a6968e1d21660a97ec7c10ff62678bf]
catalognumber = "VVCL-2185~6"
date = "2023-01-25"
album = "nolca solca / halca [初回生産限定盤B] Vocal, Live Event, Video"
tracks = [
    [1, "キュンとさせてあげるよ 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [2, "うそじゃないよ 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [3, "reprise 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [4, "サワリタイミライ 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [5, "one another 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [6, "センチメンタルクライシス 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [7, "誰彼スクランブル 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [8, "キミがいたしるし 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [9, "A・WA・WA・WA 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [10, "Knockin' on!! 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [11, "あれこれドラスティック 『Help Me!!!!!!! PRESSURE PRESSURE』", "halca", 0],
    [12, "スターティングブルー 『live playground #003』", "halca", 0],
    [13, "あれこれドラスティック 『live playground #003』", "halca", 0],
    [14, "reprise 『live playground #003』", "halca", 0],
    [15, "be your XXX 『live playground #003』", "halca", 0],
    [16, "キミがいたしるし 『live playground #003』", "halca", 0],
    [17, "誰彼スクランブル 『live playground #003』", "halca", 0],
    [18, "FIRST DROP 『live playground #003』", "halca", 0],
    [19, "放課後のリバティ 『live playground #003』", "halca", 0],
    [20, "HORiZON 『live playground #003』", "halca", 0],
]
links = ["https://beta.musicbrainz.org/release/2152ed8a-707b-4c37-8094-99a5528fac28", "https://vgmdb.net/album/124804"]
