[b957fbe36fd583cb3840117412035889]
catalognumber = "ZMCZ-12648"
date = "2018-11-28"
album = "君にふれて / 安月名莉子"
tracks = [
    [1, "君にふれて", "安月名莉子", 0],
    [2, "rise", "安月名莉子", 0],
    [3, "君にふれて (instrumental)", "安月名莉子", 0],
    [4, "rise (instrumental)", "安月名莉子", 0],
]
links = ["https://beta.musicbrainz.org/release/5777a56f-9712-40f2-acc2-0fc14e8c9592", "https://vgmdb.net/album/80208"]

[16e1c844f16af3ef6c85c2077988d575]
catalognumber = "ZMCZ-12649"
date = "2018-11-28"
album = "hectopascal / 小糸侑 (CV:高田憂希)&七海燈子 (CV:寿美菜子)"
tracks = [
    [1, "hectopascal", "小糸侑(CV:高田憂希) & 七海燈子(CV:寿美菜子)", 0],
    [2, "好き、以外の言葉で", "小糸侑(CV:高田憂希) & 七海燈子(CV:寿美菜子)", 0],
    [3, "hectopascal (instrumental)", "小糸侑(CV:高田憂希) & 七海燈子(CV:寿美菜子)", 0],
    [4, "好き、以外の言葉で (instrumental)", "小糸侑(CV:高田憂希) & 七海燈子(CV:寿美菜子)", 0],
]
links = ["https://beta.musicbrainz.org/release/b81230f0-3bac-4cfd-b613-3f4d92f8254e", "https://vgmdb.net/album/80209"]

[a3ea86e34feb1c489335ce2ec3a367c1]
catalognumber = "ZMCZ-12791"
date = "2018-12-19"
album = "TVアニメ「やがて君になる」オリジナル・サウンドトラック"
tracks = [
    [1, "そよぐ風と木漏れ日", "大島ミチル", 0],
    [2, "木漏れ日の影で", "大島ミチル", 0],
    [3, "変わらない道", "大島ミチル", 0],
    [4, "素直じゃないんだから", "大島ミチル", 0],
    [5, "回遊する想い", "大島ミチル", 0],
    [6, "遣らず雨", "大島ミチル", 0],
    [7, "君はそのままでいいんだよ", "大島ミチル", 0],
    [8, "追憶のとき", "大島ミチル", 0],
    [9, "朝陽", "大島ミチル", 0],
    [10, "昼過ぎて", "大島ミチル", 0],
    [11, "夕暮れの生徒会室", "大島ミチル", 0],
    [12, "ゆめうつつ", "大島ミチル", 0],
    [13, "ワルツ・イン・ブルーム", "大島ミチル", 0],
    [14, "希望を追いかけて", "大島ミチル", 0],
    [15, "飛翔のスケルツォ", "大島ミチル", 0],
    [16, "ふたつの吐息", "大島ミチル", 0],
    [17, "朱に染まる", "大島ミチル", 0],
    [18, "翻弄されそう", "大島ミチル", 0],
    [19, "「恋とはこんなものかしら」", "大島ミチル", 0],
    [20, "抱擁", "大島ミチル", 0],
    [21, "特別がわからない", "大島ミチル", 0],
    [22, "私を好きにならないで", "大島ミチル", 0],
    [23, "七海燈子の戸惑い", "大島ミチル", 0],
    [24, "期待と不安", "大島ミチル", 0],
    [25, "しまいこんだ記憶", "大島ミチル", 0],
    [26, "灰色の空", "大島ミチル", 0],
    [27, "揺らぐ夜", "大島ミチル", 0],
    [28, "別れの予感", "大島ミチル", 0],
    [29, "ジレンマ", "大島ミチル", 0],
    [30, "切なる願い", "大島ミチル", 0],
    [31, "心に負った傷", "大島ミチル", 0],
    [32, "孤独を抱いて", "大島ミチル", 0],
    [33, "想いが募る", "大島ミチル", 0],
    [34, "君に会いたくて", "大島ミチル", 0],
    [35, "いつか届くように", "大島ミチル", 0],
    [36, "もういちど、君を知りたい", "大島ミチル", 0],
    [37, "アイキャッチ1", "大島ミチル", 0],
    [38, "アイキャッチ2", "大島ミチル", 0],
    [39, "アイキャッチ3", "大島ミチル", 0],
]
links = ["https://beta.musicbrainz.org/release/245e089e-07a4-4354-ab4e-e4a8db5e1b50", "https://vgmdb.net/album/81114"]

[4b752a5ff19df66b92d137529f82b37e]
catalognumber = "TBZR-1073~4"
date = "2019-01-30"
album = "ラジオCD やがて君になる～私、このラジオ好きになりそう～ Vol.1"
tracks = []
links = ["https://vgmdb.net/album/84108"]

[37f667593e8cfef2ca86b137332eb8be]
catalognumber = "TBZR-1095~6"
date = "2019-05-29"
album = "ラジオCD やがて君になる～私、このラジオ好きになりそう～ Vol.2"
tracks = []
links = ["https://vgmdb.net/album/85683"]

[a0a3bba4e2c667b77741d2d97253c065]
catalognumber = "ZMCZ-16541"
date = "2023-03-29"
album = "BLUE MOON / 安月名莉子"
tracks = [
    [1, "Memories", "安月名莉子", 0],
    [2, "君にふれて", "安月名莉子", 0],
    [3, "Whiteout", "安月名莉子", 0],
    [4, "花", "安月名莉子", 0],
    [5, "Glow at the Velocity of Light", "安月名莉子", 0],
    [6, "be perfect, plz!", "安月名莉子", 0],
    [7, "keep weaving your spider way", "安月名莉子", 0],
    [8, "Chance! & Revenge!", "安月名莉子", 0],
    [9, "知らなきゃ", "安月名莉子", 0],
    [10, "selfish", "安月名莉子", 0],
    [11, "かたち", "安月名莉子", 0],
    [12, "BLUE CYALUME", "安月名莉子", 0],
]
links = ["https://beta.musicbrainz.org/release/f648f806-44b1-426c-83f5-039895f2d950", "https://vgmdb.net/album/126385"]

[d0e1d8abcb92bd704b92977f5e4903e6]
catalognumber = "DV12784"
date = "2023-07-08"
album = "Bloom Into You Original Soundtrack"
tracks = [
    [1, "Komorebi no Kage de", "", 0],
    [2, "Kaiyuusuru Omoi", "", 0],
    [3, "Kimi wa Sono Mama de iinda yo", "", 0],
    [4, "Asahi", "", 0],
    [5, "Futatsu no Toiki", "", 0],
    [6, "Honrou Saresou", "", 0],
    [7, "Houyou", "", 0],
    [8, "Tokubetsu ga Wakaranai", "", 0],
    [9, "Watashi wo Suki ni Naranai de", "", 0],
    [10, "Nanami Touko no Tomadoi", "", 0],
    [11, "Kitai to Fuan", "", 0],
    [12, "Shimaikonda Kioku", "", 0],
    [13, "Yuragu Yoru", "", 0],
    [14, "Setsunaru Negai", "", 0],
    [15, "Kodoku wo Daite", "", 0],
    [16, "Omoi ga Tsunoru", "", 0],
    [17, "Kimi ni Aitakute", "", 0],
    [18, "Eye-Catch 1", "", 0],
    [19, "Eye-Catch 2", "", 0],
    [20, "Eye-Catch 3", "", 0],
]
links = ["https://vgmdb.net/album/134870"]
