[7967230c9efca97857a2f53e50ed736c]
catalognumber = "GNCA-0395"
date = "2015-08-26"
album = "初めてガールズ!"
tracks = [
    [1, "初めてガールズ!", "Ray", 1],
    [2, "My Future", "Ray", 1],
    [3, "初めてガールズ!", "一年藤組", 1],
    [4, "初めてガールズ! <instrumental>", "Ray", 1],
    [5, "My Future <instrumental>", "Ray", 1],
]
links = ["https://beta.musicbrainz.org/release/33553099-4022-4305-9744-c3ff2815fd6f"]
