[1072b5ebc5f64a258c2d7613886b457a]
catalognumber = "TFDS-00765"
date = "2022-04-15"
album = "星が泳ぐ / マカロニえんぴつ"
tracks = [
    [1, "星が泳ぐ", "マカロニえんぴつ", 0],
]
links = ["https://beta.musicbrainz.org/release/6aee3485-4a73-4892-a61f-65c23db76129", "https://vgmdb.net/album/119675"]

[39d69b5f1e1ec11fb9a31f1a0a20a869]
catalognumber = "USSW-0343"
date = "2022-04-27"
album = "回夏 / cadode"
tracks = [
    [1, "回夏", "cadode", 0],
    [2, "光", "cadode", 0],
    [3, "カオサン通り (band)", "cadode", 0],
    [4, "回夏 -karaoke-", "cadode", 0],
    [5, "光 -karaoke-", "cadode", 0],
    [6, "カオサン通り (band) -karaoke-", "cadode", 0],
    [7, "回夏 -Instrumental-", "cadode", 0],
    [8, "光 -Instrumental-", "cadode", 0],
    [9, "カオサン通り (band) -Instrumental-", "cadode", 0],
]
links = ["https://beta.musicbrainz.org/release/52532761-4bcf-4523-a604-f7d033461400", "https://vgmdb.net/album/118399"]

[36c69ff0d1b5ed9d5f9539aaf8c0077c]
catalognumber = "USSW-0342"
date = "2022-04-27"
album = "回夏 / cadode [アニメ盤] Vocal, Live Event, Video"
tracks = [
    [1, "ワンダー", "cadode", 0],
    [2, "あの夏で待ってる", "cadode", 0],
    [3, "明後日に恋をする", "cadode", 0],
    [4, "タイムマシンに乗るから", "cadode", 0],
    [5, "回夏", "cadode", 0],
    [6, "光", "cadode", 0],
]
links = ["https://beta.musicbrainz.org/release/4fd4b2c9-2e7b-44c0-b520-401471032bf0", "https://vgmdb.net/album/118400"]

[520666a3110b6a00267c08c838fb2387]
catalognumber = "USSW-0342"
date = "2022-04-27"
album = "回夏 / cadode [アニメ盤] Vocal"
tracks = [
    [1, "回夏", "cadode", 0],
    [2, "光", "cadode", 0],
    [3, "カオサン通り (band)", "cadode", 0],
    [4, "回夏 -karaoke-", "cadode", 0],
    [5, "光 -karaoke-", "cadode", 0],
    [6, "カオサン通り (band) -karaoke-", "cadode", 0],
    [7, "回夏 -Instrumental-", "cadode", 0],
    [8, "光 -Instrumental-", "cadode", 0],
    [9, "カオサン通り (band) -Instrumental-", "cadode", 0],
]
links = ["https://beta.musicbrainz.org/release/4fd4b2c9-2e7b-44c0-b520-401471032bf0", "https://vgmdb.net/album/118400"]

[76c2e3d55d4ca546898732856312a649]
catalognumber = "TFCC-86863"
date = "2022-06-22"
album = "たましいの居場所 / マカロニえんぴつ"
tracks = [
    [1, "たましいの居場所", "マカロニえんぴつ", 0],
    [2, "星が泳ぐ", "マカロニえんぴつ", 0],
    [3, "街中華☆超愛", "マカロニえんぴつ", 0],
    [4, "僕らは夢の中", "マカロニえんぴつ", 0],
]
links = ["https://beta.musicbrainz.org/release/6c84c6a2-b157-4463-84d2-a336c6003a92", "https://vgmdb.net/album/119688"]

[e2a30678d67bafb4c648b0afeaef6054]
catalognumber = "TFCC-86861~2"
date = "2022-06-22"
album = "たましいの居場所 / マカロニえんぴつ [初回生産限定盤] Vocal"
tracks = [
    [1, "たましいの居場所", "マカロニえんぴつ", 0],
    [2, "星が泳ぐ", "マカロニえんぴつ", 0],
    [3, "街中華☆超愛", "マカロニえんぴつ", 0],
    [4, "僕らは夢の中", "マカロニえんぴつ", 0],
]
links = ["https://beta.musicbrainz.org/release/196151a1-ed90-4275-a6e1-f504c6a1cd17", "https://vgmdb.net/album/119689"]

[22904fc60a16a01f4b3608b68fc8647c]
catalognumber = "TFCC-86861~2"
date = "2022-06-22"
album = "たましいの居場所 / マカロニえんぴつ [初回生産限定盤] Vocal, Video"
tracks = [
    [1, "生きるをする", "マカロニえんぴつ", 0],
    [2, "mother", "マカロニえんぴつ", 0],
    [3, "ノンシュガー", "マカロニえんぴつ", 0],
    [4, "メレンゲ", "マカロニえんぴつ", 0],
    [5, "裸の旅人", "マカロニえんぴつ", 0],
    [6, "はしりがき", "マカロニえんぴつ", 0],
    [7, "八月の陽炎", "マカロニえんぴつ", 0],
    [8, "なんでもないよ、", "マカロニえんぴつ", 0],
    [9, "ハッピーエンドへの期待は", "マカロニえんぴつ", 0],
    [10, "好きだった(はずだった)", "マカロニえんぴつ", 0],
    [11, "キスをしよう", "マカロニえんぴつ", 0],
    [12, "星が泳ぐ", "マカロニえんぴつ", 0],
    [13, "なんでもないよ、 (OKKAKE Long ver.)", "マカロニえんぴつ", 0],
]
links = ["https://beta.musicbrainz.org/release/196151a1-ed90-4275-a6e1-f504c6a1cd17", "https://vgmdb.net/album/119689"]

[9157d9a32b9ea7e58df14ba62a1da30a]
catalognumber = "TFDS-00797"
date = "2022-07-08"
album = "失恋ソング沢山聴いて 泣いてばかりの私はもう。 / りりあ。"
tracks = [
    [1, "失恋ソング沢山聴いて 泣いてばかりの私はもう。", "りりあ。", 0],
]
links = ["https://beta.musicbrainz.org/release/93360dff-5e9b-45f6-b6fa-d8bc79e33d07", "https://vgmdb.net/album/121271"]

[b8b026201eec41fdf9fec515f095643b]
catalognumber = "USSW-0369"
date = "2022-08-10"
album = "夏夢ノイジー / 亜咲花 [アニメ盤]"
tracks = [
    [1, "夏夢ノイジー", "亜咲花", 0],
    [2, "VOICE", "亜咲花", 0],
    [3, "dreamer", "亜咲花", 0],
    [4, "夏夢ノイジー (off vocal)", "亜咲花", 0],
    [5, "VOICE (off vocal)", "亜咲花", 0],
    [6, "dreamer (off vocal)", "亜咲花", 0],
]
links = ["https://beta.musicbrainz.org/release/0a0bf369-819a-414b-a33a-9139c14cc847", "https://vgmdb.net/album/121086"]

[373f777078310b5059ba831f42014be1]
catalognumber = "USSW-0368"
date = "2022-08-10"
album = "夏夢ノイジー / 亜咲花 [DVD付盤] Vocal"
tracks = [
    [1, "夏夢ノイジー", "亜咲花", 0],
    [2, "VOICE", "亜咲花", 0],
    [3, "dreamer", "亜咲花", 0],
    [4, "夏夢ノイジー (off vocal)", "亜咲花", 0],
    [5, "VOICE (off vocal)", "亜咲花", 0],
    [6, "dreamer (off vocal)", "亜咲花", 0],
]
links = ["https://beta.musicbrainz.org/release/b2d6cc55-58b4-4bb7-b930-be2b6a4e5968", "https://vgmdb.net/album/121085"]

[dff4ff8e55be8615df709bbf5bd1221d]
catalognumber = "USSW-0368"
date = "2022-08-10"
album = "夏夢ノイジー / 亜咲花 [DVD付盤] Vocal, Video"
tracks = [
    [1, "夏夢ノイジー (Music Video)", "亜咲花", 0],
    [2, "夏夢ノイジー (Music Video Making Movie)", "亜咲花", 0],
]
links = ["https://beta.musicbrainz.org/release/b2d6cc55-58b4-4bb7-b930-be2b6a4e5968", "https://vgmdb.net/album/121085"]

[3bbf0719a9dc06735cbb9b64fff69068]
catalognumber = "USSW-0379"
date = "2022-08-31"
album = "TVアニメ『サマータイムレンダ』オリジナル・サウンドトラック Disc 1 [USSW-0379-1]"
tracks = [
    [1, "渦", "高田龍一", 0],
    [2, "潮騒", "岡部啓一", 0],
    [3, "陽炎", "高田龍一", 0],
    [4, "共鳴", "岡部啓一", 0],
    [5, "張力", "帆足圭吾", 0],
    [6, "影法師", "帆足圭吾", 0],
    [7, "引力", "岡部啓一", 0],
    [8, "反射", "高田龍一", 0],
    [9, "沈力", "高田龍一", 0],
    [10, "心騒ぎ", "高田龍一", 0],
    [11, "澱", "帆足圭吾", 0],
    [12, "深夏", "高田龍一", 0],
    [13, "脳溝", "帆足圭吾", 0],
    [14, "臨影", "岡部啓一", 0],
    [15, "浮力", "高田龍一", 0],
    [16, "洞", "岡部啓一", 0],
    [17, "波の綾", "帆足圭吾", 0],
    [18, "異形乃輪", "岡部啓一", 0],
    [19, "凪", "帆足圭吾", 0],
    [20, "漣", "高田龍一", 0],
    [21, "狂濤", "岡部啓一", 0],
    [22, "砕波", "岡部啓一", 0],
    [23, "溺迫", "岡部啓一", 0],
    [24, "対峙", "高田龍一", 0],
    [25, "迷ひ路", "帆足圭吾", 0],
    [26, "絶つ望", "高田龍一", 0],
    [27, "葛藤", "高田龍一", 0],
    [28, "軋轢", "高田龍一", 0],
    [29, "惑戦", "帆足圭吾", 0],
    [30, "遁走", "岡部啓一", 0],
]
links = ["https://beta.musicbrainz.org/release/24ea0932-781d-476f-9c47-14abe2a48fe5", "https://vgmdb.net/album/121600"]

[cd8477269713b7c7c0d2a157babe3967]
catalognumber = "USSW-0379"
date = "2022-08-31"
album = "TVアニメ『サマータイムレンダ』オリジナル・サウンドトラック Disc 2 [USSW-0379-2]"
tracks = [
    [1, "電子泥", "高田龍一", 0],
    [2, "物案じ", "高田龍一", 0],
    [3, "危礁", "高田龍一", 0],
    [4, "月灯", "帆足圭吾", 0],
    [5, "傀儡争", "高田龍一", 0],
    [6, "影息吹", "帆足圭吾", 0],
    [7, "垂", "帆足圭吾", 0],
    [8, "日都ケ島手毬唄", "帆足圭吾", 0],
    [9, "湿力", "高田龍一", 0],
    [10, "修羅火", "岡部啓一", 0],
    [11, "白い青", "高田龍一", 0],
    [12, "呟奇譚", "岡部啓一", 0],
    [13, "鎮魂", "高田龍一", 0],
    [14, "生謡", "岡部啓一", 0],
    [15, "霧這", "岡部啓一", 0],
    [16, "鯨閃", "岡部啓一、高田龍一", 0],
    [17, "波稲", "岡部啓一", 0],
    [18, "墨斗兵", "岡部啓一", 0],
    [19, "薫風", "高田龍一", 0],
    [20, "潜思", "岡部啓一", 0],
    [21, "記憶", "帆足圭吾", 0],
    [22, "和心地", "岡部啓一", 0],
    [23, "陰陽", "帆足圭吾", 0],
    [24, "疾波闘", "帆足圭吾", 0],
    [25, "破綻", "帆足圭吾", 0],
    [26, "再輝動", "帆足圭吾", 0],
    [27, "翻命", "帆足圭吾", 0],
    [28, "島風", "帆足圭吾", 0],
    [29, "輪廻", "帆足圭吾", 0],
]
links = ["https://beta.musicbrainz.org/release/24ea0932-781d-476f-9c47-14abe2a48fe5", "https://vgmdb.net/album/121600"]

[2a78bd50612f1b8fd4215ea33fa8911d]
catalognumber = "USSW-0400"
date = "2023-01-25"
album = "浮遊バグ / cadode [限定盤] Vocal, Live Event, Video"
tracks = [
    [1, "1st Oneman「独演 回夏迄」Live Movie", "cadode", 0],
    [2, "「浮いちまった︕」Making Movie", "cadode", 0],
]
links = ["https://beta.musicbrainz.org/release/43d75056-b47e-403f-af7c-ab67cb6ef364", "https://vgmdb.net/album/124786"]

[9edf498bf4259ff69ad5fd26eae35696]
catalognumber = "USSW-0400"
date = "2023-01-25"
album = "浮遊バグ / cadode [限定盤] Vocal"
tracks = [
    [1, "さかいめだらけ", "cadode", 0],
    [2, "浮いちまった!", "cadode", 0],
    [3, "寺にでも行こうぜ", "cadode", 0],
    [4, "回夏", "cadode", 0],
    [5, "逆風", "cadode", 0],
    [6, "シュウ末紀行", "cadode", 0],
    [7, "hunch", "cadode", 0],
    [8, "かたばみ", "cadode", 0],
    [9, "光", "cadode", 0],
    [10, "近道", "cadode", 0],
]
links = ["https://beta.musicbrainz.org/release/43d75056-b47e-403f-af7c-ab67cb6ef364", "https://vgmdb.net/album/124786"]

[ee5f6d9f664487238e7b2b3ea40f4c1a]
catalognumber = "USSW-0401"
date = "2023-01-25"
album = "浮遊バグ / cadode"
tracks = [
    [1, "さかいめだらけ", "cadode", 0],
    [2, "浮いちまった!", "cadode", 0],
    [3, "寺にでも行こうぜ", "cadode", 0],
    [4, "回夏", "cadode", 0],
    [5, "逆風", "cadode", 0],
    [6, "シュウ末紀行", "cadode", 0],
    [7, "hunch", "cadode", 0],
    [8, "かたばみ", "cadode", 0],
    [9, "光", "cadode", 0],
    [10, "近道", "cadode", 0],
]
links = ["https://beta.musicbrainz.org/release/25b1d1bc-62ee-4404-976b-fe72d17ab667", "https://vgmdb.net/album/124785"]

[d1c9d2718799a54af48ab8d3b740ff5c]
catalognumber = "USSW-0413"
date = "2023-06-28"
album = "Who's Me? / 亜咲花 [DVD付盤] Disc 2 (DVD) [USSW-0413-2]"
tracks = [
    [1, "Triple Crown (Music Video)", "亜咲花", 0],
    [2, "Triple Crown (Music Video Making Movie)", "亜咲花", 0],
]
links = ["https://beta.musicbrainz.org/release/ecad82f8-5cf5-4c9e-8acd-f0bd42f300d8", "https://vgmdb.net/album/128873"]

[771db168d080a9ef9c9325b75a7df878]
catalognumber = "USSW-0413"
date = "2023-06-28"
album = "Who's Me? / 亜咲花 [DVD付盤] Disc 1 (CD) [USSW-0413-1]"
tracks = [
    [1, "Triple Crown", "亜咲花", 0],
    [2, "No.1", "亜咲花", 0],
    [3, "Life Goes On", "亜咲花", 0],
    [4, "Sun Is Coming Up", "亜咲花", 0],
    [5, "Easy Life, Easy Curry -カレーメシのうた-", "亜咲花", 0],
    [6, "See The Light", "亜咲花", 0],
    [7, "Ready Set Go!!", "亜咲花", 0],
    [8, "夏夢ノイジー", "亜咲花", 0],
    [9, "BELIEVE MYSELF", "亜咲花", 0],
    [10, "光と影のラプラス", "亜咲花", 0],
    [11, "Mob's God's", "亜咲花", 0],
    [12, "燈火", "亜咲花", 0],
    [13, "Trust My Heart", "亜咲花", 0],
    [14, "バラッド", "亜咲花", 0],
    [15, "追想", "亜咲花", 0],
]
links = ["https://beta.musicbrainz.org/release/ecad82f8-5cf5-4c9e-8acd-f0bd42f300d8", "https://vgmdb.net/album/128873"]

[6c9f697496bcff7eb6cce8d158465fd5]
catalognumber = "USSW-0414"
date = "2023-06-28"
album = "Who's Me? / 亜咲花"
tracks = [
    [1, "Triple Crown", "亜咲花", 0],
    [2, "No.1", "亜咲花", 0],
    [3, "Life Goes On", "亜咲花", 0],
    [4, "Sun Is Coming Up", "亜咲花", 0],
    [5, "Easy Life, Easy Curry -カレーメシのうた-", "亜咲花", 0],
    [6, "See The Light", "亜咲花", 0],
    [7, "Ready Set Go!!", "亜咲花", 0],
    [8, "夏夢ノイジー", "亜咲花", 0],
    [9, "BELIEVE MYSELF", "亜咲花", 0],
    [10, "光と影のラプラス", "亜咲花", 0],
    [11, "Mob's God's", "亜咲花", 0],
    [12, "燈火", "亜咲花", 0],
    [13, "Trust My Heart", "亜咲花", 0],
    [14, "バラッド", "亜咲花", 0],
    [15, "追想", "亜咲花", 0],
]
links = ["https://beta.musicbrainz.org/release/39f00cbb-fcd2-48f5-859c-160473594604", "https://vgmdb.net/album/128872"]
