[8fdbb03603c1b30e8a20d640d2934786]
catalognumber = "KICA-7631~2"
date = "1994-02-23"
album = "コナミ・アミューズメントサウンズ'94…春 Disc 1 [KICA-7631]"
tracks = [
    [1, "戦闘準備完了！ (プレイヤー格納庫デモ音楽)", "", 0],
    [2, "ターゲットを選べ！ (スタッフエントリーBGM)", "", 0],
    [3, "おれたちが相手だ！ (ステージ紹介デモ)", "", 0],
    [4, "突撃！ (フィールド降下時ファンファーレ)", "", 0],
    [5, "ゆけゆけウォリアーズ (えすえふ、だんじょん、べーすステージBGM)", "", 0],
    [6, "きのこのこ (ろっく、きのこのこステージBGM)", "", 0],
    [7, "どんとこいアミーゴ！ (がーでん、さぼてんステージBGM)", "", 0],
    [8, "ゴーゴーポリネット！ (じーぴー、してぃーステージBGM)", "", 0],
    [9, "ワルダー城　(おしろステージBGM)", "", 0],
    [10, "ピンボール (ぴんぼーるステージBGM)", "", 0],
    [11, "時間がないぞ！ (ラスト30BGM)", "", 0],
    [12, "やられちまった！ (「xxにやられた」デモBGM)", "", 0],
    [13, "やったぜベイビー (エンディングBGM)", "", 0],
    [14, "ポリネット戦士 (ノーマルコースエンディングデモBGM)", "", 0],
    [15, "これが噂のポリダンス (ハードコースエンディングデモBGM)", "", 0],
    [16, "正義の戦士 (スーパーハードコースエンディングデモBGM)", "", 0],
    [17, "コンティニュー (コンティニューBGM)", "", 0],
    [18, "SLAM DUNK (オープニング)", "", 0],
    [19, "LET' PLAY (モードセレクト)", "", 0],
    [20, "GO CHALLENGE (チームセレクト)", "", 0],
    [21, "TV BROADCAST (スタートデモ)", "", 0],
    [22, "L.A. (試合中BGM 1)", "", 0],
    [23, "BOSTON (試合中BGM 2)", "", 0],
    [24, "CHALOTTE (試合中BGM 3)", "", 0],
    [25, "PHOENIX (試合中BGM 4)", "", 0],
    [26, "ORLAND (試合中BGM 5)", "", 0],
    [27, "CHICAGO (試合中BGM 6)", "", 0],
    [28, "CLEVELAND (試合中BGM 7)", "", 0],
    [29, "DETROITO (試合中BGM 8)", "", 0],
    [30, "COACHING TIPS (コーチングティップス)", "", 0],
    [31, "HALF TIME SHOW (チアガールBGMイントロ～チアガールBGM)", "", 0],
    [32, "WINNER (勝敗デモ)", "", 0],
    [33, "LOSER (負けデモ)", "", 0],
    [34, "FINAL 1 (決勝戦BGM 1)", "", 0],
    [35, "FINAL 2 (決勝戦BGM 2)", "", 0],
    [36, "FINAL 3 (決勝戦BGM 3)", "", 0],
    [37, "FINAL 4 (決勝戦BGM 4)", "", 0],
    [38, "FANFARE (エンディング 1)", "", 0],
    [39, "CHAMPION (エンディング 2)", "", 0],
    [40, "GLORIOUS VICTORY (スタッフロール)", "", 0],
    [41, "CONTINUE (コンティニュー)", "", 0],
    [42, "GAME OVER (ゲームオーバー)", "", 0],
]
links = ["https://vgmdb.net/album/4468"]

[8c940442a5c52d629571447d88cb5c8f]
catalognumber = "KICA-7631~2"
date = "1994-02-23"
album = "コナミ・アミューズメントサウンズ'94…春 Disc 2 [KICA-7632]"
tracks = [
    [1, "Pleased to meet you (プレーヤー紹介デモ)", "", 0],
    [2, "Prologue (プロローグデモ)", "", 0],
    [3, "Funky guys (プレーヤーセレクト)", "", 0],
    [4, "Who'll be the hero? (1stBGM)", "", 0],
    [5, "Oh the train (2stBGM)", "", 0],
    [6, "Feel my power (3stBGM 1)", "", 0],
    [7, "Sharara's dancing～Light steps (3stBGM 2)", "", 0],
    [8, "Drifting tension (4stBGM)", "", 0],
    [9, "We are free (5stBGM)", "", 0],
    [10, "Hey! Hey! Hey! (6stBGM)", "", 0],
    [11, "The final technique (7stBGM)", "", 0],
    [12, "Who are you? (ボスstBGM 1)", "", 0],
    [13, "In the shadows (ボスstBGM 2)", "", 0],
    [14, "VS Geldo (最終ボスst)", "", 0],
    [15, "Kick it! (ステージクリア)", "", 0],
    [16, "Out of luck! (ゲームオーバー)", "", 0],
    [17, "Nice fight. Congraturations! (ネーミング)", "", 0],
    [18, "Are you ready to have a good time? (エンディング)", "", 0],
    [19, "Who'll be the hero? (DJ Mix Version～F.O.) (ボーナストラック)", "", 0],
    [20, "ZERO G (タイトルロゴ)", "", 0],
    [21, "FRONTLINE ASSEMBLY (セレクト)", "", 0],
    [22, "ORIENTRANCE ～RADIOACTIVITY MIX～ (空き地ステージ)", "", 0],
    [23, "ENERGY HIGH (高速道路ステージ)", "", 0],
    [24, "BRAIN EXPANDER (神殿跡ステージ)", "", 0],
    [25, "KNIGHT HORSE ～TRIGGER SYNC EDIT～ (市街地ステージ)", "", 0],
    [26, "DEATH BEFORE VISION (山岳地帯ステージ)", "", 0],
    [27, "BRICK PANDEMONIUM (レンガ壁ステージ)", "", 0],
    [28, "MEDITERRNEAN PAD ～LAKESIDE MIX～ (湿地帯ステージ)", "", 0],
    [29, "SECRET WEAPON ～RESISTANCE EDIT～ (ミサイル基地ステージ)", "", 0],
    [30, "HI-TECH DESTROYER (パターンクリア/GOOD)", "", 0],
    [31, "TOMORROW JUST ANOTHER SPACE (全ステージクリア)", "", 0],
    [32, "TRANSMISSION (パターンクリア/BAD)", "", 0],
    [33, "ADDITIONAL CHARGE (コンティニュー待ち)", "", 0],
    [34, "CHILL OUT (ゲームオーバー)", "", 0],
    [35, "ACKNOWLEDGEMENT (ランキング)", "", 0],
]
links = ["https://vgmdb.net/album/4468"]

[d4371852f344a5fde572c257cb33d471]
catalognumber = "JBCJ-9004"
date = "2003-07-21"
album = "THE BEST OF TV ANIMATION SLAM DUNK 〜Single Collection〜"
tracks = [
    [1, "君が好きだと叫びたい", "BAAD", 0],
    [2, "あなただけ見つめてる", "大黒摩季", 0],
    [3, "世界が終るまでは…", "WANDS", 0],
    [4, "煌めく瞬間に捕われて", "MANISH", 0],
    [5, "ぜったいに 誰も", "ZYYG", 0],
    [6, "マイ フレンド", "ZARD", 0],
    [7, "ENDLESS CHAIN 〜CINE VERSION〜", "BAAD", 0],
    [8, "煌めく瞬間に捕われて 〜CINE VERSION〜", "MANISH", 0],
]
links = ["https://beta.musicbrainz.org/release/d161ea2e-9e80-4649-80d7-873c67f711ad"]

[d612cea5a069fec4ec06146ece61e2e5]
catalognumber = "LC2208~10"
date = "2014-03-26"
album = "Third / 泉 陸奥彦 Disc 1 [LC2208]"
tracks = [
    [1, "Nature", "泉陸奥彦 feat. 菅沼孝三, Sota Fujimori, 肥塚良彦", 0],
    [2, "Daybreak", "泉陸奥彦 feat. 菅沼孝三", 0],
    [3, "Snow Goose", "Mutsuhiko Izumi", 0],
    [4, "Half Moon", "Mutsuhiko Izumi", 0],
    [5, "Polaris (Album Version)", "泉陸奥彦 feat. 細川博史", 0],
    [6, "Masterpiece Silver Ending (Album Version)", "泉陸奥彦 feat. 工藤義弘", 0],
    [7, "Double Orbit (L.A.Rider Version)", "泉陸奥彦 feat. 工藤義弘, 96", 0],
    [8, "Fairy Tales", "Mutsuhiko Izumi", 0],
    [9, "MODEL FT2", "泉陸奥彦", 0],
    [10, "BLUE BOOTS", "泉陸奥彦", 0],
    [11, "blue moon (Album Version)", "泉陸奥彦 feat. 菅沼孝三, Sota Fujimori", 0],
    [12, "Red Knit", "泉陸奥彦 feat. Jimmy Weckl", 0],
    [13, "Blue Knit", "泉陸奥彦", 0],
    [14, "Three Worms", "泉陸奥彦 feat. 則竹裕之, Jimmy Weckl", 0],
    [15, "Chicago Blue (Biginning Version)", "泉陸奥彦", 0],
    [16, "FIRE", "Mutsuhiko Izumi", 0],
    [17, "Spiral Wind", "泉陸奥彦 feat. 細川博史, 肥塚良彦", 0],
    [18, "FIFTH GIG (Album Version)", "泉陸奥彦 feat. 安田隆", 0],
    [19, "MR.MACHINE (Album Version)", "泉陸奥彦 feat. 山形秀行, 96, 肥塚良彦", 0],
    [20, "JET WORLD", "Mutsuhiko Izumi", 0],
    [21, "HYPER JET LAND", "泉陸奥彦", 0],
    [22, "THE ENDLESS SUMMER", "Mutsuhiko Izumi", 0],
    [23, "NAN QUEEN", "Mutsuhiko Izumi", 0],
    [24, "DAY DREAM (Album Version)", "泉陸奥彦 feat. 菅沼孝三", 0],
    [25, "MODEL DD3 (Album Version)", "泉陸奥彦 feat. 菅沼孝三", 0],
    [26, "MODEL DD4", "泉陸奥彦 feat. Jimmy Weckl, 小野秀幸", 0],
    [27, "MODEL DD6", "MUTSUHIKO IZUMI", 0],
    [28, "Holy Snow (Album Version)", "泉陸奥彦", 0],
]
links = ["https://beta.musicbrainz.org/release/cd6fc94a-2cb1-4db7-88d7-7d1839ac1d65", "https://vgmdb.net/album/127593"]

[6353d0d00b335414f0f769f62e753707]
catalognumber = "LC2208~10"
date = "2014-03-26"
album = "Third / 泉 陸奥彦 Disc 2 [LC2209]"
tracks = [
    [1, "WAY TO GO", "Bill Germain", 0],
    [2, "FLY HIGH", "Bill Germain", 0],
    [3, "MAGIC MUSIC MAGIC", "Melodie Sexton", 0],
    [4, "KING G", "Dennis Gunn", 0],
    [5, "WANNA BE YOUR BOY", "Dennis Gunn", 0],
    [6, "A HAND TO HOLD (Sunrise Mix)", "Angel O’Brien & Gary Adkins", 0],
    [7, "RIGHT ON TIME", "Robbie Danzie", 0],
    [8, "Not So Bad", "Brad Holmes", 0],
    [9, "AFTER A HARD DAY", "Brad Holmes", 0],
    [10, "Let Me Go", "Brad Holmes", 0],
    [11, "NO MORE CRYING", "Brenda Vaughn", 0],
    [12, "STOP THIS TRAIN", "Thomas Howard Lichtenstein", 0],
    [13, "POWER", "Thomas Howard Lichtenstein", 0],
    [14, "GO GO AGAIN", "Fu Fu's", 0],
    [15, "Destiny lovers", "くにたけみゆき", 0],
    [16, "MISS YOU", "くにたけみゆき", 0],
    [17, "エンジェルマジック", "くにたけみゆき", 0],
    [18, "My Friend", "くにたけみゆき", 0],
    [19, "スタアの恋人", "くにたけみゆき", 0],
    [20, "Balance", "くにたけみゆき", 0],
    [21, "スペースカーニバル", "shooting star", 0],
    [22, "Magic words？", "森野くま子", 0],
    [23, "恋のメリーゴーランド", "森野くま子", 0],
    [24, "Happy Happy", "ki☆ki", 0],
    [25, "黄金岬", "満腹寺コトブキ", 0],
    [26, "ECO FIGHTER", "入尾信充", 0],
    [27, "Blue Earth", "KAORI", 0],
    [28, "I can be!!", "Hiromixxx", 0],
    [29, "IMITATION TOUCH", "柴田浩之", 0],
    [30, "I love マミー", "荒牧陽子", 0],
    [31, "Power Game", "荒牧陽子", 0],
    [32, "Ready Go!!", "荒牧陽子", 0],
    [33, "歌の翼", "あーたん", 0],
]
links = ["https://beta.musicbrainz.org/release/cd6fc94a-2cb1-4db7-88d7-7d1839ac1d65", "https://vgmdb.net/album/127593"]

[5542595b476a8937595e9e559d552bfa]
catalognumber = "LC2208~10"
date = "2014-03-26"
album = "Third / 泉 陸奥彦 Disc 3 [LC2210]"
tracks = [
    [1, "Zanzibar Breeze (Album Version)", "泉陸奥彦", 0],
    [2, "FIGHTING WU-SHU", "泉陸奥彦", 0],
    [3, "HONG KONG DREAM", "泉陸奥彦", 0],
    [4, "KEEPING THE FAITH", "泉陸奥彦", 0],
    [5, "STORIES FOR BOYS", "泉陸奥彦", 0],
    [6, "TITLE DEMO", "泉陸奥彦", 0],
    [7, "SELECT DEMO", "泉陸奥彦", 0],
    [8, "AD2045", "泉陸奥彦", 0],
    [9, "VIRTUAL GEAR", "泉陸奥彦", 0],
    [10, "FLYING RED CAR", "泉陸奥彦", 0],
    [11, "SPEED STAR", "泉陸奥彦", 0],
    [12, "THE FUNK", "泉陸奥彦", 0],
    [13, "IT’S A HOT", "泉陸奥彦", 0],
    [14, "JET WAVE", "泉陸奥彦", 0],
    [15, "THE RHYTHM", "泉陸奥彦", 0],
    [16, "SEA OF JOY", "泉陸奥彦", 0],
    [17, "CHECK THE BEAT", "泉陸奥彦", 0],
    [18, "ONE, TWO, THREE, FOUR", "泉陸奥彦", 0],
    [19, "DANCE!", "泉陸奥彦", 0],
    [20, "WINDING BEAT", "泉陸奥彦", 0],
    [21, "BEAT POWER", "泉陸奥彦", 0],
    [22, "CHALOTTE", "泉陸奥彦", 0],
    [23, "ORLAND", "泉陸奥彦", 0],
    [24, "CLEVELAND", "泉陸奥彦", 0],
    [25, "FINAL 2", "泉陸奥彦", 0],
    [26, "FINAL 3", "泉陸奥彦", 0],
    [27, "CONTINUE", "泉陸奥彦", 0],
    [28, "HENRY EXPLORERS", "泉陸奥彦", 0],
    [29, "A THICK FOREST", "泉陸奥彦", 0],
    [30, "SCRATCH “P”", "泉陸奥彦", 0],
    [31, "STALACTITE", "泉陸奥彦", 0],
    [32, "STAR LIGHT", "泉陸奥彦", 0],
    [33, "SPIRAL STAIR", "泉陸奥彦", 0],
    [34, "FALLING", "泉陸奥彦", 0],
    [35, "CRIMSON POWER", "泉陸奥彦", 0],
    [36, "STORM BRINGER", "泉陸奥彦", 0],
    [37, "バキャロスの遺跡", "泉陸奥彦", 0],
    [38, "４人の戦士", "泉陸奥彦", 0],
    [39, "復讐のコロシアム", "泉陸奥彦", 0],
    [40, "ガンオー現わる～森の死闘", "泉陸奥彦", 0],
    [41, "デスシャドウ", "泉陸奥彦", 0],
    [42, "恐怖のドラゴン", "泉陸奥彦", 0],
    [43, "Fire Scramble", "泉陸奥彦", 0],
    [44, "ガチャガチャンプ BGM1", "泉陸奥彦", 0],
    [45, "ガチャガチャンプ BGM2", "泉陸奥彦", 0],
    [46, "ガチャガチャンプ BGM3", "泉陸奥彦", 0],
    [47, "ガチャガチャンプ BGM4", "泉陸奥彦", 0],
    [48, "ガチャガチャンプ BGM5", "泉陸奥彦", 0],
    [49, "Humburger Men", "泉陸奥彦", 0],
    [50, "Go To Hell", "泉陸奥彦", 0],
    [51, "Revenge Of Boss", "泉陸奥彦", 0],
    [52, "Hunger City", "泉陸奥彦", 0],
    [53, "Satisfaction", "泉陸奥彦", 0],
    [54, "SWING, SWING～“A” JAM BLUES", "泉陸奥彦", 0],
    [55, "RED SUN", "泉陸奥彦", 0],
]
links = ["https://beta.musicbrainz.org/release/cd6fc94a-2cb1-4db7-88d7-7d1839ac1d65", "https://vgmdb.net/album/127593"]
