[55ed22ee0655cc3920fbfc207828c244]
catalognumber = "N/A"
date = "2018-01-14"
album = "スライム倒して300年、知らないうちにレベルMAXになってました 5 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/71900"]

[5b0ec432b86559af8f9f545a4503115f]
catalognumber = "N/A"
date = "2018-07-14"
album = "スライム倒して300年、知らないうちにレベルMAXになってました 7 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/75150"]

[e7c57a9ba195514bf56dc70b2811f99f]
catalognumber = "N/A"
date = "2019-03-15"
album = "スライム倒して300年、知らないうちにレベルMAXになってました 9 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/81730"]

[3752425e8d49062e29b5d39364fafb7f]
catalognumber = "N/A"
date = "2020-04-15"
album = "スライム倒して300年、知らないうちにレベルMAXになってました 12 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/92066"]

[5f03e68438ec270effad1e2ae7f6f40d]
catalognumber = "N/A"
date = "2020-10-15"
album = "スライム倒して300年、知らないうちにレベルMAXになってました 14 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/105237"]

[00e90a97c795ac9cf14a2f80f4f6a413]
catalognumber = "COZC-1728~9"
date = "2021-04-07"
album = "ぐだふわエブリデー / 悠木碧 [初回限定盤] Vocal"
tracks = [
    [1, "ぐだふわエブリデー", "悠木碧", 0],
    [2, "異世界管理局創造課", "悠木碧", 0],
    [3, "ぐだふわエブリデー (Instrumental)", "悠木碧", 0],
    [4, "異世界管理局情報課 (Instrumental)", "悠木碧", 0],
]
links = ["https://beta.musicbrainz.org/release/94861409-530b-48fe-893b-f7303205a021", "https://vgmdb.net/album/108459"]

[500e9f8f71ae675cfe67eb66e9dcb414]
catalognumber = "COZC-1728~9"
date = "2021-04-07"
album = "ぐだふわエブリデー / 悠木碧 [初回限定盤] Vocal, Talk, Video"
tracks = [
    [1, "ぐだふわエブリデー (ミュージックビデオ)", "", 0],
    [2, "ぐだふわエブリデー (インタビューコメント映像)", "", 0],
]
links = ["https://vgmdb.net/album/108459"]

[cc47c579e2953779b5bf7842691b09e5]
catalognumber = "COCC-17860"
date = "2021-04-07"
album = "ぐだふわエブリデー / 悠木碧"
tracks = [
    [1, "ぐだふわエブリデー", "悠木碧", 0],
    [2, "異世界管理局創造課", "悠木碧", 0],
    [3, "ぐだふわエブリデー (Instrumental)", "悠木碧", 0],
    [4, "異世界管理局情報課 (Instrumental)", "悠木碧", 0],
]
links = ["https://beta.musicbrainz.org/release/99e94029-652c-4110-a36b-bcefb88c107f", "https://vgmdb.net/album/108458"]

[0a69859a65d02ca2dce8c77645a78240]
catalognumber = "N/A"
date = "2021-04-15"
album = "スライム倒して300年、知らないうちにレベルMAXになってました 16 ドラマCD"
tracks = []
links = ["https://vgmdb.net/album/108085"]

[46cc023abd09734c8fa3fda8634e4c05]
catalognumber = "COZC-1751~2"
date = "2021-06-16"
album = "Viewtiful Days!/記憶に恋をした / 和氣あず未 [初回限定盤] Vocal"
tracks = [
    [1, "Viewtiful Days!", "和氣あず未", 0],
    [2, "2030", "和氣あず未", 0],
    [3, "記憶に恋をした", "和氣あず未", 0],
    [4, "hopeless", "和氣あず未", 0],
    [5, "Viewtiful Days! (Instrumental)", "和氣あず未", 0],
    [6, "2030 (Instrumental)", "和氣あず未", 0],
    [7, "記憶に恋をした (Instrumental)", "和氣あず未", 0],
    [8, "hopeless (Instrumental)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/09753d29-1261-4023-b5d4-79cc00769e57", "https://vgmdb.net/album/109839"]

[39f0923488538a9677d7b686f47d0239]
catalognumber = "COZC-1751~2"
date = "2021-06-16"
album = "Viewtiful Days!/記憶に恋をした / 和氣あず未 [初回限定盤] Vocal, Video"
tracks = [
    [1, "Viewtiful Days! (ミュージックビデオ)", "", 0],
    [2, "Viewtiful Days! (ミュージックビデオ メイキング)", "", 0],
    [3, "記憶に恋をした (ミュージックビデオ) (Short ver.)", "", 0],
]
links = ["https://vgmdb.net/album/109839"]

[eb5af8b66fa3f6f20d608509a1b54058]
catalognumber = "COCC-17881"
date = "2021-06-16"
album = "Viewtiful Days!/記憶に恋をした / 和氣あず未"
tracks = [
    [1, "Viewtiful Days!", "和氣あず未", 0],
    [2, "2030", "和氣あず未", 0],
    [3, "記憶に恋をした", "和氣あず未", 0],
    [4, "hopeless", "和氣あず未", 0],
    [5, "Viewtiful Days! (Instrumental)", "和氣あず未", 0],
    [6, "2030 (Instrumental)", "和氣あず未", 0],
    [7, "記憶に恋をした (Instrumental)", "和氣あず未", 0],
    [8, "hopeless (Instrumental)", "和氣あず未", 0],
]
links = ["https://beta.musicbrainz.org/release/0d3fe544-2a5e-4d76-8762-64097b285ad8", "https://vgmdb.net/album/109838"]

[41884fc7906dc4ea7149cb9a6d6d3228]
catalognumber = "TDCL-92045"
date = "2021-07-28"
album = "スライム倒して300年、知らないうちにレベルMAXになってました ORIGINAL SOUNDTRACK"
tracks = [
    [1, "異世界転生", "井内啓二", 0],
    [2, "サブタイトル", "井内啓二", 0],
    [3, "異世界スローライフ", "井内啓二", 0],
    [4, "初めてのスライム戦", "井内啓二", 0],
    [5, "フラタ村", "井内啓二", 0],
    [6, "冒険者ギルドにて", "井内啓二", 0],
    [7, "スライム倒して300年", "井内啓二", 0],
    [8, "高原の魔女", "井内啓二", 0],
    [9, "豊かな食卓", "井内啓二", 0],
    [10, "スライム狂詩曲", "井内啓二", 0],
    [11, "初めての弟子", "井内啓二", 0],
    [12, "ライカ", "井内啓二", 0],
    [13, "ママと呼ばれて", "井内啓二", 0],
    [14, "ファルファとシャルシャ", "井内啓二", 0],
    [15, "ハラハラハルカラ", "井内啓二", 0],
    [16, "魔法使いの弟子たち", "井内啓二", 0],
    [17, "スライムの賢者", "井内啓二", 0],
    [18, "アイキャッチ", "井内啓二", 0],
    [19, "キノコ狩り", "井内啓二", 0],
    [20, "ハルカラの異変", "井内啓二", 0],
    [21, "失意のハルカラ", "井内啓二", 0],
    [22, "ドラゴンの村の宴", "井内啓二", 0],
    [23, "ドラゴンと戦うことになった", "井内啓二", 0],
    [24, "フラットルテ", "井内啓二", 0],
    [25, "ロザリーは地縛霊", "井内啓二", 0],
    [26, "リヴァイアサンに乗って", "井内啓二", 0],
    [27, "星に願いを", "井内啓二", 0],
    [28, "城塞都市ヴァンゼルド", "井内啓二", 0],
    [29, "意地悪ペコラ", "井内啓二", 0],
    [30, "「お前より豚のほうがよっぽど役に立つよ」亭", "井内啓二", 0],
    [31, "武術大会", "井内啓二", 0],
    [32, "世界樹へ!", "井内啓二", 0],
    [33, "困ったときは魔法で解決", "井内啓二", 0],
    [34, "働き過ぎには御用心", "井内啓二", 0],
    [35, "ありがとう", "クク(CV:小岩井ことり)", 0],
]
links = ["https://beta.musicbrainz.org/release/3ba67103-6502-455d-93eb-41512e77291a", "https://vgmdb.net/album/110616"]

[ac118f4c0e6e379a6ec0117d4b351111]
catalognumber = "COCC-18280"
date = "2025-04-23"
album = "So☆Lucky / 小倉唯 [スライム盤]"
tracks = [
    [1, "So☆Lucky", "小倉唯", 0],
    [2, "So☆Lucky (TVサイズ)", "小倉唯", 0],
    [3, "So☆Lucky -Instrumental-", "小倉唯", 0],
    [4, "So☆Lucky (TVサイズ) -Instrumental-", "小倉唯", 0],
]
links = ["https://beta.musicbrainz.org/release/88bc45ab-20a4-4c98-a7b7-2ae3ada88861", "https://vgmdb.net/album/146636"]

[33bd0468fa0c7992392aa6f43ee2c5bb]
catalognumber = "COCC-18277"
date = "2025-04-30"
album = "イニミニマニモ / 大西亜玖璃"
tracks = [
    [1, "イニミニマニモ", "大西亜玖璃", 0],
    [2, "ときめきプロローグ", "大西亜玖璃", 0],
    [3, "イニミニマニモ (Instrumental)", "大西亜玖璃", 0],
    [4, "ときめきプロローグ (Instrumental)", "大西亜玖璃", 0],
]
links = ["https://beta.musicbrainz.org/release/a75f52d0-b18a-42e3-afa2-3d8be126598c", "https://vgmdb.net/album/146634"]

[00c80cc75a0396e6a480199815427590]
catalognumber = "TDCL-92061"
date = "2025-06-25"
album = "スライム倒して 300 年、知らないうちにレベルMAX になってました 〜そのに〜 オリジナルサウンドトラックCD"
tracks = [
    [1, "メインタイトル そのに", "井内啓二", 0],
    [2, "続・フラタ村の日常", "井内啓二", 0],
    [3, "爽やかな朝", "井内啓二", 0],
    [4, "高原の魔女の家", "井内啓二", 0],
    [5, "にぎやかな日常", "井内啓二", 0],
    [6, "ハルカラの失態", "井内啓二", 0],
    [7, "スライムの姉妹", "井内啓二", 0],
    [8, "魔女の家へようこそ", "井内啓二", 0],
    [9, "フラタ村の祭り", "井内啓二", 0],
    [10, "家事するライカ", "井内啓二", 0],
    [11, "ダンジョン潜るよどこまでも", "井内啓二", 0],
    [12, "女神の晩餐会", "井内啓二", 0],
    [13, "メガーメガとの再会", "井内啓二", 0],
    [14, "蘇る社畜の記憶", "井内啓二", 0],
    [15, "黄昏の午後", "井内啓二", 0],
    [16, "精霊たちの集い", "井内啓二", 0],
    [17, "したたりの精霊・ユフフ", "井内啓二", 0],
    [18, "ご機嫌ペコラ", "井内啓二", 0],
    [19, "ブッスラー流スライム拳", "井内啓二", 0],
    [20, "暴走するフラットルテ", "井内啓二", 0],
    [21, "墓場警備員・ポンデリ", "井内啓二", 0],
    [22, "不気味な気配", "井内啓二", 0],
    [23, "魔女たちの狂詩曲", "井内啓二", 0],
    [24, "ベルゼブブの裏庭", "井内啓二", 0],
    [25, "サンドラ", "井内啓二", 0],
    [26, "譲れない戦い", "井内啓二", 0],
    [27, "ユフフママの娘になった", "井内啓二", 0],
    [28, "ライカ vs. アズサ", "井内啓二", 0],
    [29, "姉妹結婚式", "井内啓二", 0],
    [30, "トキメキ!海!", "井内啓二", 0],
    [31, "クラゲの精霊・キュアリーナ", "井内啓二", 0],
    [32, "古代文明の調査", "井内啓二", 0],
    [33, "悪霊の囁き", "井内啓二", 0],
    [34, "脳内に響く声", "井内啓二", 0],
    [35, "ニンタン大聖堂", "井内啓二", 0],
    [36, "ニンタン神の怒り", "井内啓二", 0],
    [37, "MAD ODD WOO", "ペコラ(CV:田村ゆかり)", 0],
    [38, "生まれ変わろうと", "アズサ(CV:悠木碧)", 0],
    [39, "アイキャッチ1", "井内啓二", 0],
    [40, "アイキャッチ2", "井内啓二", 0],
    [41, "高原の日々 そのいち", "井内啓二", 0],
    [42, "高原の日々 そのに", "井内啓二", 0],
    [43, "高原の日々 そのさん", "井内啓二", 0],
    [44, "高原の日々 そのよん", "井内啓二", 0],
    [45, "高原の日々 そのご", "井内啓二", 0],
    [46, "高原の日々 そのろく", "井内啓二", 0],
    [47, "高原の日々 そのしち", "井内啓二", 0],
    [48, "高原の日々 そのはち", "井内啓二", 0],
    [49, "高原の日々 そのきゅう", "井内啓二", 0],
    [50, "高原の日々 そのじゅう", "井内啓二", 0],
    [51, "高原の日々 そのじゅういち", "井内啓二", 0],
    [52, "高原の日々 そのじゅうに", "井内啓二", 0],
    [53, "高原の日々 そのじゅうさん", "井内啓二", 0],
    [54, "高原の日々 そのじゅうよん", "井内啓二", 0],
    [55, "高原の日々 そのじゅうご", "井内啓二", 0],
    [56, "高原の日々 そのじゅうろく", "井内啓二", 0],
    [57, "高原の日々 そのじゅうしち", "井内啓二", 0],
    [58, "高原の日々 そのじゅうはち", "井内啓二", 0],
    [59, "高原の日々 そのじゅうきゅう", "井内啓二", 0],
    [60, "高原の日々 そのにじゅう", "井内啓二", 0],
]
links = ["https://beta.musicbrainz.org/release/cae66fb8-327f-4222-8dc3-10a4bf32898d", "https://vgmdb.net/album/149326"]
