[a858d895417a2feb1b52cdb9009685ee]
catalognumber = "SVWC-70331~2"
date = "2018-01-24"
album = "ne! ne! ne! / STARTails☆ Disc 1 (CD) [SVWC-70331]"
tracks = [
    [1, "ne! ne! ne!", "STARTails☆", 1],
    [2, "夕焼けといっしょに", "STARTails☆", 1],
    [3, "ne! ne! ne! (Instrumental)", "STARTails☆", 1],
    [4, "夕焼けといっしょに (Instrumental)", "STARTails☆", 1],
]
links = ["https://beta.musicbrainz.org/release/6c3b5f1d-f5ec-47cd-bf12-c71c8398c4eb", "https://vgmdb.net/album/73072"]

[be5824fc568092752adf7e63a6b761fa]
catalognumber = "SVWC-70331~2"
date = "2018-01-24"
album = "ne! ne! ne! / STARTails☆ Disc 2 (Blu-ray) [SVWC-70332]"
tracks = [
    [1, "ne! ne! ne! (Music Video)", "STARTails☆", 1],
]
links = ["https://beta.musicbrainz.org/release/6c3b5f1d-f5ec-47cd-bf12-c71c8398c4eb", "https://vgmdb.net/album/73072"]

[03effeb3eb8fee7864c63c60d8352939]
catalognumber = "VVCL-1167~8"
date = "2018-03-07"
album = "風の声を聴きながら/コラージュ / 三月のパンタシア Disc 1 (CD) [VVCL-1167]"
tracks = [
    [1, "風の声を聴きながら", "三月のパンタシア", 1],
    [2, "#最高の片想い", "三月のパンタシア", 1],
    [3, "コラージュ", "三月のパンタシア", 1],
    [4, "風の声を聴きながら -instrumental-", "三月のパンタシア", 1],
]
links = ["https://beta.musicbrainz.org/release/1f31d1ad-a98a-40c8-8c2a-4060e64292f1", "https://vgmdb.net/album/73088"]

[fda58266733e003c2b3c8be4ac0d709f]
catalognumber = "VVCL-1167~8"
date = "2018-03-07"
album = "風の声を聴きながら/コラージュ / 三月のパンタシア Disc 2 (DVD) [VVCL-1168]"
tracks = [
    [1, "風の声を聴きながら -Music Video-", "三月のパンタシア", 1],
]
links = ["https://beta.musicbrainz.org/release/1f31d1ad-a98a-40c8-8c2a-4060e64292f1", "https://vgmdb.net/album/73088"]

[90f93a0f3f3599faa5463b76370982a1]
catalognumber = "VVCL-1172~3"
date = "2018-03-07"
album = "コラージュ/風の声を聴きながら / 三月のパンタシア [衛宮さんちの今日のごはん盤] Disc 1 (CD) [VVCL-1172]"
tracks = [
    [1, "コラージュ", "三月のパンタシア", 1],
    [2, "#最高の片想い", "三月のパンタシア", 1],
    [3, "風の声を聴きながら", "三月のパンタシア", 1],
    [4, "コラージュ -TV size-", "三月のパンタシア", 1],
]
links = ["https://beta.musicbrainz.org/release/00014f7b-c37c-498d-a6ae-b426ac4bb893", "https://vgmdb.net/album/73897"]

[1a7095fafafbbd2eaa713f7bb54f19f3]
catalognumber = "VVCL-1172~3"
date = "2018-03-07"
album = "コラージュ/風の声を聴きながら / 三月のパンタシア [衛宮さんちの今日のごはん盤] Disc 2 (DVD) [VVCL-1173]"
tracks = [
    [1, "アニメ「衛宮さんちの今日のごはん」ノンクレジットEDムービー", "三月のパンタシア", 0],
]
links = ["https://beta.musicbrainz.org/release/00014f7b-c37c-498d-a6ae-b426ac4bb893", "https://vgmdb.net/album/73897"]

[508c1a025c3a221d9eeb628d2bf5dee8]
catalognumber = "VVCL-1169"
date = "2018-03-07"
album = "風の声を聴きながら/コラージュ / 三月のパンタシア"
tracks = [
    [1, "風の声を聴きながら", "三月のパンタシア", 2],
    [2, "#最高の片想い", "三月のパンタシア", 1],
    [3, "コラージュ", "三月のパンタシア", 1],
    [4, "風の声を聴きながら -instrumental-", "三月のパンタシア", 1],
]
links = ["https://beta.musicbrainz.org/release/6d92795b-dc13-4483-b132-6f187fb99f62", "https://vgmdb.net/album/73089"]

[9db1333f07800366822e69f2e50dc7cd]
catalognumber = "VVCL-1170~1"
date = "2018-03-07"
album = "風の声を聴きながら/コラージュ / 三月のパンタシア [スロウスタート盤] Disc 2 (DVD) [VVCL-1171]"
tracks = [
    [1, "TVアニメ「スロウスタート」ノンクレジットエンディング", "三月のパンタシア", 0],
]
links = ["https://beta.musicbrainz.org/release/5f832170-71a4-4422-b198-a1999c6f7b49", "https://vgmdb.net/album/73090"]

[dd85da7ad850c4ede4257455020c38ee]
catalognumber = "VVCL-1170~1"
date = "2018-03-07"
album = "風の声を聴きながら/コラージュ / 三月のパンタシア [スロウスタート盤] Disc 1 (CD) [VVCL-1170]"
tracks = [
    [1, "風の声を聴きながら", "三月のパンタシア", 1],
    [2, "#最高の片想い", "三月のパンタシア", 1],
    [3, "コラージュ", "三月のパンタシア", 1],
    [4, "風の声を聴きながら -TV size-", "三月のパンタシア", 1],
]
links = ["https://beta.musicbrainz.org/release/5f832170-71a4-4422-b198-a1999c6f7b49", "https://vgmdb.net/album/73090"]

[70c552f17f390d190d56760bfd1a8813]
catalognumber = "SVWC-70333"
date = "2018-03-14"
album = "スロウスタート キャラクターソングアルバム Step by Step"
tracks = [
    [1, "スパークルデイズ", "百地たまて starring 伊藤彩沙", 1],
    [2, "ストロベリーアイスクリーム", "十倉栄依子 starring 嶺内ともみ", 1],
    [3, "ほんわかびより", "千石冠 starring 長縄まりあ", 1],
    [4, "Sweet Slow Days", "京塚志温 starring M・A・O", 1],
    [5, "ココロ替え宣言", "万年大会 starring 内田真礼", 1],
    [6, "シュガー＆シュガーレス", "榎並清瀬 starring 沼倉愛美", 1],
    [7, "みんなありがと。", "一之瀬花名 starring 近藤玲奈", 1],
]
links = ["https://beta.musicbrainz.org/release/1ec98fef-850f-49a8-be9f-3e5fd364abfa", "https://vgmdb.net/album/73547"]

[31805f8366007d50f65da4c4a3219b8b]
catalognumber = "ANZX-12122"
date = "2018-03-28"
album = "スロウスタート 第1巻 特典CD"
tracks = [
    [1, "カナエタマエ", "一之瀬花名(近藤玲奈)&百地たまて(伊藤彩沙)", 1],
    [2, "カナエタマエ (Instrumental)", "一之瀬花名(近藤玲奈)&百地たまて(伊藤彩沙)", 1],
    [3, "花名とたまてとふしぎな部屋", "一之瀬花名(近藤玲奈)/百地たまて(伊藤彩沙)/京塚志温(M・A・O)", 1],
    [4, "スロウスタート", "藤澤慶昌", 1],
    [5, "たまり場", "藤澤慶昌", 1],
    [6, "宜しくお願いします!", "藤澤慶昌", 1],
    [7, "バナナチョコミントハワイアン", "藤澤慶昌", 1],
    [8, "友達", "藤澤慶昌", 1],
    [9, "ロマン弁当", "藤澤慶昌", 1],
    [10, "妹汁", "藤澤慶昌", 1],
    [11, "普通の成績", "藤澤慶昌", 1],
    [12, "おはよう!", "藤澤慶昌", 1],
    [13, "勉強会", "藤澤慶昌", 1],
    [14, "ボロは纏えど心は錦", "藤澤慶昌", 1],
    [15, "誕生日プレゼント", "藤澤慶昌", 1],
    [16, "肉団", "藤澤慶昌", 1],
    [17, "宿命", "藤澤慶昌", 1],
    [18, "遠回り", "藤澤慶昌", 1],
    [19, "でゅふふふ", "藤澤慶昌", 1],
    [20, "祝福", "藤澤慶昌", 1],
    [21, "無心", "藤澤慶昌", 1],
    [22, "一日千秋", "藤澤慶昌", 1],
    [23, "泣くほど嬉しいプレゼント", "藤澤慶昌", 1],
    [24, "中学浪人", "藤澤慶昌", 1],
    [25, "はなちゃん先生", "藤澤慶昌", 1],
    [26, "引きこもり", "藤澤慶昌", 1],
]
links = ["https://beta.musicbrainz.org/release/47bed4a0-9187-4db7-9c45-9649fc8eda0e", "https://vgmdb.net/album/73947"]

[e73e06f4158c1a70f9b8695cd8d4b51a]
catalognumber = "ANZX-12124"
date = "2018-04-25"
album = "スロウスタート 第2巻 特典CD"
tracks = [
    [1, "マリンバリンバ", "十倉栄依子(嶺内ともみ)&千石冠(長縄まりあ)", 1],
    [2, "マリンバリンバ (Instrumental)", "十倉栄依子(嶺内ともみ)&千石冠(長縄まりあ)", 1],
    [3, "栄依子と冠、猫カフェへゆく", "十倉栄依子(嶺内ともみ)/千石冠(長縄まりあ)", 1],
    [4, "都市伝説", "藤澤慶昌", 1],
    [5, "今年も受験生", "藤澤慶昌", 1],
    [6, "実は、私…", "藤澤慶昌", 1],
    [7, "榎並先生", "藤澤慶昌", 1],
    [8, "小芝居", "藤澤慶昌", 1],
    [9, "ひとり風呂", "藤澤慶昌", 1],
    [10, "目の前の問題", "藤澤慶昌", 1],
    [11, "ソックリさん", "藤澤慶昌", 1],
    [12, "ドッペルゲンガー", "藤澤慶昌", 1],
    [13, "イベントスチル", "藤澤慶昌", 1],
    [14, "仲良くなったってこと", "藤澤慶昌", 1],
    [15, "内緒話", "藤澤慶昌", 1],
    [16, "あられもない姿", "藤澤慶昌", 1],
    [17, "お戯れ", "藤澤慶昌", 1],
    [18, "参戦", "藤澤慶昌", 1],
    [19, "いざ、出陣!", "藤澤慶昌", 1],
    [20, "ne! ne! ne! ～スロウVer.～", "藤澤慶昌", 1],
    [21, "風の声を聴きながら ～スロウオルゴールVer.～", "藤澤慶昌", 1],
    [22, "新しい日常", "藤澤慶昌", 1],
    [23, "みんなと一緒なら", "藤澤慶昌", 1],
    [24, "私の秘密", "藤澤慶昌", 1],
]
links = ["https://beta.musicbrainz.org/release/f5636b6c-aa1b-4e2a-ac5c-f1d94d138fb1", "https://vgmdb.net/album/73948"]

[e051b9bc68b29f2c3cc857ceba970e39]
catalognumber = "ANZX-12126"
date = "2018-05-30"
album = "スロウスタート 第3巻 特典CD"
tracks = [
    [1, "ときめきコレクション♡", "京塚志温(M・A・O)&万年大会(内田真礼)", 1],
    [2, "ときめきコレクション♡ (Instrumental)", "京塚志温(M・A・O)&万年大会(内田真礼)", 1],
    [3, "しあわせのじゅもん", "京塚志温(M・A・O)/万年大会(内田真礼)", 1],
]
links = ["https://beta.musicbrainz.org/release/e57244b7-56b1-48c6-80fe-98fd760f1f73", "https://vgmdb.net/album/73949"]

[7b4afdfb0ce81e8e5ab059b5bc5158e3]
catalognumber = "ANZX-12128"
date = "2018-06-27"
album = "スロウスタート 第4巻 特典CD"
tracks = [
    [1, "スープにスパイス", "十倉栄依子(嶺内ともみ)&榎並清瀬(沼倉愛美)", 1],
    [2, "スープにスパイス (Instrumental)", "十倉栄依子(嶺内ともみ)&榎並清瀬(沼倉愛美)", 1],
    [3, "清瀬さんと一緒。", "十倉栄依子(嶺内ともみ)/榎並清瀬(沼倉愛美)", 1],
]
links = ["https://beta.musicbrainz.org/release/bc4e0095-194a-4738-9a7a-ca689a16f6ee", "https://vgmdb.net/album/73950"]

[bd94127d82b11d0673a01c86a6cfaa83]
catalognumber = "ANZX-12130"
date = "2018-07-25"
album = "スロウスタート 第5巻 特典CD"
tracks = [
    [1, "はぴらき☆エブリディ", "一之瀬花名(近藤玲奈)&京塚志温(M・A・O)&万年大会(内田真礼)", 1],
    [2, "はぴらき☆エブリディ (Instrumental)", "一之瀬花名(近藤玲奈)&京塚志温(M・A・O)&万年大会(内田真礼)", 1],
    [3, "てまりハイツの朝は、わりと早い", "一之瀬花名(近藤玲奈)/京塚志温(M・A・O)/万年大会(内田真礼)", 1],
]
links = ["https://beta.musicbrainz.org/release/cc6e3d47-8319-4a4b-a609-056834a86ebb", "https://vgmdb.net/album/73951"]

[cbba7d6e6b5eede078f9276ccc2dc62c]
catalognumber = "ANZX-12132"
date = "2018-08-29"
album = "スロウスタート 第6巻 特典CD"
tracks = [
    [1, "明日もきっと", "STARTails☆(近藤玲奈・伊藤彩沙・嶺内ともみ・長縄まりあ)", 1],
    [2, "明日もきっと (Instrumental)", "STARTails☆(近藤玲奈・伊藤彩沙・嶺内ともみ・長縄まりあ)", 1],
    [3, "今はこんなに", "一之瀬花名(近藤玲奈)/百地たまて(伊藤彩沙)/十倉栄依子(嶺内ともみ)/千石冠(長縄まりあ)", 1],
]
links = ["https://beta.musicbrainz.org/release/5ecf3f5b-6553-4e7b-9d77-c5e928c80863", "https://vgmdb.net/album/73952"]

[6696b42bfbaefeefd155724320d7ca4b]
catalognumber = "VVCL-1387"
date = "2019-01-23"
album = "MiX ～面白いほどよくわかるノンストップSACRA MUSIC～"
tracks = [
    [1, "Rising Hope", "LiSA", 0],
    [2, "IGNITE", "藍井エイル", 0],
    [3, "The Everlasting Guilty Crown", "EGOIST", 0],
    [4, "sh0ut", "SawanoHiroyuki[nZk]:Tielle&Gemie", 0],
    [5, "ジョーカーに宜しく", "PENGUIN RESEARCH", 0],
    [6, "デート", "斉藤壮馬", 0],
    [7, "ずっと", "佐香智久", 0],
    [8, "星空☆ディスティネーション", "花澤香菜", 0],
    [9, "風の声を聴きながら", "三月のパンタシア", 1],
    [10, "Overfly", "春奈るな", 0],
    [11, "キミの隣", "halca", 0],
    [12, "irony -season 02-", "ClariS", 0],
    [13, "adrenaline!!!", "TrySail", 0],
    [14, "極楽浄土", "GARNiDELiA", 0],
    [15, "名前のない怪物", "EGOIST", 0],
    [16, "ボタン", "PENGUIN RESEARCH", 0],
    [17, "スタートダッシュ", "スピラ・スピカ", 0],
    [18, "vanilla sky", "綾野ましろ", 0],
    [19, "ミレナリオ", "ELISA", 0],
    [20, "SWEET HURT", "ReoNa", 0],
    [21, "=LOVE", "=LOVE", 0],
    [22, "ゲッタバンバン", "佐香智久", 0],
    [23, "君色シグナル", "春奈るな", 0],
    [24, "ヒトリゴト", "ClariS", 0],
    [25, "はじまりの速度", "三月のパンタシア", 0],
    [26, "シューゲイザー", "藍井エイル", 0],
    [27, "ROCK-mode’18", "LiSA", 0],
    [28, "High Free Spirits", "TrySail", 0],
    [29, "&Z", "SawanoHiroyuki[nZk]:mizuki", 0],
    [30, "凛", "ASCA", 0],
    [31, "ex:tella", "ELISA", 0],
    [32, "ideal white", "綾野ましろ", 0],
    [33, "シリウス", "藍井エイル", 0],
    [34, "ambiguous", "GARNiDELiA", 0],
    [35, "Catch the Moment", "LiSA", 0],
]
links = ["https://beta.musicbrainz.org/release/3bc10fbc-e9ee-49bd-80be-f761b96b3fa0", "https://vgmdb.net/album/82372"]

[03d1fa01253c69cf7c4d7af869f1601e]
catalognumber = "VVCL-1423~4"
date = "2019-03-13"
album = "ガールズブルー・ハッピーサッド / 三月のパンタシア Disc 1 (CD) [VVCL-1423]"
tracks = [
    [1, "三月がずっと続けばいい", "三月のパンタシア", 0],
    [2, "ピンクレモネード", "三月のパンタシア", 0],
    [3, "風の声を聴きながら", "三月のパンタシア", 1],
    [4, "パステルレイン", "三月のパンタシア", 0],
    [5, "青春なんていらないわ", "三月のパンタシア", 0],
    [6, "ソーダアイス", "三月のパンタシア", 0],
    [7, "ビタースイート", "三月のパンタシア", 0],
    [8, "ラフスケッチ", "三月のパンタシア", 0],
    [9, "ルビコン", "三月のパンタシア", 0],
    [10, "街路、ライトの灯りだけ", "三月のパンタシア", 0],
    [11, "コラージュ", "三月のパンタシア", 1],
    [12, "東京", "三月のパンタシア", 0],
]
links = ["https://beta.musicbrainz.org/release/675bb26e-0f26-4e39-b8b3-a4e691dffbd3", "https://vgmdb.net/album/83392"]

[39430b385d7effec7c9b1f2f5878c674]
catalognumber = "VVCL-1423~4"
date = "2019-03-13"
album = "ガールズブルー・ハッピーサッド / 三月のパンタシア Disc 2 (Blu-ray) [VVCL-1424]"
tracks = [
    [1, "ルビコン -Music Video-", "三月のパンタシア", 0],
    [2, "風の声を聴きながら -Music Video-", "三月のパンタシア", 1],
    [3, "ピンクレモネード -Lyric Video-", "三月のパンタシア", 0],
    [4, "青春なんていらないわ -Lyric Video-", "三月のパンタシア", 0],
    [5, "街路、ライトの灯りだけ -Lyric Video-", "三月のパンタシア", 0],
    [6, "三月がずっと続けばいい -Lyric Video-", "三月のパンタシア", 0],
    [7, "ビタースイート -Lyric Video-", "三月のパンタシア", 0],
    [8, "パステルレイン -Lyric Video-", "三月のパンタシア", 0],
]
links = ["https://beta.musicbrainz.org/release/675bb26e-0f26-4e39-b8b3-a4e691dffbd3", "https://vgmdb.net/album/83392"]

[01531aad7080a459fe50fb49d76e2974]
catalognumber = "VVCL-1425"
date = "2019-03-13"
album = "ガールズブルー・ハッピーサッド / 三月のパンタシア"
tracks = [
    [1, "三月がずっと続けばいい", "三月のパンタシア", 0],
    [2, "ピンクレモネード", "三月のパンタシア", 0],
    [3, "風の声を聴きながら", "三月のパンタシア", 1],
    [4, "パステルレイン", "三月のパンタシア", 0],
    [5, "青春なんていらないわ", "三月のパンタシア", 0],
    [6, "ソーダアイス", "三月のパンタシア", 0],
    [7, "ビタースイート", "三月のパンタシア", 0],
    [8, "ラフスケッチ", "三月のパンタシア", 0],
    [9, "ルビコン", "三月のパンタシア", 0],
    [10, "街路、ライトの灯りだけ", "三月のパンタシア", 0],
    [11, "コラージュ", "三月のパンタシア", 1],
    [12, "東京", "三月のパンタシア", 0],
]
links = ["https://beta.musicbrainz.org/release/9bc39de1-ff9b-4f80-a06f-86445d71fd54", "https://vgmdb.net/album/83391"]
