[70b86849f648d54c8847f3d3f430355d]
catalognumber = "EYCA-12097"
date = "2018-11-28"
album = "徒花ネクロマンシー / フランシュシュ"
tracks = [
    [1, "徒花ネクロマンシー", "フランシュシュ", 0],
    [2, "FANTASTIC LOVERS", "アイアンフリル", 0],
    [3, "徒花ネクロマンシー (Instrumental)", "フランシュシュ", 0],
    [4, "FANTASTIC LOVERS (Instrumental)", "アイアンフリル", 0],
]
links = ["https://vgmdb.net/album/80550", "https://beta.musicbrainz.org/release/e1d29a99-999e-4e8c-9a90-060445fb3dab"]

[ba486d6b2ef9bf1f59eca753c99f8442]
catalognumber = "EYCA-12096"
date = "2018-11-28"
album = "光へ / フランシュシュ"
tracks = [
    [1, "光へ", "フランシュシュ", 0],
    [2, "ゼリーフィッシュ", "アイアンフリル", 0],
    [3, "光へ (Instrumental)", "フランシュシュ", 0],
    [4, "ゼリーフィッシュ (Instrumental)", "アイアンフリル", 0],
]
links = ["https://vgmdb.net/album/80551", "https://beta.musicbrainz.org/release/d5fbe0b9-21aa-424c-a17e-614a5d46c200"]

[0104dd34690fcf075fbb9a47f5b337b0]
catalognumber = "EYXA-12123B"
date = "2018-12-21"
album = "ゾンビランドサガ SAGA.1 SPECIAL DISC♥"
tracks = [
    [1, "ようこそ佐賀へ", "デス娘(仮)", 0],
    [2, "サガ・アーケードラップ", "サガ・アーケードラッパーズ", 0],
    [3, "DEAD or RAP!!!", "グリーンフェイス", 0],
    [4, "目覚めRETURNER", "フランシュシュ", 0],
    [5, "アツクナレ", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/81103", "https://beta.musicbrainz.org/release/abf87625-fe3f-4f56-8166-682bdf3cd11e"]

[d3f4066937d52008b6603a35ae996224]
catalognumber = "EYXA-12124B"
date = "2019-02-22"
album = "ゾンビランドサガ SAGA.2 SPECIAL DISC♥"
tracks = [
    [1, "ドライブイン鳥 (フランシュシュver.)", "フランシュシュ", 0],
    [2, "To my Dearest", "フランシュシュ", 0],
    [3, "特攻DANCE〜DAWN OF THE BAD〜", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/81104", "https://beta.musicbrainz.org/release/0b14c284-5e78-48ec-a68e-657315f4fb18"]

[d3e1c880c55a3995adfb3a8b34f2a32b]
catalognumber = "EYXA-12125B"
date = "2019-04-26"
album = "ゾンビランドサガ SAGA.3 SPECIAL DISC♥"
tracks = [
    [1, "ヨミガエレ", "フランシュシュ", 0],
    [2, "FLAGをはためかせろ!", "フランシュシュ", 0],
    [3, "目覚めRETURNER (Electric Returner)", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/81105", "https://beta.musicbrainz.org/release/bb0a6ba9-acea-45e5-9944-419e40192bcf"]

[dd85622b9c990f37579e453c6f19c0eb]
catalognumber = "EYXA-12572"
date = "2019-07-26"
album = "ゾンビランドサガLIVE ～フランシュシュみんなでおらぼう!～"
tracks = [
    [1, "徒花ネクロマンシー", "", 0],
    [2, "DEAD or RAP!!!", "", 0],
    [3, "アツクナレ", "", 0],
    [4, "目覚めRETURNER", "", 0],
    [5, "ゼリーフィッシュ", "", 0],
    [6, "FANTASTIC LOVERS", "", 0],
    [7, "To my Dearest", "", 0],
    [8, "特攻DANCE ～DAWN OF THE BAD～", "", 0],
    [9, "ヨミガエレ", "", 0],
    [10, "光へ", "", 0],
    [11, "FLAGをはためかせろ!", "", 0],
]
links = ["https://vgmdb.net/album/85218"]

[d5e5ee5796752f697b85f977549f24c9]
catalognumber = "EYCA-12628"
date = "2019-08-28"
album = "ゾンビランドサガ オリジナルサウンドトラックス"
tracks = [
    [1, "デスメタルショック", "高梨康治", 0],
    [2, "ゾンビパニック", "Funta7", 0],
    [3, "徒花ネクロマンシー (TVサイズ)", "フランシュシュ", 0],
    [4, "グッドモーニング サガ", "高梨康治", 0],
    [5, "わたし死んでるんですよね?", "高梨康治", 0],
    [6, "ゾンビ オン ステージ", "高梨康治", 0],
    [7, "阿鼻叫喚", "Funta7", 0],
    [8, "悔しさを胸に", "高梨康治", 0],
    [9, "てっぺんとってやる!", "高梨康治", 0],
    [10, "仲間とともに", "Funta7", 0],
    [11, "始まりの風", "Funta7", 0],
    [12, "フランシュシュ", "Funta7", 0],
    [13, "素直になれなくて", "高梨康治", 0],
    [14, "悲しみ深く", "高梨康治", 0],
    [15, "だってアイドルだから", "高梨康治", 0],
    [16, "次のステージへ", "高梨康治", 0],
    [17, "ハイテンションな男", "高梨康治", 0],
    [18, "ゾンビの館", "高梨康治", 0],
    [19, "どうなってるの?", "Funta7", 0],
    [20, "新しい一日", "高梨康治", 0],
    [21, "幸せな思い出", "Funta7", 0],
    [22, "夜露死苦", "高梨康治", 0],
    [23, "修羅を走る", "高梨康治", 0],
    [24, "運命への道", "高梨康治", 0],
    [25, "友よ…", "Funta7", 0],
    [26, "アイドルで行こう!", "Funta7", 0],
    [27, "輝く瞳", "Funta7", 0],
    [28, "昔かたぎの女", "高梨康治", 0],
    [29, "光を見失って", "高梨康治", 0],
    [30, "淋しい夜", "高梨康治", 0],
    [31, "君がいてくれたら", "高梨康治", 0],
    [32, "胸に灯る闘志", "高梨康治", 0],
    [33, "ぜったいに見捨ててやらん", "高梨康治", 0],
    [34, "光へ (TVサイズ)", "フランシュシュ", 0],
    [35, "最高のステージ", "高梨康治", 0],
    [36, "伝説の女たち", "高梨康治", 0],
    [37, "ゾンビランドサガ", "高梨康治", 0],
]
links = ["https://vgmdb.net/album/87274", "https://beta.musicbrainz.org/release/6f010c83-7606-4c31-91d8-31ca9c60236a"]

[640f3f09307feb7e206ab7426bf5c92b]
catalognumber = "EYCA-12682/B"
date = "2019-11-27"
album = "ゾンビランドサガ フランシュシュ The Best Vocal"
tracks = [
    [1, "ようこそ佐賀へ", "デス娘(仮)", 0],
    [2, "徒花ネクロマンシー (Album ver.)", "フランシュシュ", 0],
    [3, "DEAD or RAP!!!", "グリーンフェイス", 0],
    [4, "目覚めRETURNER", "フランシュシュ", 0],
    [5, "ドライブイン鳥 (フランシュシュ ver.)", "フランシュシュ", 0],
    [6, "アツクナレ", "フランシュシュ", 0],
    [7, "目覚めRETURNER (Electric Returner)", "フランシュシュ", 0],
    [8, "To my Dearest", "フランシュシュ", 0],
    [9, "佐賀事変", "フランシュシュ", 0],
    [10, "特攻DANCE 〜DAWN OF THE BAD〜", "フランシュシュ", 0],
    [11, "ヨミガエレ", "フランシュシュ", 0],
    [12, "FLAGをはためかせろ!", "フランシュシュ", 0],
    [13, "輝いて", "フランシュシュ", 0],
    [14, "光へ", "フランシュシュ", 0],
    [15, "FANTASTIC LOVERS", "アイアンフリル", 0],
    [16, "ゼリーフィッシュ", "アイアンフリル", 0],
    [17, "サガ・アーケードラップ", "サガ・アーケードラッパーズ", 0],
    [18, "To my Dearest〜Lily's practice singing〜", "星川リリィ", 0],
    [19, "宣誓!ALIVE センセーション", "源さくら", 0],
]
links = ["https://vgmdb.net/album/89026", "https://beta.musicbrainz.org/release/c5ac5f4b-f162-435c-8eb8-5d20db755880"]

[a863afb9a2cde7647a6a5e4111c10851]
catalognumber = "EYCA-12682/B"
date = "2019-11-27"
album = "ゾンビランドサガ フランシュシュ The Best Vocal, Video"
tracks = [
    [1, "佐賀事変 (Music Video)", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/89026", "https://beta.musicbrainz.org/release/c5ac5f4b-f162-435c-8eb8-5d20db755880"]

[a909bb563d01c45cf69989f5096057eb]
catalognumber = "N/A"
date = "2020-09-03"
album = "ゾンビランドDEMPA!! / でんぱ組.inc VS フランシュシュ"
tracks = [
    [1, "ゾンビランドDEMPA!!", "でんぱ組.inc VS フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/102501", "https://beta.musicbrainz.org/release/14fe2911-c87b-46ef-a7ec-3cb5558a7371"]

[3c870ac3b38ead801644bb288a1e7bf3]
catalognumber = "EYXA-13345B"
date = "2021-03-26"
album = "ゾンビランドサガ Blu-ray BOX SPECIAL DISC"
tracks = [
    [1, "ナイショ・ビフォア・クリスマスSAGA #01", "", 0],
    [2, "ナイショ・ビフォア・クリスマスSAGA #02", "", 0],
    [3, "ナイショ・ビフォア・クリスマスSAGA #03", "", 0],
    [4, "ナイショ・ビフォア・クリスマスSAGA #04", "", 0],
]
links = ["https://vgmdb.net/album/107609"]

[7e6b73b8f6b8e997469b3c8082216524]
catalognumber = "EYCA-13357"
date = "2021-05-19"
album = "夢を手に、戻れる場所もない日々を/風の強い日は嫌いか?"
tracks = [
    [1, "夢を手に、戻れる場所もない日々を", "フランシュシュ", 0],
    [2, "風の強い日は嫌いか？", "ホワイト竜", 0],
    [3, "夢を手に、戻れる場所もない日々を Instrumental", "フランシュシュ", 0],
    [4, "風の強い日は嫌いか？ Instrumental", "ホワイト竜", 0],
]
links = ["https://vgmdb.net/album/109368", "https://beta.musicbrainz.org/release/9bedc006-7e68-4038-b25d-d7745f8ce6b6"]

[3b06e4707c47987e2b87a85ea9d88c4c]
catalognumber = "EYCA-13356"
date = "2021-05-19"
album = "大河よ共に泣いてくれ/Nope!!!!!"
tracks = [
    [1, "大河よ共に泣いてくれ", "フランシュシュ", 0],
    [2, "Nope!!!!!", "アイアンフリル", 0],
    [3, "大河よ共に泣いてくれ Instrumental", "フランシュシュ", 0],
    [4, "Nope!!!!! Instrumental", "アイアンフリル", 0],
]
links = ["https://vgmdb.net/album/109367", "https://beta.musicbrainz.org/release/fd8c74d6-37c7-497c-81d5-d687af1e34d8"]

[2601191266b971cfb088110b7527b0a0]
catalognumber = "GNCL-1332"
date = "2021-05-26"
album = "下剋上 / 森中花咲"
tracks = [
    [1, "下剋上", "森中花咲", 0],
    [2, "正六面惑星パンドラ", "森中花咲", 0],
    [3, "刹那花火", "森中花咲", 0],
    [4, "deleteless", "森中花咲", 0],
    [5, "リトルペタル", "森中花咲", 0],
    [6, "君の所為で駄目になってしまいました", "森中花咲", 0],
    [7, "相反スペル", "森中花咲", 0],
    [8, "徒花ネクロマンシー", "森中花咲", 0],
    [9, "お召し上がりは今日中に", "森中花咲", 0],
    [10, "此処に咲いて", "森中花咲", 0],
]
links = ["https://vgmdb.net/album/111942", "https://beta.musicbrainz.org/release/cddb247e-9085-4e17-953d-26caee80808a"]

[622b4f3dd27bce844d82320fab33fb62]
catalognumber = "GNCL-1331"
date = "2021-05-26"
album = "下剋上 / 森中花咲 [初回限定盤] Disc 1 [GNCL-133101]"
tracks = [
    [1, "下剋上", "森中花咲", 0],
    [2, "正六面惑星パンドラ", "森中花咲", 0],
    [3, "刹那花火", "森中花咲", 0],
    [4, "deleteless", "森中花咲", 0],
    [5, "リトルペタル", "森中花咲", 0],
    [6, "君の所為で駄目になってしまいました", "森中花咲", 0],
    [7, "相反スペル", "森中花咲", 0],
    [8, "徒花ネクロマンシー", "森中花咲", 0],
    [9, "お召し上がりは今日中に", "森中花咲", 0],
    [10, "此処に咲いて", "森中花咲", 0],
]
links = ["https://vgmdb.net/album/111941", "https://beta.musicbrainz.org/release/9fcd24fb-095f-434a-8d35-fffab0a6c89b"]

[90119bca9456c9c3782f2b914a3f7fce]
catalognumber = "GNCL-1331"
date = "2021-05-26"
album = "下剋上 / 森中花咲 [初回限定盤] Disc 2 [GNCL-133102]"
tracks = [
    [1, "諦めモード", "森中花咲", 0],
    [2, "美しき残酷な世界", "森中花咲", 0],
    [3, "God knows...", "森中花咲", 0],
    [4, "Zoetrope", "森中花咲", 0],
    [5, "不可思議のカルテ", "森中花咲", 0],
]
links = ["https://vgmdb.net/album/111941", "https://beta.musicbrainz.org/release/9fcd24fb-095f-434a-8d35-fffab0a6c89b"]

[4a1873870e80c845b09714fae43d0cc7]
catalognumber = "EYXA-13374"
date = "2021-05-28"
album = "ゾンビランドサガLIVE～フランシュシュ LIVE OF THE DEAD \"R\"～"
tracks = [
    [1, "佐賀事変", "", 0],
    [2, "DEAD or RAP!!!", "", 0],
    [3, "特攻DANCE～DAWN OF THE BAD～", "", 0],
    [4, "徒花ネクロマンシー", "", 0],
    [5, "アツクナレ", "", 0],
    [6, "目覚めRETURNER→目覚めRETURNER (Electric Returner)", "", 0],
    [7, "ゼリーフィッシュ", "", 0],
    [8, "To my Dearest～Lilly's practice singing～→To my Dearest", "", 0],
    [9, "光へ", "", 0],
    [10, "輝いて", "", 0],
    [11, "ヨミガエレ (En)", "", 0],
    [12, "夢を手に、戻れる場所もない日々を (En)", "", 0],
    [13, "FLAGをはためかせろ! (En)", "", 0],
    [14, "THE DAY OF THE DEAD \"R\" ～メイキング&ライブ後コメント～", "", 0],
    [15, "THE ROAD TO LIVE OF THE DEAD \"R\" ～キャストインタビュー～", "", 0],
]
links = ["https://vgmdb.net/album/109369"]

[dea0907399a7509beacb1f76859854d2]
catalognumber = "EYXA-13353B~C"
date = "2021-06-25"
album = "ゾンビランドサガ リベンジ SAGA.1 Bonus CD & CD-ROM Vocal"
tracks = [
    [1, "イカの魂無駄にはしない〜小島食品工場株式会社社歌〜", "小島食品工場スタッフ", 0],
    [2, "REVENGE", "フランシュシュ", 0],
    [3, "風の強い日は嫌いか? (FranChouChou cover)", "フランシュシュ", 0],
    [4, "目覚めRETURNER (3号ソロver.)", "フランシュシュ3号", 0],
    [5, "50と4つの忘れ物", "紺野純子", 0],
    [6, "激昂サバイブ", "フランシュシュ", 0],
    [7, "目覚めRETURNER (Electric Returner Type “R”)", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/110437", "https://beta.musicbrainz.org/release/8d03b297-e88b-4bcc-bee1-927a98f36ab3"]

[d2add29137a298a50c82ebd9e11dcd18]
catalognumber = "EYXA-13353B~C"
date = "2021-06-25"
album = "ゾンビランドサガ リベンジ SAGA.1 Bonus CD & CD-ROM Talk"
tracks = [
    [1, "ラジオ「ホワイト竜の佐賀がサガであるために」", "フランシュシュ", 0],
    [2, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」#01", "フランシュシュ", 0],
    [3, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」#02", "フランシュシュ", 0],
    [4, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」#03", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/110437", "https://beta.musicbrainz.org/release/8d03b297-e88b-4bcc-bee1-927a98f36ab3"]

[67352bee0f2dfa79d106c3b763cc5db5]
catalognumber = "EYXA-13354B~C"
date = "2021-07-30"
album = "ゾンビランドサガ リベンジ SAGA.2 Bonus CD & CD-ROM Vocal"
tracks = [
    [1, "命", "大空ライト", 0],
    [2, "リトルパラッポ", "フランシュシュ6号", 0],
    [3, "今日はカレーだイェイイェイイェイ", "男の子マンションズ", 0],
    [4, "ぶっちゃけてフォーユー", "フランシュシュ", 0],
    [5, "光へ (with7号ver.)", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/110486", "https://beta.musicbrainz.org/release/98c93c97-c1b3-41ea-89ef-b531f066afff"]

[3c429e5809d0d825feb7053592eb769b]
catalognumber = "EYXA-13354B~C"
date = "2021-07-30"
album = "ゾンビランドサガ リベンジ SAGA.2 Bonus CD & CD-ROM Talk"
tracks = [
    [1, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #04", "フランシュシュ", 0],
    [2, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #05", "フランシュシュ", 0],
    [3, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #06", "フランシュシュ", 0],
    [4, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #07", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/110486", "https://beta.musicbrainz.org/release/98c93c97-c1b3-41ea-89ef-b531f066afff"]

[1ce4c11ffb95c84162342f30164e6b0d]
catalognumber = "EYXA-13355B~C"
date = "2021-08-27"
album = "ゾンビランドサガ リベンジ SAGA.3 Bonus CD & CD-ROM Vocal"
tracks = [
    [1, "Never ending saga", "巽幸太郎", 0],
    [2, "輝いて (TV size)", "フランシュシュ", 0],
    [3, "追い風トラベラーズ", "フランシュシュ", 0],
    [4, "breath of SAGA", "唐沢美帆", 0],
    [5, "佐賀がサガであるために ～ジングル～", "山下洋介", 0],
    [6, "佐賀がサガであるために ～テーマ～", "山下洋介", 0],
    [7, "STOMP!!!!!", "陶山隼", 0],
    [8, "Showdown", "陶山隼", 0],
    [9, "夕さりの露", "陶山隼", 0],
    [10, "ChouChouture", "加藤裕介", 0],
    [11, "激昂サバイブ (Complete Edition)", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/110487", "https://beta.musicbrainz.org/release/c8a70324-71a4-4af0-923c-073c00848e9a"]

[23ff65ade2d5362a744e96d9cb740484]
catalognumber = "EYXA-13355B~C"
date = "2021-08-27"
album = "ゾンビランドサガ リベンジ SAGA.3 Bonus CD & CD-ROM Talk"
tracks = [
    [1, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #08", "フランシュシュ", 0],
    [2, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #09", "フランシュシュ", 0],
    [3, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #10", "フランシュシュ", 0],
    [4, "ラジオ「フランシュシュ2号の佐賀がサガであるために From ゾンビランドサガ リベンジ」 #11", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/110487", "https://beta.musicbrainz.org/release/c8a70324-71a4-4af0-923c-073c00848e9a"]

[1839796d09c571f0ccf9f83997efb9f1]
catalognumber = "LZC-2037"
date = "2021-10-27"
album = "徒花ネクロマンシー SAYAKAVER. ～triangle～ ver. / 佐咲紗花"
tracks = [
    [1, "徒花ネクロマンシー SAYAKAVER. 〜triangle〜 ver.", "佐咲紗花", 0],
]
links = ["https://vgmdb.net/album/115574", "https://beta.musicbrainz.org/release/738d7050-ea4e-4515-9e53-2dee24a6a48c"]

[29746d480388e573e10c620df08b005a]
catalognumber = "BRMM-10468"
date = "2021-11-10"
album = "バンドリ! ガールズバンドパーティ! カバーコレクション Vol.6 Disc 1"
tracks = [
    [1, "空色デイズ", "Poppin'Party", 0],
    [2, "イエスタデイ", "Poppin'Party", 0],
    [3, "大河よ共に泣いてくれ", "Poppin'Party", 0],
    [4, "徒花ネクロマンシー", "Pastel＊Palettes", 0],
    [5, "ノスタルジックレインフォール", "Pastel＊Palettes", 0],
    [6, "夜に駆ける", "Pastel＊Palettes", 0],
    [7, "SHINY DAYS", "ハロー、ハッピーワールド！", 0],
    [8, "シルエット", "ハロー、ハッピーワールド！", 0],
    [9, "ノーポイッ！", "ハロー、ハッピーワールド！", 0],
    [10, "V.I.P", "Morfonica", 0],
    [11, "CQCQ", "Morfonica", 0],
    [12, "アゲハ蝶", "Morfonica", 0],
]
links = ["https://vgmdb.net/album/114399", "https://beta.musicbrainz.org/release/87a6da57-1d76-447c-85ce-d195f569f3cb"]

[9dacf616fc5b79e822593fede5bce5c7]
catalognumber = "BRMM-10468"
date = "2021-11-10"
album = "バンドリ! ガールズバンドパーティ! カバーコレクション Vol.6 Disc 2"
tracks = [
    [1, "Don't say \"lazy\"", "Afterglow", 0],
    [2, "サムライハート(Some Like It Hot!!)", "Afterglow", 0],
    [3, "ベノム", "Afterglow", 0],
    [4, "KING", "Roselia", 0],
    [5, "Shangri-La", "Roselia", 0],
    [6, "My Dearest", "Roselia", 0],
    [7, "CORE PRIDE", "RAISE A SUILEN", 0],
    [8, "DEPARTURES", "RAISE A SUILEN", 0],
    [9, "DAYBREAK FRONTLINE", "RAISE A SUILEN", 0],
]
links = ["https://vgmdb.net/album/114399", "https://beta.musicbrainz.org/release/87a6da57-1d76-447c-85ce-d195f569f3cb"]

[26fbd8ed690d60e6697d862110dbda84]
catalognumber = "LACA-15920"
date = "2022-03-23"
album = "SAYAKAVER. 〜triangle〜 / 佐咲紗花"
tracks = [
    [1, "正解はひとつ!じゃない!!", "佐咲紗花", 0],
    [2, "花ハ踊レヤいろはにほ", "佐咲紗花", 0],
    [3, "カレンダーガール", "佐咲紗花", 0],
    [4, "徒花ネクロマンシー", "佐咲紗花", 0],
    [5, "廻廻奇譚", "佐咲紗花", 0],
    [6, "怪物", "佐咲紗花", 0],
    [7, "Stay Alive", "佐咲紗花", 0],
    [8, "回レ!雪月花", "佐咲紗花 × atsuko (angela)", 0],
    [9, "ポラリス", "佐咲紗花", 0],
    [10, "牙狼〜SAVIOR IN THE DARK〜", "佐咲紗花", 0],
]
links = ["https://vgmdb.net/album/117644", "https://beta.musicbrainz.org/release/1447a1ea-6a0e-4258-aeb9-823c1a281483"]

[59846bcc4bd550a9ad00e702115eabfe]
catalognumber = "COCC-17975"
date = "2022-05-25"
album = "THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER R/LOCK ON! 05 トロピカルガール"
tracks = [
    [1, "トロピカルガール (M@STER VERSION)", "夢見りあむ(CV.星希成奏)、乙倉悠貴(CV.中島由貴)、姫川友紀(CV.杜野まこ)、三村かな子(CV.大坪由佳)、難波笑美(CV.伊達朱里紗)", 0],
    [2, "徒花ネクロマンシー", "辻野あかり(CV.梅澤めぐ)、星輝子(CV.松田颯水)、木村夏樹(CV.安野希世乃)、小日向美穂(CV.津田美波)、関裕美(CV.会沢紗弥)", 0],
    [3, "トロピカルガール (M@STER VERSION) オリジナル・カラオケ", "夢見りあむ(CV.星希成奏)、乙倉悠貴(CV.中島由貴)、姫川友紀(CV.杜野まこ)、三村かな子(CV.大坪由佳)、難波笑美(CV.伊達朱里紗)", 0],
    [4, "トロピカルガール (M@STER VERSION) 夢見りあむソロ・リミックス", "夢見りあむ(CV. 星希成奏)", 0],
    [5, "トロピカルガール (M@STER VERSION) 乙倉悠貴ソロ・リミックス", "乙倉悠貴(CV. 中島由貴)", 0],
    [6, "トロピカルガール (M@STER VERSION) 姫川友紀ソロ・リミックス", "姫川友紀(CV. 杜野まこ)", 0],
    [7, "トロピカルガール (M@STER VERSION) 三村かな子ソロ・リミックス", "三村かな子(CV. 大坪由佳)", 0],
    [8, "トロピカルガール (M@STER VERSION) 難波笑美ソロ・リミックス", "難波笑美(CV. 伊達朱里紗)", 0],
    [9, "トロピカルガール (Game Version)", "夢見りあむ(CV.星希成奏)、乙倉悠貴(CV.中島由貴)、姫川友紀(CV.杜野まこ)、三村かな子(CV.大坪由佳)、難波笑美(CV.伊達朱里紗)", 0],
]
links = ["https://vgmdb.net/album/119940", "https://beta.musicbrainz.org/release/4dddddf8-2cd9-4a27-b1f1-2024e12bb9b8"]

[de79955f5eb32e2cd2cbdd75ca839e23]
catalognumber = "COCC-17976"
date = "2022-06-29"
album = "THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER R/LOCK ON! 06 Demolish"
tracks = [
    [1, "Demolish (M@STER VERSION)", "本田未央(CV:原紗友里)、結城晴(CV:小市眞琴)、ナターリア(CV:生田輝)", 0],
    [2, "大河よ共に泣いてくれ", "白坂小梅(CV:桜咲千依)、松永涼(CV:千菅春香)", 0],
    [3, "REVENGE", "早坂美玲(CV:朝井彩加)", 0],
    [4, "Demolish (M@STER VERSION) オリジナル・カラオケ", "本田未央(CV:原紗友里)、結城晴(CV:小市眞琴)、ナターリア(CV:生田輝)", 0],
    [5, "Demolish (M@STER VERSION) 本田未央ソロ・リミックス", "本田未央(CV:原紗友里)", 0],
    [6, "Demolish (M@STER VERSION) 結城晴ソロ・リミックス", "結城晴(CV:小市眞琴)", 0],
    [7, "Demolish (M@STER VERSION) ナターリアソロ・リミックス", "ナターリア(CV:生田輝)", 0],
    [8, "Demolish (GAME VERSION)", "本田未央(CV:原紗友里)、結城晴(CV:小市眞琴)、ナターリア(CV:生田輝)", 0],
]
links = ["https://vgmdb.net/album/120910", "https://beta.musicbrainz.org/release/c8e2daca-7c14-48a3-8fd4-ef547f2bcd47"]

[8b45ba979a537ed7734b2da4a213db59]
catalognumber = "EYCA-13868~9"
date = "2022-09-28"
album = "ゾンビランドサガリベンジ フランシュシュ The Best Revenge Disc 1 [EYCA-13868]"
tracks = [
    [1, "ChouChouture", "加藤裕介", 0],
    [2, "REVENGE", "フランシュシュ", 0],
    [3, "We are FranChouChou!", "フランシュシュ", 0],
    [4, "大河よ共に泣いてくれ", "フランシュシュ", 0],
    [5, "風の強い日は嫌いか?", "フランシュシュ", 0],
    [6, "目覚めRETURNER (Electric Returner Type \"R\")", "フランシュシュ", 0],
    [7, "Beginning", "フランシュシュ", 0],
    [8, "激昂サバイブ (Complete Edition)", "フランシュシュ", 0],
    [9, "ぶっちゃけてフォーユー", "フランシュシュ", 0],
    [10, "光へ (with7号ver.)", "フランシュシュ", 0],
    [11, "冒険ズンドコドン!", "フランシュシュ", 0],
    [12, "追い風トラベラーズ", "フランシュシュ", 0],
    [13, "夢を手に、戻れる場所もない日々を", "フランシュシュ", 0],
]
links = ["https://vgmdb.net/album/121498", "https://beta.musicbrainz.org/release/53d95d26-e204-449f-954a-14d3b0d8efca"]

[842b76bd12bf74ff1851e82e2929d94b]
catalognumber = "EYCA-13868~9"
date = "2022-09-28"
album = "ゾンビランドサガリベンジ フランシュシュ The Best Revenge Disc 2 [EYCA-13869]"
tracks = [
    [1, "イカの魂無駄にはしない~小島食品工場株式会社社歌~", "小島食品工場スタッフ", 0],
    [2, "佐賀がサガであるために - ~テーマ~", "山下洋介", 0],
    [3, "佐賀がサガであるために - ~ジングル~", "山下洋介", 0],
    [4, "breath of SAGA", "唐沢美帆", 0],
    [5, "風の強い日は嫌いか?", "ホワイト竜", 0],
    [6, "50と4つの忘れ物", "紺野純子", 0],
    [7, "STOMP!!!!!", "陶山隼", 0],
    [8, "Nope!!!!!", "アイアンフリル", 0],
    [9, "リトルパラッポ", "フランシュシュ6号", 0],
    [10, "目覚めRETURNER - 3号ソロver.", "フランシュシュ3号", 0],
    [11, "命", "大空ライト", 0],
    [12, "今日はカレーだイェイイェイイェイ", "男の子マンションズ", 0],
    [13, "Showdown", "陶山隼", 0],
    [14, "夕さりの露", "陶山隼", 0],
    [15, "激昂サバイブ", "フランシュシュ", 0],
    [16, "Never ending saga", "巽幸太郎", 0],
]
links = ["https://vgmdb.net/album/121498", "https://beta.musicbrainz.org/release/7b550258-6f19-446d-bf08-7fefb573f60e"]
