[f5100577205bcc6f541a76f3bc17f924]
catalognumber = "AIXX-01176"
date = "2018-01-20"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉"
tracks = [
    [1, "KISS OF DEATH (Produced by HYDE)", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/dae8fbb8-e10c-447b-932f-62978a0bbbb0", "https://vgmdb.net/album/74389"]

[0245253af3c68411ec046fb6ad462f78]
catalognumber = "AICL-3494~5"
date = "2018-03-07"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉 [初回盤] Disc 1 (CD) [AICL-3494]"
tracks = [
    [1, "KISS OF DEATH (Produced by HYDE)", "中島美嘉", 0],
    [2, "GLAMOROUS SKY (Re:Present 2018)", "中島美嘉", 0],
    [3, "KISS OF DEATH (Produced by HYDE) -instrumental-", "中島美嘉", 0],
    [4, "GLAMOROUS SKY (Re:Present 2018) -instrumental-", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/d70d9d59-2a75-435a-8c8e-dcb019f0a8b8", "https://vgmdb.net/album/74502"]

[ca45cd17c630855b77cd6a23a4013a39]
catalognumber = "AICL-3494~5"
date = "2018-03-07"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉 [初回盤] Disc 2 (DVD) [AICL-3495]"
tracks = [
    [1, "KISS OF DEATH (Produced by HYDE) (Music Video)", "", 0],
    [2, "KISS OF DEATH (Produced by HYDE) (Making of Music Video)", "", 0],
]
links = ["https://vgmdb.net/album/74502"]

[55529721ba4921815298f8ad1492533f]
catalognumber = "AICL-3496"
date = "2018-03-07"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉"
tracks = [
    [1, "KISS OF DEATH (Produced by HYDE)", "中島美嘉", 0],
    [2, "GLAMOROUS SKY (Re:Present 2018)", "中島美嘉", 0],
    [3, "KISS OF DEATH (Produced by HYDE) -instrumental-", "中島美嘉", 0],
    [4, "GLAMOROUS SKY (Re:Present 2018) -instrumental-", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/d70d9d59-2a75-435a-8c8e-dcb019f0a8b8", "https://vgmdb.net/album/74503"]

[0ca96614507d45099bdc22ed01cce1b6]
catalognumber = "AICL-3492~3"
date = "2018-03-07"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉 [アニメ盤] Disc 2 (DVD) [AICL-3493]"
tracks = [
    [1, "「ダーリン・イン・ザ・フランキス」OP映像", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/d2280b1e-a4cc-4a64-9a1f-b7222e806382", "https://vgmdb.net/album/74501"]

[264eb06a905d7408b62e0996692d1d38]
catalognumber = "AICL-3492~3"
date = "2018-03-07"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉 [アニメ盤] Disc 1 (CD) [AICL-3492]"
tracks = [
    [1, "KISS OF DEATH (Produced by HYDE)", "中島美嘉", 0],
    [2, "GLAMOROUS SKY (Re:Present 2018)", "中島美嘉", 0],
    [3, "KISS OF DEATH (Produced by HYDE) -TV size-", "中島美嘉", 0],
    [4, "KISS OF DEATH (Produced by HYDE) -instrumental-", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/d2280b1e-a4cc-4a64-9a1f-b7222e806382", "https://vgmdb.net/album/74501"]

[201b07225c954c114435b3c2a70950fd]
catalognumber = "SVWC-70341~2"
date = "2018-03-28"
album = "ダーリン・イン・ザ・フランキス エンディング集 vol.1 Disc 1 (CD) [SVWC-70341]"
tracks = [
    [1, "トリカゴ", "XX:me", 0],
    [2, "真夏のセツナ", "XX:me", 0],
    [3, "Beautiful World", "XX:me", 0],
    [4, "トリカゴ (TV Size ver.)", "XX:me", 0],
    [5, "真夏のセツナ (TV Size ver.)", "XX:me", 0],
    [6, "Beautiful World (TV Size ver.)", "XX:me", 0],
]
links = ["https://beta.musicbrainz.org/release/b6a8dc04-023e-4530-a9e0-b7b1b85e3431", "https://vgmdb.net/album/74094"]

[21818bac6b419fae2c3355177e2c6829]
catalognumber = "SVWC-70341~2"
date = "2018-03-28"
album = "ダーリン・イン・ザ・フランキス エンディング集 vol.1 Disc 2 (DVD) [SVWC-70342]"
tracks = [
    [1, "トリカゴ", "XX:me", 0],
    [2, "真夏のセツナ", "XX:me", 0],
    [3, "Beautiful World", "XX:me", 0],
]
links = ["https://beta.musicbrainz.org/release/b6a8dc04-023e-4530-a9e0-b7b1b85e3431", "https://vgmdb.net/album/74094"]

[4c5b0f5c9de1843b42eafb2130db0c17]
catalognumber = "ANZX-14442"
date = "2018-04-25"
album = "ダーリン・イン・ザ・フランキス オリジナルサウンドトラック vol.1"
tracks = [
    [1, "cÅGE", "橘麻美", 0],
    [2, "Vanquish", "橘麻美", 0],
    [3, "Odds and ends", "橘麻美", 0],
    [4, "o‐DOR", "橘麻美", 0],
    [5, "Dino‐S", "橘麻美", 0],
    [6, "BEAST", "橘麻美", 0],
    [7, "Counterattack", "橘麻美", 0],
    [8, "Operation", "橘麻美", 0],
    [9, "Reversal", "橘麻美", 0],
    [10, "In the FRANXX", "橘麻美", 0],
    [11, "Trente", "橘麻美", 0],
    [12, "Distopia", "橘麻美", 0],
    [13, "Godliness", "橘麻美", 0],
    [14, "Aile", "橘麻美", 0],
    [15, "Clarity", "橘麻美", 0],
    [16, "Nuance", "橘麻美", 0],
    [17, "Miel", "橘麻美", 0],
    [18, "Dropping", "橘麻美", 0],
    [19, "CODE:002", "橘麻美", 0],
    [20, "VICTORIA", "橘麻美", 0],
    [21, "Torikago ~BGM‐Rearrange~", "橘麻美", 0],
]
links = ["https://beta.musicbrainz.org/release/7dc50ec4-9bff-4b24-afa8-679b63720ffb", "https://vgmdb.net/album/74611"]

[cd618297f3d1b17a043bf8466586056f]
catalognumber = "ANZX-14444"
date = "2018-05-30"
album = "ダーリン・イン・ザ・フランキス Drama CD vol.1「危険な誘惑」"
tracks = [
    [1, "危険な誘惑 #01", "橘麻美", 0],
    [2, "危険な誘惑 #02", "橘麻美", 0],
    [3, "危険な誘惑 #03", "橘麻美", 0],
    [4, "危険な誘惑 #04", "橘麻美", 0],
    [5, "危険な誘惑 #05", "橘麻美", 0],
    [6, "危険な誘惑 #06", "橘麻美", 0],
    [7, "危険な誘惑 #07", "橘麻美", 0],
    [8, "危険な誘惑 #08", "橘麻美", 0],
]
links = ["https://beta.musicbrainz.org/release/d38d9877-2d90-49ae-bc4e-6918f9d63d7c", "https://vgmdb.net/album/74615"]

[5598f569276fd6a01935a4b06a8c46f6]
catalognumber = "AICL-3537~9"
date = "2018-06-27"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉 [ダーリン・イン・ザ・フランキス Deluxe Edition] Vocal Disc 2"
tracks = [
    [1, "「ダーリン・イン・ザ・フランキス」 ノンクレジットOP映像 (Phase1)", "中島美嘉", 0],
    [2, "「ダーリン・イン・ザ・フランキス」 ノンクレジットOP映像 (Phase2)", "中島美嘉", 0],
    [3, "「ダーリン・イン・ザ・フランキス」 ティーザーSPOT", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/2c4fdf63-4acd-4c6c-b07f-96cf31aa45a5", "https://vgmdb.net/album/77479"]

[0d7fb556176771a293f1918753c6e037]
catalognumber = "AICL-3537~9"
date = "2018-06-27"
album = "KISS OF DEATH (Produced by HYDE) / 中島美嘉 [ダーリン・イン・ザ・フランキス Deluxe Edition] Vocal Disc 1"
tracks = [
    [1, "KISS OF DEATH (Produced by HYDE) (Main MIX)", "中島美嘉", 0],
    [2, "KISS OF DEATH (Produced by HYDE) -TV Size- / Phase1", "中島美嘉", 0],
    [3, "KISS OF DEATH (Produced by HYDE) -TV Size- / Phase2", "中島美嘉", 0],
    [4, "KISS OF DEATH (Produced by HYDE) (Remix ver.)", "中島美嘉", 0],
    [5, "KISS OF DEATH (Produced by HYDE) (Piano Inst ver.)", "Asami Tachibana", 0],
]
links = ["https://beta.musicbrainz.org/release/2c4fdf63-4acd-4c6c-b07f-96cf31aa45a5", "https://vgmdb.net/album/77479"]

[23072ff22ec15c7010ba5f3bb413ff6e]
catalognumber = "SVWC-70343~4"
date = "2018-06-27"
album = "ダーリン・イン・ザ・フランキス エンディング集 vol.2 Disc 1 (CD) [SVWC-70343]"
tracks = [
    [1, "ひとり", "XX:me", 0],
    [2, "escape", "XX:me", 0],
    [3, "ダーリン", "XX:me", 0],
    [4, "ひとり (TV Size ver.)", "XX:me", 0],
    [5, "escape (TV Size ver.)", "XX:me", 0],
    [6, "ダーリン (TV Size ver.)", "XX:me", 0],
]
links = ["https://beta.musicbrainz.org/release/593451ba-6125-4a81-b267-e230a7357d5a", "https://vgmdb.net/album/74095"]

[31fa56d8f8a64ff40fb78e061e80c7fb]
catalognumber = "SVWC-70343~4"
date = "2018-06-27"
album = "ダーリン・イン・ザ・フランキス エンディング集 vol.2 Disc 2 (DVD) [SVWC-70344]"
tracks = [
    [1, "ひとり", "XX:me", 0],
    [2, "Escape", "XX:me", 0],
]
links = ["https://beta.musicbrainz.org/release/593451ba-6125-4a81-b267-e230a7357d5a", "https://vgmdb.net/album/74095"]

[85d6c58d8f4cf3e55de23071e1a4548f]
catalognumber = "ANZX-14448"
date = "2018-07-25"
album = "ダーリン・イン・ザ・フランキス オリジナルサウンドトラック vol.2"
tracks = [
    [1, "FUSE", "橘麻美", 0],
    [2, "Battle Cry", "橘麻美", 0],
    [3, "Your smile", "橘麻美", 0],
    [4, "Abandoned Places", "橘麻美", 0],
    [5, "The Seven Sages", "橘麻美", 0],
    [6, "Klaxosaur", "橘麻美", 0],
    [7, "Gutenberg", "橘麻美", 0],
    [8, "Shady History", "橘麻美", 0],
    [9, "ADuLt", "橘麻美", 0],
    [10, "One’s Word", "橘麻美", 0],
    [11, "Vita", "橘麻美", 0],
    [12, "CHiLDRen", "橘麻美", 0],
    [13, "CODE:015", "橘麻美", 0],
    [14, "Lilac", "橘麻美", 0],
    [15, "Red Hibiscus", "橘麻美", 0],
    [16, "The Sands", "橘麻美", 0],
    [17, "Boys×Girls", "橘麻美", 0],
    [18, "VICTORIA –piano ver.–", "橘麻美", 0],
    [19, "Lilac –guitar ver.–", "橘麻美", 0],
    [20, "Mistilteinn", "橘麻美", 0],
    [21, "D♯regards", "橘麻美", 0],
]
links = ["https://beta.musicbrainz.org/release/7832f8e3-5ba1-42ab-bdde-7c59fef5df5b", "https://vgmdb.net/album/74731"]

[9b416ec2febf207d69bdcb30b244bbc7]
catalognumber = "UICV-9288"
date = "2018-08-01"
album = "AFTER LIGHT / HYDE [Limited Edition]"
tracks = [
    [1, "AFTER LIGHT", "HYDE", 0],
    [2, "KISS OF DEATH", "HYDE", 0],
]
links = ["https://beta.musicbrainz.org/release/1ed68f44-914b-407e-851d-1ae8b895cb4f", "https://vgmdb.net/album/78581"]

[b3d54d435d8b1cce533d2022f0dd5a4c]
catalognumber = "UICV-5074"
date = "2018-08-01"
album = "AFTER LIGHT / HYDE"
tracks = [
    [1, "AFTER LIGHT", "HYDE", 0],
    [2, "KISS OF DEATH", "HYDE", 0],
]
links = ["https://beta.musicbrainz.org/release/1ed68f44-914b-407e-851d-1ae8b895cb4f", "https://vgmdb.net/album/78580"]

[b5ae0d35e552190c7cb0091f7761f00c]
catalognumber = "PJO-0004"
date = "2018-08-10"
album = "works ~2017-2018~"
tracks = [
    [1, "Make debut!", "Precious Jazz Orchestra", 0],
    [2, "ふゆびより", "Precious Jazz Orchestra", 0],
    [3, "Chant", "Precious Jazz Orchestra", 0],
    [4, "KISS OF DEATH", "Precious Jazz Orchestra", 0],
    [5, "CLEAR", "Precious Jazz Orchestra", 0],
    [6, "ここから、ここから", "Precious Jazz Orchestra", 0],
]
links = ["https://beta.musicbrainz.org/release/2107ff89-c117-4d1f-a9b2-84571349a525", "https://vgmdb.net/album/81917"]

[6b70119cd219ee61de2ef0a7a77a3ec5]
catalognumber = "ANZX-14450"
date = "2018-08-29"
album = "ダーリン・イン・ザ・フランキス オリジナルサウンドトラック vol.3"
tracks = [
    [1, "CODE:016", "橘麻美", 0],
    [2, "RoCco", "橘麻美", 0],
    [3, "Lotus", "橘麻美", 0],
    [4, "CODE:001", "橘麻美", 0],
    [5, "CoiL", "橘麻美", 0],
    [6, "DESPAIR", "橘麻美", 0],
    [7, "InVaDeR", "橘麻美", 0],
    [8, "GLADIOLUS", "橘麻美", 0],
    [9, "JUSTICE", "橘麻美", 0],
    [10, "Requiem", "橘麻美", 0],
    [11, "Cherry blossoms", "橘麻美", 0],
    [12, "HIRO and ZERO TWO", "橘麻美", 0],
    [13, "cÅGE –piano ver.–", "橘麻美", 0],
    [14, "JUSTICE –Epiano ver.–", "橘麻美", 0],
    [15, "Pray for..", "橘麻美", 0],
    [16, "cÅGE –SPS ver.–", "橘麻美", 0],
    [17, "FUSE –instrumental–", "橘麻美", 0],
    [18, "Battle Cry –instrumental–", "橘麻美", 0],
    [19, "Vanquish –instrumental–", "橘麻美", 0],
    [20, "D♯regards –instrumental–", "橘麻美", 0],
    [21, "cAGE –instrumental–", "橘麻美", 0],
    [22, "Torikago ~BGM‐Rearrange‐guitar ver.~", "橘麻美", 0],
]
links = ["https://beta.musicbrainz.org/release/7e8b1e2a-dcc1-42b9-b961-59e1c357ed48", "https://vgmdb.net/album/74732"]

[75d2c79fd689f243212aaa51647a9f8b]
catalognumber = "ANZX-14452"
date = "2018-09-26"
album = "ダーリン・イン・ザ・フランキス Drama CD vol.2"
tracks = [
    [1, "第1話 「13部隊の一番長い夜」", "上村祐翔, 戸松遥, 市ノ瀬加那, 市川蒼, 梅原裕一郎, 田村睦心, 山下七海 & 早見沙織", 0],
    [2, "第2話 「ダイエット大作戦」", "上村祐翔, 戸松遥, 市ノ瀬加那, 市川蒼, 梅原裕一郎, 田村睦心, 山下七海 & 早見沙織", 0],
    [3, "第3話 「第13都市ミストルティンにおける環境対応テスト、28次定例報告」", "上村祐翔, 戸松遥, 市ノ瀬加那, 市川蒼, 梅原裕一郎, 田村睦心, 山下七海 & 早見沙織", 0],
]
links = ["https://beta.musicbrainz.org/release/08b4801e-e854-4ca4-812b-5fa697d3222c", "https://vgmdb.net/album/74733"]

[2c93fac82a5ace7cdca87a690f1d2038]
catalognumber = "ANZX-14454"
date = "2018-10-24"
album = "ダーリン・イン・ザ・フランキス Drama CD vol.3"
tracks = [
    [1, "第1話 「ナインズ」", "", 0],
    [2, "第2話 「NINE CHILDREN & a BABY(?)」", "", 0],
    [3, "第3話 「あの時の君は」", "", 0],
]
links = ["https://vgmdb.net/album/74734"]

[49eb84c19982264ffa4336df44674f24]
catalognumber = "AICL-3898"
date = "2020-10-07"
album = "JOKER / 中島美嘉"
tracks = [
    [1, "ノクターン", "中島美嘉", 0],
    [2, "A or B", "中島美嘉", 0],
    [3, "Kiss of Death", "中島美嘉", 0],
    [4, "Good Bye", "中島美嘉", 0],
    [5, "Desire", "中島美嘉", 0],
    [6, "So What", "中島美嘉", 0],
    [7, "Justice", "中島美嘉", 0],
    [8, "無垢なるもの (Marie Starring Mika Nakashima)", "Marie starring MIKA NAKASHIMA", 0],
    [9, "Happy Life (中島美嘉×salyu)", "中島美嘉×Salyu", 0],
    [10, "彩恋～sai_ren～", "中島美嘉", 0],
    [11, "Innocent", "中島美嘉", 0],
    [12, "ドミノ", "中島美嘉", 0],
    [13, "夜が明ける前に", "中島美嘉", 0],
    [14, "虹が出たら君に逢いに", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/45f0746f-338b-48a7-8090-3f6d5d346f9c", "https://vgmdb.net/album/102547"]

[3be0e04826d9e49ddf12e4e6921b9212]
catalognumber = "AICL-3896~7"
date = "2020-10-07"
album = "JOKER / 中島美嘉 [初回盤] Vocal"
tracks = [
    [1, "ノクターン", "中島美嘉", 0],
    [2, "A or B", "中島美嘉", 0],
    [3, "KISS OF DEATH", "中島美嘉", 0],
    [4, "Good Bye", "中島美嘉", 0],
    [5, "DESIRE", "中島美嘉", 0],
    [6, "So What", "中島美嘉", 0],
    [7, "Justice", "中島美嘉", 0],
    [8, "無垢なるもの", "Marie starring MIKA NAKASHIMA", 0],
    [9, "Happy Life", "中島美嘉×Salyu", 0],
    [10, "彩恋 〜SAI_REN〜", "中島美嘉", 0],
    [11, "innocent", "中島美嘉", 0],
    [12, "ドミノ", "中島美嘉", 0],
    [13, "夜が明ける前に", "中島美嘉", 0],
    [14, "虹が出たら君に逢いに", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/5cf864e6-83c2-48c7-b208-ee776fcb4307", "https://vgmdb.net/album/102548"]

[8692eecfa63e0f4c347c2ffb13c6e822]
catalognumber = "AICL-3896~7"
date = "2020-10-07"
album = "JOKER / 中島美嘉 [初回盤] Arrangement, Vocal, Live Event, Video"
tracks = [
    [1, "A or B [Music Video]", "中島美嘉", 0],
    [2, "KISS OF DEATH [Music Video]", "中島美嘉", 0],
    [3, "イノサンRouge [Music Video]", "Marie starring MIKA NAKASHIMA", 0],
    [4, "ノクターン [Music Video]", "中島美嘉", 0],
    [5, "Justice [Music Video]", "中島美嘉", 0],
    [6, "innocent [MIKA NAKASHIMA Special Studio Live]", "中島美嘉", 0],
    [7, "KISS OF DEATH [MIKA NAKASHIMA Special Studio Live]", "中島美嘉", 0],
    [8, "ノクターン [MIKA NAKASHIMA Special Studio Live]", "中島美嘉", 0],
    [9, "A or B [MIKA NAKASHIMA Special Studio Live]", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/5cf864e6-83c2-48c7-b208-ee776fcb4307", "https://vgmdb.net/album/102548"]

[9606f9b84dbf1cdf1d6c67e1b68bf2c6]
catalognumber = "AICL-3994"
date = "2020-12-02"
album = "WITH / 中島美嘉"
tracks = [
    [1, "真冬のハーモニー", "中島美嘉 with 藤巻亮太", 0],
    [2, "イノサンRouge", "Marie starring MIKA NAKASHIMA", 0],
    [3, "KISS OF DEATH (Produced by HYDE)", "中島美嘉", 0],
    [4, "Happy Life", "中島美嘉×Salyu", 0],
    [5, "花束", "中島美嘉", 0],
    [6, "愛の歌", "中島美嘉", 0],
    [7, "Fighter", "中島美嘉×加藤ミリヤ", 0],
    [8, "僕が死のうと思ったのは", "中島美嘉", 0],
    [9, "愛詞 (あいことば)", "中島美嘉", 0],
    [10, "声", "中島美嘉", 0],
    [11, "I DON'T KNOW", "MICA 3 CHU", 0],
    [12, "素直なまま", "中島美嘉", 0],
    [13, "一色", "NANA starring MIKA NAKASHIMA", 0],
    [14, "GLAMOROUS SKY", "NANA starring MIKA NAKASHIMA", 0],
    [15, "Love Addict", "中島美嘉", 0],
    [16, "DESTINY’S LOTUS", "中島美嘉", 0],
]
links = ["https://beta.musicbrainz.org/release/d662953d-9358-431a-a990-0f0915186d1d", "https://vgmdb.net/album/106630"]

[9a6109d1c3ea4692c5ce3e4408498528]
catalognumber = "N/A"
date = "2021-12-25"
album = "「アンデミックプラス」"
tracks = [
    [1, "Ready To (VRC6)", "nocturnalplant", 0],
    [2, "Here (N163)", "nocturnalplant", 0],
    [3, "Kaibutsu / 怪物 (VRC6)", "nocturnalplant", 0],
    [4, "It's Like a Small Light / それは小さな光のような (N163)", "nocturnalplant", 0],
    [5, "My Dream Within a Dream / ユメのなかノわたしのユメ(NES)", "nocturnalplant", 0],
    [6, "Escape (MMC5)", "nocturnalplant", 0],
    [7, "Ugoku, Ugoku / 動く、動く (VRC6)", "nocturnalplant", 0],
    [8, "Seasons Die One After Another / 季節は次々死んでいく (VRC6)", "nocturnalplant", 0],
    [9, "Wild Side (VRC6)", "nocturnalplant", 0],
    [10, "Lacrimosa (VRC7)", "nocturnalplant", 0],
    [11, "One Room Sugar Life / ワンルームシュガーライフ(VRC6)", "nocturnalplant", 0],
    [12, "Spice / スパイス (N163)", "nocturnalplant", 0],
    [13, "Fiction / フィクション (MMC5)", "nocturnalplant", 0],
    [14, "Nai Nai / ないない (VRC6)", "nocturnalplant", 0],
    [15, "Wonderful Wonder (MMC5)", "nocturnalplant", 0],
    [16, "Kami Iro-Awase / カミイロアワセ (VRC6)", "nocturnalplant", 0],
    [17, "Life is Cider / Life is サイダー (MMC5)", "nocturnalplant", 0],
    [18, "Chiisana Hibi / ちいさな日々 (FDS)", "nocturnalplant", 0],
    [19, "Daddy Daddy Do (VRC6)", "nocturnalplant", 0],
    [20, "The Sound of Rain / 雨だれの歌 (MMC5)", "nocturnalplant", 0],
]
links = ["https://beta.musicbrainz.org/release/b59b4b7f-a004-456b-b187-0df52d856a06", "https://vgmdb.net/album/121589"]
