[2506a9f63b482304d626882f6bee0a96]
catalognumber = "COCC-16507"
date = "2011-08-24"
album = "yes, prisoner / Cras numquam scire"
tracks = [
    [1, "yes, prisoner", "maRIONnetTe", 1],
    [2, "Cras numquam scire", "Yucca feat. Hugh Anthony Disward (CV:小野大輔", 1],
    [3, "yes, prisoner (instrumental)", "maRIONnetTe", 0],
    [4, "Cras numquam scire (instrumental)", "Yucca feat. Hugh Anthony Disward (CV:小野大輔", 1],
]
links = ["https://beta.musicbrainz.org/release/02c53f42-8e1c-4db0-b79f-3b7e06d5ea4e", "https://vgmdb.net/album/26789"]

[28c56a5e08a9b132bc1868c990146f6c]
catalognumber = "COCX-36945~6"
date = "2011-10-12"
album = "TVアニメ「ダンタリアンの書架」オリジナル･サウンドトラック組曲「ダンタリアンの書架」 Disc 1 [COCX-36945]"
tracks = [
    [1, "Cras numquam scire (TV-Size)", "Yucca", 1],
    [2, "第1組曲 1楽章 古く深い静かな森。誰の気配もなく…", "辻陽", 0],
    [3, "第1組曲 2楽章 澄んだ空気。感情的になり過ぎず、歌うように。", "辻陽", 0],
    [4, "第1組曲 3楽章 古歌を口ずさむ。素朴さと端正な輝き。", "辻陽", 0],
    [5, "第2組曲 1楽章 漆黒の湖底。湖面に映える月光。", "辻陽", 0],
    [6, "第2組曲 2楽章 牧歌的情景。途中、濃霧に遭って彷徨う。", "辻陽", 0],
    [7, "第2組曲 3楽章 森の聖堂に響く音。振り返ると野を吹く涼風。", "辻陽", 0],
    [8, "第3組曲 1楽章 甘美な追想と舞曲的性格の中間部。", "辻陽", 0],
    [9, "第3組曲 2楽章 気まぐれな規則性と原始的な力。", "辻陽", 0],
    [10, "第3組曲 3楽章 寂れた庭園の跡。何かが崩壊していく様。", "辻陽", 0],
    [11, "第4組曲 1楽章 疲れる行軍。危うい対称と時折溢れる感情。", "辻陽", 0],
    [12, "第4組曲 2楽章 濃霧の中に現れる城。城中での諧謔的な舞踏。再び濃霧の中へ消える。", "辻陽", 0],
    [13, "第4組曲 3楽章 夢想的情緒。驟雨の様なピアノ間奏。", "辻陽", 0],
]
links = ["https://beta.musicbrainz.org/release/8e2b8c20-6f82-4893-8dbf-982a927b8e19", "https://vgmdb.net/album/28398"]

[a0ae26033dccfeb18016fc5ace49a2b0]
catalognumber = "COCX-36945~6"
date = "2011-10-12"
album = "TVアニメ「ダンタリアンの書架」オリジナル･サウンドトラック組曲「ダンタリアンの書架」 Disc 2 [COCX-36946]"
tracks = [
    [1, "第5組曲 1楽章 虚ろな木管ファンファーレ。伽藍の中。返事のない独白。一瞬の光。", "辻陽", 0],
    [2, "第5組曲 2楽章 異形のピアノ。救えぬヴァイオリン。", "辻陽", 0],
    [3, "第5組曲 3楽章 懐かしい情景。多少の喪失感と一抹の希望。", "辻陽", 0],
    [4, "第6組曲 1楽章 分厚い壁の中から聴こえる声音。虚空。", "辻陽", 0],
    [5, "第6組曲 2楽章 湿った生暖かい空気。執拗な祈祷とたき火の跡。", "辻陽", 0],
    [6, "第6組曲 3楽章 頬を撫でるそよ風。淡い光射す草原。", "辻陽", 0],
    [7, "第7組曲 1楽章 童心。夏の終わり…", "辻陽", 0],
    [8, "第7組曲 2楽章 揺らぎ・微睡みの幸福感。故郷の夢。", "辻陽", 0],
    [9, "第7組曲 3楽章 旅路。光射す方角を目指して…", "辻陽", 0],
    [10, "第8組曲 1楽章 闇に誕生する光…そして増殖。", "辻陽", 0],
    [11, "第8組曲 2楽章 旅の空。雲の変容と望郷。", "辻陽", 0],
    [12, "第8組曲 3楽章 真っ直ぐに続く道。回想と物語のエピローグ。", "辻陽", 0],
    [13, "ダンタリアンの為の3つの音塊", "辻陽", 0],
    [14, "Dallaglio's Piano", "辻陽", 0],
    [15, "Test Play", "辻陽", 0],
    [16, "Christabel's Violin", "辻陽", 0],
    [17, "Study for PlayerPiano&Violin", "辻陽", 0],
    [18, "Exit", "辻陽", 0],
    [19, "Piece for Doll", "辻陽", 0],
    [20, "TangoAntiqua", "辻陽", 0],
]
links = ["https://beta.musicbrainz.org/release/8e2b8c20-6f82-4893-8dbf-982a927b8e19", "https://vgmdb.net/album/28398"]
