[57f6b5974c28ba0c09f6d74f183b6639]
catalognumber = "EYCA-11832/B"
date = "2018-02-28"
album = "スキノスキル / Wake Up, Girls! Disc 1 (CD)"
tracks = [
    [1, "スキノスキル", "Wake Up, Girls!", 1],
    [2, "SHIFT", "Wake Up, Girls!", 1],
    [3, "スキノスキル (Instrumental)", "Wake Up, Girls!", 1],
    [4, "SHIFT (Instrumental)", "Wake Up, Girls!", 1],
]
links = ["https://beta.musicbrainz.org/release/eaedff6b-d12d-4c3c-8cb7-4f743f65a107", "https://vgmdb.net/album/73069"]

[543fac20a2241fe7c100be0dcc2a35c8]
catalognumber = "EYCA-11832/B"
date = "2018-02-28"
album = "スキノスキル / Wake Up, Girls! Disc 2 (DVD)"
tracks = [
    [1, "スキノスキル Music Video", "Wake Up, Girls!", 1],
]
links = ["https://beta.musicbrainz.org/release/eaedff6b-d12d-4c3c-8cb7-4f743f65a107", "https://vgmdb.net/album/73069"]

[b87933f4c4dee8dc3ff8895217f93269]
catalognumber = "EYCA-11830/B"
date = "2018-02-28"
album = "スライドライド / Run Girls, Run! Disc 1 (CD)"
tracks = [
    [1, "スライドライド", "Run Girls, Run!", 1],
    [2, "サクラジェラート", "Run Girls, Run!", 1],
    [3, "スライドライド (Insrumental)", "Run Girls, Run!", 1],
    [4, "サクラジェラート (Instrumental)", "Run Girls, Run!", 1],
]
links = ["https://beta.musicbrainz.org/release/b84b3c2f-393e-465e-bfdb-4e2ffb6c32f9", "https://vgmdb.net/album/73071"]

[75e16225478e88cf8330d94fa3a5b9a5]
catalognumber = "EYCA-11830/B"
date = "2018-02-28"
album = "スライドライド / Run Girls, Run! Disc 2 (DVD)"
tracks = [
    [1, "スライドライド Music Video", "Run Girls, Run!", 1],
]
links = ["https://beta.musicbrainz.org/release/b84b3c2f-393e-465e-bfdb-4e2ffb6c32f9", "https://vgmdb.net/album/73071"]

[b35030210271487eee083ac5fa050cea]
catalognumber = "EYCA-11831"
date = "2018-02-28"
album = "スライドライド / Run Girls, Run!"
tracks = [
    [1, "スライドライド", "Run Girls, Run!", 2],
    [2, "サクラジェラート", "Run Girls, Run!", 1],
    [3, "スライドライド (Insrumental)", "Run Girls, Run!", 1],
    [4, "サクラジェラート (Instrumental)", "Run Girls, Run!", 1],
]
links = ["https://beta.musicbrainz.org/release/3b20e268-dc9f-46d5-9ee4-37d63004af41", "https://vgmdb.net/album/73070"]

[18bf31e964fea3466a62720ee16e1357]
catalognumber = "EYCA-11833"
date = "2018-02-28"
album = "スキノスキル / Wake Up, Girls!"
tracks = [
    [1, "スキノスキル", "Wake Up, Girls!", 2],
    [2, "SHIFT", "Wake Up, Girls!", 1],
    [3, "スキノスキル (Instrumental)", "Wake Up, Girls!", 1],
    [4, "SHIFT (Instrumental)", "Wake Up, Girls!", 1],
]
links = ["https://beta.musicbrainz.org/release/9e3bbc01-a375-47ef-87a7-5be12fbcc7a7", "https://vgmdb.net/album/73068"]

[d0b8d26a9f6e4f6b195cbbc77e91b88e]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 6 (CD) [EYCA-12105]"
tracks = [
    [1, "Polaris", "Wake Up, Girls!", 0],
    [2, "雫の冠", "Wake Up, Girls!", 0],
    [3, "7 Senses", "Wake Up, Girls!", 0],
    [4, "TUNAGO", "Wake Up, Girls!", 0],
    [5, "ゆき模様 恋のもよう", "Wake Up, Girls!", 0],
    [6, "同じ夢を見てる", "ミツキとヨウコ(CV.大坪由佳&吉岡茉祐)", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[c832911eb73c4a689ea61e9ca0fbad20]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 7 (CD) [EYCA-12106]"
tracks = [
    [1, "恋?で愛?で暴君です!", "Wake Up, Girls!", 0],
    [2, "僕らのフロンティア", "Wake Up, Girls!", 0],
    [3, "スキノスキル", "Wake Up, Girls!", 1],
    [4, "SHIFT", "Wake Up, Girls!", 1],
    [5, "One In A Billion (Wake Up, Girls! ver.)", "Wake Up, Girls!", 0],
    [6, "ハートライン (Wake Up, Girls! ver.)", "Wake Up, Girls!", 0],
    [7, "王様のカデンツァ (Wake Up, Girls! ver.)", "Wake Up, Girls!", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[df268fea83cc593611d193fbb83b81d4]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 1 (CD) [EYCA-12100]"
tracks = [
    [1, "タチアガレ!", "Wake Up, Girls!", 0],
    [2, "7 Girls War", "Wake Up, Girls!", 0],
    [3, "言の葉 青葉", "Wake Up, Girls!", 0],
    [4, "16歳のアガペー", "Wake Up, Girls!", 0],
    [5, "極上スマイル", "Wake Up, Girls!", 0],
    [6, "ワグ・ズーズー", "Wake Up, Girlzoo!", 0],
    [7, "地下鉄ラビリンス", "Wake Up, Girls!", 0],
    [8, "素顔でKISS ME", "Wake Up, Girls!", 0],
    [9, "少女交響曲 (Album ver.)", "Wake Up, Girls!", 0],
    [10, "Beyond the Bottom (Album ver.)", "Wake Up, Girls!", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[ed4af25c39f56e8f9d6b17d93448468a]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 2 (CD) [EYCA-12101]"
tracks = [
    [1, "あぁ光塚歌劇団", "光塚歌劇団", 0],
    [2, "太陽曰く燃えよカオス (岡本未夕 ver.)", "Wake Up, Girls!", 0],
    [3, "Regain Brave", "木高ゆみ(CV:高木美佑)", 0],
    [4, "End of endless", "mip'o(CV:田中美海)", 0],
    [5, "プラチナ・サンライズ", "Wake Up, Girls!", 0],
    [6, "セブンティーン・クライシス", "Wake Up, Girls!", 0],
    [7, "タイトロープ ラナウェイ", "Wake Up, Girls!", 0],
    [8, "outlander rhapsody", "Wake Up, Girls!", 0],
    [9, "お約束たいそう", "片山実波(CV:田中美海)", 0],
    [10, "お約束たいそう2", "片山実波(CV.田中美海)", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[3d39bd92a5380ab35facc65fd15bedae]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 3 (CD) [EYCA-12102]"
tracks = [
    [1, "WOO YEAH!", "岡本未夕(CV:高木美佑))", 0],
    [2, "ハジマル", "島田真夢(CV:吉岡茉祐)", 0],
    [3, "歌と魚とハダシとわたし", "片山実波(CV:田中美海)", 0],
    [4, "オオカミとピアノ", "久海菜々美(CV:山下七海)", 0],
    [5, "可笑しの国", "林田藍里(CV:永野愛理)", 0],
    [6, "スキ キライ ナイト", "菊間夏夜(CV:奥野香耶)", 0],
    [7, "ステラ・ドライブ", "七瀬佳乃(CV:青山吉能)", 0],
    [8, "ワグ・ズーズー (miyu ver.)", "岡本未夕(CV:高木美佑)", 0],
    [9, "ワグ・ズーズー (mayu ver.)", "島田真夢(CV:吉岡茉祐)", 0],
    [10, "ワグ・ズーズー (minami ver.)", "Wake Up, Girlzoo!,Wake Up, Girls!,片山実波(CV.田中美海)", 0],
    [11, "ワグ・ズーズー (nanami ver.)", "Wake Up, Girlzoo!,Wake Up, Girls!,久海菜々美(CV.山下七海)", 0],
    [12, "ワグ・ズーズー (airi ver.)", "Wake Up, Girlzoo!,Wake Up, Girls!,林田藍里(CV.永野愛理)", 0],
    [13, "ワグ・ズーズー (kaya ver.)", "菊間夏夜(CV.奥野香耶)", 0],
    [14, "ワグ・ズーズー (yoshino ver.)", "Wake Up, Girlzoo!,Wake Up, Girls!,七瀬佳乃(CV.青山吉能)", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[bb4aecf41d4f3f4b1ff9fd990b32b7e1]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 4 (CD) [EYCA-12103]"
tracks = [
    [1, "It's amazing show time☆", "岡本未夕(CV:高木美佑)", 0],
    [2, "走り出したencore", "島田真夢(CV:吉岡茉祐)", 0],
    [3, "それいけオトメ", "片山実波(田中美海)", 0],
    [4, "snuggery", "久海菜々美(CV: 山下七海)", 0],
    [5, "ヒカリキラリミルキーウェイ", "林田藍里(CV:永野愛理)", 0],
    [6, "Into The Light", "菊間夏夜(CV:奥野香耶)", 0],
    [7, "青い月のシャングリラ", "七瀬佳乃(CV:青山吉能)", 0],
    [8, "HIGAWARI PRINCESS (PRINCESS Miyu ver.)", "Wake Up, Girls!", 0],
    [9, "HIGAWARI PRINCESS (PRINCESS Mayu ver.)", "島田真夢(CV.吉岡茉祐)", 0],
    [10, "HIGAWARI PRINCESS (PRINCESS Minami ver.)", "片山実波(田中美海)", 0],
    [11, "HIGAWARI PRINCESS (PRINCESS Nanami ver.)", "久海菜々美(CV.山下七海)", 0],
    [12, "HIGAWARI PRINCESS (PRINCESS Airi ver.)", "Wake Up, Girls!", 0],
    [13, "HIGAWARI PRINCESS (PRINCESS Kaya ver.)", "菊間夏夜(CV.奥野香耶)", 0],
    [14, "HIGAWARI PRINCESS (PRINCESS Yoshino ver.)", "七瀬佳乃(CV.青山吉能)", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[a1fffe911bb4984c8e6fe7c52fee3e76]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 5 (CD) [EYCA-12104]"
tracks = [
    [1, "シャリラ!", "岡本未夕(CV.高木美佑)", 0],
    [2, "ユメ、まっすぐ。", "島田真夢(CV.吉岡茉祐)", 0],
    [3, "ぽんと PUSH! もっと SMILE!", "片山実波(CV.田中美海)", 0],
    [4, "ドラマチックを君と", "久海菜々美(CV.山下七海)", 0],
    [5, "Party! Party!", "林田藍里(CV.永野愛理)", 0],
    [6, "プライド", "菊間夏夜(CV.奥野香耶)", 0],
    [7, "Dice of Life!", "七瀬佳乃(CV.青山吉能)", 0],
    [8, "Non stop diamond hope (Miyu ver.)", "岡本未夕(CV.高木美佑)", 0],
    [9, "Non stop diamond hope (Mayu ver.)", "島田真夢(CV.吉岡茉祐)", 0],
    [10, "Non stop diamond hope (Minami ver.)", "片山実波(CV.田中美海)", 0],
    [11, "Non stop diamond hope (Nanami ver.)", "久海菜々美(CV.山下七海)", 0],
    [12, "Non stop diamond hope (Airi ver.)", "林田藍里(CV.永野愛理)", 0],
    [13, "Non stop diamond hope (Kaya ver.)", "菊間夏夜(CV.奥野香耶)", 0],
    [14, "Non stop diamond hope (Yoshino ver.)", "七瀬佳乃(CV.青山吉能)", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[c57f3590cc2c1e5c5170a8274702f2a7]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 8 (CD) [EYCA-12107]"
tracks = [
    [1, "海そしてシャッター通り", "Wake Up, Girls!", 0],
    [2, "言葉の結晶", "Wake Up, Girls!", 0],
    [3, "土曜日のフライト", "Wake Up, Girls!", 0],
    [4, "さようならのパレード", "Wake Up, Girls!", 0],
    [5, "海そしてシャッター通り (Instrumental)", "Wake Up, Girls!", 0],
    [6, "言葉の結晶 (Instrumental)", "Wake Up, Girls!", 0],
    [7, "土曜日のフライト (Instrumental)", "Wake Up, Girls!", 0],
    [8, "さようならのパレード (Instrumental)", "Wake Up, Girls!", 0],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[294d9e22a1e6bde18d1aaf8220e0697e]
catalognumber = "EYCA-12100~7/B"
date = "2019-01-23"
album = "Wake Up, Best! MEMORIAL Disc 9 (Blu-ray) [EYCA-12107B]"
tracks = [
    [1, "タチアガレ! Music Video", "Wake Up, Girls!", 0],
    [2, "7 Girls War Music Video", "Wake Up, Girls!", 0],
    [3, "言の葉 青葉 Music Video", "Wake Up, Girls!", 0],
    [4, "少女交響曲 Music video", "Wake Up, Girls!", 0],
    [5, "Beyond the Bottom Music Video", "Wake Up, Girls!", 0],
    [6, "僕らのフロンテイア Music Video", "Wake Up, Girls!", 0],
    [7, "恋?で愛?で暴君です! Music Video", "Wake Up, Girls!", 0],
    [8, "TUNAGO Music Video", "Wake Up, Girls!", 0],
    [9, "7 Senses Music Video", "Wake Up, Girls!", 0],
    [10, "雫の冠 Music Video", "Wake Up, Girls!", 0],
    [11, "スキノスキル Music Video", "Wake Up, Girls!", 1],
]
links = ["https://beta.musicbrainz.org/release/3a91b24f-645f-46f6-85fe-6cdb9f0e29c3", "https://vgmdb.net/album/81098"]

[7fea4d1f291c7a65c0b26c9c70ae2bac]
catalognumber = "EYCA-12883~4"
date = "2020-03-04"
album = "Wake Up, Girls! LIVE ALBUM 〜想い出のパレード〜 Disc 1 [EYCA-12883]"
tracks = [
    [1, "タチアガレ! [Live]", "Wake Up, Girls!", 0],
    [2, "16歳のアガペー [Live]", "Wake Up, Girls!", 0],
    [3, "7 Girls War [Live]", "Wake Up, Girls!", 0],
    [4, "ゆき模様 恋のもよう [Live]", "Wake Up, Girls!", 0],
    [5, "言の葉 青葉 [Live]", "Wake Up, Girls!", 0],
    [6, "One In A Billion [Live]", "Wake Up, Girls!", 0],
    [7, "素顔でKISS ME [Live]", "Wake Up, Girls!", 0],
    [8, "恋?で愛?で暴君です! [Live]", "Wake Up, Girls!", 0],
    [9, "キャラソンサビメドレー (ハジマル〜可笑しの国〜ステラ・ドライブ〜スキ キライ ナイト〜オオカミとピアノ〜歌と魚とハダシとワタシ〜WOO YEAH!〜Non stop diamon hope) [Live]", "Wake Up, Girls!", 0],
    [10, "ワグ・ズーズー [Live]", "Wake Up, Girls!", 0],
    [11, "HIGAWARI PRINCESS [Live]", "Wake Up, Girls!", 0],
    [12, "スキノスキル [Live]", "Wake Up, Girls!", 1],
    [13, "僕らのフロンティア [Live]", "Wake Up, Girls!", 0],
]
links = ["https://beta.musicbrainz.org/release/3698306b-8f77-4560-b76b-ef7434d241c2", "https://vgmdb.net/album/94496"]

[407b98fa70856a52d2fba11ec0f5ad86]
catalognumber = "EYCA-12883~4"
date = "2020-03-04"
album = "Wake Up, Girls! LIVE ALBUM 〜想い出のパレード〜 Disc 2 [EYCA-12884]"
tracks = [
    [1, "7 Senses [Live]", "Wake Up, Girls!", 0],
    [2, "極上スマイル [Live]", "Wake Up, Girls!", 0],
    [3, "雫の冠 [Live]", "Wake Up, Girls!", 0],
    [4, "少女交響曲 [Live]", "Wake Up, Girls!", 0],
    [5, "Beyond the Bottom [Live]", "Wake Up, Girls!", 0],
    [6, "海そしてシャッター通り [Live]", "Wake Up, Girls!", 0],
    [7, "言葉の結晶 [Live]", "Wake Up, Girls!", 0],
    [8, "土曜日のフライト [Live]", "Wake Up, Girls!", 0],
    [9, "さようならのパレード [Live]", "Wake Up, Girls!", 0],
    [10, "SHIFT [Live] <アンコール>", "Wake Up, Girls!", 1],
    [11, "地下鉄ラビリンス [Live] <アンコール>", "Wake Up, Girls!", 0],
    [12, "TUNAGO [Live] <アンコール>", "Wake Up, Girls!", 0],
    [13, "Polaris [Live] <ダブル・アンコール>", "Wake Up, Girls!", 0],
    [14, "タチアガレ! [Live] <トリプル・アンコール>", "Wake Up, Girls!", 0],
]
links = ["https://beta.musicbrainz.org/release/3698306b-8f77-4560-b76b-ef7434d241c2", "https://vgmdb.net/album/94496"]

[34df2560ae8ab94d8ceaab027a7942c6]
catalognumber = "N/A"
date = "2020-03-10"
album = "デスマーチからはじまる異世界狂想曲 ドラマCD「幻の料理」"
tracks = [
    [1, "幻の料理 1", "[dialogue]", 0],
    [2, "幻の料理 2", "[dialogue]", 0],
    [3, "幻の料理 3", "[dialogue]", 0],
    [4, "幻の料理 4", "[dialogue]", 0],
    [5, "幻の料理 5", "[dialogue]", 0],
    [6, "幻の料理 6", "[dialogue]", 0],
    [7, "幻の料理 7", "[dialogue]", 0],
    [8, "幻の料理 8", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/8230fa5e-0222-468e-aa1a-3c71349a2951", "https://vgmdb.net/album/93557"]

[8776c92151f97b065de0889ee636cf90]
catalognumber = "EYCA-12943/B"
date = "2020-05-20"
album = "Run Girls, World! / Run Girls, Run! [CD+Blu-ray] Disc 1 (CD) [EYCA-12943]"
tracks = [
    [1, "カケル×カケル", "Run Girls, Run!", 0],
    [2, "スライドライド", "Run Girls, Run!", 1],
    [3, "りんごの木", "林鼓子", 0],
    [4, "キラッとスタート", "Run Girls, Run!", 1],
    [5, "Go! Up! スターダム!", "Run Girls, Run!", 0],
    [6, "Break the Blue!!", "Run Girls, Run!", 0],
    [7, "Darling Darling", "森嶋優花", 0],
    [8, "never-ending!!", "Run Girls, Run!", 0],
    [9, "ダイヤモンドスマイル", "Run Girls, Run!", 0],
    [10, "水着とスイカ", "Run Girls, Run!", 0],
    [11, "逆さまのガウディ", "厚木那奈美", 0],
    [12, "Share the light", "Run Girls, Run!", 0],
    [13, "イルミナージュ・ランド", "Run Girls, Run!", 0],
    [14, "ランガリング・シンガソング", "Run Girls, Run!", 0],
]
links = ["https://beta.musicbrainz.org/release/0972b816-a8ea-4c1a-9bc2-7c667999913e", "https://vgmdb.net/album/96893"]

[cf4e479483069c5882b31ef756fb3675]
catalognumber = "EYCA-12943/B"
date = "2020-05-20"
album = "Run Girls, World! / Run Girls, Run! [CD+Blu-ray] Disc 2 (Blu-ray) [EYCA-12943B]"
tracks = [
    [1, "ランガリング・シンガソング Music Video", "Run Girls, Run!", 0],
    [2, "スライドライド Music Video", "Run Girls, Run!", 1],
    [3, "キラッとスタート Music Video", "Run Girls, Run!", 1],
    [4, "Go! Up! スターダム! Music Video", "Run Girls, Run!", 0],
    [5, "Break the Blue!! Music Video", "Run Girls, Run!", 0],
    [6, "ダイヤモンドスマイル Music Video", "Run Girls, Run!", 0],
    [7, "Share the light Music Video", "Run Girls, Run!", 0],
]
links = ["https://beta.musicbrainz.org/release/0972b816-a8ea-4c1a-9bc2-7c667999913e", "https://vgmdb.net/album/96893"]

[2b9fac7da7d26cf78138659e9ce3c8b0]
catalognumber = "EYCA-12944"
date = "2020-05-20"
album = "Run Girls, World! / Run Girls, Run!"
tracks = [
    [1, "カケル×カケル", "Run Girls, Run!", 0],
    [2, "スライドライド", "Run Girls, Run!", 1],
    [3, "りんごの木", "林鼓子", 0],
    [4, "キラッとスタート", "Run Girls, Run!", 1],
    [5, "Go! Up! スターダム!", "Run Girls, Run!", 0],
    [6, "Break the Blue!!", "Run Girls, Run!", 0],
    [7, "Darling Darling", "森嶋優花", 0],
    [8, "never-ending!!", "Run Girls, Run!", 0],
    [9, "ダイヤモンドスマイル", "Run Girls, Run!", 0],
    [10, "水着とスイカ", "Run Girls, Run!", 0],
    [11, "逆さまのガウディ", "厚木那奈美", 0],
    [12, "Share the light", "Run Girls, Run!", 0],
    [13, "イルミナージュ・ランド", "Run Girls, Run!", 0],
    [14, "ランガリング・シンガソング", "Run Girls, Run!", 0],
]
links = ["https://beta.musicbrainz.org/release/8f45cafb-4c7e-44ee-9315-2e46dc6ec769", "https://vgmdb.net/album/96894"]

[d413027f92ef888f5454b7f0c38da4e2]
catalognumber = "N/A"
date = "2022-02-10"
album = "デスマーチからはじまる異世界狂想曲 ドラマCD「妖精蜂の巣箱」"
tracks = [
    [1, "妖精蜂の巣箱 1", "[dialogue]", 0],
    [2, "妖精蜂の巣箱 2", "[dialogue]", 0],
    [3, "妖精蜂の巣箱 3", "[dialogue]", 0],
    [4, "妖精蜂の巣箱 4", "[dialogue]", 0],
    [5, "妖精蜂の巣箱 5", "[dialogue]", 0],
    [6, "妖精蜂の巣箱 6", "[dialogue]", 0],
    [7, "妖精蜂の巣箱 7", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/6380cb3c-c803-4b01-a7b8-ffd1034150b2", "https://vgmdb.net/album/117447"]
