[a08fd1a3434d90a12e96b7e4393117ad]
catalognumber = "POCE-1432"
date = "2016-05-04"
album = "青春は食べ物です / petit milady"
tracks = [
    [1, "青春は食べ物です", "petit milady", 2],
    [2, "Unknown Love Bakery", "petit milady", 1],
    [3, "青春は食べ物です (Instrumental)", "petit milady", 1],
    [4, "Unknown Love Bakery (Instrumental)", "petit milady", 1],
]
links = ["https://beta.musicbrainz.org/release/3c693779-a4a1-4ed1-9aa7-fbb5df459bf0", "https://vgmdb.net/album/57772"]

[f5f0752acdb665b9b1d0a833b0cdd2d3]
catalognumber = "POCE-9416"
date = "2016-05-04"
album = "青春は食べ物です / petit milady Disc 1 (CD) [POCX-9417]"
tracks = [
    [1, "青春は食べ物です", "petit milady", 1],
    [2, "Unknown Love Bakery", "petit milady", 1],
    [3, "青春は食べ物です (Instrumental)", "petit milady", 1],
    [4, "Unknown Love Bakery (Instrumental)", "petit milady", 1],
]
links = ["https://beta.musicbrainz.org/release/e8c7cd8c-ba8b-4a10-a30d-4065c6735829", "https://vgmdb.net/album/57773"]

[13d92823ccdeb18e34b551b06c7ea407]
catalognumber = "POCE-9416"
date = "2016-05-04"
album = "青春は食べ物です / petit milady Disc 2 (DVD) [POBX-9416]"
tracks = [
    [1, "青春は食べ物です [Music Video]", "petit milady", 1],
]
links = ["https://beta.musicbrainz.org/release/e8c7cd8c-ba8b-4a10-a30d-4065c6735829", "https://vgmdb.net/album/57773"]

[75532566abf944dff6bab65d34149eff]
catalognumber = "JDE-003"
date = "2016-11-03"
album = "パンでPeace! オリジナルサウンドトラック〜パンでMusic!〜"
tracks = [
    [1, "パンでPeace!", "", 1],
    [2, "お母さんのサンドイッチ", "", 1],
    [3, "だ、だれ?", "", 1],
    [4, "フランスパンの兵隊", "", 1],
    [5, "パン友ができました", "", 1],
    [6, "これは武器", "", 1],
    [7, "Milk mustache", "", 1],
    [8, "淡い塩味", "", 1],
    [9, "ふわふゆベーカリー", "", 1],
    [10, "みんなでパン作り", "", 1],
    [11, "横たわるチョココロネ", "", 1],
    [12, "恐怖の体重計", "", 1],
    [13, "廻るバスケット", "", 1],
    [14, "喫茶猫のしっぽ", "", 1],
    [15, "魅惑のクロワッサン", "", 1],
    [16, "Maternal love", "", 1],
    [17, "思い出のパン", "", 1],
    [18, "お泊まり会", "", 1],
]
links = ["https://vgmdb.net/album/100980"]
