[9a3bdd26b44bcbd08e26c28e24f74859]
catalognumber = "EBCD-0006"
date = "2012-02-02"
album = "フォトカノ ドラマＣＤ プロローグメッセージ with スペシャルドラマ「～幼なじみが妹で、妹が幼なじみで～」"
tracks = []
links = ["https://vgmdb.net/album/30848"]

[de002859c0393d3ed86074d555ef95de]
catalognumber = "TRCD-10108~9"
date = "2012-02-10"
album = "フォトカノ♥ ～オリジナルサウンドトラック～ Disc 1 [TRCD-10108]"
tracks = [
    [1, "タイトル", "", 0],
    [2, "自室にて", "", 0],
    [3, "学校生活", "", 0],
    [4, "新見遙佳のテーマ", "", 0],
    [5, "室戸亜岐のテーマ", "", 0],
    [6, "早倉舞依のテーマ", "", 0],
    [7, "実原氷里のテーマ", "", 0],
    [8, "間咲ののかのテーマ", "", 0],
    [9, "柚ノ木梨奈のテーマ", "", 0],
    [10, "深角友恵のテーマ", "", 0],
    [11, "果音のテーマ", "", 0],
    [12, "大谷桃子のテーマ", "", 0],
    [13, "紅林かつみのテーマ", "", 0],
    [14, "成田瑠宇のテーマ", "", 0],
    [15, "九堂博道のテーマ", "", 0],
    [16, "内田有子のテーマ", "", 0],
    [17, "中川行太と東孝のテーマ", "", 0],
    [18, "喜多川美紗のテーマ", "", 0],
    [19, "暗く、落ち込む気持ち ～寂しい曲～", "", 0],
    [20, "とんだ失敗 ～コミカルな曲～", "", 0],
    [21, "昔の思い出、将来の夢 ～しんみりした曲～", "", 0],
    [22, "穏やかな昼下がり ～のどかな曲～", "", 0],
    [23, "ラブ ラブ トゥルーラブ(梨奈&果音)", "", 0],
    [24, "ラブ ラブ トゥルーラブ(梨奈)", "", 0],
    [25, "おやすみの曲", "", 0],
]
links = ["https://vgmdb.net/album/30847"]

[c2e4bf3c0037092f17bb4d16deb825bb]
catalognumber = "TRCD-10108~9"
date = "2012-02-10"
album = "フォトカノ♥ ～オリジナルサウンドトラック～ Disc 2 [TRCD-10109]"
tracks = [
    [1, "アホ毛あっぴ～のうた", "", 0],
    [2, "ハッピー&ラッキー ～とても楽しい曲～", "", 0],
    [3, "昼下がりの雨 ～しっとりした曲～", "", 0],
    [4, "地獄のゾンビハウス ～おどろおどろしい曲～", "", 0],
    [5, "バイオリズム下校マッチング会話のテーマ", "", 0],
    [6, "早倉舞依 新体操演技伴奏曲", "", 0],
    [7, "想い慕って ～キスシーンの曲～", "", 0],
    [8, "フォトセッション1 ～ハッピー～", "", 0],
    [9, "フォトセッション2 ～ドキドキ～", "", 0],
    [10, "フォトセッション3 ～エロス～", "", 0],
    [11, "うさパワー選択", "", 0],
    [12, "マジカルピュアハート オープン!", "", 0],
    [13, "ムーンライト スターライト PianoVer.", "", 0],
    [14, "ムーンライト スターライト AcousticVer.(梨奈&果音)", "", 0],
    [15, "ムーンライト スターライト AcousticVer.(梨奈)", "", 0],
    [16, "学校生活 ～最後の一週間～", "", 0],
    [17, "告白", "", 0],
    [18, "エピローグ", "", 0],
]
links = ["https://vgmdb.net/album/30847"]

[2b298a474f1bfc08b3925db225027ab1]
catalognumber = "TRCD-10115"
date = "2012-04-25"
album = "フォトカノ キャラクターソング vol.1 新見遙佳"
tracks = [
    [1, "ハートのエース", "", 0],
    [2, "お風呂モノローグ -新見遙佳-", "", 0],
    [3, "ムーンライト スターライト(Haruka ver.)", "", 0],
    [4, "フォトグラフメモリー(Haruka ver.)", "", 0],
    [5, "ハートのエース(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/31585"]

[547911119fbf86df6186f487d5f53cc0]
catalognumber = "TRCD-10116"
date = "2012-04-25"
album = "フォトカノ キャラクターソング vol.2 室戸亜岐"
tracks = [
    [1, "Blue Heaven", "", 0],
    [2, "お風呂モノローグ -室戸亜岐-", "", 0],
    [3, "ムーンライト スターライト(Aki ver.)", "", 0],
    [4, "フォトグラフメモリー(Aki ver.)", "", 0],
    [5, "Blue Heaven(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/31586"]

[e7a29e0f4de222d07f3a30c61c97b4ce]
catalognumber = "TRCD-10117"
date = "2012-04-25"
album = "フォトカノ キャラクターソング vol.3 間咲ののか"
tracks = [
    [1, "はっぴ～モーニング！", "", 0],
    [2, "お風呂モノローグ -間咲ののか-", "", 0],
    [3, "ムーンライト スターライト(Nonoka ver.)", "", 0],
    [4, "フォトグラフメモリー(Nonoka ver.)", "", 0],
    [5, "はっぴ～モーニング！(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/31587"]

[66bbada30fe9aad39816de677741481c]
catalognumber = "TRCD-10119"
date = "2012-05-30"
album = "フォトカノ キャラクターソング vol.5 果音"
tracks = [
    [1, "放課後☆トゥインクルスター", "", 0],
    [2, "お風呂モノローグ -果音-", "", 0],
    [3, "ムーンライト スターライト(Kanon ver.)", "", 0],
    [4, "フォトグラフメモリー(Kanon ver.)", "", 0],
    [5, "放課後☆トゥインクルスター(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/32301"]

[58742387e57e5be93af4385e79f8c7fc]
catalognumber = "TRCD-10118"
date = "2012-05-30"
album = "フォトカノ キャラクターソング vol.4 早倉舞衣"
tracks = [
    [1, "DOKI♥DOKI♥ラブリースイーツ", "", 0],
    [2, "お風呂モノローグ -早倉舞衣-", "", 0],
    [3, "ムーンライト スターライト(Mai ver.)", "", 0],
    [4, "フォトグラフメモリー(Mai ver.)", "", 0],
    [5, "DOKI♥DOKI♥ラブリースイーツ(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/32300"]

[c11632ff05d9080fbd228a3971562b95]
catalognumber = "TRCD-10120"
date = "2012-05-30"
album = "フォトカノ キャラクターソング vol.6 深角友恵"
tracks = [
    [1, "Rain Song", "", 0],
    [2, "お風呂モノローグ -深角友恵-", "", 0],
    [3, "ムーンライト スターライト(Tomoe ver.)", "", 0],
    [4, "フォトグラフメモリー(Tomoe ver.)", "", 0],
    [5, "Rain Song(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/32302"]

[149b3f21b53129e88f3b08db5a219747]
catalognumber = "TRCD-10122"
date = "2012-06-27"
album = "フォトカノ キャラクターソング vol.8 実原氷里"
tracks = [
    [1, "ひかりの子守歌", "", 0],
    [2, "お風呂モノローグ -実原氷里-", "", 0],
    [3, "ムーンライト スターライト(Hikari ver.)", "", 0],
    [4, "フォトグラフメモリー(Hikari ver.)", "", 0],
    [5, "ひかりの子守歌(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/56869"]

[517717862e0a6c95640e707997dcfca2]
catalognumber = "TRCD-10123"
date = "2012-06-27"
album = "フォトカノ キャラクターソング vol.9 大谷桃子"
tracks = [
    [1, "初恋 恋愛 センセーション", "", 0],
    [2, "お風呂モノローグ -大谷桃子-", "", 0],
    [3, "ムーンライト スターライト(Momoko ver.)", "", 0],
    [4, "フォトグラフメモリー(Momoko ver.)", "", 0],
    [5, "初恋 恋愛 センセーション(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/56870"]

[81ac321fd07b1e3364a7b68835e2e372]
catalognumber = "TRCD-10121"
date = "2012-06-27"
album = "フォトカノ キャラクターソング vol.7 柚ノ木梨奈"
tracks = [
    [1, "恋するFeeling ～Can't Stop Lovin' You～", "", 0],
    [2, "お風呂モノローグ -柚ノ木梨奈-", "", 0],
    [3, "ムーンライト スターライト(Rina ver.)", "", 0],
    [4, "フォトグラフメモリー(Rina ver.)", "", 0],
    [5, "恋するFeeling ～Can't Stop Lovin' You～(off vocal)", "", 0],
    [6, "ムーンライト スターライト(off vocal)", "", 0],
    [7, "フォトグラフメモリー(off vocal)", "", 0],
]
links = ["https://vgmdb.net/album/56867"]

[3deb1178d036f72ef7c42cc336273e50]
catalognumber = "PCCG-70175"
date = "2013-04-24"
album = "恋するレンズ / hayatokaori"
tracks = [
    [1, "恋するレンズ", "hayatokaori", 0],
    [2, "Dear my shooting star", "hayatokaori", 0],
    [3, "恋するレンズ (Instrumental)", "hayatokaori", 0],
    [4, "Dear my shooting star (Instrumental)", "hayatokaori", 0],
]
links = ["https://beta.musicbrainz.org/release/2e6df6a2-939f-42c6-b319-4a58f459d60c", "https://vgmdb.net/album/38151"]

[41ab9738e891984bec4f6c101132b27f]
catalognumber = "N/A"
date = "2013-04-24"
album = "にいやんなりきりCD / 果音(CV.伊瀬茉莉也)"
tracks = []
links = ["https://vgmdb.net/album/56761"]

[35bda0f500e2bc99c8f4d32d8f24bb39]
catalognumber = "PCCG-70176"
date = "2013-04-24"
album = "スマイルF / うたカノ♪"
tracks = [
    [1, "スマイルF", "うたカノ♪", 0],
    [2, "PURIPURI! プリティラビィ", "伊瀬茉莉也", 0],
    [3, "スマイルF (Instrumental)", "うたカノ♪", 0],
    [4, "PURIPURI! プリティラビィ (Instrumental)", "伊瀬茉莉也", 0],
]
links = ["https://beta.musicbrainz.org/release/2738234d-974d-4548-bb34-9c0a6715b840", "https://vgmdb.net/album/38152"]

[d27d5a02e41dad4b8b376f038c0be1ef]
catalognumber = "PCXE-50271-2"
date = "2013-06-28"
album = "スマイルF \"うたカノ♪二年生ヴァージョン\""
tracks = [
    [1, "スマイルF \"うたカノ♪二年生ヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56832"]

[b36fef922de8c5fb03fbc493e16162ec]
catalognumber = "PCCG-01349"
date = "2013-06-28"
album = "TVアニメ「フォトカノ」オリジナルサウンドトラック"
tracks = [
    [1, "メインテーマ", "窪田ミナ", 0],
    [2, "リボン", "窪田ミナ", 0],
    [3, "ライズボール", "窪田ミナ", 0],
    [4, "プリズム", "窪田ミナ", 0],
    [5, "恋のはじまり", "窪田ミナ", 0],
    [6, "写真部のテーマ", "窪田ミナ", 0],
    [7, "ガールズ", "窪田ミナ", 0],
    [8, "風のダンス", "窪田ミナ", 0],
    [9, "約束", "窪田ミナ", 0],
    [10, "スイートピー", "窪田ミナ", 0],
    [11, "極秘会議", "窪田ミナ", 0],
    [12, "秋桜", "窪田ミナ", 0],
    [13, "タンポポとこんぺいとう", "窪田ミナ", 0],
    [14, "メッセージ", "窪田ミナ", 0],
    [15, "あかね色", "窪田ミナ", 0],
    [16, "ミッション", "窪田ミナ", 0],
    [17, "星の見える丘", "窪田ミナ", 0],
    [18, "想いの向こう", "窪田ミナ", 0],
    [19, "ピクニック", "窪田ミナ", 0],
    [20, "ハートビート", "窪田ミナ", 0],
    [21, "ブルー", "窪田ミナ", 0],
    [22, "ファニー・スパイ", "窪田ミナ", 0],
    [23, "嘘と鏡", "窪田ミナ", 0],
    [24, "17ステップス", "窪田ミナ", 0],
    [25, "もの想う午後", "窪田ミナ", 0],
    [26, "フォトセッション", "窪田ミナ", 0],
    [27, "君を探して", "窪田ミナ", 0],
    [28, "フォトグラフ", "窪田ミナ", 0],
]
links = ["https://beta.musicbrainz.org/release/0ef6c5fd-caf3-47e7-8780-6a684c8a2097", "https://vgmdb.net/album/38627"]

[c199a694dac97fbdd49af72f5011894a]
catalognumber = "PCCG-01350"
date = "2013-07-03"
album = "TVアニメ「フォトカノ」キャラクターソングアルバム THROUGH THE CAMERA"
tracks = [
    [1, "ラブジェニック", "新見遙佳(CV:伊藤かな恵)", 0],
    [2, "Tinkle My Bell", "前田果音(CV:伊瀬茉莉也)", 0],
    [3, "未来の花嫁", "柚ノ木梨奈(CV:大亀あすか)", 0],
    [4, "みずいろインサイド", "室戸亜岐(CV:中原麻衣)", 0],
    [5, "空想リプル", "早倉舞衣(CV:金元寿子)", 0],
    [6, "truth", "実原氷里(CV:水橋かおり)", 0],
    [7, "お願いライズボール", "間咲ののか(CV:斎藤千和)", 0],
    [8, "Teardrop Memories", "深角友恵(CV:沢城みゆき)", 0],
    [9, "恋のステルス暗撮者", "内田有子(CV:高垣彩陽)", 0],
]
links = ["https://beta.musicbrainz.org/release/85388b42-9af7-439d-bb73-d0b6340766bd", "https://vgmdb.net/album/38632"]

[0a77f3d729e606d20a97fee2bfd68920]
catalognumber = "PCXE-50272-2"
date = "2013-07-26"
album = "スマイルF \"うたカノ♪一年生&三年生ヴァージョン\""
tracks = [
    [1, "スマイルF \"うたカノ♪一年生＆三年生ヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56845"]

[9ec0db7f9e7dabe98499950de4bd9654]
catalognumber = "BEZP-556"
date = "2013-08-10"
album = "写真部のシャッターチャンス"
tracks = []
links = ["https://vgmdb.net/album/56791"]

[038daec67f2b4d243b9c20f86a939cd0]
catalognumber = "DSP-01996"
date = "2013-08-30"
album = "写真部のシャッターチャンス エピソード1"
tracks = []
links = ["https://vgmdb.net/album/56814"]

[071a8c8cc26ba20a090ce7fd0217ca8d]
catalognumber = "PCXE-50273-2"
date = "2013-08-30"
album = "スマイルF \"新見遙佳ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"新見遙佳ソロヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56846"]

[9ec4997028135006280e85b60a9e7067]
catalognumber = "PCXE-50274-2"
date = "2013-09-18"
album = "スマイルF \"実原氷里ソロヴァージョン+室戸亜岐ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"実原氷里ソロヴァージョン\"", "", 0],
    [2, "スマイルF \"室戸亜岐ソロヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56848"]

[41192d4a24dcb7e41708a9b67141ae9f]
catalognumber = "PCXE-50275-2"
date = "2013-10-25"
album = "スマイルF \"間咲ののかソロヴァージョン+早倉舞衣ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"間咲ののかソロヴァージョン\"", "", 0],
    [2, "スマイルF \"早倉舞衣ソロヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56897"]

[d4a2dcb3165b58d027df6f7e4989a322]
catalognumber = "PCXE-50276-2"
date = "2013-11-29"
album = "スマイルF \"柚ノ木梨奈ソロヴァージョン+深角友恵ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"柚ノ木梨奈ソロヴァージョン\"", "", 0],
    [2, "スマイルF \"深角友恵ソロヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56916"]

[9e5d95430610cee034cf44420abbf2b1]
catalognumber = "PCXE-50277-2"
date = "2013-12-27"
album = "スマイルF \"前田果音ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"前田果音ソロヴァージョン\"", "", 0],
]
links = ["https://vgmdb.net/album/56917"]

[b1437a90762e480cdcc893ed4ccd0385]
catalognumber = "DSP-01998"
date = "2013-12-27"
album = "写真部のシャッターチャンス エピソード2"
tracks = []
links = ["https://vgmdb.net/album/56815"]

[09777bd6f0084678bc72652ed249207f]
catalognumber = "GMAS-6622"
date = "2016-06-22"
album = "GAMEのアニソン!!The BEST TUNES-1"
tracks = [
    [1, "サクラサクミライコイユメ", "", 0],
    [2, "海色", "", 0],
    [3, "純情スペクトラ", "", 0],
    [4, "Breakin’through", "", 0],
    [5, "SWORD SUMMIT", "", 0],
    [6, "EXiSTENCE", "", 0],
    [7, "絶望性:ヒーロー治療薬", "", 0],
    [8, "Dimension tripper!!!!", "", 0],
    [9, "ideal white", "", 0],
    [10, "Hacking to the Gate", "", 0],
    [11, "虹色センチメンタル", "", 0],
    [12, "プラスチックスマイル", "", 0],
    [13, "恋するレンズ", "", 0],
    [14, "Take your way", "", 0],
    [15, "Check my soul", "", 0],
    [16, "比翼の羽根", "", 0],
    [17, "楽園の翼", "", 0],
    [18, "Star!!", "", 0],
    [19, "明日へのキズナ", "", 0],
    [20, "Break your world", "", 0],
    [21, "Oath sign", "", 0],
]
links = ["https://vgmdb.net/album/150656"]
