[9a3bdd26b44bcbd08e26c28e24f74859]
catalognumber = "EBCD-0006"
date = "2012-02-02"
album = "フォトカノ ドラマＣＤ プロローグメッセージ with スペシャルドラマ「～幼なじみが妹で、妹が幼なじみで～」"
tracks = []
links = ["https://vgmdb.net/album/30848"]

[34e398313694d36376a2fa80ec9cee54]
catalognumber = "TRCD-10108~9"
date = "2012-02-10"
album = "フォトカノ♥ ～オリジナルサウンドトラック～ Disc 1 [TRCD-10108]"
tracks = [
    [1, "タイトル", "", 1],
    [2, "自室にて", "", 1],
    [3, "学校生活", "", 1],
    [4, "新見遙佳のテーマ", "", 1],
    [5, "室戸亜岐のテーマ", "", 1],
    [6, "早倉舞依のテーマ", "", 1],
    [7, "実原氷里のテーマ", "", 1],
    [8, "間咲ののかのテーマ", "", 1],
    [9, "柚ノ木梨奈のテーマ", "", 1],
    [10, "深角友恵のテーマ", "", 1],
    [11, "果音のテーマ", "", 1],
    [12, "大谷桃子のテーマ", "", 1],
    [13, "紅林かつみのテーマ", "", 1],
    [14, "成田瑠宇のテーマ", "", 1],
    [15, "九堂博道のテーマ", "", 1],
    [16, "内田有子のテーマ", "", 1],
    [17, "中川行太と東孝のテーマ", "", 1],
    [18, "喜多川美紗のテーマ", "", 1],
    [19, "暗く、落ち込む気持ち ～寂しい曲～", "", 1],
    [20, "とんだ失敗 ～コミカルな曲～", "", 1],
    [21, "昔の思い出、将来の夢 ～しんみりした曲～", "", 1],
    [22, "穏やかな昼下がり ～のどかな曲～", "", 1],
    [23, "ラブ ラブ トゥルーラブ(梨奈&果音)", "", 1],
    [24, "ラブ ラブ トゥルーラブ(梨奈)", "", 1],
    [25, "おやすみの曲", "", 0],
]
links = ["https://vgmdb.net/album/30847"]

[dbd56faa865a400c30539c008e441692]
catalognumber = "TRCD-10108~9"
date = "2012-02-10"
album = "フォトカノ♥ ～オリジナルサウンドトラック～ Disc 2 [TRCD-10109]"
tracks = [
    [1, "アホ毛あっぴ～のうた", "斎藤千和", 1],
    [2, "ハッピー&ラッキー ～とても楽しい曲～", "", 1],
    [3, "昼下がりの雨 ～しっとりした曲～", "", 1],
    [4, "地獄のゾンビハウス ～おどろおどろしい曲～", "", 1],
    [5, "バイオリズム下校マッチング会話のテーマ", "", 1],
    [6, "早倉舞依 新体操演技伴奏曲", "", 1],
    [7, "想い慕って ～キスシーンの曲～", "", 1],
    [8, "フォトセッション1 ～ハッピー～", "", 1],
    [9, "フォトセッション2 ～ドキドキ～", "", 1],
    [10, "フォトセッション3 ～エロス～", "", 1],
    [11, "うさパワー選択", "", 1],
    [12, "マジカルピュアハート オープン!", "", 1],
    [13, "ムーンライト スターライト PianoVer.", "", 1],
    [14, "ムーンライト スターライト AcousticVer.(梨奈&果音)", "", 1],
    [15, "ムーンライト スターライト AcousticVer.(梨奈)", "", 1],
    [16, "学校生活 ～最後の一週間～", "", 1],
    [17, "告白", "", 1],
    [18, "エピローグ", "", 1],
]
links = ["https://vgmdb.net/album/30847"]

[6292e7a4e54455bc6bac5367034bdc5d]
catalognumber = "TRCD-10115"
date = "2012-04-25"
album = "フォトカノ キャラクターソング vol.1 新見遙佳"
tracks = [
    [1, "ハートのエース", "伊藤かな恵", 1],
    [2, "お風呂モノローグ -新見遙佳-", "伊藤かな恵", 1],
    [3, "ムーンライト スターライト(Haruka ver.)", "伊藤かな恵", 1],
    [4, "フォトグラフメモリー(Haruka ver.)", "伊藤かな恵", 1],
    [5, "ハートのエース(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/31585"]

[85eb79463abfa5090cdb24bab3d2cc77]
catalognumber = "TRCD-10116"
date = "2012-04-25"
album = "フォトカノ キャラクターソング vol.2 室戸亜岐"
tracks = [
    [1, "Blue Heaven", "中原麻衣", 1],
    [2, "お風呂モノローグ -室戸亜岐-", "中原麻衣", 1],
    [3, "ムーンライト スターライト(Aki ver.)", "中原麻衣", 1],
    [4, "フォトグラフメモリー(Aki ver.)", "中原麻衣", 1],
    [5, "Blue Heaven(off vocal)", "中原麻衣", 1],
    [6, "ムーンライト スターライト(off vocal)", "中原麻衣", 1],
    [7, "フォトグラフメモリー(off vocal)", "中原麻衣", 1],
]
links = ["https://vgmdb.net/album/31586"]

[e0c21d2b3ffbd0851e2d4df2d7e1e502]
catalognumber = "TRCD-10117"
date = "2012-04-25"
album = "フォトカノ キャラクターソング vol.3 間咲ののか"
tracks = [
    [1, "はっぴ～モーニング！", "斎藤千和", 1],
    [2, "お風呂モノローグ -間咲ののか-", "斎藤千和", 1],
    [3, "ムーンライト スターライト(Nonoka ver.)", "斎藤千和", 1],
    [4, "フォトグラフメモリー(Nonoka ver.)", "斎藤千和", 1],
    [5, "はっぴ～モーニング！(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/31587"]

[d4727f8b8f021f776939ac1a68802ab2]
catalognumber = "TRCD-10119"
date = "2012-05-30"
album = "フォトカノ キャラクターソング vol.5 果音"
tracks = [
    [1, "放課後☆トゥインクルスター", "伊瀬茉莉也", 1],
    [2, "お風呂モノローグ -果音-", "伊瀬茉莉也", 1],
    [3, "ムーンライト スターライト(Kanon ver.)", "伊瀬茉莉也", 1],
    [4, "フォトグラフメモリー(Kanon ver.)", "伊瀬茉莉也", 1],
    [5, "放課後☆トゥインクルスター(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/32301"]

[e56a6e8ec0bc76c635173df8e2768d6b]
catalognumber = "TRCD-10118"
date = "2012-05-30"
album = "フォトカノ キャラクターソング vol.4 早倉舞衣"
tracks = [
    [1, "DOKI♥DOKI♥ラブリースイーツ", "金元寿子", 2],
    [2, "お風呂モノローグ -早倉舞衣-", "金元寿子", 1],
    [3, "ムーンライト スターライト(Mai ver.)", "金元寿子", 1],
    [4, "フォトグラフメモリー(Mai ver.)", "金元寿子", 1],
    [5, "DOKI♥DOKI♥ラブリースイーツ(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/32300"]

[188aeaf5b914485289ca0e9580d16dc2]
catalognumber = "TRCD-10120"
date = "2012-05-30"
album = "フォトカノ キャラクターソング vol.6 深角友恵"
tracks = [
    [1, "Rain Song", "沢城みゆき", 2],
    [2, "お風呂モノローグ -深角友恵-", "沢城みゆき", 1],
    [3, "ムーンライト スターライト(Tomoe ver.)", "沢城みゆき", 1],
    [4, "フォトグラフメモリー(Tomoe ver.)", "沢城みゆき", 1],
    [5, "Rain Song(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/32302"]

[c59f1314abf665afff8d7c22a883d565]
catalognumber = "TRCD-10122"
date = "2012-06-27"
album = "フォトカノ キャラクターソング vol.8 実原氷里"
tracks = [
    [1, "ひかりの子守歌", "水橋かおり", 1],
    [2, "お風呂モノローグ -実原氷里-", "水橋かおり", 1],
    [3, "ムーンライト スターライト(Hikari ver.)", "水橋かおり", 1],
    [4, "フォトグラフメモリー(Hikari ver.)", "水橋かおり", 1],
    [5, "ひかりの子守歌(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/56869"]

[7039dbc3cf2779793478194b336962f7]
catalognumber = "TRCD-10123"
date = "2012-06-27"
album = "フォトカノ キャラクターソング vol.9 大谷桃子"
tracks = [
    [1, "初恋 恋愛 センセーション", "远藤綾", 1],
    [2, "お風呂モノローグ -大谷桃子-", "远藤綾", 1],
    [3, "ムーンライト スターライト(Momoko ver.)", "远藤綾", 1],
    [4, "フォトグラフメモリー(Momoko ver.)", "远藤綾", 1],
    [5, "初恋 恋愛 センセーション(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/56870"]

[d83e889d6610ba26ebcb8b4de7d2742d]
catalognumber = "TRCD-10121"
date = "2012-06-27"
album = "フォトカノ キャラクターソング vol.7 柚ノ木梨奈"
tracks = [
    [1, "恋するFeeling ～Can't Stop Lovin' You～", "大亀あすか", 1],
    [2, "お風呂モノローグ -柚ノ木梨奈-", "大亀あすか", 1],
    [3, "ムーンライト スターライト(Rina ver.)", "大亀あすか", 1],
    [4, "フォトグラフメモリー(Rina ver.)", "大亀あすか", 1],
    [5, "恋するFeeling ～Can't Stop Lovin' You～(off vocal)", "", 1],
    [6, "ムーンライト スターライト(off vocal)", "", 1],
    [7, "フォトグラフメモリー(off vocal)", "", 1],
]
links = ["https://vgmdb.net/album/56867"]

[57e0527a834fd8f40cc051179d8275c2]
catalognumber = "PCCG-70175"
date = "2013-04-24"
album = "恋するレンズ / hayatokaori"
tracks = [
    [1, "恋するレンズ", "hayatokaori", 1],
    [2, "Dear my shooting star", "hayatokaori", 1],
    [3, "恋するレンズ (Instrumental)", "hayatokaori", 1],
    [4, "Dear my shooting star (Instrumental)", "hayatokaori", 1],
]
links = ["https://beta.musicbrainz.org/release/2e6df6a2-939f-42c6-b319-4a58f459d60c", "https://vgmdb.net/album/38151"]

[41ab9738e891984bec4f6c101132b27f]
catalognumber = "N/A"
date = "2013-04-24"
album = "にいやんなりきりCD / 果音(CV.伊瀬茉莉也)"
tracks = []
links = ["https://vgmdb.net/album/56761"]

[753efe90009880e0dcf6a05cb9e2c5ef]
catalognumber = "PCCG-70176"
date = "2013-04-24"
album = "スマイルF / うたカノ♪"
tracks = [
    [1, "スマイルF", "うたカノ♪", 2],
    [2, "PURIPURI! プリティラビィ", "伊瀬茉莉也", 1],
    [3, "スマイルF (Instrumental)", "うたカノ♪", 1],
    [4, "PURIPURI! プリティラビィ (Instrumental)", "伊瀬茉莉也", 1],
]
links = ["https://beta.musicbrainz.org/release/2738234d-974d-4548-bb34-9c0a6715b840", "https://vgmdb.net/album/38152"]

[cec588dfd382885c43606ad645feacc6]
catalognumber = "PCXE-50271-2"
date = "2013-06-28"
album = "スマイルF \"うたカノ♪二年生ヴァージョン\""
tracks = [
    [1, "スマイルF \"うたカノ♪二年生ヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56832"]

[abbf3b70fc85aef05305b2f53f17fd28]
catalognumber = "PCCG-01349"
date = "2013-06-28"
album = "TVアニメ「フォトカノ」オリジナルサウンドトラック"
tracks = [
    [1, "メインテーマ", "窪田ミナ", 1],
    [2, "リボン", "窪田ミナ", 1],
    [3, "ライズボール", "窪田ミナ", 1],
    [4, "プリズム", "窪田ミナ", 1],
    [5, "恋のはじまり", "窪田ミナ", 1],
    [6, "写真部のテーマ", "窪田ミナ", 1],
    [7, "ガールズ", "窪田ミナ", 1],
    [8, "風のダンス", "窪田ミナ", 1],
    [9, "約束", "窪田ミナ", 1],
    [10, "スイートピー", "窪田ミナ", 1],
    [11, "極秘会議", "窪田ミナ", 1],
    [12, "秋桜", "窪田ミナ", 1],
    [13, "タンポポとこんぺいとう", "窪田ミナ", 1],
    [14, "メッセージ", "窪田ミナ", 1],
    [15, "あかね色", "窪田ミナ", 1],
    [16, "ミッション", "窪田ミナ", 1],
    [17, "星の見える丘", "窪田ミナ", 1],
    [18, "想いの向こう", "窪田ミナ", 1],
    [19, "ピクニック", "窪田ミナ", 1],
    [20, "ハートビート", "窪田ミナ", 1],
    [21, "ブルー", "窪田ミナ", 1],
    [22, "ファニー・スパイ", "窪田ミナ", 1],
    [23, "嘘と鏡", "窪田ミナ", 1],
    [24, "17ステップス", "窪田ミナ", 1],
    [25, "もの想う午後", "窪田ミナ", 1],
    [26, "フォトセッション", "窪田ミナ", 1],
    [27, "君を探して", "窪田ミナ", 1],
    [28, "フォトグラフ", "窪田ミナ", 1],
]
links = ["https://beta.musicbrainz.org/release/0ef6c5fd-caf3-47e7-8780-6a684c8a2097", "https://vgmdb.net/album/38627"]

[ec47a6f5a3687f12f7838f79a1077250]
catalognumber = "PCCG-01350"
date = "2013-07-03"
album = "TVアニメ「フォトカノ」キャラクターソングアルバム THROUGH THE CAMERA"
tracks = [
    [1, "ラブジェニック", "新見遙佳(CV:伊藤かな恵)", 1],
    [2, "Tinkle My Bell", "前田果音(CV:伊瀬茉莉也)", 1],
    [3, "未来の花嫁", "柚ノ木梨奈(CV:大亀あすか)", 1],
    [4, "みずいろインサイド", "室戸亜岐(CV:中原麻衣)", 2],
    [5, "空想リプル", "早倉舞衣(CV:金元寿子)", 1],
    [6, "truth", "実原氷里(CV:水橋かおり)", 1],
    [7, "お願いライズボール", "間咲ののか(CV:斎藤千和)", 1],
    [8, "Teardrop Memories", "深角友恵(CV:沢城みゆき)", 1],
    [9, "恋のステルス暗撮者", "内田有子(CV:高垣彩陽)", 1],
]
links = ["https://beta.musicbrainz.org/release/85388b42-9af7-439d-bb73-d0b6340766bd", "https://vgmdb.net/album/38632"]

[139b3a47949eab63f1bbeb125e4e56c7]
catalognumber = "PCXE-50272-2"
date = "2013-07-26"
album = "スマイルF \"うたカノ♪一年生&三年生ヴァージョン\""
tracks = [
    [1, "スマイルF \"うたカノ♪一年生＆三年生ヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56845"]

[9ec0db7f9e7dabe98499950de4bd9654]
catalognumber = "BEZP-556"
date = "2013-08-10"
album = "写真部のシャッターチャンス"
tracks = []
links = ["https://vgmdb.net/album/56791"]

[038daec67f2b4d243b9c20f86a939cd0]
catalognumber = "DSP-01996"
date = "2013-08-30"
album = "写真部のシャッターチャンス エピソード1"
tracks = []
links = ["https://vgmdb.net/album/56814"]

[f68367ec91b77e85b6e3f561bc892ada]
catalognumber = "PCXE-50273-2"
date = "2013-08-30"
album = "スマイルF \"新見遙佳ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"新見遙佳ソロヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56846"]

[f4734d150b1b923dfb2bc0d84ca47b61]
catalognumber = "PCXE-50274-2"
date = "2013-09-18"
album = "スマイルF \"実原氷里ソロヴァージョン+室戸亜岐ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"実原氷里ソロヴァージョン\"", "", 1],
    [2, "スマイルF \"室戸亜岐ソロヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56848"]

[13dc3ec04e94778f8990309e4dfe327c]
catalognumber = "PCXE-50275-2"
date = "2013-10-25"
album = "スマイルF \"間咲ののかソロヴァージョン+早倉舞衣ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"間咲ののかソロヴァージョン\"", "", 1],
    [2, "スマイルF \"早倉舞衣ソロヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56897"]

[a2aa45e2821dc117c776414396c95146]
catalognumber = "PCXE-50276-2"
date = "2013-11-29"
album = "スマイルF \"柚ノ木梨奈ソロヴァージョン+深角友恵ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"柚ノ木梨奈ソロヴァージョン\"", "", 1],
    [2, "スマイルF \"深角友恵ソロヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56916"]

[cc59d6b5f1bfb279003f87d3fb118d42]
catalognumber = "PCXE-50277-2"
date = "2013-12-27"
album = "スマイルF \"前田果音ソロヴァージョン\""
tracks = [
    [1, "スマイルF \"前田果音ソロヴァージョン\"", "", 1],
]
links = ["https://vgmdb.net/album/56917"]

[b1437a90762e480cdcc893ed4ccd0385]
catalognumber = "DSP-01998"
date = "2013-12-27"
album = "写真部のシャッターチャンス エピソード2"
tracks = []
links = ["https://vgmdb.net/album/56815"]

[ab8486d1f210e6a8035811a2bf915767]
catalognumber = "GMAS-6622"
date = "2016-06-22"
album = "GAMEのアニソン!!The BEST TUNES-1"
tracks = [
    [1, "サクラサクミライコイユメ", "", 0],
    [2, "海色", "", 0],
    [3, "純情スペクトラ", "", 0],
    [4, "Breakin’through", "", 0],
    [5, "SWORD SUMMIT", "", 0],
    [6, "EXiSTENCE", "", 0],
    [7, "絶望性:ヒーロー治療薬", "", 0],
    [8, "Dimension tripper!!!!", "", 0],
    [9, "ideal white", "", 0],
    [10, "Hacking to the Gate", "", 0],
    [11, "虹色センチメンタル", "", 0],
    [12, "プラスチックスマイル", "", 0],
    [13, "恋するレンズ", "", 1],
    [14, "Take your way", "", 0],
    [15, "Check my soul", "", 0],
    [16, "比翼の羽根", "", 0],
    [17, "楽園の翼", "", 0],
    [18, "Star!!", "", 0],
    [19, "明日へのキズナ", "", 0],
    [20, "Break your world", "", 0],
    [21, "Oath sign", "", 0],
]
links = ["https://vgmdb.net/album/150656"]
