[01aa69fa331cf3fc1a544ac1ca7129c0]
catalognumber = "SVWC-70321~2"
date = "2017-11-22"
album = "ぼなぺてぃーと♡S/デタラメなマイナスとプラスにおけるブレンド考 / ブレンド・A Disc 1 (CD) [SVWC-70321]"
tracks = [
    [1, "ぼなぺてぃーと♡S", "ブレンド・A", 1],
    [2, "デタラメなマイナスとプラスにおけるブレンド考", "ブレンド・A", 2],
    [3, "ぼなぺてぃーと♡S <Instrumental>", "ブレンド・A", 1],
    [4, "デタラメなマイナスとプラスにおけるブレンド考 <Instrumental>", "ブレンド・A", 1],
]
links = ["https://beta.musicbrainz.org/release/5a899dfd-9629-4d87-84ab-fcb5ec7f1529", "https://vgmdb.net/album/71864"]

[fe8e0b1b1f38c81035d80a3ff8e8bfd0]
catalognumber = "SVWC-70321~2"
date = "2017-11-22"
album = "ぼなぺてぃーと♡S/デタラメなマイナスとプラスにおけるブレンド考 / ブレンド・A Disc 2 (Blu-ray) [SVWC-70322]"
tracks = [
    [1, "オープニング映像", "ブレンド・A", 0],
    [2, "ノンクレジットエンディング映像", "ブレンド・A", 0],
    [3, "ぼなぺてぃーと♡S (MUSIC VIDEO)", "ブレンド・A", 1],
]
links = ["https://beta.musicbrainz.org/release/5a899dfd-9629-4d87-84ab-fcb5ec7f1529", "https://vgmdb.net/album/71864"]

[9b3755bd97dc49a4d20da0261be469da]
catalognumber = "ANZX-12682"
date = "2017-12-27"
album = "ブレンド・S 第1巻 AUDIO DISC"
tracks = [
    [1, "ポジティブレボリューション", "桜ノ宮苺香(CV:和氣あず未)", 1],
    [2, "ぼなぺてぃーと♡S -桜ノ宮苺香ver.-", "桜ノ宮苺香(CV:和氣あず未)", 1],
    [3, "ポジティブレボリューション <Instrumental>", "桜ノ宮苺香(CV:和氣あず未)", 1],
    [4, "ドSだけじゃダメですか?", "和氣あず未、鬼頭明里、春野杏、種﨑敦美、徳井青空、前野智昭、鈴木達央", 1],
    [5, "ようこそ、スティーレへ! ～苺香～", "和氣あず未", 1],
    [6, "ブレンドはSにして", "菊谷知樹", 1],
    [7, "桜ノ宮家", "菊谷知樹", 1],
    [8, "昼下がりは憂いの時", "菊谷知樹", 1],
    [9, "今日は良い事がありそうです", "菊谷知樹", 1],
    [10, "CAFE STILE", "菊谷知樹", 1],
    [11, "初対面", "菊谷知樹", 1],
    [12, "そわそわ", "菊谷知樹", 1],
    [13, "自己紹介", "菊谷知樹", 1],
    [14, "ぐったり", "菊谷知樹", 1],
    [15, "ピース", "菊谷知樹", 1],
    [16, "コメディー・ブレンド(アメリカン)", "菊谷知樹", 1],
    [17, "初接客はドSに", "菊谷知樹", 1],
    [18, "コメディー・ブレンド(エスプレッソ)", "菊谷知樹", 1],
    [19, "また来て下さい", "菊谷知樹", 1],
    [20, "憧れ", "菊谷知樹", 1],
    [21, "寝不足", "菊谷知樹", 1],
    [22, "冷たい仕打ち", "菊谷知樹", 1],
    [23, "仕事モード", "菊谷知樹", 1],
    [24, "失敗の原因", "菊谷知樹", 1],
    [25, "召し上がれ", "菊谷知樹", 1],
    [26, "どきどきメモリアル", "菊谷知樹", 1],
    [27, "帰り道", "菊谷知樹", 1],
    [28, "BEAT DANCE EVOLUTION", "菊谷知樹", 1],
]
links = ["https://beta.musicbrainz.org/release/d266f283-5fac-4918-bc4c-14fe047a16fd", "https://vgmdb.net/album/71865"]

[c4c561e720fa45ecacf3e332aec3ccf1]
catalognumber = "ANZX-12684"
date = "2018-01-24"
album = "ブレンド・S 第2巻 AUDIO DISC"
tracks = [
    [1, "インスタントマーメイド", "日向夏帆(CV:鬼頭明里)", 1],
    [2, "ぼなぺてぃーと♡S -日向夏帆ver.-", "日向夏帆(CV:鬼頭明里)", 1],
    [3, "インスタントマーメイド <Instrumental>", "日向夏帆(CV:鬼頭明里)", 1],
    [4, "Kaho-chan QUEST～そして、ツンデレへ～", "和氣あず未、鬼頭明里、春野杏、種﨑敦美、徳井青空、前野智昭、鈴木達央", 1],
    [5, "ようこそ、スティーレへ!～夏帆～", "鬼頭明里", 1],
    [6, "始まりの時", "菊谷知樹", 1],
    [7, "不安", "菊谷知樹", 1],
    [8, "お勉強", "菊谷知樹", 1],
    [9, "全然分かりません", "菊谷知樹", 1],
    [10, "スイーツ", "菊谷知樹", 1],
    [11, "ジャングル喫茶", "菊谷知樹", 1],
    [12, "準備中", "菊谷知樹", 1],
    [13, "おっとりお姉さん", "菊谷知樹", 1],
    [14, "勝負", "菊谷知樹", 1],
    [15, "夏の海", "菊谷知樹", 1],
    [16, "作戦会議中", "菊谷知樹", 1],
    [17, "良いと思います", "菊谷知樹", 1],
    [18, "控え目", "菊谷知樹", 1],
    [19, "よくできました!", "菊谷知樹", 1],
    [20, "まったり", "菊谷知樹", 1],
    [21, "赤面", "菊谷知樹", 1],
    [22, "うきうき", "菊谷知樹", 1],
    [23, "コメディー・ブレンド(カプチーノ)", "菊谷知樹", 1],
    [24, "女王様", "菊谷知樹", 1],
    [25, "閉店", "菊谷知樹", 1],
    [26, "質問攻め", "菊谷知樹", 1],
    [27, "ピンチ", "菊谷知樹", 1],
    [28, "宵闇は哀しみの時", "菊谷知樹", 1],
    [29, "まとも", "菊谷知樹", 1],
    [30, "思いをはせて", "菊谷知樹", 1],
    [31, "ゲレンデ", "菊谷知樹", 1],
]
links = ["https://beta.musicbrainz.org/release/426b3721-e136-47c5-a19a-2df63b6314de", "https://vgmdb.net/album/72233"]

[066512cf00903afd0ac8f66087e10062]
catalognumber = "TBZR-0969~70"
date = "2018-01-31"
album = "ブレンド・Sラジオ「スティーレスタイル!」ラジオCD Disc 1 (CD) [TBZR-0969]"
tracks = [
    [1, "新規録りおろしラジオ", "", 0],
]
links = ["https://vgmdb.net/album/74658"]

[d060b62e90f670eee935afcc800df2fd]
catalognumber = "TBZR-0969~70"
date = "2018-01-31"
album = "ブレンド・Sラジオ「スティーレスタイル!」ラジオCD Disc 2 (CD-ROM) [TBZR-0970]"
tracks = [
    [1, "ブレンド・Sラジオ「スティーレスタイル!」 第1回", "", 0],
    [2, "ブレンド・Sラジオ「スティーレスタイル!」 第2回", "", 0],
    [3, "ブレンド・Sラジオ「スティーレスタイル!」 第3回", "", 0],
    [4, "ブレンド・Sラジオ「スティーレスタイル!」 第4回", "", 0],
    [5, "ブレンド・Sラジオ「スティーレスタイル!」 第5回", "", 0],
    [6, "ブレンド・Sラジオ「スティーレスタイル!」 第6回", "", 0],
]
links = ["https://vgmdb.net/album/74658"]

[e93a4fb96f92efe7ecdb8e37bdccdb7b]
catalognumber = "ANZX-12686"
date = "2018-02-28"
album = "ブレンド・S 第3巻 AUDIO DISC"
tracks = [
    [1, "マフユ・フリル・イズム", "星川麻冬(CV:春野杏)", 1],
    [2, "ぼなぺてぃーと♡S -星川麻冬ver.-", "星川麻冬(CV:春野杏)", 1],
    [3, "マフユ・フリル・イズム <Instrumental>", "星川麻冬(CV:春野杏)", 1],
    [4, "麻冬ちゃんと童話の国", "和氣あず未、鬼頭明里、春野杏、種﨑敦美、徳井青空、前野智昭、鈴木達央", 1],
    [5, "ようこそ、スティーレへ!～麻冬～", "春野 杏", 1],
]
links = ["https://beta.musicbrainz.org/release/c405f4a6-3dc6-433e-a662-b59c81e96f29", "https://vgmdb.net/album/72234"]

[37a09fedb42c3188db6e3fab773be7a1]
catalognumber = "ANZX-12688"
date = "2018-03-28"
album = "ブレンド・S 第4巻 AUDIO DISC"
tracks = [
    [1, "妄想ワーキングタイム", "天野美雨(CV:種﨑敦美)", 1],
    [2, "ぼなぺてぃーと♡S -天野美雨ver.-", "天野美雨(CV:種﨑敦美)", 1],
    [3, "妄想ワーキングタイム <Instrumental>", "天野美雨(CV:種﨑敦美)", 1],
    [4, "フォルダ先生の創作ノート", "和氣あず未、鬼頭明里、春野杏、種﨑敦美、徳井青空、前野智昭、鈴木達央", 1],
    [5, "ようこそ、スティーレへ! ～美雨～", "種﨑敦美", 1],
]
links = ["https://beta.musicbrainz.org/release/79f32e3a-a885-4a4f-a4ca-7affec4520df", "https://vgmdb.net/album/72235"]

[2c40c664b3dc99d1d0ef84cdef5b431e]
catalognumber = "ANZX-12690"
date = "2018-04-25"
album = "ブレンド・S 第5巻 AUDIO DISC"
tracks = [
    [1, "明日も世界の真ん中で♡", "神崎ひでり(CV:徳井青空)", 1],
    [2, "ぼなぺてぃーと♡S -神崎ひでりver.-", "神崎ひでり(CV:徳井青空)", 1],
    [3, "明日も世界の真ん中で♡ <Instrumental>", "神崎ひでり(CV:徳井青空)", 1],
    [4, "ひでりのアイドル活動、はじまりますん?", "和氣あず未、鬼頭明里、春野杏、種﨑敦美、徳井青空、前野智昭、鈴木達央", 1],
    [5, "ようこそ、スティーレへ!～ひでり～", "徳井青空", 1],
]
links = ["https://beta.musicbrainz.org/release/73f98a1c-6397-449a-96cc-4cd3175d24d2", "https://vgmdb.net/album/72236"]

[fc7135ae851d5cf3ad894527fc1b3898]
catalognumber = "TBZR-1007~9"
date = "2018-05-30"
album = "ブレンド・Sラジオ「スティーレスタイル!」ラジオCD Vol.2 Talk Disc 1"
tracks = [
    [1, "新規録りおろしラジオ", "", 0],
]
links = ["https://vgmdb.net/album/81992"]

[0bab0cb1da4ab921366825fd0926eedf]
catalognumber = "TBZR-1007~9"
date = "2018-05-30"
album = "ブレンド・Sラジオ「スティーレスタイル!」ラジオCD Vol.2 Talk Disc 2"
tracks = [
    [1, "ブレンド・Sラジオ「スティーレスタイル!」 第7回", "", 0],
    [2, "ブレンド・Sラジオ「スティーレスタイル!」 第8回", "", 0],
    [3, "ブレンド・Sラジオ「スティーレスタイル!」 第9回", "", 0],
    [4, "ブレンド・Sラジオ「スティーレスタイル!」 第10回", "", 0],
    [5, "ブレンド・Sラジオ「スティーレスタイル!」 第11回", "", 0],
    [6, "ブレンド・Sラジオ「スティーレスタイル!」 第12回", "", 0],
    [7, "ブレンド・Sラジオ「スティーレスタイル!」 第13回", "", 0],
    [8, "ブレンド・Sラジオ「スティーレスタイル!」 第14回", "", 0],
    [9, "ブレンド・Sラジオ「スティーレスタイル!」 第15回", "", 0],
    [10, "ブレンド・Sラジオ「スティーレスタイル!」 第16回", "", 0],
    [11, "ブレンド・Sラジオ「スティーレスタイル!」 第17回", "", 0],
    [12, "ブレンド・Sラジオ「スティーレスタイル!」 第18回", "", 0],
    [13, "ブレンド・Sラジオ「スティーレスタイル!」 第19回", "", 0],
    [14, "ブレンド・Sラジオ「スティーレスタイル!」 第20回", "", 0],
]
links = ["https://vgmdb.net/album/81992"]

[7dcc2eac6e3858dbb10d8c70b578ca25]
catalognumber = "ANZX-12692"
date = "2018-05-30"
album = "ブレンド・S 第6巻 AUDIO DISC"
tracks = [
    [1, "貴女にDolce", "ディーノ(CV:前野智昭)、秋月紅葉(CV:鈴木達央)", 1],
    [2, "ぼなぺてぃーと♡S -Hall staff ver.-", "桜ノ宮苺香(CV:和氣あず未)、日向夏帆(CV:鬼頭明里)、星川麻冬(CV:春野杏)、天野美雨(CV:種﨑敦美)、神崎ひでり(CV:徳井青空)", 1],
    [3, "ぼなぺてぃーと♡S -All staff ver.-", "桜ノ宮苺香(CV:和氣あず未)、日向夏帆(CV:鬼頭明里)、星川麻冬(CV:春野杏)、天野美雨(CV:種﨑敦美)、神崎ひでり(CV:徳井青空)、ディーノ(CV:前野智昭)、秋月紅葉(CV:鈴木達央)", 1],
    [4, "貴女にDolce <Instrumental>", "ディーノ(CV:前野智昭)、秋月紅葉(CV:鈴木達央)", 1],
    [5, "ドキッ! ♂だらけのタコ焼きパーティー", "和氣あず未、鬼頭明里、春野杏、種﨑敦美、徳井青空、前野智昭、鈴木達央", 1],
    [6, "ようこそ、スティーレへ! ～ディーノ～", "前野智昭", 1],
    [7, "ようこそ、スティーレへ! ～秋月～", "鈴木達央", 1],
]
links = ["https://beta.musicbrainz.org/release/5f74f912-773e-4310-a8f3-6418b92bc534", "https://vgmdb.net/album/72237"]

[0aa23b6472052971541b47fc42f5f5f1]
catalognumber = "SBCV-80279"
date = "2018-05-30"
album = "スティーレスタイル! 出張版"
tracks = []
links = ["https://vgmdb.net/album/74661"]

[aad864f09bfaf5e7f7bf78127b044936]
catalognumber = "STILE-0001"
date = "2018-08-08"
album = "ブレンド・Sラジオ「スティーレスタイル!」録りおろしCD"
tracks = []
links = ["https://vgmdb.net/album/74659"]

[7a21dd34ba00b4a222f514efe39863ba]
catalognumber = "NJSJ-009"
date = "2020-10-28"
album = "Prismatic Colors 特典CD / にじさんじ"
tracks = [
    [1, "ぼなぺてぃーと♡S", "葉加瀬冬雪、星川サラ、リゼ・ヘルエスタ", 1],
    [2, "oblivious", "戌亥とこ、町田ちま、メリッサ・キンレンカ", 0],
    [3, "檄！帝国華撃団", "アンジュ・カトリーナ、ドーラ、早瀬走、レヴィ・エリファ", 0],
    [4, "女々しくて", "卯月コウ、剣持刀也、シェリン・バーガンディ", 0],
]
links = ["https://beta.musicbrainz.org/release/0cd97c3b-37ed-4cc3-9702-0fe78c12f34a", "https://vgmdb.net/album/111081"]

[ebd72833f3ea012e1a90cebe07b74153]
catalognumber = "ANXX-01104"
date = "2022-05-19"
album = "インスタントマーメイド / 日向夏帆(CV:鬼頭明里)"
tracks = [
    [1, "インスタントマーメイド", "日向夏帆(CV:鬼頭明里)", 1],
]
links = ["https://beta.musicbrainz.org/release/6b5e3091-6666-4e4b-8740-b25e0ca85f15", "https://vgmdb.net/album/119756"]

[ad314b99ecaf2bcc2fa0e2dc45f60727]
catalognumber = "ANXX-01105"
date = "2022-06-30"
album = "明日も世界の真ん中で♡ / 神崎ひでり(CV:徳井青空)"
tracks = [
    [1, "明日も世界の真ん中で♡", "神崎ひでり(CV:徳井青空)", 1],
]
links = ["https://beta.musicbrainz.org/release/d7d4d282-d47c-4149-ba7e-a4f9f8bb3bef", "https://vgmdb.net/album/121268"]

[eb7643235830d2fbed3ee6b1a591563c]
catalognumber = "ANZX-14414"
date = "2022-07-27"
album = "ブレンド・S Blu-ray Disc BOX 特典CD"
tracks = [
    [1, "ブレンド・プラス", "ブレンド・A", 1],
    [2, "ぼなぺてぃーと♡S", "ブレンド・A", 1],
    [3, "デタラメなマイナスとプラスにおけるブレンド考", "ブレンド・A", 1],
    [4, "ポジティブレボリューション", "桜ノ宮苺香(CV:和氣あず未)", 1],
    [5, "インスタントマーメイド", "日向夏帆(CV:鬼頭明里)", 1],
    [6, "マフユ・フリル・イズム", "星川麻冬(CV:春野杏)", 1],
    [7, "妄想ワーキングタイム", "天野美雨(CV:種﨑敦美)", 1],
    [8, "明日も世界の真ん中で♡", "神崎ひでり(CV:徳井青空)", 1],
    [9, "貴女にDolce", "ディーノ(CV:前野智昭)、秋月紅葉(CV:鈴木達央)", 1],
    [10, "ぼなぺてぃーと♡S -桜ノ宮苺香ver.-", "桜ノ宮苺香(CV:和氣あず未)", 1],
    [11, "ぼなぺてぃーと♡S -日向夏帆ver.-", "日向夏帆(CV:鬼頭明里)", 1],
    [12, "ぼなぺてぃーと♡S -星川麻冬ver.-", "星川麻冬(CV:春野杏)", 1],
    [13, "ぼなぺてぃーと♡S -天野美雨ver.-", "天野美雨(CV:種﨑敦美)", 1],
    [14, "ぼなぺてぃーと♡S -神崎ひでりver.-", "神崎ひでり(CV:徳井青空)", 1],
    [15, "ぼなぺてぃーと♡S -Hall staff ver.-", "桜ノ宮苺香(CV:和氣あず未)、日向夏帆(CV:鬼頭明里)、星川麻冬(CV:春野杏)、天野美雨(CV:種﨑敦美)、神崎ひでり(CV:徳井青空)", 1],
    [16, "ぼなぺてぃーと♡S -All staff ver.-", "桜ノ宮苺香(CV:和氣あず未)、日向夏帆(CV:鬼頭明里)、星川麻冬(CV:春野杏)、天野美雨(CV:種﨑敦美)、神崎ひでり(CV:徳井青空)、ディーノ(CV:前野智昭)、秋月紅葉(CV:鈴木達央)", 1],
]
links = ["https://beta.musicbrainz.org/release/8ba7b5ba-8737-4802-b16f-c4321ee136bd", "https://vgmdb.net/album/119086"]

[cd934fe964db336a0fdc2bba18cc3244]
catalognumber = "BRMM-10572"
date = "2022-10-26"
album = "D4DJ Groovy Mix カバートラックス vol.6"
tracks = [
    [1, "H-A-J-I-M-A-R-I-U-T-A-!!", "Happy Around!", 0],
    [2, "PARTY☆NIGHT", "Happy Around!", 0],
    [3, "Pretender", "Peaky P-key", 0],
    [4, "ご唱和ください我の名を！", "Peaky P-key", 0],
    [5, "恋する図形(cubic futurismo)", "Photon Maiden", 0],
    [6, "ブルーバード", "Photon Maiden", 0],
    [7, "Bomb A Head!", "Merm4id", 0],
    [8, "HONEY", "Merm4id", 0],
    [9, "深い森", "燐舞曲", 0],
    [10, "killy killy JOKER", "燐舞曲", 0],
    [11, "Agapё", "Lyrical Lily", 0],
    [12, "ぼなぺてぃーと♡S", "Lyrical Lily", 1],
]
links = ["https://beta.musicbrainz.org/release/ae6b1d1f-2d8b-46dc-ab17-4c952334c8ed", "https://vgmdb.net/album/122544"]
