[3b87e776ee05fb448904128a7a1c9024]
catalognumber = "ESCL-5076"
date = "2018-06-27"
album = "初恋"
tracks = [
    [1, "Play A Love Song", "宇多田ヒカル", 0],
    [2, "あなた", "宇多田ヒカル", 0],
    [3, "初恋", "宇多田ヒカル", 0],
    [4, "誓い", "宇多田ヒカル", 0],
    [5, "Forevermore", "宇多田ヒカル", 0],
    [6, "Too Proud", "宇多田ヒカル featuring Jevon", 0],
    [7, "Good Night", "宇多田ヒカル", 0],
    [8, "パクチーの唄", "宇多田ヒカル", 0],
    [9, "残り香", "宇多田ヒカル", 0],
    [10, "大空で抱きしめて", "宇多田ヒカル", 0],
    [11, "夕凪", "宇多田ヒカル", 0],
    [12, "嫉妬されるべき人生", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/f5938dec-e508-4ddf-9110-de558cc7487a"]

[7cbc66dd39035428fc2fcb2414de072d]
catalognumber = "ESCL-5094"
date = "2018-08-15"
album = "「ペンギン・ハイウェイ」オリジナル・サウンドトラック"
tracks = [
    [1, "ペンギン・ハイウェイのテーマ", "阿部海太郎", 0],
    [2, "天才少年の朝", "阿部海太郎", 0],
    [3, "プロジェクト・アマゾン", "阿部海太郎", 0],
    [4, "ペンギン発見", "阿部海太郎", 0],
    [5, "マドンナ", "阿部海太郎", 0],
    [6, "お姉さん", "阿部海太郎", 0],
    [7, "最初の夢", "阿部海太郎", 0],
    [8, "実験成功", "阿部海太郎", 0],
    [9, "世界のしまい方", "阿部海太郎", 0],
    [10, "未知との出会い", "阿部海太郎", 0],
    [11, "夏休み", "阿部海太郎", 0],
    [12, "かわいがり", "阿部海太郎", 0],
    [13, "海辺のカフェ", "阿部海太郎", 0],
    [14, "ペンギン号、<海>へ", "阿部海太郎", 0],
    [15, "帝国の逆襲", "阿部海太郎", 0],
    [16, "ペンタを連れて", "阿部海太郎", 0],
    [17, "プロミネンス", "阿部海太郎", 0],
    [18, "全て一つの問題", "阿部海太郎", 0],
    [19, "円環の川", "阿部海太郎", 0],
    [20, "海辺の街へ", "阿部海太郎", 0],
    [21, "ジャバウォック", "阿部海太郎", 0],
    [22, "奪われる研究", "阿部海太郎", 0],
    [23, "悪い夢", "阿部海太郎", 0],
    [24, "エウレカ", "阿部海太郎", 0],
    [25, "脱出", "阿部海太郎", 0],
    [26, "研究発表", "阿部海太郎", 0],
    [27, "ペンギン・パレード", "阿部海太郎", 0],
    [28, "世界の果て", "阿部海太郎", 0],
    [29, "<海>の崩壊", "阿部海太郎", 0],
    [30, "誰もいない街", "阿部海太郎", 0],
    [31, "これからの研究課題", "阿部海太郎", 0],
]
links = ["https://beta.musicbrainz.org/release/e4306b10-b6ab-4636-979a-96568d05b857", "https://vgmdb.net/album/78787"]
