[ee859602e37a3930c42513908f1c2251]
catalognumber = "THCS-60037"
date = "2014-05-21"
album = "奏(かなで) / 藤宮香織 (cv: 雨宮天)"
tracks = [
    [1, "奏 (かなで)", "藤宮香織 (cv:雨宮天)", 0],
    [2, "奏 (かなで) -Instrumental-", "藤宮香織 (cv:雨宮天)", 0],
    [3, "友達の記憶 (劇伴)", "戸田色音", 0],
    [4, "気持ち、あふれて (劇伴)", "戸田色音", 0],
    [5, "奏 (かなで)", "長谷祐樹 (cv:山谷祥生)", 0],
]
links = ["https://vgmdb.net/album/44431", "https://beta.musicbrainz.org/release/465beaf4-48e6-4e5c-92b3-d91d274a6c4b"]

[d6a103775e2f8b5e4de6c1a2085d1c6c]
catalognumber = "THCS-60036"
date = "2014-05-21"
album = "虹のかけら / 昆夏美"
tracks = [
    [1, "虹のかけら", "昆夏美", 0],
    [2, "ギフト", "昆夏美", 0],
    [3, "虹のかけら (Instrumental)", "昆夏美", 0],
    [4, "ギフト (Instrumental)", "昆夏美", 0],
]
links = ["https://vgmdb.net/album/44423", "https://beta.musicbrainz.org/release/a56f68b0-0940-4931-8545-2cf4b5cffcb4"]

[aac157866dc52b3e1d147cd19c571054]
catalognumber = "TBR24281D-2"
date = "2014-06-18"
album = "一週間フレンズ。 ミニサウンドトラックCD"
tracks = [
    [1, "友達の記憶 ver.b", "戸田色音", 0],
    [2, "もどかしい気持ち", "戸田色音", 0],
    [3, "お昼は2人で", "戸田色音", 0],
    [4, "私の大切な友達", "戸田色音", 0],
    [5, "藤宮さんの日記", "戸田色音", 0],
    [6, "記憶の消失", "戸田色音", 0],
    [7, "偽りの記憶", "戸田色音", 0],
    [8, "不安な日々", "戸田色音", 0],
    [9, "月曜日", "戸田色音", 0],
    [10, "奏(かなで)～TV size ver.～", "藤宮香織 (雨宮天)", 0],
]
links = ["https://vgmdb.net/album/45155", "https://beta.musicbrainz.org/release/657d7fd2-781a-4f7b-91b1-5e23f5384335"]

[5ec1f2ec474752138390ed9a399a0681]
catalognumber = "THCA-60039"
date = "2014-09-17"
album = "TVアニメ「一週間フレンズ。」 オリジナル・サウンドトラック"
tracks = [
    [1, "友達の記憶 (ver.b)", "戸田色音", 0],
    [2, "もどかしい気持ち", "戸田色音", 0],
    [3, "昼休みの屋上", "戸田色音", 0],
    [4, "お昼は二人で", "戸田色音", 0],
    [5, "私の大切な友達", "戸田色音", 0],
    [6, "藤宮さんとおしゃべり", "戸田色音", 0],
    [7, "藤宮さんにドキドキ", "戸田色音", 0],
    [8, "長谷くんと桐生くん", "戸田色音", 0],
    [9, "楽しい放課後 (ver.a)", "戸田色音", 0],
    [10, "おっとり沙希ちゃん", "戸田色音", 0],
    [11, "新しい友達", "戸田色音", 0],
    [12, "てとてと沙希", "戸田色音", 0],
    [13, "そんなに仲良くならないで!", "戸田色音", 0],
    [14, "やきもき長谷くん", "戸田色音", 0],
    [15, "楽しい放課後 (ver.b)", "戸田色音", 0],
    [16, "学校の帰り道", "戸田色音", 0],
    [17, "朝の光の中で", "戸田色音", 0],
    [18, "藤宮さんの日記", "戸田色音", 0],
    [19, "消えない想い、いつまでも", "戸田色音", 0],
    [20, "不安な日々", "戸田色音", 0],
    [21, "過去の出来事", "戸田色音", 0],
    [22, "忘却の彼方に", "戸田色音", 0],
    [23, "月曜日", "戸田色音", 0],
    [24, "記憶の消失", "戸田色音", 0],
    [25, "偽りの記憶", "戸田色音", 0],
    [26, "友達になりたい", "戸田色音", 0],
    [27, "穏やかな時", "戸田色音", 0],
    [28, "気持ち、あふれて", "戸田色音", 0],
    [29, "友達の記憶 (ver.a)", "戸田色音", 0],
    [30, "虹のかけら -Piano ver.-", "戸田色音", 0],
    [31, "虹のかけら -TV size ver.-", "昆夏美", 0],
    [32, "奏 (かなで) -TV size ver.-", "藤宮香織 (雨宮天)", 0],
]
links = ["https://vgmdb.net/album/46332", "https://beta.musicbrainz.org/release/e079890b-3bac-40bd-ba38-3b7771ec961f"]

[1674e67c0a591eef07d0b1162f22e598]
catalognumber = "TBCD-0316"
date = "2014-10-29"
album = "ドラマCD「一週間フレンズ。」"
tracks = []
links = ["https://vgmdb.net/album/47940"]

[d20ac0c5db1ef72ebea3398080608080]
catalognumber = "BRMM-10659"
date = "2023-07-12"
album = "D4DJ Groovy Mix カバートラックス vol.8"
tracks = [
    [1, "ヒャダインのじょーじょーゆーじょー", "Happy Around!", 0],
    [2, "Sparkling Daydream", "Happy Around!", 0],
    [3, "BLACK SHOUT", "Peaky P-key", 0],
    [4, "Storyteller", "Peaky P-key", 0],
    [5, "99 ILLUSION！", "Photon Maiden", 0],
    [6, "This game", "Photon Maiden", 0],
    [7, "Timing", "Merm4id", 0],
    [8, "GO!!!", "Merm4id", 0],
    [9, "KiLLiNG ME", "燐舞曲", 0],
    [10, "奏（かなで）", "燐舞曲", 0],
    [11, "にゃんだーわんだーデイズ", "Lyrical Lily", 0],
    [12, "撲殺天使ドクロちゃん", "Lyrical Lily", 0],
    [13, "INTERNET OVERDOSE", "UniChØrd", 0],
    [14, "回レ!雪月花", "UniChØrd", 0],
    [15, "怪物", "Abyssmare", 0],
    [16, "Red fraction", "Abyssmare", 0],
]
links = ["https://vgmdb.net/album/130504", "https://beta.musicbrainz.org/release/b44fe389-58f4-4537-907b-2050a9167524"]
