[e3338253c0d5e4c3e411c8769f4c775d]
catalognumber = "THCS-60093"
date = "2016-04-20"
album = "ぐーちょきパレード / とりぷる☘ふぃーりんぐ"
tracks = [
    [1, "ぐーちょきパレード", "とりぷる♣ふぃーりんぐ", 1],
    [2, "ぱじゃまParty", "とりぷる♣ふぃーりんぐ", 1],
    [3, "ぐーちょきパレード (Instrumental)", "とりぷる♣ふぃーりんぐ", 1],
    [4, "ぱじゃまParty (Instrumental)", "とりぷる♣ふぃーりんぐ", 1],
]
links = ["https://beta.musicbrainz.org/release/c608bb9b-c8b3-4c13-84bb-6a75ac2daaf6", "https://vgmdb.net/album/57224"]

[9badcadad7e6e873dae86178ac3872d6]
catalognumber = "THCS-60092"
date = "2016-04-20"
album = "クローバー☘かくめーしょん / とりぷる☘ふぃーりんぐ"
tracks = [
    [1, "クローバー♣かくめーしょん", "とりぷる♣ふぃーりんぐ", 1],
    [2, "スクールはいたっち!", "とりぷる♣ふぃーりんぐ", 1],
    [3, "クローバー♣かくめーしょん (Instrumental)", "とりぷる♣ふぃーりんぐ", 1],
    [4, "スクールはいたっち! (Instrumental)", "とりぷる♣ふぃーりんぐ", 1],
]
links = ["https://beta.musicbrainz.org/release/4105d673-63d8-4069-8cad-56f494cb46fe", "https://vgmdb.net/album/57223"]

[34b3af364e74efb66d2f828730113759]
catalognumber = "THCS-60096"
date = "2016-05-18"
album = "三者三葉 キャラクターソング Vol.2 / 小田切双葉(CV:金澤まい)、臼田桜(CV:夏野菜緒)"
tracks = [
    [1, "歌がごはんでごはんはおかず (ボイスドラマ1)", "[dialogue]", 1],
    [2, "とぅいんくる☆そんぐ!!", "小田切双葉&臼田桜(CV:金澤まい&夏野菜緒)", 1],
    [3, "マイナスをゼロにいたしました (ボイスドラマ2)", "[dialogue]", 1],
    [4, "満腹至上主義", "小田切双葉(CV:金澤まい)", 1],
    [5, "ごはん肉肉肉肉ミーーーーート! (ボイスドラマ3)", "[dialogue]", 1],
    [6, "ZOKKON☆チェリーブロッサム", "臼田桜(CV:夏野菜緒)", 1],
    [7, "耳から食べて鼻から出してる (ボイスドラマ4)", "[dialogue]", 1],
    [8, "とぅいんくる☆そんぐ!! (Instrumental)", "小田切双葉&臼田桜(CV:金澤まい&夏野菜緒)", 1],
    [9, "満腹至上主義 (Instrumental)", "小田切双葉(CV:金澤まい)", 1],
    [10, "ZOKKON☆チェリーブロッサム (Instrumental)", "臼田桜(CV:夏野菜緒)", 1],
]
links = ["https://beta.musicbrainz.org/release/7484ff86-79bc-4974-8f5d-4f0b1ce7c285", "https://vgmdb.net/album/57695"]

[66100a1b2a2006e0f53ffe3835bd1224]
catalognumber = "THCS-60095"
date = "2016-05-18"
album = "三者三葉 キャラクターソング Vol.1 / 西川葉子(CV:和久井優)、薗部篠(CV:桃河りか)"
tracks = [
    [1, "正座でカラオケ (ボイスドラマ1)", "[dialogue]", 1],
    [2, "ラズベリー畑でつかまえて", "西川葉子&薗部篠(CV:和久井優 & 桃河りか)", 2],
    [3, "敵はすでに中にいたのですね (ボイスドラマ2)", "[dialogue]", 1],
    [4, "マヨってTo Heart!", "西川葉子(CV:和久井優)", 1],
    [5, "オバハラの怪音波が! (ボイスドラマ3)", "[dialogue]", 1],
    [6, "Loli-pop☆Monster", "薗部篠(CV:桃河りか)", 1],
    [7, "ごちそうを食べる夢を見ていた (ボイスドラマ4)", "[dialogue]", 1],
    [8, "ラズベリー畑でつかまえて (Instrumental)", "西川葉子&薗部篠(CV:和久井優 & 桃河りか)", 1],
    [9, "マヨってTo Heart! (Instrumental)", "西川葉子(CV:和久井優)", 1],
    [10, "Loli-pop☆Monster (Instrumental)", "薗部篠(CV:桃河りか)", 1],
]
links = ["https://beta.musicbrainz.org/release/f6c9b85e-cc40-4e2c-b61e-325be7a187cc", "https://vgmdb.net/album/57694"]

[64275e30505670098da522023fc97969]
catalognumber = "THCS-60097"
date = "2016-06-15"
album = "三者三葉 キャラクターソング Vol.3 / 葉山照(CV:今村彩夏)、葉山光(CV:西明日香)"
tracks = [
    [1, "カラオケの『カ』は… (ボイスドラマ1)", "[dialogue]", 1],
    [2, "最強ハーモニー", "葉山照&葉山光(CV:今村彩夏&西明日香)", 2],
    [3, "歌にも危険物取扱許可 (ボイスドラマ2)", "[dialogue]", 1],
    [4, "Amazing Days", "葉山照(CV:今村彩夏)", 1],
    [5, "喉のケアもしないと (ボイスドラマ3)", "[dialogue]", 1],
    [6, "全然デリシャス!", "葉山光(CV:西明日香)", 1],
    [7, "たった二人の姉妹なんだから (ボイスドラマ4)", "[dialogue]", 1],
    [8, "最強ハーモニー (Instrumental)", "葉山照&葉山光(CV:今村彩夏&西明日香)", 1],
    [9, "Amazing Days (Instrumental)", "葉山照(CV:今村彩夏)", 1],
    [10, "全然デリシャス! (Instrumental)", "葉山光(CV:西明日香)", 1],
]
links = ["https://beta.musicbrainz.org/release/39a2d68c-f1aa-4d9f-9d38-12fcc68f44c5", "https://vgmdb.net/album/57696"]

[1c3279d7c6a1640212a297819597bfea]
catalognumber = "THCS-60098"
date = "2016-06-15"
album = "三者三葉 キャラクターソング Vol.4 / 西山芹菜(CV:Machico)、近藤亜紗子(CV:鈴木愛奈)"
tracks = [
    [1, "だって友だちだもん (ボイスドラマ1)", "[dialogue]", 1],
    [2, "なんだかんだコンビネーション", "西山芹奈&近藤亜紗子(CV:Machico&鈴木愛奈)", 1],
    [3, "にゃんこの魔力 (ボイスドラマ2)", "[dialogue]", 1],
    [4, "ライバル戦線", "西山芹奈(CV:Machico)", 1],
    [5, "いまわたし肉球だから (ボイスドラマ3)", "[dialogue]", 1],
    [6, "フォローはまかせてっ!-Dear Friend-", "近藤亜紗子(CV:鈴木愛奈)", 1],
    [7, "この友情を記念して (ボイスドラマ4)", "[dialogue]", 1],
    [8, "なんだかんだコンビネーション (Instrumental)", "西山芹奈&近藤亜紗子(CV:Machico&鈴木愛奈)", 1],
    [9, "ライバル戦線 (Instrumental)", "西山芹奈(CV:Machico)", 1],
    [10, "フォローはまかせてっ!-Dear Friend- (Instrumental)", "近藤亜紗子(CV:鈴木愛奈)", 1],
]
links = ["https://beta.musicbrainz.org/release/f78e0a2d-5d7c-45e1-8266-cfa881f19d3e", "https://vgmdb.net/album/57697"]

[bb2e9ae3ea92be89a2c8f2512f582d09]
catalognumber = "THCA-60100"
date = "2016-07-13"
album = "TVアニメ「三者三葉」オリジナル・サウンドトラック"
tracks = [
    [1, "今日もパンの耳", "睦月周平", 1],
    [2, "なんなんですの、あなたたち!", "睦月周平", 1],
    [3, "おなかすいた、おなかすいたー!", "睦月周平", 1],
    [4, "いまだって普通に話してるのに", "睦月周平", 1],
    [5, "私たちが力になるから", "睦月周平", 1],
    [6, "初耳です", "睦月周平", 1],
    [7, "平常心ですわ", "睦月周平", 1],
    [8, "覚えてなさいよ", "睦月周平", 1],
    [9, "元執事の人", "睦月周平", 1],
    [10, "何か…いる", "睦月周平", 1],
    [11, "タイミング悪いわね", "睦月周平", 1],
    [12, "いい子にはごほうび", "睦月周平", 1],
    [13, "無欲の勝利", "睦月周平", 1],
    [14, "デレ?ツン?", "睦月周平", 1],
    [15, "何か…血のような", "睦月周平", 1],
    [16, "なんでしょう…この胸の高鳴り", "睦月周平", 1],
    [17, "あらあらまあまあ", "睦月周平", 1],
    [18, "友達なんだし", "睦月周平", 1],
    [19, "すがすがしいほどお嬢さま", "睦月周平", 1],
    [20, "いっぱい食べる元気な子だったよ", "睦月周平", 1],
    [21, "せめて見た目だけでも", "睦月周平", 1],
    [22, "将来はアイドルになるから", "睦月周平", 1],
    [23, "とりとめのないくだらないお話", "睦月周平", 1],
    [24, "お嬢にたんこぶ", "睦月周平", 1],
    [25, "秘密の花園、海の家バージョン!!", "睦月周平", 1],
    [26, "絶対バレない自信はあります", "睦月周平", 1],
    [27, "ゆるぎない昭和臭", "睦月周平", 1],
    [28, "思い出になりました", "睦月周平", 1],
    [29, "初めてですわ", "睦月周平", 1],
    [30, "いただきます!", "睦月周平", 1],
    [31, "どうせなら勝負しろ", "睦月周平", 1],
    [32, "レベルアップしていますのよ", "睦月周平", 1],
    [33, "そう…私は…できる女!", "睦月周平", 1],
    [34, "通い慣れてる", "睦月周平", 1],
    [35, "負けないわ", "睦月周平", 1],
    [36, "名前、考えなきゃね", "睦月周平", 1],
    [37, "エンジン全開", "睦月周平", 1],
    [38, "普段からネコかぶってる", "睦月周平", 1],
    [39, "私も大人になりました", "睦月周平", 1],
    [40, "中央女子高文化祭", "睦月周平", 1],
    [41, "教育的指導します", "睦月周平", 1],
    [42, "お姉さまも個性的", "睦月周平", 1],
    [43, "豚由来", "睦月周平", 1],
    [44, "私がこの世に生誕した日", "睦月周平", 1],
    [45, "餅を食べる日", "睦月周平", 1],
    [46, "日ごろの感謝の気持ち", "睦月周平", 1],
    [47, "ありがとう", "睦月周平", 1],
    [48, "素敵なお友達が2人もできました", "睦月周平", 1],
]
links = ["https://beta.musicbrainz.org/release/55bdf43d-5b07-41e9-accb-8bcb35a7abc4", "https://vgmdb.net/album/58768"]
