[1d0454dcc9feb43bc483d25e3394318e]
catalognumber = "ESXX-02489"
date = "2021-06-02"
album = "PINK BLOOD / 宇多田ヒカル"
tracks = [
    [1, "PINK BLOOD", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/03ec67ed-cf21-4a80-8ad4-8bcd162b974f", "https://vgmdb.net/album/111364"]

[929b341a40aaa18fa3dd948317638842]
catalognumber = "ANZX-15352"
date = "2021-08-25"
album = "不滅のあなたへ オリジナルサウンドトラック 1"
tracks = [
    [1, "流転の記憶", "川﨑龍", 0],
    [2, "目醒め", "川﨑龍", 0],
    [3, "When I was young", "川﨑龍", 0],
    [4, "はじめの一歩", "川﨑龍", 0],
    [5, "炉端の糧", "川﨑龍", 0],
    [6, "わだち", "川﨑龍", 0],
    [7, "告別", "川﨑龍", 0],
    [8, "明け方の星", "川﨑龍", 0],
    [9, "川のある村", "川﨑龍", 0],
    [10, "fog", "川﨑龍", 0],
    [11, "沈黙の森", "川﨑龍", 0],
    [12, "オニグマ", "川﨑龍", 0],
    [13, "オオカミの踊り", "川﨑龍", 0],
    [14, "食べ物", "川﨑龍", 0],
    [15, "夢", "川﨑龍", 0],
    [16, "ヤノメの夜市", "川﨑龍", 0],
    [17, "Jailbreak", "川﨑龍", 0],
    [18, "突破", "川﨑龍", 0],
    [19, "大人しい少女", "川﨑龍", 0],
    [20, "secret valley", "川﨑龍", 0],
    [21, "死の宣告", "川﨑龍", 0],
    [22, "ノッカー I", "川﨑龍", 0],
    [23, "観察者の声", "川﨑龍", 0],
    [24, "一日の終わりに", "川﨑龍", 0],
    [25, "小さな幸せ", "川﨑龍", 0],
    [26, "一つの願い", "川﨑龍", 0],
]
links = ["https://beta.musicbrainz.org/release/09cc8475-17db-4e0f-aae1-efdfc8cb901e", "https://vgmdb.net/album/111107"]

[cd34991624a4af396985205eb7730d78]
catalognumber = "ANZX-15354"
date = "2021-10-27"
album = "不滅のあなたへ オリジナルサウンドトラック 2"
tracks = [
    [1, "Metamorphosis", "川﨑龍", 0],
    [2, "戦火の空", "川﨑龍", 0],
    [3, "少女の指輪", "川﨑龍", 0],
    [4, "怪物兄弟", "川﨑龍", 0],
    [5, "不滅の告白", "川﨑龍", 0],
    [6, "タクナハの屋台", "川﨑龍", 0],
    [7, "掃除・料理・畑仕事", "川﨑龍", 0],
    [8, "HERO", "川﨑龍", 0],
    [9, "鐘のなる時", "川﨑龍", 0],
    [10, "事故", "川﨑龍", 0],
    [11, "ノッカーII", "川﨑龍", 0],
    [12, "Mask", "川﨑龍", 0],
    [13, "無法の島", "川﨑龍", 0],
    [14, "出られない港", "川﨑龍", 0],
    [15, "Children's World", "川﨑龍", 0],
    [16, "rope", "川﨑龍", 0],
    [17, "目", "川﨑龍", 0],
    [18, "償い", "川﨑龍", 0],
    [19, "対峙", "川﨑龍", 0],
    [20, "Bastion", "川﨑龍", 0],
    [21, "痛み", "川﨑龍", 0],
    [22, "再会の日", "川﨑龍", 0],
    [23, "ことの終わり", "川﨑龍", 0],
    [24, "Mediator", "浜渦正志", 0],
]
links = ["https://beta.musicbrainz.org/release/996c4f82-55f9-4d0b-a2d5-c42d43771be8", "https://vgmdb.net/album/111108"]

[66e46f5f16f1a64d3eb56c339e9ab172]
catalognumber = "ESCL-5629"
date = "2022-02-23"
album = "BADモード / 宇多田ヒカル"
tracks = [
    [1, "BADモード", "宇多田ヒカル", 0],
    [2, "君に夢中", "宇多田ヒカル", 0],
    [3, "One Last Kiss", "宇多田ヒカル", 0],
    [4, "PINK BLOOD", "宇多田ヒカル", 0],
    [5, "Time", "宇多田ヒカル", 0],
    [6, "気分じゃないの (Not In The Mood)", "宇多田ヒカル", 0],
    [7, "誰にも言わない", "宇多田ヒカル", 0],
    [8, "Find Love", "宇多田ヒカル", 0],
    [9, "Face My Fears (Japanese Version)", "宇多田ヒカル & Skrillex", 0],
    [10, "Somewhere Near Marseilles ーマルセイユ辺りー", "宇多田ヒカル", 0],
    [11, "Beautiful World (Da Capo Version)", "宇多田ヒカル", 0],
    [12, "キレイな人 (Find Love)", "宇多田ヒカル", 0],
    [13, "Face My Fears (English Version)", "宇多田ヒカル & Skrillex", 0],
    [14, "Face My Fears (A.G. Cook Remix)", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/db9773a0-6bf7-4437-96d8-b2edd5b84795", "https://vgmdb.net/album/116669"]

[327a87cb19e288d370d18e79a3b76b8c]
catalognumber = "ESCL-5626~8"
date = "2022-02-23"
album = "BADモード / 宇多田ヒカル [初回生産限定盤] Vocal, Remix"
tracks = [
    [1, "BADモード", "宇多田ヒカル", 0],
    [2, "君に夢中", "宇多田ヒカル", 0],
    [3, "One Last Kiss", "宇多田ヒカル", 0],
    [4, "PINK BLOOD", "宇多田ヒカル", 0],
    [5, "Time", "宇多田ヒカル", 0],
    [6, "気分じゃないの (Not In The Mood)", "宇多田ヒカル", 0],
    [7, "誰にも言わない", "宇多田ヒカル", 0],
    [8, "Find Love", "宇多田ヒカル", 0],
    [9, "Face My Fears (Japanese Version)", "宇多田ヒカル & Skrillex", 0],
    [10, "Somewhere Near Marseilles ーマルセイユ辺りー", "宇多田ヒカル", 0],
    [11, "Beautiful World (Da Capo Version)", "宇多田ヒカル", 0],
    [12, "キレイな人 (Find Love)", "宇多田ヒカル", 0],
    [13, "Face My Fears (English Version)", "宇多田ヒカル & Skrillex", 0],
    [14, "Face My Fears (A.G. Cook Remix)", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/c67d329e-1626-41c3-8b16-22f08b76d9ae", "https://vgmdb.net/album/116670"]

[412c6496ea7f48f19191c98a1120c019]
catalognumber = "ESCL-5626~8"
date = "2022-02-23"
album = "BADモード / 宇多田ヒカル [初回生産限定盤] Vocal, Live Event, Video Disc 2"
tracks = [
    [1, "BADモード", "宇多田ヒカル", 0],
    [2, "One Last Kiss", "宇多田ヒカル", 0],
    [3, "君に夢中", "宇多田ヒカル", 0],
    [4, "誰にも言わない", "宇多田ヒカル", 0],
    [5, "Find Love", "宇多田ヒカル", 0],
    [6, "Time", "宇多田ヒカル", 0],
    [7, "PINK BLOOD", "宇多田ヒカル", 0],
    [8, "Face My Fears (English Version)", "宇多田ヒカル", 0],
    [9, "Hotel Lobby", "宇多田ヒカル", 0],
    [10, "Beautiful World (Da Capo Version)", "宇多田ヒカル", 0],
    [11, "About Me", "宇多田ヒカル", 0],
    [12, "Face My Fears (Japanese Version)", "宇多田ヒカル", 0],
    [13, "Behind the Scene “Live Sessions from Air Studios”", "宇多田ヒカル", 0],
    [14, "Time", "宇多田ヒカル", 0],
    [15, "One Last Kiss", "宇多田ヒカル", 0],
    [16, "PINK BLOOD", "宇多田ヒカル", 0],
    [17, "君に夢中", "宇多田ヒカル", 0],
    [18, "BADモード", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/c67d329e-1626-41c3-8b16-22f08b76d9ae", "https://vgmdb.net/album/116670"]

[61fd8c04ae27008a85b94129a88e2933]
catalognumber = "ESCL-5626~8"
date = "2022-02-23"
album = "BADモード / 宇多田ヒカル [初回生産限定盤] Vocal, Live Event, Video Disc 3"
tracks = [
    [1, "BADモード", "宇多田ヒカル", 0],
    [2, "One Last Kiss", "宇多田ヒカル", 0],
    [3, "君に夢中", "宇多田ヒカル", 0],
    [4, "誰にも言わない", "宇多田ヒカル", 0],
    [5, "Find Love", "宇多田ヒカル", 0],
    [6, "Time", "宇多田ヒカル", 0],
    [7, "PINK BLOOD", "宇多田ヒカル", 0],
    [8, "Face My Fears (English Version)", "宇多田ヒカル", 0],
    [9, "Hotel Lobby", "宇多田ヒカル", 0],
    [10, "Beautiful World (Da Capo Version)", "宇多田ヒカル", 0],
    [11, "About Me", "宇多田ヒカル", 0],
    [12, "Face My Fears (Japanese Version)", "宇多田ヒカル", 0],
    [13, "Behind the Scene “Live Sessions from Air Studios”", "宇多田ヒカル", 0],
    [14, "Time", "宇多田ヒカル", 0],
    [15, "One Last Kiss", "宇多田ヒカル", 0],
    [16, "PINK BLOOD", "宇多田ヒカル", 0],
    [17, "君に夢中", "宇多田ヒカル", 0],
    [18, "BADモード", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/c67d329e-1626-41c3-8b16-22f08b76d9ae", "https://vgmdb.net/album/116670"]

[170a0e7e6ac0940ae76cf933538aa0e0]
catalognumber = "ESJL-3123~4"
date = "2022-04-27"
album = "BADモード / 宇多田ヒカル [生産限定盤] Vocal"
tracks = [
    [1, "BADモード", "宇多田ヒカル", 0],
    [2, "君に夢中", "宇多田ヒカル", 0],
    [3, "One Last Kiss", "宇多田ヒカル", 0],
    [4, "PINK BLOOD", "宇多田ヒカル", 0],
    [5, "Time", "宇多田ヒカル", 0],
    [6, "気分じゃないの (Not In The Mood)", "宇多田ヒカル", 0],
    [7, "誰にも言わない", "宇多田ヒカル", 0],
    [8, "Find Love", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/f741fd8c-b670-45c9-876e-b88e8e0e5299", "https://vgmdb.net/album/117464"]

[cf982d8113930900e1004ebb1b5b39a5]
catalognumber = "ESJL-3123~4"
date = "2022-04-27"
album = "BADモード / 宇多田ヒカル [生産限定盤] Vocal, Remix"
tracks = [
    [1, "Face My Fears (Japanese Version)", "宇多田ヒカル & Skrillex", 0],
    [2, "Somewhere Near Marseilles -マルセイユ辺り-", "宇多田ヒカル", 0],
    [3, "Beautiful World (Da Capo Version)", "宇多田ヒカル", 0],
    [4, "キレイな人 (Find Love)", "宇多田ヒカル", 0],
    [5, "Face My Fears (English Version)", "宇多田ヒカル & Skrillex", 0],
    [6, "Face My Fears (A.G. Cook Remix)", "宇多田ヒカル", 0],
]
links = ["https://beta.musicbrainz.org/release/f741fd8c-b670-45c9-876e-b88e8e0e5299", "https://vgmdb.net/album/117464"]

[f5896027f7fc5e54a79610015bd16657]
catalognumber = "MNMK-015~6"
date = "2026-02-04"
album = "Pianoschlacht IV Live Recording Disc 1 [MNMK-015]"
tracks = [
    [1, "グアナフアト - SONY α CLOCK", "", 0],
    [2, "サンクトペテルブルク- SONY α CLOCK", "", 0],
    [3, "ギョレメ＆カッパドキア- SONY α CLOCK", "", 0],
    [4, "万里の長城 - SONY α CLOCK", "", 0],
    [5, "メンフィス - SONY α CLOCK", "", 0],
    [6, "Sanzui Ka 渦", "", 0],
    [7, "Sanzui En 淵", "", 0],
    [8, "Sanzui En ~ Extra part", "", 0],
    [9, "Sanzui Zen 漸", "", 0],
    [10, "Atmosphäre Op.1 No.1", "", 0],
    [11, "Atmosphäre Op.1 No.2", "", 0],
    [12, "Atmosphäre Op.1 No.3", "", 0],
    [13, "台風のノルダ No.1", "", 0],
    [14, "台風のノルダ No.2", "", 0],
    [15, "台風のノルダ No.3", "", 0],
    [16, "台風のノルダ No.4", "", 0],
    [17, "台風のノルダ No.5", "", 0],
    [18, "台風のノルダ No.6", "", 0],
    [19, "台風のノルダ No.7", "", 0],
    [20, "Giant - IMERUAT", "", 0],
]
links = ["https://vgmdb.net/album/156008"]

[ce38b4d0fe47aa2fc2ec3808ab60933a]
catalognumber = "MNMK-015~6"
date = "2026-02-04"
album = "Pianoschlacht IV Live Recording Disc 2 [MNMK-016]"
tracks = [
    [1, "緒＜てがかり＞", "", 0],
    [2, "モツ 華麗にジャンプ. - クラシカロイド", "", 0],
    [3, "平穏な日常 - クラシカロイド", "", 0],
    [4, "みなさん、ご無事で？ - クラシカロイド", "", 0],
    [5, "イントロダクション - ポレットのイス", "", 0],
    [6, "ポレットのイス - ポレットのイス", "", 0],
    [7, "10年の歳月 - ポレットのイス", "", 0],
    [8, "お引っ越し - ポレットのイス", "", 0],
    [9, "空飛ぶイス- ポレットのイス", "", 0],
    [10, "極北の民 - ファイナルファンタジーX", "", 0],
    [11, "襲撃 - ファイナルファンタジーX", "", 0],
    [12, "Feldschlacht V - サガ フロンティア２", "", 0],
    [13, "希望与えし「戌吠の神楽」 - シグマ・ハーモニクス", "", 0],
    [14, "Mediator ~ Roots - 不滅のあなたへ", "", 0],
    [15, "閃光 - ファイナルファンタジーXIII", "", 0],
    [16, "Mißgestalt - サガ フロンティア2", "", 0],
    [17, "ルフルール - IMERUAT", "", 0],
    [18, "LIFE CM - IMERUAT", "", 0],
]
links = ["https://vgmdb.net/album/156008"]
