[c2f7eb0de4bdb403f3da45ceb61702aa]
catalognumber = "COZP-1049~50"
date = "2015-05-05"
album = "未来系Answer / TRUSTRICK [Type A] Vocal, Live Event"
tracks = [
    [1, "未来形Answer", "TRUSTRICK", 0],
    [2, "highness", "TRUSTRICK", 0],
    [3, "as one (TRUST TOUR Version)", "TRUSTRICK", 0],
    [4, "FLYING FAFNIR (TRUST TOUR Version)", "TRUSTRICK", 0],
    [5, "未来形Answer (Instrumental)", "TRUSTRICK", 0],
    [6, "未来形Answer (Anime OP Version)", "TRUSTRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/d61abe78-46b7-47d2-8de7-aea1457e86df", "https://vgmdb.net/album/51898"]

[811bf6b8de005bd33266b659bb84eb53]
catalognumber = "COZP-1049~50"
date = "2015-05-05"
album = "未来系Answer / TRUSTRICK [Type A] Video"
tracks = [
    [1, "未来形Answer (Music Video)", "TRUSTRICK", 0],
    [2, "未来形Answer (Making Clip)", "TRUSTRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/d61abe78-46b7-47d2-8de7-aea1457e86df", "https://vgmdb.net/album/51898"]

[812a226da7b008687fb59a530ca7ca9c]
catalognumber = "COCP-39111"
date = "2015-05-05"
album = "未来系Answer / TRUSTRICK [Type B]"
tracks = [
    [1, "未来形Answer", "TRUSTRICK", 0],
    [2, "highness", "TRUSTRICK", 0],
    [3, "as one (TRUST TOUR Version)", "TRUSTRICK", 0],
    [4, "FLYING FAFNIR (TRUST TOUR Version)", "TRUSTRICK", 0],
    [5, "未来形Answer (Instrumental)", "TRUSTRICK", 0],
    [6, "未来形Answer (Anime OP Version)", "TRUSTRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/f9f85d9d-b3c7-49dd-bf25-cddeb8d07ed0", "https://vgmdb.net/album/51897"]

[f8a99ce490b23ba750efd71baf2c0a4a]
catalognumber = "VPCC-81844"
date = "2015-06-17"
album = "過去ツナグ未来 / LOCAL CONNECT"
tracks = [
    [1, "コスモループ", "LOCAL CONNECT", 0],
    [2, "ツギノセカイヘ", "LOCAL CONNECT", 0],
    [3, "Paradise Lost", "LOCAL CONNECT", 0],
    [4, "君の右手", "LOCAL CONNECT", 0],
    [5, "BLIND DAY", "LOCAL CONNECT", 0],
    [6, "幸せのありか", "LOCAL CONNECT", 0],
    [7, "フォルメイカー", "LOCAL CONNECT", 0],
]
links = ["https://beta.musicbrainz.org/release/7e46bc7a-7ef9-4741-9dc7-c69149340e18", "https://vgmdb.net/album/52199"]

[8e2937203237ae87ed43f33bbb871bb6]
catalognumber = "VPCG-83501"
date = "2015-07-22"
album = "アニメ「俺物語!!」オリジナル・サウンドトラック"
tracks = [
    [1, "未来形Answer (Anime OP Version)", "TRUSTRICK", 0],
    [2, "Fond Memories", "S.E.N.S. Project", 0],
    [3, "Dull", "S.E.N.S. Project", 0],
    [4, "散歩道", "S.E.N.S. Project", 0],
    [5, "男祭り", "S.E.N.S. Project", 0],
    [6, "俺の戦い", "S.E.N.S. Project", 0],
    [7, "Story of Mind 〜 Little Love", "S.E.N.S. Project", 0],
    [8, "長い影", "S.E.N.S. Project", 0],
    [9, "てんやわんや", "S.E.N.S. Project", 0],
    [10, "馬耳東風", "S.E.N.S. Project", 0],
    [11, "You made my day", "S.E.N.S. Project", 0],
    [12, "春の風", "S.E.N.S. Project", 0],
    [13, "わた雲", "S.E.N.S. Project", 0],
    [14, "Ramble", "S.E.N.S. Project", 0],
    [15, "猪突猛進", "S.E.N.S. Project", 0],
    [16, "Health First", "S.E.N.S. Project", 0],
    [17, "Sunlight", "S.E.N.S. Project", 0],
    [18, "気になるアイツ", "S.E.N.S. Project", 0],
    [19, "Clumsy", "S.E.N.S. Project", 0],
    [20, "ほっとひと息", "S.E.N.S. Project", 0],
    [21, "Chum", "S.E.N.S. Project", 0],
    [22, "Eye of the TAKEO", "S.E.N.S. Project", 0],
    [23, "Hurry up", "S.E.N.S. Project", 0],
    [24, "Scenery", "S.E.N.S. Project", 0],
    [25, "Star in the sky", "S.E.N.S. Project", 0],
    [26, "いつも隣で", "S.E.N.S. Project", 0],
    [27, "俺の頂上決戦", "S.E.N.S. Project", 0],
    [28, "小さな夢", "S.E.N.S. Project", 0],
    [29, "Story of Mind", "S.E.N.S. Project", 0],
    [30, "幸せのありか (Anime ED Version)", "LOCAL CONNECT", 0],
]
links = ["https://beta.musicbrainz.org/release/126d62b3-7ec0-4058-b3e3-6cc57d950724", "https://vgmdb.net/album/52906"]

[42aef5ebf7c2e4e1f9d53a2fa5d04833]
catalognumber = "COCP-39753"
date = "2016-10-26"
album = "TRICK / TRUSTRICK [TYPE B]"
tracks = [
    [1, "TRICK", "TRUSTRICK feat. chelly (EGOIST)", 0],
    [2, "Recall THE END", "TRUSTRICK", 0],
    [3, "I wish you were here.", "TRUSTRICK", 0],
    [4, "blur blur", "TRUSTRICK", 0],
    [5, "pixie", "TRUSTRICK", 0],
    [6, "mint gum (sugarless version)", "TRUSTRICK", 0],
    [7, "LOVELESS", "TRUSTRICK", 0],
    [8, "星の無い夜", "TRUSTRICK", 0],
    [9, "beloved", "TRUSTRICK", 0],
    [10, "寂しさの宙から", "TRUSTRICK", 0],
    [11, "innocent promise", "TRUSTRICK", 0],
    [12, "Honey Complex", "TRUSTRICK", 0],
    [13, "未来形Answer", "TRUSTRICK", 0],
    [14, "So long", "TRUSTRICK", 0],
    [15, "Proud", "TRUSTRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/0888ea30-1c90-4a6e-b7b6-85b0defa78a1", "https://vgmdb.net/album/65453"]

[9cdd6a068436b119b97ff3b667aac654]
catalognumber = "COZP-1258~9"
date = "2016-10-26"
album = "TRICK / TRUSTRICK [TYPE A] Vocal"
tracks = [
    [1, "TRICK", "TRUSTRICK feat. chelly (EGOIST)", 0],
    [2, "Recall THE END", "TRUSTRICK", 0],
    [3, "I wish you were here.", "TRUSTRICK", 0],
    [4, "blur blur", "TRUSTRICK", 0],
    [5, "pixie", "TRUSTRICK", 0],
    [6, "mint gum (sugarless version)", "TRUSTRICK", 0],
    [7, "LOVELESS", "TRUSTRICK", 0],
    [8, "星の無い夜", "TRUSTRICK", 0],
    [9, "beloved", "TRUSTRICK", 0],
    [10, "寂しさの宙から", "TRUSTRICK", 0],
    [11, "innocent promise", "TRUSTRICK", 0],
    [12, "Honey Complex", "TRUSTRICK", 0],
    [13, "未来形Answer", "TRUSTRICK", 0],
    [14, "So long", "TRUSTRICK", 0],
    [15, "Proud", "TRUSTRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/76538859-6bb7-4ab6-944c-58764cda2a83", "https://vgmdb.net/album/65452"]

[305a9c470f5d0b5dc8a491d27986e851]
catalognumber = "COZP-1258~9"
date = "2016-10-26"
album = "TRICK / TRUSTRICK [TYPE A] Video"
tracks = [
    [1, "I wish you were here. (Music Video)", "TRUSTRICK", 0],
    [2, "blur blur (Music Video)", "TRUSTRICK", 0],
    [3, "TRICK Jacket Making Clip", "TRUSTRICK", 0],
    [4, "I wish you were here. (Making Clip)", "TRUSTRICK", 0],
    [5, "blur blur (Making Clip)", "TRUSTRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/76538859-6bb7-4ab6-944c-58764cda2a83", "https://vgmdb.net/album/65452"]
