[128a9e98bf15ce745c9e42ff7e5780c5]
catalognumber = "ZMCZ-7463"
date = "2011-10-26"
album = "残念系隣人部★★☆(星二つ半) / 友達つくり隊"
tracks = [
    [1, "残念系隣人部★★☆（星ふたつ半）", "友達つくり隊", 0],
    [2, "笑顔のデッサン", "三日月夜空(CV:井上麻里奈)＆柏崎星奈(CV:伊藤かな恵)", 0],
    [3, "残念系隣人部★★☆（星ふたつ半） (off vocal)", "友達つくり隊", 0],
    [4, "笑顔のデッサン (off vocal)", "三日月夜空(CV:井上麻里奈)＆柏崎星奈(CV:伊藤かな恵)", 0],
]
links = ["https://beta.musicbrainz.org/release/b6d88de4-1424-4227-b9d6-8c7bb5062682", "https://vgmdb.net/album/28183"]

[12f4a0b804b3c06512a81859a6cedae6]
catalognumber = "ZMCZ-7464"
date = "2011-11-25"
album = "私のキ・モ・チ / 三日月夜空 (CV: 井上麻里奈)"
tracks = [
    [1, "私のキ・モ・チ", "三日月夜空(CV:井上麻里奈)", 0],
    [2, "あたしのキ・モ・チ", "柏崎星奈(CV:伊藤かな恵)", 0],
    [3, "私のキ・モ・チ (off vocal)", "三日月夜空(CV:井上麻里奈)", 0],
    [4, "あたしのキ・モ・チ (off vocal)", "柏崎星奈(CV:伊藤かな恵)", 0],
]
links = ["https://beta.musicbrainz.org/release/aaf41821-3552-4c16-8ba0-e39316fcdc53", "https://vgmdb.net/album/28182"]

[d530395fd640f9f055fd18cbb1833c26]
catalognumber = "ZMCZ-7465"
date = "2011-12-21"
album = "僕は友達が少ない オリジナルサウンドトラック"
tracks = [
    [1, "隣人部かつどう中", "Tom-H@ck", 0],
    [2, "隣人部きゅうけい中", "Tom-H@ck", 0],
    [3, "隣人部こんらん中", "Tom-H@ck", 0],
    [4, "だめだこいつ はやくなんとかしないと", "Tom-H@ck", 0],
    [5, "女狐VS肉", "Tom-H@ck", 0],
    [6, "理科×夜空", "Tom-H@ck", 0],
    [7, "変態乳牛", "Tom-H@ck", 0],
    [8, "あぁ〜ん", "Tom-H@ck", 0],
    [9, "何か裏があるですね", "Tom-H@ck", 0],
    [10, "結局こんな感じになりました", "Tom-H@ck", 0],
    [11, "ふぁんきーあこーすてっく", "Tom-H@ck", 0],
    [12, "ゲーム「モンスター狩人」より Final Battle", "Tom-H@ck", 0],
    [13, "ゲーム「モンスター狩人」より Stage", "Tom-H@ck", 0],
    [14, "のんびーり", "Tom-H@ck", 0],
    [15, "おもちゃっぽいファンキー", "Tom-H@ck", 0],
    [16, "映画なはがない", "Tom-H@ck", 0],
    [17, "リア充の気分", "Tom-H@ck", 0],
    [18, "くらしっくピアノな感じ", "Tom-H@ck", 0],
    [19, "野生の変拍子", "Tom-H@ck", 0],
    [20, "小鷹はトモちゃんが見えない", "Tom-H@ck", 0],
    [21, "うれしはずかし", "Tom-H@ck", 0],
    [22, "ゆにばぁぁあああ〜〜〜〜〜す!!!!", "Tom-H@ck", 0],
    [23, "リア充の妄想", "Tom-H@ck", 0],
    [24, "あいきゃっちその1", "Tom-H@ck", 0],
    [25, "あいきゃっちその2", "Tom-H@ck", 0],
    [26, "はがないバック", "Tom-H@ck", 0],
    [27, "聖クロニカ学園", "Tom-H@ck", 0],
    [28, "うんこ幼女シスター", "Tom-H@ck", 0],
    [29, "おどろおどろ", "Tom-H@ck", 0],
    [30, "小鷹VS不良", "Tom-H@ck", 0],
    [31, "俺は不良なんかじゃない", "Tom-H@ck", 0],
    [32, "エロゲの朗読", "Tom-H@ck", 0],
    [33, "隣人部しっと中", "Tom-H@ck", 0],
    [34, "純粋なる恋心", "Tom-H@ck", 0],
    [35, "小鷹は気がつかない、けど", "Tom-H@ck", 0],
    [36, "私のキ・モ・チ (TVサイズ)", "三日月夜空(CV:井上麻里奈)", 0],
    [37, "残念系隣人部★★☆ (TVサイズ)", "友達つくり隊", 0],
]
links = ["https://beta.musicbrainz.org/release/092d54e6-61ca-4bdd-a569-c08d4c3faebd", "https://vgmdb.net/album/28160"]

[18dd729ce37597070bcabf7a1874af96]
catalognumber = "TGCS-6899"
date = "2012-01-13"
album = "僕は友達が少ない あそーとCD1"
tracks = [
    [1, "「（笑）」その 1", "友達つくり隊", 0],
    [2, "「（笑）」その 2", "友達つくり隊", 0],
    [3, "「（笑）」その 3", "友達つくり隊", 0],
    [4, "「（笑）」その 4", "友達つくり隊", 0],
    [5, "Pureness Shyness", "三日月夜空(CV:井上麻里奈)", 0],
    [6, "Pureness Shyness (インストゥルメンタル)", "三日月夜空(CV:井上麻里奈)", 0],
]
links = ["https://beta.musicbrainz.org/release/12e3fdec-e561-49a6-b9e3-9aec57073219", "https://vgmdb.net/album/59779"]

[63604137fd5732694a7f5a9cc9574b42]
catalognumber = "TGCS-6901"
date = "2012-02-22"
album = "僕は友達が少ない あそーとCD2"
tracks = [
    [1, "「夏休みのしくだい」その 1", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [2, "「夏休みのしくだい」その 2", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [3, "「夏休みのしくだい」その 3", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [4, "「夏休みのしくだい」その 4", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [5, "「夏休みのしくだい」その 5", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [6, "「夏休みのしくだい」その 6", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [7, "「夏休みのしくだい」その 7", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [8, "「夏休みのしくだい」その 8", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 0],
    [9, "欲張り My Soul", "柏崎星奈(CV:伊藤かな恵)", 0],
    [10, "欲張り My Soul (インストゥルメンタル)", "柏崎星奈(CV:伊藤かな恵)", 0],
]
links = ["https://beta.musicbrainz.org/release/15381fa1-ff64-450c-bc08-9de65238466f", "https://vgmdb.net/album/59781"]

[8f1de34ff13eb62438246dc890570e73]
catalognumber = "TGCS-6903"
date = "2012-03-21"
album = "僕は友達が少ない あそーとCD3"
tracks = [
    [1, "OPENING", "伊藤賢治", 0],
    [2, "FIELD", "伊藤賢治", 0],
    [3, "BATTLE", "伊藤賢治", 0],
    [4, "BOSS BATTLE", "伊藤賢治", 0],
    [5, "DEAD", "伊藤賢治", 0],
    [6, "GAME OVER", "伊藤賢治", 0],
    [7, "強き心に花よ咲け", "楠幸村(CV:山本希望)", 0],
    [8, "強き心に花よ咲け (インストゥルメンタル)", "楠幸村(CV:山本希望)", 0],
]
links = ["https://beta.musicbrainz.org/release/3cfd4993-c5f9-4ee9-861e-e49949ff3df0", "https://vgmdb.net/album/59783"]

[0de5c8744c8821ab050113a2097d09f4]
catalognumber = "QWCE-00226"
date = "2012-04-04"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 15"
tracks = [
    [1, "残念系隣人部★★☆（星ふたつ半）", "Ryu* feat.mi-mi+R.Cena", 0],
    [2, "空想メソロギヰ", "kinoto feat.R.Cena", 0],
    [3, "BLOOD TELLER", "Hommarju feat.mamiko", 0],
    [4, "ROCK OVER JAPAN", "Hommarju feat.si-na+R.Cena", 0],
    [5, "HIGH POWERED", "Dizzi Mystica feat.mi-mi+JJ", 0],
    [6, "私のキ・モ・チ", "Booing Day feat.Latte", 0],
    [7, "少年よ我に帰れ", "MK feat.405", 0],
    [8, "君の神話〜アクエリオン第二章", "Dizzi Mystica feat.R.Cena", 0],
    [9, "TERMINATED", "Dizzi Mystica feat.YURiE", 0],
    [10, "FLY AWAY", "Icon feat.puchi", 0],
    [11, "YOUTHFUL", "Icon feat.TAKANORI", 0],
    [12, "I'LL BELIEVE", "Dizzi Mystica feat.KANA+TAKANORI", 0],
    [13, "SKY'S THE LIMIT", "Dizzi Mystica feat.YURiE+MFMW", 0],
    [14, "COOLISH WALK", "Dizzi Mystica feat.mi-mi+R.Cena", 0],
    [15, "U-N-D-E-R--STANDING!", "Icon feat.puchi+TAKANORI", 0],
    [16, "紋", "Booing Day feat.yumemi", 0],
    [17, "君の中の英雄", "MK feat.KANA", 0],
    [18, "おかえりなさい", "MK feat.Nahoko", 0],
    [19, "ENDLESS STORY", "Dizzi Mystica feat.Latte", 0],
    [20, "ノルニル", "Hommarju feat.405", 0],
]
links = ["https://beta.musicbrainz.org/release/2b80d131-81ee-4e02-b169-87d60b75f2ab", "https://vgmdb.net/album/32343"]

[048b730474c7a3b0973f6a9eecb89dee]
catalognumber = "TGCS-6905"
date = "2012-04-25"
album = "僕は友達が少ない あそーとCD4"
tracks = [
    [1, "FLOWER", "羽瀬川小鷹(CV:木村良平)", 0],
    [2, "二人の季節", "三日月夜空(CV:井上麻里奈)", 0],
    [3, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [4, "天才妄想科学論", "志熊理科(CV:福圓美里)", 0],
    [5, "FLOWER (インストゥルメンタル)", "羽瀬川小鷹(CV:木村良平)", 0],
    [6, "二人の季節 (インストゥルメンタル)", "三日月夜空(CV:井上麻里奈)", 0],
    [7, "ゆけゆけゲルニカちゃん! (インストゥルメンタル)", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [8, "天才妄想科学論 (インストゥルメンタル)", "志熊理科(CV:福圓美里)", 0],
]
links = ["https://beta.musicbrainz.org/release/73727824-7fda-4ac1-8127-e78d28c232f0", "https://vgmdb.net/album/59790"]

[6b0a61280353be8694a3c408a5d292ce]
catalognumber = "TGCS-6907"
date = "2012-05-23"
album = "僕は友達が少ない あそーとCD5"
tracks = [
    [1, "二人の季節", "柏崎星奈(CV:伊藤かな恵)", 0],
    [2, "漢の生きる道", "楠幸村(CV:山本希望)", 0],
    [3, "SHOCK YOUR EYES", "志熊理科(CV:福圓美里)", 0],
    [4, "いきなり! モンスタア☆", "高山マリア(CV:井口裕香)", 0],
    [5, "不機嫌＊吸血鬼", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [6, "二人の季節 (インストゥルメンタル)", "柏崎星奈(CV:伊藤かな恵)", 0],
    [7, "漢の生きる道 (インストゥルメンタル)", "楠幸村(CV:山本希望)", 0],
    [8, "SHOCK YOUR EYES (インストゥルメンタル)", "志熊理科(CV:福圓美里)", 0],
    [9, "いきなり! モンスタア☆ (インストゥルメンタル)", "高山マリア(CV:井口裕香)", 0],
    [10, "不機嫌＊吸血鬼 (インストゥルメンタル)", "羽瀬川小鳩(CV:花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/8048b666-b756-4ba6-bee1-2b90813728fb", "https://vgmdb.net/album/59794"]

[6de26219569f68fdd055a3b1b93cc030]
catalognumber = "ZMCZ-8039"
date = "2012-08-29"
album = "小鳩のうたってみた! / 羽瀬川小鳩（CV：花澤香菜）"
tracks = [
    [1, "誓願ノ詩~聖者の傷跡~", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [2, "戦けよ、冥闇の王は降りた", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [3, "誓願ノ詩~聖者の傷跡~ (off vocal)", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [4, "戦けよ、冥闇の王は降りた (off vocal)", "羽瀬川小鳩(CV:花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/b220e60c-2a54-4a62-af45-6a0b2d0c708e", "https://vgmdb.net/album/59798"]

[22100db1b1089a6c5776b9bf39c85291]
catalognumber = "TGCS-6909"
date = "2012-08-29"
album = "僕は友達が少ない あそーとCD6"
tracks = [
    [1, "Over the Distance", "三日月夜空(CV:井上麻里奈)", 0],
    [2, "Over the Distance", "柏崎星奈(CV:伊藤かな恵)", 0],
    [3, "Over the Distance", "楠幸村(CV:山本希望)", 0],
    [4, "Over the Distance", "志熊理科(CV:福圓美里)", 0],
    [5, "Over the Distance", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [6, "Over the Distance", "高山マリア(CV:井口裕香)", 0],
    [7, "はじまりの日はいつも", "藤林あかり(CV:川澄綾子)", 0],
    [8, "Hello, Happy Sunday!!", "高山マリア(CV:井口裕香)", 0],
    [9, "Over the Distance (インストゥルメンタル)", "yamazo", 0],
    [10, "はじまりの日はいつも (インストゥルメンタル)", "藤林あかり(CV:川澄綾子)", 0],
    [11, "Hello, Happy Sunday!! (インストゥルメンタル)", "高山マリア(CV:井口裕香)", 0],
]
links = ["https://beta.musicbrainz.org/release/d663f96a-3a48-403f-a8ed-dd3daf42201e", "https://vgmdb.net/album/59795"]

[683511cf1b6bf29f4bb4750a3a881147]
catalognumber = "ZMCZ-8372"
date = "2013-02-06"
album = "僕らの翼 / 隣人部"
tracks = [
    [1, "僕らの翼", "隣人部", 0],
    [2, "思い出シュノーケル", "羽瀬川小鷹(CV:木村良平)", 0],
    [3, "僕らの翼 (オリジナルカラオケ)", "隣人部", 0],
    [4, "思い出シュノーケル (オリジナルカラオケ)", "羽瀬川小鷹(CV:木村良平)", 0],
]
links = ["https://beta.musicbrainz.org/release/a2629b0e-f75c-411a-9688-0ffe5c6b9ea8", "https://vgmdb.net/album/36266"]

[10eb1954e12ca69486485cbe8b150934]
catalognumber = "ZMCZ-8371"
date = "2013-02-06"
album = "Be My Friend / 隣人部"
tracks = [
    [1, "Be My Friend", "隣人部", 0],
    [2, "ぶいえす!!らいばる!!", "羽瀬川小鳩(CV:花澤香菜) & 高山マリア(CV:井口裕香)", 0],
    [3, "Be My Friend (オリジナルカラオケ)", "隣人部", 0],
    [4, "ぶいえす!!らいばる!! (オリジナルカラオケ)", "羽瀬川小鳩(CV:花澤香菜) & 高山マリア(CV:井口裕香)", 0],
]
links = ["https://beta.musicbrainz.org/release/9c4c17a0-ce31-4357-8b56-f99d12998de4", "https://vgmdb.net/album/36265"]

[5804b3eec1c17cd68d28be536469228a]
catalognumber = "ZMCZ-8373"
date = "2013-03-27"
album = "TVアニメ『僕は友達が少ないNEXT』オリジナルサウンドトラック"
tracks = [
    [1, "はじまりはじまり", "Tom-H@ck", 0],
    [2, "隣人部かつどう中 NEXT", "Tom-H@ck", 0],
    [3, "日常は流れゆく", "Tom-H@ck", 0],
    [4, "おや?おやおや?", "Tom-H@ck", 0],
    [5, "とても変なおねーちゃん", "Tom-H@ck", 0],
    [6, "まさか!?", "Tom-H@ck", 0],
    [7, "やれやれブルース", "Tom-H@ck", 0],
    [8, "私、怒ってます", "Tom-H@ck", 0],
    [9, "煮え切らないです", "Tom-H@ck", 0],
    [10, "美しく晴れ晴れ", "Tom-H@ck", 0],
    [11, "本気の真っすぐな想い", "Tom-H@ck", 0],
    [12, "悲しみと哀しみ", "Tom-H@ck", 0],
    [13, "深く深く…", "Tom-H@ck", 0],
    [14, "はがないバック NEXT", "Tom-H@ck", 0],
    [15, "あいきゃっちその 1 NEXT", "Tom-H@ck", 0],
    [16, "あいきゃっちその 2 NEXT", "Tom-H@ck", 0],
    [17, "えへえへ恥ずかし", "Tom-H@ck", 0],
    [18, "ダンディー?セクシー?", "Tom-H@ck", 0],
    [19, "たたっぽきゃっ", "Tom-H@ck", 0],
    [20, "キャワイイキャワイイ", "Tom-H@ck", 0],
    [21, "おもちゃでおこちゃま", "Tom-H@ck", 0],
    [22, "はがないじゃむ", "Tom-H@ck", 0],
    [23, "慌てろ～!!!", "Tom-H@ck", 0],
    [24, "天才で変態で妄想でゆにばーす", "Tom-H@ck", 0],
    [25, "ごりごり", "Tom-H@ck", 0],
    [26, "決心", "Tom-H@ck", 0],
    [27, "めでたしめでたし", "Tom-H@ck", 0],
    [28, "隣人部は続く…", "Tom-H@ck", 0],
    [29, "Be My Friend (TV Ver.)", "隣人部", 0],
    [30, "僕らの翼 (TV Ver.)", "隣人部", 0],
]
links = ["https://beta.musicbrainz.org/release/3f7a8613-89ef-45fa-8ae0-95a19d0259ea", "https://vgmdb.net/album/36264"]

[5d9ed997eca384a2e91283df628488d2]
catalognumber = "TGCS-7433"
date = "2013-03-27"
album = "僕は友達が少ないNEXT ねくすとCD 1: 録り下ろしキャラクターソング & OP･ED feat. 柏崎星奈"
tracks = [
    [1, "Staring Stars", "柏崎星奈(CV:伊藤かな恵)", 0],
    [2, "Be My Friend -星奈Featuring隣人部 VER-", "柏崎星奈(CV:伊藤かな恵) Featuring 隣人部", 0],
    [3, "僕らの翼 -星奈Featuring隣人部 VER-", "柏崎星奈(CV:伊藤かな恵) Featuring 隣人部", 0],
]
links = ["https://beta.musicbrainz.org/release/56dbed7a-2dac-4049-811a-5c29d54a1f0c", "https://vgmdb.net/album/150750"]

[65d5c32162838e0b759c724002e02ebd]
catalognumber = "QWCE-00277"
date = "2013-05-01"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 18"
tracks = [
    [1, "シアワセ☆ハイテンション↑↑", "Booing Day feat.maburu-choko+慧", 0],
    [2, "BREAK YOUR WORLD", "Flash back Dominant feat.Latte", 0],
    [3, "桜流し", "Disco da gama feat.MFMW", 0],
    [4, "ジョジョ〜その血の運命〜", "MK feat.徹", 0],
    [5, "LOVELY FRUIT", "MK feat.yumemi", 0],
    [6, "PRECIOUS", "Booing Day feat.慧+yumemi", 0],
    [7, "START:DASH!!", "Disco da gama feat.さつき+si-na", 0],
    [8, "RANTIKI", "plazma feat.YURiE", 0],
    [9, "ドキドキドク", "Icon feat.YURiE", 0],
    [10, "PRIME NUMBER 〜君と出会える日〜", "Flash back Dominant feat.puchi", 0],
    [11, "僕らの翼", "Hommarju feat.Natsuhi+si-na", 0],
    [12, "夢の続き", "Disco da gama feat.R.Cena", 0],
    [13, "GIRLISH LOVER", "MK feat.SAYURI+maburu-choko", 0],
    [14, "急接近ラッキーDAYS", "Booing Day feat.SAYURI+mai", 0],
    [15, "W:WONDER TALE", "Disco da gama feat.maburu-choko", 0],
    [16, "BLACK † WHITE", "Hommarju feat.mi-mi", 0],
    [17, "僕らは今のなかで", "Hommarju feat.SAYURI+さつき", 0],
    [18, "REVERSI", "Hommarju feat.hideki+Ryo", 0],
    [19, "GOD FATE", "Icon feat.yumemi", 0],
]
links = ["https://beta.musicbrainz.org/release/7bc6ce60-b3dc-4e21-83ff-91ab2c60b0cb", "https://vgmdb.net/album/39180"]

[0b142af8b34ba90d93bb0dd57fcf6994]
catalognumber = "ZMCZ-8797"
date = "2013-08-28"
album = "僕は友達が少ない 隣人部ボーカルコレクション"
tracks = [
    [1, "残念系隣人部★★☆", "友達つくり隊", 0],
    [2, "Pureness Shyness", "三日月夜空(CV:井上麻里奈)", 0],
    [3, "欲張り My Soul", "柏崎星奈(CV:伊藤かな恵)", 0],
    [4, "強き心に花よ咲け", "楠幸村(CV:山本希望)", 0],
    [5, "天才妄想科学論", "志熊理科(CV:福圓美里)", 0],
    [6, "二人の季節 (三日月夜空 ver.)", "三日月夜空(CV:井上麻里奈)", 0],
    [7, "FLOWER", "羽瀬川小鷹(CV:木村良平)", 0],
    [8, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [9, "笑顔のデッサン", "三日月夜空(CV:井上麻里奈)＆柏崎星奈(CV:伊藤かな恵)", 0],
    [10, "私のキ・モ・チ", "三日月夜空(CV:井上麻里奈)", 0],
    [11, "不機嫌*吸血鬼", "羽瀬川小鳩(CV:花澤香菜)", 0],
    [12, "Hello, Happy Sunday!!", "高山マリア(CV:井口裕香)", 0],
    [13, "二人の季節 (柏崎星奈 ver.)", "柏崎星奈(CV:伊藤かな恵)", 0],
    [14, "SHOCK YOUR EYES", "志熊理科(CV:福圓美里)", 0],
    [15, "漢の生きる道", "楠幸村(CV:山本希望)", 0],
    [16, "いきなり! モンスタア☆", "高山マリア(CV:井口裕香)", 0],
    [17, "あたしのキ・モ・チ", "柏崎星奈(CV:伊藤かな恵)", 0],
    [18, "Over the Distance (New Mix ver.)", "三日月夜空(CV:井上麻里奈、柏崎星奈(CV:伊藤かな恵)、楠幸村(CV:山本希望)、志熊理科(CV:福圓美里)、羽瀬川小鳩(CV:花澤香菜)、高山マリア(CV:井口裕香)", 0],
    [19, "君は友達", "羽瀬川小鷹(CV:木村良平、三日月夜空(CV:井上麻里奈)、柏崎星奈(CV:伊藤かな恵)、楠幸村(CV:山本希望)、志熊理科(CV:福圓美里)、羽瀬川小鳩(CV:花澤香菜)、高山マリア(CV:井口裕香)", 0],
]
links = ["https://beta.musicbrainz.org/release/78b85185-e488-4c36-984e-5cecb95d88d7", "https://vgmdb.net/album/39427"]

[d5bc4ecd3c21ec3c48d81350a28c4614]
catalognumber = "SVWC-70189~90"
date = "2016-08-30"
album = "KANAight ～花澤香菜キャラソン ハイパークロニクルミックス～ Disc 1 [SVWC-70189]"
tracks = [
    [1, "恋愛サーキュレーション -Yunomi \"Kawaii EDM\" Remix-", "", 0],
    [2, "リカバーデコレーション -Hymn to the Queen Remix-", "", 0],
    [3, "Delicateにラブ・ミー・プリーズ -More Delicate Remix-", "", 0],
    [4, "モノクロ☆HAPPY DAY -Small Chic Dance Remix-", "", 0],
    [5, "おしえてナウカ、夢みるペチカ -cozy analog Remix-", "", 0],
    [6, "もうそう♡えくすぷれす -folclore Remix-", "", 0],
    [7, "sweets parade -lyrical Remix-", "", 0],
]
links = ["https://vgmdb.net/album/65499"]

[fd92fa87d095df18162d5ed12cfe1ae1]
catalognumber = "SVWC-70189~90"
date = "2016-08-30"
album = "KANAight ～花澤香菜キャラソン ハイパークロニクルミックス～ Disc 2 [SVWC-70190]"
tracks = [
    [1, "恋するマドモアゼル", "シャルロット・デュノア(花澤香菜)", 0],
    [2, "I wonder why…", "向井戸まなか(花澤香菜)", 0],
    [3, "シナプスの鏡", "邪神かがみ(花澤香菜)", 0],
    [4, "みどりのメロディ", "草野(花澤香菜)", 0],
    [5, "Raison d'etre", "汐宮栞(花澤香菜)", 0],
    [6, "Delicateにラブ・ミー・プリーズ", "ざんげちゃん(花澤香菜)", 0],
    [7, "ソレイユ・ブーケ", "シャルロット・デュノア(花澤香菜)", 0],
    [8, "モノクロ☆HAPPY DAY", "黒猫(花澤香菜)", 0],
    [9, "キミをマモリタイ", "市ヶ谷りか(花澤香菜)", 0],
    [10, "ヘンな神様知ってるよ", "乱崎優歌(花澤香菜)", 0],
    [11, "Qunka!", "板東まりも(花澤香菜)", 0],
    [12, "HEAVEN's TALE", "ベンヤ(花澤香菜)", 0],
    [13, "バンブー・ランデヴー♡", "メイメイ(花澤香菜)", 0],
    [14, "迷惑スペクタクル", "横井るみ(花澤香菜)", 0],
    [15, "まじかる☆まーじゃん☆わーるど (ver.玄)", "松実玄(花澤香菜)", 0],
    [16, "Punctuation!", "松隆奈々子(花澤香菜)", 0],
    [17, "自主恋Shoooooter!", "湊智花(花澤香菜)", 0],
    [18, "君色*コンプリート", "双葉アオイ(花澤香菜)", 0],
    [19, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(花澤香菜)", 0],
    [20, "Dazzling Smile", "マリー(花澤香菜)", 0],
    [21, "ハッピーガール☆ラッキーガール!", "桜市子(花澤香菜)", 0],
    [22, "ダンジョン ショコラティエース", "シロ(花澤香菜)", 0],
    [23, "おにくじゃぽねすく!", "ゼウシくん(花澤香菜)", 0],
    [24, "プリコグ (M@STER VERSION)", "水谷絵理(花澤香菜)", 0],
    [25, "みのりのぞっこん未来予報♡", "中沢農(花澤香菜)", 0],
    [26, "君らしくなきゃヤダよ!", "結城美柑(花澤香菜)", 0],
    [27, "私がモテないのは可愛くないからだよね?", "ゆうちゃん(花澤香菜)", 0],
    [28, "心の窓辺にて", "双葉アオイ(花澤香菜)", 0],
    [29, "もうそう♡えくすぷれす", "千石撫子(花澤香菜)", 0],
    [30, "sweets parade", "髏々宮カルタ(花澤香菜)", 0],
    [31, "リカバーデコレーション", "小野寺小咲(花澤香菜)", 0],
    [32, "スプーンひとさじの愛", "宮野まゆ(花澤香菜)", 0],
    [33, "恋愛サーキュレーション", "千石撫子(花澤香菜)", 0],
    [34, "あした来る日〜桜咲くころ", "花戸小鳩(花澤香菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/af9b0033-666b-42e6-be05-cb4280729814", "https://vgmdb.net/album/65499"]

[398f0cca9beafcb0b5927142282cea11]
catalognumber = "TGCS-10191"
date = "2017-10-18"
album = "はがないせれくと"
tracks = [
    [1, "残念系隣人部★★☆(星二つ半)", "友達つくり隊", 0],
    [2, "私のキ.モ.チ", "三日月夜空", 0],
    [3, "Pureness Shyness", "三日月夜空", 0],
    [4, "欲張りMy Soul", "柏崎星奈", 0],
    [5, "強き心に花よ咲け", "楠幸村", 0],
    [6, "天才妄想科学論", "志熊理科", 0],
    [7, "不機嫌*吸血鬼(ヴァンパイア)", "友達つくり隊", 0],
    [8, "Hello, Happy Sunday!!", "高山マリア", 0],
    [9, "君は友達", "友達つくり隊", 0],
    [10, "誓願ノ詩～聖者の傷跡～", "友達つくり隊", 0],
    [11, "戦けよ、冥闇の王は降りた", "友達つくり隊", 0],
    [12, "Be My Friend", "友達つくり隊", 0],
    [13, "僕らの翼", "友達つくり隊", 0],
    [14, "Staring Stars", "柏崎星奈", 0],
    [15, "送信履歴", "三日月夜空", 0],
    [16, "FANTASISTA", "楠幸村", 0],
    [17, "PASTEL B☆X", "友達つくり隊", 0],
    [18, "ブレス", "高山マリア", 0],
    [19, "君と僕", "志熊理科", 0],
]
links = ["https://beta.musicbrainz.org/release/b06ce354-ffc6-4f6b-aede-74db5eb785ae", "https://vgmdb.net/album/69890"]
