[128a9e98bf15ce745c9e42ff7e5780c5]
catalognumber = "ZMCZ-7463"
date = "2011-10-26"
album = "残念系隣人部★★☆(星二つ半) / 友達つくり隊"
tracks = [
    [1, "残念系隣人部★★☆（星ふたつ半）", "友達つくり隊", 1],
    [2, "笑顔のデッサン", "三日月夜空(CV:井上麻里奈)＆柏崎星奈(CV:伊藤かな恵)", 1],
    [3, "残念系隣人部★★☆（星ふたつ半） (off vocal)", "友達つくり隊", 1],
    [4, "笑顔のデッサン (off vocal)", "三日月夜空(CV:井上麻里奈)＆柏崎星奈(CV:伊藤かな恵)", 1],
]
links = ["https://beta.musicbrainz.org/release/b6d88de4-1424-4227-b9d6-8c7bb5062682", "https://vgmdb.net/album/28183"]

[12f4a0b804b3c06512a81859a6cedae6]
catalognumber = "ZMCZ-7464"
date = "2011-11-25"
album = "私のキ・モ・チ / 三日月夜空 (CV: 井上麻里奈)"
tracks = [
    [1, "私のキ・モ・チ", "三日月夜空(CV:井上麻里奈)", 1],
    [2, "あたしのキ・モ・チ", "柏崎星奈(CV:伊藤かな恵)", 1],
    [3, "私のキ・モ・チ (off vocal)", "三日月夜空(CV:井上麻里奈)", 1],
    [4, "あたしのキ・モ・チ (off vocal)", "柏崎星奈(CV:伊藤かな恵)", 1],
]
links = ["https://beta.musicbrainz.org/release/aaf41821-3552-4c16-8ba0-e39316fcdc53", "https://vgmdb.net/album/28182"]

[d530395fd640f9f055fd18cbb1833c26]
catalognumber = "ZMCZ-7465"
date = "2011-12-21"
album = "僕は友達が少ない オリジナルサウンドトラック"
tracks = [
    [1, "隣人部かつどう中", "Tom-H@ck", 1],
    [2, "隣人部きゅうけい中", "Tom-H@ck", 1],
    [3, "隣人部こんらん中", "Tom-H@ck", 1],
    [4, "だめだこいつ はやくなんとかしないと", "Tom-H@ck", 1],
    [5, "女狐VS肉", "Tom-H@ck", 1],
    [6, "理科×夜空", "Tom-H@ck", 1],
    [7, "変態乳牛", "Tom-H@ck", 1],
    [8, "あぁ〜ん", "Tom-H@ck", 1],
    [9, "何か裏があるですね", "Tom-H@ck", 1],
    [10, "結局こんな感じになりました", "Tom-H@ck", 1],
    [11, "ふぁんきーあこーすてっく", "Tom-H@ck", 1],
    [12, "ゲーム「モンスター狩人」より Final Battle", "Tom-H@ck", 1],
    [13, "ゲーム「モンスター狩人」より Stage", "Tom-H@ck", 1],
    [14, "のんびーり", "Tom-H@ck", 1],
    [15, "おもちゃっぽいファンキー", "Tom-H@ck", 1],
    [16, "映画なはがない", "Tom-H@ck", 1],
    [17, "リア充の気分", "Tom-H@ck", 1],
    [18, "くらしっくピアノな感じ", "Tom-H@ck", 1],
    [19, "野生の変拍子", "Tom-H@ck", 1],
    [20, "小鷹はトモちゃんが見えない", "Tom-H@ck", 1],
    [21, "うれしはずかし", "Tom-H@ck", 1],
    [22, "ゆにばぁぁあああ〜〜〜〜〜す!!!!", "Tom-H@ck", 1],
    [23, "リア充の妄想", "Tom-H@ck", 1],
    [24, "あいきゃっちその1", "Tom-H@ck", 1],
    [25, "あいきゃっちその2", "Tom-H@ck", 1],
    [26, "はがないバック", "Tom-H@ck", 1],
    [27, "聖クロニカ学園", "Tom-H@ck", 1],
    [28, "うんこ幼女シスター", "Tom-H@ck", 1],
    [29, "おどろおどろ", "Tom-H@ck", 1],
    [30, "小鷹VS不良", "Tom-H@ck", 1],
    [31, "俺は不良なんかじゃない", "Tom-H@ck", 1],
    [32, "エロゲの朗読", "Tom-H@ck", 1],
    [33, "隣人部しっと中", "Tom-H@ck", 1],
    [34, "純粋なる恋心", "Tom-H@ck", 1],
    [35, "小鷹は気がつかない、けど", "Tom-H@ck", 1],
    [36, "私のキ・モ・チ (TVサイズ)", "三日月夜空(CV:井上麻里奈)", 1],
    [37, "残念系隣人部★★☆ (TVサイズ)", "友達つくり隊", 1],
]
links = ["https://beta.musicbrainz.org/release/092d54e6-61ca-4bdd-a569-c08d4c3faebd", "https://vgmdb.net/album/28160"]

[18dd729ce37597070bcabf7a1874af96]
catalognumber = "TGCS-6899"
date = "2012-01-13"
album = "僕は友達が少ない あそーとCD1"
tracks = [
    [1, "「（笑）」その 1", "友達つくり隊", 1],
    [2, "「（笑）」その 2", "友達つくり隊", 1],
    [3, "「（笑）」その 3", "友達つくり隊", 1],
    [4, "「（笑）」その 4", "友達つくり隊", 1],
    [5, "Pureness Shyness", "三日月夜空(CV:井上麻里奈)", 1],
    [6, "Pureness Shyness (インストゥルメンタル)", "三日月夜空(CV:井上麻里奈)", 1],
]
links = ["https://beta.musicbrainz.org/release/12e3fdec-e561-49a6-b9e3-9aec57073219", "https://vgmdb.net/album/59779"]

[63604137fd5732694a7f5a9cc9574b42]
catalognumber = "TGCS-6901"
date = "2012-02-22"
album = "僕は友達が少ない あそーとCD2"
tracks = [
    [1, "「夏休みのしくだい」その 1", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [2, "「夏休みのしくだい」その 2", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [3, "「夏休みのしくだい」その 3", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [4, "「夏休みのしくだい」その 4", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [5, "「夏休みのしくだい」その 5", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [6, "「夏休みのしくだい」その 6", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [7, "「夏休みのしくだい」その 7", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [8, "「夏休みのしくだい」その 8", "木村良平, 井上麻里奈, 伊藤かな恵, 山本希望, 福圓美里, 花澤香菜 & 井口裕香", 1],
    [9, "欲張り My Soul", "柏崎星奈(CV:伊藤かな恵)", 1],
    [10, "欲張り My Soul (インストゥルメンタル)", "柏崎星奈(CV:伊藤かな恵)", 1],
]
links = ["https://beta.musicbrainz.org/release/15381fa1-ff64-450c-bc08-9de65238466f", "https://vgmdb.net/album/59781"]

[8f1de34ff13eb62438246dc890570e73]
catalognumber = "TGCS-6903"
date = "2012-03-21"
album = "僕は友達が少ない あそーとCD3"
tracks = [
    [1, "OPENING", "伊藤賢治", 1],
    [2, "FIELD", "伊藤賢治", 1],
    [3, "BATTLE", "伊藤賢治", 1],
    [4, "BOSS BATTLE", "伊藤賢治", 1],
    [5, "DEAD", "伊藤賢治", 1],
    [6, "GAME OVER", "伊藤賢治", 1],
    [7, "強き心に花よ咲け", "楠幸村(CV:山本希望)", 1],
    [8, "強き心に花よ咲け (インストゥルメンタル)", "楠幸村(CV:山本希望)", 1],
]
links = ["https://beta.musicbrainz.org/release/3cfd4993-c5f9-4ee9-861e-e49949ff3df0", "https://vgmdb.net/album/59783"]

[048b730474c7a3b0973f6a9eecb89dee]
catalognumber = "TGCS-6905"
date = "2012-04-25"
album = "僕は友達が少ない あそーとCD4"
tracks = [
    [1, "FLOWER", "羽瀬川小鷹(CV:木村良平)", 1],
    [2, "二人の季節", "三日月夜空(CV:井上麻里奈)", 1],
    [3, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [4, "天才妄想科学論", "志熊理科(CV:福圓美里)", 1],
    [5, "FLOWER (インストゥルメンタル)", "羽瀬川小鷹(CV:木村良平)", 1],
    [6, "二人の季節 (インストゥルメンタル)", "三日月夜空(CV:井上麻里奈)", 1],
    [7, "ゆけゆけゲルニカちゃん! (インストゥルメンタル)", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [8, "天才妄想科学論 (インストゥルメンタル)", "志熊理科(CV:福圓美里)", 1],
]
links = ["https://beta.musicbrainz.org/release/73727824-7fda-4ac1-8127-e78d28c232f0", "https://vgmdb.net/album/59790"]

[6b0a61280353be8694a3c408a5d292ce]
catalognumber = "TGCS-6907"
date = "2012-05-23"
album = "僕は友達が少ない あそーとCD5"
tracks = [
    [1, "二人の季節", "柏崎星奈(CV:伊藤かな恵)", 1],
    [2, "漢の生きる道", "楠幸村(CV:山本希望)", 1],
    [3, "SHOCK YOUR EYES", "志熊理科(CV:福圓美里)", 1],
    [4, "いきなり! モンスタア☆", "高山マリア(CV:井口裕香)", 1],
    [5, "不機嫌＊吸血鬼", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [6, "二人の季節 (インストゥルメンタル)", "柏崎星奈(CV:伊藤かな恵)", 1],
    [7, "漢の生きる道 (インストゥルメンタル)", "楠幸村(CV:山本希望)", 1],
    [8, "SHOCK YOUR EYES (インストゥルメンタル)", "志熊理科(CV:福圓美里)", 1],
    [9, "いきなり! モンスタア☆ (インストゥルメンタル)", "高山マリア(CV:井口裕香)", 1],
    [10, "不機嫌＊吸血鬼 (インストゥルメンタル)", "羽瀬川小鳩(CV:花澤香菜)", 1],
]
links = ["https://beta.musicbrainz.org/release/8048b666-b756-4ba6-bee1-2b90813728fb", "https://vgmdb.net/album/59794"]

[6de26219569f68fdd055a3b1b93cc030]
catalognumber = "ZMCZ-8039"
date = "2012-08-29"
album = "小鳩のうたってみた! / 羽瀬川小鳩（CV：花澤香菜）"
tracks = [
    [1, "誓願ノ詩~聖者の傷跡~", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [2, "戦けよ、冥闇の王は降りた", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [3, "誓願ノ詩~聖者の傷跡~ (off vocal)", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [4, "戦けよ、冥闇の王は降りた (off vocal)", "羽瀬川小鳩(CV:花澤香菜)", 1],
]
links = ["https://beta.musicbrainz.org/release/b220e60c-2a54-4a62-af45-6a0b2d0c708e", "https://vgmdb.net/album/59798"]

[22100db1b1089a6c5776b9bf39c85291]
catalognumber = "TGCS-6909"
date = "2012-08-29"
album = "僕は友達が少ない あそーとCD6"
tracks = [
    [1, "Over the Distance", "三日月夜空(CV:井上麻里奈)", 1],
    [2, "Over the Distance", "柏崎星奈(CV:伊藤かな恵)", 1],
    [3, "Over the Distance", "楠幸村(CV:山本希望)", 1],
    [4, "Over the Distance", "志熊理科(CV:福圓美里)", 1],
    [5, "Over the Distance", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [6, "Over the Distance", "高山マリア(CV:井口裕香)", 1],
    [7, "はじまりの日はいつも", "藤林あかり(CV:川澄綾子)", 1],
    [8, "Hello, Happy Sunday!!", "高山マリア(CV:井口裕香)", 1],
    [9, "Over the Distance (インストゥルメンタル)", "yamazo", 1],
    [10, "はじまりの日はいつも (インストゥルメンタル)", "藤林あかり(CV:川澄綾子)", 1],
    [11, "Hello, Happy Sunday!! (インストゥルメンタル)", "高山マリア(CV:井口裕香)", 1],
]
links = ["https://beta.musicbrainz.org/release/d663f96a-3a48-403f-a8ed-dd3daf42201e", "https://vgmdb.net/album/59795"]

[3e3ba886f77b0a4571d4249cdc702cb2]
catalognumber = "TGCS-7157"
date = "2012-09-26"
album = "君は友達"
tracks = [
    [1, "君は友達", "隣人部一同", 1],
    [2, "君は友達 (インストゥルメンタル)", "隣人部一同", 1],
    [3, "君は友達 (ショートサイズ)", "隣人部一同", 1],
]
links = ["https://beta.musicbrainz.org/release/f3b20365-721a-45c3-80b9-15d959e6e900"]

[683511cf1b6bf29f4bb4750a3a881147]
catalognumber = "ZMCZ-8372"
date = "2013-02-06"
album = "僕らの翼 / 隣人部"
tracks = [
    [1, "僕らの翼", "隣人部", 2],
    [2, "思い出シュノーケル", "羽瀬川小鷹(CV:木村良平)", 1],
    [3, "僕らの翼 (オリジナルカラオケ)", "隣人部", 1],
    [4, "思い出シュノーケル (オリジナルカラオケ)", "羽瀬川小鷹(CV:木村良平)", 1],
]
links = ["https://beta.musicbrainz.org/release/a2629b0e-f75c-411a-9688-0ffe5c6b9ea8", "https://vgmdb.net/album/36266"]

[10eb1954e12ca69486485cbe8b150934]
catalognumber = "ZMCZ-8371"
date = "2013-02-06"
album = "Be My Friend / 隣人部"
tracks = [
    [1, "Be My Friend", "隣人部", 1],
    [2, "ぶいえす!!らいばる!!", "羽瀬川小鳩(CV:花澤香菜) & 高山マリア(CV:井口裕香)", 1],
    [3, "Be My Friend (オリジナルカラオケ)", "隣人部", 1],
    [4, "ぶいえす!!らいばる!! (オリジナルカラオケ)", "羽瀬川小鳩(CV:花澤香菜) & 高山マリア(CV:井口裕香)", 1],
]
links = ["https://beta.musicbrainz.org/release/9c4c17a0-ce31-4357-8b56-f99d12998de4", "https://vgmdb.net/album/36265"]

[5804b3eec1c17cd68d28be536469228a]
catalognumber = "ZMCZ-8373"
date = "2013-03-27"
album = "TVアニメ『僕は友達が少ないNEXT』オリジナルサウンドトラック"
tracks = [
    [1, "はじまりはじまり", "Tom-H@ck", 1],
    [2, "隣人部かつどう中 NEXT", "Tom-H@ck", 1],
    [3, "日常は流れゆく", "Tom-H@ck", 1],
    [4, "おや?おやおや?", "Tom-H@ck", 1],
    [5, "とても変なおねーちゃん", "Tom-H@ck", 1],
    [6, "まさか!?", "Tom-H@ck", 1],
    [7, "やれやれブルース", "Tom-H@ck", 1],
    [8, "私、怒ってます", "Tom-H@ck", 1],
    [9, "煮え切らないです", "Tom-H@ck", 1],
    [10, "美しく晴れ晴れ", "Tom-H@ck", 1],
    [11, "本気の真っすぐな想い", "Tom-H@ck", 1],
    [12, "悲しみと哀しみ", "Tom-H@ck", 1],
    [13, "深く深く…", "Tom-H@ck", 1],
    [14, "はがないバック NEXT", "Tom-H@ck", 1],
    [15, "あいきゃっちその 1 NEXT", "Tom-H@ck", 1],
    [16, "あいきゃっちその 2 NEXT", "Tom-H@ck", 1],
    [17, "えへえへ恥ずかし", "Tom-H@ck", 1],
    [18, "ダンディー?セクシー?", "Tom-H@ck", 1],
    [19, "たたっぽきゃっ", "Tom-H@ck", 1],
    [20, "キャワイイキャワイイ", "Tom-H@ck", 1],
    [21, "おもちゃでおこちゃま", "Tom-H@ck", 1],
    [22, "はがないじゃむ", "Tom-H@ck", 1],
    [23, "慌てろ～!!!", "Tom-H@ck", 1],
    [24, "天才で変態で妄想でゆにばーす", "Tom-H@ck", 1],
    [25, "ごりごり", "Tom-H@ck", 1],
    [26, "決心", "Tom-H@ck", 1],
    [27, "めでたしめでたし", "Tom-H@ck", 1],
    [28, "隣人部は続く…", "Tom-H@ck", 1],
    [29, "Be My Friend (TV Ver.)", "隣人部", 1],
    [30, "僕らの翼 (TV Ver.)", "隣人部", 1],
]
links = ["https://beta.musicbrainz.org/release/3f7a8613-89ef-45fa-8ae0-95a19d0259ea", "https://vgmdb.net/album/36264"]

[5d9ed997eca384a2e91283df628488d2]
catalognumber = "TGCS-7433"
date = "2013-03-27"
album = "僕は友達が少ないNEXT ねくすとCD 1: 録り下ろしキャラクターソング & OP･ED feat. 柏崎星奈"
tracks = [
    [1, "Staring Stars", "柏崎星奈(CV:伊藤かな恵)", 1],
    [2, "Be My Friend -星奈Featuring隣人部 VER-", "柏崎星奈(CV:伊藤かな恵) Featuring 隣人部", 1],
    [3, "僕らの翼 -星奈Featuring隣人部 VER-", "柏崎星奈(CV:伊藤かな恵) Featuring 隣人部", 1],
]
links = ["https://beta.musicbrainz.org/release/56dbed7a-2dac-4049-811a-5c29d54a1f0c", "https://vgmdb.net/album/150750"]

[2c59698be840c74ee92f1ccb7ed0c41b]
catalognumber = "ZMXZ-8392"
date = "2013-04-24"
album = "僕は友達が少ないNEXT ねくすとCD 2"
tracks = [
    [1, "送信履歴", "三日月夜空(CV:井上麻里奈)", 1],
    [2, "Be My Friend -夜空Featuring隣人部 VER-", "三日月夜空(CV:井上麻里奈) Featuring 隣人部", 1],
    [3, "僕らの翼 -夜空Featuring隣人部 VER-", "三日月夜空(CV:井上麻里奈) Featuring 隣人部", 1],
]
links = ["https://beta.musicbrainz.org/release/4cc417e9-08c6-4d0c-9ae3-3b0afbf01e99"]

[0b142af8b34ba90d93bb0dd57fcf6994]
catalognumber = "ZMCZ-8797"
date = "2013-08-28"
album = "僕は友達が少ない 隣人部ボーカルコレクション"
tracks = [
    [1, "残念系隣人部★★☆", "友達つくり隊", 1],
    [2, "Pureness Shyness", "三日月夜空(CV:井上麻里奈)", 1],
    [3, "欲張り My Soul", "柏崎星奈(CV:伊藤かな恵)", 1],
    [4, "強き心に花よ咲け", "楠幸村(CV:山本希望)", 1],
    [5, "天才妄想科学論", "志熊理科(CV:福圓美里)", 1],
    [6, "二人の季節 (三日月夜空 ver.)", "三日月夜空(CV:井上麻里奈)", 1],
    [7, "FLOWER", "羽瀬川小鷹(CV:木村良平)", 1],
    [8, "ゆけゆけゲルニカちゃん!", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [9, "笑顔のデッサン", "三日月夜空(CV:井上麻里奈)＆柏崎星奈(CV:伊藤かな恵)", 1],
    [10, "私のキ・モ・チ", "三日月夜空(CV:井上麻里奈)", 1],
    [11, "不機嫌*吸血鬼", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [12, "Hello, Happy Sunday!!", "高山マリア(CV:井口裕香)", 1],
    [13, "二人の季節 (柏崎星奈 ver.)", "柏崎星奈(CV:伊藤かな恵)", 1],
    [14, "SHOCK YOUR EYES", "志熊理科(CV:福圓美里)", 1],
    [15, "漢の生きる道", "楠幸村(CV:山本希望)", 1],
    [16, "いきなり! モンスタア☆", "高山マリア(CV:井口裕香)", 1],
    [17, "あたしのキ・モ・チ", "柏崎星奈(CV:伊藤かな恵)", 1],
    [18, "Over the Distance (New Mix ver.)", "三日月夜空(CV:井上麻里奈、柏崎星奈(CV:伊藤かな恵)、楠幸村(CV:山本希望)、志熊理科(CV:福圓美里)、羽瀬川小鳩(CV:花澤香菜)、高山マリア(CV:井口裕香)", 1],
    [19, "君は友達", "羽瀬川小鷹(CV:木村良平、三日月夜空(CV:井上麻里奈)、柏崎星奈(CV:伊藤かな恵)、楠幸村(CV:山本希望)、志熊理科(CV:福圓美里)、羽瀬川小鳩(CV:花澤香菜)、高山マリア(CV:井口裕香)", 1],
]
links = ["https://beta.musicbrainz.org/release/78b85185-e488-4c36-984e-5cecb95d88d7", "https://vgmdb.net/album/39427"]

[74768f00ddb8a3d0cffae49a8f099ae3]
catalognumber = "ZMXZ-8393"
date = "2013-09-25"
album = "僕は友達が少ないNEXT ねくすとCD 3"
tracks = [
    [1, "FANTASISTA", "楠幸村(CV:山本希望)", 1],
    [2, "Be My Friend -幸村Featuring隣人部 VER-", "楠幸村(CV:山本希望) Featuring 隣人部", 1],
    [3, "僕らの翼 -幸村Featuring隣人部 VER-", "楠幸村(CV:山本希望) Featuring 隣人部", 1],
]
links = ["https://beta.musicbrainz.org/release/d6a20385-c88f-485a-b9f1-4a7c8189162f"]

[f2051d57d79d5b7682ee012df3c156b4]
catalognumber = "ZMXZ-8394"
date = "2013-10-30"
album = "僕は友達が少ないNEXT ねくすとCD 4"
tracks = [
    [1, "PASTEL B☆X", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [2, "Be My Friend -小鳩Featuring隣人部 VER-", "羽瀬川小鳩(CV:花澤香菜)", 1],
    [3, "僕らの翼 -小鳩Featuring隣人部 VER-", "羽瀬川小鳩(CV:花澤香菜)", 1],
]
links = ["https://beta.musicbrainz.org/release/037c33d6-1d45-4e2f-b0a4-21d6aab46a90"]

[47e0ad7e26034af72269ee9e1d5e103c]
catalognumber = "ZMXZ-8395"
date = "2013-11-27"
album = "僕は友達が少ないNEXT ねくすとCD 5"
tracks = [
    [1, "ブレス", "高山マリア(CV:井口裕香)", 1],
    [2, "Be My Friend -マリアFeaturing隣人部 VER-", "高山マリア(CV:井口裕香) Featuring 隣人部", 1],
    [3, "僕らの翼 -マリアFeaturing隣人部 VER-", "高山マリア(CV:井口裕香) Featuring 隣人部", 1],
]
links = ["https://beta.musicbrainz.org/release/db8fda2b-a679-4c72-a629-4a14c5837a5a"]

[7c73b0a68108c6bdc96870ba705aa1e7]
catalognumber = "ZMXZ-8396"
date = "2013-12-25"
album = "僕は友達が少ないNEXT ねくすとCD 6"
tracks = [
    [1, "君と僕", "志熊理科(CV:福圓美里)", 1],
    [2, "Be My Friend -理科Featuring隣人部 VER-", "志熊理科(CV:福圓美里) Featuring 隣人部", 1],
    [3, "僕らの翼 -理科Featuring隣人部 VER-", "志熊理科(CV:福圓美里) Featuring 隣人部", 1],
]
links = ["https://beta.musicbrainz.org/release/f730c457-ec6d-4be6-a9d9-f8eeaf0081d6"]

[398f0cca9beafcb0b5927142282cea11]
catalognumber = "TGCS-10191"
date = "2017-10-18"
album = "はがないせれくと"
tracks = [
    [1, "残念系隣人部★★☆(星二つ半)", "友達つくり隊", 1],
    [2, "私のキ.モ.チ", "三日月夜空", 1],
    [3, "Pureness Shyness", "三日月夜空", 1],
    [4, "欲張りMy Soul", "柏崎星奈", 1],
    [5, "強き心に花よ咲け", "楠幸村", 1],
    [6, "天才妄想科学論", "志熊理科", 1],
    [7, "不機嫌*吸血鬼(ヴァンパイア)", "友達つくり隊", 1],
    [8, "Hello, Happy Sunday!!", "高山マリア", 1],
    [9, "君は友達", "友達つくり隊", 1],
    [10, "誓願ノ詩～聖者の傷跡～", "友達つくり隊", 1],
    [11, "戦けよ、冥闇の王は降りた", "友達つくり隊", 1],
    [12, "Be My Friend", "友達つくり隊", 1],
    [13, "僕らの翼", "友達つくり隊", 1],
    [14, "Staring Stars", "柏崎星奈", 1],
    [15, "送信履歴", "三日月夜空", 1],
    [16, "FANTASISTA", "楠幸村", 1],
    [17, "PASTEL B☆X", "友達つくり隊", 1],
    [18, "ブレス", "高山マリア", 1],
    [19, "君と僕", "志熊理科", 1],
]
links = ["https://beta.musicbrainz.org/release/b06ce354-ffc6-4f6b-aede-74db5eb785ae", "https://vgmdb.net/album/69890"]
