[c9e35944bd60d3c7736adf44d9075303]
catalognumber = "LACM-14623"
date = "2017-07-26"
album = "羽ばたきのバースデイ / Baby's breath"
tracks = [
    [1, "羽ばたきのバースデイ", "Baby's breath", 0],
    [2, "BLUE TEARS", "Baby's breath", 0],
    [3, "羽ばたきのバースデイ (instrumental)", "Baby's breath", 0],
    [4, "BLUE TEARS (instrumental)", "Baby's breath", 0],
]
links = ["https://beta.musicbrainz.org/release/42a58596-bee1-494c-9550-b6258da7eac3", "https://vgmdb.net/album/68189"]

[c94afb1a9c193c1a0ad3ed5eff58ca89]
catalognumber = "LACM-14651"
date = "2017-08-23"
album = "楔 / Baby's breath"
tracks = [
    [1, "楔", "Baby's breath", 0],
    [2, "Baby's place", "Baby's breath", 0],
    [3, "楔 -instrumental-", "Baby's breath", 0],
    [4, "Baby's place -instrumental-", "Baby's breath", 0],
]
links = ["https://beta.musicbrainz.org/release/5c6f9fe2-c1d5-4218-aede-d61ea21d878a", "https://vgmdb.net/album/69018"]

[39214dc4aece0ec723ed27be43c480e4]
catalognumber = "LACA-15683"
date = "2017-09-27"
album = "TVアニメ『天使の3P!』Three Angels Complete Album♪"
tracks = [
    [1, "深海プリズナー", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [2, "モノクローム果樹園", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [3, "HOWLING", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [4, "大切がきこえる", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [5, "INNOCENT BLUE", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [6, "ファーストテイク", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [7, "深海プリズナー ボーカルソフトアレンジ", "ボーカルソフト音声(CV:小倉唯)", 0],
    [8, "大切がきこえる ボーカルソフトアレンジ", "ボーカルソフト音声(CV:小倉唯)", 0],
    [9, "大切がきこえる 双龍島アレンジ", "五島潤(CV:大野柚布子)、紅葉谷希美(CV:遠藤ゆりか)、金城そら(CV:古賀葵)", 0],
    [10, "大切がきこえる ピアノアレンジ", "相ヶ江柚葉(CV:井口裕香)", 0],
    [11, "INNOCENT BLUE ボーカルソフトアレンジ", "ボーカルソフト音声(CV:小倉唯)", 0],
]
links = ["https://beta.musicbrainz.org/release/7f9f071e-14a2-455a-b1c4-2ef49908be37", "https://vgmdb.net/album/69401"]

[9122022f3cde667ba8246b4c4edc773b]
catalognumber = "HMCH-2069"
date = "2017-10-03"
album = "天使の3P! スペシャルCD 1"
tracks = [
    [1, "STAND UP!", "", 0],
    [2, "STAND UP! (Instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/69165"]

[0b3e0a086c040b220077a11bf8ae06c8]
catalognumber = "LACA-9546~7"
date = "2017-10-11"
album = "TVアニメ『天使の3P!』オリジナルサウンドトラック Sound Of Three Angels♪ Original Soundtrack, Vocal"
tracks = [
    [1, "ねぇ、いいの? あれ", "松田彬人", 0],
    [2, "キュアポリス", "松田彬人", 0],
    [3, "じゃんけん", "松田彬人", 0],
    [4, "へんたいせきにんよ", "松田彬人", 0],
    [5, "なにごとでござるか", "松田彬人", 0],
    [6, "きゃんぷ", "松田彬人", 0],
    [7, "よびすてでいいわよ", "松田彬人", 0],
    [8, "せんとうかいしとまいりますか", "松田彬人", 0],
    [9, "ゆびがつかれちゃった", "松田彬人", 0],
    [10, "いっしょにねると?", "松田彬人", 0],
    [11, "さわってもいいわよ", "松田彬人", 0],
    [12, "に・い・さ・ん", "松田彬人", 0],
    [13, "あいてしてあげようとおもったのに", "松田彬人", 0],
    [14, "みんなおちついて", "松田彬人", 0],
    [15, "すてんどぐらす", "松田彬人", 0],
    [16, "がんばれ、ぼく", "松田彬人", 0],
    [17, "はなしがあうはずない", "松田彬人", 0],
    [18, "イギリスにいく", "松田彬人", 0],
    [19, "ていあんがあるんだ", "松田彬人", 0],
    [20, "ライブがしたい", "松田彬人", 0],
    [21, "またあしたがんばろう", "松田彬人", 0],
    [22, "またここにきてたんだ", "松田彬人", 0],
    [23, "ゆうえんち", "松田彬人", 0],
    [24, "あのころから", "松田彬人", 0],
    [25, "いいところだね", "松田彬人", 0],
    [26, "おてつだいをさせてもらおうかな", "松田彬人", 0],
    [27, "そうりゅうじま", "松田彬人", 0],
    [28, "しりょふんべつ", "松田彬人", 0],
    [29, "まだよ、まだはやいわ", "松田彬人", 0],
    [30, "でも、ちょっとさみしそうかも", "松田彬人", 0],
    [31, "おんがえし", "松田彬人", 0],
    [32, "ぽえまぁ", "松田彬人", 0],
    [33, "うたいたいんです", "松田彬人", 0],
    [34, "どんなけっかになっても", "松田彬人", 0],
    [35, "ほんとうのきもち", "松田彬人", 0],
    [36, "わたしのことだけみてればいいんだから", "松田彬人", 0],
    [37, "とくべつ", "松田彬人", 0],
    [38, "せかいはこんなにすてきだよって", "松田彬人", 0],
    [39, "ごめんねひびき", "松田彬人", 0],
    [40, "つまんないの", "松田彬人", 0],
    [41, "おふろたいむ", "松田彬人", 0],
    [42, "すりーえんじぇるす①", "松田彬人", 0],
    [43, "すりーえんじぇるす②", "松田彬人", 0],
    [44, "すりーえんじぇるす③", "松田彬人", 0],
    [45, "すりーえんじぇるす④", "松田彬人", 0],
    [46, "羽ばたきのバースデイ TVsize", "Baby's breath", 0],
    [47, "楔 TVsize", "Baby's breath", 0],
]
links = ["https://beta.musicbrainz.org/release/a29c23e4-77f2-4a08-997b-834b7d17f5dc", "https://vgmdb.net/album/69585"]

[b5772f4f832d251ec9a68f00eb3531e8]
catalognumber = "LACA-9546~7"
date = "2017-10-11"
album = "TVアニメ『天使の3P!』オリジナルサウンドトラック Sound Of Three Angels♪ Vocal"
tracks = [
    [1, "深海プリズナー 潤ソロアレンジ", "五島潤", 0],
    [2, "深海プリズナー 希美ソロアレンジ", "紅葉谷希美", 0],
    [3, "深海プリズナー そらソロアレンジ", "金城そら", 0],
    [4, "モノクローム果樹園 潤ソロアレンジ", "五島潤", 0],
    [5, "モノクローム果樹園 希美ソロアレンジ", "紅葉谷希美", 0],
    [6, "モノクローム果樹園 そらソロアレンジ", "金城そら", 0],
    [7, "HOWLING 潤ソロアレンジ", "五島潤", 0],
    [8, "HOWLING 希美ソロアレンジ", "紅葉谷希美", 0],
    [9, "HOWLING そらソロアレンジ", "金城そら", 0],
    [10, "大切がきこえる 潤ソロアレンジ", "五島潤", 0],
    [11, "大切がきこえる 希美ソロアレンジ", "紅葉谷希美", 0],
    [12, "大切がきこえる そらソロアレンジ", "金城そら", 0],
    [13, "INNOCENT BLUE 潤ソロアレンジ", "五島潤", 0],
    [14, "INNOCENT BLUE 希美ソロアレンジ", "紅葉谷希美", 0],
    [15, "INNOCENT BLUE そらソロアレンジ", "金城そら", 0],
    [16, "ファーストテイク 潤ソロアレンジ", "五島潤", 0],
    [17, "ファーストテイク 希美ソロアレンジ", "紅葉谷希美", 0],
    [18, "ファーストテイク そらソロアレンジ", "金城そら", 0],
]
links = ["https://beta.musicbrainz.org/release/a29c23e4-77f2-4a08-997b-834b7d17f5dc", "https://vgmdb.net/album/69585"]

[6108b0735028f87554764964ddd99057]
catalognumber = "HMCH-2070"
date = "2017-11-02"
album = "天使の3P! スペシャルCD 2"
tracks = [
    [1, "LOVER SOUL", "", 0],
    [2, "LOVER SOUL (instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/69166"]

[9c99b43509a8c5ca2241c1a7daa6a39d]
catalognumber = "HMCH-2071"
date = "2017-12-02"
album = "天使の3P! スペシャルCD 3"
tracks = [
    [1, "Believe In...Myself", "", 0],
    [2, "Believe In...Myself (Instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/69167"]

[1f6c155dec9e667101c4b8c6694e163f]
catalognumber = "HMCH-2072"
date = "2018-01-06"
album = "天使の3P! スペシャルドラマCD"
tracks = [
    [1, "デートにイカれて", "", 0],
]
links = ["https://vgmdb.net/album/69168"]

[a6e18e0d87647ca44d334df2cfe45cd5]
catalognumber = "LACZ-10001"
date = "2018-05-04"
album = "Brand new Stage / Baby's breath"
tracks = [
    [1, "Brand new Stage", "", 0],
    [2, "Hail to reason", "", 0],
    [3, "大野柚布子 オーディオコメント", "", 0],
    [4, "遠藤ゆりか オーディオコメント", "", 0],
    [5, "古賀葵 オーディオコメント", "", 0],
    [6, "Brand new Stage (Instrumental)", "", 0],
    [7, "Hail to reason (Instrumental)", "", 0],
]
links = ["https://vgmdb.net/album/79381"]
