[9c1811a95d72875eb77ce54489f097ce]
catalognumber = "PCCG-01939"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里 [初回限定盤] Vocal"
tracks = [
    [1, "キミのとなりで", "鬼頭明里", 0],
    [2, "Dive to World", "鬼頭明里", 0],
    [3, "トウメイナユメ", "鬼頭明里", 0],
    [4, "キミのとなりで (Instrumental)", "鬼頭明里", 0],
    [5, "Dive to World (Instrumental)", "鬼頭明里", 0],
    [6, "トウメイナユメ (Instrumental)", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/102687", "https://beta.musicbrainz.org/release/66620588-0f96-4092-98f9-91e97b21d7bc"]

[67da65e02c116f0e95393e2c819f801c]
catalognumber = "PCCG-01939"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里 [初回限定盤] Vocal, Video"
tracks = [
    [1, "「キミのとなりで」MUSIC VIDEO", "鬼頭明里", 0],
    [2, "「キミのとなりで」ジャケット・MV撮影 MAKING", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/102687", "https://beta.musicbrainz.org/release/66620588-0f96-4092-98f9-91e97b21d7bc"]

[d0a0f06829c3620507ff5e8e3117159c]
catalognumber = "PCCG-01929"
date = "2020-10-28"
album = "君に会えた日 / 安達としまむら (CV: 鬼頭明里と伊藤美来)"
tracks = [
    [1, "君に会えた日", "安達としまむら(CV:鬼頭明里と伊藤美来)", 0],
    [2, "メリーゴーランド", "安達としまむら(CV:鬼頭明里と伊藤美来)", 0],
    [3, "君に会えた日 -TV size ver.-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 0],
    [4, "メリーゴーランド -Glocken Ver.-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 0],
    [5, "君に会えた日 -instrumental-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 0],
    [6, "メリーゴーランド -instrumental-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 0],
]
links = ["https://vgmdb.net/album/101612", "https://beta.musicbrainz.org/release/c7f34a0b-ea8b-4042-9bb6-1b6cc18e7824"]

[4da46ddc88ceb9a7aa5123e7c39ff252]
catalognumber = "PCCG-01940"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里 [アニメ盤]"
tracks = [
    [1, "キミのとなりで", "鬼頭明里", 0],
    [2, "Dive to World", "鬼頭明里", 0],
    [3, "トウメイナユメ", "鬼頭明里", 0],
    [4, "キミのとなりで (Instrumental)", "鬼頭明里", 0],
    [5, "Dive to World (Instrumental)", "鬼頭明里", 0],
    [6, "トウメイナユメ (Instrumental)", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/102686", "https://beta.musicbrainz.org/release/0a98b176-c9da-42a0-91d0-b075c9cf6768"]

[be104f3d7befd61be8dad54f9c16c58d]
catalognumber = "PCCG-01941"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里"
tracks = [
    [1, "キミのとなりで", "鬼頭明里", 0],
    [2, "Dive to World", "鬼頭明里", 0],
    [3, "トウメイナユメ", "鬼頭明里", 0],
    [4, "キミのとなりで (Instrumental)", "鬼頭明里", 0],
    [5, "Dive to World (Instrumental)", "鬼頭明里", 0],
    [6, "トウメイナユメ (Instrumental)", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/102685", "https://beta.musicbrainz.org/release/0a98b176-c9da-42a0-91d0-b075c9cf6768"]

[45fe23bbbf44045736719aadb35cced8]
catalognumber = "UZCL-2200"
date = "2020-12-09"
album = "アニメ 安達としまむら オリジナル・サウンドトラック"
tracks = [
    [1, "居場所", "中村巴奈重", 0],
    [2, "昼休み", "櫻井美希", 0],
    [3, "君の隣", "田渕夏海", 0],
    [4, "小さな高揚", "櫻井美希", 0],
    [5, "人付き合いとは", "田渕夏海", 0],
    [6, "お出かけ", "中村巴奈重", 0],
    [7, "漆黒の世界", "中村巴奈重", 0],
    [8, "未来人", "櫻井美希", 0],
    [9, "未知のコミュニケーション", "櫻井美希", 0],
    [10, "何気ない毎日", "中村巴奈重", 0],
    [11, "不真面目な私たち", "田渕夏海", 0],
    [12, "恥じらいと妄想", "中村巴奈重", 0],
    [13, "抑えたい気持ち", "櫻井美希", 0],
    [14, "歯がゆい想い", "田渕夏海", 0],
    [15, "もしも・・・のどきどき", "中村巴奈重", 0],
    [16, "一緒に帰ろう", "田渕夏海", 0],
    [17, "妹", "田渕夏海", 0],
    [18, "見られた・・・", "櫻井美希", 0],
    [19, "私の一番とあなたの一番", "田渕夏海", 0],
    [20, "ともだち", "櫻井美希", 0],
    [21, "距離感", "櫻井美希", 0],
    [22, "ほどけた心", "中村巴奈重", 0],
    [23, "弾ける想い", "櫻井美希", 0],
    [24, "現実", "櫻井美希", 0],
    [25, "軟弱だぞ", "田渕夏海", 0],
    [26, "悪いことの共有", "田渕夏海", 0],
    [27, "拗ねる", "中村巴奈重", 0],
    [28, "すれ違う気持ち", "中村巴奈重", 0],
    [29, "どぎまぎ", "櫻井美希", 0],
    [30, "仲良くなりたい", "田渕夏海", 0],
    [31, "安心感", "櫻井美希", 0],
    [32, "これから", "中村巴奈重", 0],
    [33, "今までも", "櫻井美希", 0],
    [34, "伝えよう", "中村巴奈重", 0],
    [35, "想いを抱きしめ", "田渕夏海", 0],
]
links = ["https://vgmdb.net/album/106167", "https://beta.musicbrainz.org/release/01bd4b9c-8f95-4f64-98ee-4dc1216414cd"]

[08c8732c00b332c11f5b62a6c82cef07]
catalognumber = "DSP-02281"
date = "2021-01-06"
album = "「君に会えた日」ソロver. 楽曲CD"
tracks = [
    [1, "君に会えた日 -安達 (CV: 鬼頭明里) ソロ ver.-", "安達 (CV: 鬼頭明里)", 0],
    [2, "君に会えた日 -しまむら (CV: 伊藤美来) ソロ ver.-", "しまむら (CV: 伊藤美来)", 0],
]
links = ["https://vgmdb.net/album/108759", "https://beta.musicbrainz.org/release/27cc82f5-c481-486b-a37d-575cb2024e6c"]

[cda61e62ef8129a61cb1f3c4701f51f3]
catalognumber = "DSP-02287"
date = "2021-03-03"
album = "KITO AKARI 1st LIVE TOUR Colorful Closet LIVE CD"
tracks = [
    [1, "Swinging Heart", "", 0],
    [2, "Always Going My Way", "", 0],
    [3, "INNOCENT", "", 0],
    [4, "CRAZY ROCK NIGHT", "", 0],
    [5, "Drawing a Wish", "", 0],
    [6, "dear my distance", "", 0],
    [7, "Star Arc", "", 0],
    [8, "Closer", "", 0],
    [9, "23時の春雷少女", "", 0],
    [10, "ロケット", "", 0],
    [11, "Desire Again", "", 0],
    [12, "キミのとなりで", "", 0],
    [13, "Tiny Light", "", 0],
    [14, "君の花を祈ろう", "", 0],
    [15, "Fly-High-Five!", "", 0],
]
links = ["https://vgmdb.net/album/111320"]

[65db36f5e2e6ab7981b095e9246853d0]
catalognumber = "PCXP-50816"
date = "2021-03-03"
album = "KITO AKARI 1st LIVE TOUR Colorful Closet"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "Swinging Heart", "", 0],
    [3, "Always Going My Way", "", 0],
    [4, "INNOCENT", "", 0],
    [5, "CRAZY ROCK NIGHT", "", 0],
    [6, "Drawing a Wish", "", 0],
    [7, "dear my distance", "", 0],
    [8, "Star Arc", "", 0],
    [9, "Closer", "", 0],
    [10, "23時の春雷少女", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "ロケット", "", 0],
    [13, "Starry", "", 0],
    [14, "Desire Again", "", 0],
    [15, "キミのとなりで", "", 0],
    [16, "Tiny Light", "", 0],
    [17, "君の花を祈ろう", "", 0],
    [18, "Fly-High-Five!", "", 0],
    [19, "Making Video「Colorful Closet」BACKSTAGE", "", 0],
]
links = ["https://vgmdb.net/album/111321"]

[b0b5a03fe3f44b3ce797c857e33b395a]
catalognumber = "N/A"
date = "2022-03-18"
album = "Ko;Emotion 2"
tracks = [
    [1, "自分勝手Dazzling (A. Ki Uplifting Remix)", "", 0],
    [2, "Wonder Wonder Trip (Kamisys Neotrance Remix)", "", 0],
    [3, "キミのとなりで (BTB Remix)", "", 0],
    [4, "Stellar Stellar (Rabbit House Remix)", "", 0],
    [5, "花月ノ夢 (litmus* Remix)", "", 0],
    [6, "Be Starters! (Nagami. Remix)", "", 0],
    [7, "Power of LOVE!!! (bbangsami Remix)", "", 0],
    [8, "Nth color (on_OTL Remix)", "", 0],
]
links = ["https://vgmdb.net/album/132140"]

[2d088073aca90f865f4a4e17607e5bc0]
catalognumber = "DSP-02337"
date = "2022-04-13"
album = "KITO AKARI 2nd LIVE MIRRORS LIVE CD SECOND HALF"
tracks = [
    [1, "Follow me!", "", 0],
    [2, "Closer", "", 0],
    [3, "dear my distance", "", 0],
    [4, "トウメイナユメ", "", 0],
    [5, "キミのとなりで", "", 0],
    [6, "深夜センチメンタル", "", 0],
    [7, "INNOCENT", "", 0],
    [8, "Tiny Light", "", 0],
    [9, "Dive to World", "", 0],
    [10, "君の花を祈ろう", "", 0],
    [11, "Swinging Heart", "", 0],
    [12, "V!vace", "", 0],
]
links = ["https://vgmdb.net/album/119994"]

[650c83b42e50cd98485aba7e5a3b7b63]
catalognumber = "SCXP-00098"
date = "2022-04-13"
album = "KITO AKARI 2nd LIVE MIRRORS [FC限定盤]"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "The One", "", 0],
    [3, "Star Arc", "", 0],
    [4, "23時の春雷少女", "", 0],
    [5, "Fly-High-Five!", "", 0],
    [6, "Always Going My Way", "", 0],
    [7, "Desire Again", "", 0],
    [8, "Drawing a Wish", "", 0],
    [9, "CRAZY ROCK NIGHT", "", 0],
    [10, "No Continue", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "Follow me!", "", 0],
    [13, "Closer", "", 0],
    [14, "dear my distance", "", 0],
    [15, "トウメイナユメ", "", 0],
    [16, "キミのとなりで", "", 0],
    [17, "深夜センチメンタル", "", 0],
    [18, "INNOCENT", "", 0],
    [19, "Tiny Light", "", 0],
    [20, "Dive to World", "", 0],
    [21, "君の花を祈ろう", "", 0],
    [22, "Swinging Heart -ENCORE-", "", 0],
    [23, "V!vace -ENCORE-", "", 0],
    [24, "Making Video 「Documentary of MIRRORS」", "", 0],
]
links = ["https://vgmdb.net/album/119993"]

[480c62936242466f1cd349b2cf53cd50]
catalognumber = "PCXP-50877"
date = "2022-04-13"
album = "KITO AKARI 2nd LIVE MIRRORS"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "The One", "", 0],
    [3, "Star Arc", "", 0],
    [4, "23時の春雷少女", "", 0],
    [5, "Fly-High-Five!", "", 0],
    [6, "Always Going My Way", "", 0],
    [7, "Desire Again", "", 0],
    [8, "Drawing a Wish", "", 0],
    [9, "CRAZY ROCK NIGHT", "", 0],
    [10, "No Continue", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "Follow me!", "", 0],
    [13, "Closer", "", 0],
    [14, "dear my distance", "", 0],
    [15, "トウメイナユメ", "", 0],
    [16, "キミのとなりで", "", 0],
    [17, "深夜センチメンタル", "", 0],
    [18, "INNOCENT", "", 0],
    [19, "Tiny Light", "", 0],
    [20, "Dive to World", "", 0],
    [21, "君の花を祈ろう", "", 0],
    [22, "Swinging Heart -ENCORE-", "", 0],
    [23, "V!vace -ENCORE-", "", 0],
    [24, "Making Video 「Documentary of MIRRORS」", "", 0],
]
links = ["https://vgmdb.net/album/116648"]

[fb7e720a3490050db4d20e462662ec39]
catalognumber = "PCCG-02185"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [初回盤] Vocal"
tracks = [
    [1, "BYERONY", "鬼頭明里", 0],
    [2, "DEAD or CALL MY NAME", "鬼頭明里", 0],
    [3, "Oxidation", "鬼頭明里", 0],
    [4, "Esquisse", "鬼頭明里", 0],
    [5, "illminate", "鬼頭明里", 0],
    [6, "Crescent Lullaby", "鬼頭明里", 0],
    [7, "グッドモーニング", "鬼頭明里", 0],
    [8, "みちくさ", "鬼頭明里", 0],
    [9, "キミのとなりで", "鬼頭明里", 0],
    [10, "晴れ待ちノオト", "鬼頭明里", 0],
    [11, "トウメイナユメ", "鬼頭明里", 0],
    [12, "Dive to World", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/121434", "https://beta.musicbrainz.org/release/fa964c9a-9cd3-4703-bec4-290a2cd9c41e"]

[f803142a1bf6f80fa6346d7a4a417128]
catalognumber = "PCCG-02185"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [初回盤] Vocal, Video"
tracks = [
    [1, "「Esquisse」MUSIC VIDEO", "鬼頭明里", 0],
    [2, "「Esquisse」MV撮影 MAKING", "鬼頭明里", 0],
    [3, "「Luminous」ジャケット撮影 MAKING", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/121434", "https://beta.musicbrainz.org/release/fa964c9a-9cd3-4703-bec4-290a2cd9c41e"]

[bb2289c16f7204c30b4c3ae34cdbaabd]
catalognumber = "PCCG-02186"
date = "2022-10-12"
album = "Luminous / 鬼頭明里"
tracks = [
    [1, "BYERONY", "鬼頭明里", 0],
    [2, "DEAD or CALL MY NAME", "鬼頭明里", 0],
    [3, "Oxidation", "鬼頭明里", 0],
    [4, "Esquisse", "鬼頭明里", 0],
    [5, "illminate", "鬼頭明里", 0],
    [6, "Crescent Lullaby", "鬼頭明里", 0],
    [7, "グッドモーニング", "鬼頭明里", 0],
    [8, "みちくさ", "鬼頭明里", 0],
    [9, "キミのとなりで", "鬼頭明里", 0],
    [10, "晴れ待ちノオト", "鬼頭明里", 0],
    [11, "トウメイナユメ", "鬼頭明里", 0],
    [12, "Dive to World", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/121433", "https://beta.musicbrainz.org/release/fc102f80-ee56-446f-b0cd-f073dde071f6"]

[c41321b0347ae20a1a95bded814717af]
catalognumber = "SCCG-00110"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [FC限定盤] Vocal"
tracks = [
    [1, "BYERONY", "鬼頭明里", 0],
    [2, "DEAD or CALL MY NAME", "鬼頭明里", 0],
    [3, "Oxidation", "鬼頭明里", 0],
    [4, "Esquisse", "鬼頭明里", 0],
    [5, "illminate", "鬼頭明里", 0],
    [6, "Crescent Lullaby", "鬼頭明里", 0],
    [7, "グッドモーニング", "鬼頭明里", 0],
    [8, "みちくさ", "鬼頭明里", 0],
    [9, "キミのとなりで", "鬼頭明里", 0],
    [10, "晴れ待ちノオト", "鬼頭明里", 0],
    [11, "トウメイナユメ", "鬼頭明里", 0],
    [12, "Dive to World", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/121476", "https://beta.musicbrainz.org/release/afb12cff-aef4-432b-8807-535d53d018b7"]

[01e11b702d3c0c1d8adbf741df39fdc4]
catalognumber = "SCCG-00110"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [FC限定盤] Vocal, Video"
tracks = [
    [1, "「Esquisse」MUSIC VIDEO", "鬼頭明里", 0],
    [2, "「Esquisse」MV撮影 MAKING", "鬼頭明里", 0],
    [3, "「Luminous」ジャケット撮影 MAKING", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/121476", "https://beta.musicbrainz.org/release/afb12cff-aef4-432b-8807-535d53d018b7"]

[9e34e2577bd93b9783650db0eb277801]
catalognumber = "SCCG-00110"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [FC限定盤] Video"
tracks = [
    [1, "鬼頭明里 ファンクラブイベント「smile giving day vol.2」イベント映像", "鬼頭明里", 0],
]
links = ["https://vgmdb.net/album/121476", "https://beta.musicbrainz.org/release/afb12cff-aef4-432b-8807-535d53d018b7"]

[bee9613045e01c111b36b1fac0535410]
catalognumber = "PCXP-51040"
date = "2024-02-14"
album = "Akari Kito Zepp TOUR 2023 「Glow up!!」"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "DEAD or CALL MY NAME", "", 0],
    [3, "BYERONY", "", 0],
    [4, "Closer", "", 0],
    [5, "V!vace", "", 0],
    [6, "CRAZY ROCK NIGHT", "", 0],
    [7, "Esquisse", "", 0],
    [8, "Tiny Light", "", 0],
    [9, "Star Arc", "", 0],
    [10, "Crescent Lullaby", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "グッドモーニング", "", 0],
    [13, "Dear Doze Days", "", 0],
    [14, "みちくさ", "", 0],
    [15, "Fleeting Time", "", 0],
    [16, "深夜センチメンタル", "", 0],
    [17, "Oxidation", "", 0],
    [18, "Blue Velvet", "", 0],
    [19, "No Continue", "", 0],
    [20, "illminate", "", 0],
    [21, "Always Going My Way", "", 0],
    [22, "Fly-High-Five!", "", 0],
    [23, "キミのとなりで -ENCORE-", "", 0],
    [24, "23時の春雷少女 -ENCORE-", "", 0],
    [25, "Making Video -Documentary of Glow up!!-", "", 0],
]
links = ["https://vgmdb.net/album/137306"]
