[37a50db8323077f344d6d861e0574f0a]
catalognumber = "PCCG-01939"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里 [初回限定盤] Vocal"
tracks = [
    [1, "キミのとなりで", "鬼頭明里", 1],
    [2, "Dive to World", "鬼頭明里", 1],
    [3, "トウメイナユメ", "鬼頭明里", 1],
    [4, "キミのとなりで (Instrumental)", "鬼頭明里", 1],
    [5, "Dive to World (Instrumental)", "鬼頭明里", 1],
    [6, "トウメイナユメ (Instrumental)", "鬼頭明里", 1],
]
links = ["https://beta.musicbrainz.org/release/66620588-0f96-4092-98f9-91e97b21d7bc", "https://vgmdb.net/album/102687"]

[bc70e7008b13f36c15ea1d2c3bb3d450]
catalognumber = "PCCG-01939"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里 [初回限定盤] Vocal, Video"
tracks = [
    [1, "「キミのとなりで」MUSIC VIDEO", "鬼頭明里", 0],
    [2, "「キミのとなりで」ジャケット・MV撮影 MAKING", "鬼頭明里", 0],
]
links = ["https://beta.musicbrainz.org/release/66620588-0f96-4092-98f9-91e97b21d7bc", "https://vgmdb.net/album/102687"]

[f4e839681a838a67197e3e15eff43a92]
catalognumber = "PCCG-01929"
date = "2020-10-28"
album = "君に会えた日 / 安達としまむら (CV: 鬼頭明里と伊藤美来)"
tracks = [
    [1, "君に会えた日", "安達としまむら(CV:鬼頭明里と伊藤美来)", 1],
    [2, "メリーゴーランド", "安達としまむら(CV:鬼頭明里と伊藤美来)", 2],
    [3, "君に会えた日 -TV size ver.-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 1],
    [4, "メリーゴーランド -Glocken Ver.-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 1],
    [5, "君に会えた日 -instrumental-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 1],
    [6, "メリーゴーランド -instrumental-", "安達としまむら(CV:鬼頭明里と伊藤美来)", 2],
]
links = ["https://beta.musicbrainz.org/release/c7f34a0b-ea8b-4042-9bb6-1b6cc18e7824", "https://vgmdb.net/album/101612"]

[5ece3df8ae9637b2a258723fe8811ec8]
catalognumber = "PCCG-01940"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里 [アニメ盤]"
tracks = [
    [1, "キミのとなりで", "鬼頭明里", 1],
    [2, "Dive to World", "鬼頭明里", 1],
    [3, "トウメイナユメ", "鬼頭明里", 1],
    [4, "キミのとなりで (Instrumental)", "鬼頭明里", 1],
    [5, "Dive to World (Instrumental)", "鬼頭明里", 1],
    [6, "トウメイナユメ (Instrumental)", "鬼頭明里", 1],
]
links = ["https://beta.musicbrainz.org/release/0a98b176-c9da-42a0-91d0-b075c9cf6768", "https://vgmdb.net/album/102686"]

[6d24c204b3eb926a6bcc37a9be7cc0e8]
catalognumber = "PCCG-01941"
date = "2020-10-28"
album = "キミのとなりで / 鬼頭明里"
tracks = [
    [1, "キミのとなりで", "鬼頭明里", 1],
    [2, "Dive to World", "鬼頭明里", 1],
    [3, "トウメイナユメ", "鬼頭明里", 1],
    [4, "キミのとなりで (Instrumental)", "鬼頭明里", 1],
    [5, "Dive to World (Instrumental)", "鬼頭明里", 1],
    [6, "トウメイナユメ (Instrumental)", "鬼頭明里", 1],
]
links = ["https://beta.musicbrainz.org/release/0a98b176-c9da-42a0-91d0-b075c9cf6768", "https://vgmdb.net/album/102685"]

[c374a69554696bc2ebb34e669933aae3]
catalognumber = "UZCL-2200"
date = "2020-12-09"
album = "アニメ 安達としまむら オリジナル・サウンドトラック"
tracks = [
    [1, "居場所", "中村巴奈重", 1],
    [2, "昼休み", "櫻井美希", 1],
    [3, "君の隣", "田渕夏海", 1],
    [4, "小さな高揚", "櫻井美希", 1],
    [5, "人付き合いとは", "田渕夏海", 1],
    [6, "お出かけ", "中村巴奈重", 1],
    [7, "漆黒の世界", "中村巴奈重", 1],
    [8, "未来人", "櫻井美希", 1],
    [9, "未知のコミュニケーション", "櫻井美希", 1],
    [10, "何気ない毎日", "中村巴奈重", 1],
    [11, "不真面目な私たち", "田渕夏海", 1],
    [12, "恥じらいと妄想", "中村巴奈重", 1],
    [13, "抑えたい気持ち", "櫻井美希", 1],
    [14, "歯がゆい想い", "田渕夏海", 1],
    [15, "もしも・・・のどきどき", "中村巴奈重", 1],
    [16, "一緒に帰ろう", "田渕夏海", 1],
    [17, "妹", "田渕夏海", 1],
    [18, "見られた・・・", "櫻井美希", 1],
    [19, "私の一番とあなたの一番", "田渕夏海", 1],
    [20, "ともだち", "櫻井美希", 1],
    [21, "距離感", "櫻井美希", 1],
    [22, "ほどけた心", "中村巴奈重", 1],
    [23, "弾ける想い", "櫻井美希", 1],
    [24, "現実", "櫻井美希", 1],
    [25, "軟弱だぞ", "田渕夏海", 1],
    [26, "悪いことの共有", "田渕夏海", 1],
    [27, "拗ねる", "中村巴奈重", 1],
    [28, "すれ違う気持ち", "中村巴奈重", 1],
    [29, "どぎまぎ", "櫻井美希", 1],
    [30, "仲良くなりたい", "田渕夏海", 1],
    [31, "安心感", "櫻井美希", 1],
    [32, "これから", "中村巴奈重", 1],
    [33, "今までも", "櫻井美希", 1],
    [34, "伝えよう", "中村巴奈重", 1],
    [35, "想いを抱きしめ", "田渕夏海", 1],
]
links = ["https://beta.musicbrainz.org/release/01bd4b9c-8f95-4f64-98ee-4dc1216414cd", "https://vgmdb.net/album/106167"]

[e61b9111d26c1f2e9c2aff994248d598]
catalognumber = "DSP-02281"
date = "2021-01-06"
album = "「君に会えた日」ソロver. 楽曲CD"
tracks = [
    [1, "君に会えた日 -安達 (CV: 鬼頭明里) ソロ ver.-", "安達 (CV: 鬼頭明里)", 1],
    [2, "君に会えた日 -しまむら (CV: 伊藤美来) ソロ ver.-", "しまむら (CV: 伊藤美来)", 1],
]
links = ["https://beta.musicbrainz.org/release/27cc82f5-c481-486b-a37d-575cb2024e6c", "https://vgmdb.net/album/108759"]

[1d10f5340e04b142232b98bc4470933f]
catalognumber = "DSP-02287"
date = "2021-03-03"
album = "KITO AKARI 1st LIVE TOUR Colorful Closet LIVE CD"
tracks = [
    [1, "Swinging Heart", "", 0],
    [2, "Always Going My Way", "", 0],
    [3, "INNOCENT", "", 0],
    [4, "CRAZY ROCK NIGHT", "", 0],
    [5, "Drawing a Wish", "", 0],
    [6, "dear my distance", "", 0],
    [7, "Star Arc", "", 0],
    [8, "Closer", "", 0],
    [9, "23時の春雷少女", "", 0],
    [10, "ロケット", "", 0],
    [11, "Desire Again", "", 0],
    [12, "キミのとなりで", "", 1],
    [13, "Tiny Light", "", 0],
    [14, "君の花を祈ろう", "", 0],
    [15, "Fly-High-Five!", "", 0],
]
links = ["https://vgmdb.net/album/111320"]

[2f02c5aa32b5162f407c47d2b0a9f15e]
catalognumber = "PCXP-50816"
date = "2021-03-03"
album = "KITO AKARI 1st LIVE TOUR Colorful Closet"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "Swinging Heart", "", 0],
    [3, "Always Going My Way", "", 0],
    [4, "INNOCENT", "", 0],
    [5, "CRAZY ROCK NIGHT", "", 0],
    [6, "Drawing a Wish", "", 0],
    [7, "dear my distance", "", 0],
    [8, "Star Arc", "", 0],
    [9, "Closer", "", 0],
    [10, "23時の春雷少女", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "ロケット", "", 0],
    [13, "Starry", "", 0],
    [14, "Desire Again", "", 0],
    [15, "キミのとなりで", "", 1],
    [16, "Tiny Light", "", 0],
    [17, "君の花を祈ろう", "", 0],
    [18, "Fly-High-Five!", "", 0],
    [19, "Making Video「Colorful Closet」BACKSTAGE", "", 0],
]
links = ["https://vgmdb.net/album/111321"]

[c0ac76f8ce5000be19540ef60bde21d4]
catalognumber = "N/A"
date = "2022-03-18"
album = "Ko;Emotion 2"
tracks = [
    [1, "自分勝手Dazzling (A. Ki Uplifting Remix)", "", 0],
    [2, "Wonder Wonder Trip (Kamisys Neotrance Remix)", "", 0],
    [3, "キミのとなりで (BTB Remix)", "", 1],
    [4, "Stellar Stellar (Rabbit House Remix)", "", 0],
    [5, "花月ノ夢 (litmus* Remix)", "", 0],
    [6, "Be Starters! (Nagami. Remix)", "", 0],
    [7, "Power of LOVE!!! (bbangsami Remix)", "", 0],
    [8, "Nth color (on_OTL Remix)", "", 0],
]
links = ["https://vgmdb.net/album/132140"]

[5bd8caa04365dccd398368c4215ee525]
catalognumber = "DSP-02337"
date = "2022-04-13"
album = "KITO AKARI 2nd LIVE MIRRORS LIVE CD SECOND HALF"
tracks = [
    [1, "Follow me!", "", 0],
    [2, "Closer", "", 0],
    [3, "dear my distance", "", 0],
    [4, "トウメイナユメ", "", 1],
    [5, "キミのとなりで", "", 1],
    [6, "深夜センチメンタル", "", 0],
    [7, "INNOCENT", "", 0],
    [8, "Tiny Light", "", 0],
    [9, "Dive to World", "", 1],
    [10, "君の花を祈ろう", "", 0],
    [11, "Swinging Heart", "", 0],
    [12, "V!vace", "", 0],
]
links = ["https://vgmdb.net/album/119994"]

[8629bf250fff06bf4c766eb78e246817]
catalognumber = "SCXP-00098"
date = "2022-04-13"
album = "KITO AKARI 2nd LIVE MIRRORS [FC限定盤]"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "The One", "", 0],
    [3, "Star Arc", "", 0],
    [4, "23時の春雷少女", "", 0],
    [5, "Fly-High-Five!", "", 0],
    [6, "Always Going My Way", "", 0],
    [7, "Desire Again", "", 0],
    [8, "Drawing a Wish", "", 0],
    [9, "CRAZY ROCK NIGHT", "", 0],
    [10, "No Continue", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "Follow me!", "", 0],
    [13, "Closer", "", 0],
    [14, "dear my distance", "", 0],
    [15, "トウメイナユメ", "", 1],
    [16, "キミのとなりで", "", 1],
    [17, "深夜センチメンタル", "", 0],
    [18, "INNOCENT", "", 0],
    [19, "Tiny Light", "", 0],
    [20, "Dive to World", "", 1],
    [21, "君の花を祈ろう", "", 0],
    [22, "Swinging Heart -ENCORE-", "", 0],
    [23, "V!vace -ENCORE-", "", 0],
    [24, "Making Video 「Documentary of MIRRORS」", "", 0],
]
links = ["https://vgmdb.net/album/119993"]

[d92a142027aa2fc876477feed2e6f9d1]
catalognumber = "PCXP-50877"
date = "2022-04-13"
album = "KITO AKARI 2nd LIVE MIRRORS"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "The One", "", 0],
    [3, "Star Arc", "", 0],
    [4, "23時の春雷少女", "", 0],
    [5, "Fly-High-Five!", "", 0],
    [6, "Always Going My Way", "", 0],
    [7, "Desire Again", "", 0],
    [8, "Drawing a Wish", "", 0],
    [9, "CRAZY ROCK NIGHT", "", 0],
    [10, "No Continue", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "Follow me!", "", 0],
    [13, "Closer", "", 0],
    [14, "dear my distance", "", 0],
    [15, "トウメイナユメ", "", 1],
    [16, "キミのとなりで", "", 1],
    [17, "深夜センチメンタル", "", 0],
    [18, "INNOCENT", "", 0],
    [19, "Tiny Light", "", 0],
    [20, "Dive to World", "", 1],
    [21, "君の花を祈ろう", "", 0],
    [22, "Swinging Heart -ENCORE-", "", 0],
    [23, "V!vace -ENCORE-", "", 0],
    [24, "Making Video 「Documentary of MIRRORS」", "", 0],
]
links = ["https://vgmdb.net/album/116648"]

[aabc8a853ecf1ba60a20b264bbd5341f]
catalognumber = "PCCG-02185"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [初回盤] Vocal"
tracks = [
    [1, "BYERONY", "鬼頭明里", 0],
    [2, "DEAD or CALL MY NAME", "鬼頭明里", 0],
    [3, "Oxidation", "鬼頭明里", 0],
    [4, "Esquisse", "鬼頭明里", 0],
    [5, "illminate", "鬼頭明里", 0],
    [6, "Crescent Lullaby", "鬼頭明里", 0],
    [7, "グッドモーニング", "鬼頭明里", 0],
    [8, "みちくさ", "鬼頭明里", 0],
    [9, "キミのとなりで", "鬼頭明里", 1],
    [10, "晴れ待ちノオト", "鬼頭明里", 0],
    [11, "トウメイナユメ", "鬼頭明里", 1],
    [12, "Dive to World", "鬼頭明里", 1],
]
links = ["https://beta.musicbrainz.org/release/fa964c9a-9cd3-4703-bec4-290a2cd9c41e", "https://vgmdb.net/album/121434"]

[1db7963bc104a21bf8d00d9a7272f436]
catalognumber = "PCCG-02185"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [初回盤] Vocal, Video"
tracks = [
    [1, "「Esquisse」MUSIC VIDEO", "鬼頭明里", 0],
    [2, "「Esquisse」MV撮影 MAKING", "鬼頭明里", 0],
    [3, "「Luminous」ジャケット撮影 MAKING", "鬼頭明里", 0],
]
links = ["https://beta.musicbrainz.org/release/fa964c9a-9cd3-4703-bec4-290a2cd9c41e", "https://vgmdb.net/album/121434"]

[5e2478089e05e5ca96c9f0b95f2578c3]
catalognumber = "PCCG-02186"
date = "2022-10-12"
album = "Luminous / 鬼頭明里"
tracks = [
    [1, "BYERONY", "鬼頭明里", 0],
    [2, "DEAD or CALL MY NAME", "鬼頭明里", 0],
    [3, "Oxidation", "鬼頭明里", 0],
    [4, "Esquisse", "鬼頭明里", 0],
    [5, "illminate", "鬼頭明里", 0],
    [6, "Crescent Lullaby", "鬼頭明里", 0],
    [7, "グッドモーニング", "鬼頭明里", 0],
    [8, "みちくさ", "鬼頭明里", 0],
    [9, "キミのとなりで", "鬼頭明里", 1],
    [10, "晴れ待ちノオト", "鬼頭明里", 0],
    [11, "トウメイナユメ", "鬼頭明里", 1],
    [12, "Dive to World", "鬼頭明里", 1],
]
links = ["https://beta.musicbrainz.org/release/fc102f80-ee56-446f-b0cd-f073dde071f6", "https://vgmdb.net/album/121433"]

[4352e63304a71fbe304d81b2632aba2e]
catalognumber = "SCCG-00110"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [FC限定盤] Vocal"
tracks = [
    [1, "BYERONY", "鬼頭明里", 0],
    [2, "DEAD or CALL MY NAME", "鬼頭明里", 0],
    [3, "Oxidation", "鬼頭明里", 0],
    [4, "Esquisse", "鬼頭明里", 0],
    [5, "illminate", "鬼頭明里", 0],
    [6, "Crescent Lullaby", "鬼頭明里", 0],
    [7, "グッドモーニング", "鬼頭明里", 0],
    [8, "みちくさ", "鬼頭明里", 0],
    [9, "キミのとなりで", "鬼頭明里", 1],
    [10, "晴れ待ちノオト", "鬼頭明里", 0],
    [11, "トウメイナユメ", "鬼頭明里", 1],
    [12, "Dive to World", "鬼頭明里", 1],
]
links = ["https://beta.musicbrainz.org/release/afb12cff-aef4-432b-8807-535d53d018b7", "https://vgmdb.net/album/121476"]

[e74304f93a4a1a2b92ba701d8818f93b]
catalognumber = "SCCG-00110"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [FC限定盤] Vocal, Video"
tracks = [
    [1, "「Esquisse」MUSIC VIDEO", "鬼頭明里", 0],
    [2, "「Esquisse」MV撮影 MAKING", "鬼頭明里", 0],
    [3, "「Luminous」ジャケット撮影 MAKING", "鬼頭明里", 0],
]
links = ["https://beta.musicbrainz.org/release/afb12cff-aef4-432b-8807-535d53d018b7", "https://vgmdb.net/album/121476"]

[4da5d63ee46d1d950af8099fa7204ce4]
catalognumber = "SCCG-00110"
date = "2022-10-12"
album = "Luminous / 鬼頭明里 [FC限定盤] Video"
tracks = [
    [1, "鬼頭明里 ファンクラブイベント「smile giving day vol.2」イベント映像", "鬼頭明里", 0],
]
links = ["https://beta.musicbrainz.org/release/afb12cff-aef4-432b-8807-535d53d018b7", "https://vgmdb.net/album/121476"]

[99585d23d1f15fef3b3afa0dce66026b]
catalognumber = "PCXP-51040"
date = "2024-02-14"
album = "Akari Kito Zepp TOUR 2023 「Glow up!!」"
tracks = [
    [1, "-Opening-", "", 0],
    [2, "DEAD or CALL MY NAME", "", 0],
    [3, "BYERONY", "", 0],
    [4, "Closer", "", 0],
    [5, "V!vace", "", 0],
    [6, "CRAZY ROCK NIGHT", "", 0],
    [7, "Esquisse", "", 0],
    [8, "Tiny Light", "", 0],
    [9, "Star Arc", "", 0],
    [10, "Crescent Lullaby", "", 0],
    [11, "-Band&Dancer Time-", "", 0],
    [12, "グッドモーニング", "", 0],
    [13, "Dear Doze Days", "", 0],
    [14, "みちくさ", "", 0],
    [15, "Fleeting Time", "", 0],
    [16, "深夜センチメンタル", "", 0],
    [17, "Oxidation", "", 0],
    [18, "Blue Velvet", "", 0],
    [19, "No Continue", "", 0],
    [20, "illminate", "", 0],
    [21, "Always Going My Way", "", 0],
    [22, "Fly-High-Five!", "", 0],
    [23, "キミのとなりで -ENCORE-", "", 1],
    [24, "23時の春雷少女 -ENCORE-", "", 0],
    [25, "Making Video -Documentary of Glow up!!-", "", 0],
]
links = ["https://vgmdb.net/album/137306"]
