[d573b03bcd397ef1282e206905587a88]
catalognumber = "THCS-60062"
date = "2015-08-19"
album = "ひだまりデイズ / 妹S(シスターズ)"
tracks = [
    [1, "ひだまりデイズ", "妹S", 1],
    [2, "フィーバー夏Vacation!", "妹S", 1],
    [3, "ひだまりデイズ (Instrumental)", "妹S", 1],
    [4, "フィーバー夏Vacation! (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/ac257499-4901-432c-83c5-7376ad262f67", "https://vgmdb.net/album/53283"]

[ad48684a939702393971172e453bae9f]
catalognumber = "THCS-60061"
date = "2015-08-19"
album = "かくしん的☆めたまるふぉ~ぜっ! / 土間うまる(CV:田中あいみ)"
tracks = [
    [1, "かくしん的☆めたまるふぉ〜ぜっ!", "土間うまる(CV:田中あいみ)", 1],
    [2, "Sisters Wink", "妹S", 1],
    [3, "かくしん的☆めたまるふぉ〜ぜっ! (Instrumental)", "土間うまる(CV:田中あいみ)", 1],
    [4, "Sisters Wink (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/c4fa0d0c-092f-4689-80d3-1bd1d57d6059", "https://vgmdb.net/album/53282"]

[a817439358e06f5daa931829ce0da583]
catalognumber = "THCS-60066"
date = "2015-09-02"
album = "干物妹!うまるちゃん キャラクターソング Vol.1 / 土間うまる(CV:田中あいみ)"
tracks = [
    [1, "勇者うまるの華麗なる生活", "土間うまる(CV:田中あいみ)", 1],
    [2, "Beautiful Days", "土間うまる(CV:田中あいみ)", 1],
    [3, "ひだまりデイズ (うまるver.)", "土間うまる(CV:田中あいみ)", 1],
    [4, "勇者うまるの華麗なる生活 (Instrumental)", "土間うまる(CV:田中あいみ)", 1],
    [5, "Beautiful Days (Instrumental)", "土間うまる(CV:田中あいみ)", 1],
]
links = ["https://beta.musicbrainz.org/release/55ea67cd-6b15-47d7-9164-0438be8f8a65", "https://vgmdb.net/album/53802"]

[51955c8cb594522240274d2e3e0910d2]
catalognumber = "THCS-60067"
date = "2015-09-02"
album = "干物妹!うまるちゃん キャラクターソング Vol.2 / 海老名菜々(CV:影山灯)"
tracks = [
    [1, "sweet sweet everytime sweet", "海老名菜々(CV:影山灯)", 1],
    [2, "そいだばね", "海老名菜々(CV:影山灯)", 1],
    [3, "ひだまりデイズ (海老名ver.)", "海老名菜々(CV:影山灯)", 1],
    [4, "sweet sweet everytime sweet (Instrumental)", "海老名菜々(CV:影山灯)", 1],
    [5, "そいだばね (Instrumental)", "海老名菜々(CV:影山灯)", 1],
]
links = ["https://beta.musicbrainz.org/release/e34791cd-bbec-42e7-a7bc-a4c46e9d8c18", "https://vgmdb.net/album/53803"]

[62b2a243ff255173e13aea927c98862b]
catalognumber = "THCS-60069"
date = "2015-09-16"
album = "干物妹!うまるちゃん キャラクターソング Vol.4 / 橘・シルフィンフォード(CV:古川由利奈)"
tracks = [
    [1, "T・S・F in にっぽん!", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [2, "シュバッとNo.1", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [3, "ひだまりデイズ (シルフィンver.)", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [4, "T・S・F in にっぽん! (Instrumental)", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [5, "シュバッとNo.1 (Instrumental)", "橘・シルフィンフォード(CV:古川由利奈)", 1],
]
links = ["https://beta.musicbrainz.org/release/6c1288df-de2d-49c5-a262-04d183958d1a", "https://vgmdb.net/album/53805"]

[55df5880020af52860c4e6787ce937ea]
catalognumber = "THCS-60068"
date = "2015-09-16"
album = "干物妹!うまるちゃん キャラクターソング Vol.3 / 本場切絵(CV:白石晴香)"
tracks = [
    [1, "My Precious", "本場切絵(CV:白石晴香)", 1],
    [2, "トトファンタジア", "本場切絵(CV:白石晴香)", 1],
    [3, "ひだまりデイズ (切絵ver.)", "本場切絵(CV:白石晴香)", 1],
    [4, "My Precious (Instrumental)", "本場切絵(CV:白石晴香)", 1],
    [5, "トトファンタジア (Instrumental)", "本場切絵(CV:白石晴香)", 1],
]
links = ["https://beta.musicbrainz.org/release/f129a835-61d5-428c-bbe0-ff4e47f48136", "https://vgmdb.net/album/53804"]

[5707391a6884cc4779dcdf3922e02997]
catalognumber = "TBR25321D-2"
date = "2015-09-16"
album = "干物妹!うまるちゃん キャラクターソングCD 1"
tracks = [
    [1, "Dreamy Friends", "妹S", 2],
    [2, "Dreamy Friends (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/f01ce2de-88f4-411a-8513-1fd1cc32db61", "https://vgmdb.net/album/54984"]

[0f7c1490948077003fada1eab8e76222]
catalognumber = "TBR25322D-2"
date = "2015-10-14"
album = "干物妹!うまるちゃん キャラクターソングCD 2"
tracks = [
    [1, "ふわり綿飴 美味しくなあれ", "妹S", 1],
    [2, "ふわり綿飴 美味しくなあれ (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/d7aaadbb-5070-47f7-b7cc-edf13e692b20", "https://vgmdb.net/album/54985"]

[f27e17ade9b6544c67ea350c9ef8b897]
catalognumber = "TBR25323D-2"
date = "2015-11-18"
album = "干物妹!うまるちゃん キャラクターソングCD 3"
tracks = [
    [1, "Happy Nightmare 〜妹達の饗宴〜", "妹S", 1],
    [2, "Happy Nightmare 〜妹達の饗宴〜 (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/ffc28655-8078-40dc-b0c9-46071b7231ab", "https://vgmdb.net/album/54986"]

[293cc803e580b8c60f3df1f5edf4a311]
catalognumber = "THCA-60080"
date = "2015-11-18"
album = "干物妹!うまるちゃん オリジナル・サウンドトラック"
tracks = [
    [1, "完璧な女子高生", "三澤康広", 1],
    [2, "うまるとお兄ちゃん", "三澤康広", 1],
    [3, "干物妹", "三澤康広", 1],
    [4, "お兄ちゃんの日常", "三澤康広", 1],
    [5, "来年から本気出す", "三澤康広", 1],
    [6, "ここが天国だ!", "三澤康広", 1],
    [7, "とんでもない干物妹", "三澤康広", 1],
    [8, "おきらくタイム", "三澤康広", 1],
    [9, "まだゴロゴロしてたい…", "三澤康広", 1],
    [10, "ぐーたら生活", "三澤康広", 1],
    [11, "夜になって後悔", "三澤康広", 1],
    [12, "不満なうまる", "三澤康広", 1],
    [13, "勝負ですわ!", "三澤康広", 1],
    [14, "宴がはじまる!", "三澤康広", 1],
    [15, "わがままうまる", "三澤康広", 1],
    [16, "美人な妹", "三澤康広", 1],
    [17, "猫かぶり", "三澤康広", 1],
    [18, "遊びに行こう", "三澤康広", 1],
    [19, "わくわく夜道", "三澤康広", 1],
    [20, "さみしい夜道", "三澤康広", 1],
    [21, "このまま時が止まればいいのに", "三澤康広", 1],
    [22, "うまるリズム その1", "三澤康広", 1],
    [23, "うまるリズム その2", "三澤康広", 1],
    [24, "最強のゲーマー", "三澤康広", 1],
    [25, "お風呂のすすめ", "三澤康広", 1],
    [26, "お兄ちゃん怖いの?", "三澤康広", 1],
    [27, "怖い夢", "三澤康広", 1],
    [28, "ツントゲガール", "三澤康広", 1],
    [29, "どこまでもついていきます", "三澤康広", 1],
    [30, "ジャポネットCM", "三澤康広", 1],
    [31, "ジャポネッコCM", "三澤康広", 1],
    [32, "デカンティーCM", "三澤康広", 1],
    [33, "こまるの人生", "三澤康広", 1],
    [34, "異議あり!", "三澤康広", 1],
    [35, "うまる補完計画", "三澤康広", 1],
    [36, "もったいないコーラ", "三澤康広", 1],
    [37, "一人でなんて決められないよ", "三澤康広", 1],
    [38, "うまるちゃんS", "三澤康広", 1],
    [39, "思い出せない道", "三澤康広", 1],
    [40, "ありがとう、お兄ちゃん", "三澤康広", 1],
    [41, "うまるはごきげんナナメ", "三澤康広", 1],
    [42, "お兄ちゃんと休日", "三澤康広", 1],
    [43, "妹仲間", "三澤康広", 1],
    [44, "うまるの夏休み", "三澤康広", 1],
    [45, "僕のたった一人の妹", "三澤康広", 1],
    [46, "かくしん的☆めたまるふぉ〜ぜっ! -TV size ver.-", "土間うまる(CV:田中あいみ)", 1],
    [47, "ひだまりデイズ -TV size ver.-", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/02d2e327-d910-46bf-a4b7-56f8790dd302", "https://vgmdb.net/album/54839"]

[93d8682346731dff81ccbb8e2c24847e]
catalognumber = "TBR25324D-2"
date = "2015-12-16"
album = "干物妹!うまるちゃん キャラクターソングCD 4"
tracks = [
    [1, "X'mas Decoration", "妹S", 2],
    [2, "X'mas Decoration (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/f3fd88ab-7f41-4440-9ab4-eacba4265d6e", "https://vgmdb.net/album/54987"]

[c2cc22eba940c81085d735516daa9ac0]
catalognumber = "THCA-60102"
date = "2016-08-17"
album = "「干物妹!うまるちゃん」ベストアルバム ～UMARU THE BEST～ Disc 1 (CD) [THCA-60102-1]"
tracks = [
    [1, "かくしん的☆めたまるふぉ～ぜっ!", "土間うまる(CV:田中あいみ)", 1],
    [2, "Sisters Wink", "妹S", 1],
    [3, "フィーバー夏Vacation!", "妹S", 1],
    [4, "勇者うまるの華麗なる生活", "土間うまる(CV:田中あいみ)", 1],
    [5, "Beautiful Days", "土間うまる(CV:田中あいみ)", 1],
    [6, "sweet sweet everytime sweet", "海老名菜々(CV:影山灯)", 1],
    [7, "そいだばね", "海老名菜々(CV:影山灯)", 1],
    [8, "My Precious", "本場切絵(CV:白石晴香)", 1],
    [9, "トトファンタジア", "本場切絵(CV:白石晴香)", 1],
    [10, "T・S・F in にっぽん!", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [11, "シュバッとNo.1", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [12, "Dreamy Friends", "妹S", 1],
    [13, "ふわり綿飴 美味しくなあれ", "妹S", 1],
    [14, "Happy Nightmare ～妹達の饗宴～", "妹S", 1],
    [15, "X'mas Decoration", "妹S", 1],
    [16, "ひだまりデイズ", "妹S", 1],
    [17, "パラダイス☆しんどろ～むっ!", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/7b6481da-c236-4283-a179-25b39088bfad", "https://vgmdb.net/album/60616"]

[01137f7121a6189094467ec1d31920e3]
catalognumber = "THCA-60102"
date = "2016-08-17"
album = "「干物妹!うまるちゃん」ベストアルバム ～UMARU THE BEST～ Disc 2 (Blu-ray) [THCA-60102-2]"
tracks = [
    [1, "かくしん的☆めたまるふぉ～ぜっ!", "土間うまる(CV:田中あいみ)", 1],
    [2, "Sisters Wink", "妹S", 1],
    [3, "フィーバー夏Vacation!", "妹S", 1],
    [4, "勇者うまるの華麗なる生活", "土間うまる(CV:田中あいみ)", 1],
    [5, "Beautiful Days", "土間うまる(CV:田中あいみ)", 1],
    [6, "sweet sweet everytime sweet", "海老名菜々(CV:影山灯)", 1],
    [7, "そいだばね", "海老名菜々(CV:影山灯)", 1],
    [8, "My Precious", "本場切絵(CV:白石晴香)", 1],
    [9, "トトファンタジア", "本場切絵(CV:白石晴香)", 1],
    [10, "T・S・F in にっぽん!", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [11, "シュバッとNo.1", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [12, "Dreamy Friends", "妹S", 1],
    [13, "ふわり綿飴 美味しくなあれ", "妹S", 1],
    [14, "Happy Nightmare ～妹達の饗宴～", "妹S", 1],
    [15, "X'mas Decoration", "妹S", 1],
    [16, "ひだまりデイズ", "妹S", 1],
    [17, "パラダイス☆しんどろ～むっ!", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/7b6481da-c236-4283-a179-25b39088bfad", "https://vgmdb.net/album/60616"]

[a0d71813757c8be35638495688fba9c7]
catalognumber = "SFCHUC100CD"
date = "2017-05-30"
album = "Himouto! Umaru-chan Soundtrack"
tracks = [
    [1, "完璧な女子高生", "", 1],
    [2, "うまるとお兄ちゃん", "", 1],
    [3, "干物妹", "", 1],
    [4, "お兄ちゃんの日常", "", 1],
    [5, "来年から本気出す", "", 1],
    [6, "ここが天国だ!", "", 1],
    [7, "とんでもない干物妹", "", 1],
    [8, "おきらくタイム", "", 1],
    [9, "まだゴロゴロしてたい…", "", 1],
    [10, "ぐーたら生活", "", 1],
    [11, "夜になって後悔", "", 1],
    [12, "不満なうまる", "", 1],
    [13, "勝負ですわ!", "", 1],
    [14, "宴がはじまる!", "", 1],
    [15, "わがままうまる", "", 1],
    [16, "美人な妹", "", 1],
    [17, "猫かぶり", "", 1],
    [18, "遊びに行こう", "", 1],
    [19, "わくわく夜道", "", 1],
    [20, "さみしい夜道", "", 1],
    [21, "このまま時が止まればいいのに", "", 1],
    [22, "うまるリズムその1", "", 1],
    [23, "うまるリズムその2", "", 1],
    [24, "最強のゲーマー", "", 1],
    [25, "お風呂のすすめ", "", 1],
    [26, "お兄ちゃん怖いの?", "", 1],
    [27, "怖い夢", "", 1],
    [28, "ツントゲガール", "", 1],
    [29, "どこまでもついていきます", "", 1],
    [30, "ジャポネットCM", "", 1],
    [31, "ジャポネッコCM", "", 1],
    [32, "デカンティーCM", "", 1],
    [33, "こまるの人生", "", 1],
    [34, "異議あり!", "", 1],
    [35, "うまる補完計画", "", 1],
    [36, "もったいないコーラ", "", 1],
    [37, "一人でなんて決められないよ", "", 1],
    [38, "うまるちゃんS", "", 1],
    [39, "思い出せない道", "", 1],
    [40, "ありがとう、お兄ちゃん", "", 1],
    [41, "うまるはごきげんナナメ", "", 1],
    [42, "お兄ちゃんと休日", "", 1],
    [43, "妹仲間", "", 1],
    [44, "うまるの夏休み", "", 1],
    [45, "僕のたった一人の妹", "", 1],
    [46, "かくしん的☆めたまるふぉ～ぜっ! -TV size ver.-", "", 1],
    [47, "ひだまりデイズ -TV size ver.-", "", 1],
]
links = ["https://vgmdb.net/album/65059"]

[5445432ecb92250621297b4253cc61f3]
catalognumber = "THCS-60167"
date = "2017-11-15"
album = "うまるん体操 / 妹S(シスターズ)"
tracks = [
    [1, "うまるん体操", "妹S", 1],
    [2, "変わらない宝物", "妹S", 2],
    [3, "うまるん体操 (Instrumental)", "妹S", 1],
    [4, "変わらない宝物 (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/38692217-9b09-4e6c-bc71-cbdba221d131", "https://vgmdb.net/album/71423"]

[878b9162ab8c0d6200ddbf64064f12e4]
catalognumber = "THCS-60166"
date = "2017-11-15"
album = "にめんせい☆ウラオモテライフ! / 土間うまる(CV:田中あいみ)"
tracks = [
    [1, "にめんせい☆ウラオモテライフ!", "土間うまる(CV:田中あいみ)", 1],
    [2, "うるとら☆まじかる☆りれーしょん", "土間うまる(CV:田中あいみ)", 1],
    [3, "にめんせい☆ウラオモテライフ! (Instrumental)", "土間うまる(CV:田中あいみ)", 1],
    [4, "うるとら☆まじかる☆りれーしょん (Instrumental)", "土間うまる(CV:田中あいみ)", 1],
]
links = ["https://beta.musicbrainz.org/release/582c9237-0f87-4438-bda3-dd03fc8b2b4c", "https://vgmdb.net/album/71422"]

[cc7face3a81073889af00cc6097d1ad5]
catalognumber = "THCA-60177"
date = "2017-12-13"
album = "TVアニメ『干物妹! うまるちゃんR』キャラクターソングアルバム: ～妹S☆QUEST～"
tracks = [
    [1, "トワ・エ・モア", "土間うまる(CV:田中あいみ)", 1],
    [2, "7th Heart", "海老名菜々(CV:影山灯)", 1],
    [3, "未完成マイヒーロー", "本場切絵(CV:白石晴香)", 1],
    [4, "いつかきっと", "橘・シルフィンフォード(CV:古川由利奈)", 2],
    [5, "海老名ちゃんのフリー秋田妹ダンジョン", "土間うまる(CV:田中あいみ)/海老名菜々(CV:影山灯)", 1],
    [6, "ダラけ×しゅぎょーDIARY!", "土間うまる(CV:田中あいみ)/本場切絵(CV:白石晴香)", 1],
    [7, "ゲ戦記うぉーず！", "土間うまる(CV:田中あいみ)/橘・シルフィンフォード(CV:古川由利奈)", 1],
    [8, "MUTEKINO SISTER FANTASY", "妹S", 1],
    [9, "トワ・エ・モア (Instrumental)", "土間うまる(CV:田中あいみ)", 1],
    [10, "7th Heart (Instrumental)", "海老名菜々(CV:影山灯)", 1],
    [11, "未完成マイヒーロー (Instrumental)", "本場切絵(CV:白石晴香)", 1],
    [12, "いつかきっと (Instrumental)", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [13, "海老名ちゃんのフリー秋田妹ダンジョン (Instrumental)", "土間うまる(CV:田中あいみ)/海老名菜々(CV:影山灯)", 1],
    [14, "ダラけ×しゅぎょーDIARY! (Instrumental)", "土間うまる(CV:田中あいみ)/本場切絵(CV:白石晴香)", 1],
    [15, "ゲ戦記うぉーず！ (Instrumental)", "土間うまる(CV:田中あいみ)/橘・シルフィンフォード(CV:古川由利奈)", 1],
    [16, "MUTEKINO SISTER FANTASY (Instrumental)", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/8990a9ef-41f3-4285-9fed-7fd61f9a890a", "https://vgmdb.net/album/72359"]

[981b445a106cb66b651f4ab66a5b6230]
catalognumber = "THCA-60200"
date = "2018-01-17"
album = "TVアニメ「干物妹!うまるちゃんR」 オリジナルサウンドトラック"
tracks = [
    [1, "ぐーたら生活R その1", "三澤康広", 1],
    [2, "ぐーたら生活R その2", "三澤康広", 1],
    [3, "良い終わり その1", "三澤康広", 1],
    [4, "良い終わり その2", "三澤康広", 1],
    [5, "サッカーはチーム戦!", "三澤康広", 1],
    [6, "ハルちゃん", "三澤康広", 1],
    [7, "外うまるの日常", "三澤康広", 1],
    [8, "ぺっぺー", "三澤康広", 1],
    [9, "耳垢うまる", "三澤康広", 1],
    [10, "わたくしの家にご招待したいですわ!!", "三澤康広", 1],
    [11, "探偵王ナコン その1", "三澤康広", 1],
    [12, "探偵王ナコン その2", "三澤康広", 1],
    [13, "イモバク", "三澤康広", 1],
    [14, "もぐもぐウォッチング", "三澤康広", 1],
    [15, "シルフィンとアレックス", "三澤康広", 1],
    [16, "ナック その1", "三澤康広", 1],
    [17, "ナック その2", "三澤康広", 1],
    [18, "クリスマスにみんなで", "三澤康広", 1],
    [19, "ダイヤモンドサービス", "三澤康広", 1],
    [20, "会社案内", "三澤康広", 1],
    [21, "切絵の絵本", "三澤康広", 1],
    [22, "どこまでもついていきますR その1", "三澤康広", 1],
    [23, "どこまでもついていきますR その2", "三澤康広", 1],
    [24, "ヒカリちゃんとタイヘイ", "三澤康広", 1],
    [25, "ひとりぼっちの留守番", "三澤康広", 1],
    [26, "夏祭り", "三澤康広", 1],
    [27, "夏休み!", "三澤康広", 1],
    [28, "ヒカリちゃん その1", "三澤康広", 1],
    [29, "ヒカリちゃん その2", "三澤康広", 1],
    [30, "うまるちゃんとお兄ちゃんR", "三澤康広", 1],
    [31, "ここが天国だ! R", "三澤康広", 1],
    [32, "ゾンビパラダイス", "三澤康広", 1],
    [33, "「スペ4」ナンバー1決定戦", "三澤康広", 1],
    [34, "プラザGAPCOM", "三澤康広", 1],
    [35, "海老名ちゃんの思い出", "三澤康広", 1],
    [36, "妖怪うまるネズミ その1", "三澤康広", 1],
    [37, "妖怪うまるネズミ その2", "三澤康広", 1],
    [38, "携帯ゲーム", "三澤康広", 1],
    [39, "スペ4", "三澤康広", 1],
    [40, "U.M.R VS T.S.F", "三澤康広", 1],
    [41, "ギュイーン", "三澤康広", 1],
    [42, "タイヘイの人生", "三澤康広", 1],
    [43, "きりえの人生", "三澤康広", 1],
    [44, "妹戦隊 うまるんジャー", "三澤康広", 1],
    [45, "刑事たちの物語 (あんぱんと牛乳)", "三澤康広", 1],
    [46, "うまるとお兄ちゃんの日常", "三澤康広", 1],
    [47, "うまるとお兄ちゃんの日常 ゆったり", "三澤康広", 1],
    [48, "かくしん的☆めたまるふぉ～ぜっ! [GAME Ver.]", "三澤康広", 1],
    [49, "ひだまりデイズ [GAME Ver.]", "三澤康広", 1],
    [50, "Map", "三澤康広", 1],
    [51, "Battle", "三澤康広", 1],
    [52, "BossBattle", "三澤康広", 1],
    [53, "Clear", "三澤康広", 1],
    [54, "GameOver", "三澤康広", 1],
]
links = ["https://beta.musicbrainz.org/release/8ca0abed-e195-498a-9f59-b78f085e2f78", "https://vgmdb.net/album/72360"]

[2f96582fd6643886bbce3e83ae2ca022]
catalognumber = "TBR32047D-5~6"
date = "2022-09-21"
album = "干物妹! うまるちゃん CHARACTER SONG FULL COMPLETE CD Disc 1 [TBR32047D-5]"
tracks = [
    [1, "かくしん的☆めたまるふぉ〜ぜっ!", "土間うまる(CV:田中あいみ)", 1],
    [2, "Sisters Wink", "妹S", 1],
    [3, "ひだまりデイズ", "妹S", 1],
    [4, "フィーバー夏Vacation!", "妹S", 1],
    [5, "勇者うまるの華麗なる生活", "土間うまる(CV:田中あいみ)", 1],
    [6, "Beautiful Days", "土間うまる(CV:田中あいみ)", 1],
    [7, "sweet sweet everytime sweet", "海老名菜々(CV:影山灯)", 1],
    [8, "そいだばね", "海老名菜々(CV:影山灯)", 1],
    [9, "My Precious", "本場切絵(CV:白石晴香)", 1],
    [10, "トトファンタジア", "本場切絵(CV:白石晴香)", 1],
    [11, "T・S・F in にっぽん!", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [12, "シュバッとNo.1", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [13, "Dreamy Friends", "妹S", 1],
    [14, "ふわり綿飴 美味しくなあれ", "妹S", 1],
    [15, "Happy Nightmare 〜妹達の饗宴〜", "妹S", 1],
    [16, "X’mas Decoration", "妹S", 1],
    [17, "パラダイス☆しんどろ〜むっ!", "妹S", 1],
    [18, "かくしん的☆めたまるふぉ〜ぜっ! -TV size ver.-", "土間うまる(CV:田中あいみ)", 1],
    [19, "ひだまりデイズ -TV size ver.-", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/4d5ddd7c-383f-495d-ac8e-c4cc0b0f4766", "https://vgmdb.net/album/121254"]

[f18b0425793b74413eee2c8a54364e4e]
catalognumber = "TBR32047D-5~6"
date = "2022-09-21"
album = "干物妹! うまるちゃん CHARACTER SONG FULL COMPLETE CD Disc 2 [TBR32047D-6]"
tracks = [
    [1, "にめんせい☆ウラオモテライフ!", "土間うまる(CV:田中あいみ)", 1],
    [2, "うるとら☆まじかる☆りれーしょん", "土間うまる(CV:田中あいみ)", 1],
    [3, "うまるん体操", "妹S", 1],
    [4, "変わらない宝物", "妹S", 1],
    [5, "トワ・エ・モア", "土間うまる(CV:田中あいみ)", 1],
    [6, "7th Heart", "海老名菜々(CV:影山灯)", 1],
    [7, "未完成マイヒーロー", "本場切絵(CV:白石晴香)", 1],
    [8, "いつかきっと", "橘・シルフィンフォード(CV:古川由利奈)", 1],
    [9, "海老名ちゃんのフリー秋田妹ダンジョン", "土間うまる(CV:田中あいみ)/海老名菜々(CV:影山灯)", 1],
    [10, "ダラけ×しゅぎょーDIARY!", "土間うまる(CV:田中あいみ)/本場切絵(CV:白石晴香)", 1],
    [11, "ゲ戦記うぉーず!", "土間うまる(CV:田中あいみ)/橘・シルフィンフォード(CV:古川由利奈)", 1],
    [12, "MUTEKINO SISTER FANTASY", "妹S", 1],
    [13, "にめんせい☆ウラオモテライフ! -TV size ver.-", "土間うまる(CV:田中あいみ)", 1],
    [14, "うまるん体操 -TV size ver.-", "妹S", 1],
]
links = ["https://beta.musicbrainz.org/release/4d5ddd7c-383f-495d-ac8e-c4cc0b0f4766", "https://vgmdb.net/album/121254"]
