[e747e3f3784d36eabf5984f88fd7ce3b]
catalognumber = "VTCL-35313"
date = "2020-02-05"
album = "歩いていこう! / 東山奈央 [アニメ盤]"
tracks = [
    [1, "歩いていこう!", "東山奈央", 0],
    [2, "Last Season", "東山奈央", 0],
    [3, "FLOWER", "東山奈央", 0],
    [4, "歩いていこう! (Instrumental ver.)", "東山奈央", 0],
    [5, "Last Season (Instrumental ver.)", "東山奈央", 0],
    [6, "FLOWER (Instrumental ver.)", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/93330", "https://beta.musicbrainz.org/release/4a1d7fde-abd1-4aba-93fb-52d7aab5c5d2"]

[fe8a701bf7031cba19793719b45d764e]
catalognumber = "VTZL-165"
date = "2020-02-05"
album = "歩いていこう! / 東山奈央 Disc 1 (CD) [VTCL-35312]"
tracks = [
    [1, "歩いていこう!", "東山奈央", 0],
    [2, "Last Season", "東山奈央", 0],
    [3, "Lost Thorn In My Side", "東山奈央", 0],
    [4, "歩いていこう! (Instrumental ver.)", "東山奈央", 0],
    [5, "Last Season (Instrumental ver.)", "東山奈央", 0],
    [6, "Lost Thorn In My Side (Instrumental ver.)", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/93331", "https://beta.musicbrainz.org/release/22b43f88-7ea6-4ba4-acec-3e8162ba7843"]

[b551c2070ea791664cb2247fbf4385b7]
catalognumber = "VTZL-165"
date = "2020-02-05"
album = "歩いていこう! / 東山奈央 Disc 2 (DVD) [VTBY-170]"
tracks = [
    [1, "歩いていこう! Music Clip", "東山奈央", 0],
    [2, "歩いていこう! Making Movie", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/93331", "https://beta.musicbrainz.org/release/22b43f88-7ea6-4ba4-acec-3e8162ba7843"]

[1e85696beb624c78c6a164c3f534b2d3]
catalognumber = "VTCL-35312"
date = "2020-02-05"
album = "歩いていこう! / 東山奈央"
tracks = [
    [1, "歩いていこう!", "東山奈央", 0],
    [2, "Last Season", "東山奈央", 0],
    [3, "Lost Thorn In My Side", "東山奈央", 0],
    [4, "歩いていこう! (Instrumental ver.)", "東山奈央", 0],
    [5, "Last Season (Instrumental ver.)", "東山奈央", 0],
    [6, "Lost Thorn In My Side (Instrumental ver.)", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/93329", "https://beta.musicbrainz.org/release/c8343146-b256-413b-9759-d7e43eb50e47"]

[292d68844e34d9231be6ae834b1b9a3f]
catalognumber = "VTCL-35311"
date = "2020-02-12"
album = "夜空 / 鈴木みのり"
tracks = [
    [1, "夜空", "鈴木みのり", 0],
    [2, "まぼろし", "鈴木みのり", 0],
    [3, "いっせーのーでっ!", "鈴木みのり", 0],
    [4, "夜空 -Instrumental-", "鈴木みのり", 0],
    [5, "まぼろし -Instrumental-", "鈴木みのり", 0],
    [6, "いっせーのーでっ! -Instrumental-", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/93338", "https://beta.musicbrainz.org/release/1bab55f2-0d39-47f6-96b8-cb6ccbc8af15"]

[dabc4d4d25a45a6b698e5a24adcc8c2f]
catalognumber = "VTZL-166"
date = "2020-02-12"
album = "夜空 / 鈴木みのり [初回限定盤A] Disc 1 (CD) [VTCL-35311]"
tracks = [
    [1, "夜空", "鈴木みのり", 0],
    [2, "まぼろし", "鈴木みのり", 0],
    [3, "いっせーのーでっ!", "鈴木みのり", 0],
    [4, "夜空 -Instrumental-", "鈴木みのり", 0],
    [5, "まぼろし -Instrumental-", "鈴木みのり", 0],
    [6, "いっせーのーでっ! -Instrumental-", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/93339", "https://beta.musicbrainz.org/release/9cdc7bbc-c39e-4b54-b68c-9a6fbf37000b"]

[62597ef1c16bbe048fdcf8a130a8667f]
catalognumber = "VTZL-166"
date = "2020-02-12"
album = "夜空 / 鈴木みのり [初回限定盤A] Disc 2 (Blu-ray) [VTXY-93]"
tracks = [
    [1, "夜空 Music Video", "鈴木みのり", 0],
    [2, "メイキング映像", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/93339", "https://beta.musicbrainz.org/release/9cdc7bbc-c39e-4b54-b68c-9a6fbf37000b"]

[1cf611c8542526e95a9a55c03fc812b5]
catalognumber = "VTZL-167"
date = "2020-02-12"
album = "夜空 / 鈴木みのり [付初回限定盤B] Vocal, Live Event"
tracks = [
    [1, "おセンチなメンタル", "鈴木みのり", 0],
    [2, "こいもよう", "鈴木みのり", 0],
    [3, "astro traveler", "鈴木みのり", 0],
    [4, "ダメハダメ", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/93340", "https://beta.musicbrainz.org/release/fbf61143-7ba8-4eba-b55d-cbd3929280e4"]

[c206bf2a139db594ba8b4883b6626acd]
catalognumber = "VTZL-167"
date = "2020-02-12"
album = "夜空 / 鈴木みのり [付初回限定盤B] Vocal"
tracks = [
    [1, "夜空", "鈴木みのり", 0],
    [2, "まぼろし", "鈴木みのり", 0],
    [3, "いっせーのーでっ!", "鈴木みのり", 0],
    [4, "夜空 -Instrumental-", "鈴木みのり", 0],
    [5, "まぼろし -Instrumental-", "鈴木みのり", 0],
    [6, "いっせーのーでっ! -Instrumental-", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/93340", "https://beta.musicbrainz.org/release/fbf61143-7ba8-4eba-b55d-cbd3929280e4"]

[e751c8c97d452d8c79367aaf774e56a4]
catalognumber = "VTCL-60521"
date = "2020-03-25"
album = "TVアニメ「恋する小惑星」サウンドコレクション"
tracks = [
    [1, "Asteroid in Love", "伊賀拓郎", 0],
    [2, "ワクワク！", "伊賀拓郎", 0],
    [3, "地学部活動 1 自己紹介", "伊賀拓郎", 0],
    [4, "地学部活動 2 浮き立つ心", "伊賀拓郎", 0],
    [5, "祝！第 1 回地学部会議！", "伊賀拓郎", 0],
    [6, "地学部活動 3 石探し", "伊賀拓郎", 0],
    [7, "憧れの人", "伊賀拓郎", 0],
    [8, "人見知りと距離感について", "伊賀拓郎", 0],
    [9, "一緒に", "伊賀拓郎", 0],
    [10, "鉢巻石", "伊賀拓郎", 0],
    [11, "先生に優しく", "伊賀拓郎", 0],
    [12, "尾行開始", "伊賀拓郎", 0],
    [13, "ほのぼのおしゃべり", "伊賀拓郎", 0],
    [14, "お話しようよ", "伊賀拓郎", 0],
    [15, "地学部活動 4 検証", "伊賀拓郎", 0],
    [16, "憧れの場所", "伊賀拓郎", 0],
    [17, "夏合宿", "伊賀拓郎", 0],
    [18, "宇宙は遠い", "伊賀拓郎", 0],
    [19, "憧憬", "伊賀拓郎", 0],
    [20, "見上げる先に", "伊賀拓郎", 0],
    [21, "口下手", "伊賀拓郎", 0],
    [22, "プカプカバカンス", "伊賀拓郎", 0],
    [23, "偵察", "伊賀拓郎", 0],
    [24, "EyeCatch", "伊賀拓郎", 0],
    [25, "旅立ち", "伊賀拓郎", 0],
    [26, "寂しい気持ち", "伊賀拓郎", 0],
    [27, "静かに", "伊賀拓郎", 0],
    [28, "侃々諤々", "伊賀拓郎", 0],
    [29, "どたばた", "伊賀拓郎", 0],
    [30, "石垣島", "伊賀拓郎", 0],
    [31, "優しく", "伊賀拓郎", 0],
    [32, "広い空へ", "伊賀拓郎", 0],
    [33, "あの星の向こうに", "木ノ幡みら（CV：高柳知葉）", 0],
    [34, "ちっぽけな願いごと", "桜井美景（CV：東山奈央）", 0],
    [35, "ココロアトラス", "猪瀬舞（CV：指出毬亜）", 0],
    [36, "ポラリスをみつけたら", "森野真理（CV：上坂すみれ）", 0],
    [37, "君と見た星", "真中あお（CV：山口愛）", 0],
]
links = ["https://vgmdb.net/album/95639", "https://beta.musicbrainz.org/release/ab57667a-6c5b-4543-9415-bda0f2babd9e"]

[2cbc26a421a34701e9c1babb6cc35ba4]
catalognumber = "VTZL-175"
date = "2020-08-26"
album = "上ミノ / 鈴木みのり Vocal"
tracks = [
    [1, "Now Is The Time!", "鈴木みのり", 0],
    [2, "ダメハダメ (Album Ver.)", "鈴木みのり", 0],
    [3, "わからないのよBABY", "鈴木みのり", 0],
    [4, "まいっちゃう", "鈴木みのり", 0],
    [5, "最果てのハロー", "鈴木みのり", 0],
    [6, "まぼろし", "鈴木みのり", 0],
    [7, "月夜の夢", "鈴木みのり", 0],
    [8, "夜空", "鈴木みのり", 0],
    [9, "gloria", "鈴木みのり", 0],
    [10, "こいもよう", "鈴木みのり", 0],
    [11, "茜空、私がいた街", "鈴木みのり", 0],
    [12, "エフェメラをあつめて", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/100726", "https://beta.musicbrainz.org/release/41318640-83d1-446e-8c4c-083029da6966"]

[924121a8e8c857975aad7541d7b42ea4]
catalognumber = "VTZL-175"
date = "2020-08-26"
album = "上ミノ / 鈴木みのり Vocal, Video"
tracks = [
    [1, "ダメハダメ Music Video", "鈴木みのり", 0],
    [2, "エフェメラをあつめて Music Video", "鈴木みのり", 0],
    [3, "出張版みのりんご～映える「肉パフェ」作って食べてみた!～", "鈴木みのり", 0],
    [4, "出張版みのりんご～大量のTシャツ脱いでみた?!～", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/100726", "https://beta.musicbrainz.org/release/41318640-83d1-446e-8c4c-083029da6966"]

[6ace101234d6f3d0a1463c0fe2ac2bf7]
catalognumber = "VTCL-60531"
date = "2020-08-26"
album = "上ミノ / 鈴木みのり"
tracks = [
    [1, "Now Is The Time!", "鈴木みのり", 0],
    [2, "ダメハダメ (Album Ver.)", "鈴木みのり", 0],
    [3, "わからないのよBABY", "鈴木みのり", 0],
    [4, "まいっちゃう", "鈴木みのり", 0],
    [5, "最果てのハロー", "鈴木みのり", 0],
    [6, "まぼろし", "鈴木みのり", 0],
    [7, "月夜の夢", "鈴木みのり", 0],
    [8, "夜空", "鈴木みのり", 0],
    [9, "gloria", "鈴木みのり", 0],
    [10, "こいもよう", "鈴木みのり", 0],
    [11, "茜空、私がいた街", "鈴木みのり", 0],
    [12, "エフェメラをあつめて", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/100727", "https://beta.musicbrainz.org/release/068f6837-43f0-43f8-a87e-d2b5a0ba1de5"]

[18f807c838f15c90f90129bf489269cc]
catalognumber = "VTZL-202"
date = "2022-06-01"
album = "BROKEN IDENTITY / 鈴木みのり [初回限定盤B] Vocal"
tracks = [
    [1, "BROKEN IDENTITY", "鈴木みのり", 0],
    [2, "リップ", "鈴木みのり", 0],
    [3, "ときめきの時空と林檎", "鈴木みのり", 0],
    [4, "BROKEN IDENTITY (Instrumental)", "鈴木みのり", 0],
    [5, "リップ (Instrumental)", "鈴木みのり", 0],
    [6, "ときめきの時空と林檎 (Instrumental)", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/118924", "https://beta.musicbrainz.org/release/bc3fec66-69c8-456d-af13-53fa60fbf60a"]

[e9742330e420f0a38a8d7ebfcaf1c366]
catalognumber = "VTZL-202"
date = "2022-06-01"
album = "BROKEN IDENTITY / 鈴木みのり [初回限定盤B] Vocal, Live Event"
tracks = [
    [1, "Now Is The Time!", "鈴木みのり", 0],
    [2, "半音階のレジスタンス", "鈴木みのり", 0],
    [3, "わからないのよBABY", "鈴木みのり", 0],
    [4, "まいっちゃう", "鈴木みのり", 0],
    [5, "夜空", "鈴木みのり", 0],
    [6, "gloria", "鈴木みのり", 0],
    [7, "リワインド", "鈴木みのり", 0],
    [8, "茜空、私がいた街", "鈴木みのり", 0],
    [9, "エフェメラをあつめて", "鈴木みのり", 0],
    [10, "Crosswalk", "鈴木みのり", 0],
    [11, "いっせーのーでっ！", "鈴木みのり", 0],
]
links = ["https://vgmdb.net/album/118924", "https://beta.musicbrainz.org/release/bc3fec66-69c8-456d-af13-53fa60fbf60a"]

[7ec81faf8fb60baae0e47c18d71ebf99]
catalognumber = "VTZL-214"
date = "2022-09-28"
album = "Welcome to MY WONDERLAND / 東山奈央 [初回限定盤] Vocal"
tracks = [
    [1, "After the Rain -instrumental-", "東山奈央", 0],
    [2, "ウェルカム・トゥ・レインボーワンダーランド!", "東山奈央", 0],
    [3, "Growing", "東山奈央", 0],
    [4, "冷めない魔法", "東山奈央", 0],
    [5, "硝子の夜", "東山奈央", 0],
    [6, "Brand New Show", "東山奈央", 0],
    [7, "クラクラ", "東山奈央", 0],
    [8, "de messiah", "東山奈央", 0],
    [9, "歩いていこう!", "東山奈央", 0],
    [10, "Magic hour", "東山奈央", 0],
    [11, "あの日のことば", "東山奈央", 0],
    [12, "サファイア・タウン・トワイライト", "東山奈央", 0],
    [13, "OVER!!", "東山奈央", 0],
    [14, "After the Rainbow -instrumental-", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/121832", "https://beta.musicbrainz.org/release/a178d6e4-935a-4401-91ba-fb11a80827c1"]

[fbade8f1db5070a056450c398e629afd]
catalognumber = "VTZL-214"
date = "2022-09-28"
album = "Welcome to MY WONDERLAND / 東山奈央 [初回限定盤] Vocal, Video"
tracks = [
    [1, "なおぼうGP! ～テーマパーク編～", "東山奈央", 0],
    [2, "歩いていこう! (MUSIC VIDEO)", "東山奈央", 0],
    [3, "off (MUSIC VIDEO)", "東山奈央", 0],
    [4, "グー (MUSIC VIDEO)", "東山奈央", 0],
    [5, "冷めない魔法 (MUSIC VIDEO)", "東山奈央", 0],
    [6, "あの日のことば (MUSIC VIDEO)", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/121832", "https://beta.musicbrainz.org/release/a178d6e4-935a-4401-91ba-fb11a80827c1"]

[378f9faf75328b068f5fef48661b64c9]
catalognumber = "VTCL-60567"
date = "2022-09-28"
album = "Welcome to MY WONDERLAND / 東山奈央"
tracks = [
    [1, "After the Rain -instrumental-", "東山奈央", 0],
    [2, "ウェルカム・トゥ・レインボーワンダーランド!", "東山奈央", 0],
    [3, "Growing", "東山奈央", 0],
    [4, "冷めない魔法", "東山奈央", 0],
    [5, "硝子の夜", "東山奈央", 0],
    [6, "Brand New Show", "東山奈央", 0],
    [7, "クラクラ", "東山奈央", 0],
    [8, "de messiah", "東山奈央", 0],
    [9, "歩いていこう!", "東山奈央", 0],
    [10, "Magic hour", "東山奈央", 0],
    [11, "あの日のことば", "東山奈央", 0],
    [12, "サファイア・タウン・トワイライト", "東山奈央", 0],
    [13, "OVER!!", "東山奈央", 0],
    [14, "After the Rainbow -instrumental-", "東山奈央", 0],
]
links = ["https://vgmdb.net/album/121831", "https://beta.musicbrainz.org/release/fc520a35-ea99-439d-8991-be8df1a9965c"]
