[d852847be98ffae7f38348c5eb853718]
catalognumber = "PCXG-50181-2"
date = "2012-11-30"
album = "新世界より オリジナルサウンドトラックCD①"
tracks = [
    [1, "陰の伝承歌 第一部", "小森茂生", 1],
    [2, "Darkside of Heart", "小森茂生", 1],
    [3, "Quiet Village", "小森茂生", 1],
    [4, "Dark Village", "小森茂生", 1],
    [5, "Akki", "小森茂生", 1],
    [6, "Theme of Daikangi-tei", "小森茂生", 1],
    [7, "Sign of Jyuryouku", "小森茂生", 1],
    [8, "Friendship", "小森茂生", 1],
    [9, "Night Canoe", "小森茂生", 1],
    [10, "Daily Pleasure", "小森茂生", 1],
    [11, "Game Battle #1", "小森茂生", 1],
    [12, "Loneliness", "小森茂生", 1],
    [13, "Strange Feeling", "小森茂生", 1],
    [14, "Time Lapse", "小森茂生", 1],
    [15, "Down The River", "小森茂生", 1],
    [16, "Battle Mode PI #1", "小森茂生", 1],
    [17, "Battle Mode PA #2", "小森茂生", 1],
    [18, "Creeping Crisis", "小森茂生", 1],
    [19, "Deep Forest #2", "小森茂生", 1],
    [20, "Confession", "小森茂生", 1],
    [21, "Sad Song", "小森茂生", 1],
    [22, "割れたリンゴ (TV edit)", "渡辺早季(CV：種田梨沙)", 1],
]
links = ["https://beta.musicbrainz.org/release/879462cb-b59b-4455-a68c-800002485bb1", "https://vgmdb.net/album/35452"]

[9311405f696683fb4a1a14eda461ac12]
catalognumber = "PCCG-70156"
date = "2013-01-25"
album = "割れたリンゴ / 雪に咲く花"
tracks = [
    [1, "割れたリンゴ", "渡辺早季(CV：種田梨沙)", 1],
    [2, "雪に咲く花", "秋月真理亜(CV：花澤香菜)", 1],
    [3, "割れたリンゴ (Instrumental)", "渡辺早季(CV：種田梨沙)", 1],
    [4, "雪に咲く花 (Instrumental)", "秋月真理亜(CV：花澤香菜)", 1],
]
links = ["https://beta.musicbrainz.org/release/91367afc-a828-4f43-9723-a9a006f5ff70", "https://vgmdb.net/album/36473"]

[fbb029a86097c86efc8efae739dcd581]
catalognumber = "PCXG-50184-2"
date = "2013-02-20"
album = "新世界より オリジナルサウンドトラックCD②"
tracks = [
    [1, "陰の伝承歌 第二部", "小森茂生", 1],
    [2, "Fight with Tuchigumo", "小森茂生", 1],
    [3, "Fear The Underground", "小森茂生", 1],
    [4, "Encounter with Minoshiromodoki", "小森茂生", 1],
    [5, "Strange Story", "小森茂生", 1],
    [6, "View Of Riverside", "小森茂生", 1],
    [7, "Tenderness", "小森茂生", 1],
    [8, "Sad Love", "小森茂生", 1],
    [9, "History Of Sorrow", "小森茂生", 1],
    [10, "History Of Dispair", "小森茂生", 1],
    [11, "Puzzle Of Nekodamashi", "小森茂生", 1],
    [12, "Game Battle #2", "小森茂生", 1],
    [13, "Hateful Feeling", "小森茂生", 1],
    [14, "Deep Forest #1", "小森茂生", 1],
    [15, "Battle Mode PI #2", "小森茂生", 1],
    [16, "Battle Mode PA #1", "小森茂生", 1],
    [17, "Battle Adovantage #3", "小森茂生", 1],
    [18, "Strain Of Fight #1", "小森茂生", 1],
    [19, "Doutful One", "小森茂生", 1],
    [20, "Mysterious", "小森茂生", 1],
    [21, "Secret #1", "小森茂生", 1],
    [22, "Settled Life Again", "小森茂生", 1],
]
links = ["https://beta.musicbrainz.org/release/91c35094-8f34-4138-a16e-f0762a21caec", "https://vgmdb.net/album/37111"]

[acea3a318a8b1886f986510af34bf7d2]
catalognumber = "PCXG-50187-2"
date = "2013-05-24"
album = "新世界より オリジナルサウンドトラックCD③"
tracks = [
    [1, "陰の伝承歌 第三部", "小森茂生", 1],
    [2, "Calm World", "小森茂生", 1],
    [3, "Gouma", "小森茂生", 1],
    [4, "Place Of Bakenezumi", "小森茂生", 1],
    [5, "Tokyo Underground", "小森茂生", 1],
    [6, "Anger", "小森茂生", 1],
    [7, "Battle Advantage #1", "小森茂生", 1],
    [8, "Relief", "小森茂生", 1],
    [9, "Peace Of Mind", "小森茂生", 1],
    [10, "Memory Of Shun", "小森茂生", 1],
    [11, "Goes To The School", "小森茂生", 1],
    [12, "Original Sin (Piano Mix)", "小森茂生", 1],
    [13, "Battle Advantage #2", "小森茂生", 1],
    [14, "Strain Of Fight #2", "小森茂生", 1],
    [15, "Game Battle #2", "小森茂生", 1],
    [16, "Last Letter", "小森茂生", 1],
    [17, "Goodbye To Childhood", "小森茂生", 1],
    [18, "Secret #2", "小森茂生", 1],
    [19, "Sad Separation", "小森茂生", 1],
    [20, "Original Sin (Strings Mix)", "小森茂生", 1],
    [21, "Hope For The Future", "小森茂生", 1],
    [22, "雪に咲く花 (TV edit)", "秋月真理亜(CV：花澤香菜)", 1],
    [23, "陰の伝承歌 第一部", "小森茂生", 1],
    [24, "陰の伝承歌 第二部", "小森茂生", 1],
    [25, "陰の伝承歌 第三部", "小森茂生", 1],
]
links = ["https://beta.musicbrainz.org/release/f67ea8c9-9192-4b9a-a7b9-fd312fae6564", "https://vgmdb.net/album/39691"]
