[c702ea8df51c1891b3f6b0e923ef0c2d]
catalognumber = "COZC-1009~10"
date = "2015-02-04"
album = "Blade of Hope / sweet ARMS [Limited Edition] Vocal"
tracks = [
    [1, "Blade of Hope", "sweet ARMS", 1],
    [2, "Fire Judgement", "sweet ARMS", 0],
    [3, "Blade of Hope (Another Version)", "sweet ARMS", 1],
    [4, "Blade of Hope -Instrumental-", "sweet ARMS", 1],
    [5, "Fire Judgement -Instrumental-", "sweet ARMS", 0],
    [6, "Blade of Hope (Another Version) -Instrumental-", "sweet ARMS", 1],
]
links = ["https://beta.musicbrainz.org/release/d3347313-0fb7-428c-aa33-ef3b3b01d6fc", "https://vgmdb.net/album/49191"]

[c054bd422e3e905c3a8236c7b9f7e91f]
catalognumber = "COZC-1009~10"
date = "2015-02-04"
album = "Blade of Hope / sweet ARMS [Limited Edition] Vocal, Video"
tracks = [
    [1, "Blade of Hope (PV)", "", 1],
    [2, "Blade of Hope (Making)", "", 1],
]
links = ["https://vgmdb.net/album/49191"]

[2f9e92efd14d3f1196cfcca09385f7f4]
catalognumber = "COZC-1011~2"
date = "2015-02-04"
album = "Still Sis / 佐土原かおり Disc 1 (CD) [COZC-1011]"
tracks = [
    [1, "Still Sis", "佐土原かおり", 0],
    [2, "Gift", "佐土原かおり", 0],
    [3, "Still Sis (Another Version)", "佐土原かおり", 0],
    [4, "Still Sis -Instrumental-", "佐土原かおり", 0],
    [5, "Gift -Instrumental-", "佐土原かおり", 0],
    [6, "Still Sis (Another Version) -Instrumental-", "佐土原かおり", 0],
]
links = ["https://beta.musicbrainz.org/release/1ee734fc-1558-47d1-b5f7-1894a89c36a9", "https://vgmdb.net/album/49193"]

[88c52659e64ff0a52637023eb10790b1]
catalognumber = "COZC-1011~2"
date = "2015-02-04"
album = "Still Sis / 佐土原かおり Disc 2 (DVD) [COZC-1012]"
tracks = [
    [1, "Still Sis (PV)", "", 0],
    [2, "Still Sis (Making)", "", 0],
]
links = ["https://vgmdb.net/album/49193"]

[d75604f815a51e1d8bff2e38cb3d625f]
catalognumber = "COCC-16969"
date = "2015-02-04"
album = "Blade of Hope / sweet ARMS"
tracks = [
    [1, "Blade of Hope", "sweet ARMS", 1],
    [2, "Fire Judgement", "sweet ARMS", 0],
    [3, "Blade of Hope (Another Version)", "sweet ARMS", 1],
    [4, "Blade of Hope -Instrumental-", "sweet ARMS", 1],
    [5, "Fire Judgement -Instrumental-", "sweet ARMS", 0],
    [6, "Blade of Hope (Another Version) -Instrumental-", "sweet ARMS", 1],
]
links = ["https://beta.musicbrainz.org/release/d5536253-46ec-4f0b-9b3c-9b619a3c1048", "https://vgmdb.net/album/49190"]

[e04aeadfae23481803999a0ba29354da]
catalognumber = "COCC-16970"
date = "2015-02-04"
album = "Still Sis / 佐土原かおり"
tracks = [
    [1, "Still Sis", "佐土原かおり", 0],
    [2, "Gift", "佐土原かおり", 0],
    [3, "Still Sis (Another Version)", "佐土原かおり", 0],
    [4, "Still Sis -Instrumental-", "佐土原かおり", 0],
    [5, "Gift -Instrumental-", "佐土原かおり", 0],
    [6, "Still Sis (Another Version) -Instrumental-", "佐土原かおり", 0],
]
links = ["https://beta.musicbrainz.org/release/94785ba5-d01f-453a-afce-4b7e7a9e345c", "https://vgmdb.net/album/49192"]

[d85a60a6ad5d395c26af46216c4654cf]
catalognumber = "COCX-38991"
date = "2015-03-04"
album = "新妹魔王の契約者(テスタメント) 臨界突破の絶頂音楽集"
tracks = [
    [1, "Blade of Hope (TV size)", "sweet ARMS", 1],
    [2, "「新妹魔王の契約者」メインテーマ", "高梨康治", 1],
    [3, "解かれし封印", "高梨康治", 1],
    [4, "魔王ウィルベルトの娘", "高梨康治", 1],
    [5, "100回殺すわよ", "高梨康治", 1],
    [6, "主従契約魔法", "高梨康治", 1],
    [7, "だって妹だから", "高梨康治", 1],
    [8, "こんなこと恥ずかしいけど…", "高梨康治", 1],
    [9, "てめーの顔ほどダサくねーよ", "高梨康治", 1],
    [10, "ふふふのふ", "高梨康治", 1],
    [11, "こう見えて魔族でして", "高梨康治", 1],
    [12, "悪夢の予兆", "高梨康治", 1],
    [13, "世界を敵に回しても", "高梨康治", 1],
    [14, "よみがえる悲しみ", "高梨康治", 1],
    [15, "お兄ちゃんと呼ばせて", "高梨康治", 1],
    [16, "いいかげんに離れなさいよ！", "高梨康治", 1],
    [17, "美しきライバル", "高梨康治", 1],
    [18, "華麗なる対決", "高梨康治", 1],
    [19, "暗躍する影", "高梨康治", 1],
    [20, "魔界への誘い", "高梨康治", 1],
    [21, "惨劇の果てに", "高梨康治", 1],
    [22, "冥い計略", "高梨康治", 1],
    [23, "邪悪な魔手", "高梨康治", 1],
    [24, "勇者の血", "高梨康治", 1],
    [25, "覚悟の戦陣", "高梨康治", 1],
    [26, "魔剣ブリュンヒルド", "高梨康治", 1],
    [27, "あなたのそばで眠りたい", "高梨康治", 1],
    [28, "ビコーズ", "成瀬澪(CV:朝井彩加)", 0],
    [29, "Sweet Heart", "成瀬万理亜(CV:福原香織)", 0],
    [30, "Blooming", "野中柚希(CV:ブリドカットセーラ恵美)", 1],
]
links = ["https://beta.musicbrainz.org/release/aa5cdb9c-c0b0-4454-bd48-e7c2fe15e487", "https://vgmdb.net/album/50277"]

[6042445b85d9840dd00cdc01655da8bc]
catalognumber = "COCX-39053"
date = "2015-03-25"
album = "新妹魔王の契約者(テスタメント) 臨界突破の悦楽音楽集"
tracks = [
    [1, "刃更", "高梨康治", 1],
    [2, "勇魔激突", "高梨康治", 1],
    [3, "勇者のやさしさ", "高梨康治", 1],
    [4, "ミステリアスな瞳", "高梨康治", 1],
    [5, "ほんとはうれしいくせに", "高梨康治", 1],
    [6, "なんで入ってくるのよ", "高梨康治", 1],
    [7, "ふるえる心", "高梨康治", 1],
    [8, "危ないやつら", "高梨康治", 1],
    [9, "お前だけは許せない", "高梨康治", 1],
    [10, "魔法をかけられて", "高梨康治", 1],
    [11, "甘いささやき", "高梨康治", 1],
    [12, "お兄ちゃんのバカ", "高梨康治", 1],
    [13, "超・刺・激・的", "高梨康治", 1],
    [14, "光ある世界", "高梨康治", 1],
    [15, "Blade of Hope ～Lyrical Arrange～", "睦月周平", 1],
    [16, "闇からの呼び声", "高梨康治", 1],
    [17, "荒ぶる魔人", "高梨康治", 1],
    [18, "守り抜く闘志", "高梨康治", 1],
    [19, "故郷への遠い道", "高梨康治", 1],
    [20, "逃れられぬ運命", "高梨康治", 1],
    [21, "魔界のコラール", "高梨康治", 1],
    [22, "魔力目覚めるとき", "高梨康治", 1],
    [23, "魔王降臨", "高梨康治", 1],
    [24, "バニシングシフト", "高梨康治", 1],
    [25, "Tomorrow Never Knows", "高梨康治", 1],
    [26, "恋する悪魔", "高梨康治", 1],
    [27, "Still Sis(TVサイズ)", "佐土原かおり", 0],
    [28, "Dear My Darling", "成瀬澪 (CV:朝井彩加) & 成瀬万理亜 (CV:福原香織)", 1],
    [29, "Symphony Memory", "野中柚希 (CV:ブリドカットセーラ恵美) & 野中胡桃 (CV:野水いおり)", 0],
]
links = ["https://beta.musicbrainz.org/release/d8826772-9de3-410a-a622-c0f864405eba", "https://vgmdb.net/album/50416"]

[d9c1be26c65d1ebf8ffecd36af9d255c]
catalognumber = "KAXA-7232CD"
date = "2015-04-24"
album = "新妹魔王の契約者(テスタメント) 臨界突破!? エクスタCD!"
tracks = [
    [1, "成瀬澪", "", 0],
    [2, "野中柚希", "", 0],
    [3, "成瀬万理亜", "", 0],
]
links = ["https://vgmdb.net/album/52564"]

[fb2f42ad3329c5dbda6f4d99cfe394e4]
catalognumber = "COCC-17073"
date = "2015-11-04"
album = "Temperature / Dual Flare"
tracks = [
    [1, "Temperature", "Dual Flare", 0],
    [2, "OWN WAY", "Dual Flare", 0],
    [3, "あいのうた～believe～", "Dual Flare", 0],
    [4, "Temperature -Instrumental-", "Dual Flare", 0],
    [5, "OWN WAY -Instrumental-", "Dual Flare", 0],
    [6, "あいのうた～believe～ -Instrumental-", "Dual Flare", 0],
]
links = ["https://beta.musicbrainz.org/release/04a0f549-5dbf-476f-9267-9129ed179eb1", "https://vgmdb.net/album/54918"]

[193e654637d2342abfab509cf14f9664]
catalognumber = "COCC-17072"
date = "2015-11-04"
album = "Over The Testament / Metamorphose"
tracks = [
    [1, "Over The Testament (Ver.1)", "Metamorphose featuring Yoko Ishida", 0],
    [2, "Over The Testament (Ver.2)", "Metamorphose featuring Kaori Oda", 0],
    [3, "Over The Testament (Another Version)", "Metamorphose featuring Yoko and Kaori", 0],
    [4, "Over The Testament -Instrumental-", "Metamorphose", 0],
    [5, "Over The Testament (Another Version) -Instrumental-", "Metamorphose", 0],
]
links = ["https://beta.musicbrainz.org/release/34ed8e47-a2d8-4a15-95b1-b59d48e054eb", "https://vgmdb.net/album/54946"]

[4ab67a6fd2fbe6d3fc03903a313de6d9]
catalognumber = "COZC-1085~6"
date = "2015-11-04"
album = "Over The Testament / Metamorphose [Limited Edition] Disc 1 (CD) [COZC-1085]"
tracks = [
    [1, "Over The Testament (Ver.1)", "Metamorphose featuring Yoko Ishida", 0],
    [2, "Over The Testament (Ver.2)", "Metamorphose featuring Kaori Oda", 0],
    [3, "Over The Testament (Another Version)", "Metamorphose featuring Yoko and Kaori", 0],
    [4, "Over The Testament -Instrumental-", "Metamorphose", 0],
    [5, "Over The Testament (Another Version) -Instrumental-", "Metamorphose", 0],
]
links = ["https://beta.musicbrainz.org/release/106e38c1-af11-4a51-a55b-2101c0b135b8", "https://vgmdb.net/album/54947"]

[4ad6f5a24a0be908929bf66d4943e029]
catalognumber = "COZC-1085~6"
date = "2015-11-04"
album = "Over The Testament / Metamorphose [Limited Edition] Disc 2 (DVD) [COZC-1086]"
tracks = [
    [1, "Metamorphose Yoko Ishida Interview", "", 0],
    [2, "Metamorphose Kaori Oda Interview etc.", "", 0],
]
links = ["https://vgmdb.net/album/54947"]

[aea095b66b65a7dd286f7ee6d9dcc126]
catalognumber = "COZC-1087~8"
date = "2015-11-04"
album = "Temperature / Dual Flare [Limited Edition] Disc 1 (CD) [COZC-1087]"
tracks = [
    [1, "Temperature", "Dual Flare", 0],
    [2, "OWN WAY", "Dual Flare", 0],
    [3, "あいのうた～believe～", "Dual Flare", 0],
    [4, "Temperature -Instrumental-", "Dual Flare", 0],
    [5, "OWN WAY -Instrumental-", "Dual Flare", 0],
    [6, "あいのうた～believe～ -Instrumental-", "Dual Flare", 0],
]
links = ["https://beta.musicbrainz.org/release/e29dac8f-406b-4111-8bab-11570f62b747", "https://vgmdb.net/album/54919"]

[2f326c7c2eab34cdc41df1731b28ac79]
catalognumber = "COZC-1087~8"
date = "2015-11-04"
album = "Temperature / Dual Flare [Limited Edition] Disc 2 (DVD) [COZC-1088]"
tracks = [
    [1, "Temperature (Music Video)", "Dual Flare", 0],
    [2, "Dual Flare スペシャル映像", "Dual Flare", 0],
]
links = ["https://beta.musicbrainz.org/release/e29dac8f-406b-4111-8bab-11570f62b747", "https://vgmdb.net/album/54919"]

[2851805deb01b35c48984dbc30533652]
catalognumber = "COCX-39378"
date = "2015-12-16"
album = "Metamorphose 1"
tracks = [
    [1, "Over The Testament (Ver.1)", "Metamorphose featuring Yoko Ishida", 0],
    [2, "Over The Testament (Ver.2)", "Metamorphose featuring Kaori Oda", 0],
    [3, "Over The Testament (Ver.3)", "Metamorphose featuring Aki Misato", 0],
    [4, "Over The Testament (Ver.4)", "Metamorphose featuring Megumi Ogata", 0],
    [5, "体温", "Metamorphose featuring Yoko Ishida", 0],
    [6, "Refrain", "Metamorphose featuring Kaori Oda", 0],
    [7, "プロローグ", "Metamorphose featuring Aki Misato", 0],
    [8, "Beat the Wings!", "Metamorphose featuring Megumi Ogata", 1],
    [9, "Over The Testament (Ver.5)", "Metamorphose", 0],
]
links = ["https://beta.musicbrainz.org/release/81b46982-51f3-4cd7-ad0b-18ba4f2d7cef", "https://vgmdb.net/album/56266"]

[c3fa5677be6249464a15b739fa5c3921]
catalognumber = "COCX-39377"
date = "2015-12-16"
album = "新妹魔王の契約者(テスタメント) BURST Perfect Music Collection"
tracks = [
    [1, "Over The Testament (TV size)", "Metamorphose", 0],
    [2, "勇者の剣", "高梨康治(Team-MAX)", 1],
    [3, "魔風戦線", "高梨康治(Team-MAX)", 1],
    [4, "美しい人", "高梨康治(Team-MAX)", 1],
    [5, "女三人寄れば", "高梨康治(Team-MAX)", 1],
    [6, "どういうことなのこれ?", "高梨康治(Team-MAX)", 1],
    [7, "ここから先はダメ", "高梨康治(Team-MAX)", 1],
    [8, "深まる謎", "高梨康治(Team-MAX)", 1],
    [9, "戦慄の闇から", "高梨康治(Team-MAX)", 1],
    [10, "姿なき敵", "高梨康治(Team-MAX)", 1],
    [11, "波乱", "高梨康治(Team-MAX)", 1],
    [12, "魔界に眠りしもの", "高梨康治(Team-MAX)", 1],
    [13, "ほんわかほんわか", "高梨康治(Team-MAX)", 1],
    [14, "おじゃまかしら?", "高梨康治(Team-MAX)", 1],
    [15, "女の戦い", "高梨康治(Team-MAX)", 1],
    [16, "黒い霧", "高梨康治(Team-MAX)", 1],
    [17, "枢機院", "高梨康治(Team-MAX)", 1],
    [18, "英霊の進撃", "高梨康治(Team-MAX)", 1],
    [19, "魔女の逆鱗", "高梨康治(Team-MAX)", 1],
    [20, "旋風", "高梨康治(Team-MAX)", 1],
    [21, "惑いの刻", "高梨康治(Team-MAX)", 1],
    [22, "恋する魔法", "高梨康治(Team-MAX)", 1],
    [23, "悩ましの魔法", "高梨康治(Team-MAX)", 1],
    [24, "攻撃魔法", "高梨康治(Team-MAX)", 1],
    [25, "言い出せなくて", "高梨康治(Team-MAX)", 1],
    [26, "謀略の影", "高梨康治(Team-MAX)", 1],
    [27, "若き魔王の肖像", "高梨康治(Team-MAX)", 1],
    [28, "魔界の顔役", "高梨康治(Team-MAX)", 1],
    [29, "慄然", "高梨康治(Team-MAX)", 1],
    [30, "対立の波紋", "高梨康治(Team-MAX)", 1],
    [31, "涙の川を渡るとき", "高梨康治(Team-MAX)", 1],
    [32, "闘志の熾火", "高梨康治(Team-MAX)", 1],
    [33, "よみがえる魔神", "高梨康治(Team-MAX)", 1],
    [34, "容赦なき侵攻", "高梨康治(Team-MAX)", 1],
    [35, "劫火の戦場", "高梨康治(Team-MAX)", 1],
    [36, "明日への決戦", "高梨康治(Team-MAX)", 1],
    [37, "今ひとたびのやすらぎ", "高梨康治(Team-MAX)", 1],
    [38, "Temperature (TV size)", "Dual Flare", 0],
    [39, "Over The Testament (TV size)", "Metamorphose featuring Ishida Yoko", 0],
    [40, "Over The Testament (TV size)", "Metamorphose featuring Kaori Oda", 0],
    [41, "Over The Testament (TV size)", "Metamorphose featuring Aki Misato", 0],
    [42, "Over The Testament (TV size)", "Metamorphose featuring Megumi Ogata", 0],
]
links = ["https://beta.musicbrainz.org/release/66312d9a-f73b-4e7b-af72-29e72984bb74", "https://vgmdb.net/album/55645"]

[fc503c0d02753a087c777958a7a4185f]
catalognumber = "KAXA-9932CD"
date = "2018-02-23"
album = "新妹魔王の契約者 Blu-ray BOX エクスタCD"
tracks = [
    [1, "(no title available)", "", 0],
    [2, "(no title available)", "", 0],
    [3, "(no title available)", "", 0],
    [4, "(no title available)", "", 0],
    [5, "(no title available)", "", 0],
    [6, "(no title available)", "", 0],
]
links = ["https://vgmdb.net/album/72480"]

[e4df450c40d2724b66b493a4bcb91294]
catalognumber = "KAXA-7608CD"
date = "2018-03-28"
album = "新妹魔王の契約者 DEPARTURES エクスタCD"
tracks = [
    [1, "成瀬澪", "", 0],
    [2, "野中柚希", "", 0],
    [3, "成瀬万理亜", "", 0],
    [4, "野中胡桃", "", 0],
    [5, "ゼスト", "", 0],
    [6, "長谷川千里", "", 0],
]
links = ["https://vgmdb.net/album/72479"]
