[cd5d1e331ee18d963e77fb69e36b633a]
catalognumber = "PCCG-70202"
date = "2014-01-29"
album = "Won(*3*)Chu KissMe!/Kiss(and)Love / SAKURA*TRICK"
tracks = [
    [1, "Won(*3*)Chu KissMe!", "SAKURA*TRICK", 0],
    [2, "Kiss(and)Love", "SAKURA*TRICK【春香＆優】(CV:戸松 遥＆井口裕香)", 0],
    [3, "Kiss(and)Love (SAKURA♪Ver.)", "SAKURA*TRICK", 0],
    [4, "Won(*3*)Chu Kiss Me! (カラオケ)", "SAKURA*TRICK", 0],
    [5, "Kiss(and)Love (カラオケ)", "SAKURA*TRICK", 0],
]
links = ["https://beta.musicbrainz.org/release/73407832-8fbb-43fd-938d-fb90d4a09a69", "https://vgmdb.net/album/42960"]

[1304ed29133b429da6884b7178e01665]
catalognumber = "PCCG-70205"
date = "2014-02-26"
album = "TVアニメ『桜Trick』SAKURA♪SONG♪ 03"
tracks = [
    [1, "Girl meets girl", "池野楓(CV:渕上舞)、飯塚ゆず(CV:戸田めぐみ)", 0],
    [2, "快晴のステップ!", "池野楓(CV:渕上舞)、飯塚ゆず(CV:戸田めぐみ)", 0],
    [3, "Girl meets girl[からおけ]", "俊龍", 0],
    [4, "快晴のステップ![からおけ]", "俊龍", 0],
]
links = ["https://beta.musicbrainz.org/release/e907f07d-8ed5-4542-b891-6f0e8ea7caf1", "https://vgmdb.net/album/43434"]

[5a0351a21da1f5fd29f217075163912a]
catalognumber = "PCCG-70203"
date = "2014-02-26"
album = "TVアニメ『桜Trick』SAKURA♪SONG♪ 01"
tracks = [
    [1, "はるいろ乙女", "高山春香(CV:戸松遥)、園田優(CV:井口裕香)", 0],
    [2, "YES?NO?ココロ", "高山春香(CV:戸松遥)、園田優(CV:井口裕香)", 0],
    [3, "はるいろ乙女[からおけ]", "高山春香(CV:戸松遥)、園田優(CV:井口裕香)", 0],
    [4, "YES?NO?ココロ[からおけ]", "高山春香(CV:戸松遥)、園田優(CV:井口裕香)", 0],
]
links = ["https://beta.musicbrainz.org/release/09e79f90-4bca-463e-9fa7-b0ca37093315", "https://vgmdb.net/album/43432"]

[42a13a146bece1f0b28e7569bff407d6]
catalognumber = "PCCG-70204"
date = "2014-02-26"
album = "TVアニメ『桜Trick』SAKURA♪SONG♪ 02"
tracks = [
    [1, "おはモニ*ハロりん♪", "野田コトネ(CV:相坂優歌)、南しずく(CV:五十嵐裕美)", 0],
    [2, "蝶々結びのI Love You", "野田コトネ(CV:相坂優歌)、南しずく(CV:五十嵐裕美)", 0],
    [3, "おはモニ*ハロりん♪[からおけ]", "俊龍", 0],
    [4, "蝶々結びのI Love You[からおけ]", "草野よしひろ", 0],
]
links = ["https://beta.musicbrainz.org/release/d5d3625d-d39e-42ad-889c-0a63d8ebade5", "https://vgmdb.net/album/43433"]

[14814dff2912e9364e9f24f0fbcec2dc]
catalognumber = "DSP-02017"
date = "2014-03-19"
album = "Won(*3*)Chu KissMe! ソロヴァージョンCD Vol.1 高山春香ver. [CV:戸松遥]"
tracks = [
    [1, "Won(*3*)Chu KissMe! 高山春香ver.", "高山春香", 0],
]
links = ["https://beta.musicbrainz.org/release/6cfbb733-822f-458d-8eae-b2cb6198fb69", "https://vgmdb.net/album/68616"]

[858f9306dec600f5ab909bd60da05570]
catalognumber = "PCCG-01391"
date = "2014-03-19"
album = "TVアニメ「桜Trick」オリジナルサウンドトラック"
tracks = [
    [1, "メインテーマ", "中西亮輔", 0],
    [2, "桜色のひととき", "中西亮輔", 0],
    [3, "ハートがドキドキ", "中西亮輔", 0],
    [4, "仲良し", "中西亮輔", 0],
    [5, "心ここにあらず?", "中西亮輔", 0],
    [6, "おとぼけのワルツ", "中西亮輔", 0],
    [7, "うるさくしちゃうよ?", "中西亮輔", 0],
    [8, "リラックスタイム", "中西亮輔", 0],
    [9, "カシマシカシマシ", "中西亮輔", 0],
    [10, "夜に想う", "中西亮輔", 0],
    [11, "ロマンティック", "中西亮輔", 0],
    [12, "緊張", "中西亮輔", 0],
    [13, "特別なこと", "中西亮輔", 0],
    [14, "今日もなにかが起こりそう", "中西亮輔", 0],
    [15, "桜色の日常", "中西亮輔", 0],
    [16, "おっとりのんびりのほほんと", "中西亮輔", 0],
    [17, "あゝ悲劇のヒロイン", "中西亮輔", 0],
    [18, "ベーゼ", "中西亮輔", 0],
    [19, "けんあく", "中西亮輔", 0],
    [20, "天からの光", "中西亮輔", 0],
    [21, "バカンスの女王", "中西亮輔", 0],
    [22, "心のざわめき", "中西亮輔", 0],
    [23, "すっぱい大作戦", "中西亮輔", 0],
    [24, "Suspicious", "中西亮輔", 0],
    [25, "ホラーな気分", "中西亮輔", 0],
    [26, "Get Set Ready Go", "中西亮輔", 0],
    [27, "絶体絶命!?", "中西亮輔", 0],
    [28, "やさしくキスして", "中西亮輔", 0],
    [29, "Carnival of Light", "中西亮輔", 0],
    [30, "Snow White", "中西亮輔", 0],
    [31, "たそがれ時", "中西亮輔", 0],
    [32, "After Hours", "中西亮輔", 0],
    [33, "さーびすしーん", "中西亮輔", 0],
    [34, "また明日", "中西亮輔", 0],
    [35, "お昼休み", "ハナビラヒラリ", 0],
    [36, "桜色モーメント", "モコ", 0],
]
links = ["https://beta.musicbrainz.org/release/1cf209c9-ddee-4928-9790-f4d2c95ce40b", "https://vgmdb.net/album/43693"]

[2635c9f1254aa5a425b5eaff11b9b268]
catalognumber = "PCCG-01392"
date = "2014-04-09"
album = "TVアニメ『桜Trick』SAKURA♪SONG ALBUM SAKURA*SAKU -桜*作-"
tracks = [
    [1, "Won(*3*)Chu KissMe! -Album Remix-", "SAKURA*TRICK【高山春香/園田優/野田コトネ/南しずく/池野楓/飯塚ゆず】(CV:戸松遥、井口裕香、相坂優歌、五十嵐裕美、渕上舞、戸田めぐみ)", 0],
    [2, "Kiss me please", "SAKURA*TRICK【春香&優】(CV:戸松遥、井口裕香)", 0],
    [3, "桃色Lip☆Trip", "SAKURA*TRICK【コトネ&しずく】(CV:相坂優歌、五十嵐裕美)", 0],
    [4, "VENUS -be us!-", "SAKURA*TRICK【楓&ゆず】(CV:渕上舞、戸田めぐみ)", 0],
    [5, "桜Sweet Kiss", "SAKURA*TRICK【美月&澄&理奈】(CV:藤田咲、麻倉もも、遠藤ゆりか)", 0],
    [6, "Kiss(and)Love -Album Remix-", "SAKURA*TRICK【高山春香/園田優/野田コトネ/南しずく/池野楓/飯塚ゆず】(CV:戸松遥、井口裕香、相坂優歌、五十嵐裕美、渕上舞、戸田めぐみ)", 0],
    [7, "Kiss(and)Love【コトネ&しずく】", "SAKURA*TRICK【コトネ&しずく】(CV:相坂優歌、五十嵐裕美)", 0],
    [8, "Kiss(and)Love【楓&ゆず】", "SAKURA*TRICK【楓&ゆず】(CV:渕上舞、戸田めぐみ)", 0],
    [9, "Won(*3*)Chu KissMe![TVサイズ]", "SAKURA*TRICK【高山春香/園田優/野田コトネ/南しずく/池野楓/飯塚ゆず】(CV:戸松遥、井口裕香、相坂優歌、五十嵐裕美、渕上舞、戸田めぐみ)", 0],
    [10, "Kiss(and)Love [TVサイズ]", "SAKURA*TRICK【春香&優】(CV:戸松遥、井口裕香)", 0],
]
links = ["https://beta.musicbrainz.org/release/cec6e555-fdae-4ce7-8be0-afd4358d6374", "https://vgmdb.net/album/43764"]

[adcb2b38bc4dd93cdd61323537f46734]
catalognumber = "DSP-02022"
date = "2014-04-16"
album = "Won(*3*)Chu KissMe! ソロヴァージョンCD Vol.2 園田優ver. [CV:井口裕香]"
tracks = [
    [1, "Won(*3*)Chu KissMe! 園田優ver.", "", 0],
]
links = ["https://vgmdb.net/album/68617"]

[432c8d7d6e0c99a80385c7a0ddd26ff3]
catalognumber = "DSP-02023"
date = "2014-05-21"
album = "Won(*3*)Chu KissMe! ソロヴァージョンCD Vol.3 野田コトネver. [CV:相坂優歌]"
tracks = [
    [1, "Won(*3*)Chu KissMe! 野田コトネver.", "", 0],
]
links = ["https://vgmdb.net/album/68618"]

[a7f5372420fc6f6514098b2d4b25f627]
catalognumber = "PCXE-50363-2"
date = "2014-05-21"
album = "桜Track Audio Drama CD -春香-"
tracks = [
    [1, "「桜Track」01", "", 0],
    [2, "「桜Track」02", "", 0],
]
links = ["https://vgmdb.net/album/47679"]

[9726fb61c7c55cbd370e2ee533ab7ffe]
catalognumber = "DSP-02024"
date = "2014-06-18"
album = "Won(*3*)Chu KissMe! ソロヴァージョンCD Vol.4 南 しずくver. [CV:五十嵐裕美]"
tracks = [
    [1, "Won(*3*)Chu KissMe! 南 しずくver.", "", 0],
]
links = ["https://vgmdb.net/album/68619"]

[154658723bee7bf8a521dda766ebc42e]
catalognumber = "DSP-02025"
date = "2014-07-16"
album = "Won(*3*)Chu KissMe! ソロヴァージョンCD Vol.5 池野楓ver. [CV:渕上舞]"
tracks = [
    [1, "Won(*3*)Chu KissMe! 池野楓ver.", "", 0],
]
links = ["https://vgmdb.net/album/68620"]

[e384c438d2bb2791ab3bed42444a2baa]
catalognumber = "SCCG-00004"
date = "2014-08-16"
album = "TVアニメ「桜Trick」オリジナルサウンドトラック more"
tracks = [
    [1, "サブタイトルA", "中西亮輔", 0],
    [2, "Hello", "中西亮輔", 0],
    [3, "意気揚々", "中西亮輔", 0],
    [4, "手伝うー!!", "中西亮輔", 0],
    [5, "いじけちゃう", "中西亮輔", 0],
    [6, "二人の魔女", "中西亮輔", 0],
    [7, "Fly with Me", "中西亮輔", 0],
    [8, "喜びのあまり・・・", "中西亮輔", 0],
    [9, "サブタイトルB", "中西亮輔", 0],
    [10, "風になって", "中西亮輔", 0],
    [11, "Awareness", "中西亮輔", 0],
    [12, "決心", "中西亮輔", 0],
    [13, "ロマンティック (alternate version)", "中西亮輔", 0],
    [14, "好き/キス", "中西亮輔", 0],
    [15, "Where We Used to Kiss", "中西亮輔", 0],
    [16, "メインテーマ (reprise)", "中西亮輔", 0],
    [17, "お昼休み [からおけ]", "ハナビラヒラリ", 0],
    [18, "お昼休み (guitar instrumental version)", "ハナビラヒラリ", 0],
    [19, "桜色モーメント [からおけ]", "モコ", 0],
    [20, "結婚行進曲", "中西亮輔", 0],
    [21, "ジングルベル", "中西亮輔", 0],
    [22, "仰げば尊し (instrumental)", "中西亮輔", 0],
    [23, "Fly with Me (vocal)", "中西亮輔", 0],
    [24, "M-53 (本編未使用)", "中西亮輔", 0],
    [25, "M-54 (本編未使用)", "中西亮輔", 0],
    [26, "M-55 (本編未使用)", "中西亮輔", 0],
    [27, "好き/キス (alternate version)", "中西亮輔", 0],
    [28, "アイキャッチ集", "中西亮輔", 0],
]
links = ["https://beta.musicbrainz.org/release/f6228dab-a9b5-4403-914d-bf6670504ce2", "https://vgmdb.net/album/47568"]

[142dc06427b922514c7c9b750006a34a]
catalognumber = "DSP-02026"
date = "2014-08-20"
album = "Won(*3*)Chu KissMe! ソロヴァージョンCD Vol.6 飯塚ゆずver. [CV:戸田めぐみ]"
tracks = [
    [1, "Won(*3*)Chu KissMe! 飯塚ゆずver.", "", 0],
]
links = ["https://vgmdb.net/album/68621"]

[1543f6c904f6b17df9bbba6a40f58e49]
catalognumber = "SVWC-70696"
date = "2024-12-25"
album = "『きらら トリビュート コレクション「結束バンドの歌ってみた」』"
tracks = [
    [1, "ドラマパート ある日の結束バンド 〜その1〜", "結束バンド", 0],
    [2, "Cagayake!GIRLS", "喜多郁代(CV:長谷川育美)", 0],
    [3, "Daydream café", "山田リョウ(CV:水野朔)", 0],
    [4, "キルミーのベイベー!", "後藤ひとり(CV:青山吉能)", 0],
    [5, "SHINY DAYS", "伊地知虹夏(CV:鈴代紗弓)", 0],
    [6, "Won(*3*)Chu KissMe!", "喜多郁代(CV:長谷川育美)", 0],
    [7, "ドラマパート ある日の結束バンド 〜その2〜", "結束バンド", 0],
]
links = ["https://beta.musicbrainz.org/release/c1e21b59-9493-4fd3-95f1-c185dc5ec2c2", "https://vgmdb.net/album/143737"]
