[cd9806058c9d85bcebab6ff1441168f1]
catalognumber = "GNCA-0640"
date = "2021-07-28"
album = "満月とシルエットの夜/夜想曲 / 坊ちゃん(CV.花江夏樹)&アリス(CV.真野あゆみ)"
tracks = [
    [1, "満月とシルエットの夜", "坊ちゃん (CV.花江夏樹) & アリス (CV.真野あゆみ)", 0],
    [2, "夜想曲", "アリス (CV.真野あゆみ)", 0],
    [3, "昼下がりの誘惑ティータイム", "アリス (CV.真野あゆみ)", 0],
    [4, "満月とシルエットの夜 (Instrumenatal)", "坊ちゃん (CV.花江夏樹) & アリス (CV.真野あゆみ)", 0],
    [5, "夜想曲 (Instrumental)", "アリス (CV.真野あゆみ)", 0],
    [6, "昼下がりの誘惑ティータイム (Instrumental)", "アリス (CV.真野あゆみ)", 0],
]
links = ["https://beta.musicbrainz.org/release/7f1f617e-dbab-4dd8-a9ab-54872ae65080", "https://vgmdb.net/album/111487"]

[29a40fadf1f451bac209205b0953da41]
catalognumber = "GNXA-232102"
date = "2021-09-29"
album = "死神坊ちゃんと黒メイド VOLUME ONE 特典ディスク"
tracks = [
    [1, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第1回", "", 0],
    [2, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第2回", "", 0],
    [3, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第3回", "", 0],
]
links = ["https://vgmdb.net/album/112732"]

[2ee29979fd9c418b4736a93ea4ea2194]
catalognumber = "GNCA-1600"
date = "2021-10-13"
album = "死神坊ちゃんと黒メイド サウンドトラック&キャラクターソング Original Soundtrack"
tracks = [
    [1, "Requiem ballad", "奥田弦", 0],
    [2, "Melodia pace", "奥田弦", 0],
    [3, "Sempre insieme", "奥田弦", 0],
    [4, "Prestazione", "奥田弦", 0],
    [5, "Belissimo", "奥田弦", 0],
    [6, "Stanza buia", "奥田弦", 0],
    [7, "Spaventoso", "渡辺剛", 0],
    [8, "Tensione -mf-", "渡辺剛", 0],
    [9, "Traduzione errata", "渡辺剛", 0],
    [10, "Eye catch A", "奥田弦", 0],
    [11, "Calmati", "奥田弦", 0],
    [12, "Turbata", "奥田弦", 0],
    [13, "Posto soleggiato", "渡辺剛", 0],
    [14, "Voce gentile", "奥田弦", 0],
    [15, "Viola", "渡辺剛", 0],
    [16, "Tempo soffice", "渡辺剛", 0],
    [17, "Slapstick", "奥田弦", 0],
    [18, "Strisciante", "奥田弦", 0],
    [19, "Passeggiare", "渡辺剛", 0],
    [20, "Festa sessione", "奥田弦", 0],
    [21, "Citta incantata", "渡辺剛", 0],
    [22, "Ricordo", "渡辺剛", 0],
    [23, "Alice", "渡辺剛", 0],
    [24, "Breve distanza", "渡辺剛", 0],
    [25, "Stupido", "渡辺剛", 0],
    [26, "Parlare", "奥田弦", 0],
    [27, "Cuff", "奥田弦", 0],
    [28, "Zain", "奥田弦", 0],
    [29, "Maledizione", "渡辺剛", 0],
    [30, "Ballo notturno", "奥田弦", 0],
    [31, "emolto gentile", "奥田弦", 0],
    [32, "Cuore profondo", "奥田弦", 0],
    [33, "Sentimenti", "奥田弦", 0],
]
links = ["https://beta.musicbrainz.org/release/f55ae2e6-a3de-40a0-9753-069557726479", "https://vgmdb.net/album/112425"]

[8158ea5e6c0a50f6bbf804b2feea7066]
catalognumber = "GNCA-1600"
date = "2021-10-13"
album = "死神坊ちゃんと黒メイド サウンドトラック&キャラクターソング Original Soundtrack, Vocal"
tracks = [
    [1, "Prefazione", "奥田弦", 0],
    [2, "Rob", "奥田弦", 0],
    [3, "Giocare", "奥田弦", 0],
    [4, "Walter", "奥田弦", 0],
    [5, "Solitario", "奥田弦", 0],
    [6, "Memoria", "奥田弦", 0],
    [7, "Secondo", "渡辺剛", 0],
    [8, "Incantato", "渡辺剛", 0],
    [9, "Rimasto", "奥田弦", 0],
    [10, "Alice e il mondo dei sogni", "渡辺剛", 0],
    [11, "Patetico", "奥田弦", 0],
    [12, "Un altro mondo", "奥田弦", 0],
    [13, "L'ultima canzone rimasta", "奥田弦", 0],
    [14, "Impulso", "奥田弦", 0],
    [15, "Monologo", "奥田弦", 0],
    [16, "ffff", "奥田弦", 0],
    [17, "Grazie mille", "奥田弦", 0],
    [18, "Grazie di cuore", "渡辺剛", 0],
    [19, "満月とシルエットの夜 〜Piano Ver.〜", "渡辺剛", 0],
    [20, "夜想曲 〜Piano Ver.〜", "渡辺剛", 0],
    [21, "Eye catch B", "渡辺剛", 0],
    [22, "月と猫のコンチェルト", "坊ちゃん (CV.花江夏樹)", 0],
    [23, "洗いっこいいなぁ", "坊ちゃん (CV.花江夏樹)", 0],
    [24, "サバトの夜に魔女賛歌", "岡崎昌幸 / 渕上祥人 / 大木理紗 / 原田真純", 0],
    [25, "Make a wish", "坊ちゃん (CV.花江夏樹), アリス (CV.真野あゆみ), ロブ (CV.大塚芳忠), ヴィオラ (CV.水瀬いのり), カフ (CV.倉持若菜) & ザイン (CV.神谷浩史)", 0],
    [26, "ふくろうと仔猫", "坊ちゃん (CV.花江夏樹) & アリス (CV.真野あゆみ)", 0],
    [27, "unreachable", "アリス (CV.真野あゆみ)", 0],
    [28, "Secret Flavor", "ヴィオラ (CV.水瀬いのり)", 0],
    [29, "月に願いを", "坊ちゃん (CV.花江夏樹)", 0],
]
links = ["https://beta.musicbrainz.org/release/f55ae2e6-a3de-40a0-9753-069557726479", "https://vgmdb.net/album/112425"]

[452865eae4fb73ebea2bf0051cb5b97a]
catalognumber = "GNXA-232202"
date = "2021-10-13"
album = "死神坊ちゃんと黒メイド VOLUME TWO 特典ディスク"
tracks = []
links = ["https://vgmdb.net/album/112422"]

[c98301c080c0135ca92e30bde43ba897]
catalognumber = "GNXA-232302"
date = "2021-10-27"
album = "死神坊ちゃんと黒メイド VOLUME THREE 特典ディスク"
tracks = [
    [1, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第4回", "", 0],
    [2, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第5回", "", 0],
]
links = ["https://vgmdb.net/album/112733"]

[27cf9e3129edf4c23f874ebaca1d155c]
catalognumber = "GNXA-232402"
date = "2021-11-12"
album = "死神坊ちゃんと黒メイド VOLUME FOUR 特典ディスク"
tracks = []
links = ["https://vgmdb.net/album/112423"]

[f712abf138b6b940f630c863916e0b7d]
catalognumber = "GNXA-232502"
date = "2021-11-26"
album = "死神坊ちゃんと黒メイド VOLUME FIVE 特典ディスク"
tracks = [
    [1, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第6回", "", 0],
    [2, "死神坊ちゃんと黒メイド 坊ちゃんとアリスとラジオ 第7回", "", 0],
]
links = ["https://vgmdb.net/album/112734"]

[4e7a61732203fed1c53fa9859891d04e]
catalognumber = "GNXA-232602"
date = "2021-12-10"
album = "死神坊ちゃんと黒メイド VOLUME SIX 特典ディスク"
tracks = []
links = ["https://vgmdb.net/album/112424"]

[cadf51c9454ea4c86ea4f6cc26ab815e]
catalognumber = "N/A"
date = "2023-07-09"
album = "君とレヴュー / 坊ちゃん (CV: 花江夏樹)&アリス (CV: 真野あゆみ)"
tracks = [
    [1, "君とレヴュー", "坊ちゃん (CV.花江夏樹) & アリス (CV.真野あゆみ)", 0],
]
links = ["https://beta.musicbrainz.org/release/2fef0805-d69b-4836-99af-06379e041295", "https://vgmdb.net/album/132062"]

[1b92e287415e3e4f858a5e20646680a3]
catalognumber = "GNCA-0696"
date = "2023-08-23"
album = "星屑レクイエム / なすお☆ [初回限定アニメ盤] Arrangement, Vocal"
tracks = [
    [1, "星屑レクイエム", "なすお☆", 0],
    [2, "星屑レクイエム（TV Size）", "なすお☆", 0],
    [3, "夜想曲（なすお☆cover）", "なすお☆", 0],
    [4, "星屑レクイエム –Instrumental–", "なすお☆", 0],
]
links = ["https://beta.musicbrainz.org/release/c3e589f4-69ab-4fa1-bc98-81442a63cb2e", "https://vgmdb.net/album/130835"]

[0d7562fdf544a8a1db1a822d6aea1bfa]
catalognumber = "GNCA-0696"
date = "2023-08-23"
album = "星屑レクイエム / なすお☆ [初回限定アニメ盤] Vocal"
tracks = [
    [1, "星屑レクイエム (Music Video)", "なすお☆", 0],
    [2, "星屑レクイエム (Music Video Making Movie)", "なすお☆", 0],
    [3, "アニメ「死神坊ちゃんと黒メイド」(第2期)ノンクレジットED映像", "なすお☆", 0],
]
links = ["https://beta.musicbrainz.org/release/c3e589f4-69ab-4fa1-bc98-81442a63cb2e", "https://vgmdb.net/album/130835"]

[6ebdafc5c68c84a4f87f0af01edd5e6d]
catalognumber = "N/A"
date = "2024-04-07"
album = "シネマティックパレード / なすお☆"
tracks = [
    [1, "シネマティックパレード", "なすお☆", 0],
    [2, "シネマティックパレード(インストゥルメンタル)", "なすお☆", 0],
]
links = ["https://beta.musicbrainz.org/release/8a04cc23-6130-4e6d-b694-fd22bdb5942c", "https://vgmdb.net/album/154427"]

[24ad88bb8b0f88553d097ce30e30d91c]
catalognumber = "N/A"
date = "2024-04-07"
album = "エトワールメモワール / アリス (CV: 真野あゆみ)"
tracks = [
    [1, "エトワールメモワール", "アリス (CV.真野あゆみ)", 0],
]
links = ["https://beta.musicbrainz.org/release/03f7ba4b-c060-44b5-8b29-ceed97dde5fc", "https://vgmdb.net/album/150113"]

[af52444d815aa26d26eca88a8faa1a5b]
catalognumber = "N/A"
date = "2024-06-24"
album = "満月とシルエットの夜～Wedding Ver.～ / 坊ちゃん(CV.花江夏樹)&アリス(CV.真野あゆみ)"
tracks = [
    [1, "満月とシルエットの夜〜Wedding Ver.〜", "坊ちゃん (CV.花江夏樹) & アリス (CV.真野あゆみ)", 0],
]
links = ["https://beta.musicbrainz.org/release/0f8c50cf-8926-4239-8209-f63bd4b90270", "https://vgmdb.net/album/140479"]
