[9cb39caacbc6a35c1c2e065a5829f411]
catalognumber = ""
date = "2014-05-28"
album = "いぬねこジュークBOX"
tracks = [
    [1, "いんとろ 犬神さんと猫山さん ～Theme from Original Animation～", "V.A.", 0],
    [2, "絶対(ハート)服従宣言", "上坂すみれ/東山奈央", 0],
    [3, "手錠を掛けて(ハート)", "上坂すみれ", 0],
    [4, "ちっちゃいもの同盟", "東山奈央/堀野紗也加", 0],
    [5, "生物部の情事 ～Theme from Original Animation～", "V.A.", 0],
    [6, "青春あらいぶ", "東山奈央/上坂すみれ", 0],
    [7, "キミ イロ ガミ", "山崎エリイ/長弘翔子", 0],
    [8, "秋ちゃんの憂鬱 ～Theme from Original Animation～", "V.A.", 0],
    [9, "飼い主じゃなくて", "大坪由佳", 0],
    [10, "あうとろ 犬神さんと猫山さん Reprise ～Theme from Original Animation～", "V.A.", 0],
    [11, "ぼーなすとっらっく : くろねこにっき", "東山奈央", 0],
]
links = ["https://music.163.com/#/album?id=2866580"]
