[8ef423808273b0ba3e7b3479567810cb]
catalognumber = "EYCA-12957"
date = "2020-05-27"
album = "TVアニメ「球詠」Original Soundtrack"
tracks = [
    [1, "のんびりワインドアップ", "森藤晶司", 1],
    [2, "明るくワインドアップ", "森藤晶司", 1],
    [3, "ダッグアウトのそよ風", "竹下智博", 1],
    [4, "いつものオーダー", "折戸伸治", 1],
    [5, "調整日の過ごし方", "水月陵", 1],
    [6, "オフはのんびり", "竹下智博", 1],
    [7, "やっちゃったボーンヘッド", "kidlit", 1],
    [8, "ラッキーなポテンヒット", "水月陵", 1],
    [9, "仲間とリフレッシュ", "しょうゆ", 1],
    [10, "キャンプイン", "kidlit", 1],
    [11, "押せ押せムード", "bermei.inazawa", 1],
    [12, "晴れた日の朝練", "折戸伸治", 1],
    [13, "クリーンヒット", "しょうゆ", 1],
    [14, "目指すは三冠王", "しょうゆ", 1],
    [15, "相手はプロ注目", "kidlit", 1],
    [16, "シビれる投手戦", "折戸伸治", 1],
    [17, "待てのサイン", "bermei.inazawa", 1],
    [18, "見えないクロスファイヤー", "しょうゆ", 1],
    [19, "ビデオ判定", "bermei.inazawa", 1],
    [20, "敵はサウスポー", "竹下智博", 1],
]
links = ["https://beta.musicbrainz.org/release/821a02b0-ba54-4d32-979f-991f3e4a06ee", "https://vgmdb.net/album/96540"]

[eb237ddd15d76a691cf9facfda60df4e]
catalognumber = "EYCA-13057~8"
date = "2020-05-27"
album = "TVアニメ「球詠」Original Soundtrack Disc 1 [EYCA-13057]"
tracks = [
    [1, "のんびりワインドアップ", "森藤晶司", 1],
    [2, "明るくワインドアップ", "森藤晶司", 1],
    [3, "ダッグアウトのそよ風", "竹下智博", 1],
    [4, "いつものオーダー", "折戸伸治", 1],
    [5, "調整日の過ごし方", "水月陵", 1],
    [6, "オフはのんびり", "竹下智博", 1],
    [7, "やっちゃったボーンヘッド", "kidlit", 1],
    [8, "ラッキーなポテンヒット", "水月陵", 1],
    [9, "仲間とリフレッシュ", "しょうゆ", 1],
    [10, "キャンプイン", "kidlit", 1],
    [11, "押せ押せムード", "bermei.inazawa", 1],
    [12, "晴れた日の朝練", "折戸伸治", 1],
    [13, "クリーンヒット", "しょうゆ", 1],
    [14, "目指すは三冠王", "しょうゆ", 1],
    [15, "相手はプロ注目", "kidlit", 1],
    [16, "シビれる投手戦", "折戸伸治", 1],
    [17, "待てのサイン", "bermei.inazawa", 1],
    [18, "見えないクロスファイヤー", "しょうゆ", 1],
    [19, "ビデオ判定", "bermei.inazawa", 1],
    [20, "敵はサウスポー", "竹下智博", 1],
]
links = ["https://beta.musicbrainz.org/release/821a02b0-ba54-4d32-979f-991f3e4a06ee", "https://vgmdb.net/album/99608"]

[2b52222c891f91390481dd0efac03eb3]
catalognumber = "EYCA-13057~8"
date = "2020-05-27"
album = "TVアニメ「球詠」Original Soundtrack Disc 2 [EYCA-13058]"
tracks = [
    [1, "頭脳戦", "折戸伸治", 1],
    [2, "勝敗つかず", "kidlit", 1],
    [3, "沈黙の打線", "森藤晶司", 1],
    [4, "スランプに陥って", "森藤晶司", 1],
    [5, "ビハインドの中で", "竹下智博", 1],
    [6, "先が見えないイップス", "森藤晶司", 1],
    [7, "すれ違うバッテリー", "bermei.inazawa", 1],
    [8, "抑えのエース登場", "kidlit", 1],
    [9, "延長の山場", "kidlit", 1],
    [10, "勝ち越しの一打", "bermei.inazawa", 1],
    [11, "心強いナイン", "bermei.inazawa", 1],
    [12, "サイレントトリートメント", "水月陵", 1],
    [13, "ノーゲーム", "水月陵", 1],
    [14, "未来にストレッチ", "kidlit", 1],
    [15, "ナイターの後に", "bermei.inazawa", 1],
    [16, "ミットで受け止めて", "水月陵", 1],
    [17, "優しいフレーミング", "水月陵", 1],
    [18, "助け合えるチームメイト", "bermei.inazawa", 1],
    [19, "エースはワインドアップ", "森藤晶司", 1],
    [20, "目覚めのワインドアップ", "森藤晶司", 1],
    [21, "Never Let You Go! (ブラバンアレンジver.)", "bermei.inazawa", 1],
]
links = ["https://beta.musicbrainz.org/release/821a02b0-ba54-4d32-979f-991f3e4a06ee", "https://vgmdb.net/album/99608"]

[37854494cde08e475b263e51e3d1cfa0]
catalognumber = "EYCA-12956"
date = "2020-05-27"
album = "Never Let You Go!/プラスマイナスゼロの法則"
tracks = [
    [1, "Never Let You Go!", "七穂", 1],
    [2, "プラスマイナスゼロの法則", "新越谷高校女子野球部", 2],
    [3, "プラスマイナスゼロの法則 七穂Ver", "七穂", 1],
    [4, "プラスマイナスゼロの法則 詠深Ver", "武田詠深", 1],
    [5, "プラスマイナスゼロの法則 珠姫Ver", "山崎珠姫", 1],
    [6, "プラスマイナスゼロの法則 希Ver", "中村希", 1],
    [7, "プラスマイナスゼロの法則 菫Ver", "藤田菫", 1],
    [8, "プラスマイナスゼロの法則 理沙Ver", "藤原理沙", 1],
    [9, "プラスマイナスゼロの法則 稜Ver", "川﨑稜", 1],
    [10, "プラスマイナスゼロの法則 息吹Ver", "川口息吹", 1],
    [11, "プラスマイナスゼロの法則 怜Ver", "岡田怜", 1],
    [12, "プラスマイナスゼロの法則 白菊Ver", "大村白菊", 1],
    [13, "プラスマイナスゼロの法則 芳乃Ver", "川口芳乃", 1],
    [14, "Never Let You Go! -instrumental-", "七穂", 1],
    [15, "プラスマイナスゼロの法則 -instrumental-", "新越谷高校女子野球部", 1],
]
links = ["https://beta.musicbrainz.org/release/6dcca0ae-6a4b-4436-a519-75144be4d682", "https://vgmdb.net/album/96541"]
