[6ab52e1d7f7f3d41fedf82cefe0c6f98]
catalognumber = "EYCA-12957"
date = "2020-05-27"
album = "TVアニメ「球詠」Original Soundtrack"
tracks = [
    [1, "のんびりワインドアップ", "森藤晶司", 0],
    [2, "明るくワインドアップ", "森藤晶司", 0],
    [3, "ダッグアウトのそよ風", "竹下智博", 0],
    [4, "いつものオーダー", "折戸伸治", 0],
    [5, "調整日の過ごし方", "水月陵", 0],
    [6, "オフはのんびり", "竹下智博", 0],
    [7, "やっちゃったボーンヘッド", "kidlit", 0],
    [8, "ラッキーなポテンヒット", "水月陵", 0],
    [9, "仲間とリフレッシュ", "しょうゆ", 0],
    [10, "キャンプイン", "kidlit", 0],
    [11, "押せ押せムード", "bermei.inazawa", 0],
    [12, "晴れた日の朝練", "折戸伸治", 0],
    [13, "クリーンヒット", "しょうゆ", 0],
    [14, "目指すは三冠王", "しょうゆ", 0],
    [15, "相手はプロ注目", "kidlit", 0],
    [16, "シビれる投手戦", "折戸伸治", 0],
    [17, "待てのサイン", "bermei.inazawa", 0],
    [18, "見えないクロスファイヤー", "しょうゆ", 0],
    [19, "ビデオ判定", "bermei.inazawa", 0],
    [20, "敵はサウスポー", "竹下智博", 0],
]
links = ["https://beta.musicbrainz.org/release/821a02b0-ba54-4d32-979f-991f3e4a06ee", "https://vgmdb.net/album/96540"]

[95423ffe8333c167f08ca5c81c10ed14]
catalognumber = "EYCA-13057~8"
date = "2020-05-27"
album = "TVアニメ「球詠」Original Soundtrack Disc 1 [EYCA-13057]"
tracks = [
    [1, "のんびりワインドアップ", "森藤晶司", 0],
    [2, "明るくワインドアップ", "森藤晶司", 0],
    [3, "ダッグアウトのそよ風", "竹下智博", 0],
    [4, "いつものオーダー", "折戸伸治", 0],
    [5, "調整日の過ごし方", "水月陵", 0],
    [6, "オフはのんびり", "竹下智博", 0],
    [7, "やっちゃったボーンヘッド", "kidlit", 0],
    [8, "ラッキーなポテンヒット", "水月陵", 0],
    [9, "仲間とリフレッシュ", "しょうゆ", 0],
    [10, "キャンプイン", "kidlit", 0],
    [11, "押せ押せムード", "bermei.inazawa", 0],
    [12, "晴れた日の朝練", "折戸伸治", 0],
    [13, "クリーンヒット", "しょうゆ", 0],
    [14, "目指すは三冠王", "しょうゆ", 0],
    [15, "相手はプロ注目", "kidlit", 0],
    [16, "シビれる投手戦", "折戸伸治", 0],
    [17, "待てのサイン", "bermei.inazawa", 0],
    [18, "見えないクロスファイヤー", "しょうゆ", 0],
    [19, "ビデオ判定", "bermei.inazawa", 0],
    [20, "敵はサウスポー", "竹下智博", 0],
]
links = ["https://beta.musicbrainz.org/release/821a02b0-ba54-4d32-979f-991f3e4a06ee", "https://vgmdb.net/album/99608"]

[30d04c69e10697a1a5c3fbad10f56172]
catalognumber = "EYCA-13057~8"
date = "2020-05-27"
album = "TVアニメ「球詠」Original Soundtrack Disc 2 [EYCA-13058]"
tracks = [
    [1, "頭脳戦", "折戸伸治", 0],
    [2, "勝敗つかず", "kidlit", 0],
    [3, "沈黙の打線", "森藤晶司", 0],
    [4, "スランプに陥って", "森藤晶司", 0],
    [5, "ビハインドの中で", "竹下智博", 0],
    [6, "先が見えないイップス", "森藤晶司", 0],
    [7, "すれ違うバッテリー", "bermei.inazawa", 0],
    [8, "抑えのエース登場", "kidlit", 0],
    [9, "延長の山場", "kidlit", 0],
    [10, "勝ち越しの一打", "bermei.inazawa", 0],
    [11, "心強いナイン", "bermei.inazawa", 0],
    [12, "サイレントトリートメント", "水月陵", 0],
    [13, "ノーゲーム", "水月陵", 0],
    [14, "未来にストレッチ", "kidlit", 0],
    [15, "ナイターの後に", "bermei.inazawa", 0],
    [16, "ミットで受け止めて", "水月陵", 0],
    [17, "優しいフレーミング", "水月陵", 0],
    [18, "助け合えるチームメイト", "bermei.inazawa", 0],
    [19, "エースはワインドアップ", "森藤晶司", 0],
    [20, "目覚めのワインドアップ", "森藤晶司", 0],
    [21, "Never Let You Go! (ブラバンアレンジver.)", "bermei.inazawa", 0],
]
links = ["https://beta.musicbrainz.org/release/821a02b0-ba54-4d32-979f-991f3e4a06ee", "https://vgmdb.net/album/99608"]

[ddc71e10ab7e819c022d6617f76de428]
catalognumber = "EYCA-12956"
date = "2020-05-27"
album = "Never Let You Go!/プラスマイナスゼロの法則"
tracks = [
    [1, "Never Let You Go!", "七穂", 0],
    [2, "プラスマイナスゼロの法則", "新越谷高校女子野球部", 0],
    [3, "プラスマイナスゼロの法則 七穂Ver", "七穂", 0],
    [4, "プラスマイナスゼロの法則 詠深Ver", "武田詠深", 0],
    [5, "プラスマイナスゼロの法則 珠姫Ver", "山崎珠姫", 0],
    [6, "プラスマイナスゼロの法則 希Ver", "中村希", 0],
    [7, "プラスマイナスゼロの法則 菫Ver", "藤田菫", 0],
    [8, "プラスマイナスゼロの法則 理沙Ver", "藤原理沙", 0],
    [9, "プラスマイナスゼロの法則 稜Ver", "川﨑稜", 0],
    [10, "プラスマイナスゼロの法則 息吹Ver", "川口息吹", 0],
    [11, "プラスマイナスゼロの法則 怜Ver", "岡田怜", 0],
    [12, "プラスマイナスゼロの法則 白菊Ver", "大村白菊", 0],
    [13, "プラスマイナスゼロの法則 芳乃Ver", "川口芳乃", 0],
    [14, "Never Let You Go! -instrumental-", "七穂", 0],
    [15, "プラスマイナスゼロの法則 -instrumental-", "新越谷高校女子野球部", 0],
]
links = ["https://beta.musicbrainz.org/release/6dcca0ae-6a4b-4436-a519-75144be4d682", "https://vgmdb.net/album/96541"]
