[40cce81d1c765ed88a8f5efec00c2522]
catalognumber = "KICA-2628"
date = "2024-11-20"
album = "TVアニメ「甘神さんちの縁結び」キャラクターソングミニアルバム 君に恋を結んで"
tracks = [
    [1, "君に恋を結んで", "甘神三姉妹", 0],
    [2, "桜のかくしごと", "甘神三姉妹", 0],
    [3, "夜空に引いた線", "甘神夜重(CV.上坂すみれ)", 0],
    [4, "夕色のねがいみち", "甘神夕奈(CV.本渡楓)", 0],
    [5, "朝姫は朝だけ姫気分♡", "甘神朝姫(CV.若山詩音)", 0],
    [6, "君に恋を結んで (off vocal version)", "甘神三姉妹", 0],
    [7, "桜のかくしごと (off vocal version)", "甘神三姉妹", 0],
    [8, "夜空に引いた線 (off vocal version)", "甘神夜重(CV.上坂すみれ)", 0],
    [9, "夕色のねがいみち (off vocal version)", "甘神夕奈(CV.本渡楓)", 0],
    [10, "朝姫は朝だけ姫気分♡ (off vocal version)", "甘神朝姫(CV.若山詩音)", 0],
]
links = ["https://beta.musicbrainz.org/release/06f758b0-c28a-44f0-a003-f2bd2f155558", "https://vgmdb.net/album/144580"]

[151c3ab3d304fe0306809efa2d8d1c57]
catalognumber = "KICA-2629"
date = "2025-03-19"
album = "TVアニメ「甘神さんちの縁結び」キャラクターソングミニアルバム Pray Pray Pray"
tracks = [
    [1, "Pray Pray Pray", "甘神三姉妹", 0],
    [2, "夢見る日和", "甘神三姉妹", 0],
    [3, "はじめての色", "甘神夜重(CV.上坂すみれ)", 0],
    [4, "見つけた願い、君との未来", "甘神夕奈(CV.本渡楓)", 0],
    [5, "7月のまぼろし", "甘神朝姫(CV.若山詩音)", 0],
    [6, "Pray Pray Pray (off vocal version)", "甘神三姉妹", 0],
    [7, "夢見る日和 (off vocal version)", "甘神三姉妹", 0],
    [8, "はじめての色 (off vocal version)", "甘神夜重(CV.上坂すみれ)", 0],
    [9, "見つけた願い、君との未来 (off vocal version)", "甘神夕奈(CV.本渡楓)", 0],
    [10, "7月のまぼろし (off vocal version)", "甘神朝姫(CV.若山詩音)", 0],
]
links = ["https://beta.musicbrainz.org/release/8e98a3fc-9820-49d9-8c0b-52fd0bd18da0", "https://vgmdb.net/album/150513"]

[93eb04cdae0687637d34435c100b2c6d]
catalognumber = "NOPA-7793"
date = "2025-06-25"
album = "TVアニメ「甘神さんちの縁結び」オリジナル・サウンドトラック"
tracks = [
    [1, "願いと奇跡", "川﨑龍", 0],
    [2, "甘神神社", "狐野智之", 0],
    [3, "甘神三姉妹", "狐野智之", 0],
    [4, "朝姫がおませさん", "狐野智之", 0],
    [5, "夕奈がおこ", "狐野智之", 0],
    [6, "夜重がおっとりニコニコ", "狐野智之", 0],
    [7, "この不届きもの!", "狐野智之", 0],
    [8, "瓜生をからかう三姉妹", "狐野智之", 0],
    [9, "あらら…", "狐野智之", 0],
    [10, "いい感じ…!", "狐野智之", 0],
    [11, "お母さんとの想い出", "狐野智之", 0],
    [12, "失せ物出でず", "狐野智之", 0],
    [13, "叶わなかった願いごと", "狐野智之", 0],
    [14, "ちぐはぐ", "川﨑龍", 0],
    [15, "星つぶの叶い雨", "川﨑龍", 0],
    [16, "婿養子…?", "狐野智之", 0],
    [17, "時には頼りに", "川﨑龍", 0],
    [18, "幼なじみの白日", "狐野智之", 0],
    [19, "憧れの舞昼さん", "狐野智之", 0],
    [20, "トーテムポール", "狐野智之", 0],
    [21, "予知夢", "狐野智之", 0],
    [22, "お見合いデート!", "狐野智之", 0],
    [23, "あーだこーだ", "狐野智之", 0],
    [24, "うぶーな瓜生", "狐野智之", 0],
    [25, "格好つかない瓜生", "狐野智之", 0],
    [26, "見惚れる瓜生", "狐野智之", 0],
    [27, "いけずな北白川", "狐野智之", 0],
    [28, "神社存続の危機?", "狐野智之", 0],
    [29, "作戦実行!!", "狐野智之", 0],
    [30, "翔ける心", "川﨑龍", 0],
    [31, "上手くいかない…", "狐野智之", 0],
    [32, "追いうちの雨", "狐野智之", 0],
    [33, "奉納舞", "狐野智之", 0],
    [34, "きっとこれからも", "川﨑龍", 0],
    [35, "前向き三姉妹", "狐野智之", 0],
    [36, "ヤキモキ", "狐野智之", 0],
    [37, "三姉妹を見守る宵深子さん", "狐野智之", 0],
    [38, "ホンネはどこに?", "狐野智之", 0],
    [39, "巫女失格…?", "狐野智之", 0],
    [40, "ほんとはね", "川﨑龍", 0],
    [41, "互いを思う三姉妹", "狐野智之", 0],
    [42, "今日も今日とて", "狐野智之", 0],
    [43, "お団子のおみっちゃん", "狐野智之", 0],
    [44, "センチメンタル", "狐野智之", 0],
    [45, "真夜中の肝試し", "狐野智之", 0],
    [46, "焦りと不安", "狐野智之", 0],
    [47, "夜重の過去", "狐野智之", 0],
    [48, "迷子のキモチ", "狐野智之", 0],
    [49, "諦めず走れ!", "狐野智之", 0],
    [50, "夜重の告白", "狐野智之", 0],
    [51, "ツンと花蓮お嬢さま", "狐野智之", 0],
    [52, "刻の織り目", "川﨑龍", 0],
    [53, "試行錯誤", "狐野智之", 0],
    [54, "時間の中に取り残され", "狐野智之", 0],
    [55, "朝姫の悩み", "狐野智之", 0],
    [56, "全力ダッシュ!", "狐野智之", 0],
    [57, "朝姫のキス", "狐野智之", 0],
    [58, "とりかへばやハプニング!?", "狐野智之", 0],
    [59, "夕奈の願い", "川﨑龍", 0],
    [60, "惚れた夕奈", "狐野智之", 0],
    [61, "届かなかった想い", "狐野智之", 0],
    [62, "暗神さん", "狐野智之", 0],
    [63, "別の世界で", "狐野智之", 0],
    [64, "揺れる心", "狐野智之", 0],
    [65, "こいごころ", "狐野智之", 0],
    [66, "優しさの溢れる家", "川﨑龍", 0],
    [67, "願いと奇跡 (Pf Solo Ver.)", "川﨑龍", 0],
]
links = ["https://beta.musicbrainz.org/release/64838153-677e-4101-b68e-291531e9d498", "https://vgmdb.net/album/150683"]
