[b969aa630eaa919c5b13a10966819e49]
catalognumber = "KICM-3211"
date = "2010-07-21"
album = "大和撫子エデュケイション / トリプルブッキング"
tracks = [
    [1, "大和撫子エデュケイション", "トリプルブッキング", 0],
    [2, "情熱の花", "トリプルブッキング", 0],
    [3, "大和撫子エデュケイション (off vocal ver.)", "トリプルブッキング", 0],
    [4, "情熱の花 (off vocal ver.)", "トリプルブッキング", 0],
]
links = ["https://beta.musicbrainz.org/release/aa0d20be-397f-486c-a520-fa0a7e31be1e", "https://vgmdb.net/album/44501"]

[70a9dfe8b483dddc182b8b33f6cffd4f]
catalognumber = "KICM-3212"
date = "2010-07-28"
album = "蒼い春 / angela"
tracks = [
    [1, "蒼い春", "angela", 0],
    [2, "ツナガル→ム", "angela", 0],
    [3, "蒼い春 (off vocal version)", "angela", 0],
    [4, "ツナガル→ム (off vocal version)", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/12daf29c-969d-4496-a934-532a77ad9092", "https://vgmdb.net/album/47110"]

[ae53f3c43407d0047f483395b4cbffba]
catalognumber = "SSX-10169"
date = "2010-08-04"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その1"
tracks = [
    [1, "プロローグ", "天草シノ", 0],
    [2, "赤い糸", "天草シノ", 0],
    [3, "イルカ", "天草シノ", 0],
    [4, "オナ禁は解禁", "天草シノ", 0],
    [5, "桜才祭", "天草シノ", 0],
    [6, "重い日", "天草シノ", 0],
    [7, "幼なじみ", "天草シノ", 0],
    [8, "金閣寺", "天草シノ", 0],
    [9, "クールビズ", "天草シノ", 0],
]
links = ["https://beta.musicbrainz.org/release/1ac557b2-dffc-425b-ad57-c137e2175b61", "https://vgmdb.net/album/86055"]

[6cc528dc3038d0139fd491e11d5d4b53]
catalognumber = "SSX-10170"
date = "2010-08-25"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その2"
tracks = [
    [1, "プロローグ", "天草シノ", 0],
    [2, "衣替え", "天草シノ", 0],
    [3, "混浴", "天草シノ", 0],
    [4, "合法的な露出", "天草シノ", 0],
    [5, "思春期", "天草シノ", 0],
    [6, "修学旅行", "天草シノ", 0],
    [7, "新聞部", "天草シノ", 0],
    [8, "女子高", "天草シノ", 0],
    [9, "柔道部", "天草シノ", 0],
]
links = ["https://beta.musicbrainz.org/release/324081c4-4773-42ae-85e3-421074ce1a9c", "https://vgmdb.net/album/86056"]

[d8b0ebf35bedd348cd103889326b0498]
catalognumber = "SSX-10171"
date = "2010-09-08"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その3"
tracks = [
    [1, "プロローグ", "天草シノ", 0],
    [2, "スク水", "天草シノ", 0],
    [3, "睡眠聴取", "天草シノ", 0],
    [4, "制服", "天草シノ", 0],
    [5, "生徒会", "天草シノ", 0],
    [6, "タンポン", "天草シノ", 0],
    [7, "体育祭", "天草シノ", 0],
    [8, "チョコバナナ", "天草シノ", 0],
    [9, "手ブラ", "天草シノ", 0],
]
links = ["https://beta.musicbrainz.org/release/6cec03bc-edd8-4c38-9027-43b80e3b7a2a", "https://vgmdb.net/album/86057"]

[f69e90e0f56601456b9531b9b1a3e77d]
catalognumber = "SSX-10172"
date = "2010-09-22"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その4"
tracks = [
    [1, "プロローグ", "天草シノ", 0],
    [2, "手皿", "天草シノ", 0],
    [3, "貞操帯", "天草シノ", 0],
    [4, "トリプルブッキング", "天草シノ", 0],
    [5, "ドジっ娘", "天草シノ", 0],
    [6, "寝技", "天草シノ", 0],
    [7, "ハーレム", "天草シノ", 0],
    [8, "バレンタイン", "天草シノ", 0],
    [9, "ヒモパン", "天草シノ", 0],
]
links = ["https://beta.musicbrainz.org/release/ab3316af-e568-46a9-b573-f9c56c9855fd", "https://vgmdb.net/album/86058"]

[757eb868388ecdced1f66c25bd0e4161]
catalognumber = "SSX-10173"
date = "2010-10-06"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その5"
tracks = [
    [1, "プロローグ", "天草シノ", 0],
    [2, "袋とじ", "天草シノ", 0],
    [3, "風紀委員", "天草シノ", 0],
    [4, "保健室", "天草シノ", 0],
    [5, "本能寺", "天草シノ", 0],
    [6, "ボーイズラブ", "天草シノ", 0],
    [7, "マジカルマコ", "天草シノ", 0],
    [8, "舞妓のおしろいは白濁液", "天草シノ", 0],
]
links = ["https://beta.musicbrainz.org/release/0dee0696-830f-4730-963c-a6825136689c", "https://vgmdb.net/album/86059"]

[3451fc730ec4f59d6b5ce34589193052]
catalognumber = "KICA-3127"
date = "2010-10-27"
album = "生徒会役員共 オリジナルサウンドトラック シノ盤"
tracks = [
    [1, "生徒会役員共のマーチ", "森悠也", 0],
    [2, "はじまりはじまり", "森悠也", 0],
    [3, "朝の風景", "森悠也", 0],
    [4, "生徒会の日常", "森悠也", 0],
    [5, "低空飛行", "森悠也", 0],
    [6, "いきなりキレなくても･･･", "森悠也", 0],
    [7, "私立桜才学園第一応援歌", "森悠也", 0],
    [8, "私立桜才学園大運動会", "森悠也", 0],
    [9, "チャンチャン", "森悠也", 0],
    [10, "燃えよタカトシ", "森悠也", 0],
    [11, "進め! 役員共!", "森悠也", 0],
    [12, "さすが先輩!", "森悠也", 0],
    [13, "ぱぱらっち?", "森悠也", 0],
    [14, "来た来た", "森悠也", 0],
    [15, "和の魂", "森悠也", 0],
    [16, "怖っ!?", "森悠也", 0],
    [17, "夏だ! 海だ! ドライブだ!!", "森悠也", 0],
    [18, "風の大地", "森悠也", 0],
    [19, "ぴろぴぱっぱ", "森悠也", 0],
    [20, "Mr.J", "森悠也", 0],
    [21, "クリスマスの夜に", "森悠也", 0],
    [22, "せーのっ", "森悠也", 0],
    [23, "おまけ〜シノの日常〜 お菓子作り 編", "天草シノ(C.V.日笠陽子)", 0],
    [24, "おまけ〜シノの日常〜 天草会長に質問 編", "天草シノ(C.V.日笠陽子)", 0],
    [25, "おまけ〜シノの日常〜 自宅でのシノちゃん", "天草シノ(C.V.日笠陽子)", 0],
]
links = ["https://beta.musicbrainz.org/release/0d25c77b-83f6-4b45-bca1-fa498d7bd309", "https://vgmdb.net/album/21697"]

[98d4a1e717a005f2a6cfe9daa32c659a]
catalognumber = "SSX-10174"
date = "2010-10-27"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その6"
tracks = [
    [1, "プロローグ", "天草シノ", 0],
    [2, "枕投げ", "天草シノ", 0],
    [3, "メイド", "天草シノ", 0],
    [4, "メス犬", "天草シノ", 0],
    [5, "目安箱", "天草シノ", 0],
    [6, "ヤンデレ", "天草シノ", 0],
    [7, "野球拳", "天草シノ", 0],
    [8, "ロボット研究会", "天草シノ", 0],
]
links = ["https://beta.musicbrainz.org/release/6a6b6a25-c20b-451f-aad5-f59a8f2afd2d", "https://vgmdb.net/album/86060"]

[0d9a687b5a7fc7a6ac875ad471ea7d70]
catalognumber = "KICA-3128"
date = "2010-10-27"
album = "生徒会役員共 オリジナルサウンドトラック アリア盤"
tracks = [
    [1, "シノとタカトシ", "森悠也", 0],
    [2, "静かな朝なのに", "森悠也", 0],
    [3, "変なの", "森悠也", 0],
    [4, "パーティーしましょ", "森悠也", 0],
    [5, "そんなトコ･･･", "森悠也", 0],
    [6, "背徳のサクラ", "森悠也", 0],
    [7, "小さいものが一生懸命", "森悠也", 0],
    [8, "大邸宅にて", "森悠也", 0],
    [9, "教えてあげるっ", "森悠也", 0],
    [10, "やんなっちゃった", "森悠也", 0],
    [11, "ゆったりすっきりのんびり", "森悠也", 0],
    [12, "夜の…", "森悠也", 0],
    [13, "じかはつでん。", "森悠也", 0],
    [14, "雨の日の出来事", "森悠也", 0],
    [15, "僕のたからもの", "森悠也", 0],
    [16, "生徒会役員共のマーチ ～アコースティック～", "森悠也", 0],
    [17, "ネコと戯れる 編 (おまけ~アリアの日常~)", "七条アリア (C.V.佐藤聡美)", 0],
    [18, "七条先輩に質問 編 (おまけ~アリアの日常~)", "七条アリア (C.V.佐藤聡美)", 0],
    [19, "アリアとお散歩 編 (おまけ~アリアの日常~)", "七条アリア (C.V.佐藤聡美)", 0],
]
links = ["https://beta.musicbrainz.org/release/b85eaa22-75ee-4075-a803-8ba46815a6be", "https://vgmdb.net/album/21698"]

[cb26857881049063a2d7d78a5f944ef5]
catalognumber = "QWCE-00183"
date = "2010-11-17"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 11"
tracks = [
    [1, "大和撫子エデュケイション", "Hommarju feat.MAKI+405", 0],
    [2, "SWORD SUMMIT", "Hommarju feat.YOZU", 0],
    [3, "STRIKE WITCHES 2〜笑顔の魔法〜", "MK feat.R.Cena", 0],
    [4, "押しちゃうぞ!!", "Booing Day feat.R.Cena", 0],
    [5, "おしえてA TO Z", "MK feat.405", 0],
    [6, "SHIVER", "Hommarju feat.TAKANORI", 0],
    [7, "フライングヒューマノイド", "Dizzi Mystica feat.mi-mi", 0],
    [8, "恋華大乱", "Booing Day feat.mi-mi", 0],
    [9, "NOW LOADING...SKY!!", "Dizzi Mystica feat.MAKI", 0],
    [10, "シアワセは月より高く", "Dizzi Mystica feat.Latte", 0],
    [11, "FAST FORWARD", "Hommarju feat.Yusuke", 0],
    [12, "白翼ノ誓約〜PURE ENGAGEMENT〜", "MK feat.YURiE+MAKI", 0],
    [13, "LAMENT〜やがて喜びを〜", "Dizzi Mystica feat.YURiE", 0],
    [14, "鬼帝の剣", "Dizzi Mystica feat.yumemi", 0],
    [15, "みらくるハッピーディ", "Starving Trancer vs. Hommarju feat.PRIM", 0],
    [16, "くちづけ", "Hommarju feat.Yusuke", 0],
    [17, "バカ・ゴー・ホーム", "Dizzi Mystica feat.TAKANORI", 0],
    [18, "RING MY BELL", "Mitchy feat.R.Cena", 0],
    [19, "挑発CHERRY HEART", "Booing Day feat.yumemi", 0],
    [20, "I LOVE", "MK feat.R.Cena", 0],
]
links = ["https://beta.musicbrainz.org/release/70e1ef56-4de0-41b8-82a8-4c852952aff1", "https://vgmdb.net/album/33902"]

[aa4799596cb37d52bf2257f6c787615a]
catalognumber = "KICA-3134"
date = "2010-12-22"
album = "アニメ生徒会役員共が全部わかるラジオ、略して全ラ!の全て その壱"
tracks = [
    [1, "天草シノ役日笠陽子の全ラ!", "", 0],
    [2, "津田コトミ役下田麻美の全ラ!", "", 0],
    [3, "七条アリア役佐藤聡美の全ラ!", "", 0],
    [4, "出島サヤカ役田村睦心の全ラ!", "", 0],
    [5, "萩村スズ役矢作紗友里の全ラ!", "", 0],
    [6, "柳本ケンジ役白石稔の全ラ!", "", 0],
    [7, "畑ランコ役新井里美の全ラ!", "", 0],
    [8, "外国人・鷺・教師etc.役利根健太朗の全ラ!", "", 0],
    [9, "津田タカトシ役浅沼晋太郎の全ラ!", "", 0],
]
links = ["https://vgmdb.net/album/86148"]

[b20aa155692923f221e056855046464c]
catalognumber = "KICA-3135"
date = "2011-01-26"
album = "アニメ生徒会役員共が全部わかるラジオ、略して全ラ!の全て その弐"
tracks = [
    [1, "火照るから全ラ! (女子トーク)", "", 0],
    [2, "トレジャーハンターアドベンチャー (男子トーク)", "", 0],
]
links = ["https://vgmdb.net/album/86149"]

[bf654e6fa7552b2394f06bcb083755af]
catalognumber = "KICS-1676"
date = "2011-12-21"
album = "mirror☆ge / angela"
tracks = [
    [1, "蒼穹", "angela", 0],
    [2, "mirrorballs", "angela", 0],
    [3, "オルタナティヴ", "angela", 0],
    [4, "『リアル』は…", "angela", 0],
    [5, "理解と破壊へのプレリュード", "angela", 0],
    [6, "ぐるぐる☆ぼし", "angela", 0],
    [7, "Catch and Go!", "angela", 0],
    [8, "どんなに、、、どれくらい、、、", "angela", 0],
    [9, "Wonderful World", "angela", 0],
    [10, "FORTUNES", "angela", 0],
    [11, "蒼い春", "angela", 0],
    [12, "キラフワ", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/18460512-38ba-437a-a43e-70c4a782118b", "https://vgmdb.net/album/51809"]

[57a4a7ffd04a308865b85caf270cb6cc]
catalognumber = "KICA-3194"
date = "2012-04-25"
album = "アニメ『生徒会役員共』が全部わかるラジオMax Power、略して全ラ!まっぱ!! DJCD Vol.1"
tracks = [
    [1, "トレジャーハンターアドベンチャー～祝われしホワイトストーン～", "", 0],
    [2, "白石さん家で全ラ!まっぱ!!", "", 0],
]
links = ["https://vgmdb.net/album/86150"]

[3ce9b45d99f474cfa7a51ab335803d33]
catalognumber = "KICA-3195"
date = "2012-05-23"
album = "アニメ『生徒会役員共』が全部わかるラジオMax Power、略して全ラ!まっぱ!! DJCD Vol.2"
tracks = [
    [1, "全ラ!まっぱ!!......こんなに長いの初めて～!!", "", 0],
]
links = ["https://vgmdb.net/album/86151"]

[8eb9c3b1d0b1def7d054e55e54e5f838]
catalognumber = "FFCM-0029"
date = "2012-10-24"
album = "アニメ『生徒会役員共』が全部わかるラジオMax Power、略して全ラ!まっぱ!! DJCD Vol.3"
tracks = []
links = ["https://vgmdb.net/album/86154"]

[cef9c9e31b6073cc145762a6ccbb1aa8]
catalognumber = "KICM-3272"
date = "2014-01-22"
album = "花咲く☆最強レジェンドDays / トリプルブッキング"
tracks = [
    [1, "花咲く☆最強レジェンドDays", "トリプルブッキング", 0],
    [2, "青春爆走☆LOVE TRAIN", "トリプルブッキング", 0],
    [3, "花咲く☆最強レジェンドDays (off vocal ver.)", "トリプルブッキング", 0],
    [4, "青春爆走☆LOVE TRAIN (off vocal ver.)", "トリプルブッキング", 0],
]
links = ["https://beta.musicbrainz.org/release/8c471872-3564-448d-90be-e56b56c2a25e", "https://vgmdb.net/album/42342"]

[060231ffc01743dacde5b9f741f48c86]
catalognumber = "SSX-10301"
date = "2014-02-19"
album = "アイドルのすゝめ / 天草シノ CV:日笠陽子"
tracks = [
    [1, "アイドルのすゝめ -", "天草シノ CV:日笠陽子", 0],
    [2, "アイドルのすゝめ (off vocal ver.) -", "天草シノ CV:日笠陽子", 0],
]
links = ["https://beta.musicbrainz.org/release/3989affc-cb30-49a6-a980-0c10c8cd7a7a", "https://vgmdb.net/album/86044"]

[fe80a4865cb1418a9d0fdb8e46d2ce1d]
catalognumber = "KICM-3275"
date = "2014-02-26"
album = "ミライナイト / 佐藤聡美"
tracks = [
    [1, "ミライナイト", "佐藤聡美", 0],
    [2, "Brave Morning!!", "佐藤聡美", 0],
    [3, "ミライナイト (instrumental ver.)", "佐藤聡美", 0],
    [4, "Brave Morning!! (instrumental ver.)", "佐藤聡美", 0],
]
links = ["https://beta.musicbrainz.org/release/6e82f35d-be54-4261-b5d0-469c7e113929", "https://vgmdb.net/album/43050"]

[391bf1dd89c5a1ab78eb0434a41b83be]
catalognumber = "KICM-93275"
date = "2014-02-26"
album = "ミライナイト / 佐藤聡美 [初回限定盤] Disc 1 (CD) [KICM-93275]"
tracks = [
    [1, "ミライナイト", "佐藤聡美", 0],
    [2, "Brave Morning!!", "佐藤聡美", 0],
    [3, "ミライナイト (instrumental ver.)", "佐藤聡美", 0],
    [4, "Brave Morning!! (instrumental ver.)", "佐藤聡美", 0],
]
links = ["https://beta.musicbrainz.org/release/b2f2bcf9-9ff4-4121-9ba4-f7153e5afe76", "https://vgmdb.net/album/43051"]

[a147221be1e1e2531958892e3593f2cb]
catalognumber = "KICM-93275"
date = "2014-02-26"
album = "ミライナイト / 佐藤聡美 [初回限定盤] Disc 2 (DVD) [SDG-10401]"
tracks = [
    [1, "「ミライナイト」 MUSIC VIDEO", "", 0],
]
links = ["https://vgmdb.net/album/43051"]

[09736723e4eb4a45305820d80b6274bd]
catalognumber = "SSX-10302"
date = "2014-03-12"
album = "生徒会役員共＊ オリジナルサウンドトラック"
tracks = [
    [1, "Take Off", "森悠也", 0],
    [2, "生徒会役員共*のマーチ ～2nd Season～", "森悠也", 0],
    [3, "私はイベントごとは欠かさないのだ!", "森悠也", 0],
    [4, "桜の空", "森悠也 & 杉並児童合唱団", 0],
    [5, "ルーズな日常", "森悠也", 0],
    [6, "まかまか", "森悠也", 0],
    [7, "ちゅらかーぎー", "森悠也", 0],
    [8, "Wedding Fanfare", "森悠也", 0],
    [9, "胡桃割れない人形 ～森のワルツ～", "森悠也", 0],
    [10, "行ったれ! 役員共!!", "森悠也", 0],
    [11, "「人」という字は人と人が", "森悠也", 0],
    [12, "消えたスルメ...", "森悠也", 0],
    [13, "小さな幸せ", "森悠也", 0],
    [14, "朝のざわめき", "森悠也", 0],
    [15, "音頭7/4", "森悠也", 0],
    [16, "尻小玉抜いちゃうぞブルース", "森悠也", 0],
]
links = ["https://beta.musicbrainz.org/release/a6e47990-ab3f-4049-964b-492b15d8e0d0", "https://vgmdb.net/album/44775"]

[83997ec6cf53d724546e621cd5319bba]
catalognumber = "SSX-10303"
date = "2014-04-09"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @tvkアニメまつり -2014.01.19-"
tracks = [
    [1, "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @tvkアニメまつり -2014.01.19-", "", 0],
]
links = ["https://vgmdb.net/album/86051"]

[793db7972b99ffbd36b7c55f2b7ef5f9]
catalognumber = "SSX-10304"
date = "2014-05-14"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @Anime Japan 2014"
tracks = [
    [1, "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @Anime Japan 2014", "", 0],
]
links = ["https://vgmdb.net/album/86052"]

[3bfb7effbd9b7466ed46e87d43e77ce7]
catalognumber = "FFCC-0041"
date = "2014-05-28"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! *DJCD Vol.1*"
tracks = []
links = ["https://vgmdb.net/album/86155"]

[23d1ad26b1f2b24fb20cb8526e1f0f64]
catalognumber = "SSX-10305"
date = "2014-06-04"
album = "KOBAYASHI Teacher English"
tracks = [
    [1, "KOBAYASHI Teacher English", "", 0],
]
links = ["https://vgmdb.net/album/86053"]

[561393bdc86a82a062f42d3dfe6d3aad]
catalognumber = "FFCC-0042"
date = "2014-06-25"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! *DJCD Vol.2*"
tracks = []
links = ["https://vgmdb.net/album/86156"]

[68205fc20f1dd4fc5186fea15564cd62]
catalognumber = "SSX-10306"
date = "2014-07-09"
album = "機長's English"
tracks = [
    [1, "機長's English", "", 0],
]
links = ["https://vgmdb.net/album/86054"]

[5c860e8e799e70226f90ed4eeeb64c94]
catalognumber = "N/A"
date = "2014-07-09"
album = "生徒会役員共* animate特典ドラマCD 「朝の窓から朝の窓まで!」"
tracks = []
links = ["https://vgmdb.net/album/86147"]

[e8ab61ba5b3d5f3681945c35abc847ee]
catalognumber = "QWCE-00386"
date = "2014-10-01"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 22"
tracks = [
    [1, "シドニア", "Hommarju feat. R.Cena", 0],
    [2, "それは僕たちの奇跡", "Ryu☆ feat. Prim", 0],
    [3, "DIVINE INTERVENTION", "plazma feat. maburu-choko", 0],
    [4, "RISING HOPE", "plazma feat. 猫体質", 0],
    [5, "TILL THE END", "Dizzi Mystica feat. hideki + LTT", 0],
    [6, "彼女がフラグを立てる理由", "Booing Day feat. si-na + maburu-choko", 0],
    [7, "夕暮れハッピーゴー", "MK feat. Haruka + maburu-choko", 0],
    [8, "オラシオン", "Booing Day feat. SAYURI", 0],
    [9, "花咲く☆最強レジェンドDAYS", "Dizzi Mystica feat. R.Cena + KANA", 0],
    [10, "CHARMING DO!", "Hommarju feat. si-na", 0],
    [11, "純粋なフジュンブツ", "Booing Day feat. 405 + さつき", 0],
    [12, "DARAKENA", "MARS feat. mai", 0],
    [13, "BEAUTIFUL WORLD", "MK feat. Natsuhi", 0],
    [14, "BE AS ONE", "plazma feat. 桜井三郎 + Bavil", 0],
    [15, "掌ーSHOW-", "Hommarju feat. KANA", 0],
    [16, "イマジネーション", "Dizzi Mystica feat. Bavil", 0],
    [17, "TRUST IN YOU", "Flash back Dominant feat. Latte + Puchi", 0],
]
links = ["https://beta.musicbrainz.org/release/27ff9430-5739-4ccd-ae1a-e6ce7688ebf0", "https://vgmdb.net/album/46821"]

[82d096716b32f3ad6c33ab491b532838]
catalognumber = "KICA-3231"
date = "2014-10-22"
album = "生徒会役員共の楽曲が全部分かるラッキーなCD、略して、全ラ。"
tracks = [
    [1, "大和撫子エデュケイション", "トリプルブッキング", 0],
    [2, "情熱の花", "トリプルブッキング", 0],
    [3, "蒼い春", "angela", 0],
    [4, "花咲く☆最強レジェンドDays", "トリプルブッキング", 0],
    [5, "青春爆走☆LOVE TRAIN", "トリプルブッキング", 0],
    [6, "ミライナイト", "佐藤聡美", 0],
    [7, "アイドルのすゝめ", "天草シノ (日笠陽子)", 0],
    [8, "桜の空 (桜才学園校歌)", "杉並児童合唱団", 0],
    [9, "花咲く☆最強レジェンドDays (男祭りver.)", "トリプルブッキング", 0],
    [10, "KOBAYASHI Teacher ENGLISH2 (BONUS TRACK)", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/2d50aa4a-d172-4d84-85fb-90e59c1a3fe8", "https://vgmdb.net/album/47583"]

[133c8bdc69ab59ca4fd83bea345eb265]
catalognumber = "KIZX-181"
date = "2014-12-24"
album = "生徒会役員共 オリジナル・サウンドトラック[抜粋版]+生徒会役員共 秋の全力男祭り!!"
tracks = [
    [1, "生徒会役員共のマーチ", "森悠也", 0],
    [2, "はじまりはじまり", "森悠也", 0],
    [3, "朝の風景", "森悠也", 0],
    [4, "生徒会の日常", "森悠也", 0],
    [5, "低空飛行", "森悠也", 0],
    [6, "いきなりキレなくても...", "森悠也", 0],
    [7, "私立桜才学園第一応援歌", "森悠也", 0],
    [8, "チャンチャン", "森悠也", 0],
    [9, "進め!役員共!", "森悠也", 0],
    [10, "さすが先輩!", "森悠也", 0],
    [11, "ぱぱらっち?", "森悠也", 0],
    [12, "来た来た", "森悠也", 0],
    [13, "怖っ!?", "森悠也", 0],
    [14, "夏だ!海だ!ドライブだ!!", "森悠也", 0],
    [15, "ぴろぴぱっぱ", "森悠也", 0],
    [16, "せーのっ", "森悠也", 0],
    [17, "シノとタカトシ", "森悠也", 0],
    [18, "静かな朝なのに", "森悠也", 0],
    [19, "変なの", "森悠也", 0],
    [20, "パーティーしましょ", "森悠也", 0],
    [21, "そんなトコ...", "森悠也", 0],
    [22, "背徳のサクラ", "森悠也", 0],
    [23, "教えてあげるっ", "森悠也", 0],
    [24, "やんなっちゃった", "森悠也", 0],
    [25, "ゆったりすっきりのんびり", "森悠也", 0],
    [26, "夜の...", "森悠也", 0],
    [27, "僕のたからもの", "森悠也", 0],
    [28, "生徒会役員共 秋の全力男祭り!!～テリブルルッキング メジャーデビュー記者会見&緊急解散記者会見～", "森悠也", 0],
]
links = ["https://beta.musicbrainz.org/release/7f0eae87-e55e-445f-a327-4d2a959858ee", "https://vgmdb.net/album/68207"]

[ba5ff16daaf961c20df34156bc54f986]
catalognumber = "KIZX-184"
date = "2015-01-21"
album = "生徒会役員共特典ドラマCD「壁の向こうはつぼまみれ」"
tracks = [
    [1, "壁の向こうはつぼまみれ", "", 0],
]
links = ["https://vgmdb.net/album/86045"]

[7c331847ced7b8b37449a7a94787281f]
catalognumber = "KICM-3321"
date = "2017-07-19"
album = "青春ノンフィクション / トリプルブッキング"
tracks = [
    [1, "青春ノンフィクション", "トリプルブッキング", 0],
    [2, "ちはやふる恋してる", "トリプルブッキング", 0],
    [3, "青春ノンフィクション (off vocal ver.)", "トリプルブッキング", 0],
    [4, "ちはやふる恋してる (off vocal ver.)", "トリプルブッキング", 0],
]
links = ["https://beta.musicbrainz.org/release/257922b8-88fd-4c5f-8e4d-3763b3c32561", "https://vgmdb.net/album/67529"]

[e0dbcdfaea650d2c005ff13be1428b95]
catalognumber = "KIZX-294"
date = "2017-07-19"
album = "生徒会役員共* Blu-ray BOX 特典CD"
tracks = [
    [1, "ドラマ「ムツミ格闘技教室!」", "", 0],
    [2, "「劇場版 生徒会役員共 web ラジオ公録イベント～昼の部～」", "", 0],
]
links = ["https://vgmdb.net/album/69999"]

[aff7b4be5bb6f2032f92c829cf418ac4]
catalognumber = "KICS-3757~8"
date = "2018-10-24"
album = "angela ALL TIME BEST 2010-2017 / angela Disc 1 [KICS-3757]"
tracks = [
    [1, "蒼い春", "angela", 0],
    [2, "FORTUNES", "angela", 0],
    [3, "蒼穹", "angela", 0],
    [4, "さよならの時くらい微笑んで", "angela", 0],
    [5, "「リアル」は・・・", "angela", 0],
    [6, "キラフワ", "angela", 0],
    [7, "THE LIGHTS OF HEROES", "angela", 0],
    [8, "いつかのゼロから", "angela", 0],
    [9, "KINGS", "angela", 0],
    [10, "To be with U!", "angela", 0],
    [11, "僕じゃない", "angela", 0],
    [12, "ANGEL", "angela", 0],
    [13, "遠くまで", "angela", 0],
    [14, "バイバイオーライ", "angela", 0],
    [15, "キラキラ-go-round", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/9dfdba84-d4b1-435b-b103-bf4fb4644c9d", "https://vgmdb.net/album/81664"]

[4d7c30fce450c70bd6ccd7fd725a5ffa]
catalognumber = "KICS-3757~8"
date = "2018-10-24"
album = "angela ALL TIME BEST 2010-2017 / angela Disc 2 [KICS-3758]"
tracks = [
    [1, "シドニア", "angela", 0],
    [2, "Different colors", "angela", 0],
    [3, "イグジスト", "angela", 0],
    [4, "暗夜航路", "angela", 0],
    [5, "その時、蒼穹へ", "angela", 0],
    [6, "愛、ひと欠片", "angela", 0],
    [7, "騎士行進曲", "angela", 0],
    [8, "DEAD OR ALIVE", "angela", 0],
    [9, "ホライズン", "angela", 0],
    [10, "愛すること", "angela", 0],
    [11, "KIZUNA", "angela", 0],
    [12, "僕は僕であって", "angela×fripSide", 0],
    [13, "全力☆Summer!", "angela", 0],
    [14, "Calling you", "angela", 0],
    [15, "笑顔をみせて", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/9dfdba84-d4b1-435b-b103-bf4fb4644c9d", "https://vgmdb.net/album/81664"]
