[d27973b8589b0906f0dce2e3c62321e6]
catalognumber = "KICM-3211"
date = "2010-07-21"
album = "大和撫子エデュケイション / トリプルブッキング"
tracks = [
    [1, "大和撫子エデュケイション", "トリプルブッキング", 1],
    [2, "情熱の花", "トリプルブッキング", 1],
    [3, "大和撫子エデュケイション (off vocal ver.)", "トリプルブッキング", 1],
    [4, "情熱の花 (off vocal ver.)", "トリプルブッキング", 1],
]
links = ["https://beta.musicbrainz.org/release/aa0d20be-397f-486c-a520-fa0a7e31be1e", "https://vgmdb.net/album/44501"]

[d15d84d1e2d107896dca787d80c73ea5]
catalognumber = "KICM-3212"
date = "2010-07-28"
album = "蒼い春 / angela"
tracks = [
    [1, "蒼い春", "angela", 1],
    [2, "ツナガル→ム", "angela", 1],
    [3, "蒼い春 (off vocal version)", "angela", 1],
    [4, "ツナガル→ム (off vocal version)", "angela", 1],
]
links = ["https://beta.musicbrainz.org/release/12daf29c-969d-4496-a934-532a77ad9092", "https://vgmdb.net/album/47110"]

[8201eadb97d0de25ed7c5aebd4d075d2]
catalognumber = "SSX-10169"
date = "2010-08-04"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その1"
tracks = [
    [1, "プロローグ", "天草シノ", 1],
    [2, "赤い糸", "天草シノ", 1],
    [3, "イルカ", "天草シノ", 1],
    [4, "オナ禁は解禁", "天草シノ", 1],
    [5, "桜才祭", "天草シノ", 1],
    [6, "重い日", "天草シノ", 1],
    [7, "幼なじみ", "天草シノ", 1],
    [8, "金閣寺", "天草シノ", 1],
    [9, "クールビズ", "天草シノ", 1],
]
links = ["https://beta.musicbrainz.org/release/1ac557b2-dffc-425b-ad57-c137e2175b61", "https://vgmdb.net/album/86055"]

[66a8857a3f6298c5e9fa60ec00b508e5]
catalognumber = "SSX-10170"
date = "2010-08-25"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その2"
tracks = [
    [1, "プロローグ", "天草シノ", 1],
    [2, "衣替え", "天草シノ", 1],
    [3, "混浴", "天草シノ", 1],
    [4, "合法的な露出", "天草シノ", 1],
    [5, "思春期", "天草シノ", 1],
    [6, "修学旅行", "天草シノ", 1],
    [7, "新聞部", "天草シノ", 1],
    [8, "女子高", "天草シノ", 1],
    [9, "柔道部", "天草シノ", 1],
]
links = ["https://beta.musicbrainz.org/release/324081c4-4773-42ae-85e3-421074ce1a9c", "https://vgmdb.net/album/86056"]

[e02fbf3d5b45358704a0c747bf5d5153]
catalognumber = "SSX-10171"
date = "2010-09-08"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その3"
tracks = [
    [1, "プロローグ", "天草シノ", 1],
    [2, "スク水", "天草シノ", 1],
    [3, "睡眠聴取", "天草シノ", 1],
    [4, "制服", "天草シノ", 1],
    [5, "生徒会", "天草シノ", 1],
    [6, "タンポン", "天草シノ", 1],
    [7, "体育祭", "天草シノ", 1],
    [8, "チョコバナナ", "天草シノ", 1],
    [9, "手ブラ", "天草シノ", 1],
]
links = ["https://beta.musicbrainz.org/release/6cec03bc-edd8-4c38-9027-43b80e3b7a2a", "https://vgmdb.net/album/86057"]

[f37f92f541898fcb65e9658e40bacaf7]
catalognumber = "SSX-10172"
date = "2010-09-22"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その4"
tracks = [
    [1, "プロローグ", "天草シノ", 1],
    [2, "手皿", "天草シノ", 1],
    [3, "貞操帯", "天草シノ", 1],
    [4, "トリプルブッキング", "天草シノ", 1],
    [5, "ドジっ娘", "天草シノ", 1],
    [6, "寝技", "天草シノ", 1],
    [7, "ハーレム", "天草シノ", 1],
    [8, "バレンタイン", "天草シノ", 1],
    [9, "ヒモパン", "天草シノ", 1],
]
links = ["https://beta.musicbrainz.org/release/ab3316af-e568-46a9-b573-f9c56c9855fd", "https://vgmdb.net/album/86058"]

[0e08040bca1ee41b9de8526fc90e819b]
catalognumber = "SSX-10173"
date = "2010-10-06"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その5"
tracks = [
    [1, "プロローグ", "天草シノ", 1],
    [2, "袋とじ", "天草シノ", 1],
    [3, "風紀委員", "天草シノ", 1],
    [4, "保健室", "天草シノ", 1],
    [5, "本能寺", "天草シノ", 1],
    [6, "ボーイズラブ", "天草シノ", 1],
    [7, "マジカルマコ", "天草シノ", 1],
    [8, "舞妓のおしろいは白濁液", "天草シノ", 1],
]
links = ["https://beta.musicbrainz.org/release/0dee0696-830f-4730-963c-a6825136689c", "https://vgmdb.net/album/86059"]

[72afd32bd1a3a381c6b1809ff4a1aeaf]
catalognumber = "KICA-3127"
date = "2010-10-27"
album = "生徒会役員共 オリジナルサウンドトラック シノ盤"
tracks = [
    [1, "生徒会役員共のマーチ", "森悠也", 1],
    [2, "はじまりはじまり", "森悠也", 1],
    [3, "朝の風景", "森悠也", 1],
    [4, "生徒会の日常", "森悠也", 1],
    [5, "低空飛行", "森悠也", 1],
    [6, "いきなりキレなくても･･･", "森悠也", 1],
    [7, "私立桜才学園第一応援歌", "森悠也", 1],
    [8, "私立桜才学園大運動会", "森悠也", 1],
    [9, "チャンチャン", "森悠也", 1],
    [10, "燃えよタカトシ", "森悠也", 1],
    [11, "進め! 役員共!", "森悠也", 1],
    [12, "さすが先輩!", "森悠也", 1],
    [13, "ぱぱらっち?", "森悠也", 1],
    [14, "来た来た", "森悠也", 1],
    [15, "和の魂", "森悠也", 1],
    [16, "怖っ!?", "森悠也", 1],
    [17, "夏だ! 海だ! ドライブだ!!", "森悠也", 1],
    [18, "風の大地", "森悠也", 1],
    [19, "ぴろぴぱっぱ", "森悠也", 1],
    [20, "Mr.J", "森悠也", 1],
    [21, "クリスマスの夜に", "森悠也", 1],
    [22, "せーのっ", "森悠也", 1],
    [23, "おまけ〜シノの日常〜 お菓子作り 編", "天草シノ(C.V.日笠陽子)", 1],
    [24, "おまけ〜シノの日常〜 天草会長に質問 編", "天草シノ(C.V.日笠陽子)", 1],
    [25, "おまけ〜シノの日常〜 自宅でのシノちゃん", "天草シノ(C.V.日笠陽子)", 1],
]
links = ["https://beta.musicbrainz.org/release/0d25c77b-83f6-4b45-bca1-fa498d7bd309", "https://vgmdb.net/album/21697"]

[6bbdd29a3859cd28dd97956a25fb7448]
catalognumber = "SSX-10174"
date = "2010-10-27"
album = "桜才学園生徒会会長天草シノによる生徒会役員共的辞書その6"
tracks = [
    [1, "プロローグ", "天草シノ", 1],
    [2, "枕投げ", "天草シノ", 1],
    [3, "メイド", "天草シノ", 1],
    [4, "メス犬", "天草シノ", 1],
    [5, "目安箱", "天草シノ", 1],
    [6, "ヤンデレ", "天草シノ", 1],
    [7, "野球拳", "天草シノ", 1],
    [8, "ロボット研究会", "天草シノ", 1],
]
links = ["https://beta.musicbrainz.org/release/6a6b6a25-c20b-451f-aad5-f59a8f2afd2d", "https://vgmdb.net/album/86060"]

[c97c2049baf2c55fbb3631481b11cab2]
catalognumber = "KICA-3128"
date = "2010-10-27"
album = "生徒会役員共 オリジナルサウンドトラック アリア盤"
tracks = [
    [1, "シノとタカトシ", "森悠也", 1],
    [2, "静かな朝なのに", "森悠也", 1],
    [3, "変なの", "森悠也", 1],
    [4, "パーティーしましょ", "森悠也", 1],
    [5, "そんなトコ･･･", "森悠也", 1],
    [6, "背徳のサクラ", "森悠也", 1],
    [7, "小さいものが一生懸命", "森悠也", 1],
    [8, "大邸宅にて", "森悠也", 1],
    [9, "教えてあげるっ", "森悠也", 1],
    [10, "やんなっちゃった", "森悠也", 1],
    [11, "ゆったりすっきりのんびり", "森悠也", 1],
    [12, "夜の…", "森悠也", 1],
    [13, "じかはつでん。", "森悠也", 1],
    [14, "雨の日の出来事", "森悠也", 1],
    [15, "僕のたからもの", "森悠也", 1],
    [16, "生徒会役員共のマーチ ～アコースティック～", "森悠也", 1],
    [17, "ネコと戯れる 編 (おまけ~アリアの日常~)", "七条アリア (C.V.佐藤聡美)", 1],
    [18, "七条先輩に質問 編 (おまけ~アリアの日常~)", "七条アリア (C.V.佐藤聡美)", 1],
    [19, "アリアとお散歩 編 (おまけ~アリアの日常~)", "七条アリア (C.V.佐藤聡美)", 1],
]
links = ["https://beta.musicbrainz.org/release/b85eaa22-75ee-4075-a803-8ba46815a6be", "https://vgmdb.net/album/21698"]

[a03c270d38e9f6e9323800ea8e1beb0a]
catalognumber = "QWCE-00183"
date = "2010-11-17"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 11"
tracks = [
    [1, "大和撫子エデュケイション", "Hommarju feat.MAKI+405", 1],
    [2, "SWORD SUMMIT", "Hommarju feat.YOZU", 0],
    [3, "STRIKE WITCHES 2〜笑顔の魔法〜", "MK feat.R.Cena", 0],
    [4, "押しちゃうぞ!!", "Booing Day feat.R.Cena", 0],
    [5, "おしえてA TO Z", "MK feat.405", 0],
    [6, "SHIVER", "Hommarju feat.TAKANORI", 0],
    [7, "フライングヒューマノイド", "Dizzi Mystica feat.mi-mi", 0],
    [8, "恋華大乱", "Booing Day feat.mi-mi", 0],
    [9, "NOW LOADING...SKY!!", "Dizzi Mystica feat.MAKI", 0],
    [10, "シアワセは月より高く", "Dizzi Mystica feat.Latte", 0],
    [11, "FAST FORWARD", "Hommarju feat.Yusuke", 0],
    [12, "白翼ノ誓約〜PURE ENGAGEMENT〜", "MK feat.YURiE+MAKI", 0],
    [13, "LAMENT〜やがて喜びを〜", "Dizzi Mystica feat.YURiE", 0],
    [14, "鬼帝の剣", "Dizzi Mystica feat.yumemi", 0],
    [15, "みらくるハッピーディ", "Starving Trancer vs. Hommarju feat.PRIM", 0],
    [16, "くちづけ", "Hommarju feat.Yusuke", 0],
    [17, "バカ・ゴー・ホーム", "Dizzi Mystica feat.TAKANORI", 0],
    [18, "RING MY BELL", "Mitchy feat.R.Cena", 0],
    [19, "挑発CHERRY HEART", "Booing Day feat.yumemi", 0],
    [20, "I LOVE", "MK feat.R.Cena", 0],
]
links = ["https://beta.musicbrainz.org/release/70e1ef56-4de0-41b8-82a8-4c852952aff1", "https://vgmdb.net/album/33902"]

[7e13a92981f4814840d9dbe6884f7383]
catalognumber = "KICA-3134"
date = "2010-12-22"
album = "アニメ生徒会役員共が全部わかるラジオ、略して全ラ!の全て その壱"
tracks = [
    [1, "天草シノ役日笠陽子の全ラ!", "", 1],
    [2, "津田コトミ役下田麻美の全ラ!", "", 1],
    [3, "七条アリア役佐藤聡美の全ラ!", "", 1],
    [4, "出島サヤカ役田村睦心の全ラ!", "", 1],
    [5, "萩村スズ役矢作紗友里の全ラ!", "", 1],
    [6, "柳本ケンジ役白石稔の全ラ!", "", 1],
    [7, "畑ランコ役新井里美の全ラ!", "", 1],
    [8, "外国人・鷺・教師etc.役利根健太朗の全ラ!", "", 1],
    [9, "津田タカトシ役浅沼晋太郎の全ラ!", "", 1],
]
links = ["https://vgmdb.net/album/86148"]

[0fdc67de842d60f8490f20f5e16c55bd]
catalognumber = "KICA-3135"
date = "2011-01-26"
album = "アニメ生徒会役員共が全部わかるラジオ、略して全ラ!の全て その弐"
tracks = [
    [1, "火照るから全ラ! (女子トーク)", "", 1],
    [2, "トレジャーハンターアドベンチャー (男子トーク)", "", 1],
]
links = ["https://vgmdb.net/album/86149"]

[5301f61685ccb1bead9c66b5468fc1d6]
catalognumber = "KICS-1676"
date = "2011-12-21"
album = "mirror☆ge / angela"
tracks = [
    [1, "蒼穹", "angela", 0],
    [2, "mirrorballs", "angela", 0],
    [3, "オルタナティヴ", "angela", 0],
    [4, "『リアル』は…", "angela", 0],
    [5, "理解と破壊へのプレリュード", "angela", 0],
    [6, "ぐるぐる☆ぼし", "angela", 0],
    [7, "Catch and Go!", "angela", 0],
    [8, "どんなに、、、どれくらい、、、", "angela", 0],
    [9, "Wonderful World", "angela", 0],
    [10, "FORTUNES", "angela", 0],
    [11, "蒼い春", "angela", 1],
    [12, "キラフワ", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/18460512-38ba-437a-a43e-70c4a782118b", "https://vgmdb.net/album/51809"]

[1853395a4128d1c21e9044cce618ed7d]
catalognumber = "KICA-3194"
date = "2012-04-25"
album = "アニメ『生徒会役員共』が全部わかるラジオMax Power、略して全ラ!まっぱ!! DJCD Vol.1"
tracks = [
    [1, "トレジャーハンターアドベンチャー～祝われしホワイトストーン～", "", 0],
    [2, "白石さん家で全ラ!まっぱ!!", "", 0],
]
links = ["https://vgmdb.net/album/86150"]

[fa35337e5ee13497fab6989e31763071]
catalognumber = "KICA-3195"
date = "2012-05-23"
album = "アニメ『生徒会役員共』が全部わかるラジオMax Power、略して全ラ!まっぱ!! DJCD Vol.2"
tracks = [
    [1, "全ラ!まっぱ!!......こんなに長いの初めて～!!", "", 1],
]
links = ["https://vgmdb.net/album/86151"]

[debe45417a1acf6cc15ad72ab089c97f]
catalognumber = "FFCM-0029"
date = "2012-10-24"
album = "アニメ『生徒会役員共』が全部わかるラジオMax Power、略して全ラ!まっぱ!! DJCD Vol.3"
tracks = []
links = ["https://vgmdb.net/album/86154"]

[27b9e619cd5265cd072eefbc2f645be8]
catalognumber = "KICM-3272"
date = "2014-01-22"
album = "花咲く☆最強レジェンドDays / トリプルブッキング"
tracks = [
    [1, "花咲く☆最強レジェンドDays", "トリプルブッキング", 1],
    [2, "青春爆走☆LOVE TRAIN", "トリプルブッキング", 1],
    [3, "花咲く☆最強レジェンドDays (off vocal ver.)", "トリプルブッキング", 1],
    [4, "青春爆走☆LOVE TRAIN (off vocal ver.)", "トリプルブッキング", 1],
]
links = ["https://beta.musicbrainz.org/release/8c471872-3564-448d-90be-e56b56c2a25e", "https://vgmdb.net/album/42342"]

[748252da14c8a3e31296d2afe04f1d68]
catalognumber = "SSX-10301"
date = "2014-02-19"
album = "アイドルのすゝめ / 天草シノ CV:日笠陽子"
tracks = [
    [1, "アイドルのすゝめ -", "天草シノ CV:日笠陽子", 1],
    [2, "アイドルのすゝめ (off vocal ver.) -", "天草シノ CV:日笠陽子", 1],
]
links = ["https://beta.musicbrainz.org/release/3989affc-cb30-49a6-a980-0c10c8cd7a7a", "https://vgmdb.net/album/86044"]

[90f948f3f86fc0a36e014a8fc6c3fef4]
catalognumber = "KICM-3275"
date = "2014-02-26"
album = "ミライナイト / 佐藤聡美"
tracks = [
    [1, "ミライナイト", "佐藤聡美", 2],
    [2, "Brave Morning!!", "佐藤聡美", 1],
    [3, "ミライナイト (instrumental ver.)", "佐藤聡美", 1],
    [4, "Brave Morning!! (instrumental ver.)", "佐藤聡美", 1],
]
links = ["https://beta.musicbrainz.org/release/6e82f35d-be54-4261-b5d0-469c7e113929", "https://vgmdb.net/album/43050"]

[c4a60817d0679b8ffefd8293df03f8c2]
catalognumber = "KICM-93275"
date = "2014-02-26"
album = "ミライナイト / 佐藤聡美 [初回限定盤] Disc 1 (CD) [KICM-93275]"
tracks = [
    [1, "ミライナイト", "佐藤聡美", 1],
    [2, "Brave Morning!!", "佐藤聡美", 1],
    [3, "ミライナイト (instrumental ver.)", "佐藤聡美", 1],
    [4, "Brave Morning!! (instrumental ver.)", "佐藤聡美", 1],
]
links = ["https://beta.musicbrainz.org/release/b2f2bcf9-9ff4-4121-9ba4-f7153e5afe76", "https://vgmdb.net/album/43051"]

[73820471d85dd272cc299247e1e5a9b5]
catalognumber = "KICM-93275"
date = "2014-02-26"
album = "ミライナイト / 佐藤聡美 [初回限定盤] Disc 2 (DVD) [SDG-10401]"
tracks = [
    [1, "「ミライナイト」 MUSIC VIDEO", "", 0],
]
links = ["https://vgmdb.net/album/43051"]

[0061d2f707bf34238296555badd763f1]
catalognumber = "SSX-10302"
date = "2014-03-12"
album = "生徒会役員共＊ オリジナルサウンドトラック"
tracks = [
    [1, "Take Off", "森悠也", 1],
    [2, "生徒会役員共*のマーチ ～2nd Season～", "森悠也", 1],
    [3, "私はイベントごとは欠かさないのだ!", "森悠也", 1],
    [4, "桜の空", "森悠也 & 杉並児童合唱団", 1],
    [5, "ルーズな日常", "森悠也", 1],
    [6, "まかまか", "森悠也", 1],
    [7, "ちゅらかーぎー", "森悠也", 1],
    [8, "Wedding Fanfare", "森悠也", 1],
    [9, "胡桃割れない人形 ～森のワルツ～", "森悠也", 1],
    [10, "行ったれ! 役員共!!", "森悠也", 1],
    [11, "「人」という字は人と人が", "森悠也", 1],
    [12, "消えたスルメ...", "森悠也", 1],
    [13, "小さな幸せ", "森悠也", 1],
    [14, "朝のざわめき", "森悠也", 1],
    [15, "音頭7/4", "森悠也", 1],
    [16, "尻小玉抜いちゃうぞブルース", "森悠也", 1],
]
links = ["https://beta.musicbrainz.org/release/a6e47990-ab3f-4049-964b-492b15d8e0d0", "https://vgmdb.net/album/44775"]

[86408c68be7e7f2a4a892cfc7b203340]
catalognumber = "SSX-10303"
date = "2014-04-09"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @tvkアニメまつり -2014.01.19-"
tracks = [
    [1, "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @tvkアニメまつり -2014.01.19-", "", 1],
]
links = ["https://vgmdb.net/album/86051"]

[e800bd6888f951722141df61d448ba3b]
catalognumber = "SSX-10304"
date = "2014-05-14"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @Anime Japan 2014"
tracks = [
    [1, "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! @Anime Japan 2014", "", 1],
]
links = ["https://vgmdb.net/album/86052"]

[f5eeb112d5236c88fb05ef45b9f9a25e]
catalognumber = "FFCC-0041"
date = "2014-05-28"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! *DJCD Vol.1*"
tracks = []
links = ["https://vgmdb.net/album/86155"]

[8b7d364c4e794929935a5b84ee5cb491]
catalognumber = "SSX-10305"
date = "2014-06-04"
album = "KOBAYASHI Teacher English"
tracks = [
    [1, "KOBAYASHI Teacher English", "", 1],
]
links = ["https://vgmdb.net/album/86053"]

[8a7f59b3aeb0fdbf6cf3ba717df3658f]
catalognumber = "FFCC-0042"
date = "2014-06-25"
album = "アニメ『生徒会役員共*』が全部わかるラジオ Super Positive Nippon、略して全ラ!すっぽんぽん!! *DJCD Vol.2*"
tracks = []
links = ["https://vgmdb.net/album/86156"]

[807b7386e7b8f469e89ea7c6d43ad8c1]
catalognumber = "SSX-10306"
date = "2014-07-09"
album = "機長's English"
tracks = [
    [1, "機長's English", "", 1],
]
links = ["https://vgmdb.net/album/86054"]

[f0b245776e41e53c578c4af5e9e8e21f]
catalognumber = "N/A"
date = "2014-07-09"
album = "生徒会役員共* animate特典ドラマCD 「朝の窓から朝の窓まで!」"
tracks = []
links = ["https://vgmdb.net/album/86147"]

[547bd3acaf302ef163162b4d611b401d]
catalognumber = "QWCE-00386"
date = "2014-10-01"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 22"
tracks = [
    [1, "シドニア", "Hommarju feat. R.Cena", 0],
    [2, "それは僕たちの奇跡", "Ryu☆ feat. Prim", 0],
    [3, "DIVINE INTERVENTION", "plazma feat. maburu-choko", 0],
    [4, "RISING HOPE", "plazma feat. 猫体質", 0],
    [5, "TILL THE END", "Dizzi Mystica feat. hideki + LTT", 0],
    [6, "彼女がフラグを立てる理由", "Booing Day feat. si-na + maburu-choko", 0],
    [7, "夕暮れハッピーゴー", "MK feat. Haruka + maburu-choko", 0],
    [8, "オラシオン", "Booing Day feat. SAYURI", 0],
    [9, "花咲く☆最強レジェンドDAYS", "Dizzi Mystica feat. R.Cena + KANA", 1],
    [10, "CHARMING DO!", "Hommarju feat. si-na", 0],
    [11, "純粋なフジュンブツ", "Booing Day feat. 405 + さつき", 0],
    [12, "DARAKENA", "MARS feat. mai", 0],
    [13, "BEAUTIFUL WORLD", "MK feat. Natsuhi", 0],
    [14, "BE AS ONE", "plazma feat. 桜井三郎 + Bavil", 0],
    [15, "掌ーSHOW-", "Hommarju feat. KANA", 0],
    [16, "イマジネーション", "Dizzi Mystica feat. Bavil", 0],
    [17, "TRUST IN YOU", "Flash back Dominant feat. Latte + Puchi", 0],
]
links = ["https://beta.musicbrainz.org/release/27ff9430-5739-4ccd-ae1a-e6ce7688ebf0", "https://vgmdb.net/album/46821"]

[1cba258c585d211cb38c40e9ae799b22]
catalognumber = "KICA-3231"
date = "2014-10-22"
album = "生徒会役員共の楽曲が全部分かるラッキーなCD、略して、全ラ。"
tracks = [
    [1, "大和撫子エデュケイション", "トリプルブッキング", 1],
    [2, "情熱の花", "トリプルブッキング", 1],
    [3, "蒼い春", "angela", 1],
    [4, "花咲く☆最強レジェンドDays", "トリプルブッキング", 1],
    [5, "青春爆走☆LOVE TRAIN", "トリプルブッキング", 1],
    [6, "ミライナイト", "佐藤聡美", 1],
    [7, "アイドルのすゝめ", "天草シノ (日笠陽子)", 1],
    [8, "桜の空 (桜才学園校歌)", "杉並児童合唱団", 1],
    [9, "花咲く☆最強レジェンドDays (男祭りver.)", "トリプルブッキング", 1],
    [10, "KOBAYASHI Teacher ENGLISH2 (BONUS TRACK)", "[dialogue]", 1],
]
links = ["https://beta.musicbrainz.org/release/2d50aa4a-d172-4d84-85fb-90e59c1a3fe8", "https://vgmdb.net/album/47583"]

[194a20406744487f62d7ae11778d8f3b]
catalognumber = "KIZX-181"
date = "2014-12-24"
album = "生徒会役員共 オリジナル・サウンドトラック[抜粋版]+生徒会役員共 秋の全力男祭り!!"
tracks = [
    [1, "生徒会役員共のマーチ", "森悠也", 1],
    [2, "はじまりはじまり", "森悠也", 1],
    [3, "朝の風景", "森悠也", 1],
    [4, "生徒会の日常", "森悠也", 1],
    [5, "低空飛行", "森悠也", 1],
    [6, "いきなりキレなくても...", "森悠也", 1],
    [7, "私立桜才学園第一応援歌", "森悠也", 1],
    [8, "チャンチャン", "森悠也", 1],
    [9, "進め!役員共!", "森悠也", 1],
    [10, "さすが先輩!", "森悠也", 1],
    [11, "ぱぱらっち?", "森悠也", 1],
    [12, "来た来た", "森悠也", 1],
    [13, "怖っ!?", "森悠也", 1],
    [14, "夏だ!海だ!ドライブだ!!", "森悠也", 1],
    [15, "ぴろぴぱっぱ", "森悠也", 1],
    [16, "せーのっ", "森悠也", 1],
    [17, "シノとタカトシ", "森悠也", 1],
    [18, "静かな朝なのに", "森悠也", 1],
    [19, "変なの", "森悠也", 1],
    [20, "パーティーしましょ", "森悠也", 1],
    [21, "そんなトコ...", "森悠也", 1],
    [22, "背徳のサクラ", "森悠也", 1],
    [23, "教えてあげるっ", "森悠也", 1],
    [24, "やんなっちゃった", "森悠也", 1],
    [25, "ゆったりすっきりのんびり", "森悠也", 1],
    [26, "夜の...", "森悠也", 1],
    [27, "僕のたからもの", "森悠也", 1],
    [28, "生徒会役員共 秋の全力男祭り!!～テリブルルッキング メジャーデビュー記者会見&緊急解散記者会見～", "森悠也", 1],
]
links = ["https://beta.musicbrainz.org/release/7f0eae87-e55e-445f-a327-4d2a959858ee", "https://vgmdb.net/album/68207"]

[66c61b4046ff512e3d19ae5d30c0cb98]
catalognumber = "KIZX-184"
date = "2015-01-21"
album = "生徒会役員共特典ドラマCD「壁の向こうはつぼまみれ」"
tracks = [
    [1, "壁の向こうはつぼまみれ", "", 1],
]
links = ["https://vgmdb.net/album/86045"]

[58dcd43038242d5bce2504c2dbb18943]
catalognumber = "KICM-3321"
date = "2017-07-19"
album = "青春ノンフィクション / トリプルブッキング"
tracks = [
    [1, "青春ノンフィクション", "トリプルブッキング", 1],
    [2, "ちはやふる恋してる", "トリプルブッキング", 1],
    [3, "青春ノンフィクション (off vocal ver.)", "トリプルブッキング", 1],
    [4, "ちはやふる恋してる (off vocal ver.)", "トリプルブッキング", 1],
]
links = ["https://beta.musicbrainz.org/release/257922b8-88fd-4c5f-8e4d-3763b3c32561", "https://vgmdb.net/album/67529"]

[944f701683521690f0bd6255aef807fa]
catalognumber = "KIZX-294"
date = "2017-07-19"
album = "生徒会役員共* Blu-ray BOX 特典CD"
tracks = [
    [1, "ドラマ「ムツミ格闘技教室!」", "", 1],
    [2, "「劇場版 生徒会役員共 web ラジオ公録イベント～昼の部～」", "", 1],
]
links = ["https://vgmdb.net/album/69999"]

[1044fa89fe8cbc73f891a5465c03c848]
catalognumber = "KICS-3757~8"
date = "2018-10-24"
album = "angela ALL TIME BEST 2010-2017 / angela Disc 1 [KICS-3757]"
tracks = [
    [1, "蒼い春", "angela", 1],
    [2, "FORTUNES", "angela", 0],
    [3, "蒼穹", "angela", 0],
    [4, "さよならの時くらい微笑んで", "angela", 0],
    [5, "「リアル」は・・・", "angela", 0],
    [6, "キラフワ", "angela", 0],
    [7, "THE LIGHTS OF HEROES", "angela", 0],
    [8, "いつかのゼロから", "angela", 0],
    [9, "KINGS", "angela", 0],
    [10, "To be with U!", "angela", 0],
    [11, "僕じゃない", "angela", 0],
    [12, "ANGEL", "angela", 0],
    [13, "遠くまで", "angela", 0],
    [14, "バイバイオーライ", "angela", 0],
    [15, "キラキラ-go-round", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/9dfdba84-d4b1-435b-b103-bf4fb4644c9d", "https://vgmdb.net/album/81664"]

[219c40c3acd8583f56e3546453dce088]
catalognumber = "KICS-3757~8"
date = "2018-10-24"
album = "angela ALL TIME BEST 2010-2017 / angela Disc 2 [KICS-3758]"
tracks = [
    [1, "シドニア", "angela", 0],
    [2, "Different colors", "angela", 0],
    [3, "イグジスト", "angela", 0],
    [4, "暗夜航路", "angela", 0],
    [5, "その時、蒼穹へ", "angela", 0],
    [6, "愛、ひと欠片", "angela", 0],
    [7, "騎士行進曲", "angela", 0],
    [8, "DEAD OR ALIVE", "angela", 0],
    [9, "ホライズン", "angela", 0],
    [10, "愛すること", "angela", 0],
    [11, "KIZUNA", "angela", 0],
    [12, "僕は僕であって", "angela×fripSide", 0],
    [13, "全力☆Summer!", "angela", 0],
    [14, "Calling you", "angela", 0],
    [15, "笑顔をみせて", "angela", 0],
]
links = ["https://beta.musicbrainz.org/release/9dfdba84-d4b1-435b-b103-bf4fb4644c9d", "https://vgmdb.net/album/81664"]
