[4998a92cb7a1ed85fcc0a1ef9adc2420]
catalognumber = "HMCH-1046"
date = "2012-02-22"
album = "Shiny tale / Mix Speaker's,Inc. [Type-B]"
tracks = [
    [1, "Shiny tale", "Mix Speaker’s,Inc.", 0],
    [2, "Pirates of Emerald", "Mix Speaker’s,Inc.", 0],
]
links = ["https://beta.musicbrainz.org/release/59a48c2d-cbed-4841-8234-d4909e4bfaf7", "https://vgmdb.net/album/93310"]

[d981dbce6cca33d88b86d9f67675e3f7]
catalognumber = "HMCH-1045"
date = "2012-02-22"
album = "Shiny tale / Mix Speaker's,Inc. [初回限定盤/Type-A] Disc 1 (CD)"
tracks = [
    [1, "Shiny tale", "Mix Speaker’s,Inc.", 0],
    [2, "Pirates of Emerald", "Mix Speaker’s,Inc.", 0],
]
links = ["https://beta.musicbrainz.org/release/e3df8166-a694-40b9-8c66-fcac6f187a6b", "https://vgmdb.net/album/93311"]

[7041015fc735fb60e043038109bb1885]
catalognumber = "HMCH-1045"
date = "2012-02-22"
album = "Shiny tale / Mix Speaker's,Inc. [初回限定盤/Type-A] Disc 2 (DVD)"
tracks = [
    [1, "Shiny tale (PV)", "Mix Speaker’s,Inc.", 0],
]
links = ["https://beta.musicbrainz.org/release/e3df8166-a694-40b9-8c66-fcac6f187a6b", "https://vgmdb.net/album/93311"]

[e2b9affb4a2b3ab915d5a8803e41f6ba]
catalognumber = "HMCH-1047"
date = "2012-02-22"
album = "Shiny tale / Mix Speaker's,Inc. [初回限定盤/Type-C]"
tracks = [
    [1, "Shiny tale", "Mix Speaker’s,Inc.", 0],
    [2, "Capsule", "Mix Speaker’s,Inc.", 0],
    [3, "Shiny tale –TV Edit–", "Mix Speaker’s,Inc.", 0],
    [4, "Shiny tale –Instrumental–", "Mix Speaker’s,Inc.", 0],
    [5, "Capsule –Instrumental–", "Mix Speaker’s,Inc.", 0],
]
links = ["https://beta.musicbrainz.org/release/043f364c-c35a-4990-a5db-8f4c858118c3", "https://vgmdb.net/album/31324"]

[0c3b1560b50a9ece6d0c2668cdf08131]
catalognumber = "HMCH-1052"
date = "2012-02-22"
album = "おひさま/イエーイ!! / 雨先案内人"
tracks = [
    [1, "おひさま", "雨先案内人", 0],
    [2, "イエーイ!!", "雨先案内人", 0],
    [3, "おひさま [Instrumental]", "雨先案内人", 0],
]
links = ["https://beta.musicbrainz.org/release/f11b689b-319f-424b-8b63-d04968c49288", "https://vgmdb.net/album/31325"]

[5e3f844963139dd781f3b39cc3e54525]
catalognumber = "HMCH-1058"
date = "2012-05-23"
album = "「男子高校生の日常」 オリジナル サウンド トラック"
tracks = [
    [1, "Shiny tale -TV Edit-", "Mix Speaker’s,Inc.", 0],
    [2, "ウワォッ!男子高校生の日常のうた", "竹内浩明", 0],
    [3, "男子高校生とブレイク", "Audio Highs", 0],
    [4, "男子高校生とヒマつぶし", "Audio Highs", 0],
    [5, "男子高校生と友達の部屋", "Audio Highs", 0],
    [6, "男子高校生と愉快な仲間", "Audio Highs", 0],
    [7, "男子高校生とチェイス", "Audio Highs", 0],
    [8, "男子高校生とゴッコ遊び", "Audio Highs", 0],
    [9, "男子高校生と一触即発", "Audio Highs", 0],
    [10, "男子高校生とそれからそれから", "Audio Highs", 0],
    [11, "嗚呼、僕たちは悲しき男子高校生", "竹内浩明", 0],
    [12, "男子高校生と何してるの?", "Audio Highs", 0],
    [13, "男子高校生とボケ突っ込み", "Audio Highs", 0],
    [14, "男子高校生と暴走", "Audio Highs", 0],
    [15, "男子高校生とサスペンス", "Audio Highs", 0],
    [16, "男子高校生と衝撃の結末", "Audio Highs", 0],
    [17, "男子高校生と男子高校生", "Audio Highs", 0],
    [18, "男子高校生と文学少女", "Audio Highs", 0],
    [19, "男子高校生と帰り道", "Audio Highs", 0],
    [20, "男子高校生と次いってみよう", "Audio Highs", 0],
    [21, "THE・文学少女", "ENA", 0],
    [22, "男子高校生となにげない日々", "Audio Highs", 0],
    [23, "男子高校生と不穏な放課後", "Audio Highs", 0],
    [24, "男子高校生と恋", "Audio Highs", 0],
    [25, "男子高校生と恥ずかしいオチ", "Audio Highs", 0],
    [26, "男子高校生と青春", "Audio Highs", 0],
    [27, "男子高校生と夏休み", "Audio Highs", 0],
    [28, "男子高校生と闘争", "Audio Highs", 0],
    [29, "男子高校生とだらだら", "Audio Highs", 0],
    [30, "男子高校生とアクション", "Audio Highs", 0],
    [31, "男子高校生とバトル", "Audio Highs", 0],
    [32, "男子高校生とりんごちゃん", "Audio Highs", 0],
    [33, "男子高校生とバイオレンス", "Audio Highs", 0],
    [34, "男子高校生と対抗心", "Audio Highs", 0],
    [35, "男子高校生とがっかり", "Audio Highs", 0],
    [36, "男子高校生とショートスケッチ", "Audio Highs", 0],
    [37, "男子高校生と文化祭", "Audio Highs", 0],
    [38, "男子高校生とホラー", "Audio Highs", 0],
    [39, "男子高校生とガールズバンド", "Audio Highs", 0],
    [40, "男子高校生と遅刻 遅刻?", "Audio Highs", 0],
    [41, "男子高校生と友情", "Audio Highs", 0],
    [42, "男子高校生と少年時代", "Audio Highs", 0],
    [43, "女子高生は異常 Fu♪", "Audio Highs", 0],
    [44, "おひさま -TV Edit-", "雨先案内人", 0],
]
links = ["https://beta.musicbrainz.org/release/65ffb361-62a1-48f8-af0c-fc2c8f0c1412", "https://vgmdb.net/album/32248"]
