[5d095d49809e28c89990a25bf61bbf53]
catalognumber = "EYCA-11968/B"
date = "2018-07-25"
album = "最悪な日でもあなたが好き。 / 芹澤優 Disc 1 (CD) [EYCA-11968]"
tracks = [
    [1, "最悪な日でもあなたが好き。", "芹澤優", 0],
    [2, "神×太陽×サマーパーティ", "芹澤優", 0],
    [3, "最悪な日でもあなたが好き。 (instrumental)", "芹澤優", 0],
    [4, "神×太陽×サマーパーティ (instrumental)", "芹澤優", 0],
]
links = ["https://beta.musicbrainz.org/release/a79e9f6b-f6ef-4721-b3b8-690f75178c53", "https://vgmdb.net/album/77299"]

[742110250cd13609967f3a0f01d94625]
catalognumber = "EYCA-11968/B"
date = "2018-07-25"
album = "最悪な日でもあなたが好き。 / 芹澤優 Disc 2 (Blu-ray) [EYCA-11968B]"
tracks = [
    [1, "最悪な日でもあなたが好き。 -Music Video-", "芹澤優", 0],
    [2, "最悪な日でもあなたが好き。 -Off Shot Movie-", "芹澤優", 0],
]
links = ["https://beta.musicbrainz.org/release/a79e9f6b-f6ef-4721-b3b8-690f75178c53", "https://vgmdb.net/album/77299"]

[9c7058ad20bc9389499097f3a6f95fac]
catalognumber = "EYCA-11969"
date = "2018-07-25"
album = "最悪な日でもあなたが好き。 / 芹澤優"
tracks = [
    [1, "最悪な日でもあなたが好き。", "芹澤優", 0],
    [2, "神×太陽×サマーパーティ", "芹澤優", 0],
    [3, "最悪な日でもあなたが好き。 (instrumental)", "芹澤優", 0],
    [4, "神×太陽×サマーパーティ (instrumental)", "芹澤優", 0],
]
links = ["https://beta.musicbrainz.org/release/f2de85ac-d092-428d-9816-cf645d7b79a6", "https://vgmdb.net/album/77298"]

[34f64a0485905d84661bc8d9417744a2]
catalognumber = "EYCA-11966/B"
date = "2018-08-29"
album = "DeCIDE / SUMMONERS 2+ Disc 1 (CD) [EYCA-11966]"
tracks = [
    [1, "DeCIDE", "SUMMONERS 2+", 0],
    [2, "イルメナイト", "SUMMONERS 2+", 0],
    [3, "DeCIDE (Instrumental)", "SUMMONERS 2+", 0],
    [4, "イルメナイト (Instrumental)", "SUMMONERS 2+", 0],
]
links = ["https://beta.musicbrainz.org/release/8f6d79d9-ec7b-4144-882f-58274c0eb9a4", "https://vgmdb.net/album/77820"]

[5f132ffffa7d4c63176698e5a4f5c0fd]
catalognumber = "EYCA-11966/B"
date = "2018-08-29"
album = "DeCIDE / SUMMONERS 2+ Disc 2 (Blu-ray) [EYCA-11966B]"
tracks = [
    [1, "DeCIDE (Music Video)", "", 0],
]
links = ["https://vgmdb.net/album/77820"]

[eff9d9f3fbd9293808ca9bc9dd87ac02]
catalognumber = "EYCA-11967"
date = "2018-08-29"
album = "DeCIDE / SUMMONERS 2+"
tracks = [
    [1, "DeCIDE", "SUMMONERS 2+", 0],
    [2, "イルメナイト", "SUMMONERS 2+", 0],
    [3, "DeCIDE (Instrumental)", "SUMMONERS 2+", 0],
    [4, "イルメナイト (Instrumental)", "SUMMONERS 2+", 0],
]
links = ["https://beta.musicbrainz.org/release/8f6d79d9-ec7b-4144-882f-58274c0eb9a4", "https://vgmdb.net/album/77819"]

[835670269d38e4a26e99d555b9f3c75c]
catalognumber = "N/A"
date = "2019-01-25"
album = "TVアニメ 「異世界魔王と召喚少女の奴隷魔術」Vol.3 とらのあな限定版 録り下ろしドラマCD"
tracks = [
    [1, "(no title available)", "", 0],
    [2, "(no title available)", "", 0],
]
links = ["https://vgmdb.net/album/78849"]

[15de03fb2c7f9e8b9b9e93c03572959d]
catalognumber = "KDS-0424"
date = "2019-04-30"
album = "異世界魔王と召喚少女の奴隷魔術 第12巻ドラマCD"
tracks = [
    [1, "異世界魔王とえっちな本", "", 0],
    [2, "召喚少女の秘密のおしゃべり", "", 0],
    [3, "ボクとわたしの交換魔術", "", 0],
]
links = ["https://vgmdb.net/album/85921"]

[f91fd2233049834fdfd73eb5bb67fc77]
catalognumber = "EYXA-13252B"
date = "2021-02-24"
album = "異世界魔王と召喚少女の奴隷魔術 魔王プレイボックス BONUS CD レムシェラ おやすみCD"
tracks = [
    [1, "レムシェラ おやすみCD", "", 0],
]
links = ["https://vgmdb.net/album/107027"]

[23a719b76f6bed9791e0249a23de5f31]
catalognumber = "ANTCD-A0000004050"
date = "2021-04-29"
album = "頑張っている君だから / シェラ&レム&ルマキーナ&ホルン(CV.芹澤優,和氣あず未,伊藤美来,内村史子)"
tracks = [
    [1, "頑張っている君だから", "シェラ&レム&ルマキーナ&ホルン(CV.芹澤優,和氣あず未,伊藤美来,内村史子)", 0],
]
links = ["https://beta.musicbrainz.org/release/a6a5dc77-e17f-4616-b0a0-8d69842e79e5", "https://vgmdb.net/album/111215"]

[b36caacd9252eef06e0901326c5e0ac1]
catalognumber = "EYCA-13371/B"
date = "2021-05-19"
album = "EVERYBODY! EVERYBODY!/YOU YOU YOU / 芹澤優 with DJ KOO & MOTSU Vocal"
tracks = [
    [1, "EVERYBODY! EVERYBODY!", "芹澤 優 with DJ KOO & MOTSU", 0],
    [2, "YOU YOU YOU", "芹澤 優 with DJ KOO & MOTSU", 0],
    [3, "EVERYBODY! EVERYBODY! (Instrumental)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [4, "YOU YOU YOU (Instrumental)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [5, "EVERYBODY! EVERYBODY! (w/o 芹澤 優)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [6, "YOU YOU YOU (w/o 芹澤 優)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [7, "EVERYBODY! EVERYBODY! (w/o DJ KOO & MOTSU)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [8, "YOU YOU YOU (w/o DJ KOO & MOTSU)", "芹澤 優 with DJ KOO & MOTSU", 0],
]
links = ["https://beta.musicbrainz.org/release/c31cee3a-2eda-432d-8500-51d709d19ea4", "https://vgmdb.net/album/109480"]

[615579245cfe612f17ed471a7f8286a9]
catalognumber = "EYCA-13371/B"
date = "2021-05-19"
album = "EVERYBODY! EVERYBODY!/YOU YOU YOU / 芹澤優 with DJ KOO & MOTSU Vocal, Video"
tracks = [
    [1, "EVERYBODY! EVERYBODY! -Music Video-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [2, "YOU YOU YOU -Music Video-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [3, "EVERYBODY! EVERYBODY! -Off Shot Movie-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [4, "YOU YOU YOU -Off Shot Movie-", "芹澤 優 with DJ KOO & MOTSU", 0],
]
links = ["https://beta.musicbrainz.org/release/c31cee3a-2eda-432d-8500-51d709d19ea4", "https://vgmdb.net/album/109480"]

[ee1b6a2ee3b492393693fdf279b32dfe]
catalognumber = "EYCA-13372/B"
date = "2021-05-19"
album = "EVERYBODY! EVERYBODY!/YOU YOU YOU / 芹澤優 with DJ KOO & MOTSU Vocal"
tracks = [
    [1, "EVERYBODY! EVERYBODY!", "芹澤 優 with DJ KOO & MOTSU", 0],
    [2, "YOU YOU YOU", "芹澤 優 with DJ KOO & MOTSU", 0],
    [3, "EVERYBODY! EVERYBODY! (Instrumental)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [4, "YOU YOU YOU (Instrumental)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [5, "EVERYBODY! EVERYBODY! (w/o 芹澤 優)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [6, "YOU YOU YOU (w/o 芹澤 優)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [7, "EVERYBODY! EVERYBODY! (w/o DJ KOO & MOTSU)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [8, "YOU YOU YOU (w/o DJ KOO & MOTSU)", "芹澤 優 with DJ KOO & MOTSU", 0],
]
links = ["https://beta.musicbrainz.org/release/dcec4863-b78d-4f2a-a5bc-7283272dd4c9", "https://vgmdb.net/album/109479"]

[b4856066804ce31ed2d798faaa73c580]
catalognumber = "EYCA-13372/B"
date = "2021-05-19"
album = "EVERYBODY! EVERYBODY!/YOU YOU YOU / 芹澤優 with DJ KOO & MOTSU Vocal, Video"
tracks = [
    [1, "EVERYBODY! EVERYBODY! -Music Video-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [2, "YOU YOU YOU -Music Video-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [3, "EVERYBODY! EVERYBODY! -Off Shot Movie-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [4, "YOU YOU YOU -Off Shot Movie-", "芹澤 優 with DJ KOO & MOTSU", 0],
]
links = ["https://beta.musicbrainz.org/release/dcec4863-b78d-4f2a-a5bc-7283272dd4c9", "https://vgmdb.net/album/109479"]

[bb743e6881c6235c6e4d79ca402b0ec5]
catalognumber = "EYCA-13373"
date = "2021-05-19"
album = "EVERYBODY! EVERYBODY!/YOU YOU YOU / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "EVERYBODY! EVERYBODY!", "芹澤 優 with DJ KOO & MOTSU", 0],
    [2, "YOU YOU YOU", "芹澤 優 with DJ KOO & MOTSU", 0],
    [3, "EVERYBODY! EVERYBODY! (Instrumental)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [4, "YOU YOU YOU (Instrumental)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [5, "EVERYBODY! EVERYBODY! (w/o 芹澤 優)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [6, "YOU YOU YOU (w/o 芹澤 優)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [7, "EVERYBODY! EVERYBODY! (w/o DJ KOO & MOTSU)", "芹澤 優 with DJ KOO & MOTSU", 0],
    [8, "YOU YOU YOU (w/o DJ KOO & MOTSU)", "芹澤 優 with DJ KOO & MOTSU", 0],
]
links = ["https://beta.musicbrainz.org/release/0d7c2612-0ec8-41a7-a68c-e0dbb3f2a70e", "https://vgmdb.net/album/109478"]

[cfa622fd71610fc07f361c944cc8d90f]
catalognumber = "ANTCD-A0000004221"
date = "2021-05-21"
album = "EVERYBODY! EVERYBODY! (Aniclub EDIT) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "EVERYBODY! EVERYBODY! (Aniclub EDIT)", "", 0],
    [2, "EVERYBODY! EVERYBODY! (Aniclub EDIT) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/111700"]

[4e887fbeba7c24595aaf39dd9aac5d2a]
catalognumber = "ANTCD-A0000004224"
date = "2021-05-21"
album = "YOU YOU YOU (Aniclub EDIT) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "YOU YOU YOU (Aniclub EDIT)", "", 0],
    [2, "YOU YOU YOU (Aniclub EDIT) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/111701"]

[7ebaeccbf74171aab4edd827c5b1b38e]
catalognumber = "ANTCD-A0000004271"
date = "2021-05-28"
album = "YOU YOU YOU (Hachiroku Eurobeat REMIX) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "YOU YOU YOU (Hachiroku Eurobeat REMIX)", "", 0],
    [2, "YOU YOU YOU (Hachiroku Eurobeat REMIX) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/111938"]

[202b8e4631cb03a7edabbef48b74d2f8]
catalognumber = "ANTCD-A0000004268"
date = "2021-05-28"
album = "EVERYBODY! EVERYBODY! (90'S Techno REMIX) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "EVERYBODY! EVERYBODY! (90'S Techno REMIX)", "", 0],
    [2, "EVERYBODY! EVERYBODY! (90'S Techno REMIX) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/111939"]

[c0f5f134047a9b201b24324bb666bc1e]
catalognumber = "ANTCD-A0000004331"
date = "2021-06-04"
album = "EVERYBODY! EVERYBODY! (Planet U REMIX) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "EVERYBODY! EVERYBODY! (Planet U REMIX)", "", 0],
    [2, "EVERYBODY! EVERYBODY! (Planet U REMIX) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/112042"]

[955a9e67dbd11838d43ecf50129de1c2]
catalognumber = "ANTCD-A0000004334"
date = "2021-06-04"
album = "YOU YOU YOU (Happy Eurobeat REMIX) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "YOU YOU YOU (Happy Eurobeat REMIX)", "", 0],
    [2, "YOU YOU YOU (Happy Eurobeat REMIX) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/112043"]

[81779c12ba7c63ba4402b1fd5bcc4c1d]
catalognumber = "ANTCD-A0000004337"
date = "2021-06-11"
album = "EVERYBODY! EVERYBODY! (Tropical Disco REMIX) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "EVERYBODY! EVERYBODY! (Tropical Disco REMIX)", "", 0],
    [2, "EVERYBODY! EVERYBODY! (Tropical Disco REMIX) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/112196"]

[7c35016e331801900fa2356e574f8f25]
catalognumber = "ANTCD-A0000004340"
date = "2021-06-11"
album = "YOU YOU YOU (Kawaii Future Bass REMIX) / 芹澤優 with DJ KOO & MOTSU"
tracks = [
    [1, "YOU YOU YOU (Kawaii Future Bass REMIX)", "", 0],
    [2, "YOU YOU YOU (Kawaii Future Bass REMIX) Instrumental", "", 0],
]
links = ["https://vgmdb.net/album/112197"]

[9ceb183cb75efe0ff67e9908294b2bc7]
catalognumber = "EYXA-13368B"
date = "2021-06-25"
album = "異世界魔王と召喚少女の奴隷魔術Ω 1 Bonus Disc"
tracks = [
    [1, "Dangerous Escape", "加藤裕介", 0],
    [2, "Chaotic Haze", "加藤裕介", 0],
    [3, "絶望の狂騒", "加藤裕介", 0],
    [4, "Damnation", "加藤裕介", 0],
    [5, "ある日の風景", "加藤裕介", 0],
    [6, "楽観主義", "加藤裕介", 0],
    [7, "出発の時", "加藤裕介", 0],
    [8, "欲望の首輪", "山下洋介", 0],
    [9, "小物感", "加藤裕介", 0],
    [10, "疑念の影", "加藤裕介", 0],
    [11, "Fervent Strike", "加藤裕介", 0],
    [12, "Demon Lord", "加藤裕介", 0],
    [13, "悦楽の極み", "加藤裕介", 0],
    [14, "拗ねてるけど?", "山下洋介", 0],
    [15, "狼狽する者", "加藤裕介", 0],
    [16, "Glorious Sacred Holy Divine Light", "加藤裕介", 0],
    [17, "枯れた都", "山下洋介", 0],
    [18, "Over Drive Fanfare", "山下洋介", 0],
    [19, "深淵の陰謀", "加藤裕介", 0],
    [20, "Diablo", "加藤裕介", 0],
    [21, "立ち上がる決意", "加藤裕介", 0],
    [22, "予告", "加藤裕介", 0],
]
links = ["https://beta.musicbrainz.org/release/faaff392-9964-42b0-960a-5b2cf46e05d5", "https://vgmdb.net/album/110438"]

[aae8b7e43a474e11e7630e1cec769ef5]
catalognumber = "EYXA-13369B"
date = "2021-07-30"
album = "異世界魔王と召喚少女の奴隷魔術Ω 2 Bonus Disc"
tracks = [
    [1, "Overwhelming Invasion", "加藤裕介", 0],
    [2, "危・スタッカート", "山下洋介", 0],
    [3, "慌てふためく者", "加藤裕介", 0],
    [4, "軟弱な者", "山下洋介", 0],
    [5, "邪素", "山下洋介", 0],
    [6, "魔力咆哮", "山下洋介", 0],
    [7, "頑張っている君だから", "シェラ&レム&ルマキーナ&ホルン(CV.芹澤優,和氣あず未,伊藤美来,内村史子)", 0],
    [8, "進め！レッツゴー！", "加藤裕介", 0],
    [9, "Kindness of Heart", "加藤裕介", 0],
    [10, "Resurrection of Darkness", "加藤裕介", 0],
    [11, "Serious Problem", "加藤裕介", 0],
    [12, "レベルアップマーチ", "加藤裕介", 0],
    [13, "気掛かりな襲撃", "加藤裕介", 0],
    [14, "召喚", "山下洋介", 0],
    [15, "崇高なる騎士", "山下洋介", 0],
    [16, "Burning Fury", "加藤裕介", 0],
    [17, "溶解魔道", "山下洋介", 0],
    [18, "戸惑いの中で", "加藤裕介", 0],
    [19, "Power of the Abyss", "加藤裕介", 0],
    [20, "Resolve", "加藤裕介", 0],
    [21, "D的純情", "山下洋介", 0],
    [22, "夢語り", "加藤裕介", 0],
]
links = ["https://beta.musicbrainz.org/release/b61993f4-df8b-4c1b-9d14-c58edd133890", "https://vgmdb.net/album/110581"]

[f01cdd04a45fb81749b3f8ea0850cd63]
catalognumber = "EYXA-13370B"
date = "2021-08-27"
album = "異世界魔王と召喚少女の奴隷魔術Ω 3 Bonus Disc"
tracks = [
    [1, "Tense Confrontation", "加藤裕介", 0],
    [2, "思い出の痛み", "加藤裕介", 0],
    [3, "Horizon", "加藤裕介", 0],
    [4, "Rite of Ruin", "加藤裕介", 0],
    [5, "肌色リズム", "山下洋介", 0],
    [6, "召喚の義", "山下洋介", 0],
    [7, "Conflict", "加藤裕介", 0],
    [8, "Erlkonig Barock", "山下洋介", 0],
    [9, "Fateful Showdown", "加藤裕介", 0],
    [10, "衝撃の震え", "加藤裕介", 0],
    [11, "大将軍バナクネス", "山下洋介", 0],
    [12, "危機来襲", "山下洋介", 0],
    [13, "希望の前奏", "山下洋介", 0],
    [14, "Compassion of Lord", "加藤裕介", 0],
    [15, "幼き温もりと...", "山下洋介", 0],
    [16, "Take a break", "加藤裕介", 0],
    [17, "癒される時", "加藤裕介", 0],
    [18, "Long time no see", "山下洋介", 0],
    [19, "ユキノトビラ", "山下洋介", 0],
    [20, "幻惑の笛", "加藤裕介", 0],
    [21, "ビスケットの歌", "加藤裕介", 0],
    [22, "Fateful Recall", "加藤裕介", 0],
]
links = ["https://beta.musicbrainz.org/release/c4c4651d-630a-45d2-88d6-d9ac5c589fb2", "https://vgmdb.net/album/110582"]

[1a741e5d2c2add5dd4104e4cf59a3793]
catalognumber = "EYBA-13716"
date = "2022-04-20"
album = "Yu Serizawa 2nd Live Tour 2021 好きな人がいるだけで。"
tracks = [
    [1, "Voice for YOU!", "", 0],
    [2, "ハイハイハイハハイテンション", "", 0],
    [3, "神×太陽×サマーパーティ", "", 0],
    [4, "ヒロインズドラマ", "", 0],
    [5, "PRINCESS POLICY", "", 0],
    [6, "Out Of Control!", "", 0],
    [7, "朗読1", "", 0],
    [8, "imaginary", "", 0],
    [9, "片思いExpansion", "", 0],
    [10, "告白", "", 0],
    [11, "朗読2", "", 0],
    [12, "今夜も月がきれい", "", 0],
    [13, "EVERYBODY! EVERYBODY!", "", 0],
    [14, "YOU YOU YOU", "", 0],
    [15, "Special Kiss", "", 0],
    [16, "COMETIC SILHOUETTE", "", 0],
    [17, "Revelation", "", 0],
    [18, "Merry Birthday!", "", 0],
    [19, "ぷりっとぱ～ふぇくと", "", 0],
    [20, "最悪な日でもあなたが好き。", "", 0],
    [21, "Plastic / Jewelry Tune [特典映像1昼公演映像]", "", 0],
    [22, "TRIal HEART ～恋の違反チケット～ [特典映像1昼公演映像]", "", 0],
    [23, "デビきゅー [特典映像1昼公演映像]", "", 0],
    [24, "パラレルスターズ [特典映像1昼公演映像]", "", 0],
    [25, "キラッとスタート [特典映像1昼公演映像]", "", 0],
    [26, "Yu Serizawa 2nd Live Tour 2021 好きな人がいるだけで。-Off Shot Movie- [特典映像2オフショット映像]", "", 0],
]
links = ["https://vgmdb.net/album/118031"]

[59a50044a1b4f5f823d4c5ba8d2b338d]
catalognumber = "EYXA-13717"
date = "2022-04-20"
album = "Yu Serizawa 2nd Live Tour 2021 好きな人がいるだけで。"
tracks = [
    [1, "Voice for YOU!", "", 0],
    [2, "ハイハイハイハハイテンション", "", 0],
    [3, "神×太陽×サマーパーティ", "", 0],
    [4, "ヒロインズドラマ", "", 0],
    [5, "PRINCESS POLICY", "", 0],
    [6, "Out Of Control!", "", 0],
    [7, "朗読1", "", 0],
    [8, "imaginary", "", 0],
    [9, "片思いExpansion", "", 0],
    [10, "告白", "", 0],
    [11, "朗読2", "", 0],
    [12, "今夜も月がきれい", "", 0],
    [13, "EVERYBODY! EVERYBODY!", "", 0],
    [14, "YOU YOU YOU", "", 0],
    [15, "Special Kiss", "", 0],
    [16, "COMETIC SILHOUETTE", "", 0],
    [17, "Revelation", "", 0],
    [18, "Merry Birthday!", "", 0],
    [19, "ぷりっとぱ～ふぇくと", "", 0],
    [20, "最悪な日でもあなたが好き。", "", 0],
    [21, "Plastic / Jewelry Tune [特典映像1昼公演映像]", "", 0],
    [22, "TRIal HEART ～恋の違反チケット～ [特典映像1昼公演映像]", "", 0],
    [23, "デビきゅー [特典映像1昼公演映像]", "", 0],
    [24, "パラレルスターズ [特典映像1昼公演映像]", "", 0],
    [25, "キラッとスタート [特典映像1昼公演映像]", "", 0],
    [26, "Yu Serizawa 2nd Live Tour 2021 好きな人がいるだけで。-Off Shot Movie- [特典映像2オフショット映像]", "", 0],
]
links = ["https://vgmdb.net/album/118030"]

[ac2aa34cbaa1c324e23719fa3cd4c827]
catalognumber = "EYCA-13827"
date = "2022-10-05"
album = "YOUr No.1 / 芹澤優"
tracks = [
    [1, "シンデレラストーリー", "芹澤 優", 0],
    [2, "Voice for YOU!", "芹澤優", 0],
    [3, "アンビバビバラビュー", "芹澤 優", 0],
    [4, "デビきゅー", "芹澤優", 0],
    [5, "EVERYBODY! EVERYBODY!", "芹澤 優 with DJ KOO & MOTSU", 0],
    [6, "BLUE ROSE", "芹澤 優", 0],
    [7, "Close to you", "芹澤 優", 0],
    [8, "PRINCESS POLICY", "芹澤 優", 0],
    [9, "YOU YOU YOU", "芹澤 優 with DJ KOO & MOTSU", 0],
    [10, "Break My Tears", "芹澤 優", 0],
    [11, "最悪な日でもあなたが好き。", "芹澤優", 0],
]
links = ["https://beta.musicbrainz.org/release/c8bab22b-32b2-401d-a744-8e9cefc04aef", "https://vgmdb.net/album/121494"]

[b4ae5436048bfb64a10a8e933f0145ea]
catalognumber = "EYCA-13826/B"
date = "2022-10-05"
album = "YOUr No.1 / 芹澤優 Vocal"
tracks = [
    [1, "シンデレラストーリー", "芹澤 優", 0],
    [2, "Voice for YOU!", "芹澤優", 0],
    [3, "アンビバビバラビュー", "芹澤 優", 0],
    [4, "デビきゅー", "芹澤優", 0],
    [5, "EVERYBODY! EVERYBODY!", "芹澤 優 with DJ KOO & MOTSU", 0],
    [6, "BLUE ROSE", "芹澤 優", 0],
    [7, "Close to you", "芹澤 優", 0],
    [8, "PRINCESS POLICY", "芹澤 優", 0],
    [9, "YOU YOU YOU", "芹澤 優 with DJ KOO & MOTSU", 0],
    [10, "Break My Tears", "芹澤 優", 0],
    [11, "最悪な日でもあなたが好き。", "芹澤優", 0],
]
links = ["https://beta.musicbrainz.org/release/db9033ce-9ee3-4ecc-bf4c-68c693185814", "https://vgmdb.net/album/121495"]

[a5acb9a98e5911ebe11db1d530c405c9]
catalognumber = "EYCA-13826/B"
date = "2022-10-05"
album = "YOUr No.1 / 芹澤優 Vocal, Video"
tracks = [
    [1, "シンデレラストーリー -Music Video-", "芹澤優", 0],
    [2, "Voice for YOU! -Music Video-", "芹澤優", 0],
    [3, "PRINCESS POLICY -Music Video-", "芹澤優", 0],
    [4, "最悪な日でもあなたが好き。 -Music Video-", "芹澤優", 0],
    [5, "デビきゅー -Music Video-", "芹澤優", 0],
    [6, "EVERYBODY! EVERYBODY! -Music Video-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [7, "YOU YOU YOU -Music Video-", "芹澤 優 with DJ KOO & MOTSU", 0],
    [8, "シンデレラストーリー -Off Shot Movie-", "芹澤優", 0],
    [9, "STYLEBOOK -Behind the Scene-", "芹澤優", 0],
]
links = ["https://beta.musicbrainz.org/release/db9033ce-9ee3-4ecc-bf4c-68c693185814", "https://vgmdb.net/album/121495"]
