[60f5e89275b23d5e40173dbebc7b7439]
catalognumber = "QWCE-00646"
date = "2017-07-19"
album = "異世界はスマートフォンとともに。キャラクターソングvol.1"
tracks = [
    [1, "XOXO", "エルゼ・シルエスカ(CV:内田真礼)", 1],
    [2, "バブルラブ", "リンゼ・シルエスカ(CV:福緒唯)", 1],
    [3, "純情エモーショナル (エルゼver.)", "エルゼ・シルエスカ(CV:内田真礼)", 1],
    [4, "純情エモーショナル (リンゼver.)", "リンゼ・シルエスカ(CV:福緒唯)", 1],
    [5, "XOXO -instrumental-", "エルゼ・シルエスカ(CV:内田真礼)", 1],
    [6, "バブルラブ -instrumental-", "リンゼ・シルエスカ(CV:福緒唯)", 1],
]
links = ["https://beta.musicbrainz.org/release/c6db622b-474f-496a-a7a0-6320c495b212", "https://vgmdb.net/album/69130"]

[4f3614406395bab8c79e95cff6b594e2]
catalognumber = "QWCE-00647"
date = "2017-08-18"
album = "異世界はスマートフォンとともに。キャラクターソングvol.2"
tracks = [
    [1, "抱く大志は桜のごとく", "九重八重(CV:赤﨑千夏)", 1],
    [2, "Staring only you", "ユミナ・エルネア・ベルファスト(CV:高野麻里佳)", 2],
    [3, "純情エモーショナル (八重ver.)", "九重八重(CV:赤﨑千夏)", 1],
    [4, "純情エモーショナル (ユミナver.)", "ユミナ・エルネア・ベルファスト(CV:高野麻里佳)", 1],
    [5, "抱く大志は桜のごとく -instrumental-", "九重八重(CV:赤﨑千夏)", 1],
    [6, "Staring only you -instrumental-", "ユミナ・エルネア・ベルファスト(CV:高野麻里佳)", 1],
]
links = ["https://beta.musicbrainz.org/release/e9598589-5a05-4b77-8020-26374cdead93", "https://vgmdb.net/album/69131"]

[b064efae1e822af9c77a98f22693cef3]
catalognumber = "AKOSC-00008"
date = "2017-08-23"
album = "Another World / A応P [アニメジャケット盤]"
tracks = [
    [1, "Another World", "A応P", 1],
    [2, "カミサマと金魚", "A応P", 1],
    [3, "Another World (TV Version)", "A応P", 1],
    [4, "Another World (Instrumental)", "A応P", 1],
    [5, "カミサマと金魚 (Instrumental)", "A応P", 1],
]
links = ["https://beta.musicbrainz.org/release/04c864af-6053-4ea2-a35a-a510adf6c1a1", "https://vgmdb.net/album/69129"]

[357cc945d140e816ed1582aa009c4580]
catalognumber = "AKOSC-00009"
date = "2017-08-23"
album = "Another World / A応P [アーティストジャケット盤]"
tracks = [
    [1, "Another World", "A応P", 1],
    [2, "カミサマと金魚", "A応P", 1],
    [3, "Another World (TV Version)", "A応P", 1],
    [4, "Another World (Instrumental)", "A応P", 1],
    [5, "カミサマと金魚 (Instrumental)", "A応P", 1],
]
links = ["https://beta.musicbrainz.org/release/fdf537ee-ac8f-4341-ba5f-cadf0eb68922", "https://vgmdb.net/album/69128"]

[e7d00b6a5229358064665145de853930]
catalognumber = "QWXE-20001-2"
date = "2017-09-20"
album = "異世界はスマートフォンとともに。 サントラCD#1"
tracks = [
    [1, "Afternoon", "加藤賢二", 1],
    [2, "Usual Way", "浅田靖", 1],
    [3, "Relax", "加藤賢二", 1],
    [4, "Stroll", "浅田靖", 1],
    [5, "Finale", "関根佑樹", 1],
    [6, "To Meet You", "u.z.", 1],
    [7, "God", "加藤賢二", 1],
    [8, "Another World", "加藤賢二", 1],
    [9, "Unrest", "加藤賢二", 1],
    [10, "Looming", "加藤賢二", 1],
    [11, "Versus", "加藤賢二", 1],
    [12, "Traveler", "富沢泰", 1],
    [13, "Beginning", "加藤賢二", 1],
    [14, "The Fight Is Mine", "浅田靖", 1],
    [15, "Must Be Carefully", "浅田靖", 1],
    [16, "To Feel One's Fate", "加藤賢二", 1],
    [17, "Glory", "加藤賢二", 1],
    [18, "Guild", "柳川和樹", 1],
    [19, "Spells I", "ラムシーニ", 1],
    [20, "Spells II", "ラムシーニ", 1],
    [21, "Spells III", "ラムシーニ", 1],
    [22, "Spells IV", "ラムシーニ", 1],
    [23, "Spells V", "ラムシーニ", 1],
    [24, "Spells VI", "ラムシーニ", 1],
    [25, "Nulli-Spells", "ラムシーニ", 1],
    [26, "Oops", "加藤賢二", 1],
    [27, "One Day", "浅田靖", 1],
    [28, "Same As Usual", "関根佑樹", 1],
]
links = ["https://beta.musicbrainz.org/release/8d353640-f9c3-4804-993a-469101ccaed3", "https://vgmdb.net/album/69632"]

[be9303b1073eda7c0df9d7bee3d43306]
catalognumber = "ETCS-00120"
date = "2017-09-20"
album = "純情エモーショナル / エルゼ(CV:内田真礼)、リンゼ(CV:福緒唯)、八重(CV:赤﨑千夏)、ユミナ(CV:高野麻里佳)、スゥシィ(CV:山下七海)、リーン(CV:上坂すみれ)"
tracks = [
    [1, "純情エモーショナル", "エルゼ・シルエスカ(CV:内田真礼)、リンゼ・シルエスカ(CV:福緒唯)、九重八重(CV:赤﨑千夏)、ユミナ・エルネア・ベルファスト(CV:高野麻里佳)、スゥシィ・エルネア・オルトリンデ(CV:山下七海)、リーン(CV:上坂すみれ)", 2],
]
links = ["https://beta.musicbrainz.org/release/1b5fd6ce-cd64-4639-92e3-f6bcc08f0282", "https://vgmdb.net/album/69633"]

[a3da06ba273a3803f2084bd919be4048]
catalognumber = "QWCE-00648"
date = "2017-09-20"
album = "異世界はスマートフォンとともに。キャラクターソングvol.3"
tracks = [
    [1, "ワックワクがとまらない!", "スゥシィ・エルネア・オルトリンデ(CV:山下七海)", 1],
    [2, "刮目!魔法少女まじかる☆リーン", "リーン(CV:上坂すみれ)", 1],
    [3, "純情エモーショナル (スゥシィver.)", "スゥシィ・エルネア・オルトリンデ(CV:山下七海)", 1],
    [4, "純情エモーショナル (リーンver.)", "リーン(CV:上坂すみれ)", 1],
    [5, "ワックワクがとまらない! -instrumental-", "スゥシィ・エルネア・オルトリンデ(CV:山下七海)", 1],
    [6, "刮目!魔法少女まじかる☆リーン -instrumental-", "リーン(CV:上坂すみれ)", 1],
]
links = ["https://beta.musicbrainz.org/release/b7b21183-475d-4341-b986-e6bad67defbb", "https://vgmdb.net/album/69132"]

[d11f8159e966ebe6cb95781efa120c78]
catalognumber = "QWXE-20002-2"
date = "2017-10-04"
album = "異世界はスマートフォンとともに。 サントラCD#2"
tracks = [
    [1, "Beginning (Wa Ver.)", "加藤賢二", 1],
    [2, "The Fight Is Mine (Wa Ver.)", "加藤賢二", 1],
    [3, "Must Be Carefully (Wa Ver.)", "浅田靖", 1],
    [4, "To Feel One's Fate (Wa Ver.)", "加藤賢二", 1],
    [5, "The Kingdom", "富沢泰", 0],
    [6, "Like a Warm Day", "加藤賢二", 1],
    [7, "Remains", "加藤賢二", 0],
    [8, "Blue Rain", "加藤賢二", 0],
    [9, "With me", "加藤賢二", 0],
    [10, "See You Next Time", "加藤賢二", 0],
    [11, "Oriental", "富沢泰", 0],
    [12, "Library", "加藤賢二", 0],
    [13, "Wonder", "浅田靖", 0],
    [14, "Mascot", "浅田靖", 0],
    [15, "Eccentric", "富沢泰", 0],
    [16, "Is This Sweet?", "富沢泰", 0],
    [17, "Is That Romance?", "加藤賢二", 1],
    [18, "Title", "加藤賢二", 0],
    [19, "Lively town", "u.z.", 0],
    [20, "Hanging Gardens", "u.z.", 1],
    [21, "Babylon", "浅田靖", 0],
]
links = ["https://beta.musicbrainz.org/release/2ef4e283-e639-4984-aa86-5850ea8bd031", "https://vgmdb.net/album/69634"]

[f963e6aa8071d0f390bfa54e1164b504]
catalognumber = "N/A"
date = "2019-03-22"
album = "異世界はスマートフォンとともに。第16巻特装版付属ドラマCD"
tracks = [
    [1, "[untitled]", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/0eed77bf-d3ca-4863-9fe3-a8172cd8de5f", "https://vgmdb.net/album/82815"]

[da036a1bfaabeae6e605112808d4f4b8]
catalognumber = "N/A"
date = "2019-12-21"
album = "異世界はスマートフォンとともに。第19巻特装版付属ドラマCD"
tracks = [
    [1, "[untitled]", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/7f9b2d26-7b85-4a8e-b54e-64d2ae6a824a", "https://vgmdb.net/album/91118"]

[a3b34900e5484b22ea8f59f73d7843b2]
catalognumber = "AKOAC-00008"
date = "2021-03-31"
album = "A応P the BEST ～From A～ / A応P Vocal"
tracks = [
    [1, "６つ子の魂ナユタまで", "A応P", 0],
    [2, "君氏危うくも近うよれ", "A応P", 0],
    [3, "それゆけ！ 恋ゴコロ", "A応P", 0],
    [4, "恋に咲く謎、はらはらと", "A応P", 0],
    [5, "まぼろしウインク", "A応P", 0],
    [6, "風吹けば月夜の果てに", "A応P", 0],
    [7, "FREEDOMでムダに無敵!!", "A応P", 0],
    [8, "nice to NEET you！", "A応P", 0],
    [9, "フライングベイビーズ", "A応P", 0],
    [10, "Another World", "A応P", 1],
    [11, "愛がなくちゃ戦えない", "A応P", 0],
]
links = ["https://beta.musicbrainz.org/release/97ae8349-2533-4cd6-bd8c-3093d3d85dcf", "https://vgmdb.net/album/109263"]

[7795e9a34c90b317b7c0b897c15e700a]
catalognumber = "AKOAC-00008"
date = "2021-03-31"
album = "A応P the BEST ～From A～ / A応P Vocal, Live Event, Video"
tracks = [
    [1, "OVERTURE to LOOK at ME!!!", "", 0],
    [2, "イントロデュースA応P", "", 0],
    [3, "二次元ポケット", "", 0],
    [4, "Another World", "", 1],
    [5, "呼べよ嵐", "", 0],
    [6, "COSMIC MAGIC STARS", "", 0],
    [7, "希望TRAVELER", "", 0],
    [8, "愛と勇気とフィロソフィー", "", 0],
    [9, "STEP BY STEP", "", 0],
    [10, "カフェとラッテのラブセオリー", "", 0],
    [11, "Take you higher", "", 0],
    [12, "開封MOTiVE", "", 0],
    [13, "DarkMatter LOVN' YOU", "", 0],
    [14, "Kiss &Cry", "", 0],
]
links = ["https://vgmdb.net/album/109263"]

[b83a585e4e1cbccdc5dbb56c0cd4525e]
catalognumber = "N/A"
date = "2022-04-19"
album = "異世界はスマートフォンとともに。第26巻特装版付属ドラマCD"
tracks = [
    [1, "[untitled]", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/f42c7232-ba16-4a5c-990d-7716ae087a21", "https://vgmdb.net/album/117448"]

[51bac439a8ce90768f0eaf2c72b7de0e]
catalognumber = "PCCG-02241"
date = "2023-05-03"
album = "リアルダイヤモンド/イセカイジュエリー"
tracks = [
    [1, "リアルダイヤモンド", "Gemstone7", 1],
    [2, "イセカイジュエリー (ユミナ、リンゼ、エルゼver.)", "ユミナ (CV:高野麻里佳), エルゼ (CV:内田真礼) & リンゼ (CV:福緒唯)", 1],
    [3, "イセカイジュエリー (ユミナ、リンゼ、エルゼ、八重、スゥ、リーンver.)", "ユミナ (CV:高野麻里佳), エルゼ (CV:内田真礼), リンゼ (CV:福緒唯), 八重 (CV:赤﨑千夏), スゥ (CV:山下七海) & リーン (CV:上坂すみれ)", 1],
    [4, "イセカイジュエリー (ユミナ、リンゼ、エルゼ、八重、スゥ、リーン、ルーシア、ヒルデガルド、桜ver.)", "ユミナ (CV:高野麻里佳), エルゼ (CV:内田真礼), リンゼ (CV:福緒唯), 八重 (CV:赤﨑千夏), スゥ (CV:山下七海), リーン (CV:上坂すみれ), ルーシア (CV:高木美佑), ヒルデガルド (CV:芹澤優) & 桜 (CV:久保田未夢)", 1],
    [5, "リアルダイヤモンド [instrumental]", "Gemstone7", 1],
    [6, "イセカイジュエリー [instrumental]", "ユミナ (CV:高野麻里佳), エルゼ (CV:内田真礼), リンゼ (CV:福緒唯), 八重 (CV:赤﨑千夏), スゥ (CV:山下七海), リーン (CV:上坂すみれ), ルーシア (CV:高木美佑), ヒルデガルド (CV:芹澤優) & 桜 (CV:久保田未夢)", 1],
]
links = ["https://beta.musicbrainz.org/release/0ba50890-d394-407a-b9ad-85f293a54e62", "https://vgmdb.net/album/127133"]

[2c75d6787da281427c52fc90daf1f140]
catalognumber = "PCCG-02257"
date = "2023-06-21"
album = "TVアニメ「異世界はスマートフォンとともに。2」オリジナル・サウンドトラック"
tracks = [
    [1, "リアルダイヤモンド (TV size)", "Gemstone7(小嶋凛、紗乃ひお、堤雪菜、春咲暖、広瀬ゆうき、福緒唯、星希成奏)", 1],
    [2, "平和の朝", "吉川慶", 1],
    [3, "楽しもうか!", "山田航平", 1],
    [4, "街だ～!", "山田航平", 1],
    [5, "おう、まかせときな!", "吉川慶", 1],
    [6, "何気ない日のひととき", "山田航平", 1],
    [7, "ベルンの街並", "吉川慶", 1],
    [8, "ヒミツのはなし♡", "吉川慶", 1],
    [9, "汗⋯", "吉川慶", 1],
    [10, "いいかげんにせんかーい!", "山田航平", 1],
    [11, "いや、ちょっ、ちがうからね!?", "山田航平", 1],
    [12, "やるね…!", "山田航平", 1],
    [13, "作戦開始", "吉川慶", 1],
    [14, "フレイズ", "山田航平", 1],
    [15, "アクセルブースト!", "吉川慶", 1],
    [16, "ベルファスト王宮", "吉川慶", 1],
    [17, "バビロン", "吉川慶", 1],
    [18, "少しお灸をすえないとかな", "山田航平", 1],
    [19, "これをこうやって、こうすれば", "山田航平", 1],
    [20, "グッドニュース", "吉川慶", 1],
    [21, "え、マジで⋯?", "吉川慶", 1],
    [22, "あの、何をしてるの…?", "山田航平", 1],
    [23, "ふーん、そういうのが好きなんだ?", "山田航平", 1],
    [24, "神様の部屋", "吉川慶", 1],
    [25, "ふしぎな場所", "山田航平", 1],
    [26, "あやしい影", "山田航平", 1],
    [27, "冬夜への想い", "吉川慶", 1],
    [28, "今はもう少し、このままで", "山田航平", 1],
    [29, "エンデ", "吉川慶", 1],
    [30, "過去からのメッセージ", "吉川慶", 1],
    [31, "フレームギア起動", "吉川慶", 1],
    [32, "お前⋯何者だ?", "吉川慶", 1],
    [33, "わるだくみ", "山田航平", 1],
    [34, "勝負の時", "吉川慶", 1],
    [35, "正義の時", "吉川慶", 1],
    [36, "緊急事態!?", "山田航平", 1],
    [37, "一件落着!", "吉川慶", 1],
    [38, "穏やかな日々", "吉川慶", 1],
    [39, "イセカイジュエリー (TV size)", "ユミナ、エルゼ、リンゼ、八重、スゥ、リーン、ルーシア、ヒルデガルド、桜(CV.高野麻里佳、内田真礼、福緒唯、赤﨑千夏、山下七海、上坂すみれ、高木美佑、芹澤優、久保田未夢)", 1],
]
links = ["https://beta.musicbrainz.org/release/023b29e2-7c10-4967-ad69-dc09c87829c9", "https://vgmdb.net/album/129653"]
