[8ba29969f86fe8c3c4b734321372ba6f]
catalognumber = "LACM-34136"
date = "2021-07-14"
album = "たゆたえ、七色 / ARCANA PROJECT [正位置ver.] Disc 1 (CD)"
tracks = [
    [1, "たゆたえ、七色", "ARCANA PROJECT", 0],
    [2, "星影のファンタジア", "ARCANA PROJECT", 0],
    [3, "きっと、その未来にたどり着くから。", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/46c3ed57-ea60-42a2-93dc-b813353086ab", "https://vgmdb.net/album/110576"]

[8dffe781e940c375e9baf7cffd096a1d]
catalognumber = "LACM-34136"
date = "2021-07-14"
album = "たゆたえ、七色 / ARCANA PROJECT [正位置ver.] Disc 2 (Blu-ray)"
tracks = [
    [1, "「たゆたえ、七色」Music Video", "ARCANA PROJECT", 0],
    [2, "「たゆたえ、七色」Jacket Making", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/46c3ed57-ea60-42a2-93dc-b813353086ab", "https://vgmdb.net/album/110576"]

[b9eb8183144e60af4dc05a8ba6175e51]
catalognumber = "LACM-24137"
date = "2021-07-14"
album = "たゆたえ、七色 / ARCANA PROJECT [アニメ盤]"
tracks = [
    [1, "たゆたえ、七色", "ARCANA PROJECT", 0],
    [2, "星影のファンタジア", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/efb99003-228c-4d99-bde7-85a6616e344e", "https://vgmdb.net/album/110575"]

[6b402c6733ad47519759a439023811ed]
catalognumber = "LACM-34137"
date = "2021-07-14"
album = "たゆたえ、七色 / ARCANA PROJECT [逆位置ver.] Disc 2 (Blu-ray)"
tracks = [
    [1, "「たゆたえ、七色」Music Video", "ARCANA PROJECT", 0],
    [2, "「たゆたえ、七色」Music Video Making", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/ed3fb6a4-c29b-43d0-9dfd-92069034aee9", "https://vgmdb.net/album/110577"]

[7b90ad39b787ca38b8c41a2121f7bfa7]
catalognumber = "LACM-34137"
date = "2021-07-14"
album = "たゆたえ、七色 / ARCANA PROJECT [逆位置ver.] Disc 1 (CD)"
tracks = [
    [1, "たゆたえ、七色", "ARCANA PROJECT", 0],
    [2, "星影のファンタジア", "ARCANA PROJECT", 0],
    [3, "Ophelia", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/ed3fb6a4-c29b-43d0-9dfd-92069034aee9", "https://vgmdb.net/album/110577"]

[25254624833b22ab8cd82dcd62eae63b]
catalognumber = "LACM-24136"
date = "2021-07-14"
album = "たゆたえ、七色 / ARCANA PROJECT"
tracks = [
    [1, "たゆたえ、七色", "ARCANA PROJECT", 0],
    [2, "星影のファンタジア", "ARCANA PROJECT", 0],
    [3, "ドンケア", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/ff7c2aa4-5335-4e0c-b851-f66b31ed7b55", "https://vgmdb.net/album/110574"]

[09b116da70e35722fd5728e370f3e57f]
catalognumber = "LACM-24155"
date = "2021-07-28"
album = "月海の揺り籠 / Mia REGINA [アーティスト盤] Vocal, Video"
tracks = [
    [1, "月海の揺り籠 (MUSIC VIDEO)", "Mia REGINA", 0],
]
links = ["https://beta.musicbrainz.org/release/639e6f31-e9d4-4e59-ae65-07ebe1c0ae7c", "https://vgmdb.net/album/111468"]

[7bde697948c841b4628e0b1016eb7ad1]
catalognumber = "LACM-24155"
date = "2021-07-28"
album = "月海の揺り籠 / Mia REGINA [アーティスト盤] Vocal"
tracks = [
    [1, "月海の揺り籠", "Mia REGINA", 0],
    [2, "Dear!!!", "Mia REGINA", 0],
    [3, "月海の揺り籠 (Instrumental)", "Mia REGINA", 0],
    [4, "Dear!!! (Instrumental)", "Mia REGINA", 0],
]
links = ["https://beta.musicbrainz.org/release/639e6f31-e9d4-4e59-ae65-07ebe1c0ae7c", "https://vgmdb.net/album/111468"]

[661ef360a88126281440203659c92108]
catalognumber = "LACM-24156"
date = "2021-07-28"
album = "月海の揺り籠 / Mia REGINA [アニメ盤]"
tracks = [
    [1, "月海の揺り籠", "Mia REGINA", 0],
    [2, "Dear!!!", "Mia REGINA", 0],
    [3, "月海の揺り籠 (Instrumental)", "Mia REGINA", 0],
    [4, "Dear!!! (Instrumental)", "Mia REGINA", 0],
]
links = ["https://beta.musicbrainz.org/release/3df30796-b425-42d0-b1c3-7031d1908cac", "https://vgmdb.net/album/111469"]

[06fda577b6cbd0cbfc2c431b7959163c]
catalognumber = "LACM-24204"
date = "2021-10-27"
album = "とめどない潮騒に僕たちは何を歌うだろうか / ARCANA PROJECT [アニメ盤]"
tracks = [
    [1, "とめどない潮騒に僕たちは何を歌うだろうか", "ARCANA PROJECT", 0],
    [2, "迷わないConquest", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/ac731660-90aa-4a81-af3a-1eb538a693a8", "https://vgmdb.net/album/113670"]

[fbdbe62540603cab2e3c243725a980f5]
catalognumber = "LACM-34204"
date = "2021-10-27"
album = "とめどない潮騒に僕たちは何を歌うだろうか / ARCANA PROJECT [逆位置ver.] Vocal"
tracks = [
    [1, "とめどない潮騒に僕たちは何を歌うだろうか", "ARCANA PROJECT", 0],
    [2, "迷わないConquest", "ARCANA PROJECT", 0],
    [3, "Ace Of Pentacles", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/15e711e2-3b08-400e-b829-c48afc3b4e72", "https://vgmdb.net/album/113672"]

[3f30bbb22b9c9beb2aa4f81bb4775b07]
catalognumber = "LACM-34204"
date = "2021-10-27"
album = "とめどない潮騒に僕たちは何を歌うだろうか / ARCANA PROJECT [逆位置ver.] Vocal, Video"
tracks = [
    [1, "「とめどない潮騒に僕たちは何を歌うだろうか」MV", "ARCANA PROJECT", 0],
    [2, "秋だ！勉強だ！第1 回 ARCANA PROJECT 定期試験", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/15e711e2-3b08-400e-b829-c48afc3b4e72", "https://vgmdb.net/album/113672"]

[775833c8e068bc36833b40b5ecf4661b]
catalognumber = "LACM-34203"
date = "2021-10-27"
album = "とめどない潮騒に僕たちは何を歌うだろうか / ARCANA PROJECT [正位置ver.] Vocal"
tracks = [
    [1, "とめどない潮騒に僕たちは何を歌うだろうか", "ARCANA PROJECT", 0],
    [2, "迷わないConquest", "ARCANA PROJECT", 0],
    [3, "Ace Of Pentacles", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/03d95858-a6cf-4f81-9665-3daad8ee42d6", "https://vgmdb.net/album/113673"]

[e57c577c1f0f75cb918bd73c0cb54066]
catalognumber = "LACM-34203"
date = "2021-10-27"
album = "とめどない潮騒に僕たちは何を歌うだろうか / ARCANA PROJECT [正位置ver.] Vocal, Video"
tracks = [
    [1, "「とめどない潮騒に僕たちは何を歌うだろうか」MV", "ARCANA PROJECT", 0],
    [2, "「とめどない潮騒に僕たちは何を歌うだろうか」MV Making", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/03d95858-a6cf-4f81-9665-3daad8ee42d6", "https://vgmdb.net/album/113673"]

[c037e698f817840629d98d58a7e65d88]
catalognumber = "LACM-24203"
date = "2021-10-27"
album = "とめどない潮騒に僕たちは何を歌うだろうか / ARCANA PROJECT"
tracks = [
    [1, "とめどない潮騒に僕たちは何を歌うだろうか", "ARCANA PROJECT", 0],
    [2, "迷わないConquest", "ARCANA PROJECT", 0],
    [3, "Ace Of Pentacles", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/9d11d6dc-834c-4241-a076-20ba0817002c", "https://vgmdb.net/album/113671"]

[c10e3f8a7155698b8d4e9b848e3070c7]
catalognumber = "LACM-24178"
date = "2021-11-10"
album = "新月のダ・カーポ / 相沢梨紗(でんぱ組.inc) [アーティスト盤] Vocal"
tracks = [
    [1, "新月のダ・カーポ", "相沢梨紗 (でんぱ組.inc)", 0],
    [2, "運命論アイドリング", "相沢梨紗 (でんぱ組.inc)", 0],
    [3, "新月のダ・カーポ (Instrumental)", "相沢梨紗 (でんぱ組.inc)", 0],
    [4, "運命論アイドリング (Instrumental)", "相沢梨紗 (でんぱ組.inc)", 0],
]
links = ["https://beta.musicbrainz.org/release/756d6fd5-5a15-42d8-b04d-9a42c2c1ba5e", "https://vgmdb.net/album/113668"]

[1509afb4f591353d99617c54635e504c]
catalognumber = "LACM-24178"
date = "2021-11-10"
album = "新月のダ・カーポ / 相沢梨紗(でんぱ組.inc) [アーティスト盤] Vocal, Video"
tracks = [
    [1, "新月のダ・カーポ (Music Video)", "相沢梨紗", 0],
    [2, "新月のダ・カーポ (Music Video Making)", "相沢梨紗", 0],
]
links = ["https://beta.musicbrainz.org/release/756d6fd5-5a15-42d8-b04d-9a42c2c1ba5e", "https://vgmdb.net/album/113668"]

[f9ec22786988b1f7dfafb27659c2aee4]
catalognumber = "LACM-24179"
date = "2021-11-10"
album = "新月のダ・カーポ / 相沢梨紗(でんぱ組.inc) [アニメ盤]"
tracks = [
    [1, "新月のダ・カーポ", "相沢梨紗 (でんぱ組.inc)", 0],
    [2, "運命論アイドリング", "相沢梨紗 (でんぱ組.inc)", 0],
    [3, "新月のダ・カーポ (Instrumental)", "相沢梨紗 (でんぱ組.inc)", 0],
    [4, "運命論アイドリング (Instrumental)", "相沢梨紗 (でんぱ組.inc)", 0],
]
links = ["https://beta.musicbrainz.org/release/85ecb852-6923-465e-a0d3-3fdf67455a4e", "https://vgmdb.net/album/113667"]

[b5882b800371ab62059579c49a44ed8b]
catalognumber = "LACM-24209"
date = "2021-11-24"
album = "High tide girl / 海咲野くくる (CV:伊藤美来)"
tracks = [
    [1, "High tide girl", "海咲野くくる(CV.伊藤美来)", 0],
    [2, "君といたアクアトープ", "海咲野くくる(CV.伊藤美来)、宮沢風花(CV.逢田梨香子)", 0],
    [3, "High tide girl (Instrumental)", "海咲野くくる(CV.伊藤美来)", 0],
    [4, "君といたアクアトープ (Instrumental)", "海咲野くくる(CV.伊藤美来)、宮沢風花(CV.逢田梨香子)", 0],
]
links = ["https://beta.musicbrainz.org/release/fe060c05-8e32-4193-9a67-887e0c447a7f", "https://vgmdb.net/album/114656"]

[f1bf6b34617b24144476833428038aaf]
catalognumber = "LACA-9875~6"
date = "2022-01-26"
album = "TVアニメ『白い砂のアクアトープ』オリジナルサウンドトラック Original Soundtrack"
tracks = [
    [1, "まくとぅそーけ、なんくるないさ", "出羽良彰", 0],
    [2, "新しいスタート", "出羽良彰", 0],
    [3, "アクリルガラス", "出羽良彰", 0],
    [4, "くくる", "出羽良彰", 0],
    [5, "導かれるままに", "出羽良彰", 0],
    [6, "風花", "出羽良彰", 0],
    [7, "あきらめきれない夢", "出羽良彰", 0],
    [8, "アクアトープ", "出羽良彰", 0],
    [9, "がまがま水族館", "出羽良彰", 0],
    [10, "夏休み館長", "出羽良彰", 0],
    [11, "ひるまさん、、", "出羽良彰", 0],
    [12, "うどんちゃん", "出羽良彰", 0],
    [13, "くちばしの傷", "出羽良彰", 0],
    [14, "なくしかけてるくくるの夢", "出羽良彰", 0],
    [15, "夢を守るため", "出羽良彰", 0],
    [16, "ふたりの再出発", "出羽良彰", 0],
    [17, "ブルー", "出羽良彰", 0],
    [18, "フラッシュバック", "出羽良彰", 0],
    [19, "母と子", "出羽良彰", 0],
    [20, "バックヤード", "出羽良彰", 0],
    [21, "不審者", "出羽良彰", 0],
    [22, "隠せない動揺", "出羽良彰", 0],
    [23, "重なる心", "出羽良彰", 0],
    [24, "予感", "出羽良彰", 0],
    [25, "不穏な空気", "出羽良彰", 0],
    [26, "よんな〜 よんな〜", "出羽良彰", 0],
    [27, "まだ、大事な仕事が", "出羽良彰", 0],
    [28, "悲しみを堪えて", "出羽良彰", 0],
    [29, "ファーストペンギン", "出羽良彰", 0],
    [30, "久しぶりの休日", "出羽良彰", 0],
    [31, "真帆とくくる", "出羽良彰", 0],
    [32, "チョコ", "出羽良彰", 0],
    [33, "揺らぐ心", "出羽良彰", 0],
    [34, "漂流", "出羽良彰", 0],
    [35, "くくるの絶望", "出羽良彰", 0],
    [36, "夢の終わりと始まり", "出羽良彰", 0],
]
links = ["https://beta.musicbrainz.org/release/7293683c-0b37-46b5-8290-ef6e8dbdb9f7", "https://vgmdb.net/album/116125"]

[2b343f1c6eb052ced44e06ba7c7639ae]
catalognumber = "LACA-9875~6"
date = "2022-01-26"
album = "TVアニメ『白い砂のアクアトープ』オリジナルサウンドトラック Original Soundtrack, Vocal"
tracks = [
    [1, "Re Start!!", "出羽良彰", 0],
    [2, "おそろいのキーホルダー", "出羽良彰", 0],
    [3, "アクアスフィア", "出羽良彰", 0],
    [4, "プランクトン", "出羽良彰", 0],
    [5, "タッチプール", "出羽良彰", 0],
    [6, "アクアリウム・ティンガーラ", "出羽良彰", 0],
    [7, "失敗の予感", "出羽良彰", 0],
    [8, "泣いてないよ、", "出羽良彰", 0],
    [9, "あなたがいるから", "出羽良彰", 0],
    [10, "レクリエーション", "出羽良彰", 0],
    [11, "ペンギンストライク", "出羽良彰", 0],
    [12, "OHANA", "出羽良彰", 0],
    [13, "ウミウシ採取", "出羽良彰", 0],
    [14, "カイシャ", "出羽良彰", 0],
    [15, "しらたま", "出羽良彰", 0],
    [16, "ここにいる理由", "出羽良彰", 0],
    [17, "限界かも、、", "出羽良彰", 0],
    [18, "知夢の憂鬱", "出羽良彰", 0],
    [19, "育児体験", "出羽良彰", 0],
    [20, "大事な一人息子", "出羽良彰", 0],
    [21, "知夢の告白", "出羽良彰", 0],
    [22, "海月風", "出羽良彰", 0],
    [23, "離島", "出羽良彰", 0],
    [24, "ルカの悩み", "出羽良彰", 0],
    [25, "積み重なるダメージ", "出羽良彰", 0],
    [26, "迷子のイルカ", "出羽良彰", 0],
    [27, "ウミガメの孵化", "出羽良彰", 0],
    [28, "イルカとの別れ", "出羽良彰", 0],
    [29, "未来へ", "出羽良彰", 0],
    [30, "たゆたえ、七色 (TV Size)", "ARCANA PROJECT", 0],
    [31, "月海の揺り籠 (TV Size)", "Mia REGINA", 0],
    [32, "とめどない潮騒に僕たちは何を歌うだろうか (TV Size)", "ARCANA PROJECT", 0],
    [33, "新月のダ・カーポ (TV Size)", "相沢梨紗", 0],
]
links = ["https://beta.musicbrainz.org/release/7293683c-0b37-46b5-8290-ef6e8dbdb9f7", "https://vgmdb.net/album/116125"]

[8e93f24de9b003ad49a76226752a04af]
catalognumber = "LACA-9911~2"
date = "2022-08-24"
album = "創世記 / ARCANA PROJECT Disc 1 [LACA-9911]"
tracks = [
    [1, "快晴のエスタリスタ", "ARCANA PROJECT", 0],
    [2, "カンパネラ響く空で", "ARCANA PROJECT", 0],
    [3, "たゆたえ、七色", "ARCANA PROJECT", 0],
    [4, "とめどない潮騒に僕たちは何を歌うだろうか", "ARCANA PROJECT", 0],
    [5, "星影のファンタジア", "ARCANA PROJECT", 0],
    [6, "夢で世界を変えるなら", "ARCANA PROJECT", 0],
    [7, "the Sunlight", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/cb08b091-78df-40d9-baae-31f5146330c9", "https://vgmdb.net/album/121056"]

[7aef3e3515b045214fa1cddbb2a670fe]
catalognumber = "LACA-9911~2"
date = "2022-08-24"
album = "創世記 / ARCANA PROJECT Disc 2 [LACA-9912]"
tracks = [
    [1, "天運ヘキサグラム", "ARCANA PROJECT", 0],
    [2, "ヒトリガタリ", "ARCANA PROJECT", 0],
    [3, "TWO of WANDS", "ARCANA PROJECT", 0],
    [4, "Echochrome", "ARCANA PROJECT", 0],
    [5, "Ace Of Pentacles", "ARCANA PROJECT", 0],
    [6, "Ophelia", "ARCANA PROJECT", 0],
    [7, "慟哭のトルメンタ", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/cb08b091-78df-40d9-baae-31f5146330c9", "https://vgmdb.net/album/121056"]

[972186a6766978d757217e4392e69d6e]
catalognumber = "LACA-39911~2"
date = "2022-08-24"
album = "創世記 / ARCANA PROJECT [初回限定盤] Vocal Disc 1"
tracks = [
    [1, "快晴のエスタリスタ", "ARCANA PROJECT", 0],
    [2, "カンパネラ響く空で", "ARCANA PROJECT", 0],
    [3, "たゆたえ、七色", "ARCANA PROJECT", 0],
    [4, "とめどない潮騒に僕たちは何を歌うだろうか", "ARCANA PROJECT", 0],
    [5, "星影のファンタジア", "ARCANA PROJECT", 0],
    [6, "夢で世界を変えるなら", "ARCANA PROJECT", 0],
    [7, "the Sunlight", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/cb08b091-78df-40d9-baae-31f5146330c9", "https://vgmdb.net/album/121057"]

[cd3ed981dbccfffa6a0b95a52ba4ff65]
catalognumber = "LACA-39911~2"
date = "2022-08-24"
album = "創世記 / ARCANA PROJECT [初回限定盤] Vocal Disc 2"
tracks = [
    [1, "天運ヘキサグラム", "ARCANA PROJECT", 0],
    [2, "ヒトリガタリ", "ARCANA PROJECT", 0],
    [3, "TWO of WANDS", "ARCANA PROJECT", 0],
    [4, "Echochrome", "ARCANA PROJECT", 0],
    [5, "Ace Of Pentacles", "ARCANA PROJECT", 0],
    [6, "Ophelia", "ARCANA PROJECT", 0],
    [7, "慟哭のトルメンタ", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/cb08b091-78df-40d9-baae-31f5146330c9", "https://vgmdb.net/album/121057"]

[53369fc3db2d55aa0a7a6da42b13cb85]
catalognumber = "LACA-39911~2"
date = "2022-08-24"
album = "創世記 / ARCANA PROJECT [初回限定盤] Vocal, Video"
tracks = [
    [1, "快晴のエスタリスタ -Music Video-", "ARCANA PROJECT", 0],
    [2, "慟哭のトルメンタ -Music Video-", "ARCANA PROJECT", 0],
    [3, "快晴のエスタリスタ -MusicVideo Making-", "ARCANA PROJECT", 0],
    [4, "慟哭のトルメンタ -MusicVideo Making-", "ARCANA PROJECT", 0],
]
links = ["https://beta.musicbrainz.org/release/cb08b091-78df-40d9-baae-31f5146330c9", "https://vgmdb.net/album/121057"]
