[29f8e2d14b31851e5e9a0a2fff39d312]
catalognumber = "TOCT-40415"
date = "2012-11-14"
album = "神様はじめました/神様お願い / ハナエ Disc 1 (CD)"
tracks = [
    [1, "神様はじめました", "ハナエ", 0],
    [2, "神様お願い", "ハナエ", 0],
    [3, "神様はじめました（TVアニメ・オープニングVer.）", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/754c16c0-9ce7-485c-bf36-5ff7694061ad", "https://vgmdb.net/album/35194"]

[18428d1ad4c8c2a098038e2866433a7a]
catalognumber = "TOCT-40415"
date = "2012-11-14"
album = "神様はじめました/神様お願い / ハナエ Disc 2 (DVD)"
tracks = [
    [1, "神様はじめました（Music Video）", "ハナエ", 0],
    [2, "Music Video オフショット映像", "ハナエ", 0],
    [3, "TVアニメ「神様はじめました」（ノンテロップ・オープニング映像）", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/754c16c0-9ce7-485c-bf36-5ff7694061ad", "https://vgmdb.net/album/35194"]

[61557fdf50357cb75fdba7facf880cea]
catalognumber = "TOCT-40416"
date = "2012-11-14"
album = "神様はじめました/神様お願い / ハナエ"
tracks = [
    [1, "神様はじめました", "ハナエ", 0],
    [2, "神様お願い", "ハナエ", 0],
    [3, "神様はじめました（オリジナル・カラオケ）", "ハナエ", 0],
    [4, "神様お願い（オリジナル・カラオケ）", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/a4bd8a26-1493-4569-a5d5-7ddbe1ed3206", "https://vgmdb.net/album/35195"]

[24ef05ca374f8ab8d556cb4524af2cfd]
catalognumber = ""
date = "2013-02-20"
album = "神様はじめました 第三巻 特典 スペシャルCD"
tracks = [
    [1, "レッツバリバリ神使の慈爱", "巴卫(立花慎之介)", 0],
    [2, "谨制语りドラマ“巴卫、看病する”", "巴卫(立花慎之介)", 0],
    [3, "立花慎之介キャストトーク", "巴卫(立花慎之介)", 0],
    [4, "孤高の野狐・巴卫(Rubato Ver.)", "増田俊郎", 0],
    [5, "鬼火の童(お囃子バージョン)", "増田俊郎", 0],
    [6, "鬼火の童・鬼切、虎彻にございます!", "増田俊郎", 0],
    [7, "桃园奈々生・花も耻じらう高校生", "増田俊郎", 0],
    [8, "神事と勉学…二足のワラジ", "増田俊郎", 0],
    [9, "最后の一花…ヨノモリ社", "増田俊郎", 0],
    [10, "解き放たれし想い", "増田俊郎", 0],
    [11, "天狗 vs 野狐", "増田俊郎", 0],
    [12, "雷神・成神姫登场!", "増田俊郎", 0],
    [13, "秘策!打ち出の小槌", "増田俊郎", 0],
    [14, "多々良沼の主・沼皇女…ガチッ!", "増田俊郎", 0],
]
links = ["https://music.163.com/#/album?id=2422482"]

[7135baba1df568d507c356773e9f7661]
catalognumber = "TMS-312"
date = "2013-03-25"
album = "『神様はじめました』オリジナル・サウンドトラック"
tracks = [
    [1, "桃園奈々生・花も恥じらう女子高生", "増田俊郎", 0],
    [2, "立ち退き→公園ベンチ→廃神社", "増田俊郎", 0],
    [3, "異世界・光_Part.2", "増田俊郎", 0],
    [4, "物の怪衆の住処", "増田俊郎", 0],
    [5, "鬼火の童・鬼切、虎徹にございます!", "増田俊郎", 0],
    [6, "孤高の野狐・巴衛 (Normal_Ver.)", "増田俊郎", 0],
    [7, "鬼火の童 (お囃子バージョン)", "増田俊郎", 0],
    [8, "託された想い", "増田俊郎", 0],
    [9, "神使のお仕事", "増田俊郎", 0],
    [10, "異世界・闇_Part.1", "増田俊郎", 0],
    [11, "不穏な雰囲気", "増田俊郎", 0],
    [12, "大ピンチ!", "増田俊郎", 0],
    [13, "鬼婆", "増田俊郎", 0],
    [14, "眩光", "増田俊郎", 0],
    [15, "結ばれませ、さすれば…。", "増田俊郎", 0],
    [16, "神事と勉学…二足のワラジ", "増田俊郎", 0],
    [17, "堕天使DA☆TEN☆DIE(インスト・バージョン)", "増田俊郎", 0],
    [18, "伝家の宝刀…“言霊縛り”", "増田俊郎", 0],
    [19, "宴", "増田俊郎", 0],
    [20, "多々良沼の主・沼皇女…ガチッ!", "増田俊郎", 0],
    [21, "あやかしの皆さん、登場～!", "増田俊郎", 0],
    [22, "異世界・光_Part.1", "増田俊郎", 0],
    [23, "祝!恋ばな成就!", "増田俊郎", 0],
    [24, "白蛇の神使・瑞希…遠い記憶", "増田俊郎", 0],
    [25, "口論!", "増田俊郎", 0],
    [26, "揺れ動く心", "増田俊郎", 0],
    [27, "解き放たれし想い", "増田俊郎", 0],
    [28, "異世界・闇_Part.2", "増田俊郎", 0],
    [29, "雷神・鳴神姫登場!", "増田俊郎", 0],
    [30, "秘策!打ち出の小槌", "増田俊郎", 0],
    [31, "緊張の瞬間!", "増田俊郎", 0],
    [32, "天狗 vs 野狐", "増田俊郎", 0],
    [33, "神楽_Part.1", "増田俊郎", 0],
    [34, "神楽_Part.2", "増田俊郎", 0],
    [35, "『神様おねがい』堕天使☆Mix (Extended Edition)", "ハナエ", 0],
    [36, "『神様おねがい』堕天使☆Mix (Extended Edition - カラオケ)", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/83f7b789-a050-40c3-97ec-dc0a36960f26", "https://vgmdb.net/album/37385"]

[38cbc096f6f75ad1942e9f3f6eb4384d]
catalognumber = ""
date = "2013-06-18"
album = "神様はじめました Blu-ray Vol.7 特典CD"
tracks = [
    [1, "DA☆TENSHI", "岸尾だいすけ", 0],
    [2, "「鞍馬、デートをする」", "岸尾だいすけ", 0],
    [3, "岸尾だいすけキャストトーク", "岸尾だいすけ", 0],
    [4, "BGM異世界編:異世界・闇_Part1", "岸尾だいすけ", 0],
    [5, "BGM異世界編:異世界・闇_Part.2", "岸尾だいすけ", 0],
    [6, "BGM異世界編:鬼婆", "岸尾だいすけ", 0],
    [7, "BGM異世界編:物の怪衆の住処", "岸尾だいすけ", 0],
    [8, "BGM異世界編:異世界・光_Part.1", "岸尾だいすけ", 0],
    [9, "BGM異世界編:神使の契約", "岸尾だいすけ", 0],
    [10, "BGM異世界編:異世界・光_Part.2", "岸尾だいすけ", 0],
    [11, "BGM異世界編:宴", "岸尾だいすけ", 0],
    [12, "BGM異世界編:眩光(Alternate Ver.)", "岸尾だいすけ", 0],
    [13, "BGM異世界編:神楽_Part.1", "岸尾だいすけ", 0],
    [14, "BGM異世界編:神楽_Part.2", "岸尾だいすけ", 0],
    [15, "BGM異世界編:堕天使DA☆TEN☆DIE", "岸尾だいすけ", 0],
    [16, "BGM異世界編:天使LA☆TEN☆SEE", "岸尾だいすけ", 0],
]
links = ["https://music.163.com/#/album?id=2786694"]

[93c6a295a93bfd05d6ecee8961467fd0]
catalognumber = "UICV-5037"
date = "2015-01-14"
album = "神様の神様/おとといおいで / ハナエ"
tracks = [
    [1, "神様の神様", "ハナエ", 0],
    [2, "おとといおいで", "ハナエ", 0],
    [3, "神様の神様 (オリジナル・カラオケ)", "ハナエ", 0],
    [4, "おとといおいで (オリジナル・カラオケ)", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/1f1383d2-1b7a-4d76-a652-71eb60d756d2", "https://vgmdb.net/album/49415"]

[cac32b3a91700628d70c00b078255980]
catalognumber = "UICV-9079"
date = "2015-01-14"
album = "神様の神様/おとといおいで / ハナエ Disc 1 (CD)"
tracks = [
    [1, "神様の神様", "ハナエ", 0],
    [2, "おとといおいで", "ハナエ", 0],
    [3, "神様の神様 (TVアニメ・オープニング Ver.)", "ハナエ", 0],
    [4, "おとといおいで (TVアニメ・エンディング Ver.)", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/2e31d0f3-ad39-4036-be78-e87fb0d8f3fc", "https://vgmdb.net/album/49416"]

[bddbce6d4154522ccf633fc6437f8806]
catalognumber = "UICV-9079"
date = "2015-01-14"
album = "神様の神様/おとといおいで / ハナエ Disc 2 (DVD)"
tracks = [
    [1, "TVアニメ「神様はじめました」スペシャル映像 (楽曲「神様の神様」)", "ハナエ", 0],
    [2, "TVアニメ「神様はじめました◎」ノンテロップ・エンディング映像 (楽曲「おとといおいで」)", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/2e31d0f3-ad39-4036-be78-e87fb0d8f3fc", "https://vgmdb.net/album/49416"]

[4f42f6045b92c9210edc5242422c1426]
catalognumber = "PCCG-01449"
date = "2015-01-21"
album = "神様はじめました◎ キャラクターソング2 ~奈々生ひとり占め~ / 奈々生と巴衛 (CV:三森すずこ&立花慎之介)"
tracks = [
    [1, "背中合わせの空模様", "", 0],
    [2, "レベル1の神様", "", 0],
    [3, "護におまかせ!", "", 0],
    [4, "背中合わせの空模様-巴衛off ver.-", "", 0],
    [5, "背中合わせの空模様-奈々生off ver.-", "", 0],
    [6, "背中合わせの空模様-instrumental-", "", 0],
    [7, "レベル1の神様-instrumental-", "", 0],
    [8, "護におまかせ!-instrumental-", "", 0],
]
links = ["https://vgmdb.net/album/49436"]

[684fd4b6280ad2fcd27fd4d95939c521]
catalognumber = "PCCG-01448"
date = "2015-01-21"
album = "神様はじめました◎ キャラクターソング1 ~いつでも君の味方!神使's~ / 神使's (CV:立花慎之介&岡本信彦)"
tracks = [
    [1, "二人の雨", "", 0],
    [2, "想いかんざし花一輪", "", 0],
    [3, "神酒PARTY", "", 0],
    [4, "二人の雨-瑞希off ver.-", "", 0],
    [5, "二人の雨-巴衛off ver.-", "", 0],
    [6, "二人の雨-instrumental-", "", 0],
    [7, "想いかんざし花一輪-instrumental-", "", 0],
    [8, "神酒PARTY-instrumental-", "", 0],
]
links = ["https://vgmdb.net/album/49435"]

[71128ccd71707ae62f46980bf6f9b393]
catalognumber = ""
date = "2015-01-21"
album = "堕天使DA☆TEN☆DIE/レッツバリバリ神使の慈愛-発茶怪remix-"
tracks = [
    [1, "堕天使DA☆TEN☆DIE", "岸尾だいすけ", 0],
    [2, "レッツバリバリ神使の慈愛-発茶怪remix-", "立花慎之介", 0],
    [3, "堕天使DA☆TEN☆DIE-instrumental-", "岸尾だいすけ", 0],
]
links = ["https://music.163.com/#/album?id=3106285"]

[4a65c3af9dd8aad17e0cb0f7664649a4]
catalognumber = "PCCG-01460"
date = "2015-02-18"
album = "神様はじめました◎ キャラクターソング4 ~血塗られた兄弟の絆~ / 悪羅王 (CV:諏訪部順一)"
tracks = [
    [1, "Dark Side x Out Side", "", 0],
    [2, "極悪の華", "", 0],
    [3, "Dance Around→Dead", "", 0],
    [4, "Dark Side x Out Side-巴衛 off ver.-", "", 0],
    [5, "Dark Side x Out Side-悪羅王 off ver.-", "", 0],
    [6, "Dark Side x Out Side-instrumental-", "", 0],
    [7, "極悪の華-instrumental-", "", 0],
    [8, "Dance Around→Dead-instrumental-", "", 0],
]
links = ["https://vgmdb.net/album/49723"]

[2322fd511773b4d33ae8ad76c7e48b9e]
catalognumber = "PCCG-01459"
date = "2015-02-18"
album = "神様はじめました◎ キャラクターソング3 ~つかまえて欲しいわ!神々の戯れ~ / 大国主 (CV:森久保祥太郎)"
tracks = [
    [1, "恋のまにまに!!", "", 0],
    [2, "きみとシークレット", "", 0],
    [3, "Awesome!", "", 0],
    [4, "恋のまにまに!!-乙比古 off ver.-", "", 0],
    [5, "恋のまにまに!!-大国主 off ver.-", "", 0],
    [6, "恋のまにまに!!-instrumental-", "", 0],
    [7, "きみとシークレット-instrumental-", "", 0],
    [8, "Awesome!-instrumental-", "", 0],
]
links = ["https://vgmdb.net/album/49722"]

[40e35ffafefabc28db86981f9bb3d083]
catalognumber = "PCXP-50272-2"
date = "2015-03-04"
album = "神様はじめました◎ 上巻 スペシャルCD"
tracks = [
    [1, "Happiness～ミカゲ社のテーマ～ (上巻Ver.)", "", 0],
    [2, "シチュエーションドラマ ～巴衛とお花見編～", "", 0],
    [3, "キャストトーク", "", 0],
]
links = ["https://vgmdb.net/album/53249"]

[0107e43d3194095656c3319bed71fbb0]
catalognumber = ""
date = "2015-03-04"
album = "TVアニメ「神様はじめました◎」上巻 スペシャルCD Vol.1"
tracks = [
    [1, "Happiness", "三森すずこ", 0],
    [2, "巴衛とお花見", "立花慎之介", 0],
    [3, "キャストトーク", "三森すずこ", 0],
]
links = ["https://music.163.com/#/album?id=3109135"]

[89931fc26cb35ad184d4cc7d25037a1d]
catalognumber = "PCCG-01463"
date = "2015-03-18"
album = "神様はじめました◎ キャラクターソング5 ~鞍馬天狗☆男祭~ / 二郎 (CV:羽多野渉) & 翠郎(CV:平川大輔)"
tracks = [
    [1, "鞍馬双天狗", "", 0],
    [2, "いつも ずっと", "", 0],
    [3, "証", "", 0],
    [4, "鞍馬双天狗-二郎 off ver-", "", 0],
    [5, "鞍馬双天狗-翠郎 off ver-", "", 0],
    [6, "鞍馬双天狗-instrumental-", "", 0],
    [7, "いつも ずっと-instrumental-", "", 0],
    [8, "証-instrumental-", "", 0],
]
links = ["https://vgmdb.net/album/49724"]

[4a4405676231168cb5dd98b9309106f1]
catalognumber = "PCCG-01464"
date = "2015-03-18"
album = "神様はじめました◎ キャラクターソング6 漆黒の堕天使~降臨の宴~ / 鞍馬 (CV:岸尾だいすけ)"
tracks = [
    [1, "Buddy Guy", "岸尾だいすけ", 0],
    [2, "刹那LOVE☆フォーエバー", "岸尾だいすけ", 0],
    [3, "熱望HONEY", "岸尾だいすけ", 0],
    [4, "翼☆バサ☆ハザード", "岸尾だいすけ", 0],
    [5, "挑発wild Soul!!", "岸尾だいすけ", 0],
    [6, "Buddy Guy-巴衛 Off Ver.-", "岸尾だいすけ", 0],
    [7, "Buddy Guy-KURAMA Off Ver.-", "岸尾だいすけ", 0],
    [8, "Buddy Guy-Instrumental-", "岸尾だいすけ", 0],
    [9, "刹那LOVE☆フォーエバー-Instrumental-", "岸尾だいすけ", 0],
    [10, "熱望HONEY-Instrumental-", "岸尾だいすけ", 0],
    [11, "翼☆バサ☆ハザード-Instrumental-", "岸尾だいすけ", 0],
    [12, "挑発wild Soul!!-Instrumental-", "岸尾だいすけ", 0],
]
links = ["https://beta.musicbrainz.org/release/741b2464-020d-4903-b082-b8ca67ee933d", "https://vgmdb.net/album/49725"]

[1d38c6650577ea3742354512fdf4a1fe]
catalognumber = "PCXP-50273-2"
date = "2015-04-01"
album = "神様はじめました◎ 中巻 スペシャルCD"
tracks = [
    [1, "Happiness～ミカゲ社のテーマ～ (中巻Ver.)", "", 0],
    [2, "シチュエーションドラマ ～巴衛と相合傘編～", "", 0],
    [3, "キャストトーク", "", 0],
]
links = ["https://vgmdb.net/album/53250"]

[e13bf12c8f9df45c087b27b159a385be]
catalognumber = "TMS-329"
date = "2015-04-01"
album = "神様はじめました オリジナルサウンドトラック 音霊集◎"
tracks = [
    [1, "全力疾走! 護くん", "増田俊郎", 0],
    [2, "登場! 神堕ちの皆さん", "増田俊郎", 0],
    [3, "発動! 退魔結界", "増田俊郎", 0],
    [4, "降臨! 大国主命", "増田俊郎", 0],
    [5, "心のオアシス、水玉姐さん", "増田俊郎", 0],
    [6, "小さな幸せ", "増田俊郎", 0],
    [7, "戦神 vs 巴衛", "増田俊郎", 0],
    [8, "契り…再び◎", "増田俊郎", 0],
    [9, "『雲珠桜』by 翠郎兄", "増田俊郎", 0],
    [10, "腹に一物…夜鳥", "増田俊郎", 0],
    [11, "怪しさ満点! 夜鳥", "増田俊郎", 0],
    [12, "鞍馬山の瘴気", "増田俊郎", 0],
    [13, "目指す理想は真寿郎さま", "増田俊郎", 0],
    [14, "鞍馬・負の記憶", "増田俊郎", 0],
    [15, "健気な小天狗・橙丸", "増田俊郎", 0],
    [16, "厳格一徹!二郎兄", "増田俊郎", 0],
    [17, "夜鳥 vs 奈々生", "増田俊郎", 0],
    [18, "さらに疾走!退魔結界", "増田俊郎", 0],
    [19, "もとのお山に…。", "増田俊郎", 0],
    [20, "めでたし! 鞍馬山", "増田俊郎", 0],
    [21, "幼き日の奈々生", "増田俊郎", 0],
    [22, "奈々生・母との思い出", "増田俊郎", 0],
    [23, "奈々生・母が託した想い", "増田俊郎", 0],
    [24, "奈々生・消え行く想い", "増田俊郎", 0],
    [25, "奈々生・幼き日の記憶 Part1", "増田俊郎", 0],
    [26, "奈々生・幼き日の記憶 Part2", "増田俊郎", 0],
    [27, "翼☆バサ☆ハザード (On Air Ver.)", "KURAMA (岸尾だいすけ)", 0],
    [28, "予告編用チェイサー", "増田俊郎", 0],
    [29, "翼☆バサ☆ハザード (Full Ver.)", "岸尾だいすけ", 0],
]
links = ["https://beta.musicbrainz.org/release/edef267d-53da-4ddb-88d5-6c5fb5e42a92", "https://vgmdb.net/album/51479"]

[86142782912459bbdb36bbcabc73fcca]
catalognumber = "PCXP-50274-2"
date = "2015-07-01"
album = "神様はじめました◎ 下巻 スペシャルCD"
tracks = [
    [1, "Happiness～ミカゲ社のテーマ～ (下巻Ver.)", "", 0],
    [2, "シチュエーションドラマ～巴衛と寝起き編～", "", 0],
    [3, "キャストトーク", "", 0],
]
links = ["https://vgmdb.net/album/53251"]

[806f0a62e6fe8e707453550fbc94410f]
catalognumber = "UICV-1065"
date = "2016-03-23"
album = "SHOW GIRL"
tracks = [
    [1, "パーティへようこそ", "ハナエ", 0],
    [2, "シュガリルラ", "ハナエ feat. 相沢梨紗", 0],
    [3, "CANDY", "ハナエ", 0],
    [4, "xxx", "ハナエ", 0],
    [5, "小さな恋のものがたり", "ハナエ", 0],
    [6, "あおいそら", "ハナエ", 0],
    [7, "LovE MoTion", "ハナエ", 0],
    [8, "ラストティーン", "ハナエ", 0],
    [9, "桜ミコトバ", "ハナエ", 0],
    [10, "SHOW GIRL", "ハナエ", 0],
]
links = ["https://beta.musicbrainz.org/release/9c6fe99e-0378-4056-8b67-f96323e005ed"]

[ff536b15ad539fe51642e1ce6b36468e]
catalognumber = "NJSJ-032"
date = "2021-11-03"
album = "1∞COLOR / 月ノ美兎、樋口楓、静凛、える、勇気ちひろ、鈴谷アキ、モイラ、渋谷ハジメ"
tracks = [
    [1, "1 ∞ color", "月ノ美兎, 樋口楓, 静凛, える, 勇気ちひろ, 鈴谷アキ, モイラ & 渋谷ハジメ", 0],
    [2, "拝啓ドッペルゲンガー", "月ノ美兎, 樋口楓", 0],
    [3, "Over Soul", "静凛, 勇気ちひろ", 0],
    [4, "輪舞-revolution", "鈴谷アキ, モイラ", 0],
    [5, "背中合わせの空模様", "える, 渋谷ハジメ", 0],
    [6, "1 ∞ color (instrumental)", "月ノ美兎, 樋口楓, 静凛, える, 勇気ちひろ, 鈴谷アキ, モイラ & 渋谷ハジメ", 0],
]
links = ["https://beta.musicbrainz.org/release/3d53527c-8e81-41fc-808c-cf0717bf80be", "https://vgmdb.net/album/115691"]
