[028ac2ec8da0238030b399cdb37872ac]
catalognumber = "LACM-14588"
date = "2017-04-26"
album = "DEAREST DROP / 田所あずさ [アーティスト盤]"
tracks = [
    [1, "DEAREST DROP", "田所あずさ", 1],
    [2, "残存エレジー", "田所あずさ", 1],
    [3, "レッドラズベリー", "田所あずさ", 0],
]
links = ["https://beta.musicbrainz.org/release/21bc8d12-c712-4dbe-9e4e-90da3cf3e0c3", "https://vgmdb.net/album/65423"]

[ec791918858ad7abcdd245dabf7cc402]
catalognumber = "LACM-14589"
date = "2017-04-26"
album = "DEAREST DROP / 田所あずさ [アニメジャケット盤]"
tracks = [
    [1, "DEAREST DROP", "田所あずさ", 1],
    [2, "残存エレジー", "田所あずさ", 1],
    [3, "DEAREST DROP (off vocal)", "田所あずさ", 1],
    [4, "残存エレジー (off vocal)", "田所あずさ", 1],
]
links = ["https://beta.musicbrainz.org/release/be043f2f-9ab2-4b32-b498-57058afa587c", "https://vgmdb.net/album/65422"]

[e06d0a84183a5fa18c45480bf8dae3f3]
catalognumber = "LACM-14607"
date = "2017-05-24"
album = "フロム / TRUE"
tracks = [
    [1, "フロム", "TRUE", 1],
    [2, "キネマ", "TRUE", 1],
    [3, "フロム (off vocal)", "TRUE", 1],
]
links = ["https://beta.musicbrainz.org/release/7250ae66-0528-480c-b48a-b04c30297b71", "https://vgmdb.net/album/65809"]

[ebbe0665763fe675af21903e9b101589]
catalognumber = "KAXA-7501CD"
date = "2017-06-28"
album = "終末なにしてますか?忙しいですか?救ってもらっていいですか? スペシャルオーディオドラマ1 しょーとしょーと詰め合わせ"
tracks = [
    [1, "タイトルコール", "", 1],
    [2, "6年8組 ヴィレム先生 出欠編", "", 1],
    [3, "ナイグラートのトロトロクッキング 1", "", 1],
    [4, "GOGO ティアット刑事 事件編", "", 1],
    [5, "6年8組 ヴィレム先生 自習編", "", 1],
    [6, "レディース総長物語", "", 1],
    [7, "ナイグラートのトロトロクッキング 2", "", 1],
    [8, "シックスティーエイトラジオ", "", 1],
    [9, "GOGO ティアット刑事 推理編", "", 1],
    [10, "6年8組 ヴィレム先生 女子更衣室編", "", 1],
    [11, "続・レディース総長物語", "", 1],
    [12, "GOGO ティアット刑事 解決編", "", 1],
    [13, "ナイグラートのトロトロクッキング 3", "", 1],
    [14, "6年8組 ヴィレム先生 放課後編", "", 1],
]
links = ["https://vgmdb.net/album/68566"]

[366cb477be2fbaec350fae75ab117fb1]
catalognumber = "LACA-9522~3"
date = "2017-07-12"
album = "TVアニメ『終末なにしてますか?忙しいですか?救ってもらっていいですか?』オリジナルサウンドトラック「青い記憶」 Original Soundtrack, Vocal"
tracks = [
    [1, "DEAREST DROP (TV size)", "田所あずさ", 1],
    [2, "フロム (TV size)", "TRUE", 1],
    [3, "Always in my heart", "山田タマル", 1],
    [4, "Scarborough Fair", "山田タマル", 1],
    [5, "キネマ (TV size)", "TRUE", 1],
    [6, "Call you", "山田タマル", 1],
    [7, "Ever be my love", "山田タマル", 1],
    [8, "小さな恋心", "加藤達也", 1],
    [9, "切ない恋心", "加藤達也", 1],
    [10, "跳ね回る恋心", "加藤達也", 1],
    [11, "Always in my heart -Guitar-", "加藤達也", 1],
    [12, "Always in my heart -Violin-", "加藤達也", 1],
    [13, "失われていく自分", "加藤達也", 1],
    [14, "愛しい人との時間", "加藤達也", 1],
    [15, "溢れる父性", "加藤達也", 1],
    [16, "過去への後悔", "加藤達也", 1],
    [17, "怒りの感情", "加藤達也", 1],
    [18, "エルクの空間", "加藤達也", 1],
    [19, "のんびりふんわり女の子", "加藤達也", 1],
    [20, "騒がしい子どもたち", "加藤達也", 1],
    [21, "いたずらまみれ", "加藤達也", 1],
    [22, "過剰にキュート", "加藤達也", 1],
    [23, "養育院での日々", "加藤達也", 1],
    [24, "失いがたい仲間たち", "加藤達也", 1],
    [25, "滅びの地", "加藤達也", 1],
    [26, "遺跡群", "加藤達也", 1],
]
links = ["https://beta.musicbrainz.org/release/406abee7-16e9-4e83-bfe8-36e6732d481f", "https://vgmdb.net/album/67258"]

[bb189aac9e252b68e731a0eae90dcdde]
catalognumber = "LACA-9522~3"
date = "2017-07-12"
album = "TVアニメ『終末なにしてますか?忙しいですか?救ってもらっていいですか?』オリジナルサウンドトラック「青い記憶」 Original Soundtrack"
tracks = [
    [1, "街の喧騒", "加藤達也", 1],
    [2, "人々の営み", "加藤達也", 1],
    [3, "キレのある追い詰められ感", "加藤達也", 1],
    [4, "妖精倉庫の日常", "加藤達也", 1],
    [5, "妖精倉庫のにぎやかイベント", "加藤達也", 1],
    [6, "静かな時間", "加藤達也", 1],
    [7, "力強い軍隊", "加藤達也", 1],
    [8, "飛空艇と冒険", "加藤達也", 1],
    [9, "旅立ち", "加藤達也", 1],
    [10, "家事は戦い", "加藤達也", 1],
    [11, "冬の日々", "加藤達也", 1],
    [12, "奇跡の瞬間", "加藤達也", 1],
    [13, "尽きる命", "加藤達也", 1],
    [14, "暖かな希望", "加藤達也", 1],
    [15, "不穏な空気", "加藤達也", 1],
    [16, "獣の進撃", "加藤達也", 1],
    [17, "ダグウェポン", "加藤達也", 1],
    [18, "必死の特攻", "加藤達也", 1],
    [19, "荒ぶる魔力", "加藤達也", 1],
    [20, "最終に向かって", "加藤達也", 1],
    [21, "伝承される魂", "加藤達也", 1],
    [22, "悲しき妖精の定め", "加藤達也", 1],
    [23, "高潔な志", "加藤達也", 1],
    [24, "これぞムーディ", "加藤達也", 1],
]
links = ["https://beta.musicbrainz.org/release/406abee7-16e9-4e83-bfe8-36e6732d481f", "https://vgmdb.net/album/67258"]

[4b5666bf6c13e84338b628c22d6db695]
catalognumber = "KAXA-7502CD"
date = "2017-07-26"
album = "終末なにしてますか?忙しいですか?救ってもらっていいですか? スペシャルオーディオドラマ2 名監督ティアット"
tracks = [
    [1, "名監督ティアット", "", 1],
]
links = ["https://vgmdb.net/album/69232"]

[1a4b599f874eff0ed19b7db381b7512b]
catalognumber = "KAXA-7503CD"
date = "2017-08-23"
album = "終末なにしてますか?忙しいですか?救ってもらっていいですか? スペシャルオーディオドラマ3 山狩りダイアリー"
tracks = [
    [1, "山狩りダイアリー", "", 1],
]
links = ["https://vgmdb.net/album/70183"]

[270ad25b462a9e09cf98e33177548b54]
catalognumber = "KAXA-7504CD"
date = "2017-09-27"
album = "終末なにしてますか?忙しいですか?救ってもらっていいですか? スペシャルオーディオドラマ4 妖精倉庫怪談物語"
tracks = [
    [1, "妖精倉庫怪談物語", "", 1],
]
links = ["https://vgmdb.net/album/70962"]

[edb01905e3c628c5703e60ffd22097f6]
catalognumber = "LACA-15659"
date = "2017-10-25"
album = "So What? / 田所あずさ"
tracks = [
    [1, "涙 one of them", "田所あずさ", 0],
    [2, "1HOPE SNIPER", "田所あずさ", 0],
    [3, "ストーリーテラー", "田所あずさ", 0],
    [4, "ギミーシェルター・ブライトネス", "田所あずさ", 0],
    [5, "スーパースタールーザー (So What? mix)", "田所あずさ", 0],
    [6, "Pajama KINGDOM", "田所あずさ", 0],
    [7, "そう上手くいかないものです。", "田所あずさ", 0],
    [8, "DEAREST DROP", "田所あずさ", 1],
    [9, "Crying", "田所あずさ", 0],
    [10, "僕は空を飛べない", "田所あずさ", 0],
    [11, "Aiming for Utopia", "田所あずさ", 0],
    [12, "I can't live without you.", "田所あずさ", 0],
    [13, "運命ジレンマ", "田所あずさ", 0],
    [14, "ころあるき", "田所あずさ", 0],
]
links = ["https://beta.musicbrainz.org/release/5748222e-0d6e-43d4-8867-3ce7552085b1", "https://vgmdb.net/album/69458"]

[e9665fcf70539766a4dff088f30799ff]
catalognumber = "LACA-35659"
date = "2017-10-25"
album = "So What? / 田所あずさ Disc 1 (CD)"
tracks = [
    [1, "涙 one of them", "田所あずさ", 0],
    [2, "1HOPE SNIPER", "田所あずさ", 0],
    [3, "ストーリーテラー", "田所あずさ", 0],
    [4, "ギミーシェルター・ブライトネス", "田所あずさ", 0],
    [5, "スーパースタールーザー (So What? mix)", "田所あずさ", 0],
    [6, "Pajama KINGDOM", "田所あずさ", 0],
    [7, "そう上手くいかないものです。", "田所あずさ", 0],
    [8, "DEAREST DROP", "田所あずさ", 1],
    [9, "Crying", "田所あずさ", 0],
    [10, "僕は空を飛べない", "田所あずさ", 0],
    [11, "Aiming for Utopia", "田所あずさ", 0],
    [12, "I can’t live without you.", "田所あずさ", 0],
    [13, "運命ジレンマ", "田所あずさ", 0],
    [14, "ころあるき", "田所あずさ", 0],
]
links = ["https://beta.musicbrainz.org/release/fc70d26d-a51e-429d-89f0-634d8f51aded", "https://vgmdb.net/album/69459"]

[ee25994b16a472728d0b82a18c789314]
catalognumber = "LACA-35659"
date = "2017-10-25"
album = "So What? / 田所あずさ Disc 2 (Blu-ray)"
tracks = [
    [1, "純真Always", "田所あずさ", 0],
    [2, "キセキ", "田所あずさ", 0],
    [3, "Fighter’s high", "田所あずさ", 0],
    [4, "MC1", "田所あずさ", 0],
    [5, "あおぞら", "田所あずさ", 0],
    [6, "Straight Forward", "田所あずさ", 0],
    [7, "アンソリティア", "田所あずさ", 0],
    [8, "MC2", "田所あずさ", 0],
    [9, "Cherish", "田所あずさ", 0],
    [10, "世界が終わったあとの夜", "田所あずさ", 0],
    [11, "MC3", "田所あずさ", 0],
    [12, "孤独な惑星", "田所あずさ", 0],
    [13, "ALERT from THE END", "田所あずさ", 0],
    [14, "英雄なんていない", "田所あずさ", 0],
    [15, "spit out", "田所あずさ", 0],
    [16, "1HOPE SNIPER", "田所あずさ", 0],
    [17, "Come on, A–Z!!(before the CUE) (Encore)", "田所あずさ", 0],
    [18, "It’s my CUE. (Encore)", "田所あずさ", 0],
    [19, "MC4 (Encore)", "田所あずさ", 0],
    [20, "Boom! Boom! (Encore)", "田所あずさ", 0],
]
links = ["https://beta.musicbrainz.org/release/fc70d26d-a51e-429d-89f0-634d8f51aded", "https://vgmdb.net/album/69459"]

[ef3640526af87a65415040dc2afefd94]
catalognumber = "KAXA-7505CD"
date = "2017-10-25"
album = "終末なにしてますか?忙しいですか?救ってもらっていいですか? スペシャルオーディオドラマ5 アイセア"
tracks = [
    [1, "アイセア", "", 1],
]
links = ["https://vgmdb.net/album/72229"]

[8b0fe4aaf6979c7ebec2c10e7ca4a921]
catalognumber = "KAXA-7506CD"
date = "2017-11-29"
album = "終末なにしてますか?忙しいですか?救ってもらっていいですか? スペシャルオーディオドラマ6 巣食ってもらっていいですか?"
tracks = [
    [1, "巣食ってもらっていいですか?", "", 1],
]
links = ["https://vgmdb.net/album/73050"]

[ca762dc8c0de7e33e60ca3e39a6031ab]
catalognumber = "LACA-35723"
date = "2018-04-25"
album = "Lonely Queen's Liberation Party / TRUE [Limited Edition] Disc 1 (CD) [LACA-35723]"
tracks = [
    [1, "Lonely Queen’s Liberation Party", "TRUE", 0],
    [2, "Sincerely", "TRUE", 0],
    [3, "次の僕へ", "TRUE", 0],
    [4, "分身", "TRUE", 0],
    [5, "終わりたい世界", "TRUE", 0],
    [6, "BUTTERFLY EFFECTOR", "TRUE", 0],
    [7, "JUMPIN’", "TRUE", 0],
    [8, "Roadmap", "TRUE", 0],
    [9, "フロム", "TRUE", 1],
    [10, "酸素", "TRUE", 0],
    [11, "耳恋ミュージック", "TRUE", 0],
    [12, "サンドリヨン", "TRUE", 0],
    [13, "パズル", "TRUE", 0],
    [14, "Anchors Step", "TRUE", 0],
]
links = ["https://beta.musicbrainz.org/release/b3811c09-f859-4033-a41b-6c9dca869435", "https://vgmdb.net/album/74815"]

[f140951da68d9ef78766056bcf248a6a]
catalognumber = "LACA-35723"
date = "2018-04-25"
album = "Lonely Queen's Liberation Party / TRUE [Limited Edition] Disc 2 (Blu-ray) [LAPD-1495]"
tracks = [
    [1, "Rainbow The Daydream", "TRUE", 0],
    [2, "サウンドスケープ", "TRUE", 0],
    [3, "アイワナビ", "TRUE", 0],
    [4, "RIPTIDE", "TRUE", 0],
    [5, "鍵のない鳥籠", "TRUE", 0],
    [6, "ヒカリ", "TRUE", 0],
    [7, "キネマ", "TRUE", 1],
    [8, "海底のお城", "TRUE", 0],
    [9, "Dear answer", "TRUE", 0],
    [10, "STEEL –鉄血の絆–", "TRUE", 0],
    [11, "飛竜の騎士", "TRUE", 0],
    [12, "グレースケール", "TRUE", 0],
    [13, "ボイスグライダー", "TRUE", 0],
    [14, "UNISONIA", "TRUE", 0],
    [15, "Divine Spell", "TRUE", 0],
    [16, "BUTTERFLY EFFECTOR", "TRUE", 0],
    [17, "カレイドスコープ", "TRUE", 0],
    [18, "フロム", "TRUE", 1],
    [19, "TRUE COLORS –ENCORE–", "TRUE", 0],
    [20, "DREAM SOLISTER –ENCORE–", "TRUE", 0],
    [21, "サウンドスケープ –ENCORE–", "TRUE", 0],
]
links = ["https://beta.musicbrainz.org/release/b3811c09-f859-4033-a41b-6c9dca869435", "https://vgmdb.net/album/74815"]

[dc445852e4f1bb945176eaf0a9316b8a]
catalognumber = "LACA-15723"
date = "2018-04-25"
album = "Lonely Queen's Liberation Party / TRUE"
tracks = [
    [1, "Lonely Queen’s Liberation Party", "TRUE", 0],
    [2, "Sincerely", "TRUE", 0],
    [3, "次の僕へ", "TRUE", 0],
    [4, "分身", "TRUE", 0],
    [5, "終わりたい世界", "TRUE", 0],
    [6, "BUTTERFLY EFFECTOR", "TRUE", 0],
    [7, "JUMPIN’", "TRUE", 0],
    [8, "Roadmap", "TRUE", 0],
    [9, "フロム", "TRUE", 1],
    [10, "酸素", "TRUE", 0],
    [11, "耳恋ミュージック", "TRUE", 0],
    [12, "サンドリヨン", "TRUE", 0],
    [13, "パズル", "TRUE", 0],
    [14, "Anchors Step", "TRUE", 0],
]
links = ["https://beta.musicbrainz.org/release/ae771a0b-bcff-435e-b96b-4a06b2cedbe2", "https://vgmdb.net/album/74816"]

[622c96562274cd75f7705f6bec50f816]
catalognumber = "MHCL-30539"
date = "2018-10-24"
album = "山田タマル ALL-TIME BEST とっくに愛してる"
tracks = [
    [1, "My Brand New Eden", "", 0],
    [2, "秘密の静寂", "", 0],
    [3, "恋の景色", "", 0],
    [4, "手", "", 0],
    [5, "さよならドミノ", "", 0],
    [6, "あなたになら言える秘密のこと", "", 0],
    [7, "A Beautiful Day", "", 0],
    [8, "Love you ROSE", "", 0],
    [9, "孤独な狩人", "", 0],
    [10, "どんどんどこまでも", "", 0],
    [11, "愛のブーケ～Arome de l'amour～(Bossa Ver.)", "", 0],
    [12, "Always in my heart", "", 1],
    [13, "Ever be my love", "", 1],
    [14, "祈り", "", 0],
    [15, "とっくに愛してる", "", 0],
    [16, "Even...if", "", 0],
    [17, "yes", "", 0],
]
links = ["https://vgmdb.net/album/80573"]

[0ca3858a1e1d0635eccc3b81650d87c4]
catalognumber = "LACA-19058~9"
date = "2025-02-26"
album = "TRUE the BEST / TRUE Disc 1 [LACA-19058]"
tracks = [
    [1, "TRUE", "TRUE", 0],
    [2, "UNISONIA", "TRUE", 0],
    [3, "はじまりの翼", "TRUE", 0],
    [4, "TWIN BIRD", "TRUE", 0],
    [5, "ailes", "TRUE", 0],
    [6, "DREAM SOLISTER", "TRUE", 0],
    [7, "Dear answer", "TRUE", 0],
    [8, "Joy Heart", "TRUE", 0],
    [9, "飛竜の騎士", "TRUE", 0],
    [10, "STEEL -鉄血の絆-", "TRUE", 0],
    [11, "Divine Spell", "TRUE", 0],
    [12, "サウンドスケープ", "TRUE", 0],
    [13, "Rainbow The Daydream", "TRUE", 0],
    [14, "フロム", "TRUE", 1],
    [15, "BUTTERFLY EFFECTOR", "TRUE", 0],
]
links = ["https://beta.musicbrainz.org/release/06306ef5-c215-4988-9949-8036bea4c8b8", "https://vgmdb.net/album/161989"]

[6bb1ed1b43863bcc9bbfd825b4304360]
catalognumber = "LACA-19058~9"
date = "2025-02-26"
album = "TRUE the BEST / TRUE Disc 2 [LACA-19059]"
tracks = [
    [1, "Sincerely", "TRUE", 0],
    [2, "Lonely Queen's Liberation Party", "TRUE", 0],
    [3, "Another colony", "TRUE", 0],
    [4, "Blast!", "TRUE", 0],
    [5, "WILL", "TRUE", 0],
    [6, "Storyteller", "TRUE", 0],
    [7, "MUSIC", "TRUE", 0],
    [8, "Happy encount", "TRUE", 0],
    [9, "rebind", "TRUE", 0],
    [10, "アンサンブル", "TRUE", 0],
    [11, "ReCoda", "TRUE", 0],
    [12, "ブルーデイズ", "TRUE", 0],
    [13, "フローズン", "TRUE", 0],
    [14, "Unsung ballad", "TRUE", 0],
    [15, "DelighT", "TRUE", 0],
]
links = ["https://beta.musicbrainz.org/release/e8f5e1a2-444e-4acf-bef9-b70737040b5e", "https://vgmdb.net/album/161989"]
