[939273c452d2053e9471e718a91896dd]
catalognumber = "SVWC-7901"
date = "2012-10-24"
album = "happy endings / 花澤香菜"
tracks = [
    [1, "happy endings", "花澤香菜", 1],
    [2, "too late for chocolate?", "花澤香菜", 1],
    [3, "trick or treat!", "花澤香菜", 1],
    [4, "happy endings (Instrumental)", "花澤香菜", 1],
]
links = ["https://beta.musicbrainz.org/release/09d60d3e-a37f-4b87-bb2e-610a81c4657f", "https://vgmdb.net/album/34881"]

[b659cf9a54ed33d5105563c8dfc9d79e]
catalognumber = "SVWC-7899~900"
date = "2012-10-24"
album = "happy endings / 花澤香菜 Vocal"
tracks = [
    [1, "happy endings", "花澤香菜", 1],
    [2, "too late for chocolate?", "花澤香菜", 1],
    [3, "trick or treat!", "花澤香菜", 1],
    [4, "happy endings (Instrumental)", "花澤香菜", 1],
]
links = ["https://beta.musicbrainz.org/release/03d57274-9e7d-4e3b-9530-8e6fa784b269", "https://vgmdb.net/album/34880"]

[be70bb803d595b3fee18a582010652f7]
catalognumber = "SVWC-7899~900"
date = "2012-10-24"
album = "happy endings / 花澤香菜 Video"
tracks = [
    [1, "happy endings (Movie clip)", "花澤香菜", 1],
]
links = ["https://beta.musicbrainz.org/release/1a0bb7d4-daa2-403b-a37a-acb486512b40", "https://vgmdb.net/album/34880"]

[eaffe1e3cdd55f45738bf91802a60c0f]
catalognumber = "ESCL-3986"
date = "2012-11-28"
album = "Spirit Inspiration / Nothing's Carved In Stone [期間生産限定盤]"
tracks = [
    [1, "Spirit Inspiration", "Nothing’s Carved In Stone", 1],
    [2, "Spirit Inspiration -アニメバージョン-", "Nothing’s Carved In Stone", 1],
]
links = ["https://beta.musicbrainz.org/release/1b604d86-bbd7-4022-aafe-e9c7835df426", "https://vgmdb.net/album/36286"]

[9b13d500be52ebd06c599b6241645a80]
catalognumber = "ESCL-3985"
date = "2012-11-28"
album = "Spirit Inspiration / Nothing's Carved In Stone"
tracks = [
    [1, "Spirit Inspiration", "Nothing’s Carved In Stone", 1],
    [2, "Lighthouse", "Nothing’s Carved In Stone", 0],
    [3, "BLUE SHADOW", "Nothing’s Carved In Stone", 0],
]
links = ["https://beta.musicbrainz.org/release/a4736a50-6cbd-41a6-b606-a60119965df8", "https://vgmdb.net/album/36285"]

[3a12ee9cb8ee1ef5d3b50593ce6aee65]
catalognumber = "ANZX-6952"
date = "2012-12-26"
album = "絶園のテンペスト キャラクターソングCD 吉野＆真広"
tracks = [
    [1, "嵐のラプソディ", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
    [2, "嵐のラプソディ (Off Vocal Version)", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
]
links = ["https://beta.musicbrainz.org/release/f4ec07ca-8fba-4a4e-bf01-ef07b45179ee", "https://vgmdb.net/album/35726"]

[bc75c6b61210d8f48d5cd5cd4b848622]
catalognumber = "SECL-1271"
date = "2013-01-30"
album = "僕たちの歌 / 佐香智久"
tracks = [
    [1, "僕たちの歌", "佐香智久", 1],
    [2, "僕たちの歌 ～アニメサイズver.～", "佐香智久", 1],
    [3, "僕たちの歌 ～Off Vocal～", "佐香智久", 1],
]
links = ["https://beta.musicbrainz.org/release/6d0259cc-2b10-4e06-9f29-ac2e0c6168a3", "https://vgmdb.net/album/36688"]

[18bcb94254fed583db027406b818c122]
catalognumber = "SECL-1272"
date = "2013-01-30"
album = "僕たちの歌 / 佐香智久"
tracks = [
    [1, "僕たちの歌", "佐香智久", 1],
    [2, "僕たちの歌 ～アニメサイズver.～", "佐香智久", 1],
    [3, "僕たちの歌 ～Off Vocal～", "佐香智久", 1],
]
links = ["https://beta.musicbrainz.org/release/b07732a5-f7e6-4041-b493-076b014a33ff", "https://vgmdb.net/album/36689"]

[01625c0823e5c972a26f964c051f0e39]
catalognumber = "SECL-1268~9"
date = "2013-01-30"
album = "僕たちの歌 / 佐香智久 Disc 1 (CD) [SECL-1268]"
tracks = [
    [1, "僕たちの歌", "佐香智久", 1],
    [2, "月の裏側", "佐香智久", 0],
    [3, "初恋", "佐香智久", 0],
    [4, "僕たちの歌 ～Off Vocal～", "佐香智久", 1],
    [5, "月の裏側 ～Off Vocal～", "佐香智久", 0],
    [6, "初恋 ～Off Vocal～", "佐香智久", 0],
]
links = ["https://beta.musicbrainz.org/release/74853562-5b65-4577-ab86-9b0ae7774eb8", "https://vgmdb.net/album/36686"]

[acd37a2152c6f3f1a1a09e1fbaaf8204]
catalognumber = "SECL-1268~9"
date = "2013-01-30"
album = "僕たちの歌 / 佐香智久 Disc 2 (DVD) [SECL-1269]"
tracks = [
    [1, "僕たちの歌 (Video Clip 智久 Only Ver.)", "", 1],
]
links = ["https://vgmdb.net/album/36686"]

[2491160ac3682e684d83c9192f7878bf]
catalognumber = "SECL-1270"
date = "2013-01-30"
album = "僕たちの歌 / 佐香智久"
tracks = [
    [1, "僕たちの歌", "佐香智久", 1],
    [2, "月の裏側", "佐香智久", 0],
    [3, "初恋", "佐香智久", 0],
    [4, "僕たちの歌 ～Off Vocal～", "佐香智久", 1],
    [5, "月の裏側 ～Off Vocal～", "佐香智久", 0],
    [6, "初恋 ～Off Vocal～", "佐香智久", 0],
]
links = ["https://beta.musicbrainz.org/release/5eb6300c-59b4-40ba-b8b9-90f91f6e7374", "https://vgmdb.net/album/36687"]

[35f410e900217c83f4e6fb1044c66cd5]
catalognumber = "DFCL-1979"
date = "2013-02-13"
album = "大好きなのに / Kylee"
tracks = [
    [1, "大好きなのに", "Kylee", 1],
    [2, "Anywhere", "Kylee", 1],
    [3, "大好きなのに [Less Vocal]", "Kylee", 1],
]
links = ["https://beta.musicbrainz.org/release/21f3c9de-bebc-412a-81f4-441f201e9610", "https://vgmdb.net/album/36778"]

[b0c08c068c4dfcd609024fb42816fdee]
catalognumber = "DFCL-1980"
date = "2013-02-13"
album = "大好きなのに / Kylee"
tracks = [
    [1, "大好きなのに", "Kylee", 1],
    [2, "Anywhere", "Kylee", 1],
    [3, "大好きなのに [TV Size]", "Kylee", 1],
    [4, "大好きなのに [Less Vocal]", "Kylee", 1],
]
links = ["https://beta.musicbrainz.org/release/d1e1976a-0984-4da8-af61-a9fa2e851c97", "https://vgmdb.net/album/36779"]

[7586389d8dd09fc33993660dc5215593]
catalognumber = "SVWC-7929"
date = "2013-02-20"
album = "claire / 花澤香菜"
tracks = [
    [1, "青い鳥", "花澤香菜", 0],
    [2, "Just The Way You Are", "花澤香菜", 0],
    [3, "初恋ノオト", "花澤香菜", 0],
    [4, "ライブラリーで恋をして!", "花澤香菜", 0],
    [5, "星空☆ディスティネーション", "花澤香菜", 0],
    [6, "スタッカート", "花澤香菜", 0],
    [7, "melody", "花澤香菜", 0],
    [8, "Ring a Bell", "花澤香菜", 0],
    [9, "Silent Snow", "花澤香菜", 0],
    [10, "シグナルは恋ゴコロ", "花澤香菜", 0],
    [11, "新しい世界の歌", "花澤香菜", 0],
    [12, "眠るサカナ", "花澤香菜", 0],
    [13, "おやすみ、また明日", "花澤香菜", 0],
    [14, "happy endings", "花澤香菜", 1],
]
links = ["https://beta.musicbrainz.org/release/a1eaac7d-76d0-4016-a402-d47361391ba8", "https://vgmdb.net/album/55285"]

[ca202ebc44b047c928dbc52e9343cf4e]
catalognumber = "ANZX-6954"
date = "2013-02-27"
album = "絶園のテンペスト Original Soundtrack vol.1"
tracks = [
    [1, "絶園", "大島ミチル", 1],
    [2, "追憶", "大島ミチル", 1],
    [3, "焦燥", "大島ミチル", 1],
    [4, "邂逅", "大島ミチル", 1],
    [5, "悪寒", "大島ミチル", 1],
    [6, "出現", "大島ミチル", 1],
    [7, "崩壊", "大島ミチル", 1],
    [8, "取引", "大島ミチル", 1],
    [9, "忽然", "大島ミチル", 1],
    [10, "懐旧", "大島ミチル", 1],
    [11, "左門", "大島ミチル", 1],
    [12, "夏村", "大島ミチル", 1],
    [13, "衝突", "大島ミチル", 1],
    [14, "急変", "大島ミチル", 1],
    [15, "疑念", "大島ミチル", 1],
]
links = ["https://beta.musicbrainz.org/release/fbd47e26-872c-4354-9d1b-ad8f730e6e86", "https://vgmdb.net/album/36936"]

[5e5d7ecfccf030f5616b5379464f43a3]
catalognumber = "ANZX-6956"
date = "2013-03-27"
album = "絶園のテンペスト 朗読CD「ハムレット」"
tracks = [
    [1, "冒頭", "", 1],
    [2, "再会", "", 1],
    [3, "恋人", "", 1],
    [4, "苦悩", "", 1],
    [5, "確証", "", 1],
    [6, "王妃", "", 1],
    [7, "追放", "", 1],
    [8, "葬儀", "", 1],
    [9, "決闘", "", 1],
]
links = ["https://vgmdb.net/album/38055"]

[ff9d39603e348d1ccfc204f590afd533]
catalognumber = "ANZX-6958"
date = "2013-04-24"
album = "絶園のテンペスト キャラクターソングCD 吉野＆真広"
tracks = [
    [1, "星の船", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
    [2, "星の船 (Off Vocal Version)", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
]
links = ["https://beta.musicbrainz.org/release/58c59ac9-43ae-4e43-be31-81009fddf42d", "https://vgmdb.net/album/38642"]

[e6fb0057baefc0d282fad2b2848cee17]
catalognumber = "ANZX-6960"
date = "2013-05-22"
album = "絶園のテンペスト Original Soundtrack vol.2"
tracks = [
    [1, "敗北", "大島ミチル", 1],
    [2, "奇異", "大島ミチル", 1],
    [3, "安堵", "大島ミチル", 1],
    [4, "心覚", "大島ミチル", 1],
    [5, "希望", "大島ミチル", 1],
    [6, "過去", "大島ミチル", 1],
    [7, "復活", "大島ミチル", 1],
    [8, "終末", "大島ミチル", 1],
    [9, "鎖部", "大島ミチル", 1],
    [10, "TEMPEST", "大島ミチル", 1],
]
links = ["https://beta.musicbrainz.org/release/d0308271-1266-43e3-902e-ae14fcffa58e", "https://vgmdb.net/album/38643"]

[5585004c7aed5baa870aa2f16f392115]
catalognumber = "ANZX-6966"
date = "2013-08-21"
album = "絶園のテンペスト CHARACTER SONG VOL.3"
tracks = [
    [1, "ポジティカ", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
    [2, "ポジティカ (Off Vocal Version)", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
]
links = ["https://beta.musicbrainz.org/release/3f41db52-f6d9-4bfd-b3b6-6b2a6bf2d2d8"]

[0463789867dbd0a78881b610bdf88c3c]
catalognumber = "ANZX-6968"
date = "2013-09-25"
album = "絶園のテンペスト Original Soundtrack vol.3"
tracks = [
    [1, "変化", "大島ミチル", 1],
    [2, "羽村", "大島ミチル", 1],
    [3, "悪戯", "大島ミチル", 1],
    [4, "奇妙", "大島ミチル", 1],
    [5, "空転", "大島ミチル", 1],
    [6, "喜楽", "大島ミチル", 1],
    [7, "錯綜", "大島ミチル", 1],
    [8, "葉風", "大島ミチル", 1],
    [9, "推理", "大島ミチル", 1],
    [10, "邂逅変奏曲 (舞姫ver)", "大島ミチル", 1],
    [11, "愛花", "大島ミチル", 1],
]
links = ["https://beta.musicbrainz.org/release/ec327ad1-7eff-437a-9c0d-216b73e4ac84", "https://vgmdb.net/album/41246"]

[cdcfb3088f1df42e01a1fcb3202714bd]
catalognumber = "ANZX-6974"
date = "2013-12-25"
album = "絶園のテンペスト CHARACTER SONG VOL.4"
tracks = [
    [1, "未来の蕾", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
    [2, "未来の蕾 (Off Vocal Version)", "滝川吉野(内山昂輝)・不破真広(豊永利行)", 1],
]
links = ["https://beta.musicbrainz.org/release/1ff00728-791b-45ba-826c-d2fe4a397273"]

[fbf32443a909bc56f68c18fd39a1d261]
catalognumber = "VVCL-1450~1"
date = "2019-05-29"
album = "さこともベスト / 佐香智久 Disc 1 (CD) [VVCL-1450]"
tracks = [
    [1, "愛言葉", "", 0],
    [2, "ずっと", "", 0],
    [3, "はんぶんこ", "", 0],
    [4, "君恋カレンダー", "", 0],
    [5, "僕たちの歌", "", 1],
    [6, "バイバイ", "", 0],
    [7, "カラフルワールド", "", 0],
    [8, "魔法の夜と不思議なワルツ", "", 0],
    [9, "少年とロボット", "", 0],
    [10, "ゲッタバンバン", "", 0],
    [11, "いつか君はそいつと別れるに決まってる", "", 0],
    [12, "フローリア", "", 0],
    [13, "不完全モノクローグ", "", 0],
]
links = ["https://vgmdb.net/album/85918"]

[27e18d5d81e4ec9457c64b72b3d1a9dd]
catalognumber = "VVCL-1450~1"
date = "2019-05-29"
album = "さこともベスト / 佐香智久 Disc 2 (DVD) [VVCL-1451]"
tracks = [
    [1, "愛言葉", "", 0],
    [2, "ずっと", "", 0],
    [3, "はんぶんこ", "", 0],
    [4, "君恋カレンダー", "", 0],
    [5, "僕たちの歌", "", 1],
    [6, "バイバイ", "", 0],
    [7, "カラフルワールド", "", 0],
    [8, "魔法の夜と不思議なワルツ", "", 0],
    [9, "少年とロボット", "", 0],
    [10, "ゲッタバンバン", "", 0],
    [11, "いつか君はそいつと別れるに決まってる", "", 0],
    [12, "フローリア", "", 0],
    [13, "不完全モノクローグ", "", 0],
]
links = ["https://vgmdb.net/album/85918"]

[a9805f2d0524c65764a1f6ce3f5bf96a]
catalognumber = "VVCL-1452"
date = "2019-05-29"
album = "さこともベスト / 佐香智久"
tracks = [
    [1, "愛言葉", "", 0],
    [2, "ずっと", "", 0],
    [3, "はんぶんこ", "", 0],
    [4, "君恋カレンダー", "", 0],
    [5, "僕たちの歌", "", 1],
    [6, "バイバイ", "", 0],
    [7, "カラフルワールド", "", 0],
    [8, "魔法の夜と不思議なワルツ", "", 0],
    [9, "少年とロボット", "", 0],
    [10, "ゲッタバンバン", "", 0],
    [11, "いつか君はそいつと別れるに決まってる", "", 0],
    [12, "フローリア", "", 0],
    [13, "不完全モノクローグ", "", 0],
]
links = ["https://vgmdb.net/album/85917"]
