[b24dd8700c0748253d0f977fea89ae84]
catalognumber = "GNCA-0009"
date = "2005-03-09"
album = "苺ましまろ Chara-CD ① 千佳"
tracks = [
    [1, "オープニングトーク（DJ：美羽）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [2, "千佳への10の質問（出題者：美羽）", "千佳(千葉紗子)、美羽(折笠富美子)", 1],
    [3, "「ソレ」は素敵なショウタイム", "千佳(千葉紗子)", 2],
    [4, "お悩み相談（当番：茉莉）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [5, "ミニドラマ「作戦会議」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [6, "おまけコーナー「アナの英会話講座」", "千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [7, "「ソレ」は素敵なショウタイム (JAM MIX)", "千佳(千葉紗子)", 1],
]
links = ["https://beta.musicbrainz.org/release/04ba6c99-777a-459d-acf9-2528edfcc4f0", "https://vgmdb.net/album/69959"]

[f06119c05f24cc656afda501c00f63e6]
catalognumber = "GNCA-0010"
date = "2005-04-06"
album = "苺ましまろ Chara-CD ② 茉莉"
tracks = [
    [1, "オープニングトーク（DJ：千佳）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [2, "茉莉への10の質問（出題者：千佳）", "茉莉(川澄綾子)、千佳(千葉紗子)", 1],
    [3, "ミルクをこぼして", "茉莉(川澄綾子)", 2],
    [4, "お悩み相談（当番：アナ）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [5, "ミニドラマ「しつけ」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [6, "おまけコーナー「美羽の大予言」", "千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子", 1],
    [7, "ミルクをこぼして (CHIFFON MIX)", "茉莉(川澄綾子)", 1],
]
links = ["https://beta.musicbrainz.org/release/7ba2f539-d298-4184-9139-f8fef84ce069", "https://vgmdb.net/album/69960"]

[7552d60d3a33603fb2ede364cfd26f35]
catalognumber = "GNCA-0011"
date = "2005-05-11"
album = "苺ましまろ Chara-CD ③ アナ"
tracks = [
    [1, "オープニングトーク（DJ：茉莉）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [2, "アナへの10の質問（出題者：茉莉）", "アナ(能登麻美子)、茉莉(川澄綾子)", 1],
    [3, "Made in 女の子", "アナ(能登麻美子)", 2],
    [4, "お悩み相談（当番：千佳）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [5, "ミニドラマ「すりすり」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [6, "おまけコーナー「茉莉の日記」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [7, "Made in 女の子 (MILK MIX)", "アナ(能登麻美子)", 1],
]
links = ["https://beta.musicbrainz.org/release/9e9b25fc-1c35-4b1a-b0f4-d61d85dd3fea", "https://vgmdb.net/album/69961"]

[fa678b7616c8c1b0dd80398153d0e1a6]
catalognumber = "GNCA-0012"
date = "2005-06-08"
album = "苺ましまろ Chara-CD ④ 美羽"
tracks = [
    [1, "オープニングトーク（DJ：アナ）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [2, "美羽への10の質問（出題者：アナ）", "美羽(折笠富美子)、アナ(能登麻美子)", 1],
    [3, "おさんぽ協奏曲", "美羽(折笠富美子)", 1],
    [4, "お悩み相談（当番：美羽）", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [5, "ミニドラマ「げろっぴー」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [6, "おまけコーナー「千佳のなんかやります」", "千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [7, "おさんぽ協奏曲 (PARFAIT MIX)", "美羽(折笠富美子)", 1],
]
links = ["https://beta.musicbrainz.org/release/5f34e2af-0cf9-4497-bd0e-dd76d7498557", "https://vgmdb.net/album/69962"]

[ee45b7556a65be97f91cde2087ffc1af]
catalognumber = "FCCM-0072"
date = "2005-07-22"
album = "苺ましまろ DRAMA CD Volume 1"
tracks = [
    [1, "メイド伊藤家の巻", "", 1],
    [2, "マンガの巻", "", 1],
    [3, "タイムカプセルの巻", "", 1],
    [4, "魔法少女の巻", "", 1],
    [5, "伸恵先生の巻", "", 1],
    [6, "ガラムマサラの巻", "", 1],
]
links = ["https://vgmdb.net/album/69963"]

[e4a7fe49567e5acb42548ada12c2b5d0]
catalognumber = "GNCA-0013"
date = "2005-07-27"
album = "TVアニメ「苺ましまろ」OPテーマ いちごコンプリート"
tracks = [
    [1, "いちごコンプリート", "千佳＠千葉紗子、美羽＠折笠富美子、茉莉＠川澄綾子、アナ＠能登麻美子", 2],
    [2, "ゆらゆらDays", "伸恵＠生天目仁美", 1],
    [3, "いちごコンプリート（Jelly mix）", "千佳＠千葉紗子、美羽＠折笠富美子、茉莉＠川澄綾子、アナ＠能登麻美子", 1],
    [4, "いちごコンプリート（オリジナルカラオケ）", "千佳＠千葉紗子、美羽＠折笠富美子、茉莉＠川澄綾子、アナ＠能登麻美子", 1],
    [5, "ゆらゆらDays（オリジナルカラオケ）", "伸恵＠生天目仁美", 1],
]
links = ["https://beta.musicbrainz.org/release/98f5f959-ee37-499b-8f23-2bd0e56f0b9b", "https://vgmdb.net/album/64538"]

[7926ea35b568becc3ae5b3c02d292671]
catalognumber = "GNCA-1036"
date = "2005-08-24"
album = "苺ましまろ Toy-CD ①"
tracks = [
    [1, "CDドラマ#1「伸恵改造計画」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [2, "ばってんとまる", "千佳(千葉紗子)、美羽(折笠富美子)", 1],
    [3, "CDドラマ#2「漂流日和」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [4, "まーぶる夢模様", "茉莉(川澄綾子)、アナ(能登麻美子)", 2],
]
links = ["https://beta.musicbrainz.org/release/35be1f07-e8b0-4bc2-b3a3-d127a5464c92", "https://vgmdb.net/album/69969"]

[d546c52e3c8624dec6a5aa818b657823]
catalognumber = "FCCM-0073"
date = "2005-08-24"
album = "苺ましまろ DRAMA CD Volume 2"
tracks = [
    [1, "美羽の旅立ちの巻", "", 1],
    [2, "桃子か桃代かモモンガの巻", "", 1],
    [3, "浦島花子の巻", "", 1],
    [4, "りゅうたまの巻", "", 1],
    [5, "夜明けの牛乳の巻", "", 1],
    [6, "白雪ウォーズの巻", "", 1],
    [7, "美羽の帰還の巻", "", 1],
]
links = ["https://vgmdb.net/album/69965"]

[6c778bfea81a5f0dc5881f5d0bbc702e]
catalognumber = "GNCA-1057"
date = "2005-09-14"
album = "Flower / 折笠富美子"
tracks = [
    [1, "Flower", "折笠富美子", 1],
    [2, "答えは胸の中にある", "折笠富美子", 1],
    [3, "嘘つきなあなたへ", "折笠富美子", 1],
    [4, "クラス・メイト", "折笠富美子", 1],
    [5, "音の花", "折笠富美子", 1],
    [6, "-18cm～いちあまりの裏側～", "折笠富美子", 1],
    [7, "さくらピエロ", "折笠富美子", 1],
    [8, "勝算アリ", "折笠富美子", 1],
    [9, "39.5°C", "折笠富美子", 1],
    [10, "シアワセの波", "折笠富美子", 1],
    [11, "ムシとフラワー", "折笠富美子", 1],
]
links = ["https://beta.musicbrainz.org/release/567920ed-2b8a-34d2-9070-66d8551fb58b", "https://vgmdb.net/album/64527"]

[e9b637fe9f183c1c3532e40de18f39d5]
catalognumber = "GNCA-1056"
date = "2005-09-14"
album = "Flower / 折笠富美子 [初回限定盤] Vocal"
tracks = [
    [1, "Flower", "折笠富美子", 1],
    [2, "答えは胸の中にある", "折笠富美子", 1],
    [3, "嘘つきなあなたへ", "折笠富美子", 1],
    [4, "クラス・メイト", "折笠富美子", 1],
    [5, "音の花", "折笠富美子", 1],
    [6, "-18cm～いちあまりの裏側～", "折笠富美子", 1],
    [7, "さくらピエロ", "折笠富美子", 1],
    [8, "勝算アリ", "折笠富美子", 1],
    [9, "39.5°C", "折笠富美子", 1],
    [10, "シアワセの波", "折笠富美子", 1],
    [11, "ムシとフラワー", "折笠富美子", 1],
]
links = ["https://beta.musicbrainz.org/release/97273709-f53e-4d60-8241-99d1be498755", "https://vgmdb.net/album/64526"]

[d5818ef0aef56b8917f6b0271eeeadf4]
catalognumber = "GNCA-1056"
date = "2005-09-14"
album = "Flower / 折笠富美子 [初回限定盤] Video"
tracks = [
    [1, "「Flower」Music Video", "", 0],
    [2, "Making Scene", "", 0],
]
links = ["https://vgmdb.net/album/64526"]

[1c4df3cd071e34c4836a29d0c5cac11c]
catalognumber = "GNCA-1035"
date = "2005-09-22"
album = "苺ましまろ オリジナルサウンドトラック"
tracks = [
    [1, "いちごコンプリート (TVサイズ)", "千佳＠千葉紗子、美羽＠折笠富美子、茉莉＠川澄綾子、アナ＠能登麻美子", 1],
    [2, "メインテーマ", "渡辺剛", 1],
    [3, "メンバー紹介……的な", "渡辺剛", 1],
    [4, "放課後", "渡辺剛", 1],
    [5, "おウチに帰ろ。", "渡辺剛", 1],
    [6, "アコーディオンです……", "渡辺剛", 1],
    [7, "転校デビュー", "渡辺剛", 1],
    [8, "お茉莉!", "渡辺剛", 1],
    [9, "悪だくみ", "渡辺剛", 1],
    [10, "おも〜い雰囲気", "渡辺剛", 1],
    [11, "耳障りなぎた〜", "渡辺剛", 1],
    [12, "ノ〜ンビリなテーマ", "渡辺剛", 1],
    [13, "アナん家", "渡辺剛", 1],
    [14, "アップアップなテーマ", "渡辺剛", 1],
    [15, "あいきゃんと、すぴーくいん ぐりっしゅ!", "渡辺剛", 1],
    [16, "ねぇ、太……", "渡辺剛", 1],
    [17, "ちーちゃん家", "渡辺剛", 1],
    [18, "そいね", "渡辺剛", 1],
    [19, "ホッとするテーマ", "渡辺剛", 1],
    [20, "かわいいは、正義!", "渡辺剛", 1],
    [21, "クラス・メイト (TVサイズ)", "折笠富美子", 1],
]
links = ["https://beta.musicbrainz.org/release/cc654967-31ab-47f9-9ad3-4b4efb027f6e", "https://vgmdb.net/album/64150"]

[7fb15a613995016adfcbadd2485d3662]
catalognumber = "FCCM-0074"
date = "2005-09-22"
album = "苺ましまろ DRAMA CD Volume 3"
tracks = [
    [1, "伸恵のひとりごと・春の巻", "", 1],
    [2, "春のましまろの巻", "", 1],
    [3, "伸恵のひとりごと・夏の巻", "", 1],
    [4, "夏のましまろの巻", "", 1],
    [5, "伸恵のひとりごと・秋の巻", "", 1],
    [6, "秋のましまろの巻", "", 1],
    [7, "伸恵のひとりごと・冬の巻", "", 1],
    [8, "冬のましまろの巻", "", 1],
    [9, "そして、また春 - の巻", "", 1],
]
links = ["https://vgmdb.net/album/69966"]

[2d544ccc015019b6edac4f555def2b66]
catalognumber = "GNCA-1037"
date = "2005-10-26"
album = "苺ましまろ Toy-CD ②"
tracks = [
    [1, "CDドラマ#1「エレメンタリースクールライフ」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [2, "美少女（ヒロイン）が多すぎる！", "美羽(折笠富美子)、アナ(能登麻美子)", 2],
    [3, "CDドラマ#2「訪問販売の男」", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [4, "坂道ばびゅーん", "千佳(千葉紗子)＆茉莉(川澄綾子)", 2],
    [5, "微青果実（ほろあお かじつ）", "伸恵(生天目仁美)", 2],
    [6, "OMAKE「でっかい者の歌」合唱集", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
]
links = ["https://beta.musicbrainz.org/release/64b5358a-7754-461e-9bde-1de731cb05f1", "https://vgmdb.net/album/69970"]

[ade1655ca257485e0a16199ff287efe6]
catalognumber = "GNCA-1082"
date = "2006-03-29"
album = "苺ましまろ キャラクターソングアルバム"
tracks = [
    [1, "いちごコンプリート", "千佳＠千葉紗子、美羽＠折笠富美子、茉莉＠川澄綾子、アナ＠能登麻美子", 1],
    [2, "微青果実（ほろあおかじつ）", "伸恵(生天目仁美)", 1],
    [3, "ばってんとまる", "千佳(千葉紗子)、美羽(折笠富美子)", 1],
    [4, "「ソレ」は素敵なショウタイム", "千佳(千葉紗子)", 1],
    [5, "まーぶる夢模様", "茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [6, "おさんぽ協奏曲", "美羽(折笠富美子)", 1],
    [7, "ゆらゆらDays", "伸恵＠生天目仁美", 1],
    [8, "坂道ばびゅーん", "千佳(千葉紗子)＆茉莉(川澄綾子)", 1],
    [9, "ミルクをこぼして", "茉莉(川澄綾子)", 1],
    [10, "Made in 女の子", "アナ(能登麻美子)", 1],
    [11, "美少女（ヒロイン）が多すぎる！", "美羽(折笠富美子)、アナ(能登麻美子)", 1],
    [12, "お家に帰ろ", "千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 2],
]
links = ["https://beta.musicbrainz.org/release/1b11381c-1644-43e0-9f72-0f4c6e3d529a", "https://vgmdb.net/album/60711"]

[98931cb27f487e793231136385bb69de]
catalognumber = "53412"
date = "2006-06-20"
album = "Strawberry Marshmallow Original Sound Track"
tracks = [
    [1, "Ichigo Complete (TV Size)", "渡辺剛", 1],
    [2, "Main Theme", "渡辺剛", 1],
    [3, "Introduction of Members… kind of", "渡辺剛", 1],
    [4, "After School", "渡辺剛", 1],
    [5, "Let’s Go Home", "渡辺剛", 1],
    [6, "It’s an Accordion…", "渡辺剛", 1],
    [7, "Debut at the New School", "渡辺剛", 1],
    [8, "O-Matsuri!", "渡辺剛", 1],
    [9, "Scheming", "渡辺剛", 1],
    [10, "A Heavy Atmosphere", "渡辺剛", 1],
    [11, "Annoying Guitar", "渡辺剛", 1],
    [12, "A Leisurely Theme", "渡辺剛", 1],
    [13, "Ana’s Home", "渡辺剛", 1],
    [14, "A Barely-Keeping-Afloat Theme", "渡辺剛", 1],
    [15, "I Can’t Speak English!", "渡辺剛", 1],
    [16, "Have You Gained…", "渡辺剛", 1],
    [17, "Chi-chan’s Home", "渡辺剛", 1],
    [18, "I’ll Sleep Next to You", "渡辺剛", 1],
    [19, "A Soothing Theme", "渡辺剛", 1],
    [20, "Cute Makes Right", "渡辺剛", 1],
    [21, "Classmate (TV Size)", "渡辺剛", 1],
]
links = ["https://beta.musicbrainz.org/release/cd53fefa-2575-4659-8909-e281f2d7f49f", "https://vgmdb.net/album/64151"]

[10a89aaf676e5c2f1ed6884b86887849]
catalognumber = "FCCM-0109"
date = "2006-07-21"
album = "苺ましまろ DRAMA CD Volume 4"
tracks = [
    [1, "誰かがいない月曜日の巻", "", 1],
    [2, "誰かがいない火曜日の巻", "", 1],
    [3, "誰かがいない水曜日の巻", "", 1],
    [4, "誰かがいない木曜日の巻", "", 1],
    [5, "誰かがいない金曜日の巻", "", 1],
    [6, "みんな揃った土曜日の巻", "", 1],
]
links = ["https://vgmdb.net/album/69967"]

[62e734d6a41254b76b4e9688dc58322a]
catalognumber = "GNCA-1096"
date = "2006-08-25"
album = "Hyper Yocomix2"
tracks = [
    [1, "創聖のアクエリオン", "石田燿子", 0],
    [2, "Shangri-La", "石田燿子", 0],
    [3, "くじびきアンバランス", "石田燿子", 0],
    [4, "DANZEN!ふたりはプリキュア(Ver.Max Heart)", "石田燿子", 0],
    [5, "乙女はDO MY BESTでしょ？", "石田燿子", 0],
    [6, "月の呪縛", "石田燿子", 0],
    [7, "焔の扉", "石田燿子", 0],
    [8, "秘密基地", "石田燿子", 0],
    [9, "SUPER LOVE", "石田燿子", 0],
    [10, "いちごコンプリート", "石田燿子", 1],
    [11, "プリンセスはあきらめない", "石田燿子", 0],
    [12, "撲殺天使ドクロちゃん", "石田燿子", 0],
    [13, "ETERNAL BLAZE", "石田燿子", 0],
    [14, "限界バトル", "石田燿子", 0],
    [15, "聖少女領域", "石田燿子", 0],
    [16, "agony", "石田燿子", 0],
    [17, "ルーレット☆ルーレット", "石田燿子", 0],
    [18, "ハッピー☆マテリアル", "石田燿子", 0],
]
links = ["https://beta.musicbrainz.org/release/513bbbc4-b8c2-4570-8026-3d99391a66a1", "https://vgmdb.net/album/21760"]

[4e270d38a4380ca564d1b4f244e346ba]
catalognumber = "FCCM-0110"
date = "2006-08-25"
album = "苺ましまろ DRAMA CD Volume 5"
tracks = [
    [1, "ましまろチャンネル・企画会議その1の巻", "", 1],
    [2, "ましまろチャンネル・アナと茉莉の秘湯めぐりの巻", "", 1],
    [3, "ましまろチャンネル・企画会議その2の巻", "", 1],
    [4, "ましまろチャンネル・子連れコッポラの巻", "", 1],
    [5, "ましまろチャンネル・企画会議その3の巻", "", 1],
    [6, "ましまろチャンネル・千佳のお部屋の巻", "", 1],
    [7, "ましまろチャンネル・企画会議その4の巻", "", 1],
    [8, "ましまろチャンネル・苺戦隊ましまろファイブの巻", "", 1],
    [9, "ましまろチャンネル・企画会議その5の巻", "", 1],
    [10, "ましまろチャンネル・メモリーの記憶の巻", "", 1],
    [11, "いつもの伊藤家の巻", "", 1],
]
links = ["https://vgmdb.net/album/69968"]

[aaa6314fdf5b6bf7118e4db70e9d8194]
catalognumber = "GNCA-1118"
date = "2007-02-23"
album = "苺ましまろ OVA Sweet-CD ①"
tracks = [
    [1, "あっかん berry berry", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 2],
    [2, "四人はアイドル!?", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [3, "フツウはどのこ?", "千佳(千葉紗子)", 1],
    [4, "ご町内クエスト", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [5, "ひぃ・ふぅ・みぃ", "美羽(折笠富美子)", 1],
    [6, "桃源郷", "渡辺剛", 1],
    [7, "かくれんぼ", "渡辺剛", 1],
    [8, "いつもの夕方", "渡辺剛", 1],
    [9, "また明日", "渡辺剛", 1],
    [10, "発射", "渡辺剛", 1],
]
links = ["https://beta.musicbrainz.org/release/6b822bd2-54a8-4782-a37d-2f4a0c6ff2b8", "https://vgmdb.net/album/64540"]

[f1396f0eb2e7fcf215c05c081444fa41]
catalognumber = "GNCA-1119"
date = "2007-04-25"
album = "苺ましまろ OVA Sweet-CD ②"
tracks = [
    [1, "とっさ・デ・Bossa(ボッサ)", "茉莉(川澄綾子)", 1],
    [2, "ましまろファンタジークエスト", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [3, "ぺらぺら is ハレルヤ", "アナ(能登麻美子)", 1],
    [4, "将来の夢", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [5, "夕待ちの風（ショートサイズ）", "折笠富美子", 1],
    [6, "まいにち", "渡辺剛", 1],
    [7, "授業中", "渡辺剛", 1],
    [8, "ネコミミ", "渡辺剛", 1],
    [9, "伸恵のCD", "渡辺剛", 1],
    [10, "踊り子さん", "渡辺剛", 1],
    [11, "いつも。", "渡辺剛", 1],
]
links = ["https://beta.musicbrainz.org/release/71f39afd-9152-4d83-b485-c27eba51babb", "https://vgmdb.net/album/64542"]

[9c638b4c6efa4d526e6564378cc353d0]
catalognumber = "GNCA-1152"
date = "2007-12-21"
album = "うららかeasy / 折笠富美子"
tracks = [
    [1, "Sweetie -うららかmix-", "折笠富美子", 1],
    [2, "starting!", "折笠富美子", 1],
    [3, "SODA 1・2・3", "折笠富美子", 1],
    [4, "夕待ちの風", "折笠富美子", 1],
    [5, "おかっぱちゃん", "折笠富美子", 1],
    [6, "心の輝き", "折笠富美子", 1],
    [7, "yuki-no-hi", "折笠富美子", 2],
    [8, "あなたでなければ", "折笠富美子", 2],
    [9, "テキスタイルPOP", "折笠富美子", 1],
    [10, "brooch", "折笠富美子", 1],
    [11, "ボクノリズム", "折笠富美子", 1],
]
links = ["https://beta.musicbrainz.org/release/7f306a2a-84e3-46e3-a6fa-80cc2889bcca", "https://vgmdb.net/album/64905"]

[5a2c86e65fc28c5677f15d30e1032e44]
catalognumber = "QWCE-00051"
date = "2008-07-02"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 4"
tracks = [
    [1, "トライアングラー", "MAKI", 0],
    [2, "Romantic summer", "Ma15", 0],
    [3, "射手座☆午後九時Don’t be late", "MAKI", 0],
    [4, "甲賀忍法帖", "KANA", 0],
    [5, "I SAY YES", "YURiE", 0],
    [6, "O2〜オー・ツー〜", "NINE", 0],
    [7, "片翼のイカロス", "Ma15", 0],
    [8, "Dancing in the velvet moon", "KANA", 0],
    [9, "暁の車", "CAMRY", 0],
    [10, "why, or why not", "YURiE", 0],
    [11, "SECRET AMBITION", "KANA", 0],
    [12, "YOU", "CAMRY", 0],
    [13, "Shooting Star", "MAKI", 0],
    [14, "clover", "CAMRY", 0],
    [15, "dis-", "MAKI", 0],
    [16, "亡國覚醒カタルシス", "KONEKO PROJECT", 0],
    [17, "明日へのbrilliant road", "YURiE", 0],
    [18, "撲殺天使ドクロちゃん", "Ma15", 0],
    [19, "いちごコンプリート", "Ma15+MAKI", 1],
    [20, "ユーフォリア", "CAMRY", 0],
]
links = ["https://beta.musicbrainz.org/release/4b9e903c-6009-4735-ac6e-3fd2b43e9cb3", "https://vgmdb.net/album/29343"]

[fa1991072f8600dbff042bbbabfbbee8]
catalognumber = "GNCA-0130"
date = "2008-12-25"
album = "「苺ましまろ encore」オープニングテーマ 『苺すぷらっしゅ』 [初回限定盤] Vocal"
tracks = [
    [1, "苺すぷらっしゅ", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 2],
    [2, "ずっと、ずっと(OVAサイズ)", "伊藤伸恵", 1],
    [3, "あっかん berry berry", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
    [4, "いちごコンプリート", "千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 1],
]
links = ["https://beta.musicbrainz.org/release/cebe3f0b-6075-42cf-bf90-06d02e693879", "https://vgmdb.net/album/60712"]

[dc8e4d852abd52c83e1b0fb306a3ea98]
catalognumber = "GNCA-0130"
date = "2008-12-25"
album = "「苺ましまろ encore」オープニングテーマ 『苺すぷらっしゅ』 [初回限定盤] Video"
tracks = [
    [1, "苺ましまろ encore (ノンテロップOP)", "伸恵(生天目仁美)、千佳(千葉紗子)、美羽(折笠富美子)、茉莉(川澄綾子)、アナ(能登麻美子)", 0],
]
links = ["https://beta.musicbrainz.org/release/cebe3f0b-6075-42cf-bf90-06d02e693879", "https://vgmdb.net/album/60712"]

[adf3702e1b9bdf738a523c00f3566bfa]
catalognumber = "GNCA-1216"
date = "2009-03-25"
album = "Serendipity / 折笠富美子"
tracks = [
    [1, "Garden", "", 0],
    [2, "PEANUTS MIND", "", 0],
    [3, "Lady Wendy", "", 0],
    [4, "君の夢 僕の愛", "", 0],
    [5, "ずっと, ずっと", "", 0],
    [6, "Sentence", "", 0],
    [7, "晨星", "", 0],
    [8, "Promenade", "", 0],
    [9, "四月の風", "", 0],
    [10, "Tomorrow", "", 0],
]
links = ["https://vgmdb.net/album/106016"]

[d11c3ca28def84bdc85a123afb7e8d93]
catalognumber = "GNCA-1337"
date = "2012-12-19"
album = "萌JAZZ vol.1"
tracks = [
    [1, "太陽曰く燃えよカオス", "STUDIO TRAM", 0],
    [2, "ハヤテのごとく!", "STUDIO TRAM", 0],
    [3, "ヒャダインのカカカタ☆カタオモイ-C", "STUDIO TRAM", 0],
    [4, "いぇす!ゆゆゆ☆ゆるゆり♪♪", "STUDIO TRAM", 0],
    [5, "経験値上昇中☆", "STUDIO TRAM", 0],
    [6, "Love Destiny", "STUDIO TRAM", 0],
    [7, "正解はひとつ!じゃない!!", "STUDIO TRAM", 0],
    [8, "いちごコンプリート", "STUDIO TRAM", 1],
    [9, "ヒャダインのカカカタ☆カタオモイ-C [Instrumental]", "STUDIO TRAM", 0],
    [10, "正解はひとつ!じゃない!! [Instrumental]", "STUDIO TRAM", 0],
]
links = ["https://beta.musicbrainz.org/release/9821c08e-123f-4f6e-b9ca-fa36166a35c0", "https://vgmdb.net/album/41820"]
