[102f8afdc8c9801682ef69c027262f70]
catalognumber = "SEXX-02556"
date = "2023-09-29"
album = "Anytime Anywhere / milet"
tracks = [
    [1, "Anytime Anywhere", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/76d44bb1-f4dc-4668-a401-5daf04f6d5ae", "https://vgmdb.net/album/132908"]

[2772b068088667ba41d346188f3d41b5]
catalognumber = "XSCL-75~6"
date = "2023-10-04"
album = "THE BOOK 3 / YOASOBI"
tracks = [
    [1, "勇者", "YOASOBI", 1],
    [2, "Interlude \"Awakening\"", "YOASOBI", 0],
    [3, "祝福", "YOASOBI", 0],
    [4, "海のまにまに", "YOASOBI", 0],
    [5, "ミスター", "YOASOBI", 0],
    [6, "Interlude \"Worship\"", "YOASOBI", 0],
    [7, "アイドル", "YOASOBI", 0],
    [8, "セブンティーン", "YOASOBI", 0],
    [9, "アドベンチャー", "YOASOBI", 0],
    [10, "好きだ", "YOASOBI", 0],
]
links = ["https://beta.musicbrainz.org/release/37e42e02-9eb9-41fd-b962-427cd8b30265", "https://vgmdb.net/album/132412"]

[2195df6660d210223ff3876622832355]
catalognumber = "XSC7-6"
date = "2023-10-21"
album = "THE BOOK 3 / YOASOBI"
tracks = [
    [1, "勇者", "YOASOBI", 1],
    [2, "Interlude \"Awakening\"", "YOASOBI", 0],
    [3, "祝福", "YOASOBI", 0],
    [4, "海のまにまに", "YOASOBI", 0],
    [5, "ミスター", "YOASOBI", 0],
    [6, "Interlude \"Worship\"", "YOASOBI", 0],
    [7, "アイドル", "YOASOBI", 0],
    [8, "セブンティーン", "YOASOBI", 0],
    [9, "アドベンチャー", "YOASOBI", 0],
    [10, "好きだ", "YOASOBI", 0],
]
links = ["https://beta.musicbrainz.org/release/2484b057-c170-4af8-b668-fc5bd7144abf", "https://vgmdb.net/album/138808"]

[76cec0a02ba8f18be3efefae140719de]
catalognumber = "XSCL-77~8"
date = "2023-12-13"
album = "勇者 / YOASOBI"
tracks = [
    [1, "勇者", "YOASOBI", 1],
    [2, "The Brave", "YOASOBI", 1],
    [3, "勇者 -Anime Edit-", "YOASOBI", 1],
    [4, "勇者 -Instrumental-", "YOASOBI", 1],
]
links = ["https://beta.musicbrainz.org/release/26bdd8e3-f308-461c-ae11-660876e485a5", "https://vgmdb.net/album/134518"]

[c11d46d59aa42cc348d001d9ce59a725]
catalognumber = "XSC7-7"
date = "2023-12-16"
album = "勇者 / YOASOBI"
tracks = [
    [1, "勇者", "", 1],
    [2, "The Brave (「勇者」英語版)", "", 1],
    [3, "勇者 - Anime Edit -", "", 1],
    [4, "勇者 - Instrumental -", "", 1],
]
links = ["https://vgmdb.net/album/138809"]

[61770495c7eb165d99ba3eef2c255a28]
catalognumber = "N/A"
date = "2023-12-22"
album = "TVアニメ『葬送のフリーレン』Original Soundtrack〜Pre-release〜"
tracks = [
    [1, "Journey of a Lifetime 〜 Frieren Main Theme", "Evan Call", 1],
    [2, "The End of One Journey", "Evan Call", 1],
    [3, "A Well-Earned Celebration", "Evan Call", 1],
    [4, "For 1000 Years", "Evan Call", 1],
    [5, "One Last Adventure", "Evan Call", 1],
    [6, "Farewell, My Friend", "Evan Call", 1],
    [7, "Departures", "Evan Call", 1],
    [8, "Time Flows Ever Onward", "Evan Call", 1],
    [9, "Grassy Turtles and Seed Rats", "Evan Call", 1],
    [10, "Where the Blue-Moon Weed Grows", "Evan Call", 1],
    [11, "Fear Brought Me This Far", "Evan Call", 1],
    [12, "Zoltraak", "Evan Call feat. Alina Lesnik", 1],
]
links = ["https://beta.musicbrainz.org/release/3a9d0628-2b0b-43c4-8142-e0085591e108", "https://vgmdb.net/album/135192"]

[1b3772b8bd301017b81e91b2f53a61b4]
catalognumber = "UP1AS-02090"
date = "2024-01-05"
album = "晴る / ヨルシカ"
tracks = [
    [1, "晴る", "ヨルシカ", 1],
]
links = ["https://beta.musicbrainz.org/release/e2a1bea0-fb36-4df3-83fc-5d13153dde0a", "https://vgmdb.net/album/135678"]

[561a2b497ec4fda1a415e596db0328b7]
catalognumber = "SECL-2939"
date = "2024-01-31"
album = "Anytime Anywhere / milet"
tracks = [
    [1, "Anytime Anywhere", "milet", 1],
    [2, "bliss", "milet", 1],
    [3, "Higher", "milet", 1],
    [4, "Wings", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/c9e6002e-7377-4fa9-87ea-78ddae65f111", "https://vgmdb.net/album/135940"]

[d6ad5a121c0f30b4c3830f40e963d070]
catalognumber = "SECL-2937~8"
date = "2024-01-31"
album = "Anytime Anywhere / milet [初回生産限定盤] Vocal"
tracks = [
    [1, "Anytime Anywhere", "milet", 1],
    [2, "bliss", "milet", 1],
    [3, "Higher", "milet", 1],
    [4, "Wings", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/65a7d1fc-158d-4135-a94e-1a45a61afd1d", "https://vgmdb.net/album/134892"]

[03ec380bcac69f842a67a6d1e0ec1ada]
catalognumber = "SECL-2937~8"
date = "2024-01-31"
album = "Anytime Anywhere / milet [初回生産限定盤] Disc 2 (Blu-ray) [SECL-2938]"
tracks = [
    [1, "Hey Song", "milet", 0],
    [2, "December", "milet", 0],
    [3, "Anytime Anywhere", "milet", 1],
    [4, "Anytime Anywhere", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/65a7d1fc-158d-4135-a94e-1a45a61afd1d", "https://vgmdb.net/album/134892"]

[c4e927bb083de3ee75f9c879ad8cdb9e]
catalognumber = "SECL-2940~1"
date = "2024-01-31"
album = "Anytime Anywhere / milet [アニメ絵柄期間生産限定盤] Vocal"
tracks = [
    [1, "Anytime Anywhere", "milet", 1],
    [2, "bliss", "milet", 1],
    [3, "Anytime Anywhere -TVサイズ 1stクール-", "milet", 1],
    [4, "Anytime Anywhere -TVサイズ 2ndクール-", "milet", 1],
    [5, "bliss -TVサイズ-", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/edfb5e4e-47b3-4b08-a83d-80c816eacf24", "https://vgmdb.net/album/135190"]

[cfcdb6c5cb54dbf7cf50835bc960caa1]
catalognumber = "SECL-2940~1"
date = "2024-01-31"
album = "Anytime Anywhere / milet [アニメ絵柄期間生産限定盤] Video"
tracks = [
    [1, "「Anytime Anywhere」×「葬送のフリーレン」 SPECIAL MUSIC VIDEO", "milet", 0],
    [2, "「葬送のフリーレン」 1stクールノンクレジットエンディングムービー", "milet", 0],
    [3, "「葬送のフリーレン」 2ndクールノンクレジットエンディングムービー", "milet", 0],
    [4, "「葬送のフリーレン」 特別エンディングノンクレジットムービー", "milet", 0],
]
links = ["https://beta.musicbrainz.org/release/edfb5e4e-47b3-4b08-a83d-80c816eacf24", "https://vgmdb.net/album/135190"]

[4f348e1bb814351a4e4a6c90790f9856]
catalognumber = "THCA-60290"
date = "2024-04-17"
album = "葬送のフリーレン ORIGINAL SOUNDTRACK Disc 1 [THCA-60290-1]"
tracks = [
    [1, "Journey of a Lifetime 〜 Frieren Main Theme", "Evan Call", 1],
    [2, "The End of One Journey", "Evan Call", 1],
    [3, "The Party of Heroes Returns", "Evan Call", 1],
    [4, "A Well-Earned Celebration", "Evan Call", 1],
    [5, "For 1000 Years", "Evan Call", 1],
    [6, "One Last Adventure", "Evan Call", 1],
    [7, "Farewell, My Friend", "Evan Call", 1],
    [8, "Departures", "Evan Call", 1],
    [9, "Time Flows Ever Onward", "Evan Call", 1],
    [10, "Heiter's Request", "Evan Call", 1],
    [11, "The Precious Moments We Share", "Evan Call", 1],
    [12, "Life Is Worth Living", "Evan Call", 1],
    [13, "Before the Light Fades", "Evan Call", 1],
    [14, "Grassy Turtles and Seed Rats", "Evan Call", 1],
    [15, "Where the Blue-Moon Weed Grows", "Evan Call", 1],
    [16, "Growing Up", "Evan Call", 1],
    [17, "Phantoms of the Dead", "Evan Call", 1],
    [18, "Magical Defense Training", "Evan Call", 1],
    [19, "Qual", "Evan Call", 1],
    [20, "Evolution of Magic", "Evan Call", 1],
    [21, "In Times of Peace", "Evan Call", 1],
    [22, "The Land Where Souls Rest", "Evan Call", 1],
    [23, "Where Hidden Magic Sleeps", "Evan Call", 1],
    [24, "Great Mage Flamme", "Evan Call", 1],
    [25, "Goodbye for Now, Eisen", "Evan Call", 1],
    [26, "More Than Mere Tales", "Evan Call", 1],
    [27, "The Warrior's Path", "Evan Call", 1],
    [28, "Fear Brought Me This Far", "Evan Call", 1],
    [29, "Dragon Smasher", "Evan Call", 1],
    [30, "Lift My Head From Shadow", "Evan Call", 1],
    [31, "Life and Legacy", "Evan Call", 1],
    [32, "Memories for My Master", "Evan Call", 1],
    [33, "To Travel for Aureole", "Evan Call", 1],
    [34, "Beyond the Journey's End", "Evan Call", 1],
]
links = ["https://beta.musicbrainz.org/release/6c130c2a-a401-4fc5-b836-c1003b3c1b3b", "https://vgmdb.net/album/135382"]

[e9a67005dd043d9ea320c9597e6c83a3]
catalognumber = "THCA-60290"
date = "2024-04-17"
album = "葬送のフリーレン ORIGINAL SOUNDTRACK Disc 2 [THCA-60290-2]"
tracks = [
    [1, "Zoltraak", "Evan Call feat. Alina Lesnik", 1],
    [2, "Frieren the Slayer", "Evan Call", 1],
    [3, "Across the Northern Lands", "Evan Call", 1],
    [4, "Gone, but Not Forgotten", "Evan Call", 1],
    [5, "Things That Scheme in the Dark", "Evan Call", 1],
    [6, "Deep in the Dungeon", "Evan Call", 1],
    [7, "Time Flows Ever Onward (Short Ver.)", "Evan Call", 1],
    [8, "Sleepy Frieren", "Evan Call", 1],
    [9, "Shipwrecks and Treasure", "Evan Call", 1],
    [10, "A Sunrise Worth Seeing", "Evan Call", 1],
    [11, "New Friends and Old Faces", "Evan Call", 1],
    [12, "Sneaking and Shopping", "Evan Call", 1],
    [13, "Drunkards and Mimics", "Evan Call", 1],
    [14, "Stark the Pure", "Evan Call", 1],
    [15, "Odd Clouds", "Evan Call", 1],
    [16, "To Catch a Stille", "Evan Call", 1],
    [17, "A Beautiful Word", "Evan Call", 1],
    [18, "Ancient Magic", "Evan Call", 1],
    [19, "Knife to the Throat", "Evan Call", 1],
    [20, "Demon's Bane", "Evan Call", 1],
    [21, "Seeds of the Past Bear Today's Fruit", "Evan Call", 1],
    [22, "Headpats and Praise", "Evan Call", 1],
    [23, "From the Heart", "Evan Call", 1],
    [24, "Pudding With Friends", "Evan Call", 1],
    [25, "Fern's Birthday", "Evan Call", 1],
    [26, "Privilege of the Young", "Evan Call", 1],
    [27, "Super Secret Magic Potions", "Evan Call", 1],
    [28, "Handsome Pose Collection", "Evan Call", 1],
    [29, "Too Many Grimoires", "Evan Call", 1],
    [30, "Stories Yet Untold", "Evan Call", 1],
    [31, "Old Man Voll", "Evan Call", 1],
    [32, "The Magic Within", "Evan Call", 1],
    [33, "New and Dangerous Magic", "Evan Call feat. Alina Lesnik", 1],
    [34, "Waltz for Stark and Fern", "Evan Call", 1],
    [35, "Mirrored Lotus", "Evan Call", 1],
    [36, "Song for the Beyond", "Evan Call", 1],
]
links = ["https://beta.musicbrainz.org/release/6c130c2a-a401-4fc5-b836-c1003b3c1b3b", "https://vgmdb.net/album/135382"]

[c99d66f5a6f2a20a6fde81221ef74f38]
catalognumber = "SECL-2975~6"
date = "2024-06-05"
album = "hanataba / milet [初回生產限定盤A] Vocal"
tracks = [
    [1, "hanataba", "milet", 0],
    [2, "Bluer", "milet", 0],
    [3, "GREEN LIGHTS", "milet", 0],
]
links = ["https://beta.musicbrainz.org/release/eebdcc34-34e4-4e26-b6cc-f14090f31ede", "https://vgmdb.net/album/149364"]

[3073801e0f97a8367addac6eb0a27e7c]
catalognumber = "SECL-2975~6"
date = "2024-06-05"
album = "hanataba / milet [初回生產限定盤A] Live Event, Video"
tracks = [
    [1, "hanataba", "milet", 0],
    [2, "Before the Dawn", "milet", 0],
    [3, "Wake Me Up", "milet", 0],
    [4, "Walkin' In My Lane", "milet", 0],
    [5, "Parachute", "milet", 0],
    [6, "inside you", "milet", 0],
    [7, "Into the Mirror", "milet", 0],
    [8, "HELL CLUB", "milet", 0],
    [9, "December", "milet", 0],
    [10, "Clan", "milet", 0],
    [11, "b r o k e n", "milet", 0],
    [12, "絆ノ奇跡", "milet", 0],
    [13, "コイコガレ", "milet", 0],
    [14, "Anytime Anywhere", "milet", 1],
    [15, "Flare", "milet", 0],
    [16, "Hey Song", "milet", 0],
    [17, "Time Is On Our Side", "milet", 0],
    [18, "Final Call", "milet", 0],
    [19, "Noel In July", "milet", 0],
    [20, "You made it -ENCORE-", "milet", 0],
    [21, "us -ENCORE-", "milet", 0],
    [22, "Living My Life -ENCORE-", "milet", 0],
]
links = ["https://beta.musicbrainz.org/release/eebdcc34-34e4-4e26-b6cc-f14090f31ede", "https://vgmdb.net/album/149364"]

[3dd8253d5e5f147286657fa4505701d6]
catalognumber = "XSJL-5"
date = "2024-10-23"
album = "THE BOOK 3 / YOASOBI"
tracks = [
    [1, "勇者", "YOASOBI", 1],
    [2, "Interlude \"Awakening\"", "YOASOBI", 0],
    [3, "祝福", "YOASOBI", 0],
    [4, "海のまにまに", "YOASOBI", 0],
    [5, "ミスター", "YOASOBI", 0],
    [6, "Interlude \"Worship\"", "YOASOBI", 0],
    [7, "アイドル", "YOASOBI", 0],
    [8, "セブンティーン", "YOASOBI", 0],
    [9, "アドベンチャー", "YOASOBI", 0],
    [10, "好きだ", "YOASOBI", 0],
]
links = ["https://beta.musicbrainz.org/release/9746d84d-8997-4220-b43c-1e7f6dde91ad", "https://vgmdb.net/album/162535"]

[49a7192e935538b384a47dd3ae59aade]
catalognumber = "PCCG-70543"
date = "2024-11-20"
album = "BRAIN HACK / Parabola"
tracks = [
    [1, "BRAIN HACK", "Parabola", 0],
    [2, "勇者 –アカペラアレンジver.–", "Parabola", 1],
    [3, "BRAIN HACK(No Lead Vocal)", "Parabola", 0],
    [4, "勇者 –アカペラアレンジver.–(No Lead Vocal)", "Parabola", 1],
]
links = ["https://beta.musicbrainz.org/release/f1973842-de9c-4f8d-a245-e34ec196f396", "https://vgmdb.net/album/144669"]

[5501de94da8e3f24490e7d119a896529]
catalognumber = "SIXX-07415"
date = "2025-12-17"
album = "Evan Call Orchestra Concert ～ 音楽と旅の現在地"
tracks = [
    [1, "World on Fire (2025 live version)", "Evan Call", 0],
    [2, "Theme of Violet Evergarden (2025 live version)", "Evan Call", 0],
    [3, "The Voice in My Heart (2025 live version)", "Evan Call", 0],
    [4, "To The Ends of Our World (2025 live version)", "Evan Call", 0],
    [5, "Across the Violet Sky (2025 live version)", "Evan Call", 0],
    [6, "Never Coming Back (2025 live version)", "Evan Call", 0],
    [7, "The Ultimate Price (2025 live version)", "Evan Call", 0],
    [8, "Violet's Letter (2025 live version)", "Evan Call", 0],
    [9, "Echo Through Eternity (2025 live version)", "Evan Call", 0],
    [10, "TSUBAME (2025 live version)", "Evan Call", 0],
    [11, "Theme of Hotarugusa (2025 live version)", "Evan Call", 0],
    [12, "The 13 Lords of the Shogun - Main Theme (2025 live version)", "Evan Call", 0],
    [13, "The Man Who Would Become Regent (2025 live version)", "Evan Call", 0],
    [14, "For Kamakura! (2025 live version)", "Evan Call", 0],
    [15, "Sengoku Youko ~ Main Theme (2025 live version)", "Evan Call", 0],
    [16, "The Dreams of Miyo Saimori (2025 live version)", "Evan Call", 0],
    [17, "A Home for the Heart (2025 live version)", "Evan Call", 0],
    [18, "Kiyoka and Miyo (2025 live version)", "Evan Call", 0],
    [19, "Tiny Little Life (2025 live version)", "Evan Call", 0],
    [20, "Journey of a Lifetime ~ Frieren Main Theme (2025 live version)", "Evan Call", 0],
    [21, "Fear Brought Me This Far (2025 live version)", "Evan Call", 1],
    [22, "Dragon Smasher (2025 live version)", "Evan Call", 1],
    [23, "Time Flows Ever Onward (2025 live version)", "Evan Call", 0],
    [24, "Frieren the Slayer (2025 live version)", "Evan Call", 1],
    [25, "Zoltraak (2025 live version)", "Evan Call feat. Alina Lesnik", 1],
    [26, "Welcome to Paldea Post Office / Paper Airplane (instrumental version) [2025 live version]", "Evan Call", 0],
    [27, "The Power of Gundam (2025 live version)", "Evan Call", 0],
    [28, "Dream Beyond Forever [2025 live version]", "Evan Call feat.Úyanga Bold", 0],
    [29, "'Murica (2025 live version)", "Evan Call", 0],
    [30, "Where Stray Stars Fall (2025 live version)", "Evan Call", 0],
]
links = ["https://beta.musicbrainz.org/release/2c2dd594-c0db-4006-9011-0766a49a8b31", "https://vgmdb.net/album/155562"]

[e8fa97128b328cba27dad4f2414c30d5]
catalognumber = "SICL-30072"
date = "2025-12-17"
album = "Evan Call Orchestra Concert ～ 音楽と旅の現在地"
tracks = [
    [1, "World on Fire", "", 0],
    [2, "Theme of Violet Evergarden", "", 0],
    [3, "The Voice in My Heart", "", 0],
    [4, "Across the Violet Sky", "", 0],
    [5, "Never Coming Back", "", 0],
    [6, "The Ultimate Price", "", 0],
    [7, "Violet's Letter", "", 0],
    [8, "TSUBAME", "", 0],
    [9, "Theme of Hotarugusa", "", 0],
    [10, "鎌倉殿の13人メインテーマ", "", 0],
    [11, "後に執権と呼ばれる男", "", 0],
    [12, "Sengoku Youko: Main Theme", "", 0],
    [13, "The Dreams of Miyo Saimori", "", 0],
    [14, "A Home for the Heart", "", 0],
    [15, "Kiyoka and Miyo", "", 0],
    [16, "Tiny Little Life", "", 0],
    [17, "Journey of a Lifetime ~ Frieren Main Theme", "", 0],
    [18, "Dragon Smasher", "", 1],
    [19, "Time Flows Ever Onward", "", 0],
    [20, "Frieren the Slayer", "", 1],
    [21, "Zoltraak", "", 1],
    [22, "Welcome to Paldea Post Office ~ Paper Airplane (Instrumental ver.)", "", 0],
    [23, "The Power of Gundam GUNDAM: Next Universal Century", "", 0],
    [24, "Dream Beyond Forever feat. Yui Mugino", "", 0],
    [25, "Where Stray Stars Fall", "", 0],
]
links = ["https://vgmdb.net/album/152780"]

[cb4a1faf7efadf4d2eda73251ec2bef3]
catalognumber = "N/A"
date = "2026-01-12"
album = "lulu. / Mrs. GREEN APPLE"
tracks = [
    [1, "lulu.", "Mrs. GREEN APPLE", 0],
]
links = ["https://beta.musicbrainz.org/release/65c3e23a-1204-4167-96c7-ba678a9c4a9f", "https://vgmdb.net/album/156362"]

[dac30e72d132265de2e94b90cb3781aa]
catalognumber = "N/A"
date = "2026-02-14"
album = "TVアニメ『葬送のフリーレン』Season2 Original Soundtrack 〜Selected Version〜"
tracks = [
    [1, "The Journey Continues", "Evan Call", 0],
    [2, "Castles and Cobblestone", "Evan Call", 0],
    [3, "Villages and Vagabonds", "Evan Call", 0],
    [4, "Memories - Wayfarers of Time", "Evan Call", 0],
    [5, "Hero of the South", "Evan Call", 0],
    [6, "Ready Your Weapon", "Evan Call", 0],
]
links = ["https://beta.musicbrainz.org/release/56d6ac1a-8676-44c4-bea5-2c6a72d70227", "https://vgmdb.net/album/157356"]

[9ee1a432b69ca48a18af5ae772bffc90]
catalognumber = "SECL-3298~9"
date = "2026-03-04"
album = "The Story of Us / milet [期間生産限定盤/アニメ盤] Arrangement, Vocal"
tracks = [
    [1, "The Story of Us", "milet", 0],
    [2, "Trace", "milet", 0],
    [3, "The Story of Us - Anime size", "milet", 0],
    [4, "Trace - Short size", "milet", 0],
    [5, "Anytime Anywhere - A.Gt Session", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/7dda93c5-2f9c-4ce1-a9d4-c36376971632", "https://vgmdb.net/album/156276"]

[d941a8ffaef31bfd81c3d5ec06c11d13]
catalognumber = "SECL-3298~9"
date = "2026-03-04"
album = "The Story of Us / milet [期間生産限定盤/アニメ盤] Arrangement, Vocal, Video"
tracks = [
    [1, "(no title available)", "", 0],
    [2, "(no title available)", "", 0],
]
links = ["https://vgmdb.net/album/156276"]

[fec1c3a7a8419e761bd018e0dabe4363]
catalognumber = "SECL-3295~6"
date = "2026-03-04"
album = "The Story of Us / milet [初回生産限定盤] Arrangement, Vocal"
tracks = [
    [1, "The Story of Us", "milet", 0],
    [2, "Trace", "milet", 0],
    [3, "Anytime Anywhere - Piano Session", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/cace6d93-d248-4a52-b10a-494656f2e939", "https://vgmdb.net/album/156277"]

[440f65a902097eca4e7115482ec5162a]
catalognumber = "SECL-3295~6"
date = "2026-03-04"
album = "The Story of Us / milet [初回生産限定盤] Arrangement, Vocal, Live Event, Video"
tracks = [
    [1, "「The Story of Us」 MUSIC VIDEO", "milet", 0],
    [2, "「Bluer」 MUSIC VIDEO", "milet", 0],
    [3, "「Anytime Anywhere」 MUSIC VIDEO", "milet", 0],
    [4, "「Anytime Anywhere」SPECIAL MUSIC VIDEO (Live from milet live tour “stairs” 2024)", "milet", 0],
    [5, "「The Story of Us」MUSIC VIDEO Behind The Scenes", "milet", 0],
    [6, "「Anytime Anywhere」MUSIC VIDEO Behind The Scenes", "milet", 0],
]
links = ["https://beta.musicbrainz.org/release/cace6d93-d248-4a52-b10a-494656f2e939", "https://vgmdb.net/album/156277"]

[a8462f7490a14e14e124d2675a04acad]
catalognumber = "SECL-3297"
date = "2026-03-04"
album = "The Story of Us / milet"
tracks = [
    [1, "The Story of Us", "milet", 0],
    [2, "Trace", "milet", 0],
    [3, "Anytime Anywhere - Piano Session", "milet", 1],
]
links = ["https://beta.musicbrainz.org/release/1a3741ea-9e0f-4403-a344-3809e0549478", "https://vgmdb.net/album/156278"]

[9056d14aff06370b2d8b7b60da08a733]
catalognumber = "THCA-60299"
date = "2026-04-15"
album = "TVアニメ『葬送のフリーレン』Season2 Original Soundtrack"
tracks = []
links = ["https://vgmdb.net/album/156443"]
