[20147d04d7d0e01cdb743258777e8328]
catalognumber = "N/A"
date = "2021-01-09"
album = "蜘蛛ですが、なにか? 限定ドラマCD <夢見る乙女>に囚われた転生者たち"
tracks = [
    [1, "＜夢見る乙女＞に囚われた転生者たち", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/35084c1d-484d-472a-9018-bf67f9457782", "https://vgmdb.net/album/105146"]

[b989cb574a9a5b4b34f48d0df2554dc6]
catalognumber = "ZMCZ-14441"
date = "2021-01-27"
album = "keep weaving your spider way / 安月名莉子"
tracks = [
    [1, "keep weaving your spider way", "安月名莉子", 0],
    [2, "tear the score", "安月名莉子", 0],
    [3, "keep weaving your spider way (instrumental)", "安月名莉子", 0],
    [4, "tear the score (instrumental)", "安月名莉子", 0],
]
links = ["https://beta.musicbrainz.org/release/181076cf-0e95-4fef-9bcf-e814c56b43eb", "https://vgmdb.net/album/106437"]

[d9ff3f0724bb23fd568ac2eb8d434c30]
catalognumber = "ZMCZ-14442"
date = "2021-01-27"
album = "がんばれ! 蜘蛛子さんのテーマ / 「私」 (CV:悠木碧)"
tracks = [
    [1, "がんばれ!蜘蛛子さんのテーマ", "「私」(CV:悠木碧)", 0],
    [2, "ヤケクソ☆ラプソディ", "「私」(CV:悠木碧)", 0],
    [3, "がんばれ!蜘蛛子さんのテーマ (instrumental)", "「私」(CV:悠木碧)", 0],
    [4, "ヤケクソ☆ラプソディ (instrumental)", "「私」(CV:悠木碧)", 0],
]
links = ["https://beta.musicbrainz.org/release/de4319ba-7e85-4c2a-8082-7cecf69bb880", "https://vgmdb.net/album/106436"]

[d0eca759d74546a2dbab055851668c2b]
catalognumber = "ZMCZ-14781"
date = "2021-04-28"
album = "TVアニメ「蜘蛛ですが、なにか?」オリジナルサウンドトラック Disc 1 [ZMCZ-14781 (TGCS-12039)]"
tracks = [
    [1, "So I'm a Spider, So What?", "片山修志", 0],
    [2, "I'm a Spider", "片山修志", 0],
    [3, "No Way", "片山修志", 0],
    [4, "Why Did I Die?", "片山修志", 0],
    [5, "Hungry", "片山修志", 0],
    [6, "Labyrinth", "片山修志", 0],
    [7, "Fear of the Unknown", "片山修志", 0],
    [8, "Hunting", "片山修志", 0],
    [9, "Struggle", "片山修志", 0],
    [10, "Defeat You!", "片山修志", 0],
    [11, "Got the Skill", "片山修志", 0],
    [12, "Leveled Up", "片山修志", 0],
    [13, "Positive Feelings", "片山修志", 0],
    [14, "Fun to Play Alone", "片山修志", 0],
    [15, "Unbelievable!?", "片山修志", 0],
    [16, "Hurry, Hurry", "片山修志", 0],
    [17, "A Tragedy", "片山修志", 0],
    [18, "Reminiscence", "片山修志", 0],
    [19, "Let's Rest Today", "片山修志", 0],
    [20, "Suspicion", "片山修志", 0],
    [21, "Ominous Sign", "片山修志", 0],
    [22, "Impending Danger", "片山修志", 0],
    [23, "The Terrible Monster", "片山修志", 0],
    [24, "Run Away", "片山修志", 0],
    [25, "I Couldn't Do Anything", "片山修志", 0],
    [26, "Thinking", "片山修志", 0],
    [27, "Mysterious Power", "片山修志", 0],
    [28, "Magical Spider Girl", "片山修志", 0],
    [29, "To Be Stronger", "片山修志", 0],
    [30, "I'm on Fire", "片山修志", 0],
    [31, "Into the Battle", "片山修志", 0],
    [32, "Hard Fight", "片山修志", 0],
    [33, "It's My Way", "片山修志", 0],
    [34, "Evolution", "片山修志", 0],
    [35, "Poison", "片山修志", 0],
    [36, "Leveled Up II", "片山修志", 0],
    [37, "Leveled Up III", "片山修志", 0],
    [38, "Preview", "片山修志", 0],
]
links = ["https://beta.musicbrainz.org/release/8cc4e028-afec-4d0e-904d-0e11d39b4536", "https://vgmdb.net/album/109093"]

[63a5d33283b2389660c4220ae4b37a32]
catalognumber = "ZMCZ-14781"
date = "2021-04-28"
album = "TVアニメ「蜘蛛ですが、なにか?」オリジナルサウンドトラック Disc 2 [ZMCZ-14781 (TGCS-12040)]"
tracks = [
    [1, "At the School", "片山修志", 0],
    [2, "On the Sunny Side of the World", "片山修志", 0],
    [3, "Melancholy", "片山修志", 0],
    [4, "Practical Lesson", "片山修志", 0],
    [5, "Crisis", "片山修志", 0],
    [6, "Fight the Monster", "片山修志", 0],
    [7, "Malicious Heart", "片山修志", 0],
    [8, "Conflict", "片山修志", 0],
    [9, "Ruler Authority", "片山修志", 0],
    [10, "Past School Days", "片山修志", 0],
    [11, "Chasing the Ball", "片山修志", 0],
    [12, "Sad Previous Life", "片山修志", 0],
    [13, "Devil's Force", "片山修志", 0],
    [14, "The Brave", "片山修志", 0],
    [15, "Encounter", "片山修志", 0],
    [16, "Death of the Brave", "片山修志", 0],
    [17, "Sorrow", "片山修志", 0],
    [18, "Contract with Me", "片山修志", 0],
    [19, "Taboo", "片山修志", 0],
    [20, "Earth Dragon Araba", "片山修志", 0],
    [21, "The Powerful Enemy", "片山修志", 0],
    [22, "In Peril", "片山修志", 0],
    [23, "Strike Back", "片山修志", 0],
    [24, "The Dragon has Fallen", "片山修志", 0],
    [25, "I'm Not Just a Spider", "片山修志", 0],
]
links = ["https://beta.musicbrainz.org/release/8cc4e028-afec-4d0e-904d-0e11d39b4536", "https://vgmdb.net/album/109093"]

[e41147e44b9091ce9368daee5fc4f715]
catalognumber = "ZMCZ-14787"
date = "2021-05-07"
album = "Bursty Greedy Spider / 鈴木このみ"
tracks = [
    [1, "Bursty Greedy Spider", "鈴木このみ", 0],
    [2, "Crossroads", "鈴木このみ", 0],
    [3, "Bursty Greedy Spider (instrumental)", "鈴木このみ", 0],
    [4, "Crossroads (instrumental)", "鈴木このみ", 0],
]
links = ["https://beta.musicbrainz.org/release/5e6ec44d-4bc6-454e-a482-d8ad9fe897d3", "https://vgmdb.net/album/109092"]

[804f1285bf22a9fa42abb2ac06755e64]
catalognumber = "ZMCZ-14788"
date = "2021-05-07"
album = "現実凸撃ヒエラルキー / 「私」(CV: 悠木碧)"
tracks = [
    [1, "現実凸撃ヒエラルキー", "「私」(CV:悠木碧)", 0],
    [2, "On My Own", "「私」(CV:悠木碧)", 0],
    [3, "現実凸撃ヒエラルキー (instrumental)", "「私」(CV:悠木碧)", 0],
    [4, "On My Own (instrumental)", "「私」(CV:悠木碧)", 0],
]
links = ["https://beta.musicbrainz.org/release/463410e8-5a68-486c-94df-f50e68e3888b", "https://vgmdb.net/album/109091"]

[92ba2ac0c3c420561124ed6f4ae90dc1]
catalognumber = "ZMCZ-14782"
date = "2021-06-30"
album = "TVアニメ「蜘蛛ですが、なにか?」オリジナルサウンドトラック vol.2 Disc 1 [ZMCZ-14782 (TGCS-12057)]"
tracks = [
    [1, "The Sea, the Sun and Salty Breeze!", "片山修志", 0],
    [2, "Don't Play with Me", "片山修志", 0],
    [3, "Mother", "片山修志", 0],
    [4, "The Puppet", "片山修志", 0],
    [5, "Invisible Battle", "片山修志", 0],
    [6, "The Administrator", "片山修志", 0],
    [7, "Hugo's Ambition", "片山修志", 0],
    [8, "The Trap", "片山修志", 0],
    [9, "Something Bad is Happening", "片山修志", 0],
    [10, "Rebellion", "片山修志", 0],
    [11, "Escape from the Castle", "片山修志", 0],
    [12, "Courageous Decision", "片山修志", 0],
    [13, "Shun's Dream", "片山修志", 0],
    [14, "Small Village", "片山修志", 0],
    [15, "Steps in the Dark", "片山修志", 0],
    [16, "Who are You?", "片山修志", 0],
    [17, "In Harm's Way", "片山修志", 0],
    [18, "I Feel Regret", "片山修志", 0],
    [19, "What You Want to Do", "片山修志", 0],
    [20, "Fei's New Look", "片山修志", 0],
    [21, "You are Too Close to Me", "片山修志", 0],
    [22, "Fly Away", "片山修志", 0],
    [23, "Sariella", "片山修志", 0],
    [24, "Word of God Religion", "片山修志", 0],
    [25, "Elves Forest", "片山修志", 0],
    [26, "Reunion with Classmates", "片山修志", 0],
    [27, "Days that Never Return", "片山修志", 0],
]
links = ["https://beta.musicbrainz.org/release/e26e8a91-7d05-48f4-8b59-232f968f3a82", "https://vgmdb.net/album/110160"]

[4188be4dde5ef4e9df5b608ef0f8928a]
catalognumber = "ZMCZ-14782"
date = "2021-06-30"
album = "TVアニメ「蜘蛛ですが、なにか?」オリジナルサウンドトラック vol.2 Disc 2 [ZMCZ-14782 (TGCS-12058)]"
tracks = [
    [1, "Sophia", "片山修志", 0],
    [2, "The World in Her Eyes", "片山修志", 0],
    [3, "Sneaking Assailants", "片山修志", 0],
    [4, "Sophia in Danger", "片山修志", 0],
    [5, "Why Did This Happen?", "片山修志", 0],
    [6, "Filimøs' Distress", "片山修志", 0],
    [7, "Potimas", "片山修志", 0],
    [8, "A Dark Cloud on the Horizon", "片山修志", 0],
    [9, "Clash", "片山修志", 0],
    [10, "Formidable Troops", "片山修志", 0],
    [11, "Resistance", "片山修志", 0],
    [12, "Demons' Camp", "片山修志", 0],
    [13, "Gloria's Attack", "片山修志", 0],
    [14, "Wrath", "片山修志", 0],
    [15, "Broken Heart", "片山修志", 0],
    [16, "Ariel", "片山修志", 0],
    [17, "Demonic Power", "片山修志", 0],
    [18, "Desperate Fight", "片山修志", 0],
    [19, "The Fang", "片山修志", 0],
    [20, "White", "片山修志", 0],
    [21, "The Demon Lord", "片山修志", 0],
]
links = ["https://beta.musicbrainz.org/release/e26e8a91-7d05-48f4-8b59-232f968f3a82", "https://vgmdb.net/album/110160"]

[91987dbc129ca5dfbcdf25d8ae37edd7]
catalognumber = "ZMCZ-15571"
date = "2022-05-25"
album = "ULTRA FLASH / 鈴木このみ [初回限定盤] Vocal, Live Event, Video"
tracks = [
    [1, "鈴木このみ \"Premium Acoustic Live 2021\" at Billboard YOKOHAMA 全編", "鈴木このみ", 0],
    [2, "鈴木このみ 7th Live Tour ～Bursty Monster～ 東京公演(一部)", "鈴木このみ", 0],
]
links = ["https://beta.musicbrainz.org/release/1dc76445-f6f0-4f79-84f5-f834d690623f", "https://vgmdb.net/album/118883"]

[4f66b41b0588db0b82eb0ad9df930b70]
catalognumber = "ZMCZ-15571"
date = "2022-05-25"
album = "ULTRA FLASH / 鈴木このみ [初回限定盤] Vocal"
tracks = [
    [1, "Bursty Greedy Spider", "鈴木このみ", 0],
    [2, "ULTRA FLASH", "鈴木このみ", 0],
    [3, "ダメージ小でした", "鈴木このみ", 0],
    [4, "Missing Promise", "鈴木このみ", 0],
    [5, "Glorious Day", "鈴木このみ", 0],
    [6, "HELLO", "鈴木このみ", 0],
    [7, "PROUD STARS", "鈴木このみ", 0],
    [8, "舞い降りてきた雪", "恋とプロデューサー featuring Konomi Suzuki", 0],
    [9, "Theater of Life", "鈴木このみ", 0],
    [10, "命の灯火", "鈴木このみ", 0],
    [11, "Realize", "鈴木このみ", 0],
    [12, "メロディックロードムービー", "鈴木このみ feat.伊東歌詞太郎", 0],
    [13, "Ordinary Wish", "鈴木このみ", 0],
]
links = ["https://beta.musicbrainz.org/release/1dc76445-f6f0-4f79-84f5-f834d690623f", "https://vgmdb.net/album/118883"]

[722c9342d6169d960583695b24115914]
catalognumber = "ZMCZ-15572"
date = "2022-05-25"
album = "ULTRA FLASH / 鈴木このみ"
tracks = [
    [1, "Bursty Greedy Spider", "鈴木このみ", 0],
    [2, "ULTRA FLASH", "鈴木このみ", 0],
    [3, "ダメージ小でした", "鈴木このみ", 0],
    [4, "Missing Promise", "鈴木このみ", 0],
    [5, "Glorious Day", "鈴木このみ", 0],
    [6, "HELLO", "鈴木このみ", 0],
    [7, "PROUD STARS", "鈴木このみ", 0],
    [8, "舞い降りてきた雪", "恋とプロデューサー featuring Konomi Suzuki", 0],
    [9, "Theater of Life", "鈴木このみ", 0],
    [10, "命の灯火", "鈴木このみ", 0],
    [11, "Realize", "鈴木このみ", 0],
    [12, "メロディックロードムービー", "鈴木このみ feat.伊東歌詞太郎", 0],
    [13, "Ordinary Wish", "鈴木このみ", 0],
]
links = ["https://beta.musicbrainz.org/release/0b7a5ddd-4f44-46dc-9059-9c1afabf64ed", "https://vgmdb.net/album/118882"]

[38f052023492af34eae5b2c23c01f85c]
catalognumber = "ZMCZ-16541"
date = "2023-03-29"
album = "BLUE MOON / 安月名莉子"
tracks = [
    [1, "Memories", "安月名莉子", 0],
    [2, "君にふれて", "安月名莉子", 0],
    [3, "Whiteout", "安月名莉子", 0],
    [4, "花", "安月名莉子", 0],
    [5, "Glow at the Velocity of Light", "安月名莉子", 0],
    [6, "be perfect, plz!", "安月名莉子", 0],
    [7, "keep weaving your spider way", "安月名莉子", 0],
    [8, "Chance! & Revenge!", "安月名莉子", 0],
    [9, "知らなきゃ", "安月名莉子", 0],
    [10, "selfish", "安月名莉子", 0],
    [11, "かたち", "安月名莉子", 0],
    [12, "BLUE CYALUME", "安月名莉子", 0],
]
links = ["https://beta.musicbrainz.org/release/f648f806-44b1-426c-83f5-039895f2d950", "https://vgmdb.net/album/126385"]
