[974fb3ddba8b115b70ad45aa13edc7d4]
catalognumber = "LACM-14541"
date = "2016-10-26"
album = "蝶結びアミュレット / Mia REGINA"
tracks = [
    [1, "蝶結びアミュレット", "Mia REGINA", 1],
    [2, "Magnetic", "Mia REGINA", 1],
    [3, "蝶結びアミュレット (Instrumental)", "Mia REGINA", 1],
    [4, "Magnetic (Instrumental)", "Mia REGINA", 1],
]
links = ["https://beta.musicbrainz.org/release/dbcda0d8-01c4-4820-87f5-2ada01d53d21", "https://vgmdb.net/album/61026"]

[98749d2e638ec13f02b3927a2aa42953]
catalognumber = "LASM-34180~1"
date = "2016-11-16"
album = "My Only Place / スフィア Disc 1 (CD) [LASM-34180]"
tracks = [
    [1, "My Only Place", "スフィア", 1],
    [2, "Miracle shooter", "スフィア", 1],
    [3, "My Only Place (off vocal)", "スフィア", 1],
    [4, "Miracle shooter (off vocal)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/10c779bf-747f-4df6-b2ac-0262dd350606", "https://vgmdb.net/album/60789"]

[2a679b567c3daed553efe05c8cff6dc6]
catalognumber = "LASM-34180~1"
date = "2016-11-16"
album = "My Only Place / スフィア Disc 2 (DVD) [LASM-34181]"
tracks = [
    [1, "My Only Place (Music Video Clip)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/10c779bf-747f-4df6-b2ac-0262dd350606", "https://vgmdb.net/album/60789"]

[3a9d3c651198ccd3f2a57e327a73a89f]
catalognumber = "LASM-4180"
date = "2016-11-16"
album = "My Only Place / スフィア"
tracks = [
    [1, "My Only Place", "スフィア", 1],
    [2, "Miracle shooter", "スフィア", 1],
    [3, "My Only Place (off vocal)", "スフィア", 1],
    [4, "Miracle shooter (off vocal)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/8e2f06c1-e182-40d4-935f-5d4eec3e1564", "https://vgmdb.net/album/60787"]

[7bd150f33d91772d733260fd6c773970]
catalognumber = "LASM-34182"
date = "2016-11-16"
album = "My Only Place / スフィア"
tracks = [
    [1, "My Only Place", "スフィア", 1],
    [2, "Miracle shooter", "スフィア", 1],
    [3, "My Only Place (off vocal)", "スフィア", 1],
    [4, "Miracle shooter (off vocal)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/fcdd2da3-7de3-4712-8d5d-613a960fc31b", "https://vgmdb.net/album/60788"]

[cf11960a8bd8ce3eb88bfaed218c1724]
catalognumber = "LACA-15610"
date = "2016-12-07"
album = "THAT'S A FACT! / Mia REGINA"
tracks = [
    [1, "overture", "Mia REGINA", 0],
    [2, "THAT’S A FACT! 〜千里の道も一歩から〜", "Mia REGINA", 0],
    [3, "無敵乙女化プログレス", "Mia REGINA", 0],
    [4, "ambivalent future", "霧島若歌", 0],
    [5, "蝶結びアミュレット", "Mia REGINA", 1],
    [6, "ギミギミ☆greedy", "霧島若歌 & ささかまリス子", 0],
    [7, "with a wish", "上花楓裏", 0],
    [8, "ラブリーデイ", "Mia REGINA", 0],
    [9, "つなぐ未来", "上花楓裏 & ささかまリス子", 0],
    [10, "ハバネロ", "ささかまリス子", 0],
    [11, "White Guilty", "Mia REGINA", 0],
    [12, "ETERNALエクスプローラー", "Mia REGINA", 0],
]
links = ["https://beta.musicbrainz.org/release/9b65f5ad-683f-4f84-af70-5fdd63409043", "https://vgmdb.net/album/80731"]

[35a602c515915eae432298f41644e65f]
catalognumber = "LACA-9486~7"
date = "2017-01-18"
album = "TVアニメ『装神少女まとい』オリジナルサウンドトラック Original Soundtrack"
tracks = [
    [1, "纏創少女", "加藤達也", 1],
    [2, "少女、神を宿す", "加藤達也", 1],
    [3, "まとい、纏創っ!", "加藤達也", 1],
    [4, "クラルス、纏創...!", "加藤達也", 1],
    [5, "ゆま、てんそう!", "加藤達也", 1],
    [6, "まといの望む願い", "加藤達也", 1],
    [7, "神の産物", "加藤達也", 1],
    [8, "宿りし神の力", "加藤達也", 1],
    [9, "まといの穏やかな日常", "加藤達也", 1],
    [10, "まといの愉快な日常", "加藤達也", 1],
    [11, "まといの軽やかな日常", "加藤達也", 1],
    [12, "まといの密やかな日常", "加藤達也", 1],
    [13, "タイカツ!!", "加藤達也", 1],
    [14, "たのしいたのしい おいかけっこ", "加藤達也", 1],
    [15, "vsナイツ～もきゅっ～", "加藤達也", 1],
    [16, "夏だ! 海だ!! ハーレムだ!!!", "加藤達也", 1],
    [17, "ゆまちん! いざ行かん!!", "加藤達也", 1],
    [18, "抜き足、差し足、忍び足...?", "加藤達也", 1],
    [19, "よーくかんがえるのです", "加藤達也", 1],
    [20, "よーく考えてみた", "加藤達也", 1],
    [21, "ガールズトーク♪", "加藤達也", 1],
    [22, "絆を結いあわせる", "加藤達也", 1],
    [23, "足りないもの", "加藤達也", 1],
    [24, "わたしの悩み", "加藤達也", 1],
    [25, "弥生の想い", "加藤達也", 1],
]
links = ["https://beta.musicbrainz.org/release/41ef9fe6-5d91-49ee-906c-087d3d6485b8", "https://vgmdb.net/album/62352"]

[d8d4793be2ba4c97e6c2be9184e2b8b8]
catalognumber = "LACA-9486~7"
date = "2017-01-18"
album = "TVアニメ『装神少女まとい』オリジナルサウンドトラック Original Soundtrack, Vocal"
tracks = [
    [1, "祈りの祭壇", "加藤達也", 1],
    [2, "絡み合う思惑", "加藤達也", 1],
    [3, "探り、探られ、暴き、暴かれ", "加藤達也", 1],
    [4, "調査開始", "加藤達也", 1],
    [5, "見えないもの", "加藤達也", 1],
    [6, "迫りくる影", "加藤達也", 1],
    [7, "忍び寄る影", "加藤達也", 1],
    [8, "襲い来る影", "加藤達也", 1],
    [9, "vsナイツ～始まり～", "加藤達也", 1],
    [10, "vsナイツ～攻め～", "加藤達也", 1],
    [11, "vsナイツ～焦り～", "加藤達也", 1],
    [12, "影とは", "加藤達也", 1],
    [13, "絆の記憶", "加藤達也", 1],
    [14, "クラルスの使命", "加藤達也", 1],
    [15, "クラルスの闘い", "加藤達也", 1],
    [16, "高次元空間", "加藤達也", 1],
    [17, "八百万の神々", "加藤達也", 1],
    [18, "願い、想い、迷い...", "加藤達也", 1],
    [19, "vsナイツ～運命の決戦～", "加藤達也", 1],
    [20, "調停者という存在", "加藤達也", 1],
    [21, "普通がイチバン", "加藤達也", 1],
    [22, "退魔少女! 変☆身!!", "加藤達也", 1],
    [23, "蝶結びアミュレット (TV SIZE)", "Mia REGINA", 1],
    [24, "My Only Place (TV SIZE)", "スフィア", 1],
]
links = ["https://beta.musicbrainz.org/release/41ef9fe6-5d91-49ee-906c-087d3d6485b8", "https://vgmdb.net/album/62352"]

[031cb085788c82d4ca858979f5ecbd2f]
catalognumber = "BCXA-1218"
date = "2017-01-27"
album = "装神少女まとい スペシャル・サウンド・ドラマCD「神様、しゃべりました」"
tracks = [
    [1, "神様、しゃべりました #01", "", 1],
    [2, "神様、しゃべりました #02", "", 1],
    [3, "神様、しゃべりました #03", "", 1],
]
links = ["https://vgmdb.net/album/62115"]

[a52172c7919d08a5ae017c3eefb8f0ec]
catalognumber = "LACA-15632"
date = "2017-02-08"
album = "TVアニメ『装神少女まとい』キャラクターソングミニアルバム"
tracks = [
    [1, "笑う神には福来たる!", "皇まとい(CV.諏訪彩花)&草薙ゆま(CV.大空直美)", 1],
    [2, "UPDATE MY PRAYER", "皇まとい(CV.諏訪彩花)", 1],
    [3, "タイカツ ドット ジェイピー!", "草薙ゆま(CV.大空直美)", 1],
    [4, "Quaedam Fulmen", "クラルス・トニトルス(CV.戸松遥)", 1],
    [5, "ソーシン節", "皇まとい(CV.諏訪彩花)、草薙ゆま(CV.大空直美)、クラルス・トニトルス(CV.戸松遥)、皇伸吾(CV.東地宏樹)、春夏・ルシエラ(CV.川澄綾子)、カリオテ(CV.檜山修之)、手塚秀夫(CV.阿部敦)", 1],
]
links = ["https://beta.musicbrainz.org/release/43f7d5f7-5fa8-4646-892d-3bc708208b66", "https://vgmdb.net/album/62965"]

[f2e2eed62d226581dd6a01db81e5504f]
catalognumber = "BCXA-1219"
date = "2017-04-21"
album = "装神少女まとい スペシャル・ラジオ・ドラマCD「おーまいがー☆しあたー」"
tracks = [
    [1, "おーまいがー☆しあたー #01", "", 1],
    [2, "おーまいがー☆しあたー #02", "", 1],
    [3, "おーまいがー☆しあたー #03", "", 1],
    [4, "おーまいがー☆しあたー #04", "", 1],
    [5, "おーまいがー☆しあたー #05", "", 1],
    [6, "おーまいがー☆しあたー #06", "", 1],
    [7, "おーまいがー☆しあたー #07", "", 1],
    [8, "おーまいがー☆しあたー #08", "", 1],
    [9, "おーまいがー☆しあたー #09", "", 1],
    [10, "おーまいがー☆しあたー #10", "", 1],
    [11, "おーまいがー☆しあたー #11", "", 1],
    [12, "おーまいがー☆しあたー #12", "", 1],
    [13, "おーまいがー☆しあたー #13", "", 1],
    [14, "おーまいがー☆しあたー #14", "", 1],
]
links = ["https://vgmdb.net/album/69341"]
