[10211a33fecf4317b0bbccb3ffb820b1]
catalognumber = "KICM-3239"
date = "2011-08-31"
album = "DEAR FUTURE / coaltar of the deepers"
tracks = [
    [1, "DEAR FUTURE", "coaltar of the deepers", 0],
    [2, "DEAR FUTURE", "Shinobu Narita (URBAN DANCE)", 0],
    [3, "DEAR FUTURE", "Ringo Deathstarr", 0],
    [4, "DEAR FUTURE remix by DJ JIMIHENDRIXXX (a.k.a. Keiichiro Shibuya)", "coaltar of the deepers feat. Yui Horie", 0],
    [5, "DEAR FUTURE", "SECRET SHINE", 0],
    [6, "DEAR FUTURE remix by kensuke ushio (agraph)", "coaltar of the deepers", 0],
    [7, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
]
links = ["https://beta.musicbrainz.org/release/dd6c71f4-44d9-47ca-8f3e-e99785617291", "https://vgmdb.net/album/27973"]

[955cf62f8b21ac26fb57ac3ec1f67be8]
catalognumber = "KICM-3238"
date = "2011-10-05"
album = "ノルニル・少年よ我に帰れ / やくしまるえつこメトロオーケストラ Vocal"
tracks = [
    [1, "ノルニル", "やくしまるえつこメトロオーケストラ", 0],
    [2, "少年よ我に帰れ", "やくしまるえつこメトロオーケストラ", 0],
    [3, "ノルニル (off vocal ver.)", "やくしまるえつこメトロオーケストラ", 0],
    [4, "少年よ我に帰れ (off vocal ver.)", "やくしまるえつこメトロオーケストラ", 0],
]
links = ["https://beta.musicbrainz.org/release/c8197584-5cd2-4c78-a12e-7eb160e565e2", "https://vgmdb.net/album/27544"]

[5f166e5fe367a291d6888001b47602cf]
catalognumber = "KICM-3238"
date = "2011-10-05"
album = "ノルニル・少年よ我に帰れ / やくしまるえつこメトロオーケストラ Arrangement, Vocal"
tracks = [
    [1, "ノルニル (Ametsub remix)", "やくしまるえつこメトロオーケストラ", 0],
    [2, "少年よ我に帰れ (DJ BAKU remix)", "やくしまるえつこメトロオーケストラ", 0],
]
links = ["https://beta.musicbrainz.org/release/c8197584-5cd2-4c78-a12e-7eb160e565e2", "https://vgmdb.net/album/27544"]

[9d8e255ce07e287844291d949e5cf231]
catalognumber = "SSX-10205"
date = "2011-10-26"
album = "輪るピングディスク VOL.1 オリジナルサウンドトラック"
tracks = [
    [1, "運命の子たち", "橋本由香利", 0],
    [2, "キラキラ", "橋本由香利", 0],
    [3, "ボーイミーツガール", "橋本由香利", 0],
    [4, "オーディオドラマ「ペンギン0号殺ペン事件」", "[dialogue]", 0],
    [5, "ピングミッション", "橋本由香利", 0],
    [6, "セクシーが来た!", "橋本由香利", 0],
    [7, "珊瑚の迷路", "橋本由香利", 0],
    [8, "僕たちの望みの喜びよ", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/39ff3d44-4721-4b0b-a06d-04a47ba5cf10", "https://vgmdb.net/album/29729"]

[6f636d6264c39a6850d725395f047790]
catalognumber = "SSX-10206"
date = "2011-11-23"
album = "輪るピングディスク VOL.2 オリジナルサウンドトラック"
tracks = [
    [1, "絆・冠葉", "橋本由香利", 0],
    [2, "絆・チェイス", "橋本由香利", 0],
    [3, "やだなにこれ", "橋本由香利", 0],
    [4, "恋のプレリュード", "橋本由香利", 0],
    [5, "オーディオドラマ「多蕗さんだらけの乙女ゲーム」", "[dialogue]", 0],
    [6, "乙女がタタッタ!", "橋本由香利", 0],
    [7, "妄想ワルツ", "橋本由香利", 0],
    [8, "衝撃の真実(カーたんとラッちゃん)", "橋本由香利", 0],
    [9, "ピングミッション・リターンズ", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/b5f4ff2a-8c25-4179-96fa-05a6dedde93c", "https://vgmdb.net/album/30170"]

[bfa702604dc3d5c05220ed0fa10c0e13]
catalognumber = "KICA-3168"
date = "2011-12-21"
album = "HHH / TRIPLE H"
tracks = [
    [1, "ROCK OVER JAPAN", "トリプルH", 0],
    [2, "イカレちまったぜ!!", "トリプルH", 0],
    [3, "BAD NEWS(黒い予感)", "トリプルH", 0],
    [4, "魂こがして", "トリプルH", 0],
    [5, "ダディーズ・シューズ", "トリプルH", 0],
    [6, "Private Girl", "トリプルH", 0],
    [7, "HIDE and SEEK", "トリプルH", 0],
    [8, "朝のかげりの中で", "トリプルH", 0],
    [9, "灰色の水曜日", "トリプルH", 0],
    [10, "HEROES～英雄たち", "トリプルH", 0],
]
links = ["https://beta.musicbrainz.org/release/6517577a-38db-4c38-86a9-3dd9fc7d6251", "https://vgmdb.net/album/30067"]

[ec7ded4a0aaa1e8a764ae77e6ba6730a]
catalognumber = "SSX-10207"
date = "2011-12-21"
album = "輪るピングディスク VOL.3 オリジナルサウンドトラック"
tracks = [
    [1, "もうひとつの世界・予兆", "橋本由香利", 0],
    [2, "あの娘と僕と", "橋本由香利", 0],
    [3, "僕たちの日々", "橋本由香利", 0],
    [4, "ホリデー", "橋本由香利", 0],
    [5, "バーニング", "橋本由香利", 0],
    [6, "オーディオドラマ「陽毬とサンちゃんのワクワク・クッキング!」", "[dialogue]", 0],
    [7, "華麗・そらの孔分室", "橋本由香利", 0],
    [8, "とぎれゆく想い", "橋本由香利", 0],
    [9, "あのとき僕たちは", "橋本由香利", 0],
    [10, "ファミリー", "橋本由香利", 0],
    [11, "夕陽で荒野のデスティニー", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/715ea81f-eb12-4f18-972c-e21d89798e5a", "https://vgmdb.net/album/30701"]

[d34ef7248d9f4c64ca6cb9e8d71fbf96]
catalognumber = "SSX-10208"
date = "2012-01-25"
album = "輪るピングディスク VOL.4 オリジナルサウンドトラック"
tracks = [
    [1, "もうひとつの世界・ミッション", "橋本由香利", 0],
    [2, "ラブプランニング", "橋本由香利", 0],
    [3, "オーディオドラマ「真砂子のTVショッピングでゲッツ!①」", "[dialogue]", 0],
    [4, "ピカレスク", "橋本由香利", 0],
    [5, "まさかの失態", "橋本由香利", 0],
    [6, "オーディオドラマ「真砂子のTVショッピングでゲッツ!②」", "[dialogue]", 0],
    [7, "タマホマレ・ヒメホマレ", "橋本由香利", 0],
    [8, "極限状況", "橋本由香利", 0],
    [9, "オーディオドラマ「真砂子のTVショッピングでゲッツ!③」", "[dialogue]", 0],
    [10, "KYじゃん", "橋本由香利", 0],
    [11, "もうひとつの世界・メリーさんの羊", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/f011c250-8608-481f-b0a3-f56e5bb774ef", "https://vgmdb.net/album/31363"]

[b6350c5a7de55d3889a11a0987eb9b6e]
catalognumber = "KICS-1737"
date = "2012-02-22"
album = "秘密 / 堀江由衣"
tracks = [
    [1, "秘密 〜プロローグ〜", "堀江由衣", 0],
    [2, "kiss to you", "堀江由衣", 0],
    [3, "Coloring", "堀江由衣", 0],
    [4, "True truly love", "堀江由衣", 0],
    [5, "秘密 〜君を見てた〜", "堀江由衣", 0],
    [6, "イマカラキミノモトヘ", "堀江由衣", 0],
    [7, "PRESENTER", "堀江由衣", 0],
    [8, "インモラリスト", "堀江由衣", 0],
    [9, "MISSION", "堀江由衣", 0],
    [10, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
    [11, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [12, "YAHHO!!", "堀江由衣", 0],
    [13, "sky fish", "堀江由衣", 0],
    [14, "秘密 〜待ち合わせ〜", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/ca8a27f8-9cbc-4686-929a-4a1d0730563c", "https://vgmdb.net/album/65824"]

[a0e5ca3b231cae87d3d507851b351d19]
catalognumber = "KICS-91737"
date = "2012-02-22"
album = "秘密 / 堀江由衣 [初回限定盤 春夏]"
tracks = [
    [1, "秘密 ～プロローグ～", "堀江由衣", 0],
    [2, "kiss to you", "堀江由衣", 0],
    [3, "Coloring", "堀江由衣", 0],
    [4, "True truly love", "堀江由衣", 0],
    [5, "秘密 ～君を見てた～", "堀江由衣", 0],
    [6, "イマカラキミノモトヘ", "堀江由衣", 0],
    [7, "PRESENTER", "堀江由衣", 0],
    [8, "インモラリスト", "堀江由衣", 0],
    [9, "MISSION", "堀江由衣", 0],
    [10, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
    [11, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [12, "YAHHO!!", "堀江由衣", 0],
    [13, "sky fish", "堀江由衣", 0],
    [14, "秘密 ～待ち合わせ～", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/5e2afb06-206e-498d-82c4-da73c61c15b8", "https://vgmdb.net/album/65825"]

[3dc26e8e3ada5e09b09e474132445e96]
catalognumber = "SSX-10209"
date = "2012-02-22"
album = "輪るピングディスク VOL.5 オリジナルサウンドトラック"
tracks = [
    [1, "ノルニル (TV‐Size)", "やくしまるえつこメトロオーケストラ", 0],
    [2, "女優マーベラス!", "橋本由香利", 0],
    [3, "オーディオドラマ「大奥・ゆりの巻 其の一」", "[dialogue]", 0],
    [4, "Mの悲劇 -Instrumental-", "橋本由香利", 0],
    [5, "女優エクセレント!", "橋本由香利", 0],
    [6, "オーディオドラマ「大奥・ゆりの巻 其の二」", "[dialogue]", 0],
    [7, "衝撃の一夜", "橋本由香利", 0],
    [8, "市民デスティニー!", "橋本由香利", 0],
    [9, "オーディオドラマ「大奥・ゆりの巻 其の三」", "[dialogue]", 0],
    [10, "口づけのとき", "橋本由香利", 0],
    [11, "もうひとつの世界・破壊神", "橋本由香利", 0],
    [12, "DEAR FUTURE (TV‐Size)", "coaltar of the deepers", 0],
]
links = ["https://beta.musicbrainz.org/release/8afcc20c-c3e2-4520-be49-ddb5c3ef0e79", "https://vgmdb.net/album/31809"]

[e39e915b081544b1dfcd18ba25ff2c0a]
catalognumber = "KICS-91738"
date = "2012-02-22"
album = "秘密 / 堀江由衣 [初回限定盤 秋冬]"
tracks = [
    [1, "秘密 ～プロローグ～", "堀江由衣", 0],
    [2, "kiss to you", "堀江由衣", 0],
    [3, "Coloring", "堀江由衣", 0],
    [4, "True truly love", "堀江由衣", 0],
    [5, "秘密 ～君を見てた～", "堀江由衣", 0],
    [6, "イマカラキミノモトヘ", "堀江由衣", 0],
    [7, "PRESENTER", "堀江由衣", 0],
    [8, "インモラリスト", "堀江由衣", 0],
    [9, "MISSION", "堀江由衣", 0],
    [10, "DEAR FUTURE", "WATCHMAN feat. Yui Horie", 0],
    [11, "CHILDISH LOVE WORLD", "堀江由衣", 0],
    [12, "YAHHO!!", "堀江由衣", 0],
    [13, "sky fish", "堀江由衣", 0],
    [14, "秘密 ～待ち合わせ～", "堀江由衣", 0],
]
links = ["https://beta.musicbrainz.org/release/5cdc70f8-03b9-4bbd-9b18-61f1418fd7c8", "https://vgmdb.net/album/65826"]

[c16fa78c279e847f5f004e96b133886c]
catalognumber = "SSX-10210"
date = "2012-03-28"
album = "輪るピングディスク VOL.6 オリジナルサウンドトラック"
tracks = [
    [1, "もうひとつの世界・闇からの侵攻", "橋本由香利", 0],
    [2, "もうひとつの世界・気配", "橋本由香利", 0],
    [3, "もうひとつの世界・戦い", "橋本由香利", 0],
    [4, "オーディオドラマ「魔球デスティニー・甲子園激闘編 その1」", "[dialogue]", 0],
    [5, "陽だまり", "橋本由香利", 0],
    [6, "あの頃", "橋本由香利", 0],
    [7, "オーディオドラマ「魔球デスティニー・甲子園激闘編 その2」", "[dialogue]", 0],
    [8, "アダルティー", "橋本由香利", 0],
    [9, "ファビュラス", "橋本由香利", 0],
    [10, "オーディオドラマ「魔球デスティニー・甲子園激闘編 その3」", "[dialogue]", 0],
    [11, "DEAR FUTURE (TV‐Size)", "WATCHMAN feat. Yui Horie", 0],
]
links = ["https://beta.musicbrainz.org/release/81c10ad6-f1be-4bc2-b4a3-bb4ad09c18a3", "https://vgmdb.net/album/32795"]

[0de5c8744c8821ab050113a2097d09f4]
catalognumber = "QWCE-00226"
date = "2012-04-04"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 15"
tracks = [
    [1, "残念系隣人部★★☆（星ふたつ半）", "Ryu* feat.mi-mi+R.Cena", 0],
    [2, "空想メソロギヰ", "kinoto feat.R.Cena", 0],
    [3, "BLOOD TELLER", "Hommarju feat.mamiko", 0],
    [4, "ROCK OVER JAPAN", "Hommarju feat.si-na+R.Cena", 0],
    [5, "HIGH POWERED", "Dizzi Mystica feat.mi-mi+JJ", 0],
    [6, "私のキ・モ・チ", "Booing Day feat.Latte", 0],
    [7, "少年よ我に帰れ", "MK feat.405", 0],
    [8, "君の神話〜アクエリオン第二章", "Dizzi Mystica feat.R.Cena", 0],
    [9, "TERMINATED", "Dizzi Mystica feat.YURiE", 0],
    [10, "FLY AWAY", "Icon feat.puchi", 0],
    [11, "YOUTHFUL", "Icon feat.TAKANORI", 0],
    [12, "I'LL BELIEVE", "Dizzi Mystica feat.KANA+TAKANORI", 0],
    [13, "SKY'S THE LIMIT", "Dizzi Mystica feat.YURiE+MFMW", 0],
    [14, "COOLISH WALK", "Dizzi Mystica feat.mi-mi+R.Cena", 0],
    [15, "U-N-D-E-R--STANDING!", "Icon feat.puchi+TAKANORI", 0],
    [16, "紋", "Booing Day feat.yumemi", 0],
    [17, "君の中の英雄", "MK feat.KANA", 0],
    [18, "おかえりなさい", "MK feat.Nahoko", 0],
    [19, "ENDLESS STORY", "Dizzi Mystica feat.Latte", 0],
    [20, "ノルニル", "Hommarju feat.405", 0],
]
links = ["https://beta.musicbrainz.org/release/2b80d131-81ee-4e02-b169-87d60b75f2ab", "https://vgmdb.net/album/32343"]

[1623ce0f9fb60518303c7f4997cf3c18]
catalognumber = "SSX-10211"
date = "2012-04-25"
album = "輪るピングディスク VOL.7 オリジナルサウンドトラック"
tracks = [
    [1, "ROCK OVER JAPAN (TV‐Size)", "トリプルH", 0],
    [2, "オーディオドラマ「Penguin-WAVE #1 ようこそ僕の診察室へ」", "[dialogue]", 0],
    [3, "BAD NEWS(黒い予感) (TV‐Size)", "トリプルH", 0],
    [4, "オーディオドラマ「Penguin-WAVE #2 モノマネグルメ」", "[dialogue]", 0],
    [5, "魂こがして (TV‐Size)", "トリプルH", 0],
    [6, "オーディオドラマ「Penguin-WAVE #3 眞悧・愛の処方箋」", "[dialogue]", 0],
    [7, "イカレちまったぜ!! (TV‐Size)", "トリプルH", 0],
    [8, "運命の子たち・別れ", "橋本由香利", 0],
    [9, "運命の子たち・少女", "橋本由香利", 0],
    [10, "運命の子たち・ギムノパイディア", "橋本由香利", 0],
    [11, "運命の子たち・果実", "橋本由香利", 0],
    [12, "Private Girl (TV‐Size)", "トリプルH", 0],
]
links = ["https://beta.musicbrainz.org/release/13962635-ed74-4dca-9cd3-ba8abfa759d0", "https://vgmdb.net/album/32796"]

[5ca86396d50cf2d071d493ac2742500a]
catalognumber = "SSX-10212"
date = "2012-05-23"
album = "輪るピングディスク VOL.8 オリジナルサウンドトラック"
tracks = [
    [1, "HIDE and SEEK (TV‐Size)", "トリプルH", 0],
    [2, "オーディオドラマ「潮干狩り 一の貝 生存戦略!」", "[dialogue]", 0],
    [3, "朝のかげりの中で (TV‐Size)", "トリプルH", 0],
    [4, "オーディオドラマ「潮干狩り 二の貝 あなたが落としたのは…」", "[dialogue]", 0],
    [5, "HEROES～英雄たち (TV‐Size)", "トリプルH", 0],
    [6, "オーディオドラマ「潮干狩り 三の貝 デスティニー星人」", "[dialogue]", 0],
    [7, "灰色の水曜日 (TV‐Size)", "トリプルH", 0],
    [8, "ナミダの海", "橋本由香利", 0],
    [9, "絆・夢と悪夢と", "橋本由香利", 0],
    [10, "絆・わたしを離さないで", "橋本由香利", 0],
    [11, "運命の子たち・小さな罰", "橋本由香利", 0],
    [12, "絆・輪る果実", "橋本由香利", 0],
    [13, "運命の子たち・蠍の炎", "橋本由香利", 0],
    [14, "運命の子たち・愛してる", "橋本由香利", 0],
    [15, "オーディオドラマ「潮干狩り 星の貝 ずっと一緒だよ」", "[dialogue]", 0],
]
links = ["https://beta.musicbrainz.org/release/8553255a-5497-4fef-aac8-d51a142d545e", "https://vgmdb.net/album/33315"]

[25beb97bf22b705eae140f9c75d39a88]
catalognumber = "XNMR-01225"
date = "2013-04-10"
album = "RADIO ONSEN EUTOPIA / やくしまるえつこ"
tracks = [
    [1, "ノルニル", "やくしまるえつこ", 0],
    [2, "恋するニワトリ", "やくしまるえつこ", 0],
    [3, "ヴィーナスとジーザス", "やくしまるえつこ", 0],
    [4, "COSMOS vs ALIEN", "やくしまるえつこ", 0],
    [5, "北風小僧の寒太郎", "やくしまるえつこ", 0],
    [6, "ヤミヤミ", "やくしまるえつこ", 0],
    [7, "少年よ我に帰れ", "やくしまるえつこ", 0],
    [8, "キャベツUFO", "やくしまるえつこ", 0],
    [9, "ラジャ・マハラジャー", "やくしまるえつこ", 0],
    [10, "ときめきハッカー", "やくしまるえつこ", 0],
    [11, "メトロポリタン美術館", "やくしまるえつこ", 0],
    [12, "ロンリープラネット", "やくしまるえつこ", 0],
]
links = ["https://beta.musicbrainz.org/release/154330f9-fad2-4567-87dc-8012658697d1", "https://vgmdb.net/album/37720"]

[b340c2b12d70ddae774304ffc9b9f711]
catalognumber = "SSX-10341"
date = "2015-02-04"
album = "輪るピングドラム オリジナルサウンドトラック(selected edition)"
tracks = [
    [1, "運命の子たち", "橋本由香利", 0],
    [2, "運命の子たち・別れ (A01G)", "橋本由香利", 0],
    [3, "運命の子たち・少女 (A01I)", "橋本由香利", 0],
    [4, "運命の子たち・ギムノパイディア (A01H3)", "橋本由香利", 0],
    [5, "運命の子たち・果実 (A01F)", "橋本由香利", 0],
    [6, "珊瑚の迷路", "橋本由香利", 0],
    [7, "とぎれゆく想い", "橋本由香利", 0],
    [8, "絆・夢と悪夢と", "橋本由香利", 0],
    [9, "絆・わたしを離さないで", "橋本由香利", 0],
    [10, "絆・輪る果実 (Scene 182 MIX)", "橋本由香利", 0],
    [11, "陽だまり", "橋本由香利", 0],
    [12, "もうひとつの世界・予兆", "橋本由香利", 0],
    [13, "もうひとつの世界・ミッション", "橋本由香利", 0],
    [14, "もうひとつの世界・メリーさんの羊", "橋本由香利", 0],
    [15, "もうひとつの世界・破壊神", "橋本由香利", 0],
    [16, "ピングミッション", "橋本由香利", 0],
    [17, "あの娘と僕と", "橋本由香利", 0],
    [18, "華麗・そらの孔分室", "橋本由香利", 0],
    [19, "Mの悲劇 -Instrumental-", "橋本由香利", 0],
    [20, "キラキラ", "橋本由香利", 0],
    [21, "タマホマレ・ヒメホマレ", "橋本由香利", 0],
    [22, "ナミダの海", "橋本由香利", 0],
    [23, "僕たちの望みの喜びよ", "橋本由香利", 0],
    [24, "もうひとつの世界・闇からの侵攻", "橋本由香利", 0],
    [25, "もうひとつの世界・気配", "橋本由香利", 0],
    [26, "もうひとつの世界・戦い", "橋本由香利", 0],
    [27, "運命の子たち・小さな罰", "橋本由香利", 0],
    [28, "運命の子たち・蠍の炎 (Scene Q38 MIX)", "橋本由香利", 0],
    [29, "運命の子たち・愛してる (Scene Q113 MIX)", "橋本由香利", 0],
    [30, "あのとき僕たちは", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/3d3e70cb-5613-4e7f-8ed6-1407c0497519", "https://vgmdb.net/album/48289"]

[55a02b99e55ff33cd473495d5a0dbab3]
catalognumber = "LACA-15774"
date = "2019-05-29"
album = "RE! RE!! RE!!! / Mia REGINA"
tracks = [
    [1, "Non stop road", "Mia REGINA", 0],
    [2, "マイペース大王", "Mia REGINA", 0],
    [3, "ねぇ、…しようよ!", "Mia REGINA", 0],
    [4, "ありがとう〜", "霧島若歌", 0],
    [5, "VICTORY", "Mia REGINA", 0],
    [6, "シュガーソングとビターステップ", "Mia REGINA", 0],
    [7, "少年よ我に帰れ", "ささかまリス子", 0],
    [8, "Precious Memories", "上花楓裏", 0],
    [9, "STARDOM!", "Mia REGINA", 0],
    [10, "タキシード・ミラージュ", "Mia REGINA", 0],
]
links = ["https://beta.musicbrainz.org/release/26afeeb3-6467-4089-92cd-7083cc469e2c", "https://vgmdb.net/album/84965"]

[d7cfa836f801c92813479bbdf991f39b]
catalognumber = "KICA-2604~5"
date = "2022-07-20"
album = "劇場版「RE:cycle of the PENGUINDRUM」MUSIC COLLECTION Disc 1 [KICA-2604]"
tracks = [
    [1, "銀河は夜の水族館", "橋本由香利", 0],
    [2, "ピーチに乗った彼女", "橋本由香利", 0],
    [3, "僕たちの幸せ", "橋本由香利", 0],
    [4, "ROCK OVER JAPAN", "トリプルH featuring プリンチュペンギン", 0],
    [5, "もうひとつの世界・記された運命", "橋本由香利", 0],
    [6, "冠葉と晶馬・侵入", "橋本由香利", 0],
    [7, "カレーと彼と", "橋本由香利", 0],
    [8, "転がる乙女リターンズ", "橋本由香利", 0],
    [9, "ファンファーレのキス", "橋本由香利", 0],
    [10, "漂流家族", "橋本由香利", 0],
    [11, "食卓の宇宙生命体", "橋本由香利", 0],
    [12, "YELLOW BLOOD", "トリプルH", 0],
    [13, "ファクトリー", "トリプルH", 0],
    [14, "引越しタタッタ!", "橋本由香利", 0],
    [15, "魔術・タマホマレ", "橋本由香利", 0],
    [16, "魔術・プロジェクトM", "橋本由香利", 0],
    [17, "もうひとつの世界・引き裂かれた日記", "橋本由香利", 0],
    [18, "エスカレーターの女", "橋本由香利", 0],
    [19, "スコープの女", "橋本由香利", 0],
    [20, "ハンティングの女", "橋本由香利", 0],
    [21, "友情と鯉と消しゴムと", "橋本由香利", 0],
    [22, "魔術・ヒメホマレ", "橋本由香利", 0],
    [23, "愛と革命のエチュード", "橋本由香利", 0],
    [24, "もうひとつの世界・破壊の日", "橋本由香利", 0],
    [25, "ロールキャベツの約束", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/152a3744-484b-4a4a-a637-9677839e044e", "https://vgmdb.net/album/119922"]

[804d46a814b48f5aa4d1250dfe18c0e0]
catalognumber = "KICA-2604~5"
date = "2022-07-20"
album = "劇場版「RE:cycle of the PENGUINDRUM」MUSIC COLLECTION Disc 2 [KICA-2605]"
tracks = [
    [1, "手のひらに乗る宇宙", "橋本由香利", 0],
    [2, "追放と封印", "橋本由香利", 0],
    [3, "僕と君の真実", "橋本由香利", 0],
    [4, "Private Girl 秘め事", "トリプルH", 0],
    [5, "ゆりと桃果・神さまの作った世界 「灰色の水曜日」より", "橋本由香利", 0],
    [6, "もうひとつの世界・悪のタワー", "橋本由香利", 0],
    [7, "灰色の水曜日 それからの私たち", "トリプルH", 0],
    [8, "もうひとつの世界・黄昏", "橋本由香利", 0],
    [9, "多蕗と桃果・籠と解放と終末と", "橋本由香利", 0],
    [10, "もうひとつの世界・聖なる戦い", "橋本由香利", 0],
    [11, "運命の子たち・君のために生きたい", "橋本由香利", 0],
    [12, "AFTER’45", "トリプルH", 0],
    [13, "運命の子たち・透明と果実と", "橋本由香利", 0],
    [14, "冠葉と晶馬・ピカレスク", "橋本由香利", 0],
    [15, "Just a 16", "トリプルH", 0],
    [16, "ダブルHが来た!", "橋本由香利", 0],
    [17, "運命の子たち・お願い神さま", "橋本由香利", 0],
    [18, "MURDER GAME", "トリプルH", 0],
    [19, "見つけてあげて", "橋本由香利", 0],
    [20, "暗闇と希望の光", "橋本由香利", 0],
    [21, "もうひとつの世界・止められない運命", "橋本由香利", 0],
    [22, "運命の子たち・輪る果実", "橋本由香利", 0],
    [23, "HEROES〜英雄たち 運命の乗り換え", "トリプルH", 0],
    [24, "ピーチに乗った彼女・きっと何者かになれる", "橋本由香利", 0],
    [25, "運命の子たち・愛してる", "橋本由香利", 0],
]
links = ["https://beta.musicbrainz.org/release/152a3744-484b-4a4a-a637-9677839e044e", "https://vgmdb.net/album/119922"]

[2a6a7c76612345f12f72f1d9029fa359]
catalognumber = "QEJY-8940"
date = "2022-10-12"
album = "僕の存在証明 / やくしまるえつこメトロオーケストラ"
tracks = [
    [1, "僕の存在証明", "やくしまるえつこメトロオーケストラ", 0],
    [2, "OUR GROUND ZEROES", "やくしまるえつこメトロオーケストラ", 0],
    [3, "僕の存在証明 (Instrumental)", "やくしまるえつこメトロオーケストラ", 0],
    [4, "OUR GROUND ZEROES (Instrumental)", "やくしまるえつこメトロオーケストラ", 0],
]
links = ["https://beta.musicbrainz.org/release/46b656f1-b87d-4e07-9521-ea651bbe9b7c", "https://vgmdb.net/album/121992"]

[0ebf90c9a7c43558bb6b66511b8d38c7]
catalognumber = "QECY-8940"
date = "2022-10-12"
album = "僕の存在証明 / やくしまるえつこメトロオーケストラ"
tracks = [
    [1, "僕の存在証明", "やくしまるえつこメトロオーケストラ", 0],
    [2, "OUR GROUND ZEROES", "やくしまるえつこメトロオーケストラ", 0],
    [3, "僕の存在証明 (Instrumental)", "やくしまるえつこメトロオーケストラ", 0],
    [4, "OUR GROUND ZEROES (Instrumental)", "やくしまるえつこメトロオーケストラ", 0],
]
links = ["https://beta.musicbrainz.org/release/f109abca-68b9-49e7-821e-2517e293e1e8", "https://vgmdb.net/album/120212"]
