[cd66e1619641b977ddd5af703e8d292c]
catalognumber = "BRMM-10425"
date = "2021-08-18"
album = "Live Beyond!! / Poppin'Party"
tracks = [
    [1, "Live Beyond!!", "Poppin'Party", 0],
    [2, "Sweets BAN!", "Poppin'Party", 0],
    [3, "キミが始まる!", "Poppin'Party", 0],
    [4, "Moonlight Walk", "Poppin'Party", 0],
    [5, "ここから先は歌にならない", "Poppin'Party", 0],
]
links = ["https://beta.musicbrainz.org/release/98d8de9f-6e3e-49da-b7bf-468859f4e06f", "https://vgmdb.net/album/111089"]

[5208551ec2714955cbad5295efea1caf]
catalognumber = "BRMM-10424"
date = "2021-08-18"
album = "Live Beyond!! / Poppin'Party [生産限定盤] Vocal"
tracks = [
    [1, "Live Beyond!!", "Poppin'Party", 0],
    [2, "Sweets BAN!", "Poppin'Party", 0],
    [3, "キミが始まる!", "Poppin'Party", 0],
    [4, "Moonlight Walk", "Poppin'Party", 0],
    [5, "ここから先は歌にならない", "Poppin'Party", 0],
]
links = ["https://beta.musicbrainz.org/release/180581c5-1135-401b-b0cc-00c61d8ab620", "https://vgmdb.net/album/111090"]

[2c36d36b8e67e317c59fbdb8d9099e25]
catalognumber = "BRMM-10424"
date = "2021-08-18"
album = "Live Beyond!! / Poppin'Party [生産限定盤] Vocal, Live Event, Video"
tracks = [
    [1, "「Live Beyond!!」MV", "Poppin'Party", 0],
    [2, "Time Lapse", "Poppin'Party", 0],
    [3, "イニシャル", "Poppin'Party", 0],
    [4, "夏のドーン！", "Poppin'Party", 0],
    [5, "夏空 SUN! SUN! SEVEN!", "Poppin'Party", 0],
    [6, "八月のif", "Poppin'Party", 0],
    [7, "ときめきエクスペリエンス！", "Poppin'Party", 0],
    [8, "STAR BEAT!～ホシノコドウ～", "Poppin'Party", 0],
    [9, "ティアドロップス", "Poppin'Party", 0],
    [10, "ミライトレイン", "Poppin'Party", 0],
    [11, "幕間映像Ⅲ", "Poppin'Party", 0],
    [12, "夢を撃ち抜く瞬間に！", "Poppin'Party with 湊友希那(CV.相羽あいな) & LAYER(CV.Raychell)", 0],
    [13, "全力！バンドリ！タイムズ前編", "Poppin'Party", 0],
    [14, "全力！バンドリ！タイムズ後編", "Poppin'Party", 0],
]
links = ["https://beta.musicbrainz.org/release/180581c5-1135-401b-b0cc-00c61d8ab620", "https://vgmdb.net/album/111090"]

[392e4a4b547afa7afd3b98aaef15fd34]
catalognumber = "N/A"
date = "2021-10-04"
album = "進化→LOVE♡ / サリア(CV:花澤香菜) & サリア(進化前)(CV:稲田徹)"
tracks = [
    [1, "進化→LOVE♡", "", 0],
]
links = ["https://vgmdb.net/album/115286"]

[598b9d09acf4ca0cf5c433af3fcb9489]
catalognumber = "GNCA-0647"
date = "2021-11-10"
album = "EVOLUTiON: / 南條愛乃"
tracks = [
    [1, "EVOLUTiON:", "南條愛乃", 0],
    [2, "全ては不確かな世界", "南條愛乃", 0],
    [3, "EVOLUTiON: <instrumental>", "南條愛乃", 0],
    [4, "全ては不確かな世界 <instrumental>", "南條愛乃", 0],
]
links = ["https://beta.musicbrainz.org/release/17b075a5-e75a-4d43-bd38-427ad272d4a0", "https://vgmdb.net/album/113933"]

[697362dd8505fee6edc463d9b72e9057]
catalognumber = "GNCA-0646"
date = "2021-11-10"
album = "EVOLUTiON: / 南條愛乃 [初回限定盤] Vocal"
tracks = [
    [1, "EVOLUTiON:", "南條愛乃", 0],
    [2, "全ては不確かな世界", "南條愛乃", 0],
    [3, "EVOLUTiON: <instrumental>", "南條愛乃", 0],
    [4, "全ては不確かな世界 <instrumental>", "南條愛乃", 0],
]
links = ["https://beta.musicbrainz.org/release/5a9c139d-da71-4f80-8e93-a7a6d430ec16", "https://vgmdb.net/album/113934"]

[af118404ac3a8575d9e71330e0c8daf4]
catalognumber = "GNCA-0646"
date = "2021-11-10"
album = "EVOLUTiON: / 南條愛乃 [初回限定盤] Vocal, Video"
tracks = [
    [1, "EVOLUTiON: MV", "南條愛乃", 0],
    [2, "EVOLUTiON: MV Making", "南條愛乃", 0],
    [3, "SPOT", "南條愛乃", 0],
]
links = ["https://beta.musicbrainz.org/release/5a9c139d-da71-4f80-8e93-a7a6d430ec16", "https://vgmdb.net/album/113934"]

[7169d628ce8be4a7f180b15f04403e95]
catalognumber = "GNXL-1009"
date = "2022-12-21"
album = "ジャーニーズ・トランク ～Memorial Music Clips～ / 南條愛乃"
tracks = [
    [1, "blue <short size>", "", 0],
    [2, "君が笑む夕暮れ", "", 0],
    [3, "あなたの愛した世界", "", 0],
    [4, "黄昏のスタアライト", "", 0],
    [5, "きみを探しに", "", 0],
    [6, "ゼロイチキセキ", "", 0],
    [7, "光のはじまり", "", 0],
    [8, "一切は物語 (feat.やなぎなぎ)", "", 0],
    [9, "君のとなり わたしの場所", "", 0],
    [10, "サヨナラの惑星", "", 0],
    [11, "藪の中のジンテーゼ", "", 0],
    [12, "believe in myself -acoustic arrange making MV-", "", 0],
    [13, "涙流るるまま", "", 0],
    [14, "EVOLUTiON:", "", 0],
    [15, "A Tiny Winter Story (MV version)", "", 0],
    [16, "A Tiny Winter Story (Lyric Video version)", "", 0],
    [17, "ヒトリとキミと", "", 0],
    [18, "ジャーニーズ・トランク", "", 0],
]
links = ["https://vgmdb.net/album/123908"]

[78bdf539e46ff1039ae22eb2289417a9]
catalognumber = "GNCA-1629"
date = "2022-12-21"
album = "ジャーニーズ・トランク / 南條愛乃 Vocal"
tracks = [
    [1, "blue -青の記憶-", "南條愛乃", 0],
    [2, "最初の10歩", "南條愛乃", 0],
    [3, "雨音と潮騒", "南條愛乃", 0],
    [4, "シンプル", "南條愛乃", 0],
    [5, "EVOLUTiON:", "南條愛乃", 0],
    [6, "この胸に名もなき星", "南條愛乃", 0],
    [7, "静夜行", "南條愛乃", 0],
    [8, "IRO", "南條愛乃", 0],
    [9, "ヒトリとキミと", "南條愛乃", 0],
    [10, "ヨルゴト", "南條愛乃", 0],
    [11, "Lonely voyage", "南條愛乃", 0],
    [12, "ハートリップ", "南條愛乃", 0],
    [13, "ジャーニーズ・トランク", "南條愛乃", 0],
]
links = ["https://beta.musicbrainz.org/release/7b5d513f-c8c5-4f2d-8b61-911b024b81fd", "https://vgmdb.net/album/123907"]

[8fd5175271ed429106a9f5c3a04af0b2]
catalognumber = "GNCA-1629"
date = "2022-12-21"
album = "ジャーニーズ・トランク / 南條愛乃 Arrangement, Vocal"
tracks = [
    [1, "鏖鋸・シュルシャガナ", "南條愛乃", 0],
    [2, "SENSE OF DISTANCE", "南條愛乃", 0],
    [3, "冬がくれた予感", "南條愛乃", 0],
    [4, "Lost Heaven", "南條愛乃", 0],
    [5, "ココロノエデン", "南條愛乃", 0],
]
links = ["https://beta.musicbrainz.org/release/7b5d513f-c8c5-4f2d-8b61-911b024b81fd", "https://vgmdb.net/album/123907"]

[86342213583baeaad66e54d5fa335a94]
catalognumber = "GNCA-1629"
date = "2022-12-21"
album = "ジャーニーズ・トランク / 南條愛乃 Vocal, Video"
tracks = [
    [1, "ジャーニーズ・トランク (MV) <short ver.>", "南條愛乃", 0],
    [2, "南條一間 〜シーズン6〜 #01 じじいとわたしと10周年", "南條愛乃", 0],
    [3, "南條一間 〜シーズン6〜 #02 じじいとわたしとパーティー", "南條愛乃", 0],
    [4, "南條一間 〜シーズン6〜 #03 じじいとわたしと旅", "南條愛乃", 0],
    [5, "南條一間 〜シーズン6〜 #04 じじいとわたしとシーリングスタンプ", "南條愛乃", 0],
    [6, "南條一間 〜シーズン6〜 #05 じじいとわたしと梅干し", "南條愛乃", 0],
    [7, "南條一間 〜シーズン6〜 #06 じじいとわたしとロビンとマッシュ", "南條愛乃", 0],
]
links = ["https://beta.musicbrainz.org/release/7b5d513f-c8c5-4f2d-8b61-911b024b81fd", "https://vgmdb.net/album/123907"]

[77c6e606c431188f3d6ffd2f05980d6f]
catalognumber = "N/A"
date = "2023-01-14"
album = "Evolution / ナノ"
tracks = [
    [1, "Evolution", "ナノ", 0],
]
links = ["https://beta.musicbrainz.org/release/5cca50b1-ad51-4327-b255-0fc957dfa079", "https://vgmdb.net/album/126481"]

[e6a6a33c5a8271816f3e4f48dca1a035]
catalognumber = "CERI-6001B"
date = "2023-01-25"
album = "Adore me / 山崎エリイ [アニメ盤]"
tracks = [
    [1, "Adore me", "山崎エリイ", 0],
    [2, "いっそ", "山崎エリイ", 0],
]
links = ["https://beta.musicbrainz.org/release/a8d9cf34-18e9-4705-831f-dc7cfcec9ee0", "https://vgmdb.net/album/125142"]

[6866c8b2267d8534a35f7b978b527190]
catalognumber = "CERI-6001A"
date = "2023-01-25"
album = "Adore me / 山崎エリイ"
tracks = [
    [1, "Adore me", "山崎エリイ", 0],
    [2, "いっそ", "山崎エリイ", 0],
]
links = ["https://beta.musicbrainz.org/release/15219c80-9646-4512-a0d6-ce6a4ac4a04b", "https://vgmdb.net/album/125141"]

[a5f6c63bfd909887189273525636eb61]
catalognumber = "COCX-41945~6"
date = "2023-02-08"
album = "NOIXE / ナノ Vocal"
tracks = [
    [1, "Evolution", "ナノ", 0],
    [2, "FIGHT SONG", "ナノ", 0],
    [3, "We Are The Vanguard", "ナノ with DEMONDICE", 0],
    [4, "Heart of Glass", "ナノ", 0],
    [5, "Let's Make Noise", "ナノ", 0],
    [6, "Broken Voices", "ナノ with KIHOW from MYTH & ROID", 0],
    [7, "CATASTROPHE", "ナノ", 0],
    [8, "Happiness", "ナノ", 0],
    [9, "A Nameless Color", "ナノ with __(アンダーバー)", 0],
    [10, "Circle of Stars", "ナノ", 0],
]
links = ["https://beta.musicbrainz.org/release/eebcc771-014f-4540-8190-0c5107224567", "https://vgmdb.net/album/124769"]

[34bc5f959e95012aa1d4df2c71286758]
catalognumber = "COCX-41945~6"
date = "2023-02-08"
album = "NOIXE / ナノ Arrangement, Vocal"
tracks = [
    [1, "Rolling Star", "ナノ", 0],
    [2, "TRUTH〜A Great Detective of Love〜", "ナノ", 0],
    [3, "リライト", "ナノ", 0],
    [4, "God knows…", "ナノ", 0],
    [5, "深い森", "ナノ", 0],
]
links = ["https://beta.musicbrainz.org/release/287b738e-f643-4cf2-a3b9-32ad9930d3af", "https://vgmdb.net/album/124769"]

[36db20a6f205731477a314a83adae878]
catalognumber = "N/A"
date = "2023-05-29"
album = "真・進化の実～知らないうちに勝ち組人生～ オリジナル・サウンドトラック"
tracks = [
    [1, "Theme of Shin-Shinka no mi", "", 0],
    [2, "デストラのテーマ", "", 0],
    [3, "ハーバトル魔法学園", "", 0],
    [4, "嬉しくなるよね", "", 0],
    [5, "誠一の過去", "", 0],
    [6, "穏やかな日々の中で", "", 0],
    [7, "問題児ばっか・・・", "", 0],
    [8, "不穏な予兆", "", 0],
    [9, "魔神教団", "", 0],
    [10, "ガールズトーク", "", 0],
    [11, "ドタバタ系", "", 0],
    [12, "into the battle", "", 0],
    [13, "暗闇での暗躍", "", 0],
    [14, "仲間と共に掴む勝利", "", 0],
    [15, "悩みの種", "", 0],
    [16, "誠一のテーマ", "", 0],
    [17, "In progress", "", 0],
    [18, "パーティーコール", "", 0],
    [19, "勝利の喜び", "", 0],
    [20, "はじまりはじまり～♪", "", 0],
    [21, "どうなっちゃうのー!?", "", 0],
    [22, "ズッコケちゃうよね", "", 0],
    [23, "自分を偽ってでも", "", 0],
    [24, "真実の告白", "", 0],
    [25, "親愛", "", 0],
    [26, "黒き感情", "", 0],
    [27, "魔神復活の予兆", "", 0],
    [28, "極秘プロジェクト", "", 0],
    [29, "戦いの火蓋", "", 0],
    [30, "反撃の狼煙", "", 0],
    [31, "決意を胸に", "", 0],
    [32, "無慈悲の旋律", "", 0],
    [33, "死の恐怖", "", 0],
    [34, "異世界の中の異界", "", 0],
    [35, "君も行きたいか!", "", 0],
    [36, "魔王国の日常", "", 0],
    [37, "テンプテーション", "", 0],
    [38, "Detective", "", 0],
    [39, "デストラの過去", "", 0],
    [40, "魔神窟", "", 0],
    [41, "きっと大丈夫", "", 0],
    [42, "最悪の目醒め", "", 0],
    [43, "真・誠一のテーマ", "", 0],
    [44, "呪縛からの解放", "", 0],
    [45, "ようやく答えが!", "", 0],
    [46, "閃き", "", 0],
]
links = ["https://vgmdb.net/album/129909"]
