[a22b959170aebdb0d42aba191106ce19]
catalognumber = "AUCL-134"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ"
tracks = [
    [1, "Hello Especially", "スキマスイッチ", 1],
    [2, "サウンドオブ", "スキマスイッチ", 1],
    [3, "10th -type Ⅱ- (instrumental)", "スキマスイッチ", 1],
    [4, "Hello Especially (anime ver.)", "スキマスイッチ", 1],
    [5, "Hello Especially (backing track)", "スキマスイッチ", 1],
]
links = ["https://beta.musicbrainz.org/release/2719c863-4f3a-44df-b1e5-717c7dfc5e8f", "https://vgmdb.net/album/39947"]

[3673c4215516ed5aaa5db0f03ce55bcd]
catalognumber = "AUCL-30003~4"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ Disc 1 (Blu-spec CD2) [AUCL-30003]"
tracks = [
    [1, "Hello Especially", "スキマスイッチ", 1],
    [2, "サウンドオブ", "スキマスイッチ", 1],
    [3, "10th –type II– (instrumental)", "スキマスイッチ", 1],
    [4, "Hello Especially (backing track)", "スキマスイッチ", 1],
]
links = ["https://beta.musicbrainz.org/release/067e6c81-691f-4e07-8fd8-e1d45d87a726", "https://vgmdb.net/album/39949"]

[5f25318af44523f1a32f7b79e1a5090f]
catalognumber = "AUCL-30003~4"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ Disc 2 (DVD) [AUCL-30004]"
tracks = [
    [1, "Hello Especially –video clip–", "スキマスイッチ", 1],
    [2, "Hello Especially –video clip making–", "スキマスイッチ", 1],
]
links = ["https://beta.musicbrainz.org/release/067e6c81-691f-4e07-8fd8-e1d45d87a726", "https://vgmdb.net/album/39949"]

[d79415cadd11900808439212164b6d51]
catalognumber = "AUCL-135"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ"
tracks = [
    [1, "Hello Especially", "スキマスイッチ", 1],
    [2, "サウンドオブ", "スキマスイッチ", 1],
    [3, "10th -type Ⅱ- (instrumental)", "スキマスイッチ", 1],
    [4, "Hello Especially (backing track)", "スキマスイッチ", 1],
]
links = ["https://beta.musicbrainz.org/release/cbf20eb3-af17-437e-8ae0-5628c0faafa8", "https://vgmdb.net/album/39948"]

[d36e2c55cfd1733ed7fd2d4b8ac3da48]
catalognumber = "SRCL-8348~9"
date = "2013-09-04"
album = "Faraway/Kiss you / miwa [初回生産限定盤] Vocal"
tracks = [
    [1, "Faraway", "miwa", 1],
    [2, "Kiss you", "miwa", 1],
    [3, "Delight <ballad version>", "miwa", 1],
    [4, "Faraway ～instrumental～", "miwa", 1],
    [5, "Kiss you ～instrumental～", "miwa", 1],
]
links = ["https://beta.musicbrainz.org/release/32e46100-92ee-44f7-b33e-080877a18bc8", "https://vgmdb.net/album/40160"]

[cb67650b709190cc7805a606f5bb3ed6]
catalognumber = "SRCL-8348~9"
date = "2013-09-04"
album = "Faraway/Kiss you / miwa [初回生産限定盤] Video"
tracks = [
    [1, "Kiss you (Video Clip)", "", 1],
    [2, "Kiss you (Making of)", "", 1],
]
links = ["https://vgmdb.net/album/40160"]

[b13cb81d8a4a1995cb32314365f6866f]
catalognumber = "SRCL-8350"
date = "2013-09-04"
album = "Faraway/Kiss you / miwa"
tracks = [
    [1, "Faraway", "miwa", 1],
    [2, "Kiss you", "miwa", 1],
    [3, "Delight <ballad version>", "miwa", 1],
    [4, "Faraway ～instrumental～", "miwa", 1],
    [5, "Kiss you ～instrumental～", "miwa", 1],
]
links = ["https://beta.musicbrainz.org/release/32e46100-92ee-44f7-b33e-080877a18bc8", "https://vgmdb.net/album/40161"]

[dbee1c31e4a6e4b0daa7f6c0d2751a63]
catalognumber = "SRCL-8351"
date = "2013-09-04"
album = "Kiss you/Faraway / miwa [Limited Edition]"
tracks = [
    [1, "Kiss you", "miwa", 1],
    [2, "Faraway", "miwa", 1],
    [3, "Delight <ballad version>", "miwa", 1],
    [4, "Kiss you ～instrumental～", "miwa", 1],
    [5, "Faraway ～instrumental～", "miwa", 1],
]
links = ["https://beta.musicbrainz.org/release/42241a36-8216-4e5e-a36c-d7c0d9425acb", "https://vgmdb.net/album/40162"]

[f56b12e2380c39f673e490cce93eb581]
catalognumber = "ANZX-6302"
date = "2013-09-18"
album = "銀の匙 Silver Spoon 第1巻 特典CD"
tracks = [
    [1, "大蝦夷農業高校校歌 (Animation Cast ver.)", "[unknown]", 1],
    [2, "大蝦夷農業高校校歌 (Animation Cast ver. Instrumental)", "[unknown]", 1],
]
links = ["https://beta.musicbrainz.org/release/9155030e-d601-44bf-a20a-6d40a71bd32c", "https://vgmdb.net/album/40370"]

[63f6d027628df60af358d5cc5a281001]
catalognumber = "ANZX-6304"
date = "2013-10-23"
album = "銀の匙 Silver Spoon 第2巻 特典CD"
tracks = [
    [1, "激録!農工戦の裏側に潜む罠!?女子♀編", "木村良平, 三宅麻理恵, 櫻井トオル, 高垣彩陽, 島崎信長, 庄司将之, 高梨謙吾, こぶしのぶゆき, 井澤詩織, 増谷康紀, 川原慶久, 蓮岳大", 1],
]
links = ["https://beta.musicbrainz.org/release/508283c3-70ea-49d5-8f8b-4306178f984b", "https://vgmdb.net/album/40648"]

[aa6f166c81a2fac7a6be29055aae756a]
catalognumber = "ANZX-6308"
date = "2013-12-25"
album = "銀の匙 Silver Spoon 第4巻 特典CD"
tracks = [
    [1, "銀の匙 Silver Spoon メインテーマ", "村井秀清", 1],
    [2, "エゾノー アレンジ2", "村井秀清", 1],
    [3, "教室 アレンジ1", "村井秀清", 1],
    [4, "御影", "村井秀清", 1],
    [5, "凍る大地", "村井秀清", 1],
    [6, "輓馬レース", "村井秀清", 1],
    [7, "酪農 アレンジ3", "村井秀清", 1],
    [8, "トラブルメーカー", "村井秀清", 1],
    [9, "エゾノー アレンジ3", "村井秀清", 1],
    [10, "銀の匙 Silver Spoon メインテーマ アレンジ3", "村井秀清", 1],
]
links = ["https://beta.musicbrainz.org/release/3e29c1c0-b313-4a56-acc1-d9d2a9ef6144", "https://vgmdb.net/album/43272"]

[dca1997bb439735af34adb1be8a8e332]
catalognumber = "ANZX-6310"
date = "2014-01-22"
album = "銀の匙 Vol.5 特典CDラジオ「エゾノー、食の祭典」"
tracks = [
    [1, "Track 1", "", 1],
    [2, "Track 2", "", 1],
    [3, "Track 3", "", 1],
    [4, "Track 4", "", 1],
]
links = ["https://vgmdb.net/album/45699"]

[1f8917678974674b5e114d3bd3af6f86]
catalognumber = "AICL-2634"
date = "2014-02-12"
album = "LIFE / フジファブリック"
tracks = [
    [1, "LIFE", "フジファブリック", 1],
    [2, "Surrender", "フジファブリック", 1],
    [3, "LIFE (backing track)", "フジファブリック", 1],
]
links = ["https://beta.musicbrainz.org/release/bcfdf1cb-4ecc-468c-bb44-ff3a4a1b65d5", "https://vgmdb.net/album/42863"]

[5baf2be7e8900b85bba3e8e1f7b4d5ea]
catalognumber = "AICL-2632~3"
date = "2014-02-12"
album = "LIFE / フジファブリック Disc 1 [AICL-2632]"
tracks = [
    [1, "LIFE", "フジファブリック", 1],
    [2, "Surrender", "フジファブリック", 1],
    [3, "LIFE (backing track)", "フジファブリック", 1],
]
links = ["https://beta.musicbrainz.org/release/b05b7d5c-abed-42c1-9e22-7a42abd12cfc", "https://vgmdb.net/album/42862"]

[234f6a164c9ba114a1fbab7bfde3f799]
catalognumber = "AICL-2632~3"
date = "2014-02-12"
album = "LIFE / フジファブリック Disc 2 [AICL-2633]"
tracks = [
    [1, "FAB STEP OP", "フジファブリック", 1],
    [2, "フラッシュダンス", "フジファブリック", 1],
    [3, "Hello", "フジファブリック", 1],
    [4, "Mystery Tour", "フジファブリック", 1],
    [5, "パッション・フルーツ", "フジファブリック", 1],
    [6, "Drop", "フジファブリック", 1],
    [7, "バタアシParty Night", "フジファブリック", 1],
    [8, "ダンス2000", "フジファブリック", 1],
]
links = ["https://beta.musicbrainz.org/release/b05b7d5c-abed-42c1-9e22-7a42abd12cfc", "https://vgmdb.net/album/42862"]

[0ad086464e04e48be632576b9f9418ce]
catalognumber = "AICL-2635"
date = "2014-02-12"
album = "LIFE / フジファブリック"
tracks = [
    [1, "LIFE", "フジファブリック", 1],
    [2, "Surrender", "フジファブリック", 1],
    [3, "LIFE (backing track)", "フジファブリック", 1],
    [4, "LIFE (TV edit)", "フジファブリック", 1],
]
links = ["https://beta.musicbrainz.org/release/8f75edc1-9b19-480e-bea9-312ed675551c", "https://vgmdb.net/album/42864"]

[98eca1bdb738e81d06ad8dec1e167bef]
catalognumber = "SRCL-8471"
date = "2014-02-19"
album = "オトノナルホウヘ→ / Goose house"
tracks = [
    [1, "オトノナルホウヘ→", "Goose house", 1],
    [2, "恋はヒラひらり", "Goose house", 1],
    [3, "オトノナルホウヘ→ -TV Size-", "Goose house", 1],
    [4, "オトノナルホウヘ→ -instrumental-", "Goose house", 1],
]
links = ["https://beta.musicbrainz.org/release/2f65908d-80b4-4481-8460-2dc799d55baa", "https://vgmdb.net/album/42735"]

[b4662a7fc5a8458b2f1439ce82609d91]
catalognumber = "SRCL-8472~3"
date = "2014-02-19"
album = "オトノナルホウヘ→ / Goose house [期間生産限定盤] Disc 1 (CD) [SRCL-8472]"
tracks = [
    [1, "オトノナルホウヘ→", "Goose house", 1],
    [2, "恋はヒラひらり", "Goose house", 1],
    [3, "オトノナルホウヘ→ -TV Size-", "Goose house", 1],
    [4, "オトノナルホウヘ→ -instrumental-", "Goose house", 1],
]
links = ["https://beta.musicbrainz.org/release/131d5ac0-2580-4063-b3fa-568f0c6d3943", "https://vgmdb.net/album/42736"]

[06760a88bf0ce4681e8659151cfa999c]
catalognumber = "SRCL-8472~3"
date = "2014-02-19"
album = "オトノナルホウヘ→ / Goose house [期間生産限定盤] Disc 2 (DVD) [SRCL-8473]"
tracks = [
    [1, "オトノナルホウヘ→ Music Video", "Goose house", 1],
]
links = ["https://beta.musicbrainz.org/release/131d5ac0-2580-4063-b3fa-568f0c6d3943", "https://vgmdb.net/album/42736"]

[7746e709d850241c4bca2bb62edddea4]
catalognumber = "SVWC-7994"
date = "2014-03-21"
album = "TVアニメ 銀の匙 Silver Spoon オリジナル・サウンドトラック"
tracks = [
    [1, "銀の匙 Silver Spoon メインテーマ", "村井秀清", 1],
    [2, "エゾノー", "村井秀清", 1],
    [3, "御影", "村井秀清", 1],
    [4, "輓馬レース", "村井秀清", 1],
    [5, "酪農 アレンジ2", "村井秀清", 1],
    [6, "銀の匙 Silver Spoon メインテーマ アレンジ3", "村井秀清", 1],
    [7, "エゾノー アレンジ4", "村井秀清", 1],
    [8, "脱走", "村井秀清", 1],
    [9, "トラブルメーカー", "村井秀清", 1],
    [10, "不安", "村井秀清", 1],
    [11, "解体", "村井秀清", 1],
    [12, "銀の匙 Silver Spoon メインテーマ アレンジ1", "村井秀清", 1],
    [13, "大地", "村井秀清", 1],
    [14, "叶わぬもの", "村井秀清", 1],
    [15, "銀の匙 Silver Spoon メインテーマ アレンジ7", "村井秀清", 1],
    [16, "エゾノー アレンジ2", "村井秀清", 1],
    [17, "ギガファーム", "村井秀清", 1],
    [18, "遁走", "村井秀清", 1],
    [19, "行けエゾノー", "村井秀清", 1],
    [20, "秋期大会", "村井秀清", 1],
    [21, "新人戦", "村井秀清", 1],
    [22, "エゾノー アレンジ3", "村井秀清", 1],
    [23, "銀の匙 Silver Spoon メインテーマ アレンジ2", "村井秀清", 1],
    [24, "教室", "村井秀清", 1],
    [25, "酪農", "村井秀清", 1],
    [26, "エゾノー アレンジ1", "村井秀清", 1],
    [27, "銀の匙 Silver Spoon メインテーマ アレンジ5", "村井秀清", 1],
]
links = ["https://beta.musicbrainz.org/release/7a48b8e2-f18f-48c2-9b6e-61bfe47af917", "https://vgmdb.net/album/43951"]

[e052ed2b3ae1f6c6b82b52b2a622213c]
catalognumber = "ANZX-6312"
date = "2014-03-26"
album = "銀の匙 Vol.6 特典CDラジオ「エゾノー、座談会」"
tracks = [
    [1, "Track 1", "", 1],
    [2, "Track 2", "", 1],
    [3, "Track 3", "", 1],
    [4, "Track 4", "", 1],
]
links = ["https://vgmdb.net/album/45707"]

[31caf277e6c2756948ec62dfce1c00b4]
catalognumber = "UMCA-19062"
date = "2020-08-19"
album = "スキマノハナタバ～Smile Song Selection～ / スキマスイッチ Vocal"
tracks = [
    [1, "全力少年 Remastered", "スキマスイッチ", 0],
    [2, "夏のコスモナウト", "スキマスイッチ", 0],
    [3, "青春", "スキマスイッチ", 0],
    [4, "ガラナ", "スキマスイッチ", 0],
    [5, "ミスターカイト", "スキマスイッチ", 0],
    [6, "星のうつわ", "スキマスイッチ", 0],
    [7, "かけら ほのか", "スキマスイッチ", 0],
    [8, "Hello Especially", "スキマスイッチ", 1],
    [9, "LとR", "スキマスイッチ", 0],
    [10, "トラベラーズ・ハイ", "スキマスイッチ", 0],
    [11, "Ah Yeah!!", "スキマスイッチ", 0],
    [12, "ゴールデンタイムラバー", "スキマスイッチ", 0],
    [13, "晴ときどき曇", "スキマスイッチ", 0],
    [14, "あけたら", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/32b53399-5317-450e-94ec-8017abd1c92d", "https://vgmdb.net/album/101177"]

[062d97962fbfd69a69370b5ac392d5fb]
catalognumber = "UMCA-19062"
date = "2020-08-19"
album = "スキマノハナタバ～Smile Song Selection～ / スキマスイッチ Video"
tracks = [
    [1, "あけたら Recording Making", "", 0],
    [2, "スキマノハナタバ ～Smile Song Selection～ Special Interview", "", 0],
]
links = ["https://vgmdb.net/album/101177"]

[b51c9dd088a3ee7304878ae65a41e2b7]
catalognumber = "UMCA-10076"
date = "2020-08-19"
album = "スキマノハナタバ～Smile Song Selection～ / スキマスイッチ"
tracks = [
    [1, "全力少年 Remastered", "スキマスイッチ", 0],
    [2, "夏のコスモナウト", "スキマスイッチ", 0],
    [3, "青春", "スキマスイッチ", 0],
    [4, "ガラナ", "スキマスイッチ", 0],
    [5, "ミスターカイト", "スキマスイッチ", 0],
    [6, "星のうつわ", "スキマスイッチ", 0],
    [7, "かけら ほのか", "スキマスイッチ", 0],
    [8, "Hello Especially", "スキマスイッチ", 1],
    [9, "LとR", "スキマスイッチ", 0],
    [10, "トラベラーズ・ハイ", "スキマスイッチ", 0],
    [11, "Ah Yeah!!", "スキマスイッチ", 0],
    [12, "ゴールデンタイムラバー", "スキマスイッチ", 0],
    [13, "晴ときどき曇", "スキマスイッチ", 0],
    [14, "あけたら", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/32b53399-5317-450e-94ec-8017abd1c92d", "https://vgmdb.net/album/101176"]
