[f1fba2f66554a663ebadb736aaa75253]
catalognumber = "AUCL-134"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ"
tracks = [
    [1, "Hello Especially", "スキマスイッチ", 0],
    [2, "サウンドオブ", "スキマスイッチ", 0],
    [3, "10th -type Ⅱ- (instrumental)", "スキマスイッチ", 0],
    [4, "Hello Especially (anime ver.)", "スキマスイッチ", 0],
    [5, "Hello Especially (backing track)", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/2719c863-4f3a-44df-b1e5-717c7dfc5e8f", "https://vgmdb.net/album/39947"]

[1e8477d901f29ed8971dda3006527edb]
catalognumber = "AUCL-30003~4"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ Disc 1 (Blu-spec CD2) [AUCL-30003]"
tracks = [
    [1, "Hello Especially", "スキマスイッチ", 0],
    [2, "サウンドオブ", "スキマスイッチ", 0],
    [3, "10th –type II– (instrumental)", "スキマスイッチ", 0],
    [4, "Hello Especially (backing track)", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/067e6c81-691f-4e07-8fd8-e1d45d87a726", "https://vgmdb.net/album/39949"]

[93c7d8ac94a0a8263fd0cce40b637787]
catalognumber = "AUCL-30003~4"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ Disc 2 (DVD) [AUCL-30004]"
tracks = [
    [1, "Hello Especially –video clip–", "スキマスイッチ", 0],
    [2, "Hello Especially –video clip making–", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/067e6c81-691f-4e07-8fd8-e1d45d87a726", "https://vgmdb.net/album/39949"]

[71b39ed74b36702caa37643908079e87]
catalognumber = "AUCL-135"
date = "2013-07-31"
album = "Hello Especially / スキマスイッチ"
tracks = [
    [1, "Hello Especially", "スキマスイッチ", 0],
    [2, "サウンドオブ", "スキマスイッチ", 0],
    [3, "10th -type Ⅱ- (instrumental)", "スキマスイッチ", 0],
    [4, "Hello Especially (backing track)", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/cbf20eb3-af17-437e-8ae0-5628c0faafa8", "https://vgmdb.net/album/39948"]

[b1d8ccba36addc79e7f0afcc3537e482]
catalognumber = "SRCL-8348~9"
date = "2013-09-04"
album = "Faraway/Kiss you / miwa [初回生産限定盤] Vocal"
tracks = [
    [1, "Faraway", "miwa", 0],
    [2, "Kiss you", "miwa", 0],
    [3, "Delight <ballad version>", "miwa", 0],
    [4, "Faraway ～instrumental～", "miwa", 0],
    [5, "Kiss you ～instrumental～", "miwa", 0],
]
links = ["https://beta.musicbrainz.org/release/32e46100-92ee-44f7-b33e-080877a18bc8", "https://vgmdb.net/album/40160"]

[b275d8afc3cba35b207fba30cb00df27]
catalognumber = "SRCL-8348~9"
date = "2013-09-04"
album = "Faraway/Kiss you / miwa [初回生産限定盤] Video"
tracks = [
    [1, "Kiss you (Video Clip)", "", 0],
    [2, "Kiss you (Making of)", "", 0],
]
links = ["https://vgmdb.net/album/40160"]

[35600af9a4a757cd1a641ec14f122b1e]
catalognumber = "SRCL-8350"
date = "2013-09-04"
album = "Faraway/Kiss you / miwa"
tracks = [
    [1, "Faraway", "miwa", 0],
    [2, "Kiss you", "miwa", 0],
    [3, "Delight <ballad version>", "miwa", 0],
    [4, "Faraway ～instrumental～", "miwa", 0],
    [5, "Kiss you ～instrumental～", "miwa", 0],
]
links = ["https://beta.musicbrainz.org/release/32e46100-92ee-44f7-b33e-080877a18bc8", "https://vgmdb.net/album/40161"]

[5408569411074a651ba775890ae7764c]
catalognumber = "SRCL-8351"
date = "2013-09-04"
album = "Kiss you/Faraway / miwa [Limited Edition]"
tracks = [
    [1, "Kiss you", "miwa", 0],
    [2, "Faraway", "miwa", 0],
    [3, "Delight <ballad version>", "miwa", 0],
    [4, "Kiss you ～instrumental～", "miwa", 0],
    [5, "Faraway ～instrumental～", "miwa", 0],
]
links = ["https://beta.musicbrainz.org/release/42241a36-8216-4e5e-a36c-d7c0d9425acb", "https://vgmdb.net/album/40162"]

[0a6bbbfb7f528d6283c072316ae163e9]
catalognumber = "ANZX-6302"
date = "2013-09-18"
album = "銀の匙 Silver Spoon 第1巻 特典CD"
tracks = [
    [1, "大蝦夷農業高校校歌 (Animation Cast ver.)", "[unknown]", 0],
    [2, "大蝦夷農業高校校歌 (Animation Cast ver. Instrumental)", "[unknown]", 0],
]
links = ["https://beta.musicbrainz.org/release/9155030e-d601-44bf-a20a-6d40a71bd32c", "https://vgmdb.net/album/40370"]

[74fb0343a5ca82b95250c56ce840c11d]
catalognumber = "ANZX-6304"
date = "2013-10-23"
album = "銀の匙 Silver Spoon 第2巻 特典CD"
tracks = [
    [1, "激録!農工戦の裏側に潜む罠!?女子♀編", "木村良平, 三宅麻理恵, 櫻井トオル, 高垣彩陽, 島崎信長, 庄司将之, 高梨謙吾, こぶしのぶゆき, 井澤詩織, 増谷康紀, 川原慶久, 蓮岳大", 0],
]
links = ["https://beta.musicbrainz.org/release/508283c3-70ea-49d5-8f8b-4306178f984b", "https://vgmdb.net/album/40648"]

[c9aaa7c91d01379a4d44837ee578db77]
catalognumber = "ANZX-6308"
date = "2013-12-25"
album = "銀の匙 Silver Spoon 第4巻 特典CD"
tracks = [
    [1, "銀の匙 Silver Spoon メインテーマ", "村井秀清", 0],
    [2, "エゾノー アレンジ2", "村井秀清", 0],
    [3, "教室 アレンジ1", "村井秀清", 0],
    [4, "御影", "村井秀清", 0],
    [5, "凍る大地", "村井秀清", 0],
    [6, "輓馬レース", "村井秀清", 0],
    [7, "酪農 アレンジ3", "村井秀清", 0],
    [8, "トラブルメーカー", "村井秀清", 0],
    [9, "エゾノー アレンジ3", "村井秀清", 0],
    [10, "銀の匙 Silver Spoon メインテーマ アレンジ3", "村井秀清", 0],
]
links = ["https://beta.musicbrainz.org/release/3e29c1c0-b313-4a56-acc1-d9d2a9ef6144", "https://vgmdb.net/album/43272"]

[8589f238440de3ba06455d2fe869c903]
catalognumber = "ANZX-6310"
date = "2014-01-22"
album = "銀の匙 Vol.5 特典CDラジオ「エゾノー、食の祭典」"
tracks = [
    [1, "Track 1", "", 0],
    [2, "Track 2", "", 0],
    [3, "Track 3", "", 0],
    [4, "Track 4", "", 0],
]
links = ["https://vgmdb.net/album/45699"]

[8c6c31e3615d7e7088f48fe49a5ea5e2]
catalognumber = "AICL-2634"
date = "2014-02-12"
album = "LIFE / フジファブリック"
tracks = [
    [1, "LIFE", "フジファブリック", 0],
    [2, "Surrender", "フジファブリック", 0],
    [3, "LIFE (backing track)", "フジファブリック", 0],
]
links = ["https://beta.musicbrainz.org/release/bcfdf1cb-4ecc-468c-bb44-ff3a4a1b65d5", "https://vgmdb.net/album/42863"]

[630250f4e34d0ef7acf386cc9d4521ab]
catalognumber = "AICL-2632~3"
date = "2014-02-12"
album = "LIFE / フジファブリック Disc 1 [AICL-2632]"
tracks = [
    [1, "LIFE", "フジファブリック", 0],
    [2, "Surrender", "フジファブリック", 0],
    [3, "LIFE (backing track)", "フジファブリック", 0],
]
links = ["https://beta.musicbrainz.org/release/b05b7d5c-abed-42c1-9e22-7a42abd12cfc", "https://vgmdb.net/album/42862"]

[fdac61ef631616c03a24038182694144]
catalognumber = "AICL-2632~3"
date = "2014-02-12"
album = "LIFE / フジファブリック Disc 2 [AICL-2633]"
tracks = [
    [1, "FAB STEP OP", "フジファブリック", 0],
    [2, "フラッシュダンス", "フジファブリック", 0],
    [3, "Hello", "フジファブリック", 0],
    [4, "Mystery Tour", "フジファブリック", 0],
    [5, "パッション・フルーツ", "フジファブリック", 0],
    [6, "Drop", "フジファブリック", 0],
    [7, "バタアシParty Night", "フジファブリック", 0],
    [8, "ダンス2000", "フジファブリック", 0],
]
links = ["https://beta.musicbrainz.org/release/b05b7d5c-abed-42c1-9e22-7a42abd12cfc", "https://vgmdb.net/album/42862"]

[b97d7610734703d5038caef2ea55fc53]
catalognumber = "AICL-2635"
date = "2014-02-12"
album = "LIFE / フジファブリック"
tracks = [
    [1, "LIFE", "フジファブリック", 0],
    [2, "Surrender", "フジファブリック", 0],
    [3, "LIFE (backing track)", "フジファブリック", 0],
    [4, "LIFE (TV edit)", "フジファブリック", 0],
]
links = ["https://beta.musicbrainz.org/release/8f75edc1-9b19-480e-bea9-312ed675551c", "https://vgmdb.net/album/42864"]

[3cbf3494830288464da051d94c86b301]
catalognumber = "SRCL-8471"
date = "2014-02-19"
album = "オトノナルホウヘ→ / Goose house"
tracks = [
    [1, "オトノナルホウヘ→", "Goose house", 0],
    [2, "恋はヒラひらり", "Goose house", 0],
    [3, "オトノナルホウヘ→ -TV Size-", "Goose house", 0],
    [4, "オトノナルホウヘ→ -instrumental-", "Goose house", 0],
]
links = ["https://beta.musicbrainz.org/release/2f65908d-80b4-4481-8460-2dc799d55baa", "https://vgmdb.net/album/42735"]

[a8467fde250705d6b5d19a86c42f5eee]
catalognumber = "SRCL-8472~3"
date = "2014-02-19"
album = "オトノナルホウヘ→ / Goose house [期間生産限定盤] Disc 1 (CD) [SRCL-8472]"
tracks = [
    [1, "オトノナルホウヘ→", "Goose house", 0],
    [2, "恋はヒラひらり", "Goose house", 0],
    [3, "オトノナルホウヘ→ -TV Size-", "Goose house", 0],
    [4, "オトノナルホウヘ→ -instrumental-", "Goose house", 0],
]
links = ["https://beta.musicbrainz.org/release/131d5ac0-2580-4063-b3fa-568f0c6d3943", "https://vgmdb.net/album/42736"]

[4207a4e1febe0867dc68ca4be220f5ba]
catalognumber = "SRCL-8472~3"
date = "2014-02-19"
album = "オトノナルホウヘ→ / Goose house [期間生産限定盤] Disc 2 (DVD) [SRCL-8473]"
tracks = [
    [1, "オトノナルホウヘ→ Music Video", "Goose house", 0],
]
links = ["https://beta.musicbrainz.org/release/131d5ac0-2580-4063-b3fa-568f0c6d3943", "https://vgmdb.net/album/42736"]

[6bdd259530a8cdbcf5cc7f0a0a93213d]
catalognumber = "SVWC-7994"
date = "2014-03-21"
album = "TVアニメ 銀の匙 Silver Spoon オリジナル・サウンドトラック"
tracks = [
    [1, "銀の匙 Silver Spoon メインテーマ", "村井秀清", 0],
    [2, "エゾノー", "村井秀清", 0],
    [3, "御影", "村井秀清", 0],
    [4, "輓馬レース", "村井秀清", 0],
    [5, "酪農 アレンジ2", "村井秀清", 0],
    [6, "銀の匙 Silver Spoon メインテーマ アレンジ3", "村井秀清", 0],
    [7, "エゾノー アレンジ4", "村井秀清", 0],
    [8, "脱走", "村井秀清", 0],
    [9, "トラブルメーカー", "村井秀清", 0],
    [10, "不安", "村井秀清", 0],
    [11, "解体", "村井秀清", 0],
    [12, "銀の匙 Silver Spoon メインテーマ アレンジ1", "村井秀清", 0],
    [13, "大地", "村井秀清", 0],
    [14, "叶わぬもの", "村井秀清", 0],
    [15, "銀の匙 Silver Spoon メインテーマ アレンジ7", "村井秀清", 0],
    [16, "エゾノー アレンジ2", "村井秀清", 0],
    [17, "ギガファーム", "村井秀清", 0],
    [18, "遁走", "村井秀清", 0],
    [19, "行けエゾノー", "村井秀清", 0],
    [20, "秋期大会", "村井秀清", 0],
    [21, "新人戦", "村井秀清", 0],
    [22, "エゾノー アレンジ3", "村井秀清", 0],
    [23, "銀の匙 Silver Spoon メインテーマ アレンジ2", "村井秀清", 0],
    [24, "教室", "村井秀清", 0],
    [25, "酪農", "村井秀清", 0],
    [26, "エゾノー アレンジ1", "村井秀清", 0],
    [27, "銀の匙 Silver Spoon メインテーマ アレンジ5", "村井秀清", 0],
]
links = ["https://beta.musicbrainz.org/release/7a48b8e2-f18f-48c2-9b6e-61bfe47af917", "https://vgmdb.net/album/43951"]

[c5b73bb711b076a80b4e8d46836254e9]
catalognumber = "ANZX-6312"
date = "2014-03-26"
album = "銀の匙 Vol.6 特典CDラジオ「エゾノー、座談会」"
tracks = [
    [1, "Track 1", "", 0],
    [2, "Track 2", "", 0],
    [3, "Track 3", "", 0],
    [4, "Track 4", "", 0],
]
links = ["https://vgmdb.net/album/45707"]

[347db192cea099af4621e6406d35c585]
catalognumber = "COCC-17527"
date = "2020-03-18"
album = "THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER 37 Needle Light"
tracks = [
    [1, "Needle Light (M@STER VERSION)", "荒木比奈(CV:田辺留依)、上条春菜(CV:長島光那)", 0],
    [2, "タッタ", "多田李衣菜(CV:青木瑠璃子)、木村夏樹(CV:安野希世乃)", 0],
    [3, "LIFE", "姫川友紀(CV:杜野まこ)", 0],
    [4, "RAGE OF DUST", "早坂美玲(CV:朝井彩加)", 0],
    [5, "Needle Light (M@STER VERSION) (オリジナル・カラオケ)", "上条春菜(CV:長島光那)、荒木比奈(CV:田辺留依)", 0],
    [6, "Needle Light (Game Version)", "上条春菜(CV:長島光那)、荒木比奈(CV:田辺留依)", 0],
]
links = ["https://beta.musicbrainz.org/release/3c1e4571-1094-4cd9-91a9-033ef3cf033c", "https://vgmdb.net/album/96538"]

[8cf709819f6c42ec52bbc0cb0533dcb8]
catalognumber = "COCC-17529"
date = "2020-06-10"
album = "THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER 39 O-Ku-Ri-Mo-No Sunday!"
tracks = [
    [1, "O-Ku-Ri-Mo-No Sunday! (M@STER VERSION)", "久川凪(CV:立花日菜)、久川颯(CV:長江里加)", 0],
    [2, "Hello Especially", "川島瑞樹(CV:東山奈央)", 0],
    [3, "全力☆Summer!", "棟方愛海(CV:藤本彩花)", 0],
    [4, "行くぜっ!怪盗少女", "及川雫(CV:のぐちゆり)、片桐早苗(CV:和氣あず未)、堀裕子(CV:鈴木絵理)", 0],
    [5, "O-Ku-Ri-Mo-No Sunday! (M@STER VERSION) (オリジナル・カラオケ)", "久川颯(CV:長江里加)、久川凪(CV:立花日菜)", 0],
    [6, "O-Ku-Ri-Mo-No Sunday! (GAME VERSION)", "久川颯(CV:長江里加)、久川凪(CV:立花日菜)", 0],
]
links = ["https://beta.musicbrainz.org/release/5472ec89-3e22-4963-a756-0d1cc3a3671a", "https://vgmdb.net/album/98666"]

[57c5d100e7b976b50aa1b8a994fd3cfe]
catalognumber = "UMCA-19062"
date = "2020-08-19"
album = "スキマノハナタバ～Smile Song Selection～ / スキマスイッチ Vocal"
tracks = [
    [1, "全力少年 Remastered", "スキマスイッチ", 0],
    [2, "夏のコスモナウト", "スキマスイッチ", 0],
    [3, "青春", "スキマスイッチ", 0],
    [4, "ガラナ", "スキマスイッチ", 0],
    [5, "ミスターカイト", "スキマスイッチ", 0],
    [6, "星のうつわ", "スキマスイッチ", 0],
    [7, "かけら ほのか", "スキマスイッチ", 0],
    [8, "Hello Especially", "スキマスイッチ", 0],
    [9, "LとR", "スキマスイッチ", 0],
    [10, "トラベラーズ・ハイ", "スキマスイッチ", 0],
    [11, "Ah Yeah!!", "スキマスイッチ", 0],
    [12, "ゴールデンタイムラバー", "スキマスイッチ", 0],
    [13, "晴ときどき曇", "スキマスイッチ", 0],
    [14, "あけたら", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/32b53399-5317-450e-94ec-8017abd1c92d", "https://vgmdb.net/album/101177"]

[859de0f10bbf00faf1806d11ec59a8fc]
catalognumber = "UMCA-19062"
date = "2020-08-19"
album = "スキマノハナタバ～Smile Song Selection～ / スキマスイッチ Video"
tracks = [
    [1, "あけたら Recording Making", "", 0],
    [2, "スキマノハナタバ ～Smile Song Selection～ Special Interview", "", 0],
]
links = ["https://vgmdb.net/album/101177"]

[56a5bc7a395c113570f8b8945512b530]
catalognumber = "UMCA-10076"
date = "2020-08-19"
album = "スキマノハナタバ～Smile Song Selection～ / スキマスイッチ"
tracks = [
    [1, "全力少年 Remastered", "スキマスイッチ", 0],
    [2, "夏のコスモナウト", "スキマスイッチ", 0],
    [3, "青春", "スキマスイッチ", 0],
    [4, "ガラナ", "スキマスイッチ", 0],
    [5, "ミスターカイト", "スキマスイッチ", 0],
    [6, "星のうつわ", "スキマスイッチ", 0],
    [7, "かけら ほのか", "スキマスイッチ", 0],
    [8, "Hello Especially", "スキマスイッチ", 0],
    [9, "LとR", "スキマスイッチ", 0],
    [10, "トラベラーズ・ハイ", "スキマスイッチ", 0],
    [11, "Ah Yeah!!", "スキマスイッチ", 0],
    [12, "ゴールデンタイムラバー", "スキマスイッチ", 0],
    [13, "晴ときどき曇", "スキマスイッチ", 0],
    [14, "あけたら", "スキマスイッチ", 0],
]
links = ["https://beta.musicbrainz.org/release/32b53399-5317-450e-94ec-8017abd1c92d", "https://vgmdb.net/album/101176"]
