[d647bb9d5c2516e54305c3d8229656fb]
catalognumber = "ZMCZ-16041"
date = "2022-10-26"
album = "HIGHEST / OxT"
tracks = [
    [1, "HIGHEST", "OxT", 0],
    [2, "Paradisus‐Paradoxum(Mare Tranquillitatis)", "OxT", 0],
    [3, "HIGHEST(instrumental)", "OxT", 0],
    [4, "Paradisus‐Paradoxum(Mare Tranquillitatis)(instrumental)", "OxT", 0],
]
links = ["https://beta.musicbrainz.org/release/ec35d6ca-a266-4712-a551-7970a5b466f9", "https://vgmdb.net/album/122598"]

[69731c4e6de5fdd7adff981a9f3e753e]
catalognumber = "ZMCZ-16042"
date = "2022-11-30"
album = "Darling in the Night / 七陰"
tracks = [
    [1, "Darling in the Night", "七陰", 0],
    [2, "蒼い閃光", "シャドウ(CV:山下誠一郎)", 0],
    [3, "Darling in the Night(instrumental)", "七陰", 0],
    [4, "蒼い閃光(instrumental)", "シャドウ(CV:山下誠一郎)", 0],
]
links = ["https://beta.musicbrainz.org/release/20130827-7991-4424-8582-ab91306b65e6", "https://vgmdb.net/album/122851"]

[d131c407e9341173c681b0afb9e6d658]
catalognumber = "ZMCZ-16582"
date = "2023-03-29"
album = "TVアニメ「陰の実力者になりたくて!」オリジナルサウンドトラック"
tracks = [
    [1, "Theme of Cid Kagenou", "末廣健一郎", 0],
    [2, "Fight in The Darkness", "末廣健一郎", 0],
    [3, "My Master", "末廣健一郎", 0],
    [4, "School Life", "末廣健一郎", 0],
    [5, "Peaceful Days", "末廣健一郎", 0],
    [6, "Get Confused", "末廣健一郎", 0],
    [7, "Sulky Mood", "末廣健一郎", 0],
    [8, "Little Confusing", "末廣健一郎", 0],
    [9, "Bad Company", "末廣健一郎", 0],
    [10, "Prestigious School", "末廣健一郎", 0],
    [11, "End of the Day", "末廣健一郎", 0],
    [12, "Blessed Time", "末廣健一郎", 0],
    [13, "Carefree Atmosphere", "末廣健一郎", 0],
    [14, "Confront Each Other", "末廣健一郎", 0],
    [15, "Think About Something", "末廣健一郎", 0],
    [16, "Upsetting", "末廣健一郎", 0],
    [17, "Showing Off", "末廣健一郎", 0],
    [18, "Pathos", "末廣健一郎", 0],
    [19, "Heavy Breeze", "末廣健一郎", 0],
    [20, "One Step Ahead", "末廣健一郎", 0],
    [21, "Unsurpassable Magic", "末廣健一郎", 0],
    [22, "Fierce Assault", "末廣健一郎", 0],
    [23, "Into Madness", "末廣健一郎", 0],
    [24, "Monologue", "末廣健一郎", 0],
    [25, "Just Teasing You", "末廣健一郎", 0],
    [26, "Lovely Day", "末廣健一郎", 0],
    [27, "Full of Grace", "末廣健一郎", 0],
    [28, "Arrongant Attitude", "末廣健一郎", 0],
    [29, "Get Bewildered", "末廣健一郎", 0],
    [30, "Piece of Cake", "末廣健一郎", 0],
    [31, "Arrogance", "末廣健一郎", 0],
    [32, "Beginning of the War", "末廣健一郎", 0],
    [33, "Making Precise Strategy", "末廣健一郎", 0],
    [34, "A Conspiracy", "末廣健一郎", 0],
    [35, "Sweat with Fear", "末廣健一郎", 0],
    [36, "Acting like extra", "末廣健一郎", 0],
    [37, "By Degrees", "末廣健一郎", 0],
    [38, "Eerie Fog", "末廣健一郎", 0],
    [39, "Ritual Act", "末廣健一郎", 0],
    [40, "Victory Plan", "末廣健一郎", 0],
    [41, "Weave a Plot", "末廣健一郎", 0],
    [42, "Nothing to Hide", "末廣健一郎", 0],
    [43, "Speculation", "末廣健一郎", 0],
    [44, "Battle-Hardened", "末廣健一郎", 0],
    [45, "A Critical Moment", "末廣健一郎", 0],
    [46, "Escape from the Target", "末廣健一郎", 0],
    [47, "Fall into the Cold Sea", "末廣健一郎", 0],
    [48, "Dark Side", "末廣健一郎", 0],
    [49, "Kind and Warm", "末廣健一郎", 0],
    [50, "With Tenderness", "末廣健一郎", 0],
    [51, "A tear ran down Someone's Cheek", "末廣健一郎", 0],
    [52, "Someday I wish", "末廣健一郎", 0],
    [53, "Black Heart", "末廣健一郎", 0],
    [54, "Seasow Battle", "末廣健一郎", 0],
    [55, "The Path of Awakening", "末廣健一郎", 0],
    [56, "In Time of War", "末廣健一郎", 0],
    [57, "Lose Ground", "末廣健一郎", 0],
    [58, "Deep Sorrow", "末廣健一郎", 0],
    [59, "Enough to Overwhelm", "末廣健一郎", 0],
    [60, "Battle Begins", "末廣健一郎", 0],
    [61, "Piano Sonata No. 14, \"Moonlight\": I. Adagio sostenuto", "末廣健一郎", 0],
]
links = ["https://beta.musicbrainz.org/release/069b05e8-eecf-4d6d-aab1-8741f404f888", "https://vgmdb.net/album/127324"]

[01ee328bfb0714ccfcd2f4200fa55408]
catalognumber = "ZMCZ-17011"
date = "2023-10-05"
album = "grayscale dominator / OxT"
tracks = [
    [1, "grayscale dominator", "OxT", 0],
    [2, "grayscale dominator (instrumental)", "OxT", 0],
]
links = ["https://beta.musicbrainz.org/release/0b295614-1370-4764-ad8a-54cd3f5c671f", "https://vgmdb.net/album/132869"]

[dd08a3e60181ffd6ac6030c021d66292]
catalognumber = "ZMCZ-17012"
date = "2023-10-12"
album = "Polaris in the Night / シャドウガーデンナンバーズ"
tracks = [
    [1, "Polaris in the Night", "シャドウガーデンナンバーズ", 0],
    [2, "Polaris in the Night (instrumental)", "シャドウガーデンナンバーズ", 0],
]
links = ["https://beta.musicbrainz.org/release/1b12bc58-df1b-46d0-b55f-46e6837bab0e", "https://vgmdb.net/album/132870"]

[ff05e7074017aa7c7ed7085a21f62181]
catalognumber = "ZMCZ-17013"
date = "2023-11-16"
album = "Everything is Changing / 前島麻由"
tracks = [
    [1, "Everything is Changing", "前島麻由", 0],
    [2, "Everything is Changing(instrumental)", "前島麻由", 0],
]
links = ["https://beta.musicbrainz.org/release/740d5530-e22f-4fd2-9ef4-c1e8b5abb57f", "https://vgmdb.net/album/135419"]

[8c2fc8ff8aea34fe656289c37e214e02]
catalognumber = "ZMCZ-16776"
date = "2023-12-26"
album = "TVアニメ「陰の実力者になりたくて！ 2nd season」オリジナルサウンドトラック"
tracks = [
    [1, "Red Moon", "末廣健一郎", 0],
    [2, "All of Them", "末廣健一郎", 0],
    [3, "Stratagem", "末廣健一郎", 0],
    [4, "Grandiose Plan", "末廣健一郎", 0],
    [5, "Lawless City", "末廣健一郎", 0],
    [6, "Yukime", "末廣健一郎", 0],
    [7, "Unknown Past", "末廣健一郎", 0],
    [8, "Invisible Movement", "末廣健一郎", 0],
    [9, "Severe Blow", "末廣健一郎", 0],
    [10, "Severe Blow Version Pipe Organ", "末廣健一郎", 0],
    [11, "Secret Beast", "末廣健一郎", 0],
    [12, "The Queen", "末廣健一郎", 0],
    [13, "Here Comes", "末廣健一郎", 0],
    [14, "Behind The Scenes", "末廣健一郎", 0],
    [15, "Mary", "末廣健一郎", 0],
    [16, "Sense of Emptiness", "末廣健一郎", 0],
    [17, "Rethink", "末廣健一郎", 0],
    [18, "Super Elite Agent", "末廣健一郎", 0],
    [19, "Sumptuously Decorated", "末廣健一郎", 0],
    [20, "Conversation", "末廣健一郎", 0],
    [21, "Overflow with Feelings", "末廣健一郎", 0],
    [22, "Feel Light", "末廣健一郎", 0],
    [23, "Knowing Everything", "末廣健一郎", 0],
    [24, "Piano Sonata No. 14, \"Moonlight\": I. Adagio sostenuto Pipe Organ Arrangement", "末廣健一郎", 0],
    [25, "Pleasant Day", "末廣健一郎", 0],
    [26, "Detailed Description", "末廣健一郎", 0],
    [27, "Almost There...", "末廣健一郎", 0],
    [28, "The Panic", "末廣健一郎", 0],
    [29, "Concentrate on The Goal", "末廣健一郎", 0],
    [30, "Three-sided Fight", "末廣健一郎", 0],
    [31, "Furious Battle", "末廣健一郎", 0],
    [32, "Get Started", "末廣健一郎", 0],
    [33, "The Great Theme of Cid Kagenou", "末廣健一郎", 0],
]
links = ["https://beta.musicbrainz.org/release/1001f89f-7234-47a7-b164-0ea0f6dc1374", "https://vgmdb.net/album/135170"]
