[38f3e18d9b117c76272f782b819412a5]
catalognumber = "KICM-3232"
date = "2011-04-27"
album = "Os-宇宙人 / エリオをかまってちゃん"
tracks = [
    [1, "Os-宇宙人", "エリオをかまってちゃん", 0],
    [2, "コタツから眺める世界地図", "エリオをかまってちゃん", 0],
    [3, "Os-宇宙人 (off vocal ver.)", "エリオをかまってちゃん", 0],
    [4, "コタツから眺める世界地図 (off vocal ver.)", "エリオをかまってちゃん", 0],
]
links = ["https://beta.musicbrainz.org/release/64e7fd74-85ce-4a7e-9327-c6e1441165ec", "https://vgmdb.net/album/26027"]

[5b3e3027f32447d9b9fad2a4d4c9f0c4]
catalognumber = "KICM-1340"
date = "2011-05-25"
album = "ルル/ときめきハッカー / やくしまるえつこ"
tracks = [
    [1, "ルル", "やくしまるえつこ", 0],
    [2, "ときめきハッカー", "やくしまるえつこ", 0],
    [3, "ルル(off vocal ver.)", "やくしまるえつこ", 0],
    [4, "ときめきハッカー(off vocal ver.)", "やくしまるえつこ", 0],
    [5, "ルル(tv-size)", "やくしまるえつこ", 0],
    [6, "ときめきハッカー(EOG only)", "やくしまるえつこ", 0],
]
links = ["https://beta.musicbrainz.org/release/678b91d1-2ca2-4112-933e-388e25443ad0", "https://vgmdb.net/album/30236"]

[0bc22658b2243502f2b8f56d5ad6588b]
catalognumber = "SSX-10195"
date = "2011-06-22"
album = "電波女と青春男・オリジナルサウンドトラック Vol.1"
tracks = [
    [1, "電波女と青春男 (vocal version)", "Franz Maxwell I.", 0],
    [2, "Honesty", "Franz Maxwell I.", 0],
    [3, "Sunny Day", "Franz Maxwell I.", 0],
    [4, "New Life", "Franz Maxwell I.", 0],
    [5, "成層圏から指令がきてるの", "Franz Maxwell I.", 0],
    [6, "Search", "Franz Maxwell I.", 0],
    [7, "Whats is this SUMAKI!", "Franz Maxwell I.", 0],
    [8, "Memories", "Franz Maxwell I.", 0],
    [9, "Moonlight", "Franz Maxwell I.", 0],
    [10, "Labyrinth", "Franz Maxwell I.", 0],
    [11, "コスプレ協奏曲", "Franz Maxwell I.", 0],
    [12, "Emergency", "Franz Maxwell I.", 0],
    [13, "Crying", "Franz Maxwell I.", 0],
    [14, "夕暮れの頃", "Franz Maxwell I.", 0],
    [15, "貧血少女", "Franz Maxwell I.", 0],
    [16, "フルーツはすき", "Franz Maxwell I.", 0],
    [17, "キノコはきらい", "Franz Maxwell I.", 0],
    [18, "よるのうみ", "Franz Maxwell I.", 0],
    [19, "Splash", "Franz Maxwell I.", 0],
    [20, "Os-宇宙人 (TV-SIZE)", "エリオをかまってちゃん", 0],
]
links = ["https://beta.musicbrainz.org/release/66f5a28a-0cbd-4c88-b741-7bd5e74ce15b", "https://vgmdb.net/album/26155"]

[892c097b08456d198bb2a00c2e7751df]
catalognumber = "SSX-10196"
date = "2011-07-27"
album = "［電波メールと青春ラジオ］DJCD vol.1"
tracks = [
    [1, "[第1回]ゲスト", "渕上舞", 0],
    [2, "[第2回]ゲスト", "加藤英美里", 0],
    [3, "[第3回]ゲスト", "野中藍", 0],
]
links = ["https://beta.musicbrainz.org/release/7e1175af-122f-4534-83a5-a8d3a3d3a49f"]

[54a2c02401c4cc5d36ce70f8e0381c9f]
catalognumber = "QWCE-00194"
date = "2011-08-03"
album = "EXIT TRANCE PRESENTS SPEED アニメトランス BEST 13"
tracks = [
    [1, "コネクト", "plazma feat.Nahoko", 0],
    [2, "CORE PRIDE", "Hommarju feat.TAKANORI", 0],
    [3, "魔・カ・セ・テ Tonight", "Booing Day feat.MAKI", 0],
    [4, "ぱんでみっく!", "Hommarju feat.mi-mi", 0],
    [5, "Destin Histoire", "Icon feat.JJ", 0],
    [6, "インモラリスト", "Hommarju feat.R.Cena+hideki", 0],
    [7, "RPG", "Booing Day feat.puchi", 0],
    [8, "わが名は小学生", "Dizzi Mystica feat.405+mi-mi", 0],
    [9, "Choose my love!", "Booing Day feat.KANA", 0],
    [10, "Morning Arch", "Dizzi Mystica feat.YURiE", 0],
    [11, "A Whole New World God Only Knows", "Hommarju feat.R.Cena", 0],
    [12, "Scarlet Ballet", "Dizzi Mystica feat.mi-mi", 0],
    [13, "STRAIGHT JET", "MK feat.Latte", 0],
    [14, "Taste of Paradise", "Dizzi Mystica feat.yumemi", 0],
    [15, "Os-宇宙人", "Dizzi Mystica feat.mi-mi", 0],
    [16, "SHINY SHINY", "MK feat.405", 0],
    [17, "SCARLET KNIGHT", "Dizzi Mystica feat.Latte", 0],
    [18, "青い栞", "Icon feat.Yusuke+yuno", 0],
    [19, "Magia", "Dizzi Mystica feat.Natsuhi+R.Cena", 0],
]
links = ["https://beta.musicbrainz.org/release/212e98cc-5094-428f-8042-5fade11a7075", "https://vgmdb.net/album/29349"]

[932feaa2f548c1bf299d318b4504e023]
catalognumber = "SSX-10197"
date = "2011-08-24"
album = "電波女と青春男 キャラクターソングアルバムvol.1"
tracks = [
    [1, "イトコ", "藤和エリオ(CV:大亀あすか)", 0],
    [2, "昼休みとヘルメットと同級生", "御船流子(CV:加藤英美里)", 0],
    [3, "キボネング・デコの名で", "前川さん(CV:渕上舞)", 0],
]
links = ["https://beta.musicbrainz.org/release/9d08e581-6ace-49c4-94c8-30331fd9cfac", "https://vgmdb.net/album/26157"]

[4b3d320731c5042b8ddb0d2d5f7d2f64]
catalognumber = "SSX-10198"
date = "2011-10-26"
album = "電波女と青春男 オリジナルサウンドトラックvol.2"
tracks = [
    [1, "でんぱおんなとせいしゅんおとこ", "Franz Maxwell I.", 0],
    [2, "Fresh Start", "Franz Maxwell I.", 0],
    [3, "そりゃないぜ", "Franz Maxwell I.", 0],
    [4, "対流圏からも指令なの", "Franz Maxwell I.", 0],
    [5, "ま、嘘だけど", "Franz Maxwell I.", 0],
    [6, "真の秘密", "Franz Maxwell I.", 0],
    [7, "解放への疾走", "Franz Maxwell I.", 0],
    [8, "No way", "Franz Maxwell I.", 0],
    [9, "Early Morning", "Franz Maxwell I.", 0],
    [10, "女々さんとパジャマ", "Franz Maxwell I.", 0],
    [11, "Country Road", "Franz Maxwell I.", 0],
    [12, "決意のペットボトル", "Franz Maxwell I.", 0],
    [13, "おぼえてないの", "Franz Maxwell I.", 0],
    [14, "夜風のサイクリング", "Franz Maxwell I.", 0],
    [15, "Beautiful Woman", "Franz Maxwell I.", 0],
    [16, "Star Dust", "Franz Maxwell I.", 0],
    [17, "よあけなんか よあけなんか", "Franz Maxwell I.", 0],
    [18, "Watch Out", "Franz Maxwell I.", 0],
    [19, "覚悟のススメ", "Franz Maxwell I.", 0],
    [20, "馳せる思い、募る願い、無限の宇宙の彼方へ", "Franz Maxwell I.", 0],
    [21, "孤独なエリオ", "Franz Maxwell I.", 0],
    [22, "わたあめ・ゆかた・やきそば", "Franz Maxwell I.", 0],
    [23, "Happy Day", "Franz Maxwell I.", 0],
]
links = ["https://beta.musicbrainz.org/release/9bc87f3f-ebd5-4a17-a73f-048b105545da", "https://vgmdb.net/album/26156"]

[56c1b47b6fb6ecec23e858cc868de5f5]
catalognumber = "SSX-10199"
date = "2011-11-23"
album = "［電波メールと青春ラジオ］DJCD vol.2"
tracks = [
    [1, "[第4回]ゲスト", "加藤英美里 & 渕上舞", 0],
    [2, "[第5回]ゲスト", "井口裕香", 0],
    [3, "[第6回]ゲスト", "入野自由", 0],
]
links = ["https://beta.musicbrainz.org/release/2df02988-09e7-423b-95c0-78150744f26c"]

[11da3ffe1749fd4620f42c5b933cc0a5]
catalognumber = "SSX-10200"
date = "2011-12-21"
album = "電波女と青春男 キャラクターソングアルバムvol.2"
tracks = [
    [1, "永遠の39歳だもーん☆", "藤和女々(CV:野中藍)", 0],
    [2, "ツヨクネガエ ツヨクハナテ", "星宮社(CV:井口裕香)", 0],
    [3, "にわ君、すなわち転校生、あるいはイトコ", "藤和エリオ、前川さん、御船流子(CV:大亀あすか、加藤英美里、渕上舞)", 0],
]
links = ["https://beta.musicbrainz.org/release/62e00aec-932d-4123-a836-b92c7c7c2a09", "https://vgmdb.net/album/26158"]

[6c6b65de8fa49df9ea409891457e062b]
catalognumber = "COCX-38253"
date = "2013-10-09"
album = "THE IDOLM@STER CINDERELLA MASTER Cute jewelries! 001"
tracks = [
    [1, "アタシポンコツアンドロイド", "双葉 杏(CV:五十嵐裕美)、前川みく(CV:高森奈津美)、島村卯月(CV:大橋彩香)、小日向美穂(CV:津田美波)、安部菜々(CV:三宅麻理恵)", 0],
    [2, "気まぐれロマンティック", "島村卯月(CV:大橋彩香)", 0],
    [3, "しっぽのきもち", "前川みく(CV:高森奈津美)", 0],
    [4, "碧いうさぎ", "安部菜々(CV:三宅麻理恵)", 0],
    [5, "ルル", "双葉 杏(CV:五十嵐裕美)", 0],
    [6, "遠く遠く", "小日向美穂(CV:津田美波)", 0],
    [7, "ススメ☆オトメ 〜jewel parade〜", "双葉 杏(CV:五十嵐裕美)、前川みく(CV:高森奈津美)、島村卯月(CV:大橋彩香)、小日向美穂(CV:津田美波)、安部菜々(CV:三宅麻理恵)", 0],
    [8, "キュートな収録後 (ボーナスドラマ)", "[dialogue]", 0],
    [9, "アタシポンコツアンドロイド (オリジナル・カラオケ)", "双葉 杏(CV:五十嵐裕美)、前川みく(CV:高森奈津美)、島村卯月(CV:大橋彩香)、小日向美穂(CV:津田美波)、安部菜々(CV:三宅麻理恵)", 0],
    [10, "ススメ☆オトメ 〜jewel parade〜 (オリジナル・カラオケ)", "双葉 杏(CV:五十嵐裕美)、前川みく(CV:高森奈津美)、島村卯月(CV:大橋彩香)、小日向美穂(CV:津田美波)、安部菜々(CV:三宅麻理恵)", 0],
]
links = ["https://beta.musicbrainz.org/release/3f485829-c846-4718-b2e4-98ae23c5c57d", "https://vgmdb.net/album/40103"]

[767d5ecbb27d4a9a0d08a3744b1a0c18]
catalognumber = "MAGICUS-55"
date = "2013-10-23"
album = "あにそん SUPER BEST MIX ~NONSTOP PREMIER TUNES~"
tracks = [
    [1, "天使にふれたよ！", "", 0],
    [2, "恋愛サーキュレーション", "", 0],
    [3, "一斉の声", "", 0],
    [4, "君をのせて", "", 0],
    [5, "悲しみをやさしさに", "", 0],
    [6, "残酷な天使のテーゼ", "", 0],
    [7, "微笑みの爆弾", "", 0],
    [8, "PSI-missing", "", 0],
    [9, "風船ガム", "", 0],
    [10, "二言目", "", 0],
    [11, "青い栞", "", 0],
    [12, "プラスチックスマイル", "", 0],
    [13, "irony", "", 0],
    [14, "君が夢を連れてきた", "", 0],
    [15, "ココロのちず", "", 0],
    [16, "Fast Forward", "", 0],
    [17, "BON VOYAGE", "", 0],
    [18, "青春狂騒曲", "", 0],
    [19, "聖少女領域", "", 0],
    [20, "星間飛行", "", 0],
    [21, "サクラサクミライコイユメ", "", 0],
    [22, "Os-宇宙人", "", 0],
    [23, "SHOOT！", "", 0],
    [24, "only my railgun", "", 0],
    [25, "ライオン", "", 0],
    [26, "ヒカリ", "", 0],
    [27, "ぴゅあぴゅあはーと", "", 0],
    [28, "Believe", "", 0],
    [29, "God knows", "", 0],
    [30, "裏切りの夕焼け", "", 0],
]
links = ["https://vgmdb.net/album/151362"]

[f79e02711162f5b90a8f86ac3728c6f7]
catalognumber = "SSX-10315~6"
date = "2014-03-26"
album = "電波女と青春男 オリジナルサウンドトラック & キャラクターソングアルバム Disc 1 [SSX-10315]"
tracks = [
    [1, "電波女と青春男", "", 0],
    [2, "Honesty", "", 0],
    [3, "Sunny Day", "", 0],
    [4, "New Life", "", 0],
    [5, "成層圏から指令がきてるの", "", 0],
    [6, "Search", "", 0],
    [7, "Whats is this SUMAKI!?", "", 0],
    [8, "Memories", "", 0],
    [9, "Moonlight", "", 0],
    [10, "Labyrinth", "", 0],
    [11, "コスプレ協奏曲", "", 0],
    [12, "Emergency", "", 0],
    [13, "Crying", "", 0],
    [14, "夕暮れの頃", "", 0],
    [15, "貧血少女", "", 0],
    [16, "フルーツはすき", "", 0],
    [17, "キノコはきらい", "", 0],
    [18, "よるのうみ", "", 0],
    [19, "Splash", "", 0],
    [20, "でんぱおんなとせいしゅんおとこ", "", 0],
    [21, "Fresh Start", "", 0],
    [22, "そりゃないぜ", "", 0],
    [23, "対流圏からも指令なの", "", 0],
    [24, "ま、嘘だけど", "", 0],
    [25, "真の秘密", "", 0],
    [26, "解放への疾走", "", 0],
    [27, "No way", "", 0],
    [28, "Early Morning", "", 0],
    [29, "女々さんとパジャマ", "", 0],
    [30, "Country Road", "", 0],
    [31, "決意のペットボトル", "", 0],
    [32, "おぼえてないの", "", 0],
    [33, "夜風のサイクリング", "", 0],
    [34, "Beautiful Woman", "", 0],
    [35, "Star Dust", "", 0],
    [36, "よあけなんかよあけなんか", "", 0],
    [37, "Watch Out", "", 0],
    [38, "覚悟のススメ", "", 0],
    [39, "馳せる思い、募る願い、無限の宇宙の彼方へ", "", 0],
    [40, "孤独なエリオ", "", 0],
    [41, "わたあめ・ゆかた・やきそば", "", 0],
    [42, "Happy Day", "", 0],
    [43, "Os-宇宙人(TV-SIZE)", "", 0],
]
links = ["https://vgmdb.net/album/44773"]

[a42a6ad921f8da76ca456fa3106024ba]
catalognumber = "SSX-10315~6"
date = "2014-03-26"
album = "電波女と青春男 オリジナルサウンドトラック & キャラクターソングアルバム Disc 2 [SSX-10316]"
tracks = [
    [1, "イトコ", "", 0],
    [2, "昼休みとヘルメットと同級生", "", 0],
    [3, "キボネング・デコの名で", "", 0],
    [4, "永遠の39歳だもーん☆", "", 0],
    [5, "ツヨクネガエ・ツヨクハナテ", "", 0],
    [6, "にわ君、すなわち転校生、あるいはイトコ", "", 0],
]
links = ["https://vgmdb.net/album/44773"]

[91e6fd82252c17c01db8b95e81478725]
catalognumber = "ABIT-33"
date = "2015-04-29"
album = "THE アニソン BEST～普遍の8bitカヴァーズ～"
tracks = [
    [1, "staple stable", "", 0],
    [2, "残酷な天使のテーゼ", "", 0],
    [3, "一斉の声", "", 0],
    [4, "COLORS", "", 0],
    [5, "irony", "", 0],
    [6, "君が好きだと叫びたい", "", 0],
    [7, "Os-宇宙人", "", 0],
    [8, "only my railgun", "", 0],
    [9, "SHOOT!", "", 0],
    [10, "裏切りの夕焼け", "", 0],
    [11, "oath sign", "", 0],
    [12, "inner universe", "", 0],
    [13, "Hacking to the Gate", "", 0],
    [14, "Paradise Lost", "", 0],
    [15, "God knows...", "", 0],
    [16, "STRIKE WITCHES ~わたしにできること~", "", 0],
    [17, "ウィーアー!", "", 0],
    [18, "コネクト", "", 0],
    [19, "Chase the world", "", 0],
    [20, "Sign", "", 0],
    [21, "crossing field", "", 0],
    [22, "great escape", "", 0],
    [23, "No buts!", "", 0],
    [24, "曇天", "", 0],
    [25, "Can do", "", 0],
]
links = ["https://vgmdb.net/album/150817"]

[4ad816326418cd93e293c639dd0eb431]
catalognumber = "SNCL-66"
date = "2022-05-25"
album = "まだ雨はやまない / しぐれうい"
tracks = [
    [1, "シンカケイスケッチ", "しぐれうい", 0],
    [2, "もうそう♡えくすぷれす", "しぐれうい", 0],
    [3, "放課後マーメイド", "しぐれうい", 0],
    [4, "寝・逃・げでリセット!", "しぐれうい", 0],
    [5, "インドア系ならトラックメイカー", "しぐれうい", 0],
    [6, "粛聖!!ロリ神レクイエム☆", "しぐれうい", 0],
    [7, "ルル", "しぐれうい", 0],
    [8, "夕立のりぼん", "しぐれうい", 0],
    [9, "花ざかりWeekend✿", "しぐれうい", 0],
    [10, "プラチナジェット", "しぐれうい", 0],
    [11, "rainy lady", "しぐれうい", 0],
    [12, "Pris-Magic!", "しぐれうい", 0],
    [13, "シンカケイスケッチ (Instrumental)", "しぐれうい", 0],
    [14, "放課後マーメイド (Instrumental)", "しぐれうい", 0],
    [15, "粛聖!!ロリ神レクイエム☆ (Instrumental)", "しぐれうい", 0],
    [16, "rainy lady (Instrumental)", "しぐれうい", 0],
    [17, "Pris-Magic! (Instrumental)", "しぐれうい", 0],
]
links = ["https://beta.musicbrainz.org/release/09cabdc8-a3c0-4ed4-b78e-fa493e5c614e", "https://vgmdb.net/album/119497"]
