[b58a9573d7dcf0c87f0fb19fc25d7e7d]
catalognumber = "EYCA-11872"
date = "2018-04-20"
album = "魔法少女サイトキャラクターソング ...私だけ見てて♡ / 穴沢虹海(CV:芹澤優)"
tracks = [
    [1, "…私だけ見てて♡", "穴沢虹海(CV:芹澤優)", 0],
    [2, "お・ぼ・え・テ・て", "穴沢虹海(CV:芹澤優)", 0],
    [3, "…私だけ見てて♡ (Instrumental)", "穴沢虹海(CV:芹澤優)", 0],
    [4, "お・ぼ・え・テ・て (Instrumental)", "穴沢虹海(CV:芹澤優)", 0],
]
links = ["https://beta.musicbrainz.org/release/0837be0b-6add-43b7-ab53-ed7be2119fe0", "https://vgmdb.net/album/76244"]

[99b084833b0c86cb755f0da1df4a7869]
catalognumber = "EYCA-11871/B"
date = "2018-04-20"
album = "魔法少女サイトキャラクターソング ...私だけ見てて♡ / 穴沢虹海(CV:芹澤優) Disc 1 (CD) [EYCA-11871]"
tracks = [
    [1, "…私だけ見てて♡", "穴沢虹海(CV:芹澤優)", 0],
    [2, "お・ぼ・え・テ・て", "穴沢虹海(CV:芹澤優)", 0],
    [3, "…私だけ見てて♡ (Instrumental)", "穴沢虹海(CV:芹澤優)", 0],
    [4, "お・ぼ・え・テ・て (Instrumental)", "穴沢虹海(CV:芹澤優)", 0],
]
links = ["https://beta.musicbrainz.org/release/75b964e9-1fb5-4851-b33b-5dae2c2d0f07", "https://vgmdb.net/album/76245"]

[3d340eafb4665305dd114c6ad9bf952a]
catalognumber = "EYCA-11871/B"
date = "2018-04-20"
album = "魔法少女サイトキャラクターソング ...私だけ見てて♡ / 穴沢虹海(CV:芹澤優) Disc 2 (DVD) [EYCA-11871B]"
tracks = [
    [1, "…私だけ見てて♡ (Music Video)", "穴沢虹海(CV:芹澤優)", 0],
]
links = ["https://beta.musicbrainz.org/release/75b964e9-1fb5-4851-b33b-5dae2c2d0f07", "https://vgmdb.net/album/76245"]

[f1407d1762322165412503a4267e2155]
catalognumber = "EYCA-11870"
date = "2018-05-09"
album = "Changing point / i☆Ris"
tracks = [
    [1, "Changing point", "i☆Ris", 0],
    [2, "アメコイ", "i☆Ris", 0],
    [3, "卒業式", "i☆Ris", 0],
    [4, "Changing point (instrumental)", "i☆Ris", 0],
    [5, "アメコイ (instrumental)", "i☆Ris", 0],
    [6, "卒業式 (instrumental)", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/ce0593bd-fa4c-4564-a691-f041f294cac0", "https://vgmdb.net/album/75836"]

[0fcd4246fb4fbe95905cbdfeb21994b1]
catalognumber = "EYCA-11869/B"
date = "2018-05-09"
album = "Changing point / i☆Ris [CD+DVD] Disc 1 (CD)"
tracks = [
    [1, "Changing point", "i☆Ris", 0],
    [2, "アメコイ", "i☆Ris", 0],
    [3, "Changing point (instrumental)", "i☆Ris", 0],
    [4, "アメコイ (instrumental)", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/8dfb1b42-443a-4c60-9bdf-910cbdce62dc", "https://vgmdb.net/album/75837"]

[7861fd429b108dc40fed15b4db23493b]
catalognumber = "EYCA-11869/B"
date = "2018-05-09"
album = "Changing point / i☆Ris [CD+DVD] Disc 2 (DVD)"
tracks = [
    [1, "Changing Point -Music Video-", "i☆Ris", 0],
    [2, "Changing Point -Off Shot Movie-", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/8dfb1b42-443a-4c60-9bdf-910cbdce62dc", "https://vgmdb.net/album/75837"]

[d577a5533ad8b77e88eb160ff8e03757]
catalognumber = "GNCA-0529"
date = "2018-05-23"
album = "ゼンゼントモダチ / 山崎はるか"
tracks = [
    [1, "ゼンゼントモダチ", "山崎はるか", 0],
    [2, "金曜日のBambi", "山崎はるか", 0],
    [3, "ゼンゼントモダチ <instrumental>", "山崎はるか", 0],
    [4, "金曜日のBambi <instrumental>", "山崎はるか", 0],
    [5, "選手宣誓ガール", "山崎はるか", 0],
]
links = ["https://beta.musicbrainz.org/release/bf5be5a0-1965-4075-a9fa-7acb7618c801", "https://vgmdb.net/album/75812"]

[aa02f33bba21259f22cebf1ca8c34dc4]
catalognumber = "GNCA-0528"
date = "2018-05-23"
album = "ゼンゼントモダチ / 山崎はるか Disc 1 (CD)"
tracks = [
    [1, "ゼンゼントモダチ", "山崎はるか", 0],
    [2, "金曜日のBambi", "山崎はるか", 0],
    [3, "ゼンゼントモダチ <instrumental>", "山崎はるか", 0],
    [4, "金曜日のBambi <instrumental>", "山崎はるか", 0],
]
links = ["https://beta.musicbrainz.org/release/2b975d26-4ff2-4b48-961e-26deac769ac6", "https://vgmdb.net/album/75813"]

[e9a0039649aa509ec3c181292a901bd0]
catalognumber = "GNCA-0528"
date = "2018-05-23"
album = "ゼンゼントモダチ / 山崎はるか Disc 2 (DVD)"
tracks = [
    [1, "ゼンゼントモダチ (MV)", "山崎はるか", 0],
    [2, "ゼンゼントモダチ (MV Dance shot ver.)", "山崎はるか", 0],
    [3, "ゼンゼントモダチ (MV Behind the scene)", "山崎はるか", 0],
    [4, "SPOT", "山崎はるか", 0],
]
links = ["https://beta.musicbrainz.org/release/2b975d26-4ff2-4b48-961e-26deac769ac6", "https://vgmdb.net/album/75813"]

[8a35338d0e98488cdfb74152d82d925a]
catalognumber = "EYCA-11875/B"
date = "2018-06-20"
album = "魔法少女サイトキャラクターソング believe again / 奴村露乃(CV:茜屋日海夏) Disc 2 (DVD)"
tracks = [
    [1, "believe again (Music Video)", "奴村露乃(CV:茜屋日海夏)", 0],
]
links = ["https://beta.musicbrainz.org/release/10f5fc05-faf6-4aa4-8a0e-bfff89191435", "https://vgmdb.net/album/76249"]

[f05e19c967db79577fe2740176a8e730]
catalognumber = "EYCA-11875/B"
date = "2018-06-20"
album = "魔法少女サイトキャラクターソング believe again / 奴村露乃(CV:茜屋日海夏) Disc 1 (CD)"
tracks = [
    [1, "believe again", "奴村露乃(CV:茜屋日海夏)", 0],
    [2, "あたしがいなくても", "奴村露乃(CV:茜屋日海夏)", 0],
    [3, "believe again (instrumental)", "奴村露乃(CV:茜屋日海夏)", 0],
    [4, "あたしがいなくても (instrumental)", "奴村露乃(CV:茜屋日海夏)", 0],
]
links = ["https://beta.musicbrainz.org/release/10f5fc05-faf6-4aa4-8a0e-bfff89191435", "https://vgmdb.net/album/76249"]

[7ea7c0b2d6e8942e130dfc0768802695]
catalognumber = "EYCA-11873/B"
date = "2018-06-20"
album = "魔法少女サイトキャラクターソング 赤イ涙の先 / 朝霧彩(CV:大野柚布子) Disc 1 (CD)"
tracks = [
    [1, "赤イ涙の先", "朝霧彩(CV:大野柚布子)", 0],
    [2, "もしアナタが 消えようとも", "朝霧彩(CV:大野柚布子)", 0],
    [3, "赤イ涙の先 (instrumental)", "朝霧彩(CV:大野柚布子)", 0],
    [4, "もしアナタが 消えようとも (instrumental)", "朝霧彩(CV:大野柚布子)", 0],
]
links = ["https://beta.musicbrainz.org/release/c8f42a49-8e05-4fc4-969d-1f23209802b4", "https://vgmdb.net/album/76247"]

[ff917a1e19a81035a782dadaf9e31fcb]
catalognumber = "EYCA-11873/B"
date = "2018-06-20"
album = "魔法少女サイトキャラクターソング 赤イ涙の先 / 朝霧彩(CV:大野柚布子) Disc 2 (DVD)"
tracks = [
    [1, "赤イ涙の先 (Music Video)", "朝霧彩(CV:大野柚布子)", 0],
]
links = ["https://beta.musicbrainz.org/release/c8f42a49-8e05-4fc4-969d-1f23209802b4", "https://vgmdb.net/album/76247"]

[717ab4a3665c9be00cf22980d75aad76]
catalognumber = "EYCA-11874"
date = "2018-06-20"
album = "魔法少女サイトキャラクターソング 赤イ涙の先 / 朝霧彩(CV:大野柚布子)"
tracks = [
    [1, "赤イ涙の先", "朝霧彩(CV:大野柚布子)", 0],
    [2, "もしアナタが 消えようとも", "朝霧彩(CV:大野柚布子)", 0],
    [3, "赤イ涙の先 (instrumental)", "朝霧彩(CV:大野柚布子)", 0],
    [4, "もしアナタが 消えようとも (instrumental)", "朝霧彩(CV:大野柚布子)", 0],
]
links = ["https://beta.musicbrainz.org/release/1d6c89a4-ea59-44b5-93e9-a45bd96b266a", "https://vgmdb.net/album/76246"]

[260ee475d5711dfc45a347e2e4d79349]
catalognumber = "EYCA-11876"
date = "2018-06-20"
album = "魔法少女サイトキャラクターソング believe again / 奴村露乃(CV:茜屋日海夏)"
tracks = [
    [1, "believe again", "奴村露乃(CV:茜屋日海夏)", 0],
    [2, "あたしがいなくても", "奴村露乃(CV:茜屋日海夏)", 0],
    [3, "believe again (instrumental)", "奴村露乃(CV:茜屋日海夏)", 0],
    [4, "あたしがいなくても (instrumental)", "奴村露乃(CV:茜屋日海夏)", 0],
]
links = ["https://beta.musicbrainz.org/release/0acd9851-d9e5-473f-94e8-ed23d1704049", "https://vgmdb.net/album/76248"]

[a9e92697481cbe029f92e300a13f5b56]
catalognumber = "EYCA-11903~4"
date = "2018-08-31"
album = "魔法少女サイト オリジナル・サウンドトラック MAHOU SYOUJYO SITE MUSIC ARCHIVE Disc 1 [EYCA-11903]"
tracks = [
    [1, "MainTitle", "井内啓二", 0],
    [2, "ワタシノセカイ", "井内啓二", 0],
    [3, "偽りの世界", "井内啓二", 0],
    [4, "希望の朝", "宮島 紫(杉並児童合唱団)", 0],
    [5, "premonition", "井内啓二", 0],
    [6, "the awakening", "井内啓二", 0],
    [7, "magical tears", "井内啓二", 0],
    [8, "into the stoppage time", "井内啓二", 0],
    [9, "the magical covenant", "井内啓二", 0],
    [10, "Magical source", "井内啓二", 0],
    [11, "Innocent murderous intent", "井内啓二", 0],
    [12, "an encounter", "井内啓二", 0],
    [13, "tempest", "井内啓二", 0],
    [14, "露乃の過去", "井内啓二", 0],
    [15, "love tactics", "井内啓二", 0],
    [16, "fear Ⅱ", "井内啓二", 0],
    [17, "dive to the consciousness", "井内啓二", 0],
    [18, "Battle: raid", "井内啓二", 0],
    [19, "Battle: close match", "井内啓二", 0],
    [20, "Battle: reversal", "井内啓二", 0],
]
links = ["https://beta.musicbrainz.org/release/190df441-d889-4847-850c-7dbb3cace17d", "https://vgmdb.net/album/78279"]

[01b8db9125fc0587b77b4963c10a39be]
catalognumber = "EYCA-11903~4"
date = "2018-08-31"
album = "魔法少女サイト オリジナル・サウンドトラック MAHOU SYOUJYO SITE MUSIC ARCHIVE Disc 2 [EYCA-11904]"
tracks = [
    [1, "respite from consciousness", "井内啓二", 0],
    [2, "tell me everything", "井内啓二", 0],
    [3, "この腐敗した世界に", "井内啓二", 0],
    [4, "a reasoning process", "井内啓二", 0],
    [5, "漆の思惑", "井内啓二", 0],
    [6, "misgiving", "井内啓二", 0],
    [7, "peculiar friends", "井内啓二", 0],
    [8, "管理人会議", "井内啓二", 0],
    [9, "心根の贖罪と浄化", "井内啓二", 0],
    [10, "rights of the matter", "井内啓二", 0],
    [11, "trap", "井内啓二", 0],
    [12, "虹海の死", "井内啓二", 0],
    [13, "悲しみを超えて", "井内啓二", 0],
    [14, "悲中の決断", "井内啓二", 0],
    [15, "change for the worse", "井内啓二", 0],
    [16, "division", "井内啓二", 0],
    [17, "insanity", "井内啓二", 0],
    [18, "falling to the dark side", "井内啓二", 0],
    [19, "beyond the constraints", "井内啓二", 0],
    [20, "彩の決意", "井内啓二", 0],
]
links = ["https://beta.musicbrainz.org/release/190df441-d889-4847-850c-7dbb3cace17d", "https://vgmdb.net/album/78279"]

[726dc04c920cd53c940e0091e2d6902c]
catalognumber = "GNCA-1557"
date = "2019-08-28"
album = "C'est Parti!! / 山崎はるか"
tracks = [
    [1, "パンピーナ!", "山崎はるか", 0],
    [2, "キセキ的☆スマイリュージョン", "山崎はるか", 0],
    [3, "Dark Sweet Nightmare", "山崎はるか", 0],
    [4, "ChuChuパフェ☆SP", "山崎はるか", 0],
    [5, "僕ら、駆け行く空へ (2019 HH Rebuild)", "山崎はるか", 0],
    [6, "Supersonic Mighty Dream", "山崎はるか", 0],
    [7, "Dragon Dance", "山崎はるか", 0],
    [8, "ゼンゼントモダチ", "山崎はるか", 0],
    [9, "ヒヤシンス", "山崎はるか", 0],
    [10, "金曜日のBambi", "山崎はるか", 0],
    [11, "キャラメル", "山崎はるか", 0],
    [12, "おいで Brand-new World!", "山崎はるか", 0],
]
links = ["https://beta.musicbrainz.org/release/a76e0d54-2f73-4bb6-8dd8-28f3fbf773ea", "https://vgmdb.net/album/87895"]

[5962782c28a9d0a396e580c7831721d3]
catalognumber = "EYCA-12850"
date = "2020-03-04"
album = "Shall we☆Carnival / i☆Ris"
tracks = [
    [1, "ハピラキ☆Dream Carnival", "", 0],
    [2, "Memorial", "", 0],
    [3, "Endless Notes", "", 0],
    [4, "アルティメット☆MAGIC", "", 0],
    [5, "Spending", "", 0],
    [6, "Changing point", "", 0],
    [7, "泡沫の光", "", 0],
    [8, "FANTASTIC ILLUSION", "", 0],
    [9, "TIN TONE", "", 0],
    [10, "One Kiss", "", 0],
    [11, "夢中グラフィティ", "", 0],
]
links = ["https://vgmdb.net/album/93165"]

[357a8d333973cbac00360a7af3632172]
catalognumber = "EYCA-12849/B"
date = "2020-03-04"
album = "Shall we☆Carnival / i☆Ris Vocal"
tracks = [
    [1, "ハピラキ☆Dream Carnival", "", 0],
    [2, "Memorial", "", 0],
    [3, "Endless Notes", "", 0],
    [4, "アルティメット☆MAGIC", "", 0],
    [5, "Spending", "", 0],
    [6, "Changing point", "", 0],
    [7, "泡沫の光", "", 0],
    [8, "FANTASTIC ILLUSION", "", 0],
    [9, "TIN TONE", "", 0],
    [10, "One Kiss", "", 0],
    [11, "夢中グラフィティ", "", 0],
]
links = ["https://vgmdb.net/album/93166"]

[cc34559762283f900d9c6305daabc524]
catalognumber = "EYCA-12849/B"
date = "2020-03-04"
album = "Shall we☆Carnival / i☆Ris Vocal, Video"
tracks = [
    [1, "ハピラキ☆Dream Carnival -Music Video-", "", 0],
    [2, "ハピラキ☆Dream Carnival -Off Shot Movie-", "", 0],
    [3, "Memorial -Music Video-", "", 0],
    [4, "Changing point -Music Video-", "", 0],
    [5, "Endless Notes -Music Video-", "", 0],
    [6, "アルティメット☆MAGIC -Music Video-", "", 0],
    [7, "FANTASTIC ILLUSION -Music Video-", "", 0],
]
links = ["https://vgmdb.net/album/93166"]

[a742f8acebe3ee02c29794f491c51a3f]
catalognumber = "EYCA-12848/B"
date = "2020-03-04"
album = "Shall we☆Carnival / i☆Ris [Limited Edition] Vocal"
tracks = [
    [1, "ハピラキ☆Dream Carnival", "", 0],
    [2, "Memorial", "", 0],
    [3, "Endless Notes", "", 0],
    [4, "アルティメット☆MAGIC", "", 0],
    [5, "Spending", "", 0],
    [6, "Changing point", "", 0],
    [7, "泡沫の光", "", 0],
    [8, "FANTASTIC ILLUSION", "", 0],
    [9, "TIN TONE", "", 0],
    [10, "One Kiss", "", 0],
    [11, "夢中グラフィティ", "", 0],
]
links = ["https://vgmdb.net/album/93167"]

[6f925654cc47e2996490165d363e42a1]
catalognumber = "EYCA-12848/B"
date = "2020-03-04"
album = "Shall we☆Carnival / i☆Ris [Limited Edition] Vocal, Video"
tracks = [
    [1, "ハピラキ☆Dream Carnival -Music Video-", "", 0],
    [2, "ハピラキ☆Dream Carnival -Off Shot Movie-", "", 0],
    [3, "Memorial -Music Video-", "", 0],
    [4, "Changing point -Music Video-", "", 0],
    [5, "Endless Notes -Music Video-", "", 0],
    [6, "アルティメット☆MAGIC -Music Video-", "", 0],
    [7, "FANTASTIC ILLUSION -Music Video-", "", 0],
]
links = ["https://vgmdb.net/album/93167"]

[ef7131ae6ea4cacc019fa629267f6991]
catalognumber = "EYCA-13877~8"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ~Best i☆Rist~ / i☆Ris Disc 1 [EYCA-13877]"
tracks = [
    [1, "Anniversary", "i☆Ris", 0],
    [2, "Color", "i☆Ris", 0],
    [3, "ウィーアー!", "i☆Ris", 0],
    [4, "イチズ", "i☆Ris", 0],
    [5, "§Rainbow", "i☆Ris", 0],
    [6, "幻想曲WONDERLAND", "i☆Ris", 0],
    [7, "徒太陽", "i☆Ris", 0],
    [8, "Make it!", "i☆Ris", 0],
    [9, "ミラクル☆パラダイス", "i☆Ris", 0],
    [10, "Realize!", "i☆Ris", 0],
    [11, "ドリームパレード", "i☆Ris", 0],
    [12, "ブライトファンタジー", "i☆Ris", 0],
    [13, "Goin’on", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121650"]

[703cdc70d069d919be9993b2ea669e12]
catalognumber = "EYCA-13877~8"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ~Best i☆Rist~ / i☆Ris Disc 2 [EYCA-13878]"
tracks = [
    [1, "Ready Smile!!", "i☆Ris", 0],
    [2, "Re:Call", "i☆Ris", 0],
    [3, "Shining Star", "i☆Ris", 0],
    [4, "Memorial", "i☆Ris", 0],
    [5, "Changing point", "i☆Ris", 0],
    [6, "Endless Notes", "i☆Ris", 0],
    [7, "アルティメット☆MAGIC", "i☆Ris", 0],
    [8, "FANTASTIC ILLUSION", "i☆Ris", 0],
    [9, "ハピラキ☆Dream Carnival", "i☆Ris", 0],
    [10, "Summer Dude", "i☆Ris", 0],
    [11, "Cheer up", "i☆Ris", 0],
    [12, "12月のSnowry", "i☆Ris", 0],
    [13, "ハートビート急上昇", "i☆Ris", 0],
    [14, "Queens Bluff", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121650"]

[3f0618fce6c7285cf7cfe80f37688a4a]
catalognumber = "EYCA-13872~4/B~C"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ～Best i☆Rist～ / i☆Ris [初回生産限定盤] Vocal Disc 1"
tracks = [
    [1, "Anniversary", "i☆Ris", 0],
    [2, "Color", "i☆Ris", 0],
    [3, "ウィーアー!", "i☆Ris", 0],
    [4, "イチズ", "i☆Ris", 0],
    [5, "§Rainbow", "i☆Ris", 0],
    [6, "幻想曲WONDERLAND", "i☆Ris", 0],
    [7, "徒太陽", "i☆Ris", 0],
    [8, "Make it!", "i☆Ris", 0],
    [9, "ミラクル☆パラダイス", "i☆Ris", 0],
    [10, "Realize!", "i☆Ris", 0],
    [11, "ドリームパレード", "i☆Ris", 0],
    [12, "ブライトファンタジー", "i☆Ris", 0],
    [13, "Goin’on", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121652"]

[27d8ff2abd4987dc257e093154d1e80a]
catalognumber = "EYCA-13872~4/B~C"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ～Best i☆Rist～ / i☆Ris [初回生産限定盤] Vocal Disc 2"
tracks = [
    [1, "Ready Smile!!", "i☆Ris", 0],
    [2, "Re:Call", "i☆Ris", 0],
    [3, "Shining Star", "i☆Ris", 0],
    [4, "Memorial", "i☆Ris", 0],
    [5, "Changing point", "i☆Ris", 0],
    [6, "Endless Notes", "i☆Ris", 0],
    [7, "アルティメット☆MAGIC", "i☆Ris", 0],
    [8, "FANTASTIC ILLUSION", "i☆Ris", 0],
    [9, "ハピラキ☆Dream Carnival", "i☆Ris", 0],
    [10, "Summer Dude", "i☆Ris", 0],
    [11, "Cheer up", "i☆Ris", 0],
    [12, "12月のSnowry", "i☆Ris", 0],
    [13, "ハートビート急上昇", "i☆Ris", 0],
    [14, "Queens Bluff", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121652"]

[fd4da2ba0e5618ab60ea39e827dc55b9]
catalognumber = "EYCA-13872~4/B~C"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ～Best i☆Rist～ / i☆Ris [初回生産限定盤] Vocal Disc 3"
tracks = [
    [1, "ありえんほどフィーバー", "i☆Ris", 0],
    [2, "Happy New World☆", "i☆Ris", 0],
    [3, "YuRuYuRuハッピーデイズ", "i☆Ris", 0],
    [4, "Spending", "i☆Ris", 0],
    [5, "Thank you forever!", "i☆Ris", 0],
    [6, "One Kiss", "i☆Ris", 0],
    [7, "キラキラGood day", "i☆Ris", 0],
    [8, "5STAR☆(仮)", "i☆Ris", 0],
    [9, "イノセントイノベーション", "i☆Ris", 0],
    [10, "鏡のLabyrinth", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121652"]

[62ebe003f20ebcef162d0f669be2c9c9]
catalognumber = "EYCA-13872~4/B~C"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ～Best i☆Rist～ / i☆Ris [初回生産限定盤] Vocal, Video"
tracks = [
    [1, "Anniversary", "", 0],
    [2, "Color", "", 0],
    [3, "ウィーアー!", "", 0],
    [4, "イチズ", "", 0],
    [5, "§Rainbow", "", 0],
    [6, "幻想曲WONDERLAND", "", 0],
    [7, "徒太陽", "", 0],
    [8, "Make it!", "", 0],
    [9, "ミラクル☆パラダイス", "", 0],
    [10, "Realize!", "", 0],
    [11, "ドリームパレード", "", 0],
    [12, "ブライトファンタジー", "", 0],
    [13, "Goin'on", "", 0],
    [14, "Ready Smile!!", "", 0],
    [15, "Re:Call", "", 0],
    [16, "Shining Star", "", 0],
    [17, "Memorial", "", 0],
    [18, "Changing point", "", 0],
    [19, "Endless Notes", "", 0],
    [20, "アルティメット☆MAGIC", "", 0],
    [21, "FANTASTIC ILLUSION", "", 0],
    [22, "ハピラキ☆Dream Carnival", "", 0],
    [23, "Summer Dude", "", 0],
    [24, "Cheer up", "", 0],
    [25, "12月のSnowry", "", 0],
    [26, "ハートビート急上昇", "", 0],
    [27, "Queens Bluff", "", 0],
]
links = ["https://vgmdb.net/album/121652"]

[4f913b243728bf70f6019822ab7eb22a]
catalognumber = "EYCA-13872~4/B~C"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ～Best i☆Rist～ / i☆Ris [初回生産限定盤] Video"
tracks = [
    [1, "Anniversary - Off Shot Movie -", "", 0],
    [2, "10th Anniversary 座談会&インタビュー映像", "", 0],
]
links = ["https://vgmdb.net/album/121652"]

[df261cf47125264a37184491bbcf0a5a]
catalognumber = "EYCA-13875~6/B"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ~Best i☆Rist~ / i☆Ris Vocal Disc 1"
tracks = [
    [1, "Anniversary", "i☆Ris", 0],
    [2, "Color", "i☆Ris", 0],
    [3, "ウィーアー!", "i☆Ris", 0],
    [4, "イチズ", "i☆Ris", 0],
    [5, "§Rainbow", "i☆Ris", 0],
    [6, "幻想曲WONDERLAND", "i☆Ris", 0],
    [7, "徒太陽", "i☆Ris", 0],
    [8, "Make it!", "i☆Ris", 0],
    [9, "ミラクル☆パラダイス", "i☆Ris", 0],
    [10, "Realize!", "i☆Ris", 0],
    [11, "ドリームパレード", "i☆Ris", 0],
    [12, "ブライトファンタジー", "i☆Ris", 0],
    [13, "Goin’on", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121651"]

[c4eeb69e024145da0bfbb3eb28bec300]
catalognumber = "EYCA-13875~6/B"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ~Best i☆Rist~ / i☆Ris Vocal Disc 2"
tracks = [
    [1, "Ready Smile!!", "i☆Ris", 0],
    [2, "Re:Call", "i☆Ris", 0],
    [3, "Shining Star", "i☆Ris", 0],
    [4, "Memorial", "i☆Ris", 0],
    [5, "Changing point", "i☆Ris", 0],
    [6, "Endless Notes", "i☆Ris", 0],
    [7, "アルティメット☆MAGIC", "i☆Ris", 0],
    [8, "FANTASTIC ILLUSION", "i☆Ris", 0],
    [9, "ハピラキ☆Dream Carnival", "i☆Ris", 0],
    [10, "Summer Dude", "i☆Ris", 0],
    [11, "Cheer up", "i☆Ris", 0],
    [12, "12月のSnowry", "i☆Ris", 0],
    [13, "ハートビート急上昇", "i☆Ris", 0],
    [14, "Queens Bluff", "i☆Ris", 0],
]
links = ["https://beta.musicbrainz.org/release/23f7bf46-672d-4d0b-93f3-c8d82e68b687", "https://vgmdb.net/album/121651"]

[b8ce5445b3d2a65513aeb5f994c1c8f6]
catalognumber = "EYCA-13875~6/B"
date = "2022-11-07"
album = "10th Anniversary BEST ALBUM ~Best i☆Rist~ / i☆Ris Vocal, Video"
tracks = [
    [1, "Anniversary", "", 0],
    [2, "Color", "", 0],
    [3, "ウィーアー!", "", 0],
    [4, "イチズ", "", 0],
    [5, "§Rainbow", "", 0],
    [6, "幻想曲WONDERLAND", "", 0],
    [7, "徒太陽", "", 0],
    [8, "Make it!", "", 0],
    [9, "ミラクル☆パラダイス", "", 0],
    [10, "Realize!", "", 0],
    [11, "ドリームパレード", "", 0],
    [12, "ブライトファンタジー", "", 0],
    [13, "Goin'on", "", 0],
    [14, "Ready Smile!!", "", 0],
    [15, "Re:Call", "", 0],
    [16, "Shining Star", "", 0],
    [17, "Memorial", "", 0],
    [18, "Changing point", "", 0],
    [19, "Endless Notes", "", 0],
    [20, "アルティメット☆MAGIC", "", 0],
    [21, "FANTASTIC ILLUSION", "", 0],
    [22, "ハピラキ☆Dream Carnival", "", 0],
    [23, "Summer Dude", "", 0],
    [24, "Cheer up", "", 0],
    [25, "12月のSnowry", "", 0],
    [26, "ハートビート急上昇", "", 0],
    [27, "Queens Bluff", "", 0],
]
links = ["https://vgmdb.net/album/121651"]
