[1]
catalognumber = "VTCL-35296"
date = "2019-01-30"
album = "気ままな天使たち×ハッピー・ハッピー・フレンズ / わたてん☆5"
tracks = [
    [1, "気ままな天使たち", "わたてん☆5", "1"],
    [2, "ハッピー･ハッピー･フレンズ", "わたてん☆5", "1"],
    [3, "気ままな天使たち -Instrumental-", "わたてん☆5", "0"],
    [4, "ハッピー･ハッピー･フレンズ -Instrumental-", "わたてん☆5", "0"],
]
links = ["https://beta.musicbrainz.org/release/91e40854-846b-493e-9687-29c9817f4afc", "https://vgmdb.net/album/82216"]

[2]
catalognumber = "TGCS-11164"
date = "2019-04-24"
album = "私に天使が舞い降りた! キャラクターソングCD 02"
tracks = [
    [1, "GO！GO！GO！", "わたてん☆5", "0"],
    [2, "GO！GO！GO！ -Instrumental-", "わたてん☆5", "0"],
]
links = ["https://beta.musicbrainz.org/release/d548ab11-783a-4f43-9a74-59a907a8af9a", "https://vgmdb.net/album/83286"]

[3]
catalognumber = ""
date = "2020-01-31"
album = "私に天使が舞い降りた! 7 特装版 付録ドラマCD"
tracks = [
    [1, "オープニング", "", ""],
    [2, "いつか本当に捕まりそうでシンパイ", "", ""],
    [3, "みゃーこってその犬?", "", ""],
    [4, "わたしの顔使ってもいいぞ", "", ""],
    [5, "もういつ死んでもいいわ", "", ""],
    [6, "味見してただけです", "", ""],
    [7, "エンディング", "", ""],
]
links = ["https://vgmdb.net/album/93041"]

[4]
catalognumber = "VTCL-60539"
date = "2020-11-25"
album = "デリシャス・スマイル! / わたてん☆5"
tracks = [
    [1, "デリシャス・スマイル！", "わたてん☆5", "0"],
    [2, "無限大ハピネス", "わたてん☆5", "0"],
    [3, "スイーツスイーツパーティー！", "わたてん☆5", "1"],
    [4, "スペシャルコーディネート", "わたてん☆5", "0"],
    [5, "スイーツランド・パラドックス", "白咲花(CV.指出毬亜)", "0"],
    [6, "みゃー姉！！", "星野ひなた(CV.長江里加)", "0"],
    [7, "参上！小悪魔エンジェル", "姫坂乃愛(CV.鬼頭明里)", "0"],
    [8, "My canon", "種村小依(CV.大和田仁美)", "1"],
    [9, "いっしょにおててをつなごうね", "小之森夏音(CV.大空直美)", "0"],
    [10, "ディアマイフレンド", "星野みやこ(CV.上田麗奈)＆松本香子(CV.Lynn)", "0"],
]
links = ["https://beta.musicbrainz.org/release/672c3b6f-d9b6-4ac9-b97c-c8180feac8ad", "https://vgmdb.net/album/103945"]

[5]
catalognumber = "VTCL-60483"
date = "2019-02-27"
album = "「私に天使が舞い降りた!」キャラクターソングアルバム 天使のうたごえ"
tracks = [
    [1, "シュガーコート・ドリーム", "白咲花(CV.指出毬亜)", "0"],
    [2, "やっぱりみゃー姉なんばーわん", "星野ひなた(CV.長江里加)", "0"],
    [3, "アタシ♡カワイイ♡宣言！！！", "姫坂乃愛(CV.鬼頭明里)", "1"],
    [4, "あかいろリトルリーダー", "種村小依(CV.大和田仁美)", "0"],
    [5, "とっておきのことば", "小之森夏音(CV.大空直美)", "1"],
    [6, "私に\"好き\"が舞い降りた", "星野みやこ(CV.上田麗奈)＆松本香子(CV.Lynn)", "0"],
    [7, "シュガーコート・ドリーム -Instrumental-", "白咲花(CV.指出毬亜)", "0"],
    [8, "やっぱりみゃー姉なんばーわん -Instrumental-", "星野ひなた(CV.長江里加)", "0"],
    [9, "アタシ♡カワイイ♡宣言！！！ -Instrumental-", "姫坂乃愛(CV.鬼頭明里)", "0"],
    [10, "あかいろリトルリーダー -Instrumental-", "種村小依(CV.大和田仁美)", "0"],
    [11, "とっておきのことば -Instrumental-", "小之森夏音(CV.大空直美)", "0"],
    [12, "私に\"好き\"が舞い降りた -Instrumental-", "星野みやこ(CV.上田麗奈)＆松本香子(CV.Lynn)", "0"],
]
links = ["https://beta.musicbrainz.org/release/9cd9a99d-e2ec-4671-b572-f75c63456033", "https://vgmdb.net/album/82935"]

[6]
catalognumber = ""
date = "2020-09-18"
album = "無限大ハピネス COMIC ver. / わたてん☆5"
tracks = [
    [1, "無限大ハピネス COMIC ver.", "わたてん☆5", "0"],
    [2, "無限大ハピネス COMIC ver. -Instrumental-", "わたてん☆5", "0"],
    [3, "おまけドラマ「インタビュー」", "わたてん☆5", ""],
]
links = ["https://beta.musicbrainz.org/release/71cf1f9b-a781-4ec6-a1a7-f73729c25a72", "https://vgmdb.net/album/103452"]

[7]
catalognumber = "TGCS-11162"
date = "2019-03-27"
album = "私に天使が舞い降りた! キャラクターソングCD 01"
tracks = [
    [1, "晴れルヤ！", "わたてん☆5", "1"],
    [2, "晴れルヤ！ -Instrumental-", "わたてん☆5", "0"],
]
links = ["https://beta.musicbrainz.org/release/1f72a7be-b63e-47dc-ac0b-1c6c9c1b6090", "https://vgmdb.net/album/83285"]

[8]
catalognumber = ""
date = "2022-08-24"
album = "私に天使が舞い降りた! CHARACTER SONG & RADIO CD"
tracks = [
    [1, "晴れルヤ!", "", "0"],
    [2, "GO! GO! GO!", "", "0"],
    [3, "(data track)", "", ""],
]
links = ["https://vgmdb.net/album/120020"]

[9]
catalognumber = "VTZL-152"
date = "2019-01-30"
album = "気ままな天使たち×ハッピー・ハッピー・フレンズ / わたてん☆5 Disc 1 (CD) [VTCL-35296]"
tracks = [
    [1, "気ままな天使たち", "わたてん☆5", "0"],
    [2, "ハッピー･ハッピー･フレンズ", "わたてん☆5", "0"],
    [3, "気ままな天使たち -Instrumental-", "わたてん☆5", "0"],
    [4, "ハッピー･ハッピー･フレンズ -Instrumental-", "わたてん☆5", "0"],
]
links = ["https://beta.musicbrainz.org/release/714febf6-3c7e-4df2-b5ff-b0bab122b5ba", "https://vgmdb.net/album/82215"]

[10]
catalognumber = "VTZL-152"
date = "2019-01-30"
album = "気ままな天使たち×ハッピー・ハッピー・フレンズ / わたてん☆5 Disc 2 (DVD) [VTBY-158]"
tracks = [
    [1, "気ままな天使たち (Music Clip)", "わたてん☆5", "0"],
    [2, "気ままな天使たち (Making Movie)", "わたてん☆5", "0"],
]
links = ["https://beta.musicbrainz.org/release/714febf6-3c7e-4df2-b5ff-b0bab122b5ba", "https://vgmdb.net/album/82215"]

[11]
catalognumber = "VTCL-60494"
date = "2019-04-03"
album = "TVアニメ「私に天使が舞い降りた!」サウンドコレクション"
tracks = [
    [1, "爽やかなる決意", "伊賀拓郎", "0"],
    [2, "私に天使が舞い降りた！ I", "伊賀拓郎", "0"],
    [3, "私に天使が舞い降りた！ II", "伊賀拓郎", "0"],
    [4, "みやこエキサイト", "伊賀拓郎", "0"],
    [5, "幸せな一日", "伊賀拓郎", "0"],
    [6, "もにょっとした気持ち", "伊賀拓郎", "0"],
    [7, "いっくぞー！", "伊賀拓郎", "0"],
    [8, "応援があれば頑張れる！", "伊賀拓郎", "0"],
    [9, "苦労して手に入れたお菓子", "伊賀拓郎", "0"],
    [10, "幸せな時間", "伊賀拓郎", "0"],
    [11, "小悪魔", "伊賀拓郎", "0"],
    [12, "サイキョーにカワイイ", "伊賀拓郎", "0"],
    [13, "トラブルメーカー", "伊賀拓郎", "0"],
    [14, "想う気持ち", "伊賀拓郎", "0"],
    [15, "焦り", "伊賀拓郎", "0"],
    [16, "友達詐欺", "伊賀拓郎", "0"],
    [17, "どんより", "伊賀拓郎", "0"],
    [18, "ドタバタパニック", "伊賀拓郎", "0"],
    [19, "勝負 II", "伊賀拓郎", "0"],
    [20, "夢うつつ", "伊賀拓郎", "0"],
    [21, "勝負 I", "伊賀拓郎", "0"],
    [22, "無駄骨徒労で報われず", "伊賀拓郎", "0"],
    [23, "信頼 I", "伊賀拓郎", "0"],
    [24, "何でも遊び心", "伊賀拓郎", "0"],
    [25, "夢は叶えるもの", "伊賀拓郎", "0"],
    [26, "信頼 II", "伊賀拓郎", "0"],
    [27, "憧れの人", "伊賀拓郎", "0"],
    [28, "悲しみ", "伊賀拓郎", "0"],
    [29, "優しさを感じて", "伊賀拓郎", "0"],
    [30, "右往左往", "伊賀拓郎", "0"],
    [31, "ホッコリタイム", "伊賀拓郎", "0"],
    [32, "一段落", "伊賀拓郎", "0"],
    [33, "ナイスアイデア", "伊賀拓郎", "0"],
    [34, "疲れた…", "伊賀拓郎", "0"],
    [35, "回想", "伊賀拓郎", "0"],
    [36, "なんてこった", "伊賀拓郎", "0"],
    [37, "ご満悦", "伊賀拓郎", "0"],
    [38, "Eye Catch", "伊賀拓郎", "0"],
    [39, "神殿にて", "伊賀拓郎", "0"],
    [40, "天使の眼差し Prologue", "星野ひなた(CV:長江里加)、姫坂乃愛(CV:鬼頭明里)、種村小依(CV:大和田仁美)、小之森夏音(CV:大空直美)", "0"],
    [41, "私を呼ぶ声", "白咲花(CV:指出毬亜)、種村小依(CV:大和田仁美)、小之森夏音(CV:大空直美)", "0"],
    [42, "ようこそ天使の国へ", "種村小依(CV:大和田仁美)、小之森夏音(CV:大空直美)", "0"],
    [43, "恋するお菓子屋さん", "星野ひなた(CV:長江里加)、姫坂乃愛(CV:鬼頭明里)", "0"],
    [44, "あの子に会いたい", "白咲花(CV:指出毬亜)、星野ひなた(CV:長江里加)", "0"],
    [45, "決意", "白咲花(CV:指出毬亜)、種村小依(CV:大和田仁美)、小之森夏音(CV:大空直美)", "0"],
    [46, "受け継ぐ心", "白咲花(CV:指出毬亜)、星野ひなた(CV:長江里加)、姫坂乃愛(CV:鬼頭明里)", "0"],
    [47, "天使の眼差し Epilogue", "白咲花(CV:指出毬亜)、星野ひなた(CV:長江里加)、姫坂乃愛(CV:鬼頭明里)、種村小依(CV:大和田仁美)、小之森夏音(CV:大空直美)", "0"],
]
links = ["https://beta.musicbrainz.org/release/5c8fd7dd-e054-44b3-b7d4-1b422b8c344a", "https://vgmdb.net/album/83724"]

[12]
catalognumber = "VTZL-213"
date = "2022-10-12"
album = "私に天使が舞い降りた! プレシャス・フレンズ サウンド・コレクション [初回限定盤] Original Soundtrack, Vocal"
tracks = [
    [1, "プレシャス・フレンズ！", "わたてん☆5", "0"],
    [2, "星野家の日常", "伊賀拓郎", "0"],
    [3, "髪飾りⅠ", "伊賀拓郎", "0"],
    [4, "お母さんズ", "伊賀拓郎", "0"],
    [5, "旅行に行こう！", "伊賀拓郎", "0"],
    [6, "おばあちゃんの家", "伊賀拓郎", "0"],
    [7, "長瀞旅行", "伊賀拓郎", "0"],
    [8, "ご飯です！", "伊賀拓郎", "0"],
    [9, "お菓子作り", "伊賀拓郎", "0"],
    [10, "桜の気持ち", "伊賀拓郎", "0"],
    [11, "長瀞温泉交流", "伊賀拓郎", "0"],
    [12, "髪飾りⅡ", "伊賀拓郎", "0"],
    [13, "観光！", "伊賀拓郎", "0"],
    [14, "花とみやこⅠ", "伊賀拓郎", "0"],
    [15, "夕暮れの長瀞", "伊賀拓郎", "0"],
    [16, "こよりとかのん", "伊賀拓郎", "0"],
    [17, "ノアとひなた", "伊賀拓郎", "0"],
    [18, "明かりに照らされて", "伊賀拓郎", "0"],
    [19, "無くなった髪飾り", "伊賀拓郎", "0"],
    [20, "大切な気持ち", "白咲花(CV.指出毬亜), 星野みやこ(CV.上田麗奈)", "0"],
    [21, "一件落着", "伊賀拓郎", "0"],
    [22, "花とみやこⅡ", "伊賀拓郎", "0"],
    [23, "おばあちゃんになっても一緒", "伊賀拓郎", "0"],
    [24, "ずっと…ずっと…", "わたてん☆5", "0"],
    [25, "みんなでいただきます！", "星野ひなた(CV.長江里加), 姫坂乃愛(CV.鬼頭明里)", "0"],
    [26, "かえりみち", "種村小依((CV.大和田仁美), 小之森夏音(CV.大空直美)", "0"],
    [27, "Q.E.D.", "松本香子(CV.Lynn)", "0"],
]
links = ["https://beta.musicbrainz.org/release/fa667eaa-c6e7-484e-bf8a-4997febeebf4", "https://vgmdb.net/album/122040"]

[13]
catalognumber = "VTZL-213"
date = "2022-10-12"
album = "私に天使が舞い降りた! プレシャス・フレンズ サウンド・コレクション [初回限定盤] Vocal, Video"
tracks = [
    [1, "プレシャス・フレンズ! (ミュージックビデオ)", "", "0"],
    [2, "わたてん☆5スケッチ映像", "", ""],
]
links = ["https://vgmdb.net/album/122040"]

[14]
catalognumber = "VTCL-60566"
date = "2022-10-12"
album = "私に天使が舞い降りた! プレシャス・フレンズ サウンド・コレクション"
tracks = [
    [1, "プレシャス・フレンズ！", "わたてん☆5", "1"],
    [2, "星野家の日常", "伊賀拓郎", "0"],
    [3, "髪飾りI", "伊賀拓郎", "0"],
    [4, "お母さんズ", "伊賀拓郎", "0"],
    [5, "旅行に行こう！", "伊賀拓郎", "0"],
    [6, "おばあちゃんの家", "伊賀拓郎", "0"],
    [7, "長瀞旅行", "伊賀拓郎", "0"],
    [8, "ご飯です！", "伊賀拓郎", "0"],
    [9, "お菓子作り", "伊賀拓郎", "0"],
    [10, "桜の気持ち", "伊賀拓郎", "0"],
    [11, "長瀞温泉交流", "伊賀拓郎", "0"],
    [12, "髪飾りII", "伊賀拓郎", "0"],
    [13, "観光！", "伊賀拓郎", "0"],
    [14, "花とみやこI", "伊賀拓郎", "0"],
    [15, "夕暮れの長瀞", "伊賀拓郎", "0"],
    [16, "こよりとかのん", "伊賀拓郎", "0"],
    [17, "ノアとひなた", "伊賀拓郎", "0"],
    [18, "明かりに照らされて", "伊賀拓郎", "0"],
    [19, "無くなった髪飾り", "伊賀拓郎", "0"],
    [20, "大切な気持ち", "白咲花(CV.指出毬亜), 星野みやこ(CV.上田麗奈)", "1"],
    [21, "一件落着", "伊賀拓郎", "0"],
    [22, "花とみやこII", "伊賀拓郎", "0"],
    [23, "おばあちゃんになっても一緒", "伊賀拓郎", "0"],
    [24, "ずっと…ずっと…", "わたてん☆5", "1"],
    [25, "みんなでいただきます！", "星野ひなた(CV.長江里加), 姫坂乃愛(CV.鬼頭明里)", "1"],
    [26, "かえりみち", "種村小依((CV.大和田仁美), 小之森夏音(CV.大空直美)", "1"],
    [27, "Q.E.D.", "松本香子(CV.Lynn)", "0"],
]
links = ["https://beta.musicbrainz.org/release/ab440614-7224-4eae-9a2f-35f5b3677ca4", "https://vgmdb.net/album/122039"]

[15]
catalognumber = "VTZL-179"
date = "2020-11-25"
album = "デリシャス・スマイル! / わたてん☆5 [初回限定盤] Vocal"
tracks = [
    [1, "デリシャス・スマイル!", "", "0"],
    [2, "無限大ハピネス", "", "0"],
    [3, "スイーツスイーツパーティー!", "", "0"],
    [4, "スペシャルコーディネート", "", "0"],
    [5, "スイーツランド・パラドックス", "", "0"],
    [6, "みゃー姉!!", "", "0"],
    [7, "参上!小悪魔エンジェル", "", "0"],
    [8, "My canon", "", "0"],
    [9, "いっしょにおててをつなごうね", "", "0"],
    [10, "ディアマイフレンド", "", "0"],
]
links = ["https://vgmdb.net/album/103946"]

[16]
catalognumber = "VTZL-179"
date = "2020-11-25"
album = "デリシャス・スマイル! / わたてん☆5 [初回限定盤] Vocal, Video"
tracks = [
    [1, "デリシャス・スマイル! (Music Clip)", "", "0"],
    [2, "デリシャス・スマイル! (Making Movie)", "", "0"],
]
links = ["https://vgmdb.net/album/103946"]

[17]
catalognumber = "TGCS-11166"
date = "2019-05-24"
album = "私に天使が舞い降りた! スペシャルラジオCD"
tracks = [
    [1, "(no title available)", "", "0"],
]
links = ["https://vgmdb.net/album/83287"]
